/********************************************************************
* TReactionDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TReactionDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTReactionDict();
extern void G__cpp_setup_inheritanceTReactionDict();
extern void G__cpp_setup_typetableTReactionDict();
extern void G__cpp_setup_memvarTReactionDict();
extern void G__cpp_setup_globalTReactionDict();
extern void G__cpp_setup_memfuncTReactionDict();
extern void G__cpp_setup_funcTReactionDict();
extern void G__set_cpp_environmentTReactionDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/bender/Programs/GRSISort/include/TReaction.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TReactionDictLN_TClass;
extern G__linked_taginfo G__TReactionDictLN_TBuffer;
extern G__linked_taginfo G__TReactionDictLN_TMemberInspector;
extern G__linked_taginfo G__TReactionDictLN_TObject;
extern G__linked_taginfo G__TReactionDictLN_TNamed;
extern G__linked_taginfo G__TReactionDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TReactionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TReactionDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TReactionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TReactionDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TReactionDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TReactionDictLN_TGraph;
extern G__linked_taginfo G__TReactionDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TReactionDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TReactionDictLN_TNucleus;
extern G__linked_taginfo G__TReactionDictLN_TReaction;

/* STUB derived class for protected member access */
