/********************************************************************
* TGRSILoopDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSILoopDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSILoopDict();
extern void G__cpp_setup_inheritanceTGRSILoopDict();
extern void G__cpp_setup_typetableTGRSILoopDict();
extern void G__cpp_setup_memvarTGRSILoopDict();
extern void G__cpp_setup_globalTGRSILoopDict();
extern void G__cpp_setup_memfuncTGRSILoopDict();
extern void G__cpp_setup_funcTGRSILoopDict();
extern void G__set_cpp_environmentTGRSILoopDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSILoop.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSILoopDictLN_TClass;
extern G__linked_taginfo G__TGRSILoopDictLN_TBuffer;
extern G__linked_taginfo G__TGRSILoopDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSILoopDictLN_TObject;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSILoopDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSILoopDictLN_TMidasEvent;
extern G__linked_taginfo G__TGRSILoopDictLN_TMidasFile;
extern G__linked_taginfo G__TGRSILoopDictLN_TXMLOdb;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSILoopDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSILoopDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSILoopDictLN_TGRSILoop;

/* STUB derived class for protected member access */
