/********************************************************************
* TGintDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGintDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGintDict();
extern void G__cpp_setup_inheritanceTGintDict();
extern void G__cpp_setup_typetableTGintDict();
extern void G__cpp_setup_memvarTGintDict();
extern void G__cpp_setup_globalTGintDict();
extern void G__cpp_setup_memfuncTGintDict();
extern void G__cpp_setup_funcTGintDict();
extern void G__set_cpp_environmentTGintDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/peter/Programs/GRSISort/include/TGint.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGintDictLN_TClass;
extern G__linked_taginfo G__TGintDictLN_TBuffer;
extern G__linked_taginfo G__TGintDictLN_TMemberInspector;
extern G__linked_taginfo G__TGintDictLN_TObject;
extern G__linked_taginfo G__TGintDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TGintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGintDictLN_TQObject;
extern G__linked_taginfo G__TGintDictLN_TApplication;
extern G__linked_taginfo G__TGintDictLN_TRint;
extern G__linked_taginfo G__TGintDictLN_TGint;

/* STUB derived class for protected member access */
