/********************************************************************
* TSharcDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSharcDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSharcDict();
extern void G__cpp_setup_inheritanceTSharcDict();
extern void G__cpp_setup_typetableTSharcDict();
extern void G__cpp_setup_memvarTSharcDict();
extern void G__cpp_setup_globalTSharcDict();
extern void G__cpp_setup_memfuncTSharcDict();
extern void G__cpp_setup_funcTSharcDict();
extern void G__set_cpp_environmentTSharcDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TSharc.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSharcDictLN_TClass;
extern G__linked_taginfo G__TSharcDictLN_TBuffer;
extern G__linked_taginfo G__TSharcDictLN_TMemberInspector;
extern G__linked_taginfo G__TSharcDictLN_TObject;
extern G__linked_taginfo G__TSharcDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TSharcDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSharcDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcDictLN_MNEMONIC;
extern G__linked_taginfo G__TSharcDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSharcDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSharcDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSharcDictLN_TVector3;
extern G__linked_taginfo G__TSharcDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TSharcDictLN_TFragment;
extern G__linked_taginfo G__TSharcDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TSharcDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_TChannel;
extern G__linked_taginfo G__TSharcDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_TGRSIDetector;
extern G__linked_taginfo G__TSharcDictLN_TSharcData;
extern G__linked_taginfo G__TSharcDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcDictLN_TSharcHit;
extern G__linked_taginfo G__TSharcDictLN_TSharc;
extern G__linked_taginfo G__TSharcDictLN_vectorlETSharcHitcOallocatorlETSharcHitgRsPgR;
extern G__linked_taginfo G__TSharcDictLN_reverse_iteratorlEvectorlETSharcHitcOallocatorlETSharcHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
