/********************************************************************
* TSharcHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSharcHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSharcHitDict();
extern void G__cpp_setup_inheritanceTSharcHitDict();
extern void G__cpp_setup_typetableTSharcHitDict();
extern void G__cpp_setup_memvarTSharcHitDict();
extern void G__cpp_setup_globalTSharcHitDict();
extern void G__cpp_setup_memfuncTSharcHitDict();
extern void G__cpp_setup_funcTSharcHitDict();
extern void G__set_cpp_environmentTSharcHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TSharcHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSharcHitDictLN_TClass;
extern G__linked_taginfo G__TSharcHitDictLN_TBuffer;
extern G__linked_taginfo G__TSharcHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TSharcHitDictLN_TObject;
extern G__linked_taginfo G__TSharcHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSharcHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSharcHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSharcHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSharcHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSharcHitDictLN_TVector3;
extern G__linked_taginfo G__TSharcHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TSharcHitDictLN_TSharcHit;

/* STUB derived class for protected member access */
