VALIDATE_ALL_CODEBASE: true
ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - CPP_CLANG_FORMAT
  - MARKDOWN_MARKDOWNLINT
  - ACTION_ACTIONLINT
  - REPOSITORT_GITLEAKS
CPP_CLANG_FORMAT_FILE_EXTENSIONS:
  - ".h"
  - ".hh"
  - ".cxx"
  - ".C"
#CPP_CLANG_FORMAT_POST_COMMANDS:
EXCLUDED_DIRECTORIES:
  - Sandbox
  - myAnalysis
# do not ignore files in .gitignore
IGNORE_GITIGNORED_FILES: false
