GRSISort: AngularCorrelations.cxx File Reference
AngularCorrelations.cxx File Reference
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include <cassert>
#include "TFile.h"
#include "TH2.h"
#include "TH1.h"
#include "TGraphErrors.h"
#include "TMultiGraph.h"
#include "TCanvas.h"
#include "TLine.h"
#include "TLegend.h"
#include "Fit/Fitter.h"
#include "TMatrixD.h"
#include "TPaveText.h"
#include "ArgParser.h"
#include "TUserSettings.h"
#include "TGriffinAngles.h"
#include "TPeakFitter.h"
#include "TRWPeak.h"
Classes
class Ac
Functions
std::vector< double > A2a4Method (TGraphErrors *data, TGraphErrors *z0, TGraphErrors *z2, TGraphErrors *z4)
double GetYError (TGraphErrors *graph, const double &x)
int main (int argc, char **argv)
TGraph * MixingMethod (TGraphErrors *data, TGraphErrors *z0, TGraphErrors *z2, TGraphErrors *z4, int twoJhigh, int twoJmid, int twoJlow, std::vector< double > &bestParameters)
Function Documentation
A2a4Method()
std::vector< double > A2a4Method (TGraphErrors * data, TGraphErrors * z0, TGraphErrors * z2, TGraphErrors * z4)
Definition at line 824 of file AngularCorrelations.cxx.
References TGRSIFunctions::LegendrePolynomial(), and Ac::Np().
Referenced by main().
GetYError()
double GetYError (TGraphErrors * graph, const double & x)
general function to get the error of a graph at point x (takes the maximum of the errors of the bracketing points)
Definition at line 28 of file AngularCorrelations.cxx.
Referenced by main(), and Ac::operator()().
main()
int main (int argc, char ** argv)
program to read in 2D matrices from AngularCorrelationHelper project and fit peaks to create angular correlation plots and to create chi-square plots
Definition at line 54 of file AngularCorrelations.cxx.
References A2a4Method(), TPeakFitter::AddPeak(), TSinglePeak::Area(), TSinglePeak::AreaErr(), bgHigh, bgLow, TPeakFitter::Fit(), TPeakFitter::GetBackground(), TSinglePeak::GetFitFunction(), TSinglePeak::GetReducedChi2(), GetYError(), MixingMethod(), ArgParser::option(), and ArgParser::parse().
Referenced by GRootCanvas::ShowEditor().
MixingMethod()
TGraph * MixingMethod (TGraphErrors * data, TGraphErrors * z0, TGraphErrors * z2, TGraphErrors * z4, int twoJhigh, int twoJmid, int twoJlow, std::vector< double > & bestParameters)
Definition at line 702 of file AngularCorrelations.cxx.
References TGRSIFunctions::CalculateA2(), TGRSIFunctions::CalculateA4(), and Ac::Np().
Referenced by main().