GRSISort: CrossTalk.C File Reference
CrossTalk.C File Reference
#include "CrossTalk.h"
#include "TH1.h"
Macros
#define CrossTalk_cxx
Functions
bool Addback (TGriffinHit &one, TGriffinHit &two)
bool PromptCoincidence (TGriffinHit *one, TGriffinHit *two)
Variables
const Short_t defaultKValue = 379
const double gb_time_high = 350.
const double gb_time_low = -250.
const double gg_time_high = 300.
const double gg_time_low = -200.
bool pileup_reject = true
Macro Definition Documentation
CrossTalk_cxx
#define CrossTalk_cxx
Definition at line 1 of file CrossTalk.C.
Function Documentation
Addback()
bool Addback (TGriffinHit & one, TGriffinHit & two)
Definition at line 19 of file CrossTalk.C.
References TDetectorHit::GetDetector(), and TDetectorHit::GetTime().
PromptCoincidence()
bool PromptCoincidence (TGriffinHit * one, TGriffinHit * two)
Definition at line 24 of file CrossTalk.C.
References TDetectorHit::GetTime(), gg_time_high, and gg_time_low.
Variable Documentation
defaultKValue
const Short_t defaultKValue = 379
Definition at line 17 of file CrossTalk.C.
gb_time_high
const double gb_time_high = 350.
Definition at line 14 of file CrossTalk.C.
gb_time_low
const double gb_time_low = -250.
Definition at line 13 of file CrossTalk.C.
gg_time_high
const double gg_time_high = 300.
Definition at line 10 of file CrossTalk.C.
Referenced by PromptCoincidence().
gg_time_low
const double gg_time_low = -200.
Definition at line 9 of file CrossTalk.C.
Referenced by PromptCoincidence().
pileup_reject
bool pileup_reject = true
Definition at line 7 of file CrossTalk.C.