GRSISort: Deadtime.cxx File Reference
Deadtime.cxx File Reference
#include <fstream>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <iostream>
#include <functional>
#include <iomanip>
#include <string>
#include <cmath>
#include <cstdio>
#include <ctime>
#include "TF1.h"
#include "TMath.h"
#include "TH1.h"
#include "TH1F.h"
#include "THStack.h"
#include "TString.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TFile.h"
#include "TKey.h"
#include "TTree.h"
#include "TH2F.h"
#include "TROOT.h"
#include "TPPG.h"
#include "TScaler.h"
#include "TApplication.h"
#include "TLeaf.h"
#include "TGriffin.h"
#include "TSceptar.h"
Functions
void CheckFile (const char *&fname)
void DoAnalysis (const char *&fname, int &nfile, double *rate, int &nsclr, int &patlen, int &ncycle, int *trun, double &eor, const char *&hname, const char *&iname, const char *&jname, const char *&kname, const char *&lname, const char *&mname, const char *&nname, int &nscaler)
int main (int argc, char *argv[])
void MakeSpectra (const char *&filename, int &prog, const char *&fname, int &nsclr, int &ncycle, double *rate, int *channel, int &index, int *trun, double &thresh)
void Printaddress (int *channel)
Function Documentation
CheckFile()
void CheckFile (const char *& fname)
Definition at line 281 of file Deadtime.cxx.
References DBLUE, DRED, and RESET_COLOR.
Referenced by main().
DoAnalysis()
void DoAnalysis (const char *& fname, int & nfile, double * rate, int & nsclr, int & patlen, int & ncycle, int * trun, double & eor, const char *& hname, const char *& iname, const char *& jname, const char *& kname, const char *& lname, const char *& mname, const char *& nname, int & nscaler)
Definition at line 295 of file Deadtime.cxx.
References DBLUE, DGREEN, DRED, and RESET_COLOR.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 51 of file Deadtime.cxx.
References CheckFile(), DBLUE, DGREEN, DMAGENTA, DoAnalysis(), MakeSpectra(), Printaddress(), and RESET_COLOR.
MakeSpectra()
void MakeSpectra (const char *& filename, int & prog, const char *& fname, int & nsclr, int & ncycle, double * rate, int * channel, int & index, int * trun, double & thresh)
Definition at line 205 of file Deadtime.cxx.
References TScaler::Clear(), DGREEN, TScalerData::GetAddress(), TScalerData::GetScaler(), TScalerData::GetTimeStamp(), and RESET_COLOR.
Referenced by main().
Printaddress()
void Printaddress (int * channel)
Definition at line 195 of file Deadtime.cxx.
References DBLUE, and RESET_COLOR.
Referenced by main().