GRSISort: FixRunInfo.cxx File Reference
FixRunInfo.cxx File Reference
#include <iostream>
#include <iomanip>
#include <fstream>
#include "TFile.h"
#include "TRunInfo.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 10 of file FixRunInfo.cxx.
References TSingleton< TRunInfo >::Get(), TRunInfo::Print(), TRunInfo::RunNumber(), TRunInfo::SetRunComment(), TRunInfo::SetRunLength(), TRunInfo::SetRunNumber(), TRunInfo::SetRunStart(), TRunInfo::SetRunStop(), TRunInfo::SetRunTitle(), and TRunInfo::SetSubRunNumber().