GRSISort: GRootCommands.cxx File Reference
GRootCommands.cxx File Reference
#include "GRootCommands.h"
#include "Globals.h"
#include <cstdio>
#include <sstream>
#include <fstream>
#include "TRint.h"
#include "TTree.h"
#include "Getline.h"
#include "TAxis.h"
#include "TDirectory.h"
#include "TFile.h"
#include "TPolyMarker.h"
#include "TSpectrum.h"
#include "TText.h"
#include "TExec.h"
#include "TKey.h"
#include "TObject.h"
#include "TObjArray.h"
#include "TH1.h"
#include "TPython.h"
#include "TTimer.h"
#include "TF1.h"
#include "GCanvas.h"
#include "GPeak.h"
#include "TPeak.h"
#include "GGaus.h"
#include "GH2D.h"
#include "GH1D.h"
#include "TGRSIOptions.h"
#include "GNotifier.h"
Namespaces
namespace anonymous_namespace{GRootCommands.cxx}
Functions
void AddFileToGUI (TFile *file)
TH2 * AddOffset (TH2 *mat, double offset, EAxis axis)
TPeak * AltPhotoPeakFit (TH1 *hist, double xlow, double xhigh, Option_t *opt)
void Commands ()
TF1 * DoubleGausFit (TH1 *hist, double, double, double xlow, double xhigh, Option_t *opt)
std::vector< TH1 * > FindHists (int dim)
GGaus * GausFit (TH1 *hist, double xlow, double xhigh, Option_t *opt)
bool GetProjection (GH2D *hist, double low, double high, double bg_low, double bg_high)
TF1 * GrabFit (int i)
TH1 * GrabHist (int i)
bool GUIIsRunning ()
void Help ()
int LabelPeaks (TH1 *hist, double sigma, double thresh, Option_t *)
std::string MergeStrings (const std::vector< std::string > &strings, char split)
bool Move1DHistogram (const Int_t &key, TH1 *histogram)
bool Move2DHistogram (const Int_t &key, TH2 *histogram)
EAxis operator& (EAxis lhs, EAxis rhs)
GPeak * PhotoPeakFit (TH1 *hist, double xlow, double centroid, double xhigh, Option_t *opt)
GPeak * PhotoPeakFit (TH1 *hist, double xlow, double xhigh, Option_t *opt)
void Prompt ()
bool RemovePeaks (TH1 **hists, unsigned int nhists)
bool ShowPeaks (TH1 **hists, unsigned int nhists, double sigma, double thresh)
void StartGUI ()
void Version ()
Variables
bool anonymous_namespace{GRootCommands.cxx}::gui_is_running = false
Function Documentation
AddFileToGUI()
void AddFileToGUI (TFile * file)
Definition at line 646 of file GRootCommands.cxx.
References GUIIsRunning().
Referenced by TGRSIint::OpenRootFile().
AddOffset()
TH2 * AddOffset (TH2 * mat, double offset, EAxis axis)
Definition at line 660 of file GRootCommands.cxx.
References kXAxis, kYAxis, and mat.
AltPhotoPeakFit()
TPeak * AltPhotoPeakFit (TH1 * hist, double xlow, double xhigh, Option_t * opt)
Definition at line 526 of file GRootCommands.cxx.
References hist.
Referenced by GCanvas::Process1DKeyboardPress().
Commands()
void Commands ()
Definition at line 42 of file GRootCommands.cxx.
DoubleGausFit()
TF1 * DoubleGausFit (TH1 * hist, double , double , double xlow, double xhigh, Option_t * opt)
Definition at line 475 of file GRootCommands.cxx.
References hist.
FindHists()
std::vector< TH1 * > FindHists (int dim)
Definition at line 218 of file GRootCommands.cxx.
References hist.
Referenced by Move1DHistogram(), and Move2DHistogram().
GausFit()
GGaus * GausFit (TH1 * hist, double xlow, double xhigh, Option_t * opt)
Definition at line 451 of file GRootCommands.cxx.
References hist.
Referenced by GCanvas::Process1DKeyboardPress().
GetProjection()
bool GetProjection (GH2D * hist, double low, double high, double bg_low, double bg_high)
Definition at line 60 of file GRootCommands.cxx.
References GH1D::Draw(), hist, kRegionBackground, GH1D::Project(), and GH1D::Project_Background().
GrabFit()
TF1 * GrabFit (int i)
Definition at line 584 of file GRootCommands.cxx.
References hist.
GrabHist()
TH1 * GrabHist (int i)
Definition at line 563 of file GRootCommands.cxx.
References hist.
GUIIsRunning()
bool GUIIsRunning ()
Definition at line 640 of file GRootCommands.cxx.
References anonymous_namespace{GRootCommands.cxx}::gui_is_running.
Referenced by AddFileToGUI().
Help()
void Help ()
Definition at line 37 of file GRootCommands.cxx.
LabelPeaks()
int LabelPeaks (TH1 * hist, double sigma, double thresh, Option_t * opt)
Definition at line 150 of file GRootCommands.cxx.
References hist.
Referenced by ShowPeaks().
MergeStrings()
std::string MergeStrings (const std::vector< std::string > & strings, char split)
Definition at line 548 of file GRootCommands.cxx.
Move1DHistogram()
bool Move1DHistogram (const Int_t & key, TH1 * histogram)
Moves displayed 1D histograms by 50% of the visible range left, right. For "normal" TH1 histograms up/down scales the y-axis up/down by a factor of 2. For GH1D histograms up/down selects the next (up) or previous (down) GH1D histogram.
Definition at line 232 of file GRootCommands.cxx.
References FindHists(), GH1D::GetNext(), GH1D::GetPrevious(), hex(), hist, kGRSIArrowDown, kGRSIArrowLeft, kGRSIArrowRight, and kGRSIArrowUp.
Referenced by GH1D::HandleEvent(), and GCanvas::Process1DArrowKeyPress().
Move2DHistogram()
bool Move2DHistogram (const Int_t & key, TH2 * histogram)
Moves displayed 2D histograms by 50% of the visible range left, right, up, or down
Definition at line 341 of file GRootCommands.cxx.
References FindHists(), hex(), hist, kGRSIArrowDown, kGRSIArrowLeft, kGRSIArrowRight, and kGRSIArrowUp.
Referenced by GCanvas::Process2DArrowKeyPress().
operator&()
EAxis operator& (EAxis lhs, EAxis rhs)
Definition at line 690 of file GRootCommands.cxx.
PhotoPeakFit() [1/2]
GPeak * PhotoPeakFit (TH1 * hist, double xlow, double centroid, double xhigh, Option_t * opt)
Definition at line 503 of file GRootCommands.cxx.
References hist.
PhotoPeakFit() [2/2]
GPeak * PhotoPeakFit (TH1 * hist, double xlow, double xhigh, Option_t * opt)
Definition at line 498 of file GRootCommands.cxx.
References hist, and PhotoPeakFit().
Referenced by TCalibrator::AddData(), PhotoPeakFit(), and GCanvas::Process1DKeyboardPress().
Prompt()
void Prompt ()
Definition at line 47 of file GRootCommands.cxx.
Referenced by GCanvas::CycleBackgroundSubtraction().
RemovePeaks()
bool RemovePeaks (TH1 ** hists, unsigned int nhists)
Definition at line 205 of file GRootCommands.cxx.
Referenced by GCanvas::Process1DKeyboardPress(), and GCanvas::Process2DKeyboardPress().
ShowPeaks()
bool ShowPeaks (TH1 ** hists, unsigned int nhists, double sigma, double thresh)
Definition at line 192 of file GRootCommands.cxx.
References LabelPeaks().
Referenced by GCanvas::Process1DKeyboardPress().
StartGUI()
void StartGUI ()
Definition at line 617 of file GRootCommands.cxx.
References anonymous_namespace{GRootCommands.cxx}::gui_is_running.
Referenced by TGRSIint::ApplyOptions().
Version()
void Version ()
Definition at line 52 of file GRootCommands.cxx.
Referenced by TGRSIOptions::Load().