GRSISort: GainMatchGRIFFIN.cxx File Reference
GainMatchGRIFFIN.cxx File Reference
#include <algorithm>
#include <vector>
#include <string>
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <THStack.h>
#include <TSpectrum.h>
#include <TGraph.h>
#include <TGraphErrors.h>
#include <TMultiGraph.h>
#include <TF1.h>
#include <TCanvas.h>
#include <TList.h>
#include <TMinuit.h>
#include <TFragment.h>
#include <TGriffin.h>
#include <TGriffinHit.h>
#include <TChannel.h>
#include <TPeak.h>
#include <TBranch.h>
#include <TGaxis.h>
#include <TStyle.h>
#include <TLegend.h>
#include <TSystem.h>
Enumerations
enum class EType { kMaxBin , kTPeak , kTSpectrum }
Functions
void check_calibration (const char *testFileName, int minchannel, int maxchannel, const std::vector< double > &peaks, EType type, double width, bool UseMyList, const char *fwhmImgName, const char *fwratioImgName)
void check_calibration (const char *testFileName, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, EType type, double width, const char *fwhmImgName, const char *fwratioImgName)
void check_calibration (const char *testFileName, int minchannel, int maxchannel, EType type, double width, const char *fwhmImgName, const char *fwratioImgName)
void check_calibration (const char *testFileName, int minchannel, int maxchannel, std::vector< int > channelstoskip, std::vector< double > peaks, EType type, double width, bool UseMyList, const char *fwhmImgName, const char *fwratioImgName)
void create_gainmatch_graphs (const char *histFileName, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, double largepeak, std::vector< double > peaks, EType type, double mindistance, bool roughenergy, bool twopeaks, double largepeak2)
void create_gainmatch_graphs (const char *histFileName, int minchannel, int maxchannel, double largepeak, const std::vector< double > &peaks, EType type=EType::kTSpectrum, double mindistance=20e3, bool roughenergy=kTRUE, bool twopeaks=kFALSE, double largepeak2=0.0)
void create_gainmatch_graphs (const char *histFileName, int minchannel, int maxchannel, double largepeak, std::vector< double > peaks, EType type, double mindistance, bool roughenergy, bool twopeaks, double largepeak2)
void create_GRIFFIN_cal (const char *ROOTFileName, const char *outFileName, int minchannel, int maxchannel, const char *paramImgName, const char *graphImgName, int order)
void create_GRIFFIN_cal (const char *ROOTFileName, const char *outFileName, int minchannel, int maxchannel, std::vector< int > channelstoskip, const char *paramImgName, const char *graphImgName, int order)
double FWHM (TH1 *h, double xmin, double xmax)
double FWTM (TH1 *h, double xmin, double xmax)
double FWXM (TH1 *h, double xmin, double xmax, double percent)
TGraph * gainmatch_peaks (TH1 *hst, std::vector< double > peakvalues, std::vector< double > peaklocations, double windowsize, EType type)
double GetCentroid (EType type, TH1 *hst, double xmin, double xmax)
double GetCentroidMaxBin (TH1 *hst, double xmin, double xmax)
double GetCentroidTPeak (TH1 *hst, double xmin, double xmax)
double GetCentroidTSpectrum (TH1 *hst, double xmin, double xmax)
double GetRoughGain (TH1 *h, double largepeak, double mindistance, bool twopeaks, double largepeak2)
int main (int argc, char **argv)
void make_calibration_histograms (const char *fragFileName, const char *histFileName, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, int bins, int xmin, int xmax)
void make_calibration_histograms (const char *fragFileName, const char *histFileName, int minchannel, int maxchannel, int bins, int xmin, int xmax)
TList * MakeGRIFFINChargeHsts (TTree *tree, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, int bins, double xmin, double xmax)
TList * MakeGRIFFINChargeHsts (TTree *tree, int minchannel, int maxchannel, int bins, double xmin, double xmax)
TList * MakeGRIFFINEnergyHsts (TTree *tree, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, int bins, double xmin, double xmax, const char *calfile)
TList * MakeGRIFFINEnergyHsts (TTree *tree, int minchannel, int maxchannel, int bins, double xmin, double xmax, const char *calfile)
void recalibrate_spectra (const char *fragFile, const char *newFile, const char *calFile, int minchannel, int maxchannel, const std::vector< int > &channelstoskip, int xbins, double xmin, double xmax)
void recalibrate_spectra (const char *fragFile, const char *newFile, const char *calFile, int minchannel, int maxchannel, int xbins, double xmin, double xmax)
Enumeration Type Documentation
EType
enum class EType strong
Enumerator
kMaxBin
kTPeak
kTSpectrum
Definition at line 28 of file GainMatchGRIFFIN.cxx.
Function Documentation
check_calibration() [1/4]
void check_calibration (const char * testFileName, int minchannel, int maxchannel, const std::vector< double > & peaks, EType type = EType::kTSpectrum, double width = 10, bool UseMyList = kFALSE, const char * fwhmImgName = "GRIFFIN_FWHM_diagnostic.png", const char * fwratioImgName = "GRIFFIN_FWratio_diagnostic.png")
Definition at line 722 of file GainMatchGRIFFIN.cxx.
References check_calibration().
check_calibration() [2/4]
void check_calibration (const char * testFileName, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, EType type = EType::kTSpectrum, double width = 10, const char * fwhmImgName = "GRIFFIN_FWHM_diagnostic.png", const char * fwratioImgName = "GRIFFIN_FWratio_diagnostic.png")
Definition at line 716 of file GainMatchGRIFFIN.cxx.
References check_calibration().
check_calibration() [3/4]
void check_calibration (const char * testFileName, int minchannel, int maxchannel, EType type = EType::kTSpectrum, double width = 10, const char * fwhmImgName = "GRIFFIN_FWHM_diagnostic.png", const char * fwratioImgName = "GRIFFIN_FWratio_diagnostic.png")
Definition at line 709 of file GainMatchGRIFFIN.cxx.
References check_calibration().
check_calibration() [4/4]
void check_calibration (const char * testFileName, int minchannel, int maxchannel, std::vector< int > channelstoskip, std::vector< double > peaks, EType type = EType::kTSpectrum, double width = 10, bool UseMyList = kFALSE, const char * fwhmImgName = "GRIFFIN_FWHM_diagnostic.png", const char * fwratioImgName = "GRIFFIN_FWratio_diagnostic.png")
Definition at line 578 of file GainMatchGRIFFIN.cxx.
References FWHM(), FWTM(), and GetCentroid().
Referenced by check_calibration(), check_calibration(), check_calibration(), and main().
create_gainmatch_graphs() [1/3]
void create_gainmatch_graphs (const char * histFileName, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, double largepeak, std::vector< double > peaks, EType type = EType::kTSpectrum, double mindistance = 20e3, bool roughenergy = kTRUE, bool twopeaks = kFALSE, double largepeak2 = 0.0)
Definition at line 232 of file GainMatchGRIFFIN.cxx.
References gainmatch_peaks(), and GetRoughGain().
create_gainmatch_graphs() [2/3]
void create_gainmatch_graphs (const char * histFileName, int minchannel, int maxchannel, double largepeak, const std::vector< double > & peaks, EType type = EType::kTSpectrum, double mindistance = 20e3, bool roughenergy = kTRUE, bool twopeaks = kFALSE, double largepeak2 = 0.0)
Definition at line 317 of file GainMatchGRIFFIN.cxx.
References create_gainmatch_graphs().
create_gainmatch_graphs() [3/3]
void create_gainmatch_graphs (const char * histFileName, int minchannel, int maxchannel, double largepeak, std::vector< double > peaks, EType type, double mindistance, bool roughenergy, bool twopeaks, double largepeak2)
Referenced by create_gainmatch_graphs(), and main().
create_GRIFFIN_cal() [1/2]
void create_GRIFFIN_cal (const char * ROOTFileName, const char * outFileName, int minchannel, int maxchannel, const char * paramImgName = "GRIFFIN_fitting_params.png", const char * graphImgName = "GRIFFIN_calgraph.png", int order = 1)
Definition at line 492 of file GainMatchGRIFFIN.cxx.
References create_GRIFFIN_cal().
Referenced by create_GRIFFIN_cal(), and main().
create_GRIFFIN_cal() [2/2]
void create_GRIFFIN_cal (const char * ROOTFileName, const char * outFileName, int minchannel, int maxchannel, std::vector< int > channelstoskip, const char * paramImgName = "GRIFFIN_fitting_params.png", const char * graphImgName = "GRIFFIN_calgraph.png", int order = 1)
Definition at line 347 of file GainMatchGRIFFIN.cxx.
FWHM()
double FWHM (TH1 * h, double xmin, double xmax)
Definition at line 784 of file GainMatchGRIFFIN.cxx.
References FWXM().
Referenced by check_calibration(), and GetCentroidTPeak().
FWTM()
double FWTM (TH1 * h, double xmin, double xmax)
Definition at line 789 of file GainMatchGRIFFIN.cxx.
References FWXM().
Referenced by check_calibration().
FWXM()
double FWXM (TH1 * h, double xmin, double xmax, double percent = 0.5)
Definition at line 729 of file GainMatchGRIFFIN.cxx.
Referenced by FWHM(), and FWTM().
gainmatch_peaks()
TGraph * gainmatch_peaks (TH1 * hst, std::vector< double > peakvalues, std::vector< double > peaklocations, double windowsize, EType type = EType::kTSpectrum)
Definition at line 323 of file GainMatchGRIFFIN.cxx.
References GetCentroid().
Referenced by create_gainmatch_graphs().
GetCentroid()
double GetCentroid (EType type, TH1 * hst, double xmin, double xmax)
Definition at line 100 of file GainMatchGRIFFIN.cxx.
References GetCentroidMaxBin(), GetCentroidTPeak(), GetCentroidTSpectrum(), kMaxBin, kTPeak, and kTSpectrum.
Referenced by check_calibration(), and gainmatch_peaks().
GetCentroidMaxBin()
double GetCentroidMaxBin (TH1 * hst, double xmin, double xmax)
Definition at line 60 of file GainMatchGRIFFIN.cxx.
Referenced by GetCentroid(), and GetCentroidTPeak().
GetCentroidTPeak()
double GetCentroidTPeak (TH1 * hst, double xmin, double xmax)
Definition at line 79 of file GainMatchGRIFFIN.cxx.
References TPeak::Fit(), FWHM(), TPeak::GetCentroid(), and GetCentroidMaxBin().
Referenced by GetCentroid().
GetCentroidTSpectrum()
double GetCentroidTSpectrum (TH1 * hst, double xmin, double xmax)
Definition at line 69 of file GainMatchGRIFFIN.cxx.
Referenced by GetCentroid().
GetRoughGain()
double GetRoughGain (TH1 * h, double largepeak, double mindistance, bool twopeaks = kFALSE, double largepeak2 = 0.0)
Definition at line 113 of file GainMatchGRIFFIN.cxx.
Referenced by create_gainmatch_graphs().
main()
int main (int argc, char ** argv)
Definition at line 796 of file GainMatchGRIFFIN.cxx.
References check_calibration(), create_gainmatch_graphs(), create_GRIFFIN_cal(), kTPeak, make_calibration_histograms(), and recalibrate_spectra().
make_calibration_histograms() [1/2]
void make_calibration_histograms (const char * fragFileName, const char * histFileName, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, int bins = 40e3, int xmin = 0, int xmax = 4000)
Definition at line 151 of file GainMatchGRIFFIN.cxx.
References MakeGRIFFINChargeHsts(), and TChannel::ReadCalFromTree().
Referenced by main(), and make_calibration_histograms().
make_calibration_histograms() [2/2]
void make_calibration_histograms (const char * fragFileName, const char * histFileName, int minchannel, int maxchannel, int bins = 40e3, int xmin = 0, int xmax = 4000)
Definition at line 172 of file GainMatchGRIFFIN.cxx.
References make_calibration_histograms().
MakeGRIFFINChargeHsts() [1/2]
TList * MakeGRIFFINChargeHsts (TTree * tree, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, int bins, double xmin, double xmax)
Definition at line 178 of file GainMatchGRIFFIN.cxx.
References TChannel::GetAddress(), TChannel::GetChannelByNumber(), TDetectorHit::GetChannelNumber(), TDetectorHit::GetCharge(), TFragment::GetDetectorType(), TDetectorHit::GetKValue(), and TChannel::ReadCalFromTree().
MakeGRIFFINChargeHsts() [2/2]
TList * MakeGRIFFINChargeHsts (TTree * tree, int minchannel, int maxchannel, int bins, double xmin, double xmax)
Definition at line 226 of file GainMatchGRIFFIN.cxx.
References MakeGRIFFINChargeHsts().
Referenced by make_calibration_histograms(), and MakeGRIFFINChargeHsts().
MakeGRIFFINEnergyHsts() [1/2]
TList * MakeGRIFFINEnergyHsts (TTree * tree, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, int bins, double xmin, double xmax, const char * calfile)
Definition at line 525 of file GainMatchGRIFFIN.cxx.
References TChannel::GetAddress(), TChannel::GetChannelByNumber(), TDetectorHit::GetChannelNumber(), TFragment::GetDetectorType(), TDetectorHit::GetEnergy(), and TChannel::ReadCalFile().
MakeGRIFFINEnergyHsts() [2/2]
TList * MakeGRIFFINEnergyHsts (TTree * tree, int minchannel, int maxchannel, int bins, double xmin, double xmax, const char * calfile)
Definition at line 571 of file GainMatchGRIFFIN.cxx.
References MakeGRIFFINEnergyHsts().
Referenced by MakeGRIFFINEnergyHsts(), and recalibrate_spectra().
recalibrate_spectra() [1/2]
void recalibrate_spectra (const char * fragFile, const char * newFile, const char * calFile, int minchannel, int maxchannel, const std::vector< int > & channelstoskip, int xbins = 40e3, double xmin = 0, double xmax = 4000)
Definition at line 498 of file GainMatchGRIFFIN.cxx.
References MakeGRIFFINEnergyHsts(), and TChannel::ReadCalFile().
Referenced by main(), and recalibrate_spectra().
recalibrate_spectra() [2/2]
void recalibrate_spectra (const char * fragFile, const char * newFile, const char * calFile, int minchannel, int maxchannel, int xbins = 40e3, double xmin = 0, double xmax = 4000)
Definition at line 519 of file GainMatchGRIFFIN.cxx.
References recalibrate_spectra().