GRSISort: GateBG.C File Reference
GateBG.C File Reference
Functions
TH1 * NewProjectionXBGP (TH2 *matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low=-1, Double_t bg_high=-1)
TH1 * ProjectionXBGP (TH2 *matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low=-1, Double_t bg_high=-1)
TH1 * ProjectionYBGP (TH2 *matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low=-1, Double_t bg_high=-1)
Function Documentation
NewProjectionXBGP()
TH1 * NewProjectionXBGP (TH2 * matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low = -1, Double_t bg_high = -1)
Definition at line 1 of file GateBG.C.
ProjectionXBGP()
TH1 * ProjectionXBGP (TH2 * matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low = -1, Double_t bg_high = -1)
Definition at line 44 of file GateBG.C.
References GPeak::Background(), and GPeak::GetLastFit().
ProjectionYBGP()
TH1 * ProjectionYBGP (TH2 * matrix, Double_t gate_low, Double_t gate_high, Double_t bg_low = -1, Double_t bg_high = -1)
Definition at line 91 of file GateBG.C.
References GPeak::Background(), and GPeak::GetLastFit().