GRSISort: Globals.h File Reference
Globals.h File Reference
#include <cstdint>
#include <iostream>
#include <iomanip>
#include <stdexcept>
#include <string>
#include <cstdio>
#include <cstdlib>
#include <execinfo.h>
#include <cxxabi.h>
#include <sstream>
#include <array>
#include <memory>
#include <unistd.h>
#include "TEnv.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <sys/prctl.h>
Classes
struct grsi::exit_exception
Namespaces
namespace grsi
Macros
#define ALERTTEXT "\033[47m\033[0;31m"
#define BG_BLUE "\033[44m"
#define BG_CYAN "\033[46m"
#define BG_GREEN "\033[42m"
#define BG_MAGENTA "\033[45m"
#define BG_RED "\033[41m"
#define BG_WHITE "\033[47m"
#define BG_YELLOW "\033[43m"
#define BLACK "\033[1;30m"
#define BLUE "\033[1;34m"
#define BUILDINGTIMECONDITION 2
#define BUILDINGTRIGGERCONDITION 999
#define CYAN "\033[1;36m"
#define DBLACK "\033[0;30m"
#define DBLUE "\033[0;34m"
#define DCYAN "\033[0;36m"
#define DGREEN "\033[0;32m"
#define DMAGENTA "\033[0;35m"
#define DRED "\033[0;31m"
#define DWHITE "\033[0;37m"
#define DYELLOW "\033[0;33m"
#define FRAGMENTBUFFERSIZE 1000
#define GREEN "\033[1;32m"
#define HIDE_CURSOR "\033[?25l"
#define MAGENTA "\033[1;35m"
#define MAXSAMPLESIZE 8192
#define NUM_SIS_CHAN 8
#define RED "\033[1;31m"
#define RESET_COLOR "\033[m"
#define SHOW_CURSOR "\033[?25h"
#define WHITE "\033[1;37m"
#define YELLOW "\033[1;33m"
Functions
template<typename T , typename... U>
void grsi::Append (std::stringstream &stream, const T &head, const U &... tail)
template<typename T >
void grsi::Append (std::stringstream &stream, const T &tail)
static std::string getexepath ()
template<typename T >
std::string hex (T val, int width=-1)
static void PrintGdbStacktrace ()
static void PrintStacktrace (std::ostream &out=std::cout, unsigned int maxFrames=63)
const std::string & ProgramName ()
void grsi::SetGRSIEnv ()
static std::string sh (std::string cmd)
template<typename T , typename... U>
std::string grsi::Stringify (const T &head, const U &... tail)
Macro Definition Documentation
ALERTTEXT
#define ALERTTEXT "\033[47m\033[0;31m"
Definition at line 34 of file Globals.h.
BG_BLUE
#define BG_BLUE "\033[44m"
Definition at line 27 of file Globals.h.
BG_CYAN
#define BG_CYAN "\033[46m"
Definition at line 29 of file Globals.h.
BG_GREEN
#define BG_GREEN "\033[42m"
Definition at line 25 of file Globals.h.
BG_MAGENTA
#define BG_MAGENTA "\033[45m"
Definition at line 28 of file Globals.h.
BG_RED
#define BG_RED "\033[41m"
Definition at line 24 of file Globals.h.
BG_WHITE
#define BG_WHITE "\033[47m"
Definition at line 23 of file Globals.h.
BG_YELLOW
#define BG_YELLOW "\033[43m"
Definition at line 26 of file Globals.h.
BLACK
#define BLACK "\033[1;30m"
Definition at line 9 of file Globals.h.
BLUE
#define BLUE "\033[1;34m"
Definition at line 5 of file Globals.h.
BUILDINGTIMECONDITION
#define BUILDINGTIMECONDITION 2
Definition at line 42 of file Globals.h.
BUILDINGTRIGGERCONDITION
#define BUILDINGTRIGGERCONDITION 999
Definition at line 43 of file Globals.h.
CYAN
#define CYAN "\033[1;36m"
Definition at line 11 of file Globals.h.
DBLACK
#define DBLACK "\033[0;30m"
Definition at line 18 of file Globals.h.
DBLUE
#define DBLUE "\033[0;34m"
Definition at line 14 of file Globals.h.
DCYAN
#define DCYAN "\033[0;36m"
Definition at line 20 of file Globals.h.
DGREEN
#define DGREEN "\033[0;32m"
Definition at line 16 of file Globals.h.
DMAGENTA
#define DMAGENTA "\033[0;35m"
Definition at line 19 of file Globals.h.
DRED
#define DRED "\033[0;31m"
Definition at line 17 of file Globals.h.
DWHITE
#define DWHITE "\033[0;37m"
Definition at line 21 of file Globals.h.
DYELLOW
#define DYELLOW "\033[0;33m"
Definition at line 15 of file Globals.h.
FRAGMENTBUFFERSIZE
#define FRAGMENTBUFFERSIZE 1000
Definition at line 40 of file Globals.h.
GREEN
#define GREEN "\033[1;32m"
Definition at line 7 of file Globals.h.
HIDE_CURSOR
#define HIDE_CURSOR "\033[?25l"
Definition at line 31 of file Globals.h.
MAGENTA
#define MAGENTA "\033[1;35m"
Definition at line 10 of file Globals.h.
MAXSAMPLESIZE
#define MAXSAMPLESIZE 8192
Definition at line 38 of file Globals.h.
NUM_SIS_CHAN
#define NUM_SIS_CHAN 8
Definition at line 36 of file Globals.h.
RED
#define RED "\033[1;31m"
Definition at line 8 of file Globals.h.
RESET_COLOR
#define RESET_COLOR "\033[m"
Definition at line 4 of file Globals.h.
SHOW_CURSOR
#define SHOW_CURSOR "\033[?25h"
Definition at line 32 of file Globals.h.
WHITE
#define WHITE "\033[1;37m"
Definition at line 12 of file Globals.h.
YELLOW
#define YELLOW "\033[1;33m"
Definition at line 6 of file Globals.h.
Function Documentation
getexepath()
static std::string getexepath () inline static
Definition at line 148 of file Globals.h.
hex()
template<typename T > std::string hex (T val, int width = -1) inline
Definition at line 134 of file Globals.h.
Referenced by TFragmentMap::Add(), TPPG::CalculateCycleFromData(), TPPG::Correct(), TChannel::GetChannel(), TScaler::GetLastScaler(), TGRSIDataParser::GriffinDataToFragment(), TScaler::ListHistograms(), TPPG::OdbMatchesData(), TLstFile::ParseHeaders(), StoppableThread::Print(), TMidasEvent::Print(), TRlmdEvent::Print(), TLstEvent::Print(), TBadFragment::Print(), TPPGData::Print(), TPPG::Print(), TScalerData::Print(), TSortingDiagnostics::Print(), TParsingDiagnosticsData::Print(), TChannel::PrintCTCoeffs(), TChannel::PrintToString(), TChannel::SetAddress(), TPPGData::SetNewPPG(), TPPGData::SetOldPPG(), TGRSIDataParser::SetTIGTimeStamp(), TGRSIDataParser::TigressDataToFragment(), TSourceCalibration::UpdateChannel(), TILLDataParser::V1SingleFippsEventToFragment(), and TParsingDiagnostics::WriteToFile().
PrintGdbStacktrace()
static void PrintGdbStacktrace () inline static
Definition at line 259 of file Globals.h.
PrintStacktrace()
static void PrintStacktrace (std::ostream & out = std::cout, unsigned int maxFrames = 63) inline static
Definition at line 168 of file Globals.h.
ProgramName()
const std::string & ProgramName ()
Referenced by TGRSIint::PrintLogo().
sh()
static std::string sh (std::string cmd) inline static
Definition at line 154 of file Globals.h.
Referenced by GRootCanvas::AdjustSize(), GRootCanvas::ShowStatusBar(), and GRootCanvas::ShowToolBar().