GRSISort: LeanComptonMatrices.cxx File Reference
LeanComptonMatrices.cxx File Reference
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <algorithm>
#include <fstream>
#include <Globals.h>
#include <string>
#include <iostream>
#include <iomanip>
#include <list>
#include "TTree.h"
#include "TTreeIndex.h"
#include "TVirtualIndex.h"
#include "TFile.h"
#include "TList.h"
#include "TFragment.h"
#include "TChannel.h"
#include "TApplication.h"
#include "TROOT.h"
#include "TChain.h"
#include "TMath.h"
#include "TF1.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TH3F.h"
#include "TVector.h"
#include "TVector3.h"
#include "TCanvas.h"
#include "TLatex.h"
#include "TStyle.h"
#include "TStopwatch.h"
#include "TSpectrum.h"
#include "TGraph.h"
#include "TMultiGraph.h"
#include "TGraphErrors.h"
#include "TRunInfo.h"
#include "TGRSISortInfo.h"
#include "TGriffin.h"
Functions
TList * ComptonHists (TTree *tree, int64_t maxEntries, TStopwatch *w)
int main (int argc, char **argv)
Variables
constexpr int MaxEntries = 0
Function Documentation
ComptonHists()
TList * ComptonHists (TTree * tree, int64_t maxEntries, TStopwatch * w)
Definition at line 142 of file LeanComptonMatrices.cxx.
References TDetectorHit::GetCrystal(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TGriffin::GetGriffinHit(), TGriffin::GetMultiplicity(), TGriffinHit::GetPosition(), TGriffin::GetPosition(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStamp(), and TGriffin::ResetAddback().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 74 of file LeanComptonMatrices.cxx.
References ComptonHists(), DBLUE, MaxEntries, TChannel::ReadCalFromTree(), RESET_COLOR, TRunInfo::RunNumber(), and TRunInfo::SubRunNumber().
Variable Documentation
MaxEntries
constexpr int MaxEntries = 0 constexpr
Definition at line 70 of file LeanComptonMatrices.cxx.
Referenced by main().