GRSISort: MakeGriffinHistograms.cxx File Reference
MakeGriffinHistograms.cxx File Reference
#include "TRuntimeObjects.h"
#include "TRunInfo.h"
#include "TGriffin.h"
#include "TGriffinBgo.h"
#include "TSceptar.h"
#include "TZeroDegree.h"
#include "TDescant.h"
Functions
void MakeAnalysisHistograms (TRuntimeObjects &obj)
bool PromptCoincidence (TBgoHit *bgo_hit, TGriffinHit *grif_hit)
bool PromptCoincidence (TGriffinHit *hit1, TGriffinHit *hit2)
bool PromptCoincidence (TSceptarHit *sc_hit, TGriffinHit *grif_hit)
bool PromptCoincidence (TZeroDegreeHit *sc_hit, TGriffinHit *grif_hit)
Variables
const Double_t bELow = 50 * keV
const Double_t gbgoTHigh = 250 * ns
const Double_t gbgoTLow = -250 * ns
const Double_t gbTHigh = 300 * ns
const Double_t gbTLow = -150 * ns
const Double_t ggTHigh = 200 * ns
const Double_t ggTLow = -200 * ns
const Double_t gzTHigh = 50 * ns
const Double_t gzTLow = -50 * ns
const ULong64_t kCycleLength = 34.5 * s
const Double_t keV = 1.
const Double_t MeV = 1E3
const Double_t ms = 1E6
const Double_t ns = 1.
const Double_t ps = 1E-3
const Double_t s = 1E9
const Double_t us = 1E3
const Double_t zELow = 200 * keV
Function Documentation
MakeAnalysisHistograms()
void MakeAnalysisHistograms (TRuntimeObjects & obj)
Definition at line 53 of file MakeGriffinHistograms.cxx.
References TRuntimeObjects::FillHistogram(), TDetectorHit::GetArrayNumber(), TDetectorHit::GetDetector(), TRuntimeObjects::GetDetector(), TDetectorHit::GetEnergy(), TGriffin::GetGriffinHit(), TDetector::GetHit(), TDetector::GetMultiplicity(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStamp(), kCycleLength, keV, ns, PromptCoincidence(), TRunInfo::RunNumber(), and s.
PromptCoincidence() [1/4]
bool PromptCoincidence (TBgoHit * bgo_hit, TGriffinHit * grif_hit)
Definition at line 38 of file MakeGriffinHistograms.cxx.
References gbgoTHigh, gbgoTLow, TDetectorHit::GetTime(), and ns.
PromptCoincidence() [2/4]
bool PromptCoincidence (TGriffinHit * hit1, TGriffinHit * hit2)
Definition at line 33 of file MakeGriffinHistograms.cxx.
References TDetectorHit::GetTime(), ggTHigh, ggTLow, and ns.
Referenced by MakeAnalysisHistograms().
PromptCoincidence() [3/4]
bool PromptCoincidence (TSceptarHit * sc_hit, TGriffinHit * grif_hit)
Definition at line 43 of file MakeGriffinHistograms.cxx.
References bELow, gbTHigh, gbTLow, TDetectorHit::GetEnergy(), TDetectorHit::GetTime(), and ns.
PromptCoincidence() [4/4]
bool PromptCoincidence (TZeroDegreeHit * sc_hit, TGriffinHit * grif_hit)
Definition at line 48 of file MakeGriffinHistograms.cxx.
References TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TDetectorHit::GetTime(), gzTHigh, gzTLow, ns, and zELow.
Variable Documentation
bELow
const Double_t bELow = 50 * keV
Definition at line 29 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gbgoTHigh
const Double_t gbgoTHigh = 250 * ns
Definition at line 23 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gbgoTLow
const Double_t gbgoTLow = -250 * ns
Definition at line 22 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gbTHigh
const Double_t gbTHigh = 300 * ns
Definition at line 25 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gbTLow
const Double_t gbTLow = -150 * ns
Definition at line 24 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
ggTHigh
const Double_t ggTHigh = 200 * ns
Definition at line 21 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
ggTLow
const Double_t ggTLow = -200 * ns
Definition at line 20 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gzTHigh
const Double_t gzTHigh = 50 * ns
Definition at line 27 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
gzTLow
const Double_t gzTLow = -50 * ns
Definition at line 26 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().
kCycleLength
const ULong64_t kCycleLength = 34.5 * s
Definition at line 31 of file MakeGriffinHistograms.cxx.
Referenced by MakeAnalysisHistograms().
keV
const Double_t keV = 1.
Definition at line 17 of file MakeGriffinHistograms.cxx.
Referenced by MakeAnalysisHistograms().
MeV
const Double_t MeV = 1E3
Definition at line 18 of file MakeGriffinHistograms.cxx.
ms
const Double_t ms = 1E6
Definition at line 14 of file MakeGriffinHistograms.cxx.
ns
const Double_t ns = 1.
Definition at line 12 of file MakeGriffinHistograms.cxx.
Referenced by MakeAnalysisHistograms(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), and PromptCoincidence().
ps
const Double_t ps = 1E-3
Definition at line 11 of file MakeGriffinHistograms.cxx.
Referenced by TKinematics::GetBeamEnergy().
s
const Double_t s = 1E9
Definition at line 15 of file MakeGriffinHistograms.cxx.
Referenced by TSiLi::AddCluster(), TGRSIDataParser::CaenPhaToFragment(), TGRSIDataParser::CaenPsdToFragment(), TGRSIFunctions::CsIFitFunction(), TPulseAnalyzer::CsIPID(), TPulseAnalyzer::determinant(), AngularCorrelationSelector::FillHistograms(), TPulseAnalyzer::get_sin_par(), hasSuffix(), MakeAnalysisHistograms(), TMidasFile::Open(), PromptCoincidence(), TGRSIDataParser::RFScalerToFragment(), GRootCanvas::ShowEditor(), and TPulseAnalyzer::SiLiFitFunction().
us
const Double_t us = 1E3
Definition at line 13 of file MakeGriffinHistograms.cxx.
zELow
const Double_t zELow = 200 * keV
Definition at line 30 of file MakeGriffinHistograms.cxx.
Referenced by PromptCoincidence().