GRSISort: SimulationAngularCorrelation.cxx File Reference
SimulationAngularCorrelation.cxx File Reference
#include <iostream>
#include <iomanip>
#include "TChain.h"
#include "TFile.h"
#include "TGraphErrors.h"
#include "TH2D.h"
#include "Globals.h"
#include "TRedirect.h"
#include "TUserSettings.h"
#include "TGriffin.h"
#include "TGriffinBgo.h"
#include "TGriffinAngles.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 16 of file SimulationAngularCorrelation.cxx.
References TChannel::AddChannel(), TBgo::AddFragment(), TGriffin::AddFragment(), TGriffinAngles::Angle(), TGriffinAngles::begin(), TBgo::Clear(), TGriffin::Clear(), TGriffinAngles::Count(), TGriffinAngles::end(), TUserSettings::GetBool(), TChannel::GetChannel(), TUserSettings::GetDouble(), TUserSettings::GetInt(), TDetector::GetMultiplicity(), TGriffin::GetNSuppressedAddbackFrags(), TUserSettings::GetString(), TUserSettings::GetStringVector(), TGriffin::GetSuppressedAddbackHit(), TGriffin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedHit(), TGriffin::GetSuppressedMultiplicity(), hist, TGriffinAngles::Index(), kAll, kRootFile, TGriffinAngles::NumberOfAngles(), TGriffinAngles::Print(), TUserSettings::ReadSettings(), TChannel::SetAddress(), TChannel::SetCrystalNumber(), TChannel::SetDetectorNumber(), TChannel::SetDigitizerType(), TChannel::SetName(), and TGriffinAngles::Verbosity().