GRSISort: TFippsLaBr.cxx File Reference
TFippsLaBr.cxx File Reference
#include <iostream>
#include "TFippsLaBr.h"
#include <TRandom.h>
#include <TMath.h>
#include "TGRSIOptions.h"
Functions
bool DefaultLaBrSuppression (const TDetectorHit *hit, const TDetectorHit *bgoHit)
Function Documentation
DefaultLaBrSuppression()
bool DefaultLaBrSuppression (const TDetectorHit * hit, const TDetectorHit * bgoHit)
Definition at line 8 of file TFippsLaBr.cxx.
References TGRSIOptions::AnalysisOptions(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TDetectorHit::GetTime(), TAnalysisOptions::SuppressionEnergy(), and TAnalysisOptions::SuppressionWindow().