GRSISort: TGRSIint.cxx File Reference
TGRSIint.cxx File Reference
#include "TGRSIint.h"
#include "GRootGuiFactory.h"
#include "GVersion.h"
#include "Getline.h"
#include "Globals.h"
#include "TDataParser.h"
#include "TGRSIOptions.h"
#include "TGRSIUtilities.h"
#include "GValue.h"
#include "TROOT.h"
#include "GCanvas.h"
#include "StoppableThread.h"
#include "TAnalysisHistLoop.h"
#include "TAnalysisWriteLoop.h"
#include "TDataLoop.h"
#include "TDetBuildingLoop.h"
#include "TEventBuildingLoop.h"
#include "TFragHistLoop.h"
#include "TFragWriteLoop.h"
#include "TFragmentChainLoop.h"
#include "TTerminalLoop.h"
#include "TUnpackingLoop.h"
#include "TPPG.h"
#include "TSortingDiagnostics.h"
#include "TParserLibrary.h"
#include "GRootCommands.h"
#include "TRunInfo.h"
#include "TInterpreter.h"
#include "TGHtmlBrowser.h"
#include <thread>
#include <utility>
#include <pwd.h>
Namespaces
namespace anonymous_namespace{TGRSIint.cxx}
Functions
void PopupLogo (bool)
void ReadTheNews ()
void WaitLogo ()
Variables
bool anonymous_namespace{TGRSIint.cxx}::g__CommandFinished
std::mutex anonymous_namespace{TGRSIint.cxx}::g__CommandListMutex
Long_t anonymous_namespace{TGRSIint.cxx}::g__CommandResult
std::mutex anonymous_namespace{TGRSIint.cxx}::g__CommandWaitingMutex
std::string anonymous_namespace{TGRSIint.cxx}::g__LineToProcess
std::condition_variable anonymous_namespace{TGRSIint.cxx}::g__NewResult
bool anonymous_namespace{TGRSIint.cxx}::g__ProcessingNeeded
std::mutex anonymous_namespace{TGRSIint.cxx}::g__ResultListMutex
Function Documentation
PopupLogo()
void PopupLogo (bool about) extern
Definition at line 302 of file grsixx.cxx.
References DrawCredits(), gAbout, gCreditsHeight, gCreditsPixmap, gCreditsRect, gCreditsWidth, gDisplay, GetRootLogo(), gFont, gGC, gHeight, gLogoPixmap, gLogoWindow, gPopupTime, gWidth, and ReadContributors().
Referenced by TGRSIint::DrawLogo().
ReadTheNews()
void ReadTheNews ()
Opens a random wikipedia page for your enjoyment
Definition at line 267 of file TGRSIint.cxx.
Referenced by TGRSIint::ApplyOptions().
WaitLogo()
void WaitLogo () extern
Definition at line 389 of file grsixx.cxx.
References DrawROOTCredit(), DrawVersion(), gAbout, gCreditsHeight, gCreditsPixmap, gCreditsRect, gDisplay, gDone, gFont, gGC, gLogoPixmap, gLogoWindow, gMayPopdown, gStayUp, ScrollCredits(), Sleep(), and StayUp().
Referenced by TGRSIint::DrawLogo().