GRSISort: TGRSIUtilities.h File Reference
TGRSIUtilities.h File Reference
#include <fstream>
#include <string>
#include <vector>
#include "TGRSITypes.h"
Functions
bool AllFilesExist (const std::vector< std::string > &filenames)
bool DirectoryExists (const char *dirname)
bool FileExists (const char *filename)
size_t FindFileSize (const char *fname)
int GetRunNumber (const std::string &)
int GetSubRunNumber (const std::string &)
void trim (std::string &line, const std::string &trimChars=" \f\n\r\t\v")
void trimWS (std::string &line)
Function Documentation
AllFilesExist()
bool AllFilesExist (const std::vector< std::string > & filenames)
Definition at line 39 of file TGRSIUtilities.cxx.
Referenced by TGRSIint::ApplyOptions().
DirectoryExists()
bool DirectoryExists (const char * dirname)
This checks if the directory exists
Definition at line 26 of file TGRSIUtilities.cxx.
Referenced by TSRIM::ReadEnergyLossFile().
FileExists()
bool FileExists (const char * filename)
This checks if the path exist, and if it is a file and not a directory!
Definition at line 13 of file TGRSIUtilities.cxx.
Referenced by TDataFrameLibrary::Load(), TParserLibrary::Load(), TGRSIint::OpenRawFile(), TGRSIint::RunMacroFile(), and TGRSIint::SetupPipeline().
FindFileSize()
size_t FindFileSize (const char * fname) inline
Definition at line 20 of file TGRSIUtilities.h.
GetRunNumber()
int GetRunNumber (const std::string & fileName)
Definition at line 67 of file TGRSIUtilities.cxx.
Referenced by TGRSIint::SetupPipeline().
GetSubRunNumber()
int GetSubRunNumber (const std::string & fileName)
Definition at line 90 of file TGRSIUtilities.cxx.
Referenced by TGRSIint::SetupPipeline().
trim()
void trim (std::string & line, const std::string & trimChars = " \f\n\r\t\v")
Removes the string "trimCars" from the string 'line'
Definition at line 44 of file TGRSIUtilities.cxx.
Referenced by GValue::ParseInputData(), TRunInfo::ParseInputData(), and TUserSettings::ReadSettings().
trimWS()
void trimWS (std::string & line)
Removes whitespace from the string 'line'
Definition at line 60 of file TGRSIUtilities.cxx.
Referenced by TChannel::ParseInputData().