GRSISort: TParallelFileMerger.h File Reference
TParallelFileMerger.h File Reference
#include <iostream>
#include "TSystem.h"
#include "TDirectory.h"
#include "TFile.h"
#include "TKey.h"
#include "TTimeStamp.h"
#include "TFileMerger.h"
#include "TBits.h"
#include "TClass.h"
#include "TFileCacheWrite.h"
#include "TMath.h"
Classes
struct ClientInfo
class TParallelFileMerger
Functions
void DeleteObject (TDirectory *dir, bool withReset)
void MigrateKey (TDirectory *destination, TDirectory *source)
bool NeedInitialMerge (TDirectory *dir)
Function Documentation
DeleteObject()
void DeleteObject (TDirectory * dir, bool withReset)
Definition at line 33 of file TParallelFileMerger.cxx.
References DeleteObject().
Referenced by DeleteObject(), TParallelFileMerger::InitialMerge(), and TParallelFileMerger::Merge().
MigrateKey()
void MigrateKey (TDirectory * destination, TDirectory * source)
Definition at line 64 of file TParallelFileMerger.cxx.
References MigrateKey().
Referenced by MigrateKey(), and ClientInfo::Set().
NeedInitialMerge()
bool NeedInitialMerge (TDirectory * dir)
Definition at line 5 of file TParallelFileMerger.cxx.
References NeedInitialMerge().
Referenced by NeedInitialMerge().