GRSISort: TSourceCalibration.cxx File Reference
TSourceCalibration.cxx File Reference
#include "TSourceCalibration.h"
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <iomanip>
#include <string>
#include <cstring>
#include "TSystem.h"
#include "TGTableLayout.h"
#include "TCanvas.h"
#include "TLinearFitter.h"
#include "TF1.h"
#include "TSpectrum.h"
#include "TPolyMarker.h"
#include "TObject.h"
#include "TChannel.h"
#include "GRootCommands.h"
#include "combinations.h"
#include "TRWPeak.h"
#include "Globals.h"
Functions
double Efficiency (double *x, double *par)
bool FilledBin (TH2 *matrix, const int &bin)
std::map< std::tuple< double, double, double, double >, std::tuple< double, double, double, double > > Match (std::vector< std::tuple< double, double, double, double > > peaks, std::vector< std::tuple< double, double, double, double > > sources, int verboseLevel)
double Polynomial (double *x, double *par)
std::map< std::tuple< double, double, double, double >, std::tuple< double, double, double, double > > SmartMatch (std::vector< std::tuple< double, double, double, double > > peaks, std::vector< std::tuple< double, double, double, double > > sources, int verboseLevel)
Function Documentation
Efficiency()
double Efficiency (double * x, double * par)
Definition at line 272 of file TSourceCalibration.cxx.
Referenced by TSourceCalibration::FitEfficiency().
FilledBin()
bool FilledBin (TH2 * matrix, const int & bin)
Definition at line 281 of file TSourceCalibration.cxx.
Referenced by TSourceCalibration::TSourceCalibration(), and TSourceCalibration::BuildThirdInterface().
Match()
std::map< std::tuple< double, double, double, double >, std::tuple< double, double, double, double > > Match (std::vector< std::tuple< double, double, double, double > > peaks, std::vector< std::tuple< double, double, double, double > > sources, int verboseLevel)
This function tries to match a list of found peaks (channels) to a list of provided peaks (energies). It does so in a brute force fashion where we try all combinations of channels and energies, do a linear fit through them, and keep the one with the best chi square.
Definition at line 28 of file TSourceCalibration.cxx.
Referenced by TChannelTab::FindPeaks().
Polynomial()
double Polynomial (double * x, double * par)
Definition at line 263 of file TSourceCalibration.cxx.
Referenced by TChannelTab::Calibrate(), TSourceCalibration::FinalWindow(), and TSourceCalibration::FitFinal().
SmartMatch()
std::map< std::tuple< double, double, double, double >, std::tuple< double, double, double, double > > SmartMatch (std::vector< std::tuple< double, double, double, double > > peaks, std::vector< std::tuple< double, double, double, double > > sources, int verboseLevel)
This function tries to match a list of found peaks (channels) to a list of provided peaks (energies). It does so in slightly smarter way than the brute force method Match, by taking the reported intensity of the source peaks into account.
Definition at line 144 of file TSourceCalibration.cxx.
Referenced by TChannelTab::FindPeaks().