GRSISort: TSourceCalibration.h File Reference
TSourceCalibration.h File Reference
#include <cstdarg>
#include <iostream>
#include <vector>
#include <string>
#include <thread>
#include <mutex>
#include "TFile.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TLegend.h"
#include "TGFrame.h"
#include "TGTab.h"
#include "TGFSComboBox.h"
#include "TGStatusBar.h"
#include "TGButtonGroup.h"
#include "TGButton.h"
#include "TGNumberEntry.h"
#include "TGLabel.h"
#include "TGProgressBar.h"
#include "TRootEmbeddedCanvas.h"
#include "TH2.h"
#include "TPaveText.h"
#include "RVersion.h"
#include "GPeak.h"
#include "TSinglePeak.h"
#include "TNucleus.h"
#include "TCalibrationGraph.h"
#include "GH1D.h"
#include "Globals.h"
#include "TRedirect.h"
Classes
class TChannelTab
class TSourceCalibration
class TSourceTab
Functions
bool FilledBin (TH2 *matrix, const int &bin)
std::map< GPeak *, std::tuple< double, double, double, double > > Match (std::vector< GPeak * > peaks, std::vector< std::tuple< double, double, double, double > > sources, TSourceTab *sourceTab)
double Polynomial (double *x, double *par)
std::map< GPeak *, std::tuple< double, double, double, double > > SmartMatch (std::vector< GPeak * > peaks, std::vector< std::tuple< double, double, double, double > > sources, TSourceTab *sourceTab)
Function Documentation
FilledBin()
bool FilledBin (TH2 * matrix, const int & bin)
Definition at line 312 of file TSourceCalibration.cxx.
Referenced by TSourceCalibration::TSourceCalibration().
Match()
std::map< GPeak *, std::tuple< double, double, double, double > > Match (std::vector< GPeak * > peaks, std::vector< std::tuple< double, double, double, double > > sources, TSourceTab * sourceTab)
This function tries to match a list of found peaks (channels) to a list of provided peaks (energies). It does so in a brute force fashion where we try all combinations of channels and energies, do a linear fit through them, and keep the one with the best chi square.
Definition at line 29 of file TSourceCalibration.cxx.
References kAll, kBasicFlow, kLoops, kSubroutines, TSourceCalibration::MaxIterations(), RESET_COLOR, TSourceTab::Status(), and TSourceCalibration::VerboseLevel().
Referenced by TSourceTab::FindPeaks(), and TSourceTab::ProjectionStatus().
Polynomial()
double Polynomial (double * x, double * par)
Definition at line 303 of file TSourceCalibration.cxx.
Referenced by TChannelTab::Calibrate().
SmartMatch()
std::map< GPeak *, std::tuple< double, double, double, double > > SmartMatch (std::vector< GPeak * > peaks, std::vector< std::tuple< double, double, double, double > > sources, TSourceTab * sourceTab)
This function tries to match a list of found peaks (channels) to a list of provided peaks (energies). It does so in slightly smarter way than the brute force method Match, by taking the reported intensity of the source peaks into account.
Definition at line 160 of file TSourceCalibration.cxx.
References kAll, kBasicFlow, kLoops, kSubroutines, TSourceCalibration::MaxIterations(), RESET_COLOR, TSourceTab::Status(), and TSourceCalibration::VerboseLevel().
Referenced by TSourceTab::FindPeaks().