GRSISort: TTigress.cxx File Reference
TTigress.cxx File Reference
#include "TTigress.h"
#include <iostream>
#include "TRandom.h"
#include "TMath.h"
#include "TClass.h"
#include "TInterpreter.h"
#include "TGRSIOptions.h"
#include "TSortingDiagnostics.h"
Functions
bool DefaultAddback (TDetectorHit *one, TDetectorHit *two)
bool DefaultSuppression (TDetectorHit *tig, TBgoHit &bgo)
std::underlying_type< TTigress::ETigressGlobalBits >::type operator| (TTigress::ETigressGlobalBits lhs, TTigress::ETigressGlobalBits rhs)
Function Documentation
DefaultAddback()
bool DefaultAddback (TDetectorHit * one, TDetectorHit * two)
Definition at line 24 of file TTigress.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), TTigress::GetForceCrystal(), TDetectorHit::GetSegment(), TTigressHit::GetSegmentMultiplicity(), and TDetectorHit::GetTime().
DefaultSuppression()
bool DefaultSuppression (TDetectorHit * tig, TBgoHit & bgo)
Definition at line 65 of file TTigress.cxx.
References TDetectorHit::GetCfd(), TDetectorHit::GetDetector(), and TDetectorHit::GetEnergy().