GRSISort: TTdrTigress.cxx File Reference
TTdrTigress.cxx File Reference
#include "TTdrTigress.h"
#include <sstream>
#include <iostream>
#include <iomanip>
#include "TRandom.h"
#include "TMath.h"
#include "TInterpreter.h"
#include "TMnemonic.h"
#include "TGRSIOptions.h"
Functions
bool DefaultAddback (TTdrTigressHit *one, TTdrTigressHit *two)
bool DefaultSuppression (TTdrTigressHit *clo, TBgoHit *bgo)
Function Documentation
DefaultAddback()
bool DefaultAddback (TTdrTigressHit * one, TTdrTigressHit * two)
Definition at line 24 of file TTdrTigress.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), TDetectorHit::GetDetector(), and TDetectorHit::GetTime().
DefaultSuppression()
bool DefaultSuppression (TTdrTigressHit * clo, TBgoHit * bgo)
Definition at line 32 of file TTdrTigress.cxx.
References TGRSIOptions::AnalysisOptions(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TDetectorHit::GetTime(), TAnalysisOptions::SuppressionEnergy(), and TAnalysisOptions::SuppressionWindow().