GRSISort: TTdrClover.cxx File Reference
TTdrClover.cxx File Reference
#include "TTdrClover.h"
#include <sstream>
#include <iostream>
#include <iomanip>
#include "TRandom.h"
#include "TMath.h"
#include "TInterpreter.h"
#include "TMnemonic.h"
#include "TGRSIOptions.h"
Functions
bool DefaultAddback (TTdrCloverHit *one, TTdrCloverHit *two)
bool DefaultSuppression (TTdrCloverHit *clo, TBgoHit *bgo)
Function Documentation
DefaultAddback()
bool DefaultAddback (TTdrCloverHit * one, TTdrCloverHit * two)
TTdrClover
The TTdrClover class defines the observables and algorithms used when analyzing GRIFFIN data. It includes detector positions, add-back methods, etc.
Definition at line 24 of file TTdrClover.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), TDetectorHit::GetDetector(), and TDetectorHit::GetTime().
DefaultSuppression()
bool DefaultSuppression (TTdrCloverHit * clo, TBgoHit * bgo)
Definition at line 32 of file TTdrClover.cxx.
References TGRSIOptions::AnalysisOptions(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TDetectorHit::GetTime(), TAnalysisOptions::SuppressionEnergy(), and TAnalysisOptions::SuppressionWindow().