GRSISort: UserFillObj.h File Reference
UserFillObj.h File Reference
Functions
if (hist &&fragment->DetectorType<=1) hist -> Fill(fragment->GetEnergy())
if (hist &&fragment->TriggerBitPattern > -1) hist -> Fill(fragment->TriggerBitPattern)
if (hist &&fragment->TriggerId > 0) hist -> Fill(fragment->GetCharge(0))
if (hist &&fragment->TriggerId< 0) hist -> Fill(fragment->GetCharge(0))
if (hist) hist -> Fill(fragment->GetCharge())
if (histcfd) histcfd -> Fill(fragment->Cfd)
if (mat &&fragment->DetectorType<=1) mat -> Fill(channel->GetNumber(), fragment->GetCharge(0))
Variables
TH1D * hist = (TH1D*)(GetOutputList()->FindObject(Form("Charge_0x%04x", fragment->ChannelAddress)))
TH1D * histcfd = (TH1D*)(GetOutputList()->FindObject(Form("Cfd_0x%04x", fragment->ChannelAddress)))
TH2D * mat = (TH2D*)(GetOutputList()->FindObject("hp_charge"))
Function Documentation
if() [1/7]
if (hist &&fragment->DetectorType<= 1) -> Fill(fragment->GetEnergy())
if() [2/7]
if (hist &&fragment-> TriggerBitPattern, - 1) -> Fill(fragment->TriggerBitPattern)
if() [3/7]
if (hist &&fragment-> TriggerId, 0) -> Fill(fragment->GetCharge(0))
if() [4/7]
if ()
Referenced by pygui.mainwindow.MainWindow::_draw_single(), and pygui.tcut_tab.TCutTab::DeleteCut().
if() [5/7]
if (hist) -> Fill(fragment->GetCharge())
if() [6/7]
if (histcfd) -> Fill(fragment->Cfd)
if() [7/7]
if (mat &&fragment->DetectorType<= 1) -> Fill(channel->GetNumber(), fragment->GetCharge(0))
Variable Documentation
hist
hist = (TH1D*)(GetOutputList()->FindObject(Form("Charge_0x%04x", fragment->ChannelAddress)))
Definition at line 3 of file UserFillObj.h.
Referenced by GCanvas::AddMarker(), TGainMatch::Align(), TGainMatch::AlignAll(), AltPhotoPeakFit(), TCompiledHistograms::ClearHistograms(), TGainMatch::CoarseMatch(), DoubleGausFit(), GH1D::DrawCopy(), GH2D::DrawCopy(), GH2I::DrawCopy(), GH1D::DrawNormalized(), GH2D::DrawNormalized(), GH2I::DrawNormalized(), TCalibrationGraphSet::DrawResidual(), GGaus::DrawResiduals(), GPeak::DrawResiduals(), TRuntimeObjects::FillHistogram(), TRuntimeObjects::FillHistogram(), TRuntimeObjects::FillHistogramSym(), GHSym::FillRandom(), FindHists(), GCanvas::FindHists(), TGainMatch::FineMatchFast(), TGainMatch::FineMatchFast(), TDecayFit::Fit(), TLMFitter::Fit(), GausFit(), TPeak::GetIntegralArea(), TPeak::GetIntegralAreaErr(), GCanvas::GetLastFit(), GH2Base::GetNextSummary(), GH2Base::GetPrevSummary(), GetProjection(), GetTimeDiff(), GetTimeDiff(), GrabFit(), GrabHist(), GCanvas::HandleMousePress(), GCanvas::HandleMouseShiftPress(), LabelPeaks(), Move1DHistogram(), Move2DHistogram(), PhotoPeakFit(), PhotoPeakFit(), GCanvas::Process1DKeyboardPress(), GCanvas::Process2DKeyboardPress(), TCompiledHistograms::SetDefaultDirectory(), TCal::SetHist(), TGRSIFit::SetHist(), and TDecayFit::UpdateResiduals().
histcfd
TH1D* histcfd = (TH1D*)(GetOutputList()->FindObject(Form("Cfd_0x%04x", fragment->ChannelAddress)))
Definition at line 9 of file UserFillObj.h.
mat
mat = (TH2D*)(GetOutputList()->FindObject("hp_charge"))
Definition at line 12 of file UserFillObj.h.
Referenced by TSourceCalibration::TSourceCalibration(), AddOffset(), TGainMatch::AlignAll(), TGainMatch::CoarseMatchAll(), CrossTalkFix(), TGainMatch::FineMatchFastAll(), and TGainMatch::FineMatchFastAll().