var annotated_dup =
[
    [ "grsi", "namespacegrsi.html", [
      [ "exit_exception", "structgrsi_1_1exit__exception.html", "structgrsi_1_1exit__exception" ]
    ] ],
    [ "pygui", "namespacepygui.html", [
      [ "AnsiColorText", "namespacepygui_1_1_ansi_color_text.html", [
        [ "AnsiColorText", "classpygui_1_1_ansi_color_text_1_1_ansi_color_text.html", "classpygui_1_1_ansi_color_text_1_1_ansi_color_text" ]
      ] ],
      [ "hist_tab", "namespacepygui_1_1hist__tab.html", [
        [ "HistTab", "classpygui_1_1hist__tab_1_1_hist_tab.html", "classpygui_1_1hist__tab_1_1_hist_tab" ]
      ] ],
      [ "mainwindow", "namespacepygui_1_1mainwindow.html", [
        [ "MainWindow", "classpygui_1_1mainwindow_1_1_main_window.html", "classpygui_1_1mainwindow_1_1_main_window" ]
      ] ],
      [ "status_widget", "namespacepygui_1_1status__widget.html", [
        [ "ThreadStatusFrame", "classpygui_1_1status__widget_1_1_thread_status_frame.html", "classpygui_1_1status__widget_1_1_thread_status_frame" ],
        [ "ThreadVars", "classpygui_1_1status__widget_1_1_thread_vars.html", "classpygui_1_1status__widget_1_1_thread_vars" ]
      ] ],
      [ "tcut_tab", "namespacepygui_1_1tcut__tab.html", [
        [ "TCutTab", "classpygui_1_1tcut__tab_1_1_t_cut_tab.html", "classpygui_1_1tcut__tab_1_1_t_cut_tab" ]
      ] ],
      [ "util", "namespacepygui_1_1util.html", [
        [ "PreserveGDir", "classpygui_1_1util_1_1_preserve_g_dir.html", "classpygui_1_1util_1_1_preserve_g_dir" ],
        [ "TKeyDict", "classpygui_1_1util_1_1_t_key_dict.html", "classpygui_1_1util_1_1_t_key_dict" ]
      ] ],
      [ "variable_tab", "namespacepygui_1_1variable__tab.html", [
        [ "VariableTab", "classpygui_1_1variable__tab_1_1_variable_tab.html", "classpygui_1_1variable__tab_1_1_variable_tab" ]
      ] ]
    ] ],
    [ "AlphanumericHelper", "class_alphanumeric_helper.html", "class_alphanumeric_helper" ],
    [ "AlphanumericSelector", "class_alphanumeric_selector.html", "class_alphanumeric_selector" ],
    [ "AngularCorrelationHelper", "class_angular_correlation_helper.html", "class_angular_correlation_helper" ],
    [ "AngularCorrelationSelector", "class_angular_correlation_selector.html", "class_angular_correlation_selector" ],
    [ "ArgParseConfig", "class_arg_parse_config.html", "class_arg_parse_config" ],
    [ "ArgParseConfigT", "class_arg_parse_config_t.html", "class_arg_parse_config_t" ],
    [ "ArgParseConfigT< bool >", "class_arg_parse_config_t_3_01bool_01_4.html", "class_arg_parse_config_t_3_01bool_01_4" ],
    [ "ArgParseItem", "class_arg_parse_item.html", "class_arg_parse_item" ],
    [ "ArgParser", "class_arg_parser.html", "class_arg_parser" ],
    [ "ClientInfo", "struct_client_info.html", "struct_client_info" ],
    [ "combinations", "classcombinations.html", "classcombinations" ],
    [ "CrossTalk", "class_cross_talk.html", "class_cross_talk" ],
    [ "CrossTalkHelper", "class_cross_talk_helper.html", "class_cross_talk_helper" ],
    [ "DifferentAxisLimits", "class_different_axis_limits.html", null ],
    [ "DifferentBinLimits", "class_different_bin_limits.html", null ],
    [ "DifferentDimension", "class_different_dimension.html", null ],
    [ "DifferentLabels", "class_different_labels.html", null ],
    [ "DifferentNumberOfBins", "class_different_number_of_bins.html", null ],
    [ "DirectoryHelper", "class_directory_helper.html", "class_directory_helper" ],
    [ "DynamicLibrary", "class_dynamic_library.html", "class_dynamic_library" ],
    [ "EfficiencyHelper", "class_efficiency_helper.html", "class_efficiency_helper" ],
    [ "ExampleEventHelper", "class_example_event_helper.html", "class_example_event_helper" ],
    [ "ExampleEventSelector", "class_example_event_selector.html", "class_example_event_selector" ],
    [ "ExampleFragmentHelper", "class_example_fragment_helper.html", "class_example_fragment_helper" ],
    [ "ExampleFragmentSelector", "class_example_fragment_selector.html", "class_example_fragment_selector" ],
    [ "ExampleTreeHelper", "class_example_tree_helper.html", "class_example_tree_helper" ],
    [ "ExampleTreeSelector", "class_example_tree_selector.html", "class_example_tree_selector" ],
    [ "FastTimingHistSelector", "class_fast_timing_hist_selector.html", "class_fast_timing_hist_selector" ],
    [ "GBrowserPlugin", "class_g_browser_plugin.html", "class_g_browser_plugin" ],
    [ "GCanvas", "class_g_canvas.html", "class_g_canvas" ],
    [ "GCube", "class_g_cube.html", "class_g_cube" ],
    [ "GCubeD", "class_g_cube_d.html", "class_g_cube_d" ],
    [ "GCubeF", "class_g_cube_f.html", "class_g_cube_f" ],
    [ "GGaus", "class_g_gaus.html", "class_g_gaus" ],
    [ "GH1D", "class_g_h1_d.html", "class_g_h1_d" ],
    [ "GH2Base", "class_g_h2_base.html", "class_g_h2_base" ],
    [ "GH2D", "class_g_h2_d.html", "class_g_h2_d" ],
    [ "GH2I", "class_g_h2_i.html", "class_g_h2_i" ],
    [ "GHSym", "class_g_h_sym.html", "class_g_h_sym" ],
    [ "GHSymD", "class_g_h_sym_d.html", "class_g_h_sym_d" ],
    [ "GHSymF", "class_g_h_sym_f.html", "class_g_h_sym_f" ],
    [ "GMarker", "class_g_marker.html", "class_g_marker" ],
    [ "GNotifier", "class_g_notifier.html", "class_g_notifier" ],
    [ "GPeak", "class_g_peak.html", "class_g_peak" ],
    [ "GPopup", "class_g_popup.html", "class_g_popup" ],
    [ "GriffinKValueHelper", "class_griffin_k_value_helper.html", "class_griffin_k_value_helper" ],
    [ "GriffinKValueSelector", "class_griffin_k_value_selector.html", "class_griffin_k_value_selector" ],
    [ "GRootBrowser", "class_g_root_browser.html", "class_g_root_browser" ],
    [ "GRootCanvas", "class_g_root_canvas.html", "class_g_root_canvas" ],
    [ "GRootContainer", "class_g_root_container.html", "class_g_root_container" ],
    [ "GRootGuiFactory", "class_g_root_gui_factory.html", "class_g_root_gui_factory" ],
    [ "GSnapshot", "class_g_snapshot.html", "class_g_snapshot" ],
    [ "GValue", "class_g_value.html", "class_g_value" ],
    [ "NRMat", "class_n_r_mat.html", "class_n_r_mat" ],
    [ "NRMat3d", "class_n_r_mat3d.html", "class_n_r_mat3d" ],
    [ "NRVec", "class_n_r_vec.html", "class_n_r_vec" ],
    [ "ParseError", "struct_parse_error.html", "struct_parse_error" ],
    [ "StoppableThread", "class_stoppable_thread.html", "class_stoppable_thread" ],
    [ "SuppressTH1GDirectory", "class_suppress_t_h1_g_directory.html", "class_suppress_t_h1_g_directory" ],
    [ "TAB3Peak", "class_t_a_b3_peak.html", "class_t_a_b3_peak" ],
    [ "TABPeak", "class_t_a_b_peak.html", "class_t_a_b_peak" ],
    [ "TAnalysisHistLoop", "class_t_analysis_hist_loop.html", "class_t_analysis_hist_loop" ],
    [ "TAnalysisOptions", "class_t_analysis_options.html", "class_t_analysis_options" ],
    [ "TAnalysisWriteLoop", "class_t_analysis_write_loop.html", "class_t_analysis_write_loop" ],
    [ "TBadFragment", "class_t_bad_fragment.html", "class_t_bad_fragment" ],
    [ "TBetaDecay", "class_t_beta_decay.html", "class_t_beta_decay" ],
    [ "TBgo", "class_t_bgo.html", "class_t_bgo" ],
    [ "TBgoHit", "class_t_bgo_hit.html", "class_t_bgo_hit" ],
    [ "TBGSubtraction", "class_t_b_g_subtraction.html", "class_t_b_g_subtraction" ],
    [ "TCal", "class_t_cal.html", "class_t_cal" ],
    [ "TCalGraph", "class_t_cal_graph.html", "class_t_cal_graph" ],
    [ "TCalibrateDescant", "class_t_calibrate_descant.html", "class_t_calibrate_descant" ],
    [ "TCalibrationGraph", "class_t_calibration_graph.html", "class_t_calibration_graph" ],
    [ "TCalibrationGraphSet", "class_t_calibration_graph_set.html", "class_t_calibration_graph_set" ],
    [ "TCalibrator", "class_t_calibrator.html", "class_t_calibrator" ],
    [ "TCalList", "class_t_cal_list.html", "class_t_cal_list" ],
    [ "TCalManager", "class_t_cal_manager.html", "class_t_cal_manager" ],
    [ "TCalPoint", "class_t_cal_point.html", "class_t_cal_point" ],
    [ "TCFDCal", "class_t_c_f_d_cal.html", "class_t_c_f_d_cal" ],
    [ "TChannel", "class_t_channel.html", "class_t_channel" ],
    [ "TChannelTab", "class_t_channel_tab.html", "class_t_channel_tab" ],
    [ "TCompiledHistograms", "class_t_compiled_histograms.html", "class_t_compiled_histograms" ],
    [ "TDataFrameLibrary", "class_t_data_frame_library.html", "class_t_data_frame_library" ],
    [ "TDataLoop", "class_t_data_loop.html", "class_t_data_loop" ],
    [ "TDataParser", "class_t_data_parser.html", "class_t_data_parser" ],
    [ "TDeadtimeScalerQueue", "class_t_deadtime_scaler_queue.html", "class_t_deadtime_scaler_queue" ],
    [ "TDecay", "class_t_decay.html", "class_t_decay" ],
    [ "TDecayChain", "class_t_decay_chain.html", "class_t_decay_chain" ],
    [ "TDecayFit", "class_t_decay_fit.html", "class_t_decay_fit" ],
    [ "TDetBuildingLoop", "class_t_det_building_loop.html", "class_t_det_building_loop" ],
    [ "TDetector", "class_t_detector.html", "class_t_detector" ],
    [ "TDetectorHit", "class_t_detector_hit.html", "class_t_detector_hit" ],
    [ "TDetectorInformation", "class_t_detector_information.html", "class_t_detector_information" ],
    [ "TEfficiencyCal", "class_t_efficiency_cal.html", "class_t_efficiency_cal" ],
    [ "TEfficiencyCalibration", "class_t_efficiency_calibration.html", "class_t_efficiency_calibration" ],
    [ "TEfficiencyGraph", "class_t_efficiency_graph.html", "class_t_efficiency_graph" ],
    [ "TEnergyCal", "class_t_energy_cal.html", "class_t_energy_cal" ],
    [ "TEpicsFrag", "class_t_epics_frag.html", "class_t_epics_frag" ],
    [ "TEventBuildingLoop", "class_t_event_building_loop.html", "class_t_event_building_loop" ],
    [ "TFragHistLoop", "class_t_frag_hist_loop.html", "class_t_frag_hist_loop" ],
    [ "TFragment", "class_t_fragment.html", "class_t_fragment" ],
    [ "TFragmentChainLoop", "class_t_fragment_chain_loop.html", "class_t_fragment_chain_loop" ],
    [ "TFragmentMap", "class_t_fragment_map.html", "class_t_fragment_map" ],
    [ "TFragWriteLoop", "class_t_frag_write_loop.html", "class_t_frag_write_loop" ],
    [ "TGainMatch", "class_t_gain_match.html", "class_t_gain_match" ],
    [ "TGauss", "class_t_gauss.html", "class_t_gauss" ],
    [ "TGRSIFit", "class_t_g_r_s_i_fit.html", "class_t_g_r_s_i_fit" ],
    [ "TGRSIFrame", "class_t_g_r_s_i_frame.html", "class_t_g_r_s_i_frame" ],
    [ "TGRSIHelper", "class_t_g_r_s_i_helper.html", "class_t_g_r_s_i_helper" ],
    [ "TGRSIint", "class_t_g_r_s_iint.html", "class_t_g_r_s_iint" ],
    [ "TGRSIInterruptHandler", "class_t_g_r_s_i_interrupt_handler.html", "class_t_g_r_s_i_interrupt_handler" ],
    [ "TGRSIMap", "class_t_g_r_s_i_map.html", "class_t_g_r_s_i_map" ],
    [ "TGRSIMapException", "class_t_g_r_s_i_map_exception.html", "class_t_g_r_s_i_map_exception" ],
    [ "TGRSIOptions", "class_t_g_r_s_i_options.html", "class_t_g_r_s_i_options" ],
    [ "TGRSIProof", "class_t_g_r_s_i_proof.html", "class_t_g_r_s_i_proof" ],
    [ "TGRSISelector", "class_t_g_r_s_i_selector.html", "class_t_g_r_s_i_selector" ],
    [ "TGRSIServer", "class_t_g_r_s_i_server.html", "class_t_g_r_s_i_server" ],
    [ "TGRSISortInfo", "class_t_g_r_s_i_sort_info.html", "class_t_g_r_s_i_sort_info" ],
    [ "TGRSISortList", "class_t_g_r_s_i_sort_list.html", "class_t_g_r_s_i_sort_list" ],
    [ "TGRSITransition", "class_t_g_r_s_i_transition.html", "class_t_g_r_s_i_transition" ],
    [ "ThreadsafeQueue", "class_threadsafe_queue.html", "class_threadsafe_queue" ],
    [ "TimeWalkHelper", "class_time_walk_helper.html", "class_time_walk_helper" ],
    [ "TimeWalkSelector", "class_time_walk_selector.html", "class_time_walk_selector" ],
    [ "TKinematics", "class_t_kinematics.html", "class_t_kinematics" ],
    [ "TLMFitter", "class_t_l_m_fitter.html", "class_t_l_m_fitter" ],
    [ "TMnemonic", "class_t_mnemonic.html", "class_t_mnemonic" ],
    [ "TMultiPeak", "class_t_multi_peak.html", "class_t_multi_peak" ],
    [ "TNucleus", "class_t_nucleus.html", "class_t_nucleus" ],
    [ "TObjectWrapper", "class_t_object_wrapper.html", "class_t_object_wrapper" ],
    [ "TParallelFileMerger", "class_t_parallel_file_merger.html", "class_t_parallel_file_merger" ],
    [ "TParameterInput", "class_t_parameter_input.html", "class_t_parameter_input" ],
    [ "TParserLibrary", "class_t_parser_library.html", "class_t_parser_library" ],
    [ "TParsingDiagnostics", "class_t_parsing_diagnostics.html", "class_t_parsing_diagnostics" ],
    [ "TParsingDiagnosticsData", "class_t_parsing_diagnostics_data.html", "class_t_parsing_diagnostics_data" ],
    [ "TPeak", "class_t_peak.html", "class_t_peak" ],
    [ "TPeakFitter", "class_t_peak_fitter.html", "class_t_peak_fitter" ],
    [ "TPPG", "class_t_p_p_g.html", "class_t_p_p_g" ],
    [ "TPPGData", "class_t_p_p_g_data.html", "class_t_p_p_g_data" ],
    [ "TPreserveGDirectory", "class_t_preserve_g_directory.html", "class_t_preserve_g_directory" ],
    [ "TPriorityValue", "class_t_priority_value.html", "class_t_priority_value" ],
    [ "TPulseAnalyzer", "class_t_pulse_analyzer.html", "class_t_pulse_analyzer" ],
    [ "TRateScalerQueue", "class_t_rate_scaler_queue.html", "class_t_rate_scaler_queue" ],
    [ "TRawEvent", "class_t_raw_event.html", "class_t_raw_event" ],
    [ "TRawFile", "class_t_raw_file.html", "class_t_raw_file" ],
    [ "TReaction", "class_t_reaction.html", "class_t_reaction" ],
    [ "TRedirect", "class_t_redirect.html", "class_t_redirect" ],
    [ "TRunInfo", "class_t_run_info.html", "class_t_run_info" ],
    [ "TRuntimeObjects", "class_t_runtime_objects.html", "class_t_runtime_objects" ],
    [ "TRWPeak", "class_t_r_w_peak.html", "class_t_r_w_peak" ],
    [ "TScaler", "class_t_scaler.html", "class_t_scaler" ],
    [ "TScalerData", "class_t_scaler_data.html", "class_t_scaler_data" ],
    [ "TSingleDecay", "class_t_single_decay.html", "class_t_single_decay" ],
    [ "TSinglePeak", "class_t_single_peak.html", "class_t_single_peak" ],
    [ "TSingleton", "class_t_singleton.html", "class_t_singleton" ],
    [ "TSortingDiagnostics", "class_t_sorting_diagnostics.html", "class_t_sorting_diagnostics" ],
    [ "TSourceCalibration", "class_t_source_calibration.html", "class_t_source_calibration" ],
    [ "TSourceList", "class_t_source_list.html", "class_t_source_list" ],
    [ "TSourceTab", "class_t_source_tab.html", "class_t_source_tab" ],
    [ "TSRIM", "class_t_s_r_i_m.html", "class_t_s_r_i_m" ],
    [ "TSuppressed", "class_t_suppressed.html", "class_t_suppressed" ],
    [ "TTerminalLoop", "class_t_terminal_loop.html", "class_t_terminal_loop" ],
    [ "TTimeCal", "class_t_time_cal.html", "class_t_time_cal" ],
    [ "TTransientBits", "class_t_transient_bits.html", "class_t_transient_bits" ],
    [ "TTransition", "class_t_transition.html", "class_t_transition" ],
    [ "TUnpackedEvent", "class_t_unpacked_event.html", "class_t_unpacked_event" ],
    [ "TUnpackingLoop", "class_t_unpacking_loop.html", "class_t_unpacking_loop" ],
    [ "TUserSettings", "class_t_user_settings.html", "class_t_user_settings" ],
    [ "TVirtualDecay", "class_t_virtual_decay.html", "class_t_virtual_decay" ],
    [ "VirtualOdb", "class_virtual_odb.html", "class_virtual_odb" ]
];