GRSISort: bufferclean.cxx File Reference
bufferclean.cxx File Reference
#include "TMidasFile.h"
#include "TMidasEvent.h"
#include "TStopwatch.h"
#include "TSystem.h"
#include <map>
#include <iostream>
#include <fstream>
#include <chrono>
#include <utility>
Functions
Bool_t CheckEvent (const std::shared_ptr< TMidasEvent > &evt)
int main (int argc, char **argv)
void Write (const std::shared_ptr< TMidasEvent > &evt, TMidasFile *outfile)
Variables
UInt_t chanId_threshold = 100
Function Documentation
CheckEvent()
Bool_t CheckEvent (const std::shared_ptr< TMidasEvent > & evt)
Definition at line 17 of file bufferclean.cxx.
References chanId_threshold.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 111 of file bufferclean.cxx.
References CheckEvent(), DGREEN, DMAGENTA, DRED, HIDE_CURSOR, TMidasFile::Open(), RESET_COLOR, SHOW_CURSOR, and Write().
Write()
void Write (const std::shared_ptr< TMidasEvent > & evt, TMidasFile * outfile)
Definition at line 106 of file bufferclean.cxx.
References TMidasFile::FillBuffer().
Referenced by pygui.hist_tab.HistTab::_dump_to_tfile(), main(), and TAnalysisOptions::WriteToFile().
Variable Documentation
chanId_threshold
UInt_t chanId_threshold = 100
Definition at line 15 of file bufferclean.cxx.
Referenced by CheckEvent().