GRSISort: TTdrEvent Class Reference
TTdrEvent Class Reference
Sorting
Detailed Description
C++ class representing one tdr file.
Definition at line 31 of file TTdrEvent.h.
Public Member Functions
TTdrEvent ()
TTdrEvent (const TTdrEvent &)
~TTdrEvent () override
void Clear (Option_t *opt="") override
void Copy (TObject &) const override
char * GetData () override
uint32_t GetDataSize () const override
TTdrEventHeader & GetHeader ()
virtual uint32_t GetTimeStamp () const
virtual int GoodFrags ()
virtual void IncrementGoodFrags ()
TTdrEvent & operator= (const TTdrEvent &)
void Print (const char *option="") const override
void SetData (const std::vector< char > &buffer)
void SetHeader (const char *buffer)
int SwapBytes (bool) override
Protected Attributes
std::vector< char > fData
TTdrEventHeader fHeader
Private Attributes
int fGoodFrags {0}
Constructor & Destructor Documentation
TTdrEvent() [1/2]
TTdrEvent::TTdrEvent ()
default constructor
Definition at line 15 of file TTdrEvent.cxx.
References fData.
TTdrEvent() [2/2]
TTdrEvent::TTdrEvent (const TTdrEvent & rhs)
copy constructor
Definition at line 27 of file TTdrEvent.cxx.
References Copy().
~TTdrEvent()
TTdrEvent::~TTdrEvent () override
destructor
Definition at line 33 of file TTdrEvent.cxx.
References Clear().
Member Function Documentation
Clear()
void TTdrEvent::Clear (Option_t * opt = "") override
clear event for reuse
Definition at line 48 of file TTdrEvent.cxx.
References fData.
Referenced by ~TTdrEvent(), and operator=().
Copy()
void TTdrEvent::Copy (TObject & rhs) const override
copy helper
Definition at line 21 of file TTdrEvent.cxx.
References fData.
Referenced by TTdrEvent(), and operator=().
GetData()
char * TTdrEvent::GetData () override virtual
return pointer to the data buffer
Reimplemented from TRawEvent.
Definition at line 87 of file TTdrEvent.cxx.
References fData.
GetDataSize()
uint32_t TTdrEvent::GetDataSize () const override virtual
return the event size
Reimplemented from TRawEvent.
Definition at line 82 of file TTdrEvent.cxx.
References fData.
GetHeader()
TTdrEventHeader & TTdrEvent::GetHeader () inline
return pointer to the data buffer
Definition at line 48 of file TTdrEvent.h.
References fHeader.
GetTimeStamp()
virtual uint32_t TRawEvent::GetTimeStamp () const inline virtual inherited
return the event size
Reimplemented in TMidasEvent.
Definition at line 38 of file TRawEvent.h.
GoodFrags()
virtual int TRawEvent::GoodFrags () inline virtual inherited
returns number of good fragments parsed
Definition at line 47 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
IncrementGoodFrags()
virtual void TRawEvent::IncrementGoodFrags () inline virtual inherited
increments the number of good fragments parsed
Definition at line 48 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
operator=()
TTdrEvent & TTdrEvent::operator= (const TTdrEvent & rhs)
assignement operator
Definition at line 38 of file TTdrEvent.cxx.
References Clear(), and Copy().
Print()
void TTdrEvent::Print (const char * option = "") const override
show all event information
Print data held in this class.
Parameters
[in] option If 'a' (for "all") then the raw data will be printed out too.
Definition at line 93 of file TTdrEvent.cxx.
References fData.
SetData()
void TTdrEvent::SetData (const std::vector< char > & buffer)
set an externally allocated data buffer
Definition at line 74 of file TTdrEvent.cxx.
References fData, TTdrEventHeader::fDataLength, fHeader, and SwapBytes().
SetHeader()
void TTdrEvent::SetHeader (const char * buffer)
set an externally allocated header buffer
Set the TDR header from buffer (assumes that buffer contains at least 24 bytes worth of data)
Definition at line 54 of file TTdrEvent.cxx.
References TTdrEventHeader::fDataEndian, TTdrEventHeader::fDataLength, fHeader, TTdrEventHeader::fHeaderEndian, TTdrEventHeader::fSequence, TTdrEventHeader::fStream, and TTdrEventHeader::fTape.
SwapBytes()
int TTdrEvent::SwapBytes (bool) override virtual
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
Reimplemented from TRawEvent.
Definition at line 157 of file TTdrEvent.cxx.
Referenced by SetData().
Member Data Documentation
fData
std::vector<char> TTdrEvent::fData protected
event data buffer
Definition at line 58 of file TTdrEvent.h.
Referenced by TTdrEvent(), Clear(), Copy(), GetData(), GetDataSize(), Print(), and SetData().
fGoodFrags
int TRawEvent::fGoodFrags {0} private inherited
number of good fragments parsed
Definition at line 51 of file TRawEvent.h.
Referenced by TRawEvent::Clear(), TRawEvent::Copy(), TRawEvent::GoodFrags(), and TRawEvent::IncrementGoodFrags().
fHeader
TTdrEventHeader TTdrEvent::fHeader protected
event header
Definition at line 57 of file TTdrEvent.h.
Referenced by GetHeader(), SetData(), and SetHeader().