GRSISort: TGRSIFit Class Reference
TGRSIFit Class Reference abstract
Fitting & Analysis
Detailed Description
Definition at line 26 of file TGRSIFit.h.
Public Member Functions
~TGRSIFit ()
Bool_t AddToGlobalList (Bool_t yes=kTRUE) override
void Clear (Option_t *opt="") override
virtual void ClearParameters (Option_t *opt="")
void Copy (TObject &obj) const override
virtual void CopyParameters (TF1 *copy) const
virtual TH1 * GetHist () const
virtual Bool_t InitParams (TH1 *)=0
Bool_t IsGoodFit () const
void Print (Option_t *opt="") const override
virtual void SetHist (TH1 *hist)
Static Public Member Functions
static Bool_t AddToGlobalList (TF1 *func, Bool_t yes=kTRUE)
static const char * GetDefaultFitType ()
static void SetDefaultFitType (const char *fitType)
Protected Member Functions
TGRSIFit ()
TGRSIFit (const char *name, const char *formula, Double_t xmin=0, Double_t xmax=1)
template<class PtrObj , typename MemFn >
TGRSIFit (const char *name, const PtrObj &pointer, MemFn memFn, Double_t xmin, Double_t xmax, Int_t npar, const char *class_name, const char *fcn_name)
TGRSIFit (const char *name, const ROOT::Math::ParamFunctor &func, Double_t xmin=0, Double_t xmax=1, Int_t npar=0)
TGRSIFit (const char *name, Double_t xmin, Double_t xmax, Int_t npar)
TGRSIFit (const TGRSIFit &copy)
TGRSIFit (TGRSIFit &&) noexcept=default
void GoodFit (Bool_t flag=true)
Bool_t IsInitialized () const
TGRSIFit & operator= (const TGRSIFit &)=default
TGRSIFit & operator= (TGRSIFit &&) noexcept=default
void SetInitialized (Bool_t flag=true)
Private Attributes
Bool_t fGoodFitFlag {false}
TRef fHist
Bool_t fInitFlag {false}
Static Private Attributes
static TString fDefaultFitType
Constructor & Destructor Documentation
~TGRSIFit()
TGRSIFit::~TGRSIFit ()
Definition at line 15 of file TGRSIFit.cxx.
References AddToGlobalList().
TGRSIFit() [1/7]
TGRSIFit::TGRSIFit () protected
Definition at line 5 of file TGRSIFit.cxx.
References Clear().
TGRSIFit() [2/7]
TGRSIFit::TGRSIFit (const char * name, const char * formula, Double_t xmin = 0, Double_t xmax = 1) inline protected
Definition at line 32 of file TGRSIFit.h.
References Clear().
TGRSIFit() [3/7]
TGRSIFit::TGRSIFit (const char * name, Double_t xmin, Double_t xmax, Int_t npar) inline protected
Definition at line 33 of file TGRSIFit.h.
References Clear().
TGRSIFit() [4/7]
TGRSIFit::TGRSIFit (const char * name, const ROOT::Math::ParamFunctor & func, Double_t xmin = 0, Double_t xmax = 1, Int_t npar = 0) inline protected
Definition at line 34 of file TGRSIFit.h.
References Clear().
TGRSIFit() [5/7]
template<class PtrObj , typename MemFn > TGRSIFit::TGRSIFit (const char * name, const PtrObj & pointer, MemFn memFn, Double_t xmin, Double_t xmax, Int_t npar, const char * class_name, const char * fcn_name) inline protected
Definition at line 36 of file TGRSIFit.h.
References Clear().
TGRSIFit() [6/7]
TGRSIFit::TGRSIFit (const TGRSIFit & copy) protected
Definition at line 10 of file TGRSIFit.cxx.
References Copy().
TGRSIFit() [7/7]
TGRSIFit::TGRSIFit (TGRSIFit &&) protected default noexcept
Member Function Documentation
AddToGlobalList() [1/2]
Bool_t TGRSIFit::AddToGlobalList (Bool_t yes = kTRUE) override
Definition at line 62 of file TGRSIFit.cxx.
Referenced by TMultiPeak::TMultiPeak(), TMultiPeak::TMultiPeak(), TPeak::TPeak(), TPeak::TPeak(), ~TGRSIFit(), and TMultiPeak::Copy().
AddToGlobalList() [2/2]
Bool_t TGRSIFit::AddToGlobalList (TF1 * func, Bool_t yes = kTRUE) static
Definition at line 90 of file TGRSIFit.cxx.
Clear()
void TGRSIFit::Clear (Option_t * opt = "") override
Definition at line 36 of file TGRSIFit.cxx.
References fDefaultFitType, fGoodFitFlag, and fInitFlag.
Referenced by TGRSIFit(), TGRSIFit(), TGRSIFit(), TGRSIFit(), TGRSIFit(), TMultiPeak::Clear(), and TPeak::Clear().
ClearParameters()
void TGRSIFit::ClearParameters (Option_t * opt = "") virtual
Definition at line 43 of file TGRSIFit.cxx.
Copy()
void TGRSIFit::Copy (TObject & obj) const override
Definition at line 20 of file TGRSIFit.cxx.
References fGoodFitFlag, and fInitFlag.
Referenced by TGRSIFit(), TMultiPeak::Copy(), and TPeak::Copy().
CopyParameters()
void TGRSIFit::CopyParameters (TF1 * copy) const virtual
Definition at line 50 of file TGRSIFit.cxx.
Referenced by TMultiPeak::Fit().
GetDefaultFitType()
static const char * TGRSIFit::GetDefaultFitType () inline static
Definition at line 58 of file TGRSIFit.h.
References fDefaultFitType.
GetHist()
virtual TH1 * TGRSIFit::GetHist () const inline virtual
Definition at line 57 of file TGRSIFit.h.
References fHist.
Referenced by TPeak::Copy(), TPeak::DrawResiduals(), TMultiPeak::Fit(), TPeak::Fit(), TPeak::GetIntegralArea(), TPeak::GetIntegralAreaErr(), TPeak::GoodStatus(), TMultiPeak::InitParams(), and TPeak::InitParams().
GoodFit()
void TGRSIFit::GoodFit (Bool_t flag = true) inline protected
Definition at line 69 of file TGRSIFit.h.
References fGoodFitFlag.
InitParams()
virtual Bool_t TGRSIFit::InitParams (TH1 *) pure virtual
Implemented in TMultiPeak, and TPeak.
IsGoodFit()
Bool_t TGRSIFit::IsGoodFit () const inline
Definition at line 52 of file TGRSIFit.h.
References fGoodFitFlag.
IsInitialized()
Bool_t TGRSIFit::IsInitialized () const inline protected
Definition at line 67 of file TGRSIFit.h.
References fInitFlag.
Referenced by TMultiPeak::Fit(), and TPeak::Fit().
operator=() [1/2]
TGRSIFit & TGRSIFit::operator= (const TGRSIFit &) protected default
operator=() [2/2]
TGRSIFit & TGRSIFit::operator= (TGRSIFit &&) protected default noexcept
Print()
void TGRSIFit::Print (Option_t * opt = "") const override
Definition at line 27 of file TGRSIFit.cxx.
References fGoodFitFlag, and fInitFlag.
Referenced by TPeak::Print().
SetDefaultFitType()
static void TGRSIFit::SetDefaultFitType (const char * fitType) inline static
Definition at line 59 of file TGRSIFit.h.
References fDefaultFitType.
SetHist()
virtual void TGRSIFit::SetHist (TH1 * hist) inline virtual
Definition at line 53 of file TGRSIFit.h.
References fHist, and hist.
Referenced by TPeak::Copy(), TMultiPeak::Fit(), and TPeak::Fit().
SetInitialized()
void TGRSIFit::SetInitialized (Bool_t flag = true) inline protected
Definition at line 68 of file TGRSIFit.h.
References fInitFlag.
Referenced by TMultiPeak::InitParams(), and TPeak::InitParams().
Member Data Documentation
fDefaultFitType
TString TGRSIFit::fDefaultFitType static private
Definition at line 75 of file TGRSIFit.h.
Referenced by Clear(), GetDefaultFitType(), and SetDefaultFitType().
fGoodFitFlag
Bool_t TGRSIFit::fGoodFitFlag {false} private
Definition at line 73 of file TGRSIFit.h.
Referenced by Clear(), Copy(), GoodFit(), IsGoodFit(), and Print().
fHist
TRef TGRSIFit::fHist private
Definition at line 74 of file TGRSIFit.h.
Referenced by GetHist(), and SetHist().
fInitFlag
Bool_t TGRSIFit::fInitFlag {false} private
Definition at line 72 of file TGRSIFit.h.
Referenced by Clear(), Copy(), IsInitialized(), Print(), and SetInitialized().