GRSISort: TLaBrBgo Class Reference
TLaBrBgo Class Reference
Detectors
Detailed Description
Definition at line 12 of file TLaBrBgo.h.
Public Member Functions
TLaBrBgo ()
TLaBrBgo (const TLaBrBgo &)
TLaBrBgo (TLaBrBgo &&) noexcept=default
virtual ~TLaBrBgo ()=default
void AddFragment (const std::shared_ptr< const TFragment > &frag, TChannel *chan) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TBgoHit * GetBgoHit (const Int_t &index)
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
TLaBrBgoHit * GetLaBrBgoHit (const int &i) const
virtual Short_t GetMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TLaBrBgo & operator= (const TLaBrBgo &)
TLaBrBgo & operator= (TLaBrBgo &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (int DetNbr, int CryNbr=5, double distance=110.0)
Private Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static std::array< TVector3, 17 > fScintPosition
Constructor & Destructor Documentation
TLaBrBgo() [1/3]
TLaBrBgo::TLaBrBgo ()
Default ctor.
Definition at line 23 of file TLaBrBgo.cxx.
References TBgo::Clear().
TLaBrBgo() [2/3]
TLaBrBgo::TLaBrBgo (const TLaBrBgo & rhs)
Copy ctor.
Definition at line 29 of file TLaBrBgo.cxx.
References TBgo::Copy().
TLaBrBgo() [3/3]
TLaBrBgo::TLaBrBgo (TLaBrBgo &&) default noexcept
~TLaBrBgo()
virtual TLaBrBgo::~TLaBrBgo () virtual default
Member Function Documentation
AddFragment()
void TBgo::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual inherited
!
Reimplemented from TDetector.
Definition at line 153 of file TBgo.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TBgo::BuildHits () inline override virtual inherited
!
Reimplemented from TDetector.
Definition at line 35 of file TBgo.h.
Clear()
void TBgo::Clear (Option_t * opt = "all") override inherited
!
Clears the mother, and all of the hits
Definition at line 134 of file TBgo.cxx.
References TDetector::Clear().
Referenced by TBgo::TBgo(), TFippsBgo::TFippsBgo(), TFippsLaBrBgo::TFippsLaBrBgo(), TGriffinBgo::TGriffinBgo(), TIfinBgo::TIfinBgo(), TLaBrBgo(), TTdrCloverBgo::TTdrCloverBgo(), and TTdrTigressBgo::TTdrTigressBgo().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TBgo::Copy (TObject & rhs) const override inherited
!
Definition at line 126 of file TBgo.cxx.
References TDetector::Copy().
Referenced by TBgo::TBgo(), TFippsBgo::TFippsBgo(), TFippsLaBrBgo::TFippsLaBrBgo(), TGriffinBgo::TGriffinBgo(), TIfinBgo::TIfinBgo(), TLaBrBgo(), TTdrCloverBgo::TTdrCloverBgo(), TTdrTigressBgo::TTdrTigressBgo(), TBgo::operator=(), TFippsBgo::operator=(), TFippsLaBrBgo::operator=(), TGriffinBgo::operator=(), TIfinBgo::operator=(), operator=(), TTdrCloverBgo::operator=(), and TTdrTigressBgo::operator=().
GetBgoHit()
TBgoHit * TBgo::GetBgoHit (const Int_t & index) inline inherited
Definition at line 29 of file TBgo.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetLaBrBgoHit()
TLaBrBgoHit * TLaBrBgo::GetLaBrBgoHit (const int & i) const inline
Definition at line 21 of file TLaBrBgo.h.
References TDetector::GetHit().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
TVector3 TBgo::GetPosition (int DetNbr, int CryNbr = 5, double distance = 110.0) static inherited
!
Definition at line 165 of file TBgo.cxx.
References TBgo::fScintPosition.
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TLaBrBgo & TLaBrBgo::operator= (const TLaBrBgo & rhs)
!
Definition at line 35 of file TLaBrBgo.cxx.
References TBgo::Copy().
operator=() [2/2]
TLaBrBgo & TLaBrBgo::operator= (TLaBrBgo &&) default noexcept
Print() [1/2]
void TBgo::Print (Option_t * opt = "") const override inherited
!
Definition at line 140 of file TBgo.cxx.
References TBgo::Print().
Referenced by TBgo::Print().
Print() [2/2]
void TBgo::Print (std::ostream & out) const override virtual inherited
!
Reimplemented from TDetector.
Definition at line 145 of file TBgo.cxx.
References TDetector::GetMultiplicity().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fScintPosition
std::array< TVector3, 17 > TBgo::fScintPosition static private inherited
! Position of each BGO scintillator
Definition at line 36 of file TBgo.h.
Referenced by TBgo::GetPosition().