GRSISort: THILDetectorInformation Class Reference
THILDetectorInformation Class Reference
Sorting
Detailed Description
This Class is designed to store setup dependent information. It is used to store existence of detector systems, etc.
Definition at line 23 of file THILDetectorInformation.h.
Public Member Functions
THILDetectorInformation ()
~THILDetectorInformation () override
TEventBuildingLoop::EBuildMode BuildMode () const override
void Clear (Option_t *="") override
bool Eagle () const
bool EaglePulser () const
bool PinDiode () const
void Print (Option_t *opt="") const override
void Set () override
void SetEagle (bool flag=true)
void SetEaglePulser (bool flag=true)
void SetPinDiode (bool flag=true)
Private Attributes
bool fEagle {false}
bool fEaglePulser {false}
bool fPinDiode {false}
Constructor & Destructor Documentation
THILDetectorInformation()
THILDetectorInformation::THILDetectorInformation ()
Default ctor for THILDetectorInformation.
Definition at line 14 of file THILDetectorInformation.cxx.
~THILDetectorInformation()
THILDetectorInformation::~THILDetectorInformation () override default
Member Function Documentation
BuildMode()
TEventBuildingLoop::EBuildMode THILDetectorInformation::BuildMode () const override virtual
Set the detector information based on the available TChannels.
Select build mode based on available detectors
Reimplemented from TDetectorInformation.
Definition at line 23 of file THILDetectorInformation.cxx.
References TEventBuildingLoop::kSkip.
Clear()
void THILDetectorInformation::Clear (Option_t * = "") override
Definition at line 40 of file THILDetectorInformation.cxx.
References TDetectorInformation::Clear(), and fEagle.
Eagle()
bool THILDetectorInformation::Eagle () const inline
Definition at line 38 of file THILDetectorInformation.h.
References fEagle.
Referenced by Print().
EaglePulser()
bool THILDetectorInformation::EaglePulser () const inline
Definition at line 40 of file THILDetectorInformation.h.
References fEaglePulser.
Referenced by Print().
PinDiode()
bool THILDetectorInformation::PinDiode () const inline
Definition at line 39 of file THILDetectorInformation.h.
References fPinDiode.
Referenced by Print().
Print()
void THILDetectorInformation::Print (Option_t * opt = "") const override
Definition at line 28 of file THILDetectorInformation.cxx.
References Eagle(), EaglePulser(), and PinDiode().
Set()
void THILDetectorInformation::Set () override virtual
Sets the run info. This figures out what systems are available.
Reimplemented from TDetectorInformation.
Definition at line 50 of file THILDetectorInformation.cxx.
References TChannel::GetChannelMap(), THILMnemonic::kEagle, THILMnemonic::kEaglePulser, THILMnemonic::kPinDiode, SetEagle(), SetEaglePulser(), SetPinDiode(), and THILMnemonic::System().
SetEagle()
void THILDetectorInformation::SetEagle (bool flag = true) inline
Definition at line 34 of file THILDetectorInformation.h.
References fEagle.
Referenced by Set().
SetEaglePulser()
void THILDetectorInformation::SetEaglePulser (bool flag = true) inline
Definition at line 36 of file THILDetectorInformation.h.
References fEaglePulser.
Referenced by Set().
SetPinDiode()
void THILDetectorInformation::SetPinDiode (bool flag = true) inline
Definition at line 35 of file THILDetectorInformation.h.
References fPinDiode.
Referenced by Set().
Member Data Documentation
fEagle
bool THILDetectorInformation::fEagle {false} private
Definition at line 45 of file THILDetectorInformation.h.
Referenced by Clear(), Eagle(), and SetEagle().
fEaglePulser
bool THILDetectorInformation::fEaglePulser {false} private
Definition at line 47 of file THILDetectorInformation.h.
Referenced by EaglePulser(), and SetEaglePulser().
fPinDiode
bool THILDetectorInformation::fPinDiode {false} private
Definition at line 46 of file THILDetectorInformation.h.
Referenced by PinDiode(), and SetPinDiode().