GRSISort: TTAC Class Reference
TTAC Class Reference
Detectors
Detailed Description
The TTAC class defines the observables and algorithms used when analyzing TAC data. It includes detector positions, etc.
Definition at line 27 of file TTAC.h.
Public Member Functions
TTAC ()
TTAC (const TTAC &rhs)
TTAC (TTAC &&) noexcept=default
~TTAC () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TTACHit * GetTACHit (const int &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TTAC & operator= (const TTAC &)
TTAC & operator= (TTAC &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Private Attributes
std::vector< TDetectorHit * > fHits
Constructor & Destructor Documentation
TTAC() [1/3]
TTAC::TTAC ()
Definition at line 10 of file TTAC.cxx.
TTAC() [2/3]
TTAC::TTAC (const TTAC & rhs)
Definition at line 19 of file TTAC.cxx.
References TDetector::Copy().
TTAC() [3/3]
TTAC::TTAC (TTAC &&) default noexcept
~TTAC()
TTAC::~TTAC () override default
Member Function Documentation
AddFragment()
void TTAC::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 47 of file TTAC.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TEmma::BuildHits(), TSharc::BuildHits(), and TSharc2::BuildHits().
BuildHits()
void TTAC::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 41 of file TTAC.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TPaces::TPaces(), TSceptar::TSceptar(), TZeroDegree::TZeroDegree(), TSharc::Clear(), TSharc2::Clear(), TTrific::Clear(), TDescant::Clear(), TSiLi::Clear(), TTigress::Clear(), TTriFoil::Clear(), TTdrPlastic::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TEagle::Clear(), TBgo::Clear(), TSuppressed::Clear(), and TTdrSiLi::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override inherited
!
Definition at line 24 of file TDetector.cxx.
References TDetectorHit::Copy(), and TDetector::fHits.
Referenced by TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TSceptar::TSceptar(), TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree::TZeroDegree(), TDescant::Copy(), TEmma::Copy(), TPaces::Copy(), TRcmp::Copy(), TRF::Copy(), TS3::Copy(), TSharc::Copy(), TSharc2::Copy(), TSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TEagle::Copy(), TBgo::Copy(), TSuppressed::Copy(), TTdrSiLi::Copy(), TTriFoil::Copy(), TDetector::operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), TFippsTAC::operator=(), TGenericDetector::operator=(), TSceptar::operator=(), operator=(), TTdrPlastic::operator=(), TTip::operator=(), TZeroDegree::operator=(), and TDetector::operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetTACHit()
TTACHit * TTAC::GetTACHit (const int & i) const inline
Definition at line 36 of file TTAC.h.
References TDetector::GetHit().
Referenced by main().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), TSharc2::GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TTAC & TTAC::operator= (const TTAC & rhs)
!
Definition at line 28 of file TTAC.cxx.
References TDetector::Copy().
operator=() [2/2]
TTAC & TTAC::operator= (TTAC &&) default noexcept
Print() [1/2]
void TTAC::Print (Option_t * opt = "") const override
!
Definition at line 34 of file TTAC.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TTAC::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 40 of file TTAC.cxx.
References TDetector::GetMultiplicity().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().