GRSISort: TZeroDegreeHit Class Reference
TZeroDegreeHit Class Reference
Detectors
TZeroDegreeHit
This is class that contains the information about a ZDS hit. This class is used to find energy, time, etc.
Definition at line 27 of file TZeroDegreeHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TZeroDegreeHit ()
TZeroDegreeHit (const TFragment &frag)
TZeroDegreeHit (const TZeroDegreeHit &)
~TZeroDegreeHit () override
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &x)
bool AnalyzeWaveform ()
virtual void AppendTimeStamp (const Long64_t &x)
Int_t CalculateCfd (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolationSteps)
Int_t CalculateCfdAndMonitor (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolationSteps, std::vector< Short_t > &monitor)
std::vector< Short_t > CalculateCfdMonitor (double attenuation, int delay, int halfsmoothingwindow)
std::vector< Int_t > CalculatePartialSum ()
std::vector< Short_t > CalculateSmoothedWaveform (unsigned int halfsmoothingwindow)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool) const override
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
Float_t GetCfd () const override
std::vector< short > & GetCfdMonitor ()
TChannel * GetChannel () const
virtual Short_t GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Int_t GetFilterPattern () const
virtual Short_t GetKValue () const
const char * GetName () const override
std::vector< int > & GetPartialSum ()
virtual TVector3 GetPosition () const
virtual TVector3 GetPosition (Double_t) const
EPpgPattern GetPPGStatus () const
Int_t GetRemainder () const
virtual Int_t GetSegment () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool InFilter (Int_t)
bool operator< (const TDetectorHit &rhs) const
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &x)
virtual void SetCfd (const Int_t &x)
virtual void SetCfd (const uint32_t &x)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &en) const
void SetFilterPattern (const int &x)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &x)
void SetWaveform (const std::vector< Short_t > &x)
bool TestHitBit (EBitFlag flag) const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Protected Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
Float_t fCharge {0.}
Short_t fKValue {0}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Protected Attributes
static TVector3 fBeamDirection
Private Attributes
std::vector< short > fCfdMonitor
TChannel * fChannel {nullptr}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Int_t fFilter {0}
std::vector< int > fPartialSum
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
#include <TZeroDegreeHit.h>
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 52 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 79 of file TDetectorHit.h.
Constructor & Destructor Documentation
TZeroDegreeHit() [1/3]
TZeroDegreeHit::TZeroDegreeHit ()
Definition at line 17 of file TZeroDegreeHit.cxx.
~TZeroDegreeHit()
TZeroDegreeHit::~TZeroDegreeHit () override default
TZeroDegreeHit() [2/3]
TZeroDegreeHit::TZeroDegreeHit (const TZeroDegreeHit & rhs)
Definition at line 42 of file TZeroDegreeHit.cxx.
References Clear(), and Copy().
TZeroDegreeHit() [3/3]
TZeroDegreeHit::TZeroDegreeHit (const TFragment & frag)
Definition at line 28 of file TZeroDegreeHit.cxx.
References AnalyzeWaveform(), TDetectorHit::CopyWave(), TGRSIOptions::Get(), and TDetectorHit::GetWaveform().
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TGriffinHit, TFippsHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 188 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & x) inline inherited
!
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AnalyzeWaveform()
bool TZeroDegreeHit::AnalyzeWaveform ()
!
Calculates the cfd time from the waveform
Definition at line 119 of file TZeroDegreeHit.cxx.
References CalculateCfd(), CalculatePartialSum(), TDetectorHit::fWaveform, TDetectorHit::SetCfd(), and TDetectorHit::SetCharge().
Referenced by TZeroDegreeHit().
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 123 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
CalculateCfd()
Int_t TZeroDegreeHit::CalculateCfd (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolationSteps)
!
Used when calculating the CFD from the waveform
Definition at line 157 of file TZeroDegreeHit.cxx.
References CalculateCfdAndMonitor().
Referenced by AnalyzeWaveform().
CalculateCfdAndMonitor()
Int_t TZeroDegreeHit::CalculateCfdAndMonitor (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolationSteps, std::vector< Short_t > & monitor)
!
Used when calculating the CFD from the waveform
Definition at line 166 of file TZeroDegreeHit.cxx.
References CalculateSmoothedWaveform(), TGRSIOptions::Debug(), TDetectorHit::fCfd, fCfdMonitor, TDetectorHit::fWaveform, and TGRSIOptions::Get().
Referenced by CalculateCfd().
CalculateCfdMonitor()
std::vector< Short_t > TZeroDegreeHit::CalculateCfdMonitor (double attenuation, int delay, int halfsmoothingwindow)
!
Used when calculating the CFD from the waveform
Definition at line 252 of file TZeroDegreeHit.cxx.
References CalculateSmoothedWaveform(), and TDetectorHit::fWaveform.
CalculatePartialSum()
std::vector< Int_t > TZeroDegreeHit::CalculatePartialSum ()
!
Definition at line 277 of file TZeroDegreeHit.cxx.
References fPartialSum, TDetectorHit::fWaveform, and TGRSIOptions::Get().
Referenced by AnalyzeWaveform().
CalculateSmoothedWaveform()
std::vector< Short_t > TZeroDegreeHit::CalculateSmoothedWaveform (unsigned int halfsmoothingwindow)
!
Used when calculating the CFD from the waveform
Definition at line 232 of file TZeroDegreeHit.cxx.
References TDetectorHit::fWaveform.
Referenced by CalculateCfdAndMonitor(), and CalculateCfdMonitor().
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 149 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TTACHit::TempCorrectedCharge(), and TFippsTACHit::TempCorrectedCharge().
Clear()
void TZeroDegreeHit::Clear (Option_t * opt = "") override
!
Clears the ZeroDegreeHit
Definition at line 92 of file TZeroDegreeHit.cxx.
References TDetectorHit::Clear(), fCfdMonitor, fFilter, and fPartialSum.
Referenced by TZeroDegreeHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 180 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 175 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 100 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 219 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TZeroDegreeHit::Copy (TObject & rhs) const override
!
Copies a TZeroDegreeHit
Definition at line 52 of file TZeroDegreeHit.cxx.
References TDetectorHit::Copy(), TDetectorHit::CopyWave(), fCfdMonitor, fFilter, fPartialSum, and TGRSIOptions::Get().
Referenced by TZeroDegreeHit(), and Copy().
Copy() [2/2]
void TZeroDegreeHit::Copy (TObject & obj, bool waveform) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 64 of file TZeroDegreeHit.cxx.
References Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 134 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit(), TDescantHit::Copy(), TTipHit::Copy(), Copy(), TDetectorHit::Copy(), TDescantHit::Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), and TTdrTigressHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharcHit::GetBackAddress(), TSharcHit::GetFrontAddress(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharcHit::GetPadAddress(), TEagleHit::Print(), TPinDiodeHit::Print(), TFragment::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TGriffinBgoHit, TGriffinHit, TLaBrBgoHit, TTigressHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TIfinBgoHit, TIfinHit, TBgoHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 167 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 186 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TTigressHit::GetDoppler(), and TSiLiHit::GetDoppler().
GetCfd()
Float_t TZeroDegreeHit::GetCfd () const override virtual
!
special function for TZeroDegreeHit to return CFD after mapping out the high bits which are the remainder between the 125 MHz data and the 100 MHz timestamp clock
Reimplemented from TDetectorHit.
Definition at line 79 of file TZeroDegreeHit.cxx.
References TDetectorHit::fCfd.
GetCfdMonitor()
std::vector< short > & TZeroDegreeHit::GetCfdMonitor () inline
Definition at line 45 of file TZeroDegreeHit.h.
References fCfdMonitor.
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 152 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
Short_t TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 224 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 69 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by TSiLiHit::TSiLiHit(), ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharcHit::GetBackCharge(), TSharcHit::GetFrontCharge(), TSharcHit::GetPadCharge(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TCSM::MakeHit(), TTigressHit::Print(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 210 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TGriffinHit::Print(), TFippsHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 267 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 192 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TDetectorHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TSharc::GetDeadLayerThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TDescantHit::GetPosition(), TTrificHit::GetPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TDescantHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TSceptarHit::GetPosition(), TSharcHit::GetPosition(), TEagleHit::GetPosition(), TPinDiodeHit::GetPosition(), TFippsLaBrHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TSharcHit::Print(), TTACHit::Print(), TTipHit::Print(), TTrificHit::Print(), Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), and PromptCoincidence().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Reimplemented in TCSMHit, TSharcHit, and TSiLiHit.
Definition at line 84 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFippsHit::CompareEnergy(), TGriffinHit::CompareEnergy(), TIfinHit::CompareEnergy(), TTdrCloverHit::CompareEnergy(), TTdrTigressHit::CompareEnergy(), TTigressHit::CompareEnergy(), TDetectorHit::CompareEnergy(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), ExampleFragmentSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TSharcHit::GetDeltaBackE(), TSharcHit::GetDeltaE(), TSharcHit::GetDeltaFrontE(), TTigressHit::GetDoppler(), TSharcHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TSharcHit::GetPadE(), TDetectorHit::GetTime(), TFragment::GetTZero(), MakeAnalysisHistograms(), MakeGRIFFINEnergyHsts(), TDetectorHit::operator<(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), and TTigressHit::SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 107 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFilterPattern()
Int_t TZeroDegreeHit::GetFilterPattern () const inline
!
Definition at line 44 of file TZeroDegreeHit.h.
References fFilter.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 150 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 166 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by EfficiencyHelper::EndOfSort(), TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPartialSum()
std::vector< int > & TZeroDegreeHit::GetPartialSum () inline
Definition at line 46 of file TZeroDegreeHit.h.
References fPartialSum.
GetPosition() [1/2]
virtual TVector3 TDetectorHit::GetPosition () const inline virtual inherited
!
Reimplemented in TDescantHit, TEmmaHit, TGriffinHit, TLaBrHit, TPacesHit, TSceptarHit, TSharcHit, TSiLiHit, TTipHit, TTrificHit, TEagleHit, TPinDiodeHit, TFippsHit, TFippsLaBrHit, TIfinHit, TTdrCloverHit, TTdrPlasticHit, TTdrSiLiHit, and TTdrTigressHit.
Definition at line 139 of file TDetectorHit.h.
Referenced by TTigressHit::GetDoppler(), TS3Hit::GetPhi(), TS3Hit::GetTheta(), and TTigressHit::Print().
GetPosition() [2/2]
virtual TVector3 TDetectorHit::GetPosition (Double_t) const inline virtual inherited
!
Reimplemented in TDescantHit, TLaBrHit, TPacesHit, TSceptarHit, TSharcHit, TSiLiHit, TEagleHit, TPinDiodeHit, TFippsLaBrHit, TTdrPlasticHit, TTdrSiLiHit, TTigressHit, TEmmaHit, and TCSMHit.
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::GetPosition().
Referenced by TDetectorHit::GetPosition().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 251 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetRemainder()
Int_t TZeroDegreeHit::GetRemainder () const
returns the remainder between 100 MHz/10ns timestamp and 125 MHz/8 ns data in ns
Definition at line 86 of file TZeroDegreeHit.cxx.
References TDetectorHit::fCfd.
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 201 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TGriffinBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TSharcHit::GetBackStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and TSiLiHit::SumHit().
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 56 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleTreeHelper::Exec(), TSiLi::fCoincidenceTime(), ExampleTreeSelector::FillHistograms(), TSharcHit::GetDeltaBackT(), TSharcHit::GetDeltaFrontT(), TSharcHit::GetDeltaT(), TSharcHit::GetPadT(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TDetectorHit::Print(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TTACHit::TempCorrectedCharge(), TFippsTACHit::TempCorrectedCharge(), TimeRandom(), and TimeRandom().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 283 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 142 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TTigressHit::Print(), TEagleHit::Print(), and TFragment::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 233 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by DirectoryHelper::Exec(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), and TGriffinHit::Print().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 242 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 151 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 107 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TFragment::Print(), and TPulseAnalyzer::SetData().
InFilter()
bool TZeroDegreeHit::InFilter (Int_t)
!
check if the desired filter is in wanted filter; return the answer;
Definition at line 72 of file TZeroDegreeHit.cxx.
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 195 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 194 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 197 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 196 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 93 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
Print() [1/2]
void TZeroDegreeHit::Print (Option_t * opt = "") const override
!
Prints the ZeroDegreeHit. Returns: Detector Energy Time
Definition at line 101 of file TZeroDegreeHit.cxx.
References Print().
Referenced by ExampleEventHelper::EndOfSort(), and Print().
Print() [2/2]
void TZeroDegreeHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 110 of file TZeroDegreeHit.cxx.
References TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), and TDetectorHit::GetTime().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), TEmma::BuildHits(), and TTigressHit::SumHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & x) inline virtual inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & en) const inline inherited
Definition at line 125 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetFilterPattern()
void TZeroDegreeHit::SetFilterPattern (const int & x) inline
!
Definition at line 41 of file TZeroDegreeHit.h.
References fFilter.
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 290 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 131 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 122 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TEmma::BuildHits().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & x) inline inherited
!
Definition at line 120 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), and TTdrPlasticHit::TTdrPlasticHit().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 201 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), and TSiLiHit::GetEnergy().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} protected inherited
address of the the channel in the DAQ.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), TFragment::GetSharcMesyBoard(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static protected inherited
Definition at line 223 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable protected inherited
Definition at line 222 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TTdrCloverHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TTdrCloverHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TTdrCloverHit::NPileUps(), TTdrCloverHit::PUHit(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), and TDetectorHit::TestHitBit().
fCfd
Float_t TDetectorHit::fCfd {0} protected inherited
CFD time of the Hit.
Definition at line 207 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TDescantHit::CalculateCfdAndMonitor(), CalculateCfdAndMonitor(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDescantHit::GetCfd(), GetCfd(), TDescantHit::GetRemainder(), GetRemainder(), TTigressHit::GetTimeToTrigger(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fCfdMonitor
std::vector<short> TZeroDegreeHit::fCfdMonitor private
Definition at line 36 of file TZeroDegreeHit.h.
Referenced by CalculateCfdAndMonitor(), Clear(), Copy(), and GetCfdMonitor().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 217 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} protected inherited
charge collected from the hit
Definition at line 205 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 216 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fFilter
Int_t TZeroDegreeHit::fFilter {0} private
Definition at line 35 of file TZeroDegreeHit.h.
Referenced by Clear(), Copy(), GetFilterPattern(), and SetFilterPattern().
fKValue
Short_t TDetectorHit::fKValue {0} protected inherited
integration value.
Definition at line 206 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), and TDetectorHit::SetKValue().
fPartialSum
std::vector<int> TZeroDegreeHit::fPartialSum private
Definition at line 37 of file TZeroDegreeHit.h.
Referenced by CalculatePartialSum(), Clear(), Copy(), and GetPartialSum().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 214 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fTime
Double_t TDetectorHit::fTime {0.} mutable protected inherited
! Calibrated Time of the hit
Definition at line 210 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} protected inherited
Timestamp given to hit in ns.
Definition at line 208 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), TTigressHit::GetTimeToTrigger(), TGriffinHit::Print(), and TDetectorHit::SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform protected inherited
Definition at line 209 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), CalculateCfdMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), CalculateSmoothedWaveform(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::SetWaveform().