GRSISort: TTdrDetectorInformation Class Reference
TTdrDetectorInformation Class Reference
Sorting
#include <TTdrDetectorInformation.h>
Public Member Functions
TTdrDetectorInformation ()
~TTdrDetectorInformation () override
TEventBuildingLoop::EBuildMode BuildMode () const override
void Clear (Option_t *="") override
void Print (Option_t *opt="") const override
void Set () override
void SetTdrClover (bool flag=true)
void SetTdrPlastic (bool flag=true)
void SetTdrSiLi (bool flag=true)
void SetTdrTigress (bool flag=true)
bool TdrClover () const
bool TdrPlastic () const
bool TdrSiLi () const
bool TdrTigress () const
Private Attributes
bool fTdrClover {false}
bool fTdrPlastic {false}
bool fTdrSiLi {false}
bool fTdrTigress {false}
Detailed Description
This Class is designed to store setup dependent information. It is used to store existence of detector systems, etc.
Definition at line 23 of file TTdrDetectorInformation.h.
Constructor & Destructor Documentation
TTdrDetectorInformation()
TTdrDetectorInformation::TTdrDetectorInformation ()
Default ctor for TTdrDetectorInformation.
Definition at line 14 of file TTdrDetectorInformation.cxx.
~TTdrDetectorInformation()
TTdrDetectorInformation::~TTdrDetectorInformation () override default
Member Function Documentation
BuildMode()
TEventBuildingLoop::EBuildMode TTdrDetectorInformation::BuildMode () const override virtual
Set the detector information based on the available TChannels.
Select build mode based on available detectors
Reimplemented from TDetectorInformation.
Definition at line 23 of file TTdrDetectorInformation.cxx.
References TEventBuildingLoop::kTimestamp.
Clear()
void TTdrDetectorInformation::Clear (Option_t * = "") override virtual
Reimplemented from TDetectorInformation.
Definition at line 41 of file TTdrDetectorInformation.cxx.
References TDetectorInformation::Clear(), fTdrClover, fTdrPlastic, fTdrSiLi, and fTdrTigress.
Print()
void TTdrDetectorInformation::Print (Option_t * opt = "") const override virtual
Reimplemented from TDetectorInformation.
Definition at line 28 of file TTdrDetectorInformation.cxx.
References TdrClover(), TdrPlastic(), TdrSiLi(), and TdrTigress().
Set()
void TTdrDetectorInformation::Set () override virtual
Sets the run info. This figures out what systems are available.
Reimplemented from TDetectorInformation.
Definition at line 54 of file TTdrDetectorInformation.cxx.
References TChannel::GetChannelMap(), TTdrMnemonic::kTdrClover, TTdrMnemonic::kTdrPlastic, TTdrMnemonic::kTdrSiLi, TTdrMnemonic::kTdrTigress, SetTdrClover(), SetTdrPlastic(), SetTdrSiLi(), SetTdrTigress(), and TTdrMnemonic::System().
SetTdrClover()
void TTdrDetectorInformation::SetTdrClover (bool flag = true) inline
Definition at line 34 of file TTdrDetectorInformation.h.
References fTdrClover.
Referenced by Set().
SetTdrPlastic()
void TTdrDetectorInformation::SetTdrPlastic (bool flag = true) inline
Definition at line 37 of file TTdrDetectorInformation.h.
References fTdrPlastic.
Referenced by Set().
SetTdrSiLi()
void TTdrDetectorInformation::SetTdrSiLi (bool flag = true) inline
Definition at line 36 of file TTdrDetectorInformation.h.
References fTdrSiLi.
Referenced by Set().
SetTdrTigress()
void TTdrDetectorInformation::SetTdrTigress (bool flag = true) inline
Definition at line 35 of file TTdrDetectorInformation.h.
References fTdrTigress.
Referenced by Set().
TdrClover()
bool TTdrDetectorInformation::TdrClover () const inline
Definition at line 39 of file TTdrDetectorInformation.h.
References fTdrClover.
Referenced by Print().
TdrPlastic()
bool TTdrDetectorInformation::TdrPlastic () const inline
Definition at line 42 of file TTdrDetectorInformation.h.
References fTdrPlastic.
Referenced by Print().
TdrSiLi()
bool TTdrDetectorInformation::TdrSiLi () const inline
Definition at line 41 of file TTdrDetectorInformation.h.
References fTdrSiLi.
Referenced by Print().
TdrTigress()
bool TTdrDetectorInformation::TdrTigress () const inline
Definition at line 40 of file TTdrDetectorInformation.h.
References fTdrTigress.
Referenced by Print().
Member Data Documentation
fTdrClover
bool TTdrDetectorInformation::fTdrClover {false} private
Definition at line 47 of file TTdrDetectorInformation.h.
Referenced by Clear(), SetTdrClover(), and TdrClover().
fTdrPlastic
bool TTdrDetectorInformation::fTdrPlastic {false} private
Definition at line 50 of file TTdrDetectorInformation.h.
Referenced by Clear(), SetTdrPlastic(), and TdrPlastic().
fTdrSiLi
bool TTdrDetectorInformation::fTdrSiLi {false} private
Definition at line 49 of file TTdrDetectorInformation.h.
Referenced by Clear(), SetTdrSiLi(), and TdrSiLi().
fTdrTigress
bool TTdrDetectorInformation::fTdrTigress {false} private
Definition at line 48 of file TTdrDetectorInformation.h.
Referenced by Clear(), SetTdrTigress(), and TdrTigress().