GRSISort: TEpicsFrag Class Reference
TEpicsFrag Class Reference
Sorting
This Class should contain all the information found in Epics (scaler) events.
Definition at line 31 of file TEpicsFrag.h.
Public Member Functions
TEpicsFrag ()
~TEpicsFrag () override
void Clear (Option_t *opt="") override
float GetData (const unsigned int &i)
int GetSize ()
void Print (Option_t *opt="") const override
Static Public Member Functions
static void AddEpicsVariable (const char *name)
static void BuildScalerMap ()
static void BuildScalerMap (TTree *tree)
static std::string GetEpicsVariableName (const int &i)
static TEpicsFrag * GetScalerAtTime (Long64_t time)
static void PrintScalerMap ()
static void PrintVariableNames ()
static void SetEpicsNameList (const std::vector< std::string > &name_vec)
Public Attributes
Int_t fDaqId
time_t fDaqTimeStamp
std::vector< float > fData
std::vector< std::string > fName
Static Private Attributes
static std::vector< std::string > fNameList
static std::map< Long64_t, TEpicsFrag > fScalerMap
static Long64_t fSmallestTime = std::numeric_limits<Long64_t>::max()
#include <TEpicsFrag.h>
Constructor & Destructor Documentation
TEpicsFrag()
TEpicsFrag::TEpicsFrag ()
Definition at line 31 of file TEpicsFrag.cxx.
References fDaqId, and fDaqTimeStamp.
~TEpicsFrag()
TEpicsFrag::~TEpicsFrag () override default
Member Function Documentation
AddEpicsVariable()
void TEpicsFrag::AddEpicsVariable (const char * name) static
Definition at line 72 of file TEpicsFrag.cxx.
References fNameList.
BuildScalerMap() [1/2]
void TEpicsFrag::BuildScalerMap () static
Definition at line 125 of file TEpicsFrag.cxx.
References BuildScalerMap().
Referenced by BuildScalerMap(), GetScalerAtTime(), and PrintScalerMap().
BuildScalerMap() [2/2]
void TEpicsFrag::BuildScalerMap (TTree * tree) static
Definition at line 103 of file TEpicsFrag.cxx.
References DRED, fDaqTimeStamp, fScalerMap, fSmallestTime, TSingleton< TRunInfo >::Get(), RESET_COLOR, and TRunInfo::RunStart().
Clear()
void TEpicsFrag::Clear (Option_t * opt = "") override
!
Definition at line 40 of file TEpicsFrag.cxx.
References fDaqId, fDaqTimeStamp, fData, and fName.
GetData()
float TEpicsFrag::GetData (const unsigned int & i) inline
Definition at line 43 of file TEpicsFrag.h.
References fData.
GetEpicsVariableName()
std::string TEpicsFrag::GetEpicsVariableName (const int & i) static
Definition at line 77 of file TEpicsFrag.cxx.
References DRED, and fNameList.
GetScalerAtTime()
TEpicsFrag * TEpicsFrag::GetScalerAtTime (Long64_t time) static
Definition at line 135 of file TEpicsFrag.cxx.
References BuildScalerMap(), DRED, fScalerMap, fSmallestTime, and RESET_COLOR.
GetSize()
int TEpicsFrag::GetSize () inline
Definition at line 42 of file TEpicsFrag.h.
References fData.
Print()
void TEpicsFrag::Print (Option_t * opt = "") const override
!
Definition at line 50 of file TEpicsFrag.cxx.
References fDaqId, fDaqTimeStamp, fData, and fName.
PrintScalerMap()
void TEpicsFrag::PrintScalerMap () static
Definition at line 150 of file TEpicsFrag.cxx.
References BuildScalerMap(), DRED, fScalerMap, and RESET_COLOR.
PrintVariableNames()
void TEpicsFrag::PrintVariableNames () static
Definition at line 87 of file TEpicsFrag.cxx.
References fNameList.
SetEpicsNameList()
void TEpicsFrag::SetEpicsNameList (const std::vector< std::string > & name_vec) static
Definition at line 95 of file TEpicsFrag.cxx.
References fNameList.
Member Data Documentation
fDaqId
Int_t TEpicsFrag::fDaqId
Definition at line 37 of file TEpicsFrag.h.
Referenced by TEpicsFrag(), Clear(), and Print().
fDaqTimeStamp
time_t TEpicsFrag::fDaqTimeStamp
Definition at line 36 of file TEpicsFrag.h.
Referenced by TEpicsFrag(), BuildScalerMap(), Clear(), and Print().
fData
std::vector<float> TEpicsFrag::fData
The data in the scaler.
Definition at line 39 of file TEpicsFrag.h.
Referenced by Clear(), GetData(), GetSize(), and Print().
fName
std::vector<std::string> TEpicsFrag::fName
The name of the scaler.
Definition at line 40 of file TEpicsFrag.h.
Referenced by Clear(), and Print().
fNameList
std::vector< std::string > TEpicsFrag::fNameList static private
Definition at line 67 of file TEpicsFrag.h.
Referenced by AddEpicsVariable(), GetEpicsVariableName(), PrintVariableNames(), and SetEpicsNameList().
fScalerMap
std::map< Long64_t, TEpicsFrag > TEpicsFrag::fScalerMap static private
Definition at line 68 of file TEpicsFrag.h.
Referenced by BuildScalerMap(), GetScalerAtTime(), and PrintScalerMap().
fSmallestTime
Long64_t TEpicsFrag::fSmallestTime = std::numeric_limits<Long64_t>::max() static private
Definition at line 69 of file TEpicsFrag.h.
Referenced by BuildScalerMap(), and GetScalerAtTime().
GRSISort () Reference Guide Generated on Mon May 13 2024 16:00:06.