GRSISort: TCalibrationGraph Class Reference
TCalibrationGraph Class Reference
Detailed Description
Definition at line 19 of file TCalibrationGraph.h.
Public Member Functions
TCalibrationGraph ()=default
TCalibrationGraph (const TCalibrationGraph &)=default
TCalibrationGraph (TCalibrationGraph &&) noexcept=default
TCalibrationGraph (TCalibrationGraphSet *parent, const int &size, const bool &isResidual=false)
TCalibrationGraph (TCalibrationGraphSet *parent, TGraphErrors *graph)
~TCalibrationGraph ()=default
bool IsResidual () const
void IsResidual (bool val)
TCalibrationGraph & operator= (const TCalibrationGraph &)=default
TCalibrationGraph & operator= (TCalibrationGraph &&) noexcept=default
Int_t RemovePoint () override
Private Attributes
bool fIsResidual {false}
TCalibrationGraphSet * fParent {nullptr}
Constructor & Destructor Documentation
TCalibrationGraph() [1/5]
TCalibrationGraph::TCalibrationGraph () default
TCalibrationGraph() [2/5]
TCalibrationGraph::TCalibrationGraph (TCalibrationGraphSet * parent, const int & size, const bool & isResidual = false) inline
Definition at line 22 of file TCalibrationGraph.h.
TCalibrationGraph() [3/5]
TCalibrationGraph::TCalibrationGraph (TCalibrationGraphSet * parent, TGraphErrors * graph) inline
Definition at line 23 of file TCalibrationGraph.h.
~TCalibrationGraph()
TCalibrationGraph::~TCalibrationGraph () default
TCalibrationGraph() [4/5]
TCalibrationGraph::TCalibrationGraph (const TCalibrationGraph &) default
TCalibrationGraph() [5/5]
TCalibrationGraph::TCalibrationGraph (TCalibrationGraph &&) default noexcept
Member Function Documentation
IsResidual() [1/2]
bool TCalibrationGraph::IsResidual () const inline
Definition at line 34 of file TCalibrationGraph.h.
References fIsResidual.
IsResidual() [2/2]
void TCalibrationGraph::IsResidual (bool val) inline
Definition at line 33 of file TCalibrationGraph.h.
References fIsResidual.
operator=() [1/2]
TCalibrationGraph & TCalibrationGraph::operator= (const TCalibrationGraph &) default
operator=() [2/2]
TCalibrationGraph & TCalibrationGraph::operator= (TCalibrationGraph &&) default noexcept
RemovePoint()
Int_t TCalibrationGraph::RemovePoint () override
Definition at line 12 of file TCalibrationGraph.cxx.
References fIsResidual, fParent, kBasicFlow, TCalibrationGraphSet::RemovePoint(), TCalibrationGraphSet::RemoveResidualPoint(), and TCalibrationGraphSet::VerboseLevel().
Member Data Documentation
fIsResidual
bool TCalibrationGraph::fIsResidual {false} private
flag to indicate that this graph is for residuals
Definition at line 42 of file TCalibrationGraph.h.
Referenced by IsResidual(), IsResidual(), and RemovePoint().
fParent
TCalibrationGraphSet* TCalibrationGraph::fParent {nullptr} private
pointer to the set this graph belongs to
Definition at line 41 of file TCalibrationGraph.h.
Referenced by RemovePoint().