GRSISort: ArgParseItem Class Reference
ArgParseItem Class Reference abstract
Detailed Description
Base class used to parse an individual item. Most methods are implemented in the templated ArgParseConfig<T>
Definition at line 22 of file ArgParser.h.
Public Member Functions
ArgParseItem (ArgParseItem &&) noexcept=default
ArgParseItem (bool firstPass)
ArgParseItem (const ArgParseItem &)=default
virtual ~ArgParseItem ()=default
virtual std::string flag_name () const =0
bool is_present () const
virtual bool is_required () const =0
virtual bool matches (const std::string &flag) const =0
virtual int num_arguments () const =0
ArgParseItem & operator= (ArgParseItem &&) noexcept=default
ArgParseItem & operator= (const ArgParseItem &)=default
void parse (const std::string &name, const std::vector< std::string > &arguments, bool firstPass, bool ignore_num_arguments=false)
virtual void parse_item (const std::vector< std::string > &arguments)=0
virtual std::string printable (int description_column, int *chars_before_desc) const =0
Private Attributes
bool fFirstPass
bool fPresent {false}
Constructor & Destructor Documentation
ArgParseItem() [1/3]
ArgParseItem::ArgParseItem (bool firstPass) inline explicit
Definition at line 24 of file ArgParser.h.
ArgParseItem() [2/3]
ArgParseItem::ArgParseItem (const ArgParseItem &) default
ArgParseItem() [3/3]
ArgParseItem::ArgParseItem (ArgParseItem &&) default noexcept
~ArgParseItem()
virtual ArgParseItem::~ArgParseItem () virtual default
Member Function Documentation
flag_name()
virtual std::string ArgParseItem::flag_name () const pure virtual
Implemented in ArgParseConfig< T >, and ArgParseConfig< bool >.
is_present()
bool ArgParseItem::is_present () const inline
Definition at line 35 of file ArgParser.h.
References fPresent.
is_required()
virtual bool ArgParseItem::is_required () const pure virtual
Implemented in ArgParseConfig< T >, and ArgParseConfig< bool >.
matches()
virtual bool ArgParseItem::matches (const std::string & flag) const pure virtual
Implemented in ArgParseConfig< T >, and ArgParseConfig< bool >.
num_arguments()
virtual int ArgParseItem::num_arguments () const pure virtual
Implemented in ArgParseConfigT< T >, and ArgParseConfigT< bool >.
Referenced by ArgParser::handle_long_flag(), ArgParser::handle_short_flag(), parse(), and ArgParseConfig< T >::printable().
operator=() [1/2]
ArgParseItem & ArgParseItem::operator= (ArgParseItem &&) default noexcept
operator=() [2/2]
ArgParseItem & ArgParseItem::operator= (const ArgParseItem &) default
parse()
void ArgParseItem::parse (const std::string & name, const std::vector< std::string > & arguments, bool firstPass, bool ignore_num_arguments = false) inline
Definition at line 38 of file ArgParser.h.
References fFirstPass, fPresent, num_arguments(), and parse_item().
Referenced by ArgParser::handle_default_option(), ArgParser::handle_long_flag(), ArgParser::handle_short_flag(), and ArgParser::parse_file().
parse_item()
virtual void ArgParseItem::parse_item (const std::vector< std::string > & arguments) pure virtual
Implemented in ArgParseConfigT< T >, and ArgParseConfigT< bool >.
Referenced by parse().
printable()
virtual std::string ArgParseItem::printable (int description_column, int * chars_before_desc) const pure virtual
Implemented in ArgParseConfig< T >, and ArgParseConfig< bool >.
Referenced by ArgParser::print().
Member Data Documentation
fFirstPass
bool ArgParseItem::fFirstPass private
Definition at line 64 of file ArgParser.h.
Referenced by parse().
fPresent
bool ArgParseItem::fPresent {false} private
Definition at line 63 of file ArgParser.h.
Referenced by is_present(), and parse().