GRSISort: TCSMHit Class Reference
TCSMHit Class Reference
Detectors
Detailed Description
Definition at line 25 of file TCSMHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TCSMHit ()
TCSMHit (const TCSMHit &)=default
TCSMHit (TCSMHit &&) noexcept=default
~TCSMHit () override=default
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &val)
virtual void AppendTimeStamp (const Long64_t &val)
virtual Float_t Charge () const
void Clear (Option_t *="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
virtual void Copy (TObject &, bool copywave) const
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual int GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
Double_t GetDdE_dx () const
Double_t GetDEnergy () const
virtual Int_t GetDetector () const
UShort_t GetDetectorNumber () const
Int_t GetDHorizontalCFD () const
Float_t GetDHorizontalCharge () const
Double_t GetDHorizontalEnergy () const
Int_t GetDHorizontalStrip () const
Double_t GetDHorizontalTime () const
TVector3 GetDPosition () const
Double_t GetDthickness () const
Double_t GetDTime () const
Int_t GetDVerticalCFD () const
Float_t GetDVerticalCharge () const
Double_t GetDVerticalEnergy () const
Int_t GetDVerticalStrip () const
Double_t GetDVerticalTime () const
Double_t GetEEnergy () const
Int_t GetEHorizontalCFD () const
Float_t GetEHorizontalCharge () const
Double_t GetEHorizontalEnergy () const
Int_t GetEHorizontalStrip () const
Double_t GetEHorizontalTime () const
Double_t GetEnergy (Option_t *="") const override
virtual Double_t GetEnergyNonlinearity (double energy) const
TVector3 GetEPosition () const
Double_t GetETime () const
Int_t GetEVerticalCFD () const
Float_t GetEVerticalCharge () const
Double_t GetEVerticalEnergy () const
Int_t GetEVerticalStrip () const
Double_t GetEVerticalTime () const
virtual Short_t GetKValue () const
const char * GetName () const override
TVector3 GetPosition (Double_t=0) const override
virtual TVector3 GetPosition () const
EPpgPattern GetPPGStatus () const
virtual Int_t GetSegment () const
Double_t GetTime (const ETimeFlag &=ETimeFlag::kAll, Option_t *="") const override
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool IsEmpty () const
bool operator< (const TDetectorHit &rhs) const
TCSMHit & operator= (const TCSMHit &)=default
TCSMHit & operator= (TCSMHit &&) noexcept=default
void Print (Option_t *="") const override
void Print (std::ostream &out) const override
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &val)
virtual void SetCfd (const Int_t &val)
virtual void SetCfd (const uint32_t &val)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
void SetDetectorNumber (const Int_t &tempnum)
void SetDHorizontalCFD (const Int_t tempd)
void SetDHorizontalCharge (const Float_t temp)
void SetDHorizontalEnergy (const Double_t tempd)
void SetDHorizontalStrip (const Int_t temp)
void SetDHorizontalTime (const Int_t tempd)
void SetDPosition (const TVector3 &tempp)
void SetDVerticalCFD (const Int_t tempd)
void SetDVerticalCharge (const Float_t temp)
void SetDVerticalEnergy (const Double_t tempd)
void SetDVerticalStrip (const Int_t temp)
void SetDVerticalTime (const Int_t tempd)
void SetEHorizontalCFD (const Int_t tempd)
void SetEHorizontalCharge (const Float_t temp)
void SetEHorizontalEnergy (const Double_t tempd)
void SetEHorizontalStrip (const Int_t temp)
void SetEHorizontalTime (const Int_t tempd)
Double_t SetEnergy (const double &energy) const
void SetEPosition (const TVector3 &tempp)
void SetEVerticalCFD (const Int_t tempd)
void SetEVerticalCharge (const Float_t temp)
void SetEVerticalEnergy (const Double_t tempd)
void SetEVerticalStrip (const Int_t temp)
void SetEVerticalTime (const Int_t tempd)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &val)
void SetWaveform (const std::vector< Short_t > &val)
bool TestHitBit (EBitFlag flag) const
virtual size_t WaveSize () const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Private Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
TChannel * fChannel {nullptr}
Float_t fCharge {0.}
Long64_t fCycleTimeStamp {0}
UShort_t fDetectorNumber
TVector3 fDPosition
Double_t fEnergy {0.}
TVector3 fEPosition
Int_t fHorDCfd
Float_t fHorDCharge
Double_t fHorDEnergy
Short_t fHorDStrip
Double_t fHorDTime
Int_t fHorECfd
Float_t fHorECharge
Double_t fHorEEnergy
Short_t fHorEStrip
Double_t fHorETime
Short_t fKValue {0}
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
Int_t fVerDCfd
Float_t fVerDCharge
Double_t fVerDEnergy
Short_t fVerDStrip
Double_t fVerDTime
Int_t fVerECfd
Float_t fVerECharge
Double_t fVerEEnergy
Short_t fVerEStrip
Double_t fVerETime
std::vector< Short_t > fWaveform
Static Private Attributes
static TVector3 fBeamDirection
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 50 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 72 of file TDetectorHit.h.
Constructor & Destructor Documentation
TCSMHit() [1/3]
TCSMHit::TCSMHit ()
Definition at line 3 of file TCSMHit.cxx.
References Clear().
TCSMHit() [2/3]
TCSMHit::TCSMHit (const TCSMHit &) default
TCSMHit() [3/3]
TCSMHit::TCSMHit (TCSMHit &&) default noexcept
~TCSMHit()
TCSMHit::~TCSMHit () override default
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TFippsHit, TGriffinHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 184 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & val) inline inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 145 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TFippsTACHit::TempCorrectedCharge(), and TTACHit::TempCorrectedCharge().
Clear()
void TCSMHit::Clear (Option_t * = "") override
!
Definition at line 8 of file TCSMHit.cxx.
References fDetectorNumber, fDPosition, fEPosition, fHorDCfd, fHorDCharge, fHorDEnergy, fHorDStrip, fHorDTime, fHorECfd, fHorECharge, fHorEEnergy, fHorEStrip, fHorETime, fVerDCfd, fVerDCharge, fVerDEnergy, fVerDStrip, fVerDTime, fVerECfd, fVerECharge, fVerEEnergy, fVerEStrip, and fVerETime.
Referenced by TCSMHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 176 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 171 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 94 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TBgoHit::TBgoHit(), TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 213 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TDetectorHit::Copy (TObject & rhs) const override inherited
!
Definition at line 105 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TDetectorHit::fBitFlags, TDetectorHit::fCfd, TDetectorHit::fChannel, TDetectorHit::fCharge, TDetectorHit::fCycleTimeStamp, TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::fPPGStatus, TDetectorHit::fTime, and TDetectorHit::fTimeStamp.
Referenced by TAriesHit::TAriesHit(), TDemandHit::TDemandHit(), TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TGriffinHit::TGriffinHit(), TRcmpHit::TRcmpHit(), TRcmpHit::TRcmpHit(), TS3Hit::TS3Hit(), TSceptarHit::TSceptarHit(), TSiLiHit::TSiLiHit(), TTigressHit::TTigressHit(), TTipHit::TTipHit(), TZeroDegreeHit::TZeroDegreeHit(), TAriesHit::Copy(), TBgoHit::Copy(), TDemandHit::Copy(), TDescantHit::Copy(), TDetectorHit::Copy(), TEagleHit::Copy(), TEmmaHit::Copy(), TFippsHit::Copy(), TFippsLaBrHit::Copy(), TFippsTACHit::Copy(), TGriffinHit::Copy(), TIfinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TPinDiodeHit::Copy(), TRcmpHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TSiLiHit::Copy(), TTACHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), TTdrSiLiHit::Copy(), TTdrTigressHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TTigressHit::CopyFragment(), TSharc2Hit::SetBack(), TSharcHit::SetBack(), TSharc2Hit::SetFront(), TSharcHit::SetFront(), TSharc2Hit::SetPad(), and TSharcHit::SetPad().
Copy() [2/2]
void TDetectorHit::Copy (TObject & rhs, bool copywave) const virtual inherited
!
Reimplemented in TAriesHit, TBgoHit, TDemandHit, TDescantHit, TEagleHit, TEmmaHit, TFippsHit, TFippsLaBrHit, TFippsTACHit, TGriffinHit, TIfinHit, TLaBrHit, TPacesHit, TPinDiodeHit, TRcmpHit, TS3Hit, TSceptarHit, TSharc2Hit, TSharcHit, TSiLiHit, TTACHit, TTdrCloverHit, TTdrPlasticHit, TTdrTigressHit, TTigressHit, TTipHit, TTrificHit, and TZeroDegreeHit.
Definition at line 128 of file TDetectorHit.cxx.
References TDetectorHit::Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 123 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TBgoHit::TBgoHit(), TDemandHit::TDemandHit(), TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TAriesHit::Copy(), TDemandHit::Copy(), TDemandHit::Copy(), TDescantHit::Copy(), TDescantHit::Copy(), TDetectorHit::Copy(), TEagleHit::Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TPinDiodeHit::Copy(), TRcmpHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), TTdrTigressHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), and TZeroDegreeHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 143 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharc2Hit::GetBackAddress(), TSharcHit::GetBackAddress(), TSharc2Hit::GetFrontAddress(), TSharcHit::GetFrontAddress(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharc2Hit::GetPadAddress(), TSharcHit::GetPadAddress(), TFragment::GetSharcMesyBoard(), TEagleHit::Print(), TFragment::Print(), TPinDiodeHit::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TBgoHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TGriffinBgoHit, TGriffinHit, TIfinBgoHit, TIfinHit, TLaBrBgoHit, TRcmpHit, TTdrCloverHit, TTdrTigressHit, and TTigressHit.
Definition at line 163 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 182 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TSiLiHit::GetDoppler(), and TTigressHit::GetDoppler().
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Reimplemented in TDescantHit, and TZeroDegreeHit.
Definition at line 142 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), DefaultSuppression(), TFragment::Get4GCfd(), TDescantHit::GetCfd(), TZeroDegreeHit::GetCfd(), TDescantHit::GetRemainder(), TZeroDegreeHit::GetRemainder(), TSharc2Hit::GetSomeTime(), TSharcHit::GetSomeTime(), TDetectorHit::GetTime(), TTigressHit::GetTimeToTrigger(), TEagleHit::Print(), TFragment::Print(), and TTigressHit::SumHit().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 148 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TFippsTACHit::GetTempCorrectedEnergy(), TTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
int TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 218 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 58 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharc2Hit::GetBackCharge(), TSharcHit::GetBackCharge(), TSharc2Hit::GetFrontCharge(), TSharcHit::GetFrontCharge(), TSharc2Hit::GetPadCharge(), TSharcHit::GetPadCharge(), TFippsTACHit::GetTempCorrectedCharge(), TTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TFragment::Print(), and TTigressHit::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 204 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TFippsHit::GetPosition(), TGriffinHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TTigress::GetPosition(), TFippsHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 261 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDdE_dx()
Double_t TCSMHit::GetDdE_dx () const inline
Definition at line 114 of file TCSMHit.h.
References GetDEnergy(), and GetDthickness().
GetDEnergy()
Double_t TCSMHit::GetDEnergy () const
!
Definition at line 80 of file TCSMHit.cxx.
References GetDetectorNumber(), GetDHorizontalEnergy(), GetDHorizontalStrip(), GetDVerticalEnergy(), and GetDVerticalStrip().
Referenced by GetDdE_dx(), and GetEnergy().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 186 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultAddback(), DefaultFippsAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinAddback(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TBgoHit::GetArrayNumber(), TDetectorHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TSharc2::GetDeadLayerThickness(), TSharc::GetDeadLayerThickness(), TSharc2::GetDetectorThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TAriesHit::GetPosition(), TDemand::GetPosition(), TDescantHit::GetPosition(), TDescantHit::GetPosition(), TEagleHit::GetPosition(), TFippsHit::GetPosition(), TFippsLaBrHit::GetPosition(), TGriffinHit::GetPosition(), TIfinHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TPinDiodeHit::GetPosition(), TSceptarHit::GetPosition(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTdrTigressHit::GetPosition(), TTigress::GetPosition(), TTrificHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TAriesHit::Print(), TDemandHit::Print(), TDescantHit::Print(), TEagleHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TPinDiodeHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TSharc2Hit::Print(), TSharcHit::Print(), TTACHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), and PromptCoincidence().
GetDetectorNumber()
UShort_t TCSMHit::GetDetectorNumber () const inline
!
Definition at line 85 of file TCSMHit.h.
References fDetectorNumber.
Referenced by GetDEnergy(), GetDthickness(), GetEEnergy(), TCSM::OldBuilddEE(), and Print().
GetDHorizontalCFD()
Int_t TCSMHit::GetDHorizontalCFD () const inline
!
Definition at line 108 of file TCSMHit.h.
References fHorDCfd.
Referenced by Print().
GetDHorizontalCharge()
Float_t TCSMHit::GetDHorizontalCharge () const inline
!
Definition at line 90 of file TCSMHit.h.
References fHorDCharge.
Referenced by Print().
GetDHorizontalEnergy()
Double_t TCSMHit::GetDHorizontalEnergy () const inline
Definition at line 80 of file TCSMHit.h.
References fHorDEnergy.
Referenced by GetDEnergy(), and Print().
GetDHorizontalStrip()
Int_t TCSMHit::GetDHorizontalStrip () const inline
!
Definition at line 102 of file TCSMHit.h.
References fHorDStrip.
Referenced by GetDEnergy(), GetDthickness(), and Print().
GetDHorizontalTime()
Double_t TCSMHit::GetDHorizontalTime () const inline
!
Definition at line 96 of file TCSMHit.h.
References fHorDTime.
GetDPosition()
TVector3 TCSMHit::GetDPosition () const inline
!
Definition at line 112 of file TCSMHit.h.
References fDPosition.
Referenced by TCSM::MakedEE(), TCSM::OldBuilddEE(), and Print().
GetDthickness()
Double_t TCSMHit::GetDthickness () const
Definition at line 41 of file TCSMHit.cxx.
References GetDetectorNumber(), GetDHorizontalStrip(), and GetDVerticalStrip().
Referenced by GetDdE_dx().
GetDTime()
Double_t TCSMHit::GetDTime () const inline
!
Definition at line 83 of file TCSMHit.h.
References fVerDTime.
GetDVerticalCFD()
Int_t TCSMHit::GetDVerticalCFD () const inline
!
Definition at line 109 of file TCSMHit.h.
References fVerDCfd.
Referenced by Print().
GetDVerticalCharge()
Float_t TCSMHit::GetDVerticalCharge () const inline
!
Definition at line 91 of file TCSMHit.h.
References fVerDCharge.
Referenced by Print().
GetDVerticalEnergy()
Double_t TCSMHit::GetDVerticalEnergy () const inline
!
Definition at line 81 of file TCSMHit.h.
References fVerDEnergy.
Referenced by GetDEnergy(), and Print().
GetDVerticalStrip()
Int_t TCSMHit::GetDVerticalStrip () const inline
!
Definition at line 103 of file TCSMHit.h.
References fVerDStrip.
Referenced by GetDEnergy(), GetDthickness(), and Print().
GetDVerticalTime()
Double_t TCSMHit::GetDVerticalTime () const inline
!
Definition at line 97 of file TCSMHit.h.
References fVerDTime.
GetEEnergy()
Double_t TCSMHit::GetEEnergy () const
!
Definition at line 149 of file TCSMHit.cxx.
References GetDetectorNumber(), GetEHorizontalEnergy(), GetEHorizontalStrip(), GetEVerticalEnergy(), and GetEVerticalStrip().
Referenced by GetEnergy().
GetEHorizontalCFD()
Int_t TCSMHit::GetEHorizontalCFD () const inline
!
Definition at line 105 of file TCSMHit.h.
References fHorECfd.
Referenced by Print().
GetEHorizontalCharge()
Float_t TCSMHit::GetEHorizontalCharge () const inline
!
Definition at line 87 of file TCSMHit.h.
References fHorECharge.
Referenced by Print().
GetEHorizontalEnergy()
Double_t TCSMHit::GetEHorizontalEnergy () const inline
Definition at line 75 of file TCSMHit.h.
References fHorEEnergy.
Referenced by GetEEnergy(), and Print().
GetEHorizontalStrip()
Int_t TCSMHit::GetEHorizontalStrip () const inline
!
Definition at line 99 of file TCSMHit.h.
References fHorEStrip.
Referenced by GetEEnergy(), and Print().
GetEHorizontalTime()
Double_t TCSMHit::GetEHorizontalTime () const inline
!
Definition at line 93 of file TCSMHit.h.
References fHorETime.
GetEnergy()
Double_t TCSMHit::GetEnergy (Option_t * = "") const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 118 of file TCSMHit.h.
References GetDEnergy(), and GetEEnergy().
Referenced by TCSM::MakeHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 96 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetEPosition()
TVector3 TCSMHit::GetEPosition () const inline
!
Definition at line 111 of file TCSMHit.h.
References fEPosition.
Referenced by TCSM::MakedEE(), TCSM::OldBuilddEE(), and Print().
GetETime()
Double_t TCSMHit::GetETime () const inline
!
Definition at line 78 of file TCSMHit.h.
References fHorETime.
GetEVerticalCFD()
Int_t TCSMHit::GetEVerticalCFD () const inline
!
Definition at line 106 of file TCSMHit.h.
References fVerECfd.
Referenced by Print().
GetEVerticalCharge()
Float_t TCSMHit::GetEVerticalCharge () const inline
!
Definition at line 88 of file TCSMHit.h.
References fVerECharge.
Referenced by Print().
GetEVerticalEnergy()
Double_t TCSMHit::GetEVerticalEnergy () const inline
!
Definition at line 76 of file TCSMHit.h.
References fVerEEnergy.
Referenced by GetEEnergy(), and Print().
GetEVerticalStrip()
Int_t TCSMHit::GetEVerticalStrip () const inline
!
Definition at line 100 of file TCSMHit.h.
References fVerEStrip.
Referenced by GetEEnergy(), and Print().
GetEVerticalTime()
Double_t TCSMHit::GetEVerticalTime () const inline
!
Definition at line 94 of file TCSMHit.h.
References fVerETime.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 146 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TTACHit::GetTempCorrectedEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 160 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPosition() [1/2]
TVector3 TCSMHit::GetPosition (Double_t = 0) const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 117 of file TCSMHit.h.
References fDPosition.
GetPosition() [2/2]
virtual TVector3 TDetectorHit::GetPosition () const inline virtual inherited
!
Reimplemented in TAriesHit, TDemandHit, TDescantHit, TEagleHit, TEmmaHit, TFippsHit, TFippsLaBrHit, TGriffinHit, TIfinHit, TLaBrHit, TPacesHit, TPinDiodeHit, TSceptarHit, TSharc2Hit, TSharcHit, TSiLiHit, TTdrCloverHit, TTdrPlasticHit, TTdrSiLiHit, TTdrTigressHit, TTipHit, and TTrificHit.
Definition at line 135 of file TDetectorHit.h.
Referenced by TTigressHit::GetDoppler(), TS3Hit::GetPhi(), TS3Hit::GetTheta(), and TTigressHit::Print().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 245 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 195 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TSharc2Hit::GetBackStrip(), TSharcHit::GetBackStrip(), TSharc2Hit::GetFrontStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and TSiLiHit::SumHit().
GetTime()
Double_t TCSMHit::GetTime (const ETimeFlag & = ETimeFlag::kAll, Option_t * = "") const inline override virtual
Returns fVerDTime.
Reimplemented from TDetectorHit.
Definition at line 120 of file TCSMHit.h.
References fVerDTime.
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 277 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), TTigressHit::GetTimeToTrigger(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TEagleHit::Print(), TFragment::Print(), TGriffinHit::Print(), and TTigressHit::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 227 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by ComptonPolarimetryHelper::Coincident(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), TGriffinHit::Print(), and ComptonPolarimetryHelper::TimeDiff().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 236 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 102 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TFragment::Print(), and TPulseAnalyzer::SetData().
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 191 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEmpty()
bool TCSMHit::IsEmpty () const
Definition at line 225 of file TCSMHit.cxx.
References fDetectorNumber, fHorDCfd, fHorDCharge, fHorDEnergy, fHorDStrip, fHorDTime, fHorECfd, fHorECharge, fHorEEnergy, fHorEStrip, fHorETime, fVerDCfd, fVerDCharge, fVerDEnergy, fVerDStrip, fVerDTime, fVerECfd, fVerECharge, fVerEEnergy, fVerEStrip, and fVerETime.
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 190 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 193 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 192 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 88 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
operator=() [1/2]
TCSMHit & TCSMHit::operator= (const TCSMHit &) default
operator=() [2/2]
TCSMHit & TCSMHit::operator= (TCSMHit &&) default noexcept
Print() [1/2]
void TCSMHit::Print (Option_t * = "") const override
!
Definition at line 197 of file TCSMHit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TCSMHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 202 of file TCSMHit.cxx.
References GetDetectorNumber(), GetDHorizontalCFD(), GetDHorizontalCharge(), GetDHorizontalEnergy(), GetDHorizontalStrip(), GetDPosition(), GetDVerticalCFD(), GetDVerticalCharge(), GetDVerticalEnergy(), GetDVerticalStrip(), GetEHorizontalCFD(), GetEHorizontalCharge(), GetEHorizontalEnergy(), GetEHorizontalStrip(), GetEPosition(), GetEVerticalCFD(), GetEVerticalCharge(), GetEVerticalEnergy(), and GetEVerticalStrip().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 109 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), and TTigressHit::SumHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & val) inline virtual inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TEagleHit::TEagleHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 111 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 112 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetDetectorNumber()
void TCSMHit::SetDetectorNumber (const Int_t & tempnum) inline
!
Definition at line 125 of file TCSMHit.h.
References fDetectorNumber.
SetDHorizontalCFD()
void TCSMHit::SetDHorizontalCFD (const Int_t tempd) inline
!
Definition at line 142 of file TCSMHit.h.
References fHorDCfd.
SetDHorizontalCharge()
void TCSMHit::SetDHorizontalCharge (const Float_t temp) inline
!
Definition at line 130 of file TCSMHit.h.
References fHorDCharge.
SetDHorizontalEnergy()
void TCSMHit::SetDHorizontalEnergy (const Double_t tempd) inline
Definition at line 154 of file TCSMHit.h.
References fHorDEnergy.
SetDHorizontalStrip()
void TCSMHit::SetDHorizontalStrip (const Int_t temp) inline
!
Definition at line 136 of file TCSMHit.h.
References fHorDStrip.
SetDHorizontalTime()
void TCSMHit::SetDHorizontalTime (const Int_t tempd) inline
!
Definition at line 148 of file TCSMHit.h.
References fHorDTime.
SetDPosition()
void TCSMHit::SetDPosition (const TVector3 & tempp) inline
!
Definition at line 152 of file TCSMHit.h.
References fDPosition.
SetDVerticalCFD()
void TCSMHit::SetDVerticalCFD (const Int_t tempd) inline
!
Definition at line 143 of file TCSMHit.h.
References fVerDCfd.
SetDVerticalCharge()
void TCSMHit::SetDVerticalCharge (const Float_t temp) inline
!
Definition at line 131 of file TCSMHit.h.
References fVerDCharge.
SetDVerticalEnergy()
void TCSMHit::SetDVerticalEnergy (const Double_t tempd) inline
Definition at line 155 of file TCSMHit.h.
References fVerDEnergy.
SetDVerticalStrip()
void TCSMHit::SetDVerticalStrip (const Int_t temp) inline
!
Definition at line 137 of file TCSMHit.h.
References fVerDStrip.
SetDVerticalTime()
void TCSMHit::SetDVerticalTime (const Int_t tempd) inline
!
Definition at line 149 of file TCSMHit.h.
References fVerDTime.
SetEHorizontalCFD()
void TCSMHit::SetEHorizontalCFD (const Int_t tempd) inline
!
Definition at line 139 of file TCSMHit.h.
References fHorECfd.
SetEHorizontalCharge()
void TCSMHit::SetEHorizontalCharge (const Float_t temp) inline
!
Definition at line 127 of file TCSMHit.h.
References fHorECharge.
SetEHorizontalEnergy()
void TCSMHit::SetEHorizontalEnergy (const Double_t tempd) inline
Definition at line 157 of file TCSMHit.h.
References fHorEEnergy.
SetEHorizontalStrip()
void TCSMHit::SetEHorizontalStrip (const Int_t temp) inline
!
Definition at line 133 of file TCSMHit.h.
References fHorEStrip.
Referenced by TCSM::CombineHits().
SetEHorizontalTime()
void TCSMHit::SetEHorizontalTime (const Int_t tempd) inline
!
Definition at line 145 of file TCSMHit.h.
References fHorETime.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & energy) const inline inherited
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetEPosition()
void TCSMHit::SetEPosition (const TVector3 & tempp) inline
!
Definition at line 151 of file TCSMHit.h.
References fEPosition.
SetEVerticalCFD()
void TCSMHit::SetEVerticalCFD (const Int_t tempd) inline
!
Definition at line 140 of file TCSMHit.h.
References fVerECfd.
SetEVerticalCharge()
void TCSMHit::SetEVerticalCharge (const Float_t temp) inline
!
Definition at line 128 of file TCSMHit.h.
References fVerECharge.
SetEVerticalEnergy()
void TCSMHit::SetEVerticalEnergy (const Double_t tempd) inline
Definition at line 158 of file TCSMHit.h.
References fVerEEnergy.
SetEVerticalStrip()
void TCSMHit::SetEVerticalStrip (const Int_t temp) inline
!
Definition at line 134 of file TCSMHit.h.
References fVerEStrip.
SetEVerticalTime()
void TCSMHit::SetEVerticalTime (const Int_t tempd) inline
!
Definition at line 146 of file TCSMHit.h.
References fVerETime.
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 284 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TTdrCloverHit::SetTdrCloverFlag(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 110 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 127 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TEagleHit::TEagleHit(), and TPinDiodeHit::TPinDiodeHit().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & val) inline inherited
!
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TTdrPlasticHit::TTdrPlasticHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 187 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TTdrCloverHit::NPileUps(), and TTdrCloverHit::PUHit().
WaveSize()
virtual size_t TDetectorHit::WaveSize () const inline virtual inherited
!
Definition at line 103 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), and TZeroDegreeHit::CalculateSmoothedWaveform().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} private inherited
address of the the channel in the DAQ.
Definition at line 196 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static private inherited
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable private inherited
Definition at line 211 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TDetectorHit::SetHitBit(), and TDetectorHit::TestHitBit().
fCfd
Float_t TDetectorHit::fCfd {0} private inherited
CFD time of the Hit.
Definition at line 199 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 208 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} private inherited
charge collected from the hit
Definition at line 197 of file TDetectorHit.h.
Referenced by TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 207 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fDetectorNumber
UShort_t TCSMHit::fDetectorNumber private
Definition at line 64 of file TCSMHit.h.
Referenced by Clear(), GetDetectorNumber(), IsEmpty(), and SetDetectorNumber().
fDPosition
TVector3 TCSMHit::fDPosition private
Definition at line 55 of file TCSMHit.h.
Referenced by Clear(), GetDPosition(), GetPosition(), and SetDPosition().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fEPosition
TVector3 TCSMHit::fEPosition private
Definition at line 62 of file TCSMHit.h.
Referenced by Clear(), GetEPosition(), and SetEPosition().
fHorDCfd
Int_t TCSMHit::fHorDCfd private
Definition at line 37 of file TCSMHit.h.
Referenced by Clear(), GetDHorizontalCFD(), IsEmpty(), and SetDHorizontalCFD().
fHorDCharge
Float_t TCSMHit::fHorDCharge private
Definition at line 36 of file TCSMHit.h.
Referenced by Clear(), GetDHorizontalCharge(), IsEmpty(), and SetDHorizontalCharge().
fHorDEnergy
Double_t TCSMHit::fHorDEnergy private
Definition at line 51 of file TCSMHit.h.
Referenced by Clear(), GetDHorizontalEnergy(), IsEmpty(), and SetDHorizontalEnergy().
fHorDStrip
Short_t TCSMHit::fHorDStrip private
Definition at line 35 of file TCSMHit.h.
Referenced by Clear(), GetDHorizontalStrip(), IsEmpty(), and SetDHorizontalStrip().
fHorDTime
Double_t TCSMHit::fHorDTime private
Definition at line 53 of file TCSMHit.h.
Referenced by Clear(), GetDHorizontalTime(), IsEmpty(), and SetDHorizontalTime().
fHorECfd
Int_t TCSMHit::fHorECfd private
Definition at line 45 of file TCSMHit.h.
Referenced by Clear(), GetEHorizontalCFD(), IsEmpty(), and SetEHorizontalCFD().
fHorECharge
Float_t TCSMHit::fHorECharge private
Definition at line 44 of file TCSMHit.h.
Referenced by Clear(), GetEHorizontalCharge(), IsEmpty(), and SetEHorizontalCharge().
fHorEEnergy
Double_t TCSMHit::fHorEEnergy private
Definition at line 57 of file TCSMHit.h.
Referenced by Clear(), GetEHorizontalEnergy(), IsEmpty(), and SetEHorizontalEnergy().
fHorEStrip
Short_t TCSMHit::fHorEStrip private
Definition at line 43 of file TCSMHit.h.
Referenced by Clear(), GetEHorizontalStrip(), IsEmpty(), and SetEHorizontalStrip().
fHorETime
Double_t TCSMHit::fHorETime private
Definition at line 59 of file TCSMHit.h.
Referenced by Clear(), GetEHorizontalTime(), GetETime(), IsEmpty(), and SetEHorizontalTime().
fKValue
Short_t TDetectorHit::fKValue {0} private inherited
integration value.
Definition at line 198 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), and TDetectorHit::SetKValue().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fTime
Double_t TDetectorHit::fTime {0.} mutable private inherited
! Calibrated Time of the hit
Definition at line 202 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} private inherited
Timestamp given to hit in ns.
Definition at line 200 of file TDetectorHit.h.
Referenced by TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), and TDetectorHit::SetTimeStamp().
fVerDCfd
Int_t TCSMHit::fVerDCfd private
Definition at line 41 of file TCSMHit.h.
Referenced by Clear(), GetDVerticalCFD(), IsEmpty(), and SetDVerticalCFD().
fVerDCharge
Float_t TCSMHit::fVerDCharge private
Definition at line 40 of file TCSMHit.h.
Referenced by Clear(), GetDVerticalCharge(), IsEmpty(), and SetDVerticalCharge().
fVerDEnergy
Double_t TCSMHit::fVerDEnergy private
Definition at line 52 of file TCSMHit.h.
Referenced by Clear(), GetDVerticalEnergy(), IsEmpty(), and SetDVerticalEnergy().
fVerDStrip
Short_t TCSMHit::fVerDStrip private
Definition at line 39 of file TCSMHit.h.
Referenced by Clear(), GetDVerticalStrip(), IsEmpty(), and SetDVerticalStrip().
fVerDTime
Double_t TCSMHit::fVerDTime private
Definition at line 54 of file TCSMHit.h.
Referenced by Clear(), GetDTime(), GetDVerticalTime(), GetTime(), IsEmpty(), and SetDVerticalTime().
fVerECfd
Int_t TCSMHit::fVerECfd private
Definition at line 49 of file TCSMHit.h.
Referenced by Clear(), GetEVerticalCFD(), IsEmpty(), and SetEVerticalCFD().
fVerECharge
Float_t TCSMHit::fVerECharge private
Definition at line 48 of file TCSMHit.h.
Referenced by Clear(), GetEVerticalCharge(), IsEmpty(), and SetEVerticalCharge().
fVerEEnergy
Double_t TCSMHit::fVerEEnergy private
Definition at line 58 of file TCSMHit.h.
Referenced by Clear(), GetEVerticalEnergy(), IsEmpty(), and SetEVerticalEnergy().
fVerEStrip
Short_t TCSMHit::fVerEStrip private
Definition at line 47 of file TCSMHit.h.
Referenced by Clear(), GetEVerticalStrip(), IsEmpty(), and SetEVerticalStrip().
fVerETime
Double_t TCSMHit::fVerETime private
Definition at line 60 of file TCSMHit.h.
Referenced by Clear(), GetEVerticalTime(), IsEmpty(), and SetEVerticalTime().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform private inherited
Definition at line 201 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), TDetectorHit::SetWaveform(), and TDetectorHit::WaveSize().