GRSISort: TSourceCalibration Class Reference
TSourceCalibration Class Reference
Calibration
Detailed Description
Definition at line 207 of file TSourceCalibration.h.
Public Member Functions
TSourceCalibration (const TSourceCalibration &)=delete
TSourceCalibration (double sigma, double threshold, int degree, int count...)
TSourceCalibration (TSourceCalibration &&) noexcept=delete
~TSourceCalibration ()
void Calibrate ()
void CalibrationStatus (Int_t event, Int_t px, Int_t py, TObject *selected)
int Degree ()
void FinalWindow ()
void FindAllPeaks ()
void FindChannelPeaks ()
void FindSourcePeaks ()
void FitFinal (const int &channelId)
void Fitting (Int_t id)
std::mutex & GraphicsMutex ()
void HandleTimer ()
void LineHeight (const unsigned int &val)
double MaxResidual ()
void Navigate (Int_t id)
void NavigateFinal (Int_t id)
TSourceCalibration & operator= (const TSourceCalibration &)=delete
TSourceCalibration & operator= (TSourceCalibration &&) noexcept=delete
void PrintCanvases () const
void PrintLayout () const
void RecursiveRemove ()
void Remove ()
void SecondWindow ()
void SelectedFinalMainTab (Int_t id)
void SelectedFinalTab (Int_t id)
void SelectedTab (Int_t id)
void SetSource (Int_t windowId, Int_t entryId)
double Sigma ()
std::vector< std::tuple< double, double, double, double > > SourceEnergy (const size_t &i)
void Start ()
double Threshold ()
void UpdateChannel (const int &channelId)
void WriteCalibration ()
bool WriteNonlinearities ()
Static Public Member Functions
static bool AcceptBadFits ()
static void AcceptBadFits (bool val)
static void BadBin (const int &val)
static void BadBins (const std::vector< int > &val)
static void DigitWidth (int val)
static bool Fast ()
static void Fast (bool val)
static double FitRange ()
static void FitRange (int val)
static std::string LogFile ()
static void LogFile (std::string val)
static int MaxIterations ()
static void MaxIterations (int val)
static double MinIntensity ()
static void MinIntensity (double val)
static void NumberOfThreads (size_t val)
static int PanelHeight ()
static void PanelHeight (int val)
static int PanelWidth ()
static void PanelWidth (int val)
static void ParameterHeight (int val)
static void ResetBadBins ()
static void SourceboxWidth (int val)
static int StatusbarHeight ()
static void StatusbarHeight (int val)
static bool UseCalibratedPeaks ()
static void UseCalibratedPeaks (bool val)
static EVerbosity VerboseLevel ()
static void VerboseLevel (EVerbosity val)
static void ZoomX ()
Private Types
enum EEntry : int {
kStartButton , kSourceBox = 100 , kSigmaEntry = 200 , kThresholdEntry = 300 ,
kDegreeEntry = 400 , kMaxResidualEntry = 500 , kApplyToAll = 600 , kWriteNonlinearities = 700
}
enum EFitting : int {
kFindSourcePeaks = 1 , kFindChannelPeaks = 2 , kFindAllPeaks = 3 , kCalibrate = 4 ,
kRecursiveRemove = 5
}
enum ENavigate : int {
kPrevious = 1 , kDiscard = 2 , kAccept = 3 , kAcceptAll = 4 ,
kWrite = 5 , kNext = 6
}
Private Member Functions
void AcceptChannel (const int &channelId=-1)
void AcceptFinalChannel (const int &channelId=-1)
void BuildFirstInterface ()
void BuildSecondInterface ()
void BuildThirdInterface ()
TGTransientFrame * CreateProgressbar (const char *format)
void DeleteElement (TGFrame *element)
void DeleteFirst ()
void DeleteSecond ()
void DisconnectFirst ()
void DisconnectSecond ()
void DisconnectThird ()
void MakeFirstConnections ()
void MakeSecondConnections ()
void MakeThirdConnections ()
Private Attributes
TGTextButton * fAcceptAllButton {nullptr}
TGTextButton * fAcceptButton {nullptr}
std::vector< int > fActiveBins
std::vector< int > fActualChannelId
TGCheckButton * fApplyToAll {nullptr}
TGHorizontalFrame * fBottomFrame {nullptr}
TGTextButton * fCalibrateButton {nullptr}
std::vector< const char * > fChannelLabel
std::vector< TChannelTab * > fChannelTab
int fDefaultDegree {1}
double fDefaultMaxResidual {2.}
double fDefaultSigma {2.}
double fDefaultThreshold {0.05}
TGNumberEntry * fDegreeEntry {nullptr}
TGLabel * fDegreeLabel {nullptr}
TGTextButton * fDiscardButton {nullptr}
TGTextButton * fEmitter {nullptr}
TGTextButton * fFindAllPeaksButton {nullptr}
TGTextButton * fFindChannelPeaksButton {nullptr}
TGTextButton * fFindSourcePeaksButton {nullptr}
TGHButtonGroup * fFittingGroup {nullptr}
std::queue< std::pair< int, std::future< TChannelTab * > > > fFutures
std::mutex fGraphicsMutex
TGVerticalFrame * fLeftFrame {nullptr}
unsigned int fLineHeight {20}
std::vector< TH2 * > fMatrices
std::vector< TGLabel * > fMatrixNames
TGNumberEntry * fMaxResidualEntry {nullptr}
TGLabel * fMaxResidualLabel {nullptr}
TGHButtonGroup * fNavigationGroup {nullptr}
TGTextButton * fNextButton {nullptr}
int fNofBins {0}
int fOldErrorLevel
TFile * fOutput {nullptr}
TGGroupFrame * fParameterFrame {nullptr}
TGTextButton * fPreviousButton {nullptr}
TGHProgressBar * fProgressBar {nullptr}
TGTextButton * fRecursiveRemoveButton {nullptr}
TRedirect * fRedirect {nullptr}
TGVerticalFrame * fRightFrame {nullptr}
TGGroupFrame * fSettingsFrame {nullptr}
TGNumberEntry * fSigmaEntry {nullptr}
TGLabel * fSigmaLabel {nullptr}
std::vector< TNucleus * > fSource
std::vector< TGComboBox * > fSourceBox
std::vector< std::vector< std::tuple< double, double, double, double > > > fSourceEnergy
TGTextButton * fStartButton {nullptr}
TGTab * fTab {nullptr}
TGNumberEntry * fThresholdEntry {nullptr}
TGLabel * fThresholdLabel {nullptr}
int fWaitMs {100}
TGTextButton * fWriteButton {nullptr}
TGCheckButton * fWriteNonlinearities {nullptr}
Static Private Attributes
static bool fAcceptBadFits = false
static std::vector< int > fBadBins
static int fDigitWidth = 5
static bool fFast = false
static int fFitRange = 10
static std::string fLogFile
static int fMaxIterations = 50
static double fMinIntensity = 4.
static size_t fNumberOfThreads = 4
static int fPanelHeight = 400
static int fPanelWidth = 600
static int fParameterHeight = 200
static int fSourceboxWidth = 100
static int fStatusbarHeight = 50
static bool fUseCalibratedPeaks = false
static EVerbosity fVerboseLevel = EVerbosity::kQuiet
Member Enumeration Documentation
EEntry
enum TSourceCalibration::EEntry : int private
Enumerator
kStartButton
kSourceBox
kSigmaEntry
kThresholdEntry
kDegreeEntry
kMaxResidualEntry
kApplyToAll
kWriteNonlinearities
Definition at line 315 of file TSourceCalibration.h.
EFitting
enum TSourceCalibration::EFitting : int private
Enumerator
kFindSourcePeaks
kFindChannelPeaks
kFindAllPeaks
kCalibrate
kRecursiveRemove
Definition at line 334 of file TSourceCalibration.h.
ENavigate
enum TSourceCalibration::ENavigate : int private
Enumerator
kPrevious
kDiscard
kAccept
kAcceptAll
kWrite
kNext
Definition at line 326 of file TSourceCalibration.h.
Constructor & Destructor Documentation
TSourceCalibration() [1/3]
TSourceCalibration::TSourceCalibration (double sigma, double threshold, int degree, int count...)
Definition at line 2161 of file TSourceCalibration.cxx.
References BuildFirstInterface(), DGREEN, fActiveBins, fActualChannelId, fBadBins, fChannelLabel, FilledBin(), fLogFile, fMatrices, fNofBins, fOldErrorLevel, fOutput, fRedirect, fVerboseLevel, kBasicFlow, kQuiet, MakeFirstConnections(), and mat.
TSourceCalibration() [2/3]
TSourceCalibration::TSourceCalibration (const TSourceCalibration &) delete
TSourceCalibration() [3/3]
TSourceCalibration::TSourceCalibration (TSourceCalibration &&) delete noexcept
~TSourceCalibration()
TSourceCalibration::~TSourceCalibration ()
Definition at line 2260 of file TSourceCalibration.cxx.
References fOldErrorLevel, fOutput, and fRedirect.
Member Function Documentation
AcceptBadFits() [1/2]
static bool TSourceCalibration::AcceptBadFits () inline static
Definition at line 293 of file TSourceCalibration.h.
References fAcceptBadFits.
Referenced by TSourceTab::Good().
AcceptBadFits() [2/2]
static void TSourceCalibration::AcceptBadFits (bool val) inline static
Definition at line 292 of file TSourceCalibration.h.
References fAcceptBadFits.
AcceptChannel()
void TSourceCalibration::AcceptChannel (const int & channelId = -1) private
Definition at line 2806 of file TSourceCalibration.cxx.
References DGREEN, fAcceptAllButton, fActiveBins, fActualChannelId, fChannelTab, fEmitter, fTab, fVerboseLevel, fWaitMs, kBasicFlow, kLoops, kSubroutines, RESET_COLOR, and SelectedTab().
Referenced by Navigate().
AcceptFinalChannel()
void TSourceCalibration::AcceptFinalChannel (const int & channelId = -1) private
BadBin()
static void TSourceCalibration::BadBin (const int & val) inline static
Definition at line 305 of file TSourceCalibration.h.
References fBadBins.
BadBins()
static void TSourceCalibration::BadBins (const std::vector< int > & val) inline static
Definition at line 304 of file TSourceCalibration.h.
References fBadBins.
BuildFirstInterface()
void TSourceCalibration::BuildFirstInterface () private
Build initial interface with histogram <-> source assignment
Definition at line 2270 of file TSourceCalibration.cxx.
References fLineHeight, fMatrices, fMatrixNames, fPanelHeight, fSource, fSourceBox, fSourceboxWidth, fSourceEnergy, fStartButton, fVerboseLevel, kBasicFlow, kSourceBox, kStartButton, kSubroutines, and SetSource().
Referenced by TSourceCalibration().
BuildSecondInterface()
void TSourceCalibration::BuildSecondInterface () private
Definition at line 2514 of file TSourceCalibration.cxx.
References DGREEN, fAcceptAllButton, fAcceptButton, fActiveBins, fApplyToAll, fBottomFrame, fCalibrateButton, fChannelTab, fDefaultDegree, fDefaultMaxResidual, fDefaultSigma, fDefaultThreshold, fDegreeEntry, fDegreeLabel, fDigitWidth, fDiscardButton, fFindAllPeaksButton, fFindChannelPeaksButton, fFindSourcePeaksButton, fFittingGroup, fLeftFrame, fMatrices, fMaxResidualEntry, fMaxResidualLabel, fNavigationGroup, fNextButton, fPanelHeight, fPanelWidth, fParameterFrame, fParameterHeight, fPreviousButton, fProgressBar, fRecursiveRemoveButton, fRightFrame, fSettingsFrame, fSigmaEntry, fSigmaLabel, fSource, fSourceEnergy, fStatusbarHeight, fTab, fThresholdEntry, fThresholdLabel, fVerboseLevel, fWriteButton, fWriteNonlinearities, kApplyToAll, kBasicFlow, kDegreeEntry, kMaxResidualEntry, kSigmaEntry, kSubroutines, kThresholdEntry, kWriteNonlinearities, SelectedTab(), StatusbarHeight(), and VerboseLevel().
Referenced by SecondWindow().
BuildThirdInterface()
void TSourceCalibration::BuildThirdInterface () private
Calibrate()
void TSourceCalibration::Calibrate ()
Definition at line 2907 of file TSourceCalibration.cxx.
References CreateProgressbar(), DGREEN, fActiveBins, fApplyToAll, fChannelTab, fProgressBar, fTab, fVerboseLevel, kBasicFlow, and RESET_COLOR.
Referenced by Fitting().
CalibrationStatus()
void TSourceCalibration::CalibrationStatus (Int_t event, Int_t px, Int_t py, TObject * selected)
CreateProgressbar()
TGTransientFrame * TSourceCalibration::CreateProgressbar (const char * format) private
Definition at line 2966 of file TSourceCalibration.cxx.
References fActiveBins, fPanelWidth, fProgressBar, and fStatusbarHeight.
Referenced by Calibrate(), FindAllPeaks(), FindSourcePeaks(), and RecursiveRemove().
Degree()
int TSourceCalibration::Degree () inline
Definition at line 245 of file TSourceCalibration.h.
References fDefaultDegree, and fDegreeEntry.
Referenced by TChannelTab::Calibrate().
DeleteElement()
void TSourceCalibration::DeleteElement (TGFrame * element) private
Definition at line 2388 of file TSourceCalibration.cxx.
Referenced by DeleteFirst(), and SecondWindow().
DeleteFirst()
void TSourceCalibration::DeleteFirst () private
Definition at line 2396 of file TSourceCalibration.cxx.
References DeleteElement(), fMatrixNames, fSourceBox, fStartButton, fVerboseLevel, and kSubroutines.
Referenced by SecondWindow().
DeleteSecond()
void TSourceCalibration::DeleteSecond () private
DigitWidth()
static void TSourceCalibration::DigitWidth (int val) inline static
Definition at line 277 of file TSourceCalibration.h.
References fDigitWidth.
DisconnectFirst()
void TSourceCalibration::DisconnectFirst () private
Disconnect all signals from histogram <-> source assignment interface
Definition at line 2378 of file TSourceCalibration.cxx.
References fSourceBox, and fStartButton.
Referenced by SecondWindow().
DisconnectSecond()
void TSourceCalibration::DisconnectSecond () private
Definition at line 2675 of file TSourceCalibration.cxx.
References DGREEN, fChannelTab, fFittingGroup, fNavigationGroup, fTab, fVerboseLevel, and kBasicFlow.
DisconnectThird()
void TSourceCalibration::DisconnectThird () private
Fast() [1/2]
static bool TSourceCalibration::Fast () inline static
Definition at line 296 of file TSourceCalibration.h.
References fFast.
Fast() [2/2]
static void TSourceCalibration::Fast (bool val) inline static
Definition at line 295 of file TSourceCalibration.h.
References fFast.
FinalWindow()
void TSourceCalibration::FinalWindow ()
FindAllPeaks()
void TSourceCalibration::FindAllPeaks ()
Definition at line 2888 of file TSourceCalibration.cxx.
References CreateProgressbar(), DGREEN, fActiveBins, fChannelTab, fProgressBar, fVerboseLevel, kBasicFlow, and RESET_COLOR.
Referenced by Fitting().
FindChannelPeaks()
void TSourceCalibration::FindChannelPeaks ()
Definition at line 2876 of file TSourceCalibration.cxx.
References DGREEN, fActiveBins, fChannelTab, fTab, fVerboseLevel, kBasicFlow, and RESET_COLOR.
Referenced by Fitting().
FindSourcePeaks()
void TSourceCalibration::FindSourcePeaks ()
Definition at line 2852 of file TSourceCalibration.cxx.
References CreateProgressbar(), DGREEN, fActiveBins, fApplyToAll, fChannelTab, fProgressBar, fTab, fVerboseLevel, kBasicFlow, and RESET_COLOR.
Referenced by Fitting().
FitFinal()
void TSourceCalibration::FitFinal (const int & channelId)
FitRange() [1/2]
static double TSourceCalibration::FitRange () inline static
Definition at line 290 of file TSourceCalibration.h.
References fFitRange.
Referenced by TSourceTab::FindCalibratedPeaks(), and TSourceTab::ReplacePeak().
FitRange() [2/2]
static void TSourceCalibration::FitRange (int val) inline static
Definition at line 289 of file TSourceCalibration.h.
References fFitRange.
Fitting()
void TSourceCalibration::Fitting (Int_t id)
Definition at line 2732 of file TSourceCalibration.cxx.
References Calibrate(), DGREEN, fActiveBins, fActualChannelId, fChannelTab, FindAllPeaks(), FindChannelPeaks(), FindSourcePeaks(), fTab, fVerboseLevel, kBasicFlow, kCalibrate, kFindAllPeaks, kFindChannelPeaks, kFindSourcePeaks, kRecursiveRemove, RecursiveRemove(), and VerboseLevel().
GraphicsMutex()
std::mutex & TSourceCalibration::GraphicsMutex () inline
Definition at line 264 of file TSourceCalibration.h.
References fGraphicsMutex.
HandleTimer()
void TSourceCalibration::HandleTimer ()
Definition at line 2424 of file TSourceCalibration.cxx.
References fAcceptAllButton, fChannelTab, fEmitter, fOutput, fStartButton, fVerboseLevel, kBasicFlow, SecondWindow(), and WriteCalibration().
LineHeight()
void TSourceCalibration::LineHeight (const unsigned int & val) inline
Definition at line 219 of file TSourceCalibration.h.
References fLineHeight.
LogFile() [1/2]
static std::string TSourceCalibration::LogFile () inline static
Definition at line 284 of file TSourceCalibration.h.
References fLogFile.
Referenced by TSourceTab::FindCalibratedPeaks(), and TSourceTab::ReplacePeak().
LogFile() [2/2]
static void TSourceCalibration::LogFile (std::string val) inline static
Definition at line 283 of file TSourceCalibration.h.
References fLogFile.
MakeFirstConnections()
void TSourceCalibration::MakeFirstConnections () private
Create connections for the histogram <-> source assignment interface
Definition at line 2365 of file TSourceCalibration.cxx.
References fSourceBox, and fStartButton.
Referenced by TSourceCalibration().
MakeSecondConnections()
void TSourceCalibration::MakeSecondConnections () private
Definition at line 2661 of file TSourceCalibration.cxx.
References DGREEN, fChannelTab, fFittingGroup, fNavigationGroup, fTab, fVerboseLevel, and kBasicFlow.
Referenced by SecondWindow().
MakeThirdConnections()
void TSourceCalibration::MakeThirdConnections () private
MaxIterations() [1/2]
static int TSourceCalibration::MaxIterations () inline static
Definition at line 287 of file TSourceCalibration.h.
References fMaxIterations.
Referenced by Match(), RoughCal(), and SmartMatch().
MaxIterations() [2/2]
static void TSourceCalibration::MaxIterations (int val) inline static
Definition at line 286 of file TSourceCalibration.h.
References fMaxIterations.
MaxResidual()
double TSourceCalibration::MaxResidual () inline
Definition at line 250 of file TSourceCalibration.h.
References fDefaultMaxResidual, and fMaxResidualEntry.
Referenced by RecursiveRemove().
MinIntensity() [1/2]
static double TSourceCalibration::MinIntensity () inline static
Definition at line 302 of file TSourceCalibration.h.
References fMinIntensity.
Referenced by TSourceTab::FindCalibratedPeaks().
MinIntensity() [2/2]
static void TSourceCalibration::MinIntensity (double val) inline static
Definition at line 301 of file TSourceCalibration.h.
References fMinIntensity.
Navigate()
void TSourceCalibration::Navigate (Int_t id)
Definition at line 2688 of file TSourceCalibration.cxx.
References AcceptChannel(), DGREEN, fActiveBins, fActualChannelId, fChannelTab, fTab, fVerboseLevel, kAccept, kAcceptAll, kBasicFlow, kDiscard, kNext, kPrevious, kWrite, SelectedTab(), VerboseLevel(), and WriteCalibration().
NavigateFinal()
void TSourceCalibration::NavigateFinal (Int_t id)
NumberOfThreads()
static void TSourceCalibration::NumberOfThreads (size_t val) inline static
Definition at line 278 of file TSourceCalibration.h.
References fNumberOfThreads.
operator=() [1/2]
TSourceCalibration & TSourceCalibration::operator= (const TSourceCalibration &) delete
operator=() [2/2]
TSourceCalibration & TSourceCalibration::operator= (TSourceCalibration &&) delete noexcept
PanelHeight() [1/2]
static int TSourceCalibration::PanelHeight () inline static
Definition at line 271 of file TSourceCalibration.h.
References fPanelHeight.
Referenced by TChannelTab::BuildInterface(), and TSourceTab::BuildInterface().
PanelHeight() [2/2]
static void TSourceCalibration::PanelHeight (int val) inline static
Definition at line 267 of file TSourceCalibration.h.
References fPanelHeight.
PanelWidth() [1/2]
static int TSourceCalibration::PanelWidth () inline static
Definition at line 270 of file TSourceCalibration.h.
References fPanelWidth.
Referenced by TChannelTab::BuildInterface(), and TSourceTab::BuildInterface().
PanelWidth() [2/2]
static void TSourceCalibration::PanelWidth (int val) inline static
Definition at line 266 of file TSourceCalibration.h.
References fPanelWidth.
ParameterHeight()
static void TSourceCalibration::ParameterHeight (int val) inline static
Definition at line 275 of file TSourceCalibration.h.
References fParameterHeight.
PrintCanvases()
void TSourceCalibration::PrintCanvases () const
Definition at line 2997 of file TSourceCalibration.cxx.
References DGREEN, fChannelTab, fVerboseLevel, and kBasicFlow.
PrintLayout()
void TSourceCalibration::PrintLayout () const
Definition at line 2982 of file TSourceCalibration.cxx.
References DGREEN, fBottomFrame, fChannelTab, fLeftFrame, fRightFrame, fTab, fVerboseLevel, and kBasicFlow.
RecursiveRemove()
void TSourceCalibration::RecursiveRemove ()
Definition at line 2929 of file TSourceCalibration.cxx.
References CreateProgressbar(), DGREEN, fActiveBins, fApplyToAll, fChannelTab, fProgressBar, fTab, fVerboseLevel, kBasicFlow, MaxResidual(), and RESET_COLOR.
Referenced by Fitting().
Remove()
void TSourceCalibration::Remove ()
ResetBadBins()
static void TSourceCalibration::ResetBadBins () inline static
Definition at line 306 of file TSourceCalibration.h.
References fBadBins.
SecondWindow()
void TSourceCalibration::SecondWindow ()
Definition at line 2452 of file TSourceCalibration.cxx.
References BuildSecondInterface(), DeleteElement(), DeleteFirst(), DGREEN, DisconnectFirst(), fActiveBins, fLineHeight, fMatrices, fPanelHeight, fPanelWidth, fProgressBar, fSource, fStatusbarHeight, fVerboseLevel, kBasicFlow, kSubroutines, and MakeSecondConnections().
Referenced by HandleTimer().
SelectedFinalMainTab()
void TSourceCalibration::SelectedFinalMainTab (Int_t id)
SelectedFinalTab()
void TSourceCalibration::SelectedFinalTab (Int_t id)
SelectedTab()
void TSourceCalibration::SelectedTab (Int_t id)
Simple function that enables and disables the previous and next buttons depending on which tab was selected. Also sets gPad to the projection of the source selected in this tab.
Definition at line 2764 of file TSourceCalibration.cxx.
References DGREEN, fActiveBins, fChannelTab, fNextButton, fPreviousButton, fTab, fVerboseLevel, kBasicFlow, RESET_COLOR, and VerboseLevel().
Referenced by AcceptChannel(), BuildSecondInterface(), and Navigate().
SetSource()
void TSourceCalibration::SetSource (Int_t windowId, Int_t entryId)
Definition at line 2410 of file TSourceCalibration.cxx.
References fSource, fSourceBox, fSourceEnergy, fVerboseLevel, kBasicFlow, and kSourceBox.
Referenced by BuildFirstInterface().
Sigma()
double TSourceCalibration::Sigma () inline
Definition at line 243 of file TSourceCalibration.h.
References fSigmaEntry.
Referenced by TSourceTab::Add(), TSourceTab::FindCalibratedPeaks(), TSourceTab::InitialCalibration(), TSourceTab::ProjectionStatus(), and TSourceTab::ReplacePeak().
SourceboxWidth()
static void TSourceCalibration::SourceboxWidth (int val) inline static
Definition at line 276 of file TSourceCalibration.h.
References fSourceboxWidth.
SourceEnergy()
std::vector< std::tuple< double, double, double, double > > TSourceCalibration::SourceEnergy (const size_t & i) inline
Definition at line 256 of file TSourceCalibration.h.
References fSourceEnergy.
Start()
void TSourceCalibration::Start ()
Definition at line 2443 of file TSourceCalibration.cxx.
References fEmitter, fStartButton, fVerboseLevel, fWaitMs, and kBasicFlow.
StatusbarHeight() [1/2]
static int TSourceCalibration::StatusbarHeight () inline static
Definition at line 272 of file TSourceCalibration.h.
References fStatusbarHeight.
Referenced by TChannelTab::BuildInterface(), TSourceTab::BuildInterface(), and BuildSecondInterface().
StatusbarHeight() [2/2]
static void TSourceCalibration::StatusbarHeight (int val) inline static
Definition at line 268 of file TSourceCalibration.h.
References fStatusbarHeight.
Threshold()
double TSourceCalibration::Threshold () inline
Definition at line 244 of file TSourceCalibration.h.
References fThresholdEntry.
Referenced by TSourceTab::InitialCalibration().
UpdateChannel()
void TSourceCalibration::UpdateChannel (const int & channelId)
UseCalibratedPeaks() [1/2]
static bool TSourceCalibration::UseCalibratedPeaks () inline static
Definition at line 299 of file TSourceCalibration.h.
References fUseCalibratedPeaks.
UseCalibratedPeaks() [2/2]
static void TSourceCalibration::UseCalibratedPeaks (bool val) inline static
Definition at line 298 of file TSourceCalibration.h.
References fUseCalibratedPeaks.
VerboseLevel() [1/2]
static EVerbosity TSourceCalibration::VerboseLevel () inline static
Definition at line 281 of file TSourceCalibration.h.
References fVerboseLevel.
Referenced by TChannelTab::TChannelTab(), TSourceTab::TSourceTab(), TSourceTab::TSourceTab(), TSourceTab::Add(), TSourceTab::Add(), TSourceTab::BuildInterface(), BuildSecondInterface(), TChannelTab::Calibrate(), TChannelTab::CreateSourceTab(), TSourceTab::Draw(), TChannelTab::FindAllCalibratedPeaks(), TChannelTab::FindCalibratedPeaks(), TSourceTab::FindCalibratedPeaks(), Fitting(), TSourceTab::InitialCalibration(), TChannelTab::Initialize(), TChannelTab::MakeConnections(), TSourceTab::MakeConnections(), Match(), Navigate(), TSourceTab::ProjectionStatus(), TSourceTab::ProjectionStatus(), TChannelTab::RecursiveRemove(), TChannelTab::RemovePoint(), TSourceTab::RemovePoint(), TSourceTab::ReplacePeak(), RoughCal(), TChannelTab::SelectCanvas(), TChannelTab::SelectedTab(), SelectedTab(), TSourceTab::SetLineColors(), SmartMatch(), TChannelTab::UpdateChannel(), TChannelTab::UpdateData(), TSourceTab::UpdateFits(), TChannelTab::UpdateFwhm(), TSourceTab::UpdateRegions(), TChannelTab::Write(), TChannelTab::ZoomX(), and TChannelTab::ZoomY().
VerboseLevel() [2/2]
static void TSourceCalibration::VerboseLevel (EVerbosity val) inline static
Definition at line 280 of file TSourceCalibration.h.
References fVerboseLevel.
WriteCalibration()
void TSourceCalibration::WriteCalibration ()
Definition at line 2953 of file TSourceCalibration.cxx.
References DGREEN, fSource, fVerboseLevel, TChannel::GetNumberOfChannels(), kBasicFlow, kSubroutines, and TChannel::WriteCalFile().
Referenced by HandleTimer(), and Navigate().
WriteNonlinearities()
bool TSourceCalibration::WriteNonlinearities () inline
Definition at line 255 of file TSourceCalibration.h.
References fWriteNonlinearities.
Referenced by TChannelTab::UpdateChannel().
ZoomX()
static void TSourceCalibration::ZoomX () static
Member Data Documentation
fAcceptAllButton
TGTextButton* TSourceCalibration::fAcceptAllButton {nullptr} private
Definition at line 371 of file TSourceCalibration.h.
Referenced by AcceptChannel(), BuildSecondInterface(), and HandleTimer().
fAcceptBadFits
bool TSourceCalibration::fAcceptBadFits = false static private
Do we accept peaks where the fit was bad (position or area uncertainties too large or not numbers)
Definition at line 428 of file TSourceCalibration.h.
Referenced by AcceptBadFits(), and AcceptBadFits().
fAcceptButton
TGTextButton* TSourceCalibration::fAcceptButton {nullptr} private
Definition at line 370 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fActiveBins
std::vector<int> TSourceCalibration::fActiveBins private
Definition at line 398 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), AcceptChannel(), BuildSecondInterface(), Calibrate(), CreateProgressbar(), FindAllPeaks(), FindChannelPeaks(), FindSourcePeaks(), Fitting(), Navigate(), RecursiveRemove(), SecondWindow(), and SelectedTab().
fActualChannelId
std::vector<int> TSourceCalibration::fActualChannelId private
Definition at line 399 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), AcceptChannel(), Fitting(), and Navigate().
fApplyToAll
TGCheckButton* TSourceCalibration::fApplyToAll {nullptr} private
Definition at line 390 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), Calibrate(), FindSourcePeaks(), and RecursiveRemove().
fBadBins
std::vector< int > TSourceCalibration::fBadBins static private
Bins of the 2D matrix to be ignored even if there are enough counts in them.
Definition at line 433 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), BadBin(), BadBins(), and ResetBadBins().
fBottomFrame
TGHorizontalFrame* TSourceCalibration::fBottomFrame {nullptr} private
Definition at line 359 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and PrintLayout().
fCalibrateButton
TGTextButton* TSourceCalibration::fCalibrateButton {nullptr} private
Definition at line 375 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fChannelLabel
std::vector<const char*> TSourceCalibration::fChannelLabel private
Definition at line 400 of file TSourceCalibration.h.
Referenced by TSourceCalibration().
fChannelTab
std::vector<TChannelTab*> TSourceCalibration::fChannelTab private
Definition at line 364 of file TSourceCalibration.h.
Referenced by AcceptChannel(), BuildSecondInterface(), Calibrate(), DisconnectSecond(), FindAllPeaks(), FindChannelPeaks(), FindSourcePeaks(), Fitting(), HandleTimer(), MakeSecondConnections(), Navigate(), PrintCanvases(), PrintLayout(), RecursiveRemove(), and SelectedTab().
fDefaultDegree
int TSourceCalibration::fDefaultDegree {1} private
The default degree of the polynomial used for calibrating, can be changed later.
Definition at line 424 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and Degree().
fDefaultMaxResidual
double TSourceCalibration::fDefaultMaxResidual {2.} private
The default maximum residual accepted when trying to iteratively find peaks.
Definition at line 425 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and MaxResidual().
fDefaultSigma
double TSourceCalibration::fDefaultSigma {2.} private
The default sigma used for the peak finding algorithm, can be changed later.
Definition at line 422 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fDefaultThreshold
double TSourceCalibration::fDefaultThreshold {0.05} private
The default threshold used for the peak finding algorithm, can be changed later. Co-56 source needs a much lower threshold, 0.01 or 0.02, but that makes it much slower too.
Definition at line 423 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fDegreeEntry
TGNumberEntry* TSourceCalibration::fDegreeEntry {nullptr} private
Definition at line 386 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and Degree().
fDegreeLabel
TGLabel* TSourceCalibration::fDegreeLabel {nullptr} private
Definition at line 385 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fDigitWidth
int TSourceCalibration::fDigitWidth = 5 static private
Number of digits used for parameter entries (if they are floating point)
Definition at line 416 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and DigitWidth().
fDiscardButton
TGTextButton* TSourceCalibration::fDiscardButton {nullptr} private
Definition at line 369 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fEmitter
TGTextButton* TSourceCalibration::fEmitter {nullptr} private
Definition at line 366 of file TSourceCalibration.h.
Referenced by AcceptChannel(), HandleTimer(), and Start().
fFast
bool TSourceCalibration::fFast = false static private
Do we use the fast peak finding method on startup or not.
Definition at line 429 of file TSourceCalibration.h.
Referenced by Fast(), and Fast().
fFindAllPeaksButton
TGTextButton* TSourceCalibration::fFindAllPeaksButton {nullptr} private
Definition at line 376 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fFindChannelPeaksButton
TGTextButton* TSourceCalibration::fFindChannelPeaksButton {nullptr} private
Definition at line 377 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fFindSourcePeaksButton
TGTextButton* TSourceCalibration::fFindSourcePeaksButton {nullptr} private
Definition at line 378 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fFitRange
int TSourceCalibration::fFitRange = 10 static private
range in sigma used for fitting peaks (peak position - range to peas position + range)
Definition at line 427 of file TSourceCalibration.h.
Referenced by FitRange(), and FitRange().
fFittingGroup
TGHButtonGroup* TSourceCalibration::fFittingGroup {nullptr} private
Definition at line 374 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), DisconnectSecond(), and MakeSecondConnections().
fFutures
std::queue<std::pair<int, std::future<TChannelTab*> > > TSourceCalibration::fFutures private
Definition at line 401 of file TSourceCalibration.h.
fGraphicsMutex
std::mutex TSourceCalibration::fGraphicsMutex private
mutex to lock changes to graphics
Definition at line 435 of file TSourceCalibration.h.
Referenced by GraphicsMutex().
fLeftFrame
TGVerticalFrame* TSourceCalibration::fLeftFrame {nullptr} private
Definition at line 360 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and PrintLayout().
fLineHeight
unsigned int TSourceCalibration::fLineHeight {20} private
Height of text boxes and progress bar.
Definition at line 410 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), LineHeight(), and SecondWindow().
fLogFile
std::string TSourceCalibration::fLogFile static private
name of log file, if empty no log file is written
Definition at line 406 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), LogFile(), and LogFile().
fMatrices
std::vector<TH2*> TSourceCalibration::fMatrices private
Definition at line 403 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), BuildFirstInterface(), BuildSecondInterface(), and SecondWindow().
fMatrixNames
std::vector<TGLabel*> TSourceCalibration::fMatrixNames private
Definition at line 394 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), and DeleteFirst().
fMaxIterations
int TSourceCalibration::fMaxIterations = 50 static private
Maximum iterations over combinations in Match and SmartMatch.
Definition at line 426 of file TSourceCalibration.h.
Referenced by MaxIterations(), and MaxIterations().
fMaxResidualEntry
TGNumberEntry* TSourceCalibration::fMaxResidualEntry {nullptr} private
Definition at line 388 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and MaxResidual().
fMaxResidualLabel
TGLabel* TSourceCalibration::fMaxResidualLabel {nullptr} private
Definition at line 387 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fMinIntensity
double TSourceCalibration::fMinIntensity = 4. static private
Minimum intensity of source peaks to be considered when trying to find them in the spectrum.
Definition at line 431 of file TSourceCalibration.h.
Referenced by MinIntensity(), and MinIntensity().
fNavigationGroup
TGHButtonGroup* TSourceCalibration::fNavigationGroup {nullptr} private
Definition at line 367 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), DisconnectSecond(), and MakeSecondConnections().
fNextButton
TGTextButton* TSourceCalibration::fNextButton {nullptr} private
Definition at line 373 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and SelectedTab().
fNofBins
int TSourceCalibration::fNofBins {0} private
Number of filled bins in first matrix.
Definition at line 404 of file TSourceCalibration.h.
Referenced by TSourceCalibration().
fNumberOfThreads
size_t TSourceCalibration::fNumberOfThreads = 4 static private
Maximum number of threads to run while creating the channel tabs.
Definition at line 432 of file TSourceCalibration.h.
Referenced by NumberOfThreads().
fOldErrorLevel
int TSourceCalibration::fOldErrorLevel private
Used to store old value of gErrorIgnoreLevel (set to kError for the scope of the class)
Definition at line 420 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), and ~TSourceCalibration().
fOutput
TFile* TSourceCalibration::fOutput {nullptr} private
Definition at line 437 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), ~TSourceCalibration(), and HandleTimer().
fPanelHeight
int TSourceCalibration::fPanelHeight = 400 static private
Height of one panel.
Definition at line 412 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), BuildSecondInterface(), PanelHeight(), PanelHeight(), and SecondWindow().
fPanelWidth
int TSourceCalibration::fPanelWidth = 600 static private
Width of one panel.
Definition at line 411 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), CreateProgressbar(), PanelWidth(), PanelWidth(), and SecondWindow().
fParameterFrame
TGGroupFrame* TSourceCalibration::fParameterFrame {nullptr} private
Definition at line 380 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fParameterHeight
int TSourceCalibration::fParameterHeight = 200 static private
Height of the frame for the parameters.
Definition at line 414 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and ParameterHeight().
fPreviousButton
TGTextButton* TSourceCalibration::fPreviousButton {nullptr} private
Definition at line 368 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and SelectedTab().
fProgressBar
TGHProgressBar* TSourceCalibration::fProgressBar {nullptr} private
Definition at line 392 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), Calibrate(), CreateProgressbar(), FindAllPeaks(), FindSourcePeaks(), RecursiveRemove(), and SecondWindow().
fRecursiveRemoveButton
TGTextButton* TSourceCalibration::fRecursiveRemoveButton {nullptr} private
Definition at line 379 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fRedirect
TRedirect* TSourceCalibration::fRedirect {nullptr} private
redirect, created in constructor and destroyed in destructor if a log file name has been provided
Definition at line 407 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), and ~TSourceCalibration().
fRightFrame
TGVerticalFrame* TSourceCalibration::fRightFrame {nullptr} private
Definition at line 361 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and PrintLayout().
fSettingsFrame
TGGroupFrame* TSourceCalibration::fSettingsFrame {nullptr} private
Definition at line 389 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fSigmaEntry
TGNumberEntry* TSourceCalibration::fSigmaEntry {nullptr} private
Definition at line 382 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and Sigma().
fSigmaLabel
TGLabel* TSourceCalibration::fSigmaLabel {nullptr} private
Definition at line 381 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fSource
std::vector<TNucleus*> TSourceCalibration::fSource private
Definition at line 396 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), BuildSecondInterface(), SecondWindow(), SetSource(), and WriteCalibration().
fSourceBox
std::vector<TGComboBox*> TSourceCalibration::fSourceBox private
Definition at line 395 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), DeleteFirst(), DisconnectFirst(), MakeFirstConnections(), and SetSource().
fSourceboxWidth
int TSourceCalibration::fSourceboxWidth = 100 static private
Width of the box to select which source each histogram is from.
Definition at line 415 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), and SourceboxWidth().
fSourceEnergy
std::vector<std::vector<std::tuple<double, double, double, double> > > TSourceCalibration::fSourceEnergy private
vector to hold source energy, energy uncertainty, intensity, and intensity uncertainty
Definition at line 397 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), BuildSecondInterface(), SetSource(), and SourceEnergy().
fStartButton
TGTextButton* TSourceCalibration::fStartButton {nullptr} private
Definition at line 362 of file TSourceCalibration.h.
Referenced by BuildFirstInterface(), DeleteFirst(), DisconnectFirst(), HandleTimer(), MakeFirstConnections(), and Start().
fStatusbarHeight
int TSourceCalibration::fStatusbarHeight = 50 static private
Height of status bar (also extra height needed for tabs)
Definition at line 413 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), CreateProgressbar(), SecondWindow(), StatusbarHeight(), and StatusbarHeight().
fTab
TGTab* TSourceCalibration::fTab {nullptr} private
Definition at line 363 of file TSourceCalibration.h.
Referenced by AcceptChannel(), BuildSecondInterface(), Calibrate(), DisconnectSecond(), FindChannelPeaks(), FindSourcePeaks(), Fitting(), MakeSecondConnections(), Navigate(), PrintLayout(), RecursiveRemove(), and SelectedTab().
fThresholdEntry
TGNumberEntry* TSourceCalibration::fThresholdEntry {nullptr} private
Definition at line 384 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and Threshold().
fThresholdLabel
TGLabel* TSourceCalibration::fThresholdLabel {nullptr} private
Definition at line 383 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fUseCalibratedPeaks
bool TSourceCalibration::fUseCalibratedPeaks = false static private
Do we use the initial calibration to find more peaks in the source spectra?
Definition at line 430 of file TSourceCalibration.h.
Referenced by UseCalibratedPeaks(), and UseCalibratedPeaks().
fVerboseLevel
EVerbosity TSourceCalibration::fVerboseLevel = EVerbosity::kQuiet static private
Changes verbosity from kQuiet to kAll.
Definition at line 439 of file TSourceCalibration.h.
Referenced by TSourceCalibration(), AcceptChannel(), BuildFirstInterface(), BuildSecondInterface(), Calibrate(), DeleteFirst(), DisconnectSecond(), FindAllPeaks(), FindChannelPeaks(), FindSourcePeaks(), Fitting(), HandleTimer(), MakeSecondConnections(), Navigate(), PrintCanvases(), PrintLayout(), RecursiveRemove(), SecondWindow(), SelectedTab(), SetSource(), Start(), VerboseLevel(), VerboseLevel(), and WriteCalibration().
fWaitMs
int TSourceCalibration::fWaitMs {100} private
How many milliseconds we wait before we process the navigation input (to avoid double triggers?)
Definition at line 418 of file TSourceCalibration.h.
Referenced by AcceptChannel(), and Start().
fWriteButton
TGTextButton* TSourceCalibration::fWriteButton {nullptr} private
Definition at line 372 of file TSourceCalibration.h.
Referenced by BuildSecondInterface().
fWriteNonlinearities
TGCheckButton* TSourceCalibration::fWriteNonlinearities {nullptr} private
Definition at line 391 of file TSourceCalibration.h.
Referenced by BuildSecondInterface(), and WriteNonlinearities().