GRSISort: TGriffinHit Class Reference
TGriffinHit Class Reference
Detectors
Detailed Description
Definition at line 18 of file TGriffinHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class EGriffinHitBits {
kTotalPU1 = 1<<0 , kTotalPU2 = 1<<1 , kPUHitOffset = kTotalPU2 , kPUHit1 = 1<<2 ,
kPUHit2 = 1<<3 , kBit4 = 1<<4 , kBit5 = 1<<5 , kBit6 = 1<<6 ,
kBit7 = 1<<7
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TGriffinHit ()
TGriffinHit (const TFragment &)
TGriffinHit (const TGriffinHit &)
~TGriffinHit () override
void Add (const TDetectorHit *) override
void AddWaveformSample (const Short_t &val)
virtual void AppendTimeStamp (const Long64_t &val)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool) const override
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
UShort_t GetArrayNumber () const override
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual int GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Int_t GetFilterPattern () const
Bool_t GetIsBremSuppressed () const
virtual Short_t GetKValue () const
const char * GetName () const override
Double_t GetNoCTEnergy (Option_t *opt="") const
TVector3 GetPosition () const override
TVector3 GetPosition (double dist) const override
virtual TVector3 GetPosition (Double_t) const
EPpgPattern GetPPGStatus () const
virtual Int_t GetSegment () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool InFilter (Int_t)
void MakeBremSuppressed (const Bool_t &supp_flag)
UShort_t NPileUps () const
bool operator< (const TDetectorHit &rhs) const
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
UShort_t PUHit () const
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &val)
virtual void SetCfd (const Int_t &val)
virtual void SetCfd (const uint32_t &val)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &energy) const
void SetFilterPattern (const int &x)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetIsBremSuppressed (const Bool_t &supp_flag)
void SetKValue (const Short_t &temp_kval)
void SetNPileUps (UChar_t npileups)
void SetPUHit (UChar_t puhit)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &val)
void SetWaveform (const std::vector< Short_t > &val)
bool TestHitBit (EBitFlag flag) const
Static Public Member Functions
static bool CompareEnergy (const TGriffinHit *, const TGriffinHit *)
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Protected Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
Float_t fCharge {0.}
Short_t fKValue {0}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Protected Attributes
static TVector3 fBeamDirection
Private Member Functions
Double_t GetDefaultDistance () const
void SetGriffinFlag (EGriffinHitBits, Bool_t set)
Private Attributes
Bool_t fBremSuppressed_flag {false}
TChannel * fChannel {nullptr}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Int_t fFilter {0}
TTransientBits< UChar_t > fGriffinHitBits
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 50 of file TDetectorHit.h.
EGriffinHitBits
enum class TGriffinHit::EGriffinHitBits strong
Enumerator
kTotalPU1
kTotalPU2
kPUHitOffset
kPUHit1
kPUHit2
kBit4
kBit5
kBit6
kBit7
Definition at line 20 of file TGriffinHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 77 of file TDetectorHit.h.
Constructor & Destructor Documentation
TGriffinHit() [1/3]
TGriffinHit::TGriffinHit ()
Definition at line 11 of file TGriffinHit.cxx.
TGriffinHit() [2/3]
TGriffinHit::TGriffinHit (const TGriffinHit & rhs)
Definition at line 20 of file TGriffinHit.cxx.
References Clear(), and Copy().
TGriffinHit() [3/3]
TGriffinHit::TGriffinHit (const TFragment & frag)
Definition at line 27 of file TGriffinHit.cxx.
References TFragment::GetNumberOfPileups(), and SetNPileUps().
~TGriffinHit()
TGriffinHit::~TGriffinHit () override default
Member Function Documentation
Add()
void TGriffinHit::Add (const TDetectorHit * hit) override virtual
!
Reimplemented from TDetectorHit.
Definition at line 99 of file TGriffinHit.cxx.
References CompareEnergy(), TDetectorHit::GetAddress(), TDetectorHit::GetCfd(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TDetectorHit::GetTime(), NPileUps(), PUHit(), TDetectorHit::SetAddress(), TDetectorHit::SetCfd(), TDetectorHit::SetCharge(), TDetectorHit::SetEnergy(), TDetectorHit::SetKValue(), SetNPileUps(), SetPUHit(), and TDetectorHit::SetTime().
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & val) inline inherited
!
Definition at line 122 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 124 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 150 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TTACHit::TempCorrectedCharge(), and TFippsTACHit::TempCorrectedCharge().
Clear()
void TGriffinHit::Clear (Option_t * opt = "") override
!
Definition at line 58 of file TGriffinHit.cxx.
References TDetectorHit::Clear(), fBremSuppressed_flag, fFilter, and fGriffinHitBits.
Referenced by TGriffinHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 181 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 176 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 100 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy() [1/2]
bool TGriffinHit::CompareEnergy (const TGriffinHit * lhs, const TGriffinHit * rhs) static
!
Definition at line 94 of file TGriffinHit.cxx.
References TDetectorHit::GetEnergy().
Referenced by Add().
CompareEnergy() [2/2]
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 217 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TGriffinHit::Copy (TObject & rhs) const override
!
Definition at line 34 of file TGriffinHit.cxx.
References TDetectorHit::Copy(), fBremSuppressed_flag, fFilter, and fGriffinHitBits.
Referenced by TGriffinHit(), and Copy().
Copy() [2/2]
void TGriffinHit::Copy (TObject & obj, bool waveform) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 43 of file TGriffinHit.cxx.
References Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 127 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::Copy(), TTipHit::Copy(), TZeroDegreeHit::Copy(), TDetectorHit::Copy(), TDescantHit::Copy(), TEmmaHit::Copy(), Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), and TTdrTigressHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 148 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharcHit::GetBackAddress(), TSharcHit::GetFrontAddress(), GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharcHit::GetPadAddress(), TEagleHit::Print(), TPinDiodeHit::Print(), TFragment::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
UShort_t TGriffinHit::GetArrayNumber () const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 61 of file TGriffinHit.h.
References TDetectorHit::GetCrystal(), and TDetectorHit::GetDetector().
Referenced by CrossTalk::FillHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 187 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TTigressHit::GetDoppler(), and TSiLiHit::GetDoppler().
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Reimplemented in TDescantHit, and TZeroDegreeHit.
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), DefaultSuppression(), TFragment::Get4GCfd(), TSharcHit::GetSomeTime(), TDetectorHit::GetTime(), TEagleHit::Print(), TFragment::Print(), and TTigressHit::SumHit().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 153 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
int TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 222 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 62 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by TSiLiHit::TSiLiHit(), ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharcHit::GetBackCharge(), TSharcHit::GetFrontCharge(), TSharcHit::GetPadCharge(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TCSM::MakeHit(), TTigressHit::Print(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 208 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TGriffinBgoHit::GetArrayNumber(), GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TTigress::GetPosition(), GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), Print(), TFippsHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 265 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDefaultDistance()
Double_t TGriffinHit::GetDefaultDistance () const inline private
Definition at line 84 of file TGriffinHit.h.
Referenced by GetPosition().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 190 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TDetectorHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TSharc::GetDeadLayerThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TDescantHit::GetPosition(), TTrificHit::GetPosition(), TTigress::GetPosition(), GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TDescantHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TSceptarHit::GetPosition(), TSharcHit::GetPosition(), TEagleHit::GetPosition(), TPinDiodeHit::GetPosition(), TFippsLaBrHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TDescantHit::Print(), Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TSharcHit::Print(), TTACHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), and PromptCoincidence().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Reimplemented in TCSMHit, TSharcHit, and TSiLiHit.
Definition at line 77 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFippsHit::CompareEnergy(), CompareEnergy(), TIfinHit::CompareEnergy(), TTdrCloverHit::CompareEnergy(), TTdrTigressHit::CompareEnergy(), TTigressHit::CompareEnergy(), TDetectorHit::CompareEnergy(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), ExampleFragmentSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TSharcHit::GetDeltaBackE(), TSharcHit::GetDeltaE(), TSharcHit::GetDeltaFrontE(), TTigressHit::GetDoppler(), TSharcHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TSharcHit::GetPadE(), TDetectorHit::GetTime(), TFragment::GetTZero(), MakeAnalysisHistograms(), MakeGRIFFINEnergyHsts(), TDetectorHit::operator<(), TDescantHit::Print(), Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), and TTigressHit::SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 100 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFilterPattern()
Int_t TGriffinHit::GetFilterPattern () const inline
!
Definition at line 48 of file TGriffinHit.h.
References fFilter.
GetIsBremSuppressed()
Bool_t TGriffinHit::GetIsBremSuppressed () const inline
Definition at line 63 of file TGriffinHit.h.
References fBremSuppressed_flag.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 151 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 164 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by EfficiencyHelper::EndOfSort(), TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetNoCTEnergy()
Double_t TGriffinHit::GetNoCTEnergy (Option_t * opt = "") const
Definition at line 170 of file TGriffinHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), and TDetectorHit::GetKValue().
Referenced by TGriffin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), and CrossTalk::FillHistograms().
GetPosition() [1/3]
TVector3 TGriffinHit::GetPosition () const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 89 of file TGriffinHit.cxx.
References GetDefaultDistance(), and GetPosition().
Referenced by GetPosition(), and Print().
GetPosition() [2/3]
TVector3 TGriffinHit::GetPosition (double dist) const override
!
Definition at line 84 of file TGriffinHit.cxx.
References TDetectorHit::GetCrystal(), TDetectorHit::GetDetector(), and TGriffin::GetPosition().
Referenced by ComptonHists(), and AngularCorrelationSelector::FillHistograms().
GetPosition() [3/3]
virtual TVector3 TDetectorHit::GetPosition (Double_t) const inline virtual inherited
!
Reimplemented in TDescantHit, TLaBrHit, TPacesHit, TSceptarHit, TSharcHit, TSiLiHit, TEagleHit, TPinDiodeHit, TFippsLaBrHit, TTdrPlasticHit, TTdrSiLiHit, TTigressHit, TEmmaHit, and TCSMHit.
Definition at line 139 of file TDetectorHit.h.
References TDetectorHit::GetPosition().
Referenced by TDetectorHit::GetPosition().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 249 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 199 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TGriffinBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TSharcHit::GetBackStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and TSiLiHit::SumHit().
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 49 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleTreeHelper::Exec(), TSiLi::fCoincidenceTime(), ExampleTreeSelector::FillHistograms(), TSharcHit::GetDeltaBackT(), TSharcHit::GetDeltaFrontT(), TSharcHit::GetDeltaT(), TSharcHit::GetPadT(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TDetectorHit::Print(), TDescantHit::Print(), Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TTACHit::TempCorrectedCharge(), TFippsTACHit::TempCorrectedCharge(), TimeRandom(), and TimeRandom().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 281 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 143 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TTigressHit::Print(), TEagleHit::Print(), and TFragment::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 231 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by DirectoryHelper::Exec(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), and Print().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 240 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 152 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 108 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TFragment::Print(), and TPulseAnalyzer::SetData().
InFilter()
bool TGriffinHit::InFilter (Int_t)
!
Definition at line 51 of file TGriffinHit.cxx.
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 196 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 195 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 198 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 197 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
MakeBremSuppressed()
void TGriffinHit::MakeBremSuppressed (const Bool_t & supp_flag) inline
Definition at line 65 of file TGriffinHit.h.
References fBremSuppressed_flag.
NPileUps()
UShort_t TGriffinHit::NPileUps () const
Definition at line 140 of file TGriffinHit.cxx.
References fGriffinHitBits, kTotalPU1, kTotalPU2, and TTransientBits< T >::TestBits().
Referenced by Add().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 94 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
Print() [1/2]
void TGriffinHit::Print (Option_t * opt = "") const override
!
Definition at line 67 of file TGriffinHit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TGriffinHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 73 of file TGriffinHit.cxx.
References TDetectorHit::fTimeStamp, TDetectorHit::GetCrystal(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), GetPosition(), TDetectorHit::GetTime(), and TDetectorHit::GetTimeStampNs().
PUHit()
UShort_t TGriffinHit::PUHit () const
Definition at line 146 of file TGriffinHit.cxx.
References fGriffinHitBits, kPUHit1, kPUHit2, kPUHitOffset, and TTransientBits< T >::TestBits().
Referenced by Add().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), TEmma::BuildHits(), and TTigressHit::SumHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & val) inline virtual inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 120 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & energy) const inline inherited
Definition at line 126 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetFilterPattern()
void TGriffinHit::SetFilterPattern (const int & x) inline
!
Definition at line 45 of file TGriffinHit.h.
References fFilter.
SetGriffinFlag()
void TGriffinHit::SetGriffinFlag (EGriffinHitBits flag, Bool_t set) private
Definition at line 135 of file TGriffinHit.cxx.
References fGriffinHitBits, and TTransientBits< T >::SetBit().
Referenced by SetNPileUps(), and SetPUHit().
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 288 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetIsBremSuppressed()
void TGriffinHit::SetIsBremSuppressed (const Bool_t & supp_flag) inline
Definition at line 64 of file TGriffinHit.h.
References fBremSuppressed_flag.
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetNPileUps()
void TGriffinHit::SetNPileUps (UChar_t npileups)
Definition at line 153 of file TGriffinHit.cxx.
References kTotalPU1, kTotalPU2, and SetGriffinFlag().
Referenced by TGriffinHit(), and Add().
SetPUHit()
void TGriffinHit::SetPUHit (UChar_t puhit)
Definition at line 159 of file TGriffinHit.cxx.
References kPUHit1, kPUHit2, kPUHitOffset, and SetGriffinFlag().
Referenced by Add().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 132 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 123 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TEmma::BuildHits().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & val) inline inherited
!
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), and TTdrPlasticHit::TTdrPlasticHit().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 202 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), and TSiLiHit::GetEnergy().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} protected inherited
address of the the channel in the DAQ.
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), TFragment::GetSharcMesyBoard(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static protected inherited
Definition at line 224 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable protected inherited
Definition at line 223 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TTdrCloverHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TTdrCloverHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TTdrCloverHit::NPileUps(), TTdrCloverHit::PUHit(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), and TDetectorHit::TestHitBit().
fBremSuppressed_flag
Bool_t TGriffinHit::fBremSuppressed_flag {false} private
! Bremsstrahlung Suppression flag.
Definition at line 41 of file TGriffinHit.h.
Referenced by Clear(), Copy(), GetIsBremSuppressed(), MakeBremSuppressed(), and SetIsBremSuppressed().
fCfd
Float_t TDetectorHit::fCfd {0} protected inherited
CFD time of the Hit.
Definition at line 208 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDescantHit::GetCfd(), TZeroDegreeHit::GetCfd(), TDescantHit::GetRemainder(), TZeroDegreeHit::GetRemainder(), TTigressHit::GetTimeToTrigger(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 218 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} protected inherited
charge collected from the hit
Definition at line 206 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 217 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 214 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fFilter
Int_t TGriffinHit::fFilter {0} private
The Filter Word.
Definition at line 39 of file TGriffinHit.h.
Referenced by Clear(), Copy(), GetFilterPattern(), and SetFilterPattern().
fGriffinHitBits
TTransientBits<UChar_t> TGriffinHit::fGriffinHitBits private
Transient Member Flags.
Definition at line 40 of file TGriffinHit.h.
Referenced by Clear(), Copy(), NPileUps(), PUHit(), and SetGriffinFlag().
fKValue
Short_t TDetectorHit::fKValue {0} protected inherited
integration value.
Definition at line 207 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), and TDetectorHit::SetKValue().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 215 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fTime
Double_t TDetectorHit::fTime {0.} mutable protected inherited
! Calibrated Time of the hit
Definition at line 211 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} protected inherited
Timestamp given to hit in ns.
Definition at line 209 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), TTigressHit::GetTimeToTrigger(), Print(), and TDetectorHit::SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform protected inherited
Definition at line 210 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::SetWaveform().