GRSISort: TEmmaHit Class Reference
TEmmaHit Class Reference
Detectors
Detailed Description
Definition at line 18 of file TEmmaHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TEmmaHit ()
TEmmaHit (const TEmmaHit &)
TEmmaHit (const TFragment &frag)
~TEmmaHit () override
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &x)
virtual void AppendTimeStamp (const Long64_t &x)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool) const override
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
Double_t GetBottom () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual Short_t GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Short_t GetFailedFill () const
Int_t GetFilterPattern () const
virtual Short_t GetKValue () const
Double_t GetLeft () const
const char * GetName () const override
TVector3 GetPosition () const override
TVector3 GetPosition (double delayL, double delayR, double delayT, double delayB) const
TVector3 GetPosition (Double_t) const override
EPpgPattern GetPPGStatus () const
Double_t GetRight () const
virtual Int_t GetSegment () const
Short_t GetTdcNumber () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
Double_t GetTop () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool InFilter (Int_t)
bool operator< (const TDetectorHit &rhs) const
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void SetAddress (const UInt_t &temp_address)
void SetAnodeTrigger (double q)
void SetBottom (double q)
virtual void SetCfd (const Float_t &x)
virtual void SetCfd (const Int_t &x)
virtual void SetCfd (const uint32_t &x)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &en) const
void SetFailedFill (int n)
void SetFilterPattern (const int &x)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
void SetLeft (double q)
void SetRight (double q)
void SetTdcNumber (int n)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &x)
void SetTop (double q)
void SetWaveform (const std::vector< Short_t > &x)
bool TestHitBit (EBitFlag flag) const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Protected Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
Float_t fCharge {0.}
Short_t fKValue {0}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Protected Attributes
static TVector3 fBeamDirection
Private Attributes
Double_t fAnodeTrigger {0}
Double_t fBottom {0}
TChannel * fChannel {nullptr}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Short_t fFail {0}
Int_t fFilter {0}
Double_t fICSum {0}
Double_t fLeft {0}
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Double_t fRight {0}
Double_t fSiE {0}
Short_t fTdcNumber {0}
Double_t fTop {0}
Static Private Attributes
static double fBdelay = 20
static double fLdelay = 40
static double fRdelay = 20
static double fTdelay = 10
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 52 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 79 of file TDetectorHit.h.
Constructor & Destructor Documentation
TEmmaHit() [1/3]
TEmmaHit::TEmmaHit ()
Definition at line 14 of file TEmmaHit.cxx.
References Clear().
TEmmaHit() [2/3]
TEmmaHit::TEmmaHit (const TEmmaHit & rhs)
Definition at line 22 of file TEmmaHit.cxx.
References Clear(), and Copy().
TEmmaHit() [3/3]
TEmmaHit::TEmmaHit (const TFragment & frag) inline
Definition at line 22 of file TEmmaHit.h.
~TEmmaHit()
TEmmaHit::~TEmmaHit () override default
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TGriffinHit, TFippsHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 193 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & x) inline inherited
!
Definition at line 126 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 128 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 154 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TTACHit::TempCorrectedCharge(), and TFippsTACHit::TempCorrectedCharge().
Clear()
void TEmmaHit::Clear (Option_t * opt = "") override
!
Definition at line 62 of file TEmmaHit.cxx.
References TDetectorHit::Clear(), and fFilter.
Referenced by TEmmaHit(), and TEmmaHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 185 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 180 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 104 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 219 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TEmmaHit::Copy (TObject & rhs) const override
!
Definition at line 33 of file TEmmaHit.cxx.
References TDetectorHit::Copy(), fAnodeTrigger, fBottom, fFail, fFilter, fICSum, fLeft, fRight, fTdcNumber, and fTop.
Referenced by TEmmaHit(), and Copy().
Copy() [2/2]
void TEmmaHit::Copy (TObject & rhs, bool waveform) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 47 of file TEmmaHit.cxx.
References Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 134 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::Copy(), TTipHit::Copy(), TZeroDegreeHit::Copy(), TDetectorHit::Copy(), TDescantHit::Copy(), Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), and TTdrTigressHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 152 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharcHit::GetBackAddress(), TSharcHit::GetFrontAddress(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharcHit::GetPadAddress(), TEagleHit::Print(), TPinDiodeHit::Print(), TFragment::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TGriffinBgoHit, TGriffinHit, TLaBrBgoHit, TTigressHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TIfinBgoHit, TIfinHit, TBgoHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 172 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 191 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TTigressHit::GetDoppler(), and TSiLiHit::GetDoppler().
GetBottom()
Double_t TEmmaHit::GetBottom () const inline
Definition at line 49 of file TEmmaHit.h.
References fBottom.
Referenced by TEmma::BuildHits(), GetPosition(), and GetPosition().
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Reimplemented in TDescantHit, and TZeroDegreeHit.
Definition at line 151 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), DefaultSuppression(), TFragment::Get4GCfd(), TSharcHit::GetSomeTime(), TDetectorHit::GetTime(), TEagleHit::Print(), TFragment::Print(), and TTigressHit::SumHit().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 157 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
Short_t TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 224 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 69 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by TSiLiHit::TSiLiHit(), ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharcHit::GetBackCharge(), TSharcHit::GetFrontCharge(), TSharcHit::GetPadCharge(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TCSM::MakeHit(), TTigressHit::Print(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 210 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TGriffinHit::Print(), TFippsHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 267 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 192 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TDetectorHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TSharc::GetDeadLayerThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TDescantHit::GetPosition(), TTrificHit::GetPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TDescantHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TSceptarHit::GetPosition(), TSharcHit::GetPosition(), TEagleHit::GetPosition(), TPinDiodeHit::GetPosition(), TFippsLaBrHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TSharcHit::Print(), TTACHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), and PromptCoincidence().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Reimplemented in TCSMHit, TSharcHit, and TSiLiHit.
Definition at line 84 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFippsHit::CompareEnergy(), TGriffinHit::CompareEnergy(), TIfinHit::CompareEnergy(), TTdrCloverHit::CompareEnergy(), TTdrTigressHit::CompareEnergy(), TTigressHit::CompareEnergy(), TDetectorHit::CompareEnergy(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), ExampleFragmentSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TSharcHit::GetDeltaBackE(), TSharcHit::GetDeltaE(), TSharcHit::GetDeltaFrontE(), TTigressHit::GetDoppler(), TSharcHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TSharcHit::GetPadE(), TDetectorHit::GetTime(), TFragment::GetTZero(), MakeAnalysisHistograms(), MakeGRIFFINEnergyHsts(), TDetectorHit::operator<(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), and TTigressHit::SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 107 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFailedFill()
Short_t TEmmaHit::GetFailedFill () const inline
Definition at line 52 of file TEmmaHit.h.
References fFail.
GetFilterPattern()
Int_t TEmmaHit::GetFilterPattern () const inline
!
Definition at line 41 of file TEmmaHit.h.
References fFilter.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 155 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), and MakeGRIFFINChargeHsts().
GetLeft()
Double_t TEmmaHit::GetLeft () const inline
Definition at line 46 of file TEmmaHit.h.
References fLeft.
Referenced by TEmma::BuildHits(), GetPosition(), and GetPosition().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 166 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by EfficiencyHelper::EndOfSort(), TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPosition() [1/3]
TVector3 TEmmaHit::GetPosition () const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 82 of file TEmmaHit.cxx.
References fBdelay, fLdelay, fRdelay, fTdelay, GetBottom(), GetLeft(), TEmma::GetPosition(), GetRight(), and GetTop().
GetPosition() [2/3]
TVector3 TEmmaHit::GetPosition (double delayL, double delayR, double delayT, double delayB) const
!
Definition at line 87 of file TEmmaHit.cxx.
References GetBottom(), GetLeft(), TEmma::GetPosition(), GetRight(), and GetTop().
GetPosition() [3/3]
TVector3 TEmmaHit::GetPosition (Double_t) const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 44 of file TEmmaHit.h.
References GetPosition().
Referenced by GetPosition().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 251 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetRight()
Double_t TEmmaHit::GetRight () const inline
Definition at line 47 of file TEmmaHit.h.
References fRight.
Referenced by TEmma::BuildHits(), GetPosition(), and GetPosition().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 201 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TGriffinBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TSharcHit::GetBackStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and TSiLiHit::SumHit().
GetTdcNumber()
Short_t TEmmaHit::GetTdcNumber () const inline
Definition at line 50 of file TEmmaHit.h.
References fTdcNumber.
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 56 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleTreeHelper::Exec(), TSiLi::fCoincidenceTime(), ExampleTreeSelector::FillHistograms(), TSharcHit::GetDeltaBackT(), TSharcHit::GetDeltaFrontT(), TSharcHit::GetDeltaT(), TSharcHit::GetPadT(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TDetectorHit::Print(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TTACHit::TempCorrectedCharge(), TFippsTACHit::TempCorrectedCharge(), TimeRandom(), and TimeRandom().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 283 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TTigressHit::Print(), TEagleHit::Print(), and TFragment::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 233 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by DirectoryHelper::Exec(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), and TGriffinHit::Print().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 242 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetTop()
Double_t TEmmaHit::GetTop () const inline
Definition at line 48 of file TEmmaHit.h.
References fTop.
Referenced by TEmma::BuildHits(), GetPosition(), and GetPosition().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 156 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 112 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TFragment::Print(), and TPulseAnalyzer::SetData().
InFilter()
bool TEmmaHit::InFilter (Int_t)
!
Definition at line 55 of file TEmmaHit.cxx.
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 200 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 199 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 202 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 201 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 97 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
Print() [1/2]
void TEmmaHit::Print (Option_t * opt = "") const override
!
Definition at line 68 of file TEmmaHit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TEmmaHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 73 of file TEmmaHit.cxx.
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), TEmma::BuildHits(), and TTigressHit::SumHit().
SetAnodeTrigger()
void TEmmaHit::SetAnodeTrigger (double q) inline
Definition at line 36 of file TEmmaHit.h.
References fAnodeTrigger.
Referenced by TEmma::BuildHits().
SetBottom()
void TEmmaHit::SetBottom (double q) inline
Definition at line 35 of file TEmmaHit.h.
References fBottom.
Referenced by TEmma::BuildHits().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & x) inline virtual inherited
!
Definition at line 122 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 124 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 123 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 120 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & en) const inline inherited
Definition at line 130 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetFailedFill()
void TEmmaHit::SetFailedFill (int n) inline
Definition at line 38 of file TEmmaHit.h.
References fFail.
Referenced by TEmma::BuildHits().
SetFilterPattern()
void TEmmaHit::SetFilterPattern (const int & x) inline
!
Definition at line 30 of file TEmmaHit.h.
References fFilter.
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 290 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetLeft()
void TEmmaHit::SetLeft (double q) inline
Definition at line 32 of file TEmmaHit.h.
References fLeft.
Referenced by TEmma::BuildHits().
SetRight()
void TEmmaHit::SetRight (double q) inline
Definition at line 33 of file TEmmaHit.h.
References fRight.
Referenced by TEmma::BuildHits().
SetTdcNumber()
void TEmmaHit::SetTdcNumber (int n) inline
Definition at line 37 of file TEmmaHit.h.
References fTdcNumber.
Referenced by TEmma::AddFragment().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 136 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 127 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TEmma::BuildHits().
SetTop()
void TEmmaHit::SetTop (double q) inline
Definition at line 34 of file TEmmaHit.h.
References fTop.
Referenced by TEmma::BuildHits().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & x) inline inherited
!
Definition at line 125 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), and TTdrPlasticHit::TTdrPlasticHit().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 206 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), and TSiLiHit::GetEnergy().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} protected inherited
address of the the channel in the DAQ.
Definition at line 209 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), TFragment::GetSharcMesyBoard(), and TDetectorHit::SetAddress().
fAnodeTrigger
Double_t TEmmaHit::fAnodeTrigger {0} private
Definition at line 69 of file TEmmaHit.h.
Referenced by Copy(), and SetAnodeTrigger().
fBdelay
double TEmmaHit::fBdelay = 20 static private
Definition at line 77 of file TEmmaHit.h.
Referenced by GetPosition().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static protected inherited
Definition at line 228 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable protected inherited
Definition at line 227 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TTdrCloverHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TTdrCloverHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TTdrCloverHit::NPileUps(), TTdrCloverHit::PUHit(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), and TDetectorHit::TestHitBit().
fBottom
Double_t TEmmaHit::fBottom {0} private
Definition at line 68 of file TEmmaHit.h.
Referenced by Copy(), GetBottom(), and SetBottom().
fCfd
Float_t TDetectorHit::fCfd {0} protected inherited
CFD time of the Hit.
Definition at line 212 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDescantHit::GetCfd(), TZeroDegreeHit::GetCfd(), TDescantHit::GetRemainder(), TZeroDegreeHit::GetRemainder(), TTigressHit::GetTimeToTrigger(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 222 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} protected inherited
charge collected from the hit
Definition at line 210 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 221 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 218 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fFail
Short_t TEmmaHit::fFail {0} private
Definition at line 72 of file TEmmaHit.h.
Referenced by Copy(), GetFailedFill(), and SetFailedFill().
fFilter
Int_t TEmmaHit::fFilter {0} private
Definition at line 26 of file TEmmaHit.h.
Referenced by Clear(), Copy(), GetFilterPattern(), and SetFilterPattern().
fICSum
Double_t TEmmaHit::fICSum {0} private
Definition at line 71 of file TEmmaHit.h.
Referenced by Copy().
fKValue
Short_t TDetectorHit::fKValue {0} protected inherited
integration value.
Definition at line 211 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), and TDetectorHit::SetKValue().
fLdelay
double TEmmaHit::fLdelay = 40 static private
Definition at line 74 of file TEmmaHit.h.
Referenced by GetPosition().
fLeft
Double_t TEmmaHit::fLeft {0} private
Definition at line 65 of file TEmmaHit.h.
Referenced by Copy(), GetLeft(), and SetLeft().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 219 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fRdelay
double TEmmaHit::fRdelay = 20 static private
Definition at line 75 of file TEmmaHit.h.
Referenced by GetPosition().
fRight
Double_t TEmmaHit::fRight {0} private
Definition at line 66 of file TEmmaHit.h.
Referenced by Copy(), GetRight(), and SetRight().
fSiE
Double_t TEmmaHit::fSiE {0} private
Definition at line 73 of file TEmmaHit.h.
fTdcNumber
Short_t TEmmaHit::fTdcNumber {0} private
Definition at line 70 of file TEmmaHit.h.
Referenced by Copy(), GetTdcNumber(), and SetTdcNumber().
fTdelay
double TEmmaHit::fTdelay = 10 static private
Definition at line 76 of file TEmmaHit.h.
Referenced by GetPosition().
fTime
Double_t TDetectorHit::fTime {0.} mutable protected inherited
! Calibrated Time of the hit
Definition at line 215 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} protected inherited
Timestamp given to hit in ns.
Definition at line 213 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), TTigressHit::GetTimeToTrigger(), TGriffinHit::Print(), and TDetectorHit::SetTimeStamp().
fTop
Double_t TEmmaHit::fTop {0} private
Definition at line 67 of file TEmmaHit.h.
Referenced by Copy(), GetTop(), and SetTop().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform protected inherited
Definition at line 214 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::SetWaveform().