GRSISort: TEagle Class Reference
TEagle Class Reference
Detectors
Detailed Description
The TEagle class defines the observables and algorithms used when analyzing EAGLE data. It includes detector positions, etc.
Definition at line 28 of file TEagle.h.
Public Member Functions
TEagle ()
TEagle (const TEagle &rhs)
~TEagle () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TEagleHit * GetEagleHit (const int &i) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TPinDiodeHit * GetPinDiodeHit (const int &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TEagle & operator= (const TEagle &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static ROOT::Math::Polar3DVector GetPinDiodePosition (int DetNbr)
static ROOT::Math::Polar3DVector GetPosition (int DetNbr)
Private Attributes
uint32_t fEventNumber
std::vector< TDetectorHit * > fHits
std::vector< TPinDiodeHit * > fPinDiodeHits
uint16_t fUsTime
Static Private Attributes
static ROOT::Math::Polar3DVector gDetectorPosition [17]
static ROOT::Math::Polar3DVector gDiodePosition [49]
Constructor & Destructor Documentation
TEagle() [1/2]
TEagle::TEagle ()
Definition at line 89 of file TEagle.cxx.
References Clear().
~TEagle()
TEagle::~TEagle () override
Definition at line 107 of file TEagle.cxx.
TEagle() [2/2]
TEagle::TEagle (const TEagle & rhs)
Definition at line 98 of file TEagle.cxx.
References Copy().
Member Function Documentation
AddFragment()
void TEagle::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 139 of file TEagle.cxx.
References fEventNumber, TDetector::fHits, fPinDiodeHits, and fUsTime.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TEagle::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 39 of file TEagle.h.
Clear()
void TEagle::Clear (Option_t * opt = "all") override
!
Clears the parent and all of the hits
Definition at line 130 of file TEagle.cxx.
References TDetector::Clear(), fEventNumber, fPinDiodeHits, and fUsTime.
Referenced by TEagle().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TEagle::Copy (TObject & rhs) const override
!
Copy function
Definition at line 118 of file TEagle.cxx.
References TDetector::Copy(), fEventNumber, fPinDiodeHits, and fUsTime.
Referenced by TEagle(), and operator=().
GetEagleHit()
TEagleHit * TEagle::GetEagleHit (const int & i) const inline
Definition at line 34 of file TEagle.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPinDiodeHit()
TPinDiodeHit * TEagle::GetPinDiodeHit (const int & i) const
Definition at line 158 of file TEagle.cxx.
References fPinDiodeHits.
GetPinDiodePosition()
static ROOT::Math::Polar3DVector TEagle::GetPinDiodePosition (int DetNbr) inline static
!
Definition at line 42 of file TEagle.h.
References gDiodePosition.
Referenced by TPinDiodeHit::GetPosition().
GetPosition()
static ROOT::Math::Polar3DVector TEagle::GetPosition (int DetNbr) inline static
!
Definition at line 41 of file TEagle.h.
References gDetectorPosition.
Referenced by TEagleHit::GetPosition().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TGriffin::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TGriffin::GetGriffinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=()
TEagle & TEagle::operator= (const TEagle & rhs)
!
Definition at line 112 of file TEagle.cxx.
References Copy().
Print() [1/2]
void TEagle::Print (Option_t * opt = "") const override
!
Prints out TEagle information
Definition at line 168 of file TEagle.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TEagle::Print (std::ostream & out) const override virtual
!
Prints out TEagle information
Reimplemented from TDetector.
Definition at line 174 of file TEagle.cxx.
References fEventNumber, TDetector::fHits, fPinDiodeHits, and fUsTime.
Member Data Documentation
fEventNumber
uint32_t TEagle::fEventNumber private
event number
Definition at line 51 of file TEagle.h.
Referenced by AddFragment(), Clear(), Copy(), and Print().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fPinDiodeHits
std::vector<TPinDiodeHit*> TEagle::fPinDiodeHits private
vector of pin diode hits
Definition at line 50 of file TEagle.h.
Referenced by AddFragment(), Clear(), Copy(), GetPinDiodeHit(), and Print().
fUsTime
uint16_t TEagle::fUsTime private
time in microseconds
Definition at line 52 of file TEagle.h.
Referenced by AddFragment(), Clear(), Copy(), and Print().
gDetectorPosition
ROOT::Math::Polar3DVector TEagle::gDetectorPosition static private
Initial value:
= {
   ROOT::Math::Polar3DVector(1., 101./180.*TMath::Pi(),   0./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  37./180.*TMath::Pi(), 324./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  79./180.*TMath::Pi(),  36./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 101./180.*TMath::Pi(), 144./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 143./180.*TMath::Pi(), 288./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  37./180.*TMath::Pi(), 180./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 101./180.*TMath::Pi(),  72./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 143./180.*TMath::Pi(),   0./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 143./180.*TMath::Pi(),  72./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  37./180.*TMath::Pi(), 108./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  79./180.*TMath::Pi(), 324./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 143./180.*TMath::Pi(), 144./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 101./180.*TMath::Pi(), 216./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  79./180.*TMath::Pi(), 180./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  37./180.*TMath::Pi(),  36./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1.,  37./180.*TMath::Pi(), 252./180.*TMath::Pi()),
   ROOT::Math::Polar3DVector(1., 143./180.*TMath::Pi(), 216./180.*TMath::Pi())}
! Position of each detector (plus one default position)
Definition at line 12 of file TEagle.h.
Referenced by GetPosition().
gDiodePosition
ROOT::Math::Polar3DVector TEagle::gDiodePosition static private
! Position of each diode
Definition at line 32 of file TEagle.h.
Referenced by GetPinDiodePosition().