GRSISort: TDecayFit Class Reference
TDecayFit Class Reference
Fitting & Analysis
Detailed Description
Definition at line 25 of file TDecay.h.
Public Member Functions
TDecayFit ()=default
TDecayFit (const char *name, const char *formula, Double_t xmin=0, Double_t xmax=1)
template<class PtrObj , typename MemFn >
TDecayFit (const char *name, const PtrObj &p, MemFn memFn, Double_t xmin, Double_t xmax, Int_t npar, const char *className=nullptr, const char *methodName=nullptr)
TDecayFit (const char *name, const ROOT::Math::ParamFunctor &f, Double_t xmin=0, Double_t xmax=1, Int_t npar=0)
TDecayFit (const char *name, Double_t xmin, Double_t xmax, Int_t npar)
TDecayFit (const char *name, Double_t(*fcn)(const Double_t *, const Double_t *), Double_t xmin=0, Double_t xmax=1, Int_t npar=0)
TDecayFit (const char *name, Double_t(*fcn)(Double_t *, Double_t *), Double_t xmin=0, Double_t xmax=1, Int_t npar=0)
template<typename Func >
TDecayFit (const char *name, Func f, Double_t xmin, Double_t xmax, Int_t npar, const char *className=nullptr)
TDecayFit (const TDecayFit &)=default
TDecayFit (TDecayFit &&) noexcept=default
~TDecayFit ()=default
void DrawComponents () const
void DrawResiduals ()
TFitResultPtr Fit (TH1 *hist, Option_t *opt="")
TVirtualDecay * GetDecay () const
TGraph * GetResiduals ()
TDecayFit & operator= (const TDecayFit &)=default
TDecayFit & operator= (TDecayFit &&) noexcept=default
void Print (Option_t *opt="") const override
void SetDecay (TVirtualDecay *decay)
void UpdateResiduals (TH1 *hist)
Private Member Functions
void DefaultGraphs ()
Private Attributes
TVirtualDecay * fDecay {nullptr}
TGraph fResiduals
Constructor & Destructor Documentation
TDecayFit() [1/10]
TDecayFit::TDecayFit () default
TDecayFit() [2/10]
TDecayFit::TDecayFit (const char * name, const char * formula, Double_t xmin = 0, Double_t xmax = 1) inline
Definition at line 28 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [3/10]
TDecayFit::TDecayFit (const char * name, Double_t xmin, Double_t xmax, Int_t npar) inline
Definition at line 33 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [4/10]
TDecayFit::TDecayFit (const char * name, const ROOT::Math::ParamFunctor & f, Double_t xmin = 0, Double_t xmax = 1, Int_t npar = 0) inline
Definition at line 37 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [5/10]
TDecayFit::TDecayFit (const char * name, Double_t(* fcn)(Double_t *, Double_t *), Double_t xmin = 0, Double_t xmax = 1, Int_t npar = 0) inline
Definition at line 43 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [6/10]
TDecayFit::TDecayFit (const char * name, Double_t(* fcn)(const Double_t *, const Double_t *), Double_t xmin = 0, Double_t xmax = 1, Int_t npar = 0) inline
Definition at line 48 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [7/10]
template<class PtrObj , typename MemFn > TDecayFit::TDecayFit (const char * name, const PtrObj & p, MemFn memFn, Double_t xmin, Double_t xmax, Int_t npar, const char * className = nullptr, const char * methodName = nullptr) inline
Definition at line 56 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [8/10]
template<typename Func > TDecayFit::TDecayFit (const char * name, Func f, Double_t xmin, Double_t xmax, Int_t npar, const char * className = nullptr) inline
Definition at line 64 of file TDecay.h.
References DefaultGraphs().
TDecayFit() [9/10]
TDecayFit::TDecayFit (const TDecayFit &) default
TDecayFit() [10/10]
TDecayFit::TDecayFit (TDecayFit &&) default noexcept
~TDecayFit()
TDecayFit::~TDecayFit () default
Member Function Documentation
DefaultGraphs()
void TDecayFit::DefaultGraphs () private
Definition at line 54 of file TDecay.cxx.
References fResiduals.
Referenced by TDecayFit(), TDecayFit(), TDecayFit(), TDecayFit(), TDecayFit(), TDecayFit(), and TDecayFit().
DrawComponents()
void TDecayFit::DrawComponents () const
This draws the individual components on the current canvas
Definition at line 15 of file TDecay.cxx.
References TVirtualDecay::DrawComponents(), and fDecay.
DrawResiduals()
void TDecayFit::DrawResiduals ()
Definition at line 93 of file TDecay.cxx.
References fResiduals.
Fit()
TFitResultPtr TDecayFit::Fit (TH1 * hist, Option_t * opt = "")
Definition at line 39 of file TDecay.cxx.
References hist, and UpdateResiduals().
Referenced by TDecay::Fit(), TDecayChain::Fit(), and TSingleDecay::Fit().
GetDecay()
TVirtualDecay * TDecayFit::GetDecay () const
Definition at line 34 of file TDecay.cxx.
References fDecay.
Referenced by TDecay::Fit(), and TDecay::SetParameters().
GetResiduals()
TGraph * TDecayFit::GetResiduals () inline
Definition at line 82 of file TDecay.h.
References fResiduals.
operator=() [1/2]
TDecayFit & TDecayFit::operator= (const TDecayFit &) default
operator=() [2/2]
TDecayFit & TDecayFit::operator= (TDecayFit &&) default noexcept
Print()
void TDecayFit::Print (Option_t * opt = "") const override
This prints the parameters of the fit (decay rate, intensities, etc...)
Definition at line 27 of file TDecay.cxx.
References fDecay.
SetDecay()
void TDecayFit::SetDecay (TVirtualDecay * decay)
This tells the TDecayFit which TVirtualDecay it belongs to
Definition at line 21 of file TDecay.cxx.
References fDecay.
Referenced by TDecay::TDecay(), TDecayChain::TDecayChain(), TSingleDecay::TSingleDecay(), TSingleDecay::TSingleDecay(), and TDecay::SetParameters().
UpdateResiduals()
void TDecayFit::UpdateResiduals (TH1 * hist)
GetHist()->GetBinError(i));// + GetParameter("Height") + 10.;
Definition at line 61 of file TDecay.cxx.
References fResiduals, and hist.
Referenced by Fit().
Member Data Documentation
fDecay
TVirtualDecay* TDecayFit::fDecay {nullptr} private
Definition at line 88 of file TDecay.h.
Referenced by DrawComponents(), GetDecay(), Print(), and SetDecay().
fResiduals
TGraph TDecayFit::fResiduals private
Definition at line 89 of file TDecay.h.
Referenced by DefaultGraphs(), DrawResiduals(), GetResiduals(), and UpdateResiduals().