GRSISort: TSceptar Class Reference
TSceptar Class Reference
Detectors
Detailed Description
The TSceptar class defines the observables and algorithms used when analyzing GRIFFIN data. It includes detector positions, etc.
Definition at line 27 of file TSceptar.h.
Public Member Functions
TSceptar ()
TSceptar (const TSceptar &rhs)
TSceptar (TSceptar &&) noexcept=default
~TSceptar () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TSceptarHit * GetSceptarHit (const int &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TSceptar & operator= (const TSceptar &)
TSceptar & operator= (TSceptar &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (int DetNbr)
static bool SetWave ()
Private Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static std::array< TVector3, 21 > fPaddlePosition
static bool fSetWave = false
Constructor & Destructor Documentation
TSceptar() [1/3]
TSceptar::TSceptar ()
Definition at line 32 of file TSceptar.cxx.
References TDetector::Clear().
TSceptar() [2/3]
TSceptar::TSceptar (const TSceptar & rhs)
Definition at line 40 of file TSceptar.cxx.
References TDetector::Copy().
TSceptar() [3/3]
TSceptar::TSceptar (TSceptar &&) default noexcept
~TSceptar()
TSceptar::~TSceptar () override default
Member Function Documentation
AddFragment()
void TSceptar::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 52 of file TSceptar.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TSceptar::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 40 of file TSceptar.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::TAries(), TDemand::TDemand(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TPaces::TPaces(), TSceptar(), TTAC::TTAC(), TZeroDegree::TZeroDegree(), TBgo::Clear(), TDescant::Clear(), TEagle::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TSharc2::Clear(), TSharc::Clear(), TSiLi::Clear(), TSuppressed::Clear(), TTdrPlastic::Clear(), TTdrSiLi::Clear(), TTigress::Clear(), TTrific::Clear(), and TTriFoil::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override inherited
!
Definition at line 24 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TAries::TAries(), TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TSceptar(), TTAC::TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree::TZeroDegree(), TBgo::Copy(), TDemand::Copy(), TDescant::Copy(), TEagle::Copy(), TEmma::Copy(), TPaces::Copy(), TRcmp::Copy(), TRF::Copy(), TS3::Copy(), TSharc2::Copy(), TSharc::Copy(), TSiLi::Copy(), TSuppressed::Copy(), TTdrSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TTriFoil::Copy(), TAries::operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), TFippsTAC::operator=(), TGenericDetector::operator=(), operator=(), TTAC::operator=(), TTdrPlastic::operator=(), TTip::operator=(), and TZeroDegree::operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
static TVector3 TSceptar::GetPosition (int DetNbr) inline static
!
Definition at line 42 of file TSceptar.h.
References fPaddlePosition.
Referenced by TSceptarHit::GetPosition().
GetSceptarHit()
TSceptarHit * TSceptar::GetSceptarHit (const int & i) const inline
Definition at line 36 of file TSceptar.h.
References TDetector::GetHit().
Referenced by ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), and TimeWalkSelector::FillHistograms().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TSceptar & TSceptar::operator= (const TSceptar & rhs)
!
Definition at line 46 of file TSceptar.cxx.
References TDetector::Copy().
operator=() [2/2]
TSceptar & TSceptar::operator= (TSceptar &&) default noexcept
Print() [1/2]
void TSceptar::Print (Option_t * opt = "") const override
!
Prints out TSceptar Multiplicity, currently does little.
Definition at line 58 of file TSceptar.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TSceptar::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 64 of file TSceptar.cxx.
References TDetector::GetMultiplicity().
SetWave()
static bool TSceptar::SetWave () inline static
!
Definition at line 44 of file TSceptar.h.
References fSetWave.
Referenced by TSceptarHit::TSceptarHit().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fPaddlePosition
std::array< TVector3, 21 > TSceptar::fPaddlePosition static private
Initial value:
= {
   TVector3(0, 0, 1),
   TVector3(14.3025, 4.6472, 22.8096),
   TVector3(0, 15.0386, 22.8096),
   TVector3(-14.3025, 4.6472, 22.8096),
   TVector3(-8.8395, -12.1665, 22.8096),
   TVector3(8.8395, -12.1665, 22.8096),
   TVector3(19.7051, 6.4026, 6.2123),
   TVector3(0, 20.7192, 6.2123),
   TVector3(-19.7051, 6.4026, 6.2123),
   TVector3(-12.1784, -16.7622, 6.2123),
   TVector3(12.1784, -16.7622, 6.2123),
   TVector3(19.7051, 6.4026, -6.2123),
   TVector3(0, 20.7192, -6.2123),
   TVector3(-19.7051, 6.4026, -6.2123),
   TVector3(-12.1784, -16.7622, -6.2123),
   TVector3(12.1784, -16.7622, -6.2123),
   TVector3(14.3025, 4.6472, -22.8096),
   TVector3(0, 15.0386, -22.8096),
   TVector3(-14.3025, 4.6472, -22.8096),
   TVector3(-8.8395, -12.1665, -22.8096),
   TVector3(8.8395, -12.1665, -22.8096)}
! Position of each Paddle
Definition at line 8 of file TSceptar.h.
Referenced by GetPosition().
fSetWave
bool TSceptar::fSetWave = false static private
Definition at line 47 of file TSceptar.h.
Referenced by SetWave().