GRSISort: TTimeCal Class Reference
TTimeCal Class Reference
Calibration
Detailed Description
Definition at line 10 of file TTimeCal.h.
Public Member Functions
TTimeCal ()=default
TTimeCal (const char *name, const char *title)
TTimeCal (const TTimeCal &)=default
TTimeCal (TTimeCal &&) noexcept=default
~TTimeCal ()=default
void AddParameter (Double_t param)
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
TChannel * GetChannel () const
virtual TF1 * GetFitFunction () const
TH1 * GetHist () const
virtual TNucleus * GetNucleus () const
Double_t GetParameter (size_t parameter) const override
std::vector< Double_t > GetParameters () const override
Bool_t IsGroupable () const override
TTimeCal & operator= (const TTimeCal &)=default
TTimeCal & operator= (TTimeCal &&) noexcept=default
void Print (Option_t *opt="") const override
virtual void ReadFromChannel ()
Bool_t SetChannel (TChannel *chan)
Bool_t SetChannel (UInt_t chanNum)
virtual void SetFitFunction (TF1 *func)
virtual void SetHist (TH1 *hist)
virtual void SetNucleus (TNucleus *nuc, Option_t *opt="")
void SetParameter (Int_t idx, Double_t param)
void SetParameters (std::vector< Double_t > paramVec)
virtual void WriteToAllChannels (const std::string &mnemonic="")
void WriteToChannel () const override
Protected Member Functions
void InitTCal ()
Private Attributes
TRef fChan {nullptr}
TF1 * fFitFunc {nullptr}
TH1 * fHist {nullptr}
TNucleus * fNuc {nullptr}
std::vector< Double_t > fParameters
Constructor & Destructor Documentation
TTimeCal() [1/4]
TTimeCal::TTimeCal () default
TTimeCal() [2/4]
TTimeCal::TTimeCal (const char * name, const char * title) inline
Definition at line 13 of file TTimeCal.h.
TTimeCal() [3/4]
TTimeCal::TTimeCal (const TTimeCal &) default
TTimeCal() [4/4]
TTimeCal::TTimeCal (TTimeCal &&) default noexcept
~TTimeCal()
TTimeCal::~TTimeCal () default
Member Function Documentation
AddParameter()
void TTimeCal::AddParameter (Double_t param)
Definition at line 26 of file TTimeCal.cxx.
References fParameters.
Clear()
void TTimeCal::Clear (Option_t * opt = "") override
Definition at line 5 of file TTimeCal.cxx.
References TCal::Clear(), and fParameters.
Copy()
void TCal::Copy (TObject & obj) const override inherited
Copies the TCal.
Definition at line 37 of file TCal.cxx.
References TCal::fChan, TCal::fFitFunc, and TCal::fNuc.
Referenced by TCal::TCal(), TEfficiencyCal::Copy(), and TGainMatch::Copy().
GetChannel()
TChannel * TCal::GetChannel () const inherited
Gets the channel being pointed to by the TCal. Returns 0 if no channel is set.
Definition at line 121 of file TCal.cxx.
References TCal::fChan.
Referenced by TCalManager::AddToManager(), TCalManager::AddToManager(), TCal::Print(), TCFDCal::Print(), Print(), TCFDCal::ReadFromChannel(), ReadFromChannel(), TCal::WriteToAllChannels(), TCFDCal::WriteToChannel(), TEnergyCal::WriteToChannel(), TGainMatch::WriteToChannel(), and WriteToChannel().
GetFitFunction()
virtual TF1 * TCal::GetFitFunction () const inline virtual inherited
Definition at line 59 of file TCal.h.
References TCal::fFitFunc.
Referenced by TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), TCal::GetParameter(), and TCal::GetParameters().
GetHist()
TH1 * TCal::GetHist () const inline inherited
Definition at line 74 of file TCal.h.
References TCal::fHist.
GetNucleus()
virtual TNucleus * TCal::GetNucleus () const inline virtual inherited
Reimplemented in TGainMatch.
Definition at line 76 of file TCal.h.
References TCal::fNuc.
Referenced by TEfficiencyCal::AddPoint(), TCal::Print(), TEnergyCal::SetNucleus(), TEnergyCal::SetPoint(), and TEnergyCal::SetPointError().
GetParameter()
Double_t TTimeCal::GetParameter (size_t parameter) const override virtual
Reimplemented from TCal.
Definition at line 71 of file TTimeCal.cxx.
References fParameters.
GetParameters()
std::vector< Double_t > TTimeCal::GetParameters () const override virtual
Reimplemented from TCal.
Definition at line 62 of file TTimeCal.cxx.
References fParameters.
InitTCal()
void TCal::InitTCal () protected inherited
Initiallizes the TCal.
Definition at line 172 of file TCal.cxx.
References TCal::Clear(), TCal::fChan, TCal::fFitFunc, TCal::fHist, and TCal::fNuc.
Referenced by TCal::TCal(), TCal::TCal(), and TCal::TCal().
IsGroupable()
Bool_t TTimeCal::IsGroupable () const inline override virtual
Implements TCal.
Definition at line 21 of file TTimeCal.h.
operator=() [1/2]
TTimeCal & TTimeCal::operator= (const TTimeCal &) default
operator=() [2/2]
TTimeCal & TTimeCal::operator= (TTimeCal &&) default noexcept
Print()
void TTimeCal::Print (Option_t * opt = "") const override
Definition at line 49 of file TTimeCal.cxx.
References fParameters, TCal::GetChannel(), and TChannel::GetNumber().
ReadFromChannel()
void TTimeCal::ReadFromChannel () virtual
Definition at line 40 of file TTimeCal.cxx.
References fParameters, TCal::GetChannel(), and TChannel::GetTIMECoeff().
SetChannel() [1/2]
Bool_t TCal::SetChannel (TChannel * chan) inherited
Sets the channel being calibrated
Definition at line 51 of file TCal.cxx.
References TCal::fChan.
Referenced by TCalManager::AddToManager(), TGainMatch::CoarseMatch(), TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), TCal::SetChannel(), and TCal::WriteToAllChannels().
SetChannel() [2/2]
Bool_t TCal::SetChannel (UInt_t chanNum) inherited
Sets the channel for the calibration to the channel number channum. Returns 0 if the channel does not exist
Definition at line 109 of file TCal.cxx.
References TChannel::GetChannelByNumber(), and TCal::SetChannel().
SetFitFunction()
virtual void TCal::SetFitFunction (TF1 * func) inline virtual inherited
Definition at line 60 of file TCal.h.
References TCal::fFitFunc.
Referenced by TGainMatch::CalculateGain(), TGainMatch::CoarseMatch(), TGainMatch::FineMatch(), and TGainMatch::FineMatchFast().
SetHist()
void TCal::SetHist (TH1 * hist) virtual inherited
Sets this histogram pointed to. TCal does NOT take ownership so you cannot delete this histogram as long as you want to access the hist in the TCal/write it out. I will add this functionality if I get annoyed enough with the way it is.
Reimplemented in TGainMatch.
Definition at line 129 of file TCal.cxx.
References TCal::fHist, and hist.
SetNucleus()
void TCal::SetNucleus (TNucleus * nuc, Option_t * opt = "") virtual inherited
Sets the nucleus to be calibrated against
Reimplemented in TGainMatch, and TEnergyCal.
Definition at line 24 of file TCal.cxx.
References TCal::fNuc.
Referenced by TEnergyCal::SetNucleus().
SetParameter()
void TTimeCal::SetParameter (Int_t idx, Double_t param)
Definition at line 36 of file TTimeCal.cxx.
SetParameters()
void TTimeCal::SetParameters (std::vector< Double_t > paramVec)
Definition at line 31 of file TTimeCal.cxx.
References fParameters.
WriteToAllChannels()
void TCal::WriteToAllChannels (const std::string & mnemonic = "") virtual inherited
Writes this calibration to all channels in the current TChannel Map
Definition at line 63 of file TCal.cxx.
References TCal::GetChannel(), TChannel::GetChannelMap(), TCal::SetChannel(), and TCal::WriteToChannel().
WriteToChannel()
void TTimeCal::WriteToChannel () const override virtual
Reimplemented from TCal.
Definition at line 11 of file TTimeCal.cxx.
References TChannel::AddTIMECoefficient(), TChannel::DestroyTIMECal(), fParameters, TCal::GetChannel(), and TChannel::GetNumber().
Member Data Documentation
fChan
TRef TCal::fChan {nullptr} private inherited
This points at the TChannel.
Definition at line 82 of file TCal.h.
Referenced by TCal::Clear(), TCal::Copy(), TCal::GetChannel(), TCal::InitTCal(), and TCal::SetChannel().
fFitFunc
TF1* TCal::fFitFunc {nullptr} private inherited
Fit function representing calibration.
Definition at line 83 of file TCal.h.
Referenced by TCal::Copy(), TCal::GetFitFunction(), TCal::InitTCal(), TCal::Print(), and TCal::SetFitFunction().
fHist
TH1* TCal::fHist {nullptr} private inherited
Histogram that was fit by the TPeak.
Definition at line 84 of file TCal.h.
Referenced by TCal::GetHist(), TCal::InitTCal(), and TCal::SetHist().
fNuc
TNucleus* TCal::fNuc {nullptr} private inherited
Nucleus that we are calibrating against.
Definition at line 85 of file TCal.h.
Referenced by TCal::Clear(), TCal::Copy(), TCal::GetNucleus(), TCal::InitTCal(), and TCal::SetNucleus().
fParameters
std::vector<Double_t> TTimeCal::fParameters private
Definition at line 36 of file TTimeCal.h.
Referenced by AddParameter(), Clear(), GetParameter(), GetParameters(), Print(), ReadFromChannel(), SetParameters(), and WriteToChannel().