GRSISort: TRlmdEvent Class Reference
TRlmdEvent Class Reference
Sorting
Detailed Description
RLMD event.
C++ class representing one RLMD file.
Definition at line 22 of file TRlmdEvent.h.
Public Member Functions
TRlmdEvent ()
TRlmdEvent (const TRlmdEvent &)
~TRlmdEvent () override
void Clear (Option_t *opt="") override
void Copy (TObject &) const override
char * GetData () override
uint32_t GetDataSize () const override
virtual uint32_t GetTimeStamp () const
virtual int GoodFrags ()
virtual void IncrementGoodFrags ()
TRlmdEvent & operator= (const TRlmdEvent &)
void Print (const char *option="") const override
void SetData (std::vector< char > buffer)
int SwapBytes (bool) override
Protected Attributes
std::vector< char > fData
Private Attributes
int fGoodFrags {0}
Constructor & Destructor Documentation
TRlmdEvent() [1/2]
TRlmdEvent::TRlmdEvent ()
default constructor
Definition at line 9 of file TRlmdEvent.cxx.
References fData.
TRlmdEvent() [2/2]
TRlmdEvent::TRlmdEvent (const TRlmdEvent & rhs)
copy constructor
Definition at line 21 of file TRlmdEvent.cxx.
References Copy().
~TRlmdEvent()
TRlmdEvent::~TRlmdEvent () override
destructor
Definition at line 27 of file TRlmdEvent.cxx.
References Clear().
Member Function Documentation
Clear()
void TRlmdEvent::Clear (Option_t * opt = "") override
clear event for reuse
Definition at line 42 of file TRlmdEvent.cxx.
References fData.
Referenced by ~TRlmdEvent(), and operator=().
Copy()
void TRlmdEvent::Copy (TObject & rhs) const override
copy helper
Definition at line 15 of file TRlmdEvent.cxx.
References fData.
Referenced by TRlmdEvent(), and operator=().
GetData()
char * TRlmdEvent::GetData () override virtual
return pointer to the data buffer
Reimplemented from TRawEvent.
Definition at line 61 of file TRlmdEvent.cxx.
References fData.
GetDataSize()
uint32_t TRlmdEvent::GetDataSize () const override virtual
return the event size
Reimplemented from TRawEvent.
Definition at line 56 of file TRlmdEvent.cxx.
References fData.
GetTimeStamp()
virtual uint32_t TRawEvent::GetTimeStamp () const inline virtual inherited
return the event size
Reimplemented in TMidasEvent.
Definition at line 38 of file TRawEvent.h.
GoodFrags()
virtual int TRawEvent::GoodFrags () inline virtual inherited
returns number of good fragments parsed
Definition at line 47 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
IncrementGoodFrags()
virtual void TRawEvent::IncrementGoodFrags () inline virtual inherited
increments the number of good fragments parsed
Definition at line 48 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
operator=()
TRlmdEvent & TRlmdEvent::operator= (const TRlmdEvent & rhs)
assignement operator
Definition at line 32 of file TRlmdEvent.cxx.
References Clear(), and Copy().
Print()
void TRlmdEvent::Print (const char * option = "") const override
show all event information
Print data held in this class.
Parameters
[in] option If 'a' (for "all") then the raw data will be printed out too.
Definition at line 67 of file TRlmdEvent.cxx.
References fData, and hex().
SetData()
void TRlmdEvent::SetData (std::vector< char > buffer)
set an externally allocated data buffer
Definition at line 48 of file TRlmdEvent.cxx.
References fData, and SwapBytes().
SwapBytes()
int TRlmdEvent::SwapBytes (bool) override virtual
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
Reimplemented from TRawEvent.
Definition at line 87 of file TRlmdEvent.cxx.
Referenced by SetData().
Member Data Documentation
fData
std::vector<char> TRlmdEvent::fData protected
event data buffer
Definition at line 45 of file TRlmdEvent.h.
Referenced by TRlmdEvent(), Clear(), Copy(), GetData(), GetDataSize(), Print(), and SetData().
fGoodFrags
int TRawEvent::fGoodFrags {0} private inherited
number of good fragments parsed
Definition at line 51 of file TRawEvent.h.
Referenced by TRawEvent::Clear(), TRawEvent::Copy(), TRawEvent::GoodFrags(), and TRawEvent::IncrementGoodFrags().