GRSISort: TSourceTab Class Reference
TSourceTab Class Reference
Calibration
Detailed Description
Definition at line 58 of file TSourceCalibration.h.
Public Member Functions
TSourceTab (const TSourceTab &rhs)
TSourceTab (TSourceCalibration *sourceCal, TChannelTab *channel, TGCompositeFrame *frame, GH1D *projection, const char *sourceName, std::vector< std::tuple< double, double, double, double > > sourceEnergy)
TSourceTab (TSourceTab &&) noexcept=default
~TSourceTab ()
void Add (std::map< double, std::tuple< double, double, double, double > > map)
void Add (std::map< TGauss *, std::tuple< double, double, double, double > > map)
TGraphErrors * Data () const
void Disconnect ()
void Draw ()
void FindCalibratedPeaks (const TF1 *calibration)
TGraphErrors * Fwhm () const
void InitialCalibration (const bool &force)
void MakeConnections ()
TSourceTab & operator= (const TSourceTab &)=default
TSourceTab & operator= (TSourceTab &&) noexcept=default
void Print () const
void PrintCanvases () const
void PrintLayout () const
TRootEmbeddedCanvas * ProjectionCanvas () const
void ProjectionStatus (Event_t *event)
void ProjectionStatus (Int_t event, Int_t px, Int_t py, TObject *selected)
void RemovePoint (Int_t oldPoint)
void ReplacePeak (const size_t &index, const double &channel)
void SourceEnergy (std::vector< std::tuple< double, double, double, double > > val)
const char * SourceName () const
void Status (const char *status, int position)
Private Member Functions
void BuildInterface ()
bool Good (TGauss *peak)
bool Good (TGauss *peak, double lowRange, double highRange)
void SetLineColors ()
void UpdateFits ()
void UpdateRegions ()
Private Attributes
std::vector< TPeakFitter * > fBadFits
TChannelTab * fChannelTab {nullptr}
TGraphErrors * fData {nullptr}
std::vector< TPeakFitter * > fFits
TGraphErrors * fFwhm {nullptr}
std::vector< TGauss * > fPeaks
GH1D * fProjection {nullptr}
TRootEmbeddedCanvas * fProjectionCanvas {nullptr}
std::vector< std::pair< double, double > > fRegions
TSourceCalibration * fSourceCalibration {nullptr}
std::vector< std::tuple< double, double, double, double > > fSourceEnergy
TGCompositeFrame * fSourceFrame {nullptr}
const char * fSourceName
TGStatusBar * fSourceStatusBar {nullptr}
Constructor & Destructor Documentation
TSourceTab() [1/3]
TSourceTab::TSourceTab (TSourceCalibration * sourceCal, TChannelTab * channel, TGCompositeFrame * frame, GH1D * projection, const char * sourceName, std::vector< std::tuple< double, double, double, double > > sourceEnergy)
Definition at line 466 of file TSourceCalibration.cxx.
References BuildInterface(), DCYAN, fSourceEnergy, kBasicFlow, RESET_COLOR, and TSourceCalibration::VerboseLevel().
TSourceTab() [2/3]
TSourceTab::TSourceTab (const TSourceTab & rhs)
Definition at line 476 of file TSourceCalibration.cxx.
References DCYAN, fBadFits, fChannelTab, fData, fFits, fFwhm, fPeaks, fProjection, fProjectionCanvas, fSourceFrame, fSourceStatusBar, kBasicFlow, RESET_COLOR, and TSourceCalibration::VerboseLevel().
TSourceTab() [3/3]
TSourceTab::TSourceTab (TSourceTab &&) default noexcept
~TSourceTab()
TSourceTab::~TSourceTab ()
Definition at line 495 of file TSourceCalibration.cxx.
References fBadFits, fFits, fPeaks, fProjectionCanvas, fSourceFrame, and fSourceStatusBar.
Member Function Documentation
Add() [1/2]
void TSourceTab::Add (std::map< double, std::tuple< double, double, double, double > > map)
Definition at line 970 of file TSourceCalibration.cxx.
References DCYAN, fData, kBasicFlow, kSubroutines, and TSourceCalibration::VerboseLevel().
Referenced by FindCalibratedPeaks(), InitialCalibration(), and ProjectionStatus().
Add() [2/2]
void TSourceTab::Add (std::map< TGauss *, std::tuple< double, double, double, double > > map)
Definition at line 1000 of file TSourceCalibration.cxx.
References DCYAN, fData, fFwhm, fProjection, fSourceCalibration, Good(), kBasicFlow, kLoops, kSubroutines, TSinglePeak::SetLineColor(), TSourceCalibration::Sigma(), and TSourceCalibration::VerboseLevel().
BuildInterface()
void TSourceTab::BuildInterface () private
Definition at line 517 of file TSourceCalibration.cxx.
References DCYAN, fProjection, fProjectionCanvas, fSourceFrame, fSourceStatusBar, kBasicFlow, TSourceCalibration::PanelHeight(), TSourceCalibration::PanelWidth(), RESET_COLOR, TSourceCalibration::StatusbarHeight(), and TSourceCalibration::VerboseLevel().
Referenced by TSourceTab().
Data()
TGraphErrors * TSourceTab::Data () const inline
Definition at line 83 of file TSourceCalibration.h.
References fData.
Disconnect()
void TSourceTab::Disconnect ()
Definition at line 551 of file TSourceCalibration.cxx.
References fProjectionCanvas.
Draw()
void TSourceTab::Draw ()
Definition at line 777 of file TSourceCalibration.cxx.
References GH1D::Draw(), fProjection, fProjectionCanvas, kSubroutines, and TSourceCalibration::VerboseLevel().
FindCalibratedPeaks()
void TSourceTab::FindCalibratedPeaks (const TF1 * calibration)
This functions finds uses the existing calibration to find all peaks from the list of source energies.
Definition at line 838 of file TSourceCalibration.cxx.
References Add(), GH1D::Clear(), DCYAN, fBadFits, fData, fFits, TSourceCalibration::FitRange(), fPeaks, fProjection, fProjectionCanvas, fSourceCalibration, fSourceEnergy, Good(), kBasicFlow, kLoops, kSubroutines, TSourceCalibration::LogFile(), TSourceCalibration::MinIntensity(), SetLineColors(), TSourceCalibration::Sigma(), UpdateFits(), and TSourceCalibration::VerboseLevel().
Fwhm()
TGraphErrors * TSourceTab::Fwhm () const inline
Definition at line 84 of file TSourceCalibration.h.
References fFwhm.
Good() [1/2]
bool TSourceTab::Good (TGauss * peak) private
Definition at line 722 of file TSourceCalibration.cxx.
References TSourceCalibration::AcceptBadFits(), TSinglePeak::Area(), TSinglePeak::AreaErr(), TGauss::Centroid(), and TGauss::CentroidErr().
Referenced by Add(), FindCalibratedPeaks(), and ReplacePeak().
Good() [2/2]
bool TSourceTab::Good (TGauss * peak, double lowRange, double highRange) inline private
Definition at line 101 of file TSourceCalibration.h.
References TGauss::Centroid(), and Good().
Referenced by Good().
InitialCalibration()
void TSourceTab::InitialCalibration (const bool & force)
This functions finds the peaks in the histogram, fits them, and adds the fits to the list of peaks. This list is then used to find all peaks that lie on a straight line.
Definition at line 784 of file TSourceCalibration.cxx.
References Add(), GH1D::Clear(), DCYAN, fBadFits, fData, fFits, fPeaks, fProjection, fRegions, fSourceCalibration, fSourceEnergy, kBasicFlow, kLoops, kSubroutines, RoughCal(), TSourceCalibration::Sigma(), Status(), TSourceCalibration::Threshold(), UpdateRegions(), and TSourceCalibration::VerboseLevel().
MakeConnections()
void TSourceTab::MakeConnections ()
Definition at line 543 of file TSourceCalibration.cxx.
References DCYAN, fProjectionCanvas, kBasicFlow, RESET_COLOR, and TSourceCalibration::VerboseLevel().
operator=() [1/2]
TSourceTab & TSourceTab::operator= (const TSourceTab &) default
operator=() [2/2]
TSourceTab & TSourceTab::operator= (TSourceTab &&) default noexcept
Print()
void TSourceTab::Print () const
Definition at line 1281 of file TSourceCalibration.cxx.
References fBadFits, fData, fFits, fFwhm, fPeaks, and fProjection.
Referenced by RemovePoint().
PrintCanvases()
void TSourceTab::PrintCanvases () const
Definition at line 1326 of file TSourceCalibration.cxx.
References fProjectionCanvas, and fSourceName.
PrintLayout()
void TSourceTab::PrintLayout () const
Definition at line 1335 of file TSourceCalibration.cxx.
References fProjectionCanvas, fSourceFrame, and fSourceStatusBar.
ProjectionCanvas()
TRootEmbeddedCanvas * TSourceTab::ProjectionCanvas () const inline
Definition at line 85 of file TSourceCalibration.h.
References fProjectionCanvas.
ProjectionStatus() [1/2]
void TSourceTab::ProjectionStatus (Event_t * event)
Definition at line 558 of file TSourceCalibration.cxx.
References fProjectionCanvas, kBasicFlow, and TSourceCalibration::VerboseLevel().
ProjectionStatus() [2/2]
void TSourceTab::ProjectionStatus (Int_t event, Int_t px, Int_t py, TObject * selected)
Definition at line 584 of file TSourceCalibration.cxx.
References Add(), TChannelTab::Calibrate(), DCYAN, fChannelTab, fData, fFits, fPeaks, fProjection, fProjectionCanvas, fSourceCalibration, fSourceEnergy, kArrowKeyPress, kArrowKeyRelease, kBasicFlow, kLoops, kSubroutines, Match(), TSourceCalibration::Sigma(), Status(), TChannelTab::UpdateData(), TChannelTab::UpdateFwhm(), and TSourceCalibration::VerboseLevel().
RemovePoint()
void TSourceTab::RemovePoint (Int_t oldPoint)
Definition at line 1222 of file TSourceCalibration.cxx.
References DCYAN, fBadFits, fData, fFits, fPeaks, kBasicFlow, kSubroutines, Print(), SetLineColors(), UpdateFits(), and TSourceCalibration::VerboseLevel().
ReplacePeak()
void TSourceTab::ReplacePeak (const size_t & index, const double & channel)
Replace the peak at the index with one centered at channel (calculated from an initial calibration and the source energy of this peak). This replaces the TGauss* in fPeaks, and updates the values of this index in fData and fFwhm.
Definition at line 1146 of file TSourceCalibration.cxx.
References DCYAN, fData, fFits, fFwhm, TSourceCalibration::FitRange(), fPeaks, fProjection, fSourceCalibration, Good(), kBasicFlow, kSubroutines, TSourceCalibration::LogFile(), TSourceCalibration::Sigma(), UpdateFits(), and TSourceCalibration::VerboseLevel().
SetLineColors()
void TSourceTab::SetLineColors () private
This function sets the line colors of good and bad fits to alternating colors. Red and blue for the good fits, and grey and dark grey for the bad fits.
Definition at line 1243 of file TSourceCalibration.cxx.
References fBadFits, fFits, fPeaks, kSubroutines, and TSourceCalibration::VerboseLevel().
Referenced by FindCalibratedPeaks(), and RemovePoint().
SourceEnergy()
void TSourceTab::SourceEnergy (std::vector< std::tuple< double, double, double, double > > val) inline
Definition at line 79 of file TSourceCalibration.h.
References fSourceEnergy.
SourceName()
const char * TSourceTab::SourceName () const inline
Definition at line 86 of file TSourceCalibration.h.
References fSourceName.
Status()
void TSourceTab::Status (const char * status, int position)
Definition at line 1273 of file TSourceCalibration.cxx.
References fSourceFrame, and fSourceStatusBar.
Referenced by InitialCalibration(), Match(), ProjectionStatus(), RoughCal(), and SmartMatch().
UpdateFits()
void TSourceTab::UpdateFits () private
This functions removes all fits named "gauss_total" from the histogram and adds instead the fit functions from all good and bad peaks to it.
Definition at line 727 of file TSourceCalibration.cxx.
References fBadFits, fFits, fProjection, fProjectionCanvas, fSourceEnergy, kSubroutines, and TSourceCalibration::VerboseLevel().
Referenced by FindCalibratedPeaks(), RemovePoint(), and ReplacePeak().
UpdateRegions()
void TSourceTab::UpdateRegions () private
Definition at line 701 of file TSourceCalibration.cxx.
References fProjection, fRegions, kLoops, kSubroutines, GH1D::ListOfRegions(), GH1D::Print(), and TSourceCalibration::VerboseLevel().
Referenced by InitialCalibration().
Member Data Documentation
fBadFits
std::vector<TPeakFitter*> TSourceTab::fBadFits private
all bad fits (centroid err > 10%, area err > 100%, or either of them not a number at all)
Definition at line 120 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), FindCalibratedPeaks(), InitialCalibration(), Print(), RemovePoint(), SetLineColors(), and UpdateFits().
fChannelTab
TChannelTab* TSourceTab::fChannelTab {nullptr} private
Definition at line 107 of file TSourceCalibration.h.
Referenced by TSourceTab(), and ProjectionStatus().
fData
TGraphErrors* TSourceTab::fData {nullptr} private
Definition at line 117 of file TSourceCalibration.h.
Referenced by TSourceTab(), Add(), Add(), Data(), FindCalibratedPeaks(), InitialCalibration(), Print(), ProjectionStatus(), RemovePoint(), and ReplacePeak().
fFits
std::vector<TPeakFitter*> TSourceTab::fFits private
all good fits
Definition at line 119 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), FindCalibratedPeaks(), InitialCalibration(), Print(), ProjectionStatus(), RemovePoint(), ReplacePeak(), SetLineColors(), and UpdateFits().
fFwhm
TGraphErrors* TSourceTab::fFwhm {nullptr} private
Definition at line 118 of file TSourceCalibration.h.
Referenced by TSourceTab(), Add(), Fwhm(), Print(), and ReplacePeak().
fPeaks
std::vector<TGauss*> TSourceTab::fPeaks private
all peaks that have been fitted and are good
Definition at line 121 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), FindCalibratedPeaks(), InitialCalibration(), Print(), ProjectionStatus(), RemovePoint(), ReplacePeak(), and SetLineColors().
fProjection
GH1D* TSourceTab::fProjection {nullptr} private
Definition at line 115 of file TSourceCalibration.h.
Referenced by TSourceTab(), Add(), BuildInterface(), Draw(), FindCalibratedPeaks(), InitialCalibration(), Print(), ProjectionStatus(), ReplacePeak(), UpdateFits(), and UpdateRegions().
fProjectionCanvas
TRootEmbeddedCanvas* TSourceTab::fProjectionCanvas {nullptr} private
Definition at line 111 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), BuildInterface(), Disconnect(), Draw(), FindCalibratedPeaks(), MakeConnections(), PrintCanvases(), PrintLayout(), ProjectionCanvas(), ProjectionStatus(), ProjectionStatus(), and UpdateFits().
fRegions
std::vector<std::pair<double, double> > TSourceTab::fRegions private
Definition at line 123 of file TSourceCalibration.h.
Referenced by InitialCalibration(), and UpdateRegions().
fSourceCalibration
TSourceCalibration* TSourceTab::fSourceCalibration {nullptr} private
Definition at line 106 of file TSourceCalibration.h.
Referenced by Add(), FindCalibratedPeaks(), InitialCalibration(), ProjectionStatus(), and ReplacePeak().
fSourceEnergy
std::vector<std::tuple<double, double, double, double> > TSourceTab::fSourceEnergy private
gamma rays from the source, with their energies, uncertainties in the energies, intensities, and uncertainties in the intesities
Definition at line 122 of file TSourceCalibration.h.
Referenced by TSourceTab(), FindCalibratedPeaks(), InitialCalibration(), ProjectionStatus(), SourceEnergy(), and UpdateFits().
fSourceFrame
TGCompositeFrame* TSourceTab::fSourceFrame {nullptr} private
Definition at line 110 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), BuildInterface(), PrintLayout(), and Status().
fSourceName
const char* TSourceTab::fSourceName private
Definition at line 116 of file TSourceCalibration.h.
Referenced by PrintCanvases(), and SourceName().
fSourceStatusBar
TGStatusBar* TSourceTab::fSourceStatusBar {nullptr} private
Definition at line 112 of file TSourceCalibration.h.
Referenced by TSourceTab(), ~TSourceTab(), BuildInterface(), PrintLayout(), and Status().