GRSISort: EfficiencyHelper Class Reference
EfficiencyHelper Class Reference
Detailed Description
Definition at line 14 of file EfficiencyHelper.hh.
Public Types
using Result_t = std::map<std::string, TList>
Public Member Functions
EfficiencyHelper (TList *list)
ROOT::RDF::RResultPtr< std::map< std::string, TList > > Book (ROOT::RDataFrame *d) override
void CreateHistograms (unsigned int slot) override
void EndOfSort (std::shared_ptr< std::map< std::string, TList > > &list) override
void Exec (unsigned int slot, TGriffin &grif, TGriffinBgo &grifBgo)
void Finalize ()
std::string GetActionName () const
std::shared_ptr< std::map< std::string, TList > > GetResultPtr () const
void Initialize ()
void InitTask (TTreeReader *, unsigned int)
std::string & Prefix ()
std::string Prefix () const
void Prefix (const std::string &val)
virtual void Setup ()
Protected Member Functions
TPPG * Ppg ()
TRunInfo * RunInfo ()
TUserSettings * UserSettings ()
Protected Attributes
std::vector< TGRSIMap< std::string, GCube * > > fCube
std::map< std::string, TCutG * > fCuts
std::vector< TGRSIMap< std::string, TH1 * > > fH1
std::vector< TGRSIMap< std::string, TH2 * > > fH2
std::vector< TGRSIMap< std::string, TH3 * > > fH3
std::vector< std::shared_ptr< std::map< std::string, TList > > > fLists
std::vector< TGRSIMap< std::string, TObject * > > fObject
TPPG * fPpg {nullptr}
std::string fPrefix {"TGRSIHelper"}
TRunInfo * fRunInfo {nullptr}
std::vector< TGRSIMap< std::string, GHSym * > > fSym
std::vector< TGRSIMap< std::string, TTree * > > fTree
TUserSettings * fUserSettings {nullptr}
Private Member Functions
void CheckSizes (unsigned int slot, const char *usage)
bool GoodCfd (TDetectorHit *h1)
bool PromptCoincidence (TGriffinHit *h1, TGriffinHit *h2)
bool Reject (TGriffinHit *hit)
bool TimeRandom (TGriffinHit *h1, TGriffinHit *h2)
Private Attributes
Long64_t fCycleLength {0}
double fGgBgHigh {1500.}
double fGgBgLow {500.}
double fGgHigh {250.}
double fGgLow {-250.}
int fKValueGriffin {379}
double fMaxCfd {20.}
double fMinimumGriffinEnergy {0.}
bool fPileUpRejection {true}
Static Private Attributes
static constexpr int fSizeLimit = 1073741822
Member Typedef Documentation
Result_t
using TGRSIHelper::Result_t = std::map<std::string, TList> inherited
This type is a requirement for every helper.
Definition at line 67 of file TGRSIHelper.h.
Constructor & Destructor Documentation
EfficiencyHelper()
EfficiencyHelper::EfficiencyHelper (TList * list) inline explicit
Definition at line 18 of file EfficiencyHelper.hh.
References fGgBgHigh, fGgBgLow, fGgHigh, fGgLow, fKValueGriffin, fMaxCfd, fMinimumGriffinEnergy, fPileUpRejection, TGRSIHelper::fUserSettings, TUserSettings::GetBool(), TUserSettings::GetDouble(), TUserSettings::GetInt(), TGRSIHelper::Prefix(), and TGRSIHelper::Setup().
Member Function Documentation
Book()
ROOT::RDF::RResultPtr< std::map< std::string, TList > > EfficiencyHelper::Book (ROOT::RDataFrame *) inline override virtual
This method will call the Book action on the provided dataframe.
Reimplemented from TGRSIHelper.
Definition at line 37 of file EfficiencyHelper.hh.
CheckSizes()
void TGRSIHelper::CheckSizes (unsigned int slot, const char * usage) private inherited
check size of each object in the output list
Definition at line 215 of file TGRSIHelper.cxx.
References DRED, TGRSIHelper::fLists, TGRSIHelper::fSizeLimit, and RESET_COLOR.
Referenced by TGRSIHelper::Finalize(), and TGRSIHelper::Setup().
CreateHistograms()
void EfficiencyHelper::CreateHistograms (unsigned int) override virtual
Virtual helper function that the user uses to create their histograms.
Reimplemented from TGRSIHelper.
Definition at line 3 of file EfficiencyHelper.cxx.
References TGRSIHelper::fH1, and TGRSIHelper::fH2.
EndOfSort()
void EfficiencyHelper::EndOfSort (std::shared_ptr< std::map< std::string, TList > > &) override virtual
This method gets called at the end of Finalize()
Reimplemented from TGRSIHelper.
Definition at line 152 of file EfficiencyHelper.cxx.
References bgHigh, and bgLow.
Exec()
void EfficiencyHelper::Exec (unsigned int slot, TGriffin & grif, TGriffinBgo & grifBgo)
Definition at line 42 of file EfficiencyHelper.cxx.
References TGRSIHelper::fH1, TGRSIHelper::fH2, TGriffin::GetAddbackHit(), TGriffin::GetAddbackMultiplicity(), TGriffin::GetGriffinHit(), TDetector::GetMultiplicity(), TGriffin::GetSuppressedAddbackHit(), TGriffin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedHit(), TGriffin::GetSuppressedMultiplicity(), PromptCoincidence(), Reject(), and TimeRandom().
Finalize()
void TGRSIHelper::Finalize () inherited
This required method is called at the end of the event loop. It is used to merge all the internal TLists which were used in each of the data processing slots.
This function merges all maps of lists into the map of the first slot (slot 0)
Definition at line 154 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::EndOfSort(), and TGRSIHelper::fLists.
GetActionName()
std::string TGRSIHelper::GetActionName () const inline inherited
Definition at line 104 of file TGRSIHelper.h.
References TGRSIHelper::Prefix().
GetResultPtr()
std::shared_ptr< std::map< std::string, TList > > TGRSIHelper::GetResultPtr () const inline inherited
Definition at line 92 of file TGRSIHelper.h.
References TGRSIHelper::fLists.
GoodCfd()
bool EfficiencyHelper::GoodCfd (TDetectorHit * h1) inline private
Definition at line 76 of file EfficiencyHelper.hh.
References fMaxCfd, TDetectorHit::GetTime(), and TDetectorHit::GetTimeStampNs().
Initialize()
void TGRSIHelper::Initialize () inline inherited
Definition at line 94 of file TGRSIHelper.h.
InitTask()
void TGRSIHelper::InitTask (TTreeReader * , unsigned int) inline inherited
Definition at line 93 of file TGRSIHelper.h.
Ppg()
TPPG * TGRSIHelper::Ppg () inline protected inherited
Definition at line 43 of file TGRSIHelper.h.
References TGRSIHelper::fPpg.
Referenced by ExampleEventHelper::CreateHistograms().
Prefix() [1/3]
std::string & TGRSIHelper::Prefix () inline inherited
Definition at line 40 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper::GriffinKValueHelper(), TimeWalkHelper::TimeWalkHelper(), TGRSIHelper::Book(), TGRSIHelper::CreateHistograms(), and TGRSIHelper::GetActionName().
Prefix() [2/3]
std::string TGRSIHelper::Prefix () const inline inherited
Definition at line 102 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Prefix() [3/3]
void TGRSIHelper::Prefix (const std::string & val) inline inherited
Definition at line 103 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
PromptCoincidence()
bool EfficiencyHelper::PromptCoincidence (TGriffinHit * h1, TGriffinHit * h2) inline private
Definition at line 66 of file EfficiencyHelper.hh.
References fGgHigh, fGgLow, and TDetectorHit::GetTime().
Referenced by Exec().
Reject()
bool EfficiencyHelper::Reject (TGriffinHit * hit) inline private
Definition at line 82 of file EfficiencyHelper.hh.
References fKValueGriffin, fMinimumGriffinEnergy, fPileUpRejection, TDetectorHit::GetEnergy(), and TDetectorHit::GetKValue().
Referenced by Exec().
RunInfo()
TRunInfo * TGRSIHelper::RunInfo () inline protected inherited
Definition at line 44 of file TGRSIHelper.h.
References TGRSIHelper::fRunInfo.
Setup()
void TGRSIHelper::Setup () virtual inherited
This function builds the vectors of TLists and maps for 1D- and 2D-histograms. It calls the overloaded CreateHistograms functions in which the user can define their histograms. Then it adds all those histograms to the list of the corresponding slot.
Definition at line 71 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::CreateHistograms(), TGRSIHelper::fCube, TGRSIHelper::fH1, TGRSIHelper::fH2, TGRSIHelper::fH3, TGRSIHelper::fLists, TGRSIHelper::fObject, TGRSIHelper::fSym, TGRSIHelper::fTree, TGRSIOptions::Get(), and TGRSIOptions::GetMaxWorkers().
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper::GriffinKValueHelper(), and TimeWalkHelper::TimeWalkHelper().
TimeRandom()
bool EfficiencyHelper::TimeRandom (TGriffinHit * h1, TGriffinHit * h2) inline private
Definition at line 70 of file EfficiencyHelper.hh.
References fGgBgHigh, fGgBgLow, and TDetectorHit::GetTime().
Referenced by Exec().
UserSettings()
TUserSettings * TGRSIHelper::UserSettings () inline protected inherited
Definition at line 45 of file TGRSIHelper.h.
References TGRSIHelper::fUserSettings.
Member Data Documentation
fCube
std::vector<TGRSIMap<std::string, GCube*> > TGRSIHelper::fCube protected inherited
Definition at line 52 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fCuts
std::map<std::string, TCutG*> TGRSIHelper::fCuts protected inherited
Definition at line 55 of file TGRSIHelper.h.
Referenced by TGRSIHelper::TGRSIHelper().
fCycleLength
Long64_t EfficiencyHelper::fCycleLength {0} private
Definition at line 51 of file EfficiencyHelper.hh.
fGgBgHigh
double EfficiencyHelper::fGgBgHigh {1500.} private
Definition at line 61 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and TimeRandom().
fGgBgLow
double EfficiencyHelper::fGgBgLow {500.} private
Definition at line 60 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and TimeRandom().
fGgHigh
double EfficiencyHelper::fGgHigh {250.} private
Definition at line 59 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and PromptCoincidence().
fGgLow
double EfficiencyHelper::fGgLow {-250.} private
Definition at line 58 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and PromptCoincidence().
fH1
std::vector<TGRSIMap<std::string, TH1*> > TGRSIHelper::fH1 protected inherited
Definition at line 48 of file TGRSIHelper.h.
Referenced by ComptonPolarimetryHelper::CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), GriffinKValueHelper::CreateHistograms(), ComptonPolarimetryHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), and TGRSIHelper::Setup().
fH2
std::vector<TGRSIMap<std::string, TH2*> > TGRSIHelper::fH2 protected inherited
Definition at line 49 of file TGRSIHelper.h.
Referenced by AlphanumericHelper::CreateHistograms(), AngularCorrelationHelper::CreateHistograms(), ComptonPolarimetryHelper::CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleFragmentHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), GriffinKValueHelper::CreateHistograms(), TimeWalkHelper::CreateHistograms(), ExampleEventHelper::EndOfSort(), AlphanumericHelper::Exec(), AngularCorrelationHelper::Exec(), ComptonPolarimetryHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), Exec(), ExampleEventHelper::Exec(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fH3
std::vector<TGRSIMap<std::string, TH3*> > TGRSIHelper::fH3 protected inherited
Definition at line 50 of file TGRSIHelper.h.
Referenced by TimeWalkHelper::CreateHistograms(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fKValueGriffin
int EfficiencyHelper::fKValueGriffin {379} private
Definition at line 53 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and Reject().
fLists
std::vector<std::shared_ptr<std::map<std::string, TList> > > TGRSIHelper::fLists protected inherited
Definition at line 47 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes(), TGRSIHelper::Finalize(), TGRSIHelper::GetResultPtr(), and TGRSIHelper::Setup().
fMaxCfd
double EfficiencyHelper::fMaxCfd {20.} private
Definition at line 62 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and GoodCfd().
fMinimumGriffinEnergy
double EfficiencyHelper::fMinimumGriffinEnergy {0.} private
Definition at line 55 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and Reject().
fObject
std::vector<TGRSIMap<std::string, TObject*> > TGRSIHelper::fObject protected inherited
Definition at line 54 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::CreateHistograms(), and TGRSIHelper::Setup().
fPileUpRejection
bool EfficiencyHelper::fPileUpRejection {true} private
Definition at line 54 of file EfficiencyHelper.hh.
Referenced by EfficiencyHelper(), and Reject().
fPpg
TPPG* TGRSIHelper::fPpg {nullptr} protected inherited
Definition at line 56 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::CreateHistograms(), and TGRSIHelper::Ppg().
fPrefix
std::string TGRSIHelper::fPrefix {"TGRSIHelper"} protected inherited
Definition at line 59 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Prefix(), TGRSIHelper::Prefix(), and TGRSIHelper::Prefix().
fRunInfo
TRunInfo* TGRSIHelper::fRunInfo {nullptr} protected inherited
Definition at line 57 of file TGRSIHelper.h.
Referenced by TGRSIHelper::RunInfo().
fSizeLimit
int TGRSIHelper::fSizeLimit = 1073741822 static constexpr private inherited
! 1 GiB size limit for objects in ROOT
Definition at line 62 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes().
fSym
std::vector<TGRSIMap<std::string, GHSym*> > TGRSIHelper::fSym protected inherited
Definition at line 51 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fTree
std::vector<TGRSIMap<std::string, TTree*> > TGRSIHelper::fTree protected inherited
Definition at line 53 of file TGRSIHelper.h.
Referenced by ExampleTreeHelper::CreateHistograms(), ExampleTreeHelper::Exec(), and TGRSIHelper::Setup().
fUserSettings
TUserSettings* TGRSIHelper::fUserSettings {nullptr} protected inherited
Definition at line 58 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), EfficiencyHelper(), and TGRSIHelper::UserSettings().