GRSISort: TBGSubtraction Class Reference
TBGSubtraction Class Reference
GUI
Detailed Description
This class implements a GUI to perform projections of a 2D-Matrix with proper background subtraction.
Definition at line 42 of file TBGSubtraction.h.
Public Member Functions
TBGSubtraction (const TBGSubtraction &)=delete
TBGSubtraction (TBGSubtraction &&)=delete
TBGSubtraction (TH2 *mat, const char *gate_axis="x", int maxBinning=20)
~TBGSubtraction ()
void AxisComboSelected ()
void ClickedBGButton1 ()
void ClickedBGButton2 ()
void DoAllGates ()
void DoEntry (Long_t)
void DoGateCanvasZoomed ()
void DoGateProjection ()
void DoPeakFit ()
void DoProjectionCanvasZoomed ()
void DoSlider (Int_t pos=0)
void DrawAllMarkers ()
void DrawBGMarkers1 ()
void DrawBGMarkers2 ()
void DrawGateMarkers ()
void DrawOnNewCanvas ()
void DrawPeak ()
void DrawPeakMarkers ()
void GateStatusInfo (Int_t event, Int_t px, Int_t py, TObject *selected)
void MakeBGHisto1 ()
void MakeBGHisto2 ()
void MakeGateHisto ()
TBGSubtraction & operator= (const TBGSubtraction &)=delete
TBGSubtraction & operator= (TBGSubtraction &&)=delete
void PeakComboSelected ()
void ProjectionStatusInfo (Int_t event, Int_t px, Int_t py, TObject *selected)
void SetStatusFromUpdateCheckButton ()
void UpdateBackground ()
void UpdatePeakSliders ()
void UpdateProjectionSliders ()
void WriteHistograms ()
Private Types
enum EEntries {
kBGParamEntry , kGateLowEntry , kGateHighEntry , kPeakLowEntry ,
kPeakHighEntry , kPeakEntry , kBGLowEntry1 , kBGHighEntry1 ,
kBGLowEntry2 , kBGHighEntry2 , kWrite2FileNameEntry , kHistogramDescriptionEntry ,
kComboAxisEntry , kComboPeakEntry , kBGCheckButton1 , kBGCheckButton2 ,
kAutoUpdateCheckButton
}
enum EPeaks { kGauss = 0 , kRWPeak = 1 , kABPeak = 2 , kAB3Peak = 3 }
enum ESliders {
kGateSlider , kBGSlider1 , kBGSlider2 , kPeakSlider ,
kBinningSlider
}
Private Member Functions
void BuildInterface ()
void Disconnect ()
void DrawBGMarkers (TGCheckButton *&check_button, GMarker *&low_marker, GMarker *&high_marker, TGNumberEntry *&low_entry, TGNumberEntry *&high_entry, Color_t color=kBlue)
void InitializeInterface ()
void MakeConnections ()
void RebinProjection ()
void ResetInterface ()
void StatusInfo (Int_t event, Int_t px, Int_t py, TObject *selected)
void UpdateBGSlider1 ()
void UpdateBGSlider2 ()
void UpdateBinningSlider ()
void UpdateGateSlider ()
Private Attributes
TGCheckButton * fAutoUpdateCheckButton {nullptr}
TGComboBox * fAxisCombo {nullptr}
TGCheckButton * fBGCheckButton1 {nullptr}
TGCheckButton * fBGCheckButton2 {nullptr}
TGHorizontalFrame * fBGEntryFrame1 {nullptr}
TGHorizontalFrame * fBGEntryFrame2 {nullptr}
TGNumberEntry * fBGEntryHigh1 {nullptr}
TGNumberEntry * fBGEntryHigh2 {nullptr}
TGNumberEntry * fBGEntryLow1 {nullptr}
TGNumberEntry * fBGEntryLow2 {nullptr}
TH1 * fBGHist1 {nullptr}
TH1 * fBGHist2 {nullptr}
TGNumberEntry * fBGParamEntry {nullptr}
TGHorizontalFrame * fBGParamFrame {nullptr}
TGLabel * fBGParamLabel {nullptr}
TGDoubleHSlider * fBGSlider1 {nullptr}
TGDoubleHSlider * fBGSlider2 {nullptr}
TGHorizontalFrame * fBinningFrame {nullptr}
TGLabel * fBinningLabel {nullptr}
TGHSlider * fBinningSlider {nullptr}
TGLayoutHints * fBly {nullptr}
TGLayoutHints * fBly1 {nullptr}
TGHorizontalFrame * fButtonFrame {nullptr}
TFile * fCurrentFile {nullptr}
TGHorizontalFrame * fDescriptionFrame {nullptr}
Bool_t fForceUpdate {true}
Int_t fGateAxis {0}
TRootEmbeddedCanvas * fGateCanvas {nullptr}
TGHorizontalFrame * fGateEntryFrame {nullptr}
TGNumberEntry * fGateEntryHigh {nullptr}
TGNumberEntry * fGateEntryLow {nullptr}
TGVerticalFrame * fGateFrame {nullptr}
TH1 * fGateHist {nullptr}
TGDoubleHSlider * fGateSlider {nullptr}
GMarker * fHighBGMarker1 {nullptr}
GMarker * fHighBGMarker2 {nullptr}
GMarker * fHighGateMarker {nullptr}
GMarker * fHighPeakMarker {nullptr}
TGTextEntry * fHistogramDescription {nullptr}
TGLayoutHints * fLayoutCanvases {nullptr}
TGLayoutHints * fLayoutParam {nullptr}
GMarker * fLowBGMarker1 {nullptr}
GMarker * fLowBGMarker2 {nullptr}
GMarker * fLowGateMarker {nullptr}
GMarker * fLowPeakMarker {nullptr}
TGMainFrame * fMain {nullptr}
TH2 * fMatrix {nullptr}
Int_t fMaxBinning {20}
TSinglePeak * fPeak {nullptr}
TGComboBox * fPeakCombo {nullptr}
TGTextButton * fPeakFitButton {nullptr}
TGHorizontalFrame * fPeakFitFrame {nullptr}
TPeakFitter * fPeakFitter {nullptr}
Double_t fPeakHighLimit {0.}
Double_t fPeakHighValue {0.}
Double_t fPeakLowLimit {0.}
Double_t fPeakLowValue {0.}
GMarker * fPeakMarker {nullptr}
TGTripleHSlider * fPeakSlider {nullptr}
Double_t fPeakValue {0.}
TH1 * fProjection {nullptr}
TRootEmbeddedCanvas * fProjectionCanvas {nullptr}
TGVerticalFrame * fProjectionFrame {nullptr}
TGStatusBar * fProjectionStatus {nullptr}
TH1 * fSubtractedBinHist {nullptr}
TH1 * fSubtractedHist {nullptr}
TGTextButton * fWrite2FileButton {nullptr}
TGTextEntry * fWrite2FileName {nullptr}
Member Enumeration Documentation
EEntries
enum TBGSubtraction::EEntries private
Enumerator
kBGParamEntry
kGateLowEntry
kGateHighEntry
kPeakLowEntry
kPeakHighEntry
kPeakEntry
kBGLowEntry1
kBGHighEntry1
kBGLowEntry2
kBGHighEntry2
kWrite2FileNameEntry
kHistogramDescriptionEntry
kComboAxisEntry
kComboPeakEntry
kBGCheckButton1
kBGCheckButton2
kAutoUpdateCheckButton
Definition at line 53 of file TBGSubtraction.h.
EPeaks
enum TBGSubtraction::EPeaks private
Enumerator
kGauss
kRWPeak
kABPeak
kAB3Peak
Definition at line 72 of file TBGSubtraction.h.
ESliders
enum TBGSubtraction::ESliders private
Enumerator
kGateSlider
kBGSlider1
kBGSlider2
kPeakSlider
kBinningSlider
Definition at line 46 of file TBGSubtraction.h.
Constructor & Destructor Documentation
TBGSubtraction() [1/3]
TBGSubtraction::TBGSubtraction (TH2 * mat, const char * gate_axis = "x", int maxBinning = 20) explicit
Definition at line 13 of file TBGSubtraction.cxx.
References BuildInterface(), fCurrentFile, fGateAxis, fMatrix, fProjection, InitializeInterface(), and MakeConnections().
TBGSubtraction() [2/3]
TBGSubtraction::TBGSubtraction (const TBGSubtraction &) delete
TBGSubtraction() [3/3]
TBGSubtraction::TBGSubtraction (TBGSubtraction &&) delete
~TBGSubtraction()
TBGSubtraction::~TBGSubtraction ()
Definition at line 406 of file TBGSubtraction.cxx.
References Disconnect(), fHighBGMarker1, fHighBGMarker2, fHighGateMarker, fHighPeakMarker, fLowBGMarker1, fLowBGMarker2, fLowGateMarker, fLowPeakMarker, and fPeakMarker.
Member Function Documentation
AxisComboSelected()
void TBGSubtraction::AxisComboSelected ()
Definition at line 565 of file TBGSubtraction.cxx.
References fAxisCombo, fGateAxis, fMatrix, fProjection, fProjectionCanvas, and ResetInterface().
Referenced by InitializeInterface().
BuildInterface()
void TBGSubtraction::BuildInterface () private
Definition at line 247 of file TBGSubtraction.cxx.
References fAutoUpdateCheckButton, fAxisCombo, fBGCheckButton1, fBGCheckButton2, fBGEntryFrame1, fBGEntryFrame2, fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fBGParamEntry, fBGParamFrame, fBGParamLabel, fBGSlider1, fBGSlider2, fBinningFrame, fBinningLabel, fBinningSlider, fBly, fBly1, fButtonFrame, fDescriptionFrame, fGateCanvas, fGateEntryFrame, fGateEntryHigh, fGateEntryLow, fGateFrame, fGateSlider, fHistogramDescription, fLayoutCanvases, fLayoutParam, fMaxBinning, fPeakCombo, fPeakFitButton, fPeakFitFrame, fPeakSlider, fProjectionCanvas, fProjectionFrame, fProjectionStatus, fWrite2FileButton, fWrite2FileName, kAutoUpdateCheckButton, kBGCheckButton1, kBGCheckButton2, kBGHighEntry1, kBGHighEntry2, kBGLowEntry1, kBGLowEntry2, kBGParamEntry, kBGSlider1, kBGSlider2, kBinningSlider, kComboAxisEntry, kComboPeakEntry, kGateHighEntry, kGateLowEntry, kGateSlider, kHistogramDescriptionEntry, kPeakSlider, and kWrite2FileNameEntry.
Referenced by TBGSubtraction().
ClickedBGButton1()
void TBGSubtraction::ClickedBGButton1 ()
Definition at line 459 of file TBGSubtraction.cxx.
References fBGCheckButton1, and fBGParamEntry.
ClickedBGButton2()
void TBGSubtraction::ClickedBGButton2 ()
Disconnect()
void TBGSubtraction::Disconnect () private
Disconnect Canvases to recognize that they have been zoomed This function includes setting the slider, and drawing the gate markers.
Definition at line 104 of file TBGSubtraction.cxx.
References fAutoUpdateCheckButton, fAxisCombo, fBGCheckButton1, fBGCheckButton2, fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fBGParamEntry, fBGSlider1, fBGSlider2, fBinningSlider, fGateCanvas, fGateEntryHigh, fGateEntryLow, fGateSlider, fPeakCombo, fPeakFitButton, fPeakSlider, fProjectionCanvas, and fWrite2FileButton.
Referenced by ~TBGSubtraction().
DoAllGates()
void TBGSubtraction::DoAllGates ()
Definition at line 880 of file TBGSubtraction.cxx.
References MakeBGHisto1(), MakeBGHisto2(), and MakeGateHisto().
Referenced by DoProjectionCanvasZoomed(), ResetInterface(), and SetStatusFromUpdateCheckButton().
DoEntry()
void TBGSubtraction::DoEntry (Long_t)
Definition at line 749 of file TBGSubtraction.cxx.
References fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fGateEntryHigh, fGateEntryLow, fGateSlider, kBGHighEntry1, kBGHighEntry2, kBGLowEntry1, kBGLowEntry2, kGateHighEntry, kGateLowEntry, UpdateBGSlider1(), UpdateBGSlider2(), and UpdateGateSlider().
DoGateCanvasZoomed()
void TBGSubtraction::DoGateCanvasZoomed ()
Definition at line 796 of file TBGSubtraction.cxx.
References DrawPeakMarkers(), fGateCanvas, fPeakHighLimit, fPeakHighValue, fPeakLowLimit, fPeakLowValue, fPeakValue, and UpdatePeakSliders().
Referenced by InitializeInterface().
DoGateProjection()
void TBGSubtraction::DoGateProjection ()
Definition at line 948 of file TBGSubtraction.cxx.
References DrawPeakMarkers(), fBGCheckButton1, fBGCheckButton2, fBGHist1, fBGHist2, fBGParamEntry, fBGSlider1, fBGSlider2, fGateCanvas, fGateHist, fGateSlider, fProjection, fSubtractedBinHist, and fSubtractedHist.
Referenced by DoSlider(), ResetInterface(), SetStatusFromUpdateCheckButton(), and UpdateBackground().
DoPeakFit()
void TBGSubtraction::DoPeakFit ()
Definition at line 439 of file TBGSubtraction.cxx.
References TSinglePeak::Centroid(), DrawPeak(), fGateCanvas, TPeakFitter::Fit(), fPeak, fPeakFitter, fPeakHighValue, fPeakLowValue, fPeakValue, fSubtractedBinHist, TPeakFitter::ResetInitFlag(), and TPeakFitter::SetRange().
DoProjectionCanvasZoomed()
void TBGSubtraction::DoProjectionCanvasZoomed ()
Definition at line 829 of file TBGSubtraction.cxx.
References DoAllGates(), DrawAllMarkers(), fAutoUpdateCheckButton, fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fGateEntryHigh, fGateEntryLow, fProjectionCanvas, and UpdateProjectionSliders().
Referenced by InitializeInterface().
DoSlider()
void TBGSubtraction::DoSlider (Int_t pos = 0)
Definition at line 512 of file TBGSubtraction.cxx.
References DoGateProjection(), DrawBGMarkers1(), DrawBGMarkers2(), DrawGateMarkers(), DrawPeakMarkers(), fAutoUpdateCheckButton, fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fBGSlider1, fBGSlider2, fGateEntryHigh, fGateEntryLow, fGateSlider, fPeakHighValue, fPeakLowValue, fPeakSlider, fPeakValue, kBGSlider1, kBGSlider2, kBinningSlider, kGateSlider, kPeakSlider, MakeBGHisto1(), MakeBGHisto2(), MakeGateHisto(), and RebinProjection().
DrawAllMarkers()
void TBGSubtraction::DrawAllMarkers ()
Definition at line 710 of file TBGSubtraction.cxx.
References DrawBGMarkers1(), DrawBGMarkers2(), and DrawGateMarkers().
Referenced by DoProjectionCanvasZoomed(), ResetInterface(), and UpdateBackground().
DrawBGMarkers()
void TBGSubtraction::DrawBGMarkers (TGCheckButton *& check_button, GMarker *& low_marker, GMarker *& high_marker, TGNumberEntry *& low_entry, TGNumberEntry *& high_entry, Color_t color = kBlue) private
Definition at line 668 of file TBGSubtraction.cxx.
References GMarker::Draw(), fProjection, fProjectionCanvas, GMarker::GetBinX(), GMarker::GetLocalX(), GMarker::SetBinX(), GMarker::SetColor(), GMarker::SetHist(), GMarker::SetLineX(), and GMarker::SetLocalX().
Referenced by DrawBGMarkers1(), and DrawBGMarkers2().
DrawBGMarkers1()
void TBGSubtraction::DrawBGMarkers1 ()
Definition at line 700 of file TBGSubtraction.cxx.
References DrawBGMarkers(), fBGCheckButton1, fBGEntryHigh1, fBGEntryLow1, fHighBGMarker1, and fLowBGMarker1.
Referenced by DoSlider(), and DrawAllMarkers().
DrawBGMarkers2()
void TBGSubtraction::DrawBGMarkers2 ()
Definition at line 705 of file TBGSubtraction.cxx.
References DrawBGMarkers(), fBGCheckButton2, fBGEntryHigh2, fBGEntryLow2, fHighBGMarker2, and fLowBGMarker2.
Referenced by DoSlider(), and DrawAllMarkers().
DrawGateMarkers()
void TBGSubtraction::DrawGateMarkers ()
Definition at line 717 of file TBGSubtraction.cxx.
References GMarker::Draw(), fGateEntryHigh, fGateEntryLow, fHighGateMarker, fLowGateMarker, fProjection, fProjectionCanvas, GMarker::GetBinX(), GMarker::GetLocalX(), GMarker::SetBinX(), GMarker::SetColor(), GMarker::SetHist(), GMarker::SetLineX(), and GMarker::SetLocalX().
Referenced by DoSlider(), and DrawAllMarkers().
DrawOnNewCanvas()
void TBGSubtraction::DrawOnNewCanvas ()
Definition at line 1099 of file TBGSubtraction.cxx.
References fSubtractedBinHist.
DrawPeak()
void TBGSubtraction::DrawPeak ()
Definition at line 454 of file TBGSubtraction.cxx.
References TSinglePeak::Draw(), and fPeak.
Referenced by DoPeakFit().
DrawPeakMarkers()
void TBGSubtraction::DrawPeakMarkers ()
Definition at line 623 of file TBGSubtraction.cxx.
References GMarker::Draw(), fGateCanvas, fHighPeakMarker, fLowPeakMarker, fPeakHighValue, fPeakLowValue, fPeakMarker, fPeakValue, fSubtractedBinHist, GMarker::GetBinX(), GMarker::GetLocalX(), GMarker::SetBinX(), GMarker::SetColor(), GMarker::SetHist(), GMarker::SetLineX(), GMarker::SetLocalX(), and GMarker::SetStyle().
Referenced by DoGateCanvasZoomed(), DoGateProjection(), DoSlider(), RebinProjection(), and ResetInterface().
GateStatusInfo()
void TBGSubtraction::GateStatusInfo (Int_t event, Int_t px, Int_t py, TObject * selected)
Definition at line 1153 of file TBGSubtraction.cxx.
References fGateCanvas, and StatusInfo().
InitializeInterface()
void TBGSubtraction::InitializeInterface () private
Definition at line 220 of file TBGSubtraction.cxx.
References AxisComboSelected(), DoGateCanvasZoomed(), DoProjectionCanvasZoomed(), fAxisCombo, fGateAxis, fPeakCombo, PeakComboSelected(), ResetInterface(), and SetStatusFromUpdateCheckButton().
Referenced by TBGSubtraction().
MakeBGHisto1()
void TBGSubtraction::MakeBGHisto1 ()
Definition at line 906 of file TBGSubtraction.cxx.
References fBGEntryHigh1, fBGEntryLow1, fBGHist1, fBGSlider1, fGateAxis, fMatrix, and fProjectionCanvas.
Referenced by DoAllGates(), and DoSlider().
MakeBGHisto2()
void TBGSubtraction::MakeBGHisto2 ()
Definition at line 930 of file TBGSubtraction.cxx.
References fBGEntryHigh2, fBGEntryLow2, fBGHist2, fBGSlider2, fGateAxis, and fMatrix.
Referenced by DoAllGates(), and DoSlider().
MakeConnections()
void TBGSubtraction::MakeConnections () private
Connect Canvases to recognize that they have been zoomed This function includes setting the slider, and drawing the gate markers.
Definition at line 44 of file TBGSubtraction.cxx.
References fAutoUpdateCheckButton, fAxisCombo, fBGCheckButton1, fBGCheckButton2, fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fBGParamEntry, fBGSlider1, fBGSlider2, fBinningSlider, fGateCanvas, fGateEntryHigh, fGateEntryLow, fGateSlider, fPeakCombo, fPeakFitButton, fPeakSlider, fProjectionCanvas, and fWrite2FileButton.
Referenced by TBGSubtraction().
MakeGateHisto()
void TBGSubtraction::MakeGateHisto ()
Definition at line 887 of file TBGSubtraction.cxx.
References fAxisCombo, fGateAxis, fGateEntryHigh, fGateEntryLow, fGateHist, fGateSlider, and fMatrix.
Referenced by DoAllGates(), and DoSlider().
operator=() [1/2]
TBGSubtraction & TBGSubtraction::operator= (const TBGSubtraction &) delete
operator=() [2/2]
TBGSubtraction & TBGSubtraction::operator= (TBGSubtraction &&) delete
PeakComboSelected()
void TBGSubtraction::PeakComboSelected ()
Definition at line 588 of file TBGSubtraction.cxx.
References TPeakFitter::AddPeak(), fPeak, fPeakCombo, fPeakFitter, kAB3Peak, kABPeak, kGauss, kRWPeak, TPeakFitter::RemovePeak(), and TPeakFitter::ResetInitFlag().
Referenced by InitializeInterface().
ProjectionStatusInfo()
void TBGSubtraction::ProjectionStatusInfo (Int_t event, Int_t px, Int_t py, TObject * selected)
Definition at line 1159 of file TBGSubtraction.cxx.
References fProjectionCanvas, and StatusInfo().
RebinProjection()
void TBGSubtraction::RebinProjection () private
Definition at line 1189 of file TBGSubtraction.cxx.
References DrawPeakMarkers(), fBinningSlider, fGateCanvas, fSubtractedBinHist, and fSubtractedHist.
Referenced by DoSlider().
ResetInterface()
void TBGSubtraction::ResetInterface () private
Definition at line 164 of file TBGSubtraction.cxx.
References DoAllGates(), DoGateProjection(), DrawAllMarkers(), DrawPeakMarkers(), fBGEntryHigh1, fBGEntryHigh2, fBGEntryLow1, fBGEntryLow2, fGateCanvas, fGateEntryHigh, fGateEntryLow, fPeakHighLimit, fPeakHighValue, fPeakLowLimit, fPeakLowValue, fPeakValue, fProjectionCanvas, fSubtractedBinHist, UpdateBinningSlider(), UpdatePeakSliders(), and UpdateProjectionSliders().
Referenced by AxisComboSelected(), and InitializeInterface().
SetStatusFromUpdateCheckButton()
void TBGSubtraction::SetStatusFromUpdateCheckButton ()
Definition at line 1171 of file TBGSubtraction.cxx.
References DoAllGates(), DoGateProjection(), fAutoUpdateCheckButton, fPeakFitButton, and fWrite2FileButton.
Referenced by InitializeInterface().
StatusInfo()
void TBGSubtraction::StatusInfo (Int_t event, Int_t px, Int_t py, TObject * selected) private
Definition at line 1165 of file TBGSubtraction.cxx.
References fProjectionStatus.
Referenced by GateStatusInfo(), and ProjectionStatusInfo().
UpdateBackground()
void TBGSubtraction::UpdateBackground ()
Definition at line 422 of file TBGSubtraction.cxx.
References DoGateProjection(), GMarker::Draw(), DrawAllMarkers(), fAutoUpdateCheckButton, fBGCheckButton1, fBGCheckButton2, fBGParamEntry, fGateCanvas, fProjection, and fProjectionCanvas.
UpdateBGSlider1()
void TBGSubtraction::UpdateBGSlider1 () private
Definition at line 474 of file TBGSubtraction.cxx.
References fBGEntryHigh1, fBGEntryLow1, and fBGSlider1.
Referenced by DoEntry(), and UpdateProjectionSliders().
UpdateBGSlider2()
void TBGSubtraction::UpdateBGSlider2 () private
Definition at line 480 of file TBGSubtraction.cxx.
References fBGEntryHigh2, fBGEntryLow2, and fBGSlider2.
Referenced by DoEntry(), and UpdateProjectionSliders().
UpdateBinningSlider()
void TBGSubtraction::UpdateBinningSlider () private
Definition at line 505 of file TBGSubtraction.cxx.
References fBinningSlider, and fMaxBinning.
Referenced by ResetInterface().
UpdateGateSlider()
void TBGSubtraction::UpdateGateSlider () private
Definition at line 468 of file TBGSubtraction.cxx.
References fGateEntryHigh, fGateEntryLow, and fGateSlider.
Referenced by DoEntry(), and UpdateProjectionSliders().
UpdatePeakSliders()
void TBGSubtraction::UpdatePeakSliders ()
Definition at line 495 of file TBGSubtraction.cxx.
References fPeakHighLimit, fPeakHighValue, fPeakLowLimit, fPeakLowValue, fPeakSlider, and fPeakValue.
Referenced by DoGateCanvasZoomed(), and ResetInterface().
UpdateProjectionSliders()
void TBGSubtraction::UpdateProjectionSliders ()
Definition at line 486 of file TBGSubtraction.cxx.
References UpdateBGSlider1(), UpdateBGSlider2(), and UpdateGateSlider().
Referenced by DoProjectionCanvasZoomed(), and ResetInterface().
WriteHistograms()
void TBGSubtraction::WriteHistograms ()
Definition at line 1109 of file TBGSubtraction.cxx.
References fBGHist1, fBGHist2, fGateHist, fHistogramDescription, fSubtractedHist, and fWrite2FileName.
Member Data Documentation
fAutoUpdateCheckButton
TGCheckButton* TBGSubtraction::fAutoUpdateCheckButton {nullptr} private
Definition at line 107 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoProjectionCanvasZoomed(), DoSlider(), MakeConnections(), SetStatusFromUpdateCheckButton(), and UpdateBackground().
fAxisCombo
TGComboBox* TBGSubtraction::fAxisCombo {nullptr} private
Definition at line 135 of file TBGSubtraction.h.
Referenced by AxisComboSelected(), BuildInterface(), Disconnect(), InitializeInterface(), MakeConnections(), and MakeGateHisto().
fBGCheckButton1
TGCheckButton* TBGSubtraction::fBGCheckButton1 {nullptr} private
Definition at line 105 of file TBGSubtraction.h.
Referenced by BuildInterface(), ClickedBGButton1(), Disconnect(), DoGateProjection(), DrawBGMarkers1(), MakeConnections(), and UpdateBackground().
fBGCheckButton2
TGCheckButton* TBGSubtraction::fBGCheckButton2 {nullptr} private
Definition at line 106 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoGateProjection(), DrawBGMarkers2(), MakeConnections(), and UpdateBackground().
fBGEntryFrame1
TGHorizontalFrame* TBGSubtraction::fBGEntryFrame1 {nullptr} private
Definition at line 129 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBGEntryFrame2
TGHorizontalFrame* TBGSubtraction::fBGEntryFrame2 {nullptr} private
Definition at line 130 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBGEntryHigh1
TGNumberEntry* TBGSubtraction::fBGEntryHigh1 {nullptr} private
Definition at line 98 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawBGMarkers1(), MakeBGHisto1(), MakeConnections(), ResetInterface(), and UpdateBGSlider1().
fBGEntryHigh2
TGNumberEntry* TBGSubtraction::fBGEntryHigh2 {nullptr} private
Definition at line 100 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawBGMarkers2(), MakeBGHisto2(), MakeConnections(), ResetInterface(), and UpdateBGSlider2().
fBGEntryLow1
TGNumberEntry* TBGSubtraction::fBGEntryLow1 {nullptr} private
Definition at line 97 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawBGMarkers1(), MakeBGHisto1(), MakeConnections(), ResetInterface(), and UpdateBGSlider1().
fBGEntryLow2
TGNumberEntry* TBGSubtraction::fBGEntryLow2 {nullptr} private
Definition at line 99 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawBGMarkers2(), MakeBGHisto2(), MakeConnections(), ResetInterface(), and UpdateBGSlider2().
fBGHist1
TH1* TBGSubtraction::fBGHist1 {nullptr} private
Definition at line 87 of file TBGSubtraction.h.
Referenced by DoGateProjection(), MakeBGHisto1(), and WriteHistograms().
fBGHist2
TH1* TBGSubtraction::fBGHist2 {nullptr} private
Definition at line 88 of file TBGSubtraction.h.
Referenced by DoGateProjection(), MakeBGHisto2(), and WriteHistograms().
fBGParamEntry
TGNumberEntry* TBGSubtraction::fBGParamEntry {nullptr} private
Definition at line 96 of file TBGSubtraction.h.
Referenced by BuildInterface(), ClickedBGButton1(), Disconnect(), DoGateProjection(), MakeConnections(), and UpdateBackground().
fBGParamFrame
TGHorizontalFrame* TBGSubtraction::fBGParamFrame {nullptr} private
Definition at line 127 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBGParamLabel
TGLabel* TBGSubtraction::fBGParamLabel {nullptr} private
Definition at line 103 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBGSlider1
TGDoubleHSlider* TBGSubtraction::fBGSlider1 {nullptr} private
Definition at line 92 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoGateProjection(), DoSlider(), MakeBGHisto1(), MakeConnections(), and UpdateBGSlider1().
fBGSlider2
TGDoubleHSlider* TBGSubtraction::fBGSlider2 {nullptr} private
Definition at line 93 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoGateProjection(), DoSlider(), MakeBGHisto2(), MakeConnections(), and UpdateBGSlider2().
fBinningFrame
TGHorizontalFrame* TBGSubtraction::fBinningFrame {nullptr} private
Definition at line 126 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBinningLabel
TGLabel* TBGSubtraction::fBinningLabel {nullptr} private
Definition at line 104 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBinningSlider
TGHSlider* TBGSubtraction::fBinningSlider {nullptr} private
Definition at line 95 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), MakeConnections(), RebinProjection(), and UpdateBinningSlider().
fBly
TGLayoutHints* TBGSubtraction::fBly {nullptr} private
Definition at line 109 of file TBGSubtraction.h.
Referenced by BuildInterface().
fBly1
TGLayoutHints* TBGSubtraction::fBly1 {nullptr} private
Definition at line 110 of file TBGSubtraction.h.
Referenced by BuildInterface().
fButtonFrame
TGHorizontalFrame* TBGSubtraction::fButtonFrame {nullptr} private
Definition at line 132 of file TBGSubtraction.h.
Referenced by BuildInterface().
fCurrentFile
TFile* TBGSubtraction::fCurrentFile {nullptr} private
Definition at line 149 of file TBGSubtraction.h.
Referenced by TBGSubtraction().
fDescriptionFrame
TGHorizontalFrame* TBGSubtraction::fDescriptionFrame {nullptr} private
Definition at line 131 of file TBGSubtraction.h.
Referenced by BuildInterface().
fForceUpdate
Bool_t TBGSubtraction::fForceUpdate {true} private
Definition at line 153 of file TBGSubtraction.h.
fGateAxis
Int_t TBGSubtraction::fGateAxis {0} private
Definition at line 151 of file TBGSubtraction.h.
Referenced by TBGSubtraction(), AxisComboSelected(), InitializeInterface(), MakeBGHisto1(), MakeBGHisto2(), and MakeGateHisto().
fGateCanvas
TRootEmbeddedCanvas* TBGSubtraction::fGateCanvas {nullptr} private
Definition at line 83 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoGateCanvasZoomed(), DoGateProjection(), DoPeakFit(), DrawPeakMarkers(), GateStatusInfo(), MakeConnections(), RebinProjection(), ResetInterface(), and UpdateBackground().
fGateEntryFrame
TGHorizontalFrame* TBGSubtraction::fGateEntryFrame {nullptr} private
Definition at line 128 of file TBGSubtraction.h.
Referenced by BuildInterface().
fGateEntryHigh
TGNumberEntry* TBGSubtraction::fGateEntryHigh {nullptr} private
Definition at line 102 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawGateMarkers(), MakeConnections(), MakeGateHisto(), ResetInterface(), and UpdateGateSlider().
fGateEntryLow
TGNumberEntry* TBGSubtraction::fGateEntryLow {nullptr} private
Definition at line 101 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoProjectionCanvasZoomed(), DoSlider(), DrawGateMarkers(), MakeConnections(), MakeGateHisto(), ResetInterface(), and UpdateGateSlider().
fGateFrame
TGVerticalFrame* TBGSubtraction::fGateFrame {nullptr} private
Definition at line 123 of file TBGSubtraction.h.
Referenced by BuildInterface().
fGateHist
TH1* TBGSubtraction::fGateHist {nullptr} private
Definition at line 86 of file TBGSubtraction.h.
Referenced by DoGateProjection(), MakeGateHisto(), and WriteHistograms().
fGateSlider
TGDoubleHSlider* TBGSubtraction::fGateSlider {nullptr} private
Definition at line 91 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoEntry(), DoGateProjection(), DoSlider(), MakeConnections(), MakeGateHisto(), and UpdateGateSlider().
fHighBGMarker1
GMarker* TBGSubtraction::fHighBGMarker1 {nullptr} private
Definition at line 142 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawBGMarkers1().
fHighBGMarker2
GMarker* TBGSubtraction::fHighBGMarker2 {nullptr} private
Definition at line 144 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawBGMarkers2().
fHighGateMarker
GMarker* TBGSubtraction::fHighGateMarker {nullptr} private
Definition at line 140 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawGateMarkers().
fHighPeakMarker
GMarker* TBGSubtraction::fHighPeakMarker {nullptr} private
Definition at line 146 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawPeakMarkers().
fHistogramDescription
TGTextEntry* TBGSubtraction::fHistogramDescription {nullptr} private
Definition at line 115 of file TBGSubtraction.h.
Referenced by BuildInterface(), and WriteHistograms().
fLayoutCanvases
TGLayoutHints* TBGSubtraction::fLayoutCanvases {nullptr} private
Definition at line 111 of file TBGSubtraction.h.
Referenced by BuildInterface().
fLayoutParam
TGLayoutHints* TBGSubtraction::fLayoutParam {nullptr} private
Definition at line 112 of file TBGSubtraction.h.
Referenced by BuildInterface().
fLowBGMarker1
GMarker* TBGSubtraction::fLowBGMarker1 {nullptr} private
Definition at line 141 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawBGMarkers1().
fLowBGMarker2
GMarker* TBGSubtraction::fLowBGMarker2 {nullptr} private
Definition at line 143 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawBGMarkers2().
fLowGateMarker
GMarker* TBGSubtraction::fLowGateMarker {nullptr} private
Definition at line 139 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawGateMarkers().
fLowPeakMarker
GMarker* TBGSubtraction::fLowPeakMarker {nullptr} private
Definition at line 145 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawPeakMarkers().
fMain
TGMainFrame* TBGSubtraction::fMain {nullptr} private
Definition at line 81 of file TBGSubtraction.h.
fMatrix
TH2* TBGSubtraction::fMatrix {nullptr} private
Definition at line 84 of file TBGSubtraction.h.
Referenced by TBGSubtraction(), AxisComboSelected(), MakeBGHisto1(), MakeBGHisto2(), and MakeGateHisto().
fMaxBinning
Int_t TBGSubtraction::fMaxBinning {20} private
maximum binning possible with binning slider (hard-coded, for now?)
Definition at line 163 of file TBGSubtraction.h.
Referenced by BuildInterface(), and UpdateBinningSlider().
fPeak
TSinglePeak* TBGSubtraction::fPeak {nullptr} private
the peak to be fit (will be a class that inherits from TSinglePeak)
Definition at line 160 of file TBGSubtraction.h.
Referenced by DoPeakFit(), DrawPeak(), and PeakComboSelected().
fPeakCombo
TGComboBox* TBGSubtraction::fPeakCombo {nullptr} private
Definition at line 136 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), InitializeInterface(), MakeConnections(), and PeakComboSelected().
fPeakFitButton
TGTextButton* TBGSubtraction::fPeakFitButton {nullptr} private
Definition at line 117 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), MakeConnections(), and SetStatusFromUpdateCheckButton().
fPeakFitFrame
TGHorizontalFrame* TBGSubtraction::fPeakFitFrame {nullptr} private
Definition at line 125 of file TBGSubtraction.h.
Referenced by BuildInterface().
fPeakFitter
TPeakFitter* TBGSubtraction::fPeakFitter {nullptr} private
the peak fitter that fPeak is added to
Definition at line 161 of file TBGSubtraction.h.
Referenced by DoPeakFit(), and PeakComboSelected().
fPeakHighLimit
Double_t TBGSubtraction::fPeakHighLimit {0.} private
upper limit for peak slider range
Definition at line 155 of file TBGSubtraction.h.
Referenced by DoGateCanvasZoomed(), ResetInterface(), and UpdatePeakSliders().
fPeakHighValue
Double_t TBGSubtraction::fPeakHighValue {0.} private
high range for fit
Definition at line 157 of file TBGSubtraction.h.
Referenced by DoGateCanvasZoomed(), DoPeakFit(), DoSlider(), DrawPeakMarkers(), ResetInterface(), and UpdatePeakSliders().
fPeakLowLimit
Double_t TBGSubtraction::fPeakLowLimit {0.} private
lower limit for peak slider range
Definition at line 154 of file TBGSubtraction.h.
Referenced by DoGateCanvasZoomed(), ResetInterface(), and UpdatePeakSliders().
fPeakLowValue
Double_t TBGSubtraction::fPeakLowValue {0.} private
low range for fit
Definition at line 156 of file TBGSubtraction.h.
Referenced by DoGateCanvasZoomed(), DoPeakFit(), DoSlider(), DrawPeakMarkers(), ResetInterface(), and UpdatePeakSliders().
fPeakMarker
GMarker* TBGSubtraction::fPeakMarker {nullptr} private
Definition at line 147 of file TBGSubtraction.h.
Referenced by ~TBGSubtraction(), and DrawPeakMarkers().
fPeakSlider
TGTripleHSlider* TBGSubtraction::fPeakSlider {nullptr} private
Definition at line 94 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), DoSlider(), MakeConnections(), and UpdatePeakSliders().
fPeakValue
Double_t TBGSubtraction::fPeakValue {0.} private
centroid for fit
Definition at line 158 of file TBGSubtraction.h.
Referenced by DoGateCanvasZoomed(), DoPeakFit(), DoSlider(), DrawPeakMarkers(), ResetInterface(), and UpdatePeakSliders().
fProjection
TH1* TBGSubtraction::fProjection {nullptr} private
Definition at line 85 of file TBGSubtraction.h.
Referenced by TBGSubtraction(), AxisComboSelected(), DoGateProjection(), DrawBGMarkers(), DrawGateMarkers(), and UpdateBackground().
fProjectionCanvas
TRootEmbeddedCanvas* TBGSubtraction::fProjectionCanvas {nullptr} private
Definition at line 82 of file TBGSubtraction.h.
Referenced by AxisComboSelected(), BuildInterface(), Disconnect(), DoProjectionCanvasZoomed(), DrawBGMarkers(), DrawGateMarkers(), MakeBGHisto1(), MakeConnections(), ProjectionStatusInfo(), ResetInterface(), and UpdateBackground().
fProjectionFrame
TGVerticalFrame* TBGSubtraction::fProjectionFrame {nullptr} private
Definition at line 124 of file TBGSubtraction.h.
Referenced by BuildInterface().
fProjectionStatus
TGStatusBar* TBGSubtraction::fProjectionStatus {nullptr} private
Definition at line 120 of file TBGSubtraction.h.
Referenced by BuildInterface(), and StatusInfo().
fSubtractedBinHist
TH1* TBGSubtraction::fSubtractedBinHist {nullptr} private
Definition at line 90 of file TBGSubtraction.h.
Referenced by DoGateProjection(), DoPeakFit(), DrawOnNewCanvas(), DrawPeakMarkers(), RebinProjection(), and ResetInterface().
fSubtractedHist
TH1* TBGSubtraction::fSubtractedHist {nullptr} private
Definition at line 89 of file TBGSubtraction.h.
Referenced by DoGateProjection(), RebinProjection(), and WriteHistograms().
fWrite2FileButton
TGTextButton* TBGSubtraction::fWrite2FileButton {nullptr} private
Definition at line 116 of file TBGSubtraction.h.
Referenced by BuildInterface(), Disconnect(), MakeConnections(), and SetStatusFromUpdateCheckButton().
fWrite2FileName
TGTextEntry* TBGSubtraction::fWrite2FileName {nullptr} private
Definition at line 114 of file TBGSubtraction.h.
Referenced by BuildInterface(), and WriteHistograms().