GRSISort: GH1D Class Reference
GH1D Class Reference
Detailed Description
Definition at line 17 of file GH1D.h.
Public Member Functions
GH1D ()
GH1D (const char *name, const char *title, Int_t nbinsx, const Double_t *xbins)
GH1D (const char *name, const char *title, Int_t nbinsx, const Float_t *xbins)
GH1D (const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup)
GH1D (const TF1 &function, Int_t nbinsx, Double_t xlow, Double_t xup)
GH1D (const TH1 &source)
GH1D (const TH1 *source)
GH1D (const TVectorD &vec)
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
void Draw (Option_t *opt="") override
TH1 * DrawCopy (Option_t *opt="", const char *name_postfix="copy") const override
TH1 * DrawNormalized (Option_t *opt="", Double_t norm=1) const override
void DrawRegions (Option_t *opt="")
GH1D * GetNext (bool DrawEmpty=false) const
TVirtualPad * GetPad () const
TObject * GetParent () const
GH1D * GetPrevious (bool DrawEmpty=false) const
int GetProjectionAxis () const
void HandleEvent (Event_t *event, Window_t window)
void HandleMovement (Int_t eventType, Int_t eventX, Int_t eventY, TObject *selected)
TList * ListOfRegions ()
TVirtualPad * Pad () const
void Print (Option_t *opt="") const override
void PrintRegions ()
GH1D * Project (double value_low, double value_high) const
GH1D * Project (int bins=-1)
GH1D * Project_Background (double value_low, double value_high, double bg_value_low, double bg_value_high, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground) const
void RemoveRegion (TRegion *region)
void SetPad (TVirtualPad *pad)
void SetParent (TObject *obj)
void SetProjectionAxis (int axis)
void UpdatePad ()
void UpdateRegions ()
bool WriteDatFile (const char *outFile)
Static Public Member Functions
static EVerbosity VerboseLevel ()
static void VerboseLevel (EVerbosity level)
Private Member Functions
void RemoveCurrentRegion ()
Private Attributes
bool fBackground {false}
TBox * fCurrentRegion {nullptr}
bool fGate {false}
size_t fNofRegions {0}
TVirtualPad * fPad {nullptr}
TRef fParent
int fProjectionAxis
bool fRegion {false}
std::array< int, 3 > fRegionColor {kOrange + 2, kGreen + 2, kCyan + 2}
TList fRegions
double fStartX {0.}
double fStartY {0.}
Static Private Attributes
static EVerbosity fVerboseLevel = EVerbosity::kQuiet
Constructor & Destructor Documentation
GH1D() [1/8]
GH1D::GH1D () inline
Definition at line 19 of file GH1D.h.
Referenced by Project().
GH1D() [2/8]
GH1D::GH1D (const TVectorD & vec) inline explicit
Definition at line 20 of file GH1D.h.
GH1D() [3/8]
GH1D::GH1D (const char * name, const char * title, Int_t nbinsx, const Float_t * xbins) inline
Definition at line 21 of file GH1D.h.
GH1D() [4/8]
GH1D::GH1D (const char * name, const char * title, Int_t nbinsx, const Double_t * xbins) inline
Definition at line 25 of file GH1D.h.
GH1D() [5/8]
GH1D::GH1D (const char * name, const char * title, Int_t nbinsx, Double_t xlow, Double_t xup) inline
Definition at line 29 of file GH1D.h.
GH1D() [6/8]
GH1D::GH1D (const TF1 & function, Int_t nbinsx, Double_t xlow, Double_t xup)
Definition at line 34 of file GH1D.cxx.
GH1D() [7/8]
GH1D::GH1D (const TH1 & source) explicit
Definition at line 24 of file GH1D.cxx.
GH1D() [8/8]
GH1D::GH1D (const TH1 * source) explicit
Definition at line 29 of file GH1D.cxx.
Member Function Documentation
Clear()
void GH1D::Clear (Option_t * opt = "") override
Definition at line 89 of file GH1D.cxx.
References fParent.
Referenced by TSourceTab::FindCalibratedPeaks(), and TSourceTab::InitialCalibration().
Copy()
void GH1D::Copy (TObject & obj) const override
Definition at line 101 of file GH1D.cxx.
References fParent.
Draw()
void GH1D::Draw (Option_t * opt = "") override
Definition at line 108 of file GH1D.cxx.
References DrawRegions(), and SetPad().
Referenced by TSourceTab::Draw(), DrawRegions(), GetProjection(), and GCanvas::Process1DKeyboardPress().
DrawCopy()
TH1 * GH1D::DrawCopy (Option_t * opt = "", const char * name_postfix = "copy") const override
Definition at line 124 of file GH1D.cxx.
References hist.
DrawNormalized()
TH1 * GH1D::DrawNormalized (Option_t * opt = "", Double_t norm = 1) const override
Definition at line 134 of file GH1D.cxx.
References hist.
DrawRegions()
void GH1D::DrawRegions (Option_t * opt = "")
Definition at line 534 of file GH1D.cxx.
References Draw(), and fRegions.
Referenced by Draw(), and HandleEvent().
GetNext()
GH1D * GH1D::GetNext (bool DrawEmpty = false) const
Definition at line 157 of file GH1D.cxx.
References fParent, and GH2Base::GetNext().
Referenced by Move1DHistogram().
GetPad()
TVirtualPad * GH1D::GetPad () const inline
Definition at line 43 of file GH1D.h.
References fPad.
GetParent()
TObject * GH1D::GetParent () const inline
Definition at line 40 of file GH1D.h.
References fParent.
Referenced by GCanvas::Process1DKeyboardPress().
GetPrevious()
GH1D * GH1D::GetPrevious (bool DrawEmpty = false) const
Definition at line 144 of file GH1D.cxx.
References fParent, and GH2Base::GetPrevious().
Referenced by Move1DHistogram().
GetProjectionAxis()
int GH1D::GetProjectionAxis () const inline
Definition at line 46 of file GH1D.h.
References fProjectionAxis.
HandleEvent()
void GH1D::HandleEvent (Event_t * event, Window_t window)
Definition at line 278 of file GH1D.cxx.
References TRegion::Draw(), DrawRegions(), fBackground, fCurrentRegion, fGate, fNofRegions, fPad, fRegion, fRegionColor, fRegions, fStartX, fStartY, hex(), kAll, kBackground, kBasicFlow, kGate, kLoops, kQuiet, kRegion, kSubroutines, Move1DHistogram(), Pad(), PrintRegions(), RemoveCurrentRegion(), UpdatePad(), and VerboseLevel().
HandleMovement()
void GH1D::HandleMovement (Int_t eventType, Int_t eventX, Int_t eventY, TObject * selected)
Definition at line 248 of file GH1D.cxx.
References fPad, fStartX, fStartY, kBasicFlow, kLoops, kSubroutines, RemoveRegion(), and VerboseLevel().
ListOfRegions()
TList * GH1D::ListOfRegions () inline
Definition at line 68 of file GH1D.h.
References fRegions.
Referenced by TSourceTab::UpdateRegions().
Pad()
TVirtualPad * GH1D::Pad () const inline
Definition at line 67 of file GH1D.h.
References fPad.
Referenced by TRegion::Draw(), HandleEvent(), TRegion::Hide(), PrintRegions(), and TRegion::Update().
Print()
void GH1D::Print (Option_t * opt = "") const override
Definition at line 95 of file GH1D.cxx.
References fParent.
Referenced by TSourceTab::UpdateRegions().
PrintRegions()
void GH1D::PrintRegions ()
Definition at line 541 of file GH1D.cxx.
References Pad().
Referenced by HandleEvent(), and TRegion::Hide().
Project() [1/2]
GH1D * GH1D::Project (double value_low, double value_high) const
Definition at line 170 of file GH1D.cxx.
References fParent, fProjectionAxis, GH2D::ProjectionX(), and GH2D::ProjectionY().
Project() [2/2]
GH1D * GH1D::Project (int bins = -1)
Definition at line 220 of file GH1D.cxx.
References GH1D().
Referenced by GetProjection(), and GCanvas::Process1DKeyboardPress().
Project_Background()
GH1D * GH1D::Project_Background (double value_low, double value_high, double bg_value_low, double bg_value_high, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground) const
Definition at line 190 of file GH1D.cxx.
References fParent, fProjectionAxis, GH2Base::ProjectionX_Background(), and GH2Base::ProjectionY_Background().
Referenced by GetProjection(), and GCanvas::Process1DKeyboardPress().
RemoveCurrentRegion()
void GH1D::RemoveCurrentRegion () private
Definition at line 554 of file GH1D.cxx.
References fBackground, fCurrentRegion, fGate, fPad, and fRegion.
Referenced by HandleEvent().
RemoveRegion()
void GH1D::RemoveRegion (TRegion * region)
Definition at line 564 of file GH1D.cxx.
References fPad, and fRegions.
Referenced by HandleMovement().
SetPad()
void GH1D::SetPad (TVirtualPad * pad)
Definition at line 241 of file GH1D.cxx.
References fPad.
Referenced by Draw().
SetParent()
void GH1D::SetParent (TObject * obj) inline
Definition at line 41 of file GH1D.h.
References fParent.
Referenced by GH2Base::GH2ProjectionX(), and GH2Base::GH2ProjectionY().
SetProjectionAxis()
void GH1D::SetProjectionAxis (int axis) inline
Definition at line 47 of file GH1D.h.
References fProjectionAxis.
Referenced by GH2Base::GH2ProjectionX(), and GH2Base::GH2ProjectionY().
UpdatePad()
void GH1D::UpdatePad () inline
Definition at line 75 of file GH1D.h.
References fPad.
Referenced by TRegion::Draw(), and HandleEvent().
UpdateRegions()
void GH1D::UpdateRegions ()
Definition at line 527 of file GH1D.cxx.
References fRegions.
VerboseLevel() [1/2]
static EVerbosity GH1D::VerboseLevel () inline static
Definition at line 85 of file GH1D.h.
References fVerboseLevel.
Referenced by TRegion::Draw(), HandleEvent(), HandleMovement(), TRegion::Hide(), TRegion::Update(), and TRegion::Update().
VerboseLevel() [2/2]
static void GH1D::VerboseLevel (EVerbosity level) inline static
Definition at line 84 of file GH1D.h.
References fVerboseLevel.
WriteDatFile()
bool GH1D::WriteDatFile (const char * outFile)
Definition at line 43 of file GH1D.cxx.
Member Data Documentation
fBackground
bool GH1D::fBackground {false} private
Definition at line 97 of file GH1D.h.
Referenced by HandleEvent(), and RemoveCurrentRegion().
fCurrentRegion
TBox* GH1D::fCurrentRegion {nullptr} private
! box for the current region
Definition at line 99 of file GH1D.h.
Referenced by HandleEvent(), and RemoveCurrentRegion().
fGate
bool GH1D::fGate {false} private
Definition at line 96 of file GH1D.h.
Referenced by HandleEvent(), and RemoveCurrentRegion().
fNofRegions
size_t GH1D::fNofRegions {0} private
! counts number of regions in this histogram, only used to set the color of the region
Definition at line 101 of file GH1D.h.
Referenced by HandleEvent().
fPad
TVirtualPad* GH1D::fPad {nullptr} private
!
Definition at line 92 of file GH1D.h.
Referenced by GetPad(), HandleEvent(), HandleMovement(), Pad(), RemoveCurrentRegion(), RemoveRegion(), SetPad(), and UpdatePad().
fParent
TRef GH1D::fParent private
Definition at line 90 of file GH1D.h.
Referenced by Clear(), Copy(), GetNext(), GetParent(), GetPrevious(), Print(), Project(), Project_Background(), and SetParent().
fProjectionAxis
int GH1D::fProjectionAxis private
Definition at line 91 of file GH1D.h.
Referenced by GetProjectionAxis(), Project(), Project_Background(), and SetProjectionAxis().
fRegion
bool GH1D::fRegion {false} private
Definition at line 98 of file GH1D.h.
Referenced by HandleEvent(), and RemoveCurrentRegion().
fRegionColor
std::array<int, 3> GH1D::fRegionColor {kOrange + 2, kGreen + 2, kCyan + 2} private
Definition at line 100 of file GH1D.h.
Referenced by HandleEvent().
fRegions
TList GH1D::fRegions private
Definition at line 102 of file GH1D.h.
Referenced by DrawRegions(), HandleEvent(), ListOfRegions(), RemoveRegion(), and UpdateRegions().
fStartX
double GH1D::fStartX {0.} private
! initial x-position of new region
Definition at line 94 of file GH1D.h.
Referenced by HandleEvent(), and HandleMovement().
fStartY
double GH1D::fStartY {0.} private
! initial y-position of new region
Definition at line 95 of file GH1D.h.
Referenced by HandleEvent(), and HandleMovement().
fVerboseLevel
EVerbosity GH1D::fVerboseLevel = EVerbosity::kQuiet static private
! level of verbosity
Definition at line 104 of file GH1D.h.
Referenced by VerboseLevel(), and VerboseLevel().