GRSISort: TParameterInput Class Reference
TParameterInput Class Reference
GUI
Detailed Description
Definition at line 32 of file TCalibrateDescant.h.
Public Member Functions
TParameterInput (const TParameterInput &)=delete
TParameterInput (TGVerticalFrame *&frame)
TParameterInput (TParameterInput &&) noexcept=delete
~TParameterInput ()=default
TGHorizontalFrame * Build (const std::string &name, const Int_t &baseId, const Double_t &xmin, const Double_t &xmax)
void Connect (TCalibrateDescant *parent)
double HighLimit () const
double LowLimit () const
const char * Name () const
TParameterInput & operator= (const TParameterInput &)=delete
TParameterInput & operator= (TParameterInput &&) noexcept=delete
Bool_t ProcessMessage (Long_t msg, Long_t parameter1, Long_t parameter2) override
void Set (double val)
void Set (double val, double low, double high)
void UpdateEntries ()
void UpdateSlider ()
double Value () const
Private Member Functions
void PrintStatus (const char *)
Private Attributes
Int_t fBaseId {-1}
TGNumberEntry * fEntry {nullptr}
TGNumberEntry * fEntryHigh {nullptr}
TGNumberEntry * fEntryLow {nullptr}
TGLabel * fLabel {nullptr}
TGTripleHSlider * fSlider {nullptr}
Constructor & Destructor Documentation
TParameterInput() [1/3]
TParameterInput::TParameterInput (TGVerticalFrame *& frame) inline explicit
Definition at line 34 of file TCalibrateDescant.h.
TParameterInput() [2/3]
TParameterInput::TParameterInput (const TParameterInput &) delete
TParameterInput() [3/3]
TParameterInput::TParameterInput (TParameterInput &&) delete noexcept
~TParameterInput()
TParameterInput::~TParameterInput () default
Member Function Documentation
Build()
TGHorizontalFrame * TParameterInput::Build (const std::string & name, const Int_t & baseId, const Double_t & xmin, const Double_t & xmax)
Definition at line 95 of file TCalibrateDescant.cxx.
References fBaseId, fEntry, fEntryHigh, fEntryLow, fLabel, and fSlider.
Referenced by TCalibrateDescant::BuildInterface().
Connect()
void TParameterInput::Connect (TCalibrateDescant * parent)
Definition at line 164 of file TCalibrateDescant.cxx.
References fEntry, fEntryHigh, fEntryLow, and fSlider.
Referenced by TCalibrateDescant::MakeConnections().
HighLimit()
double TParameterInput::HighLimit () const inline
Definition at line 46 of file TCalibrateDescant.h.
References fEntryHigh.
Referenced by TCalibrateDescant::Fit(), PrintStatus(), and UpdateSlider().
LowLimit()
double TParameterInput::LowLimit () const inline
Definition at line 45 of file TCalibrateDescant.h.
References fEntryLow.
Referenced by TCalibrateDescant::Fit(), PrintStatus(), and UpdateSlider().
Name()
const char * TParameterInput::Name () const inline
Definition at line 48 of file TCalibrateDescant.h.
References fLabel.
Referenced by TCalibrateDescant::InitializeParameters(), and PrintStatus().
operator=() [1/2]
TParameterInput & TParameterInput::operator= (const TParameterInput &) delete
operator=() [2/2]
TParameterInput & TParameterInput::operator= (TParameterInput &&) delete noexcept
PrintStatus()
void TParameterInput::PrintStatus (const char * function) private
Definition at line 204 of file TCalibrateDescant.cxx.
References fSlider, HighLimit(), LowLimit(), Name(), and Value().
Referenced by Set(), Set(), UpdateEntries(), and UpdateSlider().
ProcessMessage()
Bool_t TParameterInput::ProcessMessage (Long_t msg, Long_t parameter1, Long_t parameter2) override
This functions deals with changes in the text fields of the TGNumberEntry as those don't seem to emit signals?
Definition at line 180 of file TCalibrateDescant.cxx.
References UpdateSlider().
Set() [1/2]
void TParameterInput::Set (double val)
Definition at line 121 of file TCalibrateDescant.cxx.
References fEntry, PrintStatus(), and UpdateSlider().
Referenced by TCalibrateDescant::InitializeParameters(), and TCalibrateDescant::UpdateInitialParameters().
Set() [2/2]
void TParameterInput::Set (double val, double low, double high)
Definition at line 130 of file TCalibrateDescant.cxx.
References fEntry, fEntryHigh, fEntryLow, PrintStatus(), and UpdateSlider().
UpdateEntries()
void TParameterInput::UpdateEntries ()
Definition at line 155 of file TCalibrateDescant.cxx.
References fEntry, fEntryHigh, fEntryLow, fSlider, and PrintStatus().
UpdateSlider()
void TParameterInput::UpdateSlider ()
Definition at line 144 of file TCalibrateDescant.cxx.
References fSlider, HighLimit(), LowLimit(), PrintStatus(), and Value().
Referenced by ProcessMessage(), Set(), and Set().
Value()
double TParameterInput::Value () const inline
Definition at line 44 of file TCalibrateDescant.h.
References fEntry.
Referenced by TCalibrateDescant::Fit(), PrintStatus(), TCalibrateDescant::UpdateInitialFunction(), and UpdateSlider().
Member Data Documentation
fBaseId
Int_t TParameterInput::fBaseId {-1} private
Definition at line 61 of file TCalibrateDescant.h.
Referenced by Build().
fEntry
TGNumberEntry* TParameterInput::fEntry {nullptr} private
Definition at line 65 of file TCalibrateDescant.h.
Referenced by Build(), Connect(), Set(), Set(), UpdateEntries(), and Value().
fEntryHigh
TGNumberEntry* TParameterInput::fEntryHigh {nullptr} private
Definition at line 67 of file TCalibrateDescant.h.
Referenced by Build(), Connect(), HighLimit(), Set(), and UpdateEntries().
fEntryLow
TGNumberEntry* TParameterInput::fEntryLow {nullptr} private
Definition at line 66 of file TCalibrateDescant.h.
Referenced by Build(), Connect(), LowLimit(), Set(), and UpdateEntries().
fLabel
TGLabel* TParameterInput::fLabel {nullptr} private
Definition at line 63 of file TCalibrateDescant.h.
Referenced by Build(), and Name().
fSlider
TGTripleHSlider* TParameterInput::fSlider {nullptr} private
Definition at line 64 of file TCalibrateDescant.h.
Referenced by Build(), Connect(), PrintStatus(), UpdateEntries(), and UpdateSlider().