GRSISort: TCalManager Class Reference
TCalManager Class Reference
Calibration
Detailed Description
Definition at line 12 of file TCalManager.h.
Public Member Functions
TCalManager ()=default
TCalManager (const char *classname)
TCalManager (const TCalManager &)=default
TCalManager (TCalManager &&) noexcept=default
~TCalManager ()
Bool_t AddToManager (TCal *cal, Option_t *opt="")
Bool_t AddToManager (TCal *cal, UInt_t chanNum, Option_t *opt="")
void Clear (Option_t *opt="") override
TCal * GetCal (UInt_t chanNum)
const char * GetClass ()
TCalManager & operator= (const TCalManager &)=default
TCalManager & operator= (TCalManager &&) noexcept=default
TCal * operator[] (UInt_t channum)
void Print (Option_t *opt="") const override
void RemoveCal (UInt_t channum, Option_t *opt="")
void SetClass (const char *className)
void SetClass (TClass *cls)
void WriteToChannel () const
Private Attributes
std::map< UInt_t, TCal * > fCalMap
TClass * fClass {nullptr}
Constructor & Destructor Documentation
TCalManager() [1/4]
TCalManager::TCalManager () default
TCalManager() [2/4]
TCalManager::TCalManager (const char * classname) explicit
Definition at line 5 of file TCalManager.cxx.
References SetClass().
TCalManager() [3/4]
TCalManager::TCalManager (const TCalManager &) default
TCalManager() [4/4]
TCalManager::TCalManager (TCalManager &&) default noexcept
~TCalManager()
TCalManager::~TCalManager ()
Definition at line 10 of file TCalManager.cxx.
References fCalMap.
Member Function Documentation
AddToManager() [1/2]
Bool_t TCalManager::AddToManager (TCal * cal, Option_t * opt = "")
Makes a Deep copy of cal and adds it to the CalManager Map.
Definition at line 78 of file TCalManager.cxx.
References AddToManager(), TCal::GetChannel(), and TChannel::GetNumber().
AddToManager() [2/2]
Bool_t TCalManager::AddToManager (TCal * cal, UInt_t chanNum, Option_t * opt = "")
Makes a Deep copy of cal and adds it to the CalManager Map for channel number chanNum.
Definition at line 92 of file TCalManager.cxx.
References fCalMap, fClass, GetCal(), TCal::GetChannel(), TChannel::GetNumber(), TCal::SetChannel(), and SetClass().
Referenced by AddToManager(), TGainMatch::AlignAll(), TGainMatch::CoarseMatchAll(), TGainMatch::FineMatchAll(), and TGainMatch::FineMatchFastAll().
Clear()
void TCalManager::Clear (Option_t * opt = "") override
This deletes all of the current TCal's. It also resets the class type to 0.
Definition at line 151 of file TCalManager.cxx.
References fCalMap, and fClass.
GetCal()
TCal * TCalManager::GetCal (UInt_t chanNum)
Gets the TCal for the channel number chanNum
Definition at line 65 of file TCalManager.cxx.
References fCalMap.
Referenced by AddToManager(), operator[](), and RemoveCal().
GetClass()
const char * TCalManager::GetClass () inline
Definition at line 28 of file TCalManager.h.
References fClass.
operator=() [1/2]
TCalManager & TCalManager::operator= (const TCalManager &) default
operator=() [2/2]
TCalManager & TCalManager::operator= (TCalManager &&) default noexcept
operator[]()
TCal * TCalManager::operator[] (UInt_t channum) inline
Definition at line 34 of file TCalManager.h.
References GetCal().
Print()
void TCalManager::Print (Option_t * opt = "") const override
Definition at line 162 of file TCalManager.cxx.
References fCalMap, and fClass.
RemoveCal()
void TCalManager::RemoveCal (UInt_t channum, Option_t * opt = "")
Definition at line 17 of file TCalManager.cxx.
References fCalMap, and GetCal().
SetClass() [1/2]
void TCalManager::SetClass (const char * className)
Sets the Derived class of the TCal being held in the TCalManager
Definition at line 26 of file TCalManager.cxx.
References SetClass().
Referenced by TCalManager(), AddToManager(), and SetClass().
SetClass() [2/2]
void TCalManager::SetClass (TClass * cls)
Sets the Derived class of the TCal being held in the TCalManager
Definition at line 32 of file TCalManager.cxx.
References fClass.
WriteToChannel()
void TCalManager::WriteToChannel () const
Writes all of the TCals to TChannel based on the method WriteToChannel defined in the TCal held by TCalManager.
Definition at line 140 of file TCalManager.cxx.
References fCalMap.
Member Data Documentation
fCalMap
std::map<UInt_t, TCal*> TCalManager::fCalMap private
Definition at line 37 of file TCalManager.h.
Referenced by ~TCalManager(), AddToManager(), Clear(), GetCal(), Print(), RemoveCal(), and WriteToChannel().
fClass
TClass* TCalManager::fClass {nullptr} private
Definition at line 38 of file TCalManager.h.
Referenced by AddToManager(), Clear(), GetClass(), Print(), and SetClass().