GRSISort: TScalerData Class Reference
TScalerData Class Reference
Sorting
Detailed Description
Definition at line 37 of file TScaler.h.
Public Member Functions
TScalerData ()
TScalerData (const TScalerData &)
TScalerData (TScalerData &&) noexcept=default
~TScalerData ()=default
void Clear (Option_t *opt="") override
void Copy (TObject &rhs) const override
UInt_t GetAddress () const
UInt_t GetHighTimeStamp () const
UInt_t GetLowTimeStamp () const
UInt_t GetNetworkPacketId () const
std::vector< UInt_t > GetScaler () const
UInt_t GetScaler (size_t index) const
ULong64_t GetTimeStamp () const
TScalerData & operator= (const TScalerData &)=default
TScalerData & operator= (TScalerData &&) noexcept=default
void Print (Option_t *opt="") const override
void ResizeScaler (size_t newSize=1)
void SetAddress (UInt_t address)
void SetHighTimeStamp (UInt_t highTime)
void SetLowTimeStamp (UInt_t lowTime)
void SetNetworkPacketId (UInt_t networkId)
void SetScaler (size_t index, UInt_t scaler)
void SetScaler (UInt_t *data, int size)
Private Attributes
UInt_t fAddress {0}
UInt_t fHighTimeStamp {0}
UInt_t fLowTimeStamp {0}
UInt_t fNetworkPacketId {0}
std::vector< UInt_t > fScaler
Constructor & Destructor Documentation
TScalerData() [1/3]
TScalerData::TScalerData ()
Definition at line 7 of file TScaler.cxx.
References Clear(), and fScaler.
TScalerData() [2/3]
TScalerData::TScalerData (const TScalerData & rhs)
Definition at line 13 of file TScaler.cxx.
References Copy().
TScalerData() [3/3]
TScalerData::TScalerData (TScalerData &&) default noexcept
~TScalerData()
TScalerData::~TScalerData () default
Member Function Documentation
Clear()
void TScalerData::Clear (Option_t * opt = "") override
Clears the TScalerData.
Definition at line 27 of file TScaler.cxx.
References fAddress, fHighTimeStamp, fLowTimeStamp, fNetworkPacketId, and fScaler.
Referenced by TScalerData().
Copy()
void TScalerData::Copy (TObject & rhs) const override
Definition at line 18 of file TScaler.cxx.
References fAddress, fHighTimeStamp, fLowTimeStamp, fNetworkPacketId, and fScaler.
Referenced by TScalerData().
GetAddress()
UInt_t TScalerData::GetAddress () const inline
Definition at line 66 of file TScaler.h.
References fAddress.
Referenced by TScaler::Draw(), TScaler::Draw(), TScaler::DrawRawTimes(), TScaler::GetLastScaler(), TScaler::GetScaler(), TScaler::GetScalerDifference(), TScaler::GetTimePeriod(), MakeSpectra(), and TScaler::ReadTree().
GetHighTimeStamp()
UInt_t TScalerData::GetHighTimeStamp () const inline
Definition at line 69 of file TScaler.h.
References fHighTimeStamp.
Referenced by GetTimeStamp().
GetLowTimeStamp()
UInt_t TScalerData::GetLowTimeStamp () const inline
Definition at line 68 of file TScaler.h.
References fLowTimeStamp.
Referenced by GetTimeStamp(), and TGRSIDataParser::SetScalerHighTimeStamp().
GetNetworkPacketId()
UInt_t TScalerData::GetNetworkPacketId () const inline
Definition at line 67 of file TScaler.h.
References fNetworkPacketId.
GetScaler() [1/2]
std::vector< UInt_t > TScalerData::GetScaler () const inline
Definition at line 70 of file TScaler.h.
References fScaler.
Referenced by TScaler::Draw(), TScaler::Draw(), TScaler::DrawRawTimes(), TScaler::GetLastScaler(), TScaler::GetScaler(), TScaler::GetScalerDifference(), MakeSpectra(), and TScaler::ReadTree().
GetScaler() [2/2]
UInt_t TScalerData::GetScaler (size_t index) const inline
Definition at line 71 of file TScaler.h.
References fScaler.
GetTimeStamp()
ULong64_t TScalerData::GetTimeStamp () const inline
Definition at line 79 of file TScaler.h.
References GetHighTimeStamp(), and GetLowTimeStamp().
Referenced by TScaler::Draw(), TScaler::Draw(), TScaler::DrawRawTimes(), TScaler::GetScaler(), TScaler::GetScalerDifference(), TScaler::GetTimePeriod(), MakeSpectra(), Print(), and TScaler::ReadTree().
operator=() [1/2]
TScalerData & TScalerData::operator= (const TScalerData &) default
operator=() [2/2]
TScalerData & TScalerData::operator= (TScalerData &&) default noexcept
Print()
void TScalerData::Print (Option_t * opt = "") const override
Definition at line 37 of file TScaler.cxx.
References fAddress, fScaler, GetTimeStamp(), and hex().
ResizeScaler()
void TScalerData::ResizeScaler (size_t newSize = 1) inline
Definition at line 87 of file TScaler.h.
References fScaler.
SetAddress()
void TScalerData::SetAddress (UInt_t address) inline
Definition at line 48 of file TScaler.h.
References fAddress.
Referenced by TGRSIDataParser::EmmaRawDataToFragment(), TGRSIDataParser::EmmaSumDataToFragment(), and TGRSIDataParser::GriffinDataToScalerEvent().
SetHighTimeStamp()
void TScalerData::SetHighTimeStamp (UInt_t highTime) inline
Definition at line 51 of file TScaler.h.
References fHighTimeStamp.
Referenced by TGRSIDataParser::SetScalerHighTimeStamp().
SetLowTimeStamp()
void TScalerData::SetLowTimeStamp (UInt_t lowTime) inline
Definition at line 50 of file TScaler.h.
References fLowTimeStamp.
Referenced by TGRSIDataParser::SetScalerLowTimeStamp().
SetNetworkPacketId()
void TScalerData::SetNetworkPacketId (UInt_t networkId) inline
Definition at line 49 of file TScaler.h.
References fNetworkPacketId.
Referenced by TGRSIDataParser::SetScalerNetworkPacket().
SetScaler() [1/2]
void TScalerData::SetScaler (size_t index, UInt_t scaler) inline
Definition at line 52 of file TScaler.h.
References fScaler.
Referenced by TGRSIDataParser::SetScalerValue().
SetScaler() [2/2]
void TScalerData::SetScaler (UInt_t * data, int size) inline
Definition at line 61 of file TScaler.h.
References fScaler.
Member Data Documentation
fAddress
UInt_t TScalerData::fAddress {0} private
Definition at line 94 of file TScaler.h.
Referenced by Clear(), Copy(), GetAddress(), Print(), and SetAddress().
fHighTimeStamp
UInt_t TScalerData::fHighTimeStamp {0} private
Definition at line 97 of file TScaler.h.
Referenced by Clear(), Copy(), GetHighTimeStamp(), and SetHighTimeStamp().
fLowTimeStamp
UInt_t TScalerData::fLowTimeStamp {0} private
Definition at line 96 of file TScaler.h.
Referenced by Clear(), Copy(), GetLowTimeStamp(), and SetLowTimeStamp().
fNetworkPacketId
UInt_t TScalerData::fNetworkPacketId {0} private
Definition at line 93 of file TScaler.h.
Referenced by Clear(), Copy(), GetNetworkPacketId(), and SetNetworkPacketId().
fScaler
std::vector<UInt_t> TScalerData::fScaler private
Definition at line 95 of file TScaler.h.
Referenced by TScalerData(), Clear(), Copy(), GetScaler(), GetScaler(), Print(), ResizeScaler(), SetScaler(), and SetScaler().