GRSISort: TSiLiHit Class Reference
TSiLiHit Class Reference
Detectors
Detailed Description
Definition at line 17 of file TSiLiHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ESiLiHitBits { kUseFitCharge = BIT(0) , kSiLiHitBit1 = BIT(1) }
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TSiLiHit ()
TSiLiHit (const TFragment &)
TSiLiHit (const TSiLiHit &)
TSiLiHit (TSiLiHit &&) noexcept=default
~TSiLiHit () override=default
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &val)
virtual void AppendTimeStamp (const Long64_t &val)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool=false) const override
virtual void CopyWave (TObject &) const
double GetAddbackEnergy (unsigned int i)
int16_t GetAddbackSegment (unsigned int i)
unsigned int GetAddbackSize ()
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual int GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
double GetDoppler (double beta, TVector3 *vec=nullptr, double E=0) const
double GetEnergy (Option_t *opt=nullptr) const override
virtual Double_t GetEnergyNonlinearity (double energy) const
double GetFitCharge () const
double GetFitEnergy () const
virtual Short_t GetKValue () const
const char * GetName () const override
Int_t GetPin () const
TVector3 GetPosition () const override
TVector3 GetPosition (bool) const
TVector3 GetPosition (Double_t dist) const override
TVector3 GetPosition (Double_t dist, bool) const
EPpgPattern GetPPGStatus () const
Int_t GetPreamp () const
Int_t GetRing () const
Int_t GetSector () const
virtual Int_t GetSegment () const
Double_t GetSig2Noise () const
Double_t GetSmirnov () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
Double_t GetTimeFit () const
Double_t GetTimeFitCfd () const
Double_t GetTimeFitns () const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
Int_t GetTimeStampLow ()
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
double GetWaveformEnergy () const
virtual bool HasWave () const
bool MagnetShadow () const
bool operator< (const TDetectorHit &rhs) const
TSiLiHit & operator= (const TSiLiHit &)=default
TSiLiHit & operator= (TSiLiHit &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &val)
virtual void SetCfd (const Int_t &val)
virtual void SetCfd (const uint32_t &val)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &energy) const
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
Double_t SetTime (const Double_t &time) const
void SetTimeFit (double t0)
virtual void SetTimeStamp (const Long64_t &val)
void SetWavefit (const TFragment &)
void SetWaveform (const std::vector< Short_t > &val)
void SumHit (TSiLiHit *)
bool TestHitBit (EBitFlag flag) const
void UseFitCharge (bool set=true)
virtual size_t WaveSize () const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TPulseAnalyzer * FitFrag (const TFragment &frag, int ShapeFit, int segment)
static TPulseAnalyzer * FitFrag (const TFragment &frag, int ShapeFit=0, TChannel *=nullptr)
static int FitPulseAnalyzer (TPulseAnalyzer *pulse, int ShapeFit, int segment)
static int FitPulseAnalyzer (TPulseAnalyzer *pulse, int ShapeFit=0, TChannel *=nullptr)
static TVector3 * GetBeamDirection ()
static TChannel * GetSiLiHitChannel (int segment)
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Private Member Functions
Double_t GetDefaultDistance () const
Private Attributes
std::vector< double > fAddBackEnergy
std::vector< int16_t > fAddBackSegments
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
TChannel * fChannel {nullptr}
Float_t fCharge {0.}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Double_t fFitBase {0.}
Double_t fFitCharge {0.}
Short_t fKValue {0}
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Double_t fSig2Noise {0.}
TTransientBits< UChar_t > fSiLiHitBits
Double_t fSmirnov {0.}
Double_t fTime {0.}
Double_t fTimeFit {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Private Attributes
static TVector3 fBeamDirection
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 50 of file TDetectorHit.h.
ESiLiHitBits
enum class TSiLiHit::ESiLiHitBits strong
Enumerator
kUseFitCharge
kSiLiHitBit1
Definition at line 19 of file TSiLiHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 72 of file TDetectorHit.h.
Constructor & Destructor Documentation
TSiLiHit() [1/4]
TSiLiHit::TSiLiHit ()
Definition at line 4 of file TSiLiHit.cxx.
References Clear().
TSiLiHit() [2/4]
TSiLiHit::TSiLiHit (const TSiLiHit & rhs)
Definition at line 16 of file TSiLiHit.cxx.
References Clear(), and Copy().
TSiLiHit() [3/4]
TSiLiHit::TSiLiHit (TSiLiHit &&) default noexcept
TSiLiHit() [4/4]
TSiLiHit::TSiLiHit (const TFragment & frag) explicit
Definition at line 9 of file TSiLiHit.cxx.
References TDetectorHit::Copy(), and SetWavefit().
~TSiLiHit()
TSiLiHit::~TSiLiHit () override default
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TGriffinHit, TFippsHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 184 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & val) inline inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 145 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TTACHit::TempCorrectedCharge(), and TFippsTACHit::TempCorrectedCharge().
Clear()
void TSiLiHit::Clear (Option_t * opt = "") override
Definition at line 38 of file TSiLiHit.cxx.
References TTransientBits< T >::Clear(), TDetectorHit::Clear(), TDetectorHit::ClearTransients(), fAddBackEnergy, fAddBackSegments, fFitBase, fFitCharge, fSig2Noise, fSiLiHitBits, fSmirnov, and fTimeFit.
Referenced by TSiLiHit(), and TSiLiHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 176 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 171 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 94 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TBgoHit::TBgoHit(), TDetectorHit::TDetectorHit(), Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 209 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TDetectorHit::Copy (TObject & rhs) const override inherited
!
Definition at line 101 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TDetectorHit::fBitFlags, TDetectorHit::fCfd, TDetectorHit::fChannel, TDetectorHit::fCharge, TDetectorHit::fCycleTimeStamp, TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::fPPGStatus, TDetectorHit::fTime, and TDetectorHit::fTimeStamp.
Referenced by TAriesHit::TAriesHit(), TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TGriffinHit::TGriffinHit(), TRcmpHit::TRcmpHit(), TRcmpHit::TRcmpHit(), TS3Hit::TS3Hit(), TSceptarHit::TSceptarHit(), TSiLiHit(), TTigressHit::TTigressHit(), TTipHit::TTipHit(), TZeroDegreeHit::TZeroDegreeHit(), TAriesHit::Copy(), TDescantHit::Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TRcmpHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TFippsHit::Copy(), TFippsLaBrHit::Copy(), TFippsTACHit::Copy(), TIfinHit::Copy(), TDetector::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), TTdrSiLiHit::Copy(), TTdrTigressHit::Copy(), TDetectorHit::Copy(), TBgoHit::Copy(), Copy(), TTigressHit::CopyFragment(), TSharc2Hit::SetBack(), TSharcHit::SetBack(), TSharc2Hit::SetFront(), TSharcHit::SetFront(), TSharc2Hit::SetPad(), and TSharcHit::SetPad().
Copy() [2/2]
void TSiLiHit::Copy (TObject & rhs, bool copywave = false) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 22 of file TSiLiHit.cxx.
References TDetectorHit::Copy(), fAddBackEnergy, fAddBackSegments, fFitBase, fFitCharge, fSig2Noise, fSiLiHitBits, fSmirnov, and fTimeFit.
Referenced by TSiLiHit(), and SumHit().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 119 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TBgoHit::TBgoHit(), TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::Copy(), TTipHit::Copy(), TZeroDegreeHit::Copy(), TDetectorHit::Copy(), TAriesHit::Copy(), TDescantHit::Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TRcmpHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), and TTdrTigressHit::Copy().
FitFrag() [1/2]
TPulseAnalyzer * TSiLiHit::FitFrag (const TFragment & frag, int ShapeFit, int segment) static
Definition at line 68 of file TSiLiHit.cxx.
References FitFrag(), and GetSiLiHitChannel().
Referenced by FitFrag(), and SetWavefit().
FitFrag() [2/2]
TPulseAnalyzer * TSiLiHit::FitFrag (const TFragment & frag, int ShapeFit = 0, TChannel * channel = nullptr) static
Definition at line 73 of file TSiLiHit.cxx.
References FitPulseAnalyzer(), and TSiLi::fSiLiNoiseFac.
FitPulseAnalyzer() [1/2]
int TSiLiHit::FitPulseAnalyzer (TPulseAnalyzer * pulse, int ShapeFit, int segment) static
Definition at line 91 of file TSiLiHit.cxx.
References FitPulseAnalyzer(), and GetSiLiHitChannel().
Referenced by FitFrag(), and FitPulseAnalyzer().
FitPulseAnalyzer() [2/2]
int TSiLiHit::FitPulseAnalyzer (TPulseAnalyzer * pulse, int ShapeFit = 0, TChannel * channel = nullptr) static
Definition at line 96 of file TSiLiHit.cxx.
References TSiLi::fBaseFreq, TSiLi::fSiLiDefaultBaseline, TSiLi::fSiLiDefaultDecay, TSiLi::fSiLiDefaultRise, TPulseAnalyzer::GetSiliShape(), TPulseAnalyzer::GetSiliShapeTF1(), TChannel::GetWaveBaseLine(), TChannel::GetWaveDecay(), TChannel::GetWaveRise(), TPulseAnalyzer::IsSet(), and TChannel::UseWaveParam().
GetAddbackEnergy()
double TSiLiHit::GetAddbackEnergy (unsigned int i) inline
Definition at line 115 of file TSiLiHit.h.
References fAddBackEnergy, and GetAddbackSize().
GetAddbackSegment()
int16_t TSiLiHit::GetAddbackSegment (unsigned int i) inline
Definition at line 122 of file TSiLiHit.h.
References fAddBackSegments, and GetAddbackSize().
GetAddbackSize()
unsigned int TSiLiHit::GetAddbackSize () inline
Definition at line 107 of file TSiLiHit.h.
References fAddBackEnergy, and fAddBackSegments.
Referenced by GetAddbackEnergy(), and GetAddbackSegment().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 143 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharc2Hit::GetBackAddress(), TSharcHit::GetBackAddress(), TSharc2Hit::GetFrontAddress(), TSharcHit::GetFrontAddress(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharc2Hit::GetPadAddress(), TSharcHit::GetPadAddress(), TFragment::GetSharcMesyBoard(), TEagleHit::Print(), TPinDiodeHit::Print(), TFragment::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TGriffinBgoHit, TGriffinHit, TLaBrBgoHit, TRcmpHit, TTigressHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TIfinBgoHit, TIfinHit, TBgoHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 163 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 182 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TTigressHit::GetDoppler(), and GetDoppler().
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Reimplemented in TDescantHit, and TZeroDegreeHit.
Definition at line 142 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), DefaultSuppression(), TFragment::Get4GCfd(), TDescantHit::GetCfd(), TZeroDegreeHit::GetCfd(), TDescantHit::GetRemainder(), TZeroDegreeHit::GetRemainder(), TSharc2Hit::GetSomeTime(), TSharcHit::GetSomeTime(), TDetectorHit::GetTime(), TTigressHit::GetTimeToTrigger(), TEagleHit::Print(), TFragment::Print(), and TTigressHit::SumHit().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 148 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), GetFitEnergy(), TDetectorHit::GetName(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and SetWavefit().
GetChannelNumber()
int TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 214 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 54 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharc2Hit::GetBackCharge(), TSharcHit::GetBackCharge(), TSharc2Hit::GetFrontCharge(), TSharcHit::GetFrontCharge(), TSharc2Hit::GetPadCharge(), TSharcHit::GetPadCharge(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TTigressHit::Print(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 200 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TGriffinHit::Print(), TFippsHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 257 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDefaultDistance()
Double_t TSiLiHit::GetDefaultDistance () const inline private
Definition at line 131 of file TSiLiHit.h.
Referenced by GetPosition().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 182 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TDetectorHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TSharc2::GetDeadLayerThickness(), TSharc::GetDeadLayerThickness(), TSharc2::GetDetectorThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TDescantHit::GetPosition(), TTrificHit::GetPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TAriesHit::GetPosition(), TDescantHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TSceptarHit::GetPosition(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TEagleHit::GetPosition(), TPinDiodeHit::GetPosition(), TFippsLaBrHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TAriesHit::Print(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TSharc2Hit::Print(), TSharcHit::Print(), TTACHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), and PromptCoincidence().
GetDoppler()
double TSiLiHit::GetDoppler (double beta, TVector3 * vec = nullptr, double E = 0) const inline
Definition at line 93 of file TSiLiHit.h.
References TDetectorHit::GetBeamDirection(), GetEnergy(), and GetPosition().
GetEnergy()
double TSiLiHit::GetEnergy (Option_t * opt = nullptr) const override virtual
Reimplemented from TDetectorHit.
Definition at line 203 of file TSiLiHit.cxx.
References TChannel::CalibrateENG(), fFitCharge, fSiLiHitBits, TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TDetectorHit::kIsEnergySet, kUseFitCharge, TDetectorHit::SetEnergy(), TTransientBits< T >::TestBit(), and TDetectorHit::TestHitBit().
Referenced by TSiLi::AddCluster(), TSiLi::fAddbackCriterion(), GetDoppler(), GetTimeFit(), and SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 92 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFitCharge()
double TSiLiHit::GetFitCharge () const inline
Definition at line 89 of file TSiLiHit.h.
References fFitCharge.
GetFitEnergy()
double TSiLiHit::GetFitEnergy () const
Definition at line 191 of file TSiLiHit.cxx.
References TChannel::CalibrateENG(), fFitCharge, fSiLiHitBits, TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), kUseFitCharge, and TTransientBits< T >::TestBit().
Referenced by GetWaveformEnergy().
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 146 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TTACHit::GetTempCorrectedEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 156 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by EfficiencyHelper::EndOfSort(), TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPin()
Int_t TSiLiHit::GetPin () const
Definition at line 182 of file TSiLiHit.cxx.
References TSiLi::GetPin(), and TDetectorHit::GetSegment().
Referenced by TSiLi::fRejectCriterion().
GetPosition() [1/4]
TVector3 TSiLiHit::GetPosition () const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 77 of file TSiLiHit.h.
References GetPosition().
Referenced by GetDoppler(), GetPosition(), and GetPosition().
GetPosition() [2/4]
TVector3 TSiLiHit::GetPosition (bool smear) const
Definition at line 132 of file TSiLiHit.cxx.
References GetDefaultDistance(), and GetPosition().
GetPosition() [3/4]
TVector3 TSiLiHit::GetPosition (Double_t) const inline override virtual
!
Reimplemented from TDetectorHit.
Definition at line 76 of file TSiLiHit.h.
References GetPosition().
Referenced by GetPosition().
GetPosition() [4/4]
TVector3 TSiLiHit::GetPosition (Double_t dist, bool smear) const
Definition at line 127 of file TSiLiHit.cxx.
References TSiLi::GetPosition(), GetRing(), and GetSector().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 241 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetPreamp()
Int_t TSiLiHit::GetPreamp () const
Definition at line 178 of file TSiLiHit.cxx.
References TSiLi::GetPreamp(), and TDetectorHit::GetSegment().
Referenced by TSiLi::fRejectCriterion().
GetRing()
Int_t TSiLiHit::GetRing () const
Definition at line 170 of file TSiLiHit.cxx.
References TSiLi::GetRing(), and TDetectorHit::GetSegment().
Referenced by TSiLi::AddCluster(), TSiLi::fAddbackCriterion(), and GetPosition().
GetSector()
Int_t TSiLiHit::GetSector () const
Definition at line 174 of file TSiLiHit.cxx.
References TSiLi::GetSector(), and TDetectorHit::GetSegment().
Referenced by TSiLi::AddCluster(), TSiLi::fAddbackCriterion(), and GetPosition().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 191 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TGriffinBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TSharc2Hit::GetBackStrip(), TSharcHit::GetBackStrip(), TSharc2Hit::GetFrontStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), GetPin(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), GetPreamp(), GetRing(), GetSector(), MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and SumHit().
GetSig2Noise()
Double_t TSiLiHit::GetSig2Noise () const inline
Definition at line 47 of file TSiLiHit.h.
References fSig2Noise.
GetSiLiHitChannel()
TChannel * TSiLiHit::GetSiLiHitChannel (int segment) static
Definition at line 83 of file TSiLiHit.cxx.
References TChannel::FindChannelByName().
Referenced by FitFrag(), and FitPulseAnalyzer().
GetSmirnov()
Double_t TSiLiHit::GetSmirnov () const inline
Definition at line 48 of file TSiLiHit.h.
References fSmirnov.
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 41 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonPolarimetryHelper::Coincident(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleTreeHelper::Exec(), TSiLi::fCoincidenceTime(), ExampleTreeSelector::FillHistograms(), TSharc2Hit::GetDeltaBackT(), TSharcHit::GetDeltaBackT(), TSharc2Hit::GetDeltaFrontT(), TSharcHit::GetDeltaFrontT(), TSharc2Hit::GetDeltaT(), TSharcHit::GetDeltaT(), TSharc2Hit::GetPadT(), TSharcHit::GetPadT(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TDetectorHit::Print(), TAriesHit::Print(), TDescantHit::Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TTACHit::TempCorrectedCharge(), TFippsTACHit::TempCorrectedCharge(), ComptonPolarimetryHelper::TimeDiff(), TimeRandom(), and TimeRandom().
GetTimeFit()
Double_t TSiLiHit::GetTimeFit () const inline
Definition at line 40 of file TSiLiHit.h.
References fTimeFit, TDetectorHit::GetChannel(), GetEnergy(), and TChannel::GetTZero().
Referenced by TSiLi::fCoincidenceTime(), GetTimeFitCfd(), and GetTimeFitns().
GetTimeFitCfd()
Double_t TSiLiHit::GetTimeFitCfd () const inline
Definition at line 55 of file TSiLiHit.h.
References GetTimeFit(), and TDetectorHit::GetTimeStamp().
GetTimeFitns()
Double_t TSiLiHit::GetTimeFitns () const inline
Definition at line 51 of file TSiLiHit.h.
References GetTimeFit(), and TDetectorHit::GetTimeStamp().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 273 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), GetTimeFitCfd(), GetTimeFitns(), GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), TTigressHit::GetTimeToTrigger(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TGriffinHit::Print(), TTigressHit::Print(), TEagleHit::Print(), and TFragment::Print().
GetTimeStampLow()
Int_t TSiLiHit::GetTimeStampLow () inline
Definition at line 50 of file TSiLiHit.h.
References TDetectorHit::GetTimeStamp().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 223 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by ComptonPolarimetryHelper::Coincident(), DirectoryHelper::Exec(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), TGriffinHit::Print(), and ComptonPolarimetryHelper::TimeDiff().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 232 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
GetWaveformEnergy()
double TSiLiHit::GetWaveformEnergy () const inline
Definition at line 87 of file TSiLiHit.h.
References GetFitEnergy().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 102 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TFragment::Print(), and TPulseAnalyzer::SetData().
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 191 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 190 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 193 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 192 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
MagnetShadow()
bool TSiLiHit::MagnetShadow () const
Definition at line 186 of file TSiLiHit.cxx.
References TDetectorHit::GetSegment(), and TSiLi::MagnetShadow().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 88 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
operator=() [1/2]
TSiLiHit & TSiLiHit::operator= (const TSiLiHit &) default
operator=() [2/2]
TSiLiHit & TSiLiHit::operator= (TSiLiHit &&) default noexcept
Print() [1/2]
void TSiLiHit::Print (Option_t * opt = "") const override
Definition at line 137 of file TSiLiHit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TSiLiHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 142 of file TSiLiHit.cxx.
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 109 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), and TTigressHit::SumHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & val) inline virtual inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 111 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 112 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & energy) const inline inherited
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TDetectorHit::GetEnergy(), GetEnergy(), SumHit(), and TTigressHit::SumHit().
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 280 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TDetectorHit::SetTime(), SumHit(), and UseFitCharge().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 110 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 127 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeFit()
void TSiLiHit::SetTimeFit (double t0) inline
Definition at line 65 of file TSiLiHit.h.
References fTimeFit.
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
SetWavefit()
void TSiLiHit::SetWavefit (const TFragment & frag)
Definition at line 54 of file TSiLiHit.cxx.
References fFitBase, fFitCharge, TSiLi::fFitSiLiShape, FitFrag(), fSig2Noise, fSmirnov, fTimeFit, TPulseAnalyzer::get_sig2noise(), TPulseAnalyzer::Get_wpar_amplitude(), TPulseAnalyzer::Get_wpar_baselinefin(), TPulseAnalyzer::Get_wpar_T0(), TDetectorHit::GetChannel(), and TPulseAnalyzer::GetsiliSmirnov().
Referenced by TSiLiHit().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & val) inline inherited
!
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TTdrPlasticHit::TTdrPlasticHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SumHit()
void TSiLiHit::SumHit (TSiLiHit * hit)
Definition at line 151 of file TSiLiHit.cxx.
References Copy(), fAddBackEnergy, fAddBackSegments, GetEnergy(), TDetectorHit::GetSegment(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), and TDetectorHit::SetHitBit().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 187 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), and GetEnergy().
UseFitCharge()
void TSiLiHit::UseFitCharge (bool set = true) inline
Definition at line 81 of file TSiLiHit.h.
References fSiLiHitBits, TDetectorHit::kIsEnergySet, kUseFitCharge, TTransientBits< T >::SetBit(), and TDetectorHit::SetHitBit().
WaveSize()
virtual size_t TDetectorHit::WaveSize () const inline virtual inherited
!
Definition at line 103 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), and TZeroDegreeHit::CalculateSmoothedWaveform().
Member Data Documentation
fAddBackEnergy
std::vector<double> TSiLiHit::fAddBackEnergy private
!
Definition at line 134 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetAddbackEnergy(), GetAddbackSize(), and SumHit().
fAddBackSegments
std::vector<int16_t> TSiLiHit::fAddBackSegments private
!
Definition at line 133 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetAddbackSegment(), GetAddbackSize(), and SumHit().
fAddress
UInt_t TDetectorHit::fAddress {0} private inherited
address of the the channel in the DAQ.
Definition at line 196 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static private inherited
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable private inherited
Definition at line 211 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TTdrCloverHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TTdrCloverHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TTdrCloverHit::NPileUps(), TTdrCloverHit::PUHit(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), and TDetectorHit::TestHitBit().
fCfd
Float_t TDetectorHit::fCfd {0} private inherited
CFD time of the Hit.
Definition at line 199 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 208 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} private inherited
charge collected from the hit
Definition at line 197 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 207 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fFitBase
Double_t TSiLiHit::fFitBase {0.} private
Definition at line 142 of file TSiLiHit.h.
Referenced by Clear(), Copy(), and SetWavefit().
fFitCharge
Double_t TSiLiHit::fFitCharge {0.} private
Definition at line 141 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetEnergy(), GetFitCharge(), GetFitEnergy(), and SetWavefit().
fKValue
Short_t TDetectorHit::fKValue {0} private inherited
integration value.
Definition at line 198 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TFippsTACHit::GetTempCorrectedEnergy(), and TDetectorHit::SetKValue().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fSig2Noise
Double_t TSiLiHit::fSig2Noise {0.} private
Definition at line 139 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetSig2Noise(), and SetWavefit().
fSiLiHitBits
TTransientBits<UChar_t> TSiLiHit::fSiLiHitBits private
Definition at line 136 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetEnergy(), GetFitEnergy(), and UseFitCharge().
fSmirnov
Double_t TSiLiHit::fSmirnov {0.} private
Definition at line 140 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetSmirnov(), and SetWavefit().
fTime
Double_t TDetectorHit::fTime {0.} mutable private inherited
! Calibrated Time of the hit
Definition at line 202 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeFit
Double_t TSiLiHit::fTimeFit {0.} private
Definition at line 138 of file TSiLiHit.h.
Referenced by Clear(), Copy(), GetTimeFit(), SetTimeFit(), and SetWavefit().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} private inherited
Timestamp given to hit in ns.
Definition at line 200 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), and TDetectorHit::SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform private inherited
Definition at line 201 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), TDetectorHit::SetWaveform(), and TDetectorHit::WaveSize().