GRSISort: TFipps Class Reference
TFipps Class Reference
Detectors
Detailed Description
The TFipps class defines the observables and algorithms used when analyzing FIPPS data. It includes detector positions, add-back methods, etc.
Definition at line 32 of file TFipps.h.
Public Types
enum class EFippsBits {
kIsAddbackSet = 1<<0 , kIsCrossTalkSet = 1<<1 , kIsSuppressedSet = 1<<2 , kIsSuppressedAddbackSet = 1<<3 ,
kBit4 = 1<<4 , kBit5 = 1<<5 , kBit6 = 1<<6 , kBit7 = 1<<7
}
Public Member Functions
TFipps ()
TFipps (const TFipps &)
~TFipps () override
bool AddbackCriterion (const TDetectorHit *hit1, const TDetectorHit *hit2) override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
void FixCrossTalk ()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetAddbackCriterion () const
TFippsHit * GetAddbackHit (const int &i)
Int_t GetAddbackMultiplicity ()
TFippsHit * GetFippsHit (const Int_t &i)
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
UShort_t GetNAddbackFrags (const size_t &idx)
TFippsHit * GetSuppressedAddbackHit (const int &i)
Int_t GetSuppressedAddbackMultiplicity (const TBgo *bgo)
TFippsHit * GetSuppressedHit (const int &i)
Int_t GetSuppressedMultiplicity (const TBgo *bgo)
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetSuppressionCriterion () const
bool IsAddbackSet () const
Bool_t IsCrossTalkSet () const
bool IsSuppressed () const
bool IsSuppressedAddbackSet () const
TFipps & operator= (const TFipps &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void ResetAddback ()
void ResetFlags () const
void ResetSuppressed ()
void ResetSuppressedAddback ()
void SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
void SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
bool SuppressionCriterion (const TDetectorHit *hit, const TDetectorHit *bgoHit) override
Static Public Member Functions
static Double_t CTCorrectedEnergy (const TFippsHit *const hit_to_correct, const TFippsHit *const other_hit, Bool_t time_constraint=true)
static const char * GetColorFromNumber (int number)
static TVector3 GetPosition (int DetNbr, int CryNbr=5, double dist=90.0)
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Protected Attributes
std::vector< TDetectorHit * > fHits
Private Member Functions
void ClearStatus () const
std::vector< UShort_t > & GetAddbackFragVector ()
std::vector< TDetectorHit * > & GetAddbackVector ()
std::vector< UShort_t > & GetSuppressedAddbackFragVector ()
std::vector< TDetectorHit * > & GetSuppressedAddbackVector ()
std::vector< TDetectorHit * > & GetSuppressedVector ()
void SetAddback (bool flag=true) const
void SetBitNumber (EFippsBits bit, Bool_t set) const
void SetCrossTalk (bool flag=true) const
void SetSuppressed (bool flag=true) const
void SetSuppressedAddback (bool flag=true) const
Bool_t TestBitNumber (EFippsBits bit) const
Private Attributes
std::vector< UShort_t > fAddbackFrags
std::vector< TDetectorHit * > fAddbackHits
TTransientBits< UChar_t > fFippsBits
std::vector< UShort_t > fSuppressedAddbackFrags
std::vector< TDetectorHit * > fSuppressedAddbackHits
std::vector< TDetectorHit * > fSuppressedHits
Static Private Attributes
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fAddbackCriterion = DefaultFippsAddback
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fSuppressionCriterion = DefaultFippsSuppression
static TVector3 gCloverPosition [17]
Member Enumeration Documentation
EFippsBits
enum class TFipps::EFippsBits strong
Enumerator
kIsAddbackSet
kIsCrossTalkSet
kIsSuppressedSet
kIsSuppressedAddbackSet
kBit4
kBit5
kBit6
kBit7
Definition at line 34 of file TFipps.h.
Constructor & Destructor Documentation
TFipps() [1/2]
TFipps::TFipps ()
Definition at line 100 of file TFipps.cxx.
References Clear().
TFipps() [2/2]
TFipps::TFipps (const TFipps & rhs)
Definition at line 109 of file TFipps.cxx.
References Copy().
~TFipps()
TFipps::~TFipps () override
Definition at line 135 of file TFipps.cxx.
References fAddbackHits, fSuppressedAddbackHits, and fSuppressedHits.
Member Function Documentation
AddbackCriterion()
bool TFipps::AddbackCriterion (const TDetectorHit * hit1, const TDetectorHit * hit2) inline override virtual
Reimplemented from TSuppressed.
Definition at line 69 of file TFipps.h.
References fAddbackCriterion.
AddFragment()
void TFipps::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 409 of file TFipps.cxx.
References TDetector::fHits, TChannel::GetMnemonic(), TMnemonic::kG, and TMnemonic::SubSystem().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
BuildHits()
void TFipps::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 57 of file TFipps.h.
Clear()
void TFipps::Clear (Option_t * opt = "all") override
!
Definition at line 145 of file TFipps.cxx.
References TSuppressed::Clear(), ClearStatus(), fAddbackFrags, fAddbackHits, fSuppressedAddbackFrags, fSuppressedAddbackHits, and fSuppressedHits.
Referenced by TFipps().
ClearStatus()
void TFipps::ClearStatus () const inline private
!
Definition at line 119 of file TFipps.h.
References fFippsBits.
Referenced by Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 68 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TFipps::Copy (TObject & rhs) const override
!
Definition at line 118 of file TFipps.cxx.
References TSuppressed::Copy(), fAddbackFrags, fAddbackHits, fFippsBits, fSuppressedAddbackFrags, fSuppressedAddbackHits, and fSuppressedHits.
Referenced by TFipps(), and operator=().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 34 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), and TGriffin::GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected inherited
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 65 of file TSuppressed.h.
References TDetector::GetHitVector(), and TSuppressed::SuppressionCriterion().
Referenced by GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), and TTdrTigress::GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 90 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetector::GetHitVector(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and TSuppressed::SuppressionCriterion().
Referenced by GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), and TTdrTigress::GetSuppressedAddbackMultiplicity().
CTCorrectedEnergy()
Double_t TFipps::CTCorrectedEnergy (const TFippsHit *const hit_to_correct, const TFippsHit *const other_hit, Bool_t time_constraint = true) static
Corrects the energy of the hit to correct by ADDING the uncorrected energy of the other hit times the parameter for this combination This is different to the very similar TGriffin function that SUBTRACTS instead of ADDING. If time_constraint is true it also checks that the two hits are within the addback window to each other.
Definition at line 521 of file TFipps.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), DRED, TDetectorHit::GetChannel(), TDetectorHit::GetCrystal(), TChannel::GetCTCoeff(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TFippsHit::GetNoCTEnergy(), TDetectorHit::GetTime(), and RESET_COLOR.
Referenced by FixCrossTalk().
FixCrossTalk()
void TFipps::FixCrossTalk ()
Definition at line 562 of file TFipps.cxx.
References TGRSIOptions::AnalysisOptions(), CTCorrectedEnergy(), TDetector::GetHitVector(), TAnalysisOptions::IsCorrectingCrossTalk(), SetCrossTalk(), and TDetectorHit::SetEnergy().
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), GetFippsHit(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), and GetSuppressedMultiplicity().
GetAddbackCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFipps::GetAddbackCriterion () const inline
Definition at line 67 of file TFipps.h.
References fAddbackCriterion.
GetAddbackFragVector()
std::vector< UShort_t > & TFipps::GetAddbackFragVector () private
!
Definition at line 195 of file TFipps.cxx.
References fAddbackFrags.
Referenced by GetAddbackMultiplicity(), GetNAddbackFrags(), and ResetAddback().
GetAddbackHit()
TFippsHit * TFipps::GetAddbackHit (const int & i)
Definition at line 377 of file TFipps.cxx.
References FixCrossTalk(), GetAddbackVector(), and IsCrossTalkSet().
GetAddbackMultiplicity()
Int_t TFipps::GetAddbackMultiplicity ()
Definition at line 314 of file TFipps.cxx.
References TSuppressed::CreateAddback(), FixCrossTalk(), GetAddbackFragVector(), GetAddbackVector(), TDetector::GetHitVector(), IsAddbackSet(), IsCrossTalkSet(), and SetAddback().
GetAddbackVector()
std::vector< TDetectorHit * > & TFipps::GetAddbackVector () private
!
Definition at line 190 of file TFipps.cxx.
References fAddbackHits.
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), and ResetAddback().
GetColorFromNumber()
const char * TFipps::GetColorFromNumber (int number) static
Definition at line 586 of file TFipps.cxx.
Referenced by main().
GetFippsHit()
TFippsHit * TFipps::GetFippsHit (const Int_t & i)
Definition at line 255 of file TFipps.cxx.
References TDetector::fHits, FixCrossTalk(), and IsCrossTalkSet().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), and MakeAnalysisHistograms().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), FixCrossTalk(), TIfin::FixCrossTalk(), GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin, and TTrific.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), main(), MakeAnalysisHistograms(), TTigress::Print(), Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetNAddbackFrags()
UShort_t TFipps::GetNAddbackFrags (const size_t & idx)
Definition at line 504 of file TFipps.cxx.
References GetAddbackFragVector().
GetPosition()
TVector3 TFipps::GetPosition (int DetNbr, int CryNbr = 5, double dist = 90.0) static
!
Definition at line 430 of file TFipps.cxx.
References gCloverPosition.
Referenced by TFippsHit::GetPosition().
GetSuppressedAddbackFragVector()
std::vector< UShort_t > & TFipps::GetSuppressedAddbackFragVector () private
Definition at line 210 of file TFipps.cxx.
References fSuppressedAddbackFrags.
Referenced by GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedAddbackHit()
TFippsHit * TFipps::GetSuppressedAddbackHit (const int & i)
Definition at line 393 of file TFipps.cxx.
References FixCrossTalk(), GetSuppressedAddbackVector(), and IsCrossTalkSet().
GetSuppressedAddbackMultiplicity()
Int_t TFipps::GetSuppressedAddbackMultiplicity (const TBgo * bgo)
Definition at line 345 of file TFipps.cxx.
References TSuppressed::CreateSuppressedAddback(), FixCrossTalk(), TDetector::GetHitVector(), GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), IsCrossTalkSet(), IsSuppressedAddbackSet(), and SetSuppressedAddback().
GetSuppressedAddbackVector()
std::vector< TDetectorHit * > & TFipps::GetSuppressedAddbackVector () private
Definition at line 205 of file TFipps.cxx.
References fSuppressedAddbackHits.
Referenced by GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedHit()
TFippsHit * TFipps::GetSuppressedHit (const int & i)
Definition at line 271 of file TFipps.cxx.
References FixCrossTalk(), fSuppressedHits, and IsCrossTalkSet().
GetSuppressedMultiplicity()
Int_t TFipps::GetSuppressedMultiplicity (const TBgo * bgo)
Automatically builds the suppressed hits using the fSuppressionCriterion and returns the number of suppressed hits
Definition at line 287 of file TFipps.cxx.
References TSuppressed::CreateSuppressed(), FixCrossTalk(), TDetector::GetHitVector(), GetSuppressedVector(), IsCrossTalkSet(), IsSuppressed(), and SetSuppressed().
GetSuppressedVector()
std::vector< TDetectorHit * > & TFipps::GetSuppressedVector () private
Definition at line 200 of file TFipps.cxx.
References fSuppressedHits.
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
GetSuppressionCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFipps::GetSuppressionCriterion () const inline
Definition at line 89 of file TFipps.h.
References fSuppressionCriterion.
IsAddbackSet()
bool TFipps::IsAddbackSet () const
Definition at line 215 of file TFipps.cxx.
References kIsAddbackSet, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), and Print().
IsCrossTalkSet()
bool TFipps::IsCrossTalkSet () const
Definition at line 220 of file TFipps.cxx.
References kIsCrossTalkSet, and TestBitNumber().
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), GetFippsHit(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), GetSuppressedMultiplicity(), and Print().
IsSuppressed()
bool TFipps::IsSuppressed () const
Definition at line 225 of file TFipps.cxx.
References kIsSuppressedSet, and TestBitNumber().
Referenced by GetSuppressedMultiplicity().
IsSuppressedAddbackSet()
bool TFipps::IsSuppressedAddbackSet () const
Definition at line 230 of file TFipps.cxx.
References kIsSuppressedAddbackSet, and TestBitNumber().
Referenced by GetSuppressedAddbackMultiplicity().
operator=()
TFipps & TFipps::operator= (const TFipps & rhs)
!
Definition at line 183 of file TFipps.cxx.
References Copy().
Print() [1/2]
void TFipps::Print (Option_t * opt = "") const override
!
Definition at line 162 of file TFipps.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TFipps::Print (std::ostream & out) const override virtual
Reimplemented from TDetector.
Definition at line 167 of file TFipps.cxx.
References fAddbackHits, TDetector::GetMultiplicity(), IsAddbackSet(), and IsCrossTalkSet().
ResetAddback()
void TFipps::ResetAddback ()
Definition at line 473 of file TFipps.cxx.
References GetAddbackFragVector(), GetAddbackVector(), SetAddback(), and SetCrossTalk().
ResetFlags()
void TFipps::ResetFlags () const
Definition at line 468 of file TFipps.cxx.
References fFippsBits.
ResetSuppressed()
void TFipps::ResetSuppressed ()
Definition at line 484 of file TFipps.cxx.
References GetSuppressedVector(), and SetSuppressed().
ResetSuppressedAddback()
void TFipps::ResetSuppressedAddback ()
Definition at line 493 of file TFipps.cxx.
References GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), SetCrossTalk(), and SetSuppressedAddback().
SetAddback()
void TFipps::SetAddback (bool flag = true) const private
Definition at line 235 of file TFipps.cxx.
References kIsAddbackSet, and SetBitNumber().
Referenced by GetAddbackMultiplicity(), and ResetAddback().
SetAddbackCriterion()
void TFipps::SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 63 of file TFipps.h.
References fAddbackCriterion.
SetBitNumber()
void TFipps::SetBitNumber (EFippsBits bit, Bool_t set) const private
Definition at line 514 of file TFipps.cxx.
References fFippsBits, and TTransientBits< T >::SetBit().
Referenced by SetAddback(), SetCrossTalk(), SetSuppressed(), and SetSuppressedAddback().
SetCrossTalk()
void TFipps::SetCrossTalk (bool flag = true) const private
Definition at line 240 of file TFipps.cxx.
References kIsCrossTalkSet, and SetBitNumber().
Referenced by FixCrossTalk(), ResetAddback(), and ResetSuppressedAddback().
SetSuppressed()
void TFipps::SetSuppressed (bool flag = true) const private
Definition at line 245 of file TFipps.cxx.
References kIsSuppressedSet, and SetBitNumber().
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
SetSuppressedAddback()
void TFipps::SetSuppressedAddback (bool flag = true) const private
Definition at line 250 of file TFipps.cxx.
References kIsSuppressedAddbackSet, and SetBitNumber().
Referenced by GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
SetSuppressionCriterion()
void TFipps::SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 85 of file TFipps.h.
References fSuppressionCriterion.
SuppressionCriterion()
bool TFipps::SuppressionCriterion (const TDetectorHit * hit, const TDetectorHit * bgoHit) inline override virtual
Reimplemented from TSuppressed.
Definition at line 91 of file TFipps.h.
References fSuppressionCriterion.
TestBitNumber()
Bool_t TFipps::TestBitNumber (EFippsBits bit) const inline private
Definition at line 121 of file TFipps.h.
References fFippsBits, and TTransientBits< T >::TestBit().
Referenced by IsAddbackSet(), IsCrossTalkSet(), IsSuppressed(), and IsSuppressedAddbackSet().
Member Data Documentation
fAddbackCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFipps::fAddbackCriterion = DefaultFippsAddback static private
Definition at line 100 of file TFipps.h.
Referenced by AddbackCriterion(), GetAddbackCriterion(), and SetAddbackCriterion().
fAddbackFrags
std::vector<UShort_t> TFipps::fAddbackFrags mutable private
! Number of crystals involved in creating the addback hit
Definition at line 109 of file TFipps.h.
Referenced by Clear(), Copy(), and GetAddbackFragVector().
fAddbackHits
std::vector<TDetectorHit*> TFipps::fAddbackHits mutable private
! Used to create addback hits on the fly
Definition at line 108 of file TFipps.h.
Referenced by ~TFipps(), Clear(), Copy(), GetAddbackVector(), and Print().
fFippsBits
TTransientBits<UChar_t> TFipps::fFippsBits mutable private
Definition at line 106 of file TFipps.h.
Referenced by ClearStatus(), Copy(), ResetFlags(), SetBitNumber(), and TestBitNumber().
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 84 of file TDetector.h.
Referenced by TDetector::~TDetector(), TSiLi::AddCluster(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TEagle::AddFragment(), TEaglePulser::AddFragment(), AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TDetector::AddHit(), TCSM::BuildHits(), TEmma::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TSharc::Clear(), TTrific::Clear(), TDetector::Clear(), TEmma::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TTrific::GetMultiplicity(), TSharc::GetSize(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
fSuppressedAddbackFrags
std::vector<UShort_t> TFipps::fSuppressedAddbackFrags mutable private
! Number of crystals involved in creating the suppressed addback hit
Definition at line 112 of file TFipps.h.
Referenced by Clear(), Copy(), and GetSuppressedAddbackFragVector().
fSuppressedAddbackHits
std::vector<TDetectorHit*> TFipps::fSuppressedAddbackHits mutable private
! Used to create suppressed addback hits on the fly
Definition at line 111 of file TFipps.h.
Referenced by ~TFipps(), Clear(), Copy(), and GetSuppressedAddbackVector().
fSuppressedHits
std::vector<TDetectorHit*> TFipps::fSuppressedHits mutable private
! Used to create suppressed hits on the fly
Definition at line 110 of file TFipps.h.
Referenced by ~TFipps(), Clear(), Copy(), GetSuppressedHit(), and GetSuppressedVector().
fSuppressionCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFipps::fSuppressionCriterion = DefaultFippsSuppression static private
Definition at line 101 of file TFipps.h.
Referenced by GetSuppressionCriterion(), SetSuppressionCriterion(), and SuppressionCriterion().
gCloverPosition
TVector3 TFipps::gCloverPosition static private
! Position of each HPGe Clover
Definition at line 43 of file TFipps.h.
Referenced by GetPosition().