GRSISort: TGRSIDataParser Class Reference
TGRSIDataParser Class Reference
Sorting
Detailed Description
The TGRSIDataParser is the DAQ dependent part of GRSISort. It takes a "DAQ-dependent"-flavoured MIDAS file and converts it into a generic TFragment that the rest of GRSISort can deal with. This is where event word masks are applied, and any changes to the event format must be implemented.
Definition at line 44 of file TGRSIDataParser.h.
Public Types
enum class EBank {
kWFDN = 0 , kGRF1 = 1 , kGRF2 = 2 , kGRF3 = 3 ,
kGRF4 = 4 , kFME0 = 5 , kFME1 = 6 , kFME2 = 7 ,
kFME3 = 8 , kMADC = 9 , kEMMT = 10
}
enum class EDataParserState {
kGood , kBadHeader , kMissingWords , kBadScalerLowTS ,
kBadScalerValue , kBadScalerHighTS , kBadScalerType , kBadTriggerId ,
kBadLowTS , kBadHighTS , kSecondHeader , kWrongNofWords ,
kNotSingleCfd , kSizeMismatch , kBadFooter , kFault ,
kMissingPsd , kMissingCfd , kMissingCharge , kBadBank ,
kBadModuleType , kEndOfData , kBadRFScalerWord , kUndefined
}
Public Member Functions
TGRSIDataParser ()
TGRSIDataParser (const TGRSIDataParser &)=default
TGRSIDataParser (TGRSIDataParser &&) noexcept=default
~TGRSIDataParser () override=default
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & AddGoodOutputQueue (size_t maxSize=50000)
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & BadOutputQueue ()
int CaenPhaToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
int CaenPsdToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
virtual void ClearQueue ()
int EightPIDataToFragment (uint32_t stream, uint32_t *data, int size, unsigned int midasSerialNumber=0, time_t midasTime=0)
int EmmaMadcDataToFragment (const uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
int EmmaRawDataToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
int EmmaSumDataToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
int EmmaTdcDataToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
int EPIXToScalar (float *data, int size, unsigned int midasSerialNumber=0, time_t midasTime=0)
int GriffinDataToFragment (uint32_t *data, int size, EBank bank, unsigned int midasSerialNumber=0, time_t midasTime=0)
int GriffinDataToPPGEvent (uint32_t *data, int size, unsigned int midasSerialNumber=0, time_t midasTime=0)
int GriffinDataToScalerEvent (uint32_t *data, int address)
virtual size_t ItemsPushed ()
TGRSIDataParser & operator= (const TGRSIDataParser &)=delete
TGRSIDataParser & operator= (TGRSIDataParser &&) noexcept=delete
virtual std::string OutputQueueStatus ()
int Process (std::shared_ptr< TRawEvent >) override
int ProcessGriffin (uint32_t *data, const int &size, const EBank &bank, std::shared_ptr< TMidasEvent > &event)
void Push (std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > &queues, const std::shared_ptr< TFragment > &frag)
void Push (ThreadsafeQueue< std::shared_ptr< const TBadFragment > > &queue, const std::shared_ptr< TBadFragment > &frag)
int RFScalerToFragment (uint32_t *data, int size, const std::shared_ptr< TFragment > &frag)
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & ScalerOutputQueue ()
int SCLRToScalar (uint32_t *data, int size, unsigned int midasSerialNumber=0, time_t midasTime=0)
virtual void SetFinished ()
virtual void SetNoWaveForms (bool temp=true)
virtual void SetRecordDiag (bool temp=true)
virtual void SetStatusVariables (std::atomic_size_t *itemsPopped, std::atomic_long *inputSize)
int TigressDataToFragment (uint32_t *data, int size, std::shared_ptr< TMidasEvent > &event)
Protected Member Functions
TChannel * Channel () const
bool FragmentHasWaveform () const
void FragmentHasWaveform (const bool &val)
TFragmentMap FragmentMap () const
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & GoodOutputQueues ()
uint64_t LastDaqId () const
uint64_t LastNetworkPacket () const
std::map< UInt_t, Long64_t > LastTimeStampMap () const
uint64_t LastTriggerId () const
void LastTriggerId (const uint64_t &val)
uint64_t MaxTriggerId () const
bool NoWaveforms () const
bool RecordDiag () const
Static Protected Member Functions
static TGRSIOptions * Options ()
static void Options (TGRSIOptions *val)
Private Member Functions
bool SetGRIFCc (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFChannelTriggerId (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFDeadTime (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFHeader (uint32_t, const std::shared_ptr< TFragment > &, EBank)
bool SetGRIFNetworkPacket (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFPrimaryFilterId (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFPrimaryFilterPattern (uint32_t, const std::shared_ptr< TFragment > &, EBank)
bool SetGRIFPsd (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFTimeStampLow (uint32_t, const std::shared_ptr< TFragment > &)
bool SetGRIFWaveForm (uint32_t, const std::shared_ptr< TFragment > &)
bool SetNewPPGPattern (uint32_t, TPPGData *)
bool SetOldPPGPattern (uint32_t, TPPGData *)
bool SetPPGHighTimeStamp (uint32_t, TPPGData *)
bool SetPPGLowTimeStamp (uint32_t, TPPGData *)
bool SetPPGNetworkPacket (uint32_t, TPPGData *)
bool SetScalerHighTimeStamp (uint32_t, TScalerData *, int &)
bool SetScalerLowTimeStamp (uint32_t, TScalerData *)
bool SetScalerNetworkPacket (uint32_t, TScalerData *)
bool SetScalerValue (int, uint32_t, TScalerData *)
void SetTIGAddress (uint32_t, const std::shared_ptr< TFragment > &)
void SetTIGCfd (uint32_t, const std::shared_ptr< TFragment > &)
void SetTIGCharge (uint32_t, const std::shared_ptr< TFragment > &)
void SetTIGLed (uint32_t, const std::shared_ptr< TFragment > &)
bool SetTIGTimeStamp (uint32_t *, const std::shared_ptr< TFragment > &)
bool SetTIGTriggerID (uint32_t, const std::shared_ptr< TFragment > &)
void SetTIGWave (uint32_t, const std::shared_ptr< TFragment > &)
Private Attributes
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > fBadOutputQueue
TChannel * fChannel
bool fFragmentHasWaveform
std::map< Long_t, int > fFragmentIdMap
TFragmentMap fFragmentMap
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > fGoodOutputQueues
bool fIgnoreMissingChannel
std::atomic_long * fInputSize
std::atomic_size_t * fItemsPopped
uint64_t fLastDaqId
uint64_t fLastNetworkPacket
std::map< UInt_t, Long64_t > fLastTimeStampMap
uint64_t fLastTriggerId
const uint64_t fMaxTriggerId
bool fNoWaveforms
bool fRecordDiag
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > fScalerOutputQueue
EDataParserState fState
Static Private Attributes
static TGRSIOptions * fOptions = nullptr
Member Enumeration Documentation
EBank
enum class TGRSIDataParser::EBank strong
Enumerator
kWFDN
kGRF1
kGRF2
kGRF3
kGRF4
kFME0
kFME1
kFME2
kFME3
kMADC
kEMMT
Definition at line 54 of file TGRSIDataParser.h.
EDataParserState
enum class TGRSIDataParser::EDataParserState strong
Enumerator
kGood
kBadHeader
kMissingWords
kBadScalerLowTS
kBadScalerValue
kBadScalerHighTS
kBadScalerType
kBadTriggerId
kBadLowTS
kBadHighTS
kSecondHeader
kWrongNofWords
kNotSingleCfd
kSizeMismatch
kBadFooter
kFault
kMissingPsd
kMissingCfd
kMissingCharge
kBadBank
kBadModuleType
kEndOfData
kBadRFScalerWord
kUndefined
Definition at line 56 of file TGRSIDataParser.h.
Constructor & Destructor Documentation
TGRSIDataParser() [1/3]
TGRSIDataParser::TGRSIDataParser ()
Definition at line 20 of file TGRSIDataParser.cxx.
TGRSIDataParser() [2/3]
TGRSIDataParser::TGRSIDataParser (const TGRSIDataParser &) default
TGRSIDataParser() [3/3]
TGRSIDataParser::TGRSIDataParser (TGRSIDataParser &&) default noexcept
~TGRSIDataParser()
TGRSIDataParser::~TGRSIDataParser () override default
Member Function Documentation
AddGoodOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TDataParser::AddGoodOutputQueue (size_t maxSize = 50000) inline virtual inherited
Definition at line 65 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::AddGoodOutputQueue().
BadOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & TDataParser::BadOutputQueue () inline virtual inherited
Definition at line 73 of file TDataParser.h.
References TDataParser::fBadOutputQueue.
Referenced by TUnpackingLoop::BadOutputQueue(), EmmaTdcDataToFragment(), GriffinDataToFragment(), and RFScalerToFragment().
CaenPhaToFragment()
int TGRSIDataParser::CaenPhaToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Converts a Caen flavoured MIDAS events into TFragments and returns the number of events processed
Definition at line 1790 of file TGRSIDataParser.cxx.
References TGRSIOptions::Get(), TDataParser::GoodOutputQueues(), TDataParser::Options(), TDataParser::Push(), s, and TGRSIOptions::SuppressErrors().
Referenced by Process().
CaenPsdToFragment()
int TGRSIDataParser::CaenPsdToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Converts a Caen flavoured MIDAS events into TFragments and returns the number of events processed
Definition at line 1587 of file TGRSIDataParser.cxx.
References TGRSIOptions::Get(), TDataParser::GoodOutputQueues(), TDataParser::Options(), TDataParser::Push(), s, and TGRSIOptions::SuppressErrors().
Referenced by Process().
Channel()
TChannel * TDataParser::Channel () const inline protected inherited
Definition at line 105 of file TDataParser.h.
References TDataParser::fChannel.
Referenced by EmmaMadcDataToFragment(), and SetTIGCharge().
ClearQueue()
void TDataParser::ClearQueue () virtual inherited
Definition at line 32 of file TDataParser.cxx.
References TDataParser::fBadOutputQueue, TDataParser::fGoodOutputQueues, and TDataParser::fScalerOutputQueue.
Referenced by TUnpackingLoop::ClearQueue().
EightPIDataToFragment()
int TGRSIDataParser::EightPIDataToFragment (uint32_t stream, uint32_t * data, int size, unsigned int midasSerialNumber = 0, time_t midasTime = 0)
EmmaMadcDataToFragment()
int TGRSIDataParser::EmmaMadcDataToFragment (const uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Converts a MIDAS File from the Emma DAQ into a TFragment.
Definition at line 2014 of file TGRSIDataParser.cxx.
References TDataParser::Channel(), TChannel::GetChannel(), TDataParser::GoodOutputQueues(), TDataParser::Push(), xferhfts, xfermidsn, and xfermidts.
Referenced by Process().
EmmaRawDataToFragment()
int TGRSIDataParser::EmmaRawDataToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Extract SRAW data, i.e. the instantaneous rates
Definition at line 2224 of file TGRSIDataParser.cxx.
References TRateScalerQueue::Add(), TRateScalerQueue::Get(), and TScalerData::SetAddress().
Referenced by Process().
EmmaSumDataToFragment()
int TGRSIDataParser::EmmaSumDataToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Extract SSUM data, i.e. the cumulative counts
Definition at line 2237 of file TGRSIDataParser.cxx.
References TRateScalerQueue::Add(), TRateScalerQueue::Get(), and TScalerData::SetAddress().
Referenced by Process().
EmmaTdcDataToFragment()
int TGRSIDataParser::EmmaTdcDataToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Building TDC events, duplicating logic from EmmaMadcDataToFragment
Definition at line 2086 of file TGRSIDataParser.cxx.
References TParsingDiagnostics::BadFragment(), TDataParser::BadOutputQueue(), countsbetweenwraps, fState, TSingleton< TParsingDiagnostics >::Get(), TDataParser::GoodOutputQueues(), kBadFooter, kFault, kGood, kUndefined, lasttimestamp, TDataParser::Push(), wraparoundcounter, xferhfts, xfermidsn, and xfermidts.
Referenced by Process().
EPIXToScalar()
int TGRSIDataParser::EPIXToScalar (float * data, int size, unsigned int midasSerialNumber = 0, time_t midasTime = 0)
Definition at line 1985 of file TGRSIDataParser.cxx.
References TEpicsFrag::GetEpicsVariableName(), and TDataParser::ScalerOutputQueue().
Referenced by Process().
FragmentHasWaveform() [1/2]
bool TDataParser::FragmentHasWaveform () const inline protected inherited
Definition at line 112 of file TDataParser.h.
References TDataParser::fFragmentHasWaveform.
Referenced by GriffinDataToFragment(), and SetGRIFPrimaryFilterPattern().
FragmentHasWaveform() [2/2]
void TDataParser::FragmentHasWaveform (const bool & val) inline protected inherited
Definition at line 122 of file TDataParser.h.
References TDataParser::fFragmentHasWaveform.
FragmentMap()
TFragmentMap TDataParser::FragmentMap () const inline protected inherited
Definition at line 114 of file TDataParser.h.
References TDataParser::fFragmentMap.
Referenced by GriffinDataToFragment().
GoodOutputQueues()
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & TDataParser::GoodOutputQueues () inline protected inherited
Definition at line 101 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by CaenPhaToFragment(), CaenPsdToFragment(), EmmaMadcDataToFragment(), EmmaTdcDataToFragment(), GriffinDataToFragment(), RFScalerToFragment(), and TigressDataToFragment().
GriffinDataToFragment()
int TGRSIDataParser::GriffinDataToFragment (uint32_t * data, int size, EBank bank, unsigned int midasSerialNumber = 0, time_t midasTime = 0)
Converts a Griffin flavoured MIDAS file into a TFragment and returns the number of words processed (or the negative index of the word it failed on)
Definition at line 500 of file TGRSIDataParser.cxx.
References TFragmentMap::Add(), TParsingDiagnostics::BadFragment(), TDataParser::BadOutputQueue(), BLUE, DRED, DYELLOW, fIgnoreMissingChannel, TDataParser::FragmentHasWaveform(), TDataParser::FragmentMap(), fState, TSingleton< TParsingDiagnostics >::Get(), TGRSIOptions::Get(), TChannel::GetChannel(), TParsingDiagnostics::GoodFragment(), TDataParser::GoodOutputQueues(), GriffinDataToPPGEvent(), GriffinDataToScalerEvent(), hex(), kBadBank, kBadFooter, kBadHeader, kBadHighTS, kBadLowTS, kBadModuleType, kBadTriggerId, kEndOfData, kFault, kGood, kGRF1, kGRF2, kGRF3, kGRF4, kMissingCfd, kMissingCharge, kMissingPsd, kMissingWords, kNotSingleCfd, kSecondHeader, kSizeMismatch, kWrongNofWords, TDataParser::LastTimeStampMap(), TDataParser::NoWaveforms(), TDataParser::Options(), TDataParser::Push(), TDataParser::RecordDiag(), RESET_COLOR, RFScalerToFragment(), SetGRIFCc(), SetGRIFChannelTriggerId(), SetGRIFDeadTime(), SetGRIFHeader(), SetGRIFNetworkPacket(), SetGRIFPrimaryFilterId(), SetGRIFPrimaryFilterPattern(), SetGRIFPsd(), SetGRIFTimeStampLow(), and SetGRIFWaveForm().
Referenced by ProcessGriffin(), and QueueEvents().
GriffinDataToPPGEvent()
int TGRSIDataParser::GriffinDataToPPGEvent (uint32_t * data, int size, unsigned int midasSerialNumber = 0, time_t midasTime = 0)
Definition at line 1401 of file TGRSIDataParser.cxx.
References TPPG::AddData(), TParsingDiagnostics::BadFragment(), TSingleton< TPPG >::Get(), TSingleton< TParsingDiagnostics >::Get(), TParsingDiagnostics::GoodFragment(), SetNewPPGPattern(), SetOldPPGPattern(), SetPPGHighTimeStamp(), SetPPGLowTimeStamp(), and SetPPGNetworkPacket().
Referenced by GriffinDataToFragment().
GriffinDataToScalerEvent()
int TGRSIDataParser::GriffinDataToScalerEvent (uint32_t * data, int address)
Definition at line 1494 of file TGRSIDataParser.cxx.
References TDeadtimeScalerQueue::Add(), TRateScalerQueue::Add(), TParsingDiagnostics::BadFragment(), fState, TDeadtimeScalerQueue::Get(), TRateScalerQueue::Get(), TSingleton< TParsingDiagnostics >::Get(), TParsingDiagnostics::GoodFragment(), kBadScalerHighTS, kBadScalerLowTS, kBadScalerType, kBadScalerValue, TScalerData::SetAddress(), SetScalerHighTimeStamp(), SetScalerLowTimeStamp(), SetScalerNetworkPacket(), and SetScalerValue().
Referenced by GriffinDataToFragment().
ItemsPushed()
virtual size_t TDataParser::ItemsPushed () inline virtual inherited
Definition at line 88 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::GetItemsPushed().
LastDaqId()
uint64_t TDataParser::LastDaqId () const inline protected inherited
Definition at line 108 of file TDataParser.h.
References TDataParser::fLastDaqId.
LastNetworkPacket()
uint64_t TDataParser::LastNetworkPacket () const inline protected inherited
Definition at line 110 of file TDataParser.h.
References TDataParser::fLastNetworkPacket.
LastTimeStampMap()
std::map< UInt_t, Long64_t > TDataParser::LastTimeStampMap () const inline protected inherited
Definition at line 115 of file TDataParser.h.
References TDataParser::fLastTimeStampMap.
Referenced by GriffinDataToFragment().
LastTriggerId() [1/2]
uint64_t TDataParser::LastTriggerId () const inline protected inherited
Definition at line 109 of file TDataParser.h.
References TDataParser::fLastTriggerId.
Referenced by SetTIGTriggerID().
LastTriggerId() [2/2]
void TDataParser::LastTriggerId (const uint64_t & val) inline protected inherited
Definition at line 120 of file TDataParser.h.
References TDataParser::fLastTriggerId.
MaxTriggerId()
uint64_t TDataParser::MaxTriggerId () const inline protected inherited
Definition at line 107 of file TDataParser.h.
References TDataParser::fMaxTriggerId.
Referenced by SetTIGTriggerID().
NoWaveforms()
bool TDataParser::NoWaveforms () const inline protected inherited
Definition at line 103 of file TDataParser.h.
References TDataParser::fNoWaveforms.
Referenced by GriffinDataToFragment(), and TigressDataToFragment().
operator=() [1/2]
TGRSIDataParser & TGRSIDataParser::operator= (const TGRSIDataParser &) delete
operator=() [2/2]
TGRSIDataParser & TGRSIDataParser::operator= (TGRSIDataParser &&) delete noexcept
Options() [1/2]
static TGRSIOptions * TDataParser::Options () inline static protected inherited
Definition at line 117 of file TDataParser.h.
References TDataParser::fOptions.
Referenced by CaenPhaToFragment(), CaenPsdToFragment(), and GriffinDataToFragment().
Options() [2/2]
static void TDataParser::Options (TGRSIOptions * val) inline static protected inherited
Definition at line 124 of file TDataParser.h.
References TDataParser::fOptions.
OutputQueueStatus()
std::string TDataParser::OutputQueueStatus () virtual inherited
Definition at line 78 of file TDataParser.cxx.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::EndStatus().
Process()
int TGRSIDataParser::Process (std::shared_ptr< TRawEvent > rawEvent) override virtual
Implements TDataParser.
Definition at line 25 of file TGRSIDataParser.cxx.
References CaenPhaToFragment(), CaenPsdToFragment(), DRED, EmmaMadcDataToFragment(), EmmaRawDataToFragment(), EmmaSumDataToFragment(), EmmaTdcDataToFragment(), EPIXToScalar(), TGRSIOptions::Get(), kGRF1, kGRF2, kGRF3, kGRF4, ProcessGriffin(), RESET_COLOR, TRunInfo::SetRunLength(), TRunInfo::SetRunStop(), TGRSIOptions::SuppressErrors(), and TigressDataToFragment().
ProcessGriffin()
int TGRSIDataParser::ProcessGriffin (uint32_t * data, const int & size, const EBank & bank, std::shared_ptr< TMidasEvent > & event)
Definition at line 434 of file TGRSIDataParser.cxx.
References DRED, TGRSIOptions::Get(), TGRSIDataParserException::GetFailedWord(), GriffinDataToFragment(), RESET_COLOR, and TGRSIDataParserException::what().
Referenced by Process().
Push() [1/2]
void TDataParser::Push (std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & queues, const std::shared_ptr< TFragment > & frag) inherited
Definition at line 59 of file TDataParser.cxx.
References TDataParser::fFragmentIdMap.
Push() [2/2]
void TDataParser::Push (ThreadsafeQueue< std::shared_ptr< const TBadFragment > > & queue, const std::shared_ptr< TBadFragment > & frag) inherited
Definition at line 70 of file TDataParser.cxx.
References TDataParser::fFragmentIdMap.
Referenced by CaenPhaToFragment(), CaenPsdToFragment(), THILDataParser::EagleEventToFragment(), EmmaMadcDataToFragment(), EmmaTdcDataToFragment(), GriffinDataToFragment(), RFScalerToFragment(), TTdrDataParser::TdrToFragment(), TigressDataToFragment(), TILLDataParser::V1SingleFippsEventToFragment(), and TILLDataParser::V2SingleFippsEventToFragment().
RecordDiag()
bool TDataParser::RecordDiag () const inline protected inherited
Definition at line 104 of file TDataParser.h.
References TDataParser::fRecordDiag.
Referenced by GriffinDataToFragment().
RFScalerToFragment()
int TGRSIDataParser::RFScalerToFragment (uint32_t * data, int size, const std::shared_ptr< TFragment > & frag)
Definition at line 1239 of file TGRSIDataParser.cxx.
References TParsingDiagnostics::BadFragment(), TDataParser::BadOutputQueue(), fState, TSingleton< TParsingDiagnostics >::Get(), TDataParser::GoodOutputQueues(), kBadRFScalerWord, kEndOfData, kUndefined, TDataParser::Push(), and s.
Referenced by GriffinDataToFragment().
ScalerOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & TDataParser::ScalerOutputQueue () inline virtual inherited
Definition at line 75 of file TDataParser.h.
References TDataParser::fScalerOutputQueue.
Referenced by EPIXToScalar(), and TUnpackingLoop::ScalerOutputQueue().
SCLRToScalar()
int TGRSIDataParser::SCLRToScalar (uint32_t * data, int size, unsigned int midasSerialNumber = 0, time_t midasTime = 0)
SetFinished()
void TDataParser::SetFinished () virtual inherited
Definition at line 50 of file TDataParser.cxx.
References TDataParser::fBadOutputQueue, TDataParser::fGoodOutputQueues, and TDataParser::fScalerOutputQueue.
Referenced by TUnpackingLoop::Iteration().
SetGRIFCc()
bool TGRSIDataParser::SetGRIFCc (uint32_t value, const std::shared_ptr< TFragment > & frag) private
set the short integration and the lower 9 bits of the long integration
Definition at line 1217 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFChannelTriggerId()
bool TGRSIDataParser::SetGRIFChannelTriggerId (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Sets the Griffin Channel Trigger ID
Definition at line 1148 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFDeadTime()
bool TGRSIDataParser::SetGRIFDeadTime (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Sets the Griffin deadtime and the upper 14 bits of the timestamp
Definition at line 1205 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFHeader()
bool TGRSIDataParser::SetGRIFHeader (uint32_t value, const std::shared_ptr< TFragment > & frag, EBank bank) private
Definition at line 1062 of file TGRSIDataParser.cxx.
References kGRF1, kGRF2, kGRF3, and kGRF4.
Referenced by GriffinDataToFragment().
SetGRIFNetworkPacket()
bool TGRSIDataParser::SetGRIFNetworkPacket (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Ignores the network packet number (for now)
Definition at line 1158 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFPrimaryFilterId()
bool TGRSIDataParser::SetGRIFPrimaryFilterId (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Sets the Griffin Primary filter ID and PPG
Definition at line 1137 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFPrimaryFilterPattern()
bool TGRSIDataParser::SetGRIFPrimaryFilterPattern (uint32_t value, const std::shared_ptr< TFragment > & frag, EBank bank) private
Sets the Griffin Primary Filter Pattern
Definition at line 1114 of file TGRSIDataParser.cxx.
References TDataParser::FragmentHasWaveform(), kGRF1, kGRF2, kGRF3, and kGRF4.
Referenced by GriffinDataToFragment().
SetGRIFPsd()
bool TGRSIDataParser::SetGRIFPsd (uint32_t value, const std::shared_ptr< TFragment > & frag) private
set the zero crossing and the higher 10 bits of the long integration
Definition at line 1228 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFTimeStampLow()
bool TGRSIDataParser::SetGRIFTimeStampLow (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Sets the lower 28 bits of the griffin time stamp
Definition at line 1176 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetGRIFWaveForm()
bool TGRSIDataParser::SetGRIFWaveForm (uint32_t value, const std::shared_ptr< TFragment > & frag) private
Sets the Griffin waveform if record_waveform is set to true
Definition at line 1187 of file TGRSIDataParser.cxx.
Referenced by GriffinDataToFragment().
SetNewPPGPattern()
bool TGRSIDataParser::SetNewPPGPattern (uint32_t value, TPPGData * ppgevent) private
Definition at line 1450 of file TGRSIDataParser.cxx.
References TPPGData::SetNewPPG().
Referenced by GriffinDataToPPGEvent().
SetNoWaveForms()
virtual void TDataParser::SetNoWaveForms (bool temp = true) inline virtual inherited
Definition at line 50 of file TDataParser.h.
References TDataParser::fNoWaveforms.
Referenced by TUnpackingLoop::SetNoWaveForms().
SetOldPPGPattern()
bool TGRSIDataParser::SetOldPPGPattern (uint32_t value, TPPGData * ppgevent) private
Definition at line 1459 of file TGRSIDataParser.cxx.
References TPPGData::SetOldPPG().
Referenced by GriffinDataToPPGEvent().
SetPPGHighTimeStamp()
bool TGRSIDataParser::SetPPGHighTimeStamp (uint32_t value, TPPGData * ppgevent) private
Definition at line 1485 of file TGRSIDataParser.cxx.
References TPPGData::SetHighTimeStamp().
Referenced by GriffinDataToPPGEvent().
SetPPGLowTimeStamp()
bool TGRSIDataParser::SetPPGLowTimeStamp (uint32_t value, TPPGData * ppgevent) private
Definition at line 1476 of file TGRSIDataParser.cxx.
References TPPGData::SetLowTimeStamp().
Referenced by GriffinDataToPPGEvent().
SetPPGNetworkPacket()
bool TGRSIDataParser::SetPPGNetworkPacket (uint32_t value, TPPGData * ppgevent) private
Definition at line 1465 of file TGRSIDataParser.cxx.
References TPPGData::SetNetworkPacketId().
Referenced by GriffinDataToPPGEvent().
SetRecordDiag()
virtual void TDataParser::SetRecordDiag (bool temp = true) inline virtual inherited
Definition at line 51 of file TDataParser.h.
References TDataParser::fRecordDiag.
Referenced by TUnpackingLoop::SetRecordDiag().
SetScalerHighTimeStamp()
bool TGRSIDataParser::SetScalerHighTimeStamp (uint32_t value, TScalerData * scalerEvent, int & type) private
Definition at line 1569 of file TGRSIDataParser.cxx.
References TScalerData::GetLowTimeStamp(), and TScalerData::SetHighTimeStamp().
Referenced by GriffinDataToScalerEvent().
SetScalerLowTimeStamp()
bool TGRSIDataParser::SetScalerLowTimeStamp (uint32_t value, TScalerData * scalerEvent) private
Definition at line 1558 of file TGRSIDataParser.cxx.
References TScalerData::SetLowTimeStamp().
Referenced by GriffinDataToScalerEvent().
SetScalerNetworkPacket()
bool TGRSIDataParser::SetScalerNetworkPacket (uint32_t value, TScalerData * scalerEvent) private
Definition at line 1549 of file TGRSIDataParser.cxx.
References TScalerData::SetNetworkPacketId().
Referenced by GriffinDataToScalerEvent().
SetScalerValue()
bool TGRSIDataParser::SetScalerValue (int index, uint32_t value, TScalerData * scalerEvent) private
Definition at line 1581 of file TGRSIDataParser.cxx.
References TScalerData::SetScaler().
Referenced by GriffinDataToScalerEvent().
SetStatusVariables()
virtual void TDataParser::SetStatusVariables (std::atomic_size_t * itemsPopped, std::atomic_long * inputSize) inline virtual inherited
Definition at line 77 of file TDataParser.h.
References TDataParser::fInputSize, and TDataParser::fItemsPopped.
Referenced by TUnpackingLoop::Iteration().
SetTIGAddress()
void TGRSIDataParser::SetTIGAddress (uint32_t value, const std::shared_ptr< TFragment > & currentFrag) private
Sets the digitizer address of the 'currentFrag' TFragment
Definition at line 229 of file TGRSIDataParser.cxx.
Referenced by TigressDataToFragment().
SetTIGCfd()
void TGRSIDataParser::SetTIGCfd (uint32_t value, const std::shared_ptr< TFragment > & currentFrag) private
Sets the CFD of a Tigress Event.
Definition at line 262 of file TGRSIDataParser.cxx.
Referenced by TigressDataToFragment().
SetTIGCharge()
void TGRSIDataParser::SetTIGCharge (uint32_t value, const std::shared_ptr< TFragment > & currentFragment) private
Sets the integrated charge of a Tigress event.
Definition at line 276 of file TGRSIDataParser.cxx.
References TDataParser::Channel(), TChannel::GetChannel(), and TChannel::GetDigitizerTypeString().
Referenced by TigressDataToFragment().
SetTIGLed()
void TGRSIDataParser::SetTIGLed (uint32_t , const std::shared_ptr< TFragment > &) private
Sets the LED of a Tigress event.
Definition at line 269 of file TGRSIDataParser.cxx.
Referenced by TigressDataToFragment().
SetTIGTimeStamp()
bool TGRSIDataParser::SetTIGTimeStamp (uint32_t * data, const std::shared_ptr< TFragment > & currentFrag) private
Sets the Timestamp of a Tigress Event
Definition at line 340 of file TGRSIDataParser.cxx.
References hex().
Referenced by TigressDataToFragment().
SetTIGTriggerID()
bool TGRSIDataParser::SetTIGTriggerID (uint32_t value, const std::shared_ptr< TFragment > & currentFrag) private
Sets the Trigger ID of a Tigress event.
Definition at line 308 of file TGRSIDataParser.cxx.
References DBLUE, DRED, TDataParser::LastTriggerId(), TDataParser::MaxTriggerId(), and RESET_COLOR.
Referenced by TigressDataToFragment().
SetTIGWave()
void TGRSIDataParser::SetTIGWave (uint32_t value, const std::shared_ptr< TFragment > & currentFrag) private
Sets the waveform for a Tigress event.
Definition at line 235 of file TGRSIDataParser.cxx.
Referenced by TigressDataToFragment().
TigressDataToFragment()
int TGRSIDataParser::TigressDataToFragment (uint32_t * data, int size, std::shared_ptr< TMidasEvent > & event)
Converts A MIDAS File from the Tigress DAQ into a TFragment.
check whether the fragment is 'good'
Definition at line 136 of file TGRSIDataParser.cxx.
References DYELLOW, TChannel::GetChannel(), TDataParser::GoodOutputQueues(), hex(), TDataParser::NoWaveforms(), TDataParser::Push(), RED, RESET_COLOR, SetTIGAddress(), SetTIGCfd(), SetTIGCharge(), SetTIGLed(), SetTIGTimeStamp(), SetTIGTriggerID(), and SetTIGWave().
Referenced by Process().
Member Data Documentation
fBadOutputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TBadFragment> > > TDataParser::fBadOutputQueue private inherited
Definition at line 130 of file TDataParser.h.
Referenced by TDataParser::BadOutputQueue(), TDataParser::ClearQueue(), THILDataParser::EagleEventToFragment(), TDataParser::SetFinished(), TTdrDataParser::TdrToFragment(), TILLDataParser::V1SingleFippsEventToFragment(), and TILLDataParser::V2SingleFippsEventToFragment().
fChannel
TChannel* TDataParser::fChannel private inherited
Definition at line 136 of file TDataParser.h.
Referenced by TDataParser::~TDataParser(), and TDataParser::Channel().
fFragmentHasWaveform
bool TDataParser::fFragmentHasWaveform private inherited
Definition at line 144 of file TDataParser.h.
Referenced by TDataParser::FragmentHasWaveform(), and TDataParser::FragmentHasWaveform().
fFragmentIdMap
std::map<Long_t, int> TDataParser::fFragmentIdMap private inherited
Definition at line 143 of file TDataParser.h.
Referenced by TDataParser::Push(), and TDataParser::Push().
fFragmentMap
TFragmentMap TDataParser::fFragmentMap private inherited
Class that holds a map of fragments per address, takes care of calculating charges for GRF4 banks.
Definition at line 146 of file TDataParser.h.
Referenced by TDataParser::FragmentMap().
fGoodOutputQueues
std::vector<std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > > TDataParser::fGoodOutputQueues private inherited
Definition at line 129 of file TDataParser.h.
Referenced by TDataParser::AddGoodOutputQueue(), TDataParser::ClearQueue(), THILDataParser::EagleEventToFragment(), TDataParser::GoodOutputQueues(), TDataParser::ItemsPushed(), TDataParser::OutputQueueStatus(), TDataParser::SetFinished(), TTdrDataParser::TdrToFragment(), TILLDataParser::V1SingleFippsEventToFragment(), and TILLDataParser::V2SingleFippsEventToFragment().
fIgnoreMissingChannel
bool TGRSIDataParser::fIgnoreMissingChannel private
flag that's set to TGRSIOptions::IgnoreMissingChannel
Definition at line 107 of file TGRSIDataParser.h.
Referenced by GriffinDataToFragment().
fInputSize
std::atomic_long* TDataParser::fInputSize private inherited
Definition at line 154 of file TDataParser.h.
Referenced by THILDataParser::Process(), TILLDataParser::Process(), TDataParser::SetStatusVariables(), and TTdrDataParser::TdrToFragment().
fItemsPopped
std::atomic_size_t* TDataParser::fItemsPopped private inherited
Definition at line 153 of file TDataParser.h.
Referenced by THILDataParser::Process(), TILLDataParser::Process(), TDataParser::SetStatusVariables(), and TTdrDataParser::TdrToFragment().
fLastDaqId
uint64_t TDataParser::fLastDaqId private inherited
The last daq ID in the raw file.
Definition at line 139 of file TDataParser.h.
Referenced by TDataParser::LastDaqId().
fLastNetworkPacket
uint64_t TDataParser::fLastNetworkPacket private inherited
The last network packet recieved.
Definition at line 141 of file TDataParser.h.
Referenced by TDataParser::LastNetworkPacket().
fLastTimeStampMap
std::map<UInt_t, Long64_t> TDataParser::fLastTimeStampMap private inherited
Definition at line 148 of file TDataParser.h.
Referenced by TDataParser::LastTimeStampMap().
fLastTriggerId
uint64_t TDataParser::fLastTriggerId private inherited
The last Trigged ID in the raw File.
Definition at line 140 of file TDataParser.h.
Referenced by TDataParser::LastTriggerId(), and TDataParser::LastTriggerId().
fMaxTriggerId
const uint64_t TDataParser::fMaxTriggerId private inherited
The last trigger ID Called.
Definition at line 138 of file TDataParser.h.
Referenced by TDataParser::MaxTriggerId().
fNoWaveforms
bool TDataParser::fNoWaveforms private inherited
The flag to turn wave_forms on or off.
Definition at line 134 of file TDataParser.h.
Referenced by TDataParser::NoWaveforms(), and TDataParser::SetNoWaveForms().
fOptions
TGRSIOptions * TDataParser::fOptions = nullptr static private inherited
Static pointer to TGRSIOptions, gets set on the first call of GriffinDataToFragment.
Definition at line 150 of file TDataParser.h.
Referenced by TDataParser::Options(), and TDataParser::Options().
fRecordDiag
bool TDataParser::fRecordDiag private inherited
The flag to turn on diagnostics recording.
Definition at line 135 of file TDataParser.h.
Referenced by THILDataParser::EagleEventToFragment(), TDataParser::RecordDiag(), TDataParser::SetRecordDiag(), TTdrDataParser::TdrToFragment(), TILLDataParser::V1SingleFippsEventToFragment(), and TILLDataParser::V2SingleFippsEventToFragment().
fScalerOutputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<TEpicsFrag> > > TDataParser::fScalerOutputQueue private inherited
Definition at line 131 of file TDataParser.h.
Referenced by TDataParser::ClearQueue(), TDataParser::ScalerOutputQueue(), and TDataParser::SetFinished().
fState
EDataParserState TGRSIDataParser::fState private
Definition at line 106 of file TGRSIDataParser.h.
Referenced by EmmaTdcDataToFragment(), GriffinDataToFragment(), GriffinDataToScalerEvent(), and RFScalerToFragment().