GRSISort: TMidasFile Class Reference
TMidasFile Class Reference
Sorting
Detailed Description
Reader for MIDAS .mid files.
This Class is used to read and write MIDAS files in the root framework. It reads and writes TMidasEvents.
Definition at line 32 of file TMidasFile.h.
Public Types
enum class EOpenType { kRead , kWrite }
Public Member Functions
TMidasFile ()
TMidasFile (const char *filename, TRawFile::EOpenType open_type=TRawFile::EOpenType::kRead)
TMidasFile (const TMidasFile &)=default
TMidasFile (TMidasFile &&) noexcept=default
~TMidasFile () override
char * BufferData ()
size_t BufferSize () const
virtual size_t BytesRead ()
void ClearBuffer ()
void Close () override
virtual std::string Filename () const
virtual void Filename (const char *val)
virtual size_t FileSize ()
void FileSize (size_t fileSize)
void FillBuffer (const std::shared_ptr< TMidasEvent > &midasEvent, Option_t *opt="")
virtual const char * GetFilename () const
int GetLastErrno () const
const char * GetLastError () const
std::shared_ptr< TRawEvent > GetOdbEvent () override
int GetRunNumber () override
int GetSubRunNumber () override
void IncrementBytesRead (size_t val=1)
std::shared_ptr< TRawEvent > NewEvent () override
bool Open (const char *filename) override
TMidasFile & operator= (const TMidasFile &)=default
TMidasFile & operator= (TMidasFile &&) noexcept=default
void OutClose ()
bool OutOpen (const char *filename)
int Read (std::shared_ptr< TRawEvent > event) override
void ResizeBuffer (size_t newSize)
void SetMaxBufferSize (int maxsize)
void Skip (size_t nofEvents) override
std::string Status (bool long_file_description=true) override
bool Write (const std::shared_ptr< TMidasEvent > &midasEvent, Option_t *opt="")
bool WriteBuffer ()
Private Member Functions
void ReadMoreBytes (size_t bytes)
void SetEPICSOdb ()
void SetFileOdb ()
void SetGRIFFOdb ()
void SetRunInfo (uint32_t time)
void SetTIGDAQOdb ()
void SetTIGOdb ()
Private Attributes
size_t fBytesRead {0}
uint32_t fCurrentBufferSize {0}
int fCurrentEventNumber {0}
bool fDoByteSwap {false}
int fFile {-1}
std::string fFilename
size_t fFileSize {0}
void * fGzFile {nullptr}
int fLastErrno {0}
std::string fLastError
uint32_t fMaxBufferSize {1000000}
TXMLOdb * fOdb
std::shared_ptr< TMidasEvent > fOdbEvent
int fOutFile {-1}
std::string fOutFilename
void * fOutGzFile {nullptr}
void * fPoFile {nullptr}
std::vector< char > fReadBuffer
std::vector< char > fWriteBuffer
Member Enumeration Documentation
EOpenType
enum class TRawFile::EOpenType strong inherited
Enumerator
kRead
kWrite
Definition at line 33 of file TRawFile.h.
Constructor & Destructor Documentation
TMidasFile() [1/4]
TMidasFile::TMidasFile ()
default constructor
Definition at line 25 of file TMidasFile.cxx.
TMidasFile() [2/4]
TMidasFile::TMidasFile (const char * filename, TRawFile::EOpenType open_type = TRawFile::EOpenType::kRead) explicit
Definition at line 35 of file TMidasFile.cxx.
References fLastError, TRawFile::kRead, TRawFile::kWrite, Open(), OutOpen(), RED, and RESET_COLOR.
TMidasFile() [3/4]
TMidasFile::TMidasFile (const TMidasFile &) default
TMidasFile() [4/4]
TMidasFile::TMidasFile (TMidasFile &&) default noexcept
~TMidasFile()
TMidasFile::~TMidasFile () override
destructor
Definition at line 49 of file TMidasFile.cxx.
References Close(), and OutClose().
Member Function Documentation
BufferData()
char * TRawFile::BufferData () inline inherited
Definition at line 70 of file TRawFile.h.
References TRawFile::fReadBuffer.
Referenced by Read(), ReadMoreBytes(), and Skip().
BufferSize()
size_t TRawFile::BufferSize () const inline inherited
Definition at line 69 of file TRawFile.h.
References TRawFile::fReadBuffer.
Referenced by Read(), ReadMoreBytes(), and Skip().
BytesRead()
virtual size_t TRawFile::BytesRead () inline virtual inherited
Definition at line 61 of file TRawFile.h.
References TRawFile::fBytesRead.
Referenced by TDataLoop::Iteration(), and Status().
ClearBuffer()
void TRawFile::ClearBuffer () inline inherited
Definition at line 71 of file TRawFile.h.
References TRawFile::fReadBuffer.
Referenced by Read(), and Skip().
Close()
void TMidasFile::Close () override virtual
Close input file.
Implements TRawFile.
Definition at line 546 of file TMidasFile.cxx.
References fFile, fGzFile, TRawFile::Filename(), and fPoFile.
Referenced by ~TMidasFile(), and Open().
Filename() [1/2]
virtual std::string TRawFile::Filename () const inline virtual inherited
Get the name of this file.
Definition at line 66 of file TRawFile.h.
References TRawFile::fFilename.
Referenced by Close(), GetRunNumber(), GetSubRunNumber(), and Open().
Filename() [2/2]
virtual void TRawFile::Filename (const char * val) inline virtual inherited
Definition at line 67 of file TRawFile.h.
References TRawFile::fFilename.
FileSize() [1/2]
virtual size_t TRawFile::FileSize () inline virtual inherited
Definition at line 63 of file TRawFile.h.
References TRawFile::fFileSize.
Referenced by TDataLoop::Iteration(), Open(), and Status().
FileSize() [2/2]
void TRawFile::FileSize (size_t fileSize) inline inherited
Definition at line 64 of file TRawFile.h.
References TRawFile::fFileSize.
FillBuffer()
void TMidasFile::FillBuffer (const std::shared_ptr< TMidasEvent > & midasEvent, Option_t * opt = "")
Definition at line 437 of file TMidasFile.cxx.
References fCurrentBufferSize, fMaxBufferSize, fWriteBuffer, and WriteBuffer().
Referenced by ProcessEvent(), Write(), and WriteEvents().
GetFilename()
virtual const char * TRawFile::GetFilename () const inline virtual inherited
Get the name of this file.
Definition at line 56 of file TRawFile.h.
References TRawFile::fFilename.
Referenced by Open(), TRlmdFile::Open(), TLstFile::Open(), TTdrFile::Open(), and WriteEvents().
GetLastErrno()
int TMidasFile::GetLastErrno () const inline
Get error value for the last file error.
Definition at line 65 of file TMidasFile.h.
References fLastErrno.
Referenced by WriteEvents().
GetLastError()
const char * TMidasFile::GetLastError () const inline
Get error text for the last file error.
Definition at line 66 of file TMidasFile.h.
References fLastError.
Referenced by WriteEvents().
GetOdbEvent()
std::shared_ptr< TRawEvent > TMidasFile::GetOdbEvent () inline override virtual
Reimplemented from TRawFile.
Definition at line 69 of file TMidasFile.h.
References fOdbEvent.
Referenced by ExamineMidasFile().
GetRunNumber()
int TMidasFile::GetRunNumber () override virtual
Implements TRawFile.
Definition at line 587 of file TMidasFile.cxx.
References TRawFile::Filename().
Referenced by Open().
GetSubRunNumber()
int TMidasFile::GetSubRunNumber () override virtual
Implements TRawFile.
Definition at line 615 of file TMidasFile.cxx.
References TRawFile::Filename().
Referenced by Open(), and QueueEvents().
IncrementBytesRead()
void TRawFile::IncrementBytesRead (size_t val = 1) inline inherited
Definition at line 62 of file TRawFile.h.
References TRawFile::fBytesRead.
Referenced by Read(), and Skip().
NewEvent()
std::shared_ptr< TRawEvent > TMidasFile::NewEvent () inline override virtual
Implements TRawFile.
Definition at line 81 of file TMidasFile.h.
Open()
bool TMidasFile::Open (const char * filename) override virtual
Open input file.
Open a midas .mid file with given file name.
Remote files can be accessed using these special file names:
pipein://command - read data produced by given command, see examples below
ssh://username@hostname/path/file.mid - read remote file through an ssh pipe
ssh://username@hostname/path/file.mid.gz and file.mid.bz2 - same for compressed files
dccp://path/file.mid (also file.mid.gz and file.mid.bz2) - read data from dcache, requires dccp in the PATH
Examples:
./event_dump.exe /ladd/data9/t2km11/data/run02696.mid.gz - read normal compressed file
./event_dump.exe ssh://ladd09//ladd/data9/t2km11/data/run02696.mid.gz - read compressed file through ssh to ladd09 (note double "/")
./event_dump.exe pipein://"cat /ladd/data9/t2km11/data/run02696.mid.gz | gzip -dc" - read data piped from a command or script (note quotes)
./event_dump.exe pipein://"gzip -dc /ladd/data9/t2km11/data/run02696.mid.gz" - another way to read compressed files
./event_dump.exe dccp:///pnfs/triumf.ca/data/t2km11/aug2008/run02837.mid.gz - read file directly from a dcache pool (note triple "/")
Parameters
[in] filename The file to open.
Returns
"true" for succes, "false" for error, use GetLastError() to see why
Implements TRawFile.
Definition at line 95 of file TMidasFile.cxx.
References TRunInfo::ClearLibraryVersion(), Close(), fFile, fGzFile, TRawFile::Filename(), TRawFile::FileSize(), fLastErrno, fLastError, fOdbEvent, fPoFile, TRawFile::GetFilename(), GetRunNumber(), GetSubRunNumber(), hasSuffix(), O_LARGEFILE, Read(), s, TRunInfo::SetDetectorInformation(), SetFileOdb(), TRunInfo::SetLibraryVersion(), TChannel::SetMnemonicClass(), and TRunInfo::SetRunInfo().
Referenced by TMidasFile(), ExamineMidasFile(), and main().
operator=() [1/2]
TMidasFile & TMidasFile::operator= (const TMidasFile &) default
operator=() [2/2]
TMidasFile & TMidasFile::operator= (TMidasFile &&) default noexcept
OutClose()
void TMidasFile::OutClose ()
Close output file.
Definition at line 566 of file TMidasFile.cxx.
References fOutFile, fOutFilename, fOutGzFile, fWriteBuffer, and WriteBuffer().
Referenced by ~TMidasFile(), and OutOpen().
OutOpen()
bool TMidasFile::OutOpen (const char * filename)
Open output file.
Open a midas .mid file for OUTPUT with given file name.
Remote files not yet implemented
Parameters
[in] filename The file to open.
Returns
"true" for succes, "false" for error, use GetLastError() to see why
Definition at line 229 of file TMidasFile.cxx.
References fLastErrno, fLastError, fOutFile, fOutFilename, fOutGzFile, hasSuffix(), O_LARGEFILE, and OutClose().
Referenced by TMidasFile().
Read()
int TMidasFile::Read (std::shared_ptr< TRawEvent > event) override virtual
Read one event from the file.
Parameters
[in] event shared Pointer to an empty TMidasEvent
Returns
"true" for success, "false" for failure, see GetLastError() to see why
EDITED FROM THE ORIGINAL TO RETURN TOTAL SUCESSFULLY BYTES READ INSTEAD OF TRUE/FALSE, PCB
Implements TRawFile.
Definition at line 309 of file TMidasFile.cxx.
References TRawFile::BufferData(), TRawFile::BufferSize(), TRawFile::ClearBuffer(), fCurrentEventNumber, fDoByteSwap, fLastErrno, fLastError, TRawFile::IncrementBytesRead(), and ReadMoreBytes().
Referenced by ExamineMidasFile(), Open(), QueueEvents(), and WriteEvents().
ReadMoreBytes()
void TMidasFile::ReadMoreBytes (size_t bytes) private
Definition at line 411 of file TMidasFile.cxx.
References TRawFile::BufferData(), TRawFile::BufferSize(), fFile, fGzFile, fLastErrno, fLastError, readpipe(), and TRawFile::ResizeBuffer().
Referenced by Read(), and Skip().
ResizeBuffer()
void TRawFile::ResizeBuffer (size_t newSize) inline inherited
Definition at line 72 of file TRawFile.h.
References TRawFile::fReadBuffer.
Referenced by ReadMoreBytes().
SetEPICSOdb()
void TMidasFile::SetEPICSOdb () private
Definition at line 728 of file TMidasFile.cxx.
References TXMLOdb::FindPath(), fOdb, TXMLOdb::ReadStringArray(), and TEpicsFrag::SetEpicsNameList().
Referenced by SetFileOdb().
SetFileOdb()
void TMidasFile::SetFileOdb () private
Definition at line 637 of file TMidasFile.cxx.
References TChannel::DeleteAllChannels(), DYELLOW, TXMLOdb::FindPath(), fOdb, fOdbEvent, TGRSIOptions::Get(), TXMLOdb::GetNodeName(), RED, RESET_COLOR, SetEPICSOdb(), SetGRIFFOdb(), SetRunInfo(), SetTIGDAQOdb(), and SetTIGOdb().
Referenced by Open().
SetGRIFFOdb()
void TMidasFile::SetGRIFFOdb () private
Definition at line 737 of file TMidasFile.cxx.
References TChannel::AddChannel(), TChannel::AddENGCoefficient(), BG_WHITE, DRED, TXMLOdb::FindPath(), fOdb, TSingleton< TPPG >::Get(), TChannel::GetChannel(), TChannel::GetNumberOfChannels(), kRootFile, TXMLOdb::ReadDoubleArray(), TXMLOdb::ReadIntArray(), TXMLOdb::ReadStringArray(), RESET_COLOR, TChannel::SetAddress(), TChannel::SetDigitizerType(), TChannel::SetName(), TChannel::SetNumber(), and TPPG::SetOdbCycle().
Referenced by SetFileOdb().
SetMaxBufferSize()
void TMidasFile::SetMaxBufferSize (int maxsize)
Definition at line 539 of file TMidasFile.cxx.
References fMaxBufferSize.
SetRunInfo()
void TMidasFile::SetRunInfo (uint32_t time) private
Definition at line 700 of file TMidasFile.cxx.
References DBLUE, TXMLOdb::FindPath(), fOdb, RESET_COLOR, TRunInfo::SetRunComment(), TRunInfo::SetRunStart(), TRunInfo::SetRunTitle(), and TRunInfo::SubRunNumber().
Referenced by SetFileOdb().
SetTIGDAQOdb()
void TMidasFile::SetTIGDAQOdb () private
Definition at line 989 of file TMidasFile.cxx.
References TChannel::AddENGCoefficient(), BG_WHITE, DRED, TXMLOdb::FindPath(), fOdb, TChannel::GetChannel(), TChannel::GetNumberOfChannels(), kRootFile, TXMLOdb::ReadDoubleArray(), TXMLOdb::ReadIntArray(), TXMLOdb::ReadStringArray(), RESET_COLOR, TChannel::SetAddress(), TChannel::SetName(), and TChannel::SetNumber().
Referenced by SetFileOdb().
SetTIGOdb()
void TMidasFile::SetTIGOdb () private
Definition at line 879 of file TMidasFile.cxx.
References TChannel::AddChannel(), TChannel::AddENGCoefficient(), BG_WHITE, DRED, TXMLOdb::FindPath(), fOdb, TChannel::GetChannel(), TChannel::GetDigitizerTypeString(), TXMLOdb::GetNodeName(), TChannel::GetNumberOfChannels(), kRootFile, TXMLOdb::ReadDoubleArray(), TXMLOdb::ReadIntArray(), TXMLOdb::ReadStringArray(), RESET_COLOR, TChannel::SetAddress(), TChannel::SetDigitizerType(), TChannel::SetIntegration(), TChannel::SetName(), and TChannel::SetNumber().
Referenced by SetFileOdb().
Skip()
void TMidasFile::Skip (size_t nofEvents) override virtual
Skip nofEvents from the file.
Implements TRawFile.
Definition at line 357 of file TMidasFile.cxx.
References TRawFile::BufferData(), TRawFile::BufferSize(), TMidasEvent::Clear(), TRawFile::ClearBuffer(), fCurrentEventNumber, fDoByteSwap, TMidas_EVENT_HEADER::fEventId, fLastErrno, fLastError, TMidasEvent::GetDataSize(), TMidasEvent::GetEventHeader(), TRawFile::IncrementBytesRead(), TMidasEvent::IsGoodSize(), ReadMoreBytes(), and TMidasEvent::SwapBytesEventHeader().
Status()
std::string TMidasFile::Status (bool long_file_description = true) override virtual
Implements TRawFile.
Definition at line 56 of file TMidasFile.cxx.
References TRawFile::BytesRead(), fCurrentEventNumber, TRawFile::FileSize(), HIDE_CURSOR, and SHOW_CURSOR.
Write()
bool TMidasFile::Write (const std::shared_ptr< TMidasEvent > & midasEvent, Option_t * opt = "")
Write one event to the output file.
Definition at line 497 of file TMidasFile.cxx.
References fOutFile, and fOutGzFile.
Referenced by ProcessEvent().
WriteBuffer()
bool TMidasFile::WriteBuffer ()
Definition at line 477 of file TMidasFile.cxx.
References fCurrentBufferSize, fOutFile, fOutGzFile, and fWriteBuffer.
Referenced by FillBuffer(), OutClose(), and WriteEvents().
Member Data Documentation
fBytesRead
size_t TRawFile::fBytesRead {0} private inherited
Definition at line 87 of file TRawFile.h.
Referenced by TRawFile::BytesRead(), TRlmdFile::Close(), TRawFile::IncrementBytesRead(), TRlmdFile::Open(), TLstFile::Read(), TTdrFile::Read(), TRlmdFile::Read(), TTdrFile::Skip(), TLstFile::Status(), and TTdrFile::Status().
fCurrentBufferSize
uint32_t TMidasFile::fCurrentBufferSize {0} private
Definition at line 108 of file TMidasFile.h.
Referenced by FillBuffer(), and WriteBuffer().
fCurrentEventNumber
int TMidasFile::fCurrentEventNumber {0} private
Definition at line 113 of file TMidasFile.h.
Referenced by Read(), Skip(), and Status().
fDoByteSwap
bool TMidasFile::fDoByteSwap {false} private
"true" if file has to be byteswapped
Definition at line 115 of file TMidasFile.h.
Referenced by Read(), and Skip().
fFile
int TMidasFile::fFile {-1} private
open input file descriptor
Definition at line 117 of file TMidasFile.h.
Referenced by Close(), Open(), and ReadMoreBytes().
fFilename
std::string TRawFile::fFilename private inherited
name of the currently open file
Definition at line 83 of file TRawFile.h.
Referenced by TRawFile::Filename(), TRawFile::Filename(), TRawFile::GetFilename(), TRlmdFile::GetRunNumber(), TLstFile::GetRunNumber(), TTdrFile::GetRunNumber(), TTdrFile::GetSubRunNumber(), TRlmdFile::Open(), TLstFile::Open(), and TTdrFile::Open().
fFileSize
size_t TRawFile::fFileSize {0} private inherited
Definition at line 88 of file TRawFile.h.
Referenced by TRlmdFile::Close(), TRawFile::FileSize(), TRawFile::FileSize(), TRlmdFile::Open(), TLstFile::Open(), TTdrFile::Open(), TLstFile::Read(), TTdrFile::Read(), TRlmdFile::Read(), TTdrFile::Skip(), TRlmdFile::Status(), TLstFile::Status(), and TTdrFile::Status().
fGzFile
void* TMidasFile::fGzFile {nullptr} private
zlib compressed input file reader
Definition at line 118 of file TMidasFile.h.
Referenced by Close(), Open(), and ReadMoreBytes().
fLastErrno
int TMidasFile::fLastErrno {0} private
errno from the last operation
Definition at line 111 of file TMidasFile.h.
Referenced by GetLastErrno(), Open(), OutOpen(), Read(), ReadMoreBytes(), and Skip().
fLastError
std::string TMidasFile::fLastError private
error string from last errno
Definition at line 112 of file TMidasFile.h.
Referenced by TMidasFile(), GetLastError(), Open(), OutOpen(), Read(), ReadMoreBytes(), and Skip().
fMaxBufferSize
uint32_t TMidasFile::fMaxBufferSize {1000000} private
Definition at line 109 of file TMidasFile.h.
Referenced by FillBuffer(), and SetMaxBufferSize().
fOdb
TXMLOdb* TMidasFile::fOdb private
Definition at line 102 of file TMidasFile.h.
Referenced by SetEPICSOdb(), SetFileOdb(), SetGRIFFOdb(), SetRunInfo(), SetTIGDAQOdb(), and SetTIGOdb().
fOdbEvent
std::shared_ptr<TMidasEvent> TMidasFile::fOdbEvent private
Definition at line 98 of file TMidasFile.h.
Referenced by GetOdbEvent(), Open(), and SetFileOdb().
fOutFile
int TMidasFile::fOutFile {-1} private
open output file descriptor
Definition at line 120 of file TMidasFile.h.
Referenced by OutClose(), OutOpen(), Write(), and WriteBuffer().
fOutFilename
std::string TMidasFile::fOutFilename private
name of the currently open file
Definition at line 105 of file TMidasFile.h.
Referenced by OutClose(), and OutOpen().
fOutGzFile
void* TMidasFile::fOutGzFile {nullptr} private
zlib compressed output file reader
Definition at line 121 of file TMidasFile.h.
Referenced by OutClose(), OutOpen(), Write(), and WriteBuffer().
fPoFile
void* TMidasFile::fPoFile {nullptr} private
popen() input file reader
Definition at line 119 of file TMidasFile.h.
Referenced by Close(), and Open().
fReadBuffer
std::vector<char> TRawFile::fReadBuffer private inherited
Definition at line 85 of file TRawFile.h.
Referenced by TRawFile::BufferData(), TRawFile::BufferSize(), TRawFile::ClearBuffer(), TLstFile::Open(), TTdrFile::Open(), TLstFile::Read(), TTdrFile::Read(), TRlmdFile::Read(), and TRawFile::ResizeBuffer().
fWriteBuffer
std::vector<char> TMidasFile::fWriteBuffer private
Definition at line 107 of file TMidasFile.h.
Referenced by FillBuffer(), OutClose(), and WriteBuffer().