GRSISort: TParserLibrary Class Reference
TParserLibrary Class Reference
Detailed Description
Definition at line 10 of file TParserLibrary.h.
Public Member Functions
~TParserLibrary ()
TDataParser * CreateDataParser ()
TRawFile * CreateRawFile (const std::string &file)
void DestroyDataParser (TDataParser *parser)
void DestroyRawFile (TRawFile *file)
std::string LibraryVersion ()
void Load ()
Static Public Member Functions
static TParserLibrary * AddCurrent ()
static TParserLibrary * Get (bool verbose=false)
static TParserLibrary * GetAll ()
static void PrintDirectory ()
static void Set (TParserLibrary *val)
Private Member Functions
TParserLibrary ()=default
TParserLibrary (const TParserLibrary &)=default
TParserLibrary (TParserLibrary &&) noexcept=default
TParserLibrary & operator= (const TParserLibrary &)=default
TParserLibrary & operator= (TParserLibrary &&) noexcept=default
Private Attributes
TDataParser *(* fCreateDataParser)()
TRawFile *(* fCreateRawFile)(const std::string &)
void(* fDestroyDataParser)(TDataParser *)
void(* fDestroyRawFile)(TRawFile *)
void * fHandle {nullptr}
void(* fInitLibrary)()
std::string(* fLibraryVersion)()
Static Private Attributes
static TDirectory * fDir
static TParserLibrary * fSingleton
Friends
class TSingleton< TParserLibrary >
Constructor & Destructor Documentation
~TParserLibrary()
TParserLibrary::~TParserLibrary ()
Definition at line 14 of file TParserLibrary.cxx.
References fHandle.
TParserLibrary() [1/3]
TParserLibrary::TParserLibrary () private default
TParserLibrary() [2/3]
TParserLibrary::TParserLibrary (const TParserLibrary &) private default
TParserLibrary() [3/3]
TParserLibrary::TParserLibrary (TParserLibrary &&) private default noexcept
Member Function Documentation
AddCurrent()
static TParserLibrary * TSingleton< TParserLibrary >::AddCurrent () inline static inherited
Definition at line 141 of file TSingleton.h.
CreateDataParser()
TDataParser * TParserLibrary::CreateDataParser () inline
function to open library specific data parser
Definition at line 31 of file TParserLibrary.h.
References fCreateDataParser, and Load().
Referenced by TUnpackingLoop::TUnpackingLoop().
CreateRawFile()
TRawFile * TParserLibrary::CreateRawFile (const std::string & file) inline
function to open library specific raw data file
Definition at line 18 of file TParserLibrary.h.
References fCreateRawFile, and Load().
Referenced by TGRSIint::OpenRawFile().
DestroyDataParser()
void TParserLibrary::DestroyDataParser (TDataParser * parser) inline
function to destroy library specific data parser
Definition at line 37 of file TParserLibrary.h.
References fDestroyDataParser, and Load().
DestroyRawFile()
void TParserLibrary::DestroyRawFile (TRawFile * file) inline
function to destroy library specific raw data file
Definition at line 24 of file TParserLibrary.h.
References fDestroyRawFile, and Load().
Get()
static TParserLibrary * TSingleton< TParserLibrary >::Get (bool verbose = false) inline static inherited
Definition at line 33 of file TSingleton.h.
GetAll()
static TParserLibrary * TSingleton< TParserLibrary >::GetAll () inline static inherited
Definition at line 66 of file TSingleton.h.
LibraryVersion()
std::string TParserLibrary::LibraryVersion () inline
returns version of shared object library loaded
Definition at line 44 of file TParserLibrary.h.
References fLibraryVersion, and Load().
Load()
void TParserLibrary::Load ()
if necessary loads shared object library and sets/initializes all other functions
Definition at line 21 of file TParserLibrary.cxx.
References dlsym, DRED, fCreateDataParser, fCreateRawFile, fDestroyDataParser, fDestroyRawFile, fHandle, file_exists(), fInitLibrary, fLibraryVersion, TGRSIOptions::Get(), TGRSIOptions::ParserLibrary(), RESET_COLOR, TRunInfo::SetLibraryPath(), and TRunInfo::SetLibraryVersion().
Referenced by TGRSIint::ApplyOptions(), CreateDataParser(), CreateRawFile(), DestroyDataParser(), DestroyRawFile(), LibraryVersion(), TGRSIProof::LoadLibsIntoProof(), and TGRSISelector::SlaveBegin().
operator=() [1/2]
TParserLibrary & TParserLibrary::operator= (const TParserLibrary &) private default
operator=() [2/2]
TParserLibrary & TParserLibrary::operator= (TParserLibrary &&) private default noexcept
PrintDirectory()
static void TSingleton< TParserLibrary >::PrintDirectory () inline static inherited
Definition at line 171 of file TSingleton.h.
Set()
static void TSingleton< TParserLibrary >::Set (TParserLibrary * val) inline static inherited
Definition at line 133 of file TSingleton.h.
Friends And Related Symbol Documentation
TSingleton< TParserLibrary >
friend class TSingleton< TParserLibrary > friend
Definition at line 1 of file TParserLibrary.h.
Member Data Documentation
fCreateDataParser
TDataParser *(* TParserLibrary::fCreateDataParser) () private
Definition at line 66 of file TParserLibrary.h.
Referenced by CreateDataParser(), and Load().
fCreateRawFile
TRawFile *(* TParserLibrary::fCreateRawFile) (const std::string &) private
Definition at line 63 of file TParserLibrary.h.
Referenced by CreateRawFile(), and Load().
fDestroyDataParser
void(* TParserLibrary::fDestroyDataParser) (TDataParser *) private
Definition at line 67 of file TParserLibrary.h.
Referenced by DestroyDataParser(), and Load().
fDestroyRawFile
void(* TParserLibrary::fDestroyRawFile) (TRawFile *) private
Definition at line 64 of file TParserLibrary.h.
Referenced by DestroyRawFile(), and Load().
fDir
TDirectory * TSingleton< TParserLibrary >::fDir static private inherited
Definition at line 187 of file TSingleton.h.
fHandle
void* TParserLibrary::fHandle {nullptr} private
handle for shared object library
Definition at line 58 of file TParserLibrary.h.
Referenced by ~TParserLibrary(), and Load().
fInitLibrary
void(* TParserLibrary::fInitLibrary) () private
Definition at line 60 of file TParserLibrary.h.
Referenced by Load().
fLibraryVersion
std::string(* TParserLibrary::fLibraryVersion) () private
Definition at line 61 of file TParserLibrary.h.
Referenced by LibraryVersion(), and Load().
fSingleton
TParserLibrary * TSingleton< TParserLibrary >::fSingleton static private inherited
Definition at line 186 of file TSingleton.h.