GRSISort: TILLMnemonic Class Reference
TILLMnemonic Class Reference
Definition at line 11 of file TILLMnemonic.h.
Public Types
enum class EMnemonic {
kA , kB , kC , kD ,
kE , kF , kG , kH ,
kI , kJ , kK , kL ,
kM , kN , kO , kP ,
kQ , kR , kS , kT ,
kU , kV , kW , kX ,
kY , kZ , kClear
}
enum class ESystem {
kFipps , kFippsBgo , kFippsLaBr , kFippsLaBrBgo ,
kFippsTAC , kFippsPulser , kIfin , kIfinBgo ,
kClear
}
Public Member Functions
TILLMnemonic ()
TILLMnemonic (const char *name)
~TILLMnemonic () override=default
virtual int16_t ArrayPosition () const
virtual EMnemonic ArraySubPosition () const
virtual std::string ArraySubPositionString () const
void Clear (Option_t *opt="") override
virtual EMnemonic CollectedCharge () const
virtual std::string CollectedChargeString () const
void EnumerateDigitizer (TPriorityValue< std::string > &digitizerName, TPriorityValue< EDigitizer > &digitizerType, TPriorityValue< int > &timeStampUnit) override
TClass * GetClassType () const override
const char * GetName () const override
double GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel *channel) const override
virtual int NumericArraySubPosition () const
virtual EMnemonic OutputSensor () const
virtual std::string OutputSensorString () const
virtual void Parse (const char *name)
void Parse (std::string *name) override
void Print (Option_t *opt="") const override
virtual int16_t Segment () const
virtual void SetClassType (TClass *classType)
void SetName (const char *val)
void SetName (const std::string &val)
virtual void SetRFMnemonic (std::string *name)
virtual EMnemonic SubSystem () const
virtual std::string SubSystemString () const
ESystem System () const
virtual std::string SystemString () const
Protected Member Functions
void EnumerateMnemonic (std::string mnemonic_word, EMnemonic &mnemonic_enum)
Protected Attributes
int16_t fArrayPosition
EMnemonic fArraySubPosition
std::string fArraySubPositionString
TClass * fClassType
EMnemonic fCollectedCharge
std::string fCollectedChargeString
std::string fName
EMnemonic fOutputSensor
std::string fOutputSensorString
int16_t fSegment
EMnemonic fSubSystem
std::string fSubSystemString
std::string fSystemString
Static Protected Attributes
static bool fPrint = true
Private Member Functions
void EnumerateSystem ()
Private Attributes
ESystem fSystem
#include <TILLMnemonic.h>
Member Enumeration Documentation
EMnemonic
enum class TMnemonic::EMnemonic strong inherited
Enumerator
kA
kB
kC
kD
kE
kF
kG
kH
kI
kJ
kK
kL
kM
kN
kO
kP
kQ
kR
kS
kT
kU
kV
kW
kX
kY
kZ
kClear
Definition at line 27 of file TMnemonic.h.
ESystem
enum class TILLMnemonic::ESystem strong
Enumerator
kFipps
kFippsBgo
kFippsLaBr
kFippsLaBrBgo
kFippsTAC
kFippsPulser
kIfin
kIfinBgo
kClear
Definition at line 20 of file TILLMnemonic.h.
Constructor & Destructor Documentation
TILLMnemonic() [1/2]
TILLMnemonic::TILLMnemonic () inline
Definition at line 13 of file TILLMnemonic.h.
References Clear().
TILLMnemonic() [2/2]
TILLMnemonic::TILLMnemonic (const char * name) inline
Definition at line 14 of file TILLMnemonic.h.
References TMnemonic::Parse().
~TILLMnemonic()
TILLMnemonic::~TILLMnemonic () override default
Member Function Documentation
ArrayPosition()
virtual int16_t TMnemonic::ArrayPosition () const inline virtual inherited
Definition at line 34 of file TMnemonic.h.
References TMnemonic::fArrayPosition.
Referenced by TCSM::AddFragment(), TS3Hit::GetArrayPosition(), TChannel::GetDetectorNumber(), and TTipHit::SetUpNumbering().
ArraySubPosition()
virtual EMnemonic TMnemonic::ArraySubPosition () const inline virtual inherited
Definition at line 30 of file TMnemonic.h.
References TMnemonic::fArraySubPosition.
Referenced by TSharc::AddFragment(), and TTrific::AddFragment().
ArraySubPositionString()
virtual std::string TMnemonic::ArraySubPositionString () const inline virtual inherited
Definition at line 39 of file TMnemonic.h.
References TMnemonic::fArraySubPositionString.
Referenced by TCSM::AddFragment(), TS3Hit::GetDistanceStr(), and TTipHit::SetUpNumbering().
Clear()
void TILLMnemonic::Clear (Option_t * opt = "") override virtual
Reimplemented from TMnemonic.
Referenced by TILLMnemonic().
CollectedCharge()
virtual EMnemonic TMnemonic::CollectedCharge () const inline virtual inherited
Definition at line 32 of file TMnemonic.h.
References TMnemonic::fCollectedCharge.
Referenced by TEmma::AddFragment(), TS3::AddFragment(), and TSharc::AddFragment().
CollectedChargeString()
virtual std::string TMnemonic::CollectedChargeString () const inline virtual inherited
Definition at line 40 of file TMnemonic.h.
References TMnemonic::fCollectedChargeString.
Referenced by TCSM::AddFragment().
EnumerateDigitizer()
void TILLMnemonic::EnumerateDigitizer (TPriorityValue< std::string > & digitizerName, TPriorityValue< EDigitizer > & digitizerType, TPriorityValue< int > & timeStampUnit) override virtual
Reimplemented from TMnemonic.
Definition at line 54 of file TILLMnemonic.cxx.
References kDefault, kV1724, kV1725, kV1730, kV1751, TPriorityValue< T >::Priority(), TPriorityValue< T >::Set(), and TPriorityValue< T >::Value().
EnumerateMnemonic()
void TMnemonic::EnumerateMnemonic (std::string mnemonic_word, EMnemonic & mnemonic_enum) protected inherited
Definition at line 27 of file TMnemonic.cxx.
References TMnemonic::kA, TMnemonic::kB, TMnemonic::kC, TMnemonic::kClear, TMnemonic::kD, TMnemonic::kE, TMnemonic::kF, TMnemonic::kG, TMnemonic::kH, TMnemonic::kI, TMnemonic::kJ, TMnemonic::kK, TMnemonic::kL, TMnemonic::kM, TMnemonic::kN, TMnemonic::kO, TMnemonic::kP, TMnemonic::kQ, TMnemonic::kR, TMnemonic::kS, TMnemonic::kT, TMnemonic::kU, TMnemonic::kV, TMnemonic::kW, TMnemonic::kX, TMnemonic::kY, and TMnemonic::kZ.
Referenced by TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
EnumerateSystem()
void TILLMnemonic::EnumerateSystem () private
Definition at line 23 of file TILLMnemonic.cxx.
References fSystem, TMnemonic::fSystemString, kClear, kFipps, kFippsBgo, kFippsLaBr, kFippsLaBrBgo, kFippsPulser, kFippsTAC, kIfin, kIfinBgo, TMnemonic::kS, TMnemonic::kT, and TMnemonic::SubSystem().
Referenced by Parse().
GetClassType()
TClass * TILLMnemonic::GetClassType () const override virtual
Reimplemented from TMnemonic.
Definition at line 103 of file TILLMnemonic.cxx.
References TMnemonic::fClassType, kFipps, kFippsBgo, kFippsLaBr, kFippsLaBrBgo, kFippsPulser, kFippsTAC, kIfin, kIfinBgo, and System().
GetName()
const char * TMnemonic::GetName () const inline override inherited
Definition at line 60 of file TMnemonic.h.
References TMnemonic::fName.
GetTime()
double TILLMnemonic::GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel * channel) const override virtual
Reimplemented from TMnemonic.
Definition at line 123 of file TILLMnemonic.cxx.
References TChannel::CalibrateCFD(), TChannel::GetTimeOffset(), TChannel::GetTimeStampUnit(), and TChannel::GetTZero().
NumericArraySubPosition()
int TMnemonic::NumericArraySubPosition () const virtual inherited
Reimplemented in TGRSIMnemonic.
Definition at line 130 of file TMnemonic.cxx.
References TMnemonic::fArraySubPosition, TMnemonic::kB, TMnemonic::kG, TMnemonic::kR, and TMnemonic::kW.
Referenced by TChannel::GetCrystalNumber().
OutputSensor()
virtual EMnemonic TMnemonic::OutputSensor () const inline virtual inherited
Definition at line 33 of file TMnemonic.h.
References TMnemonic::fOutputSensor.
Referenced by TEmma::AddFragment(), TGriffin::AddFragment(), and TTigress::AddFragment().
OutputSensorString()
virtual std::string TMnemonic::OutputSensorString () const inline virtual inherited
Definition at line 41 of file TMnemonic.h.
References TMnemonic::fOutputSensorString.
Parse() [1/2]
void TMnemonic::Parse (const char * name) virtual inherited
Definition at line 96 of file TMnemonic.cxx.
References TMnemonic::Parse().
Parse() [2/2]
void TILLMnemonic::Parse (std::string * name) override virtual
Reimplemented from TMnemonic.
Definition at line 79 of file TILLMnemonic.cxx.
References EnumerateSystem(), and TMnemonic::Parse().
Print()
void TILLMnemonic::Print (Option_t * opt = "") const override virtual
Reimplemented from TMnemonic.
Definition at line 90 of file TILLMnemonic.cxx.
References TMnemonic::fArrayPosition, TMnemonic::fArraySubPositionString, TMnemonic::fCollectedChargeString, TMnemonic::fOutputSensorString, TMnemonic::fSegment, TMnemonic::fSubSystemString, and TMnemonic::fSystemString.
Segment()
virtual int16_t TMnemonic::Segment () const inline virtual inherited
Definition at line 35 of file TMnemonic.h.
References TMnemonic::fSegment.
Referenced by TChannel::GetSegmentNumber().
SetClassType()
virtual void TMnemonic::SetClassType (TClass * classType) inline virtual inherited
Definition at line 50 of file TMnemonic.h.
References TMnemonic::fClassType.
Referenced by TChannel::SetClassType().
SetName() [1/2]
void TMnemonic::SetName (const char * val) inline inherited
Definition at line 58 of file TMnemonic.h.
References TMnemonic::fName.
Referenced by TMnemonic::Parse().
SetName() [2/2]
void TMnemonic::SetName (const std::string & val) inline inherited
Definition at line 59 of file TMnemonic.h.
References TMnemonic::fName.
SetRFMnemonic()
void TMnemonic::SetRFMnemonic (std::string * name) virtual inherited
Definition at line 102 of file TMnemonic.cxx.
References TMnemonic::EnumerateMnemonic(), TMnemonic::fArrayPosition, TMnemonic::fArraySubPosition, TMnemonic::fArraySubPositionString, TMnemonic::fCollectedCharge, TMnemonic::fCollectedChargeString, TMnemonic::fOutputSensor, TMnemonic::fOutputSensorString, TMnemonic::fSegment, TMnemonic::fSubSystem, TMnemonic::fSubSystemString, and TMnemonic::fSystemString.
Referenced by TMnemonic::Parse(), and TGRSIMnemonic::Parse().
SubSystem()
virtual EMnemonic TMnemonic::SubSystem () const inline virtual inherited
Definition at line 29 of file TMnemonic.h.
References TMnemonic::fSubSystem.
Referenced by TEmma::AddFragment(), TGriffin::AddFragment(), TTigress::AddFragment(), TFipps::AddFragment(), TIfin::AddFragment(), TGRSIMnemonic::EnumerateSystem(), EnumerateSystem(), and TTdrMnemonic::EnumerateSystem().
SubSystemString()
virtual std::string TMnemonic::SubSystemString () const inline virtual inherited
Definition at line 38 of file TMnemonic.h.
References TMnemonic::fSubSystemString.
Referenced by TTipHit::SetUpNumbering().
System()
ESystem TILLMnemonic::System () const inline
Definition at line 32 of file TILLMnemonic.h.
References fSystem.
Referenced by GetClassType(), and TILLDetectorInformation::Set().
SystemString()
virtual std::string TMnemonic::SystemString () const inline virtual inherited
Definition at line 37 of file TMnemonic.h.
References TMnemonic::fSystemString.
Member Data Documentation
fArrayPosition
int16_t TMnemonic::fArrayPosition protected inherited
Definition at line 64 of file TMnemonic.h.
Referenced by TMnemonic::ArrayPosition(), TMnemonic::Clear(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), and TMnemonic::SetRFMnemonic().
fArraySubPosition
EMnemonic TMnemonic::fArraySubPosition protected inherited
Definition at line 73 of file TMnemonic.h.
Referenced by TMnemonic::ArraySubPosition(), TMnemonic::Clear(), TMnemonic::NumericArraySubPosition(), TGRSIMnemonic::NumericArraySubPosition(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fArraySubPositionString
std::string TMnemonic::fArraySubPositionString protected inherited
Definition at line 68 of file TMnemonic.h.
Referenced by TMnemonic::ArraySubPositionString(), TMnemonic::Clear(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), and TMnemonic::SetRFMnemonic().
fClassType
TClass* TMnemonic::fClassType mutable protected inherited
! TGRSIDetector Type that this mnemonic represents
Definition at line 77 of file TMnemonic.h.
Referenced by TMnemonic::GetClassType(), TGRSIMnemonic::GetClassType(), THILMnemonic::GetClassType(), GetClassType(), TTdrMnemonic::GetClassType(), and TMnemonic::SetClassType().
fCollectedCharge
EMnemonic TMnemonic::fCollectedCharge protected inherited
Definition at line 74 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::CollectedCharge(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fCollectedChargeString
std::string TMnemonic::fCollectedChargeString protected inherited
Definition at line 69 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::CollectedChargeString(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), and TMnemonic::SetRFMnemonic().
fName
std::string TMnemonic::fName protected inherited
Definition at line 63 of file TMnemonic.h.
Referenced by TMnemonic::GetName(), TMnemonic::SetName(), and TMnemonic::SetName().
fOutputSensor
EMnemonic TMnemonic::fOutputSensor protected inherited
Definition at line 75 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::OutputSensor(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fOutputSensorString
std::string TMnemonic::fOutputSensorString protected inherited
Definition at line 70 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::OutputSensorString(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), and TMnemonic::SetRFMnemonic().
fPrint
bool TMnemonic::fPrint = true static protected inherited
Definition at line 81 of file TMnemonic.h.
Referenced by TMnemonic::EnumerateDigitizer().
fSegment
int16_t TMnemonic::fSegment protected inherited
Definition at line 65 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), TGRSIMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), TMnemonic::Segment(), and TMnemonic::SetRFMnemonic().
fSubSystem
EMnemonic TMnemonic::fSubSystem protected inherited
Definition at line 72 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), TMnemonic::SetRFMnemonic(), and TMnemonic::SubSystem().
fSubSystemString
std::string TMnemonic::fSubSystemString protected inherited
Definition at line 67 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), TMnemonic::SetRFMnemonic(), and TMnemonic::SubSystemString().
fSystem
ESystem TILLMnemonic::fSystem private
Definition at line 46 of file TILLMnemonic.h.
Referenced by ClassImp(), EnumerateSystem(), and System().
fSystemString
std::string TMnemonic::fSystemString protected inherited
Definition at line 66 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TGRSIMnemonic::EnumerateSystem(), THILMnemonic::EnumerateSystem(), EnumerateSystem(), TTdrMnemonic::EnumerateSystem(), TMnemonic::Parse(), TGRSIMnemonic::Print(), THILMnemonic::Print(), Print(), TMnemonic::Print(), TTdrMnemonic::Print(), TMnemonic::SetRFMnemonic(), and TMnemonic::SystemString().