GRSISort: TTdrTigress Class Reference
TTdrTigress Class Reference
Detectors
Detailed Description
Definition at line 26 of file TTdrTigress.h.
Public Types
enum class ETdrTigressBits {
kIsAddbackSet = 1 << 0 , kIsCrossTalkSet = 1 << 1 , kIsSuppressedSet = 1 << 2 , kIsSupprAddbSet = 1 << 3 ,
kBit4 = 1 << 4 , kBit5 = 1 << 5 , kBit6 = 1 << 6 , kBit7 = 1 << 7
}
Public Member Functions
TTdrTigress ()
TTdrTigress (const TTdrTigress &)
~TTdrTigress () override
virtual bool AddbackCriterion (const TDetectorHit *, const TDetectorHit *)
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
virtual void BuildHits ()
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> GetAddbackCriterion () const
TDetectorHit * GetAddbackHit (const int &i)
Int_t GetAddbackMultiplicity ()
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
UShort_t GetNAddbackFrags (const size_t &idx)
UShort_t GetNSuppressedAddbackFrags (const size_t &idx)
TDetectorHit * GetSuppressedAddbackHit (const int &i)
Int_t GetSuppressedAddbackMultiplicity (TBgo *)
TDetectorHit * GetSuppressedHit (const int &i)
Int_t GetSuppressedMultiplicity (TBgo *)
std::function< bool(TTdrTigressHit *, TBgoHit *)> GetSuppressionCriterion () const
TDetectorHit * GetTdrTigressHit (const Int_t &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
bool IsAddbackSet () const
bool IsSuppressedAddbackSet () const
bool IsSuppressedSet () const
virtual bool NoHits () const
TTdrTigress & operator= (const TTdrTigress &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void ResetAddback ()
void ResetFlags () const
void ResetSuppressed ()
void ResetSuppressedAddback ()
void SetAddbackCriterion (std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> criterion)
void SetSuppressionCriterion (std::function< bool(TTdrTigressHit *, TBgoHit *)> criterion)
virtual bool SuppressionCriterion (const TDetectorHit *, const TDetectorHit *)
Static Public Member Functions
static const char * GetColorFromNumber (Int_t number)
static TVector3 GetPosition (int DetNbr, int CryNbr=5, double dist=110.0)
static bool SetCoreWave ()
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Private Member Functions
void ClearStatus () const
std::vector< UShort_t > & GetAddbackFragVector ()
std::vector< TDetectorHit * > & GetAddbackVector ()
std::vector< UShort_t > & GetSuppressedAddbackFragVector ()
std::vector< TDetectorHit * > & GetSuppressedAddbackVector ()
std::vector< TDetectorHit * > & GetSuppressedVector ()
void SetAddback (bool flag=true) const
void SetBitNumber (ETdrTigressBits bit, Bool_t set) const
void SetSuppressed (bool flag=true) const
void SetSuppressedAddback (bool flag=true) const
Bool_t TestBitNumber (ETdrTigressBits bit) const
Private Attributes
std::vector< UShort_t > fAddbackFrags
std::vector< TDetectorHit * > fAddbackHits
long fCycleStart
std::vector< TDetectorHit * > fHits
std::vector< UShort_t > fSuppressedAddbackFrags
std::vector< TDetectorHit * > fSuppressedAddbackHits
std::vector< TDetectorHit * > fSuppressedHits
TTransientBits< UChar_t > fTdrTigressBits
Static Private Attributes
static std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> fAddbackCriterion = DefaultAddback
static std::map< int, TSpline * > fEnergyResiduals
static bool fSetCoreWave = false
static std::function< bool(TTdrTigressHit *, TBgoHit *)> fSuppressionCriterion = DefaultSuppression
static TVector3 gTigressPosition [17]
Member Enumeration Documentation
ETdrTigressBits
enum class TTdrTigress::ETdrTigressBits strong
Enumerator
kIsAddbackSet
kIsCrossTalkSet
kIsSuppressedSet
kIsSupprAddbSet
kBit4
kBit5
kBit6
kBit7
Definition at line 28 of file TTdrTigress.h.
Constructor & Destructor Documentation
TTdrTigress() [1/2]
TTdrTigress::TTdrTigress ()
Definition at line 114 of file TTdrTigress.cxx.
References Clear().
TTdrTigress() [2/2]
TTdrTigress::TTdrTigress (const TTdrTigress & rhs)
Definition at line 123 of file TTdrTigress.cxx.
References Copy().
~TTdrTigress()
TTdrTigress::~TTdrTigress () override
Definition at line 147 of file TTdrTigress.cxx.
Member Function Documentation
AddbackCriterion()
virtual bool TSuppressed::AddbackCriterion (const TDetectorHit * , const TDetectorHit *) inline virtual inherited
Reimplemented in TFipps, TGriffin, and TIfin.
Definition at line 30 of file TSuppressed.h.
Referenced by TSuppressed::CreateAddback(), and TSuppressed::CreateSuppressedAddback().
AddFragment()
void TTdrTigress::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 363 of file TTdrTigress.cxx.
References TDetector::Hits().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
virtual void TDetector::BuildHits () inline virtual inherited
!
Reimplemented in TAries, TBgo, TCSM, TDemand, TDescant, TEagle, TEaglePulser, TEmma, TFipps, TFippsLaBr, TFippsPulser, TFippsTAC, TGenericDetector, TGriffin, TIfin, TLaBr, TPaces, TRcmp, TRF, TS3, TSceptar, TSharc2, TSharc, TSiLi, TTAC, TTigress, TTip, TTrific, TTriFoil, and TZeroDegree.
Definition at line 55 of file TDetector.h.
Clear()
void TTdrTigress::Clear (Option_t * opt = "all") override
!
Definition at line 152 of file TTdrTigress.cxx.
References TSuppressed::Clear(), ClearStatus(), fAddbackFrags, fAddbackHits, fCycleStart, fSuppressedAddbackFrags, fSuppressedAddbackHits, and fSuppressedHits.
Referenced by TTdrTigress().
ClearStatus()
void TTdrTigress::ClearStatus () const inline private
!
Definition at line 106 of file TTdrTigress.h.
References fTdrTigressBits.
Referenced by Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TTdrTigress::Copy (TObject & rhs) const override
!
Definition at line 132 of file TTdrTigress.cxx.
References TSuppressed::Copy(), fAddbackFrags, fAddbackHits, fCycleStart, fSetCoreWave, fSuppressedAddbackFrags, fSuppressedAddbackHits, fSuppressedHits, and fTdrTigressBits.
Referenced by TTdrTigress(), and operator=().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 38 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by TFipps::GetAddbackMultiplicity(), TGriffin::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), and GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected inherited
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 69 of file TSuppressed.h.
References TDetector::GetHitVector(), and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), and GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 94 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetector::GetHitVector(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), and GetSuppressedAddbackMultiplicity().
GetAddbackCriterion()
std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> TTdrTigress::GetAddbackCriterion () const inline
Definition at line 60 of file TTdrTigress.h.
References fAddbackCriterion.
GetAddbackFragVector()
std::vector< UShort_t > & TTdrTigress::GetAddbackFragVector () private
!
Definition at line 212 of file TTdrTigress.cxx.
References fAddbackFrags.
Referenced by GetAddbackMultiplicity(), GetNAddbackFrags(), and ResetAddback().
GetAddbackHit()
TDetectorHit * TTdrTigress::GetAddbackHit (const int & i)
Definition at line 285 of file TTdrTigress.cxx.
References GetAddbackMultiplicity(), and GetAddbackVector().
GetAddbackMultiplicity()
Int_t TTdrTigress::GetAddbackMultiplicity ()
Definition at line 262 of file TTdrTigress.cxx.
References TSuppressed::CreateAddback(), GetAddbackFragVector(), GetAddbackVector(), TDetector::GetHitVector(), IsAddbackSet(), and SetAddback().
Referenced by GetAddbackHit().
GetAddbackVector()
std::vector< TDetectorHit * > & TTdrTigress::GetAddbackVector () private
!
Definition at line 207 of file TTdrTigress.cxx.
References fAddbackHits.
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), and ResetAddback().
GetColorFromNumber()
const char * TTdrTigress::GetColorFromNumber (Int_t number) static
Definition at line 458 of file TTdrTigress.cxx.
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetNAddbackFrags()
UShort_t TTdrTigress::GetNAddbackFrags (const size_t & idx)
Definition at line 419 of file TTdrTigress.cxx.
References GetAddbackFragVector().
GetNSuppressedAddbackFrags()
UShort_t TTdrTigress::GetNSuppressedAddbackFrags (const size_t & idx)
Definition at line 442 of file TTdrTigress.cxx.
References GetSuppressedAddbackFragVector().
GetPosition()
TVector3 TTdrTigress::GetPosition (int DetNbr, int CryNbr = 5, double dist = 110.0) static
!
Definition at line 375 of file TTdrTigress.cxx.
References gTigressPosition.
Referenced by TTdrTigressHit::GetPosition().
GetSuppressedAddbackFragVector()
std::vector< UShort_t > & TTdrTigress::GetSuppressedAddbackFragVector () private
!
Definition at line 247 of file TTdrTigress.cxx.
References fSuppressedAddbackFrags.
Referenced by GetNSuppressedAddbackFrags(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedAddbackHit()
TDetectorHit * TTdrTigress::GetSuppressedAddbackHit (const int & i)
Definition at line 350 of file TTdrTigress.cxx.
References GetSuppressedAddbackVector().
GetSuppressedAddbackMultiplicity()
Int_t TTdrTigress::GetSuppressedAddbackMultiplicity (TBgo * bgo)
Definition at line 327 of file TTdrTigress.cxx.
References TSuppressed::CreateSuppressedAddback(), TDetector::GetHitVector(), GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), IsSuppressedAddbackSet(), and SetSuppressedAddback().
GetSuppressedAddbackVector()
std::vector< TDetectorHit * > & TTdrTigress::GetSuppressedAddbackVector () private
!
Definition at line 242 of file TTdrTigress.cxx.
References fSuppressedAddbackHits.
Referenced by GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedHit()
TDetectorHit * TTdrTigress::GetSuppressedHit (const int & i)
Definition at line 314 of file TTdrTigress.cxx.
References GetSuppressedVector().
GetSuppressedMultiplicity()
Int_t TTdrTigress::GetSuppressedMultiplicity (TBgo * bgo)
Definition at line 295 of file TTdrTigress.cxx.
References TSuppressed::CreateSuppressed(), fSuppressedHits, TDetector::Hits(), IsSuppressedSet(), and SetSuppressed().
GetSuppressedVector()
std::vector< TDetectorHit * > & TTdrTigress::GetSuppressedVector () private
!
Definition at line 227 of file TTdrTigress.cxx.
References fSuppressedHits.
Referenced by GetSuppressedHit(), and ResetSuppressed().
GetSuppressionCriterion()
std::function< bool(TTdrTigressHit *, TBgoHit *)> TTdrTigress::GetSuppressionCriterion () const inline
Definition at line 65 of file TTdrTigress.h.
References fSuppressionCriterion.
GetTdrTigressHit()
TDetectorHit * TTdrTigress::GetTdrTigressHit (const Int_t & i) const inline
Definition at line 44 of file TTdrTigress.h.
References TDetector::GetHit().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
IsAddbackSet()
bool TTdrTigress::IsAddbackSet () const
Definition at line 217 of file TTdrTigress.cxx.
References kIsAddbackSet, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), and Print().
IsSuppressedAddbackSet()
bool TTdrTigress::IsSuppressedAddbackSet () const
Definition at line 252 of file TTdrTigress.cxx.
References kIsSupprAddbSet, and TestBitNumber().
Referenced by GetSuppressedAddbackMultiplicity(), and Print().
IsSuppressedSet()
bool TTdrTigress::IsSuppressedSet () const
Definition at line 232 of file TTdrTigress.cxx.
References kIsSuppressedSet, and TestBitNumber().
Referenced by GetSuppressedMultiplicity(), and Print().
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=()
TTdrTigress & TTdrTigress::operator= (const TTdrTigress & rhs)
!
Definition at line 201 of file TTdrTigress.cxx.
References Copy().
Print() [1/2]
void TTdrTigress::Print (Option_t * opt = "") const override
!
Definition at line 165 of file TTdrTigress.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TTdrTigress::Print (std::ostream & out) const override virtual
Reimplemented from TDetector.
Definition at line 170 of file TTdrTigress.cxx.
References fAddbackHits, fCycleStart, fSuppressedAddbackHits, fSuppressedHits, TDetector::GetMultiplicity(), IsAddbackSet(), IsSuppressedAddbackSet(), and IsSuppressedSet().
ResetAddback()
void TTdrTigress::ResetAddback ()
Definition at line 412 of file TTdrTigress.cxx.
References GetAddbackFragVector(), GetAddbackVector(), and SetAddback().
ResetFlags()
void TTdrTigress::ResetFlags () const
Definition at line 407 of file TTdrTigress.cxx.
References fTdrTigressBits.
ResetSuppressed()
void TTdrTigress::ResetSuppressed ()
Definition at line 429 of file TTdrTigress.cxx.
References GetSuppressedVector(), and SetSuppressed().
ResetSuppressedAddback()
void TTdrTigress::ResetSuppressedAddback ()
Definition at line 435 of file TTdrTigress.cxx.
References GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), and SetSuppressedAddback().
SetAddback()
void TTdrTigress::SetAddback (bool flag = true) const private
Definition at line 222 of file TTdrTigress.cxx.
References kIsAddbackSet, and SetBitNumber().
Referenced by GetAddbackMultiplicity(), and ResetAddback().
SetAddbackCriterion()
void TTdrTigress::SetAddbackCriterion (std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> criterion) inline
Definition at line 56 of file TTdrTigress.h.
SetBitNumber()
void TTdrTigress::SetBitNumber (ETdrTigressBits bit, Bool_t set) const private
Definition at line 452 of file TTdrTigress.cxx.
References fTdrTigressBits, and TTransientBits< T >::SetBit().
Referenced by SetAddback(), SetSuppressed(), and SetSuppressedAddback().
SetCoreWave()
static bool TTdrTigress::SetCoreWave () inline static
!
Definition at line 101 of file TTdrTigress.h.
References fSetCoreWave.
SetSuppressed()
void TTdrTigress::SetSuppressed (bool flag = true) const private
Definition at line 237 of file TTdrTigress.cxx.
References kIsSuppressedSet, and SetBitNumber().
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
SetSuppressedAddback()
void TTdrTigress::SetSuppressedAddback (bool flag = true) const private
Definition at line 257 of file TTdrTigress.cxx.
References kIsSupprAddbSet, and SetBitNumber().
Referenced by GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
SetSuppressionCriterion()
void TTdrTigress::SetSuppressionCriterion (std::function< bool(TTdrTigressHit *, TBgoHit *)> criterion) inline
Definition at line 61 of file TTdrTigress.h.
References fSuppressionCriterion.
SuppressionCriterion()
virtual bool TSuppressed::SuppressionCriterion (const TDetectorHit * , const TDetectorHit *) inline virtual inherited
Reimplemented in TFipps, TFippsLaBr, TGriffin, TIfin, and TLaBr.
Definition at line 31 of file TSuppressed.h.
Referenced by TSuppressed::CreateSuppressed(), and TSuppressed::CreateSuppressedAddback().
TestBitNumber()
Bool_t TTdrTigress::TestBitNumber (ETdrTigressBits bit) const inline private
Definition at line 108 of file TTdrTigress.h.
References fTdrTigressBits, and TTransientBits< T >::TestBit().
Referenced by IsAddbackSet(), IsSuppressedAddbackSet(), and IsSuppressedSet().
Member Data Documentation
fAddbackCriterion
std::function< bool(TTdrTigressHit *, TTdrTigressHit *)> TTdrTigress::fAddbackCriterion = DefaultAddback static private
Definition at line 87 of file TTdrTigress.h.
Referenced by GetAddbackCriterion().
fAddbackFrags
std::vector<UShort_t> TTdrTigress::fAddbackFrags mutable private
! Number of crystals involved in creating in the addback hit
Definition at line 95 of file TTdrTigress.h.
Referenced by Clear(), Copy(), and GetAddbackFragVector().
fAddbackHits
std::vector<TDetectorHit*> TTdrTigress::fAddbackHits mutable private
! Used to create addback hits on the fly
Definition at line 94 of file TTdrTigress.h.
Referenced by Clear(), Copy(), GetAddbackVector(), and Print().
fCycleStart
long TTdrTigress::fCycleStart private
! The start of the cycle
Definition at line 92 of file TTdrTigress.h.
Referenced by Clear(), Copy(), and Print().
fEnergyResiduals
std::map< int, TSpline * > TTdrTigress::fEnergyResiduals static private
!
Definition at line 110 of file TTdrTigress.h.
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fSetCoreWave
bool TTdrTigress::fSetCoreWave = false static private
! Flag for Waveforms ON/OFF
Definition at line 90 of file TTdrTigress.h.
Referenced by Copy(), and SetCoreWave().
fSuppressedAddbackFrags
std::vector<UShort_t> TTdrTigress::fSuppressedAddbackFrags mutable private
! Number of crystals involved in creating in the suppressed addback hit
Definition at line 99 of file TTdrTigress.h.
Referenced by Clear(), Copy(), and GetSuppressedAddbackFragVector().
fSuppressedAddbackHits
std::vector<TDetectorHit*> TTdrTigress::fSuppressedAddbackHits mutable private
! Used to create suppressed addback hits on the fly
Definition at line 98 of file TTdrTigress.h.
Referenced by Clear(), Copy(), GetSuppressedAddbackVector(), and Print().
fSuppressedHits
std::vector<TDetectorHit*> TTdrTigress::fSuppressedHits mutable private
! Used to create suppressed hits on the fly
Definition at line 97 of file TTdrTigress.h.
Referenced by Clear(), Copy(), GetSuppressedMultiplicity(), GetSuppressedVector(), and Print().
fSuppressionCriterion
std::function< bool(TTdrTigressHit *, TBgoHit *)> TTdrTigress::fSuppressionCriterion = DefaultSuppression static private
Definition at line 88 of file TTdrTigress.h.
Referenced by GetSuppressionCriterion(), and SetSuppressionCriterion().
fTdrTigressBits
TTransientBits<UChar_t> TTdrTigress::fTdrTigressBits mutable private
Definition at line 105 of file TTdrTigress.h.
Referenced by ClearStatus(), Copy(), ResetFlags(), SetBitNumber(), and TestBitNumber().
gTigressPosition
TVector3 TTdrTigress::gTigressPosition static private
! Position of each HPGe Tigress
Definition at line 56 of file TTdrTigress.h.
Referenced by GetPosition().