GRSISort: TTransition Class Reference
TTransition Class Reference
Fitting & Analysis
#include <TTransition.h>
Public Member Functions
TTransition ()
~TTransition () override
void Clear (Option_t *opt="") override
int Compare (const TObject *obj) const override
int CompareEnergy (const TObject *obj) const
int CompareIntensity (const TObject *obj) const
double GetEnergy () const
double GetEnergyUncertainty () const
double GetIntensity () const
double GetIntensityUncertainty () const
bool IsSortable () const override
bool operator< (const TTransition &rhs) const
bool operator> (const TTransition &rhs) const
void Print (Option_t *opt="") const override
std::string PrintToString ()
void SetCompareIntensity (const bool &val)
void SetEnergy (const double &tmpenergy)
void SetEnergyUncertainty (const double &tmperror)
void SetIntensity (const double &tmpintens)
void SetIntensityUncertainty (const double &tmpinterror)
Private Attributes
bool fCompareIntensity {true}
double fEnergy {0.}
double fEngUncertainty {0.}
double fIntensity {0.}
double fIntUncertainty {0.}
Friends
class TNucleus
Detailed Description
This Class contains the information about a nuclear transition. These transitions are a part of a TNucleus and are typically set within the TNucleus framework
Definition at line 23 of file TTransition.h.
Constructor & Destructor Documentation
TTransition()
TTransition::TTransition ()
Definition at line 9 of file TTransition.cxx.
~TTransition()
TTransition::~TTransition () override
Definition at line 14 of file TTransition.cxx.
Member Function Documentation
Clear()
void TTransition::Clear (Option_t * opt = "") override
Definition at line 19 of file TTransition.cxx.
References fEnergy, fEngUncertainty, fIntensity, and fIntUncertainty.
Compare()
int TTransition::Compare (const TObject * obj) const override
Definition at line 57 of file TTransition.cxx.
References CompareEnergy(), CompareIntensity(), and fCompareIntensity.
CompareEnergy()
int TTransition::CompareEnergy (const TObject * obj) const
Compares the energies of the TTransitions
Definition at line 78 of file TTransition.cxx.
References fEnergy.
Referenced by Compare().
CompareIntensity()
int TTransition::CompareIntensity (const TObject * obj) const
Compares the intensities of the TTransitions
Definition at line 66 of file TTransition.cxx.
References fIntensity.
Referenced by Compare().
GetEnergy()
double TTransition::GetEnergy () const inline
Definition at line 41 of file TTransition.h.
References fEnergy.
Referenced by TSourceList::AddTransition(), operator<(), and operator>().
GetEnergyUncertainty()
double TTransition::GetEnergyUncertainty () const inline
Definition at line 42 of file TTransition.h.
References fEngUncertainty.
Referenced by TSourceList::AddTransition().
GetIntensity()
double TTransition::GetIntensity () const inline
Definition at line 43 of file TTransition.h.
References fIntensity.
Referenced by TSourceList::AddTransition().
GetIntensityUncertainty()
double TTransition::GetIntensityUncertainty () const inline
Definition at line 44 of file TTransition.h.
References fIntUncertainty.
Referenced by TSourceList::AddTransition().
IsSortable()
bool TTransition::IsSortable () const inline override
Definition at line 30 of file TTransition.h.
operator<()
bool TTransition::operator< (const TTransition & rhs) const inline
Definition at line 52 of file TTransition.h.
References GetEnergy().
operator>()
bool TTransition::operator> (const TTransition & rhs) const inline
Definition at line 51 of file TTransition.h.
References GetEnergy().
Print()
void TTransition::Print (Option_t * opt = "") const override
Definition at line 27 of file TTransition.cxx.
References fEnergy, fEngUncertainty, fIntensity, and fIntUncertainty.
PrintToString()
std::string TTransition::PrintToString ()
Definition at line 46 of file TTransition.cxx.
References fEnergy, fEngUncertainty, fIntensity, and fIntUncertainty.
SetCompareIntensity()
void TTransition::SetCompareIntensity (const bool & val) inline
Definition at line 39 of file TTransition.h.
References fCompareIntensity.
SetEnergy()
void TTransition::SetEnergy (const double & tmpenergy) inline
Definition at line 35 of file TTransition.h.
References fEnergy.
SetEnergyUncertainty()
void TTransition::SetEnergyUncertainty (const double & tmperror) inline
Definition at line 36 of file TTransition.h.
References fEngUncertainty.
SetIntensity()
void TTransition::SetIntensity (const double & tmpintens) inline
Definition at line 37 of file TTransition.h.
References fIntensity.
SetIntensityUncertainty()
void TTransition::SetIntensityUncertainty (const double & tmpinterror) inline
Definition at line 38 of file TTransition.h.
References fIntUncertainty.
Friends And Related Symbol Documentation
TNucleus
friend class TNucleus friend
Definition at line 24 of file TTransition.h.
Member Data Documentation
fCompareIntensity
bool TTransition::fCompareIntensity {true} private
Whether to sort by intensity or energy.
Definition at line 59 of file TTransition.h.
Referenced by Compare(), and SetCompareIntensity().
fEnergy
double TTransition::fEnergy {0.} private
Energy of the transition.
Definition at line 55 of file TTransition.h.
Referenced by Clear(), CompareEnergy(), GetEnergy(), Print(), PrintToString(), and SetEnergy().
fEngUncertainty
double TTransition::fEngUncertainty {0.} private
Uncertainty in the energy of the transition.
Definition at line 56 of file TTransition.h.
Referenced by Clear(), GetEnergyUncertainty(), Print(), PrintToString(), and SetEnergyUncertainty().
fIntensity
double TTransition::fIntensity {0.} private
Intensity of the transition.
Definition at line 57 of file TTransition.h.
Referenced by Clear(), CompareIntensity(), GetIntensity(), Print(), PrintToString(), and SetIntensity().
fIntUncertainty
double TTransition::fIntUncertainty {0.} private
Uncertainty in the intensity.
Definition at line 58 of file TTransition.h.
Referenced by Clear(), GetIntensityUncertainty(), Print(), PrintToString(), and SetIntensityUncertainty().