GRSISort: GRootBrowser Class Reference
GRootBrowser Class Reference
GROOT
Detailed Description
This class creates a ROOT object browser, constitued by three main tabs.
All tabs can 'swallow' frames, thanks to the new method: ExecPlugin(const char *name = 0, const char *fname = 0, const char *cmd = 0, Int_t pos = kRight, Int_t subpos = -1) allowing to select plugins (can be a macro or a command) to be executed, and where to embed the frame created by the plugin (tab and tab element). Examples:
create a new browser: TBrowser b;
create a new TCanvas in a new top right tab element: b.ExecPlugin("Canvas", 0, "new TCanvas()");
create a new top right tab element embedding the TGMainFrame created by the macro 'myMacro.C': b.ExecPlugin("MyPlugin", "myMacro.C");
create a new bottom tab element embedding the TGMainFrame created by the macro 'myMacro.C': b.ExecPlugin("MyPlugin", "myMacro.C", 0, GRootBrowser::kBottom);
this browser implementation can be selected via the env 'Browser.Name' in .rootrc, (GRootBrowser or GRootBrowserLite) the default being GRootBrowserLite (old browser) a list of options (plugins) for the new GRootBrowser is also specified via the env 'Browser.Options' in .rootrc, the default being: FECI Here is the list of available options: F: File browser E: Text Editor H: HTML browser C: Canvas I: I/O redirection P: Proof G: GL viewer
Definition at line 100 of file GRootBrowser.h.
Public Types
enum class EInsertPosition { kLeft , kRight , kBottom }
enum class ENewBrowserMessages {
kBrowse = 11011 , kOpenFile , kClone , kHelpAbout ,
kHelpOnBrowser , kHelpOnCanvas , kHelpOnMenus , kHelpOnGraphicsEd ,
kHelpOnObjects , kHelpOnPS , kHelpOnRemote , kNewEditor ,
kNewCanvas , kNewHtml , kExecPluginMacro , kExecPluginCmd ,
kCloseTab , kCloseWindow , kQuitRoot
}
Public Member Functions
GRootBrowser (TBrowser *b, const char *name, Int_t x, Int_t y, UInt_t width, UInt_t height, Option_t *opt="", Bool_t initshow=kTRUE)
GRootBrowser (TBrowser *b=nullptr, const char *name="ROOT Browser", UInt_t width=800, UInt_t height=500, Option_t *opt="", Bool_t initshow=kTRUE)
~GRootBrowser ()
void Add (TObject *obj, const char *name=nullptr, Int_t check=-1) override
void BrowseObj (TObject *obj) override
virtual void Checked (TObject *obj, Bool_t checked)
void CloneBrowser ()
virtual void CloseTab (Int_t id)
void CloseTabs () override
void CloseWindow () override
void CreateBrowser (const char *name)
void DoTab (Int_t id)
virtual void DoubleClicked (TObject *obj)
void EventInfo (Int_t event, Int_t px, Int_t py, TObject *selected)
Long_t ExecPlugin (const char *name=nullptr, const char *fname=nullptr, const char *cmd=nullptr, Int_t pos=static_cast< Int_t >(EInsertPosition::kRight), Int_t subpos=-1) override
void ExecuteDefaultAction (TObject *obj) override
TGFrame * GetActFrame () const
Option_t * GetDrawOption () const override
TGMainFrame * GetMainFrame () const override
TGStatusBar * GetStatusBar () const
TGTab * GetTab (Int_t pos) const
TGTab * GetTabBottom () const
TGTab * GetTabLeft () const
TGTab * GetTabRight () const
TGFrame * GetToolbarFrame () const
Bool_t HandleKey (Event_t *event) override
void HandleMenu (Int_t id)
void InitPlugins (Option_t *opt="")
virtual Bool_t IsCloseTabShown () const
void ReallyDelete () override
void RecursiveRemove (TObject *obj) override
void RecursiveReparent (TGPopupMenu *popup)
void Refresh (Bool_t force=kFALSE) override
void RemoveTab (Int_t pos, Int_t subpos)
void SetActBrowser (TBrowserImp *b)
void SetStatusText (const char *txt, Int_t col) override
void SetTab (Int_t pos=static_cast< Int_t >(EInsertPosition::kRight), Int_t subpos=-1)
void SetTabTitle (const char *title, Int_t pos=static_cast< Int_t >(EInsertPosition::kRight), Int_t subpos=-1)
void Show () override
virtual void ShowCloseTab (Bool_t show)
void ShowMenu (TGCompositeFrame *menu)
void StartEmbedding (Int_t pos=static_cast< Int_t >(EInsertPosition::kRight), Int_t subpos=-1) override
void StopEmbedding (const char *name, TGLayoutHints *layout)
void StopEmbedding (const char *name=nullptr) override
void SwitchMenus (TGCompositeFrame *from)
Static Public Member Functions
static TBrowserImp * NewBrowser (TBrowser *b, const char *title, Int_t x, Int_t y, UInt_t width, UInt_t height, Option_t *opt="")
static TBrowserImp * NewBrowser (TBrowser *b=nullptr, const char *title="ROOT Browser", UInt_t width=800, UInt_t height=500, Option_t *opt="")
Private Member Functions
GRootBrowser (const GRootBrowser &)
GRootBrowser (GRootBrowser &&) noexcept
GRootBrowser & operator= (const GRootBrowser &)
GRootBrowser & operator= (GRootBrowser &&) noexcept
Private Attributes
TBrowserImp * fActBrowser {nullptr}
TGCompositeFrame * fActMenuBar {nullptr}
TList fBrowsers
std::array< Int_t, 3 > fCrTab {}
TGCompositeFrame * fEditFrame {nullptr}
Int_t fEditPos {0}
Int_t fEditSubPos {0}
TGTab * fEditTab {nullptr}
TGHorizontalFrame * fH1 {nullptr}
TGHorizontalFrame * fH2 {nullptr}
TGHorizontalFrame * fHf {nullptr}
TGHSplitter * fHSplitter {nullptr}
const TGPicture * fIconPic {nullptr}
TGLayoutHints * fLH0 {nullptr}
TGLayoutHints * fLH1 {nullptr}
TGLayoutHints * fLH2 {nullptr}
TGLayoutHints * fLH3 {nullptr}
TGLayoutHints * fLH4 {nullptr}
TGLayoutHints * fLH5 {nullptr}
TGLayoutHints * fLH6 {nullptr}
TGLayoutHints * fLH7 {nullptr}
TGMenuBar * fMenuBar {nullptr}
TGPopupMenu * fMenuExecPlugin {nullptr}
TGPopupMenu * fMenuFile {nullptr}
TGHorizontalFrame * fMenuFrame {nullptr}
TGPopupMenu * fMenuHelp {nullptr}
Int_t fNbInitPlugins {0}
std::array< Int_t, 3 > fNbTab {}
Int_t fPid {0}
TList fPlugins
TGHorizontalFrame * fPreMenuFrame {nullptr}
Bool_t fShowCloseTab {kTRUE}
TGStatusBar * fStatusBar {nullptr}
TGTab * fTabBottom {nullptr}
TGTab * fTabLeft {nullptr}
TGTab * fTabRight {nullptr}
TGHorizontalFrame * fToolbarFrame {nullptr}
TGHorizontalFrame * fTopMenuFrame {nullptr}
TGVerticalFrame * fV1 {nullptr}
TGVerticalFrame * fV2 {nullptr}
TGVerticalFrame * fVf {nullptr}
TGVSplitter * fVSplitter {nullptr}
Member Enumeration Documentation
EInsertPosition
enum class GRootBrowser::EInsertPosition strong
Enumerator
kLeft
kRight
kBottom
Definition at line 173 of file GRootBrowser.h.
ENewBrowserMessages
enum class GRootBrowser::ENewBrowserMessages strong
Enumerator
kBrowse
kOpenFile
kClone
kHelpAbout
kHelpOnBrowser
kHelpOnCanvas
kHelpOnMenus
kHelpOnGraphicsEd
kHelpOnObjects
kHelpOnPS
kHelpOnRemote
kNewEditor
kNewCanvas
kNewHtml
kExecPluginMacro
kExecPluginCmd
kCloseTab
kCloseWindow
kQuitRoot
Definition at line 151 of file GRootBrowser.h.
Constructor & Destructor Documentation
GRootBrowser() [1/4]
GRootBrowser::GRootBrowser (const GRootBrowser &) private
Referenced by NewBrowser(), and NewBrowser().
GRootBrowser() [2/4]
GRootBrowser::GRootBrowser (GRootBrowser &&) private noexcept
GRootBrowser() [3/4]
GRootBrowser::GRootBrowser (TBrowser * b = nullptr, const char * name = "ROOT Browser", UInt_t width = 800, UInt_t height = 500, Option_t * opt = "", Bool_t initshow = kTRUE) explicit
Create browser with a specified width and height.
Definition at line 43 of file GRootBrowser.cxx.
References CreateBrowser(), and InitPlugins().
GRootBrowser() [4/4]
GRootBrowser::GRootBrowser (TBrowser * b, const char * name, Int_t x, Int_t y, UInt_t width, UInt_t height, Option_t * opt = "", Bool_t initshow = kTRUE)
Create browser with a specified width and height and at position x, y.
Definition at line 59 of file GRootBrowser.cxx.
References CreateBrowser(), and InitPlugins().
~GRootBrowser()
GRootBrowser::~GRootBrowser ()
Clean up all widgets, frames and layouthints that were used
Definition at line 225 of file GRootBrowser.cxx.
References fH1, fH2, fHf, fHSplitter, fIconPic, fLH0, fLH1, fLH2, fLH3, fLH4, fLH5, fLH6, fLH7, fMenuBar, fMenuExecPlugin, fMenuFile, fMenuFrame, fMenuHelp, fPreMenuFrame, fStatusBar, fTabBottom, fTabLeft, fTabRight, fToolbarFrame, fTopMenuFrame, fV1, fV2, fVf, and fVSplitter.
Member Function Documentation
Add()
void GRootBrowser::Add (TObject * obj, const char * name = nullptr, Int_t check = -1) override
Add items to the actual browser. This function has to be called by the Browse() member function of objects when they are called by a browser. If check < 0 (default) no check box is drawn, if 0 then unchecked checkbox is added, if 1 checked checkbox is added.
Definition at line 265 of file GRootBrowser.cxx.
References fActBrowser.
BrowseObj()
void GRootBrowser::BrowseObj (TObject * obj) override
Browse object. This, in turn, will trigger the calling of GRootBrowser::Add() which will fill the IconBox and the tree. Emits signal "BrowseObj(TObject*)".
Definition at line 286 of file GRootBrowser.cxx.
References fActBrowser.
Checked()
void GRootBrowser::Checked (TObject * obj, Bool_t checked) virtual
Emits signal when double clicking on icon.
Definition at line 1136 of file GRootBrowser.cxx.
CloneBrowser()
void GRootBrowser::CloneBrowser ()
Clone the browser. A new Browser will be created, with the same plugins executed in the current one.
Definition at line 299 of file GRootBrowser.cxx.
References GBrowserPlugin::fCommand, fNbInitPlugins, fPlugins, GBrowserPlugin::fSubTab, and GBrowserPlugin::fTab.
Referenced by HandleMenu().
CloseTab()
void GRootBrowser::CloseTab (Int_t id) virtual
Remove tab element id from right tab.
Definition at line 317 of file GRootBrowser.cxx.
References kRight, and RemoveTab().
Referenced by HandleMenu().
CloseTabs()
void GRootBrowser::CloseTabs () override
Properly close the mainframes embedded in the different tabs
Definition at line 325 of file GRootBrowser.cxx.
References CloseWindow(), fActBrowser, fMenuFile, fPlugins, fTabBottom, fTabLeft, and fTabRight.
Referenced by CloseWindow().
CloseWindow()
void GRootBrowser::CloseWindow () override
Called when window is closed via the window manager.
Definition at line 421 of file GRootBrowser.cxx.
References CloseTabs().
Referenced by CloseTabs(), HandleMenu(), and RemoveTab().
CreateBrowser()
void GRootBrowser::CreateBrowser (const char * name)
Create the actual interface.
Definition at line 76 of file GRootBrowser.cxx.
References fActMenuBar, fCrTab, fEditFrame, fEditPos, fEditSubPos, fEditTab, fH1, fH2, fHf, fHSplitter, fIconPic, fLH0, fLH1, fLH2, fLH3, fLH4, fLH5, fLH6, fLH7, fMenuBar, fMenuExecPlugin, fMenuFile, fMenuFrame, fMenuHelp, fNbInitPlugins, fNbTab, fPreMenuFrame, fStatusBar, fTabBottom, fTabLeft, fTabRight, fToolbarFrame, fTopMenuFrame, fV1, fV2, fVf, fVSplitter, kBrowse, kClone, kCloseTab, kCloseWindow, kExecPluginCmd, kExecPluginMacro, kHelpAbout, kHelpOnBrowser, kHelpOnCanvas, kHelpOnGraphicsEd, kHelpOnMenus, kHelpOnObjects, kHelpOnPS, kHelpOnRemote, kNewCanvas, kNewEditor, kNewHtml, kOpenFile, and kQuitRoot.
Referenced by GRootBrowser(), and GRootBrowser().
DoTab()
void GRootBrowser::DoTab (Int_t id)
Handle Tab navigation.
Definition at line 432 of file GRootBrowser.cxx.
References fTabRight, and SwitchMenus().
DoubleClicked()
void GRootBrowser::DoubleClicked (TObject * obj) virtual
Emits signal when double clicking on icon.
Definition at line 1129 of file GRootBrowser.cxx.
EventInfo()
void GRootBrowser::EventInfo (Int_t event, Int_t px, Int_t py, TObject * selected)
Display a tooltip with infos about the primitive below the cursor.
Definition at line 443 of file GRootBrowser.cxx.
References SetStatusText().
ExecPlugin()
Long_t GRootBrowser::ExecPlugin (const char * name = nullptr, const char * fname = nullptr, const char * cmd = nullptr, Int_t pos = static_cast<Int_t>(EInsertPosition::kRight), Int_t subpos = -1) override
Execute a macro and embed the created frame in the tab "pos" and tab element "subpos".
Definition at line 468 of file GRootBrowser.cxx.
References fPlugins, SetTabTitle(), StartEmbedding(), and StopEmbedding().
Referenced by HandleMenu(), and InitPlugins().
ExecuteDefaultAction()
void GRootBrowser::ExecuteDefaultAction (TObject * obj) override
Emits signal "ExecuteDefaultAction(TObject*)".
Definition at line 1146 of file GRootBrowser.cxx.
GetActFrame()
TGFrame * GRootBrowser::GetActFrame () const inline
Definition at line 190 of file GRootBrowser.h.
References fEditFrame.
GetDrawOption()
Option_t * GRootBrowser::GetDrawOption () const override
Returns drawing option.
Definition at line 507 of file GRootBrowser.cxx.
References fActBrowser.
GetMainFrame()
TGMainFrame * GRootBrowser::GetMainFrame () const inline override
Definition at line 219 of file GRootBrowser.h.
GetStatusBar()
TGStatusBar * GRootBrowser::GetStatusBar () const inline
Definition at line 192 of file GRootBrowser.h.
References fStatusBar.
GetTab()
TGTab * GRootBrowser::GetTab (Int_t pos) const
Returns the TGTab at position pos.
Definition at line 518 of file GRootBrowser.cxx.
References fTabBottom, fTabLeft, fTabRight, kBottom, kLeft, and kRight.
Referenced by SetTab(), SetTabTitle(), and StartEmbedding().
GetTabBottom()
TGTab * GRootBrowser::GetTabBottom () const inline
Definition at line 195 of file GRootBrowser.h.
References fTabBottom.
GetTabLeft()
TGTab * GRootBrowser::GetTabLeft () const inline
Definition at line 193 of file GRootBrowser.h.
References fTabLeft.
GetTabRight()
TGTab * GRootBrowser::GetTabRight () const inline
Definition at line 194 of file GRootBrowser.h.
References fTabRight.
GetToolbarFrame()
TGFrame * GRootBrowser::GetToolbarFrame () const inline
Definition at line 191 of file GRootBrowser.h.
References fToolbarFrame.
HandleKey()
Bool_t GRootBrowser::HandleKey (Event_t * event) override
Handle keyboard events.
Definition at line 531 of file GRootBrowser.cxx.
References fMenuFile, kBrowse, kClone, kCloseTab, kCloseWindow, kNewCanvas, kNewEditor, kNewHtml, kOpenFile, kQuitRoot, and Refresh().
HandleMenu()
void GRootBrowser::HandleMenu (Int_t id)
Handle menu entries events.
Definition at line 574 of file GRootBrowser.cxx.
References CloneBrowser(), CloseTab(), CloseWindow(), ExecPlugin(), fActBrowser, fMenuFile, fTabRight, gOpenFileTypes, gPluginFileTypes, kBrowse, kClone, kCloseTab, kCloseWindow, kExecPluginCmd, kExecPluginMacro, kHelpAbout, kHelpOnBrowser, kHelpOnCanvas, kHelpOnGraphicsEd, kHelpOnMenus, kHelpOnObjects, kHelpOnPS, kHelpOnRemote, kNewCanvas, kNewEditor, kNewHtml, kOpenFile, kQuitRoot, and kRight.
InitPlugins()
void GRootBrowser::InitPlugins (Option_t * opt = "")
Initialize default plugins. Could be also of the form:
StartEmbedding(0);
TPluginHandler *ph;
ph = gROOT->GetPluginManager()->FindHandler("TGClassBrowser");
if (ph && ph->LoadPlugin() != -1) {
   ph->ExecPlugin(3, gClient->GetRoot(), 200, 500);
}
StopEmbedding();
Definition at line 716 of file GRootBrowser.cxx.
References ExecPlugin(), fNbInitPlugins, and SetTab().
Referenced by GRootBrowser(), and GRootBrowser().
IsCloseTabShown()
virtual Bool_t GRootBrowser::IsCloseTabShown () const inline virtual
Definition at line 227 of file GRootBrowser.h.
References fShowCloseTab.
NewBrowser() [1/2]
TBrowserImp * GRootBrowser::NewBrowser (TBrowser * b, const char * title, Int_t x, Int_t y, UInt_t width, UInt_t height, Option_t * opt = "") static
static contructor returning TBrowserImp, as needed by the plugin mechanism.
Definition at line 1163 of file GRootBrowser.cxx.
References GRootBrowser().
NewBrowser() [2/2]
TBrowserImp * GRootBrowser::NewBrowser (TBrowser * b = nullptr, const char * title = "ROOT Browser", UInt_t width = 800, UInt_t height = 500, Option_t * opt = "") static
static contructor returning TBrowserImp, as needed by the plugin mechanism.
Definition at line 1153 of file GRootBrowser.cxx.
References GRootBrowser().
operator=() [1/2]
GRootBrowser & GRootBrowser::operator= (const GRootBrowser &) private
operator=() [2/2]
GRootBrowser & GRootBrowser::operator= (GRootBrowser &&) private noexcept
ReallyDelete()
void GRootBrowser::ReallyDelete () override
Really delete the browser and the this GUI.
Definition at line 802 of file GRootBrowser.cxx.
RecursiveRemove()
void GRootBrowser::RecursiveRemove (TObject * obj) override
Recursively remove object from browser.
Definition at line 811 of file GRootBrowser.cxx.
References fActBrowser.
RecursiveReparent()
void GRootBrowser::RecursiveReparent (TGPopupMenu * popup)
Recursively reparent TGPopupMenu to gClient->GetDefaultRoot().
Definition at line 821 of file GRootBrowser.cxx.
References RecursiveReparent().
Referenced by RecursiveReparent(), and SwitchMenus().
Refresh()
void GRootBrowser::Refresh (Bool_t force = kFALSE) override
Refresh the actual browser contents.
Definition at line 836 of file GRootBrowser.cxx.
References fActBrowser.
Referenced by HandleKey().
RemoveTab()
void GRootBrowser::RemoveTab (Int_t pos, Int_t subpos)
Remove tab element "subpos" from tab "pos".
Definition at line 846 of file GRootBrowser.cxx.
References CloseWindow(), fActMenuBar, fMenuFrame, fNbTab, fPlugins, fTabBottom, fTabLeft, fTabRight, kBottom, kLeft, kRight, and SwitchMenus().
Referenced by CloseTab().
SetActBrowser()
void GRootBrowser::SetActBrowser (TBrowserImp * b) inline
Definition at line 202 of file GRootBrowser.h.
References fActBrowser.
SetStatusText()
void GRootBrowser::SetStatusText (const char * txt, Int_t col) override
Set text in culumn col in status bar.
Definition at line 948 of file GRootBrowser.cxx.
References fStatusBar.
Referenced by EventInfo().
SetTab()
void GRootBrowser::SetTab (Int_t pos = static_cast<Int_t>(EInsertPosition::kRight), Int_t subpos = -1)
Switch to Tab "subpos" in TGTab "pos".
Definition at line 906 of file GRootBrowser.cxx.
References fCrTab, GetTab(), kRight, and SwitchMenus().
Referenced by InitPlugins().
SetTabTitle()
void GRootBrowser::SetTabTitle (const char * title, Int_t pos = static_cast<Int_t>(EInsertPosition::kRight), Int_t subpos = -1)
Set text "title" of Tab "subpos" in TGTab "pos".
Definition at line 924 of file GRootBrowser.cxx.
References fCrTab, fPlugins, and GetTab().
Referenced by ExecPlugin(), and StopEmbedding().
Show()
void GRootBrowser::Show () inline override
Definition at line 217 of file GRootBrowser.h.
ShowCloseTab()
virtual void GRootBrowser::ShowCloseTab (Bool_t show) inline virtual
Definition at line 226 of file GRootBrowser.h.
References fShowCloseTab.
ShowMenu()
void GRootBrowser::ShowMenu (TGCompositeFrame * menu)
Show the selected frame's menu and hide previous one.
Definition at line 956 of file GRootBrowser.cxx.
References fActMenuBar, fMenuBar, and fMenuFrame.
Referenced by SwitchMenus().
StartEmbedding()
void GRootBrowser::StartEmbedding (Int_t pos = static_cast<Int_t>(EInsertPosition::kRight), Int_t subpos = -1) override
Start embedding external frame in the tab "pos" and tab element "subpos".
Definition at line 985 of file GRootBrowser.cxx.
References fCrTab, fEditFrame, fEditPos, fEditSubPos, fEditTab, fNbTab, fShowCloseTab, and GetTab().
Referenced by ExecPlugin().
StopEmbedding() [1/2]
void GRootBrowser::StopEmbedding (const char * name, TGLayoutHints * layout)
Stop embedding external frame in the current editable frame.
Definition at line 1023 of file GRootBrowser.cxx.
References fEditFrame, fEditPos, fEditSubPos, fEditTab, fTabRight, SetTabTitle(), and SwitchMenus().
StopEmbedding() [2/2]
void GRootBrowser::StopEmbedding (const char * name = nullptr) inline override
Definition at line 205 of file GRootBrowser.h.
References StopEmbedding().
Referenced by ExecPlugin(), and StopEmbedding().
SwitchMenus()
void GRootBrowser::SwitchMenus (TGCompositeFrame * from)
Move the menu from original frame to our TGMenuFrame, or display the menu associated to the current tab.
Definition at line 1056 of file GRootBrowser.cxx.
References fActMenuBar, fLH2, fMenuBar, fMenuFrame, RecursiveReparent(), and ShowMenu().
Referenced by DoTab(), RemoveTab(), SetTab(), and StopEmbedding().
Member Data Documentation
fActBrowser
TBrowserImp* GRootBrowser::fActBrowser {nullptr} private
Actual (active) browser imp.
Definition at line 139 of file GRootBrowser.h.
Referenced by Add(), BrowseObj(), CloseTabs(), GetDrawOption(), HandleMenu(), RecursiveRemove(), Refresh(), and SetActBrowser().
fActMenuBar
TGCompositeFrame* GRootBrowser::fActMenuBar {nullptr} private
Actual (active) menu bar.
Definition at line 138 of file GRootBrowser.h.
Referenced by CreateBrowser(), RemoveTab(), ShowMenu(), and SwitchMenus().
fBrowsers
TList GRootBrowser::fBrowsers private
List of (sub)browsers.
Definition at line 140 of file GRootBrowser.h.
fCrTab
std::array<Int_t, 3> GRootBrowser::fCrTab {} private
Actual (active) tab elements (for each Tab)
Definition at line 145 of file GRootBrowser.h.
Referenced by CreateBrowser(), SetTab(), SetTabTitle(), and StartEmbedding().
fEditFrame
TGCompositeFrame* GRootBrowser::fEditFrame {nullptr} private
Frame in "Edit" mode.
Definition at line 129 of file GRootBrowser.h.
Referenced by CreateBrowser(), GetActFrame(), StartEmbedding(), and StopEmbedding().
fEditPos
Int_t GRootBrowser::fEditPos {0} private
Id of tab in "Edit" mode.
Definition at line 119 of file GRootBrowser.h.
Referenced by CreateBrowser(), StartEmbedding(), and StopEmbedding().
fEditSubPos
Int_t GRootBrowser::fEditSubPos {0} private
Id of subtab in "Edit" mode.
Definition at line 120 of file GRootBrowser.h.
Referenced by CreateBrowser(), StartEmbedding(), and StopEmbedding().
fEditTab
TGTab* GRootBrowser::fEditTab {nullptr} private
Tab in "Edit" mode.
Definition at line 118 of file GRootBrowser.h.
Referenced by CreateBrowser(), StartEmbedding(), and StopEmbedding().
fH1
TGHorizontalFrame* GRootBrowser::fH1 {nullptr} private
Horizontal frame.
Definition at line 123 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fH2
TGHorizontalFrame* GRootBrowser::fH2 {nullptr} private
Horizontal frame.
Definition at line 124 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fHf
TGHorizontalFrame* GRootBrowser::fHf {nullptr} private
Horizontal frame.
Definition at line 122 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fHSplitter
TGHSplitter* GRootBrowser::fHSplitter {nullptr} private
Horizontal splitter.
Definition at line 128 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fIconPic
const TGPicture* GRootBrowser::fIconPic {nullptr} private
icon picture
Definition at line 148 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH0
TGLayoutHints* GRootBrowser::fLH0 {nullptr} private
Layout hints, part 1.
Definition at line 107 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH1
TGLayoutHints* GRootBrowser::fLH1 {nullptr} private
Layout hints, part 2.
Definition at line 108 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH2
TGLayoutHints* GRootBrowser::fLH2 {nullptr} private
Layout hints, part 3.
Definition at line 109 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CreateBrowser(), and SwitchMenus().
fLH3
TGLayoutHints* GRootBrowser::fLH3 {nullptr} private
Layout hints, part 4.
Definition at line 110 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH4
TGLayoutHints* GRootBrowser::fLH4 {nullptr} private
Layout hints, part 5.
Definition at line 111 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH5
TGLayoutHints* GRootBrowser::fLH5 {nullptr} private
Layout hints, part 6.
Definition at line 112 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH6
TGLayoutHints* GRootBrowser::fLH6 {nullptr} private
Layout hints, part 7.
Definition at line 113 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fLH7
TGLayoutHints* GRootBrowser::fLH7 {nullptr} private
Layout hints, part 8.
Definition at line 114 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fMenuBar
TGMenuBar* GRootBrowser::fMenuBar {nullptr} private
Main (owned) menu bar.
Definition at line 134 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CreateBrowser(), ShowMenu(), and SwitchMenus().
fMenuExecPlugin
TGPopupMenu* GRootBrowser::fMenuExecPlugin {nullptr} private
"Exec Plugin" popup menu
Definition at line 136 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fMenuFile
TGPopupMenu* GRootBrowser::fMenuFile {nullptr} private
"File" popup menu
Definition at line 135 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CloseTabs(), CreateBrowser(), HandleKey(), and HandleMenu().
fMenuFrame
TGHorizontalFrame* GRootBrowser::fMenuFrame {nullptr} private
Shared menu frame.
Definition at line 132 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CreateBrowser(), RemoveTab(), ShowMenu(), and SwitchMenus().
fMenuHelp
TGPopupMenu* GRootBrowser::fMenuHelp {nullptr} private
"Browser Help" popup menu
Definition at line 137 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fNbInitPlugins
Int_t GRootBrowser::fNbInitPlugins {0} private
Number of initial plugins (from .rootrc)
Definition at line 143 of file GRootBrowser.h.
Referenced by CloneBrowser(), CreateBrowser(), and InitPlugins().
fNbTab
std::array<Int_t, 3> GRootBrowser::fNbTab {} private
Number of tab elements (for each Tab)
Definition at line 144 of file GRootBrowser.h.
Referenced by CreateBrowser(), RemoveTab(), and StartEmbedding().
fPid
Int_t GRootBrowser::fPid {0} private
Current process id.
Definition at line 146 of file GRootBrowser.h.
fPlugins
TList GRootBrowser::fPlugins private
List of plugins.
Definition at line 141 of file GRootBrowser.h.
Referenced by CloneBrowser(), CloseTabs(), ExecPlugin(), RemoveTab(), and SetTabTitle().
fPreMenuFrame
TGHorizontalFrame* GRootBrowser::fPreMenuFrame {nullptr} private
First (owned) menu frame.
Definition at line 131 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fShowCloseTab
Bool_t GRootBrowser::fShowCloseTab {kTRUE} private
kTRUE to show close icon on tab elements
Definition at line 147 of file GRootBrowser.h.
Referenced by IsCloseTabShown(), ShowCloseTab(), and StartEmbedding().
fStatusBar
TGStatusBar* GRootBrowser::fStatusBar {nullptr} private
Status bar.
Definition at line 142 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CreateBrowser(), GetStatusBar(), and SetStatusText().
fTabBottom
TGTab* GRootBrowser::fTabBottom {nullptr} private
Bottom Tab.
Definition at line 117 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CloseTabs(), CreateBrowser(), GetTab(), GetTabBottom(), and RemoveTab().
fTabLeft
TGTab* GRootBrowser::fTabLeft {nullptr} private
Left Tab.
Definition at line 115 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CloseTabs(), CreateBrowser(), GetTab(), GetTabLeft(), and RemoveTab().
fTabRight
TGTab* GRootBrowser::fTabRight {nullptr} private
Right Tab.
Definition at line 116 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CloseTabs(), CreateBrowser(), DoTab(), GetTab(), GetTabRight(), HandleMenu(), RemoveTab(), and StopEmbedding().
fToolbarFrame
TGHorizontalFrame* GRootBrowser::fToolbarFrame {nullptr} private
Toolbar frame.
Definition at line 133 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), CreateBrowser(), and GetToolbarFrame().
fTopMenuFrame
TGHorizontalFrame* GRootBrowser::fTopMenuFrame {nullptr} private
Top menu frame.
Definition at line 130 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fV1
TGVerticalFrame* GRootBrowser::fV1 {nullptr} private
Vertical frame.
Definition at line 125 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fV2
TGVerticalFrame* GRootBrowser::fV2 {nullptr} private
Vertical frame.
Definition at line 126 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fVf
TGVerticalFrame* GRootBrowser::fVf {nullptr} private
Vertical frame.
Definition at line 121 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().
fVSplitter
TGVSplitter* GRootBrowser::fVSplitter {nullptr} private
Vertical splitter.
Definition at line 127 of file GRootBrowser.h.
Referenced by ~GRootBrowser(), and CreateBrowser().