GRSISort: TDescantHit Class Reference
TDescantHit Class Reference
Detectors
Detailed Description
Definition at line 19 of file TDescantHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TDescantHit ()
TDescantHit (const TDescantHit &)
TDescantHit (const TFragment &frag)
TDescantHit (TDescantHit &&) noexcept=default
~TDescantHit () override=default
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &val)
bool AnalyzeWaveform ()
virtual void AppendTimeStamp (const Long64_t &val)
Int_t CalculateCfd (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolation_steps)
Int_t CalculateCfdAndMonitor (double attenuation, unsigned int delay, int halfSmoothingWindow, unsigned int interpolationSteps, std::vector< Short_t > &monitor)
std::vector< Short_t > CalculateCfdMonitor (double attenuation, unsigned int delay, unsigned int halfSmoothingWindow)
std::vector< Int_t > CalculatePartialSum ()
Int_t CalculatePsd (double fraction, unsigned int interpolationSteps)
Int_t CalculatePsdAndPartialSums (double fraction, unsigned int interpolationSteps, std::vector< Int_t > &partialSums)
std::vector< Short_t > CalculateSmoothedWaveform (unsigned int halfSmoothingWindow)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool) const override
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
Int_t GetCcLong () const
Int_t GetCcShort () const
Float_t GetCfd () const override
std::vector< int16_t > & GetCfdMonitor ()
TChannel * GetChannel () const
virtual int GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Int_t GetFilterPattern () const
virtual Short_t GetKValue () const
const char * GetName () const override
std::vector< int > & GetPartialSum ()
TVector3 GetPosition () const override
TVector3 GetPosition (Double_t dist) const override
EPpgPattern GetPPGStatus () const
Int_t GetPsd () const
Int_t GetRemainder () const
virtual Int_t GetSegment () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
Int_t GetZc () const
virtual bool HasWave () const
bool InFilter (Int_t)
bool operator< (const TDetectorHit &rhs) const
TDescantHit & operator= (const TDescantHit &)=default
TDescantHit & operator= (TDescantHit &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void SetAddress (const UInt_t &temp_address)
void SetCcLong (const int &x)
void SetCcShort (const int &x)
virtual void SetCfd (const Float_t &val)
virtual void SetCfd (const Int_t &val)
virtual void SetCfd (const uint32_t &val)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &energy) const
void SetFilterPattern (const int &x)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
void SetPsd (const int &x)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &val)
void SetWaveform (const std::vector< Short_t > &val)
void SetZc (const int &x)
bool TestHitBit (EBitFlag flag) const
virtual size_t WaveSize () const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Private Member Functions
Double_t GetDefaultDistance () const
Private Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Int_t fCcLong
Int_t fCcShort
Float_t fCfd {0}
std::vector< int16_t > fCfdMonitor
TChannel * fChannel {nullptr}
Float_t fCharge {0.}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Int_t fFilter
Short_t fKValue {0}
std::vector< int > fPartialSum
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Int_t fPsd
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Int_t fZc
Static Private Attributes
static TVector3 fBeamDirection
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 50 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 72 of file TDetectorHit.h.
Constructor & Destructor Documentation
TDescantHit() [1/4]
TDescantHit::TDescantHit ()
Definition at line 13 of file TDescantHit.cxx.
References Clear().
TDescantHit() [2/4]
TDescantHit::TDescantHit (const TDescantHit & rhs)
Definition at line 18 of file TDescantHit.cxx.
References Clear(), and Copy().
TDescantHit() [3/4]
TDescantHit::TDescantHit (TDescantHit &&) default noexcept
TDescantHit() [4/4]
TDescantHit::TDescantHit (const TFragment & frag) explicit
Definition at line 24 of file TDescantHit.cxx.
References AnalyzeWaveform(), TDetectorHit::Copy(), TDetectorHit::CopyWave(), TGRSIOptions::Get(), TFragment::GetCcLong(), TFragment::GetCcShort(), TDetectorHit::GetWaveform(), TFragment::GetZc(), SetCcLong(), SetCcShort(), and SetZc().
~TDescantHit()
TDescantHit::~TDescantHit () override default
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TGriffinHit, TFippsHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 184 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & val) inline inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AnalyzeWaveform()
bool TDescantHit::AnalyzeWaveform ()
!
Definition at line 123 of file TDescantHit.cxx.
References CalculateCfd(), CalculatePartialSum(), CalculatePsd(), fPsd, TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), TDetectorHit::SetCfd(), TDetectorHit::SetCharge(), SetPsd(), TDetectorHit::SetWaveform(), and TDetectorHit::WaveSize().
Referenced by TDescantHit().
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
CalculateCfd()
Int_t TDescantHit::CalculateCfd (double attenuation, unsigned int delay, int halfsmoothingwindow, unsigned int interpolation_steps)
!
Definition at line 171 of file TDescantHit.cxx.
References CalculateCfdAndMonitor().
Referenced by AnalyzeWaveform().
CalculateCfdAndMonitor()
Int_t TDescantHit::CalculateCfdAndMonitor (double attenuation, unsigned int delay, int halfSmoothingWindow, unsigned int interpolationSteps, std::vector< Short_t > & monitor)
!
Definition at line 180 of file TDescantHit.cxx.
References CalculateSmoothedWaveform(), TGRSIOptions::Debug(), fCfdMonitor, TGRSIOptions::Get(), TDetectorHit::GetCfd(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::WaveSize().
Referenced by CalculateCfd().
CalculateCfdMonitor()
std::vector< Short_t > TDescantHit::CalculateCfdMonitor (double attenuation, unsigned int delay, unsigned int halfSmoothingWindow)
!
Definition at line 261 of file TDescantHit.cxx.
References CalculateSmoothedWaveform(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::WaveSize().
CalculatePartialSum()
std::vector< Int_t > TDescantHit::CalculatePartialSum ()
!
Definition at line 284 of file TDescantHit.cxx.
References fPartialSum, TGRSIOptions::Get(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::WaveSize().
Referenced by AnalyzeWaveform(), and CalculatePsdAndPartialSums().
CalculatePsd()
Int_t TDescantHit::CalculatePsd (double fraction, unsigned int interpolationSteps)
!
Definition at line 304 of file TDescantHit.cxx.
References CalculatePsdAndPartialSums().
Referenced by AnalyzeWaveform().
CalculatePsdAndPartialSums()
Int_t TDescantHit::CalculatePsdAndPartialSums (double fraction, unsigned int interpolationSteps, std::vector< Int_t > & partialSums)
!
Definition at line 311 of file TDescantHit.cxx.
References CalculatePartialSum(), fPsd, and TDetectorHit::GetWaveform().
Referenced by CalculatePsd().
CalculateSmoothedWaveform()
std::vector< Short_t > TDescantHit::CalculateSmoothedWaveform (unsigned int halfSmoothingWindow)
!
Definition at line 242 of file TDescantHit.cxx.
References TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::WaveSize().
Referenced by CalculateCfdAndMonitor(), and CalculateCfdMonitor().
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 145 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TTACHit::TempCorrectedCharge(), and TFippsTACHit::TempCorrectedCharge().
Clear()
void TDescantHit::Clear (Option_t * opt = "") override
!
Definition at line 97 of file TDescantHit.cxx.
References TDetectorHit::Clear(), fCcLong, fCcShort, fCfdMonitor, fFilter, fPartialSum, fPsd, and fZc.
Referenced by TDescantHit(), and TDescantHit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 176 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 171 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 94 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TBgoHit::TBgoHit(), TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 209 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TDescantHit::Copy (TObject & rhs) const override
!
Definition at line 43 of file TDescantHit.cxx.
References TDetectorHit::Copy(), TDetectorHit::CopyWave(), fCcLong, fCcShort, fCfdMonitor, fFilter, fPartialSum, fPsd, fZc, and TGRSIOptions::Get().
Referenced by TDescantHit(), and Copy().
Copy() [2/2]
void TDescantHit::Copy (TObject & obj, bool waveform) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 58 of file TDescantHit.cxx.
References Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 119 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TBgoHit::TBgoHit(), TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), Copy(), TTipHit::Copy(), TZeroDegreeHit::Copy(), TDetectorHit::Copy(), TAriesHit::Copy(), Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TRcmpHit::Copy(), TS3Hit::Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), TEagleHit::Copy(), TPinDiodeHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), and TTdrTigressHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 143 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharc2Hit::GetBackAddress(), TSharcHit::GetBackAddress(), TSharc2Hit::GetFrontAddress(), TSharcHit::GetFrontAddress(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharc2Hit::GetPadAddress(), TSharcHit::GetPadAddress(), TFragment::GetSharcMesyBoard(), TEagleHit::Print(), TPinDiodeHit::Print(), TFragment::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TGriffinBgoHit, TGriffinHit, TLaBrBgoHit, TRcmpHit, TTigressHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TIfinBgoHit, TIfinHit, TBgoHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 163 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 182 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TTigressHit::GetDoppler(), and TSiLiHit::GetDoppler().
GetCcLong()
Int_t TDescantHit::GetCcLong () const inline
!
Definition at line 54 of file TDescantHit.h.
References fCcLong.
GetCcShort()
Int_t TDescantHit::GetCcShort () const inline
!
Definition at line 53 of file TDescantHit.h.
References fCcShort.
GetCfd()
Float_t TDescantHit::GetCfd () const override virtual
!
special function for TDescantHit to return CFD after mapping out the high bits which are the remainder between the 125 MHz data and the 100 MHz timestamp clock
Reimplemented from TDetectorHit.
Definition at line 84 of file TDescantHit.cxx.
References TDetectorHit::GetCfd().
GetCfdMonitor()
std::vector< int16_t > & TDescantHit::GetCfdMonitor () inline
Definition at line 55 of file TDescantHit.h.
References fCfdMonitor.
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 148 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit::TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), TS3Hit::GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TS3Hit::GetDefaultDistance(), TS3Hit::GetDefaultPhiOffset(), TDetectorHit::GetDetector(), TS3Hit::GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TTACHit::GetTempCorrectedEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), TS3Hit::SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
int TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 214 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 54 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharc2Hit::GetBackCharge(), TSharcHit::GetBackCharge(), TSharc2Hit::GetFrontCharge(), TSharcHit::GetFrontCharge(), TSharc2Hit::GetPadCharge(), TSharcHit::GetPadCharge(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TTigressHit::Print(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 200 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TGriffinHit::Print(), TFippsHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 257 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDefaultDistance()
Double_t TDescantHit::GetDefaultDistance () const inline private
Definition at line 87 of file TDescantHit.h.
Referenced by GetPosition().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 182 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TDetectorHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TSharc2::GetDeadLayerThickness(), TSharc::GetDeadLayerThickness(), TSharc2::GetDetectorThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), GetPosition(), TTrificHit::GetPosition(), TTigress::GetPosition(), TGriffinHit::GetPosition(), TFippsHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TAriesHit::GetPosition(), GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TSceptarHit::GetPosition(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TEagleHit::GetPosition(), TPinDiodeHit::GetPosition(), TFippsLaBrHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TAriesHit::Print(), Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TSharc2Hit::Print(), TSharcHit::Print(), TTACHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), and PromptCoincidence().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Reimplemented in TCSMHit, TSharc2Hit, TSharcHit, and TSiLiHit.
Definition at line 69 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFippsHit::CompareEnergy(), TGriffinHit::CompareEnergy(), TIfinHit::CompareEnergy(), TTdrCloverHit::CompareEnergy(), TTdrTigressHit::CompareEnergy(), TTigressHit::CompareEnergy(), TDetectorHit::CompareEnergy(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), ExampleFragmentSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TSharc2Hit::GetDeltaBackE(), TSharcHit::GetDeltaBackE(), TSharc2Hit::GetDeltaE(), TSharcHit::GetDeltaE(), TSharc2Hit::GetDeltaFrontE(), TSharcHit::GetDeltaFrontE(), TTigressHit::GetDoppler(), TSharc2Hit::GetEnergy(), TSharcHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TSharc2Hit::GetPadE(), TSharcHit::GetPadE(), TDetectorHit::GetTime(), TFragment::GetTZero(), MakeAnalysisHistograms(), MakeGRIFFINEnergyHsts(), TDetectorHit::operator<(), TAriesHit::Print(), Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TEagleHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), and TTigressHit::SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 92 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFilterPattern()
Int_t TDescantHit::GetFilterPattern () const inline
!
Definition at line 50 of file TDescantHit.h.
References fFilter.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 146 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TGriffinHit::GetNoCTEnergy(), TFippsHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TTACHit::GetTempCorrectedEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 156 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by EfficiencyHelper::EndOfSort(), TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPartialSum()
std::vector< int > & TDescantHit::GetPartialSum () inline
Definition at line 56 of file TDescantHit.h.
References fPartialSum.
GetPosition() [1/2]
TVector3 TDescantHit::GetPosition () const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 72 of file TDescantHit.cxx.
References GetDefaultDistance(), TDetectorHit::GetDetector(), and TDescant::GetPosition().
GetPosition() [2/2]
TVector3 TDescantHit::GetPosition (Double_t dist) const override virtual
!
TDetectorHit::GetPosition
Reimplemented from TDetectorHit.
Definition at line 66 of file TDescantHit.cxx.
References TDetectorHit::GetDetector(), and TDescant::GetPosition().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 241 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetPsd()
Int_t TDescantHit::GetPsd () const inline
!
Definition at line 51 of file TDescantHit.h.
References fPsd.
GetRemainder()
Int_t TDescantHit::GetRemainder () const
returns the remainder between 100 MHz/10ns timestamp and 125 MHz/8 ns data in ns
Definition at line 91 of file TDescantHit.cxx.
References TDetectorHit::GetCfd().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 191 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TGriffinBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TBgoHit::GetArrayNumber(), TSharc2Hit::GetBackStrip(), TSharcHit::GetBackStrip(), TSharc2Hit::GetFrontStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), TS3Hit::SetRingNumber(), TS3Hit::SetRingNumber(), TS3Hit::SetSectorNumber(), TS3Hit::SetSectorNumber(), and TSiLiHit::SumHit().
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 41 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonPolarimetryHelper::Coincident(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleTreeHelper::Exec(), TSiLi::fCoincidenceTime(), ExampleTreeSelector::FillHistograms(), TSharc2Hit::GetDeltaBackT(), TSharcHit::GetDeltaBackT(), TSharc2Hit::GetDeltaFrontT(), TSharcHit::GetDeltaFrontT(), TSharc2Hit::GetDeltaT(), TSharcHit::GetDeltaT(), TSharc2Hit::GetPadT(), TSharcHit::GetPadT(), TTACHit::GetTempCorrectedCharge(), TFippsTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TDetectorHit::Print(), TAriesHit::Print(), Print(), TGriffinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), TPinDiodeHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TTACHit::TempCorrectedCharge(), TFippsTACHit::TempCorrectedCharge(), ComptonPolarimetryHelper::TimeDiff(), TimeRandom(), and TimeRandom().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 273 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), TTigressHit::GetTimeToTrigger(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TGriffinHit::Print(), TTigressHit::Print(), TEagleHit::Print(), and TFragment::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 223 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by ComptonPolarimetryHelper::Coincident(), DirectoryHelper::Exec(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), TGriffinHit::Print(), and ComptonPolarimetryHelper::TimeDiff().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 232 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), CalculateCfdMonitor(), CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), CalculatePsdAndPartialSums(), CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
GetZc()
Int_t TDescantHit::GetZc () const inline
!
Definition at line 52 of file TDescantHit.h.
References fZc.
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 102 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), CalculateCfdMonitor(), CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TFragment::Print(), and TPulseAnalyzer::SetData().
InFilter()
bool TDescantHit::InFilter (Int_t)
!
check if the desired filter is in wanted filter; return the answer;
Definition at line 77 of file TDescantHit.cxx.
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 191 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 190 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 193 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 192 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 88 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
operator=() [1/2]
TDescantHit & TDescantHit::operator= (const TDescantHit &) default
operator=() [2/2]
TDescantHit & TDescantHit::operator= (TDescantHit &&) default noexcept
Print() [1/2]
void TDescantHit::Print (Option_t * opt = "") const override
!
Definition at line 109 of file TDescantHit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TDescantHit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 114 of file TDescantHit.cxx.
References TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), and TDetectorHit::GetTime().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 109 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), and TTigressHit::SumHit().
SetCcLong()
void TDescantHit::SetCcLong (const int & x) inline
!
Definition at line 44 of file TDescantHit.h.
References fCcLong.
Referenced by TDescantHit().
SetCcShort()
void TDescantHit::SetCcShort (const int & x) inline
!
Definition at line 43 of file TDescantHit.h.
References fCcShort.
Referenced by TDescantHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & val) inline virtual inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 111 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 112 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & energy) const inline inherited
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetFilterPattern()
void TDescantHit::SetFilterPattern (const int & x) inline
!
Definition at line 40 of file TDescantHit.h.
References fFilter.
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 280 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 110 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetPsd()
void TDescantHit::SetPsd (const int & x) inline
!
Definition at line 41 of file TDescantHit.h.
References fPsd.
Referenced by AnalyzeWaveform().
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 127 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TGriffinHit::Add(), TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & val) inline inherited
!
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TTdrPlasticHit::TTdrPlasticHit(), AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetZc()
void TDescantHit::SetZc (const int & x) inline
!
Definition at line 42 of file TDescantHit.h.
References fZc.
Referenced by TDescantHit().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 187 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), and TSiLiHit::GetEnergy().
WaveSize()
virtual size_t TDetectorHit::WaveSize () const inline virtual inherited
!
Definition at line 103 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), CalculateCfdMonitor(), CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), and TZeroDegreeHit::CalculateSmoothedWaveform().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} private inherited
address of the the channel in the DAQ.
Definition at line 196 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static private inherited
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable private inherited
Definition at line 211 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TTdrCloverHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TTdrCloverHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TTdrCloverHit::NPileUps(), TTdrCloverHit::PUHit(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), and TDetectorHit::TestHitBit().
fCcLong
Int_t TDescantHit::fCcLong private
Definition at line 34 of file TDescantHit.h.
Referenced by Clear(), Copy(), GetCcLong(), and SetCcLong().
fCcShort
Int_t TDescantHit::fCcShort private
Definition at line 33 of file TDescantHit.h.
Referenced by Clear(), Copy(), GetCcShort(), and SetCcShort().
fCfd
Float_t TDetectorHit::fCfd {0} private inherited
CFD time of the Hit.
Definition at line 199 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fCfdMonitor
std::vector<int16_t> TDescantHit::fCfdMonitor private
Definition at line 35 of file TDescantHit.h.
Referenced by CalculateCfdAndMonitor(), Clear(), Copy(), and GetCfdMonitor().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 208 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} private inherited
charge collected from the hit
Definition at line 197 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 207 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fFilter
Int_t TDescantHit::fFilter private
Definition at line 30 of file TDescantHit.h.
Referenced by Clear(), Copy(), GetFilterPattern(), and SetFilterPattern().
fKValue
Short_t TDetectorHit::fKValue {0} private inherited
integration value.
Definition at line 198 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), TFippsTACHit::GetTempCorrectedEnergy(), and TDetectorHit::SetKValue().
fPartialSum
std::vector<int> TDescantHit::fPartialSum private
Definition at line 36 of file TDescantHit.h.
Referenced by CalculatePartialSum(), Clear(), Copy(), and GetPartialSum().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fPsd
Int_t TDescantHit::fPsd private
Definition at line 31 of file TDescantHit.h.
Referenced by AnalyzeWaveform(), CalculatePsdAndPartialSums(), Clear(), Copy(), GetPsd(), and SetPsd().
fTime
Double_t TDetectorHit::fTime {0.} mutable private inherited
! Calibrated Time of the hit
Definition at line 202 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} private inherited
Timestamp given to hit in ns.
Definition at line 200 of file TDetectorHit.h.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), and TDetectorHit::SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform private inherited
Definition at line 201 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), TDetectorHit::SetWaveform(), and TDetectorHit::WaveSize().
fZc
Int_t TDescantHit::fZc private
Definition at line 32 of file TDescantHit.h.
Referenced by Clear(), Copy(), GetZc(), and SetZc().