GRSISort: TPulseAnalyzer Class Reference
TPulseAnalyzer Class Reference
Fitting & Analysis
Detailed Description
Mostly a direct port of SFU code I have stripped out some surplus and encapsulated it, but I havent changed much I'm sure there is more that can be stripped and reformated but it is working currently.
Definition at line 33 of file TPulseAnalyzer.h.
Classes
struct LinePar
struct ParPar
struct ShapePar
struct SinPar
struct WaveFormPar
Public Member Functions
TPulseAnalyzer ()
TPulseAnalyzer (const std::vector< Short_t > &wave, double=0, std::string name="")
TPulseAnalyzer (const TFragment &fragment, double=0)
TPulseAnalyzer (const TPulseAnalyzer &)=default
TPulseAnalyzer (TPulseAnalyzer &&) noexcept=default
virtual ~TPulseAnalyzer ()
void Clear (Option_t *opt="")
double CsIPID ()
double CsIt0 ()
void DrawCsIExclusion ()
void DrawCsIFit ()
void DrawRFFit ()
void Drawsilifit ()
void DrawT0fit ()
void DrawWave ()
double fit_newT0 ()
double fit_rf (double=2 *8.48409)
bool Get_bflag ()
double get_sig2noise ()
double Get_wpar_amplitude ()
double Get_wpar_baselinefin ()
double Get_wpar_decay ()
double Get_wpar_rise ()
double Get_wpar_T0 ()
int GetCsIChiSq ()
int GetCsIFitType ()
TF1 Getsilifit ()
bool GetSiliShape (double tauDecay, double tauRise)
bool GetSiliShapeTF1 (double tauDecay, double tauRise, double baseline, double basefreq=0)
double GetsiliSmirnov ()
TGraph * GetWaveGraph ()
TH1I * GetWaveHist ()
int16_t good_baseline ()
bool IsSet () const
TPulseAnalyzer & operator= (const TPulseAnalyzer &)=default
TPulseAnalyzer & operator= (TPulseAnalyzer &&) noexcept=default
void print_WavePar ()
void SetData (const std::vector< Short_t > &wave, double=0)
void SetData (const TFragment &fragment, double=0)
bool SiliShapePrepare (double tauDecay, double tauRise)
Static Public Member Functions
static double SiLiFitFunction (double *i, double *p)
Static Public Attributes
static int fNameIter = 0
Private Member Functions
bool CsIIsSet () const
long double determinant (int)
int fit_line (int, int, LinePar *)
int fit_parabola (int, int, ParPar *)
int fit_smooth_parabola (int, int, double, ParPar *)
int FitCsIShape (int, ShapePar *, WaveFormPar *)
void get_baseline ()
void get_baseline_fin ()
double get_linear_T0 ()
double get_parabolic_T0 ()
double get_sin_par (double)
double get_smooth_T0 ()
void get_t10 ()
void get_t30 ()
void get_t50 ()
void get_t90 ()
double get_tfrac (double, double, double)
void get_tmax ()
void GetCsIExclusionZone ()
int GetCsIShape ()
double GetCsIt0 (ShapePar *, WaveFormPar *)
double GetCsITau (int, ShapePar *)
void GetQuickPara ()
void SetCsI (bool option=true)
int solve_lin_eq ()
Private Attributes
int cN {0}
long double copy_matrix [20][20]
bool CsISet
ShapePar * csiTestShpar [4] {nullptr}
WaveFormPar * csiTestWpar [4] {nullptr}
std::vector< Short_t > cWavebuffer
WaveFormPar * cWpar {nullptr}
double EPS
int FILTER
std::string fName
double LARGECHISQ
int lineq_dim
long double lineq_matrix [20][20]
long double lineq_solution [20]
long double lineq_vector [20]
bool set {false}
ShapePar * shpar {nullptr}
SinPar * spar {nullptr}
int T0RANGE
Static Private Attributes
static const int BAD_BASELINE_RANGE = -1024 - 12
static const int BAD_EXCLUSION_ZONE = -1024 - 10
static const int BAD_MAX = -1024 - 11
static const int BAD_PID = -1024
static const int BADCHISQ_AMPL = -1024 - 6
static const int BADCHISQ_FAIL_DIRECT = -1024 - 9
static const int BADCHISQ_LIN_T0 = -1024 - 4
static const int BADCHISQ_MAT = -1024 - 5
static const int BADCHISQ_NEG = -1024 - 1
static const int BADCHISQ_PAR_T0 = -1024 - 3
static const int BADCHISQ_SMOOTH_T0 = -1024 - 2
static const int BADCHISQ_T0 = -1024 - 7
static const int CSI_BASELINE_RANGE = 50
static const int MAX_SAMPLES = 4096
static const int NOISE_LEVEL_CSI = 100
static const int NSHAPE = 5
static const int PIN_BASELINE_RANGE = 16
Constructor & Destructor Documentation
TPulseAnalyzer() [1/5]
TPulseAnalyzer::TPulseAnalyzer ()
Definition at line 5 of file TPulseAnalyzer.cxx.
References Clear().
TPulseAnalyzer() [2/5]
TPulseAnalyzer::TPulseAnalyzer (const TFragment & fragment, double noise_fac = 0) explicit
Definition at line 10 of file TPulseAnalyzer.cxx.
References Clear(), and SetData().
TPulseAnalyzer() [3/5]
TPulseAnalyzer::TPulseAnalyzer (const std::vector< Short_t > & wave, double noise_fac = 0, std::string name = "") explicit
Definition at line 16 of file TPulseAnalyzer.cxx.
References Clear(), and SetData().
TPulseAnalyzer() [4/5]
TPulseAnalyzer::TPulseAnalyzer (const TPulseAnalyzer &) default
TPulseAnalyzer() [5/5]
TPulseAnalyzer::TPulseAnalyzer (TPulseAnalyzer &&) default noexcept
~TPulseAnalyzer()
TPulseAnalyzer::~TPulseAnalyzer () virtual
Definition at line 23 of file TPulseAnalyzer.cxx.
References cWpar, shpar, and spar.
Member Function Documentation
Clear()
void TPulseAnalyzer::Clear (Option_t * opt = "")
Definition at line 30 of file TPulseAnalyzer.cxx.
References cN, copy_matrix, EPS, FILTER, LARGECHISQ, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, set, SetCsI(), and T0RANGE.
Referenced by TPulseAnalyzer(), TPulseAnalyzer(), and TPulseAnalyzer().
CsIIsSet()
bool TPulseAnalyzer::CsIIsSet () const inline private
Definition at line 208 of file TPulseAnalyzer.h.
References CsISet.
Referenced by CsIPID(), CsIt0(), DrawCsIFit(), GetCsIChiSq(), and GetCsIFitType().
CsIPID()
double TPulseAnalyzer::CsIPID ()
Definition at line 894 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::ShapePar::am, BAD_BASELINE_RANGE, BAD_EXCLUSION_ZONE, BAD_MAX, BAD_PID, TPulseAnalyzer::WaveFormPar::bflag, cN, CsIIsSet(), cWpar, GetCsIExclusionZone(), GetCsIShape(), TPulseAnalyzer::WaveFormPar::mflag, s, set, SetCsI(), shpar, TPulseAnalyzer::ShapePar::t, TPulseAnalyzer::WaveFormPar::teflag, and TPulseAnalyzer::ShapePar::type.
Referenced by TTipHit::SetPID().
CsIt0()
double TPulseAnalyzer::CsIt0 ()
Definition at line 866 of file TPulseAnalyzer.cxx.
References cN, CsIIsSet(), cWpar, GetCsIExclusionZone(), GetCsIShape(), set, SetCsI(), shpar, TPulseAnalyzer::ShapePar::t, and TPulseAnalyzer::WaveFormPar::teflag.
Referenced by TTipHit::SetPID().
determinant()
long double TPulseAnalyzer::determinant (int m) private
Definition at line 91 of file TPulseAnalyzer.cxx.
References copy_matrix, determinant(), and s.
Referenced by determinant(), and solve_lin_eq().
DrawCsIExclusion()
void TPulseAnalyzer::DrawCsIExclusion ()
Definition at line 1849 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::afit, TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselineMax, TPulseAnalyzer::WaveFormPar::baselineMin, TPulseAnalyzer::WaveFormPar::bfit, cN, cWpar, DrawWave(), FILTER, set, TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::temax, and TPulseAnalyzer::WaveFormPar::temin.
DrawCsIFit()
void TPulseAnalyzer::DrawCsIFit ()
Definition at line 1886 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::ShapePar::am, cN, TGRSIFunctions::CsIFitFunction(), CsIIsSet(), cWpar, DrawWave(), set, shpar, and TPulseAnalyzer::ShapePar::t.
DrawRFFit()
void TPulseAnalyzer::DrawRFFit ()
Definition at line 1799 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::SinPar::A, TPulseAnalyzer::SinPar::C, cN, DrawWave(), set, spar, and TPulseAnalyzer::SinPar::t0.
Drawsilifit()
void TPulseAnalyzer::Drawsilifit ()
Definition at line 1752 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::amplitude, cWpar, DrawWave(), Getsilifit(), set, and TPulseAnalyzer::WaveFormPar::t0.
DrawT0fit()
void TPulseAnalyzer::DrawT0fit ()
Definition at line 1820 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::b0, TPulseAnalyzer::WaveFormPar::b1, cN, cWpar, DrawWave(), TPulseAnalyzer::WaveFormPar::s0, TPulseAnalyzer::WaveFormPar::s1, TPulseAnalyzer::WaveFormPar::s2, set, TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::thigh.
DrawWave()
void TPulseAnalyzer::DrawWave ()
Definition at line 1762 of file TPulseAnalyzer.cxx.
References GetWaveHist().
Referenced by DrawCsIExclusion(), DrawCsIFit(), DrawRFFit(), Drawsilifit(), and DrawT0fit().
fit_line()
int TPulseAnalyzer::fit_line (int low, int high, LinePar * lp) private
Definition at line 289 of file TPulseAnalyzer.cxx.
References BADCHISQ_MAT, TPulseAnalyzer::LinePar::chisq, cWavebuffer, TPulseAnalyzer::LinePar::intercept, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::LinePar::ndf, TPulseAnalyzer::LinePar::slope, and solve_lin_eq().
Referenced by get_linear_T0(), and get_parabolic_T0().
fit_newT0()
double TPulseAnalyzer::fit_newT0 ()
Definition at line 191 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline_range, cN, cWpar, get_baseline(), get_baseline_fin(), get_linear_T0(), get_parabolic_T0(), get_smooth_T0(), get_t30(), get_t50(), get_tmax(), good_baseline(), LARGECHISQ, set, TPulseAnalyzer::WaveFormPar::t0, T0RANGE, TPulseAnalyzer::WaveFormPar::t50, and TPulseAnalyzer::WaveFormPar::thigh.
Referenced by TS3Hit::SetWavefit(), TTigressHit::SetWavefit(), TTigressHit::SetWavefit(), and TTipHit::SetWavefit().
fit_parabola()
int TPulseAnalyzer::fit_parabola (int low, int high, ParPar * pp) private
Definition at line 248 of file TPulseAnalyzer.cxx.
References BADCHISQ_MAT, TPulseAnalyzer::ParPar::chisq, TPulseAnalyzer::ParPar::constant, cWavebuffer, TPulseAnalyzer::ParPar::linear, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::ParPar::ndf, TPulseAnalyzer::ParPar::quadratic, and solve_lin_eq().
Referenced by get_parabolic_T0().
fit_rf()
double TPulseAnalyzer::fit_rf (double T = 2 * 8.48409)
Definition at line 173 of file TPulseAnalyzer.cxx.
References cN, get_sin_par(), set, spar, and TPulseAnalyzer::SinPar::t0.
Referenced by TRF::AddFragment().
fit_smooth_parabola()
int TPulseAnalyzer::fit_smooth_parabola (int low, int high, double x0, ParPar * pp) private
Definition at line 124 of file TPulseAnalyzer.cxx.
References BADCHISQ_MAT, TPulseAnalyzer::ParPar::chisq, TPulseAnalyzer::ParPar::constant, cWavebuffer, TPulseAnalyzer::ParPar::linear, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::ParPar::ndf, TPulseAnalyzer::ParPar::quadratic, and solve_lin_eq().
Referenced by get_smooth_T0().
FitCsIShape()
int TPulseAnalyzer::FitCsIShape (int dim, ShapePar * par, WaveFormPar * wpar) private
Definition at line 1063 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::ShapePar::am, BADCHISQ_AMPL, BADCHISQ_MAT, BADCHISQ_NEG, BADCHISQ_T0, TPulseAnalyzer::ShapePar::chisq, cN, cWavebuffer, GetCsIt0(), GetCsITau(), lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::ShapePar::ndf, solve_lin_eq(), TPulseAnalyzer::ShapePar::t, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::ShapePar::type.
Referenced by GetCsIShape().
get_baseline()
void TPulseAnalyzer::get_baseline () private
Definition at line 497 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselineStDev, TPulseAnalyzer::WaveFormPar::bflag, cN, cWavebuffer, and cWpar.
Referenced by fit_newT0(), GetCsIExclusionZone(), and GetQuickPara().
get_baseline_fin()
void TPulseAnalyzer::get_baseline_fin () private
Definition at line 524 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::baselineStDevfin, cN, cWavebuffer, cWpar, TPulseAnalyzer::WaveFormPar::t0, and T0RANGE.
Referenced by fit_newT0(), and GetQuickPara().
Get_bflag()
bool TPulseAnalyzer::Get_bflag () inline
Definition at line 145 of file TPulseAnalyzer.h.
References TPulseAnalyzer::WaveFormPar::bflag, and cWpar.
get_linear_T0()
double TPulseAnalyzer::get_linear_T0 () private
Definition at line 324 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::b0, TPulseAnalyzer::WaveFormPar::b1, BADCHISQ_LIN_T0, TPulseAnalyzer::LinePar::chisq, cWpar, fit_line(), TPulseAnalyzer::LinePar::intercept, LARGECHISQ, TPulseAnalyzer::WaveFormPar::s0, TPulseAnalyzer::WaveFormPar::s1, TPulseAnalyzer::WaveFormPar::s2, TPulseAnalyzer::LinePar::slope, TPulseAnalyzer::WaveFormPar::t0, T0RANGE, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::thigh.
Referenced by fit_newT0().
get_parabolic_T0()
double TPulseAnalyzer::get_parabolic_T0 () private
Definition at line 431 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::b0, TPulseAnalyzer::WaveFormPar::b1, BADCHISQ_PAR_T0, TPulseAnalyzer::LinePar::chisq, TPulseAnalyzer::ParPar::chisq, TPulseAnalyzer::ParPar::constant, cWpar, fit_line(), fit_parabola(), TPulseAnalyzer::LinePar::intercept, LARGECHISQ, TPulseAnalyzer::ParPar::linear, TPulseAnalyzer::ParPar::quadratic, TPulseAnalyzer::WaveFormPar::s0, TPulseAnalyzer::WaveFormPar::s1, TPulseAnalyzer::WaveFormPar::s2, TPulseAnalyzer::LinePar::slope, TPulseAnalyzer::WaveFormPar::t0, T0RANGE, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::thigh.
Referenced by fit_newT0().
get_sig2noise()
double TPulseAnalyzer::get_sig2noise ()
Definition at line 819 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::baselineStDevfin, cWpar, TPulseAnalyzer::WaveFormPar::max, set, and TPulseAnalyzer::WaveFormPar::t0.
Referenced by TS3Hit::SetWavefit(), TSiLiHit::SetWavefit(), TTigressHit::SetWavefit(), TTigressHit::SetWavefit(), and TTipHit::SetWavefit().
get_sin_par()
double TPulseAnalyzer::get_sin_par (double T) private
Definition at line 737 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::SinPar::A, TPulseAnalyzer::SinPar::C, cN, cWavebuffer, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, s, solve_lin_eq(), spar, and TPulseAnalyzer::SinPar::t0.
Referenced by fit_rf().
get_smooth_T0()
double TPulseAnalyzer::get_smooth_T0 () private
Definition at line 372 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::b0, TPulseAnalyzer::WaveFormPar::b1, BADCHISQ_SMOOTH_T0, TPulseAnalyzer::ParPar::chisq, TPulseAnalyzer::ParPar::constant, cWpar, fit_smooth_parabola(), LARGECHISQ, TPulseAnalyzer::ParPar::quadratic, TPulseAnalyzer::WaveFormPar::s0, TPulseAnalyzer::WaveFormPar::s1, TPulseAnalyzer::WaveFormPar::s2, TPulseAnalyzer::WaveFormPar::t0, T0RANGE, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::thigh.
Referenced by fit_newT0().
get_t10()
void TPulseAnalyzer::get_t10 () private
Definition at line 712 of file TPulseAnalyzer.cxx.
References cWpar, get_tfrac(), MAX_SAMPLES, TPulseAnalyzer::WaveFormPar::t10, and TPulseAnalyzer::WaveFormPar::t10_flag.
get_t30()
void TPulseAnalyzer::get_t30 () private
Definition at line 725 of file TPulseAnalyzer.cxx.
References cWpar, get_tfrac(), MAX_SAMPLES, TPulseAnalyzer::WaveFormPar::t30, and TPulseAnalyzer::WaveFormPar::t30_flag.
Referenced by fit_newT0().
get_t50()
void TPulseAnalyzer::get_t50 () private
Definition at line 687 of file TPulseAnalyzer.cxx.
References cWpar, get_tfrac(), MAX_SAMPLES, TPulseAnalyzer::WaveFormPar::t50, and TPulseAnalyzer::WaveFormPar::t50_flag.
Referenced by fit_newT0().
get_t90()
void TPulseAnalyzer::get_t90 () private
Definition at line 699 of file TPulseAnalyzer.cxx.
References cWpar, get_tfrac(), MAX_SAMPLES, TPulseAnalyzer::WaveFormPar::t90, and TPulseAnalyzer::WaveFormPar::t90_flag.
get_tfrac()
double TPulseAnalyzer::get_tfrac (double frac, double fraclow, double frachigh) private
Definition at line 578 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::bflag, cN, cWavebuffer, cWpar, lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::mflag, solve_lin_eq(), and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by get_t10(), get_t30(), get_t50(), and get_t90().
get_tmax()
void TPulseAnalyzer::get_tmax () private
Definition at line 550 of file TPulseAnalyzer.cxx.
References cN, cWavebuffer, cWpar, FILTER, TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::mflag, and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by fit_newT0(), GetCsIExclusionZone(), and GetQuickPara().
Get_wpar_amplitude()
double TPulseAnalyzer::Get_wpar_amplitude () inline
Definition at line 138 of file TPulseAnalyzer.h.
References TPulseAnalyzer::WaveFormPar::amplitude, and cWpar.
Referenced by TSiLiHit::SetWavefit().
Get_wpar_baselinefin()
double TPulseAnalyzer::Get_wpar_baselinefin () inline
Definition at line 137 of file TPulseAnalyzer.h.
References TPulseAnalyzer::WaveFormPar::baselinefin, and cWpar.
Referenced by TSiLiHit::SetWavefit().
Get_wpar_decay()
double TPulseAnalyzer::Get_wpar_decay () inline
Definition at line 139 of file TPulseAnalyzer.h.
References cWpar, and TPulseAnalyzer::WaveFormPar::tauDecay.
Get_wpar_rise()
double TPulseAnalyzer::Get_wpar_rise () inline
Definition at line 140 of file TPulseAnalyzer.h.
References cWpar, and TPulseAnalyzer::WaveFormPar::tauRise.
Get_wpar_T0()
double TPulseAnalyzer::Get_wpar_T0 () inline
Definition at line 136 of file TPulseAnalyzer.h.
References cWpar, and TPulseAnalyzer::WaveFormPar::t0.
Referenced by TSiLiHit::SetWavefit().
GetCsIChiSq()
int TPulseAnalyzer::GetCsIChiSq ()
Definition at line 850 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::ShapePar::chisq, CsIIsSet(), and shpar.
Referenced by TTipHit::SetPID().
GetCsIExclusionZone()
void TPulseAnalyzer::GetCsIExclusionZone () private
Definition at line 1225 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::afit, TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselineMax, TPulseAnalyzer::WaveFormPar::baselineMin, TPulseAnalyzer::WaveFormPar::bfit, CSI_BASELINE_RANGE, cWavebuffer, cWpar, FILTER, get_baseline(), get_tmax(), lineq_dim, lineq_matrix, lineq_solution, lineq_vector, TPulseAnalyzer::WaveFormPar::mflag, NOISE_LEVEL_CSI, solve_lin_eq(), TPulseAnalyzer::WaveFormPar::teflag, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by CsIPID(), and CsIt0().
GetCsIFitType()
int TPulseAnalyzer::GetCsIFitType ()
Definition at line 858 of file TPulseAnalyzer.cxx.
References CsIIsSet(), shpar, and TPulseAnalyzer::ShapePar::type.
Referenced by TTipHit::SetPID().
GetCsIShape()
int TPulseAnalyzer::GetCsIShape () private
Definition at line 946 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::ShapePar::am, BADCHISQ_FAIL_DIRECT, TPulseAnalyzer::ShapePar::chisq, cN, csiTestShpar, csiTestWpar, cWpar, FitCsIShape(), LARGECHISQ, shpar, TPulseAnalyzer::ShapePar::t, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::ShapePar::type.
Referenced by CsIPID(), and CsIt0().
GetCsIt0()
double TPulseAnalyzer::GetCsIt0 (ShapePar * par, WaveFormPar * wpar) private
Definition at line 1335 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline_range, EPS, GetCsITau(), lineq_dim, lineq_solution, TPulseAnalyzer::WaveFormPar::t0, and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by FitCsIShape().
GetCsITau()
double TPulseAnalyzer::GetCsITau (int i, ShapePar * par) private
Definition at line 1319 of file TPulseAnalyzer.cxx.
References NSHAPE, and TPulseAnalyzer::ShapePar::t.
Referenced by FitCsIShape(), and GetCsIt0().
GetQuickPara()
void TPulseAnalyzer::GetQuickPara () private
Definition at line 1438 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::bflag, cN, cWavebuffer, cWpar, get_baseline(), get_baseline_fin(), get_tmax(), IsSet(), TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::mflag, TPulseAnalyzer::WaveFormPar::t0, T0RANGE, TPulseAnalyzer::WaveFormPar::t10, TPulseAnalyzer::WaveFormPar::t10_flag, TPulseAnalyzer::WaveFormPar::t50, TPulseAnalyzer::WaveFormPar::t50_flag, TPulseAnalyzer::WaveFormPar::t90, TPulseAnalyzer::WaveFormPar::t90_flag, and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by SiliShapePrepare().
Getsilifit()
TF1 TPulseAnalyzer::Getsilifit ()
Definition at line 1711 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::amplitude, TPulseAnalyzer::WaveFormPar::baseamp, TPulseAnalyzer::WaveFormPar::basefreq, TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::basephase, cN, cWpar, fNameIter, set, SiLiFitFunction(), TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::tauDecay, and TPulseAnalyzer::WaveFormPar::tauRise.
Referenced by Drawsilifit(), GetSiliShapeTF1(), and GetsiliSmirnov().
GetSiliShape()
bool TPulseAnalyzer::GetSiliShape (double tauDecay, double tauRise)
Definition at line 1540 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::amplitude, TPulseAnalyzer::WaveFormPar::baselinefin, cN, cWavebuffer, cWpar, IsSet(), lineq_dim, lineq_matrix, lineq_solution, lineq_vector, SiliShapePrepare(), solve_lin_eq(), TPulseAnalyzer::WaveFormPar::t0, and TPulseAnalyzer::WaveFormPar::t10.
Referenced by TSiLiHit::FitPulseAnalyzer().
GetSiliShapeTF1()
bool TPulseAnalyzer::GetSiliShapeTF1 (double tauDecay, double tauRise, double baseline, double basefreq = 0)
Definition at line 1631 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::amplitude, TPulseAnalyzer::WaveFormPar::baseamp, TPulseAnalyzer::WaveFormPar::basefreq, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::basephase, TPulseAnalyzer::WaveFormPar::bflag, cN, cWavebuffer, cWpar, Getsilifit(), GetWaveGraph(), TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::osciflag, SiliShapePrepare(), TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::tauDecay, and TPulseAnalyzer::WaveFormPar::tauRise.
Referenced by TSiLiHit::FitPulseAnalyzer().
GetsiliSmirnov()
double TPulseAnalyzer::GetsiliSmirnov ()
Definition at line 1736 of file TPulseAnalyzer.cxx.
References cN, cWavebuffer, cWpar, Getsilifit(), and set.
Referenced by TSiLiHit::SetWavefit().
GetWaveGraph()
TGraph * TPulseAnalyzer::GetWaveGraph ()
Definition at line 1787 of file TPulseAnalyzer.cxx.
References cN, cWavebuffer, and set.
Referenced by GetSiliShapeTF1().
GetWaveHist()
TH1I * TPulseAnalyzer::GetWaveHist ()
Definition at line 1772 of file TPulseAnalyzer.cxx.
References cN, cWavebuffer, fNameIter, and set.
Referenced by DrawWave().
good_baseline()
int16_t TPulseAnalyzer::good_baseline ()
Definition at line 829 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline, cWavebuffer, cWpar, TPulseAnalyzer::WaveFormPar::max, set, T0RANGE, and TPulseAnalyzer::WaveFormPar::tmax.
Referenced by fit_newT0().
IsSet()
bool TPulseAnalyzer::IsSet () const inline
Definition at line 134 of file TPulseAnalyzer.h.
References set.
Referenced by TRF::AddFragment(), TSiLiHit::FitPulseAnalyzer(), GetQuickPara(), GetSiliShape(), TTipHit::SetPID(), TS3Hit::SetWavefit(), TTigressHit::SetWavefit(), TTigressHit::SetWavefit(), TTipHit::SetWavefit(), and SiliShapePrepare().
operator=() [1/2]
TPulseAnalyzer & TPulseAnalyzer::operator= (const TPulseAnalyzer &) default
operator=() [2/2]
TPulseAnalyzer & TPulseAnalyzer::operator= (TPulseAnalyzer &&) default noexcept
print_WavePar()
void TPulseAnalyzer::print_WavePar ()
Definition at line 1917 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::baseline, TPulseAnalyzer::WaveFormPar::baselineStDev, cWpar, TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::temax, TPulseAnalyzer::WaveFormPar::temin, and TPulseAnalyzer::WaveFormPar::tmax.
SetCsI()
void TPulseAnalyzer::SetCsI (bool option = true) inline private
Definition at line 207 of file TPulseAnalyzer.h.
References CsISet.
Referenced by Clear(), CsIPID(), CsIt0(), and SetData().
SetData() [1/2]
void TPulseAnalyzer::SetData (const std::vector< Short_t > & wave, double noise_fac = 0)
Definition at line 55 of file TPulseAnalyzer.cxx.
References cN, cWavebuffer, FILTER, set, SetCsI(), and T0RANGE.
SetData() [2/2]
void TPulseAnalyzer::SetData (const TFragment & fragment, double noise_fac = 0)
Definition at line 47 of file TPulseAnalyzer.cxx.
References TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and SetData().
Referenced by TPulseAnalyzer(), TPulseAnalyzer(), and SetData().
SiLiFitFunction()
double TPulseAnalyzer::SiLiFitFunction (double * i, double * p) static
Definition at line 1696 of file TPulseAnalyzer.cxx.
References s.
Referenced by Getsilifit().
SiliShapePrepare()
bool TPulseAnalyzer::SiliShapePrepare (double tauDecay, double tauRise)
Definition at line 1504 of file TPulseAnalyzer.cxx.
References TPulseAnalyzer::WaveFormPar::amplitude, TPulseAnalyzer::WaveFormPar::baseamp, TPulseAnalyzer::WaveFormPar::basefreq, TPulseAnalyzer::WaveFormPar::baseline_range, TPulseAnalyzer::WaveFormPar::baselinefin, TPulseAnalyzer::WaveFormPar::baselineStDevfin, TPulseAnalyzer::WaveFormPar::basephase, TPulseAnalyzer::WaveFormPar::bflag, cWpar, GetQuickPara(), IsSet(), TPulseAnalyzer::WaveFormPar::max, TPulseAnalyzer::WaveFormPar::osciflag, TPulseAnalyzer::WaveFormPar::t0, TPulseAnalyzer::WaveFormPar::t10_flag, TPulseAnalyzer::WaveFormPar::tauDecay, and TPulseAnalyzer::WaveFormPar::tauRise.
Referenced by GetSiliShape(), and GetSiliShapeTF1().
solve_lin_eq()
int TPulseAnalyzer::solve_lin_eq () private
Definition at line 75 of file TPulseAnalyzer.cxx.
References copy_matrix, determinant(), lineq_dim, lineq_matrix, lineq_solution, and lineq_vector.
Referenced by fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_sin_par(), get_tfrac(), GetCsIExclusionZone(), and GetSiliShape().
Member Data Documentation
BAD_BASELINE_RANGE
const int TPulseAnalyzer::BAD_BASELINE_RANGE = -1024 - 12 static private
Definition at line 243 of file TPulseAnalyzer.h.
Referenced by CsIPID().
BAD_EXCLUSION_ZONE
const int TPulseAnalyzer::BAD_EXCLUSION_ZONE = -1024 - 10 static private
Definition at line 241 of file TPulseAnalyzer.h.
Referenced by CsIPID().
BAD_MAX
const int TPulseAnalyzer::BAD_MAX = -1024 - 11 static private
Definition at line 242 of file TPulseAnalyzer.h.
Referenced by CsIPID().
BAD_PID
const int TPulseAnalyzer::BAD_PID = -1024 static private
Definition at line 244 of file TPulseAnalyzer.h.
Referenced by CsIPID().
BADCHISQ_AMPL
const int TPulseAnalyzer::BADCHISQ_AMPL = -1024 - 6 static private
Definition at line 256 of file TPulseAnalyzer.h.
Referenced by FitCsIShape().
BADCHISQ_FAIL_DIRECT
const int TPulseAnalyzer::BADCHISQ_FAIL_DIRECT = -1024 - 9 static private
Definition at line 240 of file TPulseAnalyzer.h.
Referenced by GetCsIShape().
BADCHISQ_LIN_T0
const int TPulseAnalyzer::BADCHISQ_LIN_T0 = -1024 - 4 static private
Definition at line 238 of file TPulseAnalyzer.h.
Referenced by get_linear_T0().
BADCHISQ_MAT
const int TPulseAnalyzer::BADCHISQ_MAT = -1024 - 5 static private
Definition at line 239 of file TPulseAnalyzer.h.
Referenced by fit_line(), fit_parabola(), fit_smooth_parabola(), and FitCsIShape().
BADCHISQ_NEG
const int TPulseAnalyzer::BADCHISQ_NEG = -1024 - 1 static private
Definition at line 255 of file TPulseAnalyzer.h.
Referenced by FitCsIShape().
BADCHISQ_PAR_T0
const int TPulseAnalyzer::BADCHISQ_PAR_T0 = -1024 - 3 static private
Definition at line 237 of file TPulseAnalyzer.h.
Referenced by get_parabolic_T0().
BADCHISQ_SMOOTH_T0
const int TPulseAnalyzer::BADCHISQ_SMOOTH_T0 = -1024 - 2 static private
Definition at line 236 of file TPulseAnalyzer.h.
Referenced by get_smooth_T0().
BADCHISQ_T0
const int TPulseAnalyzer::BADCHISQ_T0 = -1024 - 7 static private
Definition at line 254 of file TPulseAnalyzer.h.
Referenced by FitCsIShape().
cN
int TPulseAnalyzer::cN {0} private
Definition at line 175 of file TPulseAnalyzer.h.
Referenced by Clear(), CsIPID(), CsIt0(), DrawCsIExclusion(), DrawCsIFit(), DrawRFFit(), DrawT0fit(), fit_newT0(), fit_rf(), FitCsIShape(), get_baseline(), get_baseline_fin(), get_sin_par(), get_tfrac(), get_tmax(), GetCsIShape(), GetQuickPara(), Getsilifit(), GetSiliShape(), GetSiliShapeTF1(), GetsiliSmirnov(), GetWaveGraph(), GetWaveHist(), and SetData().
copy_matrix
long double TPulseAnalyzer::copy_matrix[20][20] private
Definition at line 195 of file TPulseAnalyzer.h.
Referenced by Clear(), determinant(), and solve_lin_eq().
CSI_BASELINE_RANGE
const int TPulseAnalyzer::CSI_BASELINE_RANGE = 50 static private
Definition at line 250 of file TPulseAnalyzer.h.
Referenced by GetCsIExclusionZone().
CsISet
bool TPulseAnalyzer::CsISet private
Definition at line 204 of file TPulseAnalyzer.h.
Referenced by CsIIsSet(), and SetCsI().
csiTestShpar
ShapePar* TPulseAnalyzer::csiTestShpar[4] {nullptr} private
Definition at line 181 of file TPulseAnalyzer.h.
Referenced by GetCsIShape().
csiTestWpar
WaveFormPar* TPulseAnalyzer::csiTestWpar[4] {nullptr} private
Definition at line 180 of file TPulseAnalyzer.h.
Referenced by GetCsIShape().
cWavebuffer
std::vector<Short_t> TPulseAnalyzer::cWavebuffer private
Definition at line 177 of file TPulseAnalyzer.h.
Referenced by fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_baseline(), get_baseline_fin(), get_sin_par(), get_tfrac(), get_tmax(), GetCsIExclusionZone(), GetQuickPara(), GetSiliShape(), GetSiliShapeTF1(), GetsiliSmirnov(), GetWaveGraph(), GetWaveHist(), good_baseline(), and SetData().
cWpar
WaveFormPar* TPulseAnalyzer::cWpar {nullptr} private
Definition at line 174 of file TPulseAnalyzer.h.
Referenced by ~TPulseAnalyzer(), CsIPID(), CsIt0(), DrawCsIExclusion(), DrawCsIFit(), Drawsilifit(), DrawT0fit(), fit_newT0(), get_baseline(), get_baseline_fin(), Get_bflag(), get_linear_T0(), get_parabolic_T0(), get_sig2noise(), get_smooth_T0(), get_t10(), get_t30(), get_t50(), get_t90(), get_tfrac(), get_tmax(), Get_wpar_amplitude(), Get_wpar_baselinefin(), Get_wpar_decay(), Get_wpar_rise(), Get_wpar_T0(), GetCsIExclusionZone(), GetCsIShape(), GetQuickPara(), Getsilifit(), GetSiliShape(), GetSiliShapeTF1(), GetsiliSmirnov(), good_baseline(), print_WavePar(), and SiliShapePrepare().
EPS
double TPulseAnalyzer::EPS private
Definition at line 205 of file TPulseAnalyzer.h.
Referenced by Clear(), and GetCsIt0().
FILTER
int TPulseAnalyzer::FILTER private
Definition at line 186 of file TPulseAnalyzer.h.
Referenced by Clear(), DrawCsIExclusion(), get_tmax(), GetCsIExclusionZone(), and SetData().
fName
std::string TPulseAnalyzer::fName private
Definition at line 183 of file TPulseAnalyzer.h.
fNameIter
int TPulseAnalyzer::fNameIter = 0 static
Definition at line 159 of file TPulseAnalyzer.h.
Referenced by Getsilifit(), and GetWaveHist().
LARGECHISQ
double TPulseAnalyzer::LARGECHISQ private
Definition at line 188 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_newT0(), get_linear_T0(), get_parabolic_T0(), get_smooth_T0(), and GetCsIShape().
lineq_dim
int TPulseAnalyzer::lineq_dim private
Definition at line 191 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_sin_par(), get_tfrac(), GetCsIExclusionZone(), GetCsIt0(), GetSiliShape(), and solve_lin_eq().
lineq_matrix
long double TPulseAnalyzer::lineq_matrix[20][20] private
Definition at line 192 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_sin_par(), get_tfrac(), GetCsIExclusionZone(), GetSiliShape(), and solve_lin_eq().
lineq_solution
long double TPulseAnalyzer::lineq_solution[20] private
Definition at line 194 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_sin_par(), get_tfrac(), GetCsIExclusionZone(), GetCsIt0(), GetSiliShape(), and solve_lin_eq().
lineq_vector
long double TPulseAnalyzer::lineq_vector[20] private
Definition at line 193 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_line(), fit_parabola(), fit_smooth_parabola(), FitCsIShape(), get_sin_par(), get_tfrac(), GetCsIExclusionZone(), GetSiliShape(), and solve_lin_eq().
MAX_SAMPLES
const int TPulseAnalyzer::MAX_SAMPLES = 4096 static private
Definition at line 248 of file TPulseAnalyzer.h.
Referenced by get_t10(), get_t30(), get_t50(), and get_t90().
NOISE_LEVEL_CSI
const int TPulseAnalyzer::NOISE_LEVEL_CSI = 100 static private
Definition at line 251 of file TPulseAnalyzer.h.
Referenced by GetCsIExclusionZone().
NSHAPE
const int TPulseAnalyzer::NSHAPE = 5 static private
Definition at line 252 of file TPulseAnalyzer.h.
Referenced by GetCsITau().
PIN_BASELINE_RANGE
const int TPulseAnalyzer::PIN_BASELINE_RANGE = 16 static private
Definition at line 247 of file TPulseAnalyzer.h.
set
bool TPulseAnalyzer::set {false} private
Definition at line 173 of file TPulseAnalyzer.h.
Referenced by Clear(), CsIPID(), CsIt0(), DrawCsIExclusion(), DrawCsIFit(), DrawRFFit(), Drawsilifit(), DrawT0fit(), fit_newT0(), fit_rf(), get_sig2noise(), Getsilifit(), GetsiliSmirnov(), GetWaveGraph(), GetWaveHist(), good_baseline(), IsSet(), and SetData().
shpar
ShapePar* TPulseAnalyzer::shpar {nullptr} private
Definition at line 179 of file TPulseAnalyzer.h.
Referenced by ~TPulseAnalyzer(), CsIPID(), CsIt0(), DrawCsIFit(), GetCsIChiSq(), GetCsIFitType(), and GetCsIShape().
spar
SinPar* TPulseAnalyzer::spar {nullptr} private
Definition at line 178 of file TPulseAnalyzer.h.
Referenced by ~TPulseAnalyzer(), DrawRFFit(), fit_rf(), and get_sin_par().
T0RANGE
int TPulseAnalyzer::T0RANGE private
Definition at line 187 of file TPulseAnalyzer.h.
Referenced by Clear(), fit_newT0(), get_baseline_fin(), get_linear_T0(), get_parabolic_T0(), get_smooth_T0(), GetQuickPara(), good_baseline(), and SetData().