GRSISort: TCompiledHistograms Class Reference
TCompiledHistograms Class Reference
Detailed Description
Definition at line 21 of file TCompiledHistograms.h.
Public Member Functions
TCompiledHistograms ()
TCompiledHistograms (std::string input_lib, std::string func_name)
void AddCutFile (TFile *cut_file)
void ClearHistograms ()
void Fill (std::shared_ptr< const TFragment > frag)
void Fill (std::shared_ptr< TUnpackedEvent > detectors)
TDirectory * GetDefaultDirectory ()
TList * GetGates ()
std::string GetLibraryName () const
TList * GetObjects ()
void Load (std::string libname, std::string func_name)
void Reload ()
void SetDefaultDirectory (TDirectory *dir)
Int_t Write (const char *name=nullptr, Int_t option=0, Int_t bufsize=0) override
Private Member Functions
ClassDefOverride (TCompiledHistograms, 0)
bool file_exists ()
time_t get_timestamp ()
void swap_lib (TCompiledHistograms &other)
Private Attributes
int fCheck_every
std::vector< TFile * > fCut_files
TDirectory * fDefault_directory
void(* fFunc)(TRuntimeObjects &)
std::string fFunc_name
TList fGates
time_t fLast_checked
time_t fLast_modified
std::string fLibname
std::shared_ptr< DynamicLibrary > fLibrary
std::mutex fMutex
TRuntimeObjects fObj
TList fObjects
Constructor & Destructor Documentation
TCompiledHistograms() [1/2]
TCompiledHistograms::TCompiledHistograms ()
Definition at line 23 of file TCompiledHistograms.cxx.
TCompiledHistograms() [2/2]
TCompiledHistograms::TCompiledHistograms (std::string input_lib, std::string func_name)
Definition at line 29 of file TCompiledHistograms.cxx.
References fFunc, fFunc_name, fLast_checked, fLast_modified, fLibname, fLibrary, and get_timestamp().
Member Function Documentation
AddCutFile()
void TCompiledHistograms::AddCutFile (TFile * cut_file)
Definition at line 179 of file TCompiledHistograms.cxx.
References fCut_files.
Referenced by TAnalysisHistLoop::AddCutFile(), and TFragHistLoop::AddCutFile().
ClassDefOverride()
TCompiledHistograms::ClassDefOverride (TCompiledHistograms , 0) private
ClearHistograms()
void TCompiledHistograms::ClearHistograms ()
Definition at line 46 of file TCompiledHistograms.cxx.
References fMutex, fObjects, and hist.
Referenced by TAnalysisHistLoop::ClearHistograms(), and TFragHistLoop::ClearHistograms().
file_exists()
bool TCompiledHistograms::file_exists () private
Definition at line 78 of file TCompiledHistograms.cxx.
References fLibname.
Referenced by Reload().
Fill() [1/2]
void TCompiledHistograms::Fill (std::shared_ptr< const TFragment > frag)
Definition at line 139 of file TCompiledHistograms.cxx.
References fCheck_every, fDefault_directory, fFunc, fLast_checked, fLibrary, fMutex, fObj, Reload(), TRuntimeObjects::SetDirectory(), and TRuntimeObjects::SetFragment().
Referenced by TAnalysisHistLoop::Iteration(), and TFragHistLoop::Iteration().
Fill() [2/2]
void TCompiledHistograms::Fill (std::shared_ptr< TUnpackedEvent > detectors)
Definition at line 159 of file TCompiledHistograms.cxx.
References fCheck_every, fDefault_directory, fFunc, fLast_checked, fLibrary, fMutex, fObj, Reload(), TRuntimeObjects::SetDetectors(), and TRuntimeObjects::SetDirectory().
get_timestamp()
time_t TCompiledHistograms::get_timestamp () private
Definition at line 71 of file TCompiledHistograms.cxx.
References fLibname.
Referenced by TCompiledHistograms(), and Reload().
GetDefaultDirectory()
TDirectory * TCompiledHistograms::GetDefaultDirectory () inline
Definition at line 36 of file TCompiledHistograms.h.
References fDefault_directory.
GetGates()
TList * TCompiledHistograms::GetGates () inline
Definition at line 41 of file TCompiledHistograms.h.
References fGates.
Referenced by TAnalysisHistLoop::GetGates(), and TFragHistLoop::GetGates().
GetLibraryName()
std::string TCompiledHistograms::GetLibraryName () const inline
Definition at line 33 of file TCompiledHistograms.h.
References fLibname.
Referenced by TAnalysisHistLoop::GetLibraryName(), and TFragHistLoop::GetLibraryName().
GetObjects()
TList * TCompiledHistograms::GetObjects () inline
Definition at line 40 of file TCompiledHistograms.h.
References fObjects.
Referenced by TAnalysisHistLoop::GetObjects(), and TFragHistLoop::GetObjects().
Load()
void TCompiledHistograms::Load (std::string libname, std::string func_name)
Definition at line 113 of file TCompiledHistograms.cxx.
References swap_lib().
Referenced by TAnalysisHistLoop::LoadLibrary(), and TFragHistLoop::LoadLibrary().
Reload()
void TCompiledHistograms::Reload ()
Definition at line 119 of file TCompiledHistograms.cxx.
References fFunc_name, file_exists(), fLast_checked, fLast_modified, fLibname, get_timestamp(), and swap_lib().
Referenced by Fill(), and Fill().
SetDefaultDirectory()
void TCompiledHistograms::SetDefaultDirectory (TDirectory * dir)
Definition at line 186 of file TCompiledHistograms.cxx.
References fDefault_directory, fObjects, and hist.
Referenced by TAnalysisHistLoop::OpenFile(), and TFragHistLoop::OpenFile().
swap_lib()
void TCompiledHistograms::swap_lib (TCompiledHistograms & other) private
Definition at line 128 of file TCompiledHistograms.cxx.
References fCheck_every, fFunc, fFunc_name, fLast_checked, fLast_modified, fLibname, and fLibrary.
Referenced by Load(), and Reload().
Write()
Int_t TCompiledHistograms::Write (const char * name = nullptr, Int_t option = 0, Int_t bufsize = 0) override
Definition at line 84 of file TCompiledHistograms.cxx.
References fObjects.
Referenced by TAnalysisHistLoop::Write(), and TFragHistLoop::Write().
Member Data Documentation
fCheck_every
int TCompiledHistograms::fCheck_every private
Definition at line 62 of file TCompiledHistograms.h.
Referenced by Fill(), Fill(), and swap_lib().
fCut_files
std::vector<TFile*> TCompiledHistograms::fCut_files private
Definition at line 66 of file TCompiledHistograms.h.
Referenced by AddCutFile().
fDefault_directory
TDirectory* TCompiledHistograms::fDefault_directory private
Definition at line 68 of file TCompiledHistograms.h.
Referenced by Fill(), Fill(), GetDefaultDirectory(), and SetDefaultDirectory().
fFunc
void(* TCompiledHistograms::fFunc) (TRuntimeObjects &) private
Definition at line 58 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), Fill(), Fill(), and swap_lib().
fFunc_name
std::string TCompiledHistograms::fFunc_name private
Definition at line 53 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), Reload(), and swap_lib().
fGates
TList TCompiledHistograms::fGates private
Definition at line 65 of file TCompiledHistograms.h.
Referenced by GetGates().
fLast_checked
time_t TCompiledHistograms::fLast_checked private
Definition at line 60 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), Fill(), Fill(), Reload(), and swap_lib().
fLast_modified
time_t TCompiledHistograms::fLast_modified private
Definition at line 59 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), Reload(), and swap_lib().
fLibname
std::string TCompiledHistograms::fLibname private
Definition at line 52 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), file_exists(), get_timestamp(), GetLibraryName(), Reload(), and swap_lib().
fLibrary
std::shared_ptr<DynamicLibrary> TCompiledHistograms::fLibrary private
Definition at line 55 of file TCompiledHistograms.h.
Referenced by TCompiledHistograms(), Fill(), Fill(), and swap_lib().
fMutex
std::mutex TCompiledHistograms::fMutex private
Definition at line 56 of file TCompiledHistograms.h.
Referenced by ClearHistograms(), Fill(), and Fill().
fObj
TRuntimeObjects TCompiledHistograms::fObj private
Definition at line 70 of file TCompiledHistograms.h.
Referenced by Fill(), and Fill().
fObjects
TList TCompiledHistograms::fObjects private
Definition at line 64 of file TCompiledHistograms.h.
Referenced by ClearHistograms(), GetObjects(), SetDefaultDirectory(), and Write().