GRSISort: TGRSIMapException< key_type > Class Template Reference
TGRSIMapException< key_type > Class Template Reference
Sorting
Detailed Description
template<typename key_type>
class TGRSIMapException< key_type >
This class re-implements std::map with more explicit exceptions replacing out-of-range exceptions.
Definition at line 101 of file TGRSIMap.h.
Public Member Functions
template<typename mapped_type , typename key_compare , typename allocator_type >
TGRSIMapException (const key_type key, const std::map< key_type, mapped_type, key_compare, allocator_type > &map)
std::string detail () const noexcept
const char * what () const noexcept override
Private Attributes
key_type fKey
std::vector< key_type > fKeys
Constructor & Destructor Documentation
TGRSIMapException()
template<typename key_type > template<typename mapped_type , typename key_compare , typename allocator_type > TGRSIMapException< key_type >::TGRSIMapException (const key_type key, const std::map< key_type, mapped_type, key_compare, allocator_type > & map) inline
Definition at line 104 of file TGRSIMap.h.
References TGRSIMapException< key_type >::fKeys.
Member Function Documentation
detail()
template<typename key_type > std::string TGRSIMapException< key_type >::detail () const inline noexcept
Definition at line 112 of file TGRSIMap.h.
References TGRSIMapException< key_type >::fKey, and TGRSIMapException< key_type >::fKeys.
Referenced by Analyze(), TGRSISelector::Process(), TGRSIFrame::Run(), and TGRSIMapException< key_type >::what().
what()
template<typename key_type > const char * TGRSIMapException< key_type >::what () const inline override noexcept
Definition at line 126 of file TGRSIMap.h.
References TGRSIMapException< key_type >::detail().
Member Data Documentation
fKey
template<typename key_type > key_type TGRSIMapException< key_type >::fKey private
Definition at line 129 of file TGRSIMap.h.
Referenced by TGRSIMapException< key_type >::detail().
fKeys
template<typename key_type > std::vector<key_type> TGRSIMapException< key_type >::fKeys private
Definition at line 130 of file TGRSIMap.h.
Referenced by TGRSIMapException< key_type >::TGRSIMapException(), and TGRSIMapException< key_type >::detail().