GRSISort: GH2Base Class Reference
GH2Base Class Reference abstract
Detailed Description
Definition at line 23 of file GH2Base.h.
Classes
class iterator
Public Member Functions
GH2Base ()
GH2Base (const GH2Base &)=default
GH2Base (GH2Base &&) noexcept=default
virtual ~GH2Base ()
iterator begin ()
iterator end ()
GH1D * GetNext (const GH1D *curr, bool DrawEmpty=true)
GH1D * GetNextSummary (const GH1D *curr, bool DrawEmpty=false)
GH1D * GetPrevious (const GH1D *curr, bool DrawEmpty=true)
GH1D * GetPrevSummary (const GH1D *curr, bool DrawEmpty=false)
TList * GetProjections ()
bool GetSummary () const
EDirection GetSummaryDirection () const
TList * GetSummaryProjections ()
virtual TH2 * GetTH2 ()=0
virtual void GH2Clear (Option_t *opt="")
GH1D * GH2ProjectionX (const char *name="_px", int firstbin=0, int lastbin=-1, Option_t *option="", bool KeepEmpty=false)
GH1D * GH2ProjectionY (const char *name="_py", int firstbin=0, int lastbin=-1, Option_t *option="", bool KeepEmpty=false)
GH2Base & operator= (const GH2Base &)=default
GH2Base & operator= (GH2Base &&) noexcept=default
GH1D * Projection_Background (int axis=0, int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
GH1D * ProjectionX_Background (int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
GH1D * ProjectionY_Background (int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
void SetSummary (bool is_summary=true)
void SetSummaryDirection (EDirection dir)
Private Member Functions
void Init ()
Private Attributes
bool fIsSummary {false}
TList * fProjections {nullptr}
EDirection fSummaryDirection {EDirection::kXDirection}
TList * fSummaryProjections {nullptr}
Constructor & Destructor Documentation
GH2Base() [1/3]
GH2Base::GH2Base () inline
Definition at line 26 of file GH2Base.h.
References Init().
GH2Base() [2/3]
GH2Base::GH2Base (const GH2Base &) default
GH2Base() [3/3]
GH2Base::GH2Base (GH2Base &&) default noexcept
~GH2Base()
GH2Base::~GH2Base () virtual
Definition at line 10 of file GH2Base.cxx.
References fProjections, and fSummaryProjections.
Member Function Documentation
begin()
iterator GH2Base::begin () inline
Definition at line 111 of file GH2Base.h.
end()
iterator GH2Base::end () inline
Definition at line 112 of file GH2Base.h.
GetNext()
GH1D * GH2Base::GetNext (const GH1D * curr, bool DrawEmpty = true)
Definition at line 221 of file GH2Base.cxx.
References fIsSummary, fProjections, and GetNextSummary().
Referenced by GH1D::GetNext(), and GH2Base::iterator::operator++().
GetNextSummary()
GH1D * GH2Base::GetNextSummary (const GH1D * curr, bool DrawEmpty = false)
Definition at line 244 of file GH2Base.cxx.
References fSummaryDirection, fSummaryProjections, GetTH2(), GH2ProjectionX(), GH2ProjectionY(), hist, kXDirection, and kYDirection.
Referenced by GetNext(), and GCanvas::Process2DKeyboardPress().
GetPrevious()
GH1D * GH2Base::GetPrevious (const GH1D * curr, bool DrawEmpty = true)
Definition at line 198 of file GH2Base.cxx.
References fIsSummary, fProjections, and GetPrevSummary().
Referenced by GH1D::GetPrevious().
GetPrevSummary()
GH1D * GH2Base::GetPrevSummary (const GH1D * curr, bool DrawEmpty = false)
Definition at line 294 of file GH2Base.cxx.
References fSummaryDirection, fSummaryProjections, GetTH2(), GH2ProjectionX(), GH2ProjectionY(), hist, kXDirection, and kYDirection.
Referenced by GetPrevious().
GetProjections()
TList * GH2Base::GetProjections () inline
Definition at line 60 of file GH2Base.h.
References fProjections.
Referenced by GCanvas::Process2DKeyboardPress().
GetSummary()
bool GH2Base::GetSummary () const inline
Definition at line 64 of file GH2Base.h.
References fIsSummary.
GetSummaryDirection()
EDirection GH2Base::GetSummaryDirection () const inline
Definition at line 67 of file GH2Base.h.
References fSummaryDirection.
GetSummaryProjections()
TList * GH2Base::GetSummaryProjections () inline
Definition at line 61 of file GH2Base.h.
References fSummaryProjections.
GetTH2()
virtual TH2 * GH2Base::GetTH2 () pure virtual
Implemented in GH2D, and GH2I.
Referenced by GetNextSummary(), GetPrevSummary(), GH2ProjectionX(), GH2ProjectionY(), and Projection_Background().
GH2Clear()
void GH2Base::GH2Clear (Option_t * opt = "") virtual
Definition at line 24 of file GH2Base.cxx.
References fProjections, and fSummaryProjections.
Referenced by GH2D::Clear(), and GH2I::Clear().
GH2ProjectionX()
GH1D * GH2Base::GH2ProjectionX (const char * name = "_px", int firstbin = 0, int lastbin = -1, Option_t * option = "", bool KeepEmpty = false)
Definition at line 90 of file GH2Base.cxx.
References fIsSummary, fProjections, fSummaryProjections, GetTH2(), GH1D::SetParent(), and GH1D::SetProjectionAxis().
Referenced by GetNextSummary(), GetPrevSummary(), GH2D::ProjectionX(), and GH2I::ProjectionX().
GH2ProjectionY()
GH1D * GH2Base::GH2ProjectionY (const char * name = "_py", int firstbin = 0, int lastbin = -1, Option_t * option = "", bool KeepEmpty = false)
Definition at line 144 of file GH2Base.cxx.
References fIsSummary, fProjections, fSummaryProjections, GetTH2(), GH1D::SetParent(), and GH1D::SetProjectionAxis().
Referenced by GetNextSummary(), GetPrevSummary(), GH2D::ProjectionY(), and GH2I::ProjectionY().
Init()
void GH2Base::Init () private
Definition at line 16 of file GH2Base.cxx.
References fIsSummary, fProjections, fSummaryDirection, fSummaryProjections, and kXDirection.
Referenced by GH2Base().
operator=() [1/2]
GH2Base & GH2Base::operator= (const GH2Base &) default
operator=() [2/2]
GH2Base & GH2Base::operator= (GH2Base &&) default noexcept
Projection_Background()
GH1D * GH2Base::Projection_Background (int axis = 0, int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground)
Definition at line 31 of file GH2Base.cxx.
References fProjections, GetTH2(), and kNoBackground.
Referenced by ProjectionX_Background(), and ProjectionY_Background().
ProjectionX_Background()
GH1D * GH2Base::ProjectionX_Background (int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground)
Definition at line 138 of file GH2Base.cxx.
References Projection_Background().
Referenced by GH1D::Project_Background().
ProjectionY_Background()
GH1D * GH2Base::ProjectionY_Background (int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground)
Definition at line 192 of file GH2Base.cxx.
References Projection_Background().
Referenced by GH1D::Project_Background().
SetSummary()
void GH2Base::SetSummary (bool is_summary = true) inline
Definition at line 63 of file GH2Base.h.
References fIsSummary.
Referenced by GCanvas::Process2DKeyboardPress().
SetSummaryDirection()
void GH2Base::SetSummaryDirection (EDirection dir) inline
Definition at line 66 of file GH2Base.h.
References fSummaryDirection.
Referenced by GCanvas::Process2DKeyboardPress().
Member Data Documentation
fIsSummary
bool GH2Base::fIsSummary {false} private
Definition at line 119 of file GH2Base.h.
Referenced by GetNext(), GetPrevious(), GetSummary(), GH2ProjectionX(), GH2ProjectionY(), Init(), and SetSummary().
fProjections
TList* GH2Base::fProjections {nullptr} private
Definition at line 116 of file GH2Base.h.
Referenced by ~GH2Base(), GetNext(), GetPrevious(), GetProjections(), GH2Clear(), GH2ProjectionX(), GH2ProjectionY(), Init(), and Projection_Background().
fSummaryDirection
EDirection GH2Base::fSummaryDirection {EDirection::kXDirection} private
Definition at line 120 of file GH2Base.h.
Referenced by GetNextSummary(), GetPrevSummary(), GetSummaryDirection(), Init(), and SetSummaryDirection().
fSummaryProjections
TList* GH2Base::fSummaryProjections {nullptr} private
Definition at line 118 of file GH2Base.h.
Referenced by ~GH2Base(), GetNextSummary(), GetPrevSummary(), GetSummaryProjections(), GH2Clear(), GH2ProjectionX(), GH2ProjectionY(), and Init().