GRSISort: TGRSIProof Class Reference
TGRSIProof Class Reference
Sorting
Detailed Description
This class allows proof to work with GRSI
Deprecated
Since PROOF is deprecated it is recommended to use TGRSIFrame instead.
Definition at line 44 of file TGRSIProof.h.
Public Member Functions
TGRSIProof ()=default
TGRSIProof (const TGRSIProof &)=delete
TGRSIProof (TGRSIProof &&) noexcept=delete
~TGRSIProof ()=default
void LoadLibsIntoProof ()
TGRSIProof & operator= (const TGRSIProof &)=delete
TGRSIProof & operator= (TGRSIProof &&) noexcept=delete
Static Public Member Functions
static TGRSIProof * Open (const char *worker="")
Constructor & Destructor Documentation
TGRSIProof() [1/3]
TGRSIProof::TGRSIProof () default
TGRSIProof() [2/3]
TGRSIProof::TGRSIProof (const TGRSIProof &) delete
TGRSIProof() [3/3]
TGRSIProof::TGRSIProof (TGRSIProof &&) delete noexcept
~TGRSIProof()
TGRSIProof::~TGRSIProof () default
Member Function Documentation
LoadLibsIntoProof()
void TGRSIProof::LoadLibsIntoProof () inline
Definition at line 60 of file TGRSIProof.h.
References DYELLOW, TGRSIOptions::Get(), TSingleton< TParserLibrary >::Get(), TParserLibrary::Load(), TGRSIOptions::ParserLibrary(), and RESET_COLOR.
Open()
static TGRSIProof * TGRSIProof::Open (const char * worker = "") inline static
Definition at line 53 of file TGRSIProof.h.
Referenced by main().
operator=() [1/2]
TGRSIProof & TGRSIProof::operator= (const TGRSIProof &) delete
operator=() [2/2]
TGRSIProof & TGRSIProof::operator= (TGRSIProof &&) delete noexcept