GRSISort: TSingleton< T > Class Template Reference
TSingleton< T > Class Template Reference
Sorting
Detailed Description
template<class T>
class TSingleton< T >
This class is intended as a base class for singletons, especially those that are written to file. The Get() function is written such that it reads the class from file if needed. This is the case if it hasn't been read yet, or if the gDirectory has been changed. This means in a loop over different input files, Get() will always return the info of the current file.
Definition at line 31 of file TSingleton.h.
#include <TSingleton.h>
Static Public Member Functions
static T * AddCurrent ()
static T * Get (bool verbose=false)
static T * GetAll ()
static void PrintDirectory ()
static void Set (T *val)
Protected Member Functions
TSingleton ()
~TSingleton ()
Static Private Attributes
static TDirectory * fDir = nullptr
static T * fSingleton = nullptr
Member Function Documentation
AddCurrent()
template<class T > static T * TSingleton< T >::AddCurrent () inline static
Definition at line 137 of file TSingleton.h.
References CYAN, TSingleton< T >::fDir, TSingleton< T >::fSingleton, TSingleton< T >::Get(), and RESET_COLOR.
Get()
template<class T > static T * TSingleton< T >::Get (bool verbose = false) inline static
Definition at line 34 of file TSingleton.h.
References CYAN, TSingleton< T >::fDir, TSingleton< T >::fSingleton, RESET_COLOR, and TSingleton< T >::Set().
Referenced by TSingleton< T >::AddCurrent(), and TSingleton< T >::GetAll().
GetAll()
template<class T > static T * TSingleton< T >::GetAll () inline static
Definition at line 62 of file TSingleton.h.
References TSingleton< T >::fDir, TSingleton< T >::fSingleton, and TSingleton< T >::Get().
PrintDirectory()
template<class T > static void TSingleton< T >::PrintDirectory () inline static
Definition at line 167 of file TSingleton.h.
References TSingleton< T >::fDir, and TSingleton< T >::fSingleton.
Referenced by TRunInfo::Print().
Set()
template<class T > static void TSingleton< T >::Set (T * val) inline static
Definition at line 129 of file TSingleton.h.
References TSingleton< T >::fSingleton.
Referenced by TSingleton< T >::Get().