GRSISort: TRWPeak Class Reference
TRWPeak Class Reference
Fitting & Analysis
Detailed Description
This class is used to fit RadWare like peaks in data
Definition at line 30 of file TRWPeak.h.
Public Member Functions
TRWPeak ()=default
TRWPeak (const TRWPeak &)=default
TRWPeak (Double_t centroid)
TRWPeak (TRWPeak &&) noexcept=default
~TRWPeak ()=default
Double_t Area () const
Double_t AreaErr () const
Double_t Centroid () const override
void Centroid (const Double_t &centroid) override
Double_t CentroidErr () const override
void Draw (Option_t *opt="") override
virtual void DrawBackground (Option_t *opt="")
virtual void DrawComponents (Option_t *opt="")
virtual Double_t FWHM ()
virtual Double_t FWHMErr ()
TF1 * GetBackgroundFunction ()
Double_t GetChi2 () const
TF1 * GetFitFunction () const
TF1 * GetGlobalBackground () const
Color_t GetLineColor ()
Style_t GetLineStyle ()
Double_t GetNDF () const
Int_t GetNParameters () const
TF1 * GetPeakFunction () const
Double_t GetReducedChi2 () const
void InitializeParameters (TH1 *hist, const double &rangeLow, const double &rangeHigh) override
void InitParNames () override
bool IsBackgroundParameter (const Int_t &par) const
bool IsPeakParameter (const Int_t &par) const
TRWPeak & operator= (const TRWPeak &)=default
TRWPeak & operator= (TRWPeak &&) noexcept=default
bool ParameterSetByUser (int par)
void Print (Option_t *="") const override
virtual void PrintParameters () const
void SetArea (const Double_t &area)
void SetAreaErr (const Double_t &area_err)
void SetGlobalBackground (TF1 *background)
void SetLineColor (Color_t color)
void SetLineStyle (Style_t style)
void SetListOfBGPar (const std::vector< bool > &list_of_bg_par)
Double_t Sigma () const override
Double_t SigmaErr () const override
void UpdateBackgroundParameters ()
void UpdatePeakParameters ()
Double_t Width () const override
Protected Member Functions
Double_t BackgroundFunction (Double_t *dim, Double_t *par) override
Double_t PeakFunction (Double_t *dim, Double_t *par) override
virtual Double_t PeakOnGlobalFunction (Double_t *dim, Double_t *par)
void SetChi2 (const Double_t &chi2)
void SetFitFunction (TF1 *function)
void SetNDF (const Int_t &ndf)
void SetPeakFunction (TF1 *function)
Double_t TotalFunction (Double_t *dim, Double_t *par)
Private Attributes
Double_t fArea {-0.1}
Double_t fAreaErr {0.0}
TF1 * fBackgroundFunction {nullptr}
Double_t fChi2 {std::numeric_limits<Double_t>::quiet_NaN()}
TF1 * fGlobalBackground {nullptr}
std::vector< bool > fListOfBGPars
Int_t fNDF {0}
TF1 * fPeakFunction {nullptr}
TF1 * fPeakOnGlobal {nullptr}
TF1 * fTotalFunction {nullptr}
Constructor & Destructor Documentation
TRWPeak() [1/4]
TRWPeak::TRWPeak () default
TRWPeak() [2/4]
TRWPeak::TRWPeak (Double_t centroid) inline explicit
Definition at line 34 of file TRWPeak.h.
References Centroid().
TRWPeak() [3/4]
TRWPeak::TRWPeak (const TRWPeak &) default
TRWPeak() [4/4]
TRWPeak::TRWPeak (TRWPeak &&) default noexcept
~TRWPeak()
TRWPeak::~TRWPeak () default
Member Function Documentation
Area()
Double_t TSinglePeak::Area () const inline inherited
Definition at line 57 of file TSinglePeak.h.
References TSinglePeak::fArea.
Referenced by TSourceTab::Good(), main(), and TSinglePeak::Print().
AreaErr()
Double_t TSinglePeak::AreaErr () const inline inherited
Definition at line 58 of file TSinglePeak.h.
References TSinglePeak::fAreaErr.
Referenced by TSourceTab::Good(), main(), and TSinglePeak::Print().
BackgroundFunction()
Double_t TRWPeak::BackgroundFunction (Double_t * dim, Double_t * par) override protected virtual
Reimplemented from TSinglePeak.
Definition at line 87 of file TRWPeak.cxx.
Centroid() [1/2]
Double_t TRWPeak::Centroid () const override virtual
Implements TSinglePeak.
Definition at line 60 of file TRWPeak.cxx.
References TSinglePeak::GetFitFunction().
Referenced by TRWPeak().
Centroid() [2/2]
void TRWPeak::Centroid (const Double_t & centroid) override virtual
Implements TSinglePeak.
Definition at line 3 of file TRWPeak.cxx.
References TSinglePeak::GetFitFunction(), InitParNames(), PeakFunction(), TSinglePeak::SetFitFunction(), TSinglePeak::SetListOfBGPar(), TSinglePeak::SetPeakFunction(), and TSinglePeak::TotalFunction().
CentroidErr()
Double_t TRWPeak::CentroidErr () const override virtual
Implements TSinglePeak.
Definition at line 65 of file TRWPeak.cxx.
References TSinglePeak::GetFitFunction().
Draw()
void TSinglePeak::Draw (Option_t * opt = "") override inherited
Definition at line 106 of file TSinglePeak.cxx.
References TSinglePeak::fGlobalBackground, TSinglePeak::fPeakOnGlobal, TSinglePeak::fTotalFunction, and TSinglePeak::PeakOnGlobalFunction().
Referenced by TBGSubtraction::DrawPeak().
DrawBackground()
virtual void TSinglePeak::DrawBackground (Option_t * opt = "") inline virtual inherited
Definition at line 71 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
DrawComponents()
void TSinglePeak::DrawComponents (Option_t * opt = "") virtual inherited
This behaves like the draw function except each daughter class decides how to break the draw into multiple components. This means that we should delegate this task to the daughter class.
Reimplemented in TAB3Peak, and TABPeak.
Definition at line 71 of file TSinglePeak.cxx.
FWHM()
Double_t TSinglePeak::FWHM () virtual inherited
Return the full width at half-maximum.
Definition at line 77 of file TSinglePeak.cxx.
References TSinglePeak::Centroid(), TSinglePeak::fPeakFunction, TSinglePeak::Sigma(), and TSinglePeak::UpdatePeakParameters().
Referenced by TSinglePeak::FWHMErr().
FWHMErr()
Double_t TSinglePeak::FWHMErr () virtual inherited
Return the uncertainty in the full width at half-maximum. Since it is complicated to do this without knowledge of the underlying fit function, we simply assume that the (relative) uncertainty in the FWHM is the same as the uncertainty in sigma.
Definition at line 92 of file TSinglePeak.cxx.
References TSinglePeak::FWHM(), TSinglePeak::Sigma(), and TSinglePeak::SigmaErr().
GetBackgroundFunction()
TF1 * TSinglePeak::GetBackgroundFunction () inherited
Definition at line 28 of file TSinglePeak.cxx.
References TSinglePeak::BackgroundFunction(), TSinglePeak::fBackgroundFunction, and TSinglePeak::fTotalFunction.
GetChi2()
Double_t TSinglePeak::GetChi2 () const inline inherited
Definition at line 91 of file TSinglePeak.h.
References TSinglePeak::fChi2.
GetFitFunction()
TF1 * TSinglePeak::GetFitFunction () const inline inherited
Definition at line 78 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by TGauss::TGauss(), TAB3Peak::Centroid(), TAB3Peak::Centroid(), TABPeak::Centroid(), TABPeak::Centroid(), TGauss::Centroid(), TGauss::Centroid(), Centroid(), Centroid(), TAB3Peak::CentroidErr(), TABPeak::CentroidErr(), TGauss::CentroidErr(), CentroidErr(), TAB3Peak::DrawComponents(), TABPeak::DrawComponents(), TAB3Peak::InitializeParameters(), TABPeak::InitializeParameters(), TGauss::InitializeParameters(), InitializeParameters(), TAB3Peak::InitParNames(), TABPeak::InitParNames(), TGauss::InitParNames(), InitParNames(), main(), TAB3Peak::OneHitPeakOnGlobalFunction(), TABPeak::OneHitPeakOnGlobalFunction(), TAB3Peak::Sigma(), TABPeak::Sigma(), TGauss::Sigma(), Sigma(), TAB3Peak::SigmaErr(), TABPeak::SigmaErr(), TGauss::SigmaErr(), SigmaErr(), TAB3Peak::ThreeHitPeakOnGlobalFunction(), TAB3Peak::TwoHitPeakOnGlobalFunction(), TABPeak::TwoHitPeakOnGlobalFunction(), TAB3Peak::Width(), TABPeak::Width(), and Width().
GetGlobalBackground()
TF1 * TSinglePeak::GetGlobalBackground () const inline inherited
Definition at line 80 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
Referenced by TAB3Peak::DrawComponents(), TABPeak::DrawComponents(), TAB3Peak::OneHitPeakOnGlobalFunction(), TABPeak::OneHitPeakOnGlobalFunction(), TAB3Peak::ThreeHitPeakOnGlobalFunction(), TAB3Peak::TwoHitPeakOnGlobalFunction(), and TABPeak::TwoHitPeakOnGlobalFunction().
GetLineColor()
Color_t TSinglePeak::GetLineColor () inline inherited
Definition at line 100 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by TAB3Peak::DrawComponents(), and TABPeak::DrawComponents().
GetLineStyle()
Style_t TSinglePeak::GetLineStyle () inline inherited
Definition at line 101 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
GetNDF()
Double_t TSinglePeak::GetNDF () const inline inherited
Definition at line 92 of file TSinglePeak.h.
References TSinglePeak::fNDF.
GetNParameters()
Int_t TSinglePeak::GetNParameters () const inherited
Definition at line 20 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
GetPeakFunction()
TF1 * TSinglePeak::GetPeakFunction () const inline inherited
Definition at line 79 of file TSinglePeak.h.
References TSinglePeak::fPeakFunction.
GetReducedChi2()
Double_t TSinglePeak::GetReducedChi2 () const inline inherited
Definition at line 93 of file TSinglePeak.h.
References TSinglePeak::fChi2, and TSinglePeak::fNDF.
Referenced by main().
InitializeParameters()
void TRWPeak::InitializeParameters (TH1 * hist, const double & rangeLow, const double & rangeHigh) override virtual
Makes initial guesses at parameters for the fit base on the histogram.
Reimplemented from TSinglePeak.
Definition at line 23 of file TRWPeak.cxx.
References TSinglePeak::GetFitFunction(), and TSinglePeak::ParameterSetByUser().
InitParNames()
void TRWPeak::InitParNames () override virtual
Reimplemented from TSinglePeak.
Definition at line 13 of file TRWPeak.cxx.
References TSinglePeak::GetFitFunction().
Referenced by Centroid().
IsBackgroundParameter()
bool TSinglePeak::IsBackgroundParameter (const Int_t & par) const inherited
Definition at line 4 of file TSinglePeak.cxx.
References TSinglePeak::fListOfBGPars.
Referenced by TSinglePeak::IsPeakParameter().
IsPeakParameter()
bool TSinglePeak::IsPeakParameter (const Int_t & par) const inherited
Definition at line 15 of file TSinglePeak.cxx.
References TSinglePeak::IsBackgroundParameter().
operator=() [1/2]
TRWPeak & TRWPeak::operator= (const TRWPeak &) default
operator=() [2/2]
TRWPeak & TRWPeak::operator= (TRWPeak &&) default noexcept
ParameterSetByUser()
bool TSinglePeak::ParameterSetByUser (int par) inherited
This function checks if a parameter or its limits have been set to a non-zero value. In case that the user fixed a parameter to be zero, the limits are non-zero, so this case is covered as well.
Definition at line 129 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
Referenced by TAB3Peak::InitializeParameters(), TABPeak::InitializeParameters(), TGauss::InitializeParameters(), and InitializeParameters().
PeakFunction()
Double_t TRWPeak::PeakFunction (Double_t * dim, Double_t * par) override protected virtual
Reimplemented from TSinglePeak.
Definition at line 70 of file TRWPeak.cxx.
Referenced by Centroid().
PeakOnGlobalFunction()
Double_t TSinglePeak::PeakOnGlobalFunction (Double_t * dim, Double_t * par) protected virtual inherited
Definition at line 99 of file TSinglePeak.cxx.
References TSinglePeak::fGlobalBackground, TSinglePeak::fTotalFunction, and TSinglePeak::PeakFunction().
Referenced by TSinglePeak::Draw().
Print()
void TSinglePeak::Print (Option_t * = "") const override inherited
Definition at line 37 of file TSinglePeak.cxx.
References TSinglePeak::Area(), TSinglePeak::AreaErr(), TSinglePeak::Centroid(), and TSinglePeak::CentroidErr().
PrintParameters()
void TSinglePeak::PrintParameters () const virtual inherited
Definition at line 45 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
SetArea()
void TSinglePeak::SetArea (const Double_t & area) inline inherited
Definition at line 54 of file TSinglePeak.h.
References TSinglePeak::fArea.
SetAreaErr()
void TSinglePeak::SetAreaErr (const Double_t & area_err) inline inherited
Definition at line 55 of file TSinglePeak.h.
References TSinglePeak::fAreaErr.
SetChi2()
void TSinglePeak::SetChi2 (const Double_t & chi2) inline protected inherited
Definition at line 109 of file TSinglePeak.h.
References TSinglePeak::fChi2.
SetFitFunction()
void TSinglePeak::SetFitFunction (TF1 * function) inline protected inherited
Definition at line 112 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by TAB3Peak::Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and Centroid().
SetGlobalBackground()
void TSinglePeak::SetGlobalBackground (TF1 * background) inline inherited
Definition at line 82 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
SetLineColor()
void TSinglePeak::SetLineColor (Color_t color) inline inherited
Definition at line 97 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by TSourceTab::Add().
SetLineStyle()
void TSinglePeak::SetLineStyle (Style_t style) inline inherited
Definition at line 98 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
SetListOfBGPar()
void TSinglePeak::SetListOfBGPar (const std::vector< bool > & list_of_bg_par) inline inherited
Definition at line 51 of file TSinglePeak.h.
References TSinglePeak::fListOfBGPars.
Referenced by TAB3Peak::Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and Centroid().
SetNDF()
void TSinglePeak::SetNDF (const Int_t & ndf) inline protected inherited
Definition at line 110 of file TSinglePeak.h.
References TSinglePeak::fNDF.
SetPeakFunction()
void TSinglePeak::SetPeakFunction (TF1 * function) inline protected inherited
Definition at line 113 of file TSinglePeak.h.
References TSinglePeak::fPeakFunction.
Referenced by TAB3Peak::Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and Centroid().
Sigma()
Double_t TRWPeak::Sigma () const inline override virtual
Implements TSinglePeak.
Definition at line 49 of file TRWPeak.h.
References TSinglePeak::GetFitFunction().
SigmaErr()
Double_t TRWPeak::SigmaErr () const inline override virtual
Implements TSinglePeak.
Definition at line 50 of file TRWPeak.h.
References TSinglePeak::GetFitFunction().
TotalFunction()
Double_t TSinglePeak::TotalFunction (Double_t * dim, Double_t * par) protected inherited
Definition at line 56 of file TSinglePeak.cxx.
References TSinglePeak::BackgroundFunction(), and TSinglePeak::PeakFunction().
Referenced by TAB3Peak::Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and Centroid().
UpdateBackgroundParameters()
void TSinglePeak::UpdateBackgroundParameters () inherited
Definition at line 66 of file TSinglePeak.cxx.
References TSinglePeak::fBackgroundFunction, and TSinglePeak::fTotalFunction.
UpdatePeakParameters()
void TSinglePeak::UpdatePeakParameters () inherited
Definition at line 61 of file TSinglePeak.cxx.
References TSinglePeak::fPeakFunction, and TSinglePeak::fTotalFunction.
Referenced by TSinglePeak::FWHM().
Width()
Double_t TRWPeak::Width () const inline override virtual
Implements TSinglePeak.
Definition at line 48 of file TRWPeak.h.
References TSinglePeak::GetFitFunction().
Member Data Documentation
fArea
Double_t TSinglePeak::fArea {-0.1} private inherited
Definition at line 123 of file TSinglePeak.h.
Referenced by TSinglePeak::Area(), and TSinglePeak::SetArea().
fAreaErr
Double_t TSinglePeak::fAreaErr {0.0} private inherited
Definition at line 124 of file TSinglePeak.h.
Referenced by TSinglePeak::AreaErr(), and TSinglePeak::SetAreaErr().
fBackgroundFunction
TF1* TSinglePeak::fBackgroundFunction {nullptr} private inherited
Definition at line 117 of file TSinglePeak.h.
Referenced by TSinglePeak::GetBackgroundFunction(), and TSinglePeak::UpdateBackgroundParameters().
fChi2
Double_t TSinglePeak::fChi2 {std::numeric_limits<Double_t>::quiet_NaN()} private inherited
Definition at line 125 of file TSinglePeak.h.
Referenced by TSinglePeak::GetChi2(), TSinglePeak::GetReducedChi2(), and TSinglePeak::SetChi2().
fGlobalBackground
TF1* TSinglePeak::fGlobalBackground {nullptr} private inherited
Definition at line 118 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw(), TSinglePeak::DrawBackground(), TSinglePeak::GetGlobalBackground(), TSinglePeak::PeakOnGlobalFunction(), and TSinglePeak::SetGlobalBackground().
fListOfBGPars
std::vector<bool> TSinglePeak::fListOfBGPars private inherited
Definition at line 122 of file TSinglePeak.h.
Referenced by TSinglePeak::IsBackgroundParameter(), and TSinglePeak::SetListOfBGPar().
fNDF
Int_t TSinglePeak::fNDF {0} private inherited
Definition at line 126 of file TSinglePeak.h.
Referenced by TSinglePeak::GetNDF(), TSinglePeak::GetReducedChi2(), and TSinglePeak::SetNDF().
fPeakFunction
TF1* TSinglePeak::fPeakFunction {nullptr} private inherited
Definition at line 120 of file TSinglePeak.h.
Referenced by TSinglePeak::FWHM(), TSinglePeak::GetPeakFunction(), TSinglePeak::SetPeakFunction(), and TSinglePeak::UpdatePeakParameters().
fPeakOnGlobal
TF1* TSinglePeak::fPeakOnGlobal {nullptr} private inherited
Definition at line 119 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw().
fTotalFunction
TF1* TSinglePeak::fTotalFunction {nullptr} private inherited
Definition at line 116 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw(), TSinglePeak::GetBackgroundFunction(), TSinglePeak::GetFitFunction(), TSinglePeak::GetLineColor(), TSinglePeak::GetLineStyle(), TSinglePeak::GetNParameters(), TSinglePeak::ParameterSetByUser(), TSinglePeak::PeakOnGlobalFunction(), TSinglePeak::PrintParameters(), TSinglePeak::SetFitFunction(), TSinglePeak::SetLineColor(), TSinglePeak::SetLineStyle(), TSinglePeak::UpdateBackgroundParameters(), and TSinglePeak::UpdatePeakParameters().