GRSISort: GHSymD Class Reference
GHSymD Class Reference
Detailed Description
Definition at line 171 of file GHSym.h.
Public Member Functions
GHSymD ()
GHSymD (const char *name, const char *title, Int_t nbins, const Double_t *bins)
GHSymD (const char *name, const char *title, Int_t nbins, const Float_t *bins)
GHSymD (const char *name, const char *title, Int_t nbins, Double_t low, Double_t up)
GHSymD (const GHSymD &)
GHSymD (GHSymD &&) noexcept
~GHSymD ()
void AddBinContent (Int_t bin) override
void AddBinContent (Int_t bin, Double_t w) override
Int_t BufferEmpty (Int_t action=0) override
virtual Int_t BufferFill (Double_t x, Double_t y, Double_t w)
Int_t BufferFill (Double_t, Double_t) override
void Copy (TObject &rh) const override
void Draw (Option_t *option="") override
TH1 * DrawCopy (Option_t *option="", const char *name_postfix="_copy") const override
Int_t Fill (const char *, Double_t) override
virtual Int_t Fill (const char *namex, const char *namey, Double_t w)
Int_t Fill (Double_t x, Double_t y) override
virtual Int_t Fill (Double_t x, Double_t y, Double_t w)
Int_t Fill (Double_t) override
void FillN (Int_t ntimes, const Double_t *x, const Double_t *y, const Double_t *w, Int_t stride=1) override
void FillN (Int_t, const Double_t *, const Double_t *, Int_t) override
void FillRandom (const char *fname, Int_t ntimes=5000, TRandom *rng=nullptr)
void FillRandom (TH1 *h, Int_t ntimes=5000, TRandom *rng=nullptr) override
Int_t FindFirstBinAbove (Double_t threshold=0, Int_t axis=1, Int_t firstBin=1, Int_t lastBin=-1) const override
Int_t FindLastBinAbove (Double_t threshold=0, Int_t axis=1, Int_t firstBin=1, Int_t lastBin=-1) const override
virtual void FitSlices (TF1 *f1=nullptr, Int_t firstbin=0, Int_t lastbin=-1, Int_t cut=0, Option_t *option="QNR", TObjArray *arr=nullptr)
Int_t GetBin (Int_t binx, Int_t biny=0, Int_t binz=0) const override
Double_t GetBinContent (Int_t bin) const override
Double_t GetBinContent (Int_t binx, Int_t biny) const override
Double_t GetBinContent (Int_t binx, Int_t biny, Int_t) const override
virtual Double_t GetBinWithContent2 (Double_t c, Int_t &binx, Int_t &biny, Int_t firstxbin=1, Int_t lastxbin=-1, Int_t firstybin=1, Int_t lastybin=-1, Double_t maxdiff=0) const
Double_t GetCellContent (Int_t binx, Int_t biny) const override
Double_t GetCellError (Int_t binx, Int_t biny) const override
virtual Double_t GetCorrelationFactor (Int_t axis1=1, Int_t axis2=2) const
virtual Double_t GetCovariance (Int_t axis1=1, Int_t axis2=2) const
TH2D * GetMatrix (bool force=false)
virtual void GetRandom2 (Double_t &x, Double_t &y)
void GetStats (Double_t *stats) const override
virtual Double_t Integral (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Option_t *option="") const
virtual Double_t Integral (Int_t, Int_t, Int_t, Int_t, Int_t, Int_t, Option_t *="") const
Double_t Integral (Option_t *option="") const override
virtual Double_t IntegralAndError (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Double_t &error, Option_t *option="") const
Double_t Interpolate (Double_t) const override
Double_t Interpolate (Double_t, Double_t) const override
Double_t Interpolate (Double_t, Double_t, Double_t) const override
Double_t KolmogorovTest (const TH1 *h2, Option_t *option="") const override
Long64_t Merge (TCollection *list) override
GHSymD & operator= (const GHSymD &h1)
GHSymD & operator= (GHSymD &&) noexcept
virtual TProfile * Profile (const char *name="_pf", Int_t firstbin=1, Int_t lastbin=-1, Option_t *option="") const
virtual TH1D * Projection (const char *name="_pr", Int_t firstBin=0, Int_t lastBin=-1, Option_t *option="") const
void PutStats (Double_t *stats) override
virtual GHSym * Rebin2D (Int_t ngroup=2, const char *newname="")
void Reset (Option_t *option="") override
Double_t RetrieveBinContent (Int_t bin) const override
void SetBinContent (Int_t bin, Double_t content) override
void SetBinContent (Int_t binx, Int_t biny, Double_t content) override
void SetBinContent (Int_t binx, Int_t biny, Int_t, Double_t content) override
void SetBinsLength (Int_t n=-1) override
void SetCellContent (Int_t binx, Int_t biny, Double_t content) override
void SetCellError (Int_t binx, Int_t biny, Double_t content) override
virtual void SetShowProjectionX (Int_t nbins=1)
virtual void SetShowProjectionY (Int_t nbins=1)
TH1 * ShowBackground (Int_t niter=20, Option_t *option="same") override
Int_t ShowPeaks (Double_t sigma=2, Option_t *option="", Double_t threshold=0.05) override
void Smooth (Int_t ntimes=1, Option_t *option="") override
void UpdateBinContent (Int_t bin, Double_t content) override
Protected Member Functions
virtual Double_t DoIntegral (Int_t binx1, Int_t binx2, Int_t biny1, Int_t biny2, Double_t &error, Option_t *option, Bool_t doError=kFALSE) const
TH2 * Matrix ()
void Matrix (TH2 *val)
Private Attributes
TH2 * fMatrix {nullptr}
Double_t fTsumwxy {0.}
Double_t fTsumwy {0.}
Double_t fTsumwy2 {0.}
Friends
GHSymD operator* (Float_t c1, GHSymD &h1)
GHSymD operator* (GHSymD &h1, Float_t c1)
GHSymD operator* (GHSymD &h1, GHSymD &h2)
GHSymD operator+ (GHSymD &h1, GHSymD &h2)
GHSymD operator- (GHSymD &h1, GHSymD &h2)
GHSymD operator/ (GHSymD &h1, GHSymD &h2)
Constructor & Destructor Documentation
GHSymD() [1/6]
GHSymD::GHSymD ()
Definition at line 2942 of file GHSym.cxx.
References SetBinsLength().
GHSymD() [2/6]
GHSymD::GHSymD (const char * name, const char * title, Int_t nbins, Double_t low, Double_t up)
Definition at line 2950 of file GHSym.cxx.
GHSymD() [3/6]
GHSymD::GHSymD (const char * name, const char * title, Int_t nbins, const Double_t * bins)
Definition at line 2963 of file GHSym.cxx.
GHSymD() [4/6]
GHSymD::GHSymD (const char * name, const char * title, Int_t nbins, const Float_t * bins)
Definition at line 2971 of file GHSym.cxx.
GHSymD() [5/6]
GHSymD::GHSymD (const GHSymD & rhs)
Definition at line 2979 of file GHSym.cxx.
References Copy().
GHSymD() [6/6]
GHSymD::GHSymD (GHSymD && rhs) noexcept
Definition at line 2985 of file GHSym.cxx.
References GHSym::Copy().
~GHSymD()
GHSymD::~GHSymD () default
Member Function Documentation
AddBinContent() [1/2]
void GHSymD::AddBinContent (Int_t bin) inline override
Definition at line 183 of file GHSym.h.
AddBinContent() [2/2]
void GHSymD::AddBinContent (Int_t bin, Double_t w) inline override
Definition at line 184 of file GHSym.h.
BufferEmpty()
Int_t GHSym::BufferEmpty (Int_t action = 0) override inherited
Fill histogram with all entries in the buffer. action = -1 histogram is reset and refilled from the buffer (called by THistPainter::Paint) action = 0 histogram is filled from the buffer action = 1 histogram is filled and buffer is deleted The buffer is automatically deleted when the number of entries in the buffer is greater than the number of entries in the histogram
Definition at line 77 of file GHSym.cxx.
References GHSym::Fill(), and GHSym::Reset().
Referenced by GHSym::BufferFill(), GetBinContent(), GHSymF::GetBinContent(), GHSym::GetStats(), and GHSym::Merge().
BufferFill() [1/2]
Int_t GHSym::BufferFill (Double_t x, Double_t y, Double_t w) virtual inherited
Definition at line 174 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::Fill(), and GHSym::Reset().
BufferFill() [2/2]
Int_t GHSym::BufferFill (Double_t , Double_t) inline override inherited
Definition at line 26 of file GHSym.h.
Referenced by GHSym::Fill(), and GHSym::Fill().
Copy()
void GHSymD::Copy (TObject & rh) const override
Definition at line 3014 of file GHSym.cxx.
References GHSym::Copy().
Referenced by GHSymD(), and operator=().
DoIntegral()
Double_t GHSym::DoIntegral (Int_t binx1, Int_t binx2, Int_t biny1, Int_t biny2, Double_t & error, Option_t * option, Bool_t doError = kFALSE) const protected virtual inherited
Definition at line 214 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Integral(), and GHSym::IntegralAndError().
Draw()
void GHSymD::Draw (Option_t * option = "") inline override
Definition at line 187 of file GHSym.h.
References GetMatrix().
DrawCopy()
TH1 * GHSymD::DrawCopy (Option_t * option = "", const char * name_postfix = "_copy") const override
Definition at line 3019 of file GHSym.cxx.
Fill() [1/5]
Int_t GHSym::Fill (const char * , Double_t) inline override inherited
Definition at line 30 of file GHSym.h.
References GHSym::Fill().
Referenced by GHSym::Fill().
Fill() [2/5]
Int_t GHSym::Fill (const char * namex, const char * namey, Double_t w) virtual inherited
Definition at line 382 of file GHSym.cxx.
References GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [3/5]
Int_t GHSym::Fill (Double_t x, Double_t y) override inherited
Increment cell defined by x,y by 1.
Definition at line 288 of file GHSym.cxx.
References GHSym::BufferFill(), GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [4/5]
Int_t GHSym::Fill (Double_t x, Double_t y, Double_t w) virtual inherited
Increment cell defined by x,y by 1.
Definition at line 335 of file GHSym.cxx.
References GHSym::BufferFill(), GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [5/5]
Int_t GHSym::Fill (Double_t) override inherited
Definition at line 281 of file GHSym.cxx.
Referenced by GHSym::BufferEmpty(), GHSym::BufferFill(), GHSym::FillN(), GHSym::FillRandom(), and GHSym::Merge().
FillN() [1/2]
void GHSym::FillN (Int_t ntimes, const Double_t * x, const Double_t * y, const Double_t * w, Int_t stride = 1) override inherited
Definition at line 430 of file GHSym.cxx.
References GHSym::Fill().
FillN() [2/2]
void GHSym::FillN (Int_t , const Double_t * , const Double_t * , Int_t) inline override inherited
Definition at line 34 of file GHSym.h.
FillRandom() [1/2]
void GHSym::FillRandom (const char * fname, Int_t ntimes = 5000, TRandom * rng = nullptr) inherited
Definition at line 459 of file GHSym.cxx.
References GHSym::Fill().
FillRandom() [2/2]
void GHSym::FillRandom (TH1 * h, Int_t ntimes = 5000, TRandom * rng = nullptr) override inherited
Definition at line 531 of file GHSym.cxx.
References hist.
FindFirstBinAbove()
Int_t GHSym::FindFirstBinAbove (Double_t threshold = 0, Int_t axis = 1, Int_t firstBin = 1, Int_t lastBin = -1) const override inherited
Definition at line 574 of file GHSym.cxx.
FindLastBinAbove()
Int_t GHSym::FindLastBinAbove (Double_t threshold = 0, Int_t axis = 1, Int_t firstBin = 1, Int_t lastBin = -1) const override inherited
Definition at line 607 of file GHSym.cxx.
FitSlices()
void GHSym::FitSlices (TF1 * f1 = nullptr, Int_t firstbin = 0, Int_t lastbin = -1, Int_t cut = 0, Option_t * option = "QNR", TObjArray * arr = nullptr) virtual inherited
Definition at line 640 of file GHSym.cxx.
References GHSym::Projection().
GetBin()
Int_t GHSym::GetBin (Int_t binx, Int_t biny = 0, Int_t binz = 0) const override inherited
Definition at line 813 of file GHSym.cxx.
Referenced by GHSym::DoIntegral(), GetBinContent(), GetBinContent(), GHSymF::GetBinContent(), GHSymF::GetBinContent(), GHSym::GetCellContent(), GHSym::GetCellError(), GHSym::GetStats(), GHSym::Merge(), GHSym::Profile(), GHSym::Rebin2D(), SetBinContent(), SetBinContent(), GHSymF::SetBinContent(), GHSymF::SetBinContent(), GHSym::SetCellContent(), GHSym::SetCellError(), and GHSym::Smooth().
GetBinContent() [1/3]
Double_t GHSymD::GetBinContent (Int_t bin) const override
Definition at line 3036 of file GHSym.cxx.
References GHSym::BufferEmpty().
Referenced by GetMatrix().
GetBinContent() [2/3]
Double_t GHSymD::GetBinContent (Int_t binx, Int_t biny) const inline override
Definition at line 189 of file GHSym.h.
References GHSym::GetBin(), and GetBinContent().
Referenced by GetBinContent().
GetBinContent() [3/3]
Double_t GHSymD::GetBinContent (Int_t binx, Int_t biny, Int_t) const inline override
Definition at line 190 of file GHSym.h.
References GHSym::GetBin(), and GetBinContent().
Referenced by GetBinContent().
GetBinWithContent2()
Double_t GHSym::GetBinWithContent2 (Double_t c, Int_t & binx, Int_t & biny, Int_t firstxbin = 1, Int_t lastxbin = -1, Int_t firstybin = 1, Int_t lastybin = -1, Double_t maxdiff = 0) const virtual inherited
Definition at line 834 of file GHSym.cxx.
GetCellContent()
Double_t GHSym::GetCellContent (Int_t binx, Int_t biny) const override inherited
Definition at line 890 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Projection().
GetCellError()
Double_t GHSym::GetCellError (Int_t binx, Int_t biny) const override inherited
Definition at line 895 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Projection().
GetCorrelationFactor()
Double_t GHSym::GetCorrelationFactor (Int_t axis1 = 1, Int_t axis2 = 2) const virtual inherited
Definition at line 900 of file GHSym.cxx.
References GHSym::GetCovariance().
GetCovariance()
Double_t GHSym::GetCovariance (Int_t axis1 = 1, Int_t axis2 = 2) const virtual inherited
Definition at line 922 of file GHSym.cxx.
References GHSym::GetStats().
Referenced by GHSym::GetCorrelationFactor().
GetMatrix()
TH2D * GHSymD::GetMatrix (bool force = false)
Definition at line 2993 of file GHSym.cxx.
References GetBinContent(), and GHSym::Matrix().
Referenced by Draw().
GetRandom2()
void GHSym::GetRandom2 (Double_t & x, Double_t & y) virtual inherited
Definition at line 953 of file GHSym.cxx.
GetStats()
void GHSym::GetStats (Double_t * stats) const override inherited
Definition at line 996 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::fTsumwxy, GHSym::fTsumwy, GHSym::fTsumwy2, and GHSym::GetBin().
Referenced by GHSym::GetCovariance(), GHSym::Merge(), GHSym::Projection(), and GHSym::Rebin2D().
Integral() [1/3]
Double_t GHSym::Integral (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Option_t * option = "") const virtual inherited
Definition at line 1089 of file GHSym.cxx.
References GHSym::DoIntegral().
Integral() [2/3]
virtual Double_t GHSym::Integral (Int_t , Int_t , Int_t , Int_t , Int_t , Int_t , Option_t * = "") const inline virtual inherited
Definition at line 78 of file GHSym.h.
Integral() [3/3]
Double_t GHSym::Integral (Option_t * option = "") const override inherited
Definition at line 1079 of file GHSym.cxx.
References GHSym::Integral().
Referenced by GHSym::Integral().
IntegralAndError()
Double_t GHSym::IntegralAndError (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Double_t & error, Option_t * option = "") const virtual inherited
Definition at line 1100 of file GHSym.cxx.
References GHSym::DoIntegral().
Interpolate() [1/3]
Double_t GHSym::Interpolate (Double_t) const override inherited
Definition at line 1116 of file GHSym.cxx.
Interpolate() [2/3]
Double_t GHSym::Interpolate (Double_t x, Double_t y) const override inherited
Definition at line 1127 of file GHSym.cxx.
Interpolate() [3/3]
Double_t GHSym::Interpolate (Double_t , Double_t , Double_t) const override inherited
Definition at line 1224 of file GHSym.cxx.
KolmogorovTest()
Double_t GHSym::KolmogorovTest (const TH1 * h2, Option_t * option = "") const override inherited
Definition at line 1232 of file GHSym.cxx.
Matrix() [1/2]
TH2 * GHSym::Matrix () inline protected inherited
Definition at line 113 of file GHSym.h.
References GHSym::fMatrix.
Referenced by GetMatrix(), and GHSymF::GetMatrix().
Matrix() [2/2]
void GHSym::Matrix (TH2 * val) inline protected inherited
Definition at line 114 of file GHSym.h.
References GHSym::fMatrix.
Merge()
Long64_t GHSym::Merge (TCollection * list) override inherited
Definition at line 1448 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::Copy(), GHSym::Fill(), GHSym::GetBin(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
operator=() [1/2]
GHSymD & GHSymD::operator= (const GHSymD & h1)
Definition at line 3089 of file GHSym.cxx.
References Copy().
operator=() [2/2]
GHSymD & GHSymD::operator= (GHSymD && h1) noexcept
Definition at line 3099 of file GHSym.cxx.
Profile()
TProfile * GHSym::Profile (const char * name = "_pf", Int_t firstbin = 1, Int_t lastbin = -1, Option_t * option = "") const virtual inherited
Definition at line 1720 of file GHSym.cxx.
References GHSym::GetBin().
Projection()
TH1D * GHSym::Projection (const char * name = "_pr", Int_t firstBin = 0, Int_t lastBin = -1, Option_t * option = "") const virtual inherited
method for performing projection
Definition at line 1957 of file GHSym.cxx.
References GHSym::GetCellContent(), GHSym::GetCellError(), and GHSym::GetStats().
Referenced by GHSym::FitSlices().
PutStats()
void GHSym::PutStats (Double_t * stats) override inherited
Definition at line 2198 of file GHSym.cxx.
References GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Referenced by GHSym::Merge(), and GHSym::Rebin2D().
Rebin2D()
GHSym * GHSym::Rebin2D (Int_t ngroup = 2, const char * newname = "") virtual inherited
Definition at line 2207 of file GHSym.cxx.
References GHSym::GetBin(), GHSym::GetStats(), and GHSym::PutStats().
Reset()
void GHSymD::Reset (Option_t * option = "") override
Definition at line 3054 of file GHSym.cxx.
References GHSym::Reset().
RetrieveBinContent()
Double_t GHSymD::RetrieveBinContent (Int_t bin) const inline override
Definition at line 192 of file GHSym.h.
SetBinContent() [1/3]
void GHSymD::SetBinContent (Int_t bin, Double_t content) override
Definition at line 3063 of file GHSym.cxx.
Referenced by SetBinContent().
SetBinContent() [2/3]
void GHSymD::SetBinContent (Int_t binx, Int_t biny, Double_t content) inline override
Definition at line 194 of file GHSym.h.
References GHSym::GetBin(), and SetBinContent().
Referenced by SetBinContent().
SetBinContent() [3/3]
void GHSymD::SetBinContent (Int_t binx, Int_t biny, Int_t , Double_t content) inline override
Definition at line 195 of file GHSym.h.
References GHSym::GetBin(), and SetBinContent().
SetBinsLength()
void GHSymD::SetBinsLength (Int_t n = -1) override
Definition at line 3077 of file GHSym.cxx.
Referenced by GHSymD().
SetCellContent()
void GHSym::SetCellContent (Int_t binx, Int_t biny, Double_t content) override inherited
Definition at line 2541 of file GHSym.cxx.
References GHSym::GetBin().
SetCellError()
void GHSym::SetCellError (Int_t binx, Int_t biny, Double_t content) override inherited
Definition at line 2546 of file GHSym.cxx.
References GHSym::GetBin().
SetShowProjectionX()
void GHSym::SetShowProjectionX (Int_t nbins = 1) virtual inherited
Definition at line 2551 of file GHSym.cxx.
SetShowProjectionY()
void GHSym::SetShowProjectionY (Int_t nbins = 1) virtual inherited
Definition at line 2565 of file GHSym.cxx.
ShowBackground()
TH1 * GHSym::ShowBackground (Int_t niter = 20, Option_t * option = "same") override inherited
Definition at line 2579 of file GHSym.cxx.
ShowPeaks()
Int_t GHSym::ShowPeaks (Double_t sigma = 2, Option_t * option = "", Double_t threshold = 0.05) override inherited
Definition at line 2589 of file GHSym.cxx.
Smooth()
void GHSym::Smooth (Int_t ntimes = 1, Option_t * option = "") override inherited
Definition at line 2602 of file GHSym.cxx.
References GHSym::GetBin().
UpdateBinContent()
void GHSymD::UpdateBinContent (Int_t bin, Double_t content) inline override
Definition at line 200 of file GHSym.h.
Friends And Related Symbol Documentation
operator* [1/3]
GHSymD operator* (Float_t c1, GHSymD & h1) friend
Definition at line 3109 of file GHSym.cxx.
operator* [2/3]
GHSymD operator* (GHSymD & h1, Float_t c1) friend
Definition at line 204 of file GHSym.h.
operator* [3/3]
GHSymD operator* (GHSymD & h1, GHSymD & h2) friend
Definition at line 3139 of file GHSym.cxx.
operator+
GHSymD operator+ (GHSymD & h1, GHSymD & h2) friend
Definition at line 3119 of file GHSym.cxx.
operator-
GHSymD operator- (GHSymD & h1, GHSymD & h2) friend
Definition at line 3129 of file GHSym.cxx.
operator/
GHSymD operator/ (GHSymD & h1, GHSymD & h2) friend
Definition at line 3149 of file GHSym.cxx.
Member Data Documentation
fMatrix
TH2* GHSym::fMatrix {nullptr} private inherited
! Transient pointer to the 2D-Matrix used in Draw() or GetMatrix()
Definition at line 120 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Matrix(), GHSym::Matrix(), and GHSym::Reset().
fTsumwxy
Double_t GHSym::fTsumwxy {0.} private inherited
Total Sum of weight*X*Y.
Definition at line 119 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
fTsumwy
Double_t GHSym::fTsumwy {0.} private inherited
Total Sum of weight*Y.
Definition at line 117 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
fTsumwy2
Double_t GHSym::fTsumwy2 {0.} private inherited
Total Sum of weight*Y*Y.
Definition at line 118 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().