GRSISort: TSortingDiagnostics Class Reference
TSortingDiagnostics Class Reference
Sorting
Detailed Description
This class gathers various diagnostics calculated during the sorting from a raw file to a fragment tree and analysis tree and provides convenient methods of printing and/or visualizing them.
Definition at line 31 of file TSortingDiagnostics.h.
#include <TSortingDiagnostics.h>
Public Member Functions
TSortingDiagnostics ()
TSortingDiagnostics (const TSortingDiagnostics &)
~TSortingDiagnostics () override
void AddDetectorClass (TChannel *)
void AddTime (double val)
void AddTimeStamp (Long_t val)
void Clear (Option_t *opt="all") override
void Copy (TObject &) const override
void Draw (Option_t *opt="") override
std::unordered_map< long, std::pair< long, long > > FragmentsOutOfOrder ()
std::unordered_map< double, std::pair< double, double > > FragmentsOutOfTimeOrder ()
long MaxEntryDiff () const
void MissingChannel (const UInt_t &address)
size_t NumberOfFragmentsOutOfOrder () const
size_t NumberOfFragmentsOutOfTimeOrder () const
void OutOfOrder (long newFragTS, long oldFragTS, long newEntry)
void OutOfTimeOrder (double newFragTime, double oldFragTime, long newEntry)
void Print (Option_t *opt="") const override
void RemovedHits (TClass *detClass, long removed, long total)
void WriteToFile (const char *) const
Static Public Member Functions
static TSortingDiagnostics * AddCurrent ()
static TSortingDiagnostics * Get (bool verbose=false)
static TSortingDiagnostics * GetAll ()
static void PrintDirectory ()
static void Set (TSortingDiagnostics *val)
Private Attributes
std::unordered_map< long, std::pair< long, long > > fFragmentsOutOfOrder
std::unordered_map< double, std::pair< double, double > > fFragmentsOutOfTimeOrder
std::unordered_map< TClass *, std::pair< long, long > > fHitsRemoved
long fMaxEntryDiff {0}
std::unordered_map< UInt_t, long > fMissingChannels
std::unordered_map< TClass *, long > fMissingDetectorClasses
std::vector< double > fPreviousTimes
std::vector< Long_t > fPreviousTimeStamps
Static Private Attributes
static TDirectory * fDir
static TSortingDiagnostics * fSingleton
Friends
class TSingleton< TSortingDiagnostics >
Constructor & Destructor Documentation
TSortingDiagnostics() [1/2]
TSortingDiagnostics::TSortingDiagnostics ()
Definition at line 9 of file TSortingDiagnostics.cxx.
References Clear().
TSortingDiagnostics() [2/2]
TSortingDiagnostics::TSortingDiagnostics (const TSortingDiagnostics &)
Definition at line 14 of file TSortingDiagnostics.cxx.
References Clear().
~TSortingDiagnostics()
TSortingDiagnostics::~TSortingDiagnostics () override default
Member Function Documentation
AddCurrent()
static TSortingDiagnostics * TSingleton< TSortingDiagnostics >::AddCurrent () inline static inherited
Definition at line 137 of file TSingleton.h.
AddDetectorClass()
void TSortingDiagnostics::AddDetectorClass (TChannel * channel)
Definition at line 80 of file TSortingDiagnostics.cxx.
References fMissingDetectorClasses, TChannel::GetClassType(), and TChannel::Print().
Referenced by TUnpackedEvent::Build().
AddTime()
void TSortingDiagnostics::AddTime (double val) inline
Definition at line 55 of file TSortingDiagnostics.h.
References fPreviousTimes.
Referenced by TEventBuildingLoop::CheckTimeCondition().
AddTimeStamp()
void TSortingDiagnostics::AddTimeStamp (Long_t val) inline
Definition at line 56 of file TSortingDiagnostics.h.
References fPreviousTimeStamps.
Referenced by TEventBuildingLoop::CheckTimestampCondition(), and TEventBuildingLoop::CheckTriggerIdCondition().
Clear()
void TSortingDiagnostics::Clear (Option_t * opt = "all") override
Definition at line 28 of file TSortingDiagnostics.cxx.
References fFragmentsOutOfOrder, fFragmentsOutOfTimeOrder, and fMissingDetectorClasses.
Referenced by TSortingDiagnostics(), and TSortingDiagnostics().
Copy()
void TSortingDiagnostics::Copy (TObject & obj) const override
Definition at line 21 of file TSortingDiagnostics.cxx.
References fFragmentsOutOfOrder, fFragmentsOutOfTimeOrder, and fMissingDetectorClasses.
Draw()
void TSortingDiagnostics::Draw (Option_t * opt = "") override
Definition at line 147 of file TSortingDiagnostics.cxx.
FragmentsOutOfOrder()
std::unordered_map< long, std::pair< long, long > > TSortingDiagnostics::FragmentsOutOfOrder () inline
Definition at line 63 of file TSortingDiagnostics.h.
References fFragmentsOutOfOrder.
FragmentsOutOfTimeOrder()
std::unordered_map< double, std::pair< double, double > > TSortingDiagnostics::FragmentsOutOfTimeOrder () inline
Definition at line 65 of file TSortingDiagnostics.h.
References fFragmentsOutOfTimeOrder.
Get()
static TSortingDiagnostics * TSingleton< TSortingDiagnostics >::Get (bool verbose = false) inline static inherited
Definition at line 34 of file TSingleton.h.
GetAll()
static TSortingDiagnostics * TSingleton< TSortingDiagnostics >::GetAll () inline static inherited
Definition at line 62 of file TSingleton.h.
MaxEntryDiff()
long TSortingDiagnostics::MaxEntryDiff () const inline
Definition at line 66 of file TSortingDiagnostics.h.
References fMaxEntryDiff.
MissingChannel()
void TSortingDiagnostics::MissingChannel (const UInt_t & address)
Definition at line 71 of file TSortingDiagnostics.cxx.
References fMissingChannels.
Referenced by TUnpackedEvent::Build().
NumberOfFragmentsOutOfOrder()
size_t TSortingDiagnostics::NumberOfFragmentsOutOfOrder () const inline
Definition at line 62 of file TSortingDiagnostics.h.
References fFragmentsOutOfOrder.
Referenced by Print(), and WriteToFile().
NumberOfFragmentsOutOfTimeOrder()
size_t TSortingDiagnostics::NumberOfFragmentsOutOfTimeOrder () const inline
Definition at line 64 of file TSortingDiagnostics.h.
References fFragmentsOutOfTimeOrder.
Referenced by Print(), and WriteToFile().
OutOfOrder()
void TSortingDiagnostics::OutOfOrder (long newFragTS, long oldFragTS, long newEntry)
Definition at line 53 of file TSortingDiagnostics.cxx.
References fFragmentsOutOfOrder, fMaxEntryDiff, fPreviousTimeStamps, TGRSIOptions::Get(), and TGRSIOptions::SortDepth().
Referenced by TEventBuildingLoop::CheckTimestampCondition(), and TEventBuildingLoop::CheckTriggerIdCondition().
OutOfTimeOrder()
void TSortingDiagnostics::OutOfTimeOrder (double newFragTime, double oldFragTime, long newEntry)
Definition at line 35 of file TSortingDiagnostics.cxx.
References fFragmentsOutOfTimeOrder, fMaxEntryDiff, fPreviousTimes, TGRSIOptions::Get(), and TGRSIOptions::SortDepth().
Referenced by TEventBuildingLoop::CheckTimeCondition().
Print()
void TSortingDiagnostics::Print (Option_t * opt = "") const override
Definition at line 91 of file TSortingDiagnostics.cxx.
References DGREEN, DRED, fFragmentsOutOfOrder, fFragmentsOutOfTimeOrder, fHitsRemoved, fMaxEntryDiff, fMissingChannels, fMissingDetectorClasses, hex(), NumberOfFragmentsOutOfOrder(), NumberOfFragmentsOutOfTimeOrder(), and RESET_COLOR.
Referenced by TGRSIint::Terminate().
PrintDirectory()
static void TSingleton< TSortingDiagnostics >::PrintDirectory () inline static inherited
Definition at line 167 of file TSingleton.h.
RemovedHits()
void TSortingDiagnostics::RemovedHits (TClass * detClass, long removed, long total)
Definition at line 161 of file TSortingDiagnostics.cxx.
References fHitsRemoved.
Referenced by TTigress::BuildHits().
Set()
static void TSingleton< TSortingDiagnostics >::Set (TSortingDiagnostics * val) inline static inherited
Definition at line 129 of file TSingleton.h.
WriteToFile()
void TSortingDiagnostics::WriteToFile (const char * fileName) const
Definition at line 151 of file TSortingDiagnostics.cxx.
References fMaxEntryDiff, NumberOfFragmentsOutOfOrder(), and NumberOfFragmentsOutOfTimeOrder().
Friends And Related Symbol Documentation
TSingleton< TSortingDiagnostics >
friend class TSingleton< TSortingDiagnostics > friend
Definition at line 1 of file TSortingDiagnostics.h.
Member Data Documentation
fDir
TDirectory * TSingleton< TSortingDiagnostics >::fDir static private inherited
Definition at line 181 of file TSingleton.h.
fFragmentsOutOfOrder
std::unordered_map<long, std::pair<long, long> > TSortingDiagnostics::fFragmentsOutOfOrder private
Definition at line 41 of file TSortingDiagnostics.h.
Referenced by Clear(), Copy(), FragmentsOutOfOrder(), NumberOfFragmentsOutOfOrder(), OutOfOrder(), and Print().
fFragmentsOutOfTimeOrder
std::unordered_map<double, std::pair<double, double> > TSortingDiagnostics::fFragmentsOutOfTimeOrder private
Definition at line 42 of file TSortingDiagnostics.h.
Referenced by Clear(), Copy(), FragmentsOutOfTimeOrder(), NumberOfFragmentsOutOfTimeOrder(), OutOfTimeOrder(), and Print().
fHitsRemoved
std::unordered_map<TClass*, std::pair<long, long> > TSortingDiagnostics::fHitsRemoved private
removed hits and total hits per detector class
Definition at line 49 of file TSortingDiagnostics.h.
Referenced by Print(), and RemovedHits().
fMaxEntryDiff
long TSortingDiagnostics::fMaxEntryDiff {0} private
Definition at line 45 of file TSortingDiagnostics.h.
Referenced by MaxEntryDiff(), OutOfOrder(), OutOfTimeOrder(), Print(), and WriteToFile().
fMissingChannels
std::unordered_map<UInt_t, long> TSortingDiagnostics::fMissingChannels private
counts of missing channels
Definition at line 46 of file TSortingDiagnostics.h.
Referenced by MissingChannel(), and Print().
fMissingDetectorClasses
std::unordered_map<TClass*, long> TSortingDiagnostics::fMissingDetectorClasses private
counts of missing detector classes
Definition at line 47 of file TSortingDiagnostics.h.
Referenced by AddDetectorClass(), Clear(), Copy(), and Print().
fPreviousTimes
std::vector<double> TSortingDiagnostics::fPreviousTimes private
times of previous fragments, saved every 'BuildWindow' entries
Definition at line 44 of file TSortingDiagnostics.h.
Referenced by AddTime(), and OutOfTimeOrder().
fPreviousTimeStamps
std::vector<Long_t> TSortingDiagnostics::fPreviousTimeStamps private
timestamps of previous fragments, saved every 'BuildWindow' entries
Definition at line 43 of file TSortingDiagnostics.h.
Referenced by AddTimeStamp(), and OutOfOrder().
fSingleton
TSortingDiagnostics * TSingleton< TSortingDiagnostics >::fSingleton static private inherited
Definition at line 180 of file TSingleton.h.