GRSISort: TGRSISortInfo Class Reference
TGRSISortInfo Class Reference
Sorting
Detailed Description
Definition at line 41 of file TGRSISortInfo.h.
Public Member Functions
TGRSISortInfo ()
~TGRSISortInfo () override
UInt_t AddDuplicate ()
void Clear (Option_t *opt="") override
TString Comment () const
void Print (Option_t *opt="") const override
Int_t RunNumber () const
void SetComment (const char *comment)
void SetRunInfo ()
Int_t SubRunNumber () const
Private Attributes
TString fComment
UInt_t fDuplicates {0}
Int_t fRunNumber {0}
Int_t fSubRunNumber {0}
Constructor & Destructor Documentation
TGRSISortInfo()
TGRSISortInfo::TGRSISortInfo ()
Definition at line 75 of file TGRSISortInfo.cxx.
References Clear(), and SetRunInfo().
~TGRSISortInfo()
TGRSISortInfo::~TGRSISortInfo () override default
Member Function Documentation
AddDuplicate()
UInt_t TGRSISortInfo::AddDuplicate () inline
Definition at line 56 of file TGRSISortInfo.h.
References fDuplicates.
Referenced by TGRSISortList::AddSortInfo().
Clear()
void TGRSISortInfo::Clear (Option_t * opt = "") override
Definition at line 100 of file TGRSISortInfo.cxx.
References fComment, fDuplicates, fRunNumber, and fSubRunNumber.
Referenced by TGRSISortInfo().
Comment()
TString TGRSISortInfo::Comment () const inline
Definition at line 49 of file TGRSISortInfo.h.
References fComment.
Referenced by Print().
Print()
void TGRSISortInfo::Print (Option_t * opt = "") const override
Definition at line 89 of file TGRSISortInfo.cxx.
References Comment(), fDuplicates, RunNumber(), and SubRunNumber().
Referenced by ClassImp(), and TGRSISortList::Print().
RunNumber()
Int_t TGRSISortInfo::RunNumber () const inline
Definition at line 47 of file TGRSISortInfo.h.
References fRunNumber.
Referenced by TGRSISortList::AddSortInfo(), and Print().
SetComment()
void TGRSISortInfo::SetComment (const char * comment) inline
Definition at line 51 of file TGRSISortInfo.h.
References fComment.
SetRunInfo()
void TGRSISortInfo::SetRunInfo ()
Definition at line 83 of file TGRSISortInfo.cxx.
References fRunNumber, fSubRunNumber, TRunInfo::RunNumber(), and TRunInfo::SubRunNumber().
Referenced by TGRSISortInfo().
SubRunNumber()
Int_t TGRSISortInfo::SubRunNumber () const inline
Definition at line 48 of file TGRSISortInfo.h.
References fSubRunNumber.
Referenced by TGRSISortList::AddSortInfo(), and Print().
Member Data Documentation
fComment
TString TGRSISortInfo::fComment private
Definition at line 62 of file TGRSISortInfo.h.
Referenced by Clear(), Comment(), and SetComment().
fDuplicates
UInt_t TGRSISortInfo::fDuplicates {0} private
Definition at line 61 of file TGRSISortInfo.h.
Referenced by AddDuplicate(), Clear(), and Print().
fRunNumber
Int_t TGRSISortInfo::fRunNumber {0} private
Definition at line 59 of file TGRSISortInfo.h.
Referenced by Clear(), RunNumber(), and SetRunInfo().
fSubRunNumber
Int_t TGRSISortInfo::fSubRunNumber {0} private
Definition at line 60 of file TGRSISortInfo.h.
Referenced by Clear(), SetRunInfo(), and SubRunNumber().