GRSISort: TTigress Class Reference
TTigress Class Reference
Detectors
Detailed Description
Definition at line 19 of file TTigress.h.
Public Types
enum class ETigressBits : std::uint8_t {
kIsAddbackSet = 1 << 0 , kSpare1 = 1 << 1 , kIsCrossTalkSet = 1 << 2 , kSpare3 = 1 << 3 ,
kIsSuppressed = 1 << 4 , kSpare5 = 1 << 5 , kIsSuppressedAddbackSet = 1 << 6 , kSpare7 = 1 << 7
}
enum class ETigressGlobalBits : std::uint8_t {
kSpare0 = BIT(0) , kSetCoreWave = BIT(1) , kSetSegWave = BIT(2) , kSpare3 = BIT(3) ,
kSpare4 = BIT(4) , kArrayBackPos = BIT(5) , kVectorsBuilt = BIT(6)
}
Public Member Functions
TTigress ()
TTigress (const TTigress &)
TTigress (TTigress &&) noexcept=default
~TTigress () override
bool AddbackCriterion (const TDetectorHit *hit1, const TDetectorHit *hit2) override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
void ClearTransients () override
void Copy (TObject &) const override
void FixCrossTalk ()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetAddbackCriterion () const
TTigressHit * GetAddbackHit (const int &i)
Short_t GetAddbackMultiplicity ()
virtual TDetectorHit * GetHit (const int &index) const
virtual Short_t GetMultiplicity () const
UShort_t GetNAddbackFrags (const size_t &idx)
UShort_t GetNSuppressedAddbackFrags (const size_t &idx)
TTigressHit * GetSuppressedAddbackHit (const int &i)
Short_t GetSuppressedAddbackMultiplicity (const TBgo *bgo)
TTigressHit * GetSuppressedHit (const int &i)
Short_t GetSuppressedMultiplicity (const TBgo *bgo)
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetSuppressionCriterion () const
TTigressHit * GetTigressHit (const int &i)
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
bool IsAddbackSet () const
Bool_t IsCrossTalkSet () const
bool IsSuppressed () const
bool IsSuppressedAddbackSet () const
virtual bool NoHits () const
TTigress & operator= (const TTigress &)
TTigress & operator= (TTigress &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void ResetAddback ()
void ResetFlags () const
void ResetSuppressed ()
void ResetSuppressedAddback ()
void SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
void SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
bool SuppressionCriterion (const TDetectorHit *hit, const TDetectorHit *bgoHit) override
Static Public Member Functions
static Double_t CTCorrectedEnergy (const TTigressHit *hit_to_correct, const TTigressHit *other_hit, bool time_constraint=true)
static const char * GetColorFromNumber (int number)
static double GetFaceDistance ()
static TVector3 GetPosition (const TTigressHit *hit, double dist=110.0, bool smear=false)
static TVector3 GetPosition (int DetNbr, int CryNbr, int SegNbr, double dist=110.0, bool smear=false)
static void SetRadialOffset (double offset)
static void SetTargetOffset (double offset)
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Private Member Functions
void ClearStatus () const
void SetAddback (bool flag=true) const
void SetBitNumber (ETigressBits bit, Bool_t set) const
void SetCrossTalk (bool flag=true) const
void SetSuppressed (bool flag=true) const
void SetSuppressedAddback (bool flag=true) const
Bool_t TestBitNumber (ETigressBits bit) const
Static Private Member Functions
static void BuildVectors ()
static void SetGlobalBit (ETigressGlobalBits bit, Bool_t set=true)
static Bool_t TestGlobalBit (ETigressGlobalBits bit)
Private Attributes
std::vector< UShort_t > fAddbackFrags
std::vector< TDetectorHit * > fAddbackHits
std::vector< TDetectorHit * > fHits
std::vector< UShort_t > fSuppressedAddbackFrags
std::vector< TDetectorHit * > fSuppressedAddbackHits
std::vector< TDetectorHit * > fSuppressedHits
TTransientBits< uint8_t > fTigressBits
Static Private Attributes
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fAddbackCriterion = DefaultTigressAddback
static std::array< std::array< TVector3, 2 >, 17 > fCloverCross
static std::array< TVector3, 17 > fCloverRadial
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeBluePosition
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeBluePositionBack
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeGreenPosition
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeGreenPositionBack
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeRedPosition
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeRedPositionBack
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeWhitePosition
static std::array< std::array< std::array< double, 3 >, 9 >, 17 > fGeWhitePositionBack
static TTransientBits< uint8_t > fGlobalTigressBits = TTransientBits<uint8_t>(static_cast<std::underlying_type_t<TTigress::ETigressGlobalBits>>(TTigress::ETigressGlobalBits::kSetCoreWave))
static std::array< std::array< std::array< std::array< TVector3, 9 >, 4 >, 17 >, 2 > fPositionVectors
static double fRadialOffset = 0.
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fSuppressionCriterion = DefaultTigressSuppression
static double fTargetOffset = 0.
Member Enumeration Documentation
ETigressBits
enum class TTigress::ETigressBits : std::uint8_t strong
Enumerator
kIsAddbackSet
kSpare1
kIsCrossTalkSet
kSpare3
kIsSuppressed
kSpare5
kIsSuppressedAddbackSet
kSpare7
Definition at line 21 of file TTigress.h.
ETigressGlobalBits
enum class TTigress::ETigressGlobalBits : std::uint8_t strong
Enumerator
kSpare0
kSetCoreWave
kSetSegWave
kSpare3
kSpare4
kArrayBackPos
kVectorsBuilt
Definition at line 32 of file TTigress.h.
Constructor & Destructor Documentation
TTigress() [1/3]
TTigress::TTigress ()
Default ctor. Ignores TObjectStreamer in ROOT < 6
Definition at line 46 of file TTigress.cxx.
References Clear().
TTigress() [2/3]
TTigress::TTigress (const TTigress & rhs)
Copy ctor. Ignores TObjectStreamer in ROOT < 6
Definition at line 52 of file TTigress.cxx.
References Copy().
TTigress() [3/3]
TTigress::TTigress (TTigress &&) default noexcept
~TTigress()
TTigress::~TTigress () override
Definition at line 82 of file TTigress.cxx.
References fAddbackHits, fSuppressedAddbackHits, and fSuppressedHits.
Member Function Documentation
AddbackCriterion()
bool TTigress::AddbackCriterion (const TDetectorHit * hit1, const TDetectorHit * hit2) inline override virtual
Reimplemented from TSuppressed.
Definition at line 73 of file TTigress.h.
References fAddbackCriterion.
AddFragment()
void TTigress::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Builds the TIGRESS Hits directly from the TFragment. Basically, loops through the hits for an event and sets observables.
Reimplemented from TDetector.
Definition at line 246 of file TTigress.cxx.
References TDetector::AddHit(), TTigressHit::AddSegment(), ALERTTEXT, TTigressHit::CopyFragment(), TTigressHit::CoreSet(), TDetectorHit::GetChannel(), TDetectorHit::GetCrystal(), TChannel::GetCrystalNumber(), TDetectorHit::GetDetector(), TChannel::GetDetectorNumber(), TChannel::GetMnemonic(), TDetector::GetMultiplicity(), TMnemonic::GetName(), TChannel::GetSegmentNumber(), GetTigressHit(), TMnemonic::kA, TMnemonic::kB, TMnemonic::kG, kSetCoreWave, kSetSegWave, TMnemonic::OutputSensor(), RESET_COLOR, TDetectorHit::SetAddress(), TMnemonic::SubSystem(), and TestGlobalBit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 60 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TGriffin::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TTigress::BuildHits () override virtual
!
Reimplemented from TDetector.
Definition at line 225 of file TTigress.cxx.
References TGRSIOptions::AnalysisOptions(), TTigressHit::CoreSet(), TSingleton< TSortingDiagnostics >::Get(), TDetector::Hits(), TAnalysisOptions::IsWaveformFitting(), and TSortingDiagnostics::RemovedHits().
BuildVectors()
void TTigress::BuildVectors () static private
Definition at line 585 of file TTigress.cxx.
References fCloverCross, fCloverRadial, fGeBluePosition, fGeBluePositionBack, fGeGreenPosition, fGeGreenPositionBack, fGeRedPosition, fGeRedPositionBack, fGeWhitePosition, fGeWhitePositionBack, fPositionVectors, fRadialOffset, fTargetOffset, kVectorsBuilt, and SetGlobalBit().
Referenced by GetPosition(), SetRadialOffset(), and SetTargetOffset().
Clear()
void TTigress::Clear (Option_t * opt = "all") override
!
Definition at line 97 of file TTigress.cxx.
References TSuppressed::Clear(), ClearStatus(), fAddbackFrags, fAddbackHits, fSuppressedAddbackFrags, fSuppressedAddbackHits, and fSuppressedHits.
Referenced by TTigress().
ClearStatus()
void TTigress::ClearStatus () const inline private
!
Definition at line 164 of file TTigress.h.
References fTigressBits.
Referenced by Clear().
ClearTransients()
void TTigress::ClearTransients () inline override virtual
!
Reimplemented from TDetector.
Definition at line 59 of file TTigress.h.
References TDetector::ClearTransients(), and fTigressBits.
Copy()
void TTigress::Copy (TObject & rhs) const override
!
Definition at line 58 of file TTigress.cxx.
References TSuppressed::Copy(), fAddbackFrags, fAddbackHits, fSuppressedAddbackFrags, fSuppressedAddbackHits, fSuppressedHits, and fTigressBits.
Referenced by TTigress(), and operator=().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 38 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by TFipps::GetAddbackMultiplicity(), TGriffin::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), and GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected inherited
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 69 of file TSuppressed.h.
References TDetector::Hits(), and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), and GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 94 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetector::Hits(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), and GetSuppressedAddbackMultiplicity().
CTCorrectedEnergy()
Double_t TTigress::CTCorrectedEnergy (const TTigressHit * hit_to_correct, const TTigressHit * other_hit, bool time_constraint = true) static
Definition at line 356 of file TTigress.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), DRED, TDetectorHit::GetChannel(), TDetectorHit::GetCrystal(), TChannel::GetCTCoeff(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TTigressHit::GetNoCTEnergy(), TDetectorHit::GetTime(), and RESET_COLOR.
Referenced by FixCrossTalk().
FixCrossTalk()
void TTigress::FixCrossTalk ()
Definition at line 394 of file TTigress.cxx.
References TGRSIOptions::AnalysisOptions(), CTCorrectedEnergy(), TDetector::Hits(), and SetCrossTalk().
Referenced by GetAddbackMultiplicity(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), GetSuppressedMultiplicity(), and GetTigressHit().
GetAddbackCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TTigress::GetAddbackCriterion () const inline
Definition at line 71 of file TTigress.h.
References fAddbackCriterion.
GetAddbackHit()
TTigressHit * TTigress::GetAddbackHit (const int & i)
Definition at line 215 of file TTigress.cxx.
References fAddbackHits, and GetAddbackMultiplicity().
GetAddbackMultiplicity()
Short_t TTigress::GetAddbackMultiplicity ()
Definition at line 191 of file TTigress.cxx.
References TSuppressed::CreateAddback(), fAddbackFrags, fAddbackHits, FixCrossTalk(), TDetector::Hits(), IsAddbackSet(), IsCrossTalkSet(), ResetAddback(), and SetAddback().
Referenced by GetAddbackHit().
GetColorFromNumber()
const char * TTigress::GetColorFromNumber (int number) static
Definition at line 415 of file TTigress.cxx.
GetFaceDistance()
static double TTigress::GetFaceDistance () inline static
Definition at line 119 of file TTigress.h.
References kArrayBackPos, and TestGlobalBit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 84 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), and TZeroDegree::GetZeroDegreeHit().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 70 of file TDetector.h.
References TDetector::fHits.
Referenced by AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TacOffsetHelper::Exec(), TimeWalkHelper::Exec(), SummingCorrectionsHelper::FillBranchingRatioHistograms(), SummingCorrectionsHelper::FillEfficiencyHistograms(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TSharc::GetSize(), main(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetNAddbackFrags()
UShort_t TTigress::GetNAddbackFrags (const size_t & idx)
Definition at line 340 of file TTigress.cxx.
References fAddbackFrags.
GetNSuppressedAddbackFrags()
UShort_t TTigress::GetNSuppressedAddbackFrags (const size_t & idx)
Definition at line 544 of file TTigress.cxx.
References fSuppressedAddbackFrags.
GetPosition() [1/2]
TVector3 TTigress::GetPosition (const TTigressHit * hit, double dist = 110.0, bool smear = false) static
!
Definition at line 557 of file TTigress.cxx.
References TDetectorHit::GetCrystal(), TDetectorHit::GetDetector(), TTigressHit::GetFirstSegment(), and GetPosition().
GetPosition() [2/2]
TVector3 TTigress::GetPosition (int DetNbr, int CryNbr, int SegNbr, double dist = 110.0, bool smear = false) static
!
Definition at line 562 of file TTigress.cxx.
References BuildVectors(), fCloverCross, fPositionVectors, kArrayBackPos, kVectorsBuilt, and TestGlobalBit().
Referenced by TTigressHit::GetLastPosition(), GetPosition(), and TTigressHit::GetPosition().
GetSuppressedAddbackHit()
TTigressHit * TTigress::GetSuppressedAddbackHit (const int & i)
Definition at line 489 of file TTigress.cxx.
References FixCrossTalk(), fSuppressedAddbackHits, and IsCrossTalkSet().
GetSuppressedAddbackMultiplicity()
Short_t TTigress::GetSuppressedAddbackMultiplicity (const TBgo * bgo)
Automatically builds the suppressed addback hits using the fAddbackCriterion (if the size of the fAddbackHits vector is zero) and return the number of suppressed addback hits.
Definition at line 505 of file TTigress.cxx.
References TSuppressed::CreateSuppressedAddback(), FixCrossTalk(), fSuppressedAddbackFrags, fSuppressedAddbackHits, TDetector::Hits(), IsCrossTalkSet(), IsSuppressedAddbackSet(), ResetSuppressedAddback(), and SetSuppressedAddback().
GetSuppressedHit()
TTigressHit * TTigress::GetSuppressedHit (const int & i)
!
Definition at line 436 of file TTigress.cxx.
References FixCrossTalk(), fSuppressedHits, and IsCrossTalkSet().
GetSuppressedMultiplicity()
Short_t TTigress::GetSuppressedMultiplicity (const TBgo * bgo)
Automatically builds the suppressed hits using the fSuppressionCriterion and returns the number of suppressed hits
Definition at line 452 of file TTigress.cxx.
References TSuppressed::CreateSuppressed(), FixCrossTalk(), fSuppressedHits, TDetector::Hits(), IsCrossTalkSet(), IsSuppressed(), ResetSuppressed(), and SetSuppressed().
GetSuppressionCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TTigress::GetSuppressionCriterion () const inline
Definition at line 87 of file TTigress.h.
References fSuppressionCriterion.
GetTigressHit()
TTigressHit * TTigress::GetTigressHit (const int & i)
!
Get Tigress hit indicated by index i. Throws an out of range exception if the index is out of the range of the hit vector. Applies cross-talk corrections if they haven't already been applied and are enabled. Note: This is different from using TDetector::GetHit and casting the result to a TTigressHit* as in that case no cross-talk corrections are applied.
Definition at line 170 of file TTigress.cxx.
References FixCrossTalk(), TDetector::Hits(), and IsCrossTalkSet().
Referenced by AddFragment().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 74 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), BuildHits(), TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TIfin::FixCrossTalk(), FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TGriffin::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TFipps::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), GetSuppressedMultiplicity(), GetTigressHit(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
IsAddbackSet()
bool TTigress::IsAddbackSet () const
Definition at line 150 of file TTigress.cxx.
References kIsAddbackSet, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), and Print().
IsCrossTalkSet()
bool TTigress::IsCrossTalkSet () const
Definition at line 155 of file TTigress.cxx.
References kIsCrossTalkSet, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), GetSuppressedMultiplicity(), GetTigressHit(), and Print().
IsSuppressed()
bool TTigress::IsSuppressed () const
Definition at line 426 of file TTigress.cxx.
References kIsSuppressed, and TestBitNumber().
Referenced by GetSuppressedMultiplicity().
IsSuppressedAddbackSet()
bool TTigress::IsSuppressedAddbackSet () const
Definition at line 431 of file TTigress.cxx.
References kIsSuppressedAddbackSet, and TestBitNumber().
Referenced by GetSuppressedAddbackMultiplicity().
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 72 of file TDetector.h.
References TDetector::fHits.
Referenced by TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TTigress & TTigress::operator= (const TTigress & rhs)
!
Definition at line 144 of file TTigress.cxx.
References Copy().
operator=() [2/2]
TTigress & TTigress::operator= (TTigress &&) default noexcept
Print() [1/2]
void TTigress::Print (Option_t * opt = "") const override
!
Definition at line 119 of file TTigress.cxx.
References Print().
Referenced by Print(), and Print().
Print() [2/2]
void TTigress::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 124 of file TTigress.cxx.
References fAddbackHits, TDetector::GetMultiplicity(), TDetector::Hits(), IsAddbackSet(), IsCrossTalkSet(), and Print().
ResetAddback()
void TTigress::ResetAddback ()
!
Definition at line 329 of file TTigress.cxx.
References fAddbackFrags, fAddbackHits, SetAddback(), and SetCrossTalk().
Referenced by GetAddbackMultiplicity().
ResetFlags()
void TTigress::ResetFlags () const
Definition at line 324 of file TTigress.cxx.
References fTigressBits.
ResetSuppressed()
void TTigress::ResetSuppressed ()
Definition at line 480 of file TTigress.cxx.
References fSuppressedHits, and SetSuppressed().
Referenced by GetSuppressedMultiplicity().
ResetSuppressedAddback()
void TTigress::ResetSuppressedAddback ()
Definition at line 534 of file TTigress.cxx.
References fSuppressedAddbackFrags, fSuppressedAddbackHits, and SetSuppressedAddback().
Referenced by GetSuppressedAddbackMultiplicity().
SetAddback()
void TTigress::SetAddback (bool flag = true) const private
Definition at line 160 of file TTigress.cxx.
References kIsAddbackSet, and SetBitNumber().
Referenced by GetAddbackMultiplicity(), and ResetAddback().
SetAddbackCriterion()
void TTigress::SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 67 of file TTigress.h.
References fAddbackCriterion.
SetBitNumber()
void TTigress::SetBitNumber (ETigressBits bit, Bool_t set) const private
Definition at line 350 of file TTigress.cxx.
References fTigressBits, and TTransientBits< T >::SetBit().
Referenced by SetAddback(), SetCrossTalk(), SetSuppressed(), and SetSuppressedAddback().
SetCrossTalk()
void TTigress::SetCrossTalk (bool flag = true) const private
Definition at line 165 of file TTigress.cxx.
References kIsCrossTalkSet, and SetBitNumber().
Referenced by FixCrossTalk(), and ResetAddback().
SetGlobalBit()
static void TTigress::SetGlobalBit (ETigressGlobalBits bit, Bool_t set = true) inline static private
Definition at line 167 of file TTigress.h.
References fGlobalTigressBits, and TTransientBits< T >::SetBit().
Referenced by BuildVectors().
SetRadialOffset()
static void TTigress::SetRadialOffset (double offset) inline static
Definition at line 113 of file TTigress.h.
References BuildVectors(), and fRadialOffset.
SetSuppressed()
void TTigress::SetSuppressed (bool flag = true) const private
Definition at line 475 of file TTigress.cxx.
References kIsSuppressed, and SetBitNumber().
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
SetSuppressedAddback()
void TTigress::SetSuppressedAddback (bool flag = true) const private
Definition at line 529 of file TTigress.cxx.
References kIsSuppressedAddbackSet, and SetBitNumber().
Referenced by GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
SetSuppressionCriterion()
void TTigress::SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 83 of file TTigress.h.
References fSuppressionCriterion.
SetTargetOffset()
static void TTigress::SetTargetOffset (double offset) inline static
Definition at line 108 of file TTigress.h.
References BuildVectors(), and fTargetOffset.
SuppressionCriterion()
bool TTigress::SuppressionCriterion (const TDetectorHit * hit, const TDetectorHit * bgoHit) inline override virtual
Reimplemented from TSuppressed.
Definition at line 89 of file TTigress.h.
References fSuppressionCriterion.
TestBitNumber()
Bool_t TTigress::TestBitNumber (ETigressBits bit) const inline private
Definition at line 166 of file TTigress.h.
References fTigressBits, and TTransientBits< T >::TestBit().
Referenced by IsAddbackSet(), IsCrossTalkSet(), IsSuppressed(), and IsSuppressedAddbackSet().
TestGlobalBit()
static Bool_t TTigress::TestGlobalBit (ETigressGlobalBits bit) inline static private
Definition at line 168 of file TTigress.h.
References fGlobalTigressBits, and TTransientBits< T >::TestBit().
Referenced by AddFragment(), GetFaceDistance(), and GetPosition().
Member Data Documentation
fAddbackCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TTigress::fAddbackCriterion = DefaultTigressAddback static private
Definition at line 129 of file TTigress.h.
Referenced by AddbackCriterion(), GetAddbackCriterion(), and SetAddbackCriterion().
fAddbackFrags
std::vector<UShort_t> TTigress::fAddbackFrags mutable private
! Number of crystals involved in creating in the addback hit
Definition at line 156 of file TTigress.h.
Referenced by Clear(), Copy(), GetAddbackMultiplicity(), GetNAddbackFrags(), and ResetAddback().
fAddbackHits
std::vector<TDetectorHit*> TTigress::fAddbackHits mutable private
! Used to create addback hits on the fly
Definition at line 155 of file TTigress.h.
Referenced by ~TTigress(), Clear(), Copy(), GetAddbackHit(), GetAddbackMultiplicity(), Print(), and ResetAddback().
fCloverCross
std::array< std::array< TVector3, 2 >, 17 > TTigress::fCloverCross static private
! clover perpendicular vectors, for smearing
Definition at line 140 of file TTigress.h.
Referenced by BuildVectors(), and GetPosition().
fCloverRadial
std::array< TVector3, 17 > TTigress::fCloverRadial static private
Initial value:
= {TVector3(0., 0., 0.),
                                                    TVector3(0.9239, 0.3827, 1.),
                                                    TVector3(-0.3827, 0.9239, 1.),
                                                    TVector3(-0.9239, -0.3827, 1.),
                                                    TVector3(0.3827, -0.9239, 1.),
                                                    TVector3(0.9239, 0.3827, 0.),
                                                    TVector3(0.3827, 0.9239, 0.),
                                                    TVector3(-0.3827, 0.9239, 0.),
                                                    TVector3(-0.9239, 0.3827, 0.),
                                                    TVector3(-0.9239, -0.3827, 0.),
                                                    TVector3(-0.3827, -0.9239, 0.),
                                                    TVector3(0.3827, -0.9239, 0.),
                                                    TVector3(0.9239, -0.3827, 0.),
                                                    TVector3(0.9239, 0.3827, -1.),
                                                    TVector3(-0.3827, 0.9239, -1.),
                                                    TVector3(-0.9239, -0.3827, -1.),
                                                    TVector3(0.3827, -0.9239, -1.)}
! direction vector of each HPGe Clover
Definition at line 669 of file TTigress.h.
Referenced by BuildVectors().
fGeBluePosition
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeBluePosition static private
! detector segment XYZ
Definition at line 687 of file TTigress.h.
Referenced by BuildVectors().
fGeBluePositionBack
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeBluePositionBack static private
! detector segment XYZ
Definition at line 1306 of file TTigress.h.
Referenced by BuildVectors().
fGeGreenPosition
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeGreenPosition static private
!
Definition at line 842 of file TTigress.h.
Referenced by BuildVectors().
fGeGreenPositionBack
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeGreenPositionBack static private
!
Definition at line 1461 of file TTigress.h.
Referenced by BuildVectors().
fGeRedPosition
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeRedPosition static private
!
Definition at line 997 of file TTigress.h.
Referenced by BuildVectors().
fGeRedPositionBack
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeRedPositionBack static private
!
Definition at line 1616 of file TTigress.h.
Referenced by BuildVectors().
fGeWhitePosition
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeWhitePosition static private
!
Definition at line 1152 of file TTigress.h.
Referenced by BuildVectors().
fGeWhitePositionBack
std::array< std::array< std::array< double, 3 >, 9 >, 17 > TTigress::fGeWhitePositionBack static private
!
Definition at line 1771 of file TTigress.h.
Referenced by BuildVectors().
fGlobalTigressBits
TTransientBits< uint8_t > TTigress::fGlobalTigressBits = TTransientBits<uint8_t>(static_cast<std::underlying_type_t<TTigress::ETigressGlobalBits>>(TTigress::ETigressGlobalBits::kSetCoreWave)) static private
!
Definition at line 152 of file TTigress.h.
Referenced by SetGlobalBit(), and TestGlobalBit().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 84 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fPositionVectors
std::array< std::array< std::array< std::array< TVector3, 9 >, 4 >, 17 >, 2 > TTigress::fPositionVectors static private
!
Definition at line 137 of file TTigress.h.
Referenced by BuildVectors(), and GetPosition().
fRadialOffset
double TTigress::fRadialOffset = 0. static private
!
Definition at line 134 of file TTigress.h.
Referenced by BuildVectors(), and SetRadialOffset().
fSuppressedAddbackFrags
std::vector<UShort_t> TTigress::fSuppressedAddbackFrags mutable private
! Number of crystals involved in creating in the suppressed addback hit
Definition at line 161 of file TTigress.h.
Referenced by Clear(), Copy(), GetNSuppressedAddbackFrags(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
fSuppressedAddbackHits
std::vector<TDetectorHit*> TTigress::fSuppressedAddbackHits mutable private
! Used to create suppressed addback hits on the fly
Definition at line 160 of file TTigress.h.
Referenced by ~TTigress(), Clear(), Copy(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
fSuppressedHits
std::vector<TDetectorHit*> TTigress::fSuppressedHits private
! The set of suppressed crystal hits
Definition at line 158 of file TTigress.h.
Referenced by ~TTigress(), Clear(), Copy(), GetSuppressedHit(), GetSuppressedMultiplicity(), and ResetSuppressed().
fSuppressionCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TTigress::fSuppressionCriterion = DefaultTigressSuppression static private
Definition at line 130 of file TTigress.h.
Referenced by GetSuppressionCriterion(), SetSuppressionCriterion(), and SuppressionCriterion().
fTargetOffset
double TTigress::fTargetOffset = 0. static private
!
Definition at line 133 of file TTigress.h.
Referenced by BuildVectors(), and SetTargetOffset().
fTigressBits
TTransientBits<uint8_t> TTigress::fTigressBits mutable private
Definition at line 153 of file TTigress.h.
Referenced by ClearStatus(), ClearTransients(), Copy(), ResetFlags(), SetBitNumber(), and TestBitNumber().