GRSISort: TCalGraph Class Reference
TCalGraph Class Reference abstract
Calibration
Detailed Description
This is a class that contains the basic info about a calibration. Calibrations here are TGraphErrors that are fit, with the resulting fit function being the calibrating function.
Definition at line 28 of file TCalGraph.h.
Public Member Functions
TCalGraph ()
TCalGraph (const char *name, const char *title)
TCalGraph (const TCalGraph &)
TCalGraph (TCalGraph &&) noexcept=default
~TCalGraph ()=default
Int_t AddLists (const TCalList &cal_list, const TSourceList &src_list)
void AddPoint (const TCalPoint &cal_point)
void Clear (Option_t *opt="") override
void ClearAllPoints (Option_t *opt="")
void Draw (Option_t *opt="") override
Int_t FindClosestPointX (const Double_t &x_val)
Double_t FindDistToClosestPointX (const Double_t &x_val)
TCalGraph & operator= (const TCalGraph &)=default
TCalGraph & operator= (TCalGraph &&) noexcept=default
void Print (Option_t *opt="") const override
Protected Member Functions
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > & CompareMap ()
Private Member Functions
virtual void BuildGraph ()=0
void CorrectMissingPoints (TCalList &cal_list, TCalList &src_list)
Private Attributes
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > fCompareMap
Constructor & Destructor Documentation
TCalGraph() [1/4]
TCalGraph::TCalGraph ()
Definition at line 6 of file TCalGraph.cxx.
References Clear().
TCalGraph() [2/4]
TCalGraph::TCalGraph (const char * name, const char * title) inline
Definition at line 31 of file TCalGraph.h.
TCalGraph() [3/4]
TCalGraph::TCalGraph (const TCalGraph & copy)
Definition at line 11 of file TCalGraph.cxx.
TCalGraph() [4/4]
TCalGraph::TCalGraph (TCalGraph &&) default noexcept
~TCalGraph()
TCalGraph::~TCalGraph () default
Member Function Documentation
AddLists()
Int_t TCalGraph::AddLists (const TCalList & cal_list, const TSourceList & src_list)
Definition at line 63 of file TCalGraph.cxx.
References TCalList::AddPoint(), CorrectMissingPoints(), DGREEN, DRED, fCompareMap, TCalList::Map(), and RESET_COLOR.
AddPoint()
void TCalGraph::AddPoint (const TCalPoint & cal_point)
Definition at line 36 of file TCalGraph.cxx.
References TCalPoint::Area(), TCalPoint::AreaErr(), TCalPoint::Centroid(), and TCalPoint::CentroidErr().
BuildGraph()
virtual void TCalGraph::BuildGraph () private pure virtual
Implemented in TEfficiencyGraph.
Referenced by Draw().
Clear()
void TCalGraph::Clear (Option_t * opt = "") override
Definition at line 30 of file TCalGraph.cxx.
References fCompareMap.
Referenced by TCalGraph(), and TEfficiencyGraph::Clear().
ClearAllPoints()
void TCalGraph::ClearAllPoints (Option_t * opt = "")
Definition at line 129 of file TCalGraph.cxx.
Referenced by TEfficiencyGraph::BuildGraph().
CompareMap()
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > & TCalGraph::CompareMap () inline protected
Definition at line 57 of file TCalGraph.h.
References fCompareMap.
Referenced by TEfficiencyGraph::BuildGraph().
CorrectMissingPoints()
void TCalGraph::CorrectMissingPoints (TCalList & cal_list, TCalList & src_list) private
Definition at line 113 of file TCalGraph.cxx.
References fCompareMap, and TCalList::Map().
Referenced by AddLists().
Draw()
void TCalGraph::Draw (Option_t * opt = "") inline override
Definition at line 46 of file TCalGraph.h.
References BuildGraph().
FindClosestPointX()
Int_t TCalGraph::FindClosestPointX (const Double_t & x_val)
Definition at line 43 of file TCalGraph.cxx.
Referenced by FindDistToClosestPointX().
FindDistToClosestPointX()
Double_t TCalGraph::FindDistToClosestPointX (const Double_t & x_val)
Definition at line 57 of file TCalGraph.cxx.
References FindClosestPointX().
operator=() [1/2]
TCalGraph & TCalGraph::operator= (const TCalGraph &) default
operator=() [2/2]
TCalGraph & TCalGraph::operator= (TCalGraph &&) default noexcept
Print()
void TCalGraph::Print (Option_t * opt = "") const override
Definition at line 16 of file TCalGraph.cxx.
References DBLUE, DGREEN, DRED, fCompareMap, and RESET_COLOR.
Referenced by TEfficiencyGraph::Print().
Member Data Documentation
fCompareMap
std::map<UInt_t, std::pair<TCalPoint, TCalPoint> > TCalGraph::fCompareMap private
Definition at line 64 of file TCalGraph.h.
Referenced by AddLists(), Clear(), CompareMap(), CorrectMissingPoints(), and Print().