GRSISort: GHSymF Class Reference
GHSymF Class Reference
Detailed Description
Definition at line 127 of file GHSym.h.
Public Member Functions
GHSymF ()
GHSymF (const char *name, const char *title, Int_t nbins, const Double_t *bins)
GHSymF (const char *name, const char *title, Int_t nbins, const Float_t *bins)
GHSymF (const char *name, const char *title, Int_t nbins, Double_t low, Double_t up)
GHSymF (const GHSymF &)
GHSymF (GHSymF &&) noexcept
~GHSymF ()
void AddBinContent (Int_t bin) override
void AddBinContent (Int_t bin, Double_t w) override
Int_t BufferEmpty (Int_t action=0) override
virtual Int_t BufferFill (Double_t x, Double_t y, Double_t w)
Int_t BufferFill (Double_t, Double_t) override
void Copy (TObject &rh) const override
void Draw (Option_t *option="") override
TH1 * DrawCopy (Option_t *option="", const char *name_postfix="_copy") const override
Int_t Fill (const char *, Double_t) override
virtual Int_t Fill (const char *namex, const char *namey, Double_t w)
Int_t Fill (Double_t x, Double_t y) override
virtual Int_t Fill (Double_t x, Double_t y, Double_t w)
Int_t Fill (Double_t) override
void FillN (Int_t ntimes, const Double_t *x, const Double_t *y, const Double_t *w, Int_t stride=1) override
void FillN (Int_t, const Double_t *, const Double_t *, Int_t) override
void FillRandom (const char *fname, Int_t ntimes=5000, TRandom *rng=nullptr)
void FillRandom (TH1 *h, Int_t ntimes=5000, TRandom *rng=nullptr) override
Int_t FindFirstBinAbove (Double_t threshold=0, Int_t axis=1, Int_t firstBin=1, Int_t lastBin=-1) const override
Int_t FindLastBinAbove (Double_t threshold=0, Int_t axis=1, Int_t firstBin=1, Int_t lastBin=-1) const override
virtual void FitSlices (TF1 *f1=nullptr, Int_t firstbin=0, Int_t lastbin=-1, Int_t cut=0, Option_t *option="QNR", TObjArray *arr=nullptr)
Int_t GetBin (Int_t binx, Int_t biny=0, Int_t binz=0) const override
Double_t GetBinContent (Int_t bin) const override
Double_t GetBinContent (Int_t binx, Int_t biny) const override
Double_t GetBinContent (Int_t binx, Int_t biny, Int_t) const override
virtual Double_t GetBinWithContent2 (Double_t c, Int_t &binx, Int_t &biny, Int_t firstxbin=1, Int_t lastxbin=-1, Int_t firstybin=1, Int_t lastybin=-1, Double_t maxdiff=0) const
Double_t GetCellContent (Int_t binx, Int_t biny) const override
Double_t GetCellError (Int_t binx, Int_t biny) const override
virtual Double_t GetCorrelationFactor (Int_t axis1=1, Int_t axis2=2) const
virtual Double_t GetCovariance (Int_t axis1=1, Int_t axis2=2) const
TH2F * GetMatrix (bool force=false)
virtual void GetRandom2 (Double_t &x, Double_t &y)
void GetStats (Double_t *stats) const override
virtual Double_t Integral (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Option_t *option="") const
virtual Double_t Integral (Int_t, Int_t, Int_t, Int_t, Int_t, Int_t, Option_t *="") const
Double_t Integral (Option_t *option="") const override
virtual Double_t IntegralAndError (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Double_t &error, Option_t *option="") const
Double_t Interpolate (Double_t) const override
Double_t Interpolate (Double_t, Double_t) const override
Double_t Interpolate (Double_t, Double_t, Double_t) const override
Double_t KolmogorovTest (const TH1 *h2, Option_t *option="") const override
Long64_t Merge (TCollection *list) override
GHSymF & operator= (const GHSymF &h1)
GHSymF & operator= (GHSymF &&) noexcept
virtual TProfile * Profile (const char *name="_pf", Int_t firstbin=1, Int_t lastbin=-1, Option_t *option="") const
virtual TH1D * Projection (const char *name="_pr", Int_t firstBin=0, Int_t lastBin=-1, Option_t *option="") const
void PutStats (Double_t *stats) override
virtual GHSym * Rebin2D (Int_t ngroup=2, const char *newname="")
void Reset (Option_t *option="") override
Double_t RetrieveBinContent (Int_t bin) const override
void SetBinContent (Int_t bin, Double_t content) override
void SetBinContent (Int_t binx, Int_t biny, Double_t content) override
void SetBinContent (Int_t binx, Int_t biny, Int_t, Double_t content) override
void SetBinsLength (Int_t n=-1) override
void SetCellContent (Int_t binx, Int_t biny, Double_t content) override
void SetCellError (Int_t binx, Int_t biny, Double_t content) override
virtual void SetShowProjectionX (Int_t nbins=1)
virtual void SetShowProjectionY (Int_t nbins=1)
TH1 * ShowBackground (Int_t niter=20, Option_t *option="same") override
Int_t ShowPeaks (Double_t sigma=2, Option_t *option="", Double_t threshold=0.05) override
void Smooth (Int_t ntimes=1, Option_t *option="") override
void UpdateBinContent (Int_t bin, Double_t content) override
Protected Member Functions
virtual Double_t DoIntegral (Int_t binx1, Int_t binx2, Int_t biny1, Int_t biny2, Double_t &error, Option_t *option, Bool_t doError=kFALSE) const
TH2 * Matrix ()
void Matrix (TH2 *val)
Private Attributes
TH2 * fMatrix {nullptr}
Double_t fTsumwxy {0.}
Double_t fTsumwy {0.}
Double_t fTsumwy2 {0.}
Friends
GHSymF operator* (Float_t c1, GHSymF &h1)
GHSymF operator* (GHSymF &h1, Float_t c1)
GHSymF operator* (GHSymF &h1, GHSymF &h2)
GHSymF operator+ (GHSymF &h1, GHSymF &h2)
GHSymF operator- (GHSymF &h1, GHSymF &h2)
GHSymF operator/ (GHSymF &h1, GHSymF &h2)
Constructor & Destructor Documentation
GHSymF() [1/6]
GHSymF::GHSymF ()
Definition at line 2721 of file GHSym.cxx.
References SetBinsLength().
GHSymF() [2/6]
GHSymF::GHSymF (const char * name, const char * title, Int_t nbins, Double_t low, Double_t up)
Definition at line 2729 of file GHSym.cxx.
GHSymF() [3/6]
GHSymF::GHSymF (const char * name, const char * title, Int_t nbins, const Double_t * bins)
Definition at line 2742 of file GHSym.cxx.
GHSymF() [4/6]
GHSymF::GHSymF (const char * name, const char * title, Int_t nbins, const Float_t * bins)
Definition at line 2750 of file GHSym.cxx.
GHSymF() [5/6]
GHSymF::GHSymF (const GHSymF & rhs)
Definition at line 2758 of file GHSym.cxx.
References Copy().
GHSymF() [6/6]
GHSymF::GHSymF (GHSymF && rhs) noexcept
Definition at line 2764 of file GHSym.cxx.
References GHSym::Copy().
~GHSymF()
GHSymF::~GHSymF () default
Member Function Documentation
AddBinContent() [1/2]
void GHSymF::AddBinContent (Int_t bin) inline override
Definition at line 139 of file GHSym.h.
AddBinContent() [2/2]
void GHSymF::AddBinContent (Int_t bin, Double_t w) inline override
Definition at line 140 of file GHSym.h.
BufferEmpty()
Int_t GHSym::BufferEmpty (Int_t action = 0) override inherited
Fill histogram with all entries in the buffer. action = -1 histogram is reset and refilled from the buffer (called by THistPainter::Paint) action = 0 histogram is filled from the buffer action = 1 histogram is filled and buffer is deleted The buffer is automatically deleted when the number of entries in the buffer is greater than the number of entries in the histogram
Definition at line 77 of file GHSym.cxx.
References GHSym::Fill(), and GHSym::Reset().
Referenced by GHSym::BufferFill(), GHSymD::GetBinContent(), GetBinContent(), GHSym::GetStats(), and GHSym::Merge().
BufferFill() [1/2]
Int_t GHSym::BufferFill (Double_t x, Double_t y, Double_t w) virtual inherited
Definition at line 174 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::Fill(), and GHSym::Reset().
BufferFill() [2/2]
Int_t GHSym::BufferFill (Double_t , Double_t) inline override inherited
Definition at line 26 of file GHSym.h.
Referenced by GHSym::Fill(), and GHSym::Fill().
Copy()
void GHSymF::Copy (TObject & rh) const override
Definition at line 2792 of file GHSym.cxx.
References GHSym::Copy().
Referenced by GHSymF(), and operator=().
DoIntegral()
Double_t GHSym::DoIntegral (Int_t binx1, Int_t binx2, Int_t biny1, Int_t biny2, Double_t & error, Option_t * option, Bool_t doError = kFALSE) const protected virtual inherited
Definition at line 214 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Integral(), and GHSym::IntegralAndError().
Draw()
void GHSymF::Draw (Option_t * option = "") inline override
Definition at line 142 of file GHSym.h.
References GetMatrix().
DrawCopy()
TH1 * GHSymF::DrawCopy (Option_t * option = "", const char * name_postfix = "_copy") const override
Definition at line 2797 of file GHSym.cxx.
Fill() [1/5]
Int_t GHSym::Fill (const char * , Double_t) inline override inherited
Definition at line 30 of file GHSym.h.
References GHSym::Fill().
Referenced by GHSym::Fill().
Fill() [2/5]
Int_t GHSym::Fill (const char * namex, const char * namey, Double_t w) virtual inherited
Definition at line 382 of file GHSym.cxx.
References GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [3/5]
Int_t GHSym::Fill (Double_t x, Double_t y) override inherited
Increment cell defined by x,y by 1.
Definition at line 288 of file GHSym.cxx.
References GHSym::BufferFill(), GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [4/5]
Int_t GHSym::Fill (Double_t x, Double_t y, Double_t w) virtual inherited
Increment cell defined by x,y by 1.
Definition at line 335 of file GHSym.cxx.
References GHSym::BufferFill(), GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Fill() [5/5]
Int_t GHSym::Fill (Double_t) override inherited
Definition at line 281 of file GHSym.cxx.
Referenced by GHSym::BufferEmpty(), GHSym::BufferFill(), GHSym::FillN(), GHSym::FillRandom(), and GHSym::Merge().
FillN() [1/2]
void GHSym::FillN (Int_t ntimes, const Double_t * x, const Double_t * y, const Double_t * w, Int_t stride = 1) override inherited
Definition at line 430 of file GHSym.cxx.
References GHSym::Fill().
FillN() [2/2]
void GHSym::FillN (Int_t , const Double_t * , const Double_t * , Int_t) inline override inherited
Definition at line 34 of file GHSym.h.
FillRandom() [1/2]
void GHSym::FillRandom (const char * fname, Int_t ntimes = 5000, TRandom * rng = nullptr) inherited
Definition at line 459 of file GHSym.cxx.
References GHSym::Fill().
FillRandom() [2/2]
void GHSym::FillRandom (TH1 * h, Int_t ntimes = 5000, TRandom * rng = nullptr) override inherited
Definition at line 531 of file GHSym.cxx.
References hist.
FindFirstBinAbove()
Int_t GHSym::FindFirstBinAbove (Double_t threshold = 0, Int_t axis = 1, Int_t firstBin = 1, Int_t lastBin = -1) const override inherited
Definition at line 574 of file GHSym.cxx.
FindLastBinAbove()
Int_t GHSym::FindLastBinAbove (Double_t threshold = 0, Int_t axis = 1, Int_t firstBin = 1, Int_t lastBin = -1) const override inherited
Definition at line 607 of file GHSym.cxx.
FitSlices()
void GHSym::FitSlices (TF1 * f1 = nullptr, Int_t firstbin = 0, Int_t lastbin = -1, Int_t cut = 0, Option_t * option = "QNR", TObjArray * arr = nullptr) virtual inherited
Definition at line 640 of file GHSym.cxx.
References GHSym::Projection().
GetBin()
Int_t GHSym::GetBin (Int_t binx, Int_t biny = 0, Int_t binz = 0) const override inherited
Definition at line 813 of file GHSym.cxx.
Referenced by GHSym::DoIntegral(), GHSymD::GetBinContent(), GHSymD::GetBinContent(), GetBinContent(), GetBinContent(), GHSym::GetCellContent(), GHSym::GetCellError(), GHSym::GetStats(), GHSym::Merge(), GHSym::Profile(), GHSym::Rebin2D(), GHSymD::SetBinContent(), GHSymD::SetBinContent(), SetBinContent(), SetBinContent(), GHSym::SetCellContent(), GHSym::SetCellError(), and GHSym::Smooth().
GetBinContent() [1/3]
Double_t GHSymF::GetBinContent (Int_t bin) const override
Definition at line 2814 of file GHSym.cxx.
References GHSym::BufferEmpty().
Referenced by GetMatrix().
GetBinContent() [2/3]
Double_t GHSymF::GetBinContent (Int_t binx, Int_t biny) const inline override
Definition at line 145 of file GHSym.h.
References GHSym::GetBin(), and GetBinContent().
Referenced by GetBinContent().
GetBinContent() [3/3]
Double_t GHSymF::GetBinContent (Int_t binx, Int_t biny, Int_t) const inline override
Definition at line 146 of file GHSym.h.
References GHSym::GetBin(), and GetBinContent().
Referenced by GetBinContent().
GetBinWithContent2()
Double_t GHSym::GetBinWithContent2 (Double_t c, Int_t & binx, Int_t & biny, Int_t firstxbin = 1, Int_t lastxbin = -1, Int_t firstybin = 1, Int_t lastybin = -1, Double_t maxdiff = 0) const virtual inherited
Definition at line 834 of file GHSym.cxx.
GetCellContent()
Double_t GHSym::GetCellContent (Int_t binx, Int_t biny) const override inherited
Definition at line 890 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Projection().
GetCellError()
Double_t GHSym::GetCellError (Int_t binx, Int_t biny) const override inherited
Definition at line 895 of file GHSym.cxx.
References GHSym::GetBin().
Referenced by GHSym::Projection().
GetCorrelationFactor()
Double_t GHSym::GetCorrelationFactor (Int_t axis1 = 1, Int_t axis2 = 2) const virtual inherited
Definition at line 900 of file GHSym.cxx.
References GHSym::GetCovariance().
GetCovariance()
Double_t GHSym::GetCovariance (Int_t axis1 = 1, Int_t axis2 = 2) const virtual inherited
Definition at line 922 of file GHSym.cxx.
References GHSym::GetStats().
Referenced by GHSym::GetCorrelationFactor().
GetMatrix()
TH2F * GHSymF::GetMatrix (bool force = false)
Definition at line 2772 of file GHSym.cxx.
References GetBinContent(), and GHSym::Matrix().
Referenced by Draw().
GetRandom2()
void GHSym::GetRandom2 (Double_t & x, Double_t & y) virtual inherited
Definition at line 953 of file GHSym.cxx.
GetStats()
void GHSym::GetStats (Double_t * stats) const override inherited
Definition at line 996 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::fTsumwxy, GHSym::fTsumwy, GHSym::fTsumwy2, and GHSym::GetBin().
Referenced by GHSym::GetCovariance(), GHSym::Merge(), GHSym::Projection(), and GHSym::Rebin2D().
Integral() [1/3]
Double_t GHSym::Integral (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Option_t * option = "") const virtual inherited
Definition at line 1089 of file GHSym.cxx.
References GHSym::DoIntegral().
Integral() [2/3]
virtual Double_t GHSym::Integral (Int_t , Int_t , Int_t , Int_t , Int_t , Int_t , Option_t * = "") const inline virtual inherited
Definition at line 78 of file GHSym.h.
Integral() [3/3]
Double_t GHSym::Integral (Option_t * option = "") const override inherited
Definition at line 1079 of file GHSym.cxx.
References GHSym::Integral().
Referenced by GHSym::Integral().
IntegralAndError()
Double_t GHSym::IntegralAndError (Int_t firstxbin, Int_t lastxbin, Int_t firstybin, Int_t lastybin, Double_t & error, Option_t * option = "") const virtual inherited
Definition at line 1100 of file GHSym.cxx.
References GHSym::DoIntegral().
Interpolate() [1/3]
Double_t GHSym::Interpolate (Double_t) const override inherited
Definition at line 1116 of file GHSym.cxx.
Interpolate() [2/3]
Double_t GHSym::Interpolate (Double_t x, Double_t y) const override inherited
Definition at line 1127 of file GHSym.cxx.
Interpolate() [3/3]
Double_t GHSym::Interpolate (Double_t , Double_t , Double_t) const override inherited
Definition at line 1224 of file GHSym.cxx.
KolmogorovTest()
Double_t GHSym::KolmogorovTest (const TH1 * h2, Option_t * option = "") const override inherited
Definition at line 1232 of file GHSym.cxx.
Matrix() [1/2]
TH2 * GHSym::Matrix () inline protected inherited
Definition at line 113 of file GHSym.h.
References GHSym::fMatrix.
Referenced by GHSymD::GetMatrix(), and GetMatrix().
Matrix() [2/2]
void GHSym::Matrix (TH2 * val) inline protected inherited
Definition at line 114 of file GHSym.h.
References GHSym::fMatrix.
Merge()
Long64_t GHSym::Merge (TCollection * list) override inherited
Definition at line 1448 of file GHSym.cxx.
References GHSym::BufferEmpty(), GHSym::Copy(), GHSym::Fill(), GHSym::GetBin(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
operator=() [1/2]
GHSymF & GHSymF::operator= (const GHSymF & h1)
Definition at line 2868 of file GHSym.cxx.
References Copy().
operator=() [2/2]
GHSymF & GHSymF::operator= (GHSymF && h1) noexcept
Definition at line 2878 of file GHSym.cxx.
Profile()
TProfile * GHSym::Profile (const char * name = "_pf", Int_t firstbin = 1, Int_t lastbin = -1, Option_t * option = "") const virtual inherited
Definition at line 1720 of file GHSym.cxx.
References GHSym::GetBin().
Projection()
TH1D * GHSym::Projection (const char * name = "_pr", Int_t firstBin = 0, Int_t lastBin = -1, Option_t * option = "") const virtual inherited
method for performing projection
Definition at line 1957 of file GHSym.cxx.
References GHSym::GetCellContent(), GHSym::GetCellError(), and GHSym::GetStats().
Referenced by GHSym::FitSlices().
PutStats()
void GHSym::PutStats (Double_t * stats) override inherited
Definition at line 2198 of file GHSym.cxx.
References GHSym::fTsumwxy, GHSym::fTsumwy, and GHSym::fTsumwy2.
Referenced by GHSym::Merge(), and GHSym::Rebin2D().
Rebin2D()
GHSym * GHSym::Rebin2D (Int_t ngroup = 2, const char * newname = "") virtual inherited
Definition at line 2207 of file GHSym.cxx.
References GHSym::GetBin(), GHSym::GetStats(), and GHSym::PutStats().
Reset()
void GHSymF::Reset (Option_t * option = "") override
Definition at line 2833 of file GHSym.cxx.
References GHSym::Reset().
RetrieveBinContent()
Double_t GHSymF::RetrieveBinContent (Int_t bin) const inline override
Definition at line 148 of file GHSym.h.
SetBinContent() [1/3]
void GHSymF::SetBinContent (Int_t bin, Double_t content) override
Definition at line 2842 of file GHSym.cxx.
Referenced by SetBinContent().
SetBinContent() [2/3]
void GHSymF::SetBinContent (Int_t binx, Int_t biny, Double_t content) inline override
Definition at line 150 of file GHSym.h.
References GHSym::GetBin(), and SetBinContent().
Referenced by SetBinContent().
SetBinContent() [3/3]
void GHSymF::SetBinContent (Int_t binx, Int_t biny, Int_t , Double_t content) inline override
Definition at line 151 of file GHSym.h.
References GHSym::GetBin(), and SetBinContent().
SetBinsLength()
void GHSymF::SetBinsLength (Int_t n = -1) override
Definition at line 2856 of file GHSym.cxx.
Referenced by GHSymF().
SetCellContent()
void GHSym::SetCellContent (Int_t binx, Int_t biny, Double_t content) override inherited
Definition at line 2541 of file GHSym.cxx.
References GHSym::GetBin().
SetCellError()
void GHSym::SetCellError (Int_t binx, Int_t biny, Double_t content) override inherited
Definition at line 2546 of file GHSym.cxx.
References GHSym::GetBin().
SetShowProjectionX()
void GHSym::SetShowProjectionX (Int_t nbins = 1) virtual inherited
Definition at line 2551 of file GHSym.cxx.
SetShowProjectionY()
void GHSym::SetShowProjectionY (Int_t nbins = 1) virtual inherited
Definition at line 2565 of file GHSym.cxx.
ShowBackground()
TH1 * GHSym::ShowBackground (Int_t niter = 20, Option_t * option = "same") override inherited
Definition at line 2579 of file GHSym.cxx.
ShowPeaks()
Int_t GHSym::ShowPeaks (Double_t sigma = 2, Option_t * option = "", Double_t threshold = 0.05) override inherited
Definition at line 2589 of file GHSym.cxx.
Smooth()
void GHSym::Smooth (Int_t ntimes = 1, Option_t * option = "") override inherited
Definition at line 2602 of file GHSym.cxx.
References GHSym::GetBin().
UpdateBinContent()
void GHSymF::UpdateBinContent (Int_t bin, Double_t content) inline override
Definition at line 156 of file GHSym.h.
Friends And Related Symbol Documentation
operator* [1/3]
GHSymF operator* (Float_t c1, GHSymF & h1) friend
Definition at line 2888 of file GHSym.cxx.
operator* [2/3]
GHSymF operator* (GHSymF & h1, Float_t c1) friend
Definition at line 160 of file GHSym.h.
operator* [3/3]
GHSymF operator* (GHSymF & h1, GHSymF & h2) friend
Definition at line 2918 of file GHSym.cxx.
operator+
GHSymF operator+ (GHSymF & h1, GHSymF & h2) friend
Definition at line 2898 of file GHSym.cxx.
operator-
GHSymF operator- (GHSymF & h1, GHSymF & h2) friend
Definition at line 2908 of file GHSym.cxx.
operator/
GHSymF operator/ (GHSymF & h1, GHSymF & h2) friend
Definition at line 2928 of file GHSym.cxx.
Member Data Documentation
fMatrix
TH2* GHSym::fMatrix {nullptr} private inherited
! Transient pointer to the 2D-Matrix used in Draw() or GetMatrix()
Definition at line 120 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Matrix(), GHSym::Matrix(), and GHSym::Reset().
fTsumwxy
Double_t GHSym::fTsumwxy {0.} private inherited
Total Sum of weight*X*Y.
Definition at line 119 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
fTsumwy
Double_t GHSym::fTsumwy {0.} private inherited
Total Sum of weight*Y.
Definition at line 117 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().
fTsumwy2
Double_t GHSym::fTsumwy2 {0.} private inherited
Total Sum of weight*Y*Y.
Definition at line 118 of file GHSym.h.
Referenced by GHSym::Copy(), GHSym::Fill(), GHSym::Fill(), GHSym::Fill(), GHSym::GetStats(), GHSym::PutStats(), and GHSym::Reset().