GRSISort: TTdrMnemonic Class Reference
TTdrMnemonic Class Reference
Detailed Description
Definition at line 11 of file TTdrMnemonic.h.
Public Types
enum class EMnemonic {
kA , kB , kC , kD ,
kE , kF , kG , kH ,
kI , kJ , kK , kL ,
kM , kN , kO , kP ,
kQ , kR , kS , kT ,
kU , kV , kW , kX ,
kY , kZ , kClear
}
enum class ESystem {
kTdrClover , kTdrCloverBgo , kTdrTigress , kTdrTigressBgo ,
kTdrSiLi , kTdrPlastic , kClear
}
Public Member Functions
TTdrMnemonic ()
TTdrMnemonic (const char *name)
~TTdrMnemonic () override=default
virtual int16_t ArrayPosition () const
virtual EMnemonic ArraySubPosition () const
virtual std::string ArraySubPositionString () const
void Clear (Option_t *opt="") override
virtual EMnemonic CollectedCharge () const
virtual std::string CollectedChargeString () const
void EnumerateDigitizer (TPriorityValue< std::string > &digitizerName, TPriorityValue< EDigitizer > &digitizerType, TPriorityValue< int > &timeStampUnit) override
TClass * GetClassType () const override
const char * GetName () const override
double GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel *channel) const override
virtual int NumericArraySubPosition () const
virtual EMnemonic OutputSensor () const
virtual std::string OutputSensorString () const
virtual void Parse (const char *name)
void Parse (std::string *name) override
void Print (std::ostringstream &str) const
void Print (Option_t *opt="") const override
virtual int16_t Segment () const
virtual void Segment (int16_t val)
virtual void SetClassType (TClass *classType) const
void SetName (const char *val)
void SetName (const std::string &val)
virtual void SetRFMnemonic (std::string *name)
virtual EMnemonic SubSystem () const
virtual std::string SubSystemString () const
ESystem System () const
virtual std::string SystemString () const
Private Member Functions
void EnumerateMnemonic (std::string mnemonic_word, EMnemonic &mnemonic_enum)
void EnumerateSystem ()
Private Attributes
int16_t fArrayPosition
EMnemonic fArraySubPosition
std::string fArraySubPositionString
TClass * fClassType
EMnemonic fCollectedCharge
std::string fCollectedChargeString
std::string fName
EMnemonic fOutputSensor
std::string fOutputSensorString
int16_t fSegment
EMnemonic fSubSystem
std::string fSubSystemString
ESystem fSystem
std::string fSystemString
Static Private Attributes
static bool fPrint = true
Member Enumeration Documentation
EMnemonic
enum class TMnemonic::EMnemonic strong inherited
Enumerator
kA
kB
kC
kD
kE
kF
kG
kH
kI
kJ
kK
kL
kM
kN
kO
kP
kQ
kR
kS
kT
kU
kV
kW
kX
kY
kZ
kClear
Definition at line 33 of file TMnemonic.h.
ESystem
enum class TTdrMnemonic::ESystem strong
Enumerator
kTdrClover
kTdrCloverBgo
kTdrTigress
kTdrTigressBgo
kTdrSiLi
kTdrPlastic
kClear
Definition at line 20 of file TTdrMnemonic.h.
Constructor & Destructor Documentation
TTdrMnemonic() [1/2]
TTdrMnemonic::TTdrMnemonic () inline
Definition at line 13 of file TTdrMnemonic.h.
References Clear().
TTdrMnemonic() [2/2]
TTdrMnemonic::TTdrMnemonic (const char * name) inline
Definition at line 14 of file TTdrMnemonic.h.
References TMnemonic::Parse().
~TTdrMnemonic()
TTdrMnemonic::~TTdrMnemonic () override default
Member Function Documentation
ArrayPosition()
virtual int16_t TMnemonic::ArrayPosition () const inline virtual inherited
Definition at line 66 of file TMnemonic.h.
References TMnemonic::fArrayPosition.
Referenced by TCSM::AddFragment(), TS3Hit::GetArrayPosition(), and TTipHit::SetUpNumbering().
ArraySubPosition()
virtual EMnemonic TMnemonic::ArraySubPosition () const inline virtual inherited
Definition at line 62 of file TMnemonic.h.
References TMnemonic::fArraySubPosition.
Referenced by TSharc2::AddFragment(), TSharc::AddFragment(), TTrific::AddFragment(), and TGRSIMnemonic::NumericArraySubPosition().
ArraySubPositionString()
virtual std::string TMnemonic::ArraySubPositionString () const inline virtual inherited
Definition at line 71 of file TMnemonic.h.
References TMnemonic::fArraySubPositionString.
Referenced by TCSM::AddFragment(), TS3Hit::GetDistanceStr(), and TTipHit::SetUpNumbering().
Clear()
void TTdrMnemonic::Clear (Option_t * opt = "") override
Referenced by TTdrMnemonic().
CollectedCharge()
virtual EMnemonic TMnemonic::CollectedCharge () const inline virtual inherited
Definition at line 64 of file TMnemonic.h.
References TMnemonic::fCollectedCharge.
Referenced by TEmma::AddFragment(), TRcmp::AddFragment(), TS3::AddFragment(), TSharc2::AddFragment(), and TSharc::AddFragment().
CollectedChargeString()
virtual std::string TMnemonic::CollectedChargeString () const inline virtual inherited
Definition at line 72 of file TMnemonic.h.
References TMnemonic::fCollectedChargeString.
Referenced by TCSM::AddFragment().
EnumerateDigitizer()
void TTdrMnemonic::EnumerateDigitizer (TPriorityValue< std::string > & digitizerName, TPriorityValue< EDigitizer > & digitizerType, TPriorityValue< int > & timeStampUnit) override virtual
Reimplemented from TMnemonic.
Definition at line 46 of file TTdrMnemonic.cxx.
References kDefault, kFastPixie, kPixie, kPixieTapeMove, TPriorityValue< T >::Priority(), TPriorityValue< T >::Set(), and TPriorityValue< T >::Value().
EnumerateMnemonic()
void TMnemonic::EnumerateMnemonic (std::string mnemonic_word, EMnemonic & mnemonic_enum) private inherited
Definition at line 23 of file TMnemonic.cxx.
References TMnemonic::kA, TMnemonic::kB, TMnemonic::kC, TMnemonic::kClear, TMnemonic::kD, TMnemonic::kE, TMnemonic::kF, TMnemonic::kG, TMnemonic::kH, TMnemonic::kI, TMnemonic::kJ, TMnemonic::kK, TMnemonic::kL, TMnemonic::kM, TMnemonic::kN, TMnemonic::kO, TMnemonic::kP, TMnemonic::kQ, TMnemonic::kR, TMnemonic::kS, TMnemonic::kT, TMnemonic::kU, TMnemonic::kV, TMnemonic::kW, TMnemonic::kX, TMnemonic::kY, and TMnemonic::kZ.
Referenced by TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
EnumerateSystem()
void TTdrMnemonic::EnumerateSystem () private
Definition at line 21 of file TTdrMnemonic.cxx.
References fSystem, TMnemonic::fSystemString, kClear, TMnemonic::kS, kTdrClover, kTdrCloverBgo, kTdrPlastic, kTdrSiLi, kTdrTigress, kTdrTigressBgo, and TMnemonic::SubSystem().
Referenced by Parse().
GetClassType()
TClass * TTdrMnemonic::GetClassType () const override virtual
Reimplemented from TMnemonic.
Definition at line 91 of file TTdrMnemonic.cxx.
References TMnemonic::fClassType, kTdrClover, kTdrCloverBgo, kTdrPlastic, kTdrSiLi, kTdrTigress, kTdrTigressBgo, and System().
GetName()
const char * TMnemonic::GetName () const inline override inherited
Definition at line 103 of file TMnemonic.h.
References TMnemonic::fName.
GetTime()
double TTdrMnemonic::GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel * channel) const override virtual
Reimplemented from TMnemonic.
Definition at line 109 of file TTdrMnemonic.cxx.
References TChannel::CalibrateCFD(), TChannel::GetDigitizerType(), TChannel::GetTimeOffset(), TChannel::GetTimeStampUnit(), TChannel::GetTZero(), kFastPixie, and kPixie.
NumericArraySubPosition()
int TMnemonic::NumericArraySubPosition () const virtual inherited
Reimplemented in TGRSIMnemonic.
Definition at line 132 of file TMnemonic.cxx.
References TMnemonic::fArraySubPosition, TMnemonic::kB, TMnemonic::kG, TMnemonic::kR, and TMnemonic::kW.
Referenced by TChannel::GetCrystalNumber().
OutputSensor()
virtual EMnemonic TMnemonic::OutputSensor () const inline virtual inherited
Definition at line 65 of file TMnemonic.h.
References TMnemonic::fOutputSensor.
Referenced by TEmma::AddFragment(), TGriffin::AddFragment(), and TTigress::AddFragment().
OutputSensorString()
virtual std::string TMnemonic::OutputSensorString () const inline virtual inherited
Definition at line 73 of file TMnemonic.h.
References TMnemonic::fOutputSensorString.
Parse() [1/2]
void TMnemonic::Parse (const char * name) virtual inherited
Definition at line 91 of file TMnemonic.cxx.
References TMnemonic::Parse().
Parse() [2/2]
void TTdrMnemonic::Parse (std::string * name) override virtual
Reimplemented from TMnemonic.
Definition at line 65 of file TTdrMnemonic.cxx.
References EnumerateSystem(), and TMnemonic::Parse().
Print() [1/2]
void TMnemonic::Print (std::ostringstream & str) const inherited
Definition at line 112 of file TMnemonic.cxx.
References TMnemonic::fArrayPosition, TMnemonic::fArraySubPositionString, TMnemonic::fCollectedChargeString, TMnemonic::fOutputSensorString, TMnemonic::fSegment, TMnemonic::fSubSystemString, and TMnemonic::fSystemString.
Print() [2/2]
void TTdrMnemonic::Print (Option_t * opt = "") const override
Definition at line 78 of file TTdrMnemonic.cxx.
References TMnemonic::fArrayPosition, TMnemonic::fArraySubPositionString, TMnemonic::fCollectedChargeString, TMnemonic::fOutputSensorString, TMnemonic::fSegment, TMnemonic::fSubSystemString, and TMnemonic::fSystemString.
Segment() [1/2]
virtual int16_t TMnemonic::Segment () const inline virtual inherited
Definition at line 67 of file TMnemonic.h.
References TMnemonic::fSegment.
Referenced by TGRSIMnemonic::Parse().
Segment() [2/2]
virtual void TMnemonic::Segment (int16_t val) inline virtual inherited
Definition at line 86 of file TMnemonic.h.
References TMnemonic::fSegment.
SetClassType()
virtual void TMnemonic::SetClassType (TClass * classType) const inline virtual inherited
Definition at line 92 of file TMnemonic.h.
References TMnemonic::fClassType.
Referenced by TGRSIMnemonic::GetClassType(), and TChannel::SetClassType().
SetName() [1/2]
void TMnemonic::SetName (const char * val) inline inherited
Definition at line 101 of file TMnemonic.h.
References TMnemonic::fName.
Referenced by TMnemonic::Parse().
SetName() [2/2]
void TMnemonic::SetName (const std::string & val) inline inherited
Definition at line 102 of file TMnemonic.h.
References TMnemonic::fName.
SetRFMnemonic()
void TMnemonic::SetRFMnemonic (std::string * name) virtual inherited
Definition at line 97 of file TMnemonic.cxx.
References TMnemonic::EnumerateMnemonic(), TMnemonic::fArrayPosition, TMnemonic::fArraySubPosition, TMnemonic::fArraySubPositionString, TMnemonic::fCollectedCharge, TMnemonic::fCollectedChargeString, TMnemonic::fOutputSensor, TMnemonic::fOutputSensorString, TMnemonic::fSegment, TMnemonic::fSubSystem, TMnemonic::fSubSystemString, and TMnemonic::fSystemString.
Referenced by TGRSIMnemonic::Parse(), and TMnemonic::Parse().
SubSystem()
virtual EMnemonic TMnemonic::SubSystem () const inline virtual inherited
Definition at line 61 of file TMnemonic.h.
References TMnemonic::fSubSystem.
Referenced by TEmma::AddFragment(), TFipps::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTigress::AddFragment(), TGRSIMnemonic::EnumerateSystem(), TILLMnemonic::EnumerateSystem(), and EnumerateSystem().
SubSystemString()
virtual std::string TMnemonic::SubSystemString () const inline virtual inherited
Definition at line 70 of file TMnemonic.h.
References TMnemonic::fSubSystemString.
Referenced by TTipHit::SetUpNumbering().
System()
ESystem TTdrMnemonic::System () const inline
Definition at line 30 of file TTdrMnemonic.h.
References fSystem.
Referenced by GetClassType(), and TTdrDetectorInformation::Set().
SystemString()
virtual std::string TMnemonic::SystemString () const inline virtual inherited
Definition at line 69 of file TMnemonic.h.
References TMnemonic::fSystemString.
Referenced by TGRSIMnemonic::EnumerateSystem().
Member Data Documentation
fArrayPosition
int16_t TMnemonic::fArrayPosition private inherited
Definition at line 107 of file TMnemonic.h.
Referenced by TMnemonic::ArrayPosition(), TMnemonic::Clear(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), and TMnemonic::SetRFMnemonic().
fArraySubPosition
EMnemonic TMnemonic::fArraySubPosition private inherited
Definition at line 116 of file TMnemonic.h.
Referenced by TMnemonic::ArraySubPosition(), TMnemonic::Clear(), TMnemonic::NumericArraySubPosition(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fArraySubPositionString
std::string TMnemonic::fArraySubPositionString private inherited
Definition at line 111 of file TMnemonic.h.
Referenced by TMnemonic::ArraySubPositionString(), TMnemonic::Clear(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), and TMnemonic::SetRFMnemonic().
fClassType
TClass* TMnemonic::fClassType mutable private inherited
! TGRSIDetector Type that this mnemonic represents
Definition at line 120 of file TMnemonic.h.
Referenced by THILMnemonic::GetClassType(), TILLMnemonic::GetClassType(), TMnemonic::GetClassType(), GetClassType(), and TMnemonic::SetClassType().
fCollectedCharge
EMnemonic TMnemonic::fCollectedCharge private inherited
Definition at line 117 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::CollectedCharge(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fCollectedChargeString
std::string TMnemonic::fCollectedChargeString private inherited
Definition at line 112 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::CollectedChargeString(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), and TMnemonic::SetRFMnemonic().
fName
std::string TMnemonic::fName private inherited
Definition at line 106 of file TMnemonic.h.
Referenced by TMnemonic::GetName(), TMnemonic::SetName(), and TMnemonic::SetName().
fOutputSensor
EMnemonic TMnemonic::fOutputSensor private inherited
Definition at line 118 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::OutputSensor(), TMnemonic::Parse(), and TMnemonic::SetRFMnemonic().
fOutputSensorString
std::string TMnemonic::fOutputSensorString private inherited
Definition at line 113 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::OutputSensorString(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), and TMnemonic::SetRFMnemonic().
fPrint
bool TMnemonic::fPrint = true static private inherited
Definition at line 124 of file TMnemonic.h.
Referenced by TMnemonic::EnumerateDigitizer().
fSegment
int16_t TMnemonic::fSegment private inherited
Definition at line 108 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), TMnemonic::Segment(), TMnemonic::Segment(), and TMnemonic::SetRFMnemonic().
fSubSystem
EMnemonic TMnemonic::fSubSystem private inherited
Definition at line 115 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), TMnemonic::SetRFMnemonic(), and TMnemonic::SubSystem().
fSubSystemString
std::string TMnemonic::fSubSystemString private inherited
Definition at line 110 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), TMnemonic::SetRFMnemonic(), and TMnemonic::SubSystemString().
fSystem
ESystem TTdrMnemonic::fSystem private
Definition at line 44 of file TTdrMnemonic.h.
Referenced by ClassImp(), EnumerateSystem(), and System().
fSystemString
std::string TMnemonic::fSystemString private inherited
Definition at line 109 of file TMnemonic.h.
Referenced by TMnemonic::Clear(), THILMnemonic::EnumerateSystem(), TILLMnemonic::EnumerateSystem(), EnumerateSystem(), TMnemonic::Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TMnemonic::Print(), Print(), TMnemonic::SetRFMnemonic(), and TMnemonic::SystemString().