GRSISort: TEventBuildingLoop Class Reference
TEventBuildingLoop Class Reference
Loops
Detailed Description
This loop builds events (vectors of fragments) based on timestamps and a build windows.
Definition at line 27 of file TEventBuildingLoop.h.
Public Types
enum class EBuildMode {
kDefault , kTime , kTimestamp , kTriggerId ,
kSkip
}
Public Member Functions
~TEventBuildingLoop () override
void ClearQueue () override
std::string EndStatus () override
unsigned long GetBuildWindow () const
size_t GetItemsCurrent () override
size_t GetItemsPopped () override
size_t GetItemsPushed () override
size_t GetRate () override
unsigned int GetSortDepth () const
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & InputQueue ()
bool IsPaused ()
bool IsRunning ()
bool Iteration () override
void Join ()
std::string Name () const
virtual void OnEnd ()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & OutOfOrderQueue ()
std::shared_ptr< ThreadsafeQueue< std::vector< std::shared_ptr< const TFragment > > > > & OutputQueue ()
void Pause ()
virtual std::string Progress ()
void Resume ()
void SetBuildWindow (long val)
void SetSortDepth (int val)
virtual std::string Status ()
void Stop ()
Static Public Member Functions
static std::string AllThreadHeader ()
static std::string AllThreadProgress ()
static std::string AllThreadStatus ()
static bool AnyThreadRunning ()
static std::string AnyThreadStatus ()
static void ClearAllQueues ()
static size_t ColumnWidth ()
static void ColumnWidth (size_t val)
static StoppableThread * Get (const std::string &name)
static TEventBuildingLoop * Get (std::string name="", EBuildMode mode=EBuildMode::kTimestamp, long buildWindow=2000)
static std::vector< StoppableThread * > GetAll ()
static int GetNThreads ()
static void join_status_thread ()
static void PauseAll ()
static void Print ()
static void ResumeAll ()
static void SendStop ()
static void start_status_thread ()
static void status_out ()
static void status_out_loop ()
static size_t StatusWidth ()
static void StatusWidth (size_t val)
static void stop_status_thread ()
static void StopAll ()
Static Public Attributes
static std::thread fStatusThread
static bool fStatusThreadOn = false
Protected Attributes
std::atomic_long fInputSize {0}
std::atomic_size_t fItemsPopped {0}
std::string fName
Static Protected Attributes
static std::map< std::string, StoppableThread * > fThreadMap
Private Member Functions
TEventBuildingLoop (const TEventBuildingLoop &other)
TEventBuildingLoop (std::string name, EBuildMode mode, long buildWindow)
bool CheckBuildCondition (const std::shared_ptr< const TFragment > &)
bool CheckTimeCondition (const std::shared_ptr< const TFragment > &)
bool CheckTimestampCondition (const std::shared_ptr< const TFragment > &)
bool CheckTriggerIdCondition (const std::shared_ptr< const TFragment > &)
ClassDef (StoppableThread, 0)
ClassDefOverride (TEventBuildingLoop, 0)
void Loop ()
TEventBuildingLoop & operator= (const TEventBuildingLoop &other)
Private Attributes
EBuildMode fBuildMode
long fBuildWindow
std::atomic_bool fForceStop {false}
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fInputQueue
std::vector< std::shared_ptr< const TFragment > > fNextEvent
std::multiset< std::shared_ptr< const TFragment >, std::function< bool(std::shared_ptr< const TFragment >, std::shared_ptr< const TFragment >)> > fOrdered
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fOutOfOrderQueue
std::shared_ptr< ThreadsafeQueue< std::vector< std::shared_ptr< const TFragment > > > > fOutputQueue
std::atomic_bool fPaused {false}
std::condition_variable fPausedWait
std::mutex fPauseMutex
bool fPreviousSortingDepthError
std::atomic_bool fRunning {false}
bool fSkipInputSort
unsigned int fSortingDepth
std::thread fThread
Static Private Attributes
static size_t fColumnWidth = 20
static size_t fStatusWidth = 80
Member Enumeration Documentation
EBuildMode
enum class TEventBuildingLoop::EBuildMode strong
Enumerator
kDefault
kTime
kTimestamp
kTriggerId
kSkip
Definition at line 29 of file TEventBuildingLoop.h.
Constructor & Destructor Documentation
~TEventBuildingLoop()
TEventBuildingLoop::~TEventBuildingLoop () override default
TEventBuildingLoop() [1/2]
TEventBuildingLoop::TEventBuildingLoop (std::string name, EBuildMode mode, long buildWindow) private
Definition at line 24 of file TEventBuildingLoop.cxx.
References DYELLOW, fBuildMode, fBuildWindow, fOrdered, fSkipInputSort, kDefault, kSkip, kTime, kTimestamp, kTriggerId, and RESET_COLOR.
TEventBuildingLoop() [2/2]
TEventBuildingLoop::TEventBuildingLoop (const TEventBuildingLoop & other) private
Member Function Documentation
AllThreadHeader()
std::string StoppableThread::AllThreadHeader () static inherited
Definition at line 73 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::ApplyOptions().
AllThreadProgress()
std::string StoppableThread::AllThreadProgress () static inherited
Definition at line 59 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AllThreadStatus()
std::string StoppableThread::AllThreadStatus () static inherited
Definition at line 83 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AnyThreadRunning()
bool StoppableThread::AnyThreadRunning () static inherited
Definition at line 37 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TChannel::GetChannel(), TGRSIint::LoopUntilDone(), and TGRSIInterruptHandler::Notify().
AnyThreadStatus()
std::string StoppableThread::AnyThreadStatus () static inherited
Definition at line 47 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
CheckBuildCondition()
bool TEventBuildingLoop::CheckBuildCondition (const std::shared_ptr< const TFragment > & frag) private
Definition at line 133 of file TEventBuildingLoop.cxx.
References CheckTimeCondition(), CheckTimestampCondition(), CheckTriggerIdCondition(), fBuildMode, fNextEvent, fOutputQueue, kSkip, kTime, kTimestamp, and kTriggerId.
Referenced by Iteration().
CheckTimeCondition()
bool TEventBuildingLoop::CheckTimeCondition (const std::shared_ptr< const TFragment > & frag) private
Definition at line 150 of file TEventBuildingLoop.cxx.
References TSortingDiagnostics::AddTime(), TGRSIOptions::AnalysisOptions(), fBuildWindow, fNextEvent, fOutOfOrderQueue, fOutputQueue, fPreviousSortingDepthError, fSortingDepth, TSingleton< TSortingDiagnostics >::Get(), TGRSIOptions::Get(), TSortingDiagnostics::OutOfTimeOrder(), TGRSIOptions::SortDepth(), and TAnalysisOptions::StaticWindow().
Referenced by CheckBuildCondition().
CheckTimestampCondition()
bool TEventBuildingLoop::CheckTimestampCondition (const std::shared_ptr< const TFragment > & frag) private
Definition at line 188 of file TEventBuildingLoop.cxx.
References TSortingDiagnostics::AddTimeStamp(), TGRSIOptions::AnalysisOptions(), fBuildWindow, fNextEvent, fOutOfOrderQueue, fOutputQueue, fPreviousSortingDepthError, fSortingDepth, TSingleton< TSortingDiagnostics >::Get(), TGRSIOptions::Get(), TSortingDiagnostics::OutOfOrder(), TGRSIOptions::SortDepth(), and TAnalysisOptions::StaticWindow().
Referenced by CheckBuildCondition().
CheckTriggerIdCondition()
bool TEventBuildingLoop::CheckTriggerIdCondition (const std::shared_ptr< const TFragment > & frag) private
Definition at line 223 of file TEventBuildingLoop.cxx.
References TSortingDiagnostics::AddTimeStamp(), fNextEvent, fOutOfOrderQueue, fOutputQueue, fPreviousSortingDepthError, fSortingDepth, TSingleton< TSortingDiagnostics >::Get(), TGRSIOptions::Get(), TSortingDiagnostics::OutOfOrder(), and TGRSIOptions::SortDepth().
Referenced by CheckBuildCondition().
ClassDef()
StoppableThread::ClassDef (StoppableThread , 0) private inherited
ClassDefOverride()
TEventBuildingLoop::ClassDefOverride (TEventBuildingLoop , 0) private
ClearAllQueues()
void StoppableThread::ClearAllQueues () static inherited
Definition at line 166 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIInterruptHandler::Notify().
ClearQueue()
void TEventBuildingLoop::ClearQueue () override virtual
Reimplemented from StoppableThread.
Definition at line 66 of file TEventBuildingLoop.cxx.
References fInputQueue, and fOutputQueue.
ColumnWidth() [1/2]
static size_t StoppableThread::ColumnWidth () inline static inherited
Definition at line 77 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
Referenced by TGRSIint::SetupPipeline().
ColumnWidth() [2/2]
static void StoppableThread::ColumnWidth (size_t val) inline static inherited
Definition at line 75 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
EndStatus()
std::string TEventBuildingLoop::EndStatus () override virtual
Reimplemented from StoppableThread.
Definition at line 259 of file TEventBuildingLoop.cxx.
References fInputQueue, and StoppableThread::fItemsPopped.
Get() [1/2]
StoppableThread * StoppableThread::Get (const std::string & name) static inherited
Definition at line 173 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by ClassImp(), ClassImp(), TAnalysisHistLoop::Get(), TFragHistLoop::Get(), TTerminalLoop< T >::Get(), TUnpackingLoop::Get(), TFragWriteLoop::Get(), TAnalysisWriteLoop::Get(), TFragmentChainLoop::Get(), and TDataLoop::Get().
Get() [2/2]
static TEventBuildingLoop * TEventBuildingLoop::Get (std::string name = "", EBuildMode mode = EBuildMode::kTimestamp, long buildWindow = 2000) static
Referenced by TGRSIint::SetupPipeline().
GetAll()
std::vector< StoppableThread * > StoppableThread::GetAll () static inherited
Definition at line 315 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
GetBuildWindow()
unsigned long TEventBuildingLoop::GetBuildWindow () const inline
Definition at line 60 of file TEventBuildingLoop.h.
References fBuildWindow.
GetItemsCurrent()
size_t TEventBuildingLoop::GetItemsCurrent () inline override virtual
Implements StoppableThread.
Definition at line 56 of file TEventBuildingLoop.h.
References fOutputQueue.
GetItemsPopped()
size_t TEventBuildingLoop::GetItemsPopped () inline override virtual
Implements StoppableThread.
Definition at line 55 of file TEventBuildingLoop.h.
References fOutputQueue.
GetItemsPushed()
size_t TEventBuildingLoop::GetItemsPushed () inline override virtual
Implements StoppableThread.
Definition at line 54 of file TEventBuildingLoop.h.
References fOutputQueue.
GetNThreads()
int StoppableThread::GetNThreads () static inherited
Definition at line 21 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::Print().
GetRate()
size_t TEventBuildingLoop::GetRate () inline override virtual
Implements StoppableThread.
Definition at line 57 of file TEventBuildingLoop.h.
GetSortDepth()
unsigned int TEventBuildingLoop::GetSortDepth () const inline
Definition at line 63 of file TEventBuildingLoop.h.
References fSortingDepth.
InputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TEventBuildingLoop::InputQueue () inline
Definition at line 39 of file TEventBuildingLoop.h.
References fInputQueue.
Referenced by TGRSIint::SetupPipeline().
IsPaused()
bool StoppableThread::IsPaused () inherited
Definition at line 224 of file StoppableThread.cxx.
References StoppableThread::fPaused.
IsRunning()
bool StoppableThread::IsRunning () inherited
Definition at line 219 of file StoppableThread.cxx.
References StoppableThread::fRunning.
Referenced by StoppableThread::status_out().
Iteration()
bool TEventBuildingLoop::Iteration () override virtual
Implements StoppableThread.
Definition at line 79 of file TEventBuildingLoop.cxx.
References CheckBuildCondition(), fInputQueue, StoppableThread::fInputSize, StoppableThread::fItemsPopped, fNextEvent, fOrdered, fOutputQueue, fSkipInputSort, and fSortingDepth.
Join()
void StoppableThread::Join () inherited
Definition at line 229 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), and StoppableThread::fThread.
Referenced by StoppableThread::StopAll().
join_status_thread()
void StoppableThread::join_status_thread () static inherited
Definition at line 280 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, and StoppableThread::stop_status_thread().
Loop()
void StoppableThread::Loop () private inherited
Definition at line 237 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, StoppableThread::fRunning, StoppableThread::Iteration(), and StoppableThread::OnEnd().
Referenced by StoppableThread::StoppableThread().
Name()
std::string StoppableThread::Name () const inline inherited
Definition at line 58 of file StoppableThread.h.
References StoppableThread::fName.
Referenced by TAnalysisWriteLoop::AddBranch(), TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), TUnpackingLoop::EndStatus(), and StoppableThread::status_out().
OnEnd()
virtual void StoppableThread::OnEnd () inline virtual inherited
Reimplemented in TAnalysisWriteLoop, TDataLoop, and TFragmentChainLoop.
Definition at line 54 of file StoppableThread.h.
Referenced by StoppableThread::Loop().
operator=()
TEventBuildingLoop & TEventBuildingLoop::operator= (const TEventBuildingLoop & other) private
OutOfOrderQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TEventBuildingLoop::OutOfOrderQueue () inline
Definition at line 47 of file TEventBuildingLoop.h.
References fOutOfOrderQueue.
Referenced by TGRSIint::SetupPipeline().
OutputQueue()
std::shared_ptr< ThreadsafeQueue< std::vector< std::shared_ptr< const TFragment > > > > & TEventBuildingLoop::OutputQueue () inline
Definition at line 43 of file TEventBuildingLoop.h.
References fOutputQueue.
Referenced by TGRSIint::SetupPipeline().
Pause()
void StoppableThread::Pause () inherited
Definition at line 202 of file StoppableThread.cxx.
References StoppableThread::fPaused, and StoppableThread::fRunning.
PauseAll()
void StoppableThread::PauseAll () static inherited
Definition at line 97 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Print()
void StoppableThread::Print () static inherited
Definition at line 254 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, StoppableThread::fThreadMap, StoppableThread::GetNThreads(), and hex().
Progress()
std::string StoppableThread::Progress () virtual inherited
Definition at line 119 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
Resume()
void StoppableThread::Resume () inherited
Definition at line 193 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
ResumeAll()
void StoppableThread::ResumeAll () static inherited
Definition at line 104 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIint::SetupPipeline().
SendStop()
void StoppableThread::SendStop () static inherited
Definition at line 135 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, and StoppableThread::Stop().
Referenced by StoppableThread::StopAll(), and TGRSIint::Terminate().
SetBuildWindow()
void TEventBuildingLoop::SetBuildWindow (long val) inline
Definition at line 59 of file TEventBuildingLoop.h.
References fBuildWindow.
SetSortDepth()
void TEventBuildingLoop::SetSortDepth (int val) inline
Definition at line 62 of file TEventBuildingLoop.h.
References fSortingDepth.
Referenced by TGRSIint::SetupPipeline().
start_status_thread()
void StoppableThread::start_status_thread () static inherited
Definition at line 265 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, StoppableThread::fStatusThreadOn, and StoppableThread::status_out_loop().
Referenced by StoppableThread::StoppableThread().
Status()
std::string StoppableThread::Status () virtual inherited
Definition at line 111 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
status_out()
void StoppableThread::status_out () static inherited
Definition at line 297 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::GetItemsCurrent(), StoppableThread::GetItemsPopped(), StoppableThread::GetItemsPushed(), StoppableThread::GetRate(), StoppableThread::IsRunning(), and StoppableThread::Name().
Referenced by StoppableThread::status_out_loop(), and StoppableThread::StopAll().
status_out_loop()
void StoppableThread::status_out_loop () static inherited
Definition at line 286 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn, and StoppableThread::status_out().
Referenced by StoppableThread::start_status_thread().
StatusWidth() [1/2]
static size_t StoppableThread::StatusWidth () inline static inherited
Definition at line 78 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Referenced by TGRSIint::SetupPipeline().
StatusWidth() [2/2]
static void StoppableThread::StatusWidth (size_t val) inline static inherited
Definition at line 76 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Stop()
void StoppableThread::Stop () inherited
Definition at line 209 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
Referenced by StoppableThread::SendStop().
stop_status_thread()
void StoppableThread::stop_status_thread () static inherited
Definition at line 273 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn.
Referenced by StoppableThread::join_status_thread().
StopAll()
void StoppableThread::StopAll () static inherited
Definition at line 147 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::Join(), StoppableThread::SendStop(), and StoppableThread::status_out().
Referenced by TGRSIint::Terminate().
Member Data Documentation
fBuildMode
EBuildMode TEventBuildingLoop::fBuildMode private
Definition at line 83 of file TEventBuildingLoop.h.
Referenced by TEventBuildingLoop(), and CheckBuildCondition().
fBuildWindow
long TEventBuildingLoop::fBuildWindow private
Definition at line 85 of file TEventBuildingLoop.h.
Referenced by TEventBuildingLoop(), CheckTimeCondition(), CheckTimestampCondition(), GetBuildWindow(), and SetBuildWindow().
fColumnWidth
size_t StoppableThread::fColumnWidth = 20 static private inherited
Definition at line 105 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::ColumnWidth(), StoppableThread::ColumnWidth(), StoppableThread::Print(), StoppableThread::Progress(), and StoppableThread::Status().
fForceStop
std::atomic_bool StoppableThread::fForceStop {false} private inherited
Definition at line 113 of file StoppableThread.h.
fInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TEventBuildingLoop::fInputQueue private
Definition at line 78 of file TEventBuildingLoop.h.
Referenced by ClearQueue(), EndStatus(), InputQueue(), and Iteration().
fInputSize
std::atomic_long StoppableThread::fInputSize {0} protected inherited
number of items in the input (queue), only updated within Iteration(), so not always fully up-to-date (signed to hold error from queue::pop)
Definition at line 95 of file StoppableThread.h.
Referenced by TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), TUnpackingLoop::Iteration(), StoppableThread::Progress(), and StoppableThread::Status().
fItemsPopped
std::atomic_size_t StoppableThread::fItemsPopped {0} protected inherited
number of items popped from input queue
Definition at line 94 of file StoppableThread.h.
Referenced by TAnalysisWriteLoop::EndStatus(), EndStatus(), TFragWriteLoop::EndStatus(), TFragmentChainLoop::GetItemsPopped(), TFragWriteLoop::GetItemsPopped(), TAnalysisWriteLoop::GetItemsPushed(), TFragmentChainLoop::GetItemsPushed(), TFragWriteLoop::GetItemsPushed(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), TUnpackingLoop::Iteration(), StoppableThread::Progress(), TFragmentChainLoop::Restart(), and StoppableThread::Status().
fName
std::string StoppableThread::fName protected inherited
Definition at line 99 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), and StoppableThread::Name().
fNextEvent
std::vector<std::shared_ptr<const TFragment> > TEventBuildingLoop::fNextEvent private
Definition at line 90 of file TEventBuildingLoop.h.
Referenced by CheckBuildCondition(), CheckTimeCondition(), CheckTimestampCondition(), CheckTriggerIdCondition(), and Iteration().
fOrdered
std::multiset<std::shared_ptr<const TFragment>, std::function<bool(std::shared_ptr<const TFragment>, std::shared_ptr<const TFragment>)> > TEventBuildingLoop::fOrdered private
Definition at line 94 of file TEventBuildingLoop.h.
Referenced by TEventBuildingLoop(), and Iteration().
fOutOfOrderQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TEventBuildingLoop::fOutOfOrderQueue private
Definition at line 80 of file TEventBuildingLoop.h.
Referenced by CheckTimeCondition(), CheckTimestampCondition(), CheckTriggerIdCondition(), and OutOfOrderQueue().
fOutputQueue
std::shared_ptr<ThreadsafeQueue<std::vector<std::shared_ptr<const TFragment> > > > TEventBuildingLoop::fOutputQueue private
Definition at line 79 of file TEventBuildingLoop.h.
Referenced by CheckBuildCondition(), CheckTimeCondition(), CheckTimestampCondition(), CheckTriggerIdCondition(), ClearQueue(), GetItemsCurrent(), GetItemsPopped(), GetItemsPushed(), Iteration(), and OutputQueue().
fPaused
std::atomic_bool StoppableThread::fPaused {false} private inherited
Definition at line 114 of file StoppableThread.h.
Referenced by StoppableThread::IsPaused(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fPausedWait
std::condition_variable StoppableThread::fPausedWait private inherited
Definition at line 115 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPauseMutex
std::mutex StoppableThread::fPauseMutex private inherited
Definition at line 116 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPreviousSortingDepthError
bool TEventBuildingLoop::fPreviousSortingDepthError private
Definition at line 86 of file TEventBuildingLoop.h.
Referenced by CheckTimeCondition(), CheckTimestampCondition(), and CheckTriggerIdCondition().
fRunning
std::atomic_bool StoppableThread::fRunning {false} private inherited
Definition at line 112 of file StoppableThread.h.
Referenced by StoppableThread::IsRunning(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fSkipInputSort
bool TEventBuildingLoop::fSkipInputSort private
Definition at line 87 of file TEventBuildingLoop.h.
Referenced by TEventBuildingLoop(), and Iteration().
fSortingDepth
unsigned int TEventBuildingLoop::fSortingDepth private
Definition at line 84 of file TEventBuildingLoop.h.
Referenced by CheckTimeCondition(), CheckTimestampCondition(), CheckTriggerIdCondition(), GetSortDepth(), Iteration(), and SetSortDepth().
fStatusThread
std::thread StoppableThread::fStatusThread static inherited
Definition at line 81 of file StoppableThread.h.
Referenced by StoppableThread::~StoppableThread(), StoppableThread::join_status_thread(), and StoppableThread::start_status_thread().
fStatusThreadOn
bool StoppableThread::fStatusThreadOn = false static inherited
Definition at line 83 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::start_status_thread(), StoppableThread::status_out_loop(), and StoppableThread::stop_status_thread().
fStatusWidth
size_t StoppableThread::fStatusWidth = 80 static private inherited
Definition at line 106 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::Print(), StoppableThread::StatusWidth(), and StoppableThread::StatusWidth().
fThread
std::thread StoppableThread::fThread private inherited
Definition at line 111 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), and StoppableThread::Join().
fThreadMap
std::map< std::string, StoppableThread * > StoppableThread::fThreadMap static protected inherited
Definition at line 91 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::AnyThreadRunning(), StoppableThread::AnyThreadStatus(), StoppableThread::ClearAllQueues(), StoppableThread::Get(), StoppableThread::GetAll(), StoppableThread::GetNThreads(), StoppableThread::PauseAll(), StoppableThread::Print(), StoppableThread::ResumeAll(), StoppableThread::SendStop(), StoppableThread::status_out(), and StoppableThread::StopAll().