GRSISort: TDetectorInformation Class Reference
TDetectorInformation Class Reference
Sorting
Detailed Description
Class containing setup specific detector information.
Definition at line 21 of file TDetectorInformation.h.
Public Member Functions
TDetectorInformation ()=default
TDetectorInformation (const TDetectorInformation &)=default
TDetectorInformation (TDetectorInformation &&) noexcept=default
~TDetectorInformation ()=default
virtual TEventBuildingLoop::EBuildMode BuildMode () const
void Clear (Option_t *="") override
TDetectorInformation & operator= (const TDetectorInformation &)=default
TDetectorInformation & operator= (TDetectorInformation &&) noexcept=default
void Print (Option_t *="") const override
virtual void Set ()
Constructor & Destructor Documentation
TDetectorInformation() [1/3]
TDetectorInformation::TDetectorInformation () default
TDetectorInformation() [2/3]
TDetectorInformation::TDetectorInformation (const TDetectorInformation &) default
TDetectorInformation() [3/3]
TDetectorInformation::TDetectorInformation (TDetectorInformation &&) default noexcept
~TDetectorInformation()
TDetectorInformation::~TDetectorInformation () default
Member Function Documentation
BuildMode()
virtual TEventBuildingLoop::EBuildMode TDetectorInformation::BuildMode () const inline virtual
Set the detector information based on the available TChannels.
Select build mode based on available detectors
Reimplemented in TGRSIDetectorInformation, THILDetectorInformation, TILLDetectorInformation, and TTdrDetectorInformation.
Definition at line 31 of file TDetectorInformation.h.
References TEventBuildingLoop::kDefault.
Referenced by TGRSIint::SetupPipeline().
Clear()
void TDetectorInformation::Clear (Option_t * = "") inline override
Definition at line 34 of file TDetectorInformation.h.
Referenced by TGRSIDetectorInformation::Clear(), THILDetectorInformation::Clear(), TILLDetectorInformation::Clear(), and TTdrDetectorInformation::Clear().
operator=() [1/2]
TDetectorInformation & TDetectorInformation::operator= (const TDetectorInformation &) default
operator=() [2/2]
TDetectorInformation & TDetectorInformation::operator= (TDetectorInformation &&) default noexcept
Print()
void TDetectorInformation::Print (Option_t * = "") const inline override
Definition at line 33 of file TDetectorInformation.h.
Referenced by TRunInfo::Print().
Set()
virtual void TDetectorInformation::Set () inline virtual
Reimplemented in TGRSIDetectorInformation, THILDetectorInformation, TILLDetectorInformation, and TTdrDetectorInformation.
Definition at line 30 of file TDetectorInformation.h.
Referenced by TGRSIint::SetupPipeline().