GRSISort: TMnemonic Class Reference
TMnemonic Class Reference
Detailed Description
Definition at line 19 of file TMnemonic.h.
Public Types
enum class EMnemonic {
kA , kB , kC , kD ,
kE , kF , kG , kH ,
kI , kJ , kK , kL ,
kM , kN , kO , kP ,
kQ , kR , kS , kT ,
kU , kV , kW , kX ,
kY , kZ , kClear
}
Public Member Functions
TMnemonic ()
TMnemonic (const char *name)
TMnemonic (const TMnemonic &)=default
TMnemonic (TMnemonic &&)=default
~TMnemonic ()=default
virtual int16_t ArrayPosition () const
virtual EMnemonic ArraySubPosition () const
virtual std::string ArraySubPositionString () const
void Clear (Option_t *opt="") override
virtual EMnemonic CollectedCharge () const
virtual std::string CollectedChargeString () const
virtual void EnumerateDigitizer (TPriorityValue< std::string > &, TPriorityValue< EDigitizer > &, TPriorityValue< int > &)
virtual TClass * GetClassType () const
const char * GetName () const override
virtual double GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel *channel) const
virtual int NumericArraySubPosition () const
TMnemonic & operator= (const TMnemonic &)=default
TMnemonic & operator= (TMnemonic &&)=default
virtual EMnemonic OutputSensor () const
virtual std::string OutputSensorString () const
virtual void Parse (const char *name)
virtual void Parse (std::string *name)
void Print (Option_t *opt="") const override
void Print (std::ostringstream &str) const
virtual int16_t Segment () const
virtual void Segment (int16_t val)
virtual void SetClassType (TClass *classType) const
void SetName (const char *val)
void SetName (const std::string &val)
virtual void SetRFMnemonic (std::string *name)
virtual EMnemonic SubSystem () const
virtual std::string SubSystemString () const
virtual std::string SystemString () const
Private Member Functions
void EnumerateMnemonic (std::string mnemonic_word, EMnemonic &mnemonic_enum)
Private Attributes
int16_t fArrayPosition
EMnemonic fArraySubPosition
std::string fArraySubPositionString
TClass * fClassType
EMnemonic fCollectedCharge
std::string fCollectedChargeString
std::string fName
EMnemonic fOutputSensor
std::string fOutputSensorString
int16_t fSegment
EMnemonic fSubSystem
std::string fSubSystemString
std::string fSystemString
Static Private Attributes
static bool fPrint = true
Member Enumeration Documentation
EMnemonic
enum class TMnemonic::EMnemonic strong
Enumerator
kA
kB
kC
kD
kE
kF
kG
kH
kI
kJ
kK
kL
kM
kN
kO
kP
kQ
kR
kS
kT
kU
kV
kW
kX
kY
kZ
kClear
Definition at line 33 of file TMnemonic.h.
Constructor & Destructor Documentation
TMnemonic() [1/4]
TMnemonic::TMnemonic () inline
Definition at line 21 of file TMnemonic.h.
References Clear().
TMnemonic() [2/4]
TMnemonic::TMnemonic (const char * name) inline explicit
Definition at line 22 of file TMnemonic.h.
References Parse().
TMnemonic() [3/4]
TMnemonic::TMnemonic (const TMnemonic &) default
TMnemonic() [4/4]
TMnemonic::TMnemonic (TMnemonic &&) default
~TMnemonic()
TMnemonic::~TMnemonic () default
Member Function Documentation
ArrayPosition()
virtual int16_t TMnemonic::ArrayPosition () const inline virtual
Definition at line 66 of file TMnemonic.h.
References fArrayPosition.
Referenced by TCSM::AddFragment(), TS3Hit::GetArrayPosition(), TChannel::GetDetectorNumber(), and TTipHit::SetUpNumbering().
ArraySubPosition()
virtual EMnemonic TMnemonic::ArraySubPosition () const inline virtual
Definition at line 62 of file TMnemonic.h.
References fArraySubPosition.
Referenced by TSharc::AddFragment(), TSharc2::AddFragment(), TTrific::AddFragment(), and TGRSIMnemonic::NumericArraySubPosition().
ArraySubPositionString()
virtual std::string TMnemonic::ArraySubPositionString () const inline virtual
Definition at line 71 of file TMnemonic.h.
References fArraySubPositionString.
Referenced by TCSM::AddFragment(), TS3Hit::GetDistanceStr(), and TTipHit::SetUpNumbering().
Clear()
void TMnemonic::Clear (Option_t * opt = "") override
Definition at line 8 of file TMnemonic.cxx.
References fArrayPosition, fArraySubPosition, fArraySubPositionString, fCollectedCharge, fCollectedChargeString, fOutputSensor, fOutputSensorString, fSegment, fSubSystem, fSubSystemString, fSystemString, and kClear.
Referenced by TMnemonic(), ClassImp(), ClassImp(), ClassImp(), and TGRSIMnemonic::Clear().
CollectedCharge()
virtual EMnemonic TMnemonic::CollectedCharge () const inline virtual
Definition at line 64 of file TMnemonic.h.
References fCollectedCharge.
Referenced by TEmma::AddFragment(), TRcmp::AddFragment(), TS3::AddFragment(), TSharc::AddFragment(), and TSharc2::AddFragment().
CollectedChargeString()
virtual std::string TMnemonic::CollectedChargeString () const inline virtual
Definition at line 72 of file TMnemonic.h.
References fCollectedChargeString.
Referenced by TCSM::AddFragment().
EnumerateDigitizer()
virtual void TMnemonic::EnumerateDigitizer (TPriorityValue< std::string > & , TPriorityValue< EDigitizer > & , TPriorityValue< int > &) inline virtual
Reimplemented in TGRSIMnemonic, THILMnemonic, TILLMnemonic, and TTdrMnemonic.
Definition at line 78 of file TMnemonic.h.
References fPrint, RED, and RESET_COLOR.
Referenced by TChannel::SetDigitizerType().
EnumerateMnemonic()
void TMnemonic::EnumerateMnemonic (std::string mnemonic_word, EMnemonic & mnemonic_enum) private
Definition at line 23 of file TMnemonic.cxx.
References kA, kB, kC, kClear, kD, kE, kF, kG, kH, kI, kJ, kK, kL, kM, kN, kO, kP, kQ, kR, kS, kT, kU, kV, kW, kX, kY, and kZ.
Referenced by Parse(), and SetRFMnemonic().
GetClassType()
TClass * TMnemonic::GetClassType () const virtual
Reimplemented in TGRSIMnemonic, THILMnemonic, TILLMnemonic, and TTdrMnemonic.
Definition at line 152 of file TMnemonic.cxx.
References fClassType.
Referenced by TChannel::GetClassType(), and TGRSIMnemonic::GetClassType().
GetName()
const char * TMnemonic::GetName () const inline override
Definition at line 103 of file TMnemonic.h.
References fName.
GetTime()
double TMnemonic::GetTime (Long64_t timestamp, Float_t cfd, double energy, const TChannel * channel) const virtual
Reimplemented in TGRSIMnemonic, THILMnemonic, TILLMnemonic, and TTdrMnemonic.
Definition at line 157 of file TMnemonic.cxx.
References TChannel::GetTimeStampUnit().
Referenced by TChannel::GetTime().
NumericArraySubPosition()
int TMnemonic::NumericArraySubPosition () const virtual
Reimplemented in TGRSIMnemonic.
Definition at line 132 of file TMnemonic.cxx.
References fArraySubPosition, kB, kG, kR, and kW.
Referenced by TChannel::GetCrystalNumber().
operator=() [1/2]
TMnemonic & TMnemonic::operator= (const TMnemonic &) default
operator=() [2/2]
TMnemonic & TMnemonic::operator= (TMnemonic &&) default
OutputSensor()
virtual EMnemonic TMnemonic::OutputSensor () const inline virtual
Definition at line 65 of file TMnemonic.h.
References fOutputSensor.
Referenced by TEmma::AddFragment(), TGriffin::AddFragment(), and TTigress::AddFragment().
OutputSensorString()
virtual std::string TMnemonic::OutputSensorString () const inline virtual
Definition at line 73 of file TMnemonic.h.
References fOutputSensorString.
Parse() [1/2]
void TMnemonic::Parse (const char * name) virtual
Definition at line 91 of file TMnemonic.cxx.
References Parse().
Parse() [2/2]
void TMnemonic::Parse (std::string * name) virtual
Reimplemented in TGRSIMnemonic, THILMnemonic, TILLMnemonic, and TTdrMnemonic.
Definition at line 57 of file TMnemonic.cxx.
References EnumerateMnemonic(), fArrayPosition, fArraySubPosition, fArraySubPositionString, fCollectedCharge, fCollectedChargeString, fOutputSensor, fOutputSensorString, fSegment, fSubSystem, fSubSystemString, fSystemString, SetName(), and SetRFMnemonic().
Referenced by TGRSIMnemonic::TGRSIMnemonic(), THILMnemonic::THILMnemonic(), TILLMnemonic::TILLMnemonic(), TMnemonic(), TTdrMnemonic::TTdrMnemonic(), Parse(), TGRSIMnemonic::Parse(), THILMnemonic::Parse(), TILLMnemonic::Parse(), TTdrMnemonic::Parse(), and TChannel::SetName().
Print() [1/2]
void TMnemonic::Print (Option_t * opt = "") const override
Definition at line 123 of file TMnemonic.cxx.
References Print().
Referenced by TGRSIMnemonic::Print(), and Print().
Print() [2/2]
void TMnemonic::Print (std::ostringstream & str) const
Definition at line 112 of file TMnemonic.cxx.
References fArrayPosition, fArraySubPositionString, fCollectedChargeString, fOutputSensorString, fSegment, fSubSystemString, and fSystemString.
Segment() [1/2]
virtual int16_t TMnemonic::Segment () const inline virtual
Definition at line 67 of file TMnemonic.h.
References fSegment.
Referenced by TChannel::GetSegmentNumber(), and TGRSIMnemonic::Parse().
Segment() [2/2]
virtual void TMnemonic::Segment (int16_t val) inline virtual
Definition at line 86 of file TMnemonic.h.
References fSegment.
SetClassType()
virtual void TMnemonic::SetClassType (TClass * classType) const inline virtual
Definition at line 92 of file TMnemonic.h.
References fClassType.
Referenced by TGRSIMnemonic::GetClassType(), and TChannel::SetClassType().
SetName() [1/2]
void TMnemonic::SetName (const char * val) inline
Definition at line 101 of file TMnemonic.h.
References fName.
Referenced by Parse().
SetName() [2/2]
void TMnemonic::SetName (const std::string & val) inline
Definition at line 102 of file TMnemonic.h.
References fName.
SetRFMnemonic()
void TMnemonic::SetRFMnemonic (std::string * name) virtual
Definition at line 97 of file TMnemonic.cxx.
References EnumerateMnemonic(), fArrayPosition, fArraySubPosition, fArraySubPositionString, fCollectedCharge, fCollectedChargeString, fOutputSensor, fOutputSensorString, fSegment, fSubSystem, fSubSystemString, and fSystemString.
Referenced by Parse(), and TGRSIMnemonic::Parse().
SubSystem()
virtual EMnemonic TMnemonic::SubSystem () const inline virtual
Definition at line 61 of file TMnemonic.h.
References fSubSystem.
Referenced by TEmma::AddFragment(), TGriffin::AddFragment(), TTigress::AddFragment(), TFipps::AddFragment(), TIfin::AddFragment(), TGRSIMnemonic::EnumerateSystem(), TILLMnemonic::EnumerateSystem(), and TTdrMnemonic::EnumerateSystem().
SubSystemString()
virtual std::string TMnemonic::SubSystemString () const inline virtual
Definition at line 70 of file TMnemonic.h.
References fSubSystemString.
Referenced by TTipHit::SetUpNumbering().
SystemString()
virtual std::string TMnemonic::SystemString () const inline virtual
Definition at line 69 of file TMnemonic.h.
References fSystemString.
Referenced by TGRSIMnemonic::EnumerateSystem().
Member Data Documentation
fArrayPosition
int16_t TMnemonic::fArrayPosition private
Definition at line 107 of file TMnemonic.h.
Referenced by ArrayPosition(), Clear(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), and SetRFMnemonic().
fArraySubPosition
EMnemonic TMnemonic::fArraySubPosition private
Definition at line 116 of file TMnemonic.h.
Referenced by ArraySubPosition(), Clear(), NumericArraySubPosition(), Parse(), and SetRFMnemonic().
fArraySubPositionString
std::string TMnemonic::fArraySubPositionString private
Definition at line 111 of file TMnemonic.h.
Referenced by ArraySubPositionString(), Clear(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), and SetRFMnemonic().
fClassType
TClass* TMnemonic::fClassType mutable private
! TGRSIDetector Type that this mnemonic represents
Definition at line 120 of file TMnemonic.h.
Referenced by GetClassType(), THILMnemonic::GetClassType(), TILLMnemonic::GetClassType(), TTdrMnemonic::GetClassType(), and SetClassType().
fCollectedCharge
EMnemonic TMnemonic::fCollectedCharge private
Definition at line 117 of file TMnemonic.h.
Referenced by Clear(), CollectedCharge(), Parse(), and SetRFMnemonic().
fCollectedChargeString
std::string TMnemonic::fCollectedChargeString private
Definition at line 112 of file TMnemonic.h.
Referenced by Clear(), CollectedChargeString(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), and SetRFMnemonic().
fName
std::string TMnemonic::fName private
Definition at line 106 of file TMnemonic.h.
Referenced by GetName(), SetName(), and SetName().
fOutputSensor
EMnemonic TMnemonic::fOutputSensor private
Definition at line 118 of file TMnemonic.h.
Referenced by Clear(), OutputSensor(), Parse(), and SetRFMnemonic().
fOutputSensorString
std::string TMnemonic::fOutputSensorString private
Definition at line 113 of file TMnemonic.h.
Referenced by Clear(), OutputSensorString(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), and SetRFMnemonic().
fPrint
bool TMnemonic::fPrint = true static private
Definition at line 124 of file TMnemonic.h.
Referenced by EnumerateDigitizer().
fSegment
int16_t TMnemonic::fSegment private
Definition at line 108 of file TMnemonic.h.
Referenced by Clear(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), Segment(), Segment(), and SetRFMnemonic().
fSubSystem
EMnemonic TMnemonic::fSubSystem private
Definition at line 115 of file TMnemonic.h.
Referenced by Clear(), Parse(), SetRFMnemonic(), and SubSystem().
fSubSystemString
std::string TMnemonic::fSubSystemString private
Definition at line 110 of file TMnemonic.h.
Referenced by Clear(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), SetRFMnemonic(), and SubSystemString().
fSystemString
std::string TMnemonic::fSystemString private
Definition at line 109 of file TMnemonic.h.
Referenced by Clear(), THILMnemonic::EnumerateSystem(), TILLMnemonic::EnumerateSystem(), TTdrMnemonic::EnumerateSystem(), Parse(), THILMnemonic::Print(), TILLMnemonic::Print(), TTdrMnemonic::Print(), Print(), SetRFMnemonic(), and SystemString().