GRSISort: TTransientBits< T > Class Template Reference
TTransientBits< T > Class Template Reference
Sorting
Detailed Description
template<typename T>
class TTransientBits< T >
Class for storing bits for transient data members
Definition at line 26 of file TTransientBits.h.
Public Member Functions
TTransientBits ()
TTransientBits (const T &tmp)
TTransientBits (const TTransientBits &)=default
TTransientBits (TTransientBits &&) noexcept=default
~TTransientBits ()=default
void Clear ()
void ClearBit (T bit)
template<typename U >
void ClearBit (U bit)
TTransientBits & operator= (const T &rhs)
TTransientBits & operator= (const TTransientBits &)=default
TTransientBits & operator= (TTransientBits &&) noexcept=default
void Print () const
void SetBit (T bit)
void SetBit (T bit, Bool_t flag)
template<typename U >
void SetBit (U bit)
template<typename U >
void SetBit (U bit, Bool_t flag)
Bool_t TestBit (T bit) const
template<typename U >
Bool_t TestBit (U bit) const
T TestBits (T bit) const
template<typename U >
T TestBits (U bit) const
T Value () const
Public Attributes
T fBits
Constructor & Destructor Documentation
TTransientBits() [1/4]
template<typename T > TTransientBits< T >::TTransientBits () inline
Definition at line 28 of file TTransientBits.h.
TTransientBits() [2/4]
template<typename T > TTransientBits< T >::TTransientBits (const T & tmp) inline explicit
Definition at line 29 of file TTransientBits.h.
~TTransientBits()
template<typename T > TTransientBits< T >::~TTransientBits () default
TTransientBits() [3/4]
template<typename T > TTransientBits< T >::TTransientBits (const TTransientBits< T > &) default
TTransientBits() [4/4]
template<typename T > TTransientBits< T >::TTransientBits (TTransientBits< T > &&) default noexcept
Member Function Documentation
Clear()
template<typename T > void TTransientBits< T >::Clear () inline
Definition at line 61 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Referenced by TSiLi::Clear(), and TSiLiHit::Clear().
ClearBit() [1/2]
template<typename T > void TTransientBits< T >::ClearBit (T bit) inline
Definition at line 40 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Referenced by TTransientBits< T >::SetBit(), and TTransientBits< T >::SetBit().
ClearBit() [2/2]
template<typename T > template<typename U > void TTransientBits< T >::ClearBit (U bit) inline
Definition at line 48 of file TTransientBits.h.
References TTransientBits< T >::fBits.
operator=() [1/3]
template<typename T > TTransientBits & TTransientBits< T >::operator= (const T & rhs) inline
Definition at line 54 of file TTransientBits.h.
References TTransientBits< T >::fBits.
operator=() [2/3]
template<typename T > TTransientBits & TTransientBits< T >::operator= (const TTransientBits< T > &) default
operator=() [3/3]
template<typename T > TTransientBits & TTransientBits< T >::operator= (TTransientBits< T > &&) default noexcept
Print()
template<typename T > void TTransientBits< T >::Print () const inline
Definition at line 62 of file TTransientBits.h.
References TTransientBits< T >::fBits.
SetBit() [1/4]
template<typename T > void TTransientBits< T >::SetBit (T bit) inline
Definition at line 39 of file TTransientBits.h.
References TTransientBits< T >::fBits.
SetBit() [2/4]
template<typename T > void TTransientBits< T >::SetBit (T bit, Bool_t flag) inline
Definition at line 38 of file TTransientBits.h.
References TTransientBits< T >::ClearBit(), and TTransientBits< T >::SetBit().
Referenced by TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TTrific::GetPosition(), TTrific::GetRange(), TSiLi::ResetAddback(), TTigress::ResetAddback(), TTransientBits< T >::SetBit(), TFipps::SetBitNumber(), TFippsLaBr::SetBitNumber(), TGriffin::SetBitNumber(), TIfin::SetBitNumber(), TLaBr::SetBitNumber(), TRcmp::SetBitNumber(), TS3::SetBitNumber(), TTdrClover::SetBitNumber(), TTdrTigress::SetBitNumber(), TS3::SetGlobalBit(), TTigress::SetGlobalBit(), TGriffinHit::SetGriffinFlag(), TDetectorHit::SetHitBit(), TTdrCloverHit::SetTdrCloverFlag(), TTdrTigressHit::SetTdrTigressFlag(), and TSiLiHit::UseFitCharge().
SetBit() [3/4]
template<typename T > template<typename U > void TTransientBits< T >::SetBit (U bit) inline
Definition at line 46 of file TTransientBits.h.
References TTransientBits< T >::fBits.
SetBit() [4/4]
template<typename T > template<typename U > void TTransientBits< T >::SetBit (U bit, Bool_t flag) inline
Definition at line 44 of file TTransientBits.h.
References TTransientBits< T >::ClearBit(), and TTransientBits< T >::SetBit().
Referenced by TTransientBits< T >::SetBit().
TestBit() [1/2]
template<typename T > Bool_t TTransientBits< T >::TestBit (T bit) const inline
Definition at line 41 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Referenced by TS3::BuildPixels(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TRcmp::GetBackMultiplicity(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TRcmp::GetFrontMultiplicity(), TRcmp::GetPixelMultiplicity(), TTrific::GetPosition(), TTrific::GetRange(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TFipps::TestBitNumber(), TFippsLaBr::TestBitNumber(), TGriffin::TestBitNumber(), TIfin::TestBitNumber(), TLaBr::TestBitNumber(), TRcmp::TestBitNumber(), TS3::TestBitNumber(), TTdrClover::TestBitNumber(), TTdrTigress::TestBitNumber(), TS3::TestGlobalBit(), TTigress::TestGlobalBit(), and TDetectorHit::TestHitBit().
TestBit() [2/2]
template<typename T > template<typename U > Bool_t TTransientBits< T >::TestBit (U bit) const inline
Definition at line 50 of file TTransientBits.h.
References TTransientBits< T >::fBits.
TestBits() [1/2]
template<typename T > T TTransientBits< T >::TestBits (T bit) const inline
Definition at line 42 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Referenced by TGriffinHit::NPileUps(), TTdrCloverHit::NPileUps(), TTdrTigressHit::NPileUps(), TGriffinHit::PUHit(), TTdrCloverHit::PUHit(), and TTdrTigressHit::PUHit().
TestBits() [2/2]
template<typename T > template<typename U > T TTransientBits< T >::TestBits (U bit) const inline
Definition at line 52 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Value()
template<typename T > T TTransientBits< T >::Value () const inline
Definition at line 59 of file TTransientBits.h.
References TTransientBits< T >::fBits.
Member Data Documentation
fBits
template<typename T > T TTransientBits< T >::fBits
Definition at line 64 of file TTransientBits.h.
Referenced by TTransientBits< T >::Clear(), TTransientBits< T >::ClearBit(), TTransientBits< T >::ClearBit(), TTransientBits< T >::operator=(), TTransientBits< T >::Print(), TTransientBits< T >::SetBit(), TTransientBits< T >::SetBit(), TTransientBits< T >::TestBit(), TTransientBits< T >::TestBit(), TTransientBits< T >::TestBits(), TTransientBits< T >::TestBits(), and TTransientBits< T >::Value().