GRSISort: TDescant Class Reference
TDescant Class Reference
Detectors
Detailed Description
The TDescant class defines the observables and algorithms used when analyzing GRIFFIN data. It includes detector positions, etc.
Definition at line 27 of file TDescant.h.
Public Member Functions
TDescant ()
TDescant (const TDescant &)
TDescant (TDescant &&) noexcept=default
~TDescant () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TDescantHit * GetDescantHit (const Int_t &i=0) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
bool Hit () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TDescant & operator= (const TDescant &)
TDescant & operator= (TDescant &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void SetHit (bool flag=true)
void SetWave (bool flag)
Static Public Member Functions
static TVector3 GetPosition (int DetNbr, double dist=222)
static bool SetWave ()
Private Attributes
bool fHitFlag
std::vector< TDetectorHit * > fHits
Static Private Attributes
static std::array< TVector3, 9 > fAncillaryPosition
static bool fSetWave = false
static std::array< TVector3, 71 > fSpherePosition
static std::array< TVector3, 60 > fWallPosition
Constructor & Destructor Documentation
TDescant() [1/3]
TDescant::TDescant ()
Default Constructor
Definition at line 97 of file TDescant.cxx.
References Clear().
TDescant() [2/3]
TDescant::TDescant (const TDescant & rhs)
Definition at line 108 of file TDescant.cxx.
References Copy().
TDescant() [3/3]
TDescant::TDescant (TDescant &&) default noexcept
~TDescant()
TDescant::~TDescant () override default
Member Function Documentation
AddFragment()
void TDescant::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Builds the DESCANT Hits directly from the TFragment. Basically, loops through the data for an event and sets observables. This is done for both DESCANT and it's suppressors.
Reimplemented from TDetector.
Definition at line 139 of file TDescant.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TDescant::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 43 of file TDescant.h.
Clear()
void TDescant::Clear (Option_t * opt = "") override
!
Clears all of the hits
Definition at line 113 of file TDescant.cxx.
References TDetector::Clear(), and fHitFlag.
Referenced by TDescant().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDescant::Copy (TObject & rhs) const override
!
Definition at line 103 of file TDescant.cxx.
References TDetector::Copy().
Referenced by TDescant(), and operator=().
GetDescantHit()
TDescantHit * TDescant::GetDescantHit (const Int_t & i = 0) const inline
Definition at line 36 of file TDescant.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
TVector3 TDescant::GetPosition (int DetNbr, double dist = 222) static
!
Definition at line 152 of file TDescant.cxx.
References fAncillaryPosition, fSpherePosition, fWallPosition, and TRunInfo::GetDetectorInformation().
Referenced by TDescantHit::GetPosition(), and TDescantHit::GetPosition().
Hit()
bool TDescant::Hit () const inline
!
Definition at line 47 of file TDescant.h.
References fHitFlag.
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TDescant & TDescant::operator= (const TDescant & rhs)
Definition at line 120 of file TDescant.cxx.
References Copy().
operator=() [2/2]
TDescant & TDescant::operator= (TDescant &&) default noexcept
Print() [1/2]
void TDescant::Print (Option_t * opt = "") const override
!
Prints out TDescant members, currently does little.
Definition at line 126 of file TDescant.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TDescant::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 132 of file TDescant.cxx.
References TDetector::GetMultiplicity().
SetHit()
void TDescant::SetHit (bool flag = true) inline
!
Definition at line 48 of file TDescant.h.
References fHitFlag.
SetWave() [1/2]
static bool TDescant::SetWave () inline static
!
Definition at line 45 of file TDescant.h.
References fSetWave.
SetWave() [2/2]
void TDescant::SetWave (bool flag) inline
!
Definition at line 46 of file TDescant.h.
References fSetWave.
Member Data Documentation
fAncillaryPosition
std::array< TVector3, 9 > TDescant::fAncillaryPosition static private
!
Definition at line 41 of file TDescant.h.
Referenced by GetPosition().
fHitFlag
bool TDescant::fHitFlag private
Is there a Descant hit?
Definition at line 57 of file TDescant.h.
Referenced by Clear(), Hit(), and SetHit().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fSetWave
bool TDescant::fSetWave = false static private
Flag for Waveforms ON/OFF.
Definition at line 56 of file TDescant.h.
Referenced by SetWave(), and SetWave().
fSpherePosition
std::array< TVector3, 71 > TDescant::fSpherePosition static private
Initial value:
= {
   TVector3(0.0, 0.0, 1.0), TVector3(98.6, 0.0, 490.2), TVector3(30.5, 93.8, 490.2),
   TVector3(-79.8, 57.9, 490.2), TVector3(-79.8, -57.9, 490.2), TVector3(30.5, -93.8, 490.2),
   TVector3(208.7, 0.0, 454.4), TVector3(140.9, 102.4, 468.7), TVector3(64.5, 198.5, 454.4),
   TVector3(-53.8, 165.6, 468.7), TVector3(-168.8, 122.7, 454.4), TVector3(-174.2, 0.0, 468.7),
   TVector3(-168.8, -122.7, 454.4), TVector3(-53.8, -165.6, 468.7), TVector3(64.5, -198.5, 454.4),
   TVector3(140.9, -102.4, 468.7), TVector3(313.1, 0.0, 389.9), TVector3(256.9, 105.8, 415.7),
   TVector3(180.0, 211.6, 415.7), TVector3(96.7, 297.7, 389.9), TVector3(-21.2, 277.0, 415.7),
   TVector3(-145.6, 236.6, 415.7), TVector3(-253.3, 184.0, 389.9), TVector3(-270.0, 65.4, 415.7),
   TVector3(-270.0, -65.4, 415.7), TVector3(-253.3, -184.0, 389.9), TVector3(-145.6, -236.6, 415.7),
   TVector3(-21.2, -277.0, 415.7), TVector3(96.7, -297.7, 389.9), TVector3(180.0, -211.6, 415.7),
   TVector3(256.9, -105.8, 415.7), TVector3(394.3, 0.0, 307.4), TVector3(356.2, 102.4, 335.6),
   TVector3(291.3, 211.6, 346.9), TVector3(207.4, 307.1, 335.6), TVector3(121.9, 375.0, 307.4),
   TVector3(12.7, 370.4, 335.6), TVector3(-111.3, 342.4, 346.9), TVector3(-228.0, 292.2, 335.6),
   TVector3(-319.0, 231.8, 307.4), TVector3(-348.3, 126.5, 335.6), TVector3(-360.1, 0.0, 346.9),
   TVector3(-348.3, -126.5, 335.6), TVector3(-319.0, -231.8, 307.4), TVector3(-228.0, -292.2, 335.6),
   TVector3(-111.3, -342.4, 346.9), TVector3(12.7, -370.4, 335.6), TVector3(121.9, -375.0, 307.4),
   TVector3(207.4, -307.1, 335.6), TVector3(291.3, -211.6, 346.9), TVector3(356.2, -102.4, 335.6),
   TVector3(424.8, 93.8, 246.5), TVector3(377.5, 198.5, 260.9), TVector3(305.4, 297.7, 260.9),
   TVector3(220.4, 375.0, 246.5), TVector3(42.1, 433.0, 246.5), TVector3(-72.1, 420.4, 260.9),
   TVector3(-188.8, 382.5, 260.9), TVector3(-288.6, 325.6, 246.5), TVector3(-398.8, 173.8, 246.5),
   TVector3(-422.1, 61.3, 260.9), TVector3(-422.1, -61.3, 260.9), TVector3(-398.8, -173.8, 246.5),
   TVector3(-288.6, -325.6, 246.5), TVector3(-188.8, -382.5, 260.9), TVector3(-72.1, -420.4, 260.9),
   TVector3(42.1, -433.0, 246.5), TVector3(220.4, -375.0, 246.5), TVector3(305.4, -297.7, 260.9),
   TVector3(377.5, -198.5, 260.9), TVector3(424.8, -93.8, 246.5)}
!
Definition at line 14 of file TDescant.h.
Referenced by GetPosition().
fWallPosition
std::array< TVector3, 60 > TDescant::fWallPosition static private
Initial value:
= {
   TVector3(195.966, 0.000, 1596.010), TVector3(-195.966, 0.000, 1596.010), TVector3(195.966, 492.837, 1596.010),
   TVector3(-195.966, 492.837, 1596.010), TVector3(-195.966, -492.837, 1596.010), TVector3(195.966, -492.837, 1596.010),
   TVector3(576.256, 0.000, 1501.200), TVector3(-576.256, 0.000, 1501.200), TVector3(576.256, 492.837, 1501.200),
   TVector3(-576.256, 492.837, 1501.200), TVector3(-576.256, -492.837, 1501.200), TVector3(576.256, -492.837, 1501.200),
   TVector3(208.851, 1050.481, 1700.946), TVector3(-208.851, 1050.481, 1700.946), TVector3(-208.851, -1050.481, 1700.946),
   TVector3(208.851, -1050.481, 1700.946), TVector3(922.311, 0.000, 1317.200), TVector3(-922.311, 0.000, 1317.200),
   TVector3(614.142, 1050.478, 1599.897), TVector3(-614.142, 1050.478, 1599.897), TVector3(-614.142, -1050.478, 1599.897),
   TVector3(614.142, -1050.478, 1599.897), TVector3(922.311, 492.837, 1317.200), TVector3(-922.311, 492.837, 1317.200),
   TVector3(-922.311, -492.837, 1317.200), TVector3(922.311, -492.837, 1317.200), TVector3(982.949, 1050.478, 1403.800),
   TVector3(-982.949, 1050.478, 1403.800), TVector3(-982.949, -1050.478, 1403.800), TVector3(982.949, -1050.478, 1403.800),
   TVector3(1213.570, 0.000, 1054.940), TVector3(-1213.570, 0.000, 1054.940), TVector3(1213.570, 492.837, 1054.940),
   TVector3(-1213.570, 492.837, 1054.940), TVector3(-1213.570, -492.837, 1054.940), TVector3(1213.570, -492.837, 1054.940),
   TVector3(1293.361, 1050.481, 1124.301), TVector3(-1293.361, 1050.481, 1124.301), TVector3(-1293.361, -1050.481, 1124.301),
   TVector3(1293.361, -1050.481, 1124.301), TVector3(1293.361, 1050.481, -1124.301), TVector3(-1293.361, 1050.481, -1124.301),
   TVector3(-1293.361, -1050.481, -1124.301), TVector3(1293.361, -1050.481, -1124.301), TVector3(1213.570, 492.837, -1054.940),
   TVector3(-1213.570, 492.837, -1054.940), TVector3(-1213.570, -492.837, -1054.940), TVector3(1213.570, -492.837, -1054.940),
   TVector3(1213.570, 0.000, -1054.940), TVector3(-1213.570, 0.000, -1054.940), TVector3(982.949, 1050.478, -1403.800),
   TVector3(-982.949, 1050.478, -1403.800), TVector3(-982.949, -1050.478, -1403.800), TVector3(982.949, -1050.478, -1403.800),
   TVector3(922.311, 492.837, -1317.200), TVector3(-922.311, 492.837, -1317.200), TVector3(-922.311, -492.837, -1317.200),
   TVector3(922.311, -492.837, -1317.200), TVector3(922.311, 0.000, -1317.200), TVector3(-922.311, 0.000, -1317.200)}
!
Definition at line 74 of file TDescant.h.
Referenced by GetPosition().