GRSISort: TTrific Class Reference
TTrific Class Reference
Detectors
Detailed Description
The TTrific class defines the observables and algorithms used when analyzing TIGRESS data.
Definition at line 29 of file TTrific.h.
Public Types
enum class ETrificBits {
kPositionCalculated = BIT(0) , kRangeCalculated = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kBit4 = BIT(4) , kBit5 = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7)
}
Public Member Functions
TTrific ()
TTrific (const TTrific &)
TTrific (TTrific &&) noexcept=default
~TTrific () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *chan) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
void ClearTransients () override
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TVector3 GetPosition ()
TVector3 GetPosition (Int_t detectorNumber)
Int_t GetRange ()
virtual Short_t GetSingMultiplicity () const
TTrificHit * GetTrificHit (const int &i) const
TTrificHit * GetTrificSingHit (const int &i) const
TTrificHit * GetTrificXHit (const int &i) const
TTrificHit * GetTrificYHit (const int &i) const
virtual Short_t GetXMultiplicity () const
void GetXYGrid ()
virtual Short_t GetYMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TTrific & operator= (const TTrific &)
TTrific & operator= (TTrific &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static bool SetCoreWave ()
static void SetCustomTargetChamber (Double_t distance)
static void SetSharc (Double_t distance=650.57)
static void SetTip (Double_t distance=600.)
Static Public Attributes
static const double fInitialSpacingCart = 28.0
static const double fSpacingCart = 13.0
static double fTargetToWindowCart = 700.0
Private Attributes
std::vector< TDetectorHit * > fHits
TVector3 fParticle = TVector3(0, 0, 0)
Int_t fRange = 0
std::vector< TTrificHit * > fSingFragments
TTransientBits< UShort_t > fTrificBits
std::vector< TTrificHit * > fXFragments
std::vector< TTrificHit * > fYFragments
Static Private Attributes
static const double fAngle = (60. / 180.) * TMath::Pi()
static Int_t fGridX = 0
static Int_t fGridY = 0
static const TVector3 fNormalGridVec = TVector3(0, -TMath::Cos(fAngle), TMath::Sin(fAngle))
static bool fSetCoreWave = false
static const std::array< double, 12 > fXmm = {-33, -27, -21, -15, -9, -3, 3, 9, 15, 21, 27, 33}
static const std::array< double, 12 > fYmm = {42, 36, 28, 20, 12, 4, -4, -12, -20, -28, -36, -42}
Member Enumeration Documentation
ETrificBits
enum class TTrific::ETrificBits strong
Enumerator
kPositionCalculated
kRangeCalculated
kBit2
kBit3
kBit4
kBit5
kBit6
kBit7
Definition at line 31 of file TTrific.h.
Constructor & Destructor Documentation
TTrific() [1/3]
TTrific::TTrific ()
Definition at line 32 of file TTrific.cxx.
References Clear().
TTrific() [2/3]
TTrific::TTrific (const TTrific & rhs)
Definition at line 37 of file TTrific.cxx.
References Copy().
TTrific() [3/3]
TTrific::TTrific (TTrific &&) default noexcept
~TTrific()
TTrific::~TTrific () override default
Member Function Documentation
AddFragment()
void TTrific::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 75 of file TTrific.cxx.
References TDetector::AddHit(), TMnemonic::ArraySubPosition(), fSingFragments, fXFragments, fYFragments, TChannel::GetMnemonic(), TMnemonic::kX, and TMnemonic::kY.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TTrific::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 57 of file TTrific.h.
Clear()
void TTrific::Clear (Option_t * option = "") override
!
Definition at line 96 of file TTrific.cxx.
References TDetector::Clear(), fSingFragments, fTrificBits, fXFragments, and fYFragments.
Referenced by TTrific().
ClearTransients()
void TTrific::ClearTransients () inline override virtual
!
Reimplemented from TDetector.
Definition at line 59 of file TTrific.h.
References TDetector::ClearTransients(), fParticle, fRange, and fTrificBits.
Copy()
void TTrific::Copy (TObject & rhs) const override
!
Definition at line 42 of file TTrific.cxx.
References TDetector::Copy(), fSingFragments, fTrificBits, fXFragments, and fYFragments.
Referenced by TTrific(), and operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), Print(), and TZeroDegree::Print().
GetPosition() [1/2]
TVector3 TTrific::GetPosition ()
!
Definition at line 158 of file TTrific.cxx.
References fAngle, fGridX, fGridY, fInitialSpacingCart, fParticle, fSpacingCart, fTargetToWindowCart, fTrificBits, fXFragments, fXmm, fYFragments, fYmm, GetXYGrid(), kPositionCalculated, TTransientBits< T >::SetBit(), and TTransientBits< T >::TestBit().
Referenced by GetPosition().
GetPosition() [2/2]
TVector3 TTrific::GetPosition (Int_t detectorNumber)
!
Definition at line 130 of file TTrific.cxx.
References fInitialSpacingCart, fSpacingCart, fTargetToWindowCart, and GetPosition().
GetRange()
Int_t TTrific::GetRange ()
!
Definition at line 287 of file TTrific.cxx.
References fGridX, fGridY, fRange, fSingFragments, fTrificBits, fXFragments, fYFragments, GetXYGrid(), kRangeCalculated, TTransientBits< T >::SetBit(), and TTransientBits< T >::TestBit().
GetSingMultiplicity()
virtual Short_t TTrific::GetSingMultiplicity () const inline virtual
Definition at line 69 of file TTrific.h.
References fSingFragments.
GetTrificHit()
TTrificHit * TTrific::GetTrificHit (const int & i) const inline
Definition at line 49 of file TTrific.h.
References TDetector::GetHit().
GetTrificSingHit()
TTrificHit * TTrific::GetTrificSingHit (const int & i) const inline
Definition at line 52 of file TTrific.h.
References fSingFragments.
GetTrificXHit()
TTrificHit * TTrific::GetTrificXHit (const int & i) const inline
Definition at line 50 of file TTrific.h.
References fXFragments.
GetTrificYHit()
TTrificHit * TTrific::GetTrificYHit (const int & i) const inline
Definition at line 51 of file TTrific.h.
References fYFragments.
GetXMultiplicity()
virtual Short_t TTrific::GetXMultiplicity () const inline virtual
Definition at line 67 of file TTrific.h.
References fXFragments.
GetXYGrid()
void TTrific::GetXYGrid ()
!
Definition at line 112 of file TTrific.cxx.
References fGridX, fGridY, fXFragments, fYFragments, and TDetectorHit::GetDetector().
Referenced by GetPosition(), and GetRange().
GetYMultiplicity()
virtual Short_t TTrific::GetYMultiplicity () const inline virtual
Definition at line 68 of file TTrific.h.
References fYFragments.
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), TSharc2::GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TTrific & TTrific::operator= (const TTrific & rhs)
!
Definition at line 69 of file TTrific.cxx.
References Copy().
operator=() [2/2]
TTrific & TTrific::operator= (TTrific &&) default noexcept
Print() [1/2]
void TTrific::Print (Option_t * opt = "") const override
!
Definition at line 53 of file TTrific.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TTrific::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 59 of file TTrific.cxx.
References fSingFragments, fXFragments, fYFragments, and TDetector::GetMultiplicity().
SetCoreWave()
static bool TTrific::SetCoreWave () inline static
!
Definition at line 86 of file TTrific.h.
References fSetCoreWave.
SetCustomTargetChamber()
static void TTrific::SetCustomTargetChamber (Double_t distance) inline static
Definition at line 74 of file TTrific.h.
References fTargetToWindowCart.
SetSharc()
static void TTrific::SetSharc (Double_t distance = 650.57) inline static
Definition at line 72 of file TTrific.h.
References fTargetToWindowCart.
SetTip()
static void TTrific::SetTip (Double_t distance = 600.) inline static
Definition at line 73 of file TTrific.h.
References fTargetToWindowCart.
Member Data Documentation
fAngle
const double TTrific::fAngle = (60. / 180.) * TMath::Pi() static private
Definition at line 117 of file TTrific.h.
Referenced by GetPosition().
fGridX
Int_t TTrific::fGridX = 0 static private
Definition at line 115 of file TTrific.h.
Referenced by GetPosition(), GetRange(), and GetXYGrid().
fGridY
Int_t TTrific::fGridY = 0 static private
Definition at line 116 of file TTrific.h.
Referenced by GetPosition(), GetRange(), and GetXYGrid().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fInitialSpacingCart
const double TTrific::fInitialSpacingCart = 28.0 static
Definition at line 94 of file TTrific.h.
Referenced by GetPosition(), GetPosition(), and TTrificHit::GetPosition().
fNormalGridVec
const TVector3 TTrific::fNormalGridVec = TVector3(0, -TMath::Cos(fAngle), TMath::Sin(fAngle)) static private
Definition at line 118 of file TTrific.h.
fParticle
TVector3 TTrific::fParticle = TVector3(0, 0, 0) private
!
Definition at line 106 of file TTrific.h.
Referenced by ClearTransients(), and GetPosition().
fRange
Int_t TTrific::fRange = 0 private
!
Definition at line 108 of file TTrific.h.
Referenced by ClearTransients(), and GetRange().
fSetCoreWave
bool TTrific::fSetCoreWave = false static private
! Flag for Waveforms ON/OFF
Definition at line 98 of file TTrific.h.
Referenced by SetCoreWave().
fSingFragments
std::vector<TTrificHit*> TTrific::fSingFragments private
Definition at line 102 of file TTrific.h.
Referenced by AddFragment(), Clear(), Copy(), GetRange(), GetSingMultiplicity(), GetTrificSingHit(), and Print().
fSpacingCart
const double TTrific::fSpacingCart = 13.0 static
Definition at line 93 of file TTrific.h.
Referenced by GetPosition(), GetPosition(), and TTrificHit::GetPosition().
fTargetToWindowCart
double TTrific::fTargetToWindowCart = 700.0 static
Definition at line 95 of file TTrific.h.
Referenced by GetPosition(), GetPosition(), TTrificHit::GetPosition(), SetCustomTargetChamber(), SetSharc(), and SetTip().
fTrificBits
TTransientBits<UShort_t> TTrific::fTrificBits private
Definition at line 104 of file TTrific.h.
Referenced by Clear(), ClearTransients(), Copy(), GetPosition(), and GetRange().
fXFragments
std::vector<TTrificHit*> TTrific::fXFragments private
Definition at line 100 of file TTrific.h.
Referenced by AddFragment(), Clear(), Copy(), GetPosition(), GetRange(), GetTrificXHit(), GetXMultiplicity(), GetXYGrid(), and Print().
fXmm
const std::array< double, 12 > TTrific::fXmm = {-33, -27, -21, -15, -9, -3, 3, 9, 15, 21, 27, 33} static private
Definition at line 13 of file TTrific.h.
Referenced by GetPosition().
fYFragments
std::vector<TTrificHit*> TTrific::fYFragments private
Definition at line 101 of file TTrific.h.
Referenced by AddFragment(), Clear(), Copy(), GetPosition(), GetRange(), GetTrificYHit(), GetXYGrid(), GetYMultiplicity(), and Print().
fYmm
const std::array< double, 12 > TTrific::fYmm = {42, 36, 28, 20, 12, 4, -4, -12, -20, -28, -36, -42} static private
Definition at line 14 of file TTrific.h.
Referenced by GetPosition().