GRSISort: TRunInfo Class Reference
TRunInfo Class Reference
Sorting
Detailed Description
This Class is designed to store run dependent information. It is used to store run numbers, GRSISort version, existence of detector systems, etc. The TRunInfo is written to both the fragment and analysis trees, as well as to files create by grsiframe.
An example run info looks like this:
GRSI [0] TRunInfo::Get()->Print()
Singleton 0x5651a3d5dc10 was read from analysis22151_000.root
Title: All-singles-ZDF-off 133Ba_R0794
Comment: All-singles-ZDF-off 133Ba_R0794
      RunNumber:          22151
      SubRunNumber:       000
      RunStart:           Fri Dec 22 18:11:29 2023
      RunStop:            Fri Dec 22 18:42:40 2023
      RunLength:          1871 s
GRSI [1]
When subruns/runs are added together using gadd or when multiple subruns/runs are used in grsiframe, their TRunInfos get merged.
If all files are from one run, and the subruns are added in order without any missing, the information changes to reflect this:
GRSI [0] TRunInfo::Get()->Print()
Singleton 0x55ab20f209a0 was read from Final21950_000-028.root
Title: 100Zr_beam_with_PACES_lasers_on
Comment: 100Zr_beam_with_PACES_lasers_on
      RunNumber:          21950
      SubRunNumbers:      000-028
      RunStart:           Thu Dec 14 13:37:14 2023
      RunStop:            Thu Dec 14 14:37:14 2023
      RunLength:          3599 s
GRSI [1]
Internally this is signaled by the subrun number having been set to -1, while the run number is still nonzero, and the run start and run stop are set as well as the numbers of the first and last subrun.
If the subruns are not in order or a subrun is missing from the range added, the number of the first and last subrun are both set to -1, changing the line
SubRunNumbers:      000-028
to
SubRunNumbers:      -1--1
If the files are from multiple runs that are all in consecutive order without any missing ones, the run info will say:
Singleton 0x563c6c1c3a30 was read from Final21950-21980.root
Title: 100Zr_beam_with_PACES_lasers_on
Comment: 100Zr_beam_with_PACES_lasers_on
      RunNumbers:         21950-21980
      No missing runs
      RunStart:           Thu Dec 14 13:37:14 2023
      RunStop:            Fri Dec 15 19:06:11 2023
      RunLength:          101306 s
If however some runs in between are missing, it will say
Singleton 0x55919586a8c0 was read from test50_51_54.root
Title: 100Zr_beam_with_PACES_lasers_on
Comment: 100Zr_beam_with_PACES_lasers_on
      RunNumbers:         21950-21954
      Missing runs:       21952, 21953
      Combined RunLength: 10794 s
From version 18 on TRunInfo also stores information about the GRSISort version used to sort the data. This can be accessed via
TRunInfo::Get()->PrintVersion();
Using a newer version of grsiframe on data created with an older version of GRSISort should not overwrite the version reported.
Summary of different states the run info can be in:
state identifying markers
single sub run non-zero run number and sub run number != -1
consecutive sub runs of a single run (from FirstSubRunNumber() to LastSubRunNumber()) non-zero run number and sub run number == -1
consecutive runs (from FirstRunNumber() to LastRunNumber()) zero run number and FirstRunNumber() != LastRunNumber()
non-consecutive runs zero run number and non-empty run list
Definition at line 128 of file TRunInfo.h.
Public Member Functions
TRunInfo ()
TRunInfo (const TRunInfo &)=default
TRunInfo (TRunInfo &&) noexcept=default
~TRunInfo ()=default
void Add (TRunInfo *runinfo, bool verbose=false)
virtual TEventBuildingLoop::EBuildMode BuildMode () const
void Clear (Option_t *opt="") override
std::string ListOfMissingRuns (bool all=false) const
Long64_t Merge (TCollection *list)
TRunInfo & operator= (const TRunInfo &)=default
TRunInfo & operator= (TRunInfo &&) noexcept=default
void Print (Option_t *opt="") const override
void PrintRunList () const
void PrintVersion () const
Static Public Member Functions
static void AddBadCycle (int bad_cycle)
static TRunInfo * AddCurrent ()
static void ClearDate ()
static void ClearFullVersion ()
static void ClearLibraryPath ()
static void ClearLibraryVersion ()
static void ClearVersion ()
static std::string CreateLabel (bool quiet=false)
static int FirstRunNumber ()
static int FirstSubRunNumber ()
static TRunInfo * Get (bool verbose=false)
static TRunInfo * GetAll ()
static const char * GetCalFileData ()
static const char * GetCalFileName ()
static std::string GetDate ()
static TDetectorInformation * GetDetectorInformation ()
static std::string GetFullVersion ()
static std::string GetLibraryPath ()
static std::string GetLibraryVersion ()
static const char * GetRunInfoFileData ()
static const char * GetRunInfoFileName ()
static std::string GetVersion ()
static const char * GetXMLODBFileData ()
static const char * GetXMLODBFileName ()
static double HPGeArrayPosition ()
static bool IsBadCycle (int cycle)
static int LastRunNumber ()
static int LastSubRunNumber ()
static Bool_t ParseInputData (const char *inputdata="", Option_t *opt="q")
static void PrintBadCycles ()
static void PrintDirectory ()
static std::string PrintToString (Option_t *opt="")
static Bool_t ReadInfoFile (const char *filename="")
static Bool_t ReadInfoFromFile (TFile *tempf=nullptr)
static void RemoveBadCycle (int cycle)
static std::string RunComment ()
static double RunLength ()
static int RunNumber ()
static double RunStart ()
static double RunStop ()
static std::string RunTitle ()
static void Set (TRunInfo *val)
static void SetAnalysisTreeBranches (TTree *)
static void SetCalFileData (const char *data)
static void SetCalFileName (const char *name)
static void SetDate (const char *ver)
static void SetDate (std::string ver)
static void SetDetectorInformation (TDetectorInformation *inf)
static void SetFullVersion (const char *ver)
static void SetFullVersion (std::string ver)
static void SetHPGeArrayPosition (const double arr_pos)
static void SetLibraryPath (const char *ver)
static void SetLibraryPath (std::string ver)
static void SetLibraryVersion (const char *ver)
static void SetLibraryVersion (std::string ver)
static void SetRunComment (const char *run_comment)
static void SetRunInfo (int runnum=0, int subrunnum=-1)
static void SetRunInfoFile (const char *ffile)
static void SetRunInfoFileName (const char *fname)
static void SetRunLength ()
static void SetRunLength (double tmp)
static void SetRunNumber (int tmp)
static void SetRunStart (double tmp)
static void SetRunStop (double tmp)
static void SetRunTitle (const char *run_title)
static void SetSubRunNumber (int tmp)
static void SetVersion (const char *ver)
static void SetVersion (std::string ver)
static void SetXMLODBFileData (const char *data)
static void SetXMLODBFileName (const char *name)
static int SubRunNumber ()
static bool WriteInfoFile (const std::string &filename)
static bool WriteToRoot (TFile *fileptr=nullptr)
Private Attributes
std::vector< int > fBadCycleList
std::string fCalFile
std::string fCalFileName
std::string fDate
TDetectorInformation * fDetectorInformation {nullptr}
int fFirstRunNumber {0}
int fFirstSubRunNumber {-1}
std::string fFullVersion
double fHPGeArrayPosition {110.}
int fLastRunNumber {0}
int fLastSubRunNumber {-1}
std::string fLibraryPath
std::string fLibraryVersion
std::string fRunComment
std::string fRunInfoFile
std::string fRunInfoFileName
double fRunLength {0.}
std::set< std::pair< int, int > > fRunList
int fRunNumber {0}
double fRunStart {0.}
double fRunStop {0.}
std::string fRunTitle
int fSubRunNumber {-1}
std::string fVersion
std::string fXMLODBFile
std::string fXMLODBFileName
Static Private Attributes
static TDirectory * fDir
static TRunInfo * fSingleton
Friends
class TSingleton< TRunInfo >
Constructor & Destructor Documentation
TRunInfo() [1/3]
TRunInfo::TRunInfo (const TRunInfo &) default
TRunInfo() [2/3]
TRunInfo::TRunInfo (TRunInfo &&) default noexcept
~TRunInfo()
TRunInfo::~TRunInfo () default
TRunInfo() [3/3]
TRunInfo::TRunInfo ()
Default ctor for TRunInfo. The default values are:
fHPGeArrayPosition = 110.0;
Definition at line 63 of file TRunInfo.cxx.
References Clear().
Member Function Documentation
Add()
void TRunInfo::Add (TRunInfo * runinfo, bool verbose = false)
Definition at line 387 of file TRunInfo.cxx.
References DYELLOW, fFirstRunNumber, fFirstSubRunNumber, fLastRunNumber, fLastSubRunNumber, fRunLength, fRunList, fRunNumber, fRunStart, fRunStop, fSubRunNumber, and RESET_COLOR.
Referenced by Merge().
AddBadCycle()
void TRunInfo::AddBadCycle (int bad_cycle) static
Definition at line 290 of file TRunInfo.cxx.
References fBadCycleList, and TSingleton< TRunInfo >::Get().
Referenced by ParseInputData().
AddCurrent()
static TRunInfo * TSingleton< TRunInfo >::AddCurrent () inline static inherited
Definition at line 141 of file TSingleton.h.
Referenced by Analyze().
BuildMode()
TEventBuildingLoop::EBuildMode TRunInfo::BuildMode () const virtual
Definition at line 381 of file TRunInfo.cxx.
References TEventBuildingLoop::kDefault.
Clear()
void TRunInfo::Clear (Option_t * opt = "") override
Definition at line 122 of file TRunInfo.cxx.
References fBadCycleList, fDetectorInformation, and fHPGeArrayPosition.
Referenced by TRunInfo().
ClearDate()
static void TRunInfo::ClearDate () inline static
Definition at line 170 of file TRunInfo.h.
References fDate, and TSingleton< TRunInfo >::Get().
Referenced by TGRSIint::ApplyOptions(), and SetRunInfo().
ClearFullVersion()
static void TRunInfo::ClearFullVersion () inline static
Definition at line 158 of file TRunInfo.h.
References fFullVersion, and TSingleton< TRunInfo >::Get().
Referenced by TGRSIint::ApplyOptions(), and SetRunInfo().
ClearLibraryPath()
static void TRunInfo::ClearLibraryPath () inline static
Definition at line 194 of file TRunInfo.h.
References fLibraryPath, and TSingleton< TRunInfo >::Get().
ClearLibraryVersion()
static void TRunInfo::ClearLibraryVersion () inline static
Definition at line 182 of file TRunInfo.h.
References fLibraryVersion, and TSingleton< TRunInfo >::Get().
Referenced by TMidasFile::Open().
ClearVersion()
static void TRunInfo::ClearVersion () inline static
Definition at line 146 of file TRunInfo.h.
References fVersion, and TSingleton< TRunInfo >::Get().
Referenced by TGRSIint::ApplyOptions(), TLstFile::Open(), TRlmdFile::Open(), TTdrFile::Open(), and SetRunInfo().
CreateLabel()
std::string TRunInfo::CreateLabel (bool quiet = false) static
This function creates a label/string based on the run number and the subrun number.
Definition at line 582 of file TRunInfo.cxx.
References FirstRunNumber(), FirstSubRunNumber(), LastRunNumber(), LastSubRunNumber(), RunNumber(), and SubRunNumber().
Referenced by TGRSIFrame::Run().
FirstRunNumber()
static int TRunInfo::FirstRunNumber () inline static
Definition at line 214 of file TRunInfo.h.
References fFirstRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), Print(), and TGRSISelector::Terminate().
FirstSubRunNumber()
static int TRunInfo::FirstSubRunNumber () inline static
Definition at line 215 of file TRunInfo.h.
References fFirstSubRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), Print(), and TGRSISelector::Terminate().
Get()
static TRunInfo * TSingleton< TRunInfo >::Get (bool verbose = false) inline static inherited
Definition at line 33 of file TSingleton.h.
Referenced by AddBadCycle(), Analyze(), ClearDate(), ClearFullVersion(), ClearLibraryPath(), ClearLibraryVersion(), ClearVersion(), FirstRunNumber(), FirstSubRunNumber(), GetCalFileData(), GetCalFileName(), GetDate(), GetDetectorInformation(), GetFullVersion(), GetLibraryPath(), GetLibraryVersion(), GetRunInfoFileData(), GetRunInfoFileName(), GetVersion(), GetXMLODBFileData(), GetXMLODBFileName(), HPGeArrayPosition(), IsBadCycle(), LastRunNumber(), LastSubRunNumber(), main(), PrintBadCycles(), PrintToString(), ReadInfoFromFile(), RemoveBadCycle(), TGRSIFrame::Run(), RunComment(), RunLength(), RunNumber(), RunStart(), RunStop(), RunTitle(), SetCalFileData(), SetCalFileName(), SetDate(), SetDetectorInformation(), SetFullVersion(), SetHPGeArrayPosition(), SetLibraryPath(), SetLibraryVersion(), SetRunComment(), SetRunInfo(), SetRunInfoFile(), SetRunInfoFileName(), SetRunLength(), SetRunLength(), SetRunNumber(), SetRunStart(), SetRunStop(), SetRunTitle(), SetSubRunNumber(), SetVersion(), SetXMLODBFileData(), SetXMLODBFileName(), SubRunNumber(), TGRSISelector::Terminate(), and WriteToRoot().
GetAll()
static TRunInfo * TSingleton< TRunInfo >::GetAll () inline static inherited
Definition at line 66 of file TSingleton.h.
GetCalFileData()
static const char * TRunInfo::GetCalFileData () inline static
Definition at line 256 of file TRunInfo.h.
References fCalFile, and TSingleton< TRunInfo >::Get().
GetCalFileName()
static const char * TRunInfo::GetCalFileName () inline static
Definition at line 255 of file TRunInfo.h.
References fCalFileName, and TSingleton< TRunInfo >::Get().
GetDate()
static std::string TRunInfo::GetDate () inline static
Definition at line 169 of file TRunInfo.h.
References fDate, and TSingleton< TRunInfo >::Get().
GetDetectorInformation()
static TDetectorInformation * TRunInfo::GetDetectorInformation () inline static
Definition at line 290 of file TRunInfo.h.
References fDetectorInformation, and TSingleton< TRunInfo >::Get().
Referenced by TDescant::GetPosition(), and TGRSIint::SetupPipeline().
GetFullVersion()
static std::string TRunInfo::GetFullVersion () inline static
Definition at line 157 of file TRunInfo.h.
References fFullVersion, and TSingleton< TRunInfo >::Get().
GetLibraryPath()
static std::string TRunInfo::GetLibraryPath () inline static
Definition at line 193 of file TRunInfo.h.
References fLibraryPath, and TSingleton< TRunInfo >::Get().
GetLibraryVersion()
static std::string TRunInfo::GetLibraryVersion () inline static
Definition at line 181 of file TRunInfo.h.
References fLibraryVersion, and TSingleton< TRunInfo >::Get().
GetRunInfoFileData()
static const char * TRunInfo::GetRunInfoFileData () inline static
Definition at line 262 of file TRunInfo.h.
References fRunInfoFile, and TSingleton< TRunInfo >::Get().
GetRunInfoFileName()
static const char * TRunInfo::GetRunInfoFileName () inline static
Definition at line 261 of file TRunInfo.h.
References fRunInfoFileName, and TSingleton< TRunInfo >::Get().
GetVersion()
static std::string TRunInfo::GetVersion () inline static
Definition at line 145 of file TRunInfo.h.
References fVersion, and TSingleton< TRunInfo >::Get().
GetXMLODBFileData()
static const char * TRunInfo::GetXMLODBFileData () inline static
Definition at line 259 of file TRunInfo.h.
References fXMLODBFile, and TSingleton< TRunInfo >::Get().
GetXMLODBFileName()
static const char * TRunInfo::GetXMLODBFileName () inline static
Definition at line 258 of file TRunInfo.h.
References fXMLODBFileName, and TSingleton< TRunInfo >::Get().
HPGeArrayPosition()
static double TRunInfo::HPGeArrayPosition () inline static
Definition at line 271 of file TRunInfo.h.
References fHPGeArrayPosition, and TSingleton< TRunInfo >::Get().
Referenced by ParseInputData(), Print(), and PrintToString().
IsBadCycle()
bool TRunInfo::IsBadCycle (int cycle) static
Definition at line 304 of file TRunInfo.cxx.
References fBadCycleList, and TSingleton< TRunInfo >::Get().
LastRunNumber()
static int TRunInfo::LastRunNumber () inline static
Definition at line 217 of file TRunInfo.h.
References fLastRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), Print(), and TGRSISelector::Terminate().
LastSubRunNumber()
static int TRunInfo::LastSubRunNumber () inline static
Definition at line 218 of file TRunInfo.h.
References fLastSubRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), Print(), and TGRSISelector::Terminate().
ListOfMissingRuns()
std::string TRunInfo::ListOfMissingRuns (bool all = false) const
Outputs a comma separated list of all runs missing between fFirstRunNumber and fLastRunNumber. If no runs are missing prints "none".
Definition at line 533 of file TRunInfo.cxx.
References fRunList.
Referenced by Print().
Merge()
Long64_t TRunInfo::Merge (TCollection * list)
Definition at line 263 of file TRunInfo.cxx.
References Add().
operator=() [1/2]
TRunInfo & TRunInfo::operator= (const TRunInfo &) default
operator=() [2/2]
TRunInfo & TRunInfo::operator= (TRunInfo &&) default noexcept
ParseInputData()
Bool_t TRunInfo::ParseInputData (const char * inputdata = "", Option_t * opt = "q") static
Definition at line 207 of file TRunInfo.cxx.
References AddBadCycle(), DBLUE, DRED, HPGeArrayPosition(), RESET_COLOR, SetHPGeArrayPosition(), and trim().
Referenced by ReadInfoFile(), and SetRunInfo().
Print()
void TRunInfo::Print (Option_t * opt = "") const override
Prints the TRunInfo. Options: a: Print out more details (array position and detector information).
Definition at line 72 of file TRunInfo.cxx.
References DBLUE, DRED, fDetectorInformation, FirstRunNumber(), FirstSubRunNumber(), fRunList, HPGeArrayPosition(), LastRunNumber(), LastSubRunNumber(), ListOfMissingRuns(), TDetectorInformation::Print(), TSingleton< T >::PrintDirectory(), RESET_COLOR, RunComment(), RunLength(), RunNumber(), RunStart(), RunStop(), RunTitle(), and SubRunNumber().
Referenced by Analyze(), main(), and TGRSISelector::Terminate().
PrintBadCycles()
void TRunInfo::PrintBadCycles () static
Definition at line 277 of file TRunInfo.cxx.
References fBadCycleList, and TSingleton< TRunInfo >::Get().
PrintDirectory()
static void TSingleton< TRunInfo >::PrintDirectory () inline static inherited
Definition at line 170 of file TSingleton.h.
PrintRunList()
void TRunInfo::PrintRunList () const
Definition at line 521 of file TRunInfo.cxx.
References fRunList.
PrintToString()
std::string TRunInfo::PrintToString (Option_t * opt = "") static
Definition at line 363 of file TRunInfo.cxx.
References fBadCycleList, TSingleton< TRunInfo >::Get(), and HPGeArrayPosition().
Referenced by WriteInfoFile().
PrintVersion()
void TRunInfo::PrintVersion () const
Definition at line 571 of file TRunInfo.cxx.
References fDate, fFullVersion, fLibraryPath, fLibraryVersion, fVersion, RESET_COLOR, and YELLOW.
ReadInfoFile()
Bool_t TRunInfo::ReadInfoFile (const char * filename = "") static
Read in a run info file. These files have the extension .info.
Definition at line 174 of file TRunInfo.cxx.
References CYAN, ParseInputData(), RESET_COLOR, SetRunInfoFile(), and SetRunInfoFileName().
Referenced by TGRSIint::SetupPipeline().
ReadInfoFromFile()
Bool_t TRunInfo::ReadInfoFromFile (TFile * tempf = nullptr) static
Definition at line 15 of file TRunInfo.cxx.
References fDetectorInformation, TSingleton< TRunInfo >::Get(), and TSingleton< TRunInfo >::Set().
Referenced by TGRSIint::OpenRootFile().
RemoveBadCycle()
void TRunInfo::RemoveBadCycle (int cycle) static
Definition at line 298 of file TRunInfo.cxx.
References fBadCycleList, and TSingleton< TRunInfo >::Get().
RunComment()
static std::string TRunInfo::RunComment () inline static
Definition at line 230 of file TRunInfo.h.
References fRunComment, and TSingleton< TRunInfo >::Get().
Referenced by Print().
RunLength()
static double TRunInfo::RunLength () inline static
Definition at line 247 of file TRunInfo.h.
References fRunLength, and TSingleton< TRunInfo >::Get().
Referenced by Print().
RunNumber()
static int TRunInfo::RunNumber () inline static
Definition at line 211 of file TRunInfo.h.
References fRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), main(), MakeAnalysisHistograms(), Print(), TGRSISortInfo::SetRunInfo(), SetRunInfo(), SetRunLength(), TPPG::Setup(), and TGRSISelector::Terminate().
RunStart()
static double TRunInfo::RunStart () inline static
Definition at line 245 of file TRunInfo.h.
References fRunStart, and TSingleton< TRunInfo >::Get().
Referenced by TEpicsFrag::BuildScalerMap(), and Print().
RunStop()
static double TRunInfo::RunStop () inline static
Definition at line 246 of file TRunInfo.h.
References fRunStop, and TSingleton< TRunInfo >::Get().
Referenced by Print().
RunTitle()
static std::string TRunInfo::RunTitle () inline static
Definition at line 229 of file TRunInfo.h.
References fRunTitle, and TSingleton< TRunInfo >::Get().
Referenced by Print().
Set()
static void TSingleton< TRunInfo >::Set (TRunInfo * val) inline static inherited
Definition at line 133 of file TSingleton.h.
Referenced by ReadInfoFromFile().
SetAnalysisTreeBranches()
void TRunInfo::SetAnalysisTreeBranches (TTree *) static
Definition at line 169 of file TRunInfo.cxx.
SetCalFileData()
static void TRunInfo::SetCalFileData (const char * data) inline static
Definition at line 250 of file TRunInfo.h.
References fCalFile, and TSingleton< TRunInfo >::Get().
SetCalFileName()
static void TRunInfo::SetCalFileName (const char * name) inline static
Definition at line 249 of file TRunInfo.h.
References fCalFileName, and TSingleton< TRunInfo >::Get().
SetDate() [1/2]
static void TRunInfo::SetDate (const char * ver) inline static
Definition at line 171 of file TRunInfo.h.
References SetDate().
Referenced by TGRSIint::ApplyOptions(), SetDate(), and SetRunInfo().
SetDate() [2/2]
static void TRunInfo::SetDate (std::string ver) inline static
Definition at line 172 of file TRunInfo.h.
References ALERTTEXT, fDate, TSingleton< TRunInfo >::Get(), and RESET_COLOR.
SetDetectorInformation()
static void TRunInfo::SetDetectorInformation (TDetectorInformation * inf) inline static
Definition at line 289 of file TRunInfo.h.
References fDetectorInformation, and TSingleton< TRunInfo >::Get().
Referenced by TLstFile::Open(), TMidasFile::Open(), TRlmdFile::Open(), and TTdrFile::Open().
SetFullVersion() [1/2]
static void TRunInfo::SetFullVersion (const char * ver) inline static
Definition at line 159 of file TRunInfo.h.
References SetFullVersion().
Referenced by TGRSIint::ApplyOptions(), SetFullVersion(), and SetRunInfo().
SetFullVersion() [2/2]
static void TRunInfo::SetFullVersion (std::string ver) inline static
Definition at line 160 of file TRunInfo.h.
References ALERTTEXT, fFullVersion, TSingleton< TRunInfo >::Get(), and RESET_COLOR.
SetHPGeArrayPosition()
static void TRunInfo::SetHPGeArrayPosition (const double arr_pos) inline static
Definition at line 270 of file TRunInfo.h.
References fHPGeArrayPosition, and TSingleton< TRunInfo >::Get().
Referenced by ParseInputData().
SetLibraryPath() [1/2]
static void TRunInfo::SetLibraryPath (const char * ver) inline static
Definition at line 195 of file TRunInfo.h.
References SetLibraryPath().
Referenced by TParserLibrary::Load(), and SetLibraryPath().
SetLibraryPath() [2/2]
static void TRunInfo::SetLibraryPath (std::string ver) inline static
Definition at line 196 of file TRunInfo.h.
References ALERTTEXT, fLibraryPath, TSingleton< TRunInfo >::Get(), and RESET_COLOR.
SetLibraryVersion() [1/2]
static void TRunInfo::SetLibraryVersion (const char * ver) inline static
Definition at line 183 of file TRunInfo.h.
References SetLibraryVersion().
Referenced by TParserLibrary::Load(), TMidasFile::Open(), and SetLibraryVersion().
SetLibraryVersion() [2/2]
static void TRunInfo::SetLibraryVersion (std::string ver) inline static
Definition at line 184 of file TRunInfo.h.
References ALERTTEXT, fLibraryVersion, TSingleton< TRunInfo >::Get(), and RESET_COLOR.
SetRunComment()
static void TRunInfo::SetRunComment (const char * run_comment) inline static
Definition at line 224 of file TRunInfo.h.
References fRunComment, and TSingleton< TRunInfo >::Get().
Referenced by main(), and TMidasFile::SetRunInfo().
SetRunInfo()
void TRunInfo::SetRunInfo (int runnum = 0, int subrunnum = -1) static
Sets the run info. This figures out what systems are available.
Definition at line 135 of file TRunInfo.cxx.
References ClearDate(), ClearFullVersion(), ClearVersion(), fRunInfoFile, TSingleton< TRunInfo >::Get(), TChannel::GetNumberOfChannels(), ParseInputData(), RunNumber(), SetDate(), SetFullVersion(), SetRunNumber(), SetSubRunNumber(), SetVersion(), and SubRunNumber().
Referenced by TLstFile::Open(), TMidasFile::Open(), TRlmdFile::Open(), TTdrFile::Open(), and TGRSIint::SetupPipeline().
SetRunInfoFile()
static void TRunInfo::SetRunInfoFile (const char * ffile) inline static
Definition at line 268 of file TRunInfo.h.
References fRunInfoFile, and TSingleton< TRunInfo >::Get().
Referenced by ReadInfoFile().
SetRunInfoFileName()
static void TRunInfo::SetRunInfoFileName (const char * fname) inline static
Definition at line 267 of file TRunInfo.h.
References fRunInfoFileName, and TSingleton< TRunInfo >::Get().
Referenced by ReadInfoFile().
SetRunLength() [1/2]
static void TRunInfo::SetRunLength () inline static
Definition at line 235 of file TRunInfo.h.
References fRunLength, fRunStart, fRunStop, TSingleton< TRunInfo >::Get(), and RunNumber().
Referenced by main(), TLstFile::Open(), TRlmdFile::Open(), TGRSIDataParser::Process(), and TRlmdFile::Read().
SetRunLength() [2/2]
static void TRunInfo::SetRunLength (double tmp) inline static
Definition at line 234 of file TRunInfo.h.
References fRunLength, and TSingleton< TRunInfo >::Get().
SetRunNumber()
static void TRunInfo::SetRunNumber (int tmp) inline static
Definition at line 208 of file TRunInfo.h.
References fRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by main(), and SetRunInfo().
SetRunStart()
static void TRunInfo::SetRunStart (double tmp) inline static
Definition at line 232 of file TRunInfo.h.
References fRunStart, and TSingleton< TRunInfo >::Get().
Referenced by main(), TRlmdFile::Read(), and TMidasFile::SetRunInfo().
SetRunStop()
static void TRunInfo::SetRunStop (double tmp) inline static
Definition at line 233 of file TRunInfo.h.
References fRunStop, and TSingleton< TRunInfo >::Get().
Referenced by main(), TGRSIDataParser::Process(), and TRlmdFile::Read().
SetRunTitle()
static void TRunInfo::SetRunTitle (const char * run_title) inline static
Definition at line 220 of file TRunInfo.h.
References fRunTitle, and TSingleton< TRunInfo >::Get().
Referenced by main(), and TMidasFile::SetRunInfo().
SetSubRunNumber()
static void TRunInfo::SetSubRunNumber (int tmp) inline static
Definition at line 209 of file TRunInfo.h.
References fSubRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by main(), and SetRunInfo().
SetVersion() [1/2]
static void TRunInfo::SetVersion (const char * ver) inline static
Definition at line 147 of file TRunInfo.h.
References SetVersion().
Referenced by TGRSIint::ApplyOptions(), TLstFile::Open(), TRlmdFile::Open(), TTdrFile::Open(), SetRunInfo(), and SetVersion().
SetVersion() [2/2]
static void TRunInfo::SetVersion (std::string ver) inline static
Definition at line 148 of file TRunInfo.h.
References ALERTTEXT, fVersion, TSingleton< TRunInfo >::Get(), and RESET_COLOR.
SetXMLODBFileData()
static void TRunInfo::SetXMLODBFileData (const char * data) inline static
Definition at line 253 of file TRunInfo.h.
References fXMLODBFile, and TSingleton< TRunInfo >::Get().
SetXMLODBFileName()
static void TRunInfo::SetXMLODBFileName (const char * name) inline static
Definition at line 252 of file TRunInfo.h.
References fXMLODBFileName, and TSingleton< TRunInfo >::Get().
SubRunNumber()
static int TRunInfo::SubRunNumber () inline static
Definition at line 212 of file TRunInfo.h.
References fSubRunNumber, and TSingleton< TRunInfo >::Get().
Referenced by AtExitHandler(), CreateLabel(), main(), Print(), TGRSISortInfo::SetRunInfo(), TMidasFile::SetRunInfo(), SetRunInfo(), TPPG::Setup(), and TGRSISelector::Terminate().
WriteInfoFile()
bool TRunInfo::WriteInfoFile (const std::string & filename) static
Definition at line 344 of file TRunInfo.cxx.
References PrintToString().
WriteToRoot()
bool TRunInfo::WriteToRoot (TFile * fileptr = nullptr) static
Writes Info File information to the tree
Definition at line 309 of file TRunInfo.cxx.
References fDetectorInformation, and TSingleton< TRunInfo >::Get().
Referenced by TAnalysisWriteLoop::Write(), and TFragWriteLoop::Write().
Friends And Related Symbol Documentation
TSingleton< TRunInfo >
friend class TSingleton< TRunInfo > friend
Definition at line 1 of file TRunInfo.h.
Member Data Documentation
fBadCycleList
std::vector<int> TRunInfo::fBadCycleList private
!List of bad cycles to be used for cycle rejection
Definition at line 335 of file TRunInfo.h.
Referenced by AddBadCycle(), Clear(), IsBadCycle(), PrintBadCycles(), PrintToString(), and RemoveBadCycle().
fCalFile
std::string TRunInfo::fCalFile private
Cal File to load into Cal of tree.
Definition at line 321 of file TRunInfo.h.
Referenced by GetCalFileData(), and SetCalFileData().
fCalFileName
std::string TRunInfo::fCalFileName private
Name of calfile that generated cal.
Definition at line 320 of file TRunInfo.h.
Referenced by GetCalFileName(), and SetCalFileName().
fDate
std::string TRunInfo::fDate private
The date of the last commit used in this version - GRSI_GIT_COMMIT_TIME from GVersion.h.
Definition at line 316 of file TRunInfo.h.
Referenced by ClearDate(), GetDate(), PrintVersion(), and SetDate().
fDetectorInformation
TDetectorInformation* TRunInfo::fDetectorInformation {nullptr} private
! pointer to detector specific information (set by each parser library)
Definition at line 337 of file TRunInfo.h.
Referenced by Clear(), GetDetectorInformation(), Print(), ReadInfoFromFile(), SetDetectorInformation(), and WriteToRoot().
fDir
TDirectory * TSingleton< TRunInfo >::fDir static private inherited
Definition at line 186 of file TSingleton.h.
fFirstRunNumber
int TRunInfo::fFirstRunNumber {0} private
The first run number (for combined runs)
Definition at line 304 of file TRunInfo.h.
Referenced by Add(), and FirstRunNumber().
fFirstSubRunNumber
int TRunInfo::fFirstSubRunNumber {-1} private
The first sub run number (for combined subruns)
Definition at line 305 of file TRunInfo.h.
Referenced by Add(), and FirstSubRunNumber().
fFullVersion
std::string TRunInfo::fFullVersion private
The full version of GRSISort that generated the file (includes last commit) - GRSI_GIT_COMMIT from GVersion.h.
Definition at line 315 of file TRunInfo.h.
Referenced by ClearFullVersion(), GetFullVersion(), PrintVersion(), and SetFullVersion().
fHPGeArrayPosition
double TRunInfo::fHPGeArrayPosition {110.} private
Position of the HPGe Array (default = 110.0 mm);.
Definition at line 333 of file TRunInfo.h.
Referenced by Clear(), HPGeArrayPosition(), and SetHPGeArrayPosition().
fLastRunNumber
int TRunInfo::fLastRunNumber {0} private
The last run number (for combined runs)
Definition at line 306 of file TRunInfo.h.
Referenced by Add(), and LastRunNumber().
fLastSubRunNumber
int TRunInfo::fLastSubRunNumber {-1} private
The last sub run number (for combined subruns)
Definition at line 307 of file TRunInfo.h.
Referenced by Add(), and LastSubRunNumber().
fLibraryPath
std::string TRunInfo::fLibraryPath private
The path of the parser/file library that generated the file.
Definition at line 318 of file TRunInfo.h.
Referenced by ClearLibraryPath(), GetLibraryPath(), PrintVersion(), and SetLibraryPath().
fLibraryVersion
std::string TRunInfo::fLibraryVersion private
The version of the parser/file library that generated the file.
Definition at line 317 of file TRunInfo.h.
Referenced by ClearLibraryVersion(), GetLibraryVersion(), PrintVersion(), and SetLibraryVersion().
fRunComment
std::string TRunInfo::fRunComment private
The comment on the run.
Definition at line 301 of file TRunInfo.h.
Referenced by RunComment(), and SetRunComment().
fRunInfoFile
std::string TRunInfo::fRunInfoFile private
The contents of the run info file.
Definition at line 331 of file TRunInfo.h.
Referenced by GetRunInfoFileData(), SetRunInfo(), and SetRunInfoFile().
fRunInfoFileName
std::string TRunInfo::fRunInfoFileName private
The name of the Run info file.
Definition at line 330 of file TRunInfo.h.
Referenced by GetRunInfoFileName(), and SetRunInfoFileName().
fRunLength
double TRunInfo::fRunLength {0.} private
The length of the current run in seconds - no idea why we store this as double?
Definition at line 312 of file TRunInfo.h.
Referenced by Add(), RunLength(), SetRunLength(), and SetRunLength().
fRunList
std::set<std::pair<int, int> > TRunInfo::fRunList private
List of all runs added to this run info.
Definition at line 308 of file TRunInfo.h.
Referenced by Add(), ListOfMissingRuns(), Print(), and PrintRunList().
fRunNumber
int TRunInfo::fRunNumber {0} private
The current run number.
Definition at line 302 of file TRunInfo.h.
Referenced by Add(), RunNumber(), and SetRunNumber().
fRunStart
double TRunInfo::fRunStart {0.} private
The start of the current run in seconds - no idea why we store this as double?
Definition at line 310 of file TRunInfo.h.
Referenced by Add(), RunStart(), SetRunLength(), and SetRunStart().
fRunStop
double TRunInfo::fRunStop {0.} private
The stop of the current run in seconds - no idea why we store this as double?
Definition at line 311 of file TRunInfo.h.
Referenced by Add(), RunStop(), SetRunLength(), and SetRunStop().
fRunTitle
std::string TRunInfo::fRunTitle private
The title of the run.
Definition at line 300 of file TRunInfo.h.
Referenced by RunTitle(), and SetRunTitle().
fSingleton
TRunInfo * TSingleton< TRunInfo >::fSingleton static private inherited
Definition at line 185 of file TSingleton.h.
fSubRunNumber
int TRunInfo::fSubRunNumber {-1} private
The current sub run number.
Definition at line 303 of file TRunInfo.h.
Referenced by Add(), SetSubRunNumber(), and SubRunNumber().
fVersion
std::string TRunInfo::fVersion private
The version of GRSISort that generated the file - GRSI_RELEASE from GVersion.h.
Definition at line 314 of file TRunInfo.h.
Referenced by ClearVersion(), GetVersion(), PrintVersion(), and SetVersion().
fXMLODBFile
std::string TRunInfo::fXMLODBFile private
The odb.
Definition at line 324 of file TRunInfo.h.
Referenced by GetXMLODBFileData(), and SetXMLODBFileData().
fXMLODBFileName
std::string TRunInfo::fXMLODBFileName private
Name of XML Odb file.
Definition at line 323 of file TRunInfo.h.
Referenced by GetXMLODBFileName(), and SetXMLODBFileName().