GRSISort: TFippsTAC Class Reference
TFippsTAC Class Reference
Detectors
Detailed Description
The TFippsTAC class defines the observables and algorithms used when analyzing TAC data. It includes detector positions, etc.
Definition at line 27 of file TFippsTAC.h.
Public Member Functions
TFippsTAC ()
TFippsTAC (const TFippsTAC &rhs)
~TFippsTAC () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TFippsTACHit * GetTACHit (const int &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TFippsTAC & operator= (const TFippsTAC &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Private Attributes
std::vector< TDetectorHit * > fHits
Constructor & Destructor Documentation
TFippsTAC() [1/2]
TFippsTAC::TFippsTAC ()
Definition at line 6 of file TFippsTAC.cxx.
References TDetector::Clear().
~TFippsTAC()
TFippsTAC::~TFippsTAC () override
Definition at line 15 of file TFippsTAC.cxx.
TFippsTAC() [2/2]
TFippsTAC::TFippsTAC (const TFippsTAC & rhs)
Definition at line 20 of file TFippsTAC.cxx.
References TDetector::Copy().
Member Function Documentation
AddFragment()
void TFippsTAC::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 48 of file TFippsTAC.cxx.
References TDetector::Hits().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TFippsTAC::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 39 of file TFippsTAC.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::TAries(), TDemand::TDemand(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC(), TGenericDetector::TGenericDetector(), TPaces::TPaces(), TSceptar::TSceptar(), TTAC::TTAC(), TZeroDegree::TZeroDegree(), TBgo::Clear(), TDescant::Clear(), TEagle::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TSharc2::Clear(), TSharc::Clear(), TSiLi::Clear(), TSuppressed::Clear(), TTdrPlastic::Clear(), TTdrSiLi::Clear(), TTigress::Clear(), TTrific::Clear(), and TTriFoil::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override inherited
!
Definition at line 24 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TAries::TAries(), TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC(), TGenericDetector::TGenericDetector(), TSceptar::TSceptar(), TTAC::TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree::TZeroDegree(), TBgo::Copy(), TDemand::Copy(), TDescant::Copy(), TEagle::Copy(), TEmma::Copy(), TPaces::Copy(), TRcmp::Copy(), TRF::Copy(), TS3::Copy(), TSharc2::Copy(), TSharc::Copy(), TSiLi::Copy(), TSuppressed::Copy(), TTdrSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TTriFoil::Copy(), TAries::operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), operator=(), TGenericDetector::operator=(), TSceptar::operator=(), TTAC::operator=(), TTdrPlastic::operator=(), TTip::operator=(), and TZeroDegree::operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetTACHit()
TFippsTACHit * TFippsTAC::GetTACHit (const int & i) const inline
Definition at line 34 of file TFippsTAC.h.
References TDetector::GetHit().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=()
TFippsTAC & TFippsTAC::operator= (const TFippsTAC & rhs)
!
Definition at line 29 of file TFippsTAC.cxx.
References TDetector::Copy().
Print() [1/2]
void TFippsTAC::Print (Option_t * opt = "") const override
!
Definition at line 35 of file TFippsTAC.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TFippsTAC::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 41 of file TFippsTAC.cxx.
References TDetector::Hits().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().