GRSISort: GriffinKValueHelper Class Reference
GriffinKValueHelper Class Reference
Detailed Description
Definition at line 10 of file GriffinKValueHelper.hh.
Public Types
using Result_t = std::map<std::string, TList>
Public Member Functions
GriffinKValueHelper (TList *list)
ROOT::RDF::RResultPtr< std::map< std::string, TList > > Book (ROOT::RDataFrame *d) override
void CreateHistograms (unsigned int slot) override
virtual void EndOfSort (std::shared_ptr< std::map< std::string, TList > > &)
void Exec (unsigned int sloti, TFragment &frag)
void Finalize ()
std::string GetActionName () const
std::shared_ptr< std::map< std::string, TList > > GetResultPtr () const
void Initialize ()
void InitTask (TTreeReader *, unsigned int)
std::string & Prefix ()
std::string Prefix () const
void Prefix (const std::string &val)
virtual void Setup ()
Protected Member Functions
TPPG * Ppg ()
TRunInfo * RunInfo ()
TUserSettings * UserSettings ()
Protected Attributes
std::vector< TGRSIMap< std::string, GCube * > > fCube
std::map< std::string, TCutG * > fCuts
std::vector< TGRSIMap< std::string, TH1 * > > fH1
std::vector< TGRSIMap< std::string, TH2 * > > fH2
std::vector< TGRSIMap< std::string, TH3 * > > fH3
std::vector< std::shared_ptr< std::map< std::string, TList > > > fLists
std::vector< TGRSIMap< std::string, TObject * > > fObject
TPPG * fPpg {nullptr}
std::string fPrefix {"TGRSIHelper"}
TRunInfo * fRunInfo {nullptr}
std::vector< TGRSIMap< std::string, GHSym * > > fSym
std::vector< TGRSIMap< std::string, TTree * > > fTree
TUserSettings * fUserSettings {nullptr}
Private Member Functions
void CheckSizes (unsigned int slot, const char *usage)
Static Private Attributes
static constexpr int fSizeLimit = 1073741822
Member Typedef Documentation
Result_t
using TGRSIHelper::Result_t = std::map<std::string, TList> inherited
This type is a requirement for every helper.
Definition at line 67 of file TGRSIHelper.h.
Constructor & Destructor Documentation
GriffinKValueHelper()
GriffinKValueHelper::GriffinKValueHelper (TList * list) inline explicit
Definition at line 12 of file GriffinKValueHelper.hh.
References TGRSIHelper::Prefix(), and TGRSIHelper::Setup().
Member Function Documentation
Book()
ROOT::RDF::RResultPtr< std::map< std::string, TList > > GriffinKValueHelper::Book (ROOT::RDataFrame *) inline override virtual
This method will call the Book action on the provided dataframe.
Reimplemented from TGRSIHelper.
Definition at line 18 of file GriffinKValueHelper.hh.
CheckSizes()
void TGRSIHelper::CheckSizes (unsigned int slot, const char * usage) private inherited
check size of each object in the output list
Definition at line 215 of file TGRSIHelper.cxx.
References DRED, TGRSIHelper::fLists, TGRSIHelper::fSizeLimit, and RESET_COLOR.
Referenced by TGRSIHelper::Finalize(), and TGRSIHelper::Setup().
CreateHistograms()
void GriffinKValueHelper::CreateHistograms (unsigned int) override virtual
Virtual helper function that the user uses to create their histograms.
Reimplemented from TGRSIHelper.
Definition at line 5 of file GriffinKValueHelper.cxx.
References TGRSIHelper::fH1, TGRSIHelper::fH2, and maxKValue.
EndOfSort()
virtual void TGRSIHelper::EndOfSort (std::shared_ptr< std::map< std::string, TList > > &) inline virtual inherited
This method gets called at the end of Finalize()
Reimplemented in DirectoryHelper, EfficiencyHelper, and ExampleEventHelper.
Definition at line 100 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Finalize().
Exec()
void GriffinKValueHelper::Exec (unsigned int sloti, TFragment & frag)
Definition at line 25 of file GriffinKValueHelper.cxx.
References TGRSIHelper::fH1, TGRSIHelper::fH2, TFragment::GetDetectorType(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), and TFragment::GetNumberOfPileups().
Finalize()
void TGRSIHelper::Finalize () inherited
This required method is called at the end of the event loop. It is used to merge all the internal TLists which were used in each of the data processing slots.
This function merges all maps of lists into the map of the first slot (slot 0)
Definition at line 154 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::EndOfSort(), and TGRSIHelper::fLists.
GetActionName()
std::string TGRSIHelper::GetActionName () const inline inherited
Definition at line 104 of file TGRSIHelper.h.
References TGRSIHelper::Prefix().
GetResultPtr()
std::shared_ptr< std::map< std::string, TList > > TGRSIHelper::GetResultPtr () const inline inherited
Definition at line 92 of file TGRSIHelper.h.
References TGRSIHelper::fLists.
Initialize()
void TGRSIHelper::Initialize () inline inherited
Definition at line 94 of file TGRSIHelper.h.
InitTask()
void TGRSIHelper::InitTask (TTreeReader * , unsigned int) inline inherited
Definition at line 93 of file TGRSIHelper.h.
Ppg()
TPPG * TGRSIHelper::Ppg () inline protected inherited
Definition at line 43 of file TGRSIHelper.h.
References TGRSIHelper::fPpg.
Referenced by ExampleEventHelper::CreateHistograms().
Prefix() [1/3]
std::string & TGRSIHelper::Prefix () inline inherited
Definition at line 40 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper::EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper(), TimeWalkHelper::TimeWalkHelper(), TGRSIHelper::Book(), TGRSIHelper::CreateHistograms(), and TGRSIHelper::GetActionName().
Prefix() [2/3]
std::string TGRSIHelper::Prefix () const inline inherited
Definition at line 102 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Prefix() [3/3]
void TGRSIHelper::Prefix (const std::string & val) inline inherited
Definition at line 103 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
RunInfo()
TRunInfo * TGRSIHelper::RunInfo () inline protected inherited
Definition at line 44 of file TGRSIHelper.h.
References TGRSIHelper::fRunInfo.
Setup()
void TGRSIHelper::Setup () virtual inherited
This function builds the vectors of TLists and maps for 1D- and 2D-histograms. It calls the overloaded CreateHistograms functions in which the user can define their histograms. Then it adds all those histograms to the list of the corresponding slot.
Definition at line 71 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::CreateHistograms(), TGRSIHelper::fCube, TGRSIHelper::fH1, TGRSIHelper::fH2, TGRSIHelper::fH3, TGRSIHelper::fLists, TGRSIHelper::fObject, TGRSIHelper::fSym, TGRSIHelper::fTree, TGRSIOptions::Get(), and TGRSIOptions::GetMaxWorkers().
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper::EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper(), and TimeWalkHelper::TimeWalkHelper().
UserSettings()
TUserSettings * TGRSIHelper::UserSettings () inline protected inherited
Definition at line 45 of file TGRSIHelper.h.
References TGRSIHelper::fUserSettings.
Member Data Documentation
fCube
std::vector<TGRSIMap<std::string, GCube*> > TGRSIHelper::fCube protected inherited
Definition at line 52 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fCuts
std::map<std::string, TCutG*> TGRSIHelper::fCuts protected inherited
Definition at line 55 of file TGRSIHelper.h.
Referenced by TGRSIHelper::TGRSIHelper().
fH1
std::vector<TGRSIMap<std::string, TH1*> > TGRSIHelper::fH1 protected inherited
Definition at line 48 of file TGRSIHelper.h.
Referenced by ComptonPolarimetryHelper::CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), EfficiencyHelper::CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), CreateHistograms(), ComptonPolarimetryHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), Exec(), and TGRSIHelper::Setup().
fH2
std::vector<TGRSIMap<std::string, TH2*> > TGRSIHelper::fH2 protected inherited
Definition at line 49 of file TGRSIHelper.h.
Referenced by AlphanumericHelper::CreateHistograms(), AngularCorrelationHelper::CreateHistograms(), ComptonPolarimetryHelper::CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), EfficiencyHelper::CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleFragmentHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), CreateHistograms(), TimeWalkHelper::CreateHistograms(), ExampleEventHelper::EndOfSort(), AlphanumericHelper::Exec(), AngularCorrelationHelper::Exec(), ComptonPolarimetryHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), Exec(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fH3
std::vector<TGRSIMap<std::string, TH3*> > TGRSIHelper::fH3 protected inherited
Definition at line 50 of file TGRSIHelper.h.
Referenced by TimeWalkHelper::CreateHistograms(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fLists
std::vector<std::shared_ptr<std::map<std::string, TList> > > TGRSIHelper::fLists protected inherited
Definition at line 47 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes(), TGRSIHelper::Finalize(), TGRSIHelper::GetResultPtr(), and TGRSIHelper::Setup().
fObject
std::vector<TGRSIMap<std::string, TObject*> > TGRSIHelper::fObject protected inherited
Definition at line 54 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::CreateHistograms(), and TGRSIHelper::Setup().
fPpg
TPPG* TGRSIHelper::fPpg {nullptr} protected inherited
Definition at line 56 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Ppg().
fPrefix
std::string TGRSIHelper::fPrefix {"TGRSIHelper"} protected inherited
Definition at line 59 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Prefix(), TGRSIHelper::Prefix(), and TGRSIHelper::Prefix().
fRunInfo
TRunInfo* TGRSIHelper::fRunInfo {nullptr} protected inherited
Definition at line 57 of file TGRSIHelper.h.
Referenced by TGRSIHelper::RunInfo().
fSizeLimit
int TGRSIHelper::fSizeLimit = 1073741822 static constexpr private inherited
! 1 GiB size limit for objects in ROOT
Definition at line 62 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes().
fSym
std::vector<TGRSIMap<std::string, GHSym*> > TGRSIHelper::fSym protected inherited
Definition at line 51 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fTree
std::vector<TGRSIMap<std::string, TTree*> > TGRSIHelper::fTree protected inherited
Definition at line 53 of file TGRSIHelper.h.
Referenced by ExampleTreeHelper::CreateHistograms(), ExampleTreeHelper::Exec(), and TGRSIHelper::Setup().
fUserSettings
TUserSettings* TGRSIHelper::fUserSettings {nullptr} protected inherited
Definition at line 58 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper::ComptonPolarimetryHelper(), and TGRSIHelper::UserSettings().