GRSISort: TFragment Class Reference
TFragment Class Reference
Sorting
This Class contains all of the information in an event fragment
Definition at line 29 of file TFragment.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TFragment ()
TFragment (const TFragment &)
~TFragment ()
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &x)
virtual void AppendTimeStamp (const Long64_t &x)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
TObject * Clone (const char *name="") const override
void Copy (TObject &) const override
virtual void Copy (TObject &, bool copywave) const
virtual void CopyWave (TObject &) const
Int_t Get4GCfd () const
UShort_t GetAcceptedChannelId () const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
Int_t GetCcLong () const
Int_t GetCcShort () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
UInt_t GetChannelId () const
virtual Short_t GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
ULong64_t GetCycleNumber ()
Long64_t GetCycleTimeStamp () const
Int_t GetDaqId () const
time_t GetDaqTimeStamp () const
UShort_t GetDeadTime () const
virtual Int_t GetDetector () const
UShort_t GetDetectorType () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Long64_t GetEntryNumber () const
Int_t GetFragmentId () const
virtual Short_t GetKValue () const
UShort_t GetModuleType () const
const char * GetName () const override
Int_t GetNetworkPacketNumber () const
size_t GetNumberOfCharges ()
UShort_t GetNumberOfFilters () const
Int_t GetNumberOfHits () const
Short_t GetNumberOfPileups () const
UShort_t GetNumberOfWords () const
virtual TVector3 GetPosition () const
virtual TVector3 GetPosition (Double_t) const
TPPG * GetPPG ()
EPpgPattern GetPPGStatus () const
virtual Int_t GetSegment () const
Int_t GetSharcMesyBoard () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
ULong64_t GetTimeInCycle ()
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
Int_t GetTriggerBitPattern () const
Long_t GetTriggerId (size_t iter=0) const
double GetTZero () const
const std::vector< Short_t > * GetWaveform () const
Int_t GetZc () const
virtual bool HasWave () const
bool IsDetector (const char *prefix, Option_t *opt="CA") const
bool operator< (const TDetectorHit &rhs) const
bool operator< (const TFragment &rhs) const
TFragment & operator= (const TFragment &)=default
bool operator> (const TFragment &rhs) const
void Print (Option_t *opt="") const override
virtual void Print (std::ostream &out) const override
void SetAcceptedChannelId (UShort_t value)
void SetAddress (const UInt_t &temp_address)
void SetCcLong (Int_t value)
void SetCcShort (Int_t value)
virtual void SetCfd (const Float_t &x)
virtual void SetCfd (const Int_t &x)
virtual void SetCfd (const uint32_t &x)
void SetChannelId (UInt_t value)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
void SetDaqId (Int_t value)
void SetDaqTimeStamp (time_t value)
void SetDeadTime (UShort_t value)
void SetDetectorType (UShort_t value)
Double_t SetEnergy (const double &en) const
void SetEntryNumber ()
void SetFragmentId (Int_t value)
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
void SetModuleType (UShort_t value)
void SetNetworkPacketNumber (Int_t value)
void SetNumberOfFilters (UShort_t)
void SetNumberOfPileups (Short_t value)
void SetNumberOfWords (UShort_t value)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &x)
void SetTriggerBitPattern (Int_t value)
void SetTriggerId (Long_t value)
void SetWaveform (const std::vector< Short_t > &x)
void SetZc (Int_t value)
bool TestHitBit (EBitFlag flag) const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Protected Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
Float_t fCharge {0.}
Short_t fKValue {0}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Protected Attributes
static TVector3 fBeamDirection
Private Attributes
UInt_t fAcceptedChannelId
Int_t fCcLong
Int_t fCcShort
TChannel * fChannel {nullptr}
UInt_t fChannelId
Long64_t fCycleTimeStamp {0}
Int_t fDaqId
time_t fDaqTimeStamp
UShort_t fDeadTime
UShort_t fDetectorType
Double_t fEnergy {0.}
Long64_t fEntryNumber
Int_t fFragmentId
UShort_t fModuleType
Int_t fNetworkPacketNumber
Short_t fNumberOfPileups
UShort_t fNumberOfWords
TPPG * fPPG
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Int_t fTriggerBitPattern
std::vector< Long_t > fTriggerId
Int_t fZc
Static Private Attributes
static Long64_t fNumberOfFragments = 0
#include <TFragment.h>
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 52 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 79 of file TDetectorHit.h.
Constructor & Destructor Documentation
TFragment() [1/2]
TFragment::TFragment ()
Default constructor
Definition at line 15 of file TFragment.cxx.
References Clear().
Referenced by Clone().
TFragment() [2/2]
TFragment::TFragment (const TFragment & rhs)
Copy constructor
Definition at line 24 of file TFragment.cxx.
References fAcceptedChannelId, fCcLong, fCcShort, fChannelId, fDaqId, fDaqTimeStamp, fDeadTime, fDetectorType, fFragmentId, fModuleType, fNetworkPacketNumber, fNumberOfPileups, fNumberOfWords, fPPG, fTriggerBitPattern, fTriggerId, and fZc.
~TFragment()
TFragment::~TFragment ()
Default destructor does nothing right now
Definition at line 51 of file TFragment.cxx.
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Definition at line 188 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & x) inline inherited
!
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 123 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 149 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), and TDetectorHit::Print().
Clear()
void TFragment::Clear (Option_t * opt = "") override
Clears all fields of the TFragment
Definition at line 56 of file TFragment.cxx.
References TDetectorHit::Clear(), fAcceptedChannelId, fCcLong, fCcShort, fChannelId, fDaqId, fDaqTimeStamp, fDeadTime, fDetectorType, fEntryNumber, fFragmentId, fModuleType, fNetworkPacketNumber, fNumberOfPileups, fNumberOfWords, fPPG, fTriggerBitPattern, fTriggerId, and fZc.
Referenced by TFragment(), and TBadFragment::Clear().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 180 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 175 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 100 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TDetectorHit::TDetectorHit(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
Clone()
TObject * TFragment::Clone (const char * name = "") const override
Definition at line 84 of file TFragment.cxx.
References TFragment().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 219 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TDetectorHit::Copy (TObject & rhs) const override inherited
!
Definition at line 116 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TDetectorHit::fBitFlags, TDetectorHit::fCfd, TDetectorHit::fChannel, TDetectorHit::fCharge, TDetectorHit::fCycleTimeStamp, TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::fPPGStatus, TDetectorHit::fTime, and TDetectorHit::fTimeStamp.
Referenced by TDetectorHit::TDetectorHit(), TDetector::Copy(), TDetectorHit::Copy(), and TBgoHit::Copy().
Copy() [2/2]
void TDetectorHit::Copy (TObject & rhs, bool copywave) const virtual inherited
!
Reimplemented in TBgoHit.
Definition at line 139 of file TDetectorHit.cxx.
References TDetectorHit::Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 134 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TDetectorHit::TDetectorHit(), and TDetectorHit::Copy().
Get4GCfd()
Int_t TFragment::Get4GCfd () const
Definition at line 101 of file TFragment.cxx.
References TDetectorHit::GetCfd().
GetAcceptedChannelId()
UShort_t TFragment::GetAcceptedChannelId () const inline
Definition at line 64 of file TFragment.h.
References fAcceptedChannelId.
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by Print().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TBgoHit.
Definition at line 167 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 186 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
GetCcLong()
Int_t TFragment::GetCcLong () const inline
Definition at line 65 of file TFragment.h.
References fCcLong.
GetCcShort()
Int_t TFragment::GetCcShort () const inline
Definition at line 66 of file TFragment.h.
References fCcShort.
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Definition at line 146 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by Get4GCfd(), TDetectorHit::GetTime(), and Print().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 152 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::GetName(), TDetectorHit::GetSegment(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), GetTZero(), and Print().
GetChannelId()
UInt_t TFragment::GetChannelId () const inline
Definition at line 67 of file TFragment.h.
References fChannelId.
GetChannelNumber()
Short_t TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 224 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), and ExampleFragmentSelector::FillHistograms().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 69 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), and Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 210 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TBgoHit::GetArrayNumber().
GetCycleNumber()
ULong64_t TFragment::GetCycleNumber ()
Definition at line 118 of file TFragment.cxx.
References fPPG, TSingleton< TPPG >::Get(), TPPG::GetCycleNumber(), and TDetectorHit::GetTimeStampNs().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 267 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDaqId()
Int_t TFragment::GetDaqId () const inline
Definition at line 72 of file TFragment.h.
References fDaqId.
GetDaqTimeStamp()
time_t TFragment::GetDaqTimeStamp () const inline
Definition at line 74 of file TFragment.h.
References fDaqTimeStamp.
GetDeadTime()
UShort_t TFragment::GetDeadTime () const inline
Definition at line 70 of file TFragment.h.
References fDeadTime.
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 192 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by TDetectorHit::GetArrayNumber(), and TBgoHit::GetArrayNumber().
GetDetectorType()
UShort_t TFragment::GetDetectorType () const inline
Definition at line 71 of file TFragment.h.
References fDetectorType.
Referenced by GriffinKValueHelper::Exec(), and GriffinKValueSelector::FillHistograms().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Definition at line 84 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by TDetectorHit::CompareEnergy(), ExampleFragmentHelper::Exec(), GriffinKValueHelper::Exec(), ExampleFragmentSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TDetectorHit::GetTime(), GetTZero(), and TDetectorHit::operator<().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 107 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetEntryNumber()
Long64_t TFragment::GetEntryNumber () const inline
Definition at line 68 of file TFragment.h.
References fEntryNumber.
GetFragmentId()
Int_t TFragment::GetFragmentId () const inline
Definition at line 73 of file TFragment.h.
References fFragmentId.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 150 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by GriffinKValueHelper::Exec(), and GriffinKValueSelector::FillHistograms().
GetModuleType()
UShort_t TFragment::GetModuleType () const inline
Definition at line 69 of file TFragment.h.
References fModuleType.
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 166 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by IsDetector(), and TDetectorHit::Print().
GetNetworkPacketNumber()
Int_t TFragment::GetNetworkPacketNumber () const inline
Definition at line 75 of file TFragment.h.
References fNetworkPacketNumber.
GetNumberOfCharges()
size_t TFragment::GetNumberOfCharges () inline
Definition at line 96 of file TFragment.h.
GetNumberOfFilters()
UShort_t TFragment::GetNumberOfFilters () const inline
Definition at line 76 of file TFragment.h.
References fNumberOfWords.
GetNumberOfHits()
Int_t TFragment::GetNumberOfHits () const inline
Definition at line 77 of file TFragment.h.
GetNumberOfPileups()
Short_t TFragment::GetNumberOfPileups () const inline
Definition at line 78 of file TFragment.h.
References fNumberOfPileups.
Referenced by GriffinKValueHelper::Exec(), and GriffinKValueSelector::FillHistograms().
GetNumberOfWords()
UShort_t TFragment::GetNumberOfWords () const inline
Definition at line 79 of file TFragment.h.
References fNumberOfWords.
GetPosition() [1/2]
virtual TVector3 TDetectorHit::GetPosition () const inline virtual inherited
!
Definition at line 139 of file TDetectorHit.h.
GetPosition() [2/2]
virtual TVector3 TDetectorHit::GetPosition (Double_t) const inline virtual inherited
!
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::GetPosition().
Referenced by TDetectorHit::GetPosition().
GetPPG()
TPPG * TFragment::GetPPG ()
Definition at line 129 of file TFragment.cxx.
References fPPG.
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 251 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 201 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by TBgoHit::GetArrayNumber().
GetSharcMesyBoard()
Int_t TFragment::GetSharcMesyBoard () const
Definition at line 219 of file TFragment.cxx.
References TDetectorHit::fAddress.
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Definition at line 56 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TDetectorHit::GetTimeSinceTapeMove(), and TDetectorHit::Print().
GetTimeInCycle()
ULong64_t TFragment::GetTimeInCycle ()
Definition at line 106 of file TFragment.cxx.
References fPPG, TSingleton< TPPG >::Get(), TPPG::GetTimeInCycle(), and TDetectorHit::GetTimeStampNs().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 283 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 142 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), operator<(), operator>(), TDetectorHit::Print(), and Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 233 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), and TDetectorHit::Print().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 242 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetTriggerBitPattern()
Int_t TFragment::GetTriggerBitPattern () const inline
Definition at line 80 of file TFragment.h.
References fTriggerBitPattern.
GetTriggerId()
Long_t TFragment::GetTriggerId (size_t iter = 0) const inline
Definition at line 81 of file TFragment.h.
References fTriggerId.
GetTZero()
double TFragment::GetTZero () const
Definition at line 92 of file TFragment.cxx.
References TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), and TChannel::GetTZero().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 151 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TPulseAnalyzer::SetData().
GetZc()
Int_t TFragment::GetZc () const inline
Definition at line 88 of file TFragment.h.
References fZc.
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 107 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by Print(), and TPulseAnalyzer::SetData().
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 195 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsDetector()
bool TFragment::IsDetector (const char * prefix, Option_t * opt = "CA") const
Definition at line 170 of file TFragment.cxx.
References TDetectorHit::GetName().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 194 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 197 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 196 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<() [1/2]
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 93 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
operator<() [2/2]
bool TFragment::operator< (const TFragment & rhs) const inline
Definition at line 109 of file TFragment.h.
References TDetectorHit::GetTimeStamp().
operator=()
TFragment & TFragment::operator= (const TFragment &) default
Referenced by TBadFragment::operator=().
operator>()
bool TFragment::operator> (const TFragment & rhs) const inline
Definition at line 110 of file TFragment.h.
References TDetectorHit::GetTimeStamp().
Print() [1/2]
void TFragment::Print (Option_t * opt = "") const override
Prints out all fields of the TFragment
Definition at line 137 of file TFragment.cxx.
References Print().
Referenced by TBadFragment::Print(), and Print().
Print() [2/2]
void TFragment::Print (std::ostream & out) const override virtual
Print fragment to stream out in a thread-safe way
Reimplemented from TDetectorHit.
Definition at line 143 of file TFragment.cxx.
References fDaqId, fDaqTimeStamp, fFragmentId, fNetworkPacketNumber, fTriggerBitPattern, fTriggerId, fZc, TDetectorHit::GetAddress(), TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetCharge(), TChannel::GetNumber(), TDetectorHit::GetTimeStamp(), and TDetectorHit::HasWave().
SetAcceptedChannelId()
void TFragment::SetAcceptedChannelId (UShort_t value) inline
Definition at line 39 of file TFragment.h.
References fAcceptedChannelId.
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fAddress.
SetCcLong()
void TFragment::SetCcLong (Int_t value) inline
Definition at line 40 of file TFragment.h.
References fCcLong.
SetCcShort()
void TFragment::SetCcShort (Int_t value) inline
Definition at line 41 of file TFragment.h.
References fCcShort.
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & x) inline virtual inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & x) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetChannelId()
void TFragment::SetChannelId (UInt_t value) inline
Definition at line 42 of file TFragment.h.
References fChannelId.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetDaqId()
void TFragment::SetDaqId (Int_t value) inline
Definition at line 47 of file TFragment.h.
References fDaqId.
SetDaqTimeStamp()
void TFragment::SetDaqTimeStamp (time_t value) inline
Definition at line 49 of file TFragment.h.
References fDaqTimeStamp.
SetDeadTime()
void TFragment::SetDeadTime (UShort_t value) inline
Definition at line 44 of file TFragment.h.
References fDeadTime.
SetDetectorType()
void TFragment::SetDetectorType (UShort_t value) inline
Definition at line 45 of file TFragment.h.
References fDetectorType.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & en) const inline inherited
Definition at line 125 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TDetectorHit::GetEnergy().
SetEntryNumber()
void TFragment::SetEntryNumber () inline
Definition at line 46 of file TFragment.h.
References fEntryNumber, and fNumberOfFragments.
Referenced by TFragmentChainLoop::Iteration().
SetFragmentId()
void TFragment::SetFragmentId (Int_t value) inline
Definition at line 48 of file TFragment.h.
References fFragmentId.
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 290 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), and TDetectorHit::SetTime().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fKValue.
SetModuleType()
void TFragment::SetModuleType (UShort_t value) inline
Definition at line 43 of file TFragment.h.
References fModuleType.
SetNetworkPacketNumber()
void TFragment::SetNetworkPacketNumber (Int_t value) inline
Definition at line 50 of file TFragment.h.
References fNetworkPacketNumber.
SetNumberOfFilters()
void TFragment::SetNumberOfFilters (UShort_t) inline
Definition at line 51 of file TFragment.h.
SetNumberOfPileups()
void TFragment::SetNumberOfPileups (Short_t value) inline
Definition at line 56 of file TFragment.h.
References fNumberOfPileups.
SetNumberOfWords()
void TFragment::SetNumberOfWords (UShort_t value) inline
Definition at line 57 of file TFragment.h.
References fNumberOfWords.
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 131 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TDetectorHit::GetTime().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & x) inline virtual inherited
!
Definition at line 122 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
SetTriggerBitPattern()
void TFragment::SetTriggerBitPattern (Int_t value) inline
Definition at line 58 of file TFragment.h.
References fTriggerBitPattern.
SetTriggerId()
void TFragment::SetTriggerId (Long_t value) inline
Definition at line 59 of file TFragment.h.
References fTriggerId.
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & x) inline inherited
!
Definition at line 120 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
SetZc()
void TFragment::SetZc (Int_t value) inline
Definition at line 60 of file TFragment.h.
References fZc.
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 201 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy().
Member Data Documentation
fAcceptedChannelId
UInt_t TFragment::fAcceptedChannelId private
Accepted threshold crossing counter for a channel.
Definition at line 122 of file TFragment.h.
Referenced by TFragment(), Clear(), GetAcceptedChannelId(), and SetAcceptedChannelId().
fAddress
UInt_t TDetectorHit::fAddress {0} protected inherited
address of the the channel in the DAQ.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), GetSharcMesyBoard(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static protected inherited
Definition at line 223 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable protected inherited
Definition at line 222 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TDetectorHit::SetHitBit(), and TDetectorHit::TestHitBit().
fCcLong
Int_t TFragment::fCcLong private
! Long integration over waveform tail from 4G (saved in separate branch)
Definition at line 139 of file TFragment.h.
Referenced by TFragment(), Clear(), GetCcLong(), and SetCcLong().
fCcShort
Int_t TFragment::fCcShort private
! Short integration over waveform peak from 4G (saved in separate branch)
Definition at line 138 of file TFragment.h.
Referenced by TFragment(), Clear(), GetCcShort(), and SetCcShort().
fCfd
Float_t TDetectorHit::fCfd {0} protected inherited
CFD time of the Hit.
Definition at line 207 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 217 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fChannelId
UInt_t TFragment::fChannelId private
Threshold crossing counter for a channel.
Definition at line 121 of file TFragment.h.
Referenced by TFragment(), Clear(), GetChannelId(), and SetChannelId().
fCharge
Float_t TDetectorHit::fCharge {0.} protected inherited
charge collected from the hit
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 216 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fDaqId
Int_t TFragment::fDaqId private
Daq ID.
Definition at line 117 of file TFragment.h.
Referenced by TFragment(), Clear(), GetDaqId(), Print(), and SetDaqId().
fDaqTimeStamp
time_t TFragment::fDaqTimeStamp private
Timestamp of the Daq event.
Definition at line 116 of file TFragment.h.
Referenced by TFragment(), Clear(), GetDaqTimeStamp(), Print(), and SetDaqTimeStamp().
fDeadTime
UShort_t TFragment::fDeadTime private
Added to combine Grif Fragment ////.
Deadtime from trigger
Definition at line 126 of file TFragment.h.
Referenced by TFragment(), Clear(), GetDeadTime(), and SetDeadTime().
fDetectorType
UShort_t TFragment::fDetectorType private
Detector Type (PACES,HPGe, etc.)
Definition at line 128 of file TFragment.h.
Referenced by TFragment(), Clear(), GetDetectorType(), and SetDetectorType().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fEntryNumber
Long64_t TFragment::fEntryNumber private
! Entry number in fragment tree
Definition at line 136 of file TFragment.h.
Referenced by Clear(), GetEntryNumber(), and SetEntryNumber().
fFragmentId
Int_t TFragment::fFragmentId private
Channel Trigger ID ??? not needed anymore ???
Definition at line 118 of file TFragment.h.
Referenced by TFragment(), Clear(), GetFragmentId(), Print(), and SetFragmentId().
fKValue
Short_t TDetectorHit::fKValue {0} protected inherited
integration value.
Definition at line 206 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), and TDetectorHit::SetKValue().
fModuleType
UShort_t TFragment::fModuleType private
Data Type (GRIF-16, 4G, etc.)
Definition at line 127 of file TFragment.h.
Referenced by TFragment(), Clear(), GetModuleType(), and SetModuleType().
fNetworkPacketNumber
Int_t TFragment::fNetworkPacketNumber private
Network packet number.
Definition at line 120 of file TFragment.h.
Referenced by TFragment(), Clear(), GetNetworkPacketNumber(), Print(), and SetNetworkPacketNumber().
fNumberOfFragments
Long64_t TFragment::fNumberOfFragments = 0 static private
Definition at line 142 of file TFragment.h.
Referenced by SetEntryNumber().
fNumberOfPileups
Short_t TFragment::fNumberOfPileups private
Number of piled up hits 1-3.
Definition at line 129 of file TFragment.h.
Referenced by TFragment(), Clear(), GetNumberOfPileups(), and SetNumberOfPileups().
fNumberOfWords
UShort_t TFragment::fNumberOfWords private
! Number of non-waveform words in fragment, only used for check while parsing the fragment
Definition at line 140 of file TFragment.h.
Referenced by TFragment(), Clear(), GetNumberOfFilters(), GetNumberOfWords(), and SetNumberOfWords().
fPPG
TPPG* TFragment::fPPG private
! Programmable pattern generator value
Definition at line 134 of file TFragment.h.
Referenced by TFragment(), Clear(), GetCycleNumber(), GetPPG(), and GetTimeInCycle().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 214 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fTime
Double_t TDetectorHit::fTime {0.} mutable protected inherited
! Calibrated Time of the hit
Definition at line 210 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} protected inherited
Timestamp given to hit in ns.
Definition at line 208 of file TDetectorHit.h.
Referenced by TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), and TDetectorHit::SetTimeStamp().
fTriggerBitPattern
Int_t TFragment::fTriggerBitPattern private
PrimaryFilterPattern in Griffin DAQ.
Definition at line 119 of file TFragment.h.
Referenced by TFragment(), Clear(), GetTriggerBitPattern(), Print(), and SetTriggerBitPattern().
fTriggerId
std::vector<Long_t> TFragment::fTriggerId private
PrimaryFilterID in Griffin DAQ.
Definition at line 131 of file TFragment.h.
Referenced by TFragment(), Clear(), GetTriggerId(), Print(), and SetTriggerId().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform protected inherited
Definition at line 209 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), and TDetectorHit::SetWaveform().
fZc
Int_t TFragment::fZc private
! Zero-crossing value from 4G (saved in separate branch)
Definition at line 137 of file TFragment.h.
Referenced by TFragment(), Clear(), GetZc(), Print(), and SetZc().
GRSISort () Reference Guide Generated on Mon May 13 2024 16:00:06.