GRSISort: THtmlCreator Class Reference
THtmlCreator Class Reference
Detailed Description
Definition at line 34 of file html_generator.C.
Public Member Functions
THtmlCreator ()
~THtmlCreator ()
void AddRootSourcePath ()
void AddSourcePath (std::string newpath)
void Convert ()
void DontDoMuch ()
void MakeDocForAllClasses ()
void RunAll ()
void SetEtcDir (TString name)
void SetProductName (const char *name)
Protected Member Functions
THtml * GetHtml ()
Private Member Functions
ClassDef (THtmlCreator, 0)
Private Attributes
THtml * fHtml
std::stringstream fpath
Constructor & Destructor Documentation
THtmlCreator()
THtmlCreator::THtmlCreator () inline
Definition at line 36 of file html_generator.C.
~THtmlCreator()
THtmlCreator::~THtmlCreator () inline
Definition at line 40 of file html_generator.C.
References fHtml.
Member Function Documentation
AddRootSourcePath()
void THtmlCreator::AddRootSourcePath () inline
Definition at line 98 of file html_generator.C.
References fpath.
Referenced by html_generator().
AddSourcePath()
void THtmlCreator::AddSourcePath (std::string newpath) inline
Definition at line 93 of file html_generator.C.
References fpath.
Referenced by html_generator().
ClassDef()
THtmlCreator::ClassDef (THtmlCreator , 0) private
Convert()
void THtmlCreator::Convert () inline
Definition at line 47 of file html_generator.C.
References GetHtml().
Referenced by RunAll().
DontDoMuch()
void THtmlCreator::DontDoMuch () inline
Definition at line 45 of file html_generator.C.
GetHtml()
THtml * THtmlCreator::GetHtml () inline protected
Definition at line 103 of file html_generator.C.
References fHtml.
Referenced by Convert(), MakeDocForAllClasses(), SetEtcDir(), and SetProductName().
MakeDocForAllClasses()
void THtmlCreator::MakeDocForAllClasses () inline
Definition at line 57 of file html_generator.C.
References fpath, and GetHtml().
Referenced by RunAll().
RunAll()
void THtmlCreator::RunAll () inline
Definition at line 74 of file html_generator.C.
References Convert(), and MakeDocForAllClasses().
Referenced by html_generator().
SetEtcDir()
void THtmlCreator::SetEtcDir (TString name) inline
Definition at line 86 of file html_generator.C.
References GetHtml().
Referenced by html_generator().
SetProductName()
void THtmlCreator::SetProductName (const char * name) inline
Definition at line 80 of file html_generator.C.
References GetHtml().
Referenced by html_generator().
Member Data Documentation
fHtml
THtml* THtmlCreator::fHtml private
Definition at line 111 of file html_generator.C.
Referenced by ~THtmlCreator(), and GetHtml().
fpath
std::stringstream THtmlCreator::fpath private
Definition at line 112 of file html_generator.C.
Referenced by AddRootSourcePath(), AddSourcePath(), and MakeDocForAllClasses().