GRSISort: ArgParseConfigT< T > Class Template Reference
ArgParseConfigT< T > Class Template Reference
Detailed Description
template<typename T>
class ArgParseConfigT< T >
Definition at line 197 of file ArgParser.h.
Public Member Functions
ArgParseConfigT (std::string flag, T *output_location, bool firstPass)
virtual ArgParseConfig & colour (const std::string &colour)
ArgParseConfig< T > & default_value (T value) override
virtual ArgParseConfig & description (const std::string &description)
std::string flag_name () const override
bool is_present () const
bool is_required () const override
bool matches (const std::string &flag) const override
int num_arguments () const override
void parse (const std::string &name, const std::vector< std::string > &arguments, bool firstPass, bool ignore_num_arguments=false)
void parse_item (const std::vector< std::string > &arguments) override
std::string printable (int description_column, int *chars_before_desc) const override
virtual ArgParseConfig & required ()
Private Attributes
std::string fColour
std::string fDescription
bool fFirstPass
std::vector< std::string > fFlags
T * fOutput_location
bool fPresent {false}
std::vector< std::string > fRawFlags
bool fRequired {false}
Constructor & Destructor Documentation
ArgParseConfigT()
template<typename T > ArgParseConfigT< T >::ArgParseConfigT (std::string flag, T * output_location, bool firstPass) inline
Definition at line 199 of file ArgParser.h.
Member Function Documentation
colour()
template<typename T > virtual ArgParseConfig & ArgParseConfig< T >::colour (const std::string & colour) inline virtual inherited
Definition at line 117 of file ArgParser.h.
References ArgParseConfig< T >::colour(), and ArgParseConfig< T >::fColour.
Referenced by ArgParseConfig< T >::colour().
default_value()
template<typename T > ArgParseConfig< T > & ArgParseConfigT< T >::default_value (T value) inline override virtual
Implements ArgParseConfig< T >.
Definition at line 204 of file ArgParser.h.
References ArgParseConfigT< T >::fOutput_location.
description()
template<typename T > virtual ArgParseConfig & ArgParseConfig< T >::description (const std::string & description) inline virtual inherited
Definition at line 111 of file ArgParser.h.
References ArgParseConfig< T >::description(), and ArgParseConfig< T >::fDescription.
Referenced by ArgParseConfig< T >::description().
flag_name()
template<typename T > std::string ArgParseConfig< T >::flag_name () const inline override virtual inherited
Implements ArgParseItem.
Definition at line 90 of file ArgParser.h.
References ArgParseConfig< T >::fFlags.
is_present()
bool ArgParseItem::is_present () const inline inherited
Definition at line 35 of file ArgParser.h.
References ArgParseItem::fPresent.
is_required()
template<typename T > bool ArgParseConfig< T >::is_required () const inline override virtual inherited
Implements ArgParseItem.
Definition at line 129 of file ArgParser.h.
References ArgParseConfig< T >::fRequired.
matches()
template<typename T > bool ArgParseConfig< T >::matches (const std::string & flag) const inline override virtual inherited
Implements ArgParseItem.
Definition at line 101 of file ArgParser.h.
References ArgParseConfig< T >::fFlags.
num_arguments()
template<typename T > int ArgParseConfigT< T >::num_arguments () const inline override virtual
Implements ArgParseItem.
Definition at line 216 of file ArgParser.h.
parse()
void ArgParseItem::parse (const std::string & name, const std::vector< std::string > & arguments, bool firstPass, bool ignore_num_arguments = false) inline inherited
Definition at line 38 of file ArgParser.h.
References ArgParseItem::fFirstPass, ArgParseItem::fPresent, ArgParseItem::num_arguments(), and ArgParseItem::parse_item().
Referenced by ArgParser::handle_default_option(), ArgParser::handle_long_flag(), ArgParser::handle_short_flag(), and ArgParser::parse_file().
parse_item()
template<typename T > void ArgParseConfigT< T >::parse_item (const std::vector< std::string > & arguments) inline override virtual
Implements ArgParseItem.
Definition at line 210 of file ArgParser.h.
References ArgParseConfigT< T >::fOutput_location.
printable()
template<typename T > std::string ArgParseConfig< T >::printable (int description_column, int * chars_before_desc) const inline override virtual inherited
Implements ArgParseItem.
Definition at line 133 of file ArgParser.h.
References ArgParseConfig< T >::fColour, ArgParseConfig< T >::fDescription, ArgParseConfig< T >::fFlags, ArgParseItem::num_arguments(), and RESET_COLOR.
required()
template<typename T > virtual ArgParseConfig & ArgParseConfig< T >::required () inline virtual inherited
Definition at line 123 of file ArgParser.h.
References ArgParseConfig< T >::fRequired.
Member Data Documentation
fColour
template<typename T > std::string ArgParseConfig< T >::fColour private inherited
Colour string to be use for display.
Definition at line 184 of file ArgParser.h.
Referenced by ArgParseConfig< T >::colour(), and ArgParseConfig< T >::printable().
fDescription
template<typename T > std::string ArgParseConfig< T >::fDescription private inherited
A description for display on the terminal.
Definition at line 181 of file ArgParser.h.
Referenced by ArgParseConfig< T >::description(), and ArgParseConfig< T >::printable().
fFirstPass
bool ArgParseItem::fFirstPass private inherited
Definition at line 64 of file ArgParser.h.
Referenced by ArgParseItem::parse().
fFlags
template<typename T > std::vector<std::string> ArgParseConfig< T >::fFlags private inherited
The literal flag that is searched for, including leading dashes.
Definition at line 187 of file ArgParser.h.
Referenced by ArgParseConfig< T >::ArgParseConfig(), ArgParseConfig< T >::flag_name(), ArgParseConfig< T >::matches(), and ArgParseConfig< T >::printable().
fOutput_location
template<typename T > T* ArgParseConfigT< T >::fOutput_location private
Definition at line 219 of file ArgParser.h.
Referenced by ArgParseConfigT< bool >::ArgParseConfigT(), ArgParseConfigT< T >::default_value(), ArgParseConfigT< bool >::default_value(), ArgParseConfigT< T >::parse_item(), and ArgParseConfigT< bool >::parse_item().
fPresent
bool ArgParseItem::fPresent {false} private inherited
Definition at line 63 of file ArgParser.h.
Referenced by ArgParseItem::is_present(), and ArgParseItem::parse().
fRawFlags
template<typename T > std::vector<std::string> ArgParseConfig< T >::fRawFlags private inherited
The flags without the leading dashes.
Definition at line 190 of file ArgParser.h.
Referenced by ArgParseConfig< T >::ArgParseConfig().
fRequired
template<typename T > bool ArgParseConfig< T >::fRequired {false} private inherited
Whether the flag must be supplied.
Definition at line 193 of file ArgParser.h.
Referenced by ArgParseConfig< T >::is_required(), and ArgParseConfig< T >::required().