GRSISort: TRegion Class Reference
TRegion Class Reference
Detailed Description
Definition at line 116 of file GH1D.h.
Public Member Functions
TRegion ()=default
TRegion (const TRegion &)=default
TRegion (TBox *box, ERegionType type, GH1D *parent)
TRegion (TRegion &&)=default
~TRegion ()=default
void Draw (Option_t *opt="") override
void Hide ()
TRegion & operator= (const TRegion &)=default
TRegion & operator= (TRegion &&)=default
bool Update ()
void Update (double startX, double stopX)
Private Attributes
double fHighX {0.}
double fLowX {0.}
GH1D * fParent {nullptr}
ERegionType fType {ERegionType::kDefault}
Constructor & Destructor Documentation
TRegion() [1/4]
TRegion::TRegion () default
TRegion() [2/4]
TRegion::TRegion (TBox * box, ERegionType type, GH1D * parent)
Definition at line 570 of file GH1D.cxx.
References fHighX, and fLowX.
TRegion() [3/4]
TRegion::TRegion (const TRegion &) default
TRegion() [4/4]
TRegion::TRegion (TRegion &&) default
~TRegion()
TRegion::~TRegion () default
Member Function Documentation
Draw()
void TRegion::Draw (Option_t * opt = "") override
Draw this region. Calls Update() first to update ranges and to check if we actuall want to draw this range. If Update() returns false this function will actually hide this region! Updates the pad at the end.
Definition at line 660 of file GH1D.cxx.
References fHighX, fLowX, fParent, Hide(), kQuiet, GH1D::Pad(), Update(), GH1D::UpdatePad(), and GH1D::VerboseLevel().
Referenced by GH1D::HandleEvent().
Hide()
void TRegion::Hide ()
Hide this region. Removes region from list of primitives. Does not update the pad.
Definition at line 681 of file GH1D.cxx.
References fHighX, fLowX, fParent, kBasicFlow, GH1D::Pad(), GH1D::PrintRegions(), and GH1D::VerboseLevel().
Referenced by Draw().
operator=() [1/2]
TRegion & TRegion::operator= (const TRegion &) default
operator=() [2/2]
TRegion & TRegion::operator= (TRegion &&) default
Update() [1/2]
bool TRegion::Update ()
Updates y-range of this region to match the current y-range of the frame the parent is drawn in. Also checks the x-range and adjust it to only cover the displayed range if necessary. Returns whether the region should be drawn or not. Does not update the pad itself!
Definition at line 586 of file GH1D.cxx.
References fHighX, fLowX, fParent, kBasicFlow, GH1D::Pad(), and GH1D::VerboseLevel().
Referenced by Draw(), and Update().
Update() [2/2]
void TRegion::Update (double startX, double stopX)
Depending on the starting position this function updates the left or right edge of the region to the stopping position.
Definition at line 695 of file GH1D.cxx.
References fHighX, fLowX, kBasicFlow, Update(), and GH1D::VerboseLevel().
Member Data Documentation
fHighX
double TRegion::fHighX {0.} private
Definition at line 136 of file GH1D.h.
Referenced by TRegion(), Draw(), Hide(), Update(), and Update().
fLowX
double TRegion::fLowX {0.} private
Definition at line 135 of file GH1D.h.
Referenced by TRegion(), Draw(), Hide(), Update(), and Update().
fParent
GH1D* TRegion::fParent {nullptr} private
Definition at line 133 of file GH1D.h.
Referenced by Draw(), Hide(), and Update().
fType
ERegionType TRegion::fType {ERegionType::kDefault} private
Definition at line 134 of file GH1D.h.