GRSISort: TSiLi Class Reference
TSiLi Class Reference
Detectors
Detailed Description
Definition at line 15 of file TSiLi.h.
Public Types
enum class ESiLiBits {
kAddbackSet = BIT(0) , kSiLiBit1 = BIT(1) , kSiLiBit2 = BIT(2) , kSiLiBit3 = BIT(3) ,
kSiLiBit4 = BIT(4) , kSiLiBit5 = BIT(5) , kSiLiBit6 = BIT(6) , kSiLiBit7 = BIT(7)
}
Public Member Functions
TSiLi ()
TSiLi (const TSiLi &)
TSiLi (TSiLi &&) noexcept=default
~TSiLi () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="") override
virtual void ClearTransients ()
void CoincidenceTime (double time)
void Copy (TObject &) const override
bool fAddbackCriterion (TSiLiHit *, TSiLiHit *)
bool fCoincidenceTime (TSiLiHit *, TSiLiHit *)
bool fRejectCriterion (TSiLiHit *, TSiLiHit *)
TSiLiHit * GetAddbackHit (const Int_t &i=0)
Int_t GetAddbackMultiplicity ()
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TSiLiHit * GetRejectHit (const Int_t &i=0)
Int_t GetRejectMultiplicity ()
TSiLiHit * GetSiLiHit (const Int_t &i=0) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TSiLi & operator= (const TSiLi &)
TSiLi & operator= (TSiLi &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void RejectCrosstalk (bool reject=true)
void ResetAddback ()
void UseFitCharge ()
Static Public Member Functions
static Int_t GetPin (Int_t seg)
static TVector3 GetPosition (int ring, int sector, bool smear=false)
static Int_t GetPreamp (Int_t seg)
static Int_t GetRing (Int_t seg)
static Int_t GetSector (Int_t seg)
static double GetSegmentArea (Int_t seg)
static bool MagnetShadow (Int_t seg)
static std::vector< TGraph > UpstreamShapes ()
Static Public Attributes
static double fBaseFreq = 4
static int fFitSiLiShape = 0
static bool fRejectPossibleCrosstalk = false
static double fSiLiCoincidenceTime = 200
static double fSiLiDefaultBaseline = -4300
static double fSiLiDefaultDecay = 4616.18
static double fSiLiDefaultRise = 20.90
static double fSiLiNoiseFac = 4
Private Member Functions
void AddCluster (std::vector< unsigned > &, bool=false)
Private Attributes
std::vector< TSiLiHit > fAddbackHits
std::vector< TDetectorHit * > fHits
std::vector< unsigned int > fRejectHits
TTransientBits< UChar_t > fSiLiBits
Static Private Attributes
static double fInnerDiameter = 16.
static double fOffsetPhi = -165. * TMath::Pi() / 180.
static double fOuterDiameter = 94.
static int fRingNumber = 10
static int fSectorNumber = 12
static double fTargetDistance = -117.8
Member Enumeration Documentation
ESiLiBits
enum class TSiLi::ESiLiBits strong
Enumerator
kAddbackSet
kSiLiBit1
kSiLiBit2
kSiLiBit3
kSiLiBit4
kSiLiBit5
kSiLiBit6
kSiLiBit7
Definition at line 17 of file TSiLi.h.
Constructor & Destructor Documentation
TSiLi() [1/3]
TSiLi::TSiLi ()
Definition at line 23 of file TSiLi.cxx.
References Clear().
TSiLi() [2/3]
TSiLi::TSiLi (const TSiLi & rhs)
Definition at line 35 of file TSiLi.cxx.
References Copy().
TSiLi() [3/3]
TSiLi::TSiLi (TSiLi &&) default noexcept
~TSiLi()
TSiLi::~TSiLi () override default
Member Function Documentation
AddCluster()
void TSiLi::AddCluster (std::vector< unsigned > & cluster, bool ContainsReject = false) private
Definition at line 269 of file TSiLi.cxx.
References fAddbackHits, fRejectHits, fRejectPossibleCrosstalk, TSiLiHit::GetEnergy(), TDetector::GetHit(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), GetSiLiHit(), and s.
Referenced by GetAddbackMultiplicity().
AddFragment()
void TSiLi::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 66 of file TSiLi.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TEmma::BuildHits(), TSharc::BuildHits(), and TSharc2::BuildHits().
BuildHits()
void TSiLi::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 38 of file TSiLi.h.
Clear()
void TSiLi::Clear (Option_t * opt = "") override
Definition at line 40 of file TSiLi.cxx.
References TTransientBits< T >::Clear(), TDetector::Clear(), fAddbackHits, and fSiLiBits.
Referenced by TSiLi().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
CoincidenceTime()
void TSiLi::CoincidenceTime (double time) inline
Definition at line 65 of file TSiLi.h.
References fSiLiCoincidenceTime, and ResetAddback().
Copy()
void TSiLi::Copy (TObject & rhs) const override
Definition at line 28 of file TSiLi.cxx.
References TDetector::Copy(), fAddbackHits, and fSiLiBits.
Referenced by TSiLi(), and operator=().
fAddbackCriterion()
bool TSiLi::fAddbackCriterion (TSiLiHit * one, TSiLiHit * two)
Definition at line 225 of file TSiLi.cxx.
References fCoincidenceTime(), TSiLiHit::GetEnergy(), TSiLiHit::GetRing(), and TSiLiHit::GetSector().
Referenced by GetAddbackMultiplicity().
fCoincidenceTime()
bool TSiLi::fCoincidenceTime (TSiLiHit * one, TSiLiHit * two)
Definition at line 257 of file TSiLi.cxx.
References fSiLiCoincidenceTime, TDetectorHit::GetTime(), and TSiLiHit::GetTimeFit().
Referenced by fAddbackCriterion(), and fRejectCriterion().
fRejectCriterion()
bool TSiLi::fRejectCriterion (TSiLiHit * one, TSiLiHit * two)
Definition at line 245 of file TSiLi.cxx.
References fCoincidenceTime(), TSiLiHit::GetPin(), and TSiLiHit::GetPreamp().
Referenced by GetAddbackMultiplicity().
GetAddbackHit()
TSiLiHit * TSiLi::GetAddbackHit (const Int_t & i = 0)
Get the ith addback hit. This function calls GetAddbackMultiplicity to check the range of the index. This automatically calculates all addback hits if they haven't been calculated before.
Definition at line 110 of file TSiLi.cxx.
References fAddbackHits, and GetAddbackMultiplicity().
GetAddbackMultiplicity()
Int_t TSiLi::GetAddbackMultiplicity ()
Definition at line 158 of file TSiLi.cxx.
References AddCluster(), fAddbackCriterion(), fAddbackHits, fRejectCriterion(), fRejectHits, fSiLiBits, TDetector::GetMultiplicity(), GetSiLiHit(), kAddbackSet, TTransientBits< T >::SetBit(), and TTransientBits< T >::TestBit().
Referenced by GetAddbackHit(), and GetRejectMultiplicity().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetPin()
static Int_t TSiLi::GetPin (Int_t seg) inline static
Definition at line 89 of file TSiLi.h.
References GetRing(), and GetSector().
Referenced by TSiLiHit::GetPin().
GetPosition()
TVector3 TSiLi::GetPosition (int ring, int sector, bool smear = false) static
Definition at line 77 of file TSiLi.cxx.
References fInnerDiameter, fOffsetPhi, fOuterDiameter, fRingNumber, fSectorNumber, and fTargetDistance.
Referenced by TSiLiHit::GetPosition().
GetPreamp()
static Int_t TSiLi::GetPreamp (Int_t seg) inline static
Definition at line 88 of file TSiLi.h.
References GetRing(), and GetSector().
Referenced by TSiLiHit::GetPreamp().
GetRejectHit()
TSiLiHit * TSiLi::GetRejectHit (const Int_t & i = 0)
Definition at line 122 of file TSiLi.cxx.
References fRejectHits, GetRejectMultiplicity(), and GetSiLiHit().
GetRejectMultiplicity()
Int_t TSiLi::GetRejectMultiplicity ()
Definition at line 132 of file TSiLi.cxx.
References fRejectHits, and GetAddbackMultiplicity().
Referenced by GetRejectHit().
GetRing()
static Int_t TSiLi::GetRing (Int_t seg) inline static
Definition at line 86 of file TSiLi.h.
Referenced by GetPin(), GetPreamp(), TSiLiHit::GetRing(), and GetSegmentArea().
GetSector()
static Int_t TSiLi::GetSector (Int_t seg) inline static
Definition at line 87 of file TSiLi.h.
Referenced by GetPin(), GetPreamp(), and TSiLiHit::GetSector().
GetSegmentArea()
double TSiLi::GetSegmentArea (Int_t seg) static
Definition at line 100 of file TSiLi.cxx.
References fInnerDiameter, fOuterDiameter, fRingNumber, fSectorNumber, and GetRing().
GetSiLiHit()
TSiLiHit * TSiLi::GetSiLiHit (const Int_t & i = 0) const inline
Definition at line 45 of file TSiLi.h.
References TDetector::GetHit().
Referenced by AddCluster(), GetAddbackMultiplicity(), and GetRejectHit().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), TSharc2::GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
MagnetShadow()
static bool TSiLi::MagnetShadow (Int_t seg) inline static
Definition at line 102 of file TSiLi.h.
Referenced by TSiLiHit::MagnetShadow().
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TSiLi & TSiLi::operator= (const TSiLi & rhs)
Definition at line 47 of file TSiLi.cxx.
References Copy().
operator=() [2/2]
TSiLi & TSiLi::operator= (TSiLi &&) default noexcept
Print() [1/2]
void TSiLi::Print (Option_t * opt = "") const override
Definition at line 53 of file TSiLi.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TSiLi::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 58 of file TSiLi.cxx.
References fAddbackHits, and TDetector::GetMultiplicity().
RejectCrosstalk()
void TSiLi::RejectCrosstalk (bool reject = true) inline
Definition at line 71 of file TSiLi.h.
References fRejectPossibleCrosstalk, and ResetAddback().
ResetAddback()
void TSiLi::ResetAddback () inline
Definition at line 52 of file TSiLi.h.
References fAddbackHits, fSiLiBits, kAddbackSet, and TTransientBits< T >::SetBit().
Referenced by CoincidenceTime(), and RejectCrosstalk().
UpstreamShapes()
std::vector< TGraph > TSiLi::UpstreamShapes () static
Definition at line 351 of file TSiLi.cxx.
References fInnerDiameter, fOffsetPhi, fOuterDiameter, fRingNumber, and fSectorNumber.
UseFitCharge()
void TSiLi::UseFitCharge () inline
Definition at line 58 of file TSiLi.h.
References TDetector::Hits(), and UseFitCharge().
Referenced by UseFitCharge().
Member Data Documentation
fAddbackHits
std::vector<TSiLiHit> TSiLi::fAddbackHits private
!
Definition at line 119 of file TSiLi.h.
Referenced by AddCluster(), Clear(), Copy(), GetAddbackHit(), GetAddbackMultiplicity(), Print(), and ResetAddback().
fBaseFreq
double TSiLi::fBaseFreq = 4 static
!
Definition at line 116 of file TSiLi.h.
Referenced by TSiLiHit::FitPulseAnalyzer().
fFitSiLiShape
int TSiLi::fFitSiLiShape = 0 static
!
Definition at line 115 of file TSiLi.h.
Referenced by TSiLiHit::SetWavefit().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fInnerDiameter
double TSiLi::fInnerDiameter = 16. static private
!
Definition at line 131 of file TSiLi.h.
Referenced by GetPosition(), GetSegmentArea(), and UpstreamShapes().
fOffsetPhi
double TSiLi::fOffsetPhi = -165. * TMath::Pi() / 180. static private
!
Definition at line 129 of file TSiLi.h.
Referenced by GetPosition(), and UpstreamShapes().
fOuterDiameter
double TSiLi::fOuterDiameter = 94. static private
!
Definition at line 130 of file TSiLi.h.
Referenced by GetPosition(), GetSegmentArea(), and UpstreamShapes().
fRejectHits
std::vector<unsigned int> TSiLi::fRejectHits private
!
Definition at line 120 of file TSiLi.h.
Referenced by AddCluster(), GetAddbackMultiplicity(), GetRejectHit(), and GetRejectMultiplicity().
fRejectPossibleCrosstalk
bool TSiLi::fRejectPossibleCrosstalk = false static
!
Definition at line 136 of file TSiLi.h.
Referenced by AddCluster(), and RejectCrosstalk().
fRingNumber
int TSiLi::fRingNumber = 10 static private
for geometery
!
Definition at line 127 of file TSiLi.h.
Referenced by GetPosition(), GetSegmentArea(), and UpstreamShapes().
fSectorNumber
int TSiLi::fSectorNumber = 12 static private
!
Definition at line 128 of file TSiLi.h.
Referenced by GetPosition(), GetSegmentArea(), and UpstreamShapes().
fSiLiBits
TTransientBits<UChar_t> TSiLi::fSiLiBits private
Definition at line 122 of file TSiLi.h.
Referenced by Clear(), Copy(), GetAddbackMultiplicity(), and ResetAddback().
fSiLiCoincidenceTime
double TSiLi::fSiLiCoincidenceTime = 200 static
!
Definition at line 135 of file TSiLi.h.
Referenced by CoincidenceTime(), and fCoincidenceTime().
fSiLiDefaultBaseline
double TSiLi::fSiLiDefaultBaseline = -4300 static
Definition at line 84 of file TSiLi.h.
Referenced by TSiLiHit::FitPulseAnalyzer().
fSiLiDefaultDecay
double TSiLi::fSiLiDefaultDecay = 4616.18 static
Definition at line 82 of file TSiLi.h.
Referenced by TSiLiHit::FitPulseAnalyzer().
fSiLiDefaultRise
double TSiLi::fSiLiDefaultRise = 20.90 static
Definition at line 83 of file TSiLi.h.
Referenced by TSiLiHit::FitPulseAnalyzer().
fSiLiNoiseFac
double TSiLi::fSiLiNoiseFac = 4 static
Definition at line 81 of file TSiLi.h.
Referenced by TSiLiHit::FitFrag().
fTargetDistance
double TSiLi::fTargetDistance = -117.8 static private
!
Definition at line 132 of file TSiLi.h.
Referenced by GetPosition().