GRSISort: TMultiPeak Class Reference
TMultiPeak Class Reference
Fitting & Analysis
Detailed Description
This Class is used to represent fitted data that is Gaussian like in nature (ie centroid and area).
Definition at line 32 of file TMultiPeak.h.
Public Member Functions
TMultiPeak ()
TMultiPeak (const TMultiPeak &copy)
TMultiPeak (Double_t xlow, Double_t xhigh, const std::vector< Double_t > &centroids, Option_t *type="gsc")
TMultiPeak (TMultiPeak &&) noexcept=default
~TMultiPeak ()
Bool_t AddToGlobalList (Bool_t yes=kTRUE) override
TF1 * Background () const
void Clear (Option_t *opt="") override
virtual void ClearParameters (Option_t *opt="")
void Copy (TObject &obj) const override
virtual void CopyParameters (TF1 *copy) const
void DrawPeaks ()
Bool_t Fit (TH1 *fithist, Option_t *opt="")
virtual TH1 * GetHist () const
TPeak * GetPeak (UInt_t idx)
TPeak * GetPeakClosestTo (Double_t energy)
bool InitParams (TH1 *fithist) override
Bool_t IsGoodFit () const
TMultiPeak & operator= (const TMultiPeak &)=default
TMultiPeak & operator= (TMultiPeak &&) noexcept=default
void Print (Option_t *opt="") const override
virtual void SetHist (TH1 *hist)
void SortPeaks (Bool_t(*SortFunction)(const TPeak *, const TPeak *)=TPeak::CompareEnergy)
Static Public Member Functions
static Bool_t AddToGlobalList (TF1 *func, Bool_t yes=kTRUE)
static const char * GetDefaultFitType ()
static bool GetLogLikelihoodFlag ()
static void SetDefaultFitType (const char *fitType)
static void SetLogLikelihoodFlag (bool flag)
Protected Member Functions
void GoodFit (Bool_t flag=true)
void InitNames ()
Bool_t IsInitialized () const
void SetInitialized (Bool_t flag=true)
Private Member Functions
Double_t MultiPhotoPeakBG (Double_t *dim, Double_t *par)
Double_t MultiStepBG (Double_t *dim, Double_t *par)
Double_t SinglePeakBG (Double_t *dim, Double_t *par)
Private Attributes
TF1 * fBackground {nullptr}
Bool_t fGoodFitFlag {false}
TRef fHist
Bool_t fInitFlag {false}
std::vector< TPeak * > fPeakVec
Static Private Attributes
static TString fDefaultFitType
static bool fLogLikelihoodFlag = false
Constructor & Destructor Documentation
~TMultiPeak()
TMultiPeak::~TMultiPeak ()
Definition at line 60 of file TMultiPeak.cxx.
References fBackground, and fPeakVec.
TMultiPeak() [1/4]
TMultiPeak::TMultiPeak (Double_t xlow, Double_t xhigh, const std::vector< Double_t > & centroids, Option_t * type = "gsc")
Definition at line 11 of file TMultiPeak.cxx.
References TGRSIFit::AddToGlobalList(), Clear(), fBackground, fPeakVec, InitNames(), MultiStepBG(), and SortPeaks().
TMultiPeak() [2/4]
TMultiPeak::TMultiPeak (const TMultiPeak & copy)
Definition at line 93 of file TMultiPeak.cxx.
References Copy().
TMultiPeak() [3/4]
TMultiPeak::TMultiPeak (TMultiPeak &&) default noexcept
TMultiPeak() [4/4]
TMultiPeak::TMultiPeak ()
Definition at line 48 of file TMultiPeak.cxx.
References TGRSIFit::AddToGlobalList(), fBackground, InitNames(), and MultiStepBG().
Referenced by Fit().
Member Function Documentation
AddToGlobalList() [1/2]
Bool_t TGRSIFit::AddToGlobalList (Bool_t yes = kTRUE) override inherited
Definition at line 62 of file TGRSIFit.cxx.
Referenced by TMultiPeak(), TMultiPeak(), TPeak::TPeak(), TPeak::TPeak(), TGRSIFit::~TGRSIFit(), and Copy().
AddToGlobalList() [2/2]
Bool_t TGRSIFit::AddToGlobalList (TF1 * func, Bool_t yes = kTRUE) static inherited
Definition at line 90 of file TGRSIFit.cxx.
Background()
TF1 * TMultiPeak::Background () const inline
Definition at line 51 of file TMultiPeak.h.
References fBackground.
Clear()
void TMultiPeak::Clear (Option_t * opt = "") override
Definition at line 330 of file TMultiPeak.cxx.
References TGRSIFit::Clear(), and fPeakVec.
Referenced by TMultiPeak().
ClearParameters()
void TGRSIFit::ClearParameters (Option_t * opt = "") virtual inherited
Definition at line 43 of file TGRSIFit.cxx.
Copy()
void TMultiPeak::Copy (TObject & obj) const override
Definition at line 98 of file TMultiPeak.cxx.
References TGRSIFit::AddToGlobalList(), TGRSIFit::Copy(), fBackground, and fPeakVec.
Referenced by TMultiPeak().
CopyParameters()
void TGRSIFit::CopyParameters (TF1 * copy) const virtual inherited
Definition at line 50 of file TGRSIFit.cxx.
Referenced by Fit().
DrawPeaks()
void TMultiPeak::DrawPeaks ()
Definition at line 439 of file TMultiPeak.cxx.
References fPeakVec, and SinglePeakBG().
Fit()
Bool_t TMultiPeak::Fit (TH1 * fithist, Option_t * opt = "")
Definition at line 179 of file TMultiPeak.cxx.
References TMultiPeak(), TGRSIFit::CopyParameters(), fBackground, fPeakVec, TPeak::GetArea(), TPeak::GetAreaErr(), TGRSIFit::GetHist(), GetLogLikelihoodFlag(), InitParams(), TGRSIFit::IsInitialized(), TPeak::SetArea(), TPeak::SetAreaErr(), TPeak::SetChi2(), TGRSIFit::SetHist(), and TPeak::SetNdf().
GetDefaultFitType()
static const char * TGRSIFit::GetDefaultFitType () inline static inherited
Definition at line 58 of file TGRSIFit.h.
References TGRSIFit::fDefaultFitType.
GetHist()
virtual TH1 * TGRSIFit::GetHist () const inline virtual inherited
Definition at line 57 of file TGRSIFit.h.
References TGRSIFit::fHist.
Referenced by TPeak::Copy(), TPeak::DrawResiduals(), Fit(), TPeak::Fit(), TPeak::GetIntegralArea(), TPeak::GetIntegralAreaErr(), TPeak::GoodStatus(), InitParams(), and TPeak::InitParams().
GetLogLikelihoodFlag()
static bool TMultiPeak::GetLogLikelihoodFlag () inline static
Definition at line 54 of file TMultiPeak.h.
References fLogLikelihoodFlag.
Referenced by Fit().
GetPeak()
TPeak * TMultiPeak::GetPeak (UInt_t idx)
Definition at line 415 of file TMultiPeak.cxx.
References fPeakVec.
Referenced by GetPeakClosestTo().
GetPeakClosestTo()
TPeak * TMultiPeak::GetPeakClosestTo (Double_t energy)
Definition at line 425 of file TMultiPeak.cxx.
References fPeakVec, and GetPeak().
GoodFit()
void TGRSIFit::GoodFit (Bool_t flag = true) inline protected inherited
Definition at line 69 of file TGRSIFit.h.
References TGRSIFit::fGoodFitFlag.
InitNames()
void TMultiPeak::InitNames () protected
Definition at line 74 of file TMultiPeak.cxx.
References fPeakVec.
Referenced by TMultiPeak(), and TMultiPeak().
InitParams()
Bool_t TMultiPeak::InitParams (TH1 * fithist) override virtual
Implements TGRSIFit.
Definition at line 118 of file TMultiPeak.cxx.
References fPeakVec, TGRSIFit::GetHist(), and TGRSIFit::SetInitialized().
Referenced by Fit().
IsGoodFit()
Bool_t TGRSIFit::IsGoodFit () const inline inherited
Definition at line 52 of file TGRSIFit.h.
References TGRSIFit::fGoodFitFlag.
IsInitialized()
Bool_t TGRSIFit::IsInitialized () const inline protected inherited
Definition at line 67 of file TGRSIFit.h.
References TGRSIFit::fInitFlag.
Referenced by Fit(), and TPeak::Fit().
MultiPhotoPeakBG()
Double_t TMultiPeak::MultiPhotoPeakBG (Double_t * dim, Double_t * par) private
Definition at line 353 of file TMultiPeak.cxx.
References TGRSIFunctions::PhotoPeak(), TGRSIFunctions::PolyBg(), and TGRSIFunctions::StepFunction().
MultiStepBG()
Double_t TMultiPeak::MultiStepBG (Double_t * dim, Double_t * par) private
Definition at line 373 of file TMultiPeak.cxx.
References TGRSIFunctions::PolyBg(), and TGRSIFunctions::StepFunction().
Referenced by TMultiPeak(), and TMultiPeak().
operator=() [1/2]
TMultiPeak & TMultiPeak::operator= (const TMultiPeak &) default
operator=() [2/2]
TMultiPeak & TMultiPeak::operator= (TMultiPeak &&) default noexcept
Print()
void TMultiPeak::Print (Option_t * opt = "") const override
Prints TMultiPeak properties. To see More properties use the option "+"
Definition at line 340 of file TMultiPeak.cxx.
References fPeakVec.
SetDefaultFitType()
static void TGRSIFit::SetDefaultFitType (const char * fitType) inline static inherited
Definition at line 59 of file TGRSIFit.h.
References TGRSIFit::fDefaultFitType.
SetHist()
virtual void TGRSIFit::SetHist (TH1 * hist) inline virtual inherited
Definition at line 53 of file TGRSIFit.h.
References TGRSIFit::fHist, and hist.
Referenced by TPeak::Copy(), Fit(), and TPeak::Fit().
SetInitialized()
void TGRSIFit::SetInitialized (Bool_t flag = true) inline protected inherited
Definition at line 68 of file TGRSIFit.h.
References TGRSIFit::fInitFlag.
Referenced by InitParams(), and TPeak::InitParams().
SetLogLikelihoodFlag()
static void TMultiPeak::SetLogLikelihoodFlag (bool flag) inline static
Definition at line 53 of file TMultiPeak.h.
References fLogLikelihoodFlag.
SinglePeakBG()
Double_t TMultiPeak::SinglePeakBG (Double_t * dim, Double_t * par) private
Definition at line 393 of file TMultiPeak.cxx.
References TGRSIFunctions::PhotoPeak(), TGRSIFunctions::PolyBg(), and TGRSIFunctions::StepFunction().
Referenced by DrawPeaks().
SortPeaks()
void TMultiPeak::SortPeaks (Bool_t(*)(const TPeak *, const TPeak *) SortFunction = TPeak::CompareEnergy)
Definition at line 69 of file TMultiPeak.cxx.
References fPeakVec.
Referenced by TMultiPeak().
Member Data Documentation
fBackground
TF1* TMultiPeak::fBackground {nullptr} private
Definition at line 66 of file TMultiPeak.h.
Referenced by TMultiPeak(), TMultiPeak(), ~TMultiPeak(), Background(), Copy(), and Fit().
fDefaultFitType
TString TGRSIFit::fDefaultFitType static private inherited
Definition at line 75 of file TGRSIFit.h.
Referenced by TGRSIFit::Clear(), TGRSIFit::GetDefaultFitType(), and TGRSIFit::SetDefaultFitType().
fGoodFitFlag
Bool_t TGRSIFit::fGoodFitFlag {false} private inherited
Definition at line 73 of file TGRSIFit.h.
Referenced by TGRSIFit::Clear(), TGRSIFit::Copy(), TGRSIFit::GoodFit(), TGRSIFit::IsGoodFit(), and TGRSIFit::Print().
fHist
TRef TGRSIFit::fHist private inherited
Definition at line 74 of file TGRSIFit.h.
Referenced by TGRSIFit::GetHist(), and TGRSIFit::SetHist().
fInitFlag
Bool_t TGRSIFit::fInitFlag {false} private inherited
Definition at line 72 of file TGRSIFit.h.
Referenced by TGRSIFit::Clear(), TGRSIFit::Copy(), TGRSIFit::IsInitialized(), TGRSIFit::Print(), and TGRSIFit::SetInitialized().
fLogLikelihoodFlag
Bool_t TMultiPeak::fLogLikelihoodFlag = false static private
!
Definition at line 64 of file TMultiPeak.h.
Referenced by GetLogLikelihoodFlag(), and SetLogLikelihoodFlag().
fPeakVec
std::vector<TPeak*> TMultiPeak::fPeakVec private
Definition at line 65 of file TMultiPeak.h.
Referenced by TMultiPeak(), ~TMultiPeak(), Clear(), Copy(), DrawPeaks(), Fit(), GetPeak(), GetPeakClosestTo(), InitNames(), InitParams(), Print(), and SortPeaks().