GRSISort: TAries Class Reference
TAries Class Reference
Detectors
Detailed Description
The TAries class defines the observables and algorithms used when analyzing GRIFFIN data. It includes detector positions, etc.
Definition at line 27 of file TAries.h.
Public Member Functions
TAries ()
TAries (const TAries &rhs)
TAries (TAries &&) noexcept=default
~TAries () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TAriesHit * GetAriesHit (const int &i) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TAries & operator= (const TAries &)
TAries & operator= (TAries &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static ROOT::Math::Polar3DVector GetPosition (int DetNbr)
static bool SetWave ()
Private Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static std::array< ROOT::Math::Polar3DVector, 77 > fPaddlePosition
static bool fSetWave = false
Constructor & Destructor Documentation
TAries() [1/3]
TAries::TAries ()
Definition at line 89 of file TAries.cxx.
References TDetector::Clear().
TAries() [2/3]
TAries::TAries (const TAries & rhs)
Definition at line 97 of file TAries.cxx.
References TDetector::Copy().
TAries() [3/3]
TAries::TAries (TAries &&) default noexcept
~TAries()
TAries::~TAries () override default
Member Function Documentation
AddFragment()
void TAries::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 109 of file TAries.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by AddFragment(), TBgo::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TAries::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 40 of file TAries.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries(), TGenericDetector::TGenericDetector(), TPaces::TPaces(), TSceptar::TSceptar(), TTAC::TTAC(), TZeroDegree::TZeroDegree(), TBgo::Clear(), TDescant::Clear(), TEagle::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TSharc2::Clear(), TSharc::Clear(), TSiLi::Clear(), TSuppressed::Clear(), TTdrPlastic::Clear(), TTdrSiLi::Clear(), TTigress::Clear(), TTrific::Clear(), and TTriFoil::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override inherited
!
Definition at line 24 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TAries(), TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TSceptar::TSceptar(), TTAC::TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree::TZeroDegree(), TBgo::Copy(), TDescant::Copy(), TEagle::Copy(), TEmma::Copy(), TPaces::Copy(), TRcmp::Copy(), TRF::Copy(), TS3::Copy(), TSharc2::Copy(), TSharc::Copy(), TSiLi::Copy(), TSuppressed::Copy(), TTdrSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TTriFoil::Copy(), operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), TFippsTAC::operator=(), TGenericDetector::operator=(), TSceptar::operator=(), TTAC::operator=(), TTdrPlastic::operator=(), TTip::operator=(), and TZeroDegree::operator=().
GetAriesHit()
TAriesHit * TAries::GetAriesHit (const int & i) const inline
Definition at line 36 of file TAries.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), Print(), TBgo::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
static ROOT::Math::Polar3DVector TAries::GetPosition (int DetNbr) inline static
!
Definition at line 42 of file TAries.h.
References fPaddlePosition.
Referenced by TAriesHit::GetPosition().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), TSharc2::GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TAries & TAries::operator= (const TAries & rhs)
!
Definition at line 103 of file TAries.cxx.
References TDetector::Copy().
operator=() [2/2]
TAries & TAries::operator= (TAries &&) default noexcept
Print() [1/2]
void TAries::Print (Option_t * opt = "") const override
!
Prints out TAries Multiplicity, currently does little.
Definition at line 115 of file TAries.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TAries::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 121 of file TAries.cxx.
References TDetector::GetMultiplicity().
SetWave()
static bool TAries::SetWave () inline static
!
Definition at line 44 of file TAries.h.
References fSetWave.
Referenced by TAriesHit::TAriesHit().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fPaddlePosition
std::array< ROOT::Math::Polar3DVector, 77 > TAries::fPaddlePosition static private
! Position of each Paddle
Definition at line 8 of file TAries.h.
Referenced by GetPosition().
fSetWave
bool TAries::fSetWave = false static private
Definition at line 47 of file TAries.h.
Referenced by SetWave().