GRSISort: TDetector Class Reference
TDetector Class Reference
Detectors
This is an abstract class that contains the basic info about a detector. This is where the hits are built and the data is filled. It's main role is to act as a wrapper for every other type of detector system.
Definition at line 34 of file TDetector.h.
Public Member Functions
TDetector ()
TDetector (const TDetector &)
~TDetector () override
virtual void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *)
virtual void AddHit (TDetectorHit *hit)
virtual void BuildHits ()
void Clear (Option_t *="") override
virtual void ClearTransients ()
virtual void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TDetector & operator= (const TDetector &other)
void Print (Option_t *opt="") const override
virtual void Print (std::ostream &out) const
Protected Attributes
std::vector< TDetectorHit * > fHits
Friends
std::ostream & operator<< (std::ostream &out, const TDetector &det)
#include <TDetector.h>
Constructor & Destructor Documentation
TDetector() [1/2]
TDetector::TDetector ()
Default constructor.
Definition at line 8 of file TDetector.cxx.
TDetector() [2/2]
TDetector::TDetector (const TDetector & rhs)
Default Copy constructor.
Definition at line 17 of file TDetector.cxx.
References Copy().
~TDetector()
TDetector::~TDetector () override
Default Destructor.
Definition at line 26 of file TDetector.cxx.
References fHits.
Member Function Documentation
AddFragment()
virtual void TDetector::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) inline virtual
!
Reimplemented in TBgo.
Definition at line 50 of file TDetector.h.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual
Definition at line 56 of file TDetector.h.
References fHits.
BuildHits()
virtual void TDetector::BuildHits () inline virtual
!
Reimplemented in TBgo.
Definition at line 48 of file TDetector.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override
!
Definition at line 58 of file TDetector.h.
References fHits.
Referenced by TBgo::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual
!
Definition at line 64 of file TDetector.cxx.
References fHits.
Copy()
void TDetector::Copy (TObject & rhs) const override virtual
!
Reimplemented in TBgo, and TSuppressed.
Definition at line 34 of file TDetector.cxx.
References TDetectorHit::Copy(), and fHits.
Referenced by TDetector(), ClassImp(), TBgo::Copy(), and operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & i) const virtual
Definition at line 71 of file TDetector.cxx.
References fHits.
Referenced by TBgo::GetBgoHit().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual
Definition at line 65 of file TDetector.h.
References fHits.
Referenced by TSuppressed::CreateSuppressed(), and TSuppressed::CreateSuppressedAddback().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual
Definition at line 63 of file TDetector.h.
References fHits.
Referenced by TBgo::Print().
operator=()
TDetector & TDetector::operator= (const TDetector & other) inline
Definition at line 39 of file TDetector.h.
References Copy().
Print() [1/2]
void TDetector::Print (Option_t * opt = "") const override
!
Default print statement for TDetector.
Definition at line 47 of file TDetector.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TDetector::Print (std::ostream & out) const virtual
Print detector to stream out. Iterates over hits and prints them.
Reimplemented in TBgo.
Definition at line 53 of file TDetector.cxx.
References fHits.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const TDetector & det) friend
Definition at line 67 of file TDetector.h.
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits protected
Definition at line 73 of file TDetector.h.
Referenced by ~TDetector(), TBgo::AddFragment(), AddHit(), Clear(), ClearTransients(), Copy(), GetHit(), GetHitVector(), GetMultiplicity(), and Print().
GRSISort () Reference Guide Generated on Mon May 13 2024 16:00:06.