GRSISort: TAnalysisWriteLoop Class Reference
TAnalysisWriteLoop Class Reference
Loops
Detailed Description
This loop writes built events to file
Definition at line 26 of file TAnalysisWriteLoop.h.
Public Member Functions
TAnalysisWriteLoop (const TAnalysisWriteLoop &)=delete
TAnalysisWriteLoop (TAnalysisWriteLoop &&) noexcept=delete
~TAnalysisWriteLoop ()
void ClearQueue () override
std::string EndStatus () override
size_t GetItemsCurrent () override
size_t GetItemsPopped () override
size_t GetItemsPushed () override
size_t GetRate () override
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TUnpackedEvent > > > & InputQueue ()
bool IsPaused ()
bool IsRunning ()
void Join ()
std::string Name () const
void OnEnd () override
TAnalysisWriteLoop & operator= (const TAnalysisWriteLoop &)=delete
TAnalysisWriteLoop & operator= (TAnalysisWriteLoop &&) noexcept=delete
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & OutOfOrderQueue ()
void Pause ()
virtual std::string Progress ()
void Resume ()
virtual std::string Status ()
void Stop ()
void Write ()
Static Public Member Functions
static std::string AllThreadHeader ()
static std::string AllThreadProgress ()
static std::string AllThreadStatus ()
static bool AnyThreadRunning ()
static std::string AnyThreadStatus ()
static void ClearAllQueues ()
static size_t ColumnWidth ()
static void ColumnWidth (size_t val)
static StoppableThread * Get (const std::string &name)
static TAnalysisWriteLoop * Get (std::string name="", std::string outputFilename="")
static std::vector< StoppableThread * > GetAll ()
static int GetNThreads ()
static void join_status_thread ()
static void PauseAll ()
static void Print ()
static void ResumeAll ()
static void SendStop ()
static void start_status_thread ()
static void status_out ()
static void status_out_loop ()
static size_t StatusWidth ()
static void StatusWidth (size_t val)
static void stop_status_thread ()
static void StopAll ()
Protected Member Functions
void IncrementItemsPopped ()
std::atomic_long & InputSize ()
void InputSize (int64_t val)
std::atomic_size_t & ItemsPopped ()
void ItemsPopped (size_t val)
bool Iteration () override
Private Member Functions
TAnalysisWriteLoop (std::string name, const std::string &outputFilename)
void AddBranch (TClass *cls)
void Loop ()
void WriteEvent (std::shared_ptr< TUnpackedEvent > &event)
Private Attributes
std::map< TClass *, TDetector * > fDefaultDets
std::map< TClass *, TDetector ** > fDetMap
TTree * fEventTree
std::atomic_bool fForceStop {false}
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TUnpackedEvent > > > fInputQueue
std::atomic_long fInputSize {0}
std::atomic_size_t fItemsPopped {0}
std::string fName
bool fOutOfOrder
TFragment * fOutOfOrderFrag
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fOutOfOrderQueue
TTree * fOutOfOrderTree
TFile * fOutputFile
std::atomic_bool fPaused {false}
std::condition_variable fPausedWait
std::mutex fPauseMutex
std::atomic_bool fRunning {false}
std::thread fThread
Static Private Attributes
static size_t fColumnWidth = 20
static std::thread fStatusThread
static bool fStatusThreadOn = false
static size_t fStatusWidth = 80
static std::map< std::string, StoppableThread * > fThreadMap
Constructor & Destructor Documentation
TAnalysisWriteLoop() [1/3]
TAnalysisWriteLoop::TAnalysisWriteLoop (const TAnalysisWriteLoop &) delete
Referenced by Get().
TAnalysisWriteLoop() [2/3]
TAnalysisWriteLoop::TAnalysisWriteLoop (TAnalysisWriteLoop &&) delete noexcept
~TAnalysisWriteLoop()
TAnalysisWriteLoop::~TAnalysisWriteLoop ()
Definition at line 62 of file TAnalysisWriteLoop.cxx.
References fDetMap.
TAnalysisWriteLoop() [3/3]
TAnalysisWriteLoop::TAnalysisWriteLoop (std::string name, const std::string & outputFilename) private
Definition at line 42 of file TAnalysisWriteLoop.cxx.
References fEventTree, fOutOfOrder, fOutOfOrderFrag, fOutOfOrderTree, fOutputFile, and TGRSIOptions::Get().
Member Function Documentation
AddBranch()
void TAnalysisWriteLoop::AddBranch (TClass * cls) private
Definition at line 149 of file TAnalysisWriteLoop.cxx.
References fDefaultDets, fDetMap, fEventTree, StoppableThread::Name(), and ttree_fill_mutex.
Referenced by WriteEvent().
AllThreadHeader()
std::string StoppableThread::AllThreadHeader () static inherited
Definition at line 73 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::ApplyOptions().
AllThreadProgress()
std::string StoppableThread::AllThreadProgress () static inherited
Definition at line 59 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AllThreadStatus()
std::string StoppableThread::AllThreadStatus () static inherited
Definition at line 83 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AnyThreadRunning()
bool StoppableThread::AnyThreadRunning () static inherited
Definition at line 37 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TChannel::GetChannel(), TGRSIint::LoopUntilDone(), and TGRSIInterruptHandler::Notify().
AnyThreadStatus()
std::string StoppableThread::AnyThreadStatus () static inherited
Definition at line 47 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
ClearAllQueues()
void StoppableThread::ClearAllQueues () static inherited
Definition at line 166 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIInterruptHandler::Notify().
ClearQueue()
void TAnalysisWriteLoop::ClearQueue () override virtual
Reimplemented from StoppableThread.
Definition at line 69 of file TAnalysisWriteLoop.cxx.
References fInputQueue.
ColumnWidth() [1/2]
static size_t StoppableThread::ColumnWidth () inline static inherited
Definition at line 82 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
Referenced by TGRSIint::SetupPipeline().
ColumnWidth() [2/2]
static void StoppableThread::ColumnWidth (size_t val) inline static inherited
Definition at line 80 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
EndStatus()
std::string TAnalysisWriteLoop::EndStatus () override virtual
Reimplemented from StoppableThread.
Definition at line 77 of file TAnalysisWriteLoop.cxx.
References StoppableThread::InputSize(), StoppableThread::ItemsPopped(), and StoppableThread::Name().
Get() [1/2]
StoppableThread * StoppableThread::Get (const std::string & name) static inherited
Definition at line 173 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TAnalysisHistLoop::Get(), Get(), TDataLoop::Get(), TDetBuildingLoop::Get(), TEventBuildingLoop::Get(), TFragHistLoop::Get(), TFragmentChainLoop::Get(), TFragWriteLoop::Get(), TTerminalLoop< T >::Get(), and TUnpackingLoop::Get().
Get() [2/2]
TAnalysisWriteLoop * TAnalysisWriteLoop::Get (std::string name = "", std::string outputFilename = "") static
Definition at line 25 of file TAnalysisWriteLoop.cxx.
References TAnalysisWriteLoop(), and StoppableThread::Get().
Referenced by TGRSIint::SetupPipeline().
GetAll()
std::vector< StoppableThread * > StoppableThread::GetAll () static inherited
Definition at line 315 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
GetItemsCurrent()
size_t TAnalysisWriteLoop::GetItemsCurrent () inline override virtual
Implements StoppableThread.
Definition at line 50 of file TAnalysisWriteLoop.h.
GetItemsPopped()
size_t TAnalysisWriteLoop::GetItemsPopped () inline override virtual
Implements StoppableThread.
Definition at line 49 of file TAnalysisWriteLoop.h.
GetItemsPushed()
size_t TAnalysisWriteLoop::GetItemsPushed () inline override virtual
Implements StoppableThread.
Definition at line 48 of file TAnalysisWriteLoop.h.
References StoppableThread::ItemsPopped().
GetNThreads()
int StoppableThread::GetNThreads () static inherited
Definition at line 21 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::Print().
GetRate()
size_t TAnalysisWriteLoop::GetRate () inline override virtual
Implements StoppableThread.
Definition at line 51 of file TAnalysisWriteLoop.h.
IncrementItemsPopped()
void StoppableThread::IncrementItemsPopped () inline protected inherited
Definition at line 97 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by TAnalysisHistLoop::Iteration(), Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), and TUnpackingLoop::Iteration().
InputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TUnpackedEvent > > > & TAnalysisWriteLoop::InputQueue () inline
Definition at line 37 of file TAnalysisWriteLoop.h.
References fInputQueue.
InputSize() [1/2]
std::atomic_long & StoppableThread::InputSize () inline protected inherited
Definition at line 96 of file StoppableThread.h.
References StoppableThread::fInputSize.
Referenced by EndStatus(), TFragWriteLoop::EndStatus(), TAnalysisHistLoop::Iteration(), Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), and TUnpackingLoop::Iteration().
InputSize() [2/2]
void StoppableThread::InputSize (int64_t val) inline protected inherited
Definition at line 94 of file StoppableThread.h.
References StoppableThread::fInputSize.
IsPaused()
bool StoppableThread::IsPaused () inherited
Definition at line 224 of file StoppableThread.cxx.
References StoppableThread::fPaused.
IsRunning()
bool StoppableThread::IsRunning () inherited
Definition at line 219 of file StoppableThread.cxx.
References StoppableThread::fRunning.
Referenced by StoppableThread::status_out().
ItemsPopped() [1/2]
std::atomic_size_t & StoppableThread::ItemsPopped () inline protected inherited
Definition at line 95 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by EndStatus(), TEventBuildingLoop::EndStatus(), TFragWriteLoop::EndStatus(), TFragmentChainLoop::GetItemsPopped(), TFragWriteLoop::GetItemsPopped(), GetItemsPushed(), TFragmentChainLoop::GetItemsPushed(), TFragWriteLoop::GetItemsPushed(), TDataLoop::Iteration(), TFragmentChainLoop::Iteration(), TUnpackingLoop::Iteration(), and TFragmentChainLoop::Restart().
ItemsPopped() [2/2]
void StoppableThread::ItemsPopped (size_t val) inline protected inherited
Definition at line 93 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Iteration()
bool TAnalysisWriteLoop::Iteration () override protected virtual
Implements StoppableThread.
Definition at line 90 of file TAnalysisWriteLoop.cxx.
References TDetectorHit::ClearTransients(), fInputQueue, fOutOfOrder, fOutOfOrderFrag, fOutOfOrderQueue, fOutOfOrderTree, StoppableThread::IncrementItemsPopped(), StoppableThread::InputSize(), ttree_fill_mutex, and WriteEvent().
Join()
void StoppableThread::Join () inherited
Definition at line 229 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), and StoppableThread::fThread.
Referenced by StoppableThread::StopAll().
join_status_thread()
void StoppableThread::join_status_thread () static inherited
Definition at line 280 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, and StoppableThread::stop_status_thread().
Loop()
void StoppableThread::Loop () private inherited
Definition at line 237 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, StoppableThread::fRunning, StoppableThread::Iteration(), and StoppableThread::OnEnd().
Referenced by StoppableThread::StoppableThread().
Name()
std::string StoppableThread::Name () const inline inherited
Definition at line 63 of file StoppableThread.h.
References StoppableThread::fName.
Referenced by AddBranch(), EndStatus(), TFragWriteLoop::EndStatus(), TUnpackingLoop::EndStatus(), and StoppableThread::status_out().
OnEnd()
void TAnalysisWriteLoop::OnEnd () override virtual
Reimplemented from StoppableThread.
Definition at line 85 of file TAnalysisWriteLoop.cxx.
References Write().
operator=() [1/2]
TAnalysisWriteLoop & TAnalysisWriteLoop::operator= (const TAnalysisWriteLoop &) delete
operator=() [2/2]
TAnalysisWriteLoop & TAnalysisWriteLoop::operator= (TAnalysisWriteLoop &&) delete noexcept
OutOfOrderQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TAnalysisWriteLoop::OutOfOrderQueue () inline
Definition at line 41 of file TAnalysisWriteLoop.h.
References fOutOfOrderQueue.
Pause()
void StoppableThread::Pause () inherited
Definition at line 202 of file StoppableThread.cxx.
References StoppableThread::fPaused, and StoppableThread::fRunning.
PauseAll()
void StoppableThread::PauseAll () static inherited
Definition at line 97 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Print()
void StoppableThread::Print () static inherited
Definition at line 254 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, StoppableThread::fThreadMap, StoppableThread::GetNThreads(), and hex().
Progress()
std::string StoppableThread::Progress () virtual inherited
Definition at line 119 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
Resume()
void StoppableThread::Resume () inherited
Definition at line 193 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
ResumeAll()
void StoppableThread::ResumeAll () static inherited
Definition at line 104 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIint::SetupPipeline().
SendStop()
void StoppableThread::SendStop () static inherited
Definition at line 135 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::StopAll(), and TGRSIint::Terminate().
start_status_thread()
void StoppableThread::start_status_thread () static inherited
Definition at line 265 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, StoppableThread::fStatusThreadOn, and StoppableThread::status_out_loop().
Referenced by StoppableThread::StoppableThread().
Status()
std::string StoppableThread::Status () virtual inherited
Definition at line 111 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
status_out()
void StoppableThread::status_out () static inherited
Definition at line 297 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::GetItemsCurrent(), StoppableThread::GetItemsPopped(), StoppableThread::GetItemsPushed(), StoppableThread::GetRate(), StoppableThread::IsRunning(), and StoppableThread::Name().
Referenced by StoppableThread::status_out_loop(), and StoppableThread::StopAll().
status_out_loop()
void StoppableThread::status_out_loop () static inherited
Definition at line 286 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn, and StoppableThread::status_out().
Referenced by StoppableThread::start_status_thread().
StatusWidth() [1/2]
static size_t StoppableThread::StatusWidth () inline static inherited
Definition at line 83 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Referenced by TGRSIint::SetupPipeline().
StatusWidth() [2/2]
static void StoppableThread::StatusWidth (size_t val) inline static inherited
Definition at line 81 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Stop()
void StoppableThread::Stop () inherited
Definition at line 209 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
stop_status_thread()
void StoppableThread::stop_status_thread () static inherited
Definition at line 273 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn.
Referenced by StoppableThread::join_status_thread().
StopAll()
void StoppableThread::StopAll () static inherited
Definition at line 147 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::Join(), StoppableThread::SendStop(), and StoppableThread::status_out().
Referenced by TGRSIint::Terminate().
Write()
void TAnalysisWriteLoop::Write ()
Definition at line 120 of file TAnalysisWriteLoop.cxx.
References TGRSIOptions::AnalysisOptions(), fOutputFile, GValue::Get(), TGRSIOptions::Get(), TSingleton< TPPG >::Get(), TSingleton< TSortingDiagnostics >::Get(), TChannel::GetNumberOfChannels(), GValue::Size(), TAnalysisOptions::WriteToFile(), TChannel::WriteToRoot(), and TRunInfo::WriteToRoot().
Referenced by OnEnd().
WriteEvent()
void TAnalysisWriteLoop::WriteEvent (std::shared_ptr< TUnpackedEvent > & event) private
Definition at line 190 of file TAnalysisWriteLoop.cxx.
References AddBranch(), fDetMap, fEventTree, and ttree_fill_mutex.
Referenced by Iteration().
Member Data Documentation
fColumnWidth
size_t StoppableThread::fColumnWidth = 20 static private inherited
Definition at line 108 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::ColumnWidth(), StoppableThread::ColumnWidth(), StoppableThread::Print(), StoppableThread::Progress(), and StoppableThread::Status().
fDefaultDets
std::map<TClass*, TDetector*> TAnalysisWriteLoop::fDefaultDets private
Definition at line 72 of file TAnalysisWriteLoop.h.
Referenced by AddBranch().
fDetMap
std::map<TClass*, TDetector**> TAnalysisWriteLoop::fDetMap private
Definition at line 71 of file TAnalysisWriteLoop.h.
Referenced by ~TAnalysisWriteLoop(), AddBranch(), and WriteEvent().
fEventTree
TTree* TAnalysisWriteLoop::fEventTree private
Definition at line 66 of file TAnalysisWriteLoop.h.
Referenced by TAnalysisWriteLoop(), AddBranch(), and WriteEvent().
fForceStop
std::atomic_bool StoppableThread::fForceStop {false} private inherited
Definition at line 120 of file StoppableThread.h.
fInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<TUnpackedEvent> > > TAnalysisWriteLoop::fInputQueue private
Definition at line 73 of file TAnalysisWriteLoop.h.
Referenced by ClearQueue(), InputQueue(), and Iteration().
fInputSize
std::atomic_long StoppableThread::fInputSize {0} private inherited
number of items in the input (queue), only updated within Iteration(), so not always fully up-to-date (signed to hold error from queue::pop)
Definition at line 102 of file StoppableThread.h.
Referenced by StoppableThread::InputSize(), StoppableThread::InputSize(), StoppableThread::Progress(), and StoppableThread::Status().
fItemsPopped
std::atomic_size_t StoppableThread::fItemsPopped {0} private inherited
number of items popped from input queue
Definition at line 101 of file StoppableThread.h.
Referenced by StoppableThread::IncrementItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::Progress(), and StoppableThread::Status().
fName
std::string StoppableThread::fName private inherited
Definition at line 106 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), and StoppableThread::Name().
fOutOfOrder
bool TAnalysisWriteLoop::fOutOfOrder private
Definition at line 69 of file TAnalysisWriteLoop.h.
Referenced by TAnalysisWriteLoop(), and Iteration().
fOutOfOrderFrag
TFragment* TAnalysisWriteLoop::fOutOfOrderFrag private
Definition at line 68 of file TAnalysisWriteLoop.h.
Referenced by TAnalysisWriteLoop(), and Iteration().
fOutOfOrderQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TAnalysisWriteLoop::fOutOfOrderQueue private
Definition at line 74 of file TAnalysisWriteLoop.h.
Referenced by Iteration(), and OutOfOrderQueue().
fOutOfOrderTree
TTree* TAnalysisWriteLoop::fOutOfOrderTree private
Definition at line 67 of file TAnalysisWriteLoop.h.
Referenced by TAnalysisWriteLoop(), and Iteration().
fOutputFile
TFile* TAnalysisWriteLoop::fOutputFile private
Definition at line 65 of file TAnalysisWriteLoop.h.
Referenced by TAnalysisWriteLoop(), and Write().
fPaused
std::atomic_bool StoppableThread::fPaused {false} private inherited
Definition at line 121 of file StoppableThread.h.
Referenced by StoppableThread::IsPaused(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fPausedWait
std::condition_variable StoppableThread::fPausedWait private inherited
Definition at line 122 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPauseMutex
std::mutex StoppableThread::fPauseMutex private inherited
Definition at line 123 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fRunning
std::atomic_bool StoppableThread::fRunning {false} private inherited
Definition at line 119 of file StoppableThread.h.
Referenced by StoppableThread::IsRunning(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fStatusThread
std::thread StoppableThread::fStatusThread static private inherited
Definition at line 117 of file StoppableThread.h.
Referenced by StoppableThread::~StoppableThread(), StoppableThread::join_status_thread(), and StoppableThread::start_status_thread().
fStatusThreadOn
bool StoppableThread::fStatusThreadOn = false static private inherited
Definition at line 115 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::start_status_thread(), StoppableThread::status_out_loop(), and StoppableThread::stop_status_thread().
fStatusWidth
size_t StoppableThread::fStatusWidth = 80 static private inherited
Definition at line 109 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::Print(), StoppableThread::StatusWidth(), and StoppableThread::StatusWidth().
fThread
std::thread StoppableThread::fThread private inherited
Definition at line 118 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), and StoppableThread::Join().
fThreadMap
std::map< std::string, StoppableThread * > StoppableThread::fThreadMap static private inherited
Definition at line 113 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::AnyThreadRunning(), StoppableThread::AnyThreadStatus(), StoppableThread::ClearAllQueues(), StoppableThread::Get(), StoppableThread::GetAll(), StoppableThread::GetNThreads(), StoppableThread::PauseAll(), StoppableThread::Print(), StoppableThread::ResumeAll(), StoppableThread::SendStop(), StoppableThread::status_out(), and StoppableThread::StopAll().