GRSISort: TPriorityValue< T > Class Template Reference
TPriorityValue< T > Class Template Reference
Sorting
#include <TPriorityValue.h>
Public Member Functions
TPriorityValue ()
TPriorityValue (const TPriorityValue &rhs)
TPriorityValue (T value, EPriority priority=EPriority::kDefault)
TPriorityValue (TPriorityValue &&rhs)
~TPriorityValue ()
T * Address ()
const T * Address () const
operator T () const
bool operator!= (const T &rhs) const
bool operator!= (const TPriorityValue< T > &rhs)
bool operator< (const T &rhs) const
bool operator< (const TPriorityValue< T > &rhs)
bool operator<= (const T &rhs) const
bool operator<= (const TPriorityValue< T > &rhs)
TPriorityValue< T > & operator= (const TPriorityValue< T > &rhs)
TPriorityValue< T > & operator= (TPriorityValue< T > &&rhs)
bool operator== (const T &rhs) const
bool operator== (const TPriorityValue< T > &rhs)
bool operator> (const T &rhs) const
bool operator> (const TPriorityValue< T > &rhs)
bool operator>= (const T &rhs) const
bool operator>= (const TPriorityValue< T > &rhs)
EPriority Priority () const
void Reset (T val)
void ResetPriority ()
void Set (T val, EPriority priority)
void SetPriority (EPriority priority)
const T & Value () const
Private Attributes
EPriority fPriority
T fValue
Friends
template<class U >
std::ostream & operator<< (std::ostream &, const TPriorityValue< U > &)
Detailed Description
template<class T>
class TPriorityValue< T >
The TPriorityValue defines a template of values with priorities. The priorities are used to over-write values set by the root-file by those read from an input file, and those by values set manually by the user
Definition at line 26 of file TPriorityValue.h.
Constructor & Destructor Documentation
TPriorityValue() [1/4]
template<class T > TPriorityValue< T >::TPriorityValue () inline
Definition at line 28 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and kDefault.
TPriorityValue() [2/4]
template<class T > TPriorityValue< T >::TPriorityValue (T value, EPriority priority = EPriority::kDefault) inline
Definition at line 32 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and TPriorityValue< T >::fValue.
TPriorityValue() [3/4]
template<class T > TPriorityValue< T >::TPriorityValue (const TPriorityValue< T > & rhs) inline
Definition at line 37 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and kDefault.
TPriorityValue() [4/4]
template<class T > TPriorityValue< T >::TPriorityValue (TPriorityValue< T > && rhs) inline
Definition at line 42 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and kDefault.
~TPriorityValue()
template<class T > TPriorityValue< T >::~TPriorityValue () inline
Definition at line 47 of file TPriorityValue.h.
Member Function Documentation
Address() [1/2]
template<class T > T * TPriorityValue< T >::Address () inline
Definition at line 81 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
Referenced by TChannel::AddEnergyNonlinearityPoint(), TChannel::DestroyEnergyNonlinearity(), and TChannel::SetupEnergyNonlinearity().
Address() [2/2]
template<class T > const T * TPriorityValue< T >::Address () const inline
Definition at line 82 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator T()
template<class T > TPriorityValue< T >::operator T () const inline explicit
Definition at line 142 of file TPriorityValue.h.
operator!=() [1/2]
template<class T > bool TPriorityValue< T >::operator!= (const T & rhs) const inline
Definition at line 125 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator!=() [2/2]
template<class T > bool TPriorityValue< T >::operator!= (const TPriorityValue< T > & rhs) inline
Definition at line 105 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator<() [1/2]
template<class T > bool TPriorityValue< T >::operator< (const T & rhs) const inline
Definition at line 128 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator<() [2/2]
template<class T > bool TPriorityValue< T >::operator< (const TPriorityValue< T > & rhs) inline
Definition at line 108 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator<=() [1/2]
template<class T > bool TPriorityValue< T >::operator<= (const T & rhs) const inline
Definition at line 134 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator<=() [2/2]
template<class T > bool TPriorityValue< T >::operator<= (const TPriorityValue< T > & rhs) inline
Definition at line 114 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator=() [1/2]
template<class T > TPriorityValue< T > & TPriorityValue< T >::operator= (const TPriorityValue< T > & rhs) inline
Definition at line 85 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, TPriorityValue< T >::fValue, and kDefault.
operator=() [2/2]
template<class T > TPriorityValue< T > & TPriorityValue< T >::operator= (TPriorityValue< T > && rhs) inline
Definition at line 93 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and TPriorityValue< T >::fValue.
operator==() [1/2]
template<class T > bool TPriorityValue< T >::operator== (const T & rhs) const inline
Definition at line 122 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator==() [2/2]
template<class T > bool TPriorityValue< T >::operator== (const TPriorityValue< T > & rhs) inline
Definition at line 102 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator>() [1/2]
template<class T > bool TPriorityValue< T >::operator> (const T & rhs) const inline
Definition at line 131 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator>() [2/2]
template<class T > bool TPriorityValue< T >::operator> (const TPriorityValue< T > & rhs) inline
Definition at line 111 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator>=() [1/2]
template<class T > bool TPriorityValue< T >::operator>= (const T & rhs) const inline
Definition at line 137 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
operator>=() [2/2]
template<class T > bool TPriorityValue< T >::operator>= (const TPriorityValue< T > & rhs) inline
Definition at line 117 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
Priority()
template<class T > EPriority TPriorityValue< T >::Priority () const inline
Definition at line 80 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority.
Referenced by TGRSIMnemonic::EnumerateDigitizer(), THILMnemonic::EnumerateDigitizer(), TILLMnemonic::EnumerateDigitizer(), TTdrMnemonic::EnumerateDigitizer(), and TChannel::SetENGChi2().
Reset()
template<class T > void TPriorityValue< T >::Reset (T val) inline
Definition at line 69 of file TPriorityValue.h.
References TPriorityValue< T >::fValue, and TPriorityValue< T >::ResetPriority().
Referenced by TChannel::Clear().
ResetPriority()
template<class T > void TPriorityValue< T >::ResetPriority () inline
Definition at line 74 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, and kDefault.
Referenced by TPriorityValue< T >::Reset().
Set()
template<class T > void TPriorityValue< T >::Set (T val, EPriority priority) inline
Definition at line 52 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority, TPriorityValue< T >::fValue, and kForce.
Referenced by TGRSIMnemonic::EnumerateDigitizer(), THILMnemonic::EnumerateDigitizer(), TILLMnemonic::EnumerateDigitizer(), TTdrMnemonic::EnumerateDigitizer(), and TChannel::ReadEnergyNonlinearities().
SetPriority()
template<class T > void TPriorityValue< T >::SetPriority (EPriority priority) inline
Definition at line 61 of file TPriorityValue.h.
References TPriorityValue< T >::fPriority.
Referenced by TChannel::ParseInputData().
Value()
template<class T > const T & TPriorityValue< T >::Value () const inline
Definition at line 79 of file TPriorityValue.h.
References TPriorityValue< T >::fValue.
Referenced by TChannel::TChannel(), TChannel::TChannel(), TChannel::CalibrateENG(), TGRSIMnemonic::EnumerateDigitizer(), THILMnemonic::EnumerateDigitizer(), TILLMnemonic::EnumerateDigitizer(), TTdrMnemonic::EnumerateDigitizer(), TChannel::GetCFDChi2(), TChannel::GetClassType(), TChannel::GetCrystalNumber(), TChannel::GetDetectorNumber(), TChannel::GetDigitizerType(), TChannel::GetEFFChi2(), TChannel::GetEnergyNonlinearity(), TChannel::GetEnergyNonlinearity(), TChannel::GetIntegration(), TChannel::GetLEDChi2(), TChannel::GetMnemonic(), TChannel::GetNumber(), TChannel::GetSegmentNumber(), TChannel::GetStream(), TChannel::GetTime(), TChannel::GetTIMEChi2(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TChannel::GetTimeStampUnit(), TChannel::GetUserInfoNumber(), TChannel::PrintCTToString(), TChannel::PrintToString(), TChannel::SetClassType(), TChannel::SetDigitizerType(), TChannel::SetENGChi2(), TChannel::SetName(), TChannel::SetNumber(), and TChannel::UseCalFileIntegration().
Friends And Related Symbol Documentation
operator<<
template<class T > template<class U > std::ostream & operator<< (std::ostream & , const TPriorityValue< U > &) friend
Member Data Documentation
fPriority
template<class T > EPriority TPriorityValue< T >::fPriority private
Definition at line 150 of file TPriorityValue.h.
Referenced by TPriorityValue< T >::TPriorityValue(), TPriorityValue< T >::TPriorityValue(), TPriorityValue< T >::TPriorityValue(), TPriorityValue< T >::TPriorityValue(), TPriorityValue< T >::operator=(), TPriorityValue< T >::operator=(), TPriorityValue< T >::Priority(), TPriorityValue< T >::ResetPriority(), TPriorityValue< T >::Set(), and TPriorityValue< T >::SetPriority().
fValue
template<class T > T TPriorityValue< T >::fValue private
Definition at line 149 of file TPriorityValue.h.
Referenced by TPriorityValue< T >::TPriorityValue(), TPriorityValue< T >::Address(), TPriorityValue< T >::Address(), TPriorityValue< bool >::operator bool(), TPriorityValue< T >::operator!=(), TPriorityValue< T >::operator!=(), TPriorityValue< T >::operator<(), TPriorityValue< T >::operator<(), operator<<(), TPriorityValue< T >::operator<=(), TPriorityValue< T >::operator<=(), TPriorityValue< T >::operator=(), TPriorityValue< T >::operator=(), TPriorityValue< T >::operator==(), TPriorityValue< T >::operator==(), TPriorityValue< T >::operator>(), TPriorityValue< T >::operator>(), TPriorityValue< T >::operator>=(), TPriorityValue< T >::operator>=(), TPriorityValue< T >::Reset(), TPriorityValue< T >::Set(), and TPriorityValue< T >::Value().