GRSISort: TLstEvent Class Reference
TLstEvent Class Reference
Sorting
Detailed Description
LST event.
C++ class representing one lst file.
Definition at line 22 of file TLstEvent.h.
#include <TLstEvent.h>
Public Member Functions
TLstEvent ()
TLstEvent (const TLstEvent &)
~TLstEvent () override
void Clear (Option_t *opt="") override
void Copy (TObject &) const override
char * GetData () override
uint32_t GetDataSize () const override
int8_t GetLstVersion ()
virtual uint32_t GetTimeStamp () const
virtual int GoodFrags ()
virtual void IncrementGoodFrags ()
TLstEvent & operator= (const TLstEvent &)
void Print (const char *option="") const override
void SetData (std::vector< char > &buffer)
void SetLstVersion (int32_t version)
int SwapBytes (bool) override
Protected Attributes
std::vector< char > fData
int fGoodFrags {0}
int32_t fLstVersion = 1
Constructor & Destructor Documentation
TLstEvent() [1/2]
TLstEvent::TLstEvent ()
default constructor
Definition at line 13 of file TLstEvent.cxx.
TLstEvent() [2/2]
TLstEvent::TLstEvent (const TLstEvent & rhs)
copy constructor
Definition at line 25 of file TLstEvent.cxx.
References Copy().
~TLstEvent()
TLstEvent::~TLstEvent () override
destructor
Definition at line 31 of file TLstEvent.cxx.
References Clear().
Member Function Documentation
Clear()
void TLstEvent::Clear (Option_t * opt = "") override
clear event for reuse
Definition at line 46 of file TLstEvent.cxx.
References fData.
Referenced by ~TLstEvent(), and operator=().
Copy()
void TLstEvent::Copy (TObject & rhs) const override
copy helper
Definition at line 19 of file TLstEvent.cxx.
References fData.
Referenced by TLstEvent(), and operator=().
GetData()
char * TLstEvent::GetData () override virtual
return pointer to the data buffer
Reimplemented from TRawEvent.
Definition at line 65 of file TLstEvent.cxx.
References fData.
GetDataSize()
uint32_t TLstEvent::GetDataSize () const override virtual
return the event size
Reimplemented from TRawEvent.
Definition at line 60 of file TLstEvent.cxx.
References fData.
GetLstVersion()
int8_t TLstEvent::GetLstVersion () inline
Definition at line 42 of file TLstEvent.h.
References fLstVersion.
GetTimeStamp()
virtual uint32_t TRawEvent::GetTimeStamp () const inline virtual inherited
return the event size
Reimplemented in TMidasEvent.
Definition at line 36 of file TRawEvent.h.
GoodFrags()
virtual int TRawEvent::GoodFrags () inline virtual inherited
returns number of good fragments parsed
Definition at line 48 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
IncrementGoodFrags()
virtual void TRawEvent::IncrementGoodFrags () inline virtual inherited
increments the number of good fragments parsed
Definition at line 49 of file TRawEvent.h.
References TRawEvent::fGoodFrags.
operator=()
TLstEvent & TLstEvent::operator= (const TLstEvent & rhs)
assignement operator
Definition at line 36 of file TLstEvent.cxx.
References Clear(), and Copy().
Print()
void TLstEvent::Print (const char * option = "") const override
show all event information
Print data held in this class.
Parameters
[in] option If 'a' (for "all") then the raw data will be printed out too.
Definition at line 71 of file TLstEvent.cxx.
References fData, and hex().
SetData()
void TLstEvent::SetData (std::vector< char > & buffer)
set an externally allocated data buffer
Definition at line 52 of file TLstEvent.cxx.
References fData, and SwapBytes().
SetLstVersion()
void TLstEvent::SetLstVersion (int32_t version) inline
Definition at line 41 of file TLstEvent.h.
References fLstVersion.
SwapBytes()
int TLstEvent::SwapBytes (bool) override virtual
convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC)
Reimplemented from TRawEvent.
Definition at line 135 of file TLstEvent.cxx.
Referenced by SetData().
Member Data Documentation
fData
std::vector<char> TLstEvent::fData protected
event data buffer
Definition at line 47 of file TLstEvent.h.
Referenced by Clear(), Copy(), GetData(), GetDataSize(), Print(), and SetData().
fGoodFrags
int TRawEvent::fGoodFrags {0} protected inherited
number of good fragments parsed
Definition at line 52 of file TRawEvent.h.
Referenced by TMidasEvent::Clear(), TRawEvent::GoodFrags(), and TRawEvent::IncrementGoodFrags().
fLstVersion
int32_t TLstEvent::fLstVersion = 1 protected
Lst version.
Definition at line 48 of file TLstEvent.h.
Referenced by GetLstVersion(), and SetLstVersion().