GRSISort: TSuppressed Class Reference
TSuppressed Class Reference
Detectors
Detailed Description
This is an abstract class that adds basic functionality for Compton suppressed detectors like GRIFFIN.
Definition at line 21 of file TSuppressed.h.
Public Member Functions
TSuppressed ()=default
TSuppressed (const TSuppressed &)=default
TSuppressed (TSuppressed &&) noexcept=default
~TSuppressed ()=default
virtual bool AddbackCriterion (const TDetectorHit *, const TDetectorHit *)
virtual void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *)
virtual void AddHit (TDetectorHit *hit)
virtual void BuildHits ()
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TSuppressed & operator= (const TSuppressed &)=default
TSuppressed & operator= (TSuppressed &&) noexcept=default
void Print (Option_t *opt="") const override
virtual void Print (std::ostream &out) const
virtual bool SuppressionCriterion (const TDetectorHit *, const TDetectorHit *)
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Private Attributes
std::vector< TDetectorHit * > fHits
Constructor & Destructor Documentation
TSuppressed() [1/3]
TSuppressed::TSuppressed () default
TSuppressed() [2/3]
TSuppressed::TSuppressed (const TSuppressed &) default
TSuppressed() [3/3]
TSuppressed::TSuppressed (TSuppressed &&) default noexcept
~TSuppressed()
TSuppressed::~TSuppressed () default
Member Function Documentation
AddbackCriterion()
virtual bool TSuppressed::AddbackCriterion (const TDetectorHit * , const TDetectorHit *) inline virtual
Reimplemented in TFipps, TGriffin, and TIfin.
Definition at line 30 of file TSuppressed.h.
Referenced by CreateAddback(), and CreateSuppressedAddback().
AddFragment()
virtual void TDetector::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) inline virtual inherited
!
Reimplemented in TAries, TBgo, TCSM, TDemand, TDescant, TEagle, TEaglePulser, TEmma, TFipps, TFippsLaBr, TFippsPulser, TFippsTAC, TGenericDetector, TGriffin, TIfin, TLaBr, TPaces, TRcmp, TRF, TS3, TSceptar, TSharc2, TSharc, TSiLi, TTAC, TTdrClover, TTdrPlastic, TTdrSiLi, TTdrTigress, TTigress, TTip, TTrific, TTriFoil, and TZeroDegree.
Definition at line 57 of file TDetector.h.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
virtual void TDetector::BuildHits () inline virtual inherited
!
Reimplemented in TAries, TBgo, TCSM, TDemand, TDescant, TEagle, TEaglePulser, TEmma, TFipps, TFippsLaBr, TFippsPulser, TFippsTAC, TGenericDetector, TGriffin, TIfin, TLaBr, TPaces, TRcmp, TRF, TS3, TSceptar, TSharc2, TSharc, TSiLi, TTAC, TTigress, TTip, TTrific, TTriFoil, and TZeroDegree.
Definition at line 55 of file TDetector.h.
Clear()
void TSuppressed::Clear (Option_t * opt = "all") override
!
Definition at line 9 of file TSuppressed.cxx.
References TDetector::Clear().
Referenced by TFipps::Clear(), TFippsLaBr::Clear(), TGriffin::Clear(), TIfin::Clear(), TLaBr::Clear(), TTdrClover::Clear(), and TTdrTigress::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TSuppressed::Copy (TObject & rhs) const override
!
Definition at line 3 of file TSuppressed.cxx.
References TDetector::Copy().
Referenced by TFipps::Copy(), TFippsLaBr::Copy(), TGriffin::Copy(), TIfin::Copy(), TLaBr::Copy(), TTdrClover::Copy(), and TTdrTigress::Copy().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 38 of file TSuppressed.h.
References AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by TFipps::GetAddbackMultiplicity(), TGriffin::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), and TTdrTigress::GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 69 of file TSuppressed.h.
References TDetector::GetHitVector(), and SuppressionCriterion().
Referenced by TFipps::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), and TTdrTigress::GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 94 of file TSuppressed.h.
References AddbackCriterion(), TDetector::GetHitVector(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and SuppressionCriterion().
Referenced by TFipps::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), and TTdrTigress::GetSuppressedAddbackMultiplicity().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by CreateSuppressed(), CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TGriffin::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TGriffin::GetGriffinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TSuppressed & TSuppressed::operator= (const TSuppressed &) default
operator=() [2/2]
TSuppressed & TSuppressed::operator= (TSuppressed &&) default noexcept
Print() [1/2]
void TDetector::Print (Option_t * opt = "") const override inherited
!
Default print statement for TDetector.
Definition at line 37 of file TDetector.cxx.
References TDetector::Print().
Referenced by TDetector::Print().
Print() [2/2]
void TDetector::Print (std::ostream & out) const virtual inherited
Print detector to stream out. Iterates over hits and prints them.
Reimplemented in TAries, TBgo, TDemand, TDescant, TEagle, TEaglePulser, TEmma, TFipps, TFippsLaBr, TFippsPulser, TFippsTAC, TGenericDetector, TGriffin, TIfin, TLaBr, TPaces, TRcmp, TRF, TS3, TSceptar, TSharc2, TSharc, TSiLi, TTAC, TTdrClover, TTdrPlastic, TTdrSiLi, TTdrTigress, TTigress, TTip, TTrific, TTriFoil, and TZeroDegree.
Definition at line 43 of file TDetector.cxx.
References TDetector::fHits.
SuppressionCriterion()
virtual bool TSuppressed::SuppressionCriterion (const TDetectorHit * , const TDetectorHit *) inline virtual
Reimplemented in TFipps, TFippsLaBr, TGriffin, TIfin, and TLaBr.
Definition at line 31 of file TSuppressed.h.
Referenced by CreateSuppressed(), and CreateSuppressedAddback().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().