GRSISort: TTriFoil Class Reference
TTriFoil Class Reference
Detectors
Detailed Description
Definition at line 15 of file TTriFoil.h.
Public Member Functions
TTriFoil ()
TTriFoil (const TTriFoil &rhs)
~TTriFoil () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
bool Beam () const
void BuildHits () override
void Clear (Option_t *opt="") override
virtual void ClearTransients ()
void Copy (TObject &rhs) const override
virtual TDetectorHit * GetHit (const int &) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
time_t GetTimeStamp () const
std::vector< Short_t > GetWave ()
bool HasWave () const
int NTBeam () const
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
int TBeam (unsigned int n=0) const
Protected Attributes
std::vector< TDetectorHit * > fHits
Private Attributes
bool fBeam {false}
std::vector< int > fTBeam
std::vector< Short_t > fTfWave
Long_t fTimestamp {0}
Constructor & Destructor Documentation
TTriFoil() [1/2]
TTriFoil::TTriFoil ()
Definition at line 7 of file TTriFoil.cxx.
~TTriFoil()
TTriFoil::~TTriFoil () override default
TTriFoil() [2/2]
TTriFoil::TTriFoil (const TTriFoil & rhs)
Definition at line 33 of file TTriFoil.cxx.
References Copy().
Member Function Documentation
AddFragment()
void TTriFoil::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 41 of file TTriFoil.cxx.
References fTBeam, fTfWave, and fTimestamp.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 56 of file TDetector.h.
References TDetector::fHits.
Beam()
bool TTriFoil::Beam () const inline
Definition at line 22 of file TTriFoil.h.
References fBeam.
BuildHits()
void TTriFoil::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 40 of file TTriFoil.h.
Clear()
void TTriFoil::Clear (Option_t * opt = "") override
!
Definition at line 14 of file TTriFoil.cxx.
References TDetector::Clear(), fBeam, fTBeam, fTfWave, and fTimestamp.
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 64 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TTriFoil::Copy (TObject & rhs) const override virtual
!
Reimplemented from TDetector.
Definition at line 24 of file TTriFoil.cxx.
References TDetector::Copy(), fBeam, fTBeam, fTfWave, and fTimestamp.
Referenced by TTriFoil().
GetHit()
TDetectorHit * TDetector::GetHit (const int & i) const virtual inherited
Reimplemented in TGriffin.
Definition at line 71 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), and MakeAnalysisHistograms().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin, and TTrific.
Definition at line 66 of file TDetector.h.
References TDetector::fHits.
Referenced by ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), main(), MakeAnalysisHistograms(), TTigress::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetTimeStamp()
time_t TTriFoil::GetTimeStamp () const inline
Definition at line 35 of file TTriFoil.h.
References fTimestamp.
GetWave()
std::vector< Short_t > TTriFoil::GetWave () inline
Definition at line 21 of file TTriFoil.h.
References fTfWave.
HasWave()
bool TTriFoil::HasWave () const inline
Definition at line 34 of file TTriFoil.h.
References fTfWave.
NTBeam()
int TTriFoil::NTBeam () const inline
Definition at line 23 of file TTriFoil.h.
References fTBeam.
Print() [1/2]
void TTriFoil::Print (Option_t * opt = "") const override
!
Definition at line 79 of file TTriFoil.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TTriFoil::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 84 of file TTriFoil.cxx.
TBeam()
int TTriFoil::TBeam (unsigned int n = 0) const inline
Definition at line 25 of file TTriFoil.h.
References fTBeam.
Member Data Documentation
fBeam
bool TTriFoil::fBeam {false} private
Definition at line 50 of file TTriFoil.h.
Referenced by Beam(), Clear(), and Copy().
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 77 of file TDetector.h.
Referenced by TDetector::~TDetector(), TSiLi::AddCluster(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TDetector::AddHit(), TCSM::BuildHits(), TEmma::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TSharc::Clear(), TTrific::Clear(), TDetector::Clear(), TEmma::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TTrific::GetMultiplicity(), TSharc::GetSize(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
fTBeam
std::vector<int> TTriFoil::fTBeam private
Definition at line 51 of file TTriFoil.h.
Referenced by AddFragment(), Clear(), Copy(), NTBeam(), and TBeam().
fTfWave
std::vector<Short_t> TTriFoil::fTfWave private
Definition at line 48 of file TTriFoil.h.
Referenced by AddFragment(), Clear(), Copy(), GetWave(), and HasWave().
fTimestamp
Long_t TTriFoil::fTimestamp {0} private
Definition at line 49 of file TTriFoil.h.
Referenced by AddFragment(), Clear(), Copy(), and GetTimeStamp().