GRSISort: TGRSIOptions Class Reference
TGRSIOptions Class Reference
Sorting
Detailed Description
This class stores the command line arguments that are passed to GRSISort. This includes file names (root, mid, cal, etc.) as well as command line arguments. This is a singleton class that can be accessed with TGRSIOptions::Get() in order to determine any options that have been passed on the command line.
Definition at line 29 of file TGRSIOptions.h.
Public Member Functions
TGRSIOptions ()=default
std::string AnalysisHistogramLib () const
size_t AnalysisWriteQueueSize () const
bool AverageRateEstimation () const
bool Batch () const
int CacheSize () const
const std::vector< std::string > & CalInputFiles () const
void Clear (Option_t *opt="") override
bool CloseAfterSort () const
size_t ColumnWidth () const
std::string CompiledFilterFile () const
const std::string & DataFrameLibrary () const
bool Debug () const
int Downscaling () const
const std::vector< std::string > & ExternalRunInfo () const
bool ExtractWaves () const
std::string FragmentHistogramLib () const
size_t FragmentWriteQueueSize () const
int GetMaxWorkers () const
bool IgnoreEpics () const
bool IgnoreFileOdb () const
bool IgnoreMissingChannel () const
bool IgnoreOdbChannels () const
bool IgnoreScaler () const
const std::vector< std::string > & InputCutFiles () const
const std::vector< std::string > & InputFiles () const
const std::vector< std::string > & InputOdbFiles () const
std::string InputRing () const
bool IsOnline () const
void Load (int argc, char **argv)
bool LogErrors () const
std::string LogFile () const
void LogFile (const std::string &val)
bool LongFileDescription () const
const std::vector< std::string > & MacroInputFiles () const
bool MakeAnalysisTree () const
bool MakeHistos () const
size_t NumberOfEvents () const
const std::vector< std::string > & OptionFiles () const
const std::string & OutputAnalysisFile () const
const std::string & OutputAnalysisHistogramFile () const
const std::string & OutputFilteredFile () const
const std::string & OutputFragmentFile () const
const std::string & OutputFragmentHistogramFile () const
bool ParallelUnzip () const
const std::string & ParserLibrary () const
void ParserLibrary (std::string &library)
void Print (Option_t *opt="") const override
bool ProofStats () const
bool ReadingMaterial () const
bool ReconstructTimeStamp () const
const std::vector< std::string > & RootInputFiles () const
bool SelectorOnly () const
bool SeparateOutOfOrder () const
bool ShouldExit () const
bool ShouldExitImmediately () const
bool ShowedVersion () const
bool ShowLogo () const
bool SkipInputSort () const
int SortDepth () const
bool SortMultiple () const
bool SortRaw () const
bool StartGui () const
unsigned int StatusInterval () const
size_t StatusWidth () const
int Submergers () const
bool SuppressErrors () const
void SuppressErrors (bool suppress)
std::string TreeName () const
bool UseMidFileOdb () const
bool UseRnTuple () const
const std::vector< std::string > & ValInputFiles () const
const std::vector< std::string > & WinInputFiles () const
int WordOffset () const
bool WriteBadFrags () const
bool WriteDiagnostics () const
bool WriteFragmentTree () const
Static Public Member Functions
static TAnalysisOptions * AnalysisOptions ()
static kFileType DetermineFileType (const std::string &filename)
static TGRSIOptions * Get (int argc=0, char **argv=nullptr)
static Bool_t ReadFromFile (TFile *file=nullptr)
static void SetOptions (TGRSIOptions *tmp)
static TUserSettings * UserSettings ()
static bool WriteToFile (TFile *file=nullptr)
Private Member Functions
TGRSIOptions (int argc, char **argv)
bool FileAutoDetect (const std::string &filename)
Private Attributes
std::string fAnalysisHistogramLib
size_t fAnalysisWriteQueueSize {100000}
bool fAverageRateEstimation {false}
bool fBatch {false}
int fCacheSize {-1}
bool fCloseAfterSort {false}
size_t fColumnWidth {20}
std::string fCompiledFilterFile
std::string fDataFrameLibrary
bool fDebug {false}
int fDownscaling
std::vector< std::string > fExternalRunInfo
bool fExtractWaves {false}
std::string fFragmentHistogramLib
size_t fFragmentWriteQueueSize {100000}
bool fHelp {false}
bool fIgnoreEpics {false}
bool fIgnoreFileOdb
bool fIgnoreMissingChannel {false}
bool fIgnoreOdbChannels
bool fIgnoreScaler {false}
std::vector< std::string > fInputCalFiles
std::vector< std::string > fInputCutFiles
std::vector< std::string > fInputFiles
std::vector< std::string > fInputOdbFiles
std::string fInputRing
std::vector< std::string > fInputRootFiles
std::vector< std::string > fInputValFiles
std::vector< std::string > fInputWinFiles
bool fIsOnline {false}
bool fLogErrors {false}
std::string fLogFile
bool fLongFileDescription {false}
std::vector< std::string > fMacroFiles
bool fMakeAnalysisTree
bool fMakeHistos {false}
int fMaxWorkers {-1}
size_t fNumberOfEvents {0}
std::vector< std::string > fOptionsFile
std::string fOutputAnalysisFile
std::string fOutputAnalysisHistogramFile
std::string fOutputFilteredFile
std::string fOutputFragmentFile
std::string fOutputFragmentHistogramFile
bool fParallelUnzip {false}
std::string fParserLibrary
bool fProofStats {false}
bool fReadingMaterial
bool fReconstructTimeStamp {false}
bool fSelectorOnly {false}
bool fSeparateOutOfOrder {false}
bool fShouldExit {false}
bool fShowedVersion {false}
bool fShowLogo {false}
bool fSkipInputSort {false}
int fSortDepth {200000}
bool fSortMultiple {false}
bool fSortRaw {true}
bool fStartGui {false}
unsigned int fStatusInterval {10}
size_t fStatusWidth {120}
int fSubmergers {-1}
bool fSuppressErrors {false}
std::string fTreeName
bool fUseMidFileOdb {false}
bool fUseRnTuple
int fWordOffset {-1}
bool fWriteBadFrags {false}
bool fWriteDiagnostics {false}
bool fWriteFragmentTree {false}
Static Private Attributes
static TAnalysisOptions * fAnalysisOptions = new TAnalysisOptions
static TGRSIOptions * fGRSIOptions = nullptr
static TUserSettings * fUserSettings = new TUserSettings
Constructor & Destructor Documentation
TGRSIOptions() [1/2]
TGRSIOptions::TGRSIOptions () default
Referenced by Get().
TGRSIOptions() [2/2]
TGRSIOptions::TGRSIOptions (int argc, char ** argv) private
Ctor used when interpreter is initialized
Definition at line 34 of file TGRSIOptions.cxx.
References Load().
Member Function Documentation
AnalysisHistogramLib()
std::string TGRSIOptions::AnalysisHistogramLib () const inline
Definition at line 62 of file TGRSIOptions.h.
References fAnalysisHistogramLib.
Referenced by TGRSIint::SetupPipeline().
AnalysisOptions()
static TAnalysisOptions * TGRSIOptions::AnalysisOptions () inline static
Definition at line 70 of file TGRSIOptions.h.
References fAnalysisOptions.
Referenced by TGRSIHelper::TGRSIHelper(), TTipHit::TTipHit(), TS3::AddFragment(), TTigress::BuildHits(), TGRSIDetectorInformation::BuildMode(), TEventBuildingLoop::CheckTimeCondition(), TEventBuildingLoop::CheckTimestampCondition(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultAddback(), DefaultAddback(), DefaultFippsAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinAddback(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), TFipps::FixCrossTalk(), TGriffin::FixCrossTalk(), TIfin::FixCrossTalk(), main(), TGRSISelector::Process(), TGRSIFrame::Run(), TGRSIint::SetupPipeline(), TGRSISelector::SlaveBegin(), TGRSISelector::Terminate(), and TAnalysisWriteLoop::Write().
AnalysisWriteQueueSize()
size_t TGRSIOptions::AnalysisWriteQueueSize () const inline
Definition at line 112 of file TGRSIOptions.h.
References fAnalysisWriteQueueSize.
AverageRateEstimation()
bool TGRSIOptions::AverageRateEstimation () const inline
Definition at line 134 of file TGRSIOptions.h.
References fAverageRateEstimation.
Referenced by main().
Batch()
bool TGRSIOptions::Batch () const inline
Definition at line 98 of file TGRSIOptions.h.
References fBatch.
Referenced by TGRSIint::ApplyOptions().
CacheSize()
int TGRSIOptions::CacheSize () const inline
Definition at line 136 of file TGRSIOptions.h.
References fCacheSize.
Referenced by main().
CalInputFiles()
const std::vector< std::string > & TGRSIOptions::CalInputFiles () const inline
Definition at line 45 of file TGRSIOptions.h.
References fInputCalFiles.
Referenced by main(), and TGRSIint::SetupPipeline().
Clear()
void TGRSIOptions::Clear (Option_t * opt = "") override
Clears all of the variables in the TGRSIOptions
Definition at line 40 of file TGRSIOptions.cxx.
References TAnalysisOptions::Clear(), TUserSettings::Clear(), fAnalysisHistogramLib, fAnalysisOptions, fAnalysisWriteQueueSize, fAverageRateEstimation, fBatch, fCacheSize, fCloseAfterSort, fColumnWidth, fCompiledFilterFile, fDataFrameLibrary, fDebug, fDownscaling, fExternalRunInfo, fExtractWaves, fFragmentHistogramLib, fFragmentWriteQueueSize, fHelp, fIgnoreEpics, fIgnoreFileOdb, fIgnoreMissingChannel, fIgnoreOdbChannels, fIgnoreScaler, fInputCalFiles, fInputCutFiles, fInputFiles, fInputOdbFiles, fInputRing, fInputRootFiles, fInputValFiles, fInputWinFiles, fIsOnline, fLogErrors, fLogFile, fLongFileDescription, fMacroFiles, fMakeAnalysisTree, fMakeHistos, fMaxWorkers, fNumberOfEvents, fOptionsFile, fOutputAnalysisFile, fOutputAnalysisHistogramFile, fOutputFilteredFile, fOutputFragmentFile, fOutputFragmentHistogramFile, fParallelUnzip, fParserLibrary, fProofStats, fReadingMaterial, fSelectorOnly, fSeparateOutOfOrder, fShouldExit, fShowedVersion, fShowLogo, fSkipInputSort, fSortMultiple, fSortRaw, fStartGui, fStatusInterval, fStatusWidth, fSubmergers, fTreeName, fUseMidFileOdb, fUseRnTuple, fUserSettings, fWordOffset, fWriteBadFrags, fWriteDiagnostics, and fWriteFragmentTree.
Referenced by Load().
CloseAfterSort()
bool TGRSIOptions::CloseAfterSort () const inline
Definition at line 79 of file TGRSIOptions.h.
References fCloseAfterSort.
Referenced by TGRSIint::ApplyOptions(), and TGRSIint::SetupPipeline().
ColumnWidth()
size_t TGRSIOptions::ColumnWidth () const inline
Definition at line 124 of file TGRSIOptions.h.
References fColumnWidth.
CompiledFilterFile()
std::string TGRSIOptions::CompiledFilterFile () const inline
Definition at line 63 of file TGRSIOptions.h.
References fCompiledFilterFile.
DataFrameLibrary()
const std::string & TGRSIOptions::DataFrameLibrary () const inline
Definition at line 52 of file TGRSIOptions.h.
References fDataFrameLibrary.
Referenced by TDataFrameLibrary::Load().
Debug()
bool TGRSIOptions::Debug () const inline
Definition at line 107 of file TGRSIOptions.h.
References fDebug.
Referenced by TGRSIFrame::TGRSIFrame(), and TGRSIFrame::Run().
DetermineFileType()
kFileType TGRSIOptions::DetermineFileType (const std::string & filename) static
Definition at line 478 of file TGRSIOptions.cxx.
References CALIBRATED, COMPILED_SHARED_LIBRARY, CONFIG_FILE, CUTS_FILE, DATAFRAME, GRETINA_MODE2, GRETINA_MODE3, GUI_HIST_FILE, GVALUE, LST_FILE, MIDAS_FILE, NSCL_EVT, PRESETWINDOW, RLMD_FILE, ROOT_DATA, ROOT_MACRO, TDR_FILE, UNKNOWN_FILETYPE, USERSETTINGS, and XML_FILE.
Referenced by FileAutoDetect(), and Load().
Downscaling()
int TGRSIOptions::Downscaling () const inline
Definition at line 89 of file TGRSIOptions.h.
References fDownscaling.
Referenced by TDataLoop::Iteration().
ExternalRunInfo()
const std::vector< std::string > & TGRSIOptions::ExternalRunInfo () const inline
Definition at line 48 of file TGRSIOptions.h.
References fExternalRunInfo.
Referenced by TGRSIint::SetupPipeline().
ExtractWaves()
bool TGRSIOptions::ExtractWaves () const inline
Definition at line 103 of file TGRSIOptions.h.
References fExtractWaves.
FileAutoDetect()
bool TGRSIOptions::FileAutoDetect (const std::string & filename) private
Detects the type of file provided on the command line. This uses the extension to determine the type of the file. Once the type is determined, the file is sent to the appropriate list in TGRSIOptions. This is also smart enough to dynamically link histogramming libraries.
Definition at line 562 of file TGRSIOptions.cxx.
References CALIBRATED, COMPILED_SHARED_LIBRARY, CONFIG_FILE, CUTS_FILE, DATAFRAME, DetermineFileType(), fAnalysisHistogramLib, fDataFrameLibrary, fFragmentHistogramLib, fInputCalFiles, fInputCutFiles, fInputFiles, fInputOdbFiles, fInputRootFiles, fInputValFiles, fInputWinFiles, fMacroFiles, fParserLibrary, full_path(), fUserSettings, DynamicLibrary::GetSymbol(), GRETINA_MODE2, GRETINA_MODE3, GVALUE, LST_FILE, MIDAS_FILE, NSCL_EVT, PRESETWINDOW, TUserSettings::ReadSettings(), RLMD_FILE, ROOT_DATA, ROOT_MACRO, TDR_FILE, UNKNOWN_FILETYPE, USERSETTINGS, and XML_FILE.
Referenced by Load().
FragmentHistogramLib()
std::string TGRSIOptions::FragmentHistogramLib () const inline
Definition at line 61 of file TGRSIOptions.h.
References fFragmentHistogramLib.
Referenced by TGRSIint::SetupPipeline().
FragmentWriteQueueSize()
size_t TGRSIOptions::FragmentWriteQueueSize () const inline
Definition at line 111 of file TGRSIOptions.h.
References fFragmentWriteQueueSize.
Get()
TGRSIOptions * TGRSIOptions::Get (int argc = 0, char ** argv = nullptr) static
Do not use!
Definition at line 22 of file TGRSIOptions.cxx.
References TGRSIOptions(), and fGRSIOptions.
Referenced by TAnalysisHistLoop::TAnalysisHistLoop(), TAnalysisWriteLoop::TAnalysisWriteLoop(), TDescantHit::TDescantHit(), TFragHistLoop::TFragHistLoop(), TGriffinAngles::TGriffinAngles(), TGRSIHelper::TGRSIHelper(), TGRSIint::TGRSIint(), TUnpackingLoop::TUnpackingLoop(), TZeroDegreeHit::TZeroDegreeHit(), TGRSIint::ApplyOptions(), TGRSIDataParser::CaenPhaToFragment(), TGRSIDataParser::CaenPsdToFragment(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TEventBuildingLoop::CheckTimeCondition(), TEventBuildingLoop::CheckTimestampCondition(), TEventBuildingLoop::CheckTriggerIdCondition(), TDataFrameLibrary::Compile(), TDescantHit::Copy(), TZeroDegreeHit::Copy(), TGRSIDataParser::GriffinDataToFragment(), TDataLoop::Iteration(), TDataFrameLibrary::Load(), TParserLibrary::Load(), TGRSIProof::LoadLibsIntoProof(), TGRSIint::LoopUntilDone(), main(), TSortingDiagnostics::OutOfOrder(), TSortingDiagnostics::OutOfTimeOrder(), TGRSIDataParser::Process(), THILDataParser::Process(), TGRSIDataParser::ProcessGriffin(), TMidasFile::SetFileOdb(), TGRSIHelper::Setup(), TGRSIint::SetupPipeline(), TGRSISelector::SlaveBegin(), TGRSIint::Terminate(), TGRSISelector::Terminate(), TAnalysisWriteLoop::Write(), TFragWriteLoop::Write(), and WriteToFile().
GetMaxWorkers()
int TGRSIOptions::GetMaxWorkers () const inline
Definition at line 130 of file TGRSIOptions.h.
References fMaxWorkers.
Referenced by main(), and TGRSIHelper::Setup().
IgnoreEpics()
bool TGRSIOptions::IgnoreEpics () const inline
Definition at line 92 of file TGRSIOptions.h.
References fIgnoreEpics.
IgnoreFileOdb()
bool TGRSIOptions::IgnoreFileOdb () const inline
Definition at line 87 of file TGRSIOptions.h.
References fIgnoreFileOdb.
IgnoreMissingChannel()
bool TGRSIOptions::IgnoreMissingChannel () const inline
Definition at line 116 of file TGRSIOptions.h.
References fIgnoreMissingChannel.
IgnoreOdbChannels()
bool TGRSIOptions::IgnoreOdbChannels () const inline
Definition at line 88 of file TGRSIOptions.h.
References fIgnoreOdbChannels.
IgnoreScaler()
bool TGRSIOptions::IgnoreScaler () const inline
Definition at line 91 of file TGRSIOptions.h.
References fIgnoreScaler.
Referenced by TFragWriteLoop::Write().
InputCutFiles()
const std::vector< std::string > & TGRSIOptions::InputCutFiles () const inline
Definition at line 49 of file TGRSIOptions.h.
References fInputCutFiles.
Referenced by main().
InputFiles()
const std::vector< std::string > & TGRSIOptions::InputFiles () const inline
Definition at line 43 of file TGRSIOptions.h.
References fInputFiles.
Referenced by TGRSIint::ApplyOptions(), main(), and TGRSIint::SetupPipeline().
InputOdbFiles()
const std::vector< std::string > & TGRSIOptions::InputOdbFiles () const inline
Definition at line 47 of file TGRSIOptions.h.
References fInputOdbFiles.
InputRing()
std::string TGRSIOptions::InputRing () const inline
Definition at line 60 of file TGRSIOptions.h.
References fInputRing.
IsOnline()
bool TGRSIOptions::IsOnline () const inline
Definition at line 109 of file TGRSIOptions.h.
References fIsOnline.
Load()
void TGRSIOptions::Load (int argc, char ** argv)
This checks all of the options provided to GRSISort. This also loads in some libraries in order to do on the fly histogramming.
Definition at line 203 of file TGRSIOptions.cxx.
References Clear(), CONFIG_FILE, DCYAN, ArgParser::default_option(), DetermineFileType(), DGREEN, TAnalysisOptions::fAddbackWindow, fAnalysisHistogramLib, fAnalysisOptions, fAnalysisWriteQueueSize, fAverageRateEstimation, fBatch, TAnalysisOptions::fBuildEventsByTimeStamp, TAnalysisOptions::fBuildWindow, fCacheSize, fCloseAfterSort, fColumnWidth, fDebug, fDownscaling, fExtractWaves, fFragmentHistogramLib, fFragmentWriteQueueSize, fHelp, fIgnoreEpics, fIgnoreFileOdb, fIgnoreMissingChannel, fIgnoreOdbChannels, fIgnoreScaler, FileAutoDetect(), fInputCalFiles, fInputRootFiles, fInputValFiles, TAnalysisOptions::fIsCorrectingCrossTalk, fLogErrors, fLogFile, fMakeAnalysisTree, fMakeHistos, fMaxWorkers, fNumberOfEvents, fOutputAnalysisFile, fOutputAnalysisHistogramFile, fOutputFragmentFile, fOutputFragmentHistogramFile, fParallelUnzip, fParserLibrary, fProofStats, fReadingMaterial, fReconstructTimeStamp, fSelectorOnly, fSeparateOutOfOrder, fShouldExit, fShowedVersion, fShowLogo, fSkipInputSort, fSortDepth, fStartGui, TAnalysisOptions::fStaticWindow, fStatusInterval, fStatusWidth, fSubmergers, fSuppressErrors, TAnalysisOptions::fSuppressionEnergy, TAnalysisOptions::fSuppressionWindow, fTreeName, fUseRnTuple, TAnalysisOptions::fWaveformFitting, fWordOffset, fWriteBadFrags, fWriteDiagnostics, fWriteFragmentTree, GREEN, ArgParser::option(), ArgParser::parse(), ArgParser::parse_file(), TAnalysisOptions::ReadFromFile(), and Version().
Referenced by TGRSIOptions().
LogErrors()
bool TGRSIOptions::LogErrors () const inline
Definition at line 81 of file TGRSIOptions.h.
References fLogErrors.
LogFile() [1/2]
std::string TGRSIOptions::LogFile () const inline
Definition at line 67 of file TGRSIOptions.h.
References fLogFile.
Referenced by TGRSISelector::Terminate().
LogFile() [2/2]
void TGRSIOptions::LogFile (const std::string & val) inline
Definition at line 68 of file TGRSIOptions.h.
References fLogFile.
LongFileDescription()
bool TGRSIOptions::LongFileDescription () const inline
Definition at line 127 of file TGRSIOptions.h.
References fLongFileDescription.
MacroInputFiles()
const std::vector< std::string > & TGRSIOptions::MacroInputFiles () const inline
Definition at line 51 of file TGRSIOptions.h.
References fMacroFiles.
Referenced by Analyze(), TGRSIint::ApplyOptions(), AtExitHandler(), and main().
MakeAnalysisTree()
bool TGRSIOptions::MakeAnalysisTree () const inline
Definition at line 84 of file TGRSIOptions.h.
References fMakeAnalysisTree.
Referenced by TGRSIint::SetupPipeline().
MakeHistos()
bool TGRSIOptions::MakeHistos () const inline
Definition at line 104 of file TGRSIOptions.h.
References fMakeHistos.
Referenced by TGRSIint::SetupPipeline().
NumberOfEvents()
size_t TGRSIOptions::NumberOfEvents () const inline
Definition at line 114 of file TGRSIOptions.h.
References fNumberOfEvents.
Referenced by Analyze().
OptionFiles()
const std::vector< std::string > & TGRSIOptions::OptionFiles () const inline
Definition at line 65 of file TGRSIOptions.h.
References fOptionsFile.
OutputAnalysisFile()
const std::string & TGRSIOptions::OutputAnalysisFile () const inline
Definition at line 55 of file TGRSIOptions.h.
References fOutputAnalysisFile.
Referenced by TGRSIint::SetupPipeline().
OutputAnalysisHistogramFile()
const std::string & TGRSIOptions::OutputAnalysisHistogramFile () const inline
Definition at line 59 of file TGRSIOptions.h.
References fOutputAnalysisHistogramFile.
Referenced by TGRSIint::SetupPipeline().
OutputFilteredFile()
const std::string & TGRSIOptions::OutputFilteredFile () const inline
Definition at line 57 of file TGRSIOptions.h.
References fOutputFilteredFile.
OutputFragmentFile()
const std::string & TGRSIOptions::OutputFragmentFile () const inline
Definition at line 54 of file TGRSIOptions.h.
References fOutputFragmentFile.
Referenced by TGRSIint::SetupPipeline().
OutputFragmentHistogramFile()
const std::string & TGRSIOptions::OutputFragmentHistogramFile () const inline
Definition at line 58 of file TGRSIOptions.h.
References fOutputFragmentHistogramFile.
Referenced by TGRSIint::SetupPipeline().
ParallelUnzip()
bool TGRSIOptions::ParallelUnzip () const inline
Definition at line 135 of file TGRSIOptions.h.
References fParallelUnzip.
Referenced by main().
ParserLibrary() [1/2]
const std::string & TGRSIOptions::ParserLibrary () const inline
Definition at line 144 of file TGRSIOptions.h.
References fParserLibrary.
ParserLibrary() [2/2]
void TGRSIOptions::ParserLibrary (std::string & library) inline
Definition at line 143 of file TGRSIOptions.h.
References fParserLibrary.
Referenced by TGRSIint::ApplyOptions(), TDataFrameLibrary::Compile(), TParserLibrary::Load(), TGRSIProof::LoadLibsIntoProof(), main(), and TGRSISelector::SlaveBegin().
Print()
void TGRSIOptions::Print (Option_t * opt = "") const override
Print the current status of TGRSIOptions, includes all names, lists and flags
Definition at line 135 of file TGRSIOptions.cxx.
References fAnalysisOptions, fAnalysisWriteQueueSize, fAverageRateEstimation, fBatch, fCacheSize, fCloseAfterSort, fColumnWidth, fDebug, fDownscaling, fExtractWaves, fFragmentWriteQueueSize, fHelp, fIgnoreEpics, fIgnoreFileOdb, fIgnoreMissingChannel, fIgnoreOdbChannels, fIgnoreScaler, fIsOnline, fLogErrors, fLogFile, fLongFileDescription, fMakeAnalysisTree, fMakeHistos, fMaxWorkers, fParallelUnzip, fParserLibrary, fProofStats, fReadingMaterial, fReconstructTimeStamp, fSelectorOnly, fSeparateOutOfOrder, fShouldExit, fShowedVersion, fShowLogo, fSkipInputSort, fSortDepth, fSortMultiple, fSortRaw, fStartGui, fStatusInterval, fStatusWidth, fSubmergers, fSuppressErrors, fTreeName, fUseMidFileOdb, fUseRnTuple, fWordOffset, fWriteBadFrags, fWriteDiagnostics, fWriteFragmentTree, and TAnalysisOptions::Print().
Referenced by TGRSISelector::SlaveBegin().
ProofStats()
bool TGRSIOptions::ProofStats () const inline
Definition at line 138 of file TGRSIOptions.h.
References fProofStats.
Referenced by main().
ReadFromFile()
Bool_t TGRSIOptions::ReadFromFile (TFile * file = nullptr) static
Definition at line 679 of file TGRSIOptions.cxx.
References CYAN, RESET_COLOR, and SetOptions().
ReadingMaterial()
bool TGRSIOptions::ReadingMaterial () const inline
Definition at line 86 of file TGRSIOptions.h.
References fReadingMaterial.
Referenced by TGRSIint::ApplyOptions().
ReconstructTimeStamp()
bool TGRSIOptions::ReconstructTimeStamp () const inline
Definition at line 77 of file TGRSIOptions.h.
References fReconstructTimeStamp.
RootInputFiles()
const std::vector< std::string > & TGRSIOptions::RootInputFiles () const inline
Definition at line 44 of file TGRSIOptions.h.
References fInputRootFiles.
Referenced by Analyze(), and TGRSIint::ApplyOptions().
SelectorOnly()
bool TGRSIOptions::SelectorOnly () const inline
Definition at line 133 of file TGRSIOptions.h.
References fSelectorOnly.
Referenced by Analyze(), and main().
SeparateOutOfOrder()
bool TGRSIOptions::SeparateOutOfOrder () const inline
Definition at line 73 of file TGRSIOptions.h.
References fSeparateOutOfOrder.
SetOptions()
void TGRSIOptions::SetOptions (TGRSIOptions * tmp) static
Definition at line 670 of file TGRSIOptions.cxx.
References fGRSIOptions.
Referenced by ReadFromFile().
ShouldExit()
bool TGRSIOptions::ShouldExit () const inline
Definition at line 42 of file TGRSIOptions.h.
References fShouldExit.
Referenced by TGRSIint::TGRSIint(), and main().
ShouldExitImmediately()
bool TGRSIOptions::ShouldExitImmediately () const inline
Definition at line 120 of file TGRSIOptions.h.
References fShouldExit.
ShowedVersion()
bool TGRSIOptions::ShowedVersion () const inline
Definition at line 100 of file TGRSIOptions.h.
References fShowedVersion.
ShowLogo()
bool TGRSIOptions::ShowLogo () const inline
Definition at line 101 of file TGRSIOptions.h.
References fShowLogo.
SkipInputSort()
bool TGRSIOptions::SkipInputSort () const inline
Definition at line 117 of file TGRSIOptions.h.
References fSkipInputSort.
SortDepth()
int TGRSIOptions::SortDepth () const inline
Definition at line 118 of file TGRSIOptions.h.
References fSortDepth.
Referenced by TEventBuildingLoop::CheckTimeCondition(), TEventBuildingLoop::CheckTimestampCondition(), TEventBuildingLoop::CheckTriggerIdCondition(), TSortingDiagnostics::OutOfOrder(), TSortingDiagnostics::OutOfTimeOrder(), and TGRSIint::SetupPipeline().
SortMultiple()
bool TGRSIOptions::SortMultiple () const inline
Definition at line 105 of file TGRSIOptions.h.
References fSortMultiple.
SortRaw()
bool TGRSIOptions::SortRaw () const inline
Definition at line 102 of file TGRSIOptions.h.
References fSortRaw.
Referenced by TGRSIint::SetupPipeline().
StartGui()
bool TGRSIOptions::StartGui () const inline
Definition at line 74 of file TGRSIOptions.h.
References fStartGui.
Referenced by TGRSIint::ApplyOptions().
StatusInterval()
unsigned int TGRSIOptions::StatusInterval () const inline
Definition at line 126 of file TGRSIOptions.h.
References fStatusInterval.
StatusWidth()
size_t TGRSIOptions::StatusWidth () const inline
Definition at line 125 of file TGRSIOptions.h.
References fStatusWidth.
Submergers()
int TGRSIOptions::Submergers () const inline
Definition at line 137 of file TGRSIOptions.h.
References fSubmergers.
Referenced by main().
SuppressErrors() [1/2]
bool TGRSIOptions::SuppressErrors () const inline
Definition at line 76 of file TGRSIOptions.h.
References fSuppressErrors.
Referenced by main(), and TGRSIDataParser::Process().
SuppressErrors() [2/2]
void TGRSIOptions::SuppressErrors (bool suppress) inline
Definition at line 140 of file TGRSIOptions.h.
References fSuppressErrors.
TreeName()
std::string TGRSIOptions::TreeName () const inline
Definition at line 131 of file TGRSIOptions.h.
References fTreeName.
Referenced by TGRSIFrame::TGRSIFrame(), and main().
UseMidFileOdb()
bool TGRSIOptions::UseMidFileOdb () const inline
Definition at line 82 of file TGRSIOptions.h.
References fUseMidFileOdb.
UseRnTuple()
bool TGRSIOptions::UseRnTuple () const inline
Definition at line 85 of file TGRSIOptions.h.
References fUseRnTuple.
Referenced by TGRSIint::SetupPipeline().
UserSettings()
static TUserSettings * TGRSIOptions::UserSettings () inline static
Definition at line 71 of file TGRSIOptions.h.
References fUserSettings.
Referenced by TGriffinAngles::TGriffinAngles(), and TGRSIFrame::Run().
ValInputFiles()
const std::vector< std::string > & TGRSIOptions::ValInputFiles () const inline
Definition at line 46 of file TGRSIOptions.h.
References fInputValFiles.
Referenced by main(), and TGRSIint::SetupPipeline().
WinInputFiles()
const std::vector< std::string > & TGRSIOptions::WinInputFiles () const inline
Definition at line 50 of file TGRSIOptions.h.
References fInputWinFiles.
WordOffset()
int TGRSIOptions::WordOffset () const inline
Definition at line 96 of file TGRSIOptions.h.
References fWordOffset.
WriteBadFrags()
bool TGRSIOptions::WriteBadFrags () const inline
Definition at line 94 of file TGRSIOptions.h.
References fWriteBadFrags.
WriteDiagnostics()
bool TGRSIOptions::WriteDiagnostics () const inline
Definition at line 95 of file TGRSIOptions.h.
References fWriteDiagnostics.
Referenced by TFragWriteLoop::Write().
WriteFragmentTree()
bool TGRSIOptions::WriteFragmentTree () const inline
Definition at line 93 of file TGRSIOptions.h.
References fWriteFragmentTree.
Referenced by TGRSIint::SetupPipeline().
WriteToFile()
bool TGRSIOptions::WriteToFile (TFile * file = nullptr) static
Writes options information to the tree
Definition at line 636 of file TGRSIOptions.cxx.
References TUserSettings::empty(), fAnalysisOptions, fUserSettings, Get(), and TAnalysisOptions::WriteToFile().
Referenced by TFragWriteLoop::Write().
Member Data Documentation
fAnalysisHistogramLib
std::string TGRSIOptions::fAnalysisHistogramLib private
The name of the script for histogramming events.
Definition at line 172 of file TGRSIOptions.h.
Referenced by AnalysisHistogramLib(), Clear(), FileAutoDetect(), and Load().
fAnalysisOptions
TAnalysisOptions * TGRSIOptions::fAnalysisOptions = new TAnalysisOptions static private
contains all options for analysis
Definition at line 220 of file TGRSIOptions.h.
Referenced by AnalysisOptions(), Clear(), Load(), Print(), and WriteToFile().
fAnalysisWriteQueueSize
size_t TGRSIOptions::fAnalysisWriteQueueSize {100000} private
Size of the analysis write Q.
Definition at line 212 of file TGRSIOptions.h.
Referenced by AnalysisWriteQueueSize(), Clear(), Load(), and Print().
fAverageRateEstimation
bool TGRSIOptions::fAverageRateEstimation {false} private
enable average rate estimation
Definition at line 238 of file TGRSIOptions.h.
Referenced by AverageRateEstimation(), Clear(), Load(), and Print().
fBatch
bool TGRSIOptions::fBatch {false} private
Flag to use batch mode (-b)
Definition at line 199 of file TGRSIOptions.h.
Referenced by Batch(), Clear(), Load(), and Print().
fCacheSize
int TGRSIOptions::fCacheSize {-1} private
set tree cache size, default is -1 (off)
Definition at line 240 of file TGRSIOptions.h.
Referenced by CacheSize(), Clear(), Load(), and Print().
fCloseAfterSort
bool TGRSIOptions::fCloseAfterSort {false} private
Flag to close after sorting (-q)
Definition at line 179 of file TGRSIOptions.h.
Referenced by Clear(), CloseAfterSort(), Load(), and Print().
fColumnWidth
size_t TGRSIOptions::fColumnWidth {20} private
Size of verbose columns.
Definition at line 229 of file TGRSIOptions.h.
Referenced by Clear(), ColumnWidth(), Load(), and Print().
fCompiledFilterFile
std::string TGRSIOptions::fCompiledFilterFile private
Definition at line 173 of file TGRSIOptions.h.
Referenced by Clear(), and CompiledFilterFile().
fDataFrameLibrary
std::string TGRSIOptions::fDataFrameLibrary private
library (or .cxx file) for dataframe processing (used with grsiframe)
Definition at line 158 of file TGRSIOptions.h.
Referenced by Clear(), DataFrameLibrary(), and FileAutoDetect().
fDebug
bool TGRSIOptions::fDebug {false} private
Flag for debug mode.
Definition at line 209 of file TGRSIOptions.h.
Referenced by Clear(), Debug(), Load(), and Print().
fDownscaling
int TGRSIOptions::fDownscaling private
Downscaling factor for raw events to be processed.
Definition at line 190 of file TGRSIOptions.h.
Referenced by Clear(), Downscaling(), Load(), and Print().
fExternalRunInfo
std::vector<std::string> TGRSIOptions::fExternalRunInfo private
A list of the input run info files.
Definition at line 156 of file TGRSIOptions.h.
Referenced by Clear(), and ExternalRunInfo().
fExtractWaves
bool TGRSIOptions::fExtractWaves {false} private
Flag to keep waveforms (suppress with –no-waveforms)
Definition at line 204 of file TGRSIOptions.h.
Referenced by Clear(), ExtractWaves(), Load(), and Print().
fFragmentHistogramLib
std::string TGRSIOptions::fFragmentHistogramLib private
The name of the script for histogramming fragments.
Definition at line 171 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), FragmentHistogramLib(), and Load().
fFragmentWriteQueueSize
size_t TGRSIOptions::fFragmentWriteQueueSize {100000} private
Size of the Fragment write Q.
Definition at line 211 of file TGRSIOptions.h.
Referenced by Clear(), FragmentWriteQueueSize(), Load(), and Print().
fGRSIOptions
TGRSIOptions * TGRSIOptions::fGRSIOptions = nullptr static private
Definition at line 148 of file TGRSIOptions.h.
Referenced by Get(), and SetOptions().
fHelp
bool TGRSIOptions::fHelp {false} private
help requested?
Definition at line 227 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and Print().
fIgnoreEpics
bool TGRSIOptions::fIgnoreEpics {false} private
Flag to ignore epics.
Definition at line 193 of file TGRSIOptions.h.
Referenced by Clear(), IgnoreEpics(), Load(), and Print().
fIgnoreFileOdb
bool TGRSIOptions::fIgnoreFileOdb private
Flag to ignore midas file odb.
Definition at line 188 of file TGRSIOptions.h.
Referenced by Clear(), IgnoreFileOdb(), Load(), and Print().
fIgnoreMissingChannel
bool TGRSIOptions::fIgnoreMissingChannel {false} private
Flag to completely ignore missing channels.
Definition at line 216 of file TGRSIOptions.h.
Referenced by Clear(), IgnoreMissingChannel(), Load(), and Print().
fIgnoreOdbChannels
bool TGRSIOptions::fIgnoreOdbChannels private
Flag to ignore channels from midas file odb (but do use EPICS from ODB)
Definition at line 189 of file TGRSIOptions.h.
Referenced by Clear(), IgnoreOdbChannels(), Load(), and Print().
fIgnoreScaler
bool TGRSIOptions::fIgnoreScaler {false} private
Flag to ignore scalers in GRIFFIN.
Definition at line 192 of file TGRSIOptions.h.
Referenced by Clear(), IgnoreScaler(), Load(), and Print().
fInputCalFiles
std::vector<std::string> TGRSIOptions::fInputCalFiles private
A list of the input cal files.
Definition at line 154 of file TGRSIOptions.h.
Referenced by CalInputFiles(), Clear(), FileAutoDetect(), and Load().
fInputCutFiles
std::vector<std::string> TGRSIOptions::fInputCutFiles private
A list of input cut files.
Definition at line 160 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), and InputCutFiles().
fInputFiles
std::vector<std::string> TGRSIOptions::fInputFiles private
A list of the input files.
Definition at line 152 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), and InputFiles().
fInputOdbFiles
std::vector<std::string> TGRSIOptions::fInputOdbFiles private
A list of the input odb files.
Definition at line 155 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), and InputOdbFiles().
fInputRing
std::string TGRSIOptions::fInputRing private
The name of hte input ring.
Definition at line 163 of file TGRSIOptions.h.
Referenced by Clear(), and InputRing().
fInputRootFiles
std::vector<std::string> TGRSIOptions::fInputRootFiles private
A list of the input root files.
Definition at line 153 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), Load(), and RootInputFiles().
fInputValFiles
std::vector<std::string> TGRSIOptions::fInputValFiles private
A list of the input GValue files.
Definition at line 161 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), Load(), and ValInputFiles().
fInputWinFiles
std::vector<std::string> TGRSIOptions::fInputWinFiles private
A list of the input window files.
Definition at line 162 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), and WinInputFiles().
fIsOnline
bool TGRSIOptions::fIsOnline {false} private
Flag to sort online data.
Definition at line 205 of file TGRSIOptions.h.
Referenced by Clear(), IsOnline(), and Print().
fLogErrors
bool TGRSIOptions::fLogErrors {false} private
Flag to log errors (–log-errors)
Definition at line 180 of file TGRSIOptions.h.
Referenced by Clear(), Load(), LogErrors(), and Print().
fLogFile
std::string TGRSIOptions::fLogFile private
The name of the output log file.
Definition at line 177 of file TGRSIOptions.h.
Referenced by Clear(), Load(), LogFile(), LogFile(), and Print().
fLongFileDescription
bool TGRSIOptions::fLongFileDescription {false} private
Definition at line 232 of file TGRSIOptions.h.
Referenced by Clear(), LongFileDescription(), and Print().
fMacroFiles
std::vector<std::string> TGRSIOptions::fMacroFiles private
A list of the input macro (.C) files.
Definition at line 157 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), and MacroInputFiles().
fMakeAnalysisTree
bool TGRSIOptions::fMakeAnalysisTree private
Flag to make analysis tree (-a)
Definition at line 185 of file TGRSIOptions.h.
Referenced by Clear(), Load(), MakeAnalysisTree(), and Print().
fMakeHistos
bool TGRSIOptions::fMakeHistos {false} private
Flag to make histograms (-H)
Definition at line 207 of file TGRSIOptions.h.
Referenced by Clear(), Load(), MakeHistos(), and Print().
fMaxWorkers
int TGRSIOptions::fMaxWorkers {-1} private
Max workers used in grsiproof.
Definition at line 235 of file TGRSIOptions.h.
Referenced by Clear(), GetMaxWorkers(), Load(), and Print().
fNumberOfEvents
size_t TGRSIOptions::fNumberOfEvents {0} private
Number of events, fragments, etc. to process (0 - all)
Definition at line 214 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and NumberOfEvents().
fOptionsFile
std::vector<std::string> TGRSIOptions::fOptionsFile private
A list of the input .info files.
Definition at line 175 of file TGRSIOptions.h.
Referenced by Clear(), and OptionFiles().
fOutputAnalysisFile
std::string TGRSIOptions::fOutputAnalysisFile private
The name of the analysis file to write to.
Definition at line 166 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and OutputAnalysisFile().
fOutputAnalysisHistogramFile
std::string TGRSIOptions::fOutputAnalysisHistogramFile private
The name of the analysis histogram file.
Definition at line 169 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and OutputAnalysisHistogramFile().
fOutputFilteredFile
std::string TGRSIOptions::fOutputFilteredFile private
Definition at line 167 of file TGRSIOptions.h.
Referenced by Clear(), and OutputFilteredFile().
fOutputFragmentFile
std::string TGRSIOptions::fOutputFragmentFile private
The name of the fragment file to write to.
Definition at line 165 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and OutputFragmentFile().
fOutputFragmentHistogramFile
std::string TGRSIOptions::fOutputFragmentHistogramFile private
The name of the fragment histogram file.
Definition at line 168 of file TGRSIOptions.h.
Referenced by Clear(), Load(), and OutputFragmentHistogramFile().
fParallelUnzip
bool TGRSIOptions::fParallelUnzip {false} private
enable use of parallel unzipping
Definition at line 239 of file TGRSIOptions.h.
Referenced by Clear(), Load(), ParallelUnzip(), and Print().
fParserLibrary
std::string TGRSIOptions::fParserLibrary private
location of shared object library for data parser and files
Definition at line 245 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), Load(), ParserLibrary(), ParserLibrary(), and Print().
fProofStats
bool TGRSIOptions::fProofStats {false} private
enable proof stats
Definition at line 242 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and ProofStats().
fReadingMaterial
bool TGRSIOptions::fReadingMaterial private
Flag to show reading material (–reading-material)
Definition at line 187 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and ReadingMaterial().
fReconstructTimeStamp
bool TGRSIOptions::fReconstructTimeStamp {false} private
Flag to reconstruct missing high bits of time stamps (–reconstruct-timestamp)
Definition at line 183 of file TGRSIOptions.h.
Referenced by Load(), Print(), and ReconstructTimeStamp().
fSelectorOnly
bool TGRSIOptions::fSelectorOnly {false} private
Flag to turn PROOF off in grsiproof.
Definition at line 236 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and SelectorOnly().
fSeparateOutOfOrder
bool TGRSIOptions::fSeparateOutOfOrder {false} private
Flag to build out of order into seperate event tree.
Definition at line 223 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and SeparateOutOfOrder().
fShouldExit
bool TGRSIOptions::fShouldExit {false} private
Flag to exit sorting.
Definition at line 225 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), ShouldExit(), and ShouldExitImmediately().
fShowedVersion
bool TGRSIOptions::fShowedVersion {false} private
Flag to show version.
Definition at line 201 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and ShowedVersion().
fShowLogo
bool TGRSIOptions::fShowLogo {false} private
Flag to show logo (suppress with -l)
Definition at line 202 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and ShowLogo().
fSkipInputSort
bool TGRSIOptions::fSkipInputSort {false} private
Flag to sort on time or triggers.
Definition at line 217 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and SkipInputSort().
fSortDepth
int TGRSIOptions::fSortDepth {200000} private
Size of Q that stores fragments to be built into events.
Definition at line 218 of file TGRSIOptions.h.
Referenced by Load(), Print(), and SortDepth().
fSortMultiple
bool TGRSIOptions::fSortMultiple {false} private
Flag to sort multiple files.
Definition at line 208 of file TGRSIOptions.h.
Referenced by Clear(), Print(), and SortMultiple().
fSortRaw
bool TGRSIOptions::fSortRaw {true} private
Flag to sort raw file.
Definition at line 203 of file TGRSIOptions.h.
Referenced by Clear(), Print(), and SortRaw().
fStartGui
bool TGRSIOptions::fStartGui {false} private
Flag to start GUI (-g)
Definition at line 206 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and StartGui().
fStatusInterval
unsigned int TGRSIOptions::fStatusInterval {10} private
Time between status updates.
Definition at line 231 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and StatusInterval().
fStatusWidth
size_t TGRSIOptions::fStatusWidth {120} private
Size of total verbose status.
Definition at line 230 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and StatusWidth().
fSubmergers
int TGRSIOptions::fSubmergers {-1} private
set number of sub-mergers (0 = automatic), default is -1 (off)
Definition at line 241 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and Submergers().
fSuppressErrors
bool TGRSIOptions::fSuppressErrors {false} private
Flag to suppress errors (–suppress-errors)
Definition at line 182 of file TGRSIOptions.h.
Referenced by Load(), Print(), SuppressErrors(), and SuppressErrors().
fTreeName
std::string TGRSIOptions::fTreeName private
Name of tree to be analyzed (default is empty, i.e. FragmentTree, AnalysisTree, and Lst2RootTree are checked)
Definition at line 237 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and TreeName().
fUseMidFileOdb
bool TGRSIOptions::fUseMidFileOdb {false} private
Flag to read odb from midas.
Definition at line 181 of file TGRSIOptions.h.
Referenced by Clear(), Print(), and UseMidFileOdb().
fUseRnTuple
bool TGRSIOptions::fUseRnTuple private
Flag to use experimental TRNTuple instead of TTree.
Definition at line 186 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and UseRnTuple().
fUserSettings
TUserSettings * TGRSIOptions::fUserSettings = new TUserSettings static private
contains user settings read from text-file
Definition at line 221 of file TGRSIOptions.h.
Referenced by Clear(), FileAutoDetect(), UserSettings(), and WriteToFile().
fWordOffset
int TGRSIOptions::fWordOffset {-1} private
Offset for word count in GRIFFIN header (default 1)
Definition at line 197 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and WordOffset().
fWriteBadFrags
bool TGRSIOptions::fWriteBadFrags {false} private
Flag to write bad fragments.
Definition at line 195 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and WriteBadFrags().
fWriteDiagnostics
bool TGRSIOptions::fWriteDiagnostics {false} private
Flag to write diagnostics.
Definition at line 196 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and WriteDiagnostics().
fWriteFragmentTree
bool TGRSIOptions::fWriteFragmentTree {false} private
Flag to write fragment tree.
Definition at line 194 of file TGRSIOptions.h.
Referenced by Clear(), Load(), Print(), and WriteFragmentTree().