GRSISort: TFragWriteLoop Class Reference
TFragWriteLoop Class Reference
Loops
Detailed Description
This loop writes fragments to a root-file.
Definition at line 27 of file TFragWriteLoop.h.
Public Member Functions
TFragWriteLoop (const TFragWriteLoop &)=delete
TFragWriteLoop (TFragWriteLoop &&) noexcept=delete
~TFragWriteLoop ()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & BadInputQueue ()
void ClearQueue () override
std::string EndStatus () override
size_t GetItemsCurrent () override
size_t GetItemsPopped () override
size_t GetItemsPushed () override
size_t GetRate () override
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & InputQueue ()
bool IsPaused ()
bool IsRunning ()
void Join ()
std::string Name () const
virtual void OnEnd ()
TFragWriteLoop & operator= (const TFragWriteLoop &)=delete
TFragWriteLoop & operator= (TFragWriteLoop &&) noexcept=delete
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & OutputQueue ()
void Pause ()
virtual std::string Progress ()
void Resume ()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & ScalerInputQueue ()
virtual std::string Status ()
void Stop ()
void Write ()
Static Public Member Functions
static std::string AllThreadHeader ()
static std::string AllThreadProgress ()
static std::string AllThreadStatus ()
static bool AnyThreadRunning ()
static std::string AnyThreadStatus ()
static void ClearAllQueues ()
static size_t ColumnWidth ()
static void ColumnWidth (size_t val)
static StoppableThread * Get (const std::string &name)
static TFragWriteLoop * Get (std::string name="", std::string fOutputFilename="")
static std::vector< StoppableThread * > GetAll ()
static int GetNThreads ()
static void join_status_thread ()
static void PauseAll ()
static void Print ()
static void ResumeAll ()
static void SendStop ()
static void start_status_thread ()
static void status_out ()
static void status_out_loop ()
static size_t StatusWidth ()
static void StatusWidth (size_t val)
static void stop_status_thread ()
static void StopAll ()
Protected Member Functions
void IncrementItemsPopped ()
std::atomic_long & InputSize ()
void InputSize (int64_t val)
std::atomic_size_t & ItemsPopped ()
void ItemsPopped (size_t val)
bool Iteration () override
Private Member Functions
TFragWriteLoop (std::string name, const std::string &fOutputFilename)
void Loop ()
void WriteBadEvent (const std::shared_ptr< const TBadFragment > &event)
void WriteEvent (const std::shared_ptr< const TFragment > &event)
void WriteScaler (const std::shared_ptr< TEpicsFrag > &scaler)
Private Attributes
TBadFragment * fBadEventAddress
TTree * fBadEventTree
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > fBadInputQueue
TFragment * fEventAddress
TTree * fEventTree
std::atomic_bool fForceStop {false}
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fInputQueue
std::atomic_long fInputSize {0}
std::atomic_size_t fItemsPopped {0}
std::string fName
TFile * fOutputFile
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fOutputQueue
std::atomic_bool fPaused {false}
std::condition_variable fPausedWait
std::mutex fPauseMutex
std::atomic_bool fRunning {false}
TEpicsFrag * fScalerAddress
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > fScalerInputQueue
TTree * fScalerTree
std::thread fThread
Static Private Attributes
static size_t fColumnWidth = 20
static std::thread fStatusThread
static bool fStatusThreadOn = false
static size_t fStatusWidth = 80
static std::map< std::string, StoppableThread * > fThreadMap
Constructor & Destructor Documentation
TFragWriteLoop() [1/3]
TFragWriteLoop::TFragWriteLoop (const TFragWriteLoop &) delete
Referenced by Get().
TFragWriteLoop() [2/3]
TFragWriteLoop::TFragWriteLoop (TFragWriteLoop &&) delete noexcept
~TFragWriteLoop()
TFragWriteLoop::~TFragWriteLoop ()
Definition at line 68 of file TFragWriteLoop.cxx.
References Write().
TFragWriteLoop() [3/3]
TFragWriteLoop::TFragWriteLoop (std::string name, const std::string & fOutputFilename) private
Definition at line 38 of file TFragWriteLoop.cxx.
References fBadEventAddress, fBadEventTree, fEventAddress, fEventTree, fOutputFile, fScalerAddress, and fScalerTree.
Member Function Documentation
AllThreadHeader()
std::string StoppableThread::AllThreadHeader () static inherited
Definition at line 73 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::ApplyOptions().
AllThreadProgress()
std::string StoppableThread::AllThreadProgress () static inherited
Definition at line 59 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AllThreadStatus()
std::string StoppableThread::AllThreadStatus () static inherited
Definition at line 83 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AnyThreadRunning()
bool StoppableThread::AnyThreadRunning () static inherited
Definition at line 37 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TChannel::GetChannel(), TGRSIint::LoopUntilDone(), and TGRSIInterruptHandler::Notify().
AnyThreadStatus()
std::string StoppableThread::AnyThreadStatus () static inherited
Definition at line 47 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
BadInputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & TFragWriteLoop::BadInputQueue () inline
Definition at line 42 of file TFragWriteLoop.h.
References fBadInputQueue.
Referenced by TGRSIint::SetupPipeline().
ClearAllQueues()
void StoppableThread::ClearAllQueues () static inherited
Definition at line 166 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIInterruptHandler::Notify().
ClearQueue()
void TFragWriteLoop::ClearQueue () override virtual
Reimplemented from StoppableThread.
Definition at line 73 of file TFragWriteLoop.cxx.
References fInputQueue.
ColumnWidth() [1/2]
static size_t StoppableThread::ColumnWidth () inline static inherited
Definition at line 82 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
Referenced by TGRSIint::SetupPipeline().
ColumnWidth() [2/2]
static void StoppableThread::ColumnWidth (size_t val) inline static inherited
Definition at line 80 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
EndStatus()
std::string TFragWriteLoop::EndStatus () override virtual
Reimplemented from StoppableThread.
Definition at line 81 of file TFragWriteLoop.cxx.
References fBadEventTree, fEventTree, StoppableThread::InputSize(), StoppableThread::ItemsPopped(), and StoppableThread::Name().
Get() [1/2]
StoppableThread * StoppableThread::Get (const std::string & name) static inherited
Definition at line 173 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TAnalysisHistLoop::Get(), TAnalysisWriteLoop::Get(), TDataLoop::Get(), TDetBuildingLoop::Get(), TEventBuildingLoop::Get(), TFragHistLoop::Get(), TFragmentChainLoop::Get(), Get(), TTerminalLoop< T >::Get(), and TUnpackingLoop::Get().
Get() [2/2]
TFragWriteLoop * TFragWriteLoop::Get (std::string name = "", std::string fOutputFilename = "") static
Definition at line 22 of file TFragWriteLoop.cxx.
References TFragWriteLoop(), and StoppableThread::Get().
Referenced by TGRSIint::SetupPipeline().
GetAll()
std::vector< StoppableThread * > StoppableThread::GetAll () static inherited
Definition at line 315 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
GetItemsCurrent()
size_t TFragWriteLoop::GetItemsCurrent () inline override virtual
Implements StoppableThread.
Definition at line 55 of file TFragWriteLoop.h.
GetItemsPopped()
size_t TFragWriteLoop::GetItemsPopped () inline override virtual
Implements StoppableThread.
Definition at line 54 of file TFragWriteLoop.h.
References StoppableThread::ItemsPopped().
GetItemsPushed()
size_t TFragWriteLoop::GetItemsPushed () inline override virtual
Implements StoppableThread.
Definition at line 53 of file TFragWriteLoop.h.
References StoppableThread::ItemsPopped().
GetNThreads()
int StoppableThread::GetNThreads () static inherited
Definition at line 21 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::Print().
GetRate()
size_t TFragWriteLoop::GetRate () inline override virtual
Implements StoppableThread.
Definition at line 56 of file TFragWriteLoop.h.
IncrementItemsPopped()
void StoppableThread::IncrementItemsPopped () inline protected inherited
Definition at line 97 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), Iteration(), and TUnpackingLoop::Iteration().
InputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TFragWriteLoop::InputQueue () inline
Definition at line 38 of file TFragWriteLoop.h.
References fInputQueue.
Referenced by TGRSIint::SetupPipeline().
InputSize() [1/2]
std::atomic_long & StoppableThread::InputSize () inline protected inherited
Definition at line 96 of file StoppableThread.h.
References StoppableThread::fInputSize.
Referenced by TAnalysisWriteLoop::EndStatus(), EndStatus(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), Iteration(), and TUnpackingLoop::Iteration().
InputSize() [2/2]
void StoppableThread::InputSize (int64_t val) inline protected inherited
Definition at line 94 of file StoppableThread.h.
References StoppableThread::fInputSize.
IsPaused()
bool StoppableThread::IsPaused () inherited
Definition at line 224 of file StoppableThread.cxx.
References StoppableThread::fPaused.
IsRunning()
bool StoppableThread::IsRunning () inherited
Definition at line 219 of file StoppableThread.cxx.
References StoppableThread::fRunning.
Referenced by StoppableThread::status_out().
ItemsPopped() [1/2]
std::atomic_size_t & StoppableThread::ItemsPopped () inline protected inherited
Definition at line 95 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by TAnalysisWriteLoop::EndStatus(), TEventBuildingLoop::EndStatus(), EndStatus(), TFragmentChainLoop::GetItemsPopped(), GetItemsPopped(), TAnalysisWriteLoop::GetItemsPushed(), TFragmentChainLoop::GetItemsPushed(), GetItemsPushed(), TDataLoop::Iteration(), TFragmentChainLoop::Iteration(), TUnpackingLoop::Iteration(), and TFragmentChainLoop::Restart().
ItemsPopped() [2/2]
void StoppableThread::ItemsPopped (size_t val) inline protected inherited
Definition at line 93 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Iteration()
bool TFragWriteLoop::Iteration () override protected virtual
Implements StoppableThread.
Definition at line 91 of file TFragWriteLoop.cxx.
References fBadInputQueue, fInputQueue, fScalerInputQueue, StoppableThread::IncrementItemsPopped(), StoppableThread::InputSize(), WriteBadEvent(), WriteEvent(), and WriteScaler().
Join()
void StoppableThread::Join () inherited
Definition at line 229 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), and StoppableThread::fThread.
Referenced by StoppableThread::StopAll().
join_status_thread()
void StoppableThread::join_status_thread () static inherited
Definition at line 280 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, and StoppableThread::stop_status_thread().
Loop()
void StoppableThread::Loop () private inherited
Definition at line 237 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, StoppableThread::fRunning, StoppableThread::Iteration(), and StoppableThread::OnEnd().
Referenced by StoppableThread::StoppableThread().
Name()
std::string StoppableThread::Name () const inline inherited
Definition at line 63 of file StoppableThread.h.
References StoppableThread::fName.
Referenced by TAnalysisWriteLoop::AddBranch(), TAnalysisWriteLoop::EndStatus(), EndStatus(), TUnpackingLoop::EndStatus(), and StoppableThread::status_out().
OnEnd()
virtual void StoppableThread::OnEnd () inline virtual inherited
Reimplemented in TAnalysisWriteLoop, TDataLoop, and TFragmentChainLoop.
Definition at line 59 of file StoppableThread.h.
Referenced by StoppableThread::Loop().
operator=() [1/2]
TFragWriteLoop & TFragWriteLoop::operator= (const TFragWriteLoop &) delete
operator=() [2/2]
TFragWriteLoop & TFragWriteLoop::operator= (TFragWriteLoop &&) delete noexcept
OutputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TFragWriteLoop::OutputQueue () inline
Definition at line 44 of file TFragWriteLoop.h.
References fOutputQueue.
Pause()
void StoppableThread::Pause () inherited
Definition at line 202 of file StoppableThread.cxx.
References StoppableThread::fPaused, and StoppableThread::fRunning.
PauseAll()
void StoppableThread::PauseAll () static inherited
Definition at line 97 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Print()
void StoppableThread::Print () static inherited
Definition at line 254 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, StoppableThread::fThreadMap, StoppableThread::GetNThreads(), and hex().
Progress()
std::string StoppableThread::Progress () virtual inherited
Definition at line 119 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
Resume()
void StoppableThread::Resume () inherited
Definition at line 193 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
ResumeAll()
void StoppableThread::ResumeAll () static inherited
Definition at line 104 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIint::SetupPipeline().
ScalerInputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & TFragWriteLoop::ScalerInputQueue () inline
Definition at line 43 of file TFragWriteLoop.h.
References fScalerInputQueue.
Referenced by TGRSIint::SetupPipeline().
SendStop()
void StoppableThread::SendStop () static inherited
Definition at line 135 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::StopAll(), and TGRSIint::Terminate().
start_status_thread()
void StoppableThread::start_status_thread () static inherited
Definition at line 265 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, StoppableThread::fStatusThreadOn, and StoppableThread::status_out_loop().
Referenced by StoppableThread::StoppableThread().
Status()
std::string StoppableThread::Status () virtual inherited
Definition at line 111 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
status_out()
void StoppableThread::status_out () static inherited
Definition at line 297 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::GetItemsCurrent(), StoppableThread::GetItemsPopped(), StoppableThread::GetItemsPushed(), StoppableThread::GetRate(), StoppableThread::IsRunning(), and StoppableThread::Name().
Referenced by StoppableThread::status_out_loop(), and StoppableThread::StopAll().
status_out_loop()
void StoppableThread::status_out_loop () static inherited
Definition at line 286 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn, and StoppableThread::status_out().
Referenced by StoppableThread::start_status_thread().
StatusWidth() [1/2]
static size_t StoppableThread::StatusWidth () inline static inherited
Definition at line 83 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Referenced by TGRSIint::SetupPipeline().
StatusWidth() [2/2]
static void StoppableThread::StatusWidth (size_t val) inline static inherited
Definition at line 81 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Stop()
void StoppableThread::Stop () inherited
Definition at line 209 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
stop_status_thread()
void StoppableThread::stop_status_thread () static inherited
Definition at line 273 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn.
Referenced by StoppableThread::join_status_thread().
StopAll()
void StoppableThread::StopAll () static inherited
Definition at line 147 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::Join(), StoppableThread::SendStop(), and StoppableThread::status_out().
Referenced by TGRSIint::Terminate().
Write()
void TFragWriteLoop::Write ()
Definition at line 131 of file TFragWriteLoop.cxx.
References fBadEventTree, fEventTree, fOutputFile, fScalerTree, GValue::Get(), TDeadtimeScalerQueue::Get(), TGRSIOptions::Get(), TRateScalerQueue::Get(), TSingleton< TParsingDiagnostics >::Get(), TSingleton< TPPG >::Get(), TChannel::GetNumberOfChannels(), TGRSIOptions::IgnoreScaler(), TParsingDiagnostics::ReadPPG(), GValue::Size(), TPPG::Write(), TGRSIOptions::WriteDiagnostics(), TGRSIOptions::WriteToFile(), TChannel::WriteToRoot(), and TRunInfo::WriteToRoot().
Referenced by ~TFragWriteLoop().
WriteBadEvent()
void TFragWriteLoop::WriteBadEvent (const std::shared_ptr< const TBadFragment > & event) private
Definition at line 206 of file TFragWriteLoop.cxx.
References fBadEventAddress, fBadEventTree, and ttree_fill_mutex.
Referenced by Iteration().
WriteEvent()
void TFragWriteLoop::WriteEvent (const std::shared_ptr< const TFragment > & event) private
Definition at line 193 of file TFragWriteLoop.cxx.
References TDetectorHit::ClearTransients(), fEventAddress, fEventTree, and ttree_fill_mutex.
Referenced by Iteration().
WriteScaler()
void TFragWriteLoop::WriteScaler (const std::shared_ptr< TEpicsFrag > & scaler) private
Definition at line 215 of file TFragWriteLoop.cxx.
References fScalerAddress, fScalerTree, and ttree_fill_mutex.
Referenced by Iteration().
Member Data Documentation
fBadEventAddress
TBadFragment* TFragWriteLoop::fBadEventAddress private
Definition at line 78 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), and WriteBadEvent().
fBadEventTree
TTree* TFragWriteLoop::fBadEventTree private
Definition at line 74 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), EndStatus(), Write(), and WriteBadEvent().
fBadInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TBadFragment> > > TFragWriteLoop::fBadInputQueue private
Definition at line 83 of file TFragWriteLoop.h.
Referenced by BadInputQueue(), and Iteration().
fColumnWidth
size_t StoppableThread::fColumnWidth = 20 static private inherited
Definition at line 108 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::ColumnWidth(), StoppableThread::ColumnWidth(), StoppableThread::Print(), StoppableThread::Progress(), and StoppableThread::Status().
fEventAddress
TFragment* TFragWriteLoop::fEventAddress private
Definition at line 77 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), and WriteEvent().
fEventTree
TTree* TFragWriteLoop::fEventTree private
Definition at line 73 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), EndStatus(), Write(), and WriteEvent().
fForceStop
std::atomic_bool StoppableThread::fForceStop {false} private inherited
Definition at line 120 of file StoppableThread.h.
fInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TFragWriteLoop::fInputQueue private
Definition at line 82 of file TFragWriteLoop.h.
Referenced by ClearQueue(), InputQueue(), and Iteration().
fInputSize
std::atomic_long StoppableThread::fInputSize {0} private inherited
number of items in the input (queue), only updated within Iteration(), so not always fully up-to-date (signed to hold error from queue::pop)
Definition at line 102 of file StoppableThread.h.
Referenced by StoppableThread::InputSize(), StoppableThread::InputSize(), StoppableThread::Progress(), and StoppableThread::Status().
fItemsPopped
std::atomic_size_t StoppableThread::fItemsPopped {0} private inherited
number of items popped from input queue
Definition at line 101 of file StoppableThread.h.
Referenced by StoppableThread::IncrementItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::Progress(), and StoppableThread::Status().
fName
std::string StoppableThread::fName private inherited
Definition at line 106 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), and StoppableThread::Name().
fOutputFile
TFile* TFragWriteLoop::fOutputFile private
Definition at line 71 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), and Write().
fOutputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TFragWriteLoop::fOutputQueue private
Definition at line 85 of file TFragWriteLoop.h.
Referenced by OutputQueue().
fPaused
std::atomic_bool StoppableThread::fPaused {false} private inherited
Definition at line 121 of file StoppableThread.h.
Referenced by StoppableThread::IsPaused(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fPausedWait
std::condition_variable StoppableThread::fPausedWait private inherited
Definition at line 122 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPauseMutex
std::mutex StoppableThread::fPauseMutex private inherited
Definition at line 123 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fRunning
std::atomic_bool StoppableThread::fRunning {false} private inherited
Definition at line 119 of file StoppableThread.h.
Referenced by StoppableThread::IsRunning(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fScalerAddress
TEpicsFrag* TFragWriteLoop::fScalerAddress private
Definition at line 79 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), and WriteScaler().
fScalerInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<TEpicsFrag> > > TFragWriteLoop::fScalerInputQueue private
Definition at line 84 of file TFragWriteLoop.h.
Referenced by Iteration(), and ScalerInputQueue().
fScalerTree
TTree* TFragWriteLoop::fScalerTree private
Definition at line 75 of file TFragWriteLoop.h.
Referenced by TFragWriteLoop(), Write(), and WriteScaler().
fStatusThread
std::thread StoppableThread::fStatusThread static private inherited
Definition at line 117 of file StoppableThread.h.
Referenced by StoppableThread::~StoppableThread(), StoppableThread::join_status_thread(), and StoppableThread::start_status_thread().
fStatusThreadOn
bool StoppableThread::fStatusThreadOn = false static private inherited
Definition at line 115 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::start_status_thread(), StoppableThread::status_out_loop(), and StoppableThread::stop_status_thread().
fStatusWidth
size_t StoppableThread::fStatusWidth = 80 static private inherited
Definition at line 109 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::Print(), StoppableThread::StatusWidth(), and StoppableThread::StatusWidth().
fThread
std::thread StoppableThread::fThread private inherited
Definition at line 118 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), and StoppableThread::Join().
fThreadMap
std::map< std::string, StoppableThread * > StoppableThread::fThreadMap static private inherited
Definition at line 113 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::AnyThreadRunning(), StoppableThread::AnyThreadStatus(), StoppableThread::ClearAllQueues(), StoppableThread::Get(), StoppableThread::GetAll(), StoppableThread::GetNThreads(), StoppableThread::PauseAll(), StoppableThread::Print(), StoppableThread::ResumeAll(), StoppableThread::SendStop(), StoppableThread::status_out(), and StoppableThread::StopAll().