GRSISort: TGRSISortList Class Reference
TGRSISortList Class Reference
Sorting
Detailed Description
Definition at line 18 of file TGRSISortInfo.h.
Public Member Functions
TGRSISortList ()=default
TGRSISortList (const TGRSISortList &)=default
TGRSISortList (TGRSISortList &&) noexcept=default
~TGRSISortList ()=default
Bool_t AddSortInfo (TGRSISortInfo *info, Option_t *opt="")
Bool_t AddSortList (TGRSISortList *rhslist, Option_t *opt="")
void Clear (Option_t *opt="") override
TGRSISortInfo * GetSortInfo (Int_t RunNumber, Int_t SubRunNumber)
Long64_t Merge (TCollection *list)
TGRSISortList & operator= (const TGRSISortList &)=default
TGRSISortList & operator= (TGRSISortList &&) noexcept=default
void Print (Option_t *opt="") const override
Private Types
using infoMap = std::map<Int_t, std::map<Int_t, TGRSISortInfo*>>
Private Attributes
infoMap fSortInfoList
Member Typedef Documentation
infoMap
using TGRSISortList::infoMap = std::map<Int_t, std::map<Int_t, TGRSISortInfo*>> private
Definition at line 19 of file TGRSISortInfo.h.
Constructor & Destructor Documentation
TGRSISortList() [1/3]
TGRSISortList::TGRSISortList () default
TGRSISortList() [2/3]
TGRSISortList::TGRSISortList (const TGRSISortList &) default
TGRSISortList() [3/3]
TGRSISortList::TGRSISortList (TGRSISortList &&) default noexcept
~TGRSISortList()
TGRSISortList::~TGRSISortList () default
Member Function Documentation
AddSortInfo()
Bool_t TGRSISortList::AddSortInfo (TGRSISortInfo * info, Option_t * opt = "")
Definition at line 5 of file TGRSISortInfo.cxx.
References TGRSISortInfo::AddDuplicate(), fSortInfoList, TGRSISortInfo::RunNumber(), and TGRSISortInfo::SubRunNumber().
Referenced by AddSortList().
AddSortList()
Bool_t TGRSISortList::AddSortList (TGRSISortList * rhslist, Option_t * opt = "")
Adds another TGRSISortList to the current Sort list.
Definition at line 45 of file TGRSISortInfo.cxx.
References AddSortInfo(), and fSortInfoList.
Referenced by Merge().
Clear()
void TGRSISortList::Clear (Option_t * opt = "") override
Definition at line 40 of file TGRSISortInfo.cxx.
References fSortInfoList.
GetSortInfo()
TGRSISortInfo * TGRSISortList::GetSortInfo (Int_t RunNumber, Int_t SubRunNumber)
Definition at line 26 of file TGRSISortInfo.cxx.
References fSortInfoList.
Merge()
Long64_t TGRSISortList::Merge (TCollection * list)
Definition at line 58 of file TGRSISortInfo.cxx.
References AddSortList().
operator=() [1/2]
TGRSISortList & TGRSISortList::operator= (const TGRSISortList &) default
operator=() [2/2]
TGRSISortList & TGRSISortList::operator= (TGRSISortList &&) default noexcept
Print()
void TGRSISortList::Print (Option_t * opt = "") const override
Definition at line 31 of file TGRSISortInfo.cxx.
References fSortInfoList.
Member Data Documentation
fSortInfoList
infoMap TGRSISortList::fSortInfoList private
Definition at line 38 of file TGRSISortInfo.h.
Referenced by AddSortInfo(), AddSortList(), Clear(), GetSortInfo(), and Print().