GRSISort: TGriffin Class Reference
TGriffin Class Reference
Detectors
Detailed Description
Definition at line 23 of file TGriffin.h.
Public Types
enum class EGainBits { kLowGain , kHighGain }
enum class EGriffinBits {
kIsLowGainAddbackSet = 1<<0 , kIsHighGainAddbackSet = 1<<1 , kIsLowGainCrossTalkSet = 1<<2 , kIsHighGainCrossTalkSet = 1<<3 ,
kIsLowGainSuppressed = 1<<4 , kIsHighGainSuppressed = 1<<5 , kIsLowGainSuppressedAddbackSet = 1<<6 , kIsHighGainSuppressedAddbackSet = 1<<7
}
Public Member Functions
TGriffin ()
TGriffin (const TGriffin &)
~TGriffin () override
bool AddbackCriterion (const TDetectorHit *hit1, const TDetectorHit *hit2) override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
void ClearTransients () override
void Copy (TObject &) const override
void FixHighGainCrossTalk ()
void FixLowGainCrossTalk ()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetAddbackCriterion () const
TGriffinHit * GetAddbackHighGainHit (const int &i)
Short_t GetAddbackHighGainMultiplicity ()
TGriffinHit * GetAddbackHit (const int &i)
TGriffinHit * GetAddbackLowGainHit (const int &i)
Short_t GetAddbackLowGainMultiplicity ()
Short_t GetAddbackMultiplicity ()
TGriffinHit * GetGriffinHighGainHit (const int &i)
TGriffinHit * GetGriffinHit (const int &i)
TGriffinHit * GetGriffinLowGainHit (const int &i)
Short_t GetHighGainMultiplicity () const
TDetectorHit * GetHit (const int &idx)
virtual TDetectorHit * GetHit (const int &index) const
Short_t GetLowGainMultiplicity () const
Short_t GetMultiplicity () const override
UShort_t GetNAddbackFrags (const size_t &idx)
UShort_t GetNHighGainAddbackFrags (const size_t &idx)
UShort_t GetNHighGainSuppressedAddbackFrags (const size_t &idx)
UShort_t GetNLowGainAddbackFrags (const size_t &idx)
UShort_t GetNLowGainSuppressedAddbackFrags (const size_t &idx)
UShort_t GetNSuppressedAddbackFrags (const size_t &idx)
TGriffinHit * GetSuppressedAddbackHighGainHit (const int &i)
Short_t GetSuppressedAddbackHighGainMultiplicity (const TBgo *bgo)
TGriffinHit * GetSuppressedAddbackHit (const int &i)
TGriffinHit * GetSuppressedAddbackLowGainHit (const int &i)
Short_t GetSuppressedAddbackLowGainMultiplicity (const TBgo *bgo)
Short_t GetSuppressedAddbackMultiplicity (const TBgo *bgo)
TGriffinHit * GetSuppressedHighGainHit (const int &i)
Short_t GetSuppressedHighGainMultiplicity (const TBgo *bgo)
TGriffinHit * GetSuppressedHit (const int &i)
TGriffinHit * GetSuppressedLowGainHit (const int &i)
Short_t GetSuppressedLowGainMultiplicity (const TBgo *bgo)
Short_t GetSuppressedMultiplicity (const TBgo *bgo)
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetSuppressionCriterion () const
bool IsAddbackSet (const EGainBits &gain_type) const
Bool_t IsCrossTalkSet (const EGainBits &gain_type) const
bool IsSuppressed (const EGainBits &gain_type) const
bool IsSuppressedAddbackSet (const EGainBits &gain_type) const
TGriffin & operator= (const TGriffin &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void ResetAddback ()
void ResetFlags () const
void ResetHighGainAddback ()
void ResetHighGainSuppressed ()
void ResetHighGainSuppressedAddback ()
void ResetLowGainAddback ()
void ResetLowGainSuppressed ()
void ResetLowGainSuppressedAddback ()
void ResetSuppressed ()
void ResetSuppressedAddback ()
void SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
void SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
bool SuppressionCriterion (const TDetectorHit *hit, const TDetectorHit *bgoHit) override
Static Public Member Functions
static Double_t CTCorrectedEnergy (const TGriffinHit *const hit_to_correct, const TGriffinHit *const other_hit, Bool_t time_constraint=true)
static const char * GetColorFromNumber (int number)
static EGainBits GetDefaultGainType ()
static TVector3 GetDetectorPosition (int DetNbr)
static TVector3 GetPosition (int DetNbr, int CryNbr=5, double dist=110.0)
static bool SetCoreWave ()
static void SetDefaultGainType (const EGainBits &gain_type)
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Protected Attributes
std::vector< TDetectorHit * > fHits
Private Member Functions
void ClearStatus () const
void FixCrossTalk (const EGainBits &gain_type)
std::vector< UShort_t > & GetAddbackFragVector (const EGainBits &gain_type)
TGriffinHit * GetAddbackHit (const int &i, const EGainBits &gain_type)
Short_t GetAddbackMultiplicity (const EGainBits &gain_type)
std::vector< TDetectorHit * > & GetAddbackVector (const EGainBits &gain_type)
TGriffinHit * GetGriffinHit (const int &i, const EGainBits &gain_type)
const std::vector< TDetectorHit * > & GetHitVector () const override
std::vector< TDetectorHit * > & GetHitVector (const EGainBits &gain_type)
const std::vector< TDetectorHit * > & GetHitVector (const EGainBits &gain_type) const
Short_t GetMultiplicity (const EGainBits &gain_type) const
UShort_t GetNAddbackFrags (const size_t &idx, const EGainBits &gain_type)
UShort_t GetNSuppressedAddbackFrags (const size_t &idx, const EGainBits &gain_type)
std::vector< UShort_t > & GetSuppressedAddbackFragVector (const EGainBits &gain_type)
TGriffinHit * GetSuppressedAddbackHit (const int &i, const EGainBits &gain_type)
Short_t GetSuppressedAddbackMultiplicity (const TBgo *bgo, const EGainBits &gain_type)
std::vector< TDetectorHit * > & GetSuppressedAddbackVector (const EGainBits &gain_type)
TGriffinHit * GetSuppressedHit (const int &i, const EGainBits &gain_type)
Short_t GetSuppressedMultiplicity (const TBgo *bgo, const EGainBits &gain_type)
std::vector< TDetectorHit * > & GetSuppressedVector (const EGainBits &gain_type)
void ResetAddback (const EGainBits &gain_type)
void ResetSuppressed (const EGainBits &gain_type)
void ResetSuppressedAddback (const EGainBits &gain_type)
void SetAddback (const EGainBits &gain_type, bool flag=true) const
void SetBitNumber (EGriffinBits bit, Bool_t set) const
void SetCrossTalk (const EGainBits &gain_type, bool flag=true) const
void SetSuppressed (const EGainBits &gain_type, bool flag=true) const
void SetSuppressedAddback (const EGainBits &gain_type, bool flag=true) const
Bool_t TestBitNumber (EGriffinBits bit) const
Private Attributes
std::vector< UShort_t > fAddbackHighGainFrags
std::vector< TDetectorHit * > fAddbackHighGainHits
std::vector< UShort_t > fAddbackLowGainFrags
std::vector< TDetectorHit * > fAddbackLowGainHits
long fCycleStart
TTransientBits< UChar_t > fGriffinBits
std::vector< TDetectorHit * > fGriffinHighGainHits
std::vector< TDetectorHit * > & fGriffinLowGainHits = fHits
std::vector< UShort_t > fSuppressedAddbackHighGainFrags
std::vector< TDetectorHit * > fSuppressedAddbackHighGainHits
std::vector< UShort_t > fSuppressedAddbackLowGainFrags
std::vector< TDetectorHit * > fSuppressedAddbackLowGainHits
std::vector< TDetectorHit * > fSuppressedHighGainHits
std::vector< TDetectorHit * > fSuppressedLowGainHits
Static Private Attributes
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fAddbackCriterion = DefaultGriffinAddback
static EGainBits fDefaultGainType = TGriffin::EGainBits::kLowGain
static bool fSetCoreWave = false
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fSuppressionCriterion = DefaultGriffinSuppression
static TVector3 gCloverPosition [17]
Member Enumeration Documentation
EGainBits
enum class TGriffin::EGainBits strong
Enumerator
kLowGain
kHighGain
Definition at line 35 of file TGriffin.h.
EGriffinBits
enum class TGriffin::EGriffinBits strong
Enumerator
kIsLowGainAddbackSet
kIsHighGainAddbackSet
kIsLowGainCrossTalkSet
kIsHighGainCrossTalkSet
kIsLowGainSuppressed
kIsHighGainSuppressed
kIsLowGainSuppressedAddbackSet
kIsHighGainSuppressedAddbackSet
Definition at line 25 of file TGriffin.h.
Constructor & Destructor Documentation
TGriffin() [1/2]
TGriffin::TGriffin ()
Definition at line 117 of file TGriffin.cxx.
References Clear().
TGriffin() [2/2]
TGriffin::TGriffin (const TGriffin & rhs)
Definition at line 126 of file TGriffin.cxx.
References Copy().
~TGriffin()
TGriffin::~TGriffin () override
Definition at line 180 of file TGriffin.cxx.
References fAddbackHighGainHits, fAddbackLowGainHits, fGriffinHighGainHits, fSuppressedAddbackHighGainHits, fSuppressedAddbackLowGainHits, fSuppressedHighGainHits, and fSuppressedLowGainHits.
Member Function Documentation
AddbackCriterion()
bool TGriffin::AddbackCriterion (const TDetectorHit * hit1, const TDetectorHit * hit2) inline override virtual
Reimplemented from TSuppressed.
Definition at line 78 of file TGriffin.h.
References fAddbackCriterion.
AddFragment()
void TGriffin::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 475 of file TGriffin.cxx.
References GetHitVector(), TChannel::GetMnemonic(), TMnemonic::kA, TMnemonic::kB, TMnemonic::kG, kHighGain, kLowGain, TMnemonic::OutputSensor(), and TMnemonic::SubSystem().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
BuildHits()
void TGriffin::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 57 of file TGriffin.h.
Clear()
void TGriffin::Clear (Option_t * opt = "all") override
!
Definition at line 207 of file TGriffin.cxx.
References TSuppressed::Clear(), ClearStatus(), fAddbackHighGainFrags, fAddbackHighGainHits, fAddbackLowGainFrags, fAddbackLowGainHits, fCycleStart, fGriffinHighGainHits, fSuppressedAddbackHighGainFrags, fSuppressedAddbackHighGainHits, fSuppressedAddbackLowGainFrags, fSuppressedAddbackLowGainHits, fSuppressedHighGainHits, and fSuppressedLowGainHits.
Referenced by TGriffin().
ClearStatus()
void TGriffin::ClearStatus () const inline private
!
Definition at line 169 of file TGriffin.h.
References fGriffinBits.
Referenced by Clear().
ClearTransients()
void TGriffin::ClearTransients () inline override virtual
!
Reimplemented from TDetector.
Definition at line 59 of file TGriffin.h.
Copy()
void TGriffin::Copy (TObject & rhs) const override
!
Definition at line 135 of file TGriffin.cxx.
References TSuppressed::Copy(), fAddbackHighGainFrags, fAddbackHighGainHits, fAddbackLowGainFrags, fAddbackLowGainHits, fCycleStart, fGriffinBits, fGriffinHighGainHits, fSetCoreWave, fSuppressedAddbackHighGainFrags, fSuppressedAddbackHighGainHits, fSuppressedAddbackLowGainFrags, fSuppressedAddbackLowGainHits, fSuppressedHighGainHits, and fSuppressedLowGainHits.
Referenced by TGriffin(), and operator=().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 34 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), and GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected inherited
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 65 of file TSuppressed.h.
References TDetector::GetHitVector(), and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), and TTdrTigress::GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 90 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetector::GetHitVector(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), and TTdrTigress::GetSuppressedAddbackMultiplicity().
CTCorrectedEnergy()
Double_t TGriffin::CTCorrectedEnergy (const TGriffinHit *const hit_to_correct, const TGriffinHit *const other_hit, Bool_t time_constraint = true) static
Definition at line 608 of file TGriffin.cxx.
References TAnalysisOptions::AddbackWindow(), TGRSIOptions::AnalysisOptions(), DRED, TDetectorHit::GetChannel(), TDetectorHit::GetCrystal(), TChannel::GetCTCoeff(), TDetectorHit::GetDetector(), TDetectorHit::GetEnergy(), TGriffinHit::GetNoCTEnergy(), TDetectorHit::GetTime(), and RESET_COLOR.
Referenced by FixCrossTalk().
FixCrossTalk()
void TGriffin::FixCrossTalk (const EGainBits & gain_type) private
Definition at line 656 of file TGriffin.cxx.
References TGRSIOptions::AnalysisOptions(), CTCorrectedEnergy(), GetHitVector(), SetCrossTalk(), and TDetectorHit::SetEnergy().
Referenced by FixHighGainCrossTalk(), FixLowGainCrossTalk(), GetAddbackMultiplicity(), GetGriffinHit(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), and GetSuppressedMultiplicity().
FixHighGainCrossTalk()
void TGriffin::FixHighGainCrossTalk ()
Definition at line 651 of file TGriffin.cxx.
References FixCrossTalk(), and kHighGain.
FixLowGainCrossTalk()
void TGriffin::FixLowGainCrossTalk ()
Definition at line 646 of file TGriffin.cxx.
References FixCrossTalk(), and kLowGain.
GetAddbackCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TGriffin::GetAddbackCriterion () const inline
Definition at line 76 of file TGriffin.h.
References fAddbackCriterion.
GetAddbackFragVector()
std::vector< UShort_t > & TGriffin::GetAddbackFragVector (const EGainBits & gain_type) private
!
Definition at line 341 of file TGriffin.cxx.
References fAddbackHighGainFrags, fAddbackLowGainFrags, kHighGain, and kLowGain.
Referenced by GetAddbackMultiplicity(), GetNAddbackFrags(), and ResetAddback().
GetAddbackHighGainHit()
TGriffinHit * TGriffin::GetAddbackHighGainHit (const int & i)
Definition at line 460 of file TGriffin.cxx.
References GetAddbackHit(), and kHighGain.
GetAddbackHighGainMultiplicity()
Short_t TGriffin::GetAddbackHighGainMultiplicity ()
Definition at line 420 of file TGriffin.cxx.
References GetAddbackMultiplicity(), and kHighGain.
GetAddbackHit() [1/2]
TGriffinHit * TGriffin::GetAddbackHit (const int & i) inline
Definition at line 86 of file TGriffin.h.
References GetAddbackHit(), and GetDefaultGainType().
Referenced by DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), GetAddbackHighGainHit(), GetAddbackHit(), and GetAddbackLowGainHit().
GetAddbackHit() [2/2]
TGriffinHit * TGriffin::GetAddbackHit (const int & i, const EGainBits & gain_type) private
Definition at line 465 of file TGriffin.cxx.
References GetAddbackMultiplicity(), and GetAddbackVector().
GetAddbackLowGainHit()
TGriffinHit * TGriffin::GetAddbackLowGainHit (const int & i)
Definition at line 455 of file TGriffin.cxx.
References GetAddbackHit(), and kLowGain.
GetAddbackLowGainMultiplicity()
Short_t TGriffin::GetAddbackLowGainMultiplicity ()
Definition at line 415 of file TGriffin.cxx.
References GetAddbackMultiplicity(), and kLowGain.
GetAddbackMultiplicity() [1/2]
Short_t TGriffin::GetAddbackMultiplicity () inline
Definition at line 83 of file TGriffin.h.
References GetAddbackMultiplicity(), and GetDefaultGainType().
Referenced by DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), GetAddbackHighGainMultiplicity(), GetAddbackHit(), GetAddbackLowGainMultiplicity(), and GetAddbackMultiplicity().
GetAddbackMultiplicity() [2/2]
Short_t TGriffin::GetAddbackMultiplicity (const EGainBits & gain_type) private
Definition at line 425 of file TGriffin.cxx.
References TSuppressed::CreateAddback(), FixCrossTalk(), GetAddbackFragVector(), GetAddbackVector(), GetHitVector(), IsAddbackSet(), IsCrossTalkSet(), and SetAddback().
GetAddbackVector()
std::vector< TDetectorHit * > & TGriffin::GetAddbackVector (const EGainBits & gain_type) private
!
Definition at line 332 of file TGriffin.cxx.
References fAddbackHighGainHits, fAddbackLowGainHits, kHighGain, and kLowGain.
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), and ResetAddback().
GetColorFromNumber()
const char * TGriffin::GetColorFromNumber (int number) static
Definition at line 677 of file TGriffin.cxx.
Referenced by CrossTalkFix().
GetDefaultGainType()
static EGainBits TGriffin::GetDefaultGainType () inline static
Definition at line 165 of file TGriffin.h.
References fDefaultGainType.
Referenced by GetAddbackHit(), GetAddbackMultiplicity(), GetGriffinHit(), GetMultiplicity(), GetNAddbackFrags(), GetNSuppressedAddbackFrags(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), GetSuppressedMultiplicity(), ResetAddback(), ResetSuppressed(), and ResetSuppressedAddback().
GetDetectorPosition()
TVector3 TGriffin::GetDetectorPosition (int DetNbr) static
!
Definition at line 546 of file TGriffin.cxx.
References gCloverPosition.
GetGriffinHighGainHit()
TGriffinHit * TGriffin::GetGriffinHighGainHit (const int & i)
!
Definition at line 394 of file TGriffin.cxx.
References GetGriffinHit(), and kHighGain.
GetGriffinHit() [1/2]
TGriffinHit * TGriffin::GetGriffinHit (const int & i) inline
!
Definition at line 44 of file TGriffin.h.
References GetDefaultGainType(), and GetGriffinHit().
Referenced by ComptonHists(), AlphanumericHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), GetGriffinHighGainHit(), GetGriffinHit(), GetGriffinLowGainHit(), GetHit(), main(), and MakeAnalysisHistograms().
GetGriffinHit() [2/2]
TGriffinHit * TGriffin::GetGriffinHit (const int & i, const EGainBits & gain_type) private
!
Definition at line 399 of file TGriffin.cxx.
References FixCrossTalk(), GetHitVector(), and IsCrossTalkSet().
GetGriffinLowGainHit()
TGriffinHit * TGriffin::GetGriffinLowGainHit (const int & i)
!
Definition at line 389 of file TGriffin.cxx.
References GetGriffinHit(), and kLowGain.
GetHighGainMultiplicity()
Short_t TGriffin::GetHighGainMultiplicity () const inline
Definition at line 48 of file TGriffin.h.
References fGriffinHighGainHits.
Referenced by Print().
GetHit() [1/2]
TDetectorHit * TGriffin::GetHit (const int & idx)
Definition at line 384 of file TGriffin.cxx.
References GetGriffinHit().
Referenced by MakeAnalysisHistograms().
GetHit() [2/2]
TDetectorHit * TDetector::GetHit (const int & index) const virtual
Reimplemented from TDetector.
Definition at line 74 of file TDetector.cxx.
GetHitVector() [1/3]
const std::vector< TDetectorHit * > & TGriffin::GetHitVector () const inline override private virtual
!
Reimplemented from TDetector.
Definition at line 183 of file TGriffin.h.
References fDefaultGainType, and GetHitVector().
Referenced by AddFragment(), FixCrossTalk(), GetAddbackMultiplicity(), GetGriffinHit(), GetHitVector(), GetSuppressedAddbackMultiplicity(), and GetSuppressedMultiplicity().
GetHitVector() [2/3]
std::vector< TDetectorHit * > & TGriffin::GetHitVector (const EGainBits & gain_type) private
!
Definition at line 323 of file TGriffin.cxx.
References fGriffinHighGainHits, fGriffinLowGainHits, kHighGain, and kLowGain.
GetHitVector() [3/3]
const std::vector< TDetectorHit * > & TGriffin::GetHitVector (const EGainBits & gain_type) const private
!
Definition at line 314 of file TGriffin.cxx.
References fGriffinHighGainHits, fGriffinLowGainHits, kHighGain, and kLowGain.
GetLowGainMultiplicity()
Short_t TGriffin::GetLowGainMultiplicity () const inline
Definition at line 47 of file TGriffin.h.
References fGriffinLowGainHits.
Referenced by Print().
GetMultiplicity() [1/2]
Short_t TGriffin::GetMultiplicity () const inline override virtual
Reimplemented from TDetector.
Definition at line 49 of file TGriffin.h.
References GetDefaultGainType(), and GetMultiplicity().
Referenced by ComptonHists(), AlphanumericHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), GetMultiplicity(), main(), and MakeAnalysisHistograms().
GetMultiplicity() [2/2]
Short_t TGriffin::GetMultiplicity (const EGainBits & gain_type) const private
Definition at line 305 of file TGriffin.cxx.
References fGriffinHighGainHits, fGriffinLowGainHits, kHighGain, and kLowGain.
GetNAddbackFrags() [1/2]
UShort_t TGriffin::GetNAddbackFrags (const size_t & idx) inline
Definition at line 93 of file TGriffin.h.
References GetDefaultGainType(), and GetNAddbackFrags().
Referenced by GetNAddbackFrags(), GetNHighGainAddbackFrags(), and GetNLowGainAddbackFrags().
GetNAddbackFrags() [2/2]
UShort_t TGriffin::GetNAddbackFrags (const size_t & idx, const EGainBits & gain_type) private
Definition at line 592 of file TGriffin.cxx.
References GetAddbackFragVector().
GetNHighGainAddbackFrags()
UShort_t TGriffin::GetNHighGainAddbackFrags (const size_t & idx)
Definition at line 587 of file TGriffin.cxx.
References GetNAddbackFrags(), and kHighGain.
GetNHighGainSuppressedAddbackFrags()
UShort_t TGriffin::GetNHighGainSuppressedAddbackFrags (const size_t & idx)
Definition at line 771 of file TGriffin.cxx.
References GetNSuppressedAddbackFrags(), and kHighGain.
GetNLowGainAddbackFrags()
UShort_t TGriffin::GetNLowGainAddbackFrags (const size_t & idx)
Definition at line 582 of file TGriffin.cxx.
References GetNAddbackFrags(), and kLowGain.
GetNLowGainSuppressedAddbackFrags()
UShort_t TGriffin::GetNLowGainSuppressedAddbackFrags (const size_t & idx)
Definition at line 766 of file TGriffin.cxx.
References GetNSuppressedAddbackFrags(), and kLowGain.
GetNSuppressedAddbackFrags() [1/2]
UShort_t TGriffin::GetNSuppressedAddbackFrags (const size_t & idx) inline
Definition at line 128 of file TGriffin.h.
References GetDefaultGainType(), and GetNSuppressedAddbackFrags().
Referenced by CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), GetNHighGainSuppressedAddbackFrags(), GetNLowGainSuppressedAddbackFrags(), and GetNSuppressedAddbackFrags().
GetNSuppressedAddbackFrags() [2/2]
UShort_t TGriffin::GetNSuppressedAddbackFrags (const size_t & idx, const EGainBits & gain_type) private
Definition at line 929 of file TGriffin.cxx.
References GetSuppressedAddbackFragVector().
GetPosition()
TVector3 TGriffin::GetPosition (int DetNbr, int CryNbr = 5, double dist = 110.0) static
!
Definition at line 514 of file TGriffin.cxx.
References gCloverPosition.
Referenced by AngleCombinations(), ClassImp(), ComptonHists(), TAngularCorrelation::GenerateAngleMap(), TAngularCorrelation::GenerateIndexMap(), and TGriffinHit::GetPosition().
GetSuppressedAddbackFragVector()
std::vector< UShort_t > & TGriffin::GetSuppressedAddbackFragVector (const EGainBits & gain_type) private
!
Definition at line 794 of file TGriffin.cxx.
References fSuppressedAddbackHighGainFrags, fSuppressedAddbackLowGainFrags, kHighGain, and kLowGain.
Referenced by GetNSuppressedAddbackFrags(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedAddbackHighGainHit()
TGriffinHit * TGriffin::GetSuppressedAddbackHighGainHit (const int & i)
Definition at line 742 of file TGriffin.cxx.
References GetSuppressedAddbackHit(), and kHighGain.
GetSuppressedAddbackHighGainMultiplicity()
Short_t TGriffin::GetSuppressedAddbackHighGainMultiplicity (const TBgo * bgo)
Definition at line 732 of file TGriffin.cxx.
References GetSuppressedAddbackMultiplicity(), and kHighGain.
GetSuppressedAddbackHit() [1/2]
TGriffinHit * TGriffin::GetSuppressedAddbackHit (const int & i) inline
Definition at line 121 of file TGriffin.h.
References GetDefaultGainType(), and GetSuppressedAddbackHit().
Referenced by AngularCorrelationHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GetSuppressedAddbackHighGainHit(), GetSuppressedAddbackHit(), and GetSuppressedAddbackLowGainHit().
GetSuppressedAddbackHit() [2/2]
TGriffinHit * TGriffin::GetSuppressedAddbackHit (const int & i, const EGainBits & gain_type) private
Definition at line 864 of file TGriffin.cxx.
References FixCrossTalk(), GetSuppressedAddbackVector(), and IsCrossTalkSet().
GetSuppressedAddbackLowGainHit()
TGriffinHit * TGriffin::GetSuppressedAddbackLowGainHit (const int & i)
Definition at line 737 of file TGriffin.cxx.
References GetSuppressedAddbackHit(), and kLowGain.
GetSuppressedAddbackLowGainMultiplicity()
Short_t TGriffin::GetSuppressedAddbackLowGainMultiplicity (const TBgo * bgo)
Definition at line 727 of file TGriffin.cxx.
References GetSuppressedAddbackMultiplicity(), and kLowGain.
GetSuppressedAddbackMultiplicity() [1/2]
Short_t TGriffin::GetSuppressedAddbackMultiplicity (const TBgo * bgo) inline
Definition at line 118 of file TGriffin.h.
References GetDefaultGainType(), and GetSuppressedAddbackMultiplicity().
Referenced by AngularCorrelationHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), GetSuppressedAddbackHighGainMultiplicity(), GetSuppressedAddbackLowGainMultiplicity(), and GetSuppressedAddbackMultiplicity().
GetSuppressedAddbackMultiplicity() [2/2]
Short_t TGriffin::GetSuppressedAddbackMultiplicity (const TBgo * bgo, const EGainBits & gain_type) private
Automatically builds the suppressed addback hits using the fAddbackCriterion (if the size of the fAddbackHits vector is zero) and return the number of suppressed addback hits.
Definition at line 880 of file TGriffin.cxx.
References TSuppressed::CreateSuppressedAddback(), FixCrossTalk(), GetHitVector(), GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), IsCrossTalkSet(), IsSuppressedAddbackSet(), and SetSuppressedAddback().
GetSuppressedAddbackVector()
std::vector< TDetectorHit * > & TGriffin::GetSuppressedAddbackVector (const EGainBits & gain_type) private
!
Definition at line 785 of file TGriffin.cxx.
References fSuppressedAddbackHighGainHits, fSuppressedAddbackLowGainHits, kHighGain, and kLowGain.
Referenced by GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
GetSuppressedHighGainHit()
TGriffinHit * TGriffin::GetSuppressedHighGainHit (const int & i)
!
Definition at line 693 of file TGriffin.cxx.
References GetSuppressedHit(), and kHighGain.
GetSuppressedHighGainMultiplicity()
Short_t TGriffin::GetSuppressedHighGainMultiplicity (const TBgo * bgo)
Definition at line 703 of file TGriffin.cxx.
References GetSuppressedMultiplicity(), and kHighGain.
GetSuppressedHit() [1/2]
TGriffinHit * TGriffin::GetSuppressedHit (const int & i) inline
!
Definition at line 107 of file TGriffin.h.
References GetDefaultGainType(), and GetSuppressedHit().
Referenced by AngularCorrelationHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), GetSuppressedHighGainHit(), GetSuppressedHit(), and GetSuppressedLowGainHit().
GetSuppressedHit() [2/2]
TGriffinHit * TGriffin::GetSuppressedHit (const int & i, const EGainBits & gain_type) private
!
Definition at line 803 of file TGriffin.cxx.
References FixCrossTalk(), GetSuppressedVector(), and IsCrossTalkSet().
GetSuppressedLowGainHit()
TGriffinHit * TGriffin::GetSuppressedLowGainHit (const int & i)
!
Definition at line 688 of file TGriffin.cxx.
References GetSuppressedHit(), and kLowGain.
GetSuppressedLowGainMultiplicity()
Short_t TGriffin::GetSuppressedLowGainMultiplicity (const TBgo * bgo)
Definition at line 698 of file TGriffin.cxx.
References GetSuppressedMultiplicity(), and kLowGain.
GetSuppressedMultiplicity() [1/2]
Short_t TGriffin::GetSuppressedMultiplicity (const TBgo * bgo) inline
Definition at line 110 of file TGriffin.h.
References GetDefaultGainType(), and GetSuppressedMultiplicity().
Referenced by AngularCorrelationHelper::Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), GetSuppressedHighGainMultiplicity(), GetSuppressedLowGainMultiplicity(), and GetSuppressedMultiplicity().
GetSuppressedMultiplicity() [2/2]
Short_t TGriffin::GetSuppressedMultiplicity (const TBgo * bgo, const EGainBits & gain_type) private
Automatically builds the suppressed hits using the fSuppressionCriterion and returns the number of suppressed hits
Definition at line 819 of file TGriffin.cxx.
References TSuppressed::CreateSuppressed(), FixCrossTalk(), GetHitVector(), GetSuppressedVector(), IsCrossTalkSet(), IsSuppressed(), and SetSuppressed().
GetSuppressedVector()
std::vector< TDetectorHit * > & TGriffin::GetSuppressedVector (const EGainBits & gain_type) private
!
Definition at line 776 of file TGriffin.cxx.
References fSuppressedHighGainHits, fSuppressedLowGainHits, kHighGain, and kLowGain.
Referenced by GetSuppressedHit(), GetSuppressedMultiplicity(), and ResetSuppressed().
GetSuppressionCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TGriffin::GetSuppressionCriterion () const inline
Definition at line 100 of file TGriffin.h.
References fSuppressionCriterion.
IsAddbackSet()
bool TGriffin::IsAddbackSet (const EGainBits & gain_type) const
Definition at line 350 of file TGriffin.cxx.
References kHighGain, kIsHighGainAddbackSet, kIsLowGainAddbackSet, kLowGain, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), and Print().
IsCrossTalkSet()
bool TGriffin::IsCrossTalkSet (const EGainBits & gain_type) const
Definition at line 359 of file TGriffin.cxx.
References kHighGain, kIsHighGainCrossTalkSet, kIsLowGainCrossTalkSet, kLowGain, and TestBitNumber().
Referenced by GetAddbackMultiplicity(), GetGriffinHit(), GetSuppressedAddbackHit(), GetSuppressedAddbackMultiplicity(), GetSuppressedHit(), GetSuppressedMultiplicity(), and Print().
IsSuppressed()
bool TGriffin::IsSuppressed (const EGainBits & gain_type) const
Definition at line 708 of file TGriffin.cxx.
References kHighGain, kIsHighGainSuppressed, kIsLowGainSuppressed, kLowGain, and TestBitNumber().
Referenced by GetSuppressedMultiplicity().
IsSuppressedAddbackSet()
bool TGriffin::IsSuppressedAddbackSet (const EGainBits & gain_type) const
Definition at line 747 of file TGriffin.cxx.
References kHighGain, kIsHighGainSuppressedAddbackSet, kIsLowGainSuppressedAddbackSet, kLowGain, and TestBitNumber().
Referenced by GetSuppressedAddbackMultiplicity().
operator=()
TGriffin & TGriffin::operator= (const TGriffin & rhs)
!
Definition at line 290 of file TGriffin.cxx.
References Copy().
Print() [1/2]
void TGriffin::Print (Option_t * opt = "") const override
!
Definition at line 249 of file TGriffin.cxx.
References Print().
Referenced by Print(), and Print().
Print() [2/2]
void TGriffin::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 254 of file TGriffin.cxx.
References fAddbackHighGainHits, fAddbackLowGainHits, fCycleStart, fGriffinHighGainHits, fGriffinLowGainHits, GetHighGainMultiplicity(), GetLowGainMultiplicity(), IsAddbackSet(), IsCrossTalkSet(), kHighGain, kLowGain, and Print().
ResetAddback() [1/2]
void TGriffin::ResetAddback () inline
!
Definition at line 90 of file TGriffin.h.
References GetDefaultGainType(), and ResetAddback().
Referenced by ComptonHists(), ResetAddback(), ResetHighGainAddback(), and ResetLowGainAddback().
ResetAddback() [2/2]
void TGriffin::ResetAddback (const EGainBits & gain_type) private
!
Definition at line 571 of file TGriffin.cxx.
References GetAddbackFragVector(), GetAddbackVector(), SetAddback(), and SetCrossTalk().
ResetFlags()
void TGriffin::ResetFlags () const
Definition at line 556 of file TGriffin.cxx.
References fGriffinBits.
ResetHighGainAddback()
void TGriffin::ResetHighGainAddback ()
!
Definition at line 566 of file TGriffin.cxx.
References kLowGain, and ResetAddback().
ResetHighGainSuppressed()
void TGriffin::ResetHighGainSuppressed ()
!
Definition at line 722 of file TGriffin.cxx.
References kHighGain, and ResetSuppressed().
ResetHighGainSuppressedAddback()
void TGriffin::ResetHighGainSuppressedAddback ()
!
Definition at line 761 of file TGriffin.cxx.
References kHighGain, and ResetSuppressedAddback().
ResetLowGainAddback()
void TGriffin::ResetLowGainAddback ()
!
Definition at line 561 of file TGriffin.cxx.
References kLowGain, and ResetAddback().
ResetLowGainSuppressed()
void TGriffin::ResetLowGainSuppressed ()
!
Definition at line 717 of file TGriffin.cxx.
References kLowGain, and ResetSuppressed().
ResetLowGainSuppressedAddback()
void TGriffin::ResetLowGainSuppressedAddback ()
!
Definition at line 756 of file TGriffin.cxx.
References kLowGain, and ResetSuppressedAddback().
ResetSuppressed() [1/2]
void TGriffin::ResetSuppressed () inline
!
Definition at line 114 of file TGriffin.h.
References GetDefaultGainType(), and ResetSuppressed().
Referenced by ResetHighGainSuppressed(), ResetLowGainSuppressed(), and ResetSuppressed().
ResetSuppressed() [2/2]
void TGriffin::ResetSuppressed (const EGainBits & gain_type) private
!
Definition at line 854 of file TGriffin.cxx.
References GetSuppressedVector(), and SetSuppressed().
ResetSuppressedAddback() [1/2]
void TGriffin::ResetSuppressedAddback () inline
!
Definition at line 125 of file TGriffin.h.
References GetDefaultGainType(), and ResetSuppressedAddback().
Referenced by ResetHighGainSuppressedAddback(), ResetLowGainSuppressedAddback(), and ResetSuppressedAddback().
ResetSuppressedAddback() [2/2]
void TGriffin::ResetSuppressedAddback (const EGainBits & gain_type) private
!
Definition at line 918 of file TGriffin.cxx.
References GetSuppressedAddbackFragVector(), GetSuppressedAddbackVector(), and SetSuppressedAddback().
SetAddback()
void TGriffin::SetAddback (const EGainBits & gain_type, bool flag = true) const private
Definition at line 368 of file TGriffin.cxx.
References kHighGain, kIsHighGainAddbackSet, kIsLowGainAddbackSet, kLowGain, and SetBitNumber().
Referenced by GetAddbackMultiplicity(), and ResetAddback().
SetAddbackCriterion()
void TGriffin::SetAddbackCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 72 of file TGriffin.h.
References fAddbackCriterion.
SetBitNumber()
void TGriffin::SetBitNumber (EGriffinBits bit, Bool_t set) const private
Definition at line 602 of file TGriffin.cxx.
References fGriffinBits, and TTransientBits< T >::SetBit().
Referenced by SetAddback(), SetCrossTalk(), SetSuppressed(), and SetSuppressedAddback().
SetCoreWave()
static bool TGriffin::SetCoreWave () inline static
!
Definition at line 163 of file TGriffin.h.
References fSetCoreWave.
SetCrossTalk()
void TGriffin::SetCrossTalk (const EGainBits & gain_type, bool flag = true) const private
Definition at line 376 of file TGriffin.cxx.
References kHighGain, kIsHighGainCrossTalkSet, kIsLowGainCrossTalkSet, kLowGain, and SetBitNumber().
Referenced by FixCrossTalk(), and ResetAddback().
SetDefaultGainType()
void TGriffin::SetDefaultGainType (const EGainBits & gain_type) static
Definition at line 296 of file TGriffin.cxx.
References fDefaultGainType, kHighGain, and kLowGain.
SetSuppressed()
void TGriffin::SetSuppressed (const EGainBits & gain_type, bool flag = true) const private
Definition at line 846 of file TGriffin.cxx.
References kHighGain, kIsHighGainSuppressed, kIsLowGainSuppressed, kLowGain, and SetBitNumber().
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
SetSuppressedAddback()
void TGriffin::SetSuppressedAddback (const EGainBits & gain_type, bool flag = true) const private
Definition at line 910 of file TGriffin.cxx.
References kHighGain, kIsHighGainSuppressedAddbackSet, kIsLowGainSuppressedAddbackSet, kLowGain, and SetBitNumber().
Referenced by GetSuppressedAddbackMultiplicity(), and ResetSuppressedAddback().
SetSuppressionCriterion()
void TGriffin::SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 96 of file TGriffin.h.
References fSuppressionCriterion.
SuppressionCriterion()
bool TGriffin::SuppressionCriterion (const TDetectorHit * hit, const TDetectorHit * bgoHit) inline override virtual
Reimplemented from TSuppressed.
Definition at line 102 of file TGriffin.h.
References fSuppressionCriterion.
TestBitNumber()
Bool_t TGriffin::TestBitNumber (EGriffinBits bit) const inline private
Definition at line 171 of file TGriffin.h.
References fGriffinBits, and TTransientBits< T >::TestBit().
Referenced by IsAddbackSet(), IsCrossTalkSet(), IsSuppressed(), and IsSuppressedAddbackSet().
Member Data Documentation
fAddbackCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TGriffin::fAddbackCriterion = DefaultGriffinAddback static private
Definition at line 132 of file TGriffin.h.
Referenced by AddbackCriterion(), GetAddbackCriterion(), and SetAddbackCriterion().
fAddbackHighGainFrags
std::vector<UShort_t> TGriffin::fAddbackHighGainFrags mutable private
! Number of crystals involved in creating in the addback hit
Definition at line 150 of file TGriffin.h.
Referenced by Clear(), Copy(), and GetAddbackFragVector().
fAddbackHighGainHits
std::vector<TDetectorHit*> TGriffin::fAddbackHighGainHits mutable private
! Used to create addback hits on the fly
Definition at line 148 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), GetAddbackVector(), and Print().
fAddbackLowGainFrags
std::vector<UShort_t> TGriffin::fAddbackLowGainFrags mutable private
! Number of crystals involved in creating in the addback hit
Definition at line 149 of file TGriffin.h.
Referenced by Clear(), Copy(), and GetAddbackFragVector().
fAddbackLowGainHits
std::vector<TDetectorHit*> TGriffin::fAddbackLowGainHits mutable private
! Used to create addback hits on the fly
Definition at line 147 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), GetAddbackVector(), and Print().
fCycleStart
long TGriffin::fCycleStart private
! The start of the cycle
Definition at line 144 of file TGriffin.h.
Referenced by Clear(), Copy(), and Print().
fDefaultGainType
TGriffin::EGainBits TGriffin::fDefaultGainType = TGriffin::EGainBits::kLowGain static private
Definition at line 160 of file TGriffin.h.
Referenced by GetDefaultGainType(), GetHitVector(), and SetDefaultGainType().
fGriffinBits
TTransientBits<UChar_t> TGriffin::fGriffinBits mutable private
Definition at line 145 of file TGriffin.h.
Referenced by ClearStatus(), Copy(), ResetFlags(), SetBitNumber(), and TestBitNumber().
fGriffinHighGainHits
std::vector<TDetectorHit*> TGriffin::fGriffinHighGainHits private
Definition at line 137 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), GetHighGainMultiplicity(), GetHitVector(), GetHitVector(), GetMultiplicity(), and Print().
fGriffinLowGainHits
std::vector<TDetectorHit*>& TGriffin::fGriffinLowGainHits = fHits private
! Reference to default hit vector (needs to be transient)
Definition at line 136 of file TGriffin.h.
Referenced by GetHitVector(), GetHitVector(), GetLowGainMultiplicity(), GetMultiplicity(), and Print().
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 84 of file TDetector.h.
Referenced by TDetector::~TDetector(), TSiLi::AddCluster(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TDetector::AddHit(), TCSM::BuildHits(), TEmma::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TSharc::Clear(), TTrific::Clear(), TDetector::Clear(), TEmma::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TTrific::GetMultiplicity(), TSharc::GetSize(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
fSetCoreWave
bool TGriffin::fSetCoreWave = false static private
! Flag for Waveforms ON/OFF
Definition at line 141 of file TGriffin.h.
Referenced by Copy(), and SetCoreWave().
fSuppressedAddbackHighGainFrags
std::vector<UShort_t> TGriffin::fSuppressedAddbackHighGainFrags mutable private
! Number of crystals involved in creating in the suppressed addback hit
Definition at line 158 of file TGriffin.h.
Referenced by Clear(), Copy(), and GetSuppressedAddbackFragVector().
fSuppressedAddbackHighGainHits
std::vector<TDetectorHit*> TGriffin::fSuppressedAddbackHighGainHits mutable private
! Used to create suppressed addback hits on the fly
Definition at line 156 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), and GetSuppressedAddbackVector().
fSuppressedAddbackLowGainFrags
std::vector<UShort_t> TGriffin::fSuppressedAddbackLowGainFrags mutable private
! Number of crystals involved in creating in the suppressed addback hit
Definition at line 157 of file TGriffin.h.
Referenced by Clear(), Copy(), and GetSuppressedAddbackFragVector().
fSuppressedAddbackLowGainHits
std::vector<TDetectorHit*> TGriffin::fSuppressedAddbackLowGainHits mutable private
! Used to create suppressed addback hits on the fly
Definition at line 155 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), and GetSuppressedAddbackVector().
fSuppressedHighGainHits
std::vector<TDetectorHit*> TGriffin::fSuppressedHighGainHits private
! The set of suppressed crystal hits
Definition at line 153 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), and GetSuppressedVector().
fSuppressedLowGainHits
std::vector<TDetectorHit*> TGriffin::fSuppressedLowGainHits private
! The set of suppressed crystal hits
Definition at line 152 of file TGriffin.h.
Referenced by ~TGriffin(), Clear(), Copy(), and GetSuppressedVector().
fSuppressionCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TGriffin::fSuppressionCriterion = DefaultGriffinSuppression static private
Definition at line 133 of file TGriffin.h.
Referenced by GetSuppressionCriterion(), SetSuppressionCriterion(), and SuppressionCriterion().
gCloverPosition
TVector3 TGriffin::gCloverPosition static private
! Position of each HPGe Clover
Definition at line 61 of file TGriffin.h.
Referenced by GetDetectorPosition(), and GetPosition().