GRSISort: GNotifier Class Reference
GNotifier Class Reference
Detailed Description
Definition at line 12 of file GNotifier.h.
Public Member Functions
~GNotifier ()=default
void Clear (Option_t *="") override
bool Notify () override
void Print (Option_t *="") const override
Static Public Member Functions
template<typename T >
static void AddCallback (T callback)
static void AddCallback (void(*func)())
static GNotifier * Get ()
Private Member Functions
GNotifier ()=default
GNotifier (const GNotifier &)=default
GNotifier (GNotifier &&) noexcept=default
GNotifier & operator= (const GNotifier &)=default
GNotifier & operator= (GNotifier &&) noexcept=default
Private Attributes
std::vector< std::function< void()> > fCallbacks
Static Private Attributes
static GNotifier * fGNotifier = nullptr
Constructor & Destructor Documentation
~GNotifier()
GNotifier::~GNotifier () default
GNotifier() [1/3]
GNotifier::GNotifier () private default
Referenced by Get().
GNotifier() [2/3]
GNotifier::GNotifier (const GNotifier &) private default
GNotifier() [3/3]
GNotifier::GNotifier (GNotifier &&) private default noexcept
Member Function Documentation
AddCallback() [1/2]
template<typename T > static void GNotifier::AddCallback (T callback) inline static
Definition at line 25 of file GNotifier.h.
References fCallbacks, and Get().
AddCallback() [2/2]
static void GNotifier::AddCallback (void(* func)()) inline static
Definition at line 30 of file GNotifier.h.
References fCallbacks, and Get().
Clear()
void GNotifier::Clear (Option_t * = "") inline override
Definition at line 18 of file GNotifier.h.
Get()
GNotifier * GNotifier::Get () static
Definition at line 11 of file GNotifier.cxx.
References GNotifier(), and fGNotifier.
Referenced by AddCallback(), and AddCallback().
Notify()
bool GNotifier::Notify () override
Definition at line 19 of file GNotifier.cxx.
References fCallbacks.
operator=() [1/2]
GNotifier & GNotifier::operator= (const GNotifier &) private default
operator=() [2/2]
GNotifier & GNotifier::operator= (GNotifier &&) private default noexcept
Print()
void GNotifier::Print (Option_t * = "") const inline override
Definition at line 17 of file GNotifier.h.
Member Data Documentation
fCallbacks
std::vector<std::function<void()> > GNotifier::fCallbacks private
Definition at line 41 of file GNotifier.h.
Referenced by AddCallback(), AddCallback(), and Notify().
fGNotifier
GNotifier * GNotifier::fGNotifier = nullptr static private
Definition at line 44 of file GNotifier.h.
Referenced by Get().