GRSISort: TEmma Class Reference
TEmma Class Reference
Detectors
Detailed Description
Definition at line 19 of file TEmma.h.
Public Member Functions
TEmma ()
TEmma (const TEmma &)
~TEmma () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TEmmaHit * GetAnodeHit (const int &i)
Short_t GetAnodeMultiplicity () const
TEmmaHit * GetEmmaHit (const int &i) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
TEmmaHit * GetICHit (const int &i)
Short_t GetICMultiplicity () const
virtual Short_t GetMultiplicity () const
TEmmaHit * GetSiHit (const int &i)
Short_t GetSiMultiplicity () const
TEmmaHit * GetSSBHit (const int &i)
Short_t GetSSBMultiplicity () const
TEmmaHit * GetTdcHit (const int &i)
Short_t GetTdcMultiplicity () const
TEmmaHit * GetTriggerHit (const int &i)
Short_t GetTriggerMultiplicity () const
TEmma & operator= (const TEmma &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (double left, double right, double top, double bottom, double delayL, double delayR, double delayT, double delayB)
Protected Attributes
std::vector< TDetectorHit * > fHits
Private Attributes
std::vector< TEmmaHit > fEmmaAnodeHits
std::vector< TEmmaHit > fEmmaICHits
std::vector< TEmmaHit > fEmmaSiHits
std::vector< TEmmaHit > fEmmaSSBHits
std::vector< TEmmaHit > fEmmaTdcHits
std::vector< TEmmaHit > fEmmaTriggerHits
Static Private Attributes
static double fAnodeTrigger = 0
static short fFail = 0
static double fICEnergy = 0
static double fXdiff = 0
static double fXlength = 80.
static double fXsum = 0
static double fYdiff = 0
static double fYlength = 30.
static double fYsum = 0
Constructor & Destructor Documentation
TEmma() [1/2]
TEmma::TEmma ()
Definition at line 30 of file TEmma.cxx.
References Clear().
TEmma() [2/2]
TEmma::TEmma (const TEmma & rhs)
Definition at line 38 of file TEmma.cxx.
References Copy().
~TEmma()
TEmma::~TEmma () override
Definition at line 57 of file TEmma.cxx.
Member Function Documentation
AddFragment()
void TEmma::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 81 of file TEmma.cxx.
References TMnemonic::CollectedCharge(), fEmmaAnodeHits, fEmmaICHits, fEmmaSiHits, fEmmaSSBHits, fEmmaTdcHits, fEmmaTriggerHits, TChannel::GetMnemonic(), TMnemonic::kD, TMnemonic::kI, TMnemonic::kL, TMnemonic::kN, TMnemonic::kO, TMnemonic::kP, TMnemonic::kR, TMnemonic::kS, TMnemonic::kT, TMnemonic::kU, TMnemonic::kX, TMnemonic::OutputSensor(), TEmmaHit::SetTdcNumber(), and TMnemonic::SubSystem().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
BuildHits()
void TEmma::BuildHits () override virtual
!
Reimplemented from TDetector.
Definition at line 210 of file TEmma.cxx.
References fAnodeTrigger, fEmmaTdcHits, fFail, TDetector::fHits, TEmmaHit::GetBottom(), TEmmaHit::GetLeft(), TEmmaHit::GetRight(), TEmmaHit::GetTop(), TDetectorHit::SetAddress(), TEmmaHit::SetAnodeTrigger(), TEmmaHit::SetBottom(), TEmmaHit::SetFailedFill(), TEmmaHit::SetLeft(), TEmmaHit::SetRight(), TDetectorHit::SetTimeStamp(), and TEmmaHit::SetTop().
Clear()
void TEmma::Clear (Option_t * opt = "all") override
!
Definition at line 255 of file TEmma.cxx.
References TDetector::Clear(), fEmmaAnodeHits, fEmmaICHits, fEmmaSiHits, fEmmaSSBHits, fEmmaTdcHits, fEmmaTriggerHits, and TDetector::fHits.
Referenced by TEmma().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 68 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TEmma::Copy (TObject & rhs) const override
!
Definition at line 46 of file TEmma.cxx.
References TDetector::Copy(), fEmmaAnodeHits, fEmmaICHits, fEmmaSiHits, fEmmaSSBHits, fEmmaTdcHits, and fEmmaTriggerHits.
Referenced by TEmma(), and operator=().
GetAnodeHit()
TEmmaHit * TEmma::GetAnodeHit (const int & i)
Definition at line 160 of file TEmma.cxx.
References fEmmaAnodeHits, and GetAnodeMultiplicity().
GetAnodeMultiplicity()
Short_t TEmma::GetAnodeMultiplicity () const inline
Definition at line 41 of file TEmma.h.
References fEmmaAnodeHits.
Referenced by GetAnodeHit().
GetEmmaHit()
TEmmaHit * TEmma::GetEmmaHit (const int & i) const inline
Definition at line 27 of file TEmma.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), and MakeAnalysisHistograms().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetICHit()
TEmmaHit * TEmma::GetICHit (const int & i)
Definition at line 150 of file TEmma.cxx.
References fEmmaICHits, and GetICMultiplicity().
GetICMultiplicity()
Short_t TEmma::GetICMultiplicity () const inline
Definition at line 40 of file TEmma.h.
References fEmmaICHits.
Referenced by GetICHit().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin, and TTrific.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), main(), MakeAnalysisHistograms(), TTigress::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetPosition()
TVector3 TEmma::GetPosition (double left, double right, double top, double bottom, double delayL, double delayR, double delayT, double delayB) static
Definition at line 136 of file TEmma.cxx.
References fXlength, and fYlength.
Referenced by TEmmaHit::GetPosition(), and TEmmaHit::GetPosition().
GetSiHit()
TEmmaHit * TEmma::GetSiHit (const int & i)
Definition at line 180 of file TEmma.cxx.
References fEmmaSiHits, and GetSiMultiplicity().
GetSiMultiplicity()
Short_t TEmma::GetSiMultiplicity () const inline
Definition at line 43 of file TEmma.h.
References fEmmaSiHits.
Referenced by GetSiHit().
GetSSBHit()
TEmmaHit * TEmma::GetSSBHit (const int & i)
Definition at line 200 of file TEmma.cxx.
References fEmmaSSBHits, and GetSSBMultiplicity().
GetSSBMultiplicity()
Short_t TEmma::GetSSBMultiplicity () const inline
Definition at line 44 of file TEmma.h.
References fEmmaSSBHits.
Referenced by GetSSBHit().
GetTdcHit()
TEmmaHit * TEmma::GetTdcHit (const int & i)
Definition at line 170 of file TEmma.cxx.
References fEmmaTdcHits, and GetTdcMultiplicity().
GetTdcMultiplicity()
Short_t TEmma::GetTdcMultiplicity () const inline
Definition at line 42 of file TEmma.h.
References fEmmaTdcHits.
Referenced by GetTdcHit().
GetTriggerHit()
TEmmaHit * TEmma::GetTriggerHit (const int & i)
Definition at line 190 of file TEmma.cxx.
References fEmmaTriggerHits, and GetTriggerMultiplicity().
GetTriggerMultiplicity()
Short_t TEmma::GetTriggerMultiplicity () const inline
Definition at line 45 of file TEmma.h.
References fEmmaTriggerHits.
Referenced by GetTriggerHit().
operator=()
TEmma & TEmma::operator= (const TEmma & rhs)
!
Definition at line 75 of file TEmma.cxx.
References Copy().
Print() [1/2]
void TEmma::Print (Option_t * opt = "") const override
!
Prints out TEmma members, currently only prints multiplicity.
Definition at line 62 of file TEmma.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TEmma::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 68 of file TEmma.cxx.
References TDetector::fHits.
Member Data Documentation
fAnodeTrigger
double TEmma::fAnodeTrigger = 0 static private
!
Definition at line 59 of file TEmma.h.
Referenced by BuildHits().
fEmmaAnodeHits
std::vector<TEmmaHit> TEmma::fEmmaAnodeHits private
Definition at line 53 of file TEmma.h.
Referenced by AddFragment(), Clear(), Copy(), GetAnodeHit(), and GetAnodeMultiplicity().
fEmmaICHits
std::vector<TEmmaHit> TEmma::fEmmaICHits private
Definition at line 52 of file TEmma.h.
Referenced by AddFragment(), Clear(), Copy(), GetICHit(), and GetICMultiplicity().
fEmmaSiHits
std::vector<TEmmaHit> TEmma::fEmmaSiHits private
Definition at line 55 of file TEmma.h.
Referenced by AddFragment(), Clear(), Copy(), GetSiHit(), and GetSiMultiplicity().
fEmmaSSBHits
std::vector<TEmmaHit> TEmma::fEmmaSSBHits private
Definition at line 56 of file TEmma.h.
Referenced by AddFragment(), Clear(), Copy(), GetSSBHit(), and GetSSBMultiplicity().
fEmmaTdcHits
std::vector<TEmmaHit> TEmma::fEmmaTdcHits private
Definition at line 54 of file TEmma.h.
Referenced by AddFragment(), BuildHits(), Clear(), Copy(), GetTdcHit(), and GetTdcMultiplicity().
fEmmaTriggerHits
std::vector<TEmmaHit> TEmma::fEmmaTriggerHits private
Definition at line 57 of file TEmma.h.
Referenced by AddFragment(), Clear(), Copy(), GetTriggerHit(), and GetTriggerMultiplicity().
fFail
short TEmma::fFail = 0 static private
Definition at line 67 of file TEmma.h.
Referenced by BuildHits().
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 84 of file TDetector.h.
Referenced by TDetector::~TDetector(), TSiLi::AddCluster(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TDetector::AddHit(), TCSM::BuildHits(), BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TSharc::Clear(), TTrific::Clear(), TDetector::Clear(), Clear(), TDetector::ClearTransients(), TDetector::Copy(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TTrific::GetMultiplicity(), TSharc::GetSize(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Print(), TDescant::Print(), Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
fICEnergy
double TEmma::fICEnergy = 0 static private
!
Definition at line 60 of file TEmma.h.
fXdiff
double TEmma::fXdiff = 0 static private
Definition at line 61 of file TEmma.h.
fXlength
double TEmma::fXlength = 80. static private
Definition at line 65 of file TEmma.h.
Referenced by GetPosition().
fXsum
double TEmma::fXsum = 0 static private
Definition at line 62 of file TEmma.h.
fYdiff
double TEmma::fYdiff = 0 static private
Definition at line 63 of file TEmma.h.
fYlength
double TEmma::fYlength = 30. static private
Definition at line 66 of file TEmma.h.
Referenced by GetPosition().
fYsum
double TEmma::fYsum = 0 static private
Definition at line 64 of file TEmma.h.