GRSISort: TDemand Class Reference
TDemand Class Reference
Detectors
Detailed Description
Definition at line 18 of file TDemand.h.
Public Member Functions
TDemand ()
TDemand (const TDemand &)
TDemand (TDemand &&) noexcept=default
~TDemand () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TDemandHit * GetDemandHit (const int &i) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TDemand & operator= (const TDemand &)
TDemand & operator= (TDemand &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (const TDemandHit &)
static TVector3 GetPosition (int DetNbr)
static bool SetCoreWave ()
Private Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static bool fSetCoreWave
static const std::array< double, 6 > fXPositions = {55.5, 43.5, -43.5, -55.5, -43.5, 43.5}
static const std::array< double, 6 > fYPositions = {0, 45.5, 45.5, 0, -45.5, -45.5}
static const std::array< double, 6 > fZPositions = {93.9, 93.9, 93.9, 93.9, 93.9, 93.9}
Constructor & Destructor Documentation
TDemand() [1/3]
TDemand::TDemand ()
Definition at line 26 of file TDemand.cxx.
References TDetector::Clear().
TDemand() [2/3]
TDemand::TDemand (const TDemand & rhs)
Definition at line 31 of file TDemand.cxx.
References Copy().
TDemand() [3/3]
TDemand::TDemand (TDemand &&) default noexcept
~TDemand()
TDemand::~TDemand () override default
Member Function Documentation
AddFragment()
void TDemand::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 60 of file TDemand.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TDemand::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 34 of file TDemand.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::TAries(), TDemand(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TPaces::TPaces(), TSceptar::TSceptar(), TTAC::TTAC(), TZeroDegree::TZeroDegree(), TBgo::Clear(), TDescant::Clear(), TEagle::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TSharc2::Clear(), TSharc::Clear(), TSiLi::Clear(), TSuppressed::Clear(), TTdrPlastic::Clear(), TTdrSiLi::Clear(), TTigress::Clear(), TTrific::Clear(), and TTriFoil::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDemand::Copy (TObject & rhs) const override
!
Definition at line 36 of file TDemand.cxx.
References TDetector::Copy().
Referenced by TDemand(), and operator=().
GetDemandHit()
TDemandHit * TDemand::GetDemandHit (const int & i) const inline
Definition at line 27 of file TDemand.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition() [1/2]
TVector3 TDemand::GetPosition (const TDemandHit & hit) static
!
Definition at line 66 of file TDemand.cxx.
References TDetectorHit::GetDetector(), and GetPosition().
GetPosition() [2/2]
TVector3 TDemand::GetPosition (int DetNbr) static
!
Definition at line 71 of file TDemand.cxx.
References fXPositions, fYPositions, and fZPositions.
Referenced by GetPosition(), and TDemandHit::GetPosition().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TDemand & TDemand::operator= (const TDemand & rhs)
!
Definition at line 54 of file TDemand.cxx.
References Copy().
operator=() [2/2]
TDemand & TDemand::operator= (TDemand &&) default noexcept
Print() [1/2]
void TDemand::Print (Option_t * opt = "") const override
!
Prints out TDemand members, currently shows only multiplicity.
Definition at line 41 of file TDemand.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TDemand::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 47 of file TDemand.cxx.
References TDetector::GetMultiplicity().
SetCoreWave()
static bool TDemand::SetCoreWave () inline static
!
Definition at line 45 of file TDemand.h.
References fSetCoreWave.
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fSetCoreWave
bool TDemand::fSetCoreWave static private
! Flag for Waveforms ON/OFF
Definition at line 37 of file TDemand.h.
Referenced by SetCoreWave().
fXPositions
const std::array< double, 6 > TDemand::fXPositions = {55.5, 43.5, -43.5, -55.5, -43.5, 43.5} static private
Definition at line 22 of file TDemand.h.
Referenced by GetPosition().
fYPositions
const std::array< double, 6 > TDemand::fYPositions = {0, 45.5, 45.5, 0, -45.5, -45.5} static private
Definition at line 23 of file TDemand.h.
Referenced by GetPosition().
fZPositions
const std::array< double, 6 > TDemand::fZPositions = {93.9, 93.9, 93.9, 93.9, 93.9, 93.9} static private
Definition at line 24 of file TDemand.h.
Referenced by GetPosition().