GRSISort: TGenericDetector Class Reference
TGenericDetector Class Reference
Detectors
Detailed Description
Definition at line 14 of file TGenericDetector.h.
Public Member Functions
TGenericDetector ()
TGenericDetector (const TGenericDetector &)
TGenericDetector (TGenericDetector &&) noexcept=default
~TGenericDetector () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
TDetectorHit * GetGenericDetectorHit (const int &i) const
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TGenericDetector & operator= (const TGenericDetector &)
TGenericDetector & operator= (TGenericDetector &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Private Member Functions
void ClearStatus ()
Private Attributes
std::vector< TDetectorHit * > fHits
Constructor & Destructor Documentation
TGenericDetector() [1/3]
TGenericDetector::TGenericDetector ()
Definition at line 9 of file TGenericDetector.cxx.
References TDetector::Clear().
TGenericDetector() [2/3]
TGenericDetector::TGenericDetector (const TGenericDetector & rhs)
Definition at line 20 of file TGenericDetector.cxx.
References TDetector::Copy().
TGenericDetector() [3/3]
TGenericDetector::TGenericDetector (TGenericDetector &&) default noexcept
~TGenericDetector()
TGenericDetector::~TGenericDetector () override default
Member Function Documentation
AddFragment()
void TGenericDetector::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
This function creates TGenericDetectorHits for each fragment and stores them in separate front and back vectors
Reimplemented from TDetector.
Definition at line 25 of file TGenericDetector.cxx.
References TDetector::AddHit().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TDescant::AddFragment(), AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TEmma::BuildHits(), TSharc::BuildHits(), and TSharc2::BuildHits().
BuildHits()
void TGenericDetector::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 26 of file TGenericDetector.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 68 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::TAries(), TGenericDetector(), TPaces::TPaces(), TSceptar::TSceptar(), TTAC::TTAC(), TZeroDegree::TZeroDegree(), TSharc::Clear(), TSharc2::Clear(), TTrific::Clear(), TDescant::Clear(), TSiLi::Clear(), TTigress::Clear(), TTriFoil::Clear(), TTdrPlastic::Clear(), TEmma::Clear(), TRcmp::Clear(), TS3::Clear(), TEagle::Clear(), TBgo::Clear(), TSuppressed::Clear(), and TTdrSiLi::Clear().
ClearStatus()
void TGenericDetector::ClearStatus () inline private
Definition at line 34 of file TGenericDetector.h.
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override inherited
!
Definition at line 24 of file TDetector.cxx.
References TDetectorHit::Copy(), and TDetector::fHits.
Referenced by TAries::TAries(), TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector(), TSceptar::TSceptar(), TTAC::TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree::TZeroDegree(), TDescant::Copy(), TEmma::Copy(), TPaces::Copy(), TRcmp::Copy(), TRF::Copy(), TS3::Copy(), TSharc::Copy(), TSharc2::Copy(), TSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TEagle::Copy(), TBgo::Copy(), TSuppressed::Copy(), TTdrSiLi::Copy(), TTriFoil::Copy(), TAries::operator=(), TDetector::operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), TFippsTAC::operator=(), operator=(), TSceptar::operator=(), TTAC::operator=(), TTdrPlastic::operator=(), TTip::operator=(), TZeroDegree::operator=(), and TDetector::operator=().
GetGenericDetectorHit()
TDetectorHit * TGenericDetector::GetGenericDetectorHit (const int & i) const inline
Definition at line 28 of file TGenericDetector.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), TSharc2::GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TGenericDetector & TGenericDetector::operator= (const TGenericDetector & rhs)
Definition at line 14 of file TGenericDetector.cxx.
References TDetector::Copy().
operator=() [2/2]
TGenericDetector & TGenericDetector::operator= (TGenericDetector &&) default noexcept
Print() [1/2]
void TGenericDetector::Print (Option_t * opt = "") const override
!
Definition at line 37 of file TGenericDetector.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TGenericDetector::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 42 of file TGenericDetector.cxx.
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().