GRSISort: ExampleTreeSelector Class Reference
ExampleTreeSelector Class Reference
Selectors
Detailed Description
This selector shows how to create a tree with selected events (beta-tagged with gamma multiplicities of at least three), and selected information (suppressed addback energies, and beta-gamma timing differences).
Definition at line 33 of file ExampleTreeSelector.h.
Public Member Functions
ExampleTreeSelector (TTree *=nullptr)
virtual ~ExampleTreeSelector ()=default
void Begin (TTree *tree) override
void CreateHistograms ()
virtual void EndOfSort ()
void FillHistograms ()
Int_t GetEntry (Long64_t entry, Int_t getall=0) override
TList * GetOutputList () const override
std::string GetOutputPrefix () const
void Init (TTree *tree) override
void InitializeBranches (TTree *tree)
Bool_t Notify () override
Bool_t Process (Long64_t entry) override
void SetObject (TObject *obj) override
void SetOption (const char *option) override
void SetOutputPrefix (const char *prefix)
void SlaveBegin (TTree *tree) override
void SlaveTerminate () override
void Terminate () override
virtual Int_t Version () const
Protected Attributes
TGRSIMap< std::string, GCube * > fCube
std::map< std::string, TCutG * > fCuts
int64_t fEntry {0}
TGRSIMap< std::string, TH1 * > fH1
TGRSIMap< std::string, TH2 * > fH2
TGRSIMap< std::string, TH3 * > fH3
TGRSIMap< std::string, THnSparseF * > fHSparse
TPPG * fPpg {nullptr}
TRunInfo * fRunInfo {nullptr}
TGRSIMap< std::string, GHSym * > fSym
TGRSIMap< std::string, TTree * > fTree
Private Member Functions
void CheckSizes (const char *usage)
ClassDef (ExampleTreeSelector, 2)
Private Attributes
TAnalysisOptions * fAnalysisOptions {nullptr}
std::vector< double > fBetaGammaTiming
TTree * fChain {nullptr}
Int_t fFirstRunNumber {-1}
Int_t fFirstSubRunNumber {-1}
TGriffin * fGrif
TGriffinBgo * fGriffinBgo
std::string fOutputPrefix
TSceptar * fScep
std::vector< double > fSuppressedAddback
TZeroDegree * fZds
Static Private Attributes
static constexpr int fSizeLimit = 1073741822
Constructor & Destructor Documentation
ExampleTreeSelector()
ExampleTreeSelector::ExampleTreeSelector (TTree * = nullptr) inline explicit
Definition at line 35 of file ExampleTreeSelector.h.
References TGRSISelector::SetOutputPrefix().
~ExampleTreeSelector()
virtual ExampleTreeSelector::~ExampleTreeSelector () virtual default
Member Function Documentation
Begin()
void TGRSISelector::Begin (TTree * tree) override inherited
The Begin() function is called at the start of the query. When running with PROOF Begin() is only called on the client. The tree argument is deprecated (on PROOF 0 is passed).
Definition at line 36 of file TGRSISelector.cxx.
CheckSizes()
void TGRSISelector::CheckSizes (const char * usage) private inherited
Function to check size of objects in output list.
Definition at line 303 of file TGRSISelector.cxx.
References DRED, TGRSISelector::fSizeLimit, and RESET_COLOR.
Referenced by TGRSISelector::SlaveBegin(), TGRSISelector::SlaveTerminate(), and TGRSISelector::Terminate().
ClassDef()
ExampleTreeSelector::ClassDef (ExampleTreeSelector , 2) private
CreateHistograms()
void ExampleTreeSelector::CreateHistograms () virtual
Implements TGRSISelector.
Definition at line 5 of file ExampleTreeSelector.C.
References fBetaGammaTiming, TGRSISelector::fEntry, TGRSISelector::fH1, TGRSISelector::fH2, fSuppressedAddback, TGRSISelector::fTree, and TGRSISelector::GetOutputList().
EndOfSort()
virtual void TGRSISelector::EndOfSort () inline virtual inherited
Definition at line 60 of file TGRSISelector.h.
Referenced by TGRSISelector::SlaveTerminate().
FillHistograms()
void ExampleTreeSelector::FillHistograms () virtual
Implements TGRSISelector.
Definition at line 57 of file ExampleTreeSelector.C.
References fBetaGammaTiming, fGrif, fGriffinBgo, TGRSISelector::fH1, TGRSISelector::fH2, fScep, fSuppressedAddback, TGRSISelector::fTree, fZds, TDetector::GetMultiplicity(), TSceptar::GetSceptarHit(), TGriffin::GetSuppressedAddbackHit(), TGriffin::GetSuppressedAddbackMultiplicity(), TZeroDegree::GetZeroDegreeHit(), and PromptCoincidence().
GetEntry()
Int_t TGRSISelector::GetEntry (Long64_t entry, Int_t getall = 0) inline override inherited
Definition at line 46 of file TGRSISelector.h.
References TGRSISelector::fChain.
GetOutputList()
TList * TGRSISelector::GetOutputList () const inline override inherited
this does the same as TSelector::GetOutputList()
Definition at line 53 of file TGRSISelector.h.
Referenced by AlphanumericSelector::CreateHistograms(), AngularCorrelationSelector::CreateHistograms(), CrossTalk::CreateHistograms(), ExampleEventSelector::CreateHistograms(), ExampleFragmentSelector::CreateHistograms(), CreateHistograms(), FastTimingHistSelector::CreateHistograms(), GriffinKValueSelector::CreateHistograms(), and TimeWalkSelector::CreateHistograms().
GetOutputPrefix()
std::string TGRSISelector::GetOutputPrefix () const inline inherited
Definition at line 62 of file TGRSISelector.h.
References TGRSISelector::fOutputPrefix.
Referenced by TGRSISelector::SlaveTerminate().
Init()
void TGRSISelector::Init (TTree * tree) override inherited
The Init() function is called when the selector needs to initialize a new tree or chain. Typically here the branch addresses and branch pointers of the tree will be set. It is normally not necessary to make changes to the generated code, but the routine can be extended by the user if needed. Init() will be called many times when running on PROOF (once per file to be processed). Set branch addresses and branch pointers
Definition at line 275 of file TGRSISelector.cxx.
References TGRSISelector::fChain, and TGRSISelector::InitializeBranches().
InitializeBranches()
void ExampleTreeSelector::InitializeBranches (TTree * tree) virtual
Implements TGRSISelector.
Notify()
Bool_t TGRSISelector::Notify () override inherited
The Notify() function is called when a new file is opened. This can be either for a new TTree in a TChain or when when a new TTree is started when using PROOF. It is normally not necessary to make changes to the generated code, but the routine can be extended by the user if needed. The return value is currently not used.
Definition at line 292 of file TGRSISelector.cxx.
Process()
Bool_t TGRSISelector::Process (Long64_t entry) override inherited
The Process() function is called for each entry in the tree (or possibly keyed object in the case of PROOF) to be processed. The entry argument specifies which entry in the currently loaded tree is to be processed. It can be passed to either TGRSISelector::GetEntry() or TBranch::GetEntry() to read either all or the required parts of the data. When processing keyed objects with PROOF, the object is already loaded and is available via the fObject pointer.
This function should contain the "body" of the analysis. It can contain simple or elaborate selection criteria, run algorithms on the data of the event and typically fill histograms.
The processing can be stopped by calling Abort().
Use fStatus to set the return value of TTree::Process().
The return value is currently not used
Definition at line 166 of file TGRSISelector.cxx.
References TGRSIOptions::AnalysisOptions(), TGRSIMapException< key_type >::detail(), DRED, TGRSISelector::fChain, TGRSISelector::fEntry, TGRSISelector::FillHistograms(), TChannel::ReadCalFromFile(), TAnalysisOptions::ReadFromFile(), and RESET_COLOR.
SetObject()
void TGRSISelector::SetObject (TObject * obj) inline override inherited
Definition at line 51 of file TGRSISelector.h.
SetOption()
void TGRSISelector::SetOption (const char * option) inline override inherited
Definition at line 50 of file TGRSISelector.h.
SetOutputPrefix()
void TGRSISelector::SetOutputPrefix (const char * prefix) inline inherited
Definition at line 61 of file TGRSISelector.h.
References TGRSISelector::fOutputPrefix.
Referenced by AlphanumericSelector::AlphanumericSelector(), AngularCorrelationSelector::AngularCorrelationSelector(), CrossTalk::CrossTalk(), ExampleEventSelector::ExampleEventSelector(), ExampleFragmentSelector::ExampleFragmentSelector(), ExampleTreeSelector(), FastTimingHistSelector::FastTimingHistSelector(), GriffinKValueSelector::GriffinKValueSelector(), TGRSISelector::TGRSISelector(), TimeWalkSelector::TimeWalkSelector(), and FastTimingHistSelector::CreateHistograms().
SlaveBegin()
void TGRSISelector::SlaveBegin (TTree * tree) override inherited
The SlaveBegin() function is called after the Begin() function. When running with PROOF SlaveBegin() is called on each slave server. The tree argument is deprecated (on PROOF 0 is passed).
Definition at line 44 of file TGRSISelector.cxx.
References TGRSIOptions::AnalysisOptions(), TGRSISelector::CheckSizes(), TGRSISelector::CreateHistograms(), TGRSISelector::fAnalysisOptions, TGRSISelector::fCuts, TGRSISelector::fPpg, TGRSISelector::fRunInfo, TGRSIOptions::Get(), TSingleton< TParserLibrary >::Get(), TParserLibrary::Load(), TGRSIOptions::ParserLibrary(), TGRSIOptions::Print(), TChannel::ReadCalFile(), GValue::ReadValFile(), and GValue::Size().
SlaveTerminate()
void TGRSISelector::SlaveTerminate () override inherited
The SlaveTerminate() function is called after all entries or objects have been processed. When running with PROOF SlaveTerminate() is called on each slave server.
Definition at line 206 of file TGRSISelector.cxx.
References TGRSISelector::CheckSizes(), TGRSISelector::EndOfSort(), TChannel::GetChannelMap(), and TGRSISelector::GetOutputPrefix().
Terminate()
void TGRSISelector::Terminate () override inherited
The Terminate() function is the last function to be called during a query. It always runs on the client, it can be used to present the results graphically or save the results to file.
Definition at line 219 of file TGRSISelector.cxx.
References TGRSIOptions::AnalysisOptions(), TGRSISelector::CheckSizes(), TRunInfo::FirstRunNumber(), TRunInfo::FirstSubRunNumber(), TGRSISelector::fOutputPrefix, TGRSISelector::fPpg, TGRSISelector::fRunInfo, TGRSIOptions::Get(), TSingleton< TRunInfo >::Get(), TRunInfo::LastRunNumber(), TRunInfo::LastSubRunNumber(), TGRSIOptions::LogFile(), TRunInfo::Print(), TRunInfo::RunNumber(), TRunInfo::SubRunNumber(), TPPG::Write(), TAnalysisOptions::WriteToFile(), and TChannel::WriteToRoot().
Version()
virtual Int_t ExampleTreeSelector::Version () const inline virtual
Definition at line 41 of file ExampleTreeSelector.h.
Member Data Documentation
fAnalysisOptions
TAnalysisOptions* TGRSISelector::fAnalysisOptions {nullptr} private inherited
! pointer to analysis options
Definition at line 84 of file TGRSISelector.h.
Referenced by TGRSISelector::SlaveBegin().
fBetaGammaTiming
std::vector<double> ExampleTreeSelector::fBetaGammaTiming private
vector of beta-gamma timing
Definition at line 55 of file ExampleTreeSelector.h.
Referenced by CreateHistograms(), and FillHistograms().
fChain
TTree* TGRSISelector::fChain {nullptr} private inherited
! pointer to the analyzed TTree or TChain
Definition at line 80 of file TGRSISelector.h.
Referenced by TGRSISelector::GetEntry(), TGRSISelector::Init(), and TGRSISelector::Process().
fCube
TGRSIMap<std::string, GCube*> TGRSISelector::fCube protected inherited
Definition at line 69 of file TGRSISelector.h.
fCuts
std::map<std::string, TCutG*> TGRSISelector::fCuts protected inherited
Definition at line 72 of file TGRSISelector.h.
Referenced by TGRSISelector::SlaveBegin().
fEntry
int64_t TGRSISelector::fEntry {0} protected inherited
Definition at line 75 of file TGRSISelector.h.
Referenced by CreateHistograms(), and TGRSISelector::Process().
fFirstRunNumber
Int_t TGRSISelector::fFirstRunNumber {-1} private inherited
! run number of first file
Definition at line 85 of file TGRSISelector.h.
fFirstSubRunNumber
Int_t TGRSISelector::fFirstSubRunNumber {-1} private inherited
! sub-run number of first file
Definition at line 86 of file TGRSISelector.h.
fGrif
TGriffin* ExampleTreeSelector::fGrif private
pointer for griffin branch
Definition at line 48 of file ExampleTreeSelector.h.
Referenced by FillHistograms().
fGriffinBgo
TGriffinBgo* ExampleTreeSelector::fGriffinBgo private
pointer for griffin BGO branch
Definition at line 50 of file ExampleTreeSelector.h.
Referenced by FillHistograms().
fH1
TGRSIMap<std::string, TH1*> TGRSISelector::fH1 protected inherited
Definition at line 65 of file TGRSISelector.h.
Referenced by AlphanumericSelector::CreateHistograms(), AngularCorrelationSelector::CreateHistograms(), CrossTalk::CreateHistograms(), ExampleEventSelector::CreateHistograms(), ExampleFragmentSelector::CreateHistograms(), CreateHistograms(), FastTimingHistSelector::CreateHistograms(), GriffinKValueSelector::CreateHistograms(), TimeWalkSelector::CreateHistograms(), AngularCorrelationSelector::FillHistograms(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), FillHistograms(), FastTimingHistSelector::FillHistograms(), and GriffinKValueSelector::FillHistograms().
fH2
TGRSIMap<std::string, TH2*> TGRSISelector::fH2 protected inherited
Definition at line 66 of file TGRSISelector.h.
Referenced by AlphanumericSelector::CreateHistograms(), AngularCorrelationSelector::CreateHistograms(), CrossTalk::CreateHistograms(), ExampleEventSelector::CreateHistograms(), ExampleFragmentSelector::CreateHistograms(), CreateHistograms(), FastTimingHistSelector::CreateHistograms(), GriffinKValueSelector::CreateHistograms(), TimeWalkSelector::CreateHistograms(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), CrossTalk::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleFragmentSelector::FillHistograms(), FillHistograms(), GriffinKValueSelector::FillHistograms(), and TimeWalkSelector::FillHistograms().
fH3
TGRSIMap<std::string, TH3*> TGRSISelector::fH3 protected inherited
Definition at line 67 of file TGRSISelector.h.
Referenced by TimeWalkSelector::CreateHistograms(), and TimeWalkSelector::FillHistograms().
fHSparse
TGRSIMap<std::string, THnSparseF*> TGRSISelector::fHSparse protected inherited
Definition at line 70 of file TGRSISelector.h.
Referenced by AlphanumericSelector::CreateHistograms(), AngularCorrelationSelector::CreateHistograms(), CrossTalk::CreateHistograms(), ExampleEventSelector::CreateHistograms(), ExampleFragmentSelector::CreateHistograms(), FastTimingHistSelector::CreateHistograms(), GriffinKValueSelector::CreateHistograms(), and TimeWalkSelector::CreateHistograms().
fOutputPrefix
std::string TGRSISelector::fOutputPrefix private inherited
! pre-fix for output files
Definition at line 83 of file TGRSISelector.h.
Referenced by TGRSISelector::GetOutputPrefix(), TGRSISelector::SetOutputPrefix(), and TGRSISelector::Terminate().
fPpg
TPPG* TGRSISelector::fPpg {nullptr} protected inherited
Definition at line 73 of file TGRSISelector.h.
Referenced by TGRSISelector::SlaveBegin(), and TGRSISelector::Terminate().
fRunInfo
TRunInfo* TGRSISelector::fRunInfo {nullptr} protected inherited
Definition at line 74 of file TGRSISelector.h.
Referenced by TGRSISelector::SlaveBegin(), and TGRSISelector::Terminate().
fScep
TSceptar* ExampleTreeSelector::fScep private
pointer for sceptar branch
Definition at line 49 of file ExampleTreeSelector.h.
Referenced by FillHistograms().
fSizeLimit
int TGRSISelector::fSizeLimit = 1073741822 static constexpr private inherited
! 1 GB size limit for objects in ROOT
Definition at line 78 of file TGRSISelector.h.
Referenced by TGRSISelector::CheckSizes().
fSuppressedAddback
std::vector<double> ExampleTreeSelector::fSuppressedAddback private
vector of suppressed addback energies
Definition at line 54 of file ExampleTreeSelector.h.
Referenced by CreateHistograms(), and FillHistograms().
fSym
TGRSIMap<std::string, GHSym*> TGRSISelector::fSym protected inherited
Definition at line 68 of file TGRSISelector.h.
fTree
TGRSIMap<std::string, TTree*> TGRSISelector::fTree protected inherited
Definition at line 71 of file TGRSISelector.h.
Referenced by CreateHistograms(), and FillHistograms().
fZds
TZeroDegree* ExampleTreeSelector::fZds private
pointer for ZDS branch
Definition at line 51 of file ExampleTreeSelector.h.
Referenced by FillHistograms().