GRSISort: GH2I Class Reference
GH2I Class Reference
Detailed Description
Definition at line 17 of file GH2I.h.
Public Member Functions
GH2I ()=default
GH2I (const char *name, const char *title, Int_t nbinsx, const Double_t *xbins, Int_t nbinsy, const Double_t *ybins)
GH2I (const char *name, const char *title, Int_t nbinsx, const Double_t *xbins, Int_t nbinsy, Double_t ylow, Double_t yup)
GH2I (const char *name, const char *title, Int_t nbinsx, const Float_t *xbins, Int_t nbinsy, const Float_t *ybins)
GH2I (const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t *ybins)
GH2I (const char *name, const char *title, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup)
GH2I (const GH2I &)=default
GH2I (const TObject &)
GH2I (GH2I &&) noexcept=default
~GH2I ()
iterator begin ()
void Clear (Option_t *opt="") override
TObject * Clone (const char *newname="") const override
void Copy (TObject &) const override
void Draw (Option_t *opt="") override
TH1 * DrawCopy (Option_t *opt="", const char *name_postfix="_copy") const override
TH1 * DrawNormalized (Option_t *opt="", Double_t norm=1) const override
iterator end ()
GH1D * GetNext (const GH1D *curr, bool DrawEmpty=true)
GH1D * GetNextSummary (const GH1D *curr, bool DrawEmpty=false)
GH1D * GetPrevious (const GH1D *curr, bool DrawEmpty=true)
GH1D * GetPrevSummary (const GH1D *curr, bool DrawEmpty=false)
TList * GetProjections ()
bool GetSummary () const
EDirection GetSummaryDirection () const
TList * GetSummaryProjections ()
TH2 * GetTH2 () override
virtual void GH2Clear (Option_t *opt="")
GH1D * GH2ProjectionX (const char *name="_px", int firstbin=0, int lastbin=-1, Option_t *option="", bool KeepEmpty=false)
GH1D * GH2ProjectionY (const char *name="_py", int firstbin=0, int lastbin=-1, Option_t *option="", bool KeepEmpty=false)
GH2I & operator= (const GH2I &)=default
GH2I & operator= (GH2I &&) noexcept=default
void Print (Option_t *opt="") const override
GH1D * Projection_Background (int axis=0, int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
GH1D * ProjectionX (const char *name="_px", int firstbin=0, int lastbin=-1, Option_t *option="")
GH1D * ProjectionX_Background (int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
GH1D * ProjectionY (const char *name="_py", int firstbin=0, int lastbin=-1, Option_t *option="")
GH1D * ProjectionY_Background (int firstbin=0, int lastbin=-1, int first_bg_bin=0, int last_bg_bin=-1, EBackgroundSubtraction mode=EBackgroundSubtraction::kRegionBackground)
void SetSummary (bool is_summary=true)
void SetSummaryDirection (EDirection dir)
Private Member Functions
void Init ()
Private Attributes
bool fIsSummary {false}
TList * fProjections {nullptr}
EDirection fSummaryDirection {EDirection::kXDirection}
TList * fSummaryProjections {nullptr}
Constructor & Destructor Documentation
GH2I() [1/9]
GH2I::GH2I () default
GH2I() [2/9]
GH2I::GH2I (const TObject & obj) explicit
Definition at line 34 of file GH2I.cxx.
GH2I() [3/9]
GH2I::GH2I (const char * name, const char * title, Int_t nbinsx, const Double_t * xbins, Int_t nbinsy, const Double_t * ybins)
Definition at line 9 of file GH2I.cxx.
GH2I() [4/9]
GH2I::GH2I (const char * name, const char * title, Int_t nbinsx, const Float_t * xbins, Int_t nbinsy, const Float_t * ybins)
Definition at line 14 of file GH2I.cxx.
GH2I() [5/9]
GH2I::GH2I (const char * name, const char * title, Int_t nbinsx, const Double_t * xbins, Int_t nbinsy, Double_t ylow, Double_t yup)
Definition at line 19 of file GH2I.cxx.
GH2I() [6/9]
GH2I::GH2I (const char * name, const char * title, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t * ybins)
Definition at line 24 of file GH2I.cxx.
GH2I() [7/9]
GH2I::GH2I (const char * name, const char * title, Int_t nbinsx, Double_t xlow, Double_t xup, Int_t nbinsy, Double_t ylow, Double_t yup)
Definition at line 29 of file GH2I.cxx.
GH2I() [8/9]
GH2I::GH2I (const GH2I &) default
GH2I() [9/9]
GH2I::GH2I (GH2I &&) default noexcept
~GH2I()
GH2I::~GH2I () default
Member Function Documentation
begin()
iterator GH2Base::begin () inline inherited
Definition at line 111 of file GH2Base.h.
Clear()
void GH2I::Clear (Option_t * opt = "") override
Definition at line 57 of file GH2I.cxx.
References GH2Base::GH2Clear().
Clone()
TObject * GH2I::Clone (const char * newname = "") const override
Definition at line 48 of file GH2I.cxx.
Copy()
void GH2I::Copy (TObject & obj) const override
Definition at line 43 of file GH2I.cxx.
Draw()
void GH2I::Draw (Option_t * opt = "") override
Definition at line 70 of file GH2I.cxx.
DrawCopy()
TH1 * GH2I::DrawCopy (Option_t * opt = "", const char * name_postfix = "_copy") const override
Definition at line 83 of file GH2I.cxx.
References hist.
DrawNormalized()
TH1 * GH2I::DrawNormalized (Option_t * opt = "", Double_t norm = 1) const override
Definition at line 93 of file GH2I.cxx.
References hist.
end()
iterator GH2Base::end () inline inherited
Definition at line 112 of file GH2Base.h.
GetNext()
GH1D * GH2Base::GetNext (const GH1D * curr, bool DrawEmpty = true) inherited
Definition at line 221 of file GH2Base.cxx.
References GH2Base::fIsSummary, GH2Base::fProjections, and GH2Base::GetNextSummary().
Referenced by GH1D::GetNext(), and GH2Base::iterator::operator++().
GetNextSummary()
GH1D * GH2Base::GetNextSummary (const GH1D * curr, bool DrawEmpty = false) inherited
Definition at line 244 of file GH2Base.cxx.
References GH2Base::fSummaryDirection, GH2Base::fSummaryProjections, GH2Base::GetTH2(), GH2Base::GH2ProjectionX(), GH2Base::GH2ProjectionY(), hist, kXDirection, and kYDirection.
Referenced by GH2Base::GetNext(), and GCanvas::Process2DKeyboardPress().
GetPrevious()
GH1D * GH2Base::GetPrevious (const GH1D * curr, bool DrawEmpty = true) inherited
Definition at line 198 of file GH2Base.cxx.
References GH2Base::fIsSummary, GH2Base::fProjections, and GH2Base::GetPrevSummary().
Referenced by GH1D::GetPrevious().
GetPrevSummary()
GH1D * GH2Base::GetPrevSummary (const GH1D * curr, bool DrawEmpty = false) inherited
Definition at line 294 of file GH2Base.cxx.
References GH2Base::fSummaryDirection, GH2Base::fSummaryProjections, GH2Base::GetTH2(), GH2Base::GH2ProjectionX(), GH2Base::GH2ProjectionY(), hist, kXDirection, and kYDirection.
Referenced by GH2Base::GetPrevious().
GetProjections()
TList * GH2Base::GetProjections () inline inherited
Definition at line 60 of file GH2Base.h.
References GH2Base::fProjections.
Referenced by GCanvas::Process2DKeyboardPress().
GetSummary()
bool GH2Base::GetSummary () const inline inherited
Definition at line 64 of file GH2Base.h.
References GH2Base::fIsSummary.
GetSummaryDirection()
EDirection GH2Base::GetSummaryDirection () const inline inherited
Definition at line 67 of file GH2Base.h.
References GH2Base::fSummaryDirection.
GetSummaryProjections()
TList * GH2Base::GetSummaryProjections () inline inherited
Definition at line 61 of file GH2Base.h.
References GH2Base::fSummaryProjections.
GetTH2()
TH2 * GH2I::GetTH2 () inline override virtual
Implements GH2Base.
Definition at line 46 of file GH2I.h.
GH2Clear()
void GH2Base::GH2Clear (Option_t * opt = "") virtual inherited
Definition at line 24 of file GH2Base.cxx.
References GH2Base::fProjections, and GH2Base::fSummaryProjections.
Referenced by GH2D::Clear(), and Clear().
GH2ProjectionX()
GH1D * GH2Base::GH2ProjectionX (const char * name = "_px", int firstbin = 0, int lastbin = -1, Option_t * option = "", bool KeepEmpty = false) inherited
Definition at line 90 of file GH2Base.cxx.
References GH2Base::fIsSummary, GH2Base::fProjections, GH2Base::fSummaryProjections, GH2Base::GetTH2(), GH1D::SetParent(), and GH1D::SetProjectionAxis().
Referenced by GH2Base::GetNextSummary(), GH2Base::GetPrevSummary(), GH2D::ProjectionX(), and ProjectionX().
GH2ProjectionY()
GH1D * GH2Base::GH2ProjectionY (const char * name = "_py", int firstbin = 0, int lastbin = -1, Option_t * option = "", bool KeepEmpty = false) inherited
Definition at line 144 of file GH2Base.cxx.
References GH2Base::fIsSummary, GH2Base::fProjections, GH2Base::fSummaryProjections, GH2Base::GetTH2(), GH1D::SetParent(), and GH1D::SetProjectionAxis().
Referenced by GH2Base::GetNextSummary(), GH2Base::GetPrevSummary(), GH2D::ProjectionY(), and ProjectionY().
Init()
void GH2Base::Init () private inherited
Definition at line 16 of file GH2Base.cxx.
References GH2Base::fIsSummary, GH2Base::fProjections, GH2Base::fSummaryDirection, GH2Base::fSummaryProjections, and kXDirection.
Referenced by GH2Base::GH2Base().
operator=() [1/2]
GH2I & GH2I::operator= (const GH2I &) default
operator=() [2/2]
GH2I & GH2I::operator= (GH2I &&) default noexcept
Print()
void GH2I::Print (Option_t * opt = "") const override
Definition at line 66 of file GH2I.cxx.
Projection_Background()
GH1D * GH2Base::Projection_Background (int axis = 0, int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground) inherited
Definition at line 31 of file GH2Base.cxx.
References GH2Base::fProjections, GH2Base::GetTH2(), and kNoBackground.
Referenced by GH2Base::ProjectionX_Background(), and GH2Base::ProjectionY_Background().
ProjectionX()
GH1D * GH2I::ProjectionX (const char * name = "_px", int firstbin = 0, int lastbin = -1, Option_t * option = "")
Definition at line 103 of file GH2I.cxx.
References GH2Base::GH2ProjectionX().
ProjectionX_Background()
GH1D * GH2Base::ProjectionX_Background (int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground) inherited
Definition at line 138 of file GH2Base.cxx.
References GH2Base::Projection_Background().
Referenced by GH1D::Project_Background().
ProjectionY()
GH1D * GH2I::ProjectionY (const char * name = "_py", int firstbin = 0, int lastbin = -1, Option_t * option = "")
Definition at line 108 of file GH2I.cxx.
References GH2Base::GH2ProjectionY().
ProjectionY_Background()
GH1D * GH2Base::ProjectionY_Background (int firstbin = 0, int lastbin = -1, int first_bg_bin = 0, int last_bg_bin = -1, EBackgroundSubtraction mode = EBackgroundSubtraction::kRegionBackground) inherited
Definition at line 192 of file GH2Base.cxx.
References GH2Base::Projection_Background().
Referenced by GH1D::Project_Background().
SetSummary()
void GH2Base::SetSummary (bool is_summary = true) inline inherited
Definition at line 63 of file GH2Base.h.
References GH2Base::fIsSummary.
Referenced by GCanvas::Process2DKeyboardPress().
SetSummaryDirection()
void GH2Base::SetSummaryDirection (EDirection dir) inline inherited
Definition at line 66 of file GH2Base.h.
References GH2Base::fSummaryDirection.
Referenced by GCanvas::Process2DKeyboardPress().
Member Data Documentation
fIsSummary
bool GH2Base::fIsSummary {false} private inherited
Definition at line 119 of file GH2Base.h.
Referenced by GH2Base::GetNext(), GH2Base::GetPrevious(), GH2Base::GetSummary(), GH2Base::GH2ProjectionX(), GH2Base::GH2ProjectionY(), GH2Base::Init(), and GH2Base::SetSummary().
fProjections
TList* GH2Base::fProjections {nullptr} private inherited
Definition at line 116 of file GH2Base.h.
Referenced by GH2Base::~GH2Base(), GH2Base::GetNext(), GH2Base::GetPrevious(), GH2Base::GetProjections(), GH2Base::GH2Clear(), GH2Base::GH2ProjectionX(), GH2Base::GH2ProjectionY(), GH2Base::Init(), and GH2Base::Projection_Background().
fSummaryDirection
EDirection GH2Base::fSummaryDirection {EDirection::kXDirection} private inherited
Definition at line 120 of file GH2Base.h.
Referenced by GH2Base::GetNextSummary(), GH2Base::GetPrevSummary(), GH2Base::GetSummaryDirection(), GH2Base::Init(), and GH2Base::SetSummaryDirection().
fSummaryProjections
TList* GH2Base::fSummaryProjections {nullptr} private inherited
Definition at line 118 of file GH2Base.h.
Referenced by GH2Base::~GH2Base(), GH2Base::GetNextSummary(), GH2Base::GetPrevSummary(), GH2Base::GetSummaryProjections(), GH2Base::GH2Clear(), GH2Base::GH2ProjectionX(), GH2Base::GH2ProjectionY(), and GH2Base::Init().