GRSISort: TGRSIDetectorInformation Class Reference
TGRSIDetectorInformation Class Reference
Sorting
Detailed Description
This Class is designed to store setup dependent information. It is used to store existence of detector systems, etc.
Definition at line 23 of file TGRSIDetectorInformation.h.
Public Member Functions
TGRSIDetectorInformation ()
TGRSIDetectorInformation (const TGRSIDetectorInformation &)=default
TGRSIDetectorInformation (TGRSIDetectorInformation &&) noexcept=default
~TGRSIDetectorInformation () override=default
bool Bambino () const
bool Bgo () const
TEventBuildingLoop::EBuildMode BuildMode () const override
void Clear (Option_t *="") override
bool CSM () const
bool Dante () const
bool Descant () const
bool DescantAncillary () const
bool DescantWall () const
bool Emma () const
bool Generic () const
bool Griffin () const
TGRSIDetectorInformation & operator= (const TGRSIDetectorInformation &)=default
TGRSIDetectorInformation & operator= (TGRSIDetectorInformation &&) noexcept=default
bool Paces () const
void Print (Option_t *opt="") const override
bool Rcmp () const
bool RF () const
bool S3 () const
bool Sceptar () const
void Set () override
void SetBambino (bool flag=true)
void SetBgo (bool flag=true)
void SetCSM (bool flag=true)
void SetDante (bool flag=true)
void SetDescant (bool flag=true)
void SetDescantAncillary (bool flag=true)
void SetDescantWall (bool flag=true)
void SetEmma (bool flag=true)
void SetGeneric (bool flag=true)
void SetGriffin (bool flag=true)
void SetPaces (bool flag=true)
void SetRcmp (bool flag=true)
void SetRF (bool flag=true)
void SetS3 (bool flag=true)
void SetSceptar (bool flag=true)
void SetSharc (bool flag=true)
void SetSharc2 (bool flag=true)
void SetSpice (bool flag=true)
void SetTigress (bool flag=true)
void SetTip (bool flag=true)
void SetTrific (bool flag=true)
void SetTriFoil (bool flag=true)
void SetZeroDegree (bool flag=true)
bool Sharc () const
bool Sharc2 () const
bool Spice () const
bool Tigress () const
bool Tip () const
bool Trific () const
bool TriFoil () const
bool ZeroDegree () const
Private Attributes
bool fBambino {false}
bool fBgo {false}
bool fCSM {false}
bool fDante {false}
bool fDescant {false}
bool fDescantAncillary {false}
bool fDescantWall {false}
bool fEmma {false}
bool fGeneric {false}
bool fGriffin {false}
bool fPaces {false}
bool fRcmp {false}
bool fRf {false}
bool fS3 {false}
bool fSceptar {false}
bool fSharc {false}
bool fSharc2 {false}
bool fSortByTriggerId {false}
bool fSpice {false}
bool fTigress {false}
bool fTip {false}
bool fTrific {false}
bool fTriFoil {false}
bool fZeroDegree {false}
Constructor & Destructor Documentation
TGRSIDetectorInformation() [1/3]
TGRSIDetectorInformation::TGRSIDetectorInformation ()
Default ctor for TGRSIDetectorInformation.
Definition at line 11 of file TGRSIDetectorInformation.cxx.
References Clear(), and Set().
TGRSIDetectorInformation() [2/3]
TGRSIDetectorInformation::TGRSIDetectorInformation (const TGRSIDetectorInformation &) default
TGRSIDetectorInformation() [3/3]
TGRSIDetectorInformation::TGRSIDetectorInformation (TGRSIDetectorInformation &&) default noexcept
~TGRSIDetectorInformation()
TGRSIDetectorInformation::~TGRSIDetectorInformation () override default
Member Function Documentation
Bambino()
bool TGRSIDetectorInformation::Bambino () const inline
Definition at line 73 of file TGRSIDetectorInformation.h.
References fBambino.
Referenced by Print().
Bgo()
bool TGRSIDetectorInformation::Bgo () const inline
Definition at line 88 of file TGRSIDetectorInformation.h.
References fBgo.
Referenced by Print().
BuildMode()
TEventBuildingLoop::EBuildMode TGRSIDetectorInformation::BuildMode () const override virtual
Set the detector information based on the available TChannels.
Select build mode based on available detectors
Reimplemented from TDetectorInformation.
Definition at line 18 of file TGRSIDetectorInformation.cxx.
References TGRSIOptions::AnalysisOptions(), fSortByTriggerId, TEventBuildingLoop::kTime, TEventBuildingLoop::kTimestamp, and TEventBuildingLoop::kTriggerId.
Clear()
void TGRSIDetectorInformation::Clear (Option_t * = "") override
Definition at line 64 of file TGRSIDetectorInformation.cxx.
References TDetectorInformation::Clear(), fBambino, fBgo, fCSM, fDante, fDescant, fDescantAncillary, fDescantWall, fEmma, fGeneric, fGriffin, fPaces, fRcmp, fRf, fS3, fSceptar, fSharc, fSharc2, fSpice, fTigress, fTip, fTrific, fTriFoil, and fZeroDegree.
Referenced by TGRSIDetectorInformation().
CSM()
bool TGRSIDetectorInformation::CSM () const inline
Definition at line 71 of file TGRSIDetectorInformation.h.
References fCSM.
Referenced by Print().
Dante()
bool TGRSIDetectorInformation::Dante () const inline
Definition at line 84 of file TGRSIDetectorInformation.h.
References fDante.
Referenced by Print().
Descant()
bool TGRSIDetectorInformation::Descant () const inline
Definition at line 86 of file TGRSIDetectorInformation.h.
References fDescant.
Referenced by Print().
DescantAncillary()
bool TGRSIDetectorInformation::DescantAncillary () const inline
Definition at line 39 of file TGRSIDetectorInformation.h.
References fDescantAncillary.
Referenced by Print().
DescantWall()
bool TGRSIDetectorInformation::DescantWall () const inline
Definition at line 41 of file TGRSIDetectorInformation.h.
References fDescantWall.
Referenced by Print().
Emma()
bool TGRSIDetectorInformation::Emma () const inline
Definition at line 76 of file TGRSIDetectorInformation.h.
References fEmma.
Referenced by Print().
Generic()
bool TGRSIDetectorInformation::Generic () const inline
Definition at line 79 of file TGRSIDetectorInformation.h.
References fGeneric.
Referenced by Print().
Griffin()
bool TGRSIDetectorInformation::Griffin () const inline
Definition at line 81 of file TGRSIDetectorInformation.h.
References fGriffin.
Referenced by Print().
operator=() [1/2]
TGRSIDetectorInformation & TGRSIDetectorInformation::operator= (const TGRSIDetectorInformation &) default
operator=() [2/2]
TGRSIDetectorInformation & TGRSIDetectorInformation::operator= (TGRSIDetectorInformation &&) default noexcept
Paces()
bool TGRSIDetectorInformation::Paces () const inline
Definition at line 83 of file TGRSIDetectorInformation.h.
References fPaces.
Referenced by Print().
Print()
void TGRSIDetectorInformation::Print (Option_t * opt = "") const override
Definition at line 29 of file TGRSIDetectorInformation.cxx.
References Bambino(), Bgo(), CSM(), Dante(), DBLUE, Descant(), DescantAncillary(), DescantWall(), DRED, Emma(), Generic(), Griffin(), Paces(), Rcmp(), RESET_COLOR, RF(), S3(), Sceptar(), Sharc(), Sharc2(), Spice(), Tigress(), Tip(), Trific(), TriFoil(), and ZeroDegree().
Rcmp()
bool TGRSIDetectorInformation::Rcmp () const inline
Definition at line 89 of file TGRSIDetectorInformation.h.
References fRcmp.
Referenced by Print().
RF()
bool TGRSIDetectorInformation::RF () const inline
Definition at line 70 of file TGRSIDetectorInformation.h.
References fRf.
Referenced by Print().
S3()
bool TGRSIDetectorInformation::S3 () const inline
Definition at line 75 of file TGRSIDetectorInformation.h.
References fS3.
Referenced by Print().
Sceptar()
bool TGRSIDetectorInformation::Sceptar () const inline
Definition at line 82 of file TGRSIDetectorInformation.h.
References fSceptar.
Referenced by Print().
Set()
void TGRSIDetectorInformation::Set () override virtual
Sets the run info. This figures out what systems are available.
Reimplemented from TDetectorInformation.
Definition at line 98 of file TGRSIDetectorInformation.cxx.
References fSortByTriggerId, TChannel::GetChannelMap(), TGRSIMnemonic::kBgo, TGRSIMnemonic::kCSM, TGRSIMnemonic::kDescant, TGRSIMnemonic::kEmma, TGRSIMnemonic::kGeneric, TGRSIMnemonic::kGriffin, TGRSIMnemonic::kLaBr, TGRSIMnemonic::kPaces, TGRSIMnemonic::kRcmp, TGRSIMnemonic::kRF, TGRSIMnemonic::kSceptar, TGRSIMnemonic::kSharc, TGRSIMnemonic::kSharc2, kTIG10, kTIG64, TGRSIMnemonic::kTigress, TGRSIMnemonic::kTip, TGRSIMnemonic::kTrific, TGRSIMnemonic::kTriFoil, TGRSIMnemonic::kZeroDegree, RED, RESET_COLOR, SetBambino(), SetBgo(), SetCSM(), SetDante(), SetDescant(), SetEmma(), SetGeneric(), SetGriffin(), SetPaces(), SetRcmp(), SetRF(), SetS3(), SetSceptar(), SetSharc(), SetSharc2(), SetSpice(), SetTigress(), SetTip(), SetTrific(), SetTriFoil(), and SetZeroDegree().
Referenced by TGRSIDetectorInformation().
SetBambino()
void TGRSIDetectorInformation::SetBambino (bool flag = true) inline
Definition at line 52 of file TGRSIDetectorInformation.h.
References fBambino.
Referenced by Set().
SetBgo()
void TGRSIDetectorInformation::SetBgo (bool flag = true) inline
Definition at line 64 of file TGRSIDetectorInformation.h.
References fBgo.
Referenced by Set().
SetCSM()
void TGRSIDetectorInformation::SetCSM (bool flag = true) inline
Definition at line 47 of file TGRSIDetectorInformation.h.
References fCSM.
Referenced by Set().
SetDante()
void TGRSIDetectorInformation::SetDante (bool flag = true) inline
Definition at line 60 of file TGRSIDetectorInformation.h.
References fDante.
Referenced by Set().
SetDescant()
void TGRSIDetectorInformation::SetDescant (bool flag = true) inline
Definition at line 62 of file TGRSIDetectorInformation.h.
References fDescant.
Referenced by Set().
SetDescantAncillary()
void TGRSIDetectorInformation::SetDescantAncillary (bool flag = true) inline
Definition at line 38 of file TGRSIDetectorInformation.h.
References fDescantAncillary.
SetDescantWall()
void TGRSIDetectorInformation::SetDescantWall (bool flag = true) inline
Definition at line 40 of file TGRSIDetectorInformation.h.
References fDescantWall.
SetEmma()
void TGRSIDetectorInformation::SetEmma (bool flag = true) inline
Definition at line 53 of file TGRSIDetectorInformation.h.
References fEmma.
Referenced by Set().
SetGeneric()
void TGRSIDetectorInformation::SetGeneric (bool flag = true) inline
Definition at line 50 of file TGRSIDetectorInformation.h.
References fGeneric.
Referenced by Set().
SetGriffin()
void TGRSIDetectorInformation::SetGriffin (bool flag = true) inline
Definition at line 57 of file TGRSIDetectorInformation.h.
References fGriffin.
Referenced by Set().
SetPaces()
void TGRSIDetectorInformation::SetPaces (bool flag = true) inline
Definition at line 59 of file TGRSIDetectorInformation.h.
References fPaces.
Referenced by Set().
SetRcmp()
void TGRSIDetectorInformation::SetRcmp (bool flag = true) inline
Definition at line 65 of file TGRSIDetectorInformation.h.
References fRcmp.
Referenced by Set().
SetRF()
void TGRSIDetectorInformation::SetRF (bool flag = true) inline
Definition at line 46 of file TGRSIDetectorInformation.h.
References fRf.
Referenced by Set().
SetS3()
void TGRSIDetectorInformation::SetS3 (bool flag = true) inline
Definition at line 49 of file TGRSIDetectorInformation.h.
References fS3.
Referenced by Set().
SetSceptar()
void TGRSIDetectorInformation::SetSceptar (bool flag = true) inline
Definition at line 58 of file TGRSIDetectorInformation.h.
References fSceptar.
Referenced by Set().
SetSharc()
void TGRSIDetectorInformation::SetSharc (bool flag = true) inline
Definition at line 44 of file TGRSIDetectorInformation.h.
References fSharc.
Referenced by Set().
SetSharc2()
void TGRSIDetectorInformation::SetSharc2 (bool flag = true) inline
Definition at line 55 of file TGRSIDetectorInformation.h.
References fSharc2.
Referenced by Set().
SetSpice()
void TGRSIDetectorInformation::SetSpice (bool flag = true) inline
Definition at line 48 of file TGRSIDetectorInformation.h.
References fSpice.
Referenced by Set().
SetTigress()
void TGRSIDetectorInformation::SetTigress (bool flag = true) inline
Definition at line 43 of file TGRSIDetectorInformation.h.
References fTigress.
Referenced by Set().
SetTip()
void TGRSIDetectorInformation::SetTip (bool flag = true) inline
Definition at line 51 of file TGRSIDetectorInformation.h.
References fTip.
Referenced by Set().
SetTrific()
void TGRSIDetectorInformation::SetTrific (bool flag = true) inline
Definition at line 54 of file TGRSIDetectorInformation.h.
References fTrific.
Referenced by Set().
SetTriFoil()
void TGRSIDetectorInformation::SetTriFoil (bool flag = true) inline
Definition at line 45 of file TGRSIDetectorInformation.h.
References fTriFoil.
Referenced by Set().
SetZeroDegree()
void TGRSIDetectorInformation::SetZeroDegree (bool flag = true) inline
Definition at line 61 of file TGRSIDetectorInformation.h.
References fZeroDegree.
Referenced by Set().
Sharc()
bool TGRSIDetectorInformation::Sharc () const inline
Definition at line 68 of file TGRSIDetectorInformation.h.
References fSharc.
Referenced by Print().
Sharc2()
bool TGRSIDetectorInformation::Sharc2 () const inline
Definition at line 78 of file TGRSIDetectorInformation.h.
References fSharc2.
Referenced by Print().
Spice()
bool TGRSIDetectorInformation::Spice () const inline
Definition at line 72 of file TGRSIDetectorInformation.h.
References fSpice.
Referenced by Print().
Tigress()
bool TGRSIDetectorInformation::Tigress () const inline
Definition at line 67 of file TGRSIDetectorInformation.h.
References fTigress.
Referenced by Print().
Tip()
bool TGRSIDetectorInformation::Tip () const inline
Definition at line 74 of file TGRSIDetectorInformation.h.
References fTip.
Referenced by Print().
Trific()
bool TGRSIDetectorInformation::Trific () const inline
Definition at line 77 of file TGRSIDetectorInformation.h.
References fTrific.
Referenced by Print().
TriFoil()
bool TGRSIDetectorInformation::TriFoil () const inline
Definition at line 69 of file TGRSIDetectorInformation.h.
References fTriFoil.
Referenced by Print().
ZeroDegree()
bool TGRSIDetectorInformation::ZeroDegree () const inline
Definition at line 85 of file TGRSIDetectorInformation.h.
References fZeroDegree.
Referenced by Print().
Member Data Documentation
fBambino
bool TGRSIDetectorInformation::fBambino {false} private
flag for Bambino on/off
Definition at line 107 of file TGRSIDetectorInformation.h.
Referenced by Bambino(), Clear(), and SetBambino().
fBgo
bool TGRSIDetectorInformation::fBgo {false} private
flag for Bgo on/off
Definition at line 119 of file TGRSIDetectorInformation.h.
Referenced by Bgo(), Clear(), and SetBgo().
fCSM
bool TGRSIDetectorInformation::fCSM {false} private
flag for CSM on/off
Definition at line 102 of file TGRSIDetectorInformation.h.
Referenced by Clear(), CSM(), and SetCSM().
fDante
bool TGRSIDetectorInformation::fDante {false} private
flag for LaBr on/off
Definition at line 115 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Dante(), and SetDante().
fDescant
bool TGRSIDetectorInformation::fDescant {false} private
flag for Descant on/off
Definition at line 117 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Descant(), and SetDescant().
fDescantAncillary
bool TGRSIDetectorInformation::fDescantAncillary {false} private
Descant is in the ancillary detector locations.
Definition at line 95 of file TGRSIDetectorInformation.h.
Referenced by Clear(), DescantAncillary(), and SetDescantAncillary().
fDescantWall
bool TGRSIDetectorInformation::fDescantWall {false} private
Descant is in the wall detector locations.
Definition at line 96 of file TGRSIDetectorInformation.h.
Referenced by Clear(), DescantWall(), and SetDescantWall().
fEmma
bool TGRSIDetectorInformation::fEmma {false} private
flag for Emma on/off
Definition at line 108 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Emma(), and SetEmma().
fGeneric
bool TGRSIDetectorInformation::fGeneric {false} private
flag for Generic on/off
Definition at line 106 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Generic(), and SetGeneric().
fGriffin
bool TGRSIDetectorInformation::fGriffin {false} private
flag for Griffin on/off
Definition at line 112 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Griffin(), and SetGriffin().
fPaces
bool TGRSIDetectorInformation::fPaces {false} private
flag for Paces on/off
Definition at line 114 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Paces(), and SetPaces().
fRcmp
bool TGRSIDetectorInformation::fRcmp {false} private
flag for Rcmp on/off
Definition at line 120 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Rcmp(), and SetRcmp().
fRf
bool TGRSIDetectorInformation::fRf {false} private
flag for RF on/off
Definition at line 101 of file TGRSIDetectorInformation.h.
Referenced by Clear(), RF(), and SetRF().
fS3
bool TGRSIDetectorInformation::fS3 {false} private
flag for S3 on/off
Definition at line 105 of file TGRSIDetectorInformation.h.
Referenced by Clear(), S3(), and SetS3().
fSceptar
bool TGRSIDetectorInformation::fSceptar {false} private
flag for Sceptar on/off
Definition at line 113 of file TGRSIDetectorInformation.h.
Referenced by Clear(), Sceptar(), and SetSceptar().
fSharc
bool TGRSIDetectorInformation::fSharc {false} private
flag for Sharc on/off
Definition at line 99 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetSharc(), and Sharc().
fSharc2
bool TGRSIDetectorInformation::fSharc2 {false} private
flag for SHARC 2 on/off
Definition at line 110 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetSharc2(), and Sharc2().
fSortByTriggerId
bool TGRSIDetectorInformation::fSortByTriggerId {false} private
flag to sort by trigger ID instead of time stamp
Definition at line 122 of file TGRSIDetectorInformation.h.
Referenced by BuildMode(), and Set().
fSpice
bool TGRSIDetectorInformation::fSpice {false} private
flag for Spice on/off
Definition at line 103 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetSpice(), and Spice().
fTigress
bool TGRSIDetectorInformation::fTigress {false} private
flag for Tigress on/off
Definition at line 98 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetTigress(), and Tigress().
fTip
bool TGRSIDetectorInformation::fTip {false} private
flag for Tip on/off
Definition at line 104 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetTip(), and Tip().
fTrific
bool TGRSIDetectorInformation::fTrific {false} private
flag for TRIFIC on/off
Definition at line 109 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetTrific(), and Trific().
fTriFoil
bool TGRSIDetectorInformation::fTriFoil {false} private
flag for TriFoil on/off
Definition at line 100 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetTriFoil(), and TriFoil().
fZeroDegree
bool TGRSIDetectorInformation::fZeroDegree {false} private
flag for Zero Degree Scintillator on/off
Definition at line 116 of file TGRSIDetectorInformation.h.
Referenced by Clear(), SetZeroDegree(), and ZeroDegree().