GRSISort: ArgParseConfigT< bool > Class Reference
ArgParseConfigT< bool > Class Reference
Definition at line 227 of file ArgParser.h.
Public Member Functions
ArgParseConfigT (std::string flag, bool *output_location, bool firstPass)
virtual ArgParseConfig & colour (const std::string &c)
ArgParseConfig< bool > & default_value (bool value) override
virtual ArgParseConfig & description (const std::string &d)
std::string flag_name () const override
bool is_present () const
bool is_required () const override
bool matches (const std::string &flag) const override
int num_arguments () const override
void parse (const std::string &name, const std::vector< std::string > &arguments, bool firstPass, bool ignore_num_arguments=false)
void parse_item (const std::vector< std::string > &arguments) override
std::string printable (int description_column=-1, int *chars_before_desc=nullptr) const override
virtual ArgParseConfig & required ()
ArgParseConfig< bool > & takes_argument ()
Protected Attributes
std::string fColour
std::string fDescription
std::vector< std::string > fFlags
std::vector< std::string > fRawFlags
bool fRequired
Private Attributes
bool fFirstPass
int fNum_arguments_expected
bool * fOutput_location
bool fStored_default_value
bool present_
#include <ArgParser.h>
Constructor & Destructor Documentation
ArgParseConfigT()
ArgParseConfigT< bool >::ArgParseConfigT (std::string flag, bool * output_location, bool firstPass) inline
Definition at line 229 of file ArgParser.h.
References ArgParseConfigT< T >::fOutput_location.
Member Function Documentation
colour()
virtual ArgParseConfig & ArgParseConfig< bool >::colour (const std::string & c) inline virtual inherited
Definition at line 121 of file ArgParser.h.
default_value()
ArgParseConfig< bool > & ArgParseConfigT< bool >::default_value (bool value) inline override virtual
Implements ArgParseConfig< bool >.
Definition at line 235 of file ArgParser.h.
References ArgParseConfigT< T >::fOutput_location.
description()
virtual ArgParseConfig & ArgParseConfig< bool >::description (const std::string & d) inline virtual inherited
Definition at line 115 of file ArgParser.h.
flag_name()
std::string ArgParseConfig< bool >::flag_name () const inline override virtual inherited
Implements ArgParseItem.
Definition at line 89 of file ArgParser.h.
is_present()
bool ArgParseItem::is_present () const inline inherited
Definition at line 35 of file ArgParser.h.
References ArgParseItem::present_.
is_required()
bool ArgParseConfig< bool >::is_required () const inline override virtual inherited
Implements ArgParseItem.
Definition at line 133 of file ArgParser.h.
matches()
bool ArgParseConfig< bool >::matches (const std::string & flag) const inline override virtual inherited
Implements ArgParseItem.
Definition at line 100 of file ArgParser.h.
num_arguments()
int ArgParseConfigT< bool >::num_arguments () const inline override virtual
Implements ArgParseItem.
Definition at line 258 of file ArgParser.h.
parse()
void ArgParseItem::parse (const std::string & name, const std::vector< std::string > & arguments, bool firstPass, bool ignore_num_arguments = false) inline inherited
Definition at line 38 of file ArgParser.h.
References ArgParseItem::fFirstPass, ArgParseItem::num_arguments(), ArgParseItem::parse_item(), and ArgParseItem::present_.
Referenced by ArgParser::handle_default_option(), ArgParser::handle_long_flag(), ArgParser::handle_short_flag(), and ArgParser::parse_file().
parse_item()
void ArgParseConfigT< bool >::parse_item (const std::vector< std::string > & arguments) inline override virtual
Implements ArgParseItem.
Definition at line 248 of file ArgParser.h.
References ArgParseConfigT< T >::fOutput_location.
printable()
std::string ArgParseConfig< bool >::printable (int description_column = -1, int * chars_before_desc = nullptr) const inline override virtual inherited
Implements ArgParseItem.
Definition at line 137 of file ArgParser.h.
required()
virtual ArgParseConfig & ArgParseConfig< bool >::required () inline virtual inherited
Definition at line 127 of file ArgParser.h.
takes_argument()
ArgParseConfig< bool > & ArgParseConfigT< bool >::takes_argument () inline
Definition at line 242 of file ArgParser.h.
Member Data Documentation
fColour
std::string ArgParseConfig< bool >::fColour protected inherited
Colour string to be use for display.
Definition at line 188 of file ArgParser.h.
fDescription
std::string ArgParseConfig< bool >::fDescription protected inherited
A description for display on the terminal.
Definition at line 185 of file ArgParser.h.
fFirstPass
bool ArgParseItem::fFirstPass private inherited
Definition at line 64 of file ArgParser.h.
Referenced by ArgParseItem::parse().
fFlags
std::vector<std::string> ArgParseConfig< bool >::fFlags protected inherited
The literal flag that is searched for, including leading dashes.
Definition at line 191 of file ArgParser.h.
fNum_arguments_expected
int ArgParseConfigT< bool >::fNum_arguments_expected private
Definition at line 263 of file ArgParser.h.
fOutput_location
bool* ArgParseConfigT< bool >::fOutput_location private
Definition at line 261 of file ArgParser.h.
fRawFlags
std::vector<std::string> ArgParseConfig< bool >::fRawFlags protected inherited
The flags without the leading dashes.
Definition at line 194 of file ArgParser.h.
fRequired
bool ArgParseConfig< bool >::fRequired protected inherited
Whether the flag must be supplied.
Definition at line 197 of file ArgParser.h.
fStored_default_value
bool ArgParseConfigT< bool >::fStored_default_value private
Definition at line 262 of file ArgParser.h.
present_
bool ArgParseItem::present_ private inherited
Definition at line 63 of file ArgParser.h.
Referenced by ArgParseItem::is_present(), and ArgParseItem::parse().
GRSISort () Reference Guide Generated on Thu May 9 2024 20:43:25.