GRSISort: TSourceList Class Reference
TSourceList Class Reference
Calibration
Detailed Description
Definition at line 15 of file TSourceList.h.
Public Member Functions
TSourceList ()
TSourceList (const char *name, const char *title="")
TSourceList (const TNucleus &nuc)
TSourceList (const TNucleus &nuc, const char *name, const char *title="")
TSourceList (const TSourceList &)
TSourceList (TSourceList &&) noexcept=default
~TSourceList ()=default
void AddPoint (const TCalPoint &point)
void AddPoint (const UInt_t &idx, const TCalPoint &point)
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
void FillGraph (TGraph *graph) const
const std::map< UInt_t, TCalPoint > & Map () const
Int_t NPoints () const
TSourceList & operator= (const TSourceList &)=default
TSourceList & operator= (TSourceList &&) noexcept=default
void Print (Option_t *opt="") const override
Int_t SetNucleus (const char *nuc)
Int_t SetNucleus (const TNucleus &nuc)
bool SetPointIndex (const UInt_t &old_idx, const UInt_t &new_idx)
Private Member Functions
bool AddTransition (TTransition *tran)
Private Attributes
std::map< UInt_t, TCalPoint > fCalList
std::string fNucleusName
Constructor & Destructor Documentation
TSourceList() [1/6]
TSourceList::TSourceList ()
Definition at line 6 of file TSourceList.cxx.
References Clear().
TSourceList() [2/6]
TSourceList::TSourceList (const TNucleus & nuc, const char * name, const char * title = "")
Definition at line 17 of file TSourceList.cxx.
References Clear(), and SetNucleus().
TSourceList() [3/6]
TSourceList::TSourceList (const char * name, const char * title = "") explicit
Definition at line 11 of file TSourceList.cxx.
References Clear(), and SetNucleus().
TSourceList() [4/6]
TSourceList::TSourceList (const TNucleus & nuc) explicit
Definition at line 28 of file TSourceList.cxx.
References Clear(), and SetNucleus().
TSourceList() [5/6]
TSourceList::TSourceList (const TSourceList & copy)
Definition at line 23 of file TSourceList.cxx.
References Copy().
TSourceList() [6/6]
TSourceList::TSourceList (TSourceList &&) default noexcept
~TSourceList()
TSourceList::~TSourceList () default
Member Function Documentation
AddPoint() [1/2]
void TCalList::AddPoint (const TCalPoint & point) inherited
Definition at line 30 of file TCalList.cxx.
References TCalList::AddPoint(), and TCalPoint::Centroid().
Referenced by TCalGraph::AddLists(), TCalList::AddPoint(), AddTransition(), and TCalList::Copy().
AddPoint() [2/2]
void TCalList::AddPoint (const UInt_t & idx, const TCalPoint & point) inherited
Definition at line 35 of file TCalList.cxx.
References TCalList::fCalList.
AddTransition()
bool TSourceList::AddTransition (TTransition * tran) private
Definition at line 69 of file TSourceList.cxx.
References TCalList::AddPoint(), TTransition::GetEnergy(), TTransition::GetEnergyUncertainty(), TTransition::GetIntensity(), and TTransition::GetIntensityUncertainty().
Referenced by SetNucleus().
Clear()
void TSourceList::Clear (Option_t * opt = "") override
Definition at line 45 of file TSourceList.cxx.
References TCalList::Clear(), and fNucleusName.
Referenced by TSourceList(), TSourceList(), TSourceList(), and TSourceList().
Copy()
void TSourceList::Copy (TObject & obj) const override
Definition at line 34 of file TSourceList.cxx.
References TCalList::Copy().
Referenced by TSourceList().
FillGraph()
void TCalList::FillGraph (TGraph * graph) const inherited
Definition at line 71 of file TCalList.cxx.
References TCalList::fCalList.
Map()
const std::map< UInt_t, TCalPoint > & TCalList::Map () const inline inherited
Definition at line 34 of file TCalList.h.
References TCalList::fCalList.
Referenced by TCalGraph::AddLists(), and TCalGraph::CorrectMissingPoints().
NPoints()
Int_t TCalList::NPoints () const inline inherited
Definition at line 26 of file TCalList.h.
References TCalList::fCalList.
operator=() [1/2]
TSourceList & TSourceList::operator= (const TSourceList &) default
operator=() [2/2]
TSourceList & TSourceList::operator= (TSourceList &&) default noexcept
Print()
void TSourceList::Print (Option_t * opt = "") const override
Definition at line 39 of file TSourceList.cxx.
References fNucleusName, and TCalList::Print().
SetNucleus() [1/2]
Int_t TSourceList::SetNucleus (const char * nuc) inline
Definition at line 32 of file TSourceList.h.
References SetNucleus().
Referenced by SetNucleus().
SetNucleus() [2/2]
Int_t TSourceList::SetNucleus (const TNucleus & nuc)
Definition at line 51 of file TSourceList.cxx.
References AddTransition(), fNucleusName, and TNucleus::GetTransitionList().
Referenced by TSourceList(), TSourceList(), and TSourceList().
SetPointIndex()
bool TCalList::SetPointIndex (const UInt_t & old_idx, const UInt_t & new_idx) inherited
Definition at line 40 of file TCalList.cxx.
References TCalList::fCalList.
Member Data Documentation
fCalList
std::map<UInt_t, TCalPoint> TCalList::fCalList private inherited
Definition at line 37 of file TCalList.h.
Referenced by TCalList::AddPoint(), TCalList::Clear(), TCalList::Copy(), TCalList::FillGraph(), TCalList::Map(), TCalList::NPoints(), TCalList::Print(), and TCalList::SetPointIndex().
fNucleusName
std::string TSourceList::fNucleusName private
Definition at line 37 of file TSourceList.h.
Referenced by Clear(), Print(), and SetNucleus().