GRSISort: TCalList Class Reference
TCalList Class Reference
Calibration
Detailed Description
Definition at line 14 of file TCalList.h.
Public Member Functions
TCalList ()
TCalList (const char *name, const char *title="")
TCalList (const TCalList &)
TCalList (TCalList &&) noexcept=default
~TCalList ()=default
void AddPoint (const TCalPoint &point)
void AddPoint (const UInt_t &idx, const TCalPoint &point)
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
void FillGraph (TGraph *graph) const
const std::map< UInt_t, TCalPoint > & Map () const
Int_t NPoints () const
TCalList & operator= (const TCalList &)=default
TCalList & operator= (TCalList &&) noexcept=default
void Print (Option_t *opt="") const override
bool SetPointIndex (const UInt_t &old_idx, const UInt_t &new_idx)
Private Attributes
std::map< UInt_t, TCalPoint > fCalList
Constructor & Destructor Documentation
TCalList() [1/4]
TCalList::TCalList ()
Definition at line 6 of file TCalList.cxx.
References Clear().
TCalList() [2/4]
TCalList::TCalList (const char * name, const char * title = "") explicit
Definition at line 11 of file TCalList.cxx.
References Clear().
TCalList() [3/4]
TCalList::TCalList (const TCalList & copy)
Definition at line 16 of file TCalList.cxx.
References Copy().
TCalList() [4/4]
TCalList::TCalList (TCalList &&) default noexcept
~TCalList()
TCalList::~TCalList () default
Member Function Documentation
AddPoint() [1/2]
void TCalList::AddPoint (const TCalPoint & point)
Definition at line 30 of file TCalList.cxx.
References AddPoint(), and TCalPoint::Centroid().
Referenced by TCalGraph::AddLists(), AddPoint(), TSourceList::AddTransition(), and Copy().
AddPoint() [2/2]
void TCalList::AddPoint (const UInt_t & idx, const TCalPoint & point)
Definition at line 35 of file TCalList.cxx.
References fCalList.
Clear()
void TCalList::Clear (Option_t * opt = "") override
Definition at line 66 of file TCalList.cxx.
References fCalList.
Referenced by TCalList(), TCalList(), TSourceList::Clear(), and Copy().
Copy()
void TCalList::Copy (TObject & obj) const override
Definition at line 21 of file TCalList.cxx.
References AddPoint(), Clear(), and fCalList.
Referenced by TCalList(), and TSourceList::Copy().
FillGraph()
void TCalList::FillGraph (TGraph * graph) const
Definition at line 71 of file TCalList.cxx.
References fCalList.
Map()
const std::map< UInt_t, TCalPoint > & TCalList::Map () const inline
Definition at line 34 of file TCalList.h.
References fCalList.
Referenced by TCalGraph::AddLists(), and TCalGraph::CorrectMissingPoints().
NPoints()
Int_t TCalList::NPoints () const inline
Definition at line 26 of file TCalList.h.
References fCalList.
operator=() [1/2]
TCalList & TCalList::operator= (const TCalList &) default
operator=() [2/2]
TCalList & TCalList::operator= (TCalList &&) default noexcept
Print()
void TCalList::Print (Option_t * opt = "") const override
Definition at line 56 of file TCalList.cxx.
References fCalList.
Referenced by TSourceList::Print().
SetPointIndex()
bool TCalList::SetPointIndex (const UInt_t & old_idx, const UInt_t & new_idx)
Definition at line 40 of file TCalList.cxx.
References fCalList.
Member Data Documentation
fCalList
std::map<UInt_t, TCalPoint> TCalList::fCalList private
Definition at line 37 of file TCalList.h.
Referenced by AddPoint(), Clear(), Copy(), FillGraph(), Map(), NPoints(), Print(), and SetPointIndex().