GRSISort: TEnergyCal Class Reference
TEnergyCal Class Reference
Calibration
Detailed Description
Class for performing energy calibrations using a single nucleus.
Definition at line 21 of file TEnergyCal.h.
Public Member Functions
TEnergyCal ()
TEnergyCal (const char *name, const char *title)
~TEnergyCal () override
void AddPoint (Double_t measured, Double_t accepted, Double_t measuredUncertainty=0.0, Double_t acceptedUncertainty=0.0)
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
TChannel * GetChannel () const
virtual TF1 * GetFitFunction () const
TH1 * GetHist () const
virtual TNucleus * GetNucleus () const
Double_t GetParameter (size_t parameter) const override
std::vector< Double_t > GetParameters () const override
Bool_t IsGroupable () const override
void Print (Option_t *opt="") const override
Bool_t SetChannel (const TChannel *chan)
Bool_t SetChannel (UInt_t chanNum)
void SetDefaultTitles ()
virtual void SetFitFunction (const TF1 *func)
virtual void SetHist (TH1 *hist)
void SetNucleus (TNucleus *nuc, Option_t *opt="") override
Bool_t SetPoint (Int_t idx, Double_t measured)
Bool_t SetPoint (Int_t idx, TPeak *peak)
Bool_t SetPointError (Int_t idx, Double_t measuredUncertainty)
virtual void WriteToAllChannels (const std::string &mnemonic="")
void WriteToChannel () const override
Protected Member Functions
void InitTCal ()
Private Attributes
TRef fChan
TF1 * fFitFunc
TH1 * fHist
TNucleus * fNuc
Constructor & Destructor Documentation
TEnergyCal() [1/2]
TEnergyCal::TEnergyCal ()
Definition at line 3 of file TEnergyCal.cxx.
References SetDefaultTitles().
TEnergyCal() [2/2]
TEnergyCal::TEnergyCal (const char * name, const char * title) inline
Definition at line 24 of file TEnergyCal.h.
~TEnergyCal()
TEnergyCal::~TEnergyCal () override default
Member Function Documentation
AddPoint()
void TEnergyCal::AddPoint (Double_t measured, Double_t accepted, Double_t measuredUncertainty = 0.0, Double_t acceptedUncertainty = 0.0)
Definition at line 61 of file TEnergyCal.cxx.
Clear()
void TEnergyCal::Clear (Option_t * opt = "") override
Definition at line 141 of file TEnergyCal.cxx.
References TCal::Clear(), and SetDefaultTitles().
Copy()
void TCal::Copy (TObject & obj) const override inherited
Copies the TCal.
Definition at line 42 of file TCal.cxx.
References TCal::fChan, TCal::fFitFunc, and TCal::fNuc.
Referenced by TCal::TCal(), TEfficiencyCal::Copy(), and TGainMatch::Copy().
GetChannel()
TChannel * TCal::GetChannel () const inherited
Gets the channel being pointed to by the TCal. Returns 0 if no channel is set.
Definition at line 126 of file TCal.cxx.
References TCal::fChan.
Referenced by TCalManager::AddToManager(), TCalManager::AddToManager(), TCal::Print(), TCFDCal::Print(), TTimeCal::Print(), TCFDCal::ReadFromChannel(), TTimeCal::ReadFromChannel(), TCal::WriteToAllChannels(), TCFDCal::WriteToChannel(), WriteToChannel(), TGainMatch::WriteToChannel(), and TTimeCal::WriteToChannel().
GetFitFunction()
virtual TF1 * TCal::GetFitFunction () const inline virtual inherited
Definition at line 58 of file TCal.h.
References TCal::fFitFunc.
Referenced by TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), TCal::GetParameter(), TCal::GetParameters(), and main().
GetHist()
TH1 * TCal::GetHist () const inline inherited
Definition at line 73 of file TCal.h.
References TCal::fHist.
GetNucleus()
virtual TNucleus * TCal::GetNucleus () const inline virtual inherited
Reimplemented in TGainMatch.
Definition at line 75 of file TCal.h.
References TCal::fNuc.
Referenced by TEfficiencyCal::AddPoint(), TCal::Print(), SetNucleus(), SetPoint(), and SetPointError().
GetParameter()
Double_t TEnergyCal::GetParameter (size_t parameter) const override virtual
Reimplemented from TCal.
Definition at line 34 of file TEnergyCal.cxx.
Referenced by GetParameters(), and WriteToChannel().
GetParameters()
std::vector< Double_t > TEnergyCal::GetParameters () const override virtual
Reimplemented from TCal.
Definition at line 21 of file TEnergyCal.cxx.
References GetParameter().
InitTCal()
void TCal::InitTCal () protected inherited
Initiallizes the TCal.
Definition at line 177 of file TCal.cxx.
References TCal::Clear(), TCal::fChan, TCal::fFitFunc, TCal::fHist, and TCal::fNuc.
Referenced by TCal::TCal(), TCal::TCal(), and TCal::TCal().
IsGroupable()
Bool_t TEnergyCal::IsGroupable () const inline override virtual
Implements TCal.
Definition at line 49 of file TEnergyCal.h.
Print()
void TEnergyCal::Print (Option_t * opt = "") const override
Definition at line 134 of file TEnergyCal.cxx.
References TCal::Print().
SetChannel() [1/2]
Bool_t TCal::SetChannel (const TChannel * chan) inherited
Sets the channel being calibrated
Definition at line 56 of file TCal.cxx.
References TCal::fChan.
Referenced by TCalManager::AddToManager(), TGainMatch::CoarseMatch(), TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), main(), TCal::SetChannel(), and TCal::WriteToAllChannels().
SetChannel() [2/2]
Bool_t TCal::SetChannel (UInt_t chanNum) inherited
Sets the channel for the calibration to the channel number channum. Returns 0 if the channel does not exist
Definition at line 114 of file TCal.cxx.
References TChannel::GetChannelByNumber(), and TCal::SetChannel().
SetDefaultTitles()
void TEnergyCal::SetDefaultTitles ()
Definition at line 11 of file TEnergyCal.cxx.
Referenced by TEnergyCal(), Clear(), and SetNucleus().
SetFitFunction()
virtual void TCal::SetFitFunction (const TF1 * func) inline virtual inherited
Definition at line 59 of file TCal.h.
References TCal::fFitFunc.
Referenced by TGainMatch::CalculateGain(), TGainMatch::CoarseMatch(), TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), and main().
SetHist()
void TCal::SetHist (TH1 * hist) virtual inherited
Sets this histogram pointed to. TCal does NOT take ownership so you cannot delete this histogram as long as you want to access the hist in the TCal/write it out. I will add this functionality if I get annoyed enough with the way it is.
Reimplemented in TGainMatch.
Definition at line 134 of file TCal.cxx.
References TCal::fHist, and hist.
SetNucleus()
void TEnergyCal::SetNucleus (TNucleus * nuc, Option_t * opt = "") override virtual
Reimplemented from TCal.
Definition at line 40 of file TEnergyCal.cxx.
References TCal::GetNucleus(), TNucleus::NTransitions(), SetDefaultTitles(), and TCal::SetNucleus().
SetPoint() [1/2]
Bool_t TEnergyCal::SetPoint (Int_t idx, Double_t measured)
Definition at line 71 of file TEnergyCal.cxx.
References TCal::GetNucleus().
Referenced by SetPoint().
SetPoint() [2/2]
Bool_t TEnergyCal::SetPoint (Int_t idx, TPeak * peak)
Definition at line 91 of file TEnergyCal.cxx.
References TPeak::GetCentroid(), TPeak::GetCentroidErr(), SetPoint(), and SetPointError().
SetPointError()
Bool_t TEnergyCal::SetPointError (Int_t idx, Double_t measuredUncertainty)
Definition at line 105 of file TEnergyCal.cxx.
References TCal::GetNucleus().
Referenced by SetPoint().
WriteToAllChannels()
void TCal::WriteToAllChannels (const std::string & mnemonic = "") virtual inherited
Writes this calibration to all channels in the current TChannel Map
Definition at line 68 of file TCal.cxx.
References TCal::GetChannel(), TChannel::GetChannelMap(), TCal::SetChannel(), and TCal::WriteToChannel().
WriteToChannel()
void TEnergyCal::WriteToChannel () const override virtual
Reimplemented from TCal.
Definition at line 119 of file TEnergyCal.cxx.
References TChannel::AddENGCoefficient(), TChannel::DestroyENGCal(), TCal::GetChannel(), TChannel::GetNumber(), and GetParameter().
Member Data Documentation
fChan
TRef TCal::fChan private inherited
This points at the TChannel.
Definition at line 81 of file TCal.h.
Referenced by TCal::Clear(), TCal::Copy(), TCal::GetChannel(), TCal::InitTCal(), and TCal::SetChannel().
fFitFunc
TF1* TCal::fFitFunc private inherited
Fit function representing calibration.
Definition at line 82 of file TCal.h.
Referenced by TCal::Copy(), TCal::GetFitFunction(), TCal::InitTCal(), TCal::Print(), and TCal::SetFitFunction().
fHist
TH1* TCal::fHist private inherited
Histogram that was fit by the TPeak.
Definition at line 83 of file TCal.h.
Referenced by TCal::GetHist(), TCal::InitTCal(), and TCal::SetHist().
fNuc
TNucleus* TCal::fNuc private inherited
Nucleus that we are calibrating against.
Definition at line 84 of file TCal.h.
Referenced by TCal::Clear(), TCal::Copy(), TCal::GetNucleus(), TCal::InitTCal(), and TCal::SetNucleus().