GRSISort: TRF Class Reference
TRF Class Reference
Detectors
Detailed Description
Definition at line 18 of file TRF.h.
Public Member Functions
TRF ()
TRF (const TRF &)
TRF (TRF &&) noexcept=default
~TRF () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
Double_t GetTimeFitCfd () const
Double_t GetTimeFitns () const
Double_t GetTimestampCfd () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
time_t MidasTime () const
virtual bool NoHits () const
TRF & operator= (const TRF &)=default
TRF & operator= (TRF &&) noexcept=default
Double_t Period () const
Double_t Phase () const
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Double_t Time () const
Long_t TimeStamp () const
Private Attributes
std::vector< TDetectorHit * > fHits
time_t fMidasTime
double fPeriod
double fTime
Long_t fTimeStamp
Constructor & Destructor Documentation
TRF() [1/3]
TRF::TRF ()
Definition at line 3 of file TRF.cxx.
References Clear().
TRF() [2/3]
TRF::TRF (const TRF & rhs)
Definition at line 17 of file TRF.cxx.
References Copy().
TRF() [3/3]
TRF::TRF (TRF &&) default noexcept
~TRF()
TRF::~TRF () override default
Member Function Documentation
AddFragment()
void TRF::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 22 of file TRF.cxx.
References TPulseAnalyzer::fit_rf(), fMidasTime, fPeriod, fTime, fTimeStamp, and TPulseAnalyzer::IsSet().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TRF::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 64 of file TRF.h.
Clear()
void TRF::Clear (Option_t * opt = "") override
!
Definition at line 43 of file TRF.cxx.
References fMidasTime, fPeriod, fTime, and fTimeStamp.
Referenced by TRF().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TRF::Copy (TObject & rhs) const override
Definition at line 8 of file TRF.cxx.
References TDetector::Copy(), fMidasTime, fPeriod, fTime, and fTimeStamp.
Referenced by TRF().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetTimeFitCfd()
Double_t TRF::GetTimeFitCfd () const inline
Definition at line 39 of file TRF.h.
References fTime, and GetTimestampCfd().
GetTimeFitns()
Double_t TRF::GetTimeFitns () const inline
Definition at line 47 of file TRF.h.
References fTime, and TimeStamp().
GetTimestampCfd()
Double_t TRF::GetTimestampCfd () const inline
Definition at line 55 of file TRF.h.
References TimeStamp().
Referenced by GetTimeFitCfd().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
MidasTime()
time_t TRF::MidasTime () const inline
Definition at line 37 of file TRF.h.
References fMidasTime.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TRF & TRF::operator= (const TRF &) default
operator=() [2/2]
TRF & TRF::operator= (TRF &&) default noexcept
Period()
Double_t TRF::Period () const inline
Definition at line 35 of file TRF.h.
References fPeriod.
Phase()
Double_t TRF::Phase () const inline
Definition at line 27 of file TRF.h.
References fPeriod, and fTime.
Print() [1/2]
void TRF::Print (Option_t * opt = "") const override
!
Definition at line 52 of file TRF.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TRF::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 57 of file TRF.cxx.
References fMidasTime, fTime, and fTimeStamp.
Time()
Double_t TRF::Time () const inline
Definition at line 34 of file TRF.h.
References fTime.
TimeStamp()
Long_t TRF::TimeStamp () const inline
Definition at line 36 of file TRF.h.
References fTimeStamp.
Referenced by GetTimeFitns(), and GetTimestampCfd().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fMidasTime
time_t TRF::fMidasTime private
Definition at line 72 of file TRF.h.
Referenced by AddFragment(), Clear(), Copy(), MidasTime(), and Print().
fPeriod
double TRF::fPeriod private
Definition at line 75 of file TRF.h.
Referenced by AddFragment(), Clear(), Copy(), Period(), and Phase().
fTime
double TRF::fTime private
Definition at line 74 of file TRF.h.
Referenced by AddFragment(), Clear(), Copy(), GetTimeFitCfd(), GetTimeFitns(), Phase(), Print(), and Time().
fTimeStamp
Long_t TRF::fTimeStamp private
Definition at line 73 of file TRF.h.
Referenced by AddFragment(), Clear(), Copy(), Print(), and TimeStamp().