GRSISort: TPPGData Class Reference
TPPGData Class Reference
Sorting
Definition at line 47 of file TPPG.h.
Public Member Functions
TPPGData ()
TPPGData (const TPPGData &)
~TPPGData () override=default
void Clear (Option_t *opt="") override
void Copy (TObject &rhs) const override
UInt_t GetHighTimeStamp () const
UInt_t GetLowTimeStamp () const
UInt_t GetNetworkPacketId () const
EPpgPattern GetNewPPG () const
EPpgPattern GetOldPPG () const
Long64_t GetTimeStamp () const
void Print (Option_t *opt="") const override
void SetHighTimeStamp (UInt_t highTime)
void SetLowTimeStamp (UInt_t lowTime)
void SetNetworkPacketId (UInt_t packet)
void SetNewPPG (EPpgPattern newPpg)
void SetNewPPG (UInt_t newPpg)
void SetOldPPG (EPpgPattern oldPpg)
void SetOldPPG (UInt_t oldPpg)
void SetTimeStamp ()
Private Attributes
UInt_t fHighTimeStamp
UInt_t fLowTimeStamp
UInt_t fNetworkPacketId
EPpgPattern fNewPpg
EPpgPattern fOldPpg
ULong64_t fTimeStamp
Static Private Attributes
static short fTimestampUnits = 10
#include <TPPG.h>
Constructor & Destructor Documentation
TPPGData() [1/2]
TPPGData::TPPGData ()
Definition at line 16 of file TPPG.cxx.
References Clear().
TPPGData() [2/2]
TPPGData::TPPGData (const TPPGData & rhs)
Definition at line 21 of file TPPG.cxx.
References Copy().
~TPPGData()
TPPGData::~TPPGData () override default
Member Function Documentation
Clear()
void TPPGData::Clear (Option_t * opt = "") override
Clears the TPPGData and leaves it a "junk" state. By junk, I just mean default so that we can tell that this PPG is no good.
Definition at line 44 of file TPPG.cxx.
References fHighTimeStamp, fLowTimeStamp, fNetworkPacketId, fNewPpg, fOldPpg, fTimeStamp, and kJunk.
Referenced by TPPGData().
Copy()
void TPPGData::Copy (TObject & rhs) const override
Definition at line 26 of file TPPG.cxx.
References fHighTimeStamp, fLowTimeStamp, fNetworkPacketId, fNewPpg, fOldPpg, and fTimeStamp.
Referenced by TPPGData().
GetHighTimeStamp()
UInt_t TPPGData::GetHighTimeStamp () const inline
Definition at line 101 of file TPPG.h.
References fHighTimeStamp.
Referenced by SetTimeStamp().
GetLowTimeStamp()
UInt_t TPPGData::GetLowTimeStamp () const inline
Definition at line 100 of file TPPG.h.
References fLowTimeStamp.
Referenced by SetTimeStamp().
GetNetworkPacketId()
UInt_t TPPGData::GetNetworkPacketId () const inline
Definition at line 104 of file TPPG.h.
References fNetworkPacketId.
GetNewPPG()
EPpgPattern TPPGData::GetNewPPG () const inline
Definition at line 102 of file TPPG.h.
References fNewPpg.
GetOldPPG()
EPpgPattern TPPGData::GetOldPPG () const inline
Definition at line 103 of file TPPG.h.
References fOldPpg.
GetTimeStamp()
Long64_t TPPGData::GetTimeStamp () const inline
Definition at line 106 of file TPPG.h.
References fTimeStamp.
Referenced by TPPG::AddData(), TPPG::GetNumberOfCycles(), and Print().
Print()
void TPPGData::Print (Option_t * opt = "") const override
Definition at line 56 of file TPPG.cxx.
References fNewPpg, fOldPpg, GetTimeStamp(), and hex().
SetHighTimeStamp()
void TPPGData::SetHighTimeStamp (UInt_t highTime) inline
Definition at line 64 of file TPPG.h.
References fHighTimeStamp, and SetTimeStamp().
SetLowTimeStamp()
void TPPGData::SetLowTimeStamp (UInt_t lowTime) inline
Definition at line 59 of file TPPG.h.
References fLowTimeStamp, and SetTimeStamp().
SetNetworkPacketId()
void TPPGData::SetNetworkPacketId (UInt_t packet) inline
Definition at line 95 of file TPPG.h.
References fNetworkPacketId.
SetNewPPG() [1/2]
void TPPGData::SetNewPPG (EPpgPattern newPpg) inline
Definition at line 69 of file TPPG.h.
References fNewPpg.
SetNewPPG() [2/2]
void TPPGData::SetNewPPG (UInt_t newPpg) inline
Definition at line 70 of file TPPG.h.
References fNewPpg, hex(), kBackground, kBeamOn, kDecay, kJunk, and kTapeMove.
SetOldPPG() [1/2]
void TPPGData::SetOldPPG (EPpgPattern oldPpg) inline
Definition at line 82 of file TPPG.h.
References fOldPpg.
SetOldPPG() [2/2]
void TPPGData::SetOldPPG (UInt_t oldPpg) inline
Definition at line 83 of file TPPG.h.
References fOldPpg, hex(), kBackground, kBeamOn, kDecay, kJunk, and kTapeMove.
SetTimeStamp()
void TPPGData::SetTimeStamp ()
Definition at line 36 of file TPPG.cxx.
References fTimeStamp, fTimestampUnits, GetHighTimeStamp(), and GetLowTimeStamp().
Referenced by SetHighTimeStamp(), and SetLowTimeStamp().
Member Data Documentation
fHighTimeStamp
UInt_t TPPGData::fHighTimeStamp private
high bits of time stamp in 10 ns
Definition at line 115 of file TPPG.h.
Referenced by Clear(), Copy(), GetHighTimeStamp(), and SetHighTimeStamp().
fLowTimeStamp
UInt_t TPPGData::fLowTimeStamp private
low bits of time stamp in 10 ns
Definition at line 114 of file TPPG.h.
Referenced by Clear(), Copy(), GetLowTimeStamp(), and SetLowTimeStamp().
fNetworkPacketId
UInt_t TPPGData::fNetworkPacketId private
Definition at line 113 of file TPPG.h.
Referenced by Clear(), Copy(), GetNetworkPacketId(), and SetNetworkPacketId().
fNewPpg
EPpgPattern TPPGData::fNewPpg private
Definition at line 112 of file TPPG.h.
Referenced by Clear(), Copy(), GetNewPPG(), Print(), SetNewPPG(), and SetNewPPG().
fOldPpg
EPpgPattern TPPGData::fOldPpg private
Definition at line 111 of file TPPG.h.
Referenced by Clear(), Copy(), GetOldPPG(), Print(), SetOldPPG(), and SetOldPPG().
fTimeStamp
ULong64_t TPPGData::fTimeStamp private
time stamp in ns
Definition at line 110 of file TPPG.h.
Referenced by Clear(), Copy(), GetTimeStamp(), and SetTimeStamp().
fTimestampUnits
short TPPGData::fTimestampUnits = 10 static private
timestamp units of the PPG (10 ns)
Definition at line 109 of file TPPG.h.
Referenced by SetTimeStamp().
GRSISort () Reference Guide Generated on Mon May 13 2024 16:00:07.