GRSISort: TFragHistLoop Class Reference
TFragHistLoop Class Reference
Loops
Detailed Description
This loop takes fragments and fills histograms based on 'histos/MakeFragmentHistograms.cxx'
Definition at line 25 of file TFragHistLoop.h.
Public Member Functions
TFragHistLoop (const TFragHistLoop &)=delete
TFragHistLoop (TFragHistLoop &&) noexcept=delete
~TFragHistLoop ()
void AddCutFile (TFile *cut_file)
void ClearHistograms ()
void ClearQueue () override
virtual std::string EndStatus ()
TList * GetGates ()
size_t GetItemsCurrent () override
size_t GetItemsPopped () override
size_t GetItemsPushed () override
std::string GetLibraryName () const
TList * GetObjects ()
std::string GetOutputFilename () const
size_t GetRate () override
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & InputQueue ()
bool IsPaused ()
bool IsRunning ()
void Join ()
void LoadLibrary (const std::string &library)
std::string Name () const
virtual void OnEnd ()
TFragHistLoop & operator= (const TFragHistLoop &)=delete
TFragHistLoop & operator= (TFragHistLoop &&) noexcept=delete
void Pause ()
virtual std::string Progress ()
void Resume ()
void SetOutputFilename (const std::string &name)
virtual std::string Status ()
void Stop ()
void Write ()
Static Public Member Functions
static std::string AllThreadHeader ()
static std::string AllThreadProgress ()
static std::string AllThreadStatus ()
static bool AnyThreadRunning ()
static std::string AnyThreadStatus ()
static void ClearAllQueues ()
static size_t ColumnWidth ()
static void ColumnWidth (size_t val)
static StoppableThread * Get (const std::string &name)
static TFragHistLoop * Get (std::string name="")
static std::vector< StoppableThread * > GetAll ()
static int GetNThreads ()
static void join_status_thread ()
static void PauseAll ()
static void Print ()
static void ResumeAll ()
static void SendStop ()
static void start_status_thread ()
static void status_out ()
static void status_out_loop ()
static size_t StatusWidth ()
static void StatusWidth (size_t val)
static void stop_status_thread ()
static void StopAll ()
Protected Member Functions
void IncrementItemsPopped ()
std::atomic_long & InputSize ()
void InputSize (int64_t val)
std::atomic_size_t & ItemsPopped ()
void ItemsPopped (size_t val)
bool Iteration () override
Private Member Functions
TFragHistLoop (std::string name)
void CloseFile ()
void Loop ()
void OpenFile ()
Private Attributes
TCompiledHistograms fCompiledHistograms
std::atomic_bool fForceStop {false}
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > fInputQueue
std::atomic_long fInputSize {0}
std::atomic_size_t fItemsPopped {0}
std::string fName
TFile * fOutputFile
std::string fOutputFilename
std::atomic_bool fPaused {false}
std::condition_variable fPausedWait
std::mutex fPauseMutex
std::atomic_bool fRunning {false}
std::thread fThread
Static Private Attributes
static size_t fColumnWidth = 20
static std::thread fStatusThread
static bool fStatusThreadOn = false
static size_t fStatusWidth = 80
static std::map< std::string, StoppableThread * > fThreadMap
Constructor & Destructor Documentation
TFragHistLoop() [1/3]
TFragHistLoop::TFragHistLoop (const TFragHistLoop &) delete
Referenced by Get().
TFragHistLoop() [2/3]
TFragHistLoop::TFragHistLoop (TFragHistLoop &&) delete noexcept
~TFragHistLoop()
TFragHistLoop::~TFragHistLoop ()
Definition at line 32 of file TFragHistLoop.cxx.
References CloseFile().
TFragHistLoop() [3/3]
TFragHistLoop::TFragHistLoop (std::string name) explicit private
Definition at line 25 of file TFragHistLoop.cxx.
References TGRSIOptions::Get(), and LoadLibrary().
Member Function Documentation
AddCutFile()
void TFragHistLoop::AddCutFile (TFile * cut_file)
Definition at line 141 of file TFragHistLoop.cxx.
References TCompiledHistograms::AddCutFile(), and fCompiledHistograms.
AllThreadHeader()
std::string StoppableThread::AllThreadHeader () static inherited
Definition at line 73 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::ApplyOptions().
AllThreadProgress()
std::string StoppableThread::AllThreadProgress () static inherited
Definition at line 59 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AllThreadStatus()
std::string StoppableThread::AllThreadStatus () static inherited
Definition at line 83 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AnyThreadRunning()
bool StoppableThread::AnyThreadRunning () static inherited
Definition at line 37 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TChannel::GetChannel(), TGRSIint::LoopUntilDone(), and TGRSIInterruptHandler::Notify().
AnyThreadStatus()
std::string StoppableThread::AnyThreadStatus () static inherited
Definition at line 47 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
ClearAllQueues()
void StoppableThread::ClearAllQueues () static inherited
Definition at line 166 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIInterruptHandler::Notify().
ClearHistograms()
void TFragHistLoop::ClearHistograms ()
Definition at line 66 of file TFragHistLoop.cxx.
References TCompiledHistograms::ClearHistograms(), and fCompiledHistograms.
ClearQueue()
void TFragHistLoop::ClearQueue () override virtual
Reimplemented from StoppableThread.
Definition at line 37 of file TFragHistLoop.cxx.
References fInputQueue.
CloseFile()
void TFragHistLoop::CloseFile () private
Definition at line 79 of file TFragHistLoop.cxx.
References fOutputFile, fOutputFilename, and Write().
Referenced by ~TFragHistLoop().
ColumnWidth() [1/2]
static size_t StoppableThread::ColumnWidth () inline static inherited
Definition at line 82 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
Referenced by TGRSIint::SetupPipeline().
ColumnWidth() [2/2]
static void StoppableThread::ColumnWidth (size_t val) inline static inherited
Definition at line 80 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
EndStatus()
virtual std::string StoppableThread::EndStatus () inline virtual inherited
Reimplemented in TAnalysisWriteLoop, TEventBuildingLoop, TFragWriteLoop, and TUnpackingLoop.
Definition at line 62 of file StoppableThread.h.
Referenced by StoppableThread::Join(), and StoppableThread::Stop().
Get() [1/2]
StoppableThread * StoppableThread::Get (const std::string & name) static inherited
Definition at line 173 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TAnalysisHistLoop::Get(), TAnalysisWriteLoop::Get(), TDataLoop::Get(), TDetBuildingLoop::Get(), TEventBuildingLoop::Get(), Get(), TFragmentChainLoop::Get(), TFragWriteLoop::Get(), TTerminalLoop< T >::Get(), and TUnpackingLoop::Get().
Get() [2/2]
TFragHistLoop * TFragHistLoop::Get (std::string name = "") static
Definition at line 13 of file TFragHistLoop.cxx.
References TFragHistLoop(), and StoppableThread::Get().
Referenced by TGRSIint::SetupPipeline().
GetAll()
std::vector< StoppableThread * > StoppableThread::GetAll () static inherited
Definition at line 315 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
GetGates()
TList * TFragHistLoop::GetGates ()
Definition at line 126 of file TFragHistLoop.cxx.
References fCompiledHistograms, and TCompiledHistograms::GetGates().
GetItemsCurrent()
size_t TFragHistLoop::GetItemsCurrent () inline override virtual
Implements StoppableThread.
Definition at line 60 of file TFragHistLoop.h.
GetItemsPopped()
size_t TFragHistLoop::GetItemsPopped () inline override virtual
Implements StoppableThread.
Definition at line 58 of file TFragHistLoop.h.
GetItemsPushed()
size_t TFragHistLoop::GetItemsPushed () inline override virtual
Implements StoppableThread.
Definition at line 59 of file TFragHistLoop.h.
GetLibraryName()
std::string TFragHistLoop::GetLibraryName () const
Definition at line 116 of file TFragHistLoop.cxx.
References fCompiledHistograms, and TCompiledHistograms::GetLibraryName().
GetNThreads()
int StoppableThread::GetNThreads () static inherited
Definition at line 21 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::Print().
GetObjects()
TList * TFragHistLoop::GetObjects ()
Definition at line 121 of file TFragHistLoop.cxx.
References fCompiledHistograms, and TCompiledHistograms::GetObjects().
GetOutputFilename()
std::string TFragHistLoop::GetOutputFilename () const
Definition at line 136 of file TFragHistLoop.cxx.
References fOutputFilename.
Referenced by Write().
GetRate()
size_t TFragHistLoop::GetRate () inline override virtual
Implements StoppableThread.
Definition at line 61 of file TFragHistLoop.h.
IncrementItemsPopped()
void StoppableThread::IncrementItemsPopped () inline protected inherited
Definition at line 97 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), and TUnpackingLoop::Iteration().
InputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TFragHistLoop::InputQueue () inline
Definition at line 36 of file TFragHistLoop.h.
References fInputQueue.
Referenced by TGRSIint::SetupPipeline().
InputSize() [1/2]
std::atomic_long & StoppableThread::InputSize () inline protected inherited
Definition at line 96 of file StoppableThread.h.
References StoppableThread::fInputSize.
Referenced by TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), and TUnpackingLoop::Iteration().
InputSize() [2/2]
void StoppableThread::InputSize (int64_t val) inline protected inherited
Definition at line 94 of file StoppableThread.h.
References StoppableThread::fInputSize.
IsPaused()
bool StoppableThread::IsPaused () inherited
Definition at line 224 of file StoppableThread.cxx.
References StoppableThread::fPaused.
IsRunning()
bool StoppableThread::IsRunning () inherited
Definition at line 219 of file StoppableThread.cxx.
References StoppableThread::fRunning.
Referenced by StoppableThread::status_out().
ItemsPopped() [1/2]
std::atomic_size_t & StoppableThread::ItemsPopped () inline protected inherited
Definition at line 95 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Referenced by TAnalysisWriteLoop::EndStatus(), TEventBuildingLoop::EndStatus(), TFragWriteLoop::EndStatus(), TFragmentChainLoop::GetItemsPopped(), TFragWriteLoop::GetItemsPopped(), TAnalysisWriteLoop::GetItemsPushed(), TFragmentChainLoop::GetItemsPushed(), TFragWriteLoop::GetItemsPushed(), TDataLoop::Iteration(), TFragmentChainLoop::Iteration(), TUnpackingLoop::Iteration(), and TFragmentChainLoop::Restart().
ItemsPopped() [2/2]
void StoppableThread::ItemsPopped (size_t val) inline protected inherited
Definition at line 93 of file StoppableThread.h.
References StoppableThread::fItemsPopped.
Iteration()
bool TFragHistLoop::Iteration () override protected virtual
Implements StoppableThread.
Definition at line 45 of file TFragHistLoop.cxx.
References fCompiledHistograms, TCompiledHistograms::Fill(), fInputQueue, fOutputFile, StoppableThread::IncrementItemsPopped(), StoppableThread::InputSize(), and OpenFile().
Join()
void StoppableThread::Join () inherited
Definition at line 229 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), and StoppableThread::fThread.
Referenced by StoppableThread::StopAll().
join_status_thread()
void StoppableThread::join_status_thread () static inherited
Definition at line 280 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, and StoppableThread::stop_status_thread().
LoadLibrary()
void TFragHistLoop::LoadLibrary (const std::string & library)
Definition at line 111 of file TFragHistLoop.cxx.
References fCompiledHistograms, and TCompiledHistograms::Load().
Referenced by TFragHistLoop().
Loop()
void StoppableThread::Loop () private inherited
Definition at line 237 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, StoppableThread::fRunning, StoppableThread::Iteration(), and StoppableThread::OnEnd().
Referenced by StoppableThread::StoppableThread().
Name()
std::string StoppableThread::Name () const inline inherited
Definition at line 63 of file StoppableThread.h.
References StoppableThread::fName.
Referenced by TAnalysisWriteLoop::AddBranch(), TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), TUnpackingLoop::EndStatus(), and StoppableThread::status_out().
OnEnd()
virtual void StoppableThread::OnEnd () inline virtual inherited
Reimplemented in TAnalysisWriteLoop, TDataLoop, and TFragmentChainLoop.
Definition at line 59 of file StoppableThread.h.
Referenced by StoppableThread::Loop().
OpenFile()
void TFragHistLoop::OpenFile () private
Definition at line 71 of file TFragHistLoop.cxx.
References fCompiledHistograms, fOutputFile, fOutputFilename, TGRSIint::instance(), TGRSIint::OpenRootFile(), and TCompiledHistograms::SetDefaultDirectory().
Referenced by Iteration().
operator=() [1/2]
TFragHistLoop & TFragHistLoop::operator= (const TFragHistLoop &) delete
operator=() [2/2]
TFragHistLoop & TFragHistLoop::operator= (TFragHistLoop &&) delete noexcept
Pause()
void StoppableThread::Pause () inherited
Definition at line 202 of file StoppableThread.cxx.
References StoppableThread::fPaused, and StoppableThread::fRunning.
PauseAll()
void StoppableThread::PauseAll () static inherited
Definition at line 97 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Print()
void StoppableThread::Print () static inherited
Definition at line 254 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, StoppableThread::fThreadMap, StoppableThread::GetNThreads(), and hex().
Progress()
std::string StoppableThread::Progress () virtual inherited
Definition at line 119 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
Resume()
void StoppableThread::Resume () inherited
Definition at line 193 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
ResumeAll()
void StoppableThread::ResumeAll () static inherited
Definition at line 104 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIint::SetupPipeline().
SendStop()
void StoppableThread::SendStop () static inherited
Definition at line 135 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::StopAll(), and TGRSIint::Terminate().
SetOutputFilename()
void TFragHistLoop::SetOutputFilename (const std::string & name)
Definition at line 131 of file TFragHistLoop.cxx.
References fOutputFilename.
Referenced by TGRSIint::SetupPipeline().
start_status_thread()
void StoppableThread::start_status_thread () static inherited
Definition at line 265 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, StoppableThread::fStatusThreadOn, and StoppableThread::status_out_loop().
Referenced by StoppableThread::StoppableThread().
Status()
std::string StoppableThread::Status () virtual inherited
Definition at line 111 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
status_out()
void StoppableThread::status_out () static inherited
Definition at line 297 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::GetItemsCurrent(), StoppableThread::GetItemsPopped(), StoppableThread::GetItemsPushed(), StoppableThread::GetRate(), StoppableThread::IsRunning(), and StoppableThread::Name().
Referenced by StoppableThread::status_out_loop(), and StoppableThread::StopAll().
status_out_loop()
void StoppableThread::status_out_loop () static inherited
Definition at line 286 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn, and StoppableThread::status_out().
Referenced by StoppableThread::start_status_thread().
StatusWidth() [1/2]
static size_t StoppableThread::StatusWidth () inline static inherited
Definition at line 83 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Referenced by TGRSIint::SetupPipeline().
StatusWidth() [2/2]
static void StoppableThread::StatusWidth (size_t val) inline static inherited
Definition at line 81 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Stop()
void StoppableThread::Stop () inherited
Definition at line 209 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
stop_status_thread()
void StoppableThread::stop_status_thread () static inherited
Definition at line 273 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn.
Referenced by StoppableThread::join_status_thread().
StopAll()
void StoppableThread::StopAll () static inherited
Definition at line 147 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::Join(), StoppableThread::SendStop(), and StoppableThread::status_out().
Referenced by TGRSIint::Terminate().
Write()
void TFragHistLoop::Write ()
Definition at line 90 of file TFragHistLoop.cxx.
References BLUE, fCompiledHistograms, fOutputFile, GValue::Get(), TChannel::GetDefaultChannel(), TChannel::GetNumberOfChannels(), GetOutputFilename(), RESET_COLOR, GValue::Size(), and TCompiledHistograms::Write().
Referenced by CloseFile().
Member Data Documentation
fColumnWidth
size_t StoppableThread::fColumnWidth = 20 static private inherited
Definition at line 108 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::ColumnWidth(), StoppableThread::ColumnWidth(), StoppableThread::Print(), StoppableThread::Progress(), and StoppableThread::Status().
fCompiledHistograms
TCompiledHistograms TFragHistLoop::fCompiledHistograms private
Definition at line 69 of file TFragHistLoop.h.
Referenced by AddCutFile(), ClearHistograms(), GetGates(), GetLibraryName(), GetObjects(), Iteration(), LoadLibrary(), OpenFile(), and Write().
fForceStop
std::atomic_bool StoppableThread::fForceStop {false} private inherited
Definition at line 120 of file StoppableThread.h.
fInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > TFragHistLoop::fInputQueue private
Definition at line 78 of file TFragHistLoop.h.
Referenced by ClearQueue(), InputQueue(), and Iteration().
fInputSize
std::atomic_long StoppableThread::fInputSize {0} private inherited
number of items in the input (queue), only updated within Iteration(), so not always fully up-to-date (signed to hold error from queue::pop)
Definition at line 102 of file StoppableThread.h.
Referenced by StoppableThread::InputSize(), StoppableThread::InputSize(), StoppableThread::Progress(), and StoppableThread::Status().
fItemsPopped
std::atomic_size_t StoppableThread::fItemsPopped {0} private inherited
number of items popped from input queue
Definition at line 101 of file StoppableThread.h.
Referenced by StoppableThread::IncrementItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::ItemsPopped(), StoppableThread::Progress(), and StoppableThread::Status().
fName
std::string StoppableThread::fName private inherited
Definition at line 106 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), and StoppableThread::Name().
fOutputFile
TFile* TFragHistLoop::fOutputFile private
Definition at line 74 of file TFragHistLoop.h.
Referenced by CloseFile(), Iteration(), OpenFile(), and Write().
fOutputFilename
std::string TFragHistLoop::fOutputFilename private
Definition at line 75 of file TFragHistLoop.h.
Referenced by CloseFile(), GetOutputFilename(), OpenFile(), and SetOutputFilename().
fPaused
std::atomic_bool StoppableThread::fPaused {false} private inherited
Definition at line 121 of file StoppableThread.h.
Referenced by StoppableThread::IsPaused(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fPausedWait
std::condition_variable StoppableThread::fPausedWait private inherited
Definition at line 122 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPauseMutex
std::mutex StoppableThread::fPauseMutex private inherited
Definition at line 123 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fRunning
std::atomic_bool StoppableThread::fRunning {false} private inherited
Definition at line 119 of file StoppableThread.h.
Referenced by StoppableThread::IsRunning(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fStatusThread
std::thread StoppableThread::fStatusThread static private inherited
Definition at line 117 of file StoppableThread.h.
Referenced by StoppableThread::~StoppableThread(), StoppableThread::join_status_thread(), and StoppableThread::start_status_thread().
fStatusThreadOn
bool StoppableThread::fStatusThreadOn = false static private inherited
Definition at line 115 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::start_status_thread(), StoppableThread::status_out_loop(), and StoppableThread::stop_status_thread().
fStatusWidth
size_t StoppableThread::fStatusWidth = 80 static private inherited
Definition at line 109 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::Print(), StoppableThread::StatusWidth(), and StoppableThread::StatusWidth().
fThread
std::thread StoppableThread::fThread private inherited
Definition at line 118 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), and StoppableThread::Join().
fThreadMap
std::map< std::string, StoppableThread * > StoppableThread::fThreadMap static private inherited
Definition at line 113 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::AnyThreadRunning(), StoppableThread::AnyThreadStatus(), StoppableThread::ClearAllQueues(), StoppableThread::Get(), StoppableThread::GetAll(), StoppableThread::GetNThreads(), StoppableThread::PauseAll(), StoppableThread::Print(), StoppableThread::ResumeAll(), StoppableThread::SendStop(), StoppableThread::status_out(), and StoppableThread::StopAll().