GRSISort: TS3Hit Class Reference
TS3Hit Class Reference
Detectors
Detailed Description
Definition at line 12 of file TS3Hit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TS3Hit ()
TS3Hit (const TFragment &)
TS3Hit (const TS3Hit &)
TS3Hit (TS3Hit &&) noexcept=default
~TS3Hit () override=default
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &val)
virtual void AppendTimeStamp (const Long64_t &val)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
void Copy (TObject &, bool) const override
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
Int_t GetArrayPosition () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual int GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
std::string GetDistanceStr () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
Double_t GetFitTime () const
Bool_t GetIsDownstream () const
virtual Short_t GetKValue () const
const char * GetName () const override
Double_t GetPhi (double offset=0) const
virtual TVector3 GetPosition () const
virtual TVector3 GetPosition (Double_t) const
TVector3 GetPosition (bool smear=false) const
TVector3 GetPosition (Double_t phioffset, bool smear=false) const
TVector3 GetPosition (Double_t phioffset, Double_t dist, bool smear=false) const
EPpgPattern GetPPGStatus () const
Short_t GetRing () const
Short_t GetSector () const
virtual Int_t GetSegment () const
Double_t GetSignalToNoise () const
Double_t GetTheta (double offset=0, TVector3 *vec=nullptr) const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool operator< (const TDetectorHit &rhs) const
TS3Hit & operator= (const TS3Hit &)=default
TS3Hit & operator= (TS3Hit &&) noexcept=default
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Bool_t SectorsDownstream () const
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &val)
virtual void SetCfd (const Int_t &val)
virtual void SetCfd (const uint32_t &val)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &energy) const
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetIsDownstream (Bool_t dwnstrm)
void SetKValue (const Short_t &temp_kval)
void SetRingNumber ()
void SetRingNumber (int n)
void SetRingNumber (Short_t rn)
void SetRingNumber (TFragment &frag)
void SetSectorNumber ()
void SetSectorNumber (int n)
void SetSectorNumber (Short_t sn)
void SetSectorNumber (TFragment &frag)
void SetSig2Noise (Double_t sig2noise)
Double_t SetTime (const Double_t &time) const
void SetTimeFit (Double_t time)
virtual void SetTimeStamp (const Long64_t &val)
void SetWavefit (const TFragment &)
void SetWaveform (const std::vector< Short_t > &val)
bool TestHitBit (EBitFlag flag) const
virtual size_t WaveSize () const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Private Member Functions
Double_t GetDefaultDistance () const
Double_t GetDefaultPhiOffset () const
Private Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
TChannel * fChannel {nullptr}
Float_t fCharge {0.}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
Bool_t fIsDownstream {false}
Short_t fKValue {0}
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Short_t fRing {0}
Short_t fSector {0}
Double_t fSig2Noise {0.}
Double_t fTime {0.}
Double_t fTimeFit {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Private Attributes
static TVector3 fBeamDirection
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong inherited
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 50 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong inherited
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 72 of file TDetectorHit.h.
Constructor & Destructor Documentation
TS3Hit() [1/4]
TS3Hit::TS3Hit ()
Definition at line 9 of file TS3Hit.cxx.
References Clear().
TS3Hit() [2/4]
TS3Hit::TS3Hit (const TFragment & frag) explicit
Definition at line 14 of file TS3Hit.cxx.
References TDetectorHit::Copy(), GetArrayPosition(), TDetectorHit::GetChannel(), TGRSIMnemonic::kSiLiS3, and SetIsDownstream().
TS3Hit() [3/4]
TS3Hit::TS3Hit (const TS3Hit & rhs)
Definition at line 25 of file TS3Hit.cxx.
References Clear(), and Copy().
TS3Hit() [4/4]
TS3Hit::TS3Hit (TS3Hit &&) default noexcept
~TS3Hit()
TS3Hit::~TS3Hit () override default
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual inherited
!
Reimplemented in TFippsHit, TGriffinHit, TIfinHit, TTdrCloverHit, and TTdrTigressHit.
Definition at line 184 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & val) inline inherited
!
Definition at line 117 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 119 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual inherited
!
Definition at line 145 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::Print(), TFippsTACHit::TempCorrectedCharge(), and TTACHit::TempCorrectedCharge().
Clear()
void TS3Hit::Clear (Option_t * opt = "") override
Definition at line 51 of file TS3Hit.cxx.
References TDetectorHit::Clear(), fIsDownstream, fRing, and fSector.
Referenced by TS3Hit(), and TS3Hit().
ClearChannel()
void TDetectorHit::ClearChannel () inline inherited
Definition at line 176 of file TDetectorHit.h.
References TDetectorHit::fChannel, TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline inherited
Definition at line 171 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual inherited
Definition at line 94 of file TDetectorHit.h.
References TDetectorHit::fBitFlags.
Referenced by TBgoHit::TBgoHit(), TDetectorHit::TDetectorHit(), TSiLiHit::Clear(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static inherited
Definition at line 213 of file TDetectorHit.cxx.
References TDetectorHit::GetEnergy().
Copy() [1/2]
void TS3Hit::Copy (TObject & rhs) const override
Definition at line 31 of file TS3Hit.cxx.
References TDetectorHit::Copy(), fIsDownstream, fRing, fSector, fSig2Noise, and fTimeFit.
Referenced by TS3Hit(), and Copy().
Copy() [2/2]
void TS3Hit::Copy (TObject & rhs, bool waveform) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 43 of file TS3Hit.cxx.
References Copy(), and TDetectorHit::CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual inherited
!
Definition at line 123 of file TDetectorHit.cxx.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TBgoHit::TBgoHit(), TDemandHit::TDemandHit(), TDescantHit::TDescantHit(), TDetectorHit::TDetectorHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TAriesHit::Copy(), TDemandHit::Copy(), TDemandHit::Copy(), TDescantHit::Copy(), TDescantHit::Copy(), TDetectorHit::Copy(), TEagleHit::Copy(), TEmmaHit::Copy(), TGriffinHit::Copy(), TLaBrHit::Copy(), TPacesHit::Copy(), TPinDiodeHit::Copy(), TRcmpHit::Copy(), Copy(), TSceptarHit::Copy(), TSharc2Hit::Copy(), TSharcHit::Copy(), TTACHit::Copy(), TTdrCloverHit::Copy(), TTdrPlasticHit::Copy(), TTdrTigressHit::Copy(), TTigressHit::Copy(), TTipHit::Copy(), TTipHit::Copy(), TTrificHit::Copy(), TZeroDegreeHit::Copy(), and TZeroDegreeHit::Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual inherited
!
Definition at line 143 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TSharc2Hit::GetBackAddress(), TSharcHit::GetBackAddress(), TSharc2Hit::GetFrontAddress(), TSharcHit::GetFrontAddress(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TSharc2Hit::GetPadAddress(), TSharcHit::GetPadAddress(), TFragment::GetSharcMesyBoard(), TEagleHit::Print(), TFragment::Print(), TPinDiodeHit::Print(), TTipHit::SetUpNumbering(), and TTigressHit::SumHit().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual inherited
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TBgoHit, TFippsBgoHit, TFippsHit, TFippsLaBrBgoHit, TGriffinBgoHit, TGriffinHit, TIfinBgoHit, TIfinHit, TLaBrBgoHit, TRcmpHit, TTdrCloverHit, TTdrTigressHit, and TTigressHit.
Definition at line 163 of file TDetectorHit.h.
References TDetectorHit::GetDetector().
Referenced by MakeAnalysisHistograms().
GetArrayPosition()
Int_t TS3Hit::GetArrayPosition () const inline
Definition at line 25 of file TS3Hit.h.
References TMnemonic::ArrayPosition(), TDetectorHit::GetChannel(), and TChannel::GetMnemonic().
Referenced by TS3Hit(), GetDefaultDistance(), and SectorsDownstream().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static inherited
Definition at line 182 of file TDetectorHit.h.
References TDetectorHit::fBeamDirection.
Referenced by TSiLiHit::GetDoppler(), and TTigressHit::GetDoppler().
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual inherited
!
Reimplemented in TDescantHit, and TZeroDegreeHit.
Definition at line 142 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TFippsHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), DefaultSuppression(), TFragment::Get4GCfd(), TDescantHit::GetCfd(), TZeroDegreeHit::GetCfd(), TDescantHit::GetRemainder(), TZeroDegreeHit::GetRemainder(), TSharc2Hit::GetSomeTime(), TSharcHit::GetSomeTime(), TDetectorHit::GetTime(), TTigressHit::GetTimeToTrigger(), TEagleHit::Print(), TFragment::Print(), and TTigressHit::SumHit().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline inherited
!
Definition at line 148 of file TDetectorHit.h.
References TDetectorHit::fAddress, TDetectorHit::fChannel, TChannel::GetChannel(), TDetectorHit::IsChannelSet(), TDetectorHit::kIsChannelSet, and TDetectorHit::SetHitBit().
Referenced by TS3Hit(), TTigress::AddFragment(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), GetArrayPosition(), TDetectorHit::GetCharge(), TDetectorHit::GetCrystal(), GetDefaultDistance(), GetDefaultPhiOffset(), TDetectorHit::GetDetector(), GetDistanceStr(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TDetectorHit::GetEnergyNonlinearity(), TSiLiHit::GetFitEnergy(), TDetectorHit::GetName(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TDetectorHit::GetSegment(), TFippsTACHit::GetTempCorrectedEnergy(), TTACHit::GetTempCorrectedEnergy(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFit(), TDetectorHit::GetTimeStampNs(), TDetectorHit::GetTimeStampUnit(), TFragment::GetTZero(), TFragment::Print(), SectorsDownstream(), TTipHit::SetUpNumbering(), and TSiLiHit::SetWavefit().
GetChannelNumber()
int TDetectorHit::GetChannelNumber () const virtual inherited
!
Definition at line 218 of file TDetectorHit.cxx.
References TDetectorHit::fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), MakeGRIFFINChargeHsts(), and MakeGRIFFINEnergyHsts().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual inherited
!
Definition at line 58 of file TDetectorHit.cxx.
References TDetectorHit::Charge(), TDetectorHit::fKValue, TDetectorHit::GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), TSharc2Hit::GetBackCharge(), TSharcHit::GetBackCharge(), TSharc2Hit::GetFrontCharge(), TSharcHit::GetFrontCharge(), TSharc2Hit::GetPadCharge(), TSharcHit::GetPadCharge(), TFippsTACHit::GetTempCorrectedCharge(), TTACHit::GetTempCorrectedCharge(), main(), MakeGRIFFINChargeHsts(), TFragment::Print(), and TTigressHit::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual inherited
!
Definition at line 204 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TTigressHit::GetLastPosition(), TFippsHit::GetPosition(), TGriffinHit::GetPosition(), TIfinHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrTigressHit::GetPosition(), TTigress::GetPosition(), TFippsHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TTdrCloverHit::Print(), and TTdrTigressHit::Print().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const inherited
Definition at line 261 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, and TDetectorHit::SetHitBit().
GetDefaultDistance()
Double_t TS3Hit::GetDefaultDistance () const private
Definition at line 118 of file TS3Hit.cxx.
References GetArrayPosition(), TDetectorHit::GetChannel(), GetDistanceStr(), and TGRSIMnemonic::kSiLiS3.
Referenced by GetPosition(), and GetPosition().
GetDefaultPhiOffset()
Double_t TS3Hit::GetDefaultPhiOffset () const private
Definition at line 106 of file TS3Hit.cxx.
References TDetectorHit::GetChannel(), and TGRSIMnemonic::kSiLiS3.
Referenced by GetPosition().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual inherited
!
Definition at line 186 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetDetectorNumber().
Referenced by Addback(), Addback(), TTigress::AddFragment(), TTigressHit::Compare(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultAddback(), DefaultFippsAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinAddback(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), CrossTalkHelper::Exec(), CrossTalk::FillHistograms(), TBgoHit::GetArrayNumber(), TDetectorHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TGriffinHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TIfinHit::GetArrayNumber(), TLaBrBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TTdrCloverHit::GetArrayNumber(), TTdrTigressHit::GetArrayNumber(), TTigressHit::GetArrayNumber(), TSharc2::GetDeadLayerThickness(), TSharc::GetDeadLayerThickness(), TSharc2::GetDetectorThickness(), TSharc::GetDetectorThickness(), TTigressHit::GetLastPosition(), TSharc::GetPadDeadLayerThickness(), TSharc::GetPadThickness(), TAriesHit::GetPosition(), TDemand::GetPosition(), TDescantHit::GetPosition(), TDescantHit::GetPosition(), TEagleHit::GetPosition(), TFippsHit::GetPosition(), TFippsLaBrHit::GetPosition(), TGriffinHit::GetPosition(), TIfinHit::GetPosition(), TLaBrHit::GetPosition(), TPacesHit::GetPosition(), TPinDiodeHit::GetPosition(), TSceptarHit::GetPosition(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TTdrCloverHit::GetPosition(), TTdrPlasticHit::GetPosition(), TTdrSiLiHit::GetPosition(), TTdrTigressHit::GetPosition(), TTigress::GetPosition(), TTrificHit::GetPosition(), TTrific::GetXYGrid(), main(), MakeAnalysisHistograms(), TAriesHit::Print(), TDemandHit::Print(), TDescantHit::Print(), TEagleHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TPinDiodeHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TSharc2Hit::Print(), TSharcHit::Print(), TTACHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), and PromptCoincidence().
GetDistanceStr()
std::string TS3Hit::GetDistanceStr () const inline
Definition at line 32 of file TS3Hit.h.
References TMnemonic::ArraySubPositionString(), TDetectorHit::GetChannel(), and TChannel::GetMnemonic().
Referenced by GetDefaultDistance().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual inherited
Reimplemented in TCSMHit, TSharc2Hit, TSharcHit, and TSiLiHit.
Definition at line 73 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), TDetectorHit::Charge(), TDetectorHit::fEnergy, TDetectorHit::fKValue, TDetectorHit::GetChannel(), TDetectorHit::GetEnergyNonlinearity(), TDetectorHit::kIsEnergySet, TDetectorHit::SetEnergy(), TDetectorHit::TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::CompareEnergy(), TFippsHit::CompareEnergy(), TGriffinHit::CompareEnergy(), TIfinHit::CompareEnergy(), TTdrCloverHit::CompareEnergy(), TTdrTigressHit::CompareEnergy(), TTigressHit::CompareEnergy(), ComptonHists(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), DefaultSuppression(), ExampleFragmentHelper::Exec(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), ExampleFragmentSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), TSharc2Hit::GetDeltaBackE(), TSharcHit::GetDeltaBackE(), TSharc2Hit::GetDeltaE(), TSharcHit::GetDeltaE(), TSharc2Hit::GetDeltaFrontE(), TSharcHit::GetDeltaFrontE(), TTigressHit::GetDoppler(), TSharc2Hit::GetEnergy(), TSharcHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TSharc2Hit::GetPadE(), TSharcHit::GetPadE(), TDetectorHit::GetTime(), TFragment::GetTZero(), MakeAnalysisHistograms(), MakeGRIFFINEnergyHsts(), TDetectorHit::operator<(), TAriesHit::Print(), TDemandHit::Print(), TDescantHit::Print(), TEagleHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TPinDiodeHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), PromptCoincidence(), PromptCoincidence(), and TTigressHit::SumHit().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual inherited
Definition at line 96 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by TDetectorHit::GetEnergy().
GetFitTime()
Double_t TS3Hit::GetFitTime () const inline
!
Definition at line 46 of file TS3Hit.h.
References fTimeFit.
GetIsDownstream()
Bool_t TS3Hit::GetIsDownstream () const inline
Definition at line 24 of file TS3Hit.h.
References fIsDownstream.
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual inherited
!
Definition at line 146 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), GriffinKValueHelper::Exec(), CrossTalk::FillHistograms(), GriffinKValueSelector::FillHistograms(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TTACHit::GetTempCorrectedEnergy(), and MakeGRIFFINChargeHsts().
GetName()
const char * TDetectorHit::GetName () const override inherited
!
Definition at line 160 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel().
Referenced by TFragment::IsDetector(), TDetectorHit::Print(), TTigressHit::Print(), and TTigressHit::SetWavefit().
GetPhi()
Double_t TS3Hit::GetPhi (double offset = 0) const inline
Definition at line 66 of file TS3Hit.h.
References TDetectorHit::GetPosition().
GetPosition() [1/5]
virtual TVector3 TDetectorHit::GetPosition () const inline virtual inherited
!
Reimplemented in TAriesHit, TDemandHit, TDescantHit, TEagleHit, TEmmaHit, TFippsHit, TFippsLaBrHit, TGriffinHit, TIfinHit, TLaBrHit, TPacesHit, TPinDiodeHit, TSceptarHit, TSharc2Hit, TSharcHit, TSiLiHit, TTdrCloverHit, TTdrPlasticHit, TTdrSiLiHit, TTdrTigressHit, TTipHit, and TTrificHit.
Definition at line 135 of file TDetectorHit.h.
Referenced by TTigressHit::GetDoppler(), GetPhi(), GetTheta(), and TTigressHit::Print().
GetPosition() [2/5]
virtual TVector3 TDetectorHit::GetPosition (Double_t) const inline virtual inherited
!
Reimplemented in TAriesHit, TCSMHit, TDescantHit, TEagleHit, TEmmaHit, TFippsLaBrHit, TLaBrHit, TPacesHit, TPinDiodeHit, TSceptarHit, TSharc2Hit, TSharcHit, TSiLiHit, TTdrPlasticHit, TTdrSiLiHit, and TTigressHit.
Definition at line 134 of file TDetectorHit.h.
References TDetectorHit::GetPosition().
Referenced by TDetectorHit::GetPosition().
GetPosition() [3/5]
TVector3 TS3Hit::GetPosition (bool smear = false) const
Definition at line 87 of file TS3Hit.cxx.
References GetDefaultDistance(), GetDefaultPhiOffset(), TS3::GetPosition(), GetRing(), GetSector(), and SectorsDownstream().
GetPosition() [4/5]
TVector3 TS3Hit::GetPosition (Double_t phioffset, bool smear = false) const
Definition at line 82 of file TS3Hit.cxx.
References GetDefaultDistance(), TS3::GetPosition(), GetRing(), GetSector(), and SectorsDownstream().
GetPosition() [5/5]
TVector3 TS3Hit::GetPosition (Double_t phioffset, Double_t dist, bool smear = false) const
Definition at line 77 of file TS3Hit.cxx.
References TS3::GetPosition(), GetRing(), GetSector(), and SectorsDownstream().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const inherited
Definition at line 245 of file TDetectorHit.cxx.
References TDetectorHit::fCycleTimeStamp, TDetectorHit::fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), TDetectorHit::GetTimeStampNs(), TDetectorHit::IsPPGSet(), TDetectorHit::kIsPPGSet, kJunk, and TDetectorHit::SetHitBit().
GetRing()
Short_t TS3Hit::GetRing () const inline
Definition at line 22 of file TS3Hit.h.
References fRing.
Referenced by GetPosition(), GetPosition(), and GetPosition().
GetSector()
Short_t TS3Hit::GetSector () const inline
Definition at line 23 of file TS3Hit.h.
References fSector.
Referenced by GetPosition(), GetPosition(), and GetPosition().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual inherited
!
Definition at line 195 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetSegmentNumber().
Referenced by DefaultAddback(), TBgoHit::GetArrayNumber(), TFippsBgoHit::GetArrayNumber(), TFippsLaBrBgoHit::GetArrayNumber(), TGriffinBgoHit::GetArrayNumber(), TIfinBgoHit::GetArrayNumber(), TRcmpHit::GetArrayNumber(), TSharc2Hit::GetBackStrip(), TSharcHit::GetBackStrip(), TSharc2Hit::GetFrontStrip(), TSharcHit::GetFrontStrip(), TTigressHit::GetLastPosition(), TSiLiHit::GetPin(), TSharc2Hit::GetPosition(), TSharcHit::GetPosition(), TSiLiHit::GetPreamp(), TSiLiHit::GetRing(), TSiLiHit::GetSector(), TSiLiHit::MagnetShadow(), TTrificHit::Print(), SetRingNumber(), SetRingNumber(), SetSectorNumber(), SetSectorNumber(), and TSiLiHit::SumHit().
GetSignalToNoise()
Double_t TS3Hit::GetSignalToNoise () const inline
!
Definition at line 47 of file TS3Hit.h.
References fSig2Noise.
GetTheta()
Double_t TS3Hit::GetTheta (double offset = 0, TVector3 * vec = nullptr) const inline
Definition at line 68 of file TS3Hit.h.
References TDetectorHit::GetPosition().
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual inherited
Returns a time value to the nearest nanosecond!
Reimplemented in TCSMHit.
Definition at line 45 of file TDetectorHit.cxx.
References TDetectorHit::fTime, TDetectorHit::GetCfd(), TDetectorHit::GetChannel(), TDetectorHit::GetEnergy(), TChannel::GetTime(), TDetectorHit::GetTimeStamp(), TDetectorHit::IsTimeSet(), and TDetectorHit::SetTime().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), Addback(), Addback(), ComptonPolarimetryHelper::Coincident(), TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultAddback(), DefaultAddback(), DefaultFippsAddback(), DefaultFippsSuppression(), DefaultGriffinAddback(), DefaultGriffinSuppression(), DefaultIfinAddback(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), DefaultSuppression(), TSiLi::fCoincidenceTime(), TSharc2Hit::GetDeltaBackT(), TSharcHit::GetDeltaBackT(), TSharc2Hit::GetDeltaFrontT(), TSharcHit::GetDeltaFrontT(), TSharc2Hit::GetDeltaT(), TSharcHit::GetDeltaT(), TSharc2Hit::GetPadT(), TSharcHit::GetPadT(), TFippsTACHit::GetTempCorrectedCharge(), TTACHit::GetTempCorrectedCharge(), TDetectorHit::GetTimeSinceTapeMove(), main(), MakeAnalysisHistograms(), TAriesHit::Print(), TDemandHit::Print(), TDescantHit::Print(), TDetectorHit::Print(), TFippsHit::Print(), TFippsLaBrHit::Print(), TFippsTACHit::Print(), TGriffinHit::Print(), TIfinHit::Print(), TLaBrHit::Print(), TPacesHit::Print(), TPinDiodeHit::Print(), TRcmpHit::Print(), TSceptarHit::Print(), TTACHit::Print(), TTdrCloverHit::Print(), TTdrPlasticHit::Print(), TTdrSiLiHit::Print(), TTdrTigressHit::Print(), TTigressHit::Print(), TTipHit::Print(), TTrificHit::Print(), TZeroDegreeHit::Print(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), PromptCoincidence(), TTigressHit::SumHit(), TFippsTACHit::TempCorrectedCharge(), TTACHit::TempCorrectedCharge(), ComptonPolarimetryHelper::TimeDiff(), TimeRandom(), and TimeRandom().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const inherited
returns time in ns, minus the time of the last tape move
Definition at line 277 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TDetectorHit::GetTime(), TDetectorHit::GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual inherited
Definition at line 138 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by ComptonHists(), TimeWalkHelper::Exec(), TimeWalkSelector::FillHistograms(), TDetectorHit::GetTime(), TSiLiHit::GetTimeFitCfd(), TSiLiHit::GetTimeFitns(), TSiLiHit::GetTimeStampLow(), TDetectorHit::GetTimeStampNs(), TTigressHit::GetTimeToTrigger(), main(), MakeAnalysisHistograms(), TFragment::operator<(), TFragment::operator>(), TDetectorHit::Print(), TEagleHit::Print(), TFragment::Print(), TGriffinHit::Print(), and TTigressHit::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual inherited
Definition at line 227 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), TDetectorHit::GetTimeStamp(), and TDetectorHit::GetTimeStampUnit().
Referenced by ComptonPolarimetryHelper::Coincident(), TFragment::GetCycleNumber(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TFragment::GetTimeInCycle(), TDetectorHit::GetTimeSinceTapeMove(), TDetectorHit::Print(), TGriffinHit::Print(), and ComptonPolarimetryHelper::TimeDiff().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual inherited
!
Definition at line 236 of file TDetectorHit.cxx.
References TDetectorHit::GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by TDetectorHit::GetTimeStampNs(), and TDetectorHit::Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline inherited
!
Definition at line 147 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TAriesHit::TAriesHit(), TDescantHit::TDescantHit(), TSceptarHit::TSceptarHit(), TTdrPlasticHit::TTdrPlasticHit(), TZeroDegreeHit::TZeroDegreeHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculatePsdAndPartialSums(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TPulseAnalyzer::SetData(), and TTigressHit::SetWavefit().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual inherited
!
Definition at line 102 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TSceptarHit::CalculateCfdMonitor(), TZeroDegreeHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), TZeroDegreeHit::CalculateSmoothedWaveform(), TFragment::Print(), and TPulseAnalyzer::SetData().
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected inherited
Definition at line 191 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected inherited
Definition at line 190 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected inherited
Definition at line 193 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected inherited
Definition at line 192 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, TDetectorHit::kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline inherited
Definition at line 88 of file TDetectorHit.h.
References TDetectorHit::GetEnergy().
operator=() [1/2]
TS3Hit & TS3Hit::operator= (const TS3Hit &) default
operator=() [2/2]
TS3Hit & TS3Hit::operator= (TS3Hit &&) default noexcept
Print() [1/2]
void TS3Hit::Print (Option_t * opt = "") const override
Definition at line 92 of file TS3Hit.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TS3Hit::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetectorHit.
Definition at line 97 of file TS3Hit.cxx.
SectorsDownstream()
Bool_t TS3Hit::SectorsDownstream () const
Definition at line 68 of file TS3Hit.cxx.
References GetArrayPosition(), TDetectorHit::GetChannel(), and TGRSIMnemonic::kSiLiS3.
Referenced by GetPosition(), GetPosition(), and GetPosition().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline inherited
!
Definition at line 109 of file TDetectorHit.h.
References TDetectorHit::fAddress.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TTigress::AddFragment(), and TTigressHit::SumHit().
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & val) inline virtual inherited
!
Definition at line 113 of file TDetectorHit.h.
References TDetectorHit::fCfd.
Referenced by TEagleHit::TEagleHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), and TTigressHit::SumHit().
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 115 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & val) inline virtual inherited
! this function automatically randomizes the integer provided
Definition at line 114 of file TDetectorHit.h.
References TDetectorHit::fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline inherited
!
Definition at line 111 of file TDetectorHit.h.
References TDetectorHit::fCharge.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDescantHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline inherited
! this function automatically randomizes the integer provided
Definition at line 112 of file TDetectorHit.h.
References TDetectorHit::fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & energy) const inline inherited
Definition at line 121 of file TDetectorHit.h.
References TDetectorHit::fEnergy, TDetectorHit::kIsEnergySet, and TDetectorHit::SetHitBit().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::SumHit(), and TTigressHit::SumHit().
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const inherited
Definition at line 284 of file TDetectorHit.cxx.
References TDetectorHit::fBitFlags, and TTransientBits< T >::SetBit().
Referenced by TDetectorHit::ClearChannel(), TDetectorHit::ClearEnergy(), TDetectorHit::GetChannel(), TDetectorHit::GetCycleTimeStamp(), TDetectorHit::GetPPGStatus(), TDetectorHit::SetEnergy(), TTdrCloverHit::SetTdrCloverFlag(), TDetectorHit::SetTime(), TSiLiHit::SumHit(), and TSiLiHit::UseFitCharge().
SetIsDownstream()
void TS3Hit::SetIsDownstream (Bool_t dwnstrm) inline
Definition at line 51 of file TS3Hit.h.
References fIsDownstream.
Referenced by TS3Hit().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline inherited
!
Definition at line 110 of file TDetectorHit.h.
References TDetectorHit::fKValue.
Referenced by TEagleHit::TEagleHit(), TPinDiodeHit::TPinDiodeHit(), TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), and TTdrTigressHit::Add().
SetRingNumber() [1/4]
void TS3Hit::SetRingNumber () inline
Definition at line 55 of file TS3Hit.h.
References fRing, and TDetectorHit::GetSegment().
SetRingNumber() [2/4]
void TS3Hit::SetRingNumber (int n) inline
Definition at line 58 of file TS3Hit.h.
References fRing.
SetRingNumber() [3/4]
void TS3Hit::SetRingNumber (Short_t rn) inline
Definition at line 49 of file TS3Hit.h.
References fRing.
Referenced by TS3::AddFragment(), and TS3::BuildPixels().
SetRingNumber() [4/4]
void TS3Hit::SetRingNumber (TFragment & frag) inline
Definition at line 53 of file TS3Hit.h.
References fRing, and TDetectorHit::GetSegment().
SetSectorNumber() [1/4]
void TS3Hit::SetSectorNumber () inline
Definition at line 56 of file TS3Hit.h.
References fSector, and TDetectorHit::GetSegment().
SetSectorNumber() [2/4]
void TS3Hit::SetSectorNumber (int n) inline
Definition at line 57 of file TS3Hit.h.
References fSector.
SetSectorNumber() [3/4]
void TS3Hit::SetSectorNumber (Short_t sn) inline
Definition at line 50 of file TS3Hit.h.
References fSector.
Referenced by TS3::AddFragment(), and TS3::BuildPixels().
SetSectorNumber() [4/4]
void TS3Hit::SetSectorNumber (TFragment & frag) inline
Definition at line 54 of file TS3Hit.h.
References fSector, and TDetectorHit::GetSegment().
SetSig2Noise()
void TS3Hit::SetSig2Noise (Double_t sig2noise) inline
Definition at line 62 of file TS3Hit.h.
References fSig2Noise.
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline inherited
Definition at line 127 of file TDetectorHit.h.
References TDetectorHit::fTime, TDetectorHit::kIsTimeSet, and TDetectorHit::SetHitBit().
Referenced by TFippsHit::Add(), TGriffinHit::Add(), TIfinHit::Add(), TTdrCloverHit::Add(), TTdrTigressHit::Add(), TDetectorHit::GetTime(), and TTigressHit::SumHit().
SetTimeFit()
void TS3Hit::SetTimeFit (Double_t time) inline
Definition at line 61 of file TS3Hit.h.
References fTimeFit.
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & val) inline virtual inherited
!
Definition at line 118 of file TDetectorHit.h.
References TDetectorHit::fTimeStamp.
Referenced by TEagleHit::TEagleHit(), and TPinDiodeHit::TPinDiodeHit().
SetWavefit()
void TS3Hit::SetWavefit (const TFragment & frag)
Definition at line 59 of file TS3Hit.cxx.
References TPulseAnalyzer::fit_newT0(), fSig2Noise, fTimeFit, TPulseAnalyzer::get_sig2noise(), and TPulseAnalyzer::IsSet().
Referenced by TS3::AddFragment().
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & val) inline inherited
!
Definition at line 116 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TTdrPlasticHit::TTdrPlasticHit(), TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), and TZeroDegreeHit::AnalyzeWaveform().
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline inherited
Definition at line 187 of file TDetectorHit.h.
References TDetectorHit::fBitFlags, and TTransientBits< T >::TestBit().
Referenced by TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TTdrCloverHit::NPileUps(), and TTdrCloverHit::PUHit().
WaveSize()
virtual size_t TDetectorHit::WaveSize () const inline virtual inherited
!
Definition at line 103 of file TDetectorHit.h.
References TDetectorHit::fWaveform.
Referenced by TDescantHit::AnalyzeWaveform(), TSceptarHit::AnalyzeWaveform(), TZeroDegreeHit::AnalyzeWaveform(), TDescantHit::CalculateCfdAndMonitor(), TSceptarHit::CalculateCfdAndMonitor(), TZeroDegreeHit::CalculateCfdAndMonitor(), TDescantHit::CalculateCfdMonitor(), TDescantHit::CalculatePartialSum(), TZeroDegreeHit::CalculatePartialSum(), TDescantHit::CalculateSmoothedWaveform(), TSceptarHit::CalculateSmoothedWaveform(), and TZeroDegreeHit::CalculateSmoothedWaveform().
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} private inherited
address of the the channel in the DAQ.
Definition at line 196 of file TDetectorHit.h.
Referenced by TDetectorHit::TDetectorHit(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetAddress(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), and TDetectorHit::SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static private inherited
Definition at line 213 of file TDetectorHit.h.
Referenced by TDetectorHit::GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable private inherited
Definition at line 211 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearTransients(), TDetectorHit::Copy(), TDetectorHit::IsChannelSet(), TDetectorHit::IsEnergySet(), TDetectorHit::IsPPGSet(), TDetectorHit::IsTimeSet(), TDetectorHit::SetHitBit(), and TDetectorHit::TestHitBit().
fCfd
Float_t TDetectorHit::fCfd {0} private inherited
CFD time of the Hit.
Definition at line 199 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCfd(), TDetectorHit::SetCfd(), TDetectorHit::SetCfd(), and TDetectorHit::SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private inherited
!
Definition at line 208 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearChannel(), TDetectorHit::Copy(), and TDetectorHit::GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} private inherited
charge collected from the hit
Definition at line 197 of file TDetectorHit.h.
Referenced by TDetectorHit::Charge(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::SetCharge(), and TDetectorHit::SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private inherited
!
Definition at line 207 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private inherited
! Energy of the Hit.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::ClearEnergy(), TDetectorHit::Copy(), TDetectorHit::GetEnergy(), and TDetectorHit::SetEnergy().
fIsDownstream
Bool_t TS3Hit::fIsDownstream {false} private
Definition at line 87 of file TS3Hit.h.
Referenced by Clear(), Copy(), GetIsDownstream(), and SetIsDownstream().
fKValue
Short_t TDetectorHit::fKValue {0} private inherited
integration value.
Definition at line 198 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TDetectorHit::GetKValue(), and TDetectorHit::SetKValue().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private inherited
!
Definition at line 205 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetCycleTimeStamp(), and TDetectorHit::GetPPGStatus().
fRing
Short_t TS3Hit::fRing {0} private
Definition at line 88 of file TS3Hit.h.
Referenced by Clear(), Copy(), GetRing(), SetRingNumber(), SetRingNumber(), SetRingNumber(), and SetRingNumber().
fSector
Short_t TS3Hit::fSector {0} private
Definition at line 89 of file TS3Hit.h.
Referenced by Clear(), Copy(), GetSector(), SetSectorNumber(), SetSectorNumber(), SetSectorNumber(), and SetSectorNumber().
fSig2Noise
Double_t TS3Hit::fSig2Noise {0.} private
Definition at line 92 of file TS3Hit.h.
Referenced by Copy(), GetSignalToNoise(), SetSig2Noise(), and SetWavefit().
fTime
Double_t TDetectorHit::fTime {0.} mutable private inherited
! Calibrated Time of the hit
Definition at line 202 of file TDetectorHit.h.
Referenced by TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTime(), and TDetectorHit::SetTime().
fTimeFit
Double_t TS3Hit::fTimeFit {0.} private
Definition at line 91 of file TS3Hit.h.
Referenced by Copy(), GetFitTime(), SetTimeFit(), and SetWavefit().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} private inherited
Timestamp given to hit in ns.
Definition at line 200 of file TDetectorHit.h.
Referenced by TDetectorHit::AppendTimeStamp(), TDetectorHit::Clear(), TDetectorHit::Copy(), TDetectorHit::GetTimeStamp(), and TDetectorHit::SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform private inherited
Definition at line 201 of file TDetectorHit.h.
Referenced by TDetectorHit::AddWaveformSample(), TDetectorHit::Clear(), TDetectorHit::CopyWave(), TDetectorHit::GetWaveform(), TDetectorHit::HasWave(), TDetectorHit::SetWaveform(), and TDetectorHit::WaveSize().