GRSISort: TILLDetectorInformation Class Reference
TILLDetectorInformation Class Reference
Sorting
Detailed Description
This Class is designed to store setup dependent information. It is used to store existence of detector systems, etc.
Definition at line 23 of file TILLDetectorInformation.h.
Public Member Functions
TILLDetectorInformation ()
~TILLDetectorInformation () override
TEventBuildingLoop::EBuildMode BuildMode () const override
void Clear (Option_t *="") override
bool Fipps () const
bool FippsBgo () const
bool FippsLaBr () const
bool FippsLaBrBgo () const
bool FippsPulser () const
bool FippsTAC () const
void Print (Option_t *opt="") const override
void Set () override
void SetFipps (bool flag=true)
void SetFippsBgo (bool flag=true)
void SetFippsLaBr (bool flag=true)
void SetFippsLaBrBgo (bool flag=true)
void SetFippsPulser (bool flag=true)
void SetFippsTAC (bool flag=true)
Private Attributes
bool fFipps {false}
bool fFippsBgo {false}
bool fFippsLaBr {false}
bool fFippsLaBrBgo {false}
bool fFippsPulser {false}
bool fFippsTAC {false}
Constructor & Destructor Documentation
TILLDetectorInformation()
TILLDetectorInformation::TILLDetectorInformation ()
Default ctor for TILLDetectorInformation.
Definition at line 10 of file TILLDetectorInformation.cxx.
References Clear(), and Set().
~TILLDetectorInformation()
TILLDetectorInformation::~TILLDetectorInformation () override default
Member Function Documentation
BuildMode()
TEventBuildingLoop::EBuildMode TILLDetectorInformation::BuildMode () const override virtual
Set the detector information based on the available TChannels.
Select build mode based on available detectors
Reimplemented from TDetectorInformation.
Definition at line 19 of file TILLDetectorInformation.cxx.
References TEventBuildingLoop::kTimestamp.
Clear()
void TILLDetectorInformation::Clear (Option_t * = "") override
Definition at line 39 of file TILLDetectorInformation.cxx.
References TDetectorInformation::Clear(), and fFipps.
Referenced by TILLDetectorInformation().
Fipps()
bool TILLDetectorInformation::Fipps () const inline
Definition at line 41 of file TILLDetectorInformation.h.
References fFipps.
Referenced by Print().
FippsBgo()
bool TILLDetectorInformation::FippsBgo () const inline
Definition at line 42 of file TILLDetectorInformation.h.
References fFippsBgo.
Referenced by Print().
FippsLaBr()
bool TILLDetectorInformation::FippsLaBr () const inline
Definition at line 43 of file TILLDetectorInformation.h.
References fFippsLaBr.
Referenced by Print().
FippsLaBrBgo()
bool TILLDetectorInformation::FippsLaBrBgo () const inline
Definition at line 44 of file TILLDetectorInformation.h.
References fFippsLaBrBgo.
Referenced by Print().
FippsPulser()
bool TILLDetectorInformation::FippsPulser () const inline
Definition at line 46 of file TILLDetectorInformation.h.
References fFippsPulser.
Referenced by Print().
FippsTAC()
bool TILLDetectorInformation::FippsTAC () const inline
Definition at line 45 of file TILLDetectorInformation.h.
References fFippsTAC.
Referenced by Print().
Print()
void TILLDetectorInformation::Print (Option_t * opt = "") const override
Definition at line 24 of file TILLDetectorInformation.cxx.
References Fipps(), FippsBgo(), FippsLaBr(), FippsLaBrBgo(), FippsPulser(), and FippsTAC().
Set()
void TILLDetectorInformation::Set () override virtual
Sets the run info. This figures out what systems are available.
Reimplemented from TDetectorInformation.
Definition at line 49 of file TILLDetectorInformation.cxx.
References TChannel::GetChannelMap(), TILLMnemonic::kFipps, TILLMnemonic::kFippsBgo, TILLMnemonic::kFippsLaBr, TILLMnemonic::kFippsLaBrBgo, TILLMnemonic::kFippsPulser, TILLMnemonic::kFippsTAC, SetFipps(), SetFippsBgo(), SetFippsLaBr(), SetFippsLaBrBgo(), SetFippsPulser(), SetFippsTAC(), and TILLMnemonic::System().
Referenced by TILLDetectorInformation().
SetFipps()
void TILLDetectorInformation::SetFipps (bool flag = true) inline
Definition at line 34 of file TILLDetectorInformation.h.
References fFipps.
Referenced by Set().
SetFippsBgo()
void TILLDetectorInformation::SetFippsBgo (bool flag = true) inline
Definition at line 35 of file TILLDetectorInformation.h.
References fFippsBgo.
Referenced by Set().
SetFippsLaBr()
void TILLDetectorInformation::SetFippsLaBr (bool flag = true) inline
Definition at line 36 of file TILLDetectorInformation.h.
References fFippsLaBr.
Referenced by Set().
SetFippsLaBrBgo()
void TILLDetectorInformation::SetFippsLaBrBgo (bool flag = true) inline
Definition at line 37 of file TILLDetectorInformation.h.
References fFippsLaBrBgo.
Referenced by Set().
SetFippsPulser()
void TILLDetectorInformation::SetFippsPulser (bool flag = true) inline
Definition at line 39 of file TILLDetectorInformation.h.
References fFippsPulser.
Referenced by Set().
SetFippsTAC()
void TILLDetectorInformation::SetFippsTAC (bool flag = true) inline
Definition at line 38 of file TILLDetectorInformation.h.
References fFippsTAC.
Referenced by Set().
Member Data Documentation
fFipps
bool TILLDetectorInformation::fFipps {false} private
Definition at line 52 of file TILLDetectorInformation.h.
Referenced by Clear(), Fipps(), and SetFipps().
fFippsBgo
bool TILLDetectorInformation::fFippsBgo {false} private
Definition at line 53 of file TILLDetectorInformation.h.
Referenced by FippsBgo(), and SetFippsBgo().
fFippsLaBr
bool TILLDetectorInformation::fFippsLaBr {false} private
Definition at line 54 of file TILLDetectorInformation.h.
Referenced by FippsLaBr(), and SetFippsLaBr().
fFippsLaBrBgo
bool TILLDetectorInformation::fFippsLaBrBgo {false} private
Definition at line 55 of file TILLDetectorInformation.h.
Referenced by FippsLaBrBgo(), and SetFippsLaBrBgo().
fFippsPulser
bool TILLDetectorInformation::fFippsPulser {false} private
Definition at line 57 of file TILLDetectorInformation.h.
Referenced by FippsPulser(), and SetFippsPulser().
fFippsTAC
bool TILLDetectorInformation::fFippsTAC {false} private
Definition at line 56 of file TILLDetectorInformation.h.
Referenced by FippsTAC(), and SetFippsTAC().