GRSISort: TTdrSiLi Class Reference
TTdrSiLi Class Reference
Detectors
Detailed Description
Definition at line 18 of file TTdrSiLi.h.
Public Member Functions
TTdrSiLi ()
TTdrSiLi (const TTdrSiLi &)
~TTdrSiLi () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
virtual void BuildHits ()
void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TTdrSiLiHit * GetTdrSiLiHit (const int &i) const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TTdrSiLi & operator= (const TTdrSiLi &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (int DetNbr)
static bool SetCoreWave ()
Private Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static bool fSetCoreWave = false
Constructor & Destructor Documentation
TTdrSiLi() [1/2]
TTdrSiLi::TTdrSiLi ()
Definition at line 17 of file TTdrSiLi.cxx.
References Clear().
TTdrSiLi() [2/2]
TTdrSiLi::TTdrSiLi (const TTdrSiLi & rhs)
Definition at line 25 of file TTdrSiLi.cxx.
References Copy().
~TTdrSiLi()
TTdrSiLi::~TTdrSiLi () override
Definition at line 40 of file TTdrSiLi.cxx.
Member Function Documentation
AddFragment()
void TTdrSiLi::AddFragment (const std::shared_ptr< const TFragment > & , TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 70 of file TTdrSiLi.cxx.
References TDetector::Hits().
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
virtual void TDetector::BuildHits () inline virtual inherited
!
Reimplemented in TAries, TBgo, TCSM, TDemand, TDescant, TEagle, TEaglePulser, TEmma, TFipps, TFippsLaBr, TFippsPulser, TFippsTAC, TGenericDetector, TGriffin, TIfin, TLaBr, TPaces, TRcmp, TRF, TS3, TSceptar, TSharc2, TSharc, TSiLi, TTAC, TTigress, TTip, TTrific, TTriFoil, and TZeroDegree.
Definition at line 55 of file TDetector.h.
Clear()
void TTdrSiLi::Clear (Option_t * opt = "all") override
!
Definition at line 45 of file TTdrSiLi.cxx.
References TDetector::Clear().
Referenced by TTdrSiLi().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TTdrSiLi::Copy (TObject & rhs) const override
!
Definition at line 33 of file TTdrSiLi.cxx.
References TDetector::Copy(), and fSetCoreWave.
Referenced by TTdrSiLi(), and operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TFippsLaBr::GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
TVector3 TTdrSiLi::GetPosition (int DetNbr) static
!
Definition at line 76 of file TTdrSiLi.cxx.
Referenced by TTdrSiLiHit::GetPosition().
GetTdrSiLiHit()
TTdrSiLiHit * TTdrSiLi::GetTdrSiLiHit (const int & i) const inline
Definition at line 26 of file TTdrSiLi.h.
References TDetector::GetHit().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), AddFragment(), TTdrTigress::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TGriffin::GetGriffinHit(), TIfin::GetIfinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TGriffin::Print(), TTdrPlastic::Print(), Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=()
TTdrSiLi & TTdrSiLi::operator= (const TTdrSiLi & rhs)
!
Definition at line 64 of file TTdrSiLi.cxx.
References Copy().
Print() [1/2]
void TTdrSiLi::Print (Option_t * opt = "") const override
!
Definition at line 51 of file TTdrSiLi.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TTdrSiLi::Print (std::ostream & out) const override virtual
Reimplemented from TDetector.
Definition at line 57 of file TTdrSiLi.cxx.
References TDetector::Hits().
SetCoreWave()
static bool TTdrSiLi::SetCoreWave () inline static
!
Definition at line 39 of file TTdrSiLi.h.
References fSetCoreWave.
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), and TDetector::Print().
fSetCoreWave
bool TTdrSiLi::fSetCoreWave = false static private
! Flag for Waveforms ON/OFF
Definition at line 36 of file TTdrSiLi.h.
Referenced by Copy(), and SetCoreWave().