GRSISort: TZeroDegree Class Reference
TZeroDegree Class Reference
Detectors
Detailed Description
The TZeroDegree class defines the observables and algorithms used when analyzing GRIFFIN data. It includes detector positions, etc.
Definition at line 27 of file TZeroDegree.h.
#include <TZeroDegree.h>
Public Member Functions
TZeroDegree ()
TZeroDegree (const TZeroDegree &rhs)
~TZeroDegree () override
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
virtual void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TZeroDegreeHit * GetZeroDegreeHit (const int &i) const
TZeroDegree & operator= (const TZeroDegree &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (double dist)
static bool SetWave ()
Protected Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static bool fSetWave = false
Constructor & Destructor Documentation
TZeroDegree() [1/2]
TZeroDegree::TZeroDegree ()
Definition at line 15 of file TZeroDegree.cxx.
References TDetector::Clear().
~TZeroDegree()
TZeroDegree::~TZeroDegree () override
Definition at line 24 of file TZeroDegree.cxx.
TZeroDegree() [2/2]
TZeroDegree::TZeroDegree (const TZeroDegree & rhs)
Definition at line 29 of file TZeroDegree.cxx.
References TDetector::Copy().
Member Function Documentation
AddFragment()
void TZeroDegree::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Builds the ZDS Hits directly from the TFragment. Basically, loops through the data for an event and sets observables.
Reimplemented from TDetector.
Definition at line 57 of file TZeroDegree.cxx.
References TDetector::fHits.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 56 of file TDetector.h.
References TDetector::fHits.
BuildHits()
void TZeroDegree::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 41 of file TZeroDegree.h.
Clear()
void TDetector::Clear (Option_t * = "") inline override inherited
!
Definition at line 58 of file TDetector.h.
References TDetector::fHits.
Referenced by TPaces::TPaces(), TSceptar::TSceptar(), TZeroDegree(), TSharc::Clear(), TTrific::Clear(), TDescant::Clear(), TSiLi::Clear(), TTigress::Clear(), TTriFoil::Clear(), TTdrPlastic::Clear(), TEmma::Clear(), TS3::Clear(), TEagle::Clear(), TBgo::Clear(), and TTdrSiLi::Clear().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 64 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TDetector::Copy (TObject & rhs) const override virtual inherited
!
Reimplemented in TDescant, TEmma, TGriffin, TPaces, TRF, TS3, TSharc, TSiLi, TTigress, TTrific, TEagle, TFipps, TIfin, TBgo, TSuppressed, TTdrClover, TTdrSiLi, TTdrTigress, TLaBr, TTriFoil, and TFippsLaBr.
Definition at line 34 of file TDetector.cxx.
References TDetectorHit::Copy(), and TDetector::fHits.
Referenced by TDetector::TDetector(), TEaglePulser::TEaglePulser(), TFippsPulser::TFippsPulser(), TFippsTAC::TFippsTAC(), TGenericDetector::TGenericDetector(), TSceptar::TSceptar(), TTAC::TTAC(), TTdrPlastic::TTdrPlastic(), TTip::TTip(), TZeroDegree(), ClassImp(), TDescant::Copy(), TEmma::Copy(), TPaces::Copy(), TRF::Copy(), TS3::Copy(), TSharc::Copy(), TSiLi::Copy(), TTigress::Copy(), TTrific::Copy(), TEagle::Copy(), TBgo::Copy(), TTdrSiLi::Copy(), TTriFoil::Copy(), TDetector::operator=(), TEaglePulser::operator=(), TFippsPulser::operator=(), TFippsTAC::operator=(), TGenericDetector::operator=(), TSceptar::operator=(), TTAC::operator=(), TTdrPlastic::operator=(), TTip::operator=(), and operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & i) const virtual inherited
Reimplemented in TGriffin.
Definition at line 71 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), GetZeroDegreeHit(), and MakeAnalysisHistograms().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 65 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin, and TTrific.
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), main(), MakeAnalysisHistograms(), TTigress::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetPosition()
static TVector3 TZeroDegree::GetPosition (double dist) inline static
!
Definition at line 36 of file TZeroDegree.h.
GetZeroDegreeHit()
TZeroDegreeHit * TZeroDegree::GetZeroDegreeHit (const int & i) const inline
Definition at line 34 of file TZeroDegree.h.
References TDetector::GetHit().
Referenced by ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), and ExampleTreeSelector::FillHistograms().
operator=()
TZeroDegree & TZeroDegree::operator= (const TZeroDegree & rhs)
!
Definition at line 38 of file TZeroDegree.cxx.
References TDetector::Copy().
Print() [1/2]
void TZeroDegree::Print (Option_t * opt = "") const override
!
Prints out TZeroDegree multiplicity, currently does little.
Definition at line 44 of file TZeroDegree.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TZeroDegree::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 50 of file TZeroDegree.cxx.
References TDetector::fHits.
SetWave()
static bool TZeroDegree::SetWave () inline static
!
Definition at line 49 of file TZeroDegree.h.
References fSetWave.
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 73 of file TDetector.h.
Referenced by TDetector::~TDetector(), TSiLi::AddCluster(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), AddFragment(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TDetector::AddHit(), TCSM::BuildHits(), TEmma::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TSharc::Clear(), TTrific::Clear(), TDetector::Clear(), TEmma::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TTrific::GetMultiplicity(), TSharc::GetSize(), TLaBr::GetSuppressedMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), Print(), TEagle::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), TTdrSiLi::Print(), and TSiLi::UseFitCharge().
fSetWave
bool TZeroDegree::fSetWave = false static private
Flag for Waveforms ON/OFF.
Definition at line 46 of file TZeroDegree.h.
Referenced by SetWave().