GRSISort: TEfficiencyGraph Class Reference
TEfficiencyGraph Class Reference
Calibration
Detailed Description
This is a class that contains the basic info about a calibration. Calibrations here are TGraphErrors that are fit, with the resulting fit function being the calibrating function.
Definition at line 30 of file TEfficiencyGraph.h.
Public Member Functions
TEfficiencyGraph ()
TEfficiencyGraph (const char *name, const char *title)
TEfficiencyGraph (const TEfficiencyGraph &)=default
TEfficiencyGraph (TEfficiencyGraph &&) noexcept=default
~TEfficiencyGraph ()
Int_t AddLists (const TCalList &cal_list, const TSourceList &src_list)
void AddPoint (const TCalPoint &cal_point)
void Clear (Option_t *opt="") override
void ClearAllPoints (Option_t *opt="")
void Draw (Option_t *opt="") override
Int_t FindClosestPointX (const Double_t &x_val)
Double_t FindDistToClosestPointX (const Double_t &x_val)
bool IsAbsolute () const
TEfficiencyGraph & operator= (const TEfficiencyGraph &)=default
TEfficiencyGraph & operator= (TEfficiencyGraph &&) noexcept=default
void Print (Option_t *opt="") const override
void SetAbsolute (const bool &flag)
Protected Member Functions
void BuildGraph () override
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > & CompareMap ()
Private Member Functions
void CorrectMissingPoints (TCalList &cal_list, TCalList &src_list)
Private Attributes
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > fCompareMap
bool fIsAbsolute {false}
Constructor & Destructor Documentation
TEfficiencyGraph() [1/4]
TEfficiencyGraph::TEfficiencyGraph ()
Definition at line 6 of file TEfficiencyGraph.cxx.
References Clear().
TEfficiencyGraph() [2/4]
TEfficiencyGraph::TEfficiencyGraph (const char * name, const char * title) inline
Definition at line 33 of file TEfficiencyGraph.h.
TEfficiencyGraph() [3/4]
TEfficiencyGraph::TEfficiencyGraph (const TEfficiencyGraph &) default
TEfficiencyGraph() [4/4]
TEfficiencyGraph::TEfficiencyGraph (TEfficiencyGraph &&) default noexcept
~TEfficiencyGraph()
TEfficiencyGraph::~TEfficiencyGraph () default
Member Function Documentation
AddLists()
Int_t TCalGraph::AddLists (const TCalList & cal_list, const TSourceList & src_list) inherited
Definition at line 63 of file TCalGraph.cxx.
References TCalList::AddPoint(), TCalGraph::CorrectMissingPoints(), DGREEN, DRED, TCalGraph::fCompareMap, TCalList::Map(), and RESET_COLOR.
AddPoint()
void TCalGraph::AddPoint (const TCalPoint & cal_point) inherited
Definition at line 36 of file TCalGraph.cxx.
References TCalPoint::Area(), TCalPoint::AreaErr(), TCalPoint::Centroid(), and TCalPoint::CentroidErr().
BuildGraph()
void TEfficiencyGraph::BuildGraph () override protected virtual
Implements TCalGraph.
Definition at line 23 of file TEfficiencyGraph.cxx.
References TCalGraph::ClearAllPoints(), and TCalGraph::CompareMap().
Clear()
void TEfficiencyGraph::Clear (Option_t * opt = "") override
Definition at line 18 of file TEfficiencyGraph.cxx.
References TCalGraph::Clear().
Referenced by TEfficiencyGraph().
ClearAllPoints()
void TCalGraph::ClearAllPoints (Option_t * opt = "") inherited
Definition at line 129 of file TCalGraph.cxx.
Referenced by BuildGraph().
CompareMap()
std::map< UInt_t, std::pair< TCalPoint, TCalPoint > > & TCalGraph::CompareMap () inline protected inherited
Definition at line 57 of file TCalGraph.h.
References TCalGraph::fCompareMap.
Referenced by BuildGraph().
CorrectMissingPoints()
void TCalGraph::CorrectMissingPoints (TCalList & cal_list, TCalList & src_list) private inherited
Definition at line 113 of file TCalGraph.cxx.
References TCalGraph::fCompareMap, and TCalList::Map().
Referenced by TCalGraph::AddLists().
Draw()
void TCalGraph::Draw (Option_t * opt = "") inline override inherited
Definition at line 46 of file TCalGraph.h.
References TCalGraph::BuildGraph().
FindClosestPointX()
Int_t TCalGraph::FindClosestPointX (const Double_t & x_val) inherited
Definition at line 43 of file TCalGraph.cxx.
Referenced by TCalGraph::FindDistToClosestPointX().
FindDistToClosestPointX()
Double_t TCalGraph::FindDistToClosestPointX (const Double_t & x_val) inherited
Definition at line 57 of file TCalGraph.cxx.
References TCalGraph::FindClosestPointX().
IsAbsolute()
bool TEfficiencyGraph::IsAbsolute () const inline
Definition at line 47 of file TEfficiencyGraph.h.
References fIsAbsolute.
Referenced by TEfficiencyCalibration::AddEfficiencyGraph().
operator=() [1/2]
TEfficiencyGraph & TEfficiencyGraph::operator= (const TEfficiencyGraph &) default
operator=() [2/2]
TEfficiencyGraph & TEfficiencyGraph::operator= (TEfficiencyGraph &&) default noexcept
Print()
void TEfficiencyGraph::Print (Option_t * opt = "") const override
Definition at line 13 of file TEfficiencyGraph.cxx.
References TCalGraph::Print().
SetAbsolute()
void TEfficiencyGraph::SetAbsolute (const bool & flag) inline
Definition at line 46 of file TEfficiencyGraph.h.
References fIsAbsolute.
Member Data Documentation
fCompareMap
std::map<UInt_t, std::pair<TCalPoint, TCalPoint> > TCalGraph::fCompareMap private inherited
Definition at line 64 of file TCalGraph.h.
Referenced by TCalGraph::AddLists(), TCalGraph::Clear(), TCalGraph::CompareMap(), TCalGraph::CorrectMissingPoints(), and TCalGraph::Print().
fIsAbsolute
bool TEfficiencyGraph::fIsAbsolute {false} private
Definition at line 53 of file TEfficiencyGraph.h.
Referenced by IsAbsolute(), and SetAbsolute().