GRSISort: TCalPoint Class Reference
TCalPoint Class Reference
Calibration
Detailed Description
Definition at line 11 of file TCalPoint.h.
Public Member Functions
TCalPoint ()
TCalPoint (const Double_t &centroid, const Double_t &area, const Double_t &dcentroid=0.0, const Double_t &darea=0.0)
TCalPoint (const TCalPoint &)
TCalPoint (const TPeak &peak)
TCalPoint (TCalPoint &&) noexcept=default
~TCalPoint ()=default
Double_t Area () const
Double_t AreaErr () const
Double_t Centroid () const
Double_t CentroidErr () const
void Clear (Option_t *opt="") override
void Copy (TObject &obj) const override
TCalPoint & operator= (const TCalPoint &)=default
TCalPoint & operator= (TCalPoint &&) noexcept=default
void Print (Option_t *opt="") const override
void SetArea (const Double_t &area, const Double_t &darea=0.0)
void SetCentroid (const Double_t &centroid, const Double_t &dcentroid=0.0)
void SetPoint (const Double_t &centroid, const Double_t &area, const Double_t &dcentroid=0.0, const Double_t &darea=0.0)
void SetPoint (const TPeak *peak)
Private Attributes
Double_t fArea {0.}
Double_t fAreaErr {0.}
Double_t fCentroid {0.}
Double_t fCentroidErr {0.}
Constructor & Destructor Documentation
TCalPoint() [1/5]
TCalPoint::TCalPoint ()
Definition at line 5 of file TCalPoint.cxx.
References Clear().
TCalPoint() [2/5]
TCalPoint::TCalPoint (const Double_t & centroid, const Double_t & area, const Double_t & dcentroid = 0.0, const Double_t & darea = 0.0)
Definition at line 10 of file TCalPoint.cxx.
References SetPoint().
TCalPoint() [3/5]
TCalPoint::TCalPoint (const TPeak & peak) explicit
Definition at line 15 of file TCalPoint.cxx.
References SetPoint().
TCalPoint() [4/5]
TCalPoint::TCalPoint (const TCalPoint & copy)
Definition at line 20 of file TCalPoint.cxx.
References Copy().
TCalPoint() [5/5]
TCalPoint::TCalPoint (TCalPoint &&) default noexcept
~TCalPoint()
TCalPoint::~TCalPoint () default
Member Function Documentation
Area()
Double_t TCalPoint::Area () const inline
Definition at line 33 of file TCalPoint.h.
References fArea.
Referenced by TCalGraph::AddPoint().
AreaErr()
Double_t TCalPoint::AreaErr () const inline
Definition at line 35 of file TCalPoint.h.
References fAreaErr.
Referenced by TCalGraph::AddPoint().
Centroid()
Double_t TCalPoint::Centroid () const inline
Definition at line 32 of file TCalPoint.h.
References fCentroid.
Referenced by TCalGraph::AddPoint(), and TCalList::AddPoint().
CentroidErr()
Double_t TCalPoint::CentroidErr () const inline
Definition at line 34 of file TCalPoint.h.
References fCentroidErr.
Referenced by TCalGraph::AddPoint().
Clear()
void TCalPoint::Clear (Option_t * opt = "") override
Definition at line 64 of file TCalPoint.cxx.
References fArea, fAreaErr, fCentroid, and fCentroidErr.
Referenced by TCalPoint().
Copy()
void TCalPoint::Copy (TObject & obj) const override
Definition at line 25 of file TCalPoint.cxx.
References fArea, fAreaErr, fCentroid, and fCentroidErr.
Referenced by TCalPoint().
operator=() [1/2]
TCalPoint & TCalPoint::operator= (const TCalPoint &) default
operator=() [2/2]
TCalPoint & TCalPoint::operator= (TCalPoint &&) default noexcept
Print()
void TCalPoint::Print (Option_t * opt = "") const override
Definition at line 58 of file TCalPoint.cxx.
References fArea, fAreaErr, fCentroid, and fCentroidErr.
SetArea()
void TCalPoint::SetArea (const Double_t & area, const Double_t & darea = 0.0)
Definition at line 52 of file TCalPoint.cxx.
References fArea, and fAreaErr.
Referenced by SetPoint(), and SetPoint().
SetCentroid()
void TCalPoint::SetCentroid (const Double_t & centroid, const Double_t & dcentroid = 0.0)
Definition at line 46 of file TCalPoint.cxx.
References fCentroid, and fCentroidErr.
Referenced by SetPoint(), and SetPoint().
SetPoint() [1/2]
void TCalPoint::SetPoint (const Double_t & centroid, const Double_t & area, const Double_t & dcentroid = 0.0, const Double_t & darea = 0.0)
Definition at line 34 of file TCalPoint.cxx.
References SetArea(), and SetCentroid().
Referenced by TCalPoint(), and TCalPoint().
SetPoint() [2/2]
void TCalPoint::SetPoint (const TPeak * peak)
Definition at line 40 of file TCalPoint.cxx.
References TPeak::GetArea(), TPeak::GetAreaErr(), TPeak::GetCentroid(), TPeak::GetCentroidErr(), SetArea(), and SetCentroid().
Member Data Documentation
fArea
Double_t TCalPoint::fArea {0.} private
Definition at line 40 of file TCalPoint.h.
Referenced by Area(), Clear(), Copy(), Print(), and SetArea().
fAreaErr
Double_t TCalPoint::fAreaErr {0.} private
Definition at line 41 of file TCalPoint.h.
Referenced by AreaErr(), Clear(), Copy(), Print(), and SetArea().
fCentroid
Double_t TCalPoint::fCentroid {0.} private
Definition at line 38 of file TCalPoint.h.
Referenced by Centroid(), Clear(), Copy(), Print(), and SetCentroid().
fCentroidErr
Double_t TCalPoint::fCentroidErr {0.} private
Definition at line 39 of file TCalPoint.h.
Referenced by CentroidErr(), Clear(), Copy(), Print(), and SetCentroid().