GRSISort: TFippsLaBr Class Reference
TFippsLaBr Class Reference
Detectors
Detailed Description
The TFippsLaBr class defines the observables and algorithms used when analyzing LaBr data. It includes detector positions, etc.
Definition at line 28 of file TFippsLaBr.h.
Public Types
enum class ELaBrBits {
kIsSuppressed = 1<<0 , kBit1 = 1<<1 , kBit2 = 1<<2 , kBit3 = 1<<3 ,
kBit4 = 1<<4 , kBit5 = 1<<5 , kBit6 = 1<<6 , kBit7 = 1<<7
}
Public Member Functions
TFippsLaBr ()
TFippsLaBr (const TFippsLaBr &rhs)
~TFippsLaBr () override
virtual bool AddbackCriterion (const TDetectorHit *, const TDetectorHit *)
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *opt="") override
virtual void ClearTransients ()
void Copy (TObject &rhs) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
TFippsLaBrHit * GetLaBrHit (const int &i) const
virtual Short_t GetMultiplicity () const
TFippsLaBrHit * GetSuppressedHit (const int &i)
Short_t GetSuppressedMultiplicity (const TBgo *fBgo)
std::function< bool(const TDetectorHit *, const TDetectorHit *)> GetSuppressionCriterion () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
bool IsSuppressed () const
virtual bool NoHits () const
TFippsLaBr & operator= (const TFippsLaBr &)
void Print (Option_t *opt="") const override
void Print (std::ostream &out) const override
void ResetSuppressed ()
void SetSuppressed (const bool flag)
void SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion)
bool SuppressionCriterion (const TDetectorHit *hit, const TDetectorHit *bgoHit) override
Static Public Member Functions
static TVector3 GetPosition (int DetNbr)
Protected Member Functions
template<class T >
void CreateAddback (const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
template<class T >
void CreateSuppressed (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &suppressedHits)
template<class T >
void CreateSuppressedAddback (const TBgo *bgo, const std::vector< T * > &hits, std::vector< T * > &addbacks, std::vector< UShort_t > &nofFragments)
Private Member Functions
void ClearStatus () const
void SetBitNumber (const ELaBrBits bit, const bool set) const
Bool_t TestBitNumber (const ELaBrBits bit) const
Private Attributes
std::vector< TDetectorHit * > fHits
TTransientBits< UChar_t > fLaBrBits
std::vector< TDetectorHit * > fSuppressedHits
Static Private Attributes
static std::function< bool(const TDetectorHit *, const TDetectorHit *)> fSuppressionCriterion = DefaultLaBrSuppression
static TVector3 gPosition [9]
Member Enumeration Documentation
ELaBrBits
enum class TFippsLaBr::ELaBrBits strong
Enumerator
kIsSuppressed
kBit1
kBit2
kBit3
kBit4
kBit5
kBit6
kBit7
Definition at line 30 of file TFippsLaBr.h.
Constructor & Destructor Documentation
TFippsLaBr() [1/2]
TFippsLaBr::TFippsLaBr ()
Definition at line 34 of file TFippsLaBr.cxx.
References Clear().
~TFippsLaBr()
TFippsLaBr::~TFippsLaBr () override
Definition at line 43 of file TFippsLaBr.cxx.
References fSuppressedHits.
TFippsLaBr() [2/2]
TFippsLaBr::TFippsLaBr (const TFippsLaBr & rhs)
Definition at line 49 of file TFippsLaBr.cxx.
References Copy().
Member Function Documentation
AddbackCriterion()
virtual bool TSuppressed::AddbackCriterion (const TDetectorHit * , const TDetectorHit *) inline virtual inherited
Reimplemented in TFipps, TGriffin, and TIfin.
Definition at line 30 of file TSuppressed.h.
Referenced by TSuppressed::CreateAddback(), and TSuppressed::CreateSuppressedAddback().
AddFragment()
void TFippsLaBr::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel *) override virtual
!
Reimplemented from TDetector.
Definition at line 149 of file TFippsLaBr.cxx.
References TDetector::fHits.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TBgo::AddFragment(), TDemand::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TTrific::AddFragment(), TZeroDegree::AddFragment(), TEmma::BuildHits(), TSharc2::BuildHits(), and TSharc::BuildHits().
BuildHits()
void TFippsLaBr::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 67 of file TFippsLaBr.h.
Clear()
void TFippsLaBr::Clear (Option_t * opt = "") override
!
Definition at line 58 of file TFippsLaBr.cxx.
References TSuppressed::Clear(), fLaBrBits, and fSuppressedHits.
Referenced by TFippsLaBr().
ClearStatus()
void TFippsLaBr::ClearStatus () const inline private
!
Definition at line 83 of file TFippsLaBr.h.
References fLaBrBits.
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
Copy()
void TFippsLaBr::Copy (TObject & rhs) const override
Definition at line 67 of file TFippsLaBr.cxx.
References TSuppressed::Copy(), fLaBrBits, and fSuppressedHits.
Referenced by TFippsLaBr(), and operator=().
CreateAddback()
template<class T > void TSuppressed::CreateAddback (const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of addback hits and number of fragments per addback hit based on the provided vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 38 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetectorHit::kIsEnergySet, and TDetectorHit::kIsTimeSet.
Referenced by TFipps::GetAddbackMultiplicity(), TGriffin::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), and TTdrTigress::GetAddbackMultiplicity().
CreateSuppressed()
template<class T > void TSuppressed::CreateSuppressed (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & suppressedHits) inline protected inherited
This function always(!) re-creates the vector of suppressed hits based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 69 of file TSuppressed.h.
References TDetector::GetHitVector(), and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedMultiplicity(), GetSuppressedMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TIfin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), and TTdrTigress::GetSuppressedMultiplicity().
CreateSuppressedAddback()
template<class T > void TSuppressed::CreateSuppressedAddback (const TBgo * bgo, const std::vector< T * > & hits, std::vector< T * > & addbacks, std::vector< UShort_t > & nofFragments) inline protected inherited
This funxtion always(!) re-creates the vectors of suppressed addback hits and number of fragments per suppressed addback hit based on the provided TBgo and vector of hits
Because the functions to return hit vectors etc. are almost always returning vectors of TDetectorHits, T is most likely TDetectorHit. This means we can't use T directly to create a new hit, we need to use TClass::New().
Definition at line 94 of file TSuppressed.h.
References TSuppressed::AddbackCriterion(), TDetector::GetHitVector(), TDetectorHit::kIsEnergySet, TDetectorHit::kIsTimeSet, and TSuppressed::SuppressionCriterion().
Referenced by TFipps::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), and TTdrTigress::GetSuppressedAddbackMultiplicity().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDemand::GetDemandHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), GetLaBrHit(), TLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), TSharc2::GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TFippsTAC::GetTACHit(), TTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetLaBrHit()
TFippsLaBrHit * TFippsLaBr::GetLaBrHit (const int & i) const inline
Definition at line 46 of file TFippsLaBr.h.
References TDetector::GetHit().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ComptonHists(), AlphanumericHelper::Exec(), ComptonPolarimetryHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AlphanumericSelector::FillHistograms(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TBgo::Print(), TDemand::Print(), TDescant::Print(), TEmma::Print(), TFipps::Print(), TGriffin::Print(), TIfin::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTdrClover::Print(), TTdrTigress::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), and TZeroDegree::Print().
GetPosition()
static TVector3 TFippsLaBr::GetPosition (int DetNbr) inline static
!
Definition at line 69 of file TFippsLaBr.h.
References gPosition.
Referenced by TFippsLaBrHit::GetPosition().
GetSuppressedHit()
TFippsLaBrHit * TFippsLaBr::GetSuppressedHit (const int & i)
!
Definition at line 138 of file TFippsLaBr.cxx.
References fSuppressedHits.
GetSuppressedMultiplicity()
Short_t TFippsLaBr::GetSuppressedMultiplicity (const TBgo * fBgo)
Automatically builds the suppressed hits using the fSuppressionCriterion and returns the number of suppressed hits
Definition at line 115 of file TFippsLaBr.cxx.
References TSuppressed::CreateSuppressed(), TDetector::fHits, fSuppressedHits, IsSuppressed(), and SetSuppressed().
GetSuppressionCriterion()
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFippsLaBr::GetSuppressionCriterion () const inline
Definition at line 53 of file TFippsLaBr.h.
References fSuppressionCriterion.
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TGriffin::AddFragment(), TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::FixCrossTalk(), TGriffin::GetAddbackMultiplicity(), TGriffin::GetGriffinHit(), TSharc2::GetSize(), TGriffin::GetSuppressedAddbackMultiplicity(), TGriffin::GetSuppressedMultiplicity(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
IsSuppressed()
bool TFippsLaBr::IsSuppressed () const
Definition at line 98 of file TFippsLaBr.cxx.
References kIsSuppressed, and TestBitNumber().
Referenced by GetSuppressedMultiplicity().
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=()
TFippsLaBr & TFippsLaBr::operator= (const TFippsLaBr & rhs)
!
Definition at line 79 of file TFippsLaBr.cxx.
References Copy().
Print() [1/2]
void TFippsLaBr::Print (Option_t * opt = "") const override
!
Definition at line 85 of file TFippsLaBr.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TFippsLaBr::Print (std::ostream & out) const override virtual
Reimplemented from TDetector.
Definition at line 91 of file TFippsLaBr.cxx.
References TDetector::fHits.
ResetSuppressed()
void TFippsLaBr::ResetSuppressed ()
Definition at line 108 of file TFippsLaBr.cxx.
References fSuppressedHits, and SetSuppressed().
SetBitNumber()
void TFippsLaBr::SetBitNumber (const ELaBrBits bit, const bool set) const inline private
Definition at line 84 of file TFippsLaBr.h.
References fLaBrBits, and TTransientBits< T >::SetBit().
Referenced by SetSuppressed().
SetSuppressed()
void TFippsLaBr::SetSuppressed (const bool flag)
Definition at line 103 of file TFippsLaBr.cxx.
References kIsSuppressed, and SetBitNumber().
Referenced by GetSuppressedMultiplicity(), and ResetSuppressed().
SetSuppressionCriterion()
void TFippsLaBr::SetSuppressionCriterion (std::function< bool(const TDetectorHit *, const TDetectorHit *)> criterion) inline
Definition at line 49 of file TFippsLaBr.h.
References fSuppressionCriterion.
SuppressionCriterion()
bool TFippsLaBr::SuppressionCriterion (const TDetectorHit * hit, const TDetectorHit * bgoHit) inline override virtual
Reimplemented from TSuppressed.
Definition at line 55 of file TFippsLaBr.h.
References fSuppressionCriterion.
TestBitNumber()
Bool_t TFippsLaBr::TestBitNumber (const ELaBrBits bit) const inline private
Definition at line 85 of file TFippsLaBr.h.
References fLaBrBits, and TTransientBits< T >::TestBit().
Referenced by IsSuppressed().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fLaBrBits
TTransientBits<UChar_t> TFippsLaBr::fLaBrBits mutable private
Definition at line 81 of file TFippsLaBr.h.
Referenced by Clear(), ClearStatus(), Copy(), SetBitNumber(), and TestBitNumber().
fSuppressedHits
std::vector<TDetectorHit*> TFippsLaBr::fSuppressedHits private
Definition at line 77 of file TFippsLaBr.h.
Referenced by ~TFippsLaBr(), Clear(), Copy(), GetSuppressedHit(), GetSuppressedMultiplicity(), and ResetSuppressed().
fSuppressionCriterion
std::function< bool(const TDetectorHit *, const TDetectorHit *)> TFippsLaBr::fSuppressionCriterion = DefaultLaBrSuppression static private
Definition at line 75 of file TFippsLaBr.h.
Referenced by GetSuppressionCriterion(), SetSuppressionCriterion(), and SuppressionCriterion().
gPosition
TVector3 TFippsLaBr::gPosition static private
Initial value:
= {
   TVector3(0, 0, 1),
   TVector3(14.3025, 4.6472, 22.8096),
   TVector3(0, 15.0386, 22.8096),
   TVector3(-14.3025, 4.6472, 22.8096),
   TVector3(-8.8395, -12.1665, 22.8096),
   TVector3(8.8395, -12.1665, 22.8096),
   TVector3(19.7051, 6.4026, 6.2123),
   TVector3(0, 20.7192, 6.2123),
   TVector3(-19.7051, 6.4026, 6.2123),
}
! Position of each detectir
Definition at line 21 of file TFippsLaBr.h.
Referenced by GetPosition().