GRSISort: ComptonPolarimetryHelper Class Reference
ComptonPolarimetryHelper Class Reference
Detailed Description
Definition at line 9 of file ComptonPolarimetryHelper.hh.
Public Types
using Result_t = std::map<std::string, TList>
Public Member Functions
ComptonPolarimetryHelper (TList *list)
ROOT::RDF::RResultPtr< std::map< std::string, TList > > Book (ROOT::RDataFrame *d) override
void CreateHistograms (unsigned int slot) override
virtual void EndOfSort (std::shared_ptr< std::map< std::string, TList > > &)
void Exec (unsigned int slot, TGriffin &fGriffin, TGriffinBgo &fGriffinBgo)
void Finalize ()
std::string GetActionName () const
std::shared_ptr< std::map< std::string, TList > > GetResultPtr () const
void Initialize ()
void InitTask (TTreeReader *, unsigned int)
std::string & Prefix ()
std::string Prefix () const
void Prefix (const std::string &val)
virtual void Setup ()
Protected Member Functions
TPPG * Ppg ()
TRunInfo * RunInfo ()
TUserSettings * UserSettings ()
Protected Attributes
std::vector< TGRSIMap< std::string, GCube * > > fCube
std::map< std::string, TCutG * > fCuts
std::vector< TGRSIMap< std::string, TH1 * > > fH1
std::vector< TGRSIMap< std::string, TH2 * > > fH2
std::vector< TGRSIMap< std::string, TH3 * > > fH3
std::vector< std::shared_ptr< std::map< std::string, TList > > > fLists
std::vector< TGRSIMap< std::string, TObject * > > fObject
TPPG * fPpg {nullptr}
std::string fPrefix {"TGRSIHelper"}
TRunInfo * fRunInfo {nullptr}
std::vector< TGRSIMap< std::string, GHSym * > > fSym
std::vector< TGRSIMap< std::string, TTree * > > fTree
TUserSettings * fUserSettings {nullptr}
Private Member Functions
int CheckEnergy (double energy, int index=-1) const
void CheckSizes (unsigned int slot, const char *usage)
bool Coincident (TGriffinHit *grif1, TGriffinHit *grif2) const
bool ExcludeCrystal (int arraynumber) const
bool ExcludeDetector (int detector) const
double TimeDiff (TGriffinHit *grif1, TGriffinHit *grif2) const
Private Attributes
int fBins {3000}
std::vector< int > fExcludedCrystals
std::vector< int > fExcludedDetectors
std::array< double, 2 > fGammaGateHigh = {1176., 1335.}
std::array< double, 2 > fGammaGateLow = {1170., 1329.}
std::map< unsigned int, std::deque< TGriffin * > > fGriffinDeque
double fGriffinDistance {145.}
double fMaxEnergy {3000.}
double fMinEnergy {0.}
double fPrompt {200.}
int fThetaBins {180}
bool fUseTimestamps {false}
int fXiBins {180}
Static Private Attributes
static constexpr int fSizeLimit = 1073741822
Member Typedef Documentation
Result_t
using TGRSIHelper::Result_t = std::map<std::string, TList> inherited
This type is a requirement for every helper.
Definition at line 67 of file TGRSIHelper.h.
Constructor & Destructor Documentation
ComptonPolarimetryHelper()
ComptonPolarimetryHelper::ComptonPolarimetryHelper (TList * list) inline explicit
Definition at line 73 of file ComptonPolarimetryHelper.hh.
References fBins, fExcludedCrystals, fExcludedDetectors, fGammaGateHigh, fGammaGateLow, fGriffinDistance, fMaxEnergy, fMinEnergy, fPrompt, fThetaBins, TGRSIHelper::fUserSettings, fUseTimestamps, fXiBins, TUserSettings::GetBool(), TUserSettings::GetDouble(), TUserSettings::GetInt(), TUserSettings::GetIntVector(), TGRSIHelper::Prefix(), and TGRSIHelper::Setup().
Member Function Documentation
Book()
ROOT::RDF::RResultPtr< std::map< std::string, TList > > ComptonPolarimetryHelper::Book (ROOT::RDataFrame *) inline override virtual
This method will call the Book action on the provided dataframe.
Reimplemented from TGRSIHelper.
Definition at line 104 of file ComptonPolarimetryHelper.hh.
CheckEnergy()
int ComptonPolarimetryHelper::CheckEnergy (double energy, int index = -1) const inline private
Definition at line 57 of file ComptonPolarimetryHelper.hh.
References fGammaGateHigh, and fGammaGateLow.
Referenced by Exec().
CheckSizes()
void TGRSIHelper::CheckSizes (unsigned int slot, const char * usage) private inherited
check size of each object in the output list
Definition at line 215 of file TGRSIHelper.cxx.
References DRED, TGRSIHelper::fLists, TGRSIHelper::fSizeLimit, and RESET_COLOR.
Referenced by TGRSIHelper::Finalize(), and TGRSIHelper::Setup().
Coincident()
bool ComptonPolarimetryHelper::Coincident (TGriffinHit * grif1, TGriffinHit * grif2) const inline private
Definition at line 48 of file ComptonPolarimetryHelper.hh.
References fPrompt, fUseTimestamps, TDetectorHit::GetTime(), and TDetectorHit::GetTimeStampNs().
Referenced by Exec().
CreateHistograms()
void ComptonPolarimetryHelper::CreateHistograms (unsigned int) override virtual
Virtual helper function that the user uses to create their histograms.
Reimplemented from TGRSIHelper.
Definition at line 3 of file ComptonPolarimetryHelper.cxx.
References ExcludeCrystal(), ExcludeDetector(), fBins, fGriffinDeque, fGriffinDistance, TGRSIHelper::fH1, TGRSIHelper::fH2, fMaxEnergy, fMinEnergy, fThetaBins, fXiBins, and TGriffin::GetPosition().
EndOfSort()
virtual void TGRSIHelper::EndOfSort (std::shared_ptr< std::map< std::string, TList > > &) inline virtual inherited
This method gets called at the end of Finalize()
Reimplemented in DirectoryHelper, EfficiencyHelper, and ExampleEventHelper.
Definition at line 100 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Finalize().
ExcludeCrystal()
bool ComptonPolarimetryHelper::ExcludeCrystal (int arraynumber) const inline private
Definition at line 34 of file ComptonPolarimetryHelper.hh.
References fExcludedCrystals.
Referenced by CreateHistograms(), and Exec().
ExcludeDetector()
bool ComptonPolarimetryHelper::ExcludeDetector (int detector) const inline private
Definition at line 30 of file ComptonPolarimetryHelper.hh.
References fExcludedDetectors.
Referenced by CreateHistograms(), and Exec().
Exec()
void ComptonPolarimetryHelper::Exec (unsigned int slot, TGriffin & fGriffin, TGriffinBgo & fGriffinBgo)
Definition at line 99 of file ComptonPolarimetryHelper.cxx.
References CheckEnergy(), Coincident(), ExcludeCrystal(), ExcludeDetector(), fGriffinDeque, fGriffinDistance, TGRSIHelper::fH1, TGRSIHelper::fH2, TGriffin::GetGriffinHit(), TDetector::GetMultiplicity(), TGriffin::GetPosition(), and TimeDiff().
Finalize()
void TGRSIHelper::Finalize () inherited
This required method is called at the end of the event loop. It is used to merge all the internal TLists which were used in each of the data processing slots.
This function merges all maps of lists into the map of the first slot (slot 0)
Definition at line 154 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::EndOfSort(), and TGRSIHelper::fLists.
GetActionName()
std::string TGRSIHelper::GetActionName () const inline inherited
Definition at line 104 of file TGRSIHelper.h.
References TGRSIHelper::Prefix().
GetResultPtr()
std::shared_ptr< std::map< std::string, TList > > TGRSIHelper::GetResultPtr () const inline inherited
Definition at line 92 of file TGRSIHelper.h.
References TGRSIHelper::fLists.
Initialize()
void TGRSIHelper::Initialize () inline inherited
Definition at line 94 of file TGRSIHelper.h.
InitTask()
void TGRSIHelper::InitTask (TTreeReader * , unsigned int) inline inherited
Definition at line 93 of file TGRSIHelper.h.
Ppg()
TPPG * TGRSIHelper::Ppg () inline protected inherited
Definition at line 43 of file TGRSIHelper.h.
References TGRSIHelper::fPpg.
Referenced by ExampleEventHelper::CreateHistograms().
Prefix() [1/3]
std::string & TGRSIHelper::Prefix () inline inherited
Definition at line 40 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper::EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper::GriffinKValueHelper(), TimeWalkHelper::TimeWalkHelper(), TGRSIHelper::Book(), TGRSIHelper::CreateHistograms(), and TGRSIHelper::GetActionName().
Prefix() [2/3]
std::string TGRSIHelper::Prefix () const inline inherited
Definition at line 102 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
Prefix() [3/3]
void TGRSIHelper::Prefix (const std::string & val) inline inherited
Definition at line 103 of file TGRSIHelper.h.
References TGRSIHelper::fPrefix.
RunInfo()
TRunInfo * TGRSIHelper::RunInfo () inline protected inherited
Definition at line 44 of file TGRSIHelper.h.
References TGRSIHelper::fRunInfo.
Setup()
void TGRSIHelper::Setup () virtual inherited
This function builds the vectors of TLists and maps for 1D- and 2D-histograms. It calls the overloaded CreateHistograms functions in which the user can define their histograms. Then it adds all those histograms to the list of the corresponding slot.
Definition at line 71 of file TGRSIHelper.cxx.
References TGRSIHelper::CheckSizes(), TGRSIHelper::CreateHistograms(), TGRSIHelper::fCube, TGRSIHelper::fH1, TGRSIHelper::fH2, TGRSIHelper::fH3, TGRSIHelper::fLists, TGRSIHelper::fObject, TGRSIHelper::fSym, TGRSIHelper::fTree, TGRSIOptions::Get(), and TGRSIOptions::GetMaxWorkers().
Referenced by AlphanumericHelper::AlphanumericHelper(), AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper(), CrossTalkHelper::CrossTalkHelper(), DirectoryHelper::DirectoryHelper(), EfficiencyHelper::EfficiencyHelper(), ExampleEventHelper::ExampleEventHelper(), ExampleFragmentHelper::ExampleFragmentHelper(), ExampleTreeHelper::ExampleTreeHelper(), GriffinKValueHelper::GriffinKValueHelper(), and TimeWalkHelper::TimeWalkHelper().
TimeDiff()
double ComptonPolarimetryHelper::TimeDiff (TGriffinHit * grif1, TGriffinHit * grif2) const inline private
Definition at line 39 of file ComptonPolarimetryHelper.hh.
References fUseTimestamps, TDetectorHit::GetTime(), and TDetectorHit::GetTimeStampNs().
Referenced by Exec().
UserSettings()
TUserSettings * TGRSIHelper::UserSettings () inline protected inherited
Definition at line 45 of file TGRSIHelper.h.
References TGRSIHelper::fUserSettings.
Member Data Documentation
fBins
int ComptonPolarimetryHelper::fBins {3000} private
Definition at line 18 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CreateHistograms().
fCube
std::vector<TGRSIMap<std::string, GCube*> > TGRSIHelper::fCube protected inherited
Definition at line 52 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fCuts
std::map<std::string, TCutG*> TGRSIHelper::fCuts protected inherited
Definition at line 55 of file TGRSIHelper.h.
Referenced by TGRSIHelper::TGRSIHelper().
fExcludedCrystals
std::vector<int> ComptonPolarimetryHelper::fExcludedCrystals private
Definition at line 13 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and ExcludeCrystal().
fExcludedDetectors
std::vector<int> ComptonPolarimetryHelper::fExcludedDetectors private
Definition at line 12 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and ExcludeDetector().
fGammaGateHigh
std::array<double, 2> ComptonPolarimetryHelper::fGammaGateHigh = {1176., 1335.} private
Definition at line 26 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CheckEnergy().
fGammaGateLow
std::array<double, 2> ComptonPolarimetryHelper::fGammaGateLow = {1170., 1329.} private
Definition at line 25 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CheckEnergy().
fGriffinDeque
std::map<unsigned int, std::deque<TGriffin*> > ComptonPolarimetryHelper::fGriffinDeque private
Definition at line 28 of file ComptonPolarimetryHelper.hh.
Referenced by CreateHistograms(), and Exec().
fGriffinDistance
double ComptonPolarimetryHelper::fGriffinDistance {145.} private
Definition at line 11 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), CreateHistograms(), and Exec().
fH1
std::vector<TGRSIMap<std::string, TH1*> > TGRSIHelper::fH1 protected inherited
Definition at line 48 of file TGRSIHelper.h.
Referenced by CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), EfficiencyHelper::CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), GriffinKValueHelper::CreateHistograms(), Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), and TGRSIHelper::Setup().
fH2
std::vector<TGRSIMap<std::string, TH2*> > TGRSIHelper::fH2 protected inherited
Definition at line 49 of file TGRSIHelper.h.
Referenced by AlphanumericHelper::CreateHistograms(), AngularCorrelationHelper::CreateHistograms(), CreateHistograms(), CrossTalkHelper::CreateHistograms(), DirectoryHelper::CreateHistograms(), EfficiencyHelper::CreateHistograms(), ExampleEventHelper::CreateHistograms(), ExampleFragmentHelper::CreateHistograms(), ExampleTreeHelper::CreateHistograms(), GriffinKValueHelper::CreateHistograms(), TimeWalkHelper::CreateHistograms(), ExampleEventHelper::EndOfSort(), AlphanumericHelper::Exec(), AngularCorrelationHelper::Exec(), Exec(), CrossTalkHelper::Exec(), DirectoryHelper::Exec(), EfficiencyHelper::Exec(), ExampleEventHelper::Exec(), ExampleFragmentHelper::Exec(), ExampleTreeHelper::Exec(), GriffinKValueHelper::Exec(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fH3
std::vector<TGRSIMap<std::string, TH3*> > TGRSIHelper::fH3 protected inherited
Definition at line 50 of file TGRSIHelper.h.
Referenced by TimeWalkHelper::CreateHistograms(), TimeWalkHelper::Exec(), and TGRSIHelper::Setup().
fLists
std::vector<std::shared_ptr<std::map<std::string, TList> > > TGRSIHelper::fLists protected inherited
Definition at line 47 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes(), TGRSIHelper::Finalize(), TGRSIHelper::GetResultPtr(), and TGRSIHelper::Setup().
fMaxEnergy
double ComptonPolarimetryHelper::fMaxEnergy {3000.} private
Definition at line 20 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CreateHistograms().
fMinEnergy
double ComptonPolarimetryHelper::fMinEnergy {0.} private
Definition at line 19 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CreateHistograms().
fObject
std::vector<TGRSIMap<std::string, TObject*> > TGRSIHelper::fObject protected inherited
Definition at line 54 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::CreateHistograms(), and TGRSIHelper::Setup().
fPpg
TPPG* TGRSIHelper::fPpg {nullptr} protected inherited
Definition at line 56 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Ppg().
fPrefix
std::string TGRSIHelper::fPrefix {"TGRSIHelper"} protected inherited
Definition at line 59 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Prefix(), TGRSIHelper::Prefix(), and TGRSIHelper::Prefix().
fPrompt
double ComptonPolarimetryHelper::fPrompt {200.} private
Definition at line 16 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and Coincident().
fRunInfo
TRunInfo* TGRSIHelper::fRunInfo {nullptr} protected inherited
Definition at line 57 of file TGRSIHelper.h.
Referenced by TGRSIHelper::RunInfo().
fSizeLimit
int TGRSIHelper::fSizeLimit = 1073741822 static constexpr private inherited
! 1 GiB size limit for objects in ROOT
Definition at line 62 of file TGRSIHelper.h.
Referenced by TGRSIHelper::CheckSizes().
fSym
std::vector<TGRSIMap<std::string, GHSym*> > TGRSIHelper::fSym protected inherited
Definition at line 51 of file TGRSIHelper.h.
Referenced by TGRSIHelper::Setup().
fThetaBins
int ComptonPolarimetryHelper::fThetaBins {180} private
Definition at line 22 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CreateHistograms().
fTree
std::vector<TGRSIMap<std::string, TTree*> > TGRSIHelper::fTree protected inherited
Definition at line 53 of file TGRSIHelper.h.
Referenced by ExampleTreeHelper::CreateHistograms(), ExampleTreeHelper::Exec(), and TGRSIHelper::Setup().
fUserSettings
TUserSettings* TGRSIHelper::fUserSettings {nullptr} protected inherited
Definition at line 58 of file TGRSIHelper.h.
Referenced by AngularCorrelationHelper::AngularCorrelationHelper(), ComptonPolarimetryHelper(), and TGRSIHelper::UserSettings().
fUseTimestamps
bool ComptonPolarimetryHelper::fUseTimestamps {false} private
Definition at line 15 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), Coincident(), and TimeDiff().
fXiBins
int ComptonPolarimetryHelper::fXiBins {180} private
Definition at line 21 of file ComptonPolarimetryHelper.hh.
Referenced by ComptonPolarimetryHelper(), and CreateHistograms().