GRSISort: GMarker Class Reference
GMarker Class Reference
GROOT
Detailed Description
Definition at line 24 of file GCanvas.h.
Public Member Functions
GMarker ()=default
GMarker (const GMarker &marker)
GMarker (GMarker &&) noexcept=default
GMarker (int tmpX, int tmpY, TH1 *hist)
~GMarker ()
void Copy (TObject &object) const override
void Draw (Option_t *opt="") override
int GetBinX () const
int GetBinY () const
double GetLocalX () const
double GetLocalY () const
bool operator< (const GMarker &rhs) const
GMarker & operator= (const GMarker &)=default
GMarker & operator= (GMarker &&) noexcept=default
void Print (Option_t *option="") const override
void SetBinX (const int &val)
void SetBinY (const int &val)
void SetColor (Color_t color)
void SetHist (const TH1 *val)
void SetLineX (double x1, double x2, double y1, double y2)
void SetLineY (double x1, double x2, double y1, double y2)
void SetLocalX (const double &val)
void SetLocalY (const double &val)
void SetStyle (Style_t style)
void Update (Double_t xmin, Double_t xmax, Double_t ymin, Double_t ymax)
Private Attributes
const TH1 * fHist {nullptr}
TLine * fLineX {nullptr}
TLine * fLineY {nullptr}
Constructor & Destructor Documentation
GMarker() [1/4]
GMarker::GMarker () default
GMarker() [2/4]
GMarker::GMarker (int tmpX, int tmpY, TH1 * hist)
Definition at line 53 of file GCanvas.cxx.
References fHist.
GMarker() [3/4]
GMarker::GMarker (const GMarker & marker) inline
Definition at line 28 of file GCanvas.h.
References Copy().
GMarker() [4/4]
GMarker::GMarker (GMarker &&) default noexcept
~GMarker()
GMarker::~GMarker () inline
Definition at line 32 of file GCanvas.h.
References fLineX, and fLineY.
Member Function Documentation
Copy()
void GMarker::Copy (TObject & object) const override
Definition at line 75 of file GCanvas.cxx.
References fHist, fLineX, and fLineY.
Referenced by GMarker().
Draw()
void GMarker::Draw (Option_t * opt = "") inline override
Definition at line 37 of file GCanvas.h.
References fLineX, and fLineY.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
GetBinX()
int GMarker::GetBinX () const inline
Definition at line 140 of file GCanvas.h.
References fHist, and fLineX.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
GetBinY()
int GMarker::GetBinY () const inline
Definition at line 145 of file GCanvas.h.
References fHist, and fLineY.
GetLocalX()
double GMarker::GetLocalX () const inline
Definition at line 130 of file GCanvas.h.
References fLineX.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
GetLocalY()
double GMarker::GetLocalY () const inline
Definition at line 135 of file GCanvas.h.
References fLineY.
operator<()
bool GMarker::operator< (const GMarker & rhs) const inline
Definition at line 160 of file GCanvas.h.
References fLineX.
operator=() [1/2]
GMarker & GMarker::operator= (const GMarker &) default
operator=() [2/2]
GMarker & GMarker::operator= (GMarker &&) default noexcept
Print()
void GMarker::Print (Option_t * option = "") const inline override
Definition at line 46 of file GCanvas.h.
References fLineX, and fLineY.
SetBinX()
void GMarker::SetBinX (const int & val) inline
Definition at line 127 of file GCanvas.h.
References fHist, and SetLineX().
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
SetBinY()
void GMarker::SetBinY (const int & val) inline
Definition at line 128 of file GCanvas.h.
References fHist, and SetLineX().
SetColor()
void GMarker::SetColor (Color_t color) inline
Definition at line 58 of file GCanvas.h.
References fLineX, and fLineY.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
SetHist()
void GMarker::SetHist (const TH1 * val) inline
Definition at line 151 of file GCanvas.h.
References fHist.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
SetLineX()
void GMarker::SetLineX (double x1, double x2, double y1, double y2) inline
Definition at line 89 of file GCanvas.h.
References fLineX.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), TBGSubtraction::DrawPeakMarkers(), SetBinX(), and SetBinY().
SetLineY()
void GMarker::SetLineY (double x1, double x2, double y1, double y2) inline
Definition at line 101 of file GCanvas.h.
References fLineY.
SetLocalX()
void GMarker::SetLocalX (const double & val) inline
Definition at line 113 of file GCanvas.h.
References fLineX.
Referenced by TBGSubtraction::DrawBGMarkers(), TBGSubtraction::DrawGateMarkers(), and TBGSubtraction::DrawPeakMarkers().
SetLocalY()
void GMarker::SetLocalY (const double & val) inline
Definition at line 120 of file GCanvas.h.
References fLineY.
SetStyle()
void GMarker::SetStyle (Style_t style) inline
Definition at line 68 of file GCanvas.h.
References fLineX, and fLineY.
Referenced by TBGSubtraction::DrawPeakMarkers().
Update()
void GMarker::Update (Double_t xmin, Double_t xmax, Double_t ymin, Double_t ymax) inline
Definition at line 77 of file GCanvas.h.
References fLineX, and fLineY.
Member Data Documentation
fHist
const TH1* GMarker::fHist {nullptr} private
Definition at line 154 of file GCanvas.h.
Referenced by GMarker(), Copy(), GetBinX(), GetBinY(), SetBinX(), SetBinY(), and SetHist().
fLineX
TLine* GMarker::fLineX {nullptr} private
Definition at line 155 of file GCanvas.h.
Referenced by ~GMarker(), Copy(), Draw(), GetBinX(), GetLocalX(), operator<(), Print(), SetColor(), SetLineX(), SetLocalX(), SetStyle(), and Update().
fLineY
TLine* GMarker::fLineY {nullptr} private
Definition at line 156 of file GCanvas.h.
Referenced by ~GMarker(), Copy(), Draw(), GetBinY(), GetLocalY(), Print(), SetColor(), SetLineY(), SetLocalY(), SetStyle(), and Update().