GRSISort: TAnalysisOptions Class Reference
TAnalysisOptions Class Reference
Sorting
Detailed Description
This class stores those command line arguments passed to GRSISort, that are pertinent to the analysis. This includes such settings as the addback window width, whether to correct cross talk, etc.
Definition at line 23 of file TAnalysisOptions.h.
Public Member Functions
TAnalysisOptions ()=default
double AddbackWindow () const
bool BuildEventsByTimeStamp () const
int64_t BuildWindow () const
void Clear (Option_t *opt="") override
bool IsCorrectingCrossTalk () const
bool IsWaveformFitting () const
Long64_t Merge (TCollection *list)
Long64_t Merge (TCollection *list, Option_t *)
void Print (Option_t *opt="") const override
void ReadFromFile (const std::string &file)
void ReadFromFile (TFile *file=nullptr)
void SetAddbackWindow (const double &t_abw)
void SetBuildEventsByTimeStamp (bool &val)
void SetBuildWindow (const int64_t &t_bw)
void SetCorrectCrossTalk (const bool &flag, Option_t *opt="")
void SetSuppressionEnergy (const double &e_sup)
void SetSuppressionWindow (const double &t_sup)
void SetWaveformFitting (const bool &flag)
bool StaticWindow () const
double SuppressionEnergy () const
double SuppressionWindow () const
bool WriteToFile (const std::string &file)
bool WriteToFile (TFile *file=nullptr)
Private Member Functions
bool Compare (const TAnalysisOptions *options) const
Private Attributes
double fAddbackWindow {300.}
bool fBuildEventsByTimeStamp {false}
int64_t fBuildWindow {2000}
bool fIsCorrectingCrossTalk {false}
bool fStaticWindow {true}
double fSuppressionEnergy {0.}
double fSuppressionWindow {300.}
bool fWaveformFitting {false}
Friends
class TGRSIOptions
Constructor & Destructor Documentation
TAnalysisOptions()
TAnalysisOptions::TAnalysisOptions () default
Member Function Documentation
AddbackWindow()
double TAnalysisOptions::AddbackWindow () const inline
Definition at line 52 of file TAnalysisOptions.h.
References fAddbackWindow.
Referenced by TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), DefaultAddback(), DefaultAddback(), DefaultAddback(), DefaultFippsAddback(), DefaultGriffinAddback(), and DefaultIfinAddback().
BuildEventsByTimeStamp()
bool TAnalysisOptions::BuildEventsByTimeStamp () const inline
Definition at line 51 of file TAnalysisOptions.h.
References fBuildEventsByTimeStamp.
BuildWindow()
int64_t TAnalysisOptions::BuildWindow () const inline
Definition at line 50 of file TAnalysisOptions.h.
References fBuildWindow.
Clear()
void TAnalysisOptions::Clear (Option_t * opt = "") override
Clears all of the variables in the TAnalysisOptions
Definition at line 15 of file TAnalysisOptions.cxx.
References fAddbackWindow, fBuildEventsByTimeStamp, fBuildWindow, fIsCorrectingCrossTalk, fStaticWindow, fSuppressionEnergy, fSuppressionWindow, and fWaveformFitting.
Referenced by TGRSIOptions::Clear().
Compare()
bool TAnalysisOptions::Compare (const TAnalysisOptions * options) const private
Definition at line 139 of file TAnalysisOptions.cxx.
References fAddbackWindow, fBuildEventsByTimeStamp, fBuildWindow, fIsCorrectingCrossTalk, fStaticWindow, fSuppressionEnergy, fSuppressionWindow, and fWaveformFitting.
Referenced by Merge().
IsCorrectingCrossTalk()
bool TAnalysisOptions::IsCorrectingCrossTalk () const inline
Definition at line 48 of file TAnalysisOptions.h.
References fIsCorrectingCrossTalk.
IsWaveformFitting()
bool TAnalysisOptions::IsWaveformFitting () const inline
Definition at line 45 of file TAnalysisOptions.h.
References fWaveformFitting.
Referenced by TTigress::BuildHits().
Merge() [1/2]
Long64_t TAnalysisOptions::Merge (TCollection * list) inline
Definition at line 65 of file TAnalysisOptions.h.
References Merge().
Referenced by Merge().
Merge() [2/2]
Long64_t TAnalysisOptions::Merge (TCollection * list, Option_t *)
Definition at line 178 of file TAnalysisOptions.cxx.
References Compare().
Print()
void TAnalysisOptions::Print (Option_t * opt = "") const override
Print the current status of TAnalysisOptions, includes all names, lists and flags
Definition at line 28 of file TAnalysisOptions.cxx.
References BLUE, DCYAN, fAddbackWindow, fBuildEventsByTimeStamp, fBuildWindow, fIsCorrectingCrossTalk, fStaticWindow, fSuppressionEnergy, fSuppressionWindow, fWaveformFitting, and RESET_COLOR.
Referenced by TGRSIOptions::Print(), and TGRSIint::SetupPipeline().
ReadFromFile() [1/2]
void TAnalysisOptions::ReadFromFile (const std::string & file)
Definition at line 96 of file TAnalysisOptions.cxx.
References ReadFromFile().
Referenced by TGRSIOptions::Load(), TGRSISelector::Process(), and ReadFromFile().
ReadFromFile() [2/2]
void TAnalysisOptions::ReadFromFile (TFile * file = nullptr)
Definition at line 105 of file TAnalysisOptions.cxx.
References CYAN, and RESET_COLOR.
SetAddbackWindow()
void TAnalysisOptions::SetAddbackWindow (const double & t_abw) inline
Definition at line 40 of file TAnalysisOptions.h.
References fAddbackWindow.
SetBuildEventsByTimeStamp()
void TAnalysisOptions::SetBuildEventsByTimeStamp (bool & val) inline
Definition at line 39 of file TAnalysisOptions.h.
References fBuildEventsByTimeStamp.
SetBuildWindow()
void TAnalysisOptions::SetBuildWindow (const int64_t & t_bw) inline
Definition at line 38 of file TAnalysisOptions.h.
References fBuildWindow.
SetCorrectCrossTalk()
void TAnalysisOptions::SetCorrectCrossTalk (const bool & flag, Option_t * opt = "")
Definition at line 127 of file TAnalysisOptions.cxx.
References fIsCorrectingCrossTalk.
SetSuppressionEnergy()
void TAnalysisOptions::SetSuppressionEnergy (const double & e_sup) inline
Definition at line 42 of file TAnalysisOptions.h.
References fSuppressionEnergy.
SetSuppressionWindow()
void TAnalysisOptions::SetSuppressionWindow (const double & t_sup) inline
Definition at line 41 of file TAnalysisOptions.h.
References fSuppressionWindow.
SetWaveformFitting()
void TAnalysisOptions::SetWaveformFitting (const bool & flag) inline
Definition at line 44 of file TAnalysisOptions.h.
References fWaveformFitting.
StaticWindow()
bool TAnalysisOptions::StaticWindow () const inline
Definition at line 63 of file TAnalysisOptions.h.
References fStaticWindow.
SuppressionEnergy()
double TAnalysisOptions::SuppressionEnergy () const inline
Definition at line 61 of file TAnalysisOptions.h.
References fSuppressionEnergy.
Referenced by DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), and DefaultSuppression().
SuppressionWindow()
double TAnalysisOptions::SuppressionWindow () const inline
Definition at line 60 of file TAnalysisOptions.h.
References fSuppressionWindow.
Referenced by DefaultFippsSuppression(), DefaultGriffinSuppression(), DefaultIfinSuppression(), DefaultLaBrSuppression(), DefaultSuppression(), and DefaultSuppression().
WriteToFile() [1/2]
bool TAnalysisOptions::WriteToFile (const std::string & file)
Definition at line 42 of file TAnalysisOptions.cxx.
References WriteToFile().
Referenced by TGRSIFrame::Run(), TGRSISelector::Terminate(), TAnalysisWriteLoop::Write(), WriteToFile(), and TGRSIOptions::WriteToFile().
WriteToFile() [2/2]
bool TAnalysisOptions::WriteToFile (TFile * file = nullptr)
Writes options information to the root file
Definition at line 52 of file TAnalysisOptions.cxx.
References Write().
Friends And Related Symbol Documentation
TGRSIOptions
friend class TGRSIOptions friend
Definition at line 24 of file TAnalysisOptions.h.
Member Data Documentation
fAddbackWindow
double TAnalysisOptions::fAddbackWindow {300.} private
Time used to build Addback-Ge-Events for TIGRESS/GRIFFIN. (default = 300 ns (300))
Definition at line 75 of file TAnalysisOptions.h.
Referenced by AddbackWindow(), Clear(), Compare(), TGRSIOptions::Load(), Print(), and SetAddbackWindow().
fBuildEventsByTimeStamp
bool TAnalysisOptions::fBuildEventsByTimeStamp {false} private
use time stamps instead of time (including CFD) to build events
Definition at line 74 of file TAnalysisOptions.h.
Referenced by BuildEventsByTimeStamp(), Clear(), Compare(), TGRSIOptions::Load(), Print(), and SetBuildEventsByTimeStamp().
fBuildWindow
int64_t TAnalysisOptions::fBuildWindow {2000} private
if building with a window(GRIFFIN) this is the size of the window. (default = 2us (2000))
Definition at line 73 of file TAnalysisOptions.h.
Referenced by BuildWindow(), Clear(), Compare(), TGRSIOptions::Load(), Print(), and SetBuildWindow().
fIsCorrectingCrossTalk
bool TAnalysisOptions::fIsCorrectingCrossTalk {false} private
True if we are correcting for cross-talk in GRIFFIN at analysis-level.
Definition at line 78 of file TAnalysisOptions.h.
Referenced by Clear(), Compare(), IsCorrectingCrossTalk(), TGRSIOptions::Load(), Print(), and SetCorrectCrossTalk().
fStaticWindow
bool TAnalysisOptions::fStaticWindow {true} private
Flag to use static window (default moving)
Definition at line 80 of file TAnalysisOptions.h.
Referenced by Clear(), Compare(), TGRSIOptions::Load(), Print(), and StaticWindow().
fSuppressionEnergy
double TAnalysisOptions::fSuppressionEnergy {0.} private
Minimum energy used to suppress Ge-Events. (default = 0 keV)
Definition at line 77 of file TAnalysisOptions.h.
Referenced by Clear(), Compare(), TGRSIOptions::Load(), Print(), SetSuppressionEnergy(), and SuppressionEnergy().
fSuppressionWindow
double TAnalysisOptions::fSuppressionWindow {300.} private
Time used to suppress Ge-Events. (default = 300 ns (300))
Definition at line 76 of file TAnalysisOptions.h.
Referenced by Clear(), Compare(), TGRSIOptions::Load(), Print(), SetSuppressionWindow(), and SuppressionWindow().
fWaveformFitting
bool TAnalysisOptions::fWaveformFitting {false} private
If true, waveform fitting with SFU algorithm will be performed.
Definition at line 79 of file TAnalysisOptions.h.
Referenced by Clear(), Compare(), IsWaveformFitting(), TGRSIOptions::Load(), Print(), and SetWaveformFitting().