GRSISort: TSharc2 Class Reference
TSharc2 Class Reference
Detectors
Detailed Description
Definition at line 20 of file TSharc2.h.
Public Member Functions
TSharc2 ()
TSharc2 (const TSharc2 &rhs)
TSharc2 (TSharc2 &&) noexcept=default
~TSharc2 () override=default
void AddFragment (const std::shared_ptr< const TFragment > &, TChannel *) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
void Clear (Option_t *="") override
virtual void ClearTransients ()
void Copy (TObject &) const override
virtual TDetectorHit * GetHit (const int &index) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TSharc2Hit * GetSharc2Hit (const int &i) const
int GetSize () const
std::vector< TDetectorHit * > & Hits ()
const std::vector< TDetectorHit * > & Hits () const
virtual bool NoHits () const
TSharc2 & operator= (const TSharc2 &rhs)
TSharc2 & operator= (TSharc2 &&) noexcept=default
void Print (Option_t *="") const override
void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetOffset ()
static TVector3 GetPosition (int detector, int frontstrip, int backstrip, double X=0.00, double Y=0.00, double Z=0.00)
static double GetXOffset ()
static double GetYOffset ()
static double GetZOffset ()
static void SetXYZOffset (const double x, const double y, const double z)
Private Member Functions
int CombineHits (TSharc2Hit *, TSharc2Hit *, int, int)
void RemoveHits (std::vector< TSharc2Hit > *, std::set< int > *)
Private Attributes
std::vector< TFragment > fBackFragments
std::vector< TFragment > fFrontFragments
std::vector< TDetectorHit * > fHits
Static Private Attributes
static double fRingPitch
static double fSectorWidthDS2 = 2 * TMath::Pi() / 16.0
static double fSectorWidthUS2 = 2 * TMath::Pi() / 16.0
static double fSegmentPitch
static double fStripBPitch = TSharc2::fZdim / 48.0
static double fStripFPitch = TSharc2::fYdim / 24.0
static double fStripPitchDS2 = 0.5
static double fStripPitchUS2 = 0.5
static double fXdim = +72.0
static double fXminDS2 = 11.0
static double fXminUS2 = 11.0
static double fXoffset = +0.00
static double fXposUB = +42.5
static double fYdim = +72.0
static double fYminUB = -36.0
static double fYoffset = +0.00
static double fZdim = +48.0
static double fZminUB = -5.00
static double fZoffset = +0.00
static double fZposDS2 = 58.5
static double fZposUS2 = 72.0
Constructor & Destructor Documentation
TSharc2() [1/3]
TSharc2::TSharc2 ()
Definition at line 59 of file TSharc2.cxx.
References Clear().
TSharc2() [2/3]
TSharc2::TSharc2 (const TSharc2 & rhs)
Definition at line 64 of file TSharc2.cxx.
References Clear(), and Copy().
TSharc2() [3/3]
TSharc2::TSharc2 (TSharc2 &&) default noexcept
~TSharc2()
TSharc2::~TSharc2 () override default
Member Function Documentation
AddFragment()
void TSharc2::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 71 of file TSharc2.cxx.
References TMnemonic::ArraySubPosition(), TMnemonic::CollectedCharge(), fBackFragments, fFrontFragments, TChannel::GetMnemonic(), TMnemonic::kD, and TMnemonic::kP.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by TAries::AddFragment(), TDescant::AddFragment(), TGenericDetector::AddFragment(), TLaBr::AddFragment(), TPaces::AddFragment(), TSceptar::AddFragment(), TSiLi::AddFragment(), TTAC::AddFragment(), TTigress::AddFragment(), TTip::AddFragment(), TZeroDegree::AddFragment(), TTrific::AddFragment(), TBgo::AddFragment(), TEmma::BuildHits(), TSharc::BuildHits(), and BuildHits().
BuildHits()
void TSharc2::BuildHits () override virtual
!
Reimplemented from TDetector.
Definition at line 89 of file TSharc2.cxx.
References TDetector::AddHit(), fBackFragments, fFrontFragments, and TSharc2Hit::SetFront().
Clear()
void TSharc2::Clear (Option_t * option = "") override
!
Definition at line 128 of file TSharc2.cxx.
References TDetector::Clear(), fBackFragments, fFrontFragments, fXoffset, fYoffset, and fZoffset.
Referenced by TSharc2(), and TSharc2().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Reimplemented in TGriffin, TS3, TTigress, and TTrific.
Definition at line 54 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TGriffin::ClearTransients(), TTigress::ClearTransients(), and TTrific::ClearTransients().
CombineHits()
int TSharc2::CombineHits (TSharc2Hit * , TSharc2Hit * , int , int) private
!
Copy()
void TSharc2::Copy (TObject & rhs) const override
!
Definition at line 154 of file TSharc2.cxx.
References TDetector::Copy().
Referenced by TSharc2(), and operator=().
GetHit()
TDetectorHit * TDetector::GetHit (const int & index) const virtual inherited
Reimplemented in TGriffin.
Definition at line 61 of file TDetector.cxx.
References TDetector::fHits.
Referenced by TSiLi::AddCluster(), TTigress::GetAddbackMultiplicity(), TAries::GetAriesHit(), TBgo::GetBgoHit(), TCSM::GetCSMHit(), TDescant::GetDescantHit(), TEagle::GetEagleHit(), TEmma::GetEmmaHit(), TGenericDetector::GetGenericDetectorHit(), TLaBrBgo::GetLaBrBgoHit(), TLaBr::GetLaBrHit(), TFippsLaBr::GetLaBrHit(), TPaces::GetPacesHit(), TS3::GetS3Hit(), TSceptar::GetSceptarHit(), GetSharc2Hit(), TSharc::GetSharcHit(), TSiLi::GetSiLiHit(), TTAC::GetTACHit(), TFippsTAC::GetTACHit(), TTdrClover::GetTdrCloverHit(), TTdrPlastic::GetTdrPlasticHit(), TTdrSiLi::GetTdrSiLiHit(), TTdrTigress::GetTdrTigressHit(), TTigress::GetTigressHit(), TTip::GetTipHit(), TTrific::GetTrificHit(), TZeroDegree::GetZeroDegreeHit(), MakeAnalysisHistograms(), and TTigress::Print().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 75 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), TSuppressed::CreateSuppressedAddback(), TFipps::FixCrossTalk(), TIfin::FixCrossTalk(), TFipps::GetAddbackMultiplicity(), TIfin::GetAddbackMultiplicity(), TTdrClover::GetAddbackMultiplicity(), TTdrTigress::GetAddbackMultiplicity(), TFipps::GetSuppressedAddbackMultiplicity(), TIfin::GetSuppressedAddbackMultiplicity(), TTdrClover::GetSuppressedAddbackMultiplicity(), TTdrTigress::GetSuppressedAddbackMultiplicity(), TFipps::GetSuppressedMultiplicity(), and TIfin::GetSuppressedMultiplicity().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Reimplemented in TGriffin.
Definition at line 73 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::AddFragment(), ExampleEventHelper::Exec(), ExampleTreeHelper::Exec(), TimeWalkHelper::Exec(), AngularCorrelationSelector::FillHistograms(), ExampleEventSelector::FillHistograms(), ExampleTreeSelector::FillHistograms(), TimeWalkSelector::FillHistograms(), TSiLi::GetAddbackMultiplicity(), TTigress::GetAddbackMultiplicity(), TGriffin::GetLowGainMultiplicity(), TGriffin::GetMultiplicity(), TSharc::GetSize(), main(), MakeAnalysisHistograms(), TAries::Print(), TDescant::Print(), TEmma::Print(), TLaBr::Print(), TPaces::Print(), TSceptar::Print(), TSiLi::Print(), TTAC::Print(), TTigress::Print(), TTip::Print(), TTrific::Print(), TZeroDegree::Print(), TFipps::Print(), TIfin::Print(), TBgo::Print(), TTdrClover::Print(), and TTdrTigress::Print().
GetOffset()
static TVector3 TSharc2::GetOffset () inline static
Definition at line 41 of file TSharc2.h.
References fXoffset, fYoffset, and fZoffset.
GetPosition()
TVector3 TSharc2::GetPosition (int detector, int frontstrip, int backstrip, double X = 0.00, double Y = 0.00, double Z = 0.00) static
!
Definition at line 159 of file TSharc2.cxx.
References fSectorWidthDS2, fSectorWidthUS2, fStripBPitch, fStripFPitch, fStripPitchDS2, fStripPitchUS2, fXminDS2, fXminUS2, fXposUB, fYminUB, fZminUB, fZposDS2, and fZposUS2.
Referenced by TSharc2Hit::GetPosition().
GetSharc2Hit()
TSharc2Hit * TSharc2::GetSharc2Hit (const int & i) const inline
Definition at line 35 of file TSharc2.h.
References TDetector::GetHit().
GetSize()
int TSharc2::GetSize () const inline
!
Definition at line 49 of file TSharc2.h.
References TDetector::Hits().
GetXOffset()
static double TSharc2::GetXOffset () inline static
Definition at line 38 of file TSharc2.h.
References fXoffset.
Referenced by TSharc2Hit::GetPosition().
GetYOffset()
static double TSharc2::GetYOffset () inline static
Definition at line 39 of file TSharc2.h.
References fYoffset.
Referenced by TSharc2Hit::GetPosition().
GetZOffset()
static double TSharc2::GetZOffset () inline static
Definition at line 40 of file TSharc2.h.
References fZoffset.
Referenced by TSharc2Hit::GetPosition().
Hits() [1/2]
std::vector< TDetectorHit * > & TDetector::Hits () inline inherited
Definition at line 78 of file TDetector.h.
References TDetector::fHits.
Referenced by TCSM::BuildHits(), TSharc::BuildHits(), TTigress::BuildHits(), TGriffin::GetHitVector(), TGriffin::GetHitVector(), GetSize(), TLaBr::GetSuppressedMultiplicity(), TGriffin::Print(), and TSiLi::UseFitCharge().
Hits() [2/2]
const std::vector< TDetectorHit * > & TDetector::Hits () const inline inherited
Definition at line 79 of file TDetector.h.
References TDetector::fHits.
NoHits()
virtual bool TDetector::NoHits () const inline virtual inherited
Definition at line 76 of file TDetector.h.
References TDetector::fHits.
Referenced by TTigress::BuildHits(), TTigress::GetAddbackMultiplicity(), and TLaBr::GetSuppressedMultiplicity().
operator=() [1/2]
TSharc2 & TSharc2::operator= (const TSharc2 & rhs) inline
!
Definition at line 26 of file TSharc2.h.
References Copy().
operator=() [2/2]
TSharc2 & TSharc2::operator= (TSharc2 &&) default noexcept
Print() [1/2]
void TSharc2::Print (Option_t * = "") const override
!
Definition at line 142 of file TSharc2.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TSharc2::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 147 of file TSharc2.cxx.
RemoveHits()
void TSharc2::RemoveHits (std::vector< TSharc2Hit > * hits, std::set< int > * to_remove) private
!
Definition at line 118 of file TSharc2.cxx.
SetXYZOffset()
static void TSharc2::SetXYZOffset (const double x, const double y, const double z) inline static
Definition at line 42 of file TSharc2.h.
References fXoffset, fYoffset, and fZoffset.
Member Data Documentation
fBackFragments
std::vector<TFragment> TSharc2::fBackFragments private
Definition at line 70 of file TSharc2.h.
Referenced by AddFragment(), BuildHits(), and Clear().
fFrontFragments
std::vector<TFragment> TSharc2::fFrontFragments private
Definition at line 69 of file TSharc2.h.
Referenced by AddFragment(), BuildHits(), and Clear().
fHits
std::vector<TDetectorHit*> TDetector::fHits private inherited
Definition at line 88 of file TDetector.h.
Referenced by TDetector::~TDetector(), TEagle::AddFragment(), TEaglePulser::AddFragment(), TFipps::AddFragment(), TFippsLaBr::AddFragment(), TFippsPulser::AddFragment(), TFippsTAC::AddFragment(), TIfin::AddFragment(), TTdrClover::AddFragment(), TTdrPlastic::AddFragment(), TTdrSiLi::AddFragment(), TTdrTigress::AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TFipps::GetFippsHit(), TDetector::GetHit(), TDetector::GetHitVector(), TIfin::GetIfinHit(), TDetector::GetMultiplicity(), TFippsLaBr::GetSuppressedMultiplicity(), TTdrClover::GetSuppressedMultiplicity(), TTdrTigress::GetSuppressedMultiplicity(), TDetector::Hits(), TDetector::Hits(), TDetector::NoHits(), TDetector::Print(), TEagle::Print(), TEaglePulser::Print(), TFippsLaBr::Print(), TFippsTAC::Print(), TTdrPlastic::Print(), and TTdrSiLi::Print().
fRingPitch
double TSharc2::fRingPitch static private
Definition at line 103 of file TSharc2.h.
fSectorWidthDS2
double TSharc2::fSectorWidthDS2 = 2 * TMath::Pi() / 16.0 static private
Definition at line 89 of file TSharc2.h.
Referenced by GetPosition().
fSectorWidthUS2
double TSharc2::fSectorWidthUS2 = 2 * TMath::Pi() / 16.0 static private
Definition at line 95 of file TSharc2.h.
Referenced by GetPosition().
fSegmentPitch
double TSharc2::fSegmentPitch static private
Definition at line 104 of file TSharc2.h.
fStripBPitch
double TSharc2::fStripBPitch = TSharc2::fZdim / 48.0 static private
Definition at line 102 of file TSharc2.h.
Referenced by GetPosition().
fStripFPitch
double TSharc2::fStripFPitch = TSharc2::fYdim / 24.0 static private
Definition at line 101 of file TSharc2.h.
Referenced by GetPosition().
fStripPitchDS2
double TSharc2::fStripPitchDS2 = 0.5 static private
Definition at line 88 of file TSharc2.h.
Referenced by GetPosition().
fStripPitchUS2
double TSharc2::fStripPitchUS2 = 0.5 static private
Definition at line 94 of file TSharc2.h.
Referenced by GetPosition().
fXdim
double TSharc2::fXdim = +72.0 static private
Definition at line 78 of file TSharc2.h.
fXminDS2
double TSharc2::fXminDS2 = 11.0 static private
Definition at line 87 of file TSharc2.h.
Referenced by GetPosition().
fXminUS2
double TSharc2::fXminUS2 = 11.0 static private
Definition at line 93 of file TSharc2.h.
Referenced by GetPosition().
fXoffset
double TSharc2::fXoffset = +0.00 static private
!
Definition at line 72 of file TSharc2.h.
Referenced by Clear(), GetOffset(), GetXOffset(), and SetXYZOffset().
fXposUB
double TSharc2::fXposUB = +42.5 static private
total Z dimension of all boxes
Definition at line 81 of file TSharc2.h.
Referenced by GetPosition().
fYdim
double TSharc2::fYdim = +72.0 static private
total X dimension of all boxes
Definition at line 79 of file TSharc2.h.
fYminUB
double TSharc2::fYminUB = -36.0 static private
Definition at line 82 of file TSharc2.h.
Referenced by GetPosition().
fYoffset
double TSharc2::fYoffset = +0.00 static private
!
Definition at line 73 of file TSharc2.h.
Referenced by Clear(), GetOffset(), GetYOffset(), and SetXYZOffset().
fZdim
double TSharc2::fZdim = +48.0 static private
total Y dimension of all boxes
Definition at line 80 of file TSharc2.h.
fZminUB
double TSharc2::fZminUB = -5.00 static private
Definition at line 83 of file TSharc2.h.
Referenced by GetPosition().
fZoffset
double TSharc2::fZoffset = +0.00 static private
!
Definition at line 74 of file TSharc2.h.
Referenced by Clear(), GetOffset(), GetZOffset(), and SetXYZOffset().
fZposDS2
double TSharc2::fZposDS2 = 58.5 static private
Definition at line 86 of file TSharc2.h.
Referenced by GetPosition().
fZposUS2
double TSharc2::fZposUS2 = 72.0 static private
Definition at line 92 of file TSharc2.h.
Referenced by GetPosition().