GRSISort: TDecayChain Class Reference
TDecayChain Class Reference
Fitting & Analysis
Detailed Description
Definition at line 269 of file TDecay.h.
Public Member Functions
TDecayChain ()=default
TDecayChain (const TDecayChain &)=default
TDecayChain (TDecayChain &&) noexcept=default
TDecayChain (UInt_t generations)
~TDecayChain ()
void Draw (Option_t *opt="") override
void DrawComponents (Option_t *opt="", Bool_t color_flag=true) override
Double_t Eval (Double_t t) const
Double_t EvalPar (const Double_t *x, const Double_t *par=nullptr)
TFitResultPtr Fit (TH1 *fithist, Option_t *opt="")
const TDecayFit * GetChainFunc ()
Int_t GetChainId () const
TSingleDecay * GetDecay (UInt_t generation)
TDecayChain & operator= (const TDecayChain &)=default
TDecayChain & operator= (TDecayChain &&) noexcept=default
void Print (Option_t *option="") const override
void SetChainParameters ()
void SetRange (Double_t xlow, Double_t xhigh)
Int_t Size () const
Private Member Functions
void AddToChain (TSingleDecay *decay)
Double_t ChainActivityFunc (Double_t *dim, Double_t *par)
const TDecayFit * GetFitFunction () override
Private Attributes
TDecayFit * fChainFunc {nullptr}
Int_t fChainId {-1}
std::vector< TSingleDecay * > fDecayChain
Static Private Attributes
static UInt_t fChainCounter = 0
Constructor & Destructor Documentation
TDecayChain() [1/4]
TDecayChain::TDecayChain () default
TDecayChain() [2/4]
TDecayChain::TDecayChain (UInt_t generations) explicit
Definition at line 464 of file TDecay.cxx.
References ChainActivityFunc(), fChainCounter, fChainFunc, fChainId, fDecayChain, SetChainParameters(), and TDecayFit::SetDecay().
TDecayChain() [3/4]
TDecayChain::TDecayChain (const TDecayChain &) default
TDecayChain() [4/4]
TDecayChain::TDecayChain (TDecayChain &&) default noexcept
~TDecayChain()
TDecayChain::~TDecayChain ()
Definition at line 488 of file TDecay.cxx.
References fChainFunc, and fDecayChain.
Member Function Documentation
AddToChain()
void TDecayChain::AddToChain (TSingleDecay * decay) private
Definition at line 550 of file TDecay.cxx.
References fDecayChain.
ChainActivityFunc()
Double_t TDecayChain::ChainActivityFunc (Double_t * dim, Double_t * par) private
This fits the total activity caused by the entire chain.
Definition at line 514 of file TDecay.cxx.
References TSingleDecay::EvalPar(), fDecayChain, and GetDecay().
Referenced by TDecayChain().
Draw()
void TDecayChain::Draw (Option_t * opt = "") override
Definition at line 530 of file TDecay.cxx.
References fChainFunc, and SetChainParameters().
DrawComponents()
void TDecayChain::DrawComponents (Option_t * opt = "", Bool_t color_flag = true) override virtual
Reimplemented from TVirtualDecay.
Definition at line 536 of file TDecay.cxx.
References fDecayChain, and SetChainParameters().
Eval()
Double_t TDecayChain::Eval (Double_t t) const
Definition at line 525 of file TDecay.cxx.
References fChainFunc.
EvalPar()
Double_t TDecayChain::EvalPar (const Double_t * x, const Double_t * par = nullptr)
Definition at line 608 of file TDecay.cxx.
References fChainFunc, and SetChainParameters().
Fit()
TFitResultPtr TDecayChain::Fit (TH1 * fithist, Option_t * opt = "")
Definition at line 578 of file TDecay.cxx.
References fChainFunc, fDecayChain, TDecayFit::Fit(), TSingleDecay::GetDaughterDecay(), SetChainParameters(), TSingleDecay::SetDecayRate(), TSingleDecay::SetDecayRateError(), TSingleDecay::SetIntensity(), TSingleDecay::SetIntensityError(), and TSingleDecay::UpdateDecays().
GetChainFunc()
const TDecayFit * TDecayChain::GetChainFunc () inline
Definition at line 288 of file TDecay.h.
GetChainId()
Int_t TDecayChain::GetChainId () const inline
Definition at line 297 of file TDecay.h.
GetDecay()
TSingleDecay * TDecayChain::GetDecay (UInt_t generation)
Definition at line 557 of file TDecay.cxx.
References fDecayChain, and SetChainParameters().
Referenced by ChainActivityFunc().
GetFitFunction()
const TDecayFit * TDecayChain::GetFitFunction () inline override private virtual
Implements TVirtualDecay.
Definition at line 303 of file TDecay.h.
operator=() [1/2]
TDecayChain & TDecayChain::operator= (const TDecayChain &) default
operator=() [2/2]
TDecayChain & TDecayChain::operator= (TDecayChain &&) default noexcept
Print()
void TDecayChain::Print (Option_t * option = "") const override virtual
Implements TVirtualDecay.
Definition at line 567 of file TDecay.cxx.
References fDecayChain.
SetChainParameters()
void TDecayChain::SetChainParameters ()
Definition at line 497 of file TDecay.cxx.
References fChainFunc, and fDecayChain.
Referenced by TDecayChain(), Draw(), DrawComponents(), EvalPar(), Fit(), and GetDecay().
SetRange()
void TDecayChain::SetRange (Double_t xlow, Double_t xhigh)
Definition at line 616 of file TDecay.cxx.
References fChainFunc, and fDecayChain.
Size()
Int_t TDecayChain::Size () const inline
Definition at line 282 of file TDecay.h.
Member Data Documentation
fChainCounter
UInt_t TDecayChain::fChainCounter = 0 static private
Definition at line 302 of file TDecay.h.
Referenced by TDecayChain().
fChainFunc
TDecayFit* TDecayChain::fChainFunc {nullptr} private
Definition at line 310 of file TDecay.h.
Referenced by TDecayChain(), ~TDecayChain(), Draw(), Eval(), EvalPar(), Fit(), SetChainParameters(), and SetRange().
fChainId
Int_t TDecayChain::fChainId {-1} private
Definition at line 311 of file TDecay.h.
Referenced by TDecayChain().
fDecayChain
std::vector<TSingleDecay*> TDecayChain::fDecayChain private
Definition at line 309 of file TDecay.h.
Referenced by TDecayChain(), ~TDecayChain(), AddToChain(), ChainActivityFunc(), DrawComponents(), Fit(), GetDecay(), Print(), SetChainParameters(), and SetRange().