GRSISort: TUnpackingLoop Class Reference
TUnpackingLoop Class Reference
Loops
Detailed Description
This loop parses raw events into fragments.
Definition at line 27 of file TUnpackingLoop.h.
Public Types
enum class EDataType { kMidas , kLst , kTdr }
Public Member Functions
~TUnpackingLoop () override
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & AddGoodOutputQueue (size_t maxSize=50000)
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & BadOutputQueue ()
void ClearQueue () override
std::string EndStatus () override
size_t GetItemsCurrent () override
size_t GetItemsPopped () override
size_t GetItemsPushed () override
size_t GetRate () override
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TRawEvent > > > & InputQueue ()
bool IsPaused ()
bool IsRunning ()
bool Iteration () override
void Join ()
std::string Name () const
virtual void OnEnd ()
void Pause ()
virtual std::string Progress ()
void Resume ()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & ScalerOutputQueue ()
void SetNoWaveForms (bool temp=true)
void SetRecordDiag (bool temp=true)
virtual std::string Status ()
void Stop ()
Static Public Member Functions
static std::string AllThreadHeader ()
static std::string AllThreadProgress ()
static std::string AllThreadStatus ()
static bool AnyThreadRunning ()
static std::string AnyThreadStatus ()
static void ClearAllQueues ()
static size_t ColumnWidth ()
static void ColumnWidth (size_t val)
static StoppableThread * Get (const std::string &name)
static TUnpackingLoop * Get (std::string name="")
static std::vector< StoppableThread * > GetAll ()
static int GetNThreads ()
static void join_status_thread ()
static void PauseAll ()
static void Print ()
static void ResumeAll ()
static void SendStop ()
static void start_status_thread ()
static void status_out ()
static void status_out_loop ()
static size_t StatusWidth ()
static void StatusWidth (size_t val)
static void stop_status_thread ()
static void StopAll ()
Protected Attributes
std::atomic_long fInputSize {0}
std::atomic_size_t fItemsPopped {0}
Private Member Functions
TUnpackingLoop (const TUnpackingLoop &other)
TUnpackingLoop (std::string name)
ClassDef (StoppableThread, 0)
void Loop ()
TUnpackingLoop & operator= (const TUnpackingLoop &other)
Private Attributes
EDataType fDataType
bool fEvaluateDataType
std::atomic_bool fForceStop {false}
int64_t fFragsReadFromRaw
int64_t fGoodFragsRead
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TRawEvent > > > fInputQueue
std::string fName
TDataParser * fParser
std::atomic_bool fPaused {false}
std::condition_variable fPausedWait
std::mutex fPauseMutex
std::atomic_bool fRunning {false}
std::thread fThread
Static Private Attributes
static size_t fColumnWidth = 20
static std::thread fStatusThread
static bool fStatusThreadOn = false
static size_t fStatusWidth = 80
static std::map< std::string, StoppableThread * > fThreadMap
Member Enumeration Documentation
EDataType
enum class TUnpackingLoop::EDataType strong
Enumerator
kMidas
kLst
kTdr
Definition at line 29 of file TUnpackingLoop.h.
Constructor & Destructor Documentation
~TUnpackingLoop()
TUnpackingLoop::~TUnpackingLoop () override default
TUnpackingLoop() [1/2]
TUnpackingLoop::TUnpackingLoop (std::string name) private
Definition at line 24 of file TUnpackingLoop.cxx.
References TParserLibrary::CreateDataParser(), fParser, TSingleton< TParserLibrary >::Get(), and TGRSIOptions::Get().
TUnpackingLoop() [2/2]
TUnpackingLoop::TUnpackingLoop (const TUnpackingLoop & other) private
Member Function Documentation
AddGoodOutputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TUnpackingLoop::AddGoodOutputQueue (size_t maxSize = 50000) inline
Definition at line 44 of file TUnpackingLoop.h.
References TDataParser::AddGoodOutputQueue(), and fParser.
Referenced by TGRSIint::SetupPipeline().
AllThreadHeader()
std::string StoppableThread::AllThreadHeader () static inherited
Definition at line 73 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::ApplyOptions().
AllThreadProgress()
std::string StoppableThread::AllThreadProgress () static inherited
Definition at line 59 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AllThreadStatus()
std::string StoppableThread::AllThreadStatus () static inherited
Definition at line 83 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, and StoppableThread::fThreadMap.
Referenced by TGRSIint::LoopUntilDone().
AnyThreadRunning()
bool StoppableThread::AnyThreadRunning () static inherited
Definition at line 37 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TChannel::GetChannel(), TGRSIint::LoopUntilDone(), and TGRSIInterruptHandler::Notify().
AnyThreadStatus()
std::string StoppableThread::AnyThreadStatus () static inherited
Definition at line 47 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
BadOutputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & TUnpackingLoop::BadOutputQueue () inline
Definition at line 48 of file TUnpackingLoop.h.
References TDataParser::BadOutputQueue(), and fParser.
Referenced by Iteration(), and TGRSIint::SetupPipeline().
ClassDef()
StoppableThread::ClassDef (StoppableThread , 0) private inherited
ClearAllQueues()
void StoppableThread::ClearAllQueues () static inherited
Definition at line 166 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIInterruptHandler::Notify().
ClearQueue()
void TUnpackingLoop::ClearQueue () override virtual
Reimplemented from StoppableThread.
Definition at line 39 of file TUnpackingLoop.cxx.
References TDataParser::ClearQueue(), fInputQueue, and fParser.
ColumnWidth() [1/2]
static size_t StoppableThread::ColumnWidth () inline static inherited
Definition at line 78 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
Referenced by TGRSIint::SetupPipeline().
ColumnWidth() [2/2]
static void StoppableThread::ColumnWidth (size_t val) inline static inherited
Definition at line 76 of file StoppableThread.h.
References StoppableThread::fColumnWidth.
EndStatus()
std::string TUnpackingLoop::EndStatus () override virtual
Reimplemented from StoppableThread.
Definition at line 76 of file TUnpackingLoop.cxx.
References fFragsReadFromRaw, fGoodFragsRead, fParser, StoppableThread::Name(), and TDataParser::OutputQueueStatus().
Get() [1/2]
StoppableThread * StoppableThread::Get (const std::string & name) static inherited
Definition at line 173 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TAnalysisHistLoop::Get(), TDetBuildingLoop::Get(), TFragHistLoop::Get(), TTerminalLoop< T >::Get(), Get(), TEventBuildingLoop::Get(), TFragWriteLoop::Get(), TAnalysisWriteLoop::Get(), TFragmentChainLoop::Get(), and TDataLoop::Get().
Get() [2/2]
TUnpackingLoop * TUnpackingLoop::Get (std::string name = "") static
Definition at line 11 of file TUnpackingLoop.cxx.
References StoppableThread::Get().
Referenced by TGRSIint::SetupPipeline().
GetAll()
std::vector< StoppableThread * > StoppableThread::GetAll () static inherited
Definition at line 315 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
GetItemsCurrent()
size_t TUnpackingLoop::GetItemsCurrent () inline override virtual
Implements StoppableThread.
Definition at line 64 of file TUnpackingLoop.h.
GetItemsPopped()
size_t TUnpackingLoop::GetItemsPopped () inline override virtual
Implements StoppableThread.
Definition at line 63 of file TUnpackingLoop.h.
GetItemsPushed()
size_t TUnpackingLoop::GetItemsPushed () inline override virtual
Implements StoppableThread.
Definition at line 62 of file TUnpackingLoop.h.
References fParser, and TDataParser::ItemsPushed().
GetNThreads()
int StoppableThread::GetNThreads () static inherited
Definition at line 21 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by StoppableThread::Print().
GetRate()
size_t TUnpackingLoop::GetRate () inline override virtual
Implements StoppableThread.
Definition at line 65 of file TUnpackingLoop.h.
InputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TRawEvent > > > & TUnpackingLoop::InputQueue () inline
Definition at line 40 of file TUnpackingLoop.h.
References fInputQueue.
Referenced by TGRSIint::SetupPipeline().
IsPaused()
bool StoppableThread::IsPaused () inherited
Definition at line 224 of file StoppableThread.cxx.
References StoppableThread::fPaused.
IsRunning()
bool StoppableThread::IsRunning () inherited
Definition at line 219 of file StoppableThread.cxx.
References StoppableThread::fRunning.
Referenced by StoppableThread::status_out().
Iteration()
bool TUnpackingLoop::Iteration () override virtual
Implements StoppableThread.
Definition at line 49 of file TUnpackingLoop.cxx.
References BadOutputQueue(), fFragsReadFromRaw, fGoodFragsRead, fInputQueue, StoppableThread::fInputSize, StoppableThread::fItemsPopped, fParser, TDataParser::Process(), ScalerOutputQueue(), TDataParser::SetFinished(), and TDataParser::SetStatusVariables().
Join()
void StoppableThread::Join () inherited
Definition at line 229 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), and StoppableThread::fThread.
Referenced by StoppableThread::StopAll().
join_status_thread()
void StoppableThread::join_status_thread () static inherited
Definition at line 280 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, and StoppableThread::stop_status_thread().
Loop()
void StoppableThread::Loop () private inherited
Definition at line 237 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, StoppableThread::fRunning, StoppableThread::Iteration(), and StoppableThread::OnEnd().
Referenced by StoppableThread::StoppableThread().
Name()
std::string StoppableThread::Name () const inline inherited
Definition at line 59 of file StoppableThread.h.
References StoppableThread::fName.
Referenced by TAnalysisWriteLoop::AddBranch(), TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), EndStatus(), and StoppableThread::status_out().
OnEnd()
virtual void StoppableThread::OnEnd () inline virtual inherited
Reimplemented in TAnalysisWriteLoop, TDataLoop, and TFragmentChainLoop.
Definition at line 55 of file StoppableThread.h.
Referenced by StoppableThread::Loop().
operator=()
TUnpackingLoop & TUnpackingLoop::operator= (const TUnpackingLoop & other) private
Pause()
void StoppableThread::Pause () inherited
Definition at line 202 of file StoppableThread.cxx.
References StoppableThread::fPaused, and StoppableThread::fRunning.
PauseAll()
void StoppableThread::PauseAll () static inherited
Definition at line 97 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Print()
void StoppableThread::Print () static inherited
Definition at line 254 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fStatusWidth, StoppableThread::fThreadMap, StoppableThread::GetNThreads(), and hex().
Progress()
std::string StoppableThread::Progress () virtual inherited
Definition at line 119 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
Resume()
void StoppableThread::Resume () inherited
Definition at line 193 of file StoppableThread.cxx.
References StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
ResumeAll()
void StoppableThread::ResumeAll () static inherited
Definition at line 104 of file StoppableThread.cxx.
References StoppableThread::fThreadMap.
Referenced by TGRSIint::SetupPipeline().
ScalerOutputQueue()
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & TUnpackingLoop::ScalerOutputQueue () inline
Definition at line 52 of file TUnpackingLoop.h.
References fParser, and TDataParser::ScalerOutputQueue().
Referenced by Iteration(), and TGRSIint::SetupPipeline().
SendStop()
void StoppableThread::SendStop () static inherited
Definition at line 135 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, and StoppableThread::Stop().
Referenced by StoppableThread::StopAll(), and TGRSIint::Terminate().
SetNoWaveForms()
void TUnpackingLoop::SetNoWaveForms (bool temp = true) inline
Definition at line 36 of file TUnpackingLoop.h.
References fParser, and TDataParser::SetNoWaveForms().
SetRecordDiag()
void TUnpackingLoop::SetRecordDiag (bool temp = true) inline
Definition at line 37 of file TUnpackingLoop.h.
References fParser, and TDataParser::SetRecordDiag().
start_status_thread()
void StoppableThread::start_status_thread () static inherited
Definition at line 265 of file StoppableThread.cxx.
References StoppableThread::fStatusThread, StoppableThread::fStatusThreadOn, and StoppableThread::status_out_loop().
Referenced by StoppableThread::StoppableThread().
Status()
std::string StoppableThread::Status () virtual inherited
Definition at line 111 of file StoppableThread.cxx.
References StoppableThread::fColumnWidth, StoppableThread::fInputSize, and StoppableThread::fItemsPopped.
status_out()
void StoppableThread::status_out () static inherited
Definition at line 297 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::GetItemsCurrent(), StoppableThread::GetItemsPopped(), StoppableThread::GetItemsPushed(), StoppableThread::GetRate(), StoppableThread::IsRunning(), and StoppableThread::Name().
Referenced by StoppableThread::status_out_loop(), and StoppableThread::StopAll().
status_out_loop()
void StoppableThread::status_out_loop () static inherited
Definition at line 286 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn, and StoppableThread::status_out().
Referenced by StoppableThread::start_status_thread().
StatusWidth() [1/2]
static size_t StoppableThread::StatusWidth () inline static inherited
Definition at line 79 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Referenced by TGRSIint::SetupPipeline().
StatusWidth() [2/2]
static void StoppableThread::StatusWidth (size_t val) inline static inherited
Definition at line 77 of file StoppableThread.h.
References StoppableThread::fStatusWidth.
Stop()
void StoppableThread::Stop () inherited
Definition at line 209 of file StoppableThread.cxx.
References StoppableThread::EndStatus(), StoppableThread::fPaused, StoppableThread::fPausedWait, StoppableThread::fPauseMutex, and StoppableThread::fRunning.
Referenced by StoppableThread::SendStop().
stop_status_thread()
void StoppableThread::stop_status_thread () static inherited
Definition at line 273 of file StoppableThread.cxx.
References StoppableThread::fStatusThreadOn.
Referenced by StoppableThread::join_status_thread().
StopAll()
void StoppableThread::StopAll () static inherited
Definition at line 147 of file StoppableThread.cxx.
References StoppableThread::fThreadMap, StoppableThread::Join(), StoppableThread::SendStop(), and StoppableThread::status_out().
Referenced by TGRSIint::Terminate().
Member Data Documentation
fColumnWidth
size_t StoppableThread::fColumnWidth = 20 static private inherited
Definition at line 101 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::ColumnWidth(), StoppableThread::ColumnWidth(), StoppableThread::Print(), StoppableThread::Progress(), and StoppableThread::Status().
fDataType
EDataType TUnpackingLoop::fDataType private
Definition at line 79 of file TUnpackingLoop.h.
fEvaluateDataType
bool TUnpackingLoop::fEvaluateDataType private
Definition at line 78 of file TUnpackingLoop.h.
fForceStop
std::atomic_bool StoppableThread::fForceStop {false} private inherited
Definition at line 113 of file StoppableThread.h.
fFragsReadFromRaw
int64_t TUnpackingLoop::fFragsReadFromRaw private
Definition at line 75 of file TUnpackingLoop.h.
Referenced by EndStatus(), and Iteration().
fGoodFragsRead
int64_t TUnpackingLoop::fGoodFragsRead private
Definition at line 76 of file TUnpackingLoop.h.
Referenced by EndStatus(), and Iteration().
fInputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<TRawEvent> > > TUnpackingLoop::fInputQueue private
Definition at line 71 of file TUnpackingLoop.h.
Referenced by ClearQueue(), InputQueue(), and Iteration().
fInputSize
std::atomic_long StoppableThread::fInputSize {0} protected inherited
number of items in the input (queue), only updated within Iteration(), so not always fully up-to-date (signed to hold error from queue::pop)
Definition at line 91 of file StoppableThread.h.
Referenced by TAnalysisWriteLoop::EndStatus(), TFragWriteLoop::EndStatus(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), Iteration(), StoppableThread::Progress(), and StoppableThread::Status().
fItemsPopped
std::atomic_size_t StoppableThread::fItemsPopped {0} protected inherited
number of items popped from input queue
Definition at line 90 of file StoppableThread.h.
Referenced by TAnalysisWriteLoop::EndStatus(), TEventBuildingLoop::EndStatus(), TFragWriteLoop::EndStatus(), TFragmentChainLoop::GetItemsPopped(), TFragWriteLoop::GetItemsPopped(), TAnalysisWriteLoop::GetItemsPushed(), TFragmentChainLoop::GetItemsPushed(), TFragWriteLoop::GetItemsPushed(), TAnalysisHistLoop::Iteration(), TAnalysisWriteLoop::Iteration(), TDataLoop::Iteration(), TDetBuildingLoop::Iteration(), TEventBuildingLoop::Iteration(), TFragHistLoop::Iteration(), TFragmentChainLoop::Iteration(), TFragWriteLoop::Iteration(), Iteration(), StoppableThread::Progress(), TFragmentChainLoop::Restart(), and StoppableThread::Status().
fName
std::string StoppableThread::fName private inherited
Definition at line 99 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), and StoppableThread::Name().
fParser
TDataParser* TUnpackingLoop::fParser private
Definition at line 74 of file TUnpackingLoop.h.
Referenced by TUnpackingLoop(), AddGoodOutputQueue(), BadOutputQueue(), ClearQueue(), EndStatus(), GetItemsPushed(), Iteration(), ScalerOutputQueue(), SetNoWaveForms(), and SetRecordDiag().
fPaused
std::atomic_bool StoppableThread::fPaused {false} private inherited
Definition at line 114 of file StoppableThread.h.
Referenced by StoppableThread::IsPaused(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fPausedWait
std::condition_variable StoppableThread::fPausedWait private inherited
Definition at line 115 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fPauseMutex
std::mutex StoppableThread::fPauseMutex private inherited
Definition at line 116 of file StoppableThread.h.
Referenced by StoppableThread::Loop(), StoppableThread::Resume(), and StoppableThread::Stop().
fRunning
std::atomic_bool StoppableThread::fRunning {false} private inherited
Definition at line 112 of file StoppableThread.h.
Referenced by StoppableThread::IsRunning(), StoppableThread::Loop(), StoppableThread::Pause(), StoppableThread::Resume(), and StoppableThread::Stop().
fStatusThread
std::thread StoppableThread::fStatusThread static private inherited
Definition at line 110 of file StoppableThread.h.
Referenced by StoppableThread::~StoppableThread(), StoppableThread::join_status_thread(), and StoppableThread::start_status_thread().
fStatusThreadOn
bool StoppableThread::fStatusThreadOn = false static private inherited
Definition at line 108 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::start_status_thread(), StoppableThread::status_out_loop(), and StoppableThread::stop_status_thread().
fStatusWidth
size_t StoppableThread::fStatusWidth = 80 static private inherited
Definition at line 102 of file StoppableThread.h.
Referenced by StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::Print(), StoppableThread::StatusWidth(), and StoppableThread::StatusWidth().
fThread
std::thread StoppableThread::fThread private inherited
Definition at line 111 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), and StoppableThread::Join().
fThreadMap
std::map< std::string, StoppableThread * > StoppableThread::fThreadMap static private inherited
Definition at line 106 of file StoppableThread.h.
Referenced by StoppableThread::StoppableThread(), StoppableThread::~StoppableThread(), StoppableThread::AllThreadHeader(), StoppableThread::AllThreadProgress(), StoppableThread::AllThreadStatus(), StoppableThread::AnyThreadRunning(), StoppableThread::AnyThreadStatus(), StoppableThread::ClearAllQueues(), StoppableThread::Get(), StoppableThread::GetAll(), StoppableThread::GetNThreads(), StoppableThread::PauseAll(), StoppableThread::Print(), StoppableThread::ResumeAll(), StoppableThread::SendStop(), StoppableThread::status_out(), and StoppableThread::StopAll().