GRSISort: TDetectorHit Class Reference
TDetectorHit Class Reference
Detectors
This is class that contains the basic info about detector hits:
An address. The whoami for the detector. This is the value used by TChannel::GetChannel(address);
An "Energy value." What this is left the parent class, but it is going to return a double.
A Time value. This should be a time value common for detectors (derived from the timestamp) Units matter here, I am adobting the ns as the standard.
A Position. Tvector3s are nice, they make doing geometery trival. Each hit needs one to determine where it is in space, the actual memory of the thing will be stored here. *** This is not actually needed here unless we start do waveform analysis to *** better determine where the hit is.
The waveform. Since we are dealing with digital daqs, a waveform is a fairly common thing to have. It may not always be present, put it is echoed enough that the storage for it belongs here.
Definition at line 48 of file TDetectorHit.h.
Public Types
enum class EBitFlag {
kIsEnergySet = BIT(0) , kIsChannelSet = BIT(1) , kBit2 = BIT(2) , kBit3 = BIT(3) ,
kIsPPGSet = BIT(4) , kIsTimeSet = BIT(5) , kBit6 = BIT(6) , kBit7 = BIT(7) ,
kBit8 = BIT(8) , kDetHitBit0 = BIT(9) , kDetHitBit1 = BIT(10) , kDetHitBit2 = BIT(11) ,
kDetHitBit3 = BIT(12) , kDetHitBit4 = BIT(13) , kDetHitBit5 = BIT(14) , kDetHitBit6 = BIT(15) ,
kBase = BIT(9) , kIsAllSet = 0xFFFF
}
enum class ETimeFlag {
kNoneSet = BIT(0) , kCFD = BIT(1) , kWalk = BIT(2) , kOffset = BIT(3) ,
kAll = 0xFFFF
}
Public Member Functions
TDetectorHit (const int &Address=0xffffffff)
TDetectorHit (const TDetectorHit &, bool copywave=true)
~TDetectorHit () override
virtual void Add (const TDetectorHit *)
void AddWaveformSample (const Short_t &x)
virtual void AppendTimeStamp (const Long64_t &x)
virtual Float_t Charge () const
void Clear (Option_t *opt="") override
void ClearChannel ()
void ClearEnergy ()
virtual void ClearTransients () const
void Copy (TObject &) const override
virtual void Copy (TObject &, bool copywave) const
virtual void CopyWave (TObject &) const
virtual UInt_t GetAddress () const
virtual UShort_t GetArrayNumber () const
virtual Float_t GetCfd () const
TChannel * GetChannel () const
virtual Short_t GetChannelNumber () const
virtual Float_t GetCharge () const
virtual Int_t GetCrystal () const
Long64_t GetCycleTimeStamp () const
virtual Int_t GetDetector () const
virtual double GetEnergy (Option_t *opt="") const
virtual Double_t GetEnergyNonlinearity (double energy) const
virtual Short_t GetKValue () const
const char * GetName () const override
virtual TVector3 GetPosition () const
virtual TVector3 GetPosition (Double_t) const
EPpgPattern GetPPGStatus () const
virtual Int_t GetSegment () const
virtual Double_t GetTime (const ETimeFlag &correct_flag=ETimeFlag::kAll, Option_t *opt="") const
double GetTimeSinceTapeMove () const
virtual Long64_t GetTimeStamp (Option_t *="") const
virtual Long64_t GetTimeStampNs (Option_t *opt="") const
virtual Int_t GetTimeStampUnit () const
const std::vector< Short_t > * GetWaveform () const
virtual bool HasWave () const
bool operator< (const TDetectorHit &rhs) const
TDetectorHit & operator= (const TDetectorHit &)=default
void Print (Option_t *opt="") const override
virtual void Print (std::ostream &out) const
void SetAddress (const UInt_t &temp_address)
virtual void SetCfd (const Float_t &x)
virtual void SetCfd (const Int_t &x)
virtual void SetCfd (const uint32_t &x)
void SetCharge (const Float_t &temp_charge)
void SetCharge (const Int_t &temp_charge)
Double_t SetEnergy (const double &en) const
void SetHitBit (EBitFlag, Bool_t set=true) const
void SetKValue (const Short_t &temp_kval)
Double_t SetTime (const Double_t &time) const
virtual void SetTimeStamp (const Long64_t &x)
void SetWaveform (const std::vector< Short_t > &x)
bool TestHitBit (EBitFlag flag) const
Static Public Member Functions
static bool CompareEnergy (TDetectorHit *lhs, TDetectorHit *rhs)
static TVector3 * GetBeamDirection ()
Protected Member Functions
Bool_t IsChannelSet () const
Bool_t IsEnergySet () const
Bool_t IsPPGSet () const
Bool_t IsTimeSet () const
Protected Attributes
UInt_t fAddress {0}
TTransientBits< UChar_t > fBitFlags
Float_t fCfd {0}
Float_t fCharge {0.}
Short_t fKValue {0}
Double_t fTime {0.}
Long64_t fTimeStamp {0}
std::vector< Short_t > fWaveform
Static Protected Attributes
static TVector3 fBeamDirection
Private Attributes
TChannel * fChannel {nullptr}
Long64_t fCycleTimeStamp {0}
Double_t fEnergy {0.}
EPpgPattern fPPGStatus {EPpgPattern::kJunk}
Friends
std::ostream & operator<< (std::ostream &out, const TDetectorHit &hit)
#include <TDetectorHit.h>
Member Enumeration Documentation
EBitFlag
enum class TDetectorHit::EBitFlag strong
Enumerator
kIsEnergySet
kIsChannelSet
kBit2
kBit3
kIsPPGSet
kIsTimeSet
kBit6
kBit7
kBit8
kDetHitBit0
kDetHitBit1
kDetHitBit2
kDetHitBit3
kDetHitBit4
kDetHitBit5
kDetHitBit6
kBase
kIsAllSet
Definition at line 52 of file TDetectorHit.h.
ETimeFlag
enum class TDetectorHit::ETimeFlag strong
Enumerator
kNoneSet
kCFD
kWalk
kOffset
kAll
Definition at line 79 of file TDetectorHit.h.
Constructor & Destructor Documentation
TDetectorHit() [1/2]
TDetectorHit::TDetectorHit (const int & Address = 0xffffffff)
Default constructor
Definition at line 15 of file TDetectorHit.cxx.
References Clear(), and fAddress.
TDetectorHit() [2/2]
TDetectorHit::TDetectorHit (const TDetectorHit & rhs, bool copywave = true)
Default Copy constructor
Definition at line 26 of file TDetectorHit.cxx.
References ClearTransients(), Copy(), and CopyWave().
~TDetectorHit()
TDetectorHit::~TDetectorHit () override
Definition at line 40 of file TDetectorHit.cxx.
Member Function Documentation
Add()
virtual void TDetectorHit::Add (const TDetectorHit *) inline virtual
!
Definition at line 188 of file TDetectorHit.h.
AddWaveformSample()
void TDetectorHit::AddWaveformSample (const Short_t & x) inline
!
Definition at line 121 of file TDetectorHit.h.
References fWaveform.
AppendTimeStamp()
virtual void TDetectorHit::AppendTimeStamp (const Long64_t & x) inline virtual
!
Definition at line 123 of file TDetectorHit.h.
References fTimeStamp.
Charge()
virtual Float_t TDetectorHit::Charge () const inline virtual
!
Definition at line 149 of file TDetectorHit.h.
References fCharge.
Referenced by GetCharge(), GetEnergy(), and Print().
Clear()
void TDetectorHit::Clear (Option_t * opt = "") override
!
General clear statement for a TDetectorHit.
Definition at line 175 of file TDetectorHit.cxx.
References fAddress, fBitFlags, fCfd, fChannel, fCharge, fCycleTimeStamp, fEnergy, fKValue, fPPGStatus, fTime, fTimeStamp, fWaveform, and kJunk.
Referenced by TDetectorHit(), TFragment::Clear(), and TBgoHit::Clear().
ClearChannel()
void TDetectorHit::ClearChannel () inline
Definition at line 180 of file TDetectorHit.h.
References fChannel, kIsChannelSet, and SetHitBit().
ClearEnergy()
void TDetectorHit::ClearEnergy () inline
Definition at line 175 of file TDetectorHit.h.
References fEnergy, kIsEnergySet, and SetHitBit().
ClearTransients()
virtual void TDetectorHit::ClearTransients () const inline virtual
Definition at line 100 of file TDetectorHit.h.
References fBitFlags.
Referenced by TDetectorHit(), TAnalysisWriteLoop::Iteration(), and TFragWriteLoop::WriteEvent().
CompareEnergy()
bool TDetectorHit::CompareEnergy (TDetectorHit * lhs, TDetectorHit * rhs) static
Definition at line 219 of file TDetectorHit.cxx.
References GetEnergy().
Copy() [1/2]
void TDetectorHit::Copy (TObject & rhs) const override
!
Definition at line 116 of file TDetectorHit.cxx.
References fAddress, fBitFlags, fCfd, fChannel, fCharge, fCycleTimeStamp, fEnergy, fKValue, fPPGStatus, fTime, and fTimeStamp.
Referenced by TDetectorHit(), TDetector::Copy(), Copy(), and TBgoHit::Copy().
Copy() [2/2]
void TDetectorHit::Copy (TObject & rhs, bool copywave) const virtual
!
Reimplemented in TBgoHit.
Definition at line 139 of file TDetectorHit.cxx.
References Copy(), and CopyWave().
CopyWave()
void TDetectorHit::CopyWave (TObject & rhs) const virtual
!
Definition at line 134 of file TDetectorHit.cxx.
References fWaveform.
Referenced by TDetectorHit(), and Copy().
GetAddress()
virtual UInt_t TDetectorHit::GetAddress () const inline virtual
!
Definition at line 147 of file TDetectorHit.h.
References fAddress.
Referenced by TFragment::Print().
GetArrayNumber()
virtual UShort_t TDetectorHit::GetArrayNumber () const inline virtual
! Simply returns the detector number, overwritten for detectors that have crystals/segments
Reimplemented in TBgoHit.
Definition at line 167 of file TDetectorHit.h.
References GetDetector().
GetBeamDirection()
static TVector3 * TDetectorHit::GetBeamDirection () inline static
Definition at line 186 of file TDetectorHit.h.
References fBeamDirection.
GetCfd()
virtual Float_t TDetectorHit::GetCfd () const inline virtual
!
Definition at line 146 of file TDetectorHit.h.
References fCfd.
Referenced by TFragment::Get4GCfd(), GetTime(), and TFragment::Print().
GetChannel()
TChannel * TDetectorHit::GetChannel () const inline
!
Definition at line 152 of file TDetectorHit.h.
References fAddress, fChannel, TChannel::GetChannel(), IsChannelSet(), kIsChannelSet, and SetHitBit().
Referenced by GetCharge(), GetCrystal(), GetDetector(), GetEnergy(), GetEnergyNonlinearity(), GetName(), GetSegment(), GetTime(), GetTimeStampNs(), GetTimeStampUnit(), TFragment::GetTZero(), and TFragment::Print().
GetChannelNumber()
Short_t TDetectorHit::GetChannelNumber () const virtual
!
Definition at line 224 of file TDetectorHit.cxx.
References fAddress, TChannel::GetChannel(), and TChannel::GetNumber().
Referenced by ExampleFragmentHelper::Exec(), and ExampleFragmentSelector::FillHistograms().
GetCharge()
Float_t TDetectorHit::GetCharge () const virtual
!
Definition at line 69 of file TDetectorHit.cxx.
References Charge(), fKValue, GetChannel(), TChannel::GetIntegration(), and TChannel::UseCalFileIntegration().
Referenced by ExampleFragmentHelper::Exec(), ExampleFragmentSelector::FillHistograms(), and TFragment::Print().
GetCrystal()
Int_t TDetectorHit::GetCrystal () const virtual
!
Definition at line 210 of file TDetectorHit.cxx.
References GetChannel(), and TChannel::GetCrystalNumber().
Referenced by TBgoHit::GetArrayNumber().
GetCycleTimeStamp()
Long64_t TDetectorHit::GetCycleTimeStamp () const
Definition at line 267 of file TDetectorHit.cxx.
References fCycleTimeStamp, fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), GetTimeStampNs(), IsPPGSet(), kIsPPGSet, and SetHitBit().
GetDetector()
Int_t TDetectorHit::GetDetector () const virtual
!
Definition at line 192 of file TDetectorHit.cxx.
References GetChannel(), and TChannel::GetDetectorNumber().
Referenced by GetArrayNumber(), and TBgoHit::GetArrayNumber().
GetEnergy()
double TDetectorHit::GetEnergy (Option_t * opt = "") const virtual
Definition at line 84 of file TDetectorHit.cxx.
References TChannel::CalibrateENG(), Charge(), fEnergy, fKValue, GetChannel(), GetEnergyNonlinearity(), kIsEnergySet, SetEnergy(), TestHitBit(), and TChannel::UseCalFileIntegration().
Referenced by CompareEnergy(), ExampleFragmentHelper::Exec(), GriffinKValueHelper::Exec(), ExampleFragmentSelector::FillHistograms(), GriffinKValueSelector::FillHistograms(), GetTime(), TFragment::GetTZero(), and operator<().
GetEnergyNonlinearity()
Double_t TDetectorHit::GetEnergyNonlinearity (double energy) const virtual
Definition at line 107 of file TDetectorHit.cxx.
References GetChannel(), and TChannel::GetEnergyNonlinearity().
Referenced by GetEnergy().
GetKValue()
virtual Short_t TDetectorHit::GetKValue () const inline virtual
!
Definition at line 150 of file TDetectorHit.h.
References fKValue.
Referenced by GriffinKValueHelper::Exec(), and GriffinKValueSelector::FillHistograms().
GetName()
const char * TDetectorHit::GetName () const override
!
Definition at line 166 of file TDetectorHit.cxx.
References GetChannel().
Referenced by TFragment::IsDetector(), and Print().
GetPosition() [1/2]
virtual TVector3 TDetectorHit::GetPosition () const inline virtual
!
Definition at line 139 of file TDetectorHit.h.
GetPosition() [2/2]
virtual TVector3 TDetectorHit::GetPosition (Double_t) const inline virtual
!
Definition at line 138 of file TDetectorHit.h.
References GetPosition().
Referenced by GetPosition().
GetPPGStatus()
EPpgPattern TDetectorHit::GetPPGStatus () const
Definition at line 251 of file TDetectorHit.cxx.
References fCycleTimeStamp, fPPGStatus, TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), TPPG::GetStatus(), GetTimeStampNs(), IsPPGSet(), kIsPPGSet, kJunk, and SetHitBit().
GetSegment()
Int_t TDetectorHit::GetSegment () const virtual
!
Definition at line 201 of file TDetectorHit.cxx.
References GetChannel(), and TChannel::GetSegmentNumber().
Referenced by TBgoHit::GetArrayNumber().
GetTime()
Double_t TDetectorHit::GetTime (const ETimeFlag & correct_flag = ETimeFlag::kAll, Option_t * opt = "") const virtual
Returns a time value to the nearest nanosecond!
Definition at line 56 of file TDetectorHit.cxx.
References fTime, GetCfd(), GetChannel(), GetEnergy(), TChannel::GetTime(), GetTimeStamp(), IsTimeSet(), and SetTime().
Referenced by GetTimeSinceTapeMove(), and Print().
GetTimeSinceTapeMove()
double TDetectorHit::GetTimeSinceTapeMove () const
returns time in ns, minus the time of the last tape move
Definition at line 283 of file TDetectorHit.cxx.
References TSingleton< TPPG >::Get(), TPPG::GetLastStatusTime(), GetTime(), GetTimeStampNs(), and kTapeMove.
GetTimeStamp()
virtual Long64_t TDetectorHit::GetTimeStamp (Option_t * = "") const inline virtual
Definition at line 142 of file TDetectorHit.h.
References fTimeStamp.
Referenced by GetTime(), GetTimeStampNs(), TFragment::operator<(), TFragment::operator>(), Print(), and TFragment::Print().
GetTimeStampNs()
Long64_t TDetectorHit::GetTimeStampNs (Option_t * opt = "") const virtual
Definition at line 233 of file TDetectorHit.cxx.
References GetChannel(), TChannel::GetTimeDrift(), TChannel::GetTimeOffset(), GetTimeStamp(), and GetTimeStampUnit().
Referenced by TFragment::GetCycleNumber(), GetCycleTimeStamp(), GetPPGStatus(), TFragment::GetTimeInCycle(), GetTimeSinceTapeMove(), and Print().
GetTimeStampUnit()
Int_t TDetectorHit::GetTimeStampUnit () const virtual
!
Definition at line 242 of file TDetectorHit.cxx.
References GetChannel(), and TChannel::GetTimeStampUnit().
Referenced by GetTimeStampNs(), and Print().
GetWaveform()
const std::vector< Short_t > * TDetectorHit::GetWaveform () const inline
!
Definition at line 151 of file TDetectorHit.h.
References fWaveform.
Referenced by TPulseAnalyzer::SetData().
HasWave()
virtual bool TDetectorHit::HasWave () const inline virtual
!
Definition at line 107 of file TDetectorHit.h.
References fWaveform.
Referenced by TFragment::Print(), and TPulseAnalyzer::SetData().
IsChannelSet()
Bool_t TDetectorHit::IsChannelSet () const inline protected
Definition at line 195 of file TDetectorHit.h.
References fBitFlags, kIsChannelSet, and TTransientBits< T >::TestBit().
Referenced by GetChannel().
IsEnergySet()
Bool_t TDetectorHit::IsEnergySet () const inline protected
Definition at line 194 of file TDetectorHit.h.
References fBitFlags, kIsEnergySet, and TTransientBits< T >::TestBit().
IsPPGSet()
Bool_t TDetectorHit::IsPPGSet () const inline protected
Definition at line 197 of file TDetectorHit.h.
References fBitFlags, kIsPPGSet, and TTransientBits< T >::TestBit().
Referenced by GetCycleTimeStamp(), and GetPPGStatus().
IsTimeSet()
Bool_t TDetectorHit::IsTimeSet () const inline protected
Definition at line 196 of file TDetectorHit.h.
References fBitFlags, kIsTimeSet, and TTransientBits< T >::TestBit().
Referenced by GetTime().
operator<()
bool TDetectorHit::operator< (const TDetectorHit & rhs) const inline
Definition at line 93 of file TDetectorHit.h.
References GetEnergy().
operator=()
TDetectorHit & TDetectorHit::operator= (const TDetectorHit &) default
Print() [1/2]
void TDetectorHit::Print (Option_t * opt = "") const override
!
General print statement for a TDetectorHit.
Definition at line 147 of file TDetectorHit.cxx.
References Print().
Referenced by Print(), and TBgoHit::Print().
Print() [2/2]
void TDetectorHit::Print (std::ostream & out) const virtual
Print detector hit to stream out.
Reimplemented in TBgoHit, and TFragment.
Definition at line 153 of file TDetectorHit.cxx.
References Charge(), GetName(), GetTime(), GetTimeStamp(), GetTimeStampNs(), and GetTimeStampUnit().
SetAddress()
void TDetectorHit::SetAddress (const UInt_t & temp_address) inline
!
Definition at line 113 of file TDetectorHit.h.
References fAddress.
SetCfd() [1/3]
virtual void TDetectorHit::SetCfd (const Float_t & x) inline virtual
!
Definition at line 117 of file TDetectorHit.h.
References fCfd.
SetCfd() [2/3]
virtual void TDetectorHit::SetCfd (const Int_t & x) inline virtual
! this function automatically randomizes the integer provided
Definition at line 119 of file TDetectorHit.h.
References fCfd.
SetCfd() [3/3]
virtual void TDetectorHit::SetCfd (const uint32_t & x) inline virtual
! this function automatically randomizes the integer provided
Definition at line 118 of file TDetectorHit.h.
References fCfd.
SetCharge() [1/2]
void TDetectorHit::SetCharge (const Float_t & temp_charge) inline
!
Definition at line 115 of file TDetectorHit.h.
References fCharge.
SetCharge() [2/2]
void TDetectorHit::SetCharge (const Int_t & temp_charge) inline
! this function automatically randomizes the integer provided
Definition at line 116 of file TDetectorHit.h.
References fCharge.
SetEnergy()
Double_t TDetectorHit::SetEnergy (const double & en) const inline
Definition at line 125 of file TDetectorHit.h.
References fEnergy, kIsEnergySet, and SetHitBit().
Referenced by GetEnergy().
SetHitBit()
void TDetectorHit::SetHitBit (EBitFlag flag, Bool_t set = true) const
Definition at line 290 of file TDetectorHit.cxx.
References fBitFlags, and TTransientBits< T >::SetBit().
Referenced by ClearChannel(), ClearEnergy(), GetChannel(), GetCycleTimeStamp(), GetPPGStatus(), SetEnergy(), and SetTime().
SetKValue()
void TDetectorHit::SetKValue (const Short_t & temp_kval) inline
!
Definition at line 114 of file TDetectorHit.h.
References fKValue.
SetTime()
Double_t TDetectorHit::SetTime (const Double_t & time) const inline
Definition at line 131 of file TDetectorHit.h.
References fTime, kIsTimeSet, and SetHitBit().
Referenced by GetTime().
SetTimeStamp()
virtual void TDetectorHit::SetTimeStamp (const Long64_t & x) inline virtual
!
Definition at line 122 of file TDetectorHit.h.
References fTimeStamp.
SetWaveform()
void TDetectorHit::SetWaveform (const std::vector< Short_t > & x) inline
!
Definition at line 120 of file TDetectorHit.h.
References fWaveform.
TestHitBit()
bool TDetectorHit::TestHitBit (EBitFlag flag) const inline
Definition at line 201 of file TDetectorHit.h.
References fBitFlags, and TTransientBits< T >::TestBit().
Referenced by GetEnergy().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const TDetectorHit & hit) friend
Definition at line 103 of file TDetectorHit.h.
Member Data Documentation
fAddress
UInt_t TDetectorHit::fAddress {0} protected
address of the the channel in the DAQ.
Definition at line 204 of file TDetectorHit.h.
Referenced by TDetectorHit(), Clear(), Copy(), GetAddress(), GetChannel(), GetChannelNumber(), TFragment::GetSharcMesyBoard(), and SetAddress().
fBeamDirection
TVector3 TDetectorHit::fBeamDirection static protected
Definition at line 223 of file TDetectorHit.h.
Referenced by GetBeamDirection().
fBitFlags
TTransientBits<UChar_t> TDetectorHit::fBitFlags mutable protected
Definition at line 222 of file TDetectorHit.h.
Referenced by Clear(), ClearTransients(), Copy(), IsChannelSet(), IsEnergySet(), IsPPGSet(), IsTimeSet(), SetHitBit(), and TestHitBit().
fCfd
Float_t TDetectorHit::fCfd {0} protected
CFD time of the Hit.
Definition at line 207 of file TDetectorHit.h.
Referenced by Clear(), Copy(), GetCfd(), SetCfd(), SetCfd(), and SetCfd().
fChannel
TChannel* TDetectorHit::fChannel {nullptr} mutable private
!
Definition at line 217 of file TDetectorHit.h.
Referenced by Clear(), ClearChannel(), Copy(), and GetChannel().
fCharge
Float_t TDetectorHit::fCharge {0.} protected
charge collected from the hit
Definition at line 205 of file TDetectorHit.h.
Referenced by Charge(), Clear(), Copy(), SetCharge(), and SetCharge().
fCycleTimeStamp
Long64_t TDetectorHit::fCycleTimeStamp {0} mutable private
!
Definition at line 216 of file TDetectorHit.h.
Referenced by Clear(), Copy(), GetCycleTimeStamp(), and GetPPGStatus().
fEnergy
Double_t TDetectorHit::fEnergy {0.} mutable private
! Energy of the Hit.
Definition at line 213 of file TDetectorHit.h.
Referenced by Clear(), ClearEnergy(), Copy(), GetEnergy(), and SetEnergy().
fKValue
Short_t TDetectorHit::fKValue {0} protected
integration value.
Definition at line 206 of file TDetectorHit.h.
Referenced by Clear(), Copy(), GetCharge(), GetEnergy(), GetKValue(), and SetKValue().
fPPGStatus
EPpgPattern TDetectorHit::fPPGStatus {EPpgPattern::kJunk} mutable private
!
Definition at line 214 of file TDetectorHit.h.
Referenced by Clear(), Copy(), GetCycleTimeStamp(), and GetPPGStatus().
fTime
Double_t TDetectorHit::fTime {0.} mutable protected
! Calibrated Time of the hit
Definition at line 210 of file TDetectorHit.h.
Referenced by Clear(), Copy(), GetTime(), and SetTime().
fTimeStamp
Long64_t TDetectorHit::fTimeStamp {0} protected
Timestamp given to hit in ns.
Definition at line 208 of file TDetectorHit.h.
Referenced by AppendTimeStamp(), Clear(), Copy(), GetTimeStamp(), and SetTimeStamp().
fWaveform
std::vector<Short_t> TDetectorHit::fWaveform protected
Definition at line 209 of file TDetectorHit.h.
Referenced by AddWaveformSample(), Clear(), CopyWave(), GetWaveform(), HasWave(), and SetWaveform().
GRSISort () Reference Guide Generated on Thu May 9 2024 20:43:27.