GRSISort: GRootContainer Class Reference
GRootContainer Class Reference
Detailed Description
Utility class used by GRootCanvas. The GRootContainer is the frame embedded in the TGCanvas widget. The ROOT graphics goes into this frame. This class is used to enable input events on this graphics frame and forward the events to the GRootCanvas handlers.
Definition at line 199 of file GRootCanvas.cxx.
Public Member Functions
GRootContainer (GRootCanvas *c, Window_t id, const TGWindow *p)
Bool_t HandleButton (Event_t *event) override
Bool_t HandleConfigureNotify (Event_t *ev) override
Bool_t HandleCrossing (Event_t *ev) override
Bool_t HandleDoubleClick (Event_t *ev) override
Bool_t HandleExpose (Event_t *ev) override
Bool_t HandleKey (Event_t *ev) override
Bool_t HandleMotion (Event_t *ev) override
void SavePrimitive (std::ostream &out, Option_t *="") override
void SetEditable (Bool_t) override
Private Attributes
GRootCanvas * fCanvas
Constructor & Destructor Documentation
GRootContainer()
GRootContainer::GRootContainer (GRootCanvas * c, Window_t id, const TGWindow * p)
Create a canvas container.
Definition at line 221 of file GRootCanvas.cxx.
Member Function Documentation
HandleButton()
Bool_t GRootContainer::HandleButton (Event_t * event) override
Directly handle scroll mouse buttons (4 and 5), only pass buttons 1, 2 and 3 on to the TCanvas.
Definition at line 232 of file GRootCanvas.cxx.
References fCanvas, GRootCanvas::fCanvasWindow, and GRootCanvas::HandleContainerButton().
HandleConfigureNotify()
Bool_t GRootContainer::HandleConfigureNotify (Event_t * ev) inline override
Definition at line 207 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerConfigure().
HandleCrossing()
Bool_t GRootContainer::HandleCrossing (Event_t * ev) inline override
Definition at line 215 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerCrossing().
HandleDoubleClick()
Bool_t GRootContainer::HandleDoubleClick (Event_t * ev) inline override
Definition at line 206 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerDoubleClick().
HandleExpose()
Bool_t GRootContainer::HandleExpose (Event_t * ev) inline override
Definition at line 214 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerExpose().
HandleKey()
Bool_t GRootContainer::HandleKey (Event_t * ev) inline override
Definition at line 212 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerKey().
HandleMotion()
Bool_t GRootContainer::HandleMotion (Event_t * ev) inline override
Definition at line 213 of file GRootCanvas.cxx.
References fCanvas, and GRootCanvas::HandleContainerMotion().
SavePrimitive()
void GRootContainer::SavePrimitive (std::ostream & out, Option_t * = "") override
Save a canvas container as a C++ statement(s) on output stream out.
Definition at line 2009 of file GRootCanvas.cxx.
SetEditable()
void GRootContainer::SetEditable (Bool_t) inline override
Definition at line 217 of file GRootCanvas.cxx.
Member Data Documentation
fCanvas
GRootCanvas* GRootContainer::fCanvas private
Definition at line 201 of file GRootCanvas.cxx.
Referenced by HandleButton(), HandleConfigureNotify(), HandleCrossing(), HandleDoubleClick(), HandleExpose(), HandleKey(), and HandleMotion().