GRSISort: TGRSIFrame Class Reference
TGRSIFrame Class Reference
Framing
Detailed Description
This class fills the input list with TPPG, run info, analysis options, user settings, etc. Creating it also triggers the compilation of the user helper if necessary. It also provides the infrastructure for running the helper and writing the output file.
Definition at line 36 of file TGRSIFrame.h.
Public Member Functions
TGRSIFrame ()
void Run (TRedirect *&redirect)
Private Attributes
ROOT::RDataFrame * fDataFrame {nullptr}
TGRSIOptions * fOptions {nullptr}
ROOT::RDF::RResultPtr< std::map< std::string, TList > > fOutput
std::string fOutputPrefix {"default"}
TPPG * fPpg {nullptr}
Long64_t fTotalEntries {0}
ROOT::Experimental::RLogScopedVerbosity * fVerbosity {nullptr}
Constructor & Destructor Documentation
TGRSIFrame()
TGRSIFrame::TGRSIFrame ()
Try to load an external library with the correct function in it. If that library does not exist, try to compile it. To handle all that we use the class TDataFrameLibrary (very similar to TParserLibrary)
Definition at line 19 of file TGRSIFrame.cxx.
References TPPG::Add(), TSingleton< TRunInfo >::AddCurrent(), TGRSIOptions::AnalysisOptions(), TGRSIOptions::CalInputFiles(), TDataFrameLibrary::CreateHelper(), TGRSIOptions::Debug(), fDataFrame, fOptions, fOutput, fOutputPrefix, fPpg, fTotalEntries, fVerbosity, TSingleton< TDataFrameLibrary >::Get(), TSingleton< TRunInfo >::Get(), TGRSIOptions::GetMaxWorkers(), TGRSIOptions::InputCutFiles(), TGRSIHelper::Prefix(), TPPG::Print(), TRunInfo::Print(), TChannel::ReadCalFromFile(), TRunInfo::ReadInfoFromFile(), TGRSIOptions::RootInputFiles(), TGRSIOptions::TreeName(), TGRSIOptions::UserSettings(), and TGRSIOptions::ValInputFiles().
Member Function Documentation
Run()
void TGRSIFrame::Run (TRedirect *& redirect)
Definition at line 114 of file TGRSIFrame.cxx.
References TGRSIOptions::AnalysisOptions(), TRunInfo::CreateLabel(), TGRSIOptions::Debug(), TGRSIMapException< key_type >::detail(), DRED, TRedirect::ErrFile(), fDataFrame, fOptions, fOutput, fOutputPrefix, fPpg, fTotalEntries, TSingleton< TRunInfo >::Get(), TRedirect::OutFile(), RESET_COLOR, TGRSIOptions::UserSettings(), TPPG::Write(), TAnalysisOptions::WriteToFile(), and TChannel::WriteToRoot().
Member Data Documentation
fDataFrame
ROOT::RDataFrame* TGRSIFrame::fDataFrame {nullptr} private
Definition at line 49 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fOptions
TGRSIOptions* TGRSIFrame::fOptions {nullptr} private
Definition at line 46 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fOutput
ROOT::RDF::RResultPtr<std::map<std::string, TList> > TGRSIFrame::fOutput private
Definition at line 44 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fOutputPrefix
std::string TGRSIFrame::fOutputPrefix {"default"} private
Definition at line 43 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fPpg
TPPG* TGRSIFrame::fPpg {nullptr} private
Definition at line 47 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fTotalEntries
Long64_t TGRSIFrame::fTotalEntries {0} private
Definition at line 50 of file TGRSIFrame.h.
Referenced by TGRSIFrame(), and Run().
fVerbosity
ROOT::Experimental::RLogScopedVerbosity* TGRSIFrame::fVerbosity {nullptr} private
Definition at line 53 of file TGRSIFrame.h.
Referenced by TGRSIFrame().