GRSISort: TChannel Class Reference
TChannel Class Reference
Sorting
Detailed Description
The TChannel is designed to hold all non-essential information of a TFragment (now the same as a hit; name, energy coeff, etc..) that would otherwise clog up the FragmentTree. The TChannel class contains a static map to every channel make retrieval fairly easy. The TChannel class also contains the ability to read and write a custom calibration file to set or save the TChannel information. Most of the information is read out of the ODB information in the MIDAS file.
Definition at line 50 of file TChannel.h.
Classes
struct WaveFormShapePar
Public Member Functions
TChannel ()
TChannel (const char *)
TChannel (const TChannel &)
TChannel (TChannel &&) noexcept
TChannel (TChannel *)
~TChannel ()
void AddCFDCoefficient (double temp)
void AddCTCoefficient (double temp)
void AddEFFCoefficient (double temp)
void AddEnergyNonlinearityPoint (double x, double y)
void AddENGCoefficient (Float_t temp, size_t range=0)
void AddENGDriftCoefficent (Float_t temp)
void AddLEDCoefficient (double temp)
void AddTIMECoefficient (double temp)
double CalibrateCFD (double) const
double CalibrateCFD (int) const
double CalibrateEFF (double) const
double CalibrateENG (double) const
double CalibrateENG (double, int temp_int) const
double CalibrateENG (int, int temp_int=0) const
double CalibrateLED (double) const
double CalibrateLED (int) const
double CalibrateTIME (double) const
double CalibrateTIME (int) const
void Clear (Option_t *opt="") override
void DestroyCalibrations ()
void DestroyCFDCal ()
void DestroyCTCal ()
void DestroyEFFCal ()
void DestroyEnergyNonlinearity ()
void DestroyENGCal ()
void DestroyLEDCal ()
void DestroyTIMECal ()
unsigned int GetAddress () const
std::vector< double > GetAllENGChi2 () const
std::vector< std::vector< Float_t > > GetAllENGCoeff () const
double GetCFDChi2 () const
std::vector< double > GetCFDCoeff () const
TClass * GetClassType () const
int GetCrystalNumber () const
std::vector< double > GetCTCoeff () const
int GetDetectorNumber () const
EDigitizer GetDigitizerType () const
const char * GetDigitizerTypeString () const
double GetEFFChi2 () const
std::vector< double > GetEFFCoeff () const
TGraph GetEnergyNonlinearity () const
double GetEnergyNonlinearity (double eng) const
double GetENGChi2 (size_t range=0) const
std::vector< Float_t > GetENGCoeff (size_t range=0) const
std::vector< Float_t > GetENGDriftCoefficents () const
std::pair< double, double > GetENGRange (size_t range) const
std::vector< std::pair< double, double > > GetENGRanges () const
int GetIntegration () const
double GetLEDChi2 () const
std::vector< double > GetLEDCoeff () const
const TMnemonic * GetMnemonic () const
int GetNumber () const
int GetSegmentNumber () const
int GetStream () const
double GetTime (Long64_t timestamp, Float_t cfd, double energy) const
double GetTIMEChi2 () const
std::vector< double > GetTIMECoeff () const
double GetTimeDrift () const
Long64_t GetTimeOffset () const
int GetTimeStampUnit () const
double GetTZero (double tempd) const
double GetTZero (int tempi) const
double GetWaveBaseLine () const
double GetWaveDecay () const
WaveFormShapePar GetWaveParam () const
double GetWaveRise () const
TChannel & operator= (const TChannel &rhs)
TChannel & operator= (TChannel &&) noexcept
void Print (Option_t *opt="") const override
void PrintCTCoeffs (Option_t *opt="") const
std::string PrintCTToString (Option_t *opt="") const
std::string PrintToString (Option_t *opt="") const
void ResizeENG (size_t size)
void SetAddress (unsigned int tmpadd)
void SetAllENGChi2 (const TPriorityValue< std::vector< double > > &tmp)
void SetAllENGCoefficients (const TPriorityValue< std::vector< std::vector< Float_t > > > &tmp)
void SetCFDChi2 (const TPriorityValue< double > &tmp)
void SetCFDCoefficients (const TPriorityValue< std::vector< double > > &tmp)
void SetClassType (TClass *cl_type)
void SetCrystalNumber (int tempint)
void SetCTCoefficients (const TPriorityValue< std::vector< double > > &tmp)
void SetDetectorNumber (int tempint)
void SetDigitizerType (const TPriorityValue< std::string > &tmp)
void SetEFFChi2 (const TPriorityValue< double > &tmp)
void SetEFFCoefficients (const TPriorityValue< std::vector< double > > &tmp)
void SetEnergyNonlinearity (const TPriorityValue< TGraph > &tmp)
void SetENGChi2 (const TPriorityValue< double > &tmp, const size_t &range=0)
void SetENGCoefficients (const std::vector< Float_t > &tmp, size_t range=0)
void SetENGDriftCoefficents (const TPriorityValue< std::vector< Float_t > > &tmp)
void SetENGRange (const std::pair< double, double > &tmp, const size_t &range)
void SetENGRanges (const TPriorityValue< std::vector< std::pair< double, double > > > &tmp)
void SetIntegration (const TPriorityValue< int > &tmp)
void SetLEDChi2 (const TPriorityValue< double > &tmp)
void SetLEDCoefficients (const TPriorityValue< std::vector< double > > &tmp)
void SetName (const char *tmpName) override
void SetNumber (const TPriorityValue< int > &tmp)
void SetSegmentNumber (int tempint)
void SetStream (const TPriorityValue< int > &tmp)
void SetTIMEChi2 (const TPriorityValue< double > &tmp)
void SetTIMECoefficients (const TPriorityValue< std::vector< double > > &tmp)
void SetTimeDrift (const TPriorityValue< double > &tmp)
void SetTimeOffset (const TPriorityValue< Long64_t > &tmp)
void SetUseCalFileIntegration (const TPriorityValue< bool > &tmp=TPriorityValue< bool >(true, EPriority::kUser))
void SetUseWaveParam (bool temp=true)
void SetWaveBaseLine (double temp)
void SetWaveDecay (const double &temp)
void SetWaveParam (WaveFormShapePar temp)
void SetWaveRise (const double &temp)
bool UseCalFileIntegration ()
bool UseWaveParam () const
Static Public Member Functions
static void AddChannel (TChannel *, Option_t *opt="")
static bool CompareChannels (const TChannel *, const TChannel *)
static void DeleteAllChannels ()
static TChannel * FindChannelByName (const char *ccName)
static std::vector< TChannel * > FindChannelByRegEx (const char *ccName)
static TChannel * GetChannel (unsigned int temp_address, bool warn=false)
static TChannel * GetChannelByNumber (int temp_num)
static std::unordered_map< unsigned int, TChannel * > * GetChannelMap ()
static TChannel * GetDefaultChannel ()
static std::unordered_map< unsigned int, int > * GetMissingChannelMap ()
static TClassRef GetMnemonicClass ()
static size_t GetNumberOfChannels ()
static Int_t ParseInputData (const char *inputdata="", Option_t *opt="", EPriority prio=EPriority::kUser)
static Int_t ReadCalFile (const char *filename="")
static Int_t ReadCalFile (std::ifstream &infile)
static Int_t ReadCalFromCurrentFile (Option_t *opt="overwrite")
static Int_t ReadCalFromFile (TFile *tempf, Option_t *opt="overwrite")
static Int_t ReadCalFromTree (TTree *, Option_t *opt="overwrite")
static void ReadEnergyNonlinearities (TFile *, const char *graphName="EnergyNonlinearity0x", bool all=false)
static void SetDigitizerType (const std::string &mnemonic, const char *tmpstr, EPriority prio)
static void SetIntegration (const std::string &mnemonic, int tmpint, EPriority pr)
static void SetMnemonicClass (const TClassRef &cls)
static void SetUseCalFileIntegration (const std::string &mnemonic, bool flag, EPriority pr)
static int UpdateChannel (TChannel *, Option_t *opt="")
static void WriteCalBuffer (Option_t *opt="")
static void WriteCalFile (const std::string &outfilename="")
static void WriteCTCorrections (const std::string &outfilename="")
static int WriteToRoot (TFile *fileptr=nullptr)
Private Member Functions
void AppendChannel (TChannel *)
void OverWriteChannel (TChannel *)
void SetupEnergyNonlinearity ()
Static Private Member Functions
static void InitChannelInput ()
static Int_t ReadFile (TFile *tempf)
static void SaveToSelf ()
static void SaveToSelf (const char *)
static std::vector< TChannel * > SortedChannels ()
Private Attributes
unsigned int fAddress {0}
TPriorityValue< double > fCFDChi2
TPriorityValue< std::vector< double > > fCFDCoefficients
int fCrystalNumber {-1}
TPriorityValue< std::vector< double > > fCTCoefficients
int fDetectorNumber {-1}
TPriorityValue< EDigitizer > fDigitizerType
TPriorityValue< std::string > fDigitizerTypeString
TPriorityValue< double > fEFFChi2
TPriorityValue< std::vector< double > > fEFFCoefficients
TPriorityValue< TGraph > fEnergyNonlinearity
TPriorityValue< std::vector< double > > fENGChi2
TPriorityValue< std::vector< std::vector< Float_t > > > fENGCoefficients
TPriorityValue< std::vector< Float_t > > fENGDriftCoefficents
TPriorityValue< std::vector< std::pair< double, double > > > fENGRanges
TPriorityValue< int > fIntegration {1}
TPriorityValue< double > fLEDChi2
TPriorityValue< std::vector< double > > fLEDCoefficients
TPriorityValue< TMnemonic * > fMnemonic
TPriorityValue< int > fNumber {0}
int fSegmentNumber {-1}
TPriorityValue< int > fStream {0}
TPriorityValue< double > fTIMEChi2
TPriorityValue< std::vector< double > > fTIMECoefficients
TPriorityValue< double > fTimeDrift
TPriorityValue< Long64_t > fTimeOffset
TPriorityValue< int > fTimeStampUnit {0}
TPriorityValue< bool > fUseCalFileInt {false}
WaveFormShapePar WaveFormShape {}
Static Private Attributes
static std::unordered_map< unsigned int, TChannel * > * fChannelMap = new std::unordered_map<unsigned int, TChannel*>
static std::unordered_map< int, TChannel * > * fChannelNumberMap = new std::unordered_map<int, TChannel*>
static std::string fFileData
static std::unordered_map< unsigned int, int > * fMissingChannelMap = new std::unordered_map<unsigned int, int>
static TClassRef fMnemonicClass = TClassRef("TMnemonic")
Constructor & Destructor Documentation
TChannel() [1/5]
TChannel::TChannel ()
Definition at line 42 of file TChannel.cxx.
References Clear().
Referenced by ParseInputData(), and ReadEnergyNonlinearities().
TChannel() [2/5]
TChannel::TChannel (const char * tempName) explicit
Definition at line 49 of file TChannel.cxx.
References Clear(), and SetName().
TChannel() [3/5]
TChannel::TChannel (TChannel * chan) explicit
Makes a copy of a the TChannel.
Definition at line 129 of file TChannel.cxx.
References Clear(), fCFDChi2, fCFDCoefficients, fCTCoefficients, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fLEDChi2, fLEDCoefficients, fMnemonic, fNumber, fStream, fTIMEChi2, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, GetAddress(), GetClassType(), GetCrystalNumber(), GetDetectorNumber(), GetSegmentNumber(), GetWaveParam(), SetAddress(), SetAllENGChi2(), SetAllENGCoefficients(), SetCFDChi2(), SetCFDCoefficients(), SetClassType(), SetCrystalNumber(), SetCTCoefficients(), SetDetectorNumber(), SetDigitizerType(), SetEFFChi2(), SetEFFCoefficients(), SetEnergyNonlinearity(), SetENGDriftCoefficents(), SetENGRanges(), SetIntegration(), SetLEDChi2(), SetLEDCoefficients(), SetName(), SetNumber(), SetSegmentNumber(), SetStream(), SetTIMEChi2(), SetTIMECoefficients(), SetTimeDrift(), SetTimeOffset(), SetUseCalFileIntegration(), SetWaveParam(), and TPriorityValue< T >::Value().
TChannel() [4/5]
TChannel::TChannel (const TChannel & chan)
Makes a copy of a the TChannel.
Definition at line 56 of file TChannel.cxx.
References Clear(), fCFDChi2, fCFDCoefficients, fCTCoefficients, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fLEDChi2, fLEDCoefficients, fMnemonic, fNumber, fStream, fTIMEChi2, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, GetAddress(), GetClassType(), GetCrystalNumber(), GetDetectorNumber(), GetSegmentNumber(), GetWaveParam(), SetAddress(), SetAllENGChi2(), SetAllENGCoefficients(), SetCFDChi2(), SetCFDCoefficients(), SetClassType(), SetCrystalNumber(), SetCTCoefficients(), SetDetectorNumber(), SetDigitizerType(), SetEFFChi2(), SetEFFCoefficients(), SetEnergyNonlinearity(), SetENGDriftCoefficents(), SetENGRanges(), SetIntegration(), SetLEDChi2(), SetLEDCoefficients(), SetName(), SetNumber(), SetSegmentNumber(), SetStream(), SetTIMEChi2(), SetTIMECoefficients(), SetTimeDrift(), SetTimeOffset(), SetUseCalFileIntegration(), SetWaveParam(), and TPriorityValue< T >::Value().
TChannel() [5/5]
TChannel::TChannel (TChannel && chan) noexcept
Moves chan to this. Just a copy of the copy constructor right now, needs to be changed.
Definition at line 92 of file TChannel.cxx.
~TChannel()
TChannel::~TChannel () default
Member Function Documentation
AddCFDCoefficient()
void TChannel::AddCFDCoefficient (double temp) inline
Definition at line 210 of file TChannel.h.
References fCFDCoefficients.
Referenced by ParseInputData(), and TCFDCal::WriteToChannel().
AddChannel()
void TChannel::AddChannel (TChannel * chan, Option_t * opt = "") static
Add a TChannel to fChannelMap. If the TChannel doesn't exist, create a new TChannel and add that the fChannelMap. Options: "overwrite" - The TChannel in the fChannelMap at the same address is overwritten. If this option is not specified, an Error is returned if the TChannel already exists in the fChannelMap. "save" - The temporary channel is not deleted after being placed in the map.
Definition at line 285 of file TChannel.cxx.
References fChannelMap, fChannelNumberMap, GetAddress(), GetChannel(), GetNumber(), and OverWriteChannel().
Referenced by main(), TLstFile::ParseHeaders(), ParseInputData(), ReadEnergyNonlinearities(), TMidasFile::SetGRIFFOdb(), and TMidasFile::SetTIGOdb().
AddCTCoefficient()
void TChannel::AddCTCoefficient (double temp) inline
Definition at line 214 of file TChannel.h.
References fCTCoefficients.
Referenced by CrossTalkFix(), main(), and ParseInputData().
AddEFFCoefficient()
void TChannel::AddEFFCoefficient (double temp) inline
Definition at line 213 of file TChannel.h.
References fEFFCoefficients.
Referenced by ParseInputData().
AddEnergyNonlinearityPoint()
void TChannel::AddEnergyNonlinearityPoint (double x, double y) inline
Definition at line 215 of file TChannel.h.
References TPriorityValue< T >::Address(), and fEnergyNonlinearity.
Referenced by ParseInputData(), and TChannelTab::UpdateChannel().
AddENGCoefficient()
void TChannel::AddENGCoefficient (Float_t temp, size_t range = 0) inline
Definition at line 204 of file TChannel.h.
References fENGCoefficients.
Referenced by ParseInputData(), TMidasFile::SetGRIFFOdb(), TMidasFile::SetTIGDAQOdb(), TMidasFile::SetTIGOdb(), TEnergyCal::WriteToChannel(), and TGainMatch::WriteToChannel().
AddENGDriftCoefficent()
void TChannel::AddENGDriftCoefficent (Float_t temp) inline
Definition at line 209 of file TChannel.h.
References fENGDriftCoefficents.
Referenced by main(), and ParseInputData().
AddLEDCoefficient()
void TChannel::AddLEDCoefficient (double temp) inline
Definition at line 211 of file TChannel.h.
References fLEDCoefficients.
Referenced by ParseInputData().
AddTIMECoefficient()
void TChannel::AddTIMECoefficient (double temp) inline
Definition at line 212 of file TChannel.h.
References fTIMECoefficients.
Referenced by ParseInputData(), and TTimeCal::WriteToChannel().
AppendChannel()
void TChannel::AppendChannel (TChannel * chan) private
Sets the current TChannel to chan
Definition at line 365 of file TChannel.cxx.
References fCFDChi2, fCFDCoefficients, fCTCoefficients, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fLEDChi2, fLEDCoefficients, fNumber, fStream, fTIMEChi2, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, GetClassType(), GetCrystalNumber(), GetDetectorNumber(), GetSegmentNumber(), GetWaveParam(), SetAllENGChi2(), SetAllENGCoefficients(), SetCFDChi2(), SetCFDCoefficients(), SetClassType(), SetCrystalNumber(), SetCTCoefficients(), SetDetectorNumber(), SetDigitizerType(), SetEFFChi2(), SetEFFCoefficients(), SetEnergyNonlinearity(), SetENGDriftCoefficents(), SetENGRanges(), SetIntegration(), SetLEDChi2(), SetLEDCoefficients(), SetName(), SetNumber(), SetSegmentNumber(), SetStream(), SetTIMEChi2(), SetTIMECoefficients(), SetTimeDrift(), SetTimeOffset(), SetUseCalFileIntegration(), and SetWaveParam().
Referenced by UpdateChannel().
CalibrateCFD() [1/2]
double TChannel::CalibrateCFD (double cfd) const
Returns the calibrated CFD. The polynomial CFD calibration formula is applied to get the calibrated CFD.
Definition at line 705 of file TChannel.cxx.
References fCFDCoefficients.
Referenced by CalibrateCFD(), TGRSIMnemonic::GetTime(), THILMnemonic::GetTime(), TILLMnemonic::GetTime(), and TTdrMnemonic::GetTime().
CalibrateCFD() [2/2]
double TChannel::CalibrateCFD (int cfd) const
Calibrates the CFD properly.
Definition at line 699 of file TChannel.cxx.
References CalibrateCFD().
CalibrateEFF()
double TChannel::CalibrateEFF (double) const
This needs to be added
Definition at line 770 of file TChannel.cxx.
CalibrateENG() [1/3]
double TChannel::CalibrateENG (double charge) const
Returns the calibrated energy. The polynomial energy calibration formula is applied to get the calibrated energy. This function does not use the integration parameter. If multiple ranges are present, the calibration of the range is used. In overlap regions the range used is chosen randomly.
Definition at line 646 of file TChannel.cxx.
References fENGCoefficients, fENGDriftCoefficents, and fENGRanges.
Referenced by CalibrateENG(), CalibrateENG(), CalibrateTIME(), TDetectorHit::GetEnergy(), TSiLiHit::GetEnergy(), TSiLiHit::GetFitEnergy(), TFippsHit::GetNoCTEnergy(), TGriffinHit::GetNoCTEnergy(), TIfinHit::GetNoCTEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), and TTACHit::GetTempCorrectedEnergy().
CalibrateENG() [2/3]
double TChannel::CalibrateENG (double charge, int temp_int) const
Returns the calibrated energy of the channel when a charge is passed to it. This is divided by the integration parameter. The polynomial energy calibration formula is then applied to get the calibrated energy.
Definition at line 625 of file TChannel.cxx.
References CalibrateENG(), fIntegration, and TPriorityValue< T >::Value().
CalibrateENG() [3/3]
double TChannel::CalibrateENG (int charge, int temp_int = 0) const
Returns the calibrated energy of the channel when a charge is passed to it. This is done by first adding a random number between 0 and 1 to the charge bin. This is then taken and divided by the integration parameter. The polynomial energy calibration formula is then applied to get the calibrated energy.
Definition at line 609 of file TChannel.cxx.
References CalibrateENG().
CalibrateLED() [1/2]
double TChannel::CalibrateLED (double led) const
Returns the calibrated LED. The polynomial LED calibration formula is applied to get the calibrated LED.
Definition at line 730 of file TChannel.cxx.
References fLEDCoefficients.
Referenced by CalibrateLED().
CalibrateLED() [2/2]
double TChannel::CalibrateLED (int led) const
Calibrates the LED
Definition at line 724 of file TChannel.cxx.
References CalibrateLED().
CalibrateTIME() [1/2]
double TChannel::CalibrateTIME (double energy) const
uses the values stored in TIMECOefficients to calculate a "walk correction" factor. This function returns the correction not an adjusted time stamp! pcb.
Definition at line 754 of file TChannel.cxx.
References fTIMECoefficients.
Referenced by CalibrateTIME(), GetTZero(), and GetTZero().
CalibrateTIME() [2/2]
double TChannel::CalibrateTIME (int chg) const
Calibrates the time spectrum
Definition at line 745 of file TChannel.cxx.
References CalibrateENG(), CalibrateTIME(), and fTIMECoefficients.
Clear()
void TChannel::Clear (Option_t * opt = "") override
Clears all fields of a TChannel. There are currently no options to be specified.
Definition at line 421 of file TChannel.cxx.
References fAddress, fCFDChi2, fCFDCoefficients, fCrystalNumber, fCTCoefficients, fDetectorNumber, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fLEDChi2, fLEDCoefficients, fMnemonic, fMnemonicClass, fNumber, fSegmentNumber, fStream, fTIMEChi2, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, kForce, TPriorityValue< T >::Reset(), SetName(), and WaveFormShape.
Referenced by TChannel(), TChannel(), TChannel(), TChannel(), and operator=().
CompareChannels()
bool TChannel::CompareChannels (const TChannel * chana, const TChannel * chanb) static
Compares the names of the two TChannels. Returns true if the name of chana goes lexicographically before the name of chanb.
Definition at line 264 of file TChannel.cxx.
Referenced by SortedChannels().
DeleteAllChannels()
void TChannel::DeleteAllChannels () static
Safely deletes fChannelMap and fChannelNumberMap
Definition at line 273 of file TChannel.cxx.
References fChannelMap, and fChannelNumberMap.
Referenced by main(), TMidasFile::SetFileOdb(), and WriteToRoot().
DestroyCalibrations()
void TChannel::DestroyCalibrations ()
Erases all Cal vectors
Definition at line 598 of file TChannel.cxx.
References DestroyCFDCal(), DestroyCTCal(), DestroyEFFCal(), DestroyENGCal(), DestroyLEDCal(), and DestroyTIMECal().
DestroyCFDCal()
void TChannel::DestroyCFDCal ()
Erases the CFDCoefficients vector
Definition at line 563 of file TChannel.cxx.
References fCFDCoefficients.
Referenced by DestroyCalibrations(), ParseInputData(), and TCFDCal::WriteToChannel().
DestroyCTCal()
void TChannel::DestroyCTCal ()
Definition at line 587 of file TChannel.cxx.
References fCTCoefficients.
Referenced by CrossTalkFix(), DestroyCalibrations(), main(), and ParseInputData().
DestroyEFFCal()
void TChannel::DestroyEFFCal ()
Erases the EffCal vector
Definition at line 581 of file TChannel.cxx.
References fEFFCoefficients.
Referenced by DestroyCalibrations(), and ParseInputData().
DestroyEnergyNonlinearity()
void TChannel::DestroyEnergyNonlinearity ()
Definition at line 593 of file TChannel.cxx.
References TPriorityValue< T >::Address(), and fEnergyNonlinearity.
Referenced by ParseInputData(), and TChannelTab::UpdateChannel().
DestroyENGCal()
void TChannel::DestroyENGCal ()
Erases the ENGCoefficients vector
Definition at line 554 of file TChannel.cxx.
References fENGChi2, fENGCoefficients, fENGDriftCoefficents, and fENGRanges.
Referenced by DestroyCalibrations(), main(), ParseInputData(), TEnergyCal::WriteToChannel(), and TGainMatch::WriteToChannel().
DestroyLEDCal()
void TChannel::DestroyLEDCal ()
Erases the LEDCoefficients vector
Definition at line 569 of file TChannel.cxx.
References fLEDCoefficients.
Referenced by DestroyCalibrations(), and ParseInputData().
DestroyTIMECal()
void TChannel::DestroyTIMECal ()
Erases the TimeCal vector
Definition at line 575 of file TChannel.cxx.
References fTIMECoefficients.
Referenced by DestroyCalibrations(), ParseInputData(), and TTimeCal::WriteToChannel().
FindChannelByName()
TChannel * TChannel::FindChannelByName (const char * ccName) static
Finds the TChannel by the name of the channel
Definition at line 494 of file TChannel.cxx.
References fChannelMap.
Referenced by CrossTalkFix(), TSiLiHit::GetSiLiHitChannel(), and main().
FindChannelByRegEx()
std::vector< TChannel * > TChannel::FindChannelByRegEx (const char * ccName) static
Finds the TChannel by the name of the channel
Definition at line 518 of file TChannel.cxx.
References fChannelMap.
GetAddress()
unsigned int TChannel::GetAddress () const inline
Definition at line 170 of file TChannel.h.
References fAddress.
Referenced by TChannel(), TChannel(), AddChannel(), MakeGRIFFINChargeHsts(), MakeGRIFFINEnergyHsts(), operator=(), OverWriteChannel(), ParseInputData(), and UpdateChannel().
GetAllENGChi2()
std::vector< double > TChannel::GetAllENGChi2 () const inline
Definition at line 180 of file TChannel.h.
References fENGChi2.
Referenced by OverWriteChannel().
GetAllENGCoeff()
std::vector< std::vector< Float_t > > TChannel::GetAllENGCoeff () const inline
Definition at line 191 of file TChannel.h.
References fENGCoefficients.
Referenced by OverWriteChannel().
GetCFDChi2()
double TChannel::GetCFDChi2 () const inline
Definition at line 182 of file TChannel.h.
References fCFDChi2, and TPriorityValue< T >::Value().
Referenced by OverWriteChannel().
GetCFDCoeff()
std::vector< double > TChannel::GetCFDCoeff () const inline
Definition at line 193 of file TChannel.h.
References fCFDCoefficients.
Referenced by OverWriteChannel(), and TCFDCal::ReadFromChannel().
GetChannel()
TChannel * TChannel::GetChannel (unsigned int temp_address, bool warn = false) static
Returns the TChannel at the specified address. If the address doesn't exist, returns an empty gChannel.
Definition at line 459 of file TChannel.cxx.
References StoppableThread::AnyThreadRunning(), fChannelMap, fMissingChannelMap, hex(), RED, and RESET_COLOR.
Referenced by AddChannel(), TUnpackedEvent::Build(), TGRSIDataParser::EmmaMadcDataToFragment(), TDetectorHit::GetChannel(), TDetectorHit::GetChannelNumber(), TGRSIDataParser::GriffinDataToFragment(), TLstFile::ParseHeaders(), ParseInputData(), ReadEnergyNonlinearities(), TMidasFile::SetGRIFFOdb(), TMidasFile::SetTIGDAQOdb(), TMidasFile::SetTIGOdb(), TTdrDataParser::TdrToFragment(), TGRSIDataParser::TigressDataToFragment(), UpdateChannel(), TChannelTab::UpdateChannel(), and TParsingDiagnostics::WriteToFile().
GetChannelByNumber()
TChannel * TChannel::GetChannelByNumber (int temp_num) static
Returns the TChannel based on the channel number and not the channel address.
Definition at line 482 of file TChannel.cxx.
References fChannelNumberMap.
Referenced by TGainMatch::CoarseMatch(), TGainMatch::FineMatch(), TGainMatch::FineMatchFast(), main(), MakeGRIFFINChargeHsts(), MakeGRIFFINEnergyHsts(), and TCal::SetChannel().
GetChannelMap()
static std::unordered_map< unsigned int, TChannel * > * TChannel::GetChannelMap () inline static
Definition at line 72 of file TChannel.h.
References fChannelMap.
Referenced by AlphanumericHelper::CreateHistograms(), AlphanumericSelector::CreateHistograms(), TGRSIDetectorInformation::Set(), THILDetectorInformation::Set(), TILLDetectorInformation::Set(), TTdrDetectorInformation::Set(), SetDigitizerType(), SetIntegration(), SetUseCalFileIntegration(), TGRSISelector::SlaveTerminate(), and TCal::WriteToAllChannels().
GetClassType()
TClass * TChannel::GetClassType () const
Definition at line 1632 of file TChannel.cxx.
References fMnemonic, TMnemonic::GetClassType(), and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), TSortingDiagnostics::AddDetectorClass(), AppendChannel(), TUnpackedEvent::Build(), operator=(), OverWriteChannel(), and PrintToString().
GetCrystalNumber()
int TChannel::GetCrystalNumber () const
Definition at line 1558 of file TChannel.cxx.
References fCrystalNumber, fMnemonic, TMnemonic::NumericArraySubPosition(), and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), TTigress::AddFragment(), AppendChannel(), TDetectorHit::GetCrystal(), operator=(), and OverWriteChannel().
GetCTCoeff()
std::vector< double > TChannel::GetCTCoeff () const inline
Definition at line 197 of file TChannel.h.
References fCTCoefficients.
Referenced by TFipps::CTCorrectedEnergy(), TGriffin::CTCorrectedEnergy(), TIfin::CTCorrectedEnergy(), and OverWriteChannel().
GetDefaultChannel()
TChannel * TChannel::GetDefaultChannel () static
Definition at line 413 of file TChannel.cxx.
References fChannelMap.
Referenced by TAnalysisHistLoop::Write(), TFragHistLoop::Write(), and WriteToRoot().
GetDetectorNumber()
int TChannel::GetDetectorNumber () const
Definition at line 1524 of file TChannel.cxx.
References fDetectorNumber, fMnemonic, and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), TTigress::AddFragment(), AppendChannel(), TDetectorHit::GetDetector(), operator=(), and OverWriteChannel().
GetDigitizerType()
EDigitizer TChannel::GetDigitizerType () const inline
Definition at line 174 of file TChannel.h.
References fDigitizerType, and TPriorityValue< T >::Value().
Referenced by TGRSIMnemonic::GetTime(), and TTdrMnemonic::GetTime().
GetDigitizerTypeString()
const char * TChannel::GetDigitizerTypeString () const inline
Definition at line 173 of file TChannel.h.
References fDigitizerTypeString.
Referenced by OverWriteChannel(), TGRSIDataParser::SetTIGCharge(), and TMidasFile::SetTIGOdb().
GetEFFChi2()
double TChannel::GetEFFChi2 () const inline
Definition at line 185 of file TChannel.h.
References fEFFChi2, and TPriorityValue< T >::Value().
Referenced by OverWriteChannel().
GetEFFCoeff()
std::vector< double > TChannel::GetEFFCoeff () const inline
Definition at line 196 of file TChannel.h.
References fEFFCoefficients.
Referenced by OverWriteChannel().
GetEnergyNonlinearity() [1/2]
TGraph TChannel::GetEnergyNonlinearity () const inline
Definition at line 198 of file TChannel.h.
References fEnergyNonlinearity, and TPriorityValue< T >::Value().
Referenced by TDetectorHit::GetEnergyNonlinearity(), OverWriteChannel(), and TChannelTab::UpdateChannel().
GetEnergyNonlinearity() [2/2]
double TChannel::GetEnergyNonlinearity (double eng) const
Definition at line 1569 of file TChannel.cxx.
References fEnergyNonlinearity, and TPriorityValue< T >::Value().
GetENGChi2()
double TChannel::GetENGChi2 (size_t range = 0) const inline
Definition at line 181 of file TChannel.h.
References fENGChi2.
GetENGCoeff()
std::vector< Float_t > TChannel::GetENGCoeff (size_t range = 0) const inline
Definition at line 192 of file TChannel.h.
References fENGCoefficients.
Referenced by TGainMatch::FineMatch(), and TGainMatch::FineMatchFast().
GetENGDriftCoefficents()
std::vector< Float_t > TChannel::GetENGDriftCoefficents () const inline
Definition at line 202 of file TChannel.h.
References fENGDriftCoefficents.
Referenced by OverWriteChannel().
GetENGRange()
std::pair< double, double > TChannel::GetENGRange (size_t range) const inline
Definition at line 201 of file TChannel.h.
References fENGRanges.
GetENGRanges()
std::vector< std::pair< double, double > > TChannel::GetENGRanges () const inline
Definition at line 200 of file TChannel.h.
References fENGRanges.
Referenced by OverWriteChannel().
GetIntegration()
int TChannel::GetIntegration () const inline
Definition at line 171 of file TChannel.h.
References fIntegration, and TPriorityValue< T >::Value().
Referenced by TDetectorHit::GetCharge(), and OverWriteChannel().
GetLEDChi2()
double TChannel::GetLEDChi2 () const inline
Definition at line 183 of file TChannel.h.
References fLEDChi2, and TPriorityValue< T >::Value().
Referenced by OverWriteChannel().
GetLEDCoeff()
std::vector< double > TChannel::GetLEDCoeff () const inline
Definition at line 194 of file TChannel.h.
References fLEDCoefficients.
Referenced by OverWriteChannel().
GetMissingChannelMap()
static std::unordered_map< unsigned int, int > * TChannel::GetMissingChannelMap () inline static
Definition at line 73 of file TChannel.h.
References fMissingChannelMap.
GetMnemonic()
const TMnemonic * TChannel::GetMnemonic () const
Definition at line 1627 of file TChannel.cxx.
References fMnemonic, and TPriorityValue< T >::Value().
Referenced by TCSM::AddFragment(), TEmma::AddFragment(), TFipps::AddFragment(), TGriffin::AddFragment(), TIfin::AddFragment(), TRcmp::AddFragment(), TS3::AddFragment(), TSharc2::AddFragment(), TSharc::AddFragment(), TTigress::AddFragment(), TTrific::AddFragment(), TS3Hit::GetArrayPosition(), TS3Hit::GetDistanceStr(), and TTipHit::SetUpNumbering().
GetMnemonicClass()
static TClassRef TChannel::GetMnemonicClass () inline static
Definition at line 81 of file TChannel.h.
References fMnemonicClass.
GetNumber()
int TChannel::GetNumber () const inline
Definition at line 169 of file TChannel.h.
References fNumber, and TPriorityValue< T >::Value().
Referenced by AddChannel(), TCalManager::AddToManager(), TCalManager::AddToManager(), TDetectorHit::GetChannelNumber(), OverWriteChannel(), TCal::Print(), TCFDCal::Print(), TFragment::Print(), TTimeCal::Print(), TCFDCal::WriteToChannel(), TEnergyCal::WriteToChannel(), TGainMatch::WriteToChannel(), and TTimeCal::WriteToChannel().
GetNumberOfChannels()
static size_t TChannel::GetNumberOfChannels () inline static
Definition at line 68 of file TChannel.h.
References fChannelMap.
Referenced by ReadFile(), TMidasFile::SetGRIFFOdb(), TRunInfo::SetRunInfo(), TMidasFile::SetTIGDAQOdb(), TMidasFile::SetTIGOdb(), TAnalysisHistLoop::Write(), TAnalysisWriteLoop::Write(), TFragHistLoop::Write(), TFragWriteLoop::Write(), TSourceCalibration::WriteCalibration(), and WriteToRoot().
GetSegmentNumber()
int TChannel::GetSegmentNumber () const
Definition at line 1534 of file TChannel.cxx.
References fMnemonic, fSegmentNumber, and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), TTigress::AddFragment(), AppendChannel(), TDetectorHit::GetSegment(), operator=(), and OverWriteChannel().
GetStream()
int TChannel::GetStream () const inline
Definition at line 172 of file TChannel.h.
References fStream, and TPriorityValue< T >::Value().
Referenced by OverWriteChannel().
GetTime()
double TChannel::GetTime (Long64_t timestamp, Float_t cfd, double energy) const
Definition at line 1622 of file TChannel.cxx.
References fMnemonic, TMnemonic::GetTime(), and TPriorityValue< T >::Value().
Referenced by TDetectorHit::GetTime().
GetTIMEChi2()
double TChannel::GetTIMEChi2 () const inline
Definition at line 184 of file TChannel.h.
References fTIMEChi2, and TPriorityValue< T >::Value().
Referenced by OverWriteChannel().
GetTIMECoeff()
std::vector< double > TChannel::GetTIMECoeff () const inline
Definition at line 195 of file TChannel.h.
References fTIMECoefficients.
Referenced by OverWriteChannel(), and TTimeCal::ReadFromChannel().
GetTimeDrift()
double TChannel::GetTimeDrift () const inline
Definition at line 177 of file TChannel.h.
References fTimeDrift, and TPriorityValue< T >::Value().
Referenced by TDetectorHit::GetTimeStampNs(), and OverWriteChannel().
GetTimeOffset()
Long64_t TChannel::GetTimeOffset () const inline
Definition at line 176 of file TChannel.h.
References fTimeOffset, and TPriorityValue< T >::Value().
Referenced by TGRSIMnemonic::GetTime(), THILMnemonic::GetTime(), TILLMnemonic::GetTime(), TTdrMnemonic::GetTime(), TDetectorHit::GetTimeStampNs(), main(), and OverWriteChannel().
GetTimeStampUnit()
int TChannel::GetTimeStampUnit () const inline
Definition at line 175 of file TChannel.h.
References fTimeStampUnit, and TPriorityValue< T >::Value().
Referenced by TGRSIMnemonic::GetTime(), THILMnemonic::GetTime(), TILLMnemonic::GetTime(), TMnemonic::GetTime(), TTdrMnemonic::GetTime(), and TDetectorHit::GetTimeStampUnit().
GetTZero() [1/2]
double TChannel::GetTZero (double tempd) const inline
Definition at line 294 of file TChannel.h.
References CalibrateTIME().
Referenced by TGRSIMnemonic::GetTime(), THILMnemonic::GetTime(), TILLMnemonic::GetTime(), TTdrMnemonic::GetTime(), TSiLiHit::GetTimeFit(), and TFragment::GetTZero().
GetTZero() [2/2]
double TChannel::GetTZero (int tempi) const inline
Definition at line 295 of file TChannel.h.
References CalibrateTIME().
GetWaveBaseLine()
double TChannel::GetWaveBaseLine () const inline
Definition at line 278 of file TChannel.h.
References TChannel::WaveFormShapePar::BaseLine, and WaveFormShape.
Referenced by TSiLiHit::FitPulseAnalyzer().
GetWaveDecay()
double TChannel::GetWaveDecay () const inline
Definition at line 277 of file TChannel.h.
References TChannel::WaveFormShapePar::TauDecay, and WaveFormShape.
Referenced by TSiLiHit::FitPulseAnalyzer().
GetWaveParam()
WaveFormShapePar TChannel::GetWaveParam () const inline
Definition at line 280 of file TChannel.h.
References WaveFormShape.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
GetWaveRise()
double TChannel::GetWaveRise () const inline
Definition at line 276 of file TChannel.h.
References TChannel::WaveFormShapePar::TauRise, and WaveFormShape.
Referenced by TSiLiHit::FitPulseAnalyzer().
InitChannelInput()
void TChannel::InitChannelInput () static private
Definition at line 254 of file TChannel.cxx.
References CYAN, fFileData, kRootFile, ParseInputData(), and RESET_COLOR.
operator=() [1/2]
TChannel & TChannel::operator= (const TChannel & rhs)
copy assignment operator Simply a copy of the copy constructor code (plus returing *this).
Definition at line 165 of file TChannel.cxx.
References Clear(), fCFDChi2, fCFDCoefficients, fCTCoefficients, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fLEDChi2, fLEDCoefficients, fMnemonic, fNumber, fStream, fTIMEChi2, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, GetAddress(), GetClassType(), GetCrystalNumber(), GetDetectorNumber(), GetSegmentNumber(), GetWaveParam(), SetAddress(), SetAllENGChi2(), SetAllENGCoefficients(), SetCFDChi2(), SetCFDCoefficients(), SetClassType(), SetCrystalNumber(), SetCTCoefficients(), SetDetectorNumber(), SetDigitizerType(), SetEFFChi2(), SetEFFCoefficients(), SetEnergyNonlinearity(), SetENGDriftCoefficents(), SetENGRanges(), SetIntegration(), SetLEDChi2(), SetLEDCoefficients(), SetName(), SetNumber(), SetSegmentNumber(), SetStream(), SetTIMEChi2(), SetTIMECoefficients(), SetTimeDrift(), SetTimeOffset(), SetUseCalFileIntegration(), SetWaveParam(), and TPriorityValue< T >::Value().
operator=() [2/2]
TChannel & TChannel::operator= (TChannel && rhs) noexcept
move assignment operator Doesn't really move anything yet, it's just a copy of the copy assignment operator. This needs to be changed.
Definition at line 204 of file TChannel.cxx.
OverWriteChannel()
void TChannel::OverWriteChannel (TChannel * chan) private
Overwrites the current TChannel with chan.
Definition at line 327 of file TChannel.cxx.
References GetAddress(), GetAllENGChi2(), GetAllENGCoeff(), GetCFDChi2(), GetCFDCoeff(), GetClassType(), GetCrystalNumber(), GetCTCoeff(), GetDetectorNumber(), GetDigitizerTypeString(), GetEFFChi2(), GetEFFCoeff(), GetEnergyNonlinearity(), GetENGDriftCoefficents(), GetENGRanges(), GetIntegration(), GetLEDChi2(), GetLEDCoeff(), GetNumber(), GetSegmentNumber(), GetStream(), GetTIMEChi2(), GetTIMECoeff(), GetTimeDrift(), GetTimeOffset(), GetWaveParam(), kForce, SetAddress(), SetAllENGChi2(), SetAllENGCoefficients(), SetCFDChi2(), SetCFDCoefficients(), SetClassType(), SetCrystalNumber(), SetCTCoefficients(), SetDetectorNumber(), SetDigitizerType(), SetEFFChi2(), SetEFFCoefficients(), SetEnergyNonlinearity(), SetENGDriftCoefficents(), SetENGRanges(), SetIntegration(), SetLEDChi2(), SetLEDCoefficients(), SetName(), SetNumber(), SetSegmentNumber(), SetStream(), SetTIMEChi2(), SetTIMECoefficients(), SetTimeDrift(), SetTimeOffset(), SetUseCalFileIntegration(), SetWaveParam(), and UseCalFileIntegration().
Referenced by AddChannel().
ParseInputData()
Int_t TChannel::ParseInputData (const char * inputdata = "", Option_t * opt = "", EPriority prio = EPriority::kUser) static
Definition at line 1165 of file TChannel.cxx.
References TChannel(), AddCFDCoefficient(), AddChannel(), AddCTCoefficient(), AddEFFCoefficient(), AddEnergyNonlinearityPoint(), AddENGCoefficient(), AddENGDriftCoefficent(), AddLEDCoefficient(), AddTIMECoefficient(), DestroyCFDCal(), DestroyCTCal(), DestroyEFFCal(), DestroyEnergyNonlinearity(), DestroyENGCal(), DestroyLEDCal(), DestroyTIMECal(), fCFDCoefficients, fCTCoefficients, fEFFCoefficients, fEnergyNonlinearity, fENGCoefficients, fENGDriftCoefficents, fLEDCoefficients, fTIMECoefficients, GetAddress(), GetChannel(), SetAddress(), SetCFDChi2(), SetDigitizerType(), SetEFFChi2(), SetENGChi2(), SetENGRange(), SetIntegration(), SetLEDChi2(), SetName(), SetNumber(), TPriorityValue< T >::SetPriority(), SetStream(), SetTIMEChi2(), SetTimeDrift(), SetTimeOffset(), SetupEnergyNonlinearity(), SetUseCalFileIntegration(), SetWaveBaseLine(), SetWaveDecay(), SetWaveRise(), trimWS(), and UpdateChannel().
Referenced by InitChannelInput(), ReadCalFile(), and WriteToRoot().
Print()
void TChannel::Print (Option_t * opt = "") const override
Prints out the current TChannel.
Definition at line 833 of file TChannel.cxx.
References PrintToString().
Referenced by TSortingDiagnostics::AddDetectorClass(), and main().
PrintCTCoeffs()
void TChannel::PrintCTCoeffs (Option_t * opt = "") const
Prints out the current TChannel.
Definition at line 818 of file TChannel.cxx.
References fAddress, fCTCoefficients, fNumber, and hex().
PrintCTToString()
std::string TChannel::PrintCTToString (Option_t * opt = "") const
Definition at line 839 of file TChannel.cxx.
References fAddress, fCTCoefficients, fNumber, and TPriorityValue< T >::Value().
PrintToString()
std::string TChannel::PrintToString (Option_t * opt = "") const
Definition at line 864 of file TChannel.cxx.
References TChannel::WaveFormShapePar::BaseLine, fAddress, fCFDCoefficients, fCTCoefficients, fDigitizerTypeString, fEFFChi2, fEFFCoefficients, fEnergyNonlinearity, fENGChi2, fENGCoefficients, fENGDriftCoefficents, fENGRanges, fIntegration, fNumber, fTIMECoefficients, fTimeDrift, fTimeOffset, fUseCalFileInt, GetClassType(), hex(), TChannel::WaveFormShapePar::TauDecay, TChannel::WaveFormShapePar::TauRise, UseWaveParam(), TPriorityValue< T >::Value(), and WaveFormShape.
Referenced by Print().
ReadCalFile() [1/2]
Int_t TChannel::ReadCalFile (const char * filename = "") static
Makes TChannels from a cal file to be used as the current calibration until grsisort is closed. Returns the number of channels properly read in.
Definition at line 1134 of file TChannel.cxx.
References CYAN, ReadCalFile(), and RESET_COLOR.
ReadCalFile() [2/2]
Int_t TChannel::ReadCalFile (std::ifstream & infile) static
Definition at line 1104 of file TChannel.cxx.
References DRED, fChannelMap, fChannelNumberMap, kInputFile, ParseInputData(), RESET_COLOR, and SaveToSelf().
Referenced by TGRSIHelper::TGRSIHelper(), main(), MakeGRIFFINEnergyHsts(), ReadCalFile(), recalibrate_spectra(), TGRSIint::SetupPipeline(), and TGRSISelector::SlaveBegin().
ReadCalFromCurrentFile()
Int_t TChannel::ReadCalFromCurrentFile (Option_t * opt = "overwrite") static
Definition at line 1057 of file TChannel.cxx.
References ReadFile().
ReadCalFromFile()
Int_t TChannel::ReadCalFromFile (TFile * tempf, Option_t * opt = "overwrite") static
Reads the TChannel information from a TFile if it has already been written to that File.
Definition at line 1068 of file TChannel.cxx.
References ReadFile().
Referenced by TGRSISelector::Process().
ReadCalFromTree()
Int_t TChannel::ReadCalFromTree (TTree * tree, Option_t * opt = "overwrite") static
Reads the TChannel information from a Tree if it has already been written to that Tree.
Definition at line 1078 of file TChannel.cxx.
References ReadFile().
Referenced by main(), make_calibration_histograms(), and MakeGRIFFINChargeHsts().
ReadEnergyNonlinearities()
void TChannel::ReadEnergyNonlinearities (TFile * file, const char * graphName = "EnergyNonlinearity0x", bool all = false) static
Read energy nonlinearities as TGraphErrors from provided root file using "graphName%x" as names
Definition at line 1584 of file TChannel.cxx.
References TChannel(), AddChannel(), fEnergyNonlinearity, GetChannel(), kRootFile, TPriorityValue< T >::Set(), and SetupEnergyNonlinearity().
ReadFile()
Int_t TChannel::ReadFile (TFile * tempf) static private
Definition at line 1090 of file TChannel.cxx.
References GetNumberOfChannels().
Referenced by ReadCalFromCurrentFile(), ReadCalFromFile(), and ReadCalFromTree().
ResizeENG()
void TChannel::ResizeENG (size_t size) inline
Definition at line 217 of file TChannel.h.
References fENGChi2, fENGCoefficients, and fENGRanges.
Referenced by main().
SaveToSelf() [1/2]
void TChannel::SaveToSelf () static private
This function saves the current cal-file to fFileData. For some reason it does the latter not by using WriteCalBuffer ???
Definition at line 1154 of file TChannel.cxx.
References fFileData, and WriteCalFile().
Referenced by ReadCalFile(), and WriteToRoot().
SaveToSelf() [2/2]
static void TChannel::SaveToSelf (const char *) static private
SetAddress()
void TChannel::SetAddress (unsigned int tmpadd)
Sets the address of a TChannel and also overwrites that channel if it is in the channel map
Definition at line 540 of file TChannel.cxx.
References fAddress, fChannelMap, and hex().
Referenced by TChannel(), TChannel(), main(), operator=(), OverWriteChannel(), TLstFile::ParseHeaders(), ParseInputData(), TMidasFile::SetGRIFFOdb(), TMidasFile::SetTIGDAQOdb(), and TMidasFile::SetTIGOdb().
SetAllENGChi2()
void TChannel::SetAllENGChi2 (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 244 of file TChannel.h.
References fENGChi2.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetAllENGCoefficients()
void TChannel::SetAllENGCoefficients (const TPriorityValue< std::vector< std::vector< Float_t > > > & tmp) inline
Definition at line 224 of file TChannel.h.
References fENGCoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetCFDChi2()
void TChannel::SetCFDChi2 (const TPriorityValue< double > & tmp) inline
Definition at line 252 of file TChannel.h.
References fCFDChi2.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetCFDCoefficients()
void TChannel::SetCFDCoefficients (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 237 of file TChannel.h.
References fCFDCoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetClassType()
void TChannel::SetClassType (TClass * cl_type)
Definition at line 1637 of file TChannel.cxx.
References fMnemonic, TMnemonic::SetClassType(), and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetCrystalNumber()
void TChannel::SetCrystalNumber (int tempint) inline
Definition at line 159 of file TChannel.h.
References fCrystalNumber.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetCTCoefficients()
void TChannel::SetCTCoefficients (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 241 of file TChannel.h.
References fCTCoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetDetectorNumber()
void TChannel::SetDetectorNumber (int tempint) inline
Definition at line 157 of file TChannel.h.
References fDetectorNumber.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetDigitizerType() [1/2]
void TChannel::SetDigitizerType (const std::string & mnemonic, const char * tmpstr, EPriority prio) static
Definition at line 804 of file TChannel.cxx.
References GetChannelMap().
SetDigitizerType() [2/2]
void TChannel::SetDigitizerType (const TPriorityValue< std::string > & tmp)
Definition at line 1612 of file TChannel.cxx.
References TMnemonic::EnumerateDigitizer(), fDigitizerType, fDigitizerTypeString, fMnemonic, fTimeStampUnit, and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), AppendChannel(), main(), operator=(), OverWriteChannel(), TLstFile::ParseHeaders(), ParseInputData(), TMidasFile::SetGRIFFOdb(), and TMidasFile::SetTIGOdb().
SetEFFChi2()
void TChannel::SetEFFChi2 (const TPriorityValue< double > & tmp) inline
Definition at line 255 of file TChannel.h.
References fEFFChi2.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetEFFCoefficients()
void TChannel::SetEFFCoefficients (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 240 of file TChannel.h.
References fEFFCoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetEnergyNonlinearity()
void TChannel::SetEnergyNonlinearity (const TPriorityValue< TGraph > & tmp) inline
Definition at line 242 of file TChannel.h.
References fEnergyNonlinearity.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetENGChi2()
void TChannel::SetENGChi2 (const TPriorityValue< double > & tmp, const size_t & range = 0) inline
Definition at line 245 of file TChannel.h.
References fENGChi2, TPriorityValue< T >::Priority(), and TPriorityValue< T >::Value().
Referenced by ParseInputData().
SetENGCoefficients()
void TChannel::SetENGCoefficients (const std::vector< Float_t > & tmp, size_t range = 0) inline
Definition at line 225 of file TChannel.h.
References fENGCoefficients.
Referenced by main(), and TChannelTab::UpdateChannel().
SetENGDriftCoefficents()
void TChannel::SetENGDriftCoefficents (const TPriorityValue< std::vector< Float_t > > & tmp) inline
Definition at line 236 of file TChannel.h.
References fENGDriftCoefficents.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetENGRange()
void TChannel::SetENGRange (const std::pair< double, double > & tmp, const size_t & range) inline
Definition at line 231 of file TChannel.h.
References fENGRanges.
Referenced by main(), and ParseInputData().
SetENGRanges()
void TChannel::SetENGRanges (const TPriorityValue< std::vector< std::pair< double, double > > > & tmp) inline
Definition at line 230 of file TChannel.h.
References fENGRanges.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetIntegration() [1/2]
void TChannel::SetIntegration (const std::string & mnemonic, int tmpint, EPriority pr) static
Definition at line 790 of file TChannel.cxx.
References GetChannelMap().
SetIntegration() [2/2]
void TChannel::SetIntegration (const TPriorityValue< int > & tmp) inline
Definition at line 149 of file TChannel.h.
References fIntegration.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), ParseInputData(), and TMidasFile::SetTIGOdb().
SetLEDChi2()
void TChannel::SetLEDChi2 (const TPriorityValue< double > & tmp) inline
Definition at line 253 of file TChannel.h.
References fLEDChi2.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetLEDCoefficients()
void TChannel::SetLEDCoefficients (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 238 of file TChannel.h.
References fLEDCoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetMnemonicClass()
static void TChannel::SetMnemonicClass (const TClassRef & cls) inline static
Definition at line 80 of file TChannel.h.
References fMnemonicClass.
Referenced by InitLibrary(), TLstFile::Open(), TMidasFile::Open(), TRlmdFile::Open(), and TTdrFile::Open().
SetName()
void TChannel::SetName (const char * tmpName) override
Definition at line 244 of file TChannel.cxx.
References fMnemonic, TMnemonic::Parse(), and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), TChannel(), AppendChannel(), Clear(), operator=(), OverWriteChannel(), ParseInputData(), TMidasFile::SetGRIFFOdb(), TMidasFile::SetTIGDAQOdb(), and TMidasFile::SetTIGOdb().
SetNumber()
void TChannel::SetNumber (const TPriorityValue< int > & tmp) inline
Definition at line 139 of file TChannel.h.
References fChannelNumberMap, fNumber, and TPriorityValue< T >::Value().
Referenced by TChannel(), TChannel(), AppendChannel(), main(), operator=(), OverWriteChannel(), ParseInputData(), TMidasFile::SetGRIFFOdb(), TMidasFile::SetTIGDAQOdb(), and TMidasFile::SetTIGOdb().
SetSegmentNumber()
void TChannel::SetSegmentNumber (int tempint) inline
Definition at line 158 of file TChannel.h.
References fSegmentNumber.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetStream()
void TChannel::SetStream (const TPriorityValue< int > & tmp) inline
Definition at line 151 of file TChannel.h.
References fStream.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetTIMEChi2()
void TChannel::SetTIMEChi2 (const TPriorityValue< double > & tmp) inline
Definition at line 254 of file TChannel.h.
References fTIMEChi2.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetTIMECoefficients()
void TChannel::SetTIMECoefficients (const TPriorityValue< std::vector< double > > & tmp) inline
Definition at line 239 of file TChannel.h.
References fTIMECoefficients.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetTimeDrift()
void TChannel::SetTimeDrift (const TPriorityValue< double > & tmp) inline
Definition at line 155 of file TChannel.h.
References fTimeDrift.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetTimeOffset()
void TChannel::SetTimeOffset (const TPriorityValue< Long64_t > & tmp) inline
Definition at line 154 of file TChannel.h.
References fTimeOffset.
Referenced by TChannel(), TChannel(), AppendChannel(), main(), operator=(), OverWriteChannel(), and ParseInputData().
SetupEnergyNonlinearity()
void TChannel::SetupEnergyNonlinearity () private
Definition at line 1576 of file TChannel.cxx.
References TPriorityValue< T >::Address(), fAddress, and fEnergyNonlinearity.
Referenced by ParseInputData(), and ReadEnergyNonlinearities().
SetUseCalFileIntegration() [1/2]
void TChannel::SetUseCalFileIntegration (const std::string & mnemonic, bool flag, EPriority pr) static
Writes this UseCalFileIntegration to all channels in the current TChannel Map that starts with the mnemonic. Use "" to write to ALL channels WARNING: This is case sensitive!
Definition at line 776 of file TChannel.cxx.
References GetChannelMap().
SetUseCalFileIntegration() [2/2]
void TChannel::SetUseCalFileIntegration (const TPriorityValue< bool > & tmp = TPriorityValue<bool>(true, EPriority::kUser)) inline
Definition at line 187 of file TChannel.h.
References fUseCalFileInt.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), OverWriteChannel(), and ParseInputData().
SetUseWaveParam()
void TChannel::SetUseWaveParam (bool temp = true) inline
Definition at line 273 of file TChannel.h.
References TChannel::WaveFormShapePar::InUse, and WaveFormShape.
Referenced by SetWaveBaseLine(), SetWaveDecay(), and SetWaveRise().
SetWaveBaseLine()
void TChannel::SetWaveBaseLine (double temp) inline
Definition at line 267 of file TChannel.h.
References TChannel::WaveFormShapePar::BaseLine, SetUseWaveParam(), and WaveFormShape.
Referenced by ParseInputData().
SetWaveDecay()
void TChannel::SetWaveDecay (const double & temp) inline
Definition at line 262 of file TChannel.h.
References SetUseWaveParam(), TChannel::WaveFormShapePar::TauDecay, and WaveFormShape.
Referenced by ParseInputData().
SetWaveParam()
void TChannel::SetWaveParam (WaveFormShapePar temp) inline
Definition at line 274 of file TChannel.h.
References WaveFormShape.
Referenced by TChannel(), TChannel(), AppendChannel(), operator=(), and OverWriteChannel().
SetWaveRise()
void TChannel::SetWaveRise (const double & temp) inline
Definition at line 257 of file TChannel.h.
References SetUseWaveParam(), TChannel::WaveFormShapePar::TauRise, and WaveFormShape.
Referenced by ParseInputData().
SortedChannels()
std::vector< TChannel * > TChannel::SortedChannels () static private
Definition at line 977 of file TChannel.cxx.
References CompareChannels(), and fChannelMap.
Referenced by WriteCalBuffer(), WriteCalFile(), and WriteCTCorrections().
UpdateChannel()
int TChannel::UpdateChannel (TChannel * chan, Option_t * opt = "") static
If there is information in the chan, the current TChannel with the same address is updated with that information.
Definition at line 398 of file TChannel.cxx.
References AppendChannel(), GetAddress(), and GetChannel().
Referenced by ParseInputData().
UseCalFileIntegration()
bool TChannel::UseCalFileIntegration () inline
Definition at line 189 of file TChannel.h.
References fUseCalFileInt, and TPriorityValue< T >::Value().
Referenced by TDetectorHit::GetCharge(), TDetectorHit::GetEnergy(), TFippsTACHit::GetTempCorrectedEnergy(), TTACHit::GetTempCorrectedEnergy(), and OverWriteChannel().
UseWaveParam()
bool TChannel::UseWaveParam () const inline
Definition at line 279 of file TChannel.h.
References TChannel::WaveFormShapePar::InUse, and WaveFormShape.
Referenced by TSiLiHit::FitPulseAnalyzer(), and PrintToString().
WriteCalBuffer()
void TChannel::WriteCalBuffer (Option_t * opt = "") static
writes any TChannels in memory to the internal buffer fFileData. Can be used to over write info that is there or create the buffer if the channels originated from the odb.
Definition at line 1040 of file TChannel.cxx.
References fFileData, and SortedChannels().
Referenced by WriteToRoot().
WriteCalFile()
void TChannel::WriteCalFile (const std::string & outfilename = "") static
Prints the context of addresschannelmap formatted correctly to stdout if no file name is passed to the function. If a file name is passed to the function prints the context of addresschannelmap formatted correctly to a file with the given name. This will earse and rewrite the file if the file already exisits!
Definition at line 992 of file TChannel.cxx.
References SortedChannels().
Referenced by main(), SaveToSelf(), and TSourceCalibration::WriteCalibration().
WriteCTCorrections()
void TChannel::WriteCTCorrections (const std::string & outfilename = "") static
Definition at line 1018 of file TChannel.cxx.
References SortedChannels().
Referenced by main().
WriteToRoot()
int TChannel::WriteToRoot (TFile * fileptr = nullptr) static
Writes Cal File information to the tree
Definition at line 1444 of file TChannel.cxx.
References DeleteAllChannels(), fFileData, GetDefaultChannel(), GetNumberOfChannels(), kRootFile, ParseInputData(), SaveToSelf(), and WriteCalBuffer().
Referenced by TGRSIFrame::Run(), TGRSISelector::Terminate(), TAnalysisWriteLoop::Write(), and TFragWriteLoop::Write().
Member Data Documentation
fAddress
unsigned int TChannel::fAddress {0} private
Definition at line 84 of file TChannel.h.
Referenced by Clear(), GetAddress(), PrintCTCoeffs(), PrintCTToString(), PrintToString(), SetAddress(), and SetupEnergyNonlinearity().
fCFDChi2
TPriorityValue<double> TChannel::fCFDChi2 private
Chi2 of the CFD calibration.
Definition at line 107 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetCFDChi2(), operator=(), and SetCFDChi2().
fCFDCoefficients
TPriorityValue<std::vector<double> > TChannel::fCFDCoefficients private
CFD calibration coeffs (low to high order)
Definition at line 106 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddCFDCoefficient(), AppendChannel(), CalibrateCFD(), Clear(), DestroyCFDCal(), GetCFDCoeff(), operator=(), ParseInputData(), PrintToString(), and SetCFDCoefficients().
fChannelMap
std::unordered_map< unsigned int, TChannel * > * TChannel::fChannelMap = new std::unordered_map<unsigned int, TChannel*> static private
Definition at line 126 of file TChannel.h.
Referenced by AddChannel(), DeleteAllChannels(), FindChannelByName(), FindChannelByRegEx(), GetChannel(), GetChannelMap(), GetDefaultChannel(), GetNumberOfChannels(), ReadCalFile(), SetAddress(), and SortedChannels().
fChannelNumberMap
std::unordered_map< int, TChannel * > * TChannel::fChannelNumberMap = new std::unordered_map<int, TChannel*> static private
Definition at line 128 of file TChannel.h.
Referenced by AddChannel(), DeleteAllChannels(), GetChannelByNumber(), ReadCalFile(), and SetNumber().
fCrystalNumber
int TChannel::fCrystalNumber {-1} mutable private
Definition at line 95 of file TChannel.h.
Referenced by Clear(), GetCrystalNumber(), and SetCrystalNumber().
fCTCoefficients
TPriorityValue<std::vector<double> > TChannel::fCTCoefficients private
Cross talk coefficients.
Definition at line 114 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddCTCoefficient(), AppendChannel(), Clear(), DestroyCTCal(), GetCTCoeff(), operator=(), ParseInputData(), PrintCTCoeffs(), PrintCTToString(), PrintToString(), and SetCTCoefficients().
fDetectorNumber
int TChannel::fDetectorNumber {-1} mutable private
Definition at line 93 of file TChannel.h.
Referenced by Clear(), GetDetectorNumber(), and SetDetectorNumber().
fDigitizerType
TPriorityValue<EDigitizer> TChannel::fDigitizerType private
Definition at line 87 of file TChannel.h.
Referenced by GetDigitizerType(), and SetDigitizerType().
fDigitizerTypeString
TPriorityValue<std::string> TChannel::fDigitizerTypeString private
Definition at line 86 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetDigitizerTypeString(), operator=(), PrintToString(), and SetDigitizerType().
fEFFChi2
TPriorityValue<double> TChannel::fEFFChi2 private
Chi2 of Efficiency calibration.
Definition at line 113 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetEFFChi2(), operator=(), PrintToString(), and SetEFFChi2().
fEFFCoefficients
TPriorityValue<std::vector<double> > TChannel::fEFFCoefficients private
Efficiency calibration coeffs (low to high order)
Definition at line 112 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddEFFCoefficient(), AppendChannel(), Clear(), DestroyEFFCal(), GetEFFCoeff(), operator=(), ParseInputData(), PrintToString(), and SetEFFCoefficients().
fEnergyNonlinearity
TPriorityValue<TGraph> TChannel::fEnergyNonlinearity private
Energy nonlinearity as TGraph, is used as E=E+GetEnergyNonlinearity(E), so y should be E(source)-calibration(peak)
Definition at line 115 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddEnergyNonlinearityPoint(), AppendChannel(), Clear(), DestroyEnergyNonlinearity(), GetEnergyNonlinearity(), GetEnergyNonlinearity(), operator=(), ParseInputData(), PrintToString(), ReadEnergyNonlinearities(), SetEnergyNonlinearity(), and SetupEnergyNonlinearity().
fENGChi2
TPriorityValue<std::vector<double> > TChannel::fENGChi2 private
Chi2 of the energy calibration.
Definition at line 104 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), DestroyENGCal(), GetAllENGChi2(), GetENGChi2(), operator=(), PrintToString(), ResizeENG(), SetAllENGChi2(), and SetENGChi2().
fENGCoefficients
TPriorityValue<std::vector<std::vector<Float_t> > > TChannel::fENGCoefficients private
Energy calibration coeffs (low to high order)
Definition at line 102 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddENGCoefficient(), AppendChannel(), CalibrateENG(), Clear(), DestroyENGCal(), GetAllENGCoeff(), GetENGCoeff(), operator=(), ParseInputData(), PrintToString(), ResizeENG(), SetAllENGCoefficients(), and SetENGCoefficients().
fENGDriftCoefficents
TPriorityValue<std::vector<Float_t> > TChannel::fENGDriftCoefficents private
Energy drift coefficents (applied after energy calibration has been applied)
Definition at line 105 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddENGDriftCoefficent(), AppendChannel(), CalibrateENG(), Clear(), DestroyENGCal(), GetENGDriftCoefficents(), operator=(), ParseInputData(), PrintToString(), and SetENGDriftCoefficents().
fENGRanges
TPriorityValue<std::vector<std::pair<double, double> > > TChannel::fENGRanges private
Range of energy calibrations.
Definition at line 103 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), CalibrateENG(), Clear(), DestroyENGCal(), GetENGRange(), GetENGRanges(), operator=(), PrintToString(), ResizeENG(), SetENGRange(), and SetENGRanges().
fFileData
std::string TChannel::fFileData static private
Definition at line 332 of file TChannel.h.
Referenced by InitChannelInput(), SaveToSelf(), WriteCalBuffer(), and WriteToRoot().
fIntegration
TPriorityValue<int> TChannel::fIntegration {1} private
Definition at line 85 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), CalibrateENG(), Clear(), GetIntegration(), operator=(), PrintToString(), and SetIntegration().
fLEDChi2
TPriorityValue<double> TChannel::fLEDChi2 private
Chi2 of LED calibration.
Definition at line 109 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetLEDChi2(), operator=(), and SetLEDChi2().
fLEDCoefficients
TPriorityValue<std::vector<double> > TChannel::fLEDCoefficients private
LED calibration coeffs (low to high order)
Definition at line 108 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddLEDCoefficient(), AppendChannel(), CalibrateLED(), Clear(), DestroyLEDCal(), GetLEDCoeff(), operator=(), ParseInputData(), and SetLEDCoefficients().
fMissingChannelMap
std::unordered_map< unsigned int, int > * TChannel::fMissingChannelMap = new std::unordered_map<unsigned int, int> static private
Definition at line 127 of file TChannel.h.
Referenced by GetChannel(), and GetMissingChannelMap().
fMnemonic
TPriorityValue<TMnemonic*> TChannel::fMnemonic private
Definition at line 99 of file TChannel.h.
Referenced by TChannel(), TChannel(), Clear(), GetClassType(), GetCrystalNumber(), GetDetectorNumber(), GetMnemonic(), GetSegmentNumber(), GetTime(), operator=(), SetClassType(), SetDigitizerType(), and SetName().
fMnemonicClass
TClassRef TChannel::fMnemonicClass = TClassRef("TMnemonic") static private
Definition at line 100 of file TChannel.h.
Referenced by Clear(), GetMnemonicClass(), and SetMnemonicClass().
fNumber
TPriorityValue<int> TChannel::fNumber {0} private
Definition at line 89 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetNumber(), operator=(), PrintCTCoeffs(), PrintCTToString(), PrintToString(), and SetNumber().
fSegmentNumber
int TChannel::fSegmentNumber {-1} mutable private
Definition at line 94 of file TChannel.h.
Referenced by Clear(), GetSegmentNumber(), and SetSegmentNumber().
fStream
TPriorityValue<int> TChannel::fStream {0} private
Definition at line 90 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetStream(), operator=(), and SetStream().
fTIMEChi2
TPriorityValue<double> TChannel::fTIMEChi2 private
Chi2 of the Time calibration.
Definition at line 111 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetTIMEChi2(), operator=(), and SetTIMEChi2().
fTIMECoefficients
TPriorityValue<std::vector<double> > TChannel::fTIMECoefficients private
Time calibration coeffs (low to high order)
Definition at line 110 of file TChannel.h.
Referenced by TChannel(), TChannel(), AddTIMECoefficient(), AppendChannel(), CalibrateTIME(), CalibrateTIME(), Clear(), DestroyTIMECal(), GetTIMECoeff(), operator=(), ParseInputData(), PrintToString(), and SetTIMECoefficients().
fTimeDrift
TPriorityValue<double> TChannel::fTimeDrift private
Time drift factor.
Definition at line 98 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetTimeDrift(), operator=(), PrintToString(), and SetTimeDrift().
fTimeOffset
TPriorityValue<Long64_t> TChannel::fTimeOffset private
Definition at line 97 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), GetTimeOffset(), operator=(), PrintToString(), and SetTimeOffset().
fTimeStampUnit
TPriorityValue<int> TChannel::fTimeStampUnit {0} private
Definition at line 88 of file TChannel.h.
Referenced by GetTimeStampUnit(), and SetDigitizerType().
fUseCalFileInt
TPriorityValue<bool> TChannel::fUseCalFileInt {false} private
Definition at line 91 of file TChannel.h.
Referenced by TChannel(), TChannel(), AppendChannel(), Clear(), operator=(), PrintToString(), SetUseCalFileIntegration(), and UseCalFileIntegration().
WaveFormShape
WaveFormShapePar TChannel::WaveFormShape {} private
Definition at line 124 of file TChannel.h.
Referenced by Clear(), GetWaveBaseLine(), GetWaveDecay(), GetWaveParam(), GetWaveRise(), PrintToString(), SetUseWaveParam(), SetWaveBaseLine(), SetWaveDecay(), SetWaveParam(), SetWaveRise(), and UseWaveParam().