GRSISort: TILLDataParser Class Reference
TILLDataParser Class Reference
Sorting
Detailed Description
The TILLDataParser is the DAQ dependent part of GRSISort. It takes a "DAQ-dependent"-flavoured LST file and converts it into a generic TFragment that the rest of GRSISort can deal with. This is where event word masks are applied, and any changes to the event format must be implemented.
Definition at line 43 of file TILLDataParser.h.
Public Types
enum class EBank {
kWFDN = 0 , kGRF1 = 1 , kGRF2 = 2 , kGRF3 = 3 ,
kGRF4 = 4 , kFME0 = 5 , kFME1 = 6 , kFME2 = 7 ,
kFME3 = 8
}
enum class EDataParserState {
kGood , kBadHeader , kMissingWords , kBadScalerLowTS ,
kBadScalerValue , kBadScalerHighTS , kBadScalerType , kBadTriggerId ,
kBadLowTS , kBadHighTS , kSecondHeader , kWrongNofWords ,
kNotSingleCfd , kSizeMismatch , kBadFooter , kFault ,
kMissingPsd , kMissingCfd , kMissingCharge , kBadBank ,
kBadModuleType , kEndOfData , kUndefined
}
Public Member Functions
TILLDataParser ()
~TILLDataParser ()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & AddGoodOutputQueue (size_t maxSize=50000)
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & BadOutputQueue ()
virtual void ClearQueue ()
virtual size_t ItemsPushed ()
virtual std::string OutputQueueStatus ()
int Process (std::shared_ptr< TRawEvent >) override
void Push (std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > &queues, const std::shared_ptr< TFragment > &frag)
void Push (ThreadsafeQueue< std::shared_ptr< const TBadFragment > > &queue, const std::shared_ptr< TBadFragment > &frag)
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & ScalerOutputQueue ()
virtual void SetFinished ()
virtual void SetNoWaveForms (bool temp=true)
virtual void SetRecordDiag (bool temp=true)
virtual void SetStatusVariables (std::atomic_size_t *itemsPopped, std::atomic_long *inputSize)
Protected Member Functions
TChannel * Channel () const
bool FragmentHasWaveform () const
void FragmentHasWaveform (const bool &val)
TFragmentMap FragmentMap () const
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & GoodOutputQueues ()
uint64_t LastDaqId () const
uint64_t LastNetworkPacket () const
std::map< UInt_t, Long64_t > LastTimeStampMap () const
uint64_t LastTriggerId () const
void LastTriggerId (const uint64_t &val)
uint64_t MaxTriggerId () const
bool NoWaveforms () const
bool RecordDiag () const
Static Protected Member Functions
static TGRSIOptions * Options ()
static void Options (TGRSIOptions *val)
Private Member Functions
int V1SingleFippsEventToFragment (uint32_t *data)
int V2SingleFippsEventToFragment (uint32_t *data)
Private Attributes
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > fBadOutputQueue
TChannel * fChannel
bool fFragmentHasWaveform
std::map< Long_t, int > fFragmentIdMap
TFragmentMap fFragmentMap
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > fGoodOutputQueues
std::atomic_long * fInputSize
std::atomic_size_t * fItemsPopped
uint64_t fLastDaqId
uint64_t fLastNetworkPacket
std::map< UInt_t, Long64_t > fLastTimeStampMap
uint64_t fLastTriggerId
const uint64_t fMaxTriggerId
bool fNoWaveforms
bool fRecordDiag
std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > fScalerOutputQueue
EDataParserState fState
Static Private Attributes
static TGRSIOptions * fOptions = nullptr
Member Enumeration Documentation
EBank
enum class TILLDataParser::EBank strong
Enumerator
kWFDN
kGRF1
kGRF2
kGRF3
kGRF4
kFME0
kFME1
kFME2
kFME3
Definition at line 49 of file TILLDataParser.h.
EDataParserState
enum class TILLDataParser::EDataParserState strong
Enumerator
kGood
kBadHeader
kMissingWords
kBadScalerLowTS
kBadScalerValue
kBadScalerHighTS
kBadScalerType
kBadTriggerId
kBadLowTS
kBadHighTS
kSecondHeader
kWrongNofWords
kNotSingleCfd
kSizeMismatch
kBadFooter
kFault
kMissingPsd
kMissingCfd
kMissingCharge
kBadBank
kBadModuleType
kEndOfData
kUndefined
Definition at line 59 of file TILLDataParser.h.
Constructor & Destructor Documentation
TILLDataParser()
TILLDataParser::TILLDataParser ()
Definition at line 19 of file TILLDataParser.cxx.
References fState, and kGood.
~TILLDataParser()
TILLDataParser::~TILLDataParser ()
Definition at line 25 of file TILLDataParser.cxx.
Member Function Documentation
AddGoodOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > & TDataParser::AddGoodOutputQueue (size_t maxSize = 50000) inline virtual inherited
Definition at line 65 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::AddGoodOutputQueue().
BadOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TBadFragment > > > & TDataParser::BadOutputQueue () inline virtual inherited
Definition at line 73 of file TDataParser.h.
References TDataParser::fBadOutputQueue.
Referenced by TUnpackingLoop::BadOutputQueue(), THILDataParser::EagleEventToFragment(), TGRSIDataParser::EmmaTdcDataToFragment(), TGRSIDataParser::GriffinDataToFragment(), TGRSIDataParser::RFScalerToFragment(), TTdrDataParser::TdrToFragment(), V1SingleFippsEventToFragment(), and V2SingleFippsEventToFragment().
Channel()
TChannel * TDataParser::Channel () const inline protected inherited
Definition at line 105 of file TDataParser.h.
References TDataParser::fChannel.
Referenced by TGRSIDataParser::EmmaMadcDataToFragment(), and TGRSIDataParser::SetTIGCharge().
ClearQueue()
void TDataParser::ClearQueue () virtual inherited
Definition at line 32 of file TDataParser.cxx.
References TDataParser::fBadOutputQueue, TDataParser::fGoodOutputQueues, and TDataParser::fScalerOutputQueue.
Referenced by TUnpackingLoop::ClearQueue().
FragmentHasWaveform() [1/2]
bool TDataParser::FragmentHasWaveform () const inline protected inherited
Definition at line 112 of file TDataParser.h.
References TDataParser::fFragmentHasWaveform.
Referenced by TGRSIDataParser::GriffinDataToFragment(), and TGRSIDataParser::SetGRIFPrimaryFilterPattern().
FragmentHasWaveform() [2/2]
void TDataParser::FragmentHasWaveform (const bool & val) inline protected inherited
Definition at line 122 of file TDataParser.h.
References TDataParser::fFragmentHasWaveform.
FragmentMap()
TFragmentMap TDataParser::FragmentMap () const inline protected inherited
Definition at line 114 of file TDataParser.h.
References TDataParser::fFragmentMap.
Referenced by TGRSIDataParser::GriffinDataToFragment().
GoodOutputQueues()
std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & TDataParser::GoodOutputQueues () inline protected inherited
Definition at line 101 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by TGRSIDataParser::CaenPhaToFragment(), TGRSIDataParser::CaenPsdToFragment(), THILDataParser::EagleEventToFragment(), TGRSIDataParser::EmmaMadcDataToFragment(), TGRSIDataParser::EmmaTdcDataToFragment(), TGRSIDataParser::GriffinDataToFragment(), TGRSIDataParser::RFScalerToFragment(), TTdrDataParser::TdrToFragment(), TGRSIDataParser::TigressDataToFragment(), V1SingleFippsEventToFragment(), and V2SingleFippsEventToFragment().
ItemsPushed()
virtual size_t TDataParser::ItemsPushed () inline virtual inherited
Definition at line 88 of file TDataParser.h.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::GetItemsPushed().
LastDaqId()
uint64_t TDataParser::LastDaqId () const inline protected inherited
Definition at line 108 of file TDataParser.h.
References TDataParser::fLastDaqId.
LastNetworkPacket()
uint64_t TDataParser::LastNetworkPacket () const inline protected inherited
Definition at line 110 of file TDataParser.h.
References TDataParser::fLastNetworkPacket.
LastTimeStampMap()
std::map< UInt_t, Long64_t > TDataParser::LastTimeStampMap () const inline protected inherited
Definition at line 115 of file TDataParser.h.
References TDataParser::fLastTimeStampMap.
Referenced by TGRSIDataParser::GriffinDataToFragment().
LastTriggerId() [1/2]
uint64_t TDataParser::LastTriggerId () const inline protected inherited
Definition at line 109 of file TDataParser.h.
References TDataParser::fLastTriggerId.
Referenced by TGRSIDataParser::SetTIGTriggerID().
LastTriggerId() [2/2]
void TDataParser::LastTriggerId (const uint64_t & val) inline protected inherited
Definition at line 120 of file TDataParser.h.
References TDataParser::fLastTriggerId.
MaxTriggerId()
uint64_t TDataParser::MaxTriggerId () const inline protected inherited
Definition at line 107 of file TDataParser.h.
References TDataParser::fMaxTriggerId.
Referenced by TGRSIDataParser::SetTIGTriggerID().
NoWaveforms()
bool TDataParser::NoWaveforms () const inline protected inherited
Definition at line 103 of file TDataParser.h.
References TDataParser::fNoWaveforms.
Referenced by TGRSIDataParser::GriffinDataToFragment(), and TGRSIDataParser::TigressDataToFragment().
Options() [1/2]
static TGRSIOptions * TDataParser::Options () inline static protected inherited
Definition at line 117 of file TDataParser.h.
References TDataParser::fOptions.
Referenced by TGRSIDataParser::CaenPhaToFragment(), TGRSIDataParser::CaenPsdToFragment(), and TGRSIDataParser::GriffinDataToFragment().
Options() [2/2]
static void TDataParser::Options (TGRSIOptions * val) inline static protected inherited
Definition at line 124 of file TDataParser.h.
References TDataParser::fOptions.
OutputQueueStatus()
std::string TDataParser::OutputQueueStatus () virtual inherited
Definition at line 78 of file TDataParser.cxx.
References TDataParser::fGoodOutputQueues.
Referenced by TUnpackingLoop::EndStatus().
Process()
int TILLDataParser::Process (std::shared_ptr< TRawEvent > rawEvent) override virtual
Process this TLstEvent using the provided data parser. Returns the total number of fragments read (good and bad).
Implements TDataParser.
Definition at line 29 of file TILLDataParser.cxx.
References V1SingleFippsEventToFragment(), and V2SingleFippsEventToFragment().
Push() [1/2]
void TDataParser::Push (std::vector< std::shared_ptr< ThreadsafeQueue< std::shared_ptr< const TFragment > > > > & queues, const std::shared_ptr< TFragment > & frag) inherited
Definition at line 59 of file TDataParser.cxx.
References TDataParser::fFragmentIdMap.
Push() [2/2]
void TDataParser::Push (ThreadsafeQueue< std::shared_ptr< const TBadFragment > > & queue, const std::shared_ptr< TBadFragment > & frag) inherited
Definition at line 70 of file TDataParser.cxx.
References TDataParser::fFragmentIdMap.
Referenced by TGRSIDataParser::CaenPhaToFragment(), TGRSIDataParser::CaenPsdToFragment(), THILDataParser::EagleEventToFragment(), TGRSIDataParser::EmmaMadcDataToFragment(), TGRSIDataParser::EmmaTdcDataToFragment(), TGRSIDataParser::GriffinDataToFragment(), TGRSIDataParser::RFScalerToFragment(), TTdrDataParser::TdrToFragment(), TGRSIDataParser::TigressDataToFragment(), V1SingleFippsEventToFragment(), and V2SingleFippsEventToFragment().
RecordDiag()
bool TDataParser::RecordDiag () const inline protected inherited
Definition at line 104 of file TDataParser.h.
References TDataParser::fRecordDiag.
Referenced by THILDataParser::EagleEventToFragment(), TGRSIDataParser::GriffinDataToFragment(), TTdrDataParser::TdrToFragment(), V1SingleFippsEventToFragment(), and V2SingleFippsEventToFragment().
ScalerOutputQueue()
virtual std::shared_ptr< ThreadsafeQueue< std::shared_ptr< TEpicsFrag > > > & TDataParser::ScalerOutputQueue () inline virtual inherited
Definition at line 75 of file TDataParser.h.
References TDataParser::fScalerOutputQueue.
Referenced by TGRSIDataParser::EPIXToScalar(), and TUnpackingLoop::ScalerOutputQueue().
SetFinished()
void TDataParser::SetFinished () virtual inherited
Definition at line 50 of file TDataParser.cxx.
References TDataParser::fBadOutputQueue, TDataParser::fGoodOutputQueues, and TDataParser::fScalerOutputQueue.
Referenced by TUnpackingLoop::Iteration().
SetNoWaveForms()
virtual void TDataParser::SetNoWaveForms (bool temp = true) inline virtual inherited
Definition at line 50 of file TDataParser.h.
References TDataParser::fNoWaveforms.
Referenced by TUnpackingLoop::SetNoWaveForms().
SetRecordDiag()
virtual void TDataParser::SetRecordDiag (bool temp = true) inline virtual inherited
Definition at line 51 of file TDataParser.h.
References TDataParser::fRecordDiag.
Referenced by TUnpackingLoop::SetRecordDiag().
SetStatusVariables()
virtual void TDataParser::SetStatusVariables (std::atomic_size_t * itemsPopped, std::atomic_long * inputSize) inline virtual inherited
Definition at line 77 of file TDataParser.h.
References TDataParser::fInputSize, and TDataParser::fItemsPopped.
Referenced by TUnpackingLoop::Iteration().
V1SingleFippsEventToFragment()
int TILLDataParser::V1SingleFippsEventToFragment (uint32_t * data) private
Definition at line 55 of file TILLDataParser.cxx.
References TParsingDiagnostics::BadFragment(), TDataParser::BadOutputQueue(), DRED, TSingleton< TParsingDiagnostics >::Get(), TParsingDiagnostics::GoodFragment(), TDataParser::GoodOutputQueues(), hex(), kV1724, kV1725, TDataParser::Push(), and TDataParser::RecordDiag().
Referenced by Process().
V2SingleFippsEventToFragment()
int TILLDataParser::V2SingleFippsEventToFragment (uint32_t * data) private
Definition at line 107 of file TILLDataParser.cxx.
References TParsingDiagnostics::BadFragment(), TDataParser::BadOutputQueue(), TSingleton< TParsingDiagnostics >::Get(), TParsingDiagnostics::GoodFragment(), TDataParser::GoodOutputQueues(), TDataParser::Push(), and TDataParser::RecordDiag().
Referenced by Process().
Member Data Documentation
fBadOutputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TBadFragment> > > TDataParser::fBadOutputQueue private inherited
Definition at line 130 of file TDataParser.h.
Referenced by TDataParser::BadOutputQueue(), TDataParser::ClearQueue(), and TDataParser::SetFinished().
fChannel
TChannel* TDataParser::fChannel private inherited
Definition at line 136 of file TDataParser.h.
Referenced by TDataParser::~TDataParser(), and TDataParser::Channel().
fFragmentHasWaveform
bool TDataParser::fFragmentHasWaveform private inherited
Definition at line 144 of file TDataParser.h.
Referenced by TDataParser::FragmentHasWaveform(), and TDataParser::FragmentHasWaveform().
fFragmentIdMap
std::map<Long_t, int> TDataParser::fFragmentIdMap private inherited
Definition at line 143 of file TDataParser.h.
Referenced by TDataParser::Push(), and TDataParser::Push().
fFragmentMap
TFragmentMap TDataParser::fFragmentMap private inherited
Class that holds a map of fragments per address, takes care of calculating charges for GRF4 banks.
Definition at line 146 of file TDataParser.h.
Referenced by TDataParser::FragmentMap().
fGoodOutputQueues
std::vector<std::shared_ptr<ThreadsafeQueue<std::shared_ptr<const TFragment> > > > TDataParser::fGoodOutputQueues private inherited
Definition at line 129 of file TDataParser.h.
Referenced by TDataParser::AddGoodOutputQueue(), TDataParser::ClearQueue(), TDataParser::GoodOutputQueues(), TDataParser::ItemsPushed(), TDataParser::OutputQueueStatus(), and TDataParser::SetFinished().
fInputSize
std::atomic_long* TDataParser::fInputSize private inherited
Definition at line 154 of file TDataParser.h.
Referenced by TDataParser::SetStatusVariables().
fItemsPopped
std::atomic_size_t* TDataParser::fItemsPopped private inherited
Definition at line 153 of file TDataParser.h.
Referenced by TDataParser::SetStatusVariables().
fLastDaqId
uint64_t TDataParser::fLastDaqId private inherited
The last daq ID in the raw file.
Definition at line 139 of file TDataParser.h.
Referenced by TDataParser::LastDaqId().
fLastNetworkPacket
uint64_t TDataParser::fLastNetworkPacket private inherited
The last network packet recieved.
Definition at line 141 of file TDataParser.h.
Referenced by TDataParser::LastNetworkPacket().
fLastTimeStampMap
std::map<UInt_t, Long64_t> TDataParser::fLastTimeStampMap private inherited
Definition at line 148 of file TDataParser.h.
Referenced by TDataParser::LastTimeStampMap().
fLastTriggerId
uint64_t TDataParser::fLastTriggerId private inherited
The last Trigged ID in the raw File.
Definition at line 140 of file TDataParser.h.
Referenced by TDataParser::LastTriggerId(), and TDataParser::LastTriggerId().
fMaxTriggerId
const uint64_t TDataParser::fMaxTriggerId private inherited
The last trigger ID Called.
Definition at line 138 of file TDataParser.h.
Referenced by TDataParser::MaxTriggerId().
fNoWaveforms
bool TDataParser::fNoWaveforms private inherited
The flag to turn wave_forms on or off.
Definition at line 134 of file TDataParser.h.
Referenced by TDataParser::NoWaveforms(), and TDataParser::SetNoWaveForms().
fOptions
TGRSIOptions * TDataParser::fOptions = nullptr static private inherited
Static pointer to TGRSIOptions, gets set on the first call of GriffinDataToFragment.
Definition at line 150 of file TDataParser.h.
Referenced by TDataParser::Options(), and TDataParser::Options().
fRecordDiag
bool TDataParser::fRecordDiag private inherited
The flag to turn on diagnostics recording.
Definition at line 135 of file TDataParser.h.
Referenced by TDataParser::RecordDiag(), and TDataParser::SetRecordDiag().
fScalerOutputQueue
std::shared_ptr<ThreadsafeQueue<std::shared_ptr<TEpicsFrag> > > TDataParser::fScalerOutputQueue private inherited
Definition at line 131 of file TDataParser.h.
Referenced by TDataParser::ClearQueue(), TDataParser::ScalerOutputQueue(), and TDataParser::SetFinished().
fState
EDataParserState TILLDataParser::fState private
Definition at line 93 of file TILLDataParser.h.
Referenced by TILLDataParser().