GRSISort: TBgo Class Reference
TBgo Class Reference
Detectors
Definition at line 22 of file TBgo.h.
Public Member Functions
TBgo ()
TBgo (const TBgo &)
virtual ~TBgo ()
void AddFragment (const std::shared_ptr< const TFragment > &frag, TChannel *chan) override
virtual void AddHit (TDetectorHit *hit)
void BuildHits () override
virtual void Clear (Option_t *opt="all") override
virtual void ClearTransients ()
virtual void Copy (TObject &) const override
TBgoHit * GetBgoHit (const Int_t &i)
virtual TDetectorHit * GetHit (const int &) const
virtual const std::vector< TDetectorHit * > & GetHitVector () const
virtual Short_t GetMultiplicity () const
TBgo & operator= (const TBgo &)
virtual void Print (Option_t *opt="") const override
virtual void Print (std::ostream &out) const override
Static Public Member Functions
static TVector3 GetPosition (int DetNbr, int CryNbr=5, double distance=110.0)
Protected Attributes
std::vector< TDetectorHit * > fHits
Static Private Attributes
static TVector3 gScintPosition [17]
#include <TBgo.h>
Constructor & Destructor Documentation
TBgo() [1/2]
TBgo::TBgo ()
Default ctor.
Definition at line 96 of file TBgo.cxx.
References Clear().
TBgo() [2/2]
TBgo::TBgo (const TBgo & rhs)
Copy ctor.
Definition at line 102 of file TBgo.cxx.
References Copy().
~TBgo()
TBgo::~TBgo () virtual
Definition at line 114 of file TBgo.cxx.
Member Function Documentation
AddFragment()
void TBgo::AddFragment (const std::shared_ptr< const TFragment > & frag, TChannel * chan) override virtual
!
Reimplemented from TDetector.
Definition at line 144 of file TBgo.cxx.
References TDetector::fHits.
AddHit()
virtual void TDetector::AddHit (TDetectorHit * hit) inline virtual inherited
Definition at line 56 of file TDetector.h.
References TDetector::fHits.
BuildHits()
void TBgo::BuildHits () inline override virtual
!
Reimplemented from TDetector.
Definition at line 34 of file TBgo.h.
Clear()
void TBgo::Clear (Option_t * opt = "all") override virtual
!
Clears the mother, and all of the hits
Definition at line 119 of file TBgo.cxx.
References TDetector::Clear().
Referenced by TBgo().
ClearTransients()
void TDetector::ClearTransients () virtual inherited
!
Definition at line 64 of file TDetector.cxx.
References TDetector::fHits.
Copy()
void TBgo::Copy (TObject & rhs) const override virtual
!
Reimplemented from TDetector.
Definition at line 108 of file TBgo.cxx.
References TDetector::Copy().
Referenced by TBgo(), and operator=().
GetBgoHit()
TBgoHit * TBgo::GetBgoHit (const Int_t & i) inline
Definition at line 28 of file TBgo.h.
References TDetector::GetHit().
GetHit()
TDetectorHit * TDetector::GetHit (const int & i) const virtual inherited
Definition at line 71 of file TDetector.cxx.
References TDetector::fHits.
Referenced by GetBgoHit().
GetHitVector()
virtual const std::vector< TDetectorHit * > & TDetector::GetHitVector () const inline virtual inherited
Definition at line 65 of file TDetector.h.
References TDetector::fHits.
Referenced by TSuppressed::CreateSuppressed(), and TSuppressed::CreateSuppressedAddback().
GetMultiplicity()
virtual Short_t TDetector::GetMultiplicity () const inline virtual inherited
Definition at line 63 of file TDetector.h.
References TDetector::fHits.
Referenced by Print().
GetPosition()
TVector3 TBgo::GetPosition (int DetNbr, int CryNbr = 5, double distance = 110.0) static
!
Definition at line 156 of file TBgo.cxx.
References gScintPosition.
operator=()
TBgo & TBgo::operator= (const TBgo & rhs)
!
Definition at line 138 of file TBgo.cxx.
References Copy().
Print() [1/2]
void TBgo::Print (Option_t * opt = "") const override virtual
!
Definition at line 125 of file TBgo.cxx.
References Print().
Referenced by Print().
Print() [2/2]
void TBgo::Print (std::ostream & out) const override virtual
!
Reimplemented from TDetector.
Definition at line 130 of file TBgo.cxx.
References TDetector::GetMultiplicity().
Member Data Documentation
fHits
std::vector<TDetectorHit*> TDetector::fHits protected inherited
Definition at line 73 of file TDetector.h.
Referenced by TDetector::~TDetector(), AddFragment(), TDetector::AddHit(), TDetector::Clear(), TDetector::ClearTransients(), TDetector::Copy(), TDetector::GetHit(), TDetector::GetHitVector(), TDetector::GetMultiplicity(), and TDetector::Print().
gScintPosition
TVector3 TBgo::gScintPosition static private
! Position of each BGO scintillator
Definition at line 40 of file TBgo.h.
Referenced by GetPosition().
GRSISort () Reference Guide Generated on Thu May 9 2024 20:43:26.