GRSISort: TUnpackedEvent Class Reference
TUnpackedEvent Class Reference
Detailed Description
Definition at line 18 of file TUnpackedEvent.h.
Public Member Functions
TUnpackedEvent ()
TUnpackedEvent (const TUnpackedEvent &)=default
TUnpackedEvent (TUnpackedEvent &&) noexcept=default
~TUnpackedEvent ()
void AddDetector (const std::shared_ptr< TDetector > &det)
void AddRawData (const std::shared_ptr< const TFragment > &frag)
void Build ()
void ClearRawData ()
template<typename T >
std::shared_ptr< T > GetDetector (bool make_if_not_found=false)
std::shared_ptr< TDetector > GetDetector (TClass *cls, bool make_if_not_found=false)
std::vector< std::shared_ptr< TDetector > > & GetDetectors ()
TUnpackedEvent & operator= (const TUnpackedEvent &)=default
TUnpackedEvent & operator= (TUnpackedEvent &&) noexcept=default
void SetRawData (const std::vector< std::shared_ptr< const TFragment > > &fragments)
size_t Size ()
Private Member Functions
void BuildHits ()
Private Attributes
std::vector< std::shared_ptr< TDetector > > fDetectors
std::vector< std::shared_ptr< const TFragment > > fFragments
Constructor & Destructor Documentation
TUnpackedEvent() [1/3]
TUnpackedEvent::TUnpackedEvent () default
~TUnpackedEvent()
TUnpackedEvent::~TUnpackedEvent () default
TUnpackedEvent() [2/3]
TUnpackedEvent::TUnpackedEvent (const TUnpackedEvent &) default
TUnpackedEvent() [3/3]
TUnpackedEvent::TUnpackedEvent (TUnpackedEvent &&) default noexcept
Member Function Documentation
AddDetector()
void TUnpackedEvent::AddDetector (const std::shared_ptr< TDetector > & det) inline
Definition at line 34 of file TUnpackedEvent.h.
References fDetectors.
AddRawData()
void TUnpackedEvent::AddRawData (const std::shared_ptr< const TFragment > & frag)
Definition at line 35 of file TUnpackedEvent.cxx.
References fFragments.
Build()
void TUnpackedEvent::Build ()
Definition at line 12 of file TUnpackedEvent.cxx.
References TSortingDiagnostics::AddDetectorClass(), BuildHits(), ClearRawData(), fFragments, TSingleton< TSortingDiagnostics >::Get(), TChannel::GetChannel(), TChannel::GetClassType(), GetDetector(), and TSortingDiagnostics::MissingChannel().
BuildHits()
void TUnpackedEvent::BuildHits () private
Definition at line 45 of file TUnpackedEvent.cxx.
References fDetectors.
Referenced by Build().
ClearRawData()
void TUnpackedEvent::ClearRawData ()
Definition at line 40 of file TUnpackedEvent.cxx.
References fFragments.
Referenced by Build().
GetDetector() [1/2]
template<typename T > std::shared_ptr< T > TUnpackedEvent::GetDetector (bool make_if_not_found = false)
Definition at line 59 of file TUnpackedEvent.h.
References fDetectors.
Referenced by Build().
GetDetector() [2/2]
std::shared_ptr< TDetector > TUnpackedEvent::GetDetector (TClass * cls, bool make_if_not_found = false)
Definition at line 52 of file TUnpackedEvent.cxx.
References fDetectors.
GetDetectors()
std::vector< std::shared_ptr< TDetector > > & TUnpackedEvent::GetDetectors () inline
Definition at line 33 of file TUnpackedEvent.h.
References fDetectors.
operator=() [1/2]
TUnpackedEvent & TUnpackedEvent::operator= (const TUnpackedEvent &) default
operator=() [2/2]
TUnpackedEvent & TUnpackedEvent::operator= (TUnpackedEvent &&) default noexcept
SetRawData()
void TUnpackedEvent::SetRawData (const std::vector< std::shared_ptr< const TFragment > > & fragments) inline
Definition at line 36 of file TUnpackedEvent.h.
References fFragments.
Size()
size_t TUnpackedEvent::Size () inline
Definition at line 42 of file TUnpackedEvent.h.
References fDetectors.
Member Data Documentation
fDetectors
std::vector<std::shared_ptr<TDetector> > TUnpackedEvent::fDetectors private
Definition at line 53 of file TUnpackedEvent.h.
Referenced by AddDetector(), BuildHits(), GetDetector(), GetDetector(), GetDetectors(), and Size().
fFragments
std::vector<std::shared_ptr<const TFragment> > TUnpackedEvent::fFragments private
Definition at line 52 of file TUnpackedEvent.h.
Referenced by AddRawData(), Build(), ClearRawData(), and SetRawData().