GRSISort: TAB3Peak Class Reference
TAB3Peak Class Reference
Fitting & Analysis
Detailed Description
This class is used to fit Addback peaks in data
Definition at line 27 of file TAB3Peak.h.
Public Member Functions
TAB3Peak ()=default
TAB3Peak (const TAB3Peak &)=default
TAB3Peak (Double_t centroid)
TAB3Peak (TAB3Peak &&) noexcept=default
~TAB3Peak ()=default
Double_t Area () const
Double_t AreaErr () const
Double_t Centroid () const override
void Centroid (const Double_t &centroid) override
Double_t CentroidErr () const override
void Draw (Option_t *opt="") override
virtual void DrawBackground (Option_t *opt="")
void DrawComponents (Option_t *opt="") override
virtual Double_t FWHM ()
TF1 * GetBackgroundFunction ()
Double_t GetChi2 () const
TF1 * GetFitFunction () const
TF1 * GetGlobalBackground () const
Double_t GetNDF () const
Int_t GetNParameters () const
TF1 * GetPeakFunction () const
Double_t GetReducedChi2 () const
void InitializeParameters (TH1 *hist, const double &rangeLow, const double &rangeHigh) override
void InitParNames () override
bool IsBackgroundParameter (const Int_t &par) const
bool IsPeakParameter (const Int_t &par) const
TAB3Peak & operator= (const TAB3Peak &)=default
TAB3Peak & operator= (TAB3Peak &&) noexcept=default
bool ParameterSetByUser (int par)
void Print (Option_t *="") const override
virtual void PrintParameters () const
void SetArea (const Double_t &area)
void SetAreaErr (const Double_t &area_err)
void SetGlobalBackground (TF1 *background)
void SetListOfBGPar (const std::vector< bool > &list_of_bg_par)
Double_t Sigma () const override
void UpdateBackgroundParameters ()
void UpdatePeakParameters ()
Double_t Width () const override
Protected Member Functions
Double_t BackgroundFunction (Double_t *dim, Double_t *par) override
Double_t PeakFunction (Double_t *dim, Double_t *par) override
virtual Double_t PeakOnGlobalFunction (Double_t *dim, Double_t *par)
void SetChi2 (const Double_t &chi2)
void SetFitFunction (TF1 *function)
void SetNDF (const Int_t &ndf)
void SetPeakFunction (TF1 *function)
Double_t TotalFunction (Double_t *dim, Double_t *par)
Private Member Functions
Double_t OneHitPeakOnGlobalFunction (Double_t *dim, Double_t *par)
Double_t ThreeHitPeakOnGlobalFunction (Double_t *dim, Double_t *par)
Double_t TwoHitPeakOnGlobalFunction (Double_t *dim, Double_t *par)
Static Private Member Functions
static Double_t OneHitPeakFunction (Double_t *dim, Double_t *par)
static Double_t ThreeHitPeakFunction (Double_t *dim, Double_t *par)
static Double_t TwoHitPeakFunction (Double_t *dim, Double_t *par)
Private Attributes
Double_t fArea {-0.1}
Double_t fAreaErr {0.0}
TF1 * fBackgroundFunction {nullptr}
Double_t fChi2 {std::numeric_limits<Double_t>::quiet_NaN()}
TF1 * fGlobalBackground {nullptr}
std::vector< bool > fListOfBGPars
Int_t fNDF {0}
TF1 * fOneHitOnGlobal {nullptr}
TF1 * fPeakFunction {nullptr}
TF1 * fPeakOnGlobal {nullptr}
TF1 * fThreeHitOnGlobal {nullptr}
TF1 * fTotalFunction {nullptr}
TF1 * fTwoHitOnGlobal {nullptr}
Constructor & Destructor Documentation
TAB3Peak() [1/4]
TAB3Peak::TAB3Peak () default
TAB3Peak() [2/4]
TAB3Peak::TAB3Peak (Double_t centroid) inline explicit
Definition at line 31 of file TAB3Peak.h.
References Centroid().
TAB3Peak() [3/4]
TAB3Peak::TAB3Peak (const TAB3Peak &) default
TAB3Peak() [4/4]
TAB3Peak::TAB3Peak (TAB3Peak &&) default noexcept
~TAB3Peak()
TAB3Peak::~TAB3Peak () default
Member Function Documentation
Area()
Double_t TSinglePeak::Area () const inline inherited
Definition at line 57 of file TSinglePeak.h.
References TSinglePeak::fArea.
Referenced by main(), and TSinglePeak::Print().
AreaErr()
Double_t TSinglePeak::AreaErr () const inline inherited
Definition at line 58 of file TSinglePeak.h.
References TSinglePeak::fAreaErr.
Referenced by main(), and TSinglePeak::Print().
BackgroundFunction()
Double_t TAB3Peak::BackgroundFunction (Double_t * dim, Double_t * par) override protected virtual
Reimplemented from TSinglePeak.
Definition at line 143 of file TAB3Peak.cxx.
Centroid() [1/2]
Double_t TAB3Peak::Centroid () const override virtual
Implements TSinglePeak.
Definition at line 69 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction().
Referenced by TAB3Peak().
Centroid() [2/2]
void TAB3Peak::Centroid (const Double_t & centroid) override virtual
Implements TSinglePeak.
Definition at line 4 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction(), InitParNames(), PeakFunction(), TSinglePeak::SetFitFunction(), TSinglePeak::SetListOfBGPar(), TSinglePeak::SetPeakFunction(), and TSinglePeak::TotalFunction().
CentroidErr()
Double_t TAB3Peak::CentroidErr () const override virtual
Implements TSinglePeak.
Definition at line 74 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction().
Draw()
void TSinglePeak::Draw (Option_t * opt = "") override inherited
Definition at line 99 of file TSinglePeak.cxx.
References TSinglePeak::fGlobalBackground, TSinglePeak::fPeakOnGlobal, TSinglePeak::fTotalFunction, and TSinglePeak::PeakOnGlobalFunction().
Referenced by TBGSubtraction::DrawPeak().
DrawBackground()
virtual void TSinglePeak::DrawBackground (Option_t * opt = "") inline virtual inherited
Definition at line 69 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
DrawComponents()
void TAB3Peak::DrawComponents (Option_t * opt = "") override virtual
Reimplemented from TSinglePeak.
Definition at line 156 of file TAB3Peak.cxx.
References fOneHitOnGlobal, fThreeHitOnGlobal, fTwoHitOnGlobal, TSinglePeak::GetFitFunction(), TSinglePeak::GetGlobalBackground(), OneHitPeakOnGlobalFunction(), ThreeHitPeakOnGlobalFunction(), and TwoHitPeakOnGlobalFunction().
FWHM()
Double_t TSinglePeak::FWHM () virtual inherited
Return the full width at half-maximum.
Definition at line 77 of file TSinglePeak.cxx.
References TSinglePeak::Centroid(), TSinglePeak::fPeakFunction, TSinglePeak::Sigma(), and TSinglePeak::UpdatePeakParameters().
GetBackgroundFunction()
TF1 * TSinglePeak::GetBackgroundFunction () inherited
Definition at line 28 of file TSinglePeak.cxx.
References TSinglePeak::BackgroundFunction(), TSinglePeak::fBackgroundFunction, and TSinglePeak::fTotalFunction.
GetChi2()
Double_t TSinglePeak::GetChi2 () const inline inherited
Definition at line 89 of file TSinglePeak.h.
References TSinglePeak::fChi2.
GetFitFunction()
TF1 * TSinglePeak::GetFitFunction () const inline inherited
Definition at line 76 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by TGauss::TGauss(), Centroid(), TABPeak::Centroid(), TGauss::Centroid(), TRWPeak::Centroid(), Centroid(), TABPeak::Centroid(), TGauss::Centroid(), TRWPeak::Centroid(), CentroidErr(), TABPeak::CentroidErr(), TGauss::CentroidErr(), TRWPeak::CentroidErr(), DrawComponents(), TABPeak::DrawComponents(), InitializeParameters(), TABPeak::InitializeParameters(), TGauss::InitializeParameters(), TRWPeak::InitializeParameters(), InitParNames(), TABPeak::InitParNames(), TGauss::InitParNames(), TRWPeak::InitParNames(), main(), OneHitPeakOnGlobalFunction(), TABPeak::OneHitPeakOnGlobalFunction(), Sigma(), TABPeak::Sigma(), TGauss::Sigma(), TRWPeak::Sigma(), ThreeHitPeakOnGlobalFunction(), TwoHitPeakOnGlobalFunction(), TABPeak::TwoHitPeakOnGlobalFunction(), Width(), TABPeak::Width(), and TRWPeak::Width().
GetGlobalBackground()
TF1 * TSinglePeak::GetGlobalBackground () const inline inherited
Definition at line 78 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
Referenced by DrawComponents(), TABPeak::DrawComponents(), OneHitPeakOnGlobalFunction(), TABPeak::OneHitPeakOnGlobalFunction(), ThreeHitPeakOnGlobalFunction(), TwoHitPeakOnGlobalFunction(), and TABPeak::TwoHitPeakOnGlobalFunction().
GetNDF()
Double_t TSinglePeak::GetNDF () const inline inherited
Definition at line 90 of file TSinglePeak.h.
References TSinglePeak::fNDF.
GetNParameters()
Int_t TSinglePeak::GetNParameters () const inherited
Definition at line 20 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
GetPeakFunction()
TF1 * TSinglePeak::GetPeakFunction () const inline inherited
Definition at line 77 of file TSinglePeak.h.
References TSinglePeak::fPeakFunction.
GetReducedChi2()
Double_t TSinglePeak::GetReducedChi2 () const inline inherited
Definition at line 91 of file TSinglePeak.h.
References TSinglePeak::fChi2, and TSinglePeak::fNDF.
Referenced by main().
InitializeParameters()
void TAB3Peak::InitializeParameters (TH1 * hist, const double & rangeLow, const double & rangeHigh) override virtual
Makes initial guesses at parameters for the fit base on the histogram.
Reimplemented from TSinglePeak.
Definition at line 26 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction(), and TSinglePeak::ParameterSetByUser().
InitParNames()
void TAB3Peak::InitParNames () override virtual
Reimplemented from TSinglePeak.
Definition at line 14 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction().
Referenced by Centroid().
IsBackgroundParameter()
bool TSinglePeak::IsBackgroundParameter (const Int_t & par) const inherited
Definition at line 4 of file TSinglePeak.cxx.
References TSinglePeak::fListOfBGPars.
Referenced by TSinglePeak::IsPeakParameter().
IsPeakParameter()
bool TSinglePeak::IsPeakParameter (const Int_t & par) const inherited
Definition at line 15 of file TSinglePeak.cxx.
References TSinglePeak::IsBackgroundParameter().
OneHitPeakFunction()
Double_t TAB3Peak::OneHitPeakFunction (Double_t * dim, Double_t * par) static private
Definition at line 94 of file TAB3Peak.cxx.
Referenced by OneHitPeakOnGlobalFunction(), and PeakFunction().
OneHitPeakOnGlobalFunction()
Double_t TAB3Peak::OneHitPeakOnGlobalFunction (Double_t * dim, Double_t * par) private
Definition at line 128 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction(), TSinglePeak::GetGlobalBackground(), and OneHitPeakFunction().
Referenced by DrawComponents().
operator=() [1/2]
TAB3Peak & TAB3Peak::operator= (const TAB3Peak &) default
operator=() [2/2]
TAB3Peak & TAB3Peak::operator= (TAB3Peak &&) default noexcept
ParameterSetByUser()
bool TSinglePeak::ParameterSetByUser (int par) inherited
This function checks if a parameter or its limits have been set to a non-zero value. In case that the user fixed a parameter to be zero, the limits are non-zero, so this case is covered as well.
Definition at line 122 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
Referenced by InitializeParameters(), TABPeak::InitializeParameters(), TGauss::InitializeParameters(), and TRWPeak::InitializeParameters().
PeakFunction()
Double_t TAB3Peak::PeakFunction (Double_t * dim, Double_t * par) override protected virtual
Reimplemented from TSinglePeak.
Definition at line 89 of file TAB3Peak.cxx.
References OneHitPeakFunction(), ThreeHitPeakFunction(), and TwoHitPeakFunction().
Referenced by Centroid().
PeakOnGlobalFunction()
Double_t TSinglePeak::PeakOnGlobalFunction (Double_t * dim, Double_t * par) protected virtual inherited
Definition at line 92 of file TSinglePeak.cxx.
References TSinglePeak::fGlobalBackground, TSinglePeak::fTotalFunction, and TSinglePeak::PeakFunction().
Referenced by TSinglePeak::Draw().
Print()
void TSinglePeak::Print (Option_t * = "") const override inherited
Definition at line 37 of file TSinglePeak.cxx.
References TSinglePeak::Area(), TSinglePeak::AreaErr(), TSinglePeak::Centroid(), and TSinglePeak::CentroidErr().
PrintParameters()
void TSinglePeak::PrintParameters () const virtual inherited
Definition at line 45 of file TSinglePeak.cxx.
References TSinglePeak::fTotalFunction.
SetArea()
void TSinglePeak::SetArea (const Double_t & area) inline inherited
Definition at line 54 of file TSinglePeak.h.
References TSinglePeak::fArea.
SetAreaErr()
void TSinglePeak::SetAreaErr (const Double_t & area_err) inline inherited
Definition at line 55 of file TSinglePeak.h.
References TSinglePeak::fAreaErr.
SetChi2()
void TSinglePeak::SetChi2 (const Double_t & chi2) inline protected inherited
Definition at line 101 of file TSinglePeak.h.
References TSinglePeak::fChi2.
SetFitFunction()
void TSinglePeak::SetFitFunction (TF1 * function) inline protected inherited
Definition at line 104 of file TSinglePeak.h.
References TSinglePeak::fTotalFunction.
Referenced by Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and TRWPeak::Centroid().
SetGlobalBackground()
void TSinglePeak::SetGlobalBackground (TF1 * background) inline inherited
Definition at line 80 of file TSinglePeak.h.
References TSinglePeak::fGlobalBackground.
SetListOfBGPar()
void TSinglePeak::SetListOfBGPar (const std::vector< bool > & list_of_bg_par) inline inherited
Definition at line 51 of file TSinglePeak.h.
References TSinglePeak::fListOfBGPars.
Referenced by Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and TRWPeak::Centroid().
SetNDF()
void TSinglePeak::SetNDF (const Int_t & ndf) inline protected inherited
Definition at line 102 of file TSinglePeak.h.
References TSinglePeak::fNDF.
SetPeakFunction()
void TSinglePeak::SetPeakFunction (TF1 * function) inline protected inherited
Definition at line 105 of file TSinglePeak.h.
References TSinglePeak::fPeakFunction.
Referenced by Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and TRWPeak::Centroid().
Sigma()
Double_t TAB3Peak::Sigma () const override virtual
Implements TSinglePeak.
Definition at line 84 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction().
ThreeHitPeakFunction()
Double_t TAB3Peak::ThreeHitPeakFunction (Double_t * dim, Double_t * par) static private
Definition at line 116 of file TAB3Peak.cxx.
Referenced by PeakFunction(), and ThreeHitPeakOnGlobalFunction().
ThreeHitPeakOnGlobalFunction()
Double_t TAB3Peak::ThreeHitPeakOnGlobalFunction (Double_t * dim, Double_t * par) private
Definition at line 138 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction(), TSinglePeak::GetGlobalBackground(), and ThreeHitPeakFunction().
Referenced by DrawComponents().
TotalFunction()
Double_t TSinglePeak::TotalFunction (Double_t * dim, Double_t * par) protected inherited
Definition at line 56 of file TSinglePeak.cxx.
References TSinglePeak::BackgroundFunction(), and TSinglePeak::PeakFunction().
Referenced by Centroid(), TABPeak::Centroid(), TGauss::Centroid(), and TRWPeak::Centroid().
TwoHitPeakFunction()
Double_t TAB3Peak::TwoHitPeakFunction (Double_t * dim, Double_t * par) static private
Definition at line 104 of file TAB3Peak.cxx.
Referenced by PeakFunction(), and TwoHitPeakOnGlobalFunction().
TwoHitPeakOnGlobalFunction()
Double_t TAB3Peak::TwoHitPeakOnGlobalFunction (Double_t * dim, Double_t * par) private
Definition at line 133 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction(), TSinglePeak::GetGlobalBackground(), and TwoHitPeakFunction().
Referenced by DrawComponents().
UpdateBackgroundParameters()
void TSinglePeak::UpdateBackgroundParameters () inherited
Definition at line 66 of file TSinglePeak.cxx.
References TSinglePeak::fBackgroundFunction, and TSinglePeak::fTotalFunction.
UpdatePeakParameters()
void TSinglePeak::UpdatePeakParameters () inherited
Definition at line 61 of file TSinglePeak.cxx.
References TSinglePeak::fPeakFunction, and TSinglePeak::fTotalFunction.
Referenced by TSinglePeak::FWHM().
Width()
Double_t TAB3Peak::Width () const override virtual
Implements TSinglePeak.
Definition at line 79 of file TAB3Peak.cxx.
References TSinglePeak::GetFitFunction().
Member Data Documentation
fArea
Double_t TSinglePeak::fArea {-0.1} private inherited
Definition at line 115 of file TSinglePeak.h.
Referenced by TSinglePeak::Area(), and TSinglePeak::SetArea().
fAreaErr
Double_t TSinglePeak::fAreaErr {0.0} private inherited
Definition at line 116 of file TSinglePeak.h.
Referenced by TSinglePeak::AreaErr(), and TSinglePeak::SetAreaErr().
fBackgroundFunction
TF1* TSinglePeak::fBackgroundFunction {nullptr} private inherited
Definition at line 109 of file TSinglePeak.h.
Referenced by TSinglePeak::GetBackgroundFunction(), and TSinglePeak::UpdateBackgroundParameters().
fChi2
Double_t TSinglePeak::fChi2 {std::numeric_limits<Double_t>::quiet_NaN()} private inherited
Definition at line 117 of file TSinglePeak.h.
Referenced by TSinglePeak::GetChi2(), TSinglePeak::GetReducedChi2(), and TSinglePeak::SetChi2().
fGlobalBackground
TF1* TSinglePeak::fGlobalBackground {nullptr} private inherited
Definition at line 110 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw(), TSinglePeak::DrawBackground(), TSinglePeak::GetGlobalBackground(), TSinglePeak::PeakOnGlobalFunction(), and TSinglePeak::SetGlobalBackground().
fListOfBGPars
std::vector<bool> TSinglePeak::fListOfBGPars private inherited
Definition at line 114 of file TSinglePeak.h.
Referenced by TSinglePeak::IsBackgroundParameter(), and TSinglePeak::SetListOfBGPar().
fNDF
Int_t TSinglePeak::fNDF {0} private inherited
Definition at line 118 of file TSinglePeak.h.
Referenced by TSinglePeak::GetNDF(), TSinglePeak::GetReducedChi2(), and TSinglePeak::SetNDF().
fOneHitOnGlobal
TF1* TAB3Peak::fOneHitOnGlobal {nullptr} private
Definition at line 62 of file TAB3Peak.h.
Referenced by DrawComponents().
fPeakFunction
TF1* TSinglePeak::fPeakFunction {nullptr} private inherited
Definition at line 112 of file TSinglePeak.h.
Referenced by TSinglePeak::FWHM(), TSinglePeak::GetPeakFunction(), TSinglePeak::SetPeakFunction(), and TSinglePeak::UpdatePeakParameters().
fPeakOnGlobal
TF1* TSinglePeak::fPeakOnGlobal {nullptr} private inherited
Definition at line 111 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw().
fThreeHitOnGlobal
TF1* TAB3Peak::fThreeHitOnGlobal {nullptr} private
Definition at line 64 of file TAB3Peak.h.
Referenced by DrawComponents().
fTotalFunction
TF1* TSinglePeak::fTotalFunction {nullptr} private inherited
Definition at line 108 of file TSinglePeak.h.
Referenced by TSinglePeak::Draw(), TSinglePeak::GetBackgroundFunction(), TSinglePeak::GetFitFunction(), TSinglePeak::GetNParameters(), TSinglePeak::ParameterSetByUser(), TSinglePeak::PeakOnGlobalFunction(), TSinglePeak::PrintParameters(), TSinglePeak::SetFitFunction(), TSinglePeak::UpdateBackgroundParameters(), and TSinglePeak::UpdatePeakParameters().
fTwoHitOnGlobal
TF1* TAB3Peak::fTwoHitOnGlobal {nullptr} private
Definition at line 63 of file TAB3Peak.h.
Referenced by DrawComponents().