GRSISort: GUI
GUI
Classes
class TBGSubtraction
class TCalibrateDescant
class TParameterInput
Functions
double FullEdge (double *x, double *par)
double MaximumRecoilEnergy (double gammaEnergy)
double SourceEnergy (const TCalibrateDescant::ESourceType &source)
double SourceEnergyUncertainty (const TCalibrateDescant::ESourceType &source)
Detailed Description
Function Documentation
FullEdge()
double FullEdge (double * x, double * par)
Definition at line 68 of file TCalibrateDescant.cxx.
Referenced by TCalibrateDescant::CreateGraphicMembers().
MaximumRecoilEnergy()
double MaximumRecoilEnergy (double gammaEnergy)
Definition at line 5 of file TCalibrateDescant.cxx.
Referenced by SourceEnergy(), and SourceEnergyUncertainty().
SourceEnergy()
double SourceEnergy (const TCalibrateDescant::ESourceType & source)
Definition at line 10 of file TCalibrateDescant.cxx.
References TCalibrateDescant::k137Cs, TCalibrateDescant::k152Eu121, TCalibrateDescant::k152Eu1408, TCalibrateDescant::k152Eu344, TCalibrateDescant::k22NaHigh, TCalibrateDescant::k22NaLow, TCalibrateDescant::k241Am, TCalibrateDescant::k241AmEdge, TCalibrateDescant::k24NaHigh, TCalibrateDescant::k24NaLow, TCalibrateDescant::k60Co, and MaximumRecoilEnergy().
Referenced by TCalibrateDescant::AddCalibrationPoint().
SourceEnergyUncertainty()
double SourceEnergyUncertainty (const TCalibrateDescant::ESourceType & source)
Definition at line 39 of file TCalibrateDescant.cxx.
References TCalibrateDescant::k137Cs, TCalibrateDescant::k152Eu121, TCalibrateDescant::k152Eu1408, TCalibrateDescant::k152Eu344, TCalibrateDescant::k22NaHigh, TCalibrateDescant::k22NaLow, TCalibrateDescant::k241Am, TCalibrateDescant::k241AmEdge, TCalibrateDescant::k24NaHigh, TCalibrateDescant::k24NaLow, TCalibrateDescant::k60Co, and MaximumRecoilEnergy().
Referenced by TCalibrateDescant::AddCalibrationPoint().