GRSISort: Fitting & Analysis
Fitting & Analysis
Namespaces
namespace TGRSIFunctions
Classes
class NRMat< T >
class NRMat3d< T >
class NRVec< T >
class TAB3Peak
class TABPeak
class TAngularCorrelation
class TBetaDecay
class TDecay
class TDecayChain
class TDecayFit
class TGauss
class TGRSIFit
class TGRSITransition
class TKinematics
class TLMFitter
class TMultiPeak
class TPeak
class TPeakFitter
class TPulseAnalyzer
class TReaction
class TRWPeak
class TSingleDecay
class TSinglePeak
class TSRIM
class TTransition
class TVirtualDecay
Macros
#define D2R (1.74532925199432955e-02)
#define PI (TMath::Pi())
#define PI (3.14159265358979312e+00)
#define R2D (5.72957795130823229e+01)
Typedefs
typedef NRMat3d< double > Mat3D_double
using Mat3D_I_double = const NRMat3d< double >
typedef NRMat3d< double > Mat3D_IO_double
typedef NRMat3d< double > Mat3D_O_double
typedef NRMat< bool > Mat_BOOL
typedef NRMat< char > Mat_CHR
typedef NRMat< std::complex< double > > Mat_CPLX_double
typedef NRMat< std::complex< float > > Mat_CPLX_SP
typedef NRMat< double > Mat_double
using Mat_I_BOOL = const NRMat< bool >
using Mat_I_CHR = const NRMat< char >
using Mat_I_CPLX_double = const NRMat< std::complex< double > >
using Mat_I_CPLX_SP = const NRMat< std::complex< float > >
using Mat_I_double = const NRMat< double >
using Mat_I_INT = const NRMat< int >
using Mat_I_LNG = const NRMat< long >
using Mat_I_SP = const NRMat< float >
using Mat_I_UCHR = const NRMat< unsigned char >
using Mat_I_UINT = const NRMat< unsigned int >
using Mat_I_ULNG = const NRMat< unsigned long >
typedef NRMat< int > Mat_INT
typedef NRMat< bool > Mat_IO_BOOL
typedef NRMat< char > Mat_IO_CHR
typedef NRMat< std::complex< double > > Mat_IO_CPLX_double
typedef NRMat< std::complex< float > > Mat_IO_CPLX_SP
typedef NRMat< double > Mat_IO_double
typedef NRMat< int > Mat_IO_INT
typedef NRMat< long > Mat_IO_LNG
typedef NRMat< float > Mat_IO_SP
typedef NRMat< unsigned char > Mat_IO_UCHR
typedef NRMat< unsigned int > Mat_IO_UINT
typedef NRMat< unsigned long > Mat_IO_ULNG
typedef NRMat< long > Mat_LNG
typedef NRMat< bool > Mat_O_BOOL
typedef NRMat< char > Mat_O_CHR
typedef NRMat< std::complex< double > > Mat_O_CPLX_double
typedef NRMat< std::complex< float > > Mat_O_CPLX_SP
typedef NRMat< double > Mat_O_double
typedef NRMat< int > Mat_O_INT
typedef NRMat< long > Mat_O_LNG
typedef NRMat< float > Mat_O_SP
typedef NRMat< unsigned char > Mat_O_UCHR
typedef NRMat< unsigned int > Mat_O_UINT
typedef NRMat< unsigned long > Mat_O_ULNG
typedef NRMat< float > Mat_SP
typedef NRMat< unsigned char > Mat_UCHR
typedef NRMat< unsigned int > Mat_UINT
typedef NRMat< unsigned long > Mat_ULNG
typedef std::list< TSinglePeak * > MultiplePeak_t
typedef NRVec< bool > Vec_BOOL
typedef NRVec< char > Vec_CHR
typedef NRVec< std::complex< double > > Vec_CPLX_double
typedef NRVec< std::complex< float > > Vec_CPLX_SP
typedef NRVec< double > Vec_double
using Vec_FSTREAM_p = NRVec< std::fstream * >
using Vec_I_BOOL = const NRVec< bool >
using Vec_I_CHR = const NRVec< char >
using Vec_I_CPLX_double = const NRVec< std::complex< double > >
using Vec_I_CPLX_SP = const NRVec< std::complex< float > >
using Vec_I_double = const NRVec< double >
using Vec_I_INT = const NRVec< int >
using Vec_I_LNG = const NRVec< long >
using Vec_I_SP = const NRVec< float >
using Vec_I_UCHR = const NRVec< unsigned char >
using Vec_I_UINT = const NRVec< unsigned int >
using Vec_I_ULNG = const NRVec< unsigned long >
typedef NRVec< int > Vec_INT
typedef NRVec< bool > Vec_IO_BOOL
typedef NRVec< char > Vec_IO_CHR
typedef NRVec< std::complex< double > > Vec_IO_CPLX_double
typedef NRVec< std::complex< float > > Vec_IO_CPLX_SP
typedef NRVec< double > Vec_IO_double
typedef NRVec< int > Vec_IO_INT
typedef NRVec< long > Vec_IO_LNG
typedef NRVec< float > Vec_IO_SP
typedef NRVec< unsigned char > Vec_IO_UCHR
typedef NRVec< unsigned int > Vec_IO_UINT
typedef NRVec< unsigned long > Vec_IO_ULNG
typedef NRVec< long > Vec_LNG
using Vec_Mat_double_p = NRVec< NRMat< double > * >
typedef NRVec< bool > Vec_O_BOOL
typedef NRVec< char > Vec_O_CHR
typedef NRVec< std::complex< double > > Vec_O_CPLX_double
typedef NRVec< std::complex< float > > Vec_O_CPLX_SP
typedef NRVec< double > Vec_O_double
typedef NRVec< int > Vec_O_INT
typedef NRVec< long > Vec_O_LNG
typedef NRVec< float > Vec_O_SP
typedef NRVec< unsigned char > Vec_O_UCHR
typedef NRVec< unsigned int > Vec_O_UINT
typedef NRVec< unsigned long > Vec_O_ULNG
typedef NRVec< float > Vec_SP
typedef NRVec< unsigned char > Vec_UCHR
typedef NRVec< unsigned int > Vec_UINT
typedef NRVec< unsigned long > Vec_ULNG
using Vec_ULNG_p = NRVec< unsigned long * >
Functions
NRMat< T >::NRMat ()
NRMat< T >::NRMat (const NRMat &rhs)
NRMat< T >::NRMat (const T &a, int n, int m)
NRMat< T >::NRMat (const T *a, int n, int m)
NRMat< T >::NRMat (int n, int m)
NRMat3d< T >::NRMat3d ()
NRMat3d< T >::NRMat3d (int n, int m, int k)
NRVec< T >::NRVec ()
NRVec< T >::NRVec (const NRVec &rhs)
NRVec< T >::NRVec (const T &a, int n)
NRVec< T >::NRVec (const T *a, int n)
NRVec< T >::NRVec (int n)
NRMat< T >::~NRMat ()
NRMat3d< T >::~NRMat3d ()
NRVec< T >::~NRVec ()
int NRMat3d< T >::dim1 () const
int NRMat3d< T >::dim2 () const
int NRMat3d< T >::dim3 () const
float MAX (const double &a, const float &b)
float MAX (const float &a, const double &b)
template<class T >
const T MAX (const T &a, const T &b)
int NRMat< T >::ncols () const
int NRMat< T >::nrows () const
const std::complex< float > operator* (const double &a, const std::complex< float > &b)
const std::complex< float > operator* (const std::complex< float > &a, const double &b)
const std::complex< float > operator+ (const double &a, const std::complex< float > &b)
const std::complex< float > operator+ (const std::complex< float > &a, const double &b)
const std::complex< float > operator- (const double &a, const std::complex< float > &b)
const std::complex< float > operator- (const std::complex< float > &a, const double &b)
const std::complex< float > operator/ (const double &a, const std::complex< float > &b)
const std::complex< float > operator/ (const std::complex< float > &a, const double &b)
NRMat & NRMat< T >::operator= (const NRMat &rhs)
NRVec & NRVec< T >::operator= (const NRVec &rhs)
NRVec & NRVec< T >::operator= (const T &a)
NRMat & NRMat< T >::operator= (const T &a)
T & NRVec< T >::operator[] (const int i)
T * NRMat< T >::operator[] (const int i)
T ** NRMat3d< T >::operator[] (const int i)
const T & NRVec< T >::operator[] (const int i) const
const T * NRMat< T >::operator[] (const int i) const
const T *const * NRMat3d< T >::operator[] (const int i) const
float SIGN (const double &a, const float &b)
float SIGN (const float &a, const double &b)
template<class T >
const T SIGN (const T &a, const T &b)
int NRVec< T >::size () const
template<class T >
const T SQR (const T a)
template<class T >
void SWAP (T &a, T &b)
Detailed Description
Macro Definition Documentation
D2R
#define D2R (1.74532925199432955e-02)
Definition at line 28 of file TReaction.h.
PI [1/2]
#define PI (TMath::Pi())
Definition at line 21 of file TKinematics.h.
PI [2/2]
#define PI (3.14159265358979312e+00)
Definition at line 20 of file TReaction.h.
R2D
#define R2D (5.72957795130823229e+01)
Definition at line 24 of file TReaction.h.
Typedef Documentation
Mat3D_double
typedef NRMat3d<double> Mat3D_double
Definition at line 465 of file TLMFitter.h.
Mat3D_I_double
using Mat3D_I_double = const NRMat3d<double>
Definition at line 464 of file TLMFitter.h.
Mat3D_IO_double
typedef NRMat3d<double> Mat3D_IO_double
Definition at line 465 of file TLMFitter.h.
Mat3D_O_double
typedef NRMat3d<double> Mat3D_O_double
Definition at line 465 of file TLMFitter.h.
Mat_BOOL
typedef NRMat<bool> Mat_BOOL
Definition at line 430 of file TLMFitter.h.
Mat_CHR
typedef NRMat<char> Mat_CHR
Definition at line 433 of file TLMFitter.h.
Mat_CPLX_double
typedef NRMat<std::complex<double> > Mat_CPLX_double
Definition at line 460 of file TLMFitter.h.
Mat_CPLX_SP
typedef NRMat<std::complex<float> > Mat_CPLX_SP
Definition at line 457 of file TLMFitter.h.
Mat_double
typedef NRMat<double> Mat_double
Definition at line 454 of file TLMFitter.h.
Mat_I_BOOL
using Mat_I_BOOL = const NRMat<bool>
Definition at line 429 of file TLMFitter.h.
Mat_I_CHR
using Mat_I_CHR = const NRMat<char>
Definition at line 432 of file TLMFitter.h.
Mat_I_CPLX_double
using Mat_I_CPLX_double = const NRMat<std::complex<double> >
Definition at line 459 of file TLMFitter.h.
Mat_I_CPLX_SP
using Mat_I_CPLX_SP = const NRMat<std::complex<float> >
Definition at line 456 of file TLMFitter.h.
Mat_I_double
using Mat_I_double = const NRMat<double>
Definition at line 453 of file TLMFitter.h.
Mat_I_INT
using Mat_I_INT = const NRMat<int>
Definition at line 438 of file TLMFitter.h.
Mat_I_LNG
using Mat_I_LNG = const NRMat<long>
Definition at line 444 of file TLMFitter.h.
Mat_I_SP
using Mat_I_SP = const NRMat<float>
Definition at line 450 of file TLMFitter.h.
Mat_I_UCHR
using Mat_I_UCHR = const NRMat<unsigned char>
Definition at line 435 of file TLMFitter.h.
Mat_I_UINT
using Mat_I_UINT = const NRMat<unsigned int>
Definition at line 441 of file TLMFitter.h.
Mat_I_ULNG
using Mat_I_ULNG = const NRMat<unsigned long>
Definition at line 447 of file TLMFitter.h.
Mat_INT
typedef NRMat<int> Mat_INT
Definition at line 439 of file TLMFitter.h.
Mat_IO_BOOL
typedef NRMat<bool> Mat_IO_BOOL
Definition at line 430 of file TLMFitter.h.
Mat_IO_CHR
typedef NRMat<char> Mat_IO_CHR
Definition at line 433 of file TLMFitter.h.
Mat_IO_CPLX_double
typedef NRMat<std::complex<double> > Mat_IO_CPLX_double
Definition at line 460 of file TLMFitter.h.
Mat_IO_CPLX_SP
typedef NRMat<std::complex<float> > Mat_IO_CPLX_SP
Definition at line 457 of file TLMFitter.h.
Mat_IO_double
typedef NRMat<double> Mat_IO_double
Definition at line 454 of file TLMFitter.h.
Mat_IO_INT
typedef NRMat<int> Mat_IO_INT
Definition at line 439 of file TLMFitter.h.
Mat_IO_LNG
typedef NRMat<long> Mat_IO_LNG
Definition at line 445 of file TLMFitter.h.
Mat_IO_SP
typedef NRMat<float> Mat_IO_SP
Definition at line 451 of file TLMFitter.h.
Mat_IO_UCHR
typedef NRMat<unsigned char> Mat_IO_UCHR
Definition at line 436 of file TLMFitter.h.
Mat_IO_UINT
typedef NRMat<unsigned int> Mat_IO_UINT
Definition at line 442 of file TLMFitter.h.
Mat_IO_ULNG
typedef NRMat<unsigned long> Mat_IO_ULNG
Definition at line 448 of file TLMFitter.h.
Mat_LNG
typedef NRMat<long> Mat_LNG
Definition at line 445 of file TLMFitter.h.
Mat_O_BOOL
typedef NRMat<bool> Mat_O_BOOL
Definition at line 430 of file TLMFitter.h.
Mat_O_CHR
typedef NRMat<char> Mat_O_CHR
Definition at line 433 of file TLMFitter.h.
Mat_O_CPLX_double
typedef NRMat<std::complex<double> > Mat_O_CPLX_double
Definition at line 460 of file TLMFitter.h.
Mat_O_CPLX_SP
typedef NRMat<std::complex<float> > Mat_O_CPLX_SP
Definition at line 457 of file TLMFitter.h.
Mat_O_double
typedef NRMat<double> Mat_O_double
Definition at line 454 of file TLMFitter.h.
Mat_O_INT
typedef NRMat<int> Mat_O_INT
Definition at line 439 of file TLMFitter.h.
Mat_O_LNG
typedef NRMat<long> Mat_O_LNG
Definition at line 445 of file TLMFitter.h.
Mat_O_SP
typedef NRMat<float> Mat_O_SP
Definition at line 451 of file TLMFitter.h.
Mat_O_UCHR
typedef NRMat<unsigned char> Mat_O_UCHR
Definition at line 436 of file TLMFitter.h.
Mat_O_UINT
typedef NRMat<unsigned int> Mat_O_UINT
Definition at line 442 of file TLMFitter.h.
Mat_O_ULNG
typedef NRMat<unsigned long> Mat_O_ULNG
Definition at line 448 of file TLMFitter.h.
Mat_SP
typedef NRMat<float> Mat_SP
Definition at line 451 of file TLMFitter.h.
Mat_UCHR
typedef NRMat<unsigned char> Mat_UCHR
Definition at line 436 of file TLMFitter.h.
Mat_UINT
typedef NRMat<unsigned int> Mat_UINT
Definition at line 442 of file TLMFitter.h.
Mat_ULNG
typedef NRMat<unsigned long> Mat_ULNG
Definition at line 448 of file TLMFitter.h.
MultiplePeak_t
typedef std::list<TSinglePeak*> MultiplePeak_t
Definition at line 29 of file TPeakFitter.h.
Vec_BOOL
typedef NRVec<bool> Vec_BOOL
Definition at line 395 of file TLMFitter.h.
Vec_CHR
typedef NRVec<char> Vec_CHR
Definition at line 398 of file TLMFitter.h.
Vec_CPLX_double
typedef NRVec<std::complex<double> > Vec_CPLX_double
Definition at line 425 of file TLMFitter.h.
Vec_CPLX_SP
typedef NRVec<std::complex<float> > Vec_CPLX_SP
Definition at line 422 of file TLMFitter.h.
Vec_double
typedef NRVec<double> Vec_double
Definition at line 419 of file TLMFitter.h.
Vec_FSTREAM_p
using Vec_FSTREAM_p = NRVec<std::fstream*>
Definition at line 471 of file TLMFitter.h.
Vec_I_BOOL
using Vec_I_BOOL = const NRVec<bool>
Definition at line 394 of file TLMFitter.h.
Vec_I_CHR
using Vec_I_CHR = const NRVec<char>
Definition at line 397 of file TLMFitter.h.
Vec_I_CPLX_double
using Vec_I_CPLX_double = const NRVec<std::complex<double> >
Definition at line 424 of file TLMFitter.h.
Vec_I_CPLX_SP
using Vec_I_CPLX_SP = const NRVec<std::complex<float> >
Definition at line 421 of file TLMFitter.h.
Vec_I_double
using Vec_I_double = const NRVec<double>
Definition at line 418 of file TLMFitter.h.
Vec_I_INT
using Vec_I_INT = const NRVec<int>
Definition at line 403 of file TLMFitter.h.
Vec_I_LNG
using Vec_I_LNG = const NRVec<long>
Definition at line 409 of file TLMFitter.h.
Vec_I_SP
using Vec_I_SP = const NRVec<float>
Definition at line 415 of file TLMFitter.h.
Vec_I_UCHR
using Vec_I_UCHR = const NRVec<unsigned char>
Definition at line 400 of file TLMFitter.h.
Vec_I_UINT
using Vec_I_UINT = const NRVec<unsigned int>
Definition at line 406 of file TLMFitter.h.
Vec_I_ULNG
using Vec_I_ULNG = const NRVec<unsigned long>
Definition at line 412 of file TLMFitter.h.
Vec_INT
typedef NRVec<int> Vec_INT
Definition at line 404 of file TLMFitter.h.
Vec_IO_BOOL
typedef NRVec<bool> Vec_IO_BOOL
Definition at line 395 of file TLMFitter.h.
Vec_IO_CHR
typedef NRVec<char> Vec_IO_CHR
Definition at line 398 of file TLMFitter.h.
Vec_IO_CPLX_double
typedef NRVec<std::complex<double> > Vec_IO_CPLX_double
Definition at line 425 of file TLMFitter.h.
Vec_IO_CPLX_SP
typedef NRVec<std::complex<float> > Vec_IO_CPLX_SP
Definition at line 422 of file TLMFitter.h.
Vec_IO_double
typedef NRVec<double> Vec_IO_double
Definition at line 419 of file TLMFitter.h.
Vec_IO_INT
typedef NRVec<int> Vec_IO_INT
Definition at line 404 of file TLMFitter.h.
Vec_IO_LNG
typedef NRVec<long> Vec_IO_LNG
Definition at line 410 of file TLMFitter.h.
Vec_IO_SP
typedef NRVec<float> Vec_IO_SP
Definition at line 416 of file TLMFitter.h.
Vec_IO_UCHR
typedef NRVec<unsigned char> Vec_IO_UCHR
Definition at line 401 of file TLMFitter.h.
Vec_IO_UINT
typedef NRVec<unsigned int> Vec_IO_UINT
Definition at line 407 of file TLMFitter.h.
Vec_IO_ULNG
typedef NRVec<unsigned long> Vec_IO_ULNG
Definition at line 413 of file TLMFitter.h.
Vec_LNG
typedef NRVec<long> Vec_LNG
Definition at line 410 of file TLMFitter.h.
Vec_Mat_double_p
using Vec_Mat_double_p = NRVec<NRMat<double>*>
Definition at line 470 of file TLMFitter.h.
Vec_O_BOOL
typedef NRVec<bool> Vec_O_BOOL
Definition at line 395 of file TLMFitter.h.
Vec_O_CHR
typedef NRVec<char> Vec_O_CHR
Definition at line 398 of file TLMFitter.h.
Vec_O_CPLX_double
typedef NRVec<std::complex<double> > Vec_O_CPLX_double
Definition at line 425 of file TLMFitter.h.
Vec_O_CPLX_SP
typedef NRVec<std::complex<float> > Vec_O_CPLX_SP
Definition at line 422 of file TLMFitter.h.
Vec_O_double
typedef NRVec<double> Vec_O_double
Definition at line 419 of file TLMFitter.h.
Vec_O_INT
typedef NRVec<int> Vec_O_INT
Definition at line 404 of file TLMFitter.h.
Vec_O_LNG
typedef NRVec<long> Vec_O_LNG
Definition at line 410 of file TLMFitter.h.
Vec_O_SP
typedef NRVec<float> Vec_O_SP
Definition at line 416 of file TLMFitter.h.
Vec_O_UCHR
typedef NRVec<unsigned char> Vec_O_UCHR
Definition at line 401 of file TLMFitter.h.
Vec_O_UINT
typedef NRVec<unsigned int> Vec_O_UINT
Definition at line 407 of file TLMFitter.h.
Vec_O_ULNG
typedef NRVec<unsigned long> Vec_O_ULNG
Definition at line 413 of file TLMFitter.h.
Vec_SP
typedef NRVec<float> Vec_SP
Definition at line 416 of file TLMFitter.h.
Vec_UCHR
typedef NRVec<unsigned char> Vec_UCHR
Definition at line 401 of file TLMFitter.h.
Vec_UINT
typedef NRVec<unsigned int> Vec_UINT
Definition at line 407 of file TLMFitter.h.
Vec_ULNG
typedef NRVec<unsigned long> Vec_ULNG
Definition at line 413 of file TLMFitter.h.
Vec_ULNG_p
using Vec_ULNG_p = NRVec<unsigned long*>
Definition at line 469 of file TLMFitter.h.
Function Documentation
NRMat() [1/5]
template<class T > NRMat< T >::NRMat ()
Definition at line 174 of file TLMFitter.h.
NRMat() [2/5]
template<class T > NRMat< T >::NRMat (const NRMat< T > & rhs)
Definition at line 224 of file TLMFitter.h.
References NRMat< T >::mm, NRMat< T >::nn, and NRMat< T >::v.
NRMat() [3/5]
template<class T > NRMat< T >::NRMat (const T & a, int n, int m)
Definition at line 194 of file TLMFitter.h.
References NRMat< T >::v.
NRMat() [4/5]
template<class T > NRMat< T >::NRMat (const T * a, int n, int m)
Definition at line 209 of file TLMFitter.h.
References NRMat< T >::v.
NRMat() [5/5]
template<class T > NRMat< T >::NRMat (int n, int m)
Definition at line 179 of file TLMFitter.h.
References NRMat< T >::v.
NRMat3d() [1/2]
template<class T > NRMat3d< T >::NRMat3d ()
Definition at line 332 of file TLMFitter.h.
NRMat3d() [2/2]
template<class T > NRMat3d< T >::NRMat3d (int n, int m, int k)
Definition at line 337 of file TLMFitter.h.
References NRMat3d< T >::v.
NRVec() [1/5]
template<class T > NRVec< T >::NRVec ()
Definition at line 59 of file TLMFitter.h.
NRVec() [2/5]
template<class T > NRVec< T >::NRVec (const NRVec< T > & rhs)
Definition at line 88 of file TLMFitter.h.
References NRVec< T >::nn, and NRVec< T >::v.
NRVec() [3/5]
template<class T > NRVec< T >::NRVec (const T & a, int n)
Definition at line 72 of file TLMFitter.h.
References NRVec< T >::v.
NRVec() [4/5]
template<class T > NRVec< T >::NRVec (const T * a, int n)
Definition at line 80 of file TLMFitter.h.
References NRVec< T >::v.
NRVec() [5/5]
template<class T > NRVec< T >::NRVec (int n) explicit
Definition at line 64 of file TLMFitter.h.
References NRVec< T >::v.
~NRMat()
template<class T > NRMat< T >::~NRMat ()
Definition at line 304 of file TLMFitter.h.
~NRMat3d()
template<class T > NRMat3d< T >::~NRMat3d ()
Definition at line 385 of file TLMFitter.h.
~NRVec()
template<class T > NRVec< T >::~NRVec ()
Definition at line 144 of file TLMFitter.h.
dim1()
template<class T > int NRMat3d< T >::dim1 () const inline
Definition at line 367 of file TLMFitter.h.
dim2()
template<class T > int NRMat3d< T >::dim2 () const inline
Definition at line 373 of file TLMFitter.h.
dim3()
template<class T > int NRMat3d< T >::dim3 () const inline
Definition at line 379 of file TLMFitter.h.
MAX() [1/3]
float MAX (const double & a, const float & b) inline
Definition at line 485 of file TLMFitter.h.
MAX() [2/3]
float MAX (const float & a, const double & b) inline
Definition at line 490 of file TLMFitter.h.
MAX() [3/3]
template<class T > const T MAX (const T & a, const T & b) inline
Definition at line 480 of file TLMFitter.h.
ncols()
template<class T > int NRMat< T >::ncols () const inline
Definition at line 298 of file TLMFitter.h.
Referenced by TLMFitter::gaussj().
nrows()
template<class T > int NRMat< T >::nrows () const inline
Definition at line 292 of file TLMFitter.h.
Referenced by TLMFitter::gaussj().
operator*() [1/2]
const std::complex< float > operator* (const double & a, const std::complex< float > & b) inline
Definition at line 539 of file TLMFitter.h.
operator*() [2/2]
const std::complex< float > operator* (const std::complex< float > & a, const double & b) inline
Definition at line 544 of file TLMFitter.h.
operator+() [1/2]
const std::complex< float > operator+ (const double & a, const std::complex< float > & b) inline
Definition at line 519 of file TLMFitter.h.
operator+() [2/2]
const std::complex< float > operator+ (const std::complex< float > & a, const double & b) inline
Definition at line 524 of file TLMFitter.h.
operator-() [1/2]
const std::complex< float > operator- (const double & a, const std::complex< float > & b) inline
Definition at line 529 of file TLMFitter.h.
operator-() [2/2]
const std::complex< float > operator- (const std::complex< float > & a, const double & b) inline
Definition at line 534 of file TLMFitter.h.
operator/() [1/2]
const std::complex< float > operator/ (const double & a, const std::complex< float > & b) inline
Definition at line 549 of file TLMFitter.h.
operator/() [2/2]
const std::complex< float > operator/ (const std::complex< float > & a, const double & b) inline
Definition at line 554 of file TLMFitter.h.
operator=() [1/4]
template<class T > NRMat< T > & NRMat< T >::operator= (const NRMat< T > & rhs)
Definition at line 239 of file TLMFitter.h.
References NRMat< T >::mm, and NRMat< T >::nn.
operator=() [2/4]
template<class T > NRVec< T > & NRVec< T >::operator= (const NRVec< T > & rhs)
Definition at line 96 of file TLMFitter.h.
References NRVec< T >::nn.
operator=() [3/4]
template<class T > NRVec< T > & NRVec< T >::operator= (const T & a)
Definition at line 117 of file TLMFitter.h.
operator=() [4/4]
template<class T > NRMat< T > & NRMat< T >::operator= (const T & a)
Definition at line 269 of file TLMFitter.h.
operator[]() [1/6]
template<class T > T & NRVec< T >::operator[] (const int i) inline
Definition at line 126 of file TLMFitter.h.
operator[]() [2/6]
template<class T > T * NRMat< T >::operator[] (const int i) inline
Definition at line 280 of file TLMFitter.h.
operator[]() [3/6]
template<class T > T ** NRMat3d< T >::operator[] (const int i) inline
Definition at line 355 of file TLMFitter.h.
operator[]() [4/6]
template<class T > const T & NRVec< T >::operator[] (const int i) const inline
Definition at line 132 of file TLMFitter.h.
operator[]() [5/6]
template<class T > const T * NRMat< T >::operator[] (const int i) const inline
Definition at line 286 of file TLMFitter.h.
operator[]() [6/6]
template<class T > const T *const * NRMat3d< T >::operator[] (const int i) const inline
Definition at line 361 of file TLMFitter.h.
SIGN() [1/3]
float SIGN (const double & a, const float & b) inline
Definition at line 506 of file TLMFitter.h.
SIGN() [2/3]
float SIGN (const float & a, const double & b) inline
Definition at line 501 of file TLMFitter.h.
SIGN() [3/3]
template<class T > const T SIGN (const T & a, const T & b) inline
Definition at line 496 of file TLMFitter.h.
size()
template<class T > int NRVec< T >::size () const inline
Definition at line 138 of file TLMFitter.h.
Referenced by TLMFitter::covsrt(), TLMFitter::integrator(), TLMFitter::mrqcof(), and TLMFitter::mrqmin().
SQR()
template<class T > const T SQR (const T a) inline
Definition at line 474 of file TLMFitter.h.
SWAP()
template<class T > void SWAP (T & a, T & b) inline
Definition at line 512 of file TLMFitter.h.
Referenced by TLMFitter::covsrt(), and TLMFitter::gaussj().