GRSISort: grsisort.cxx File Reference
grsisort.cxx File Reference
#include <cstdio>
#include <string>
#include <sys/stat.h>
#include <netdb.h>
#include <iostream>
#include <stdexcept>
#include <pwd.h>
#include "TPluginManager.h"
#include "TGRSIint.h"
#include "GVersion.h"
#include "Globals.h"
#include "TThread.h"
#include <utmp.h>
Macros
#define STRUCT_UTMP struct utmp
Functions
void atexitHandler ()
int main (int argc, char **argv)
static int ReadUtmp ()
static STRUCT_UTMP * SearchEntry (int, const char *)
static void SetDisplay ()
void SetGRSIEnv ()
void SetGRSIPluginHandlers ()
Variables
TStopwatch * gStopwatch
static STRUCT_UTMP * gUtmpContents
Macro Definition Documentation
STRUCT_UTMP
#define STRUCT_UTMP struct utmp
Definition at line 35 of file grsisort.cxx.
Referenced by ReadUtmp(), SearchEntry(), and SetDisplay().
Function Documentation
atexitHandler()
void atexitHandler ()
Definition at line 48 of file grsisort.cxx.
References DCYAN, DMAGENTA, gStopwatch, and RESET_COLOR.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 62 of file grsisort.cxx.
References atexitHandler(), gStopwatch, TGRSIint::instance(), grsi::exit_exception::message, SetDisplay(), grsi::SetGRSIEnv(), and SetGRSIPluginHandlers().
ReadUtmp()
static int ReadUtmp () static
Definition at line 102 of file grsisort.cxx.
References gUtmpContents, and STRUCT_UTMP.
Referenced by SetDisplay().
SearchEntry()
static STRUCT_UTMP * SearchEntry (int n, const char * tty) static
Definition at line 143 of file grsisort.cxx.
References gUtmpContents, and STRUCT_UTMP.
Referenced by SetDisplay().
SetDisplay()
static void SetDisplay () static
Definition at line 155 of file grsisort.cxx.
References gUtmpContents, ReadUtmp(), SearchEntry(), and STRUCT_UTMP.
Referenced by main().
SetGRSIEnv()
void SetGRSIEnv ()
Definition at line 175 of file grsiproof.cxx.
Referenced by main().
SetGRSIPluginHandlers()
void SetGRSIPluginHandlers ()
Definition at line 92 of file grsisort.cxx.
Referenced by main().
Variable Documentation
gStopwatch
TStopwatch* gStopwatch
Definition at line 46 of file grsisort.cxx.
Referenced by atexitHandler(), and main().
gUtmpContents
STRUCT_UTMP* gUtmpContents static
Definition at line 38 of file grsisort.cxx.
Referenced by ReadUtmp(), SearchEntry(), and SetDisplay().