GRSISort: grsiproof.cxx File Reference
grsiproof.cxx File Reference
#include "TEnv.h"
#include "TFile.h"
#include "TTree.h"
#include "TChain.h"
#include "TProofLite.h"
#include "TProofLog.h"
#include "TSystemDirectory.h"
#include "TList.h"
#include "TChainElement.h"
#include "TROOT.h"
#include "TInterpreter.h"
#include "TGRSIProof.h"
#include "TGRSIOptions.h"
#include "TChannel.h"
#include "TRunInfo.h"
#include "TObjectWrapper.h"
#include "TStopwatch.h"
#include "TGRSIMap.h"
#include "TPPG.h"
#include "TCutG.h"
#include <iostream>
#include <vector>
#include <string>
#include <csignal>
#include <libgen.h>
Functions
void Analyze (const char *treeType)
void AtExitHandler ()
static void CatchSignals ()
void HandleSignal (int)
int main (int argc, char **argv)
void SetGRSIEnv ()
Variables
bool controlC = false
TGRSIOptions * gGRSIOpt
TGRSIProof * gGRSIProof
TPPG * gPpg
TStopwatch * gStopwatch
bool startedProof = false
Function Documentation
Analyze()
void Analyze (const char * treeType)
Definition at line 37 of file grsiproof.cxx.
References TPPG::Add(), TSingleton< TRunInfo >::AddCurrent(), TGRSIMapException< key_type >::detail(), DRED, TSingleton< TRunInfo >::Get(), gGRSIOpt, gGRSIProof, gPpg, TGRSIOptions::MacroInputFiles(), TGRSIOptions::NumberOfEvents(), TRunInfo::Print(), RESET_COLOR, TGRSIOptions::RootInputFiles(), and TGRSIOptions::SelectorOnly().
Referenced by main().
AtExitHandler()
void AtExitHandler ()
Definition at line 107 of file grsiproof.cxx.
References controlC, DMAGENTA, TRunInfo::FirstRunNumber(), TRunInfo::FirstSubRunNumber(), gGRSIOpt, gGRSIProof, gStopwatch, TRunInfo::LastRunNumber(), TRunInfo::LastSubRunNumber(), TGRSIOptions::MacroInputFiles(), RESET_COLOR, TRunInfo::RunNumber(), startedProof, and TRunInfo::SubRunNumber().
Referenced by HandleSignal(), and main().
CatchSignals()
static void CatchSignals () static
Definition at line 165 of file grsiproof.cxx.
References HandleSignal().
Referenced by main().
HandleSignal()
void HandleSignal (int)
Definition at line 158 of file grsiproof.cxx.
References AtExitHandler().
Referenced by CatchSignals().
main()
int main (int argc, char ** argv)
Definition at line 186 of file grsiproof.cxx.
References TGRSIOptions::AnalysisOptions(), Analyze(), AtExitHandler(), TGRSIOptions::AverageRateEstimation(), TGRSIOptions::CacheSize(), TGRSIOptions::CalInputFiles(), CatchSignals(), DCYAN, DRED, TGRSIOptions::Get(), TGRSIOptions::GetMaxWorkers(), gGRSIOpt, gGRSIProof, gPpg, gStopwatch, TGRSIOptions::InputCutFiles(), TGRSIOptions::InputFiles(), TGRSIOptions::MacroInputFiles(), TGRSIProof::Open(), TGRSIOptions::ParallelUnzip(), TGRSIOptions::ParserLibrary(), TGRSIOptions::ProofStats(), RESET_COLOR, TGRSIOptions::SelectorOnly(), SetGRSIEnv(), TGRSIOptions::ShouldExit(), startedProof, TGRSIOptions::Submergers(), TGRSIOptions::TreeName(), and TGRSIOptions::ValInputFiles().
SetGRSIEnv()
void SetGRSIEnv ()
Definition at line 175 of file grsiproof.cxx.
Referenced by main().
Variable Documentation
controlC
bool controlC = false
Definition at line 35 of file grsiproof.cxx.
Referenced by AtExitHandler().
gGRSIOpt
TGRSIOptions* gGRSIOpt
Definition at line 30 of file grsiproof.cxx.
Referenced by Analyze(), AtExitHandler(), and main().
gGRSIProof
TGRSIProof* gGRSIProof
Definition at line 29 of file grsiproof.cxx.
Referenced by Analyze(), AtExitHandler(), and main().
gPpg
TPPG* gPpg
Definition at line 32 of file grsiproof.cxx.
Referenced by Analyze(), and main().
gStopwatch
TStopwatch* gStopwatch
Definition at line 31 of file grsiproof.cxx.
Referenced by AtExitHandler(), and main().
startedProof
bool startedProof = false
Definition at line 34 of file grsiproof.cxx.
Referenced by AtExitHandler(), and main().