GRSISort: GRootFunctions Namespace Reference
GRootFunctions Namespace Reference
Functions
Double_t Efficiency (Double_t *dim, Double_t *par)
Double_t GammaEff (Double_t *x, Double_t *par)
Double_t Gaus (Double_t *dim, Double_t *par)
Double_t GausExpo (Double_t *x, Double_t *pars)
Double_t LanGaus (Double_t *x, Double_t *pars)
Double_t LanGausHighRes (Double_t *x, Double_t *pars)
Double_t LinFit (Double_t *dim, Double_t *par)
Double_t PhotoPeak (Double_t *dim, Double_t *par)
Double_t PhotoPeakBG (Double_t *dim, Double_t *par)
Double_t PolyBg (Double_t *dim, Double_t *par, Int_t order)
Double_t QuadFit (Double_t *dim, Double_t *par)
Double_t SkewedGaus (Double_t *dim, Double_t *par)
Double_t StepBG (Double_t *dim, Double_t *par)
Double_t StepFunction (Double_t *dim, Double_t *par)
Function Documentation
Efficiency()
Double_t GRootFunctions::Efficiency (Double_t * dim, Double_t * par)
Definition at line 120 of file GRootFunctions.cxx.
GammaEff()
Double_t GRootFunctions::GammaEff (Double_t * x, Double_t * par)
Definition at line 193 of file GRootFunctions.cxx.
Referenced by TCalibrator::MakeEffGraph().
Gaus()
Double_t GRootFunctions::Gaus (Double_t * dim, Double_t * par)
Definition at line 54 of file GRootFunctions.cxx.
Referenced by PhotoPeak(), and PhotoPeakBG().
GausExpo()
Double_t GRootFunctions::GausExpo (Double_t * x, Double_t * pars)
Definition at line 141 of file GRootFunctions.cxx.
LanGaus()
Double_t GRootFunctions::LanGaus (Double_t * x, Double_t * pars)
Definition at line 153 of file GRootFunctions.cxx.
LanGausHighRes()
Double_t GRootFunctions::LanGausHighRes (Double_t * x, Double_t * pars)
Definition at line 175 of file GRootFunctions.cxx.
LinFit()
Double_t GRootFunctions::LinFit (Double_t * dim, Double_t * par)
Definition at line 20 of file GRootFunctions.cxx.
References PolyBg().
Referenced by TCalibrator::Fit().
PhotoPeak()
Double_t GRootFunctions::PhotoPeak (Double_t * dim, Double_t * par)
Definition at line 97 of file GRootFunctions.cxx.
References Gaus(), and SkewedGaus().
PhotoPeakBG()
Double_t GRootFunctions::PhotoPeakBG (Double_t * dim, Double_t * par)
Definition at line 102 of file GRootFunctions.cxx.
References Gaus(), PolyBg(), SkewedGaus(), and StepFunction().
PolyBg()
Double_t GRootFunctions::PolyBg (Double_t * dim, Double_t * par, Int_t order)
Referenced by LinFit(), PhotoPeakBG(), QuadFit(), and StepBG().
QuadFit()
Double_t GRootFunctions::QuadFit (Double_t * dim, Double_t * par)
Definition at line 25 of file GRootFunctions.cxx.
References PolyBg().
Referenced by TCalibrator::Fit().
SkewedGaus()
Double_t GRootFunctions::SkewedGaus (Double_t * dim, Double_t * par)
Definition at line 71 of file GRootFunctions.cxx.
Referenced by PhotoPeak(), and PhotoPeakBG().
StepBG()
Double_t GRootFunctions::StepBG (Double_t * dim, Double_t * par)
Definition at line 49 of file GRootFunctions.cxx.
References PolyBg(), and StepFunction().
Referenced by GPeak::GPeak().
StepFunction()
Double_t GRootFunctions::StepFunction (Double_t * dim, Double_t * par)
Definition at line 30 of file GRootFunctions.cxx.
Referenced by PhotoPeakBG(), and StepBG().