GRSISort: TGRSIFunctions Namespace Reference
TGRSIFunctions Namespace Reference
Fitting & Analysis
Functions
double A (double k, double ji, double jf, double L1, double L2, double delta)
double B (double k, double ji, double jf, double L1, double L2, double delta)
Double_t Bateman (std::vector< Double_t > &dim, std::vector< Double_t > &par, UInt_t nChain=1, Double_t SecondsPerBin=1.0)
double CalculateA2 (double j1, double j2, double j3, double l1a, double l1b, double l2a, double l2b, double delta1, double delta2)
double CalculateA4 (double j1, double j2, double j3, double l1a, double l1b, double l2a, double l2b, double delta1, double delta2)
bool CheckParameterErrors (const TFitResultPtr &fitres, std::string opt="")
double ClebschGordan (double j1, double m1, double j2, double m2, double j, double m)
Double_t ConvolutedDecay (Double_t *x, Double_t *par)
Double_t ConvolutedDecay2 (Double_t *x, Double_t *par)
Double_t CsIFitFunction (Double_t *time, Double_t *par)
Double_t DeadTimeAffect (Double_t function, Double_t deadtime, Double_t binWidth=1.0)
Double_t DeadTimeCorrect (Double_t *dim, Double_t deadtime, Double_t binWidth=1.0)
double F (double k, double jf, double L1, double L2, double ji)
Double_t Gaus (Double_t *dim, Double_t *par)
Double_t LanGaus (Double_t *x, Double_t *pars)
Double_t LanGausHighRes (Double_t *x, Double_t *pars)
Double_t LegendrePolynomial (Double_t *x, Double_t *p)
Double_t MultiGausWithBG (Double_t *dim, Double_t *par)
Double_t MultiPhotoPeakBG (Double_t *dim, Double_t *par)
Double_t MultiSkewedGausWithBG (Double_t *dim, Double_t *par)
Double_t MultiSkewedGausWithBG2 (Double_t *dim, Double_t *par)
Double_t PhotoEfficiency (Double_t *dim, Double_t *par)
Double_t PhotoPeak (Double_t *dim, Double_t *par)
Double_t PhotoPeakBG (Double_t *dim, Double_t *par)
Double_t PolyBg (Double_t *x, Double_t *par, Int_t order)
double RacahW (double a, double b, double c, double d, double e, double f)
Double_t SkewedGaus (Double_t *dim, Double_t *par)
Double_t SkewedGaus2 (Double_t *x, Double_t *par)
Double_t StepBG (Double_t *dim, Double_t *par)
Double_t StepFunction (Double_t *dim, Double_t *par)
Detailed Description
This namespace is where we store all of our commonly used functions. This makes it easier to create fits etc.
Function Documentation
A()
double TGRSIFunctions::A (double k, double ji, double jf, double L1, double L2, double delta)
Definition at line 513 of file TGRSIFunctions.cxx.
References F().
Referenced by CalculateA2(), and CalculateA4().
B()
double TGRSIFunctions::B (double k, double ji, double jf, double L1, double L2, double delta)
Definition at line 522 of file TGRSIFunctions.cxx.
References F().
Referenced by CalculateA2(), and CalculateA4().
Bateman()
Double_t TGRSIFunctions::Bateman (std::vector< Double_t > & dim, std::vector< Double_t > & par, UInt_t nChain = 1, Double_t SecondsPerBin = 1.0)
Definition at line 311 of file TGRSIFunctions.cxx.
CalculateA2()
double TGRSIFunctions::CalculateA2 (double j1, double j2, double j3, double l1a, double l1b, double l2a, double l2b, double delta1, double delta2)
Definition at line 530 of file TGRSIFunctions.cxx.
References A(), and B().
Referenced by MixingMethod().
CalculateA4()
double TGRSIFunctions::CalculateA4 (double j1, double j2, double j3, double l1a, double l1b, double l2a, double l2b, double delta1, double delta2)
Definition at line 535 of file TGRSIFunctions.cxx.
References A(), and B().
Referenced by MixingMethod().
CheckParameterErrors()
bool TGRSIFunctions::CheckParameterErrors (const TFitResultPtr & fitres, std::string opt = "")
This function compares the parameter error with the square root of the corresponding diagonal entry of the covariance matrix. If the difference between the two is larger than 0.1 (arbitrarily chosen cutoff), the check fails. Implemented options are "q" to be quiet (prints nothing), or "v" to be verbose (prints message not just for failed parameters but also ones that pass the test).
Definition at line 17 of file TGRSIFunctions.cxx.
References GREEN, RED, and RESET_COLOR.
Referenced by GPeak::Fit(), TPeakFitter::Fit(), and TPeak::Fit().
ClebschGordan()
double TGRSIFunctions::ClebschGordan (double j1, double m1, double j2, double m2, double j, double m)
Definition at line 425 of file TGRSIFunctions.cxx.
Referenced by F().
ConvolutedDecay()
Double_t TGRSIFunctions::ConvolutedDecay (Double_t * x, Double_t * par)
This function is derived from the convolution of a gaussian with an exponential decay, to fit TAC spectra of long half-lives (above 100 ps) Requires the following parameters:
par[0]: Normalization factor
par[1]: Centroid of gaussian
par[2]: Sigma of gaussian
par[3]: Lambda of the level
Definition at line 396 of file TGRSIFunctions.cxx.
ConvolutedDecay2()
Double_t TGRSIFunctions::ConvolutedDecay2 (Double_t * x, Double_t * par)
This function is the same as ConvolutedDecay but should be use when the lifetime has two different components. Requires the following parameters:
par[0]: Weight of lifetime-1
par[1]: Centroid of gaussian
par[2]: Width of gaussian
par[3]: Lambda of the level-1
par[4]: Weight of lifetime-2
par[5]: Lambda of the level-2
Definition at line 408 of file TGRSIFunctions.cxx.
CsIFitFunction()
Double_t TGRSIFunctions::CsIFitFunction (Double_t * time, Double_t * par)
p[0]-p[4] are t0, tRC, tF, TS, TGamma p[5]-p[8] are baseline, AF, AS, AGamma
Definition at line 55 of file TGRSIFunctions.cxx.
References s.
Referenced by TPulseAnalyzer::DrawCsIFit().
DeadTimeAffect()
Double_t TGRSIFunctions::DeadTimeAffect (Double_t function, Double_t deadtime, Double_t binWidth = 1.0)
Definition at line 368 of file TGRSIFunctions.cxx.
DeadTimeCorrect()
Double_t TGRSIFunctions::DeadTimeCorrect (Double_t * dim, Double_t deadtime, Double_t binWidth = 1.0)
Definition at line 359 of file TGRSIFunctions.cxx.
F()
double TGRSIFunctions::F (double k, double jf, double L1, double L2, double ji)
Definition at line 498 of file TGRSIFunctions.cxx.
References ClebschGordan(), and RacahW().
Referenced by A(), and B().
Gaus()
Double_t TGRSIFunctions::Gaus (Double_t * dim, Double_t * par)
This is a gaussian that has been scaled to match up with Radware photopeak results. It contains a scaling factor for the relative height of the skewed gaussian to the normal gaussian. Requires the following parameters:
dim[0]: channels being fit
par[0]: height of photopeak
par[1]: centroid of gaussian
par[2]: standard deviation of gaussian
par[4]: relative height of skewed gaus to gaus
Definition at line 139 of file TGRSIFunctions.cxx.
LanGaus()
Double_t TGRSIFunctions::LanGaus (Double_t * x, Double_t * pars)
Definition at line 238 of file TGRSIFunctions.cxx.
LanGausHighRes()
Double_t TGRSIFunctions::LanGausHighRes (Double_t * x, Double_t * pars)
Definition at line 267 of file TGRSIFunctions.cxx.
LegendrePolynomial()
Double_t TGRSIFunctions::LegendrePolynomial (Double_t * x, Double_t * p)
Definition at line 378 of file TGRSIFunctions.cxx.
Referenced by A2a4Method().
MultiGausWithBG()
Double_t TGRSIFunctions::MultiGausWithBG (Double_t * dim, Double_t * par)
Definition at line 290 of file TGRSIFunctions.cxx.
MultiPhotoPeakBG()
Double_t TGRSIFunctions::MultiPhotoPeakBG (Double_t * dim, Double_t * par)
Definition at line 121 of file TGRSIFunctions.cxx.
MultiSkewedGausWithBG()
Double_t TGRSIFunctions::MultiSkewedGausWithBG (Double_t * dim, Double_t * par)
Definition at line 185 of file TGRSIFunctions.cxx.
MultiSkewedGausWithBG2()
Double_t TGRSIFunctions::MultiSkewedGausWithBG2 (Double_t * dim, Double_t * par)
Definition at line 219 of file TGRSIFunctions.cxx.
References SkewedGaus2().
PhotoEfficiency()
Double_t TGRSIFunctions::PhotoEfficiency (Double_t * dim, Double_t * par)
Definition at line 385 of file TGRSIFunctions.cxx.
PhotoPeak()
Double_t TGRSIFunctions::PhotoPeak (Double_t * dim, Double_t * par)
Returns the combination of a TGRSIFunctions::Gaus + a TGRSIFunctions::SkewedGaus
Definition at line 107 of file TGRSIFunctions.cxx.
Referenced by TMultiPeak::MultiPhotoPeakBG(), and TMultiPeak::SinglePeakBG().
PhotoPeakBG()
Double_t TGRSIFunctions::PhotoPeakBG (Double_t * dim, Double_t * par)
Returns a single RadWare style peak
Definition at line 113 of file TGRSIFunctions.cxx.
PolyBg()
Double_t TGRSIFunctions::PolyBg (Double_t * x, Double_t * par, Int_t order)
Polynomial function of the form SUM(par[i]*(x - shift)^i). The shift is done to match parameters with Radware output.
Definition at line 72 of file TGRSIFunctions.cxx.
Referenced by TMultiPeak::MultiPhotoPeakBG(), TMultiPeak::MultiStepBG(), and TMultiPeak::SinglePeakBG().
RacahW()
double TGRSIFunctions::RacahW (double a, double b, double c, double d, double e, double f)
Definition at line 487 of file TGRSIFunctions.cxx.
Referenced by F().
SkewedGaus()
Double_t TGRSIFunctions::SkewedGaus (Double_t * dim, Double_t * par)
This function uses the same parameters as the photopeak and gaussian. This is because in the photopeak, the shapes are correlated. Requires the following parameters:
dim[0]: channels being fit
par[0]: height of photopeak
par[1]: centroid of gaussian
par[2]: standard deviation of gaussian
par[3]: "skewedness" of the skewed gaussin
par[4]: relative height of skewed gaus to gaus
Definition at line 159 of file TGRSIFunctions.cxx.
SkewedGaus2()
Double_t TGRSIFunctions::SkewedGaus2 (Double_t * x, Double_t * par)
This function is derived from the convolution of a gaussian with an exponential Requires the following parameters:
par[0]: height of photopeak
par[1]: centroid of gaussian
par[2]: standard deviation of gaussian
par[3]: "skewedness" of the skewed gaussin
Definition at line 206 of file TGRSIFunctions.cxx.
Referenced by MultiSkewedGausWithBG2().
StepBG()
Double_t TGRSIFunctions::StepBG (Double_t * dim, Double_t * par)
Definition at line 102 of file TGRSIFunctions.cxx.
Referenced by TPeak::TPeak().
StepFunction()
Double_t TGRSIFunctions::StepFunction (Double_t * dim, Double_t * par)
This function uses the same parameters as the photopeak and gaussian. This is because in the photopeak, the shapes are correlated. Requires the following parameters:
dim[0]: channels being fit
par[0]: height of photopeak
par[1]: centroid of gaussian
par[2]: standard deviation of gaussian
par[5]: Size of the step in the step function
Definition at line 83 of file TGRSIFunctions.cxx.
Referenced by TMultiPeak::MultiPhotoPeakBG(), TMultiPeak::MultiStepBG(), and TMultiPeak::SinglePeakBG().