GRSISort: offsetfix.cxx File Reference
offsetfix.cxx File Reference
#include "TGRSIOptions.h"
#include "TMidasFile.h"
#include "TMidasEvent.h"
#include "TFile.h"
#include "TFragment.h"
#include "TGRSIDataParser.h"
#include "TGRSIDataParserException.h"
#include "TTree.h"
#include "TSpectrum.h"
#include "TChannel.h"
#include "TH2D.h"
#include "TTreeIndex.h"
#include "TVirtualIndex.h"
#include "Globals.h"
#include "TF1.h"
#include "TMath.h"
#include "TString.h"
#include "TPolyMarker.h"
#include "TStopwatch.h"
#include "TSystem.h"
#include <vector>
#include <iostream>
#include <fstream>
Classes
class TEventTime
Functions
void CheckHighTimeStamp (std::vector< TEventTime * > *eventQ)
int CorrectionFile (int runnumber)
void GetRoughTimeDiff (std::vector< TEventTime * > *eventQ)
void GetTimeDiff (std::vector< TEventTime * > *eventQ)
int main (int argc, char **argv)
void PrintError (const std::shared_ptr< TMidasEvent > &event, int frags, bool verb)
bool ProcessEvent (const std::shared_ptr< TMidasEvent > &event, TMidasFile *outfile)
int QueueEvents (TMidasFile *infile, std::vector< TEventTime * > *eventQ)
void WriteCorrectionFile (int runnumber)
void WriteEvents (TMidasFile *file)
Variables
Bool_t SplitMezz = false
Function Documentation
CheckHighTimeStamp()
void CheckHighTimeStamp (std::vector< TEventTime * > * eventQ)
Definition at line 288 of file offsetfix.cxx.
References TEventTime::correctionmap, DBLUE, TEventTime::digmap, TEventTime::GetBestDigitizer(), TEventTime::GetLowestMidasTime(), and RESET_COLOR.
Referenced by main().
CorrectionFile()
int CorrectionFile (int runnumber)
Definition at line 816 of file offsetfix.cxx.
References TEventTime::correctionmap, DGREEN, and RESET_COLOR.
Referenced by main().
GetRoughTimeDiff()
void GetRoughTimeDiff (std::vector< TEventTime * > * eventQ)
Definition at line 361 of file offsetfix.cxx.
References TEventTime::correctionmap, DBLUE, TEventTime::digmap, DYELLOW, TEventTime::GetBestDigitizer(), and RESET_COLOR.
Referenced by main().
GetTimeDiff()
void GetTimeDiff (std::vector< TEventTime * > * eventQ)
Definition at line 472 of file offsetfix.cxx.
References TEventTime::correctionmap, DBLUE, TEventTime::digmap, DYELLOW, TEventTime::GetBestDigitizer(), hist, and RESET_COLOR.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 859 of file offsetfix.cxx.
References CheckHighTimeStamp(), CorrectionFile(), TEventTime::digmap, TGRSIOptions::Get(), GetRoughTimeDiff(), GetTimeDiff(), TMidasFile::Open(), QueueEvents(), TGRSIOptions::SuppressErrors(), WriteCorrectionFile(), and WriteEvents().
PrintError()
void PrintError (const std::shared_ptr< TMidasEvent > & event, int frags, bool verb)
Definition at line 195 of file offsetfix.cxx.
References DRED, and RESET_COLOR.
Referenced by QueueEvents().
ProcessEvent()
bool ProcessEvent (const std::shared_ptr< TMidasEvent > & event, TMidasFile * outfile)
Definition at line 581 of file offsetfix.cxx.
References TEventTime::correctionmap, TMidasFile::FillBuffer(), and SplitMezz.
Referenced by WriteEvents().
QueueEvents()
int QueueEvents (TMidasFile * infile, std::vector< TEventTime * > * eventQ)
Definition at line 207 of file offsetfix.cxx.
References DBLUE, DGREEN, DRED, DYELLOW, TGRSIDataParserException::GetFailedWord(), TMidasFile::GetSubRunNumber(), TGRSIDataParser::GriffinDataToFragment(), TGRSIDataParser::kGRF2, TEventTime::OrderDigitizerMap(), PrintError(), TMidasFile::Read(), and RESET_COLOR.
Referenced by main().
WriteCorrectionFile()
void WriteCorrectionFile (int runnumber)
Definition at line 789 of file offsetfix.cxx.
References TEventTime::correctionmap.
Referenced by main().
WriteEvents()
void WriteEvents (TMidasFile * file)
Definition at line 726 of file offsetfix.cxx.
References DGREEN, DMAGENTA, DRED, TMidasFile::FillBuffer(), TRawFile::GetFilename(), TMidasFile::GetLastErrno(), TMidasFile::GetLastError(), HIDE_CURSOR, ProcessEvent(), TMidasFile::Read(), RESET_COLOR, SHOW_CURSOR, and TMidasFile::WriteBuffer().
Referenced by main().
Variable Documentation
SplitMezz
Bool_t SplitMezz = false
Definition at line 29 of file offsetfix.cxx.
Referenced by ProcessEvent(), and TEventTime::SetDigitizer().