/********************************************************************
* TCSMDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCSMDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCSMDict();
extern void G__cpp_setup_inheritanceTCSMDict();
extern void G__cpp_setup_typetableTCSMDict();
extern void G__cpp_setup_memvarTCSMDict();
extern void G__cpp_setup_globalTCSMDict();
extern void G__cpp_setup_memfuncTCSMDict();
extern void G__cpp_setup_funcTCSMDict();
extern void G__set_cpp_environmentTCSMDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TCSM.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCSMDictLN_TClass;
extern G__linked_taginfo G__TCSMDictLN_TBuffer;
extern G__linked_taginfo G__TCSMDictLN_TMemberInspector;
extern G__linked_taginfo G__TCSMDictLN_TObject;
extern G__linked_taginfo G__TCSMDictLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__TCSMDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TCSMDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCSMDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDictLN_MNEMONIC;
extern G__linked_taginfo G__TCSMDictLN_TFragment;
extern G__linked_taginfo G__TCSMDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCSMDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_TChannel;
extern G__linked_taginfo G__TCSMDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TCSMDictLN_TCSMData;
extern G__linked_taginfo G__TCSMDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCSMDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCSMDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCSMDictLN_TVector3;
extern G__linked_taginfo G__TCSMDictLN_TCSMHit;
extern G__linked_taginfo G__TCSMDictLN_TGRSIDetector;
extern G__linked_taginfo G__TCSMDictLN_TCSM;
extern G__linked_taginfo G__TCSMDictLN_vectorlETCSMHitcOallocatorlETCSMHitgRsPgR;
extern G__linked_taginfo G__TCSMDictLN_reverse_iteratorlEvectorlETCSMHitcOallocatorlETCSMHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
