/********************************************************************
* TCSMHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCSMHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCSMHitDict();
extern void G__cpp_setup_inheritanceTCSMHitDict();
extern void G__cpp_setup_typetableTCSMHitDict();
extern void G__cpp_setup_memvarTCSMHitDict();
extern void G__cpp_setup_globalTCSMHitDict();
extern void G__cpp_setup_memfuncTCSMHitDict();
extern void G__cpp_setup_funcTCSMHitDict();
extern void G__set_cpp_environmentTCSMHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TCSMHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCSMHitDictLN_TClass;
extern G__linked_taginfo G__TCSMHitDictLN_TBuffer;
extern G__linked_taginfo G__TCSMHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TCSMHitDictLN_TObject;
extern G__linked_taginfo G__TCSMHitDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMHitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCSMHitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMHitDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCSMHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCSMHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCSMHitDictLN_TVector3;
extern G__linked_taginfo G__TCSMHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TCSMHitDictLN_TCSMHit;

/* STUB derived class for protected member access */
