/********************************************************************
* TCSMDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCSMDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCSMDataDict();
extern void G__cpp_setup_inheritanceTCSMDataDict();
extern void G__cpp_setup_typetableTCSMDataDict();
extern void G__cpp_setup_memvarTCSMDataDict();
extern void G__cpp_setup_globalTCSMDataDict();
extern void G__cpp_setup_memfuncTCSMDataDict();
extern void G__cpp_setup_funcTCSMDataDict();
extern void G__set_cpp_environmentTCSMDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TCSMData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCSMDataDictLN_TClass;
extern G__linked_taginfo G__TCSMDataDictLN_TBuffer;
extern G__linked_taginfo G__TCSMDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TCSMDataDictLN_TObject;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDataDictLN_MNEMONIC;
extern G__linked_taginfo G__TCSMDataDictLN_TFragment;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCSMDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TCSMDataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_TChannel;
extern G__linked_taginfo G__TCSMDataDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TCSMDataDictLN_TCSMData;
extern G__linked_taginfo G__TCSMDataDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TCSMDataDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
