/********************************************************************
* TGRSIRootIODict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIRootIODict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIRootIODict();
extern void G__cpp_setup_inheritanceTGRSIRootIODict();
extern void G__cpp_setup_typetableTGRSIRootIODict();
extern void G__cpp_setup_memvarTGRSIRootIODict();
extern void G__cpp_setup_globalTGRSIRootIODict();
extern void G__cpp_setup_memfuncTGRSIRootIODict();
extern void G__cpp_setup_funcTGRSIRootIODict();
extern void G__set_cpp_environmentTGRSIRootIODict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIRootIO.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIRootIODictLN_TClass;
extern G__linked_taginfo G__TGRSIRootIODictLN_TBuffer;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIRootIODictLN_TObject;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_string;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TTree;
extern G__linked_taginfo G__TGRSIRootIODictLN_TFile;
extern G__linked_taginfo G__TGRSIRootIODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_maplETStringcOTProofcLcLMD5Mod_tcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTProofcLcLMD5Mod_tgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TFragment;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TChannel;
extern G__linked_taginfo G__TGRSIRootIODictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_TGRSIRootIO;
extern G__linked_taginfo G__TGRSIRootIODictLN_vectorlETFilemUcOallocatorlETFilemUgRsPgR;
extern G__linked_taginfo G__TGRSIRootIODictLN_reverse_iteratorlEvectorlETFilemUcOallocatorlETFilemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
