/********************************************************************
* TChannelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TChannelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTChannelDict();
extern void G__cpp_setup_inheritanceTChannelDict();
extern void G__cpp_setup_typetableTChannelDict();
extern void G__cpp_setup_memvarTChannelDict();
extern void G__cpp_setup_globalTChannelDict();
extern void G__cpp_setup_memfuncTChannelDict();
extern void G__cpp_setup_funcTChannelDict();
extern void G__set_cpp_environmentTChannelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TChannel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TChannelDictLN_TClass;
extern G__linked_taginfo G__TChannelDictLN_TBuffer;
extern G__linked_taginfo G__TChannelDictLN_TMemberInspector;
extern G__linked_taginfo G__TChannelDictLN_TObject;
extern G__linked_taginfo G__TChannelDictLN_TNamed;
extern G__linked_taginfo G__TChannelDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TChannelDictLN_string;
extern G__linked_taginfo G__TChannelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TChannelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TChannelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TChannelDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TChannelDictLN_TTree;
extern G__linked_taginfo G__TChannelDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TChannelDictLN_TChannel;
extern G__linked_taginfo G__TChannelDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TChannelDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;

/* STUB derived class for protected member access */
