/********************************************************************
* TFragmentSelectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFragmentSelectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFragmentSelectorDict();
extern void G__cpp_setup_inheritanceTFragmentSelectorDict();
extern void G__cpp_setup_typetableTFragmentSelectorDict();
extern void G__cpp_setup_memvarTFragmentSelectorDict();
extern void G__cpp_setup_globalTFragmentSelectorDict();
extern void G__cpp_setup_memfuncTFragmentSelectorDict();
extern void G__cpp_setup_funcTFragmentSelectorDict();
extern void G__set_cpp_environmentTFragmentSelectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TFragmentSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFragmentSelectorDictLN_TClass;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TBuffer;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TMemberInspector;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TObject;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TList;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TTree;
extern G__linked_taginfo G__TFragmentSelectorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TSelector;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_maplETStringcOTProofcLcLMD5Mod_tcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTProofcLcLMD5Mod_tgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TFragment;
extern G__linked_taginfo G__TFragmentSelectorDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentSelectorDictLN_TFragmentSelector;

/* STUB derived class for protected member access */
