/********************************************************************
* TFragmentQueueDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFragmentQueueDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFragmentQueueDict();
extern void G__cpp_setup_inheritanceTFragmentQueueDict();
extern void G__cpp_setup_typetableTFragmentQueueDict();
extern void G__cpp_setup_memvarTFragmentQueueDict();
extern void G__cpp_setup_globalTFragmentQueueDict();
extern void G__cpp_setup_memfuncTFragmentQueueDict();
extern void G__cpp_setup_funcTFragmentQueueDict();
extern void G__set_cpp_environmentTFragmentQueueDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TFragmentQueue.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFragmentQueueDictLN_TClass;
extern G__linked_taginfo G__TFragmentQueueDictLN_TBuffer;
extern G__linked_taginfo G__TFragmentQueueDictLN_TMemberInspector;
extern G__linked_taginfo G__TFragmentQueueDictLN_TObject;
extern G__linked_taginfo G__TFragmentQueueDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_string;
extern G__linked_taginfo G__TFragmentQueueDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_TStopwatch;
extern G__linked_taginfo G__TFragmentQueueDictLN_TFragment;
extern G__linked_taginfo G__TFragmentQueueDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_TFragmentQueue;
extern G__linked_taginfo G__TFragmentQueueDictLN_maplEstringcOTFragmentQueuemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTFragmentQueuemUgRsPgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_dequelETFragmentmUcOallocatorlETFragmentmUgRsPgR;
extern G__linked_taginfo G__TFragmentQueueDictLN_queuelETFragmentmUcOdequelETFragmentmUcOallocatorlETFragmentmUgRsPgRsPgR;

/* STUB derived class for protected member access */
