/********************************************************************
* TFragmentDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFragmentDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFragmentDict();
extern void G__cpp_setup_inheritanceTFragmentDict();
extern void G__cpp_setup_typetableTFragmentDict();
extern void G__cpp_setup_memvarTFragmentDict();
extern void G__cpp_setup_globalTFragmentDict();
extern void G__cpp_setup_memfuncTFragmentDict();
extern void G__cpp_setup_funcTFragmentDict();
extern void G__set_cpp_environmentTFragmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TFragment.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFragmentDictLN_TClass;
extern G__linked_taginfo G__TFragmentDictLN_TBuffer;
extern G__linked_taginfo G__TFragmentDictLN_TMemberInspector;
extern G__linked_taginfo G__TFragmentDictLN_TObject;
extern G__linked_taginfo G__TFragmentDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TFragmentDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TFragmentDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFragmentDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFragmentDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFragmentDictLN_TFragment;
extern G__linked_taginfo G__TFragmentDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TFragmentDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
