/********************************************************************
* TGRSIRunInfoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIRunInfoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIRunInfoDict();
extern void G__cpp_setup_inheritanceTGRSIRunInfoDict();
extern void G__cpp_setup_typetableTGRSIRunInfoDict();
extern void G__cpp_setup_memvarTGRSIRunInfoDict();
extern void G__cpp_setup_globalTGRSIRunInfoDict();
extern void G__cpp_setup_memfuncTGRSIRunInfoDict();
extern void G__cpp_setup_funcTGRSIRunInfoDict();
extern void G__set_cpp_environmentTGRSIRunInfoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIRunInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIRunInfoDictLN_TClass;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_TObject;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_string;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_TTree;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIRunInfoDictLN_TGRSIRunInfo;

/* STUB derived class for protected member access */
