
OBJECTS = TGRSIDetector.o TGRSIDetectorData.o TGRSIDetectorHit.o TGRSIDetectorDict.o  
DICTOBJ = $(INCDIR)/TGRSIDetectorHit.h $(INCDIR)/TGRSIDetector.h  
DICTNAM = TGRSIDetector
NAME = GRSIDetector

-include ../../../make.rules
