/********************************************************************
* TGRSIDetectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIDetectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIDetectorDict();
extern void G__cpp_setup_inheritanceTGRSIDetectorDict();
extern void G__cpp_setup_typetableTGRSIDetectorDict();
extern void G__cpp_setup_memvarTGRSIDetectorDict();
extern void G__cpp_setup_globalTGRSIDetectorDict();
extern void G__cpp_setup_memfuncTGRSIDetectorDict();
extern void G__cpp_setup_funcTGRSIDetectorDict();
extern void G__set_cpp_environmentTGRSIDetectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIDetector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIDetectorDictLN_TClass;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TObject;
extern G__linked_taginfo G__TGRSIDetectorDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_MNEMONIC;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TFragment;
extern G__linked_taginfo G__TGRSIDetectorDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TChannel;
extern G__linked_taginfo G__TGRSIDetectorDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDictLN_TGRSIDetector;

/* STUB derived class for protected member access */
