/********************************************************************
* TGRSIDetectorHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIDetectorHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIDetectorHitDict();
extern void G__cpp_setup_inheritanceTGRSIDetectorHitDict();
extern void G__cpp_setup_typetableTGRSIDetectorHitDict();
extern void G__cpp_setup_memvarTGRSIDetectorHitDict();
extern void G__cpp_setup_globalTGRSIDetectorHitDict();
extern void G__cpp_setup_memfuncTGRSIDetectorHitDict();
extern void G__cpp_setup_funcTGRSIDetectorHitDict();
extern void G__set_cpp_environmentTGRSIDetectorHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIDetectorHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TClass;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TObject;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGRSIDetectorHitDictLN_TGRSIDetectorHit;

/* STUB derived class for protected member access */
