/********************************************************************
* TGRSIDetectorDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIDetectorDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIDetectorDataDict();
extern void G__cpp_setup_inheritanceTGRSIDetectorDataDict();
extern void G__cpp_setup_typetableTGRSIDetectorDataDict();
extern void G__cpp_setup_memvarTGRSIDetectorDataDict();
extern void G__cpp_setup_globalTGRSIDetectorDataDict();
extern void G__cpp_setup_memfuncTGRSIDetectorDataDict();
extern void G__cpp_setup_funcTGRSIDetectorDataDict();
extern void G__set_cpp_environmentTGRSIDetectorDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIDetectorData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIDetectorDataDictLN_TClass;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_TObject;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIDetectorDataDictLN_TGRSIDetectorData;

/* STUB derived class for protected member access */
