/********************************************************************
* TMidasEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TMidasEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMidasEventDict();
extern void G__cpp_setup_inheritanceTMidasEventDict();
extern void G__cpp_setup_typetableTMidasEventDict();
extern void G__cpp_setup_memvarTMidasEventDict();
extern void G__cpp_setup_globalTMidasEventDict();
extern void G__cpp_setup_memfuncTMidasEventDict();
extern void G__cpp_setup_funcTMidasEventDict();
extern void G__set_cpp_environmentTMidasEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TMidasEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMidasEventDictLN_TClass;
extern G__linked_taginfo G__TMidasEventDictLN_TBuffer;
extern G__linked_taginfo G__TMidasEventDictLN_TMemberInspector;
extern G__linked_taginfo G__TMidasEventDictLN_TObject;
extern G__linked_taginfo G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMidasEventDictLN_TMidas_EVENT_HEADER;
extern G__linked_taginfo G__TMidasEventDictLN_TMidasEvent;
extern G__linked_taginfo G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK;
extern G__linked_taginfo G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK32;

/* STUB derived class for protected member access */
