/********************************************************************
* TMidasFileDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TMidasFileDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMidasFileDict();
extern void G__cpp_setup_inheritanceTMidasFileDict();
extern void G__cpp_setup_typetableTMidasFileDict();
extern void G__cpp_setup_memvarTMidasFileDict();
extern void G__cpp_setup_globalTMidasFileDict();
extern void G__cpp_setup_memfuncTMidasFileDict();
extern void G__cpp_setup_funcTMidasFileDict();
extern void G__set_cpp_environmentTMidasFileDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TMidasFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMidasFileDictLN_TClass;
extern G__linked_taginfo G__TMidasFileDictLN_TBuffer;
extern G__linked_taginfo G__TMidasFileDictLN_TMemberInspector;
extern G__linked_taginfo G__TMidasFileDictLN_TObject;
extern G__linked_taginfo G__TMidasFileDictLN_string;
extern G__linked_taginfo G__TMidasFileDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMidasFileDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMidasFileDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMidasFileDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMidasFileDictLN_TMidasEvent;
extern G__linked_taginfo G__TMidasFileDictLN_TMidasFile;

/* STUB derived class for protected member access */
