/********************************************************************
* TGRSIFunctionsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIFunctionsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIFunctionsDict();
extern void G__cpp_setup_inheritanceTGRSIFunctionsDict();
extern void G__cpp_setup_typetableTGRSIFunctionsDict();
extern void G__cpp_setup_memvarTGRSIFunctionsDict();
extern void G__cpp_setup_globalTGRSIFunctionsDict();
extern void G__cpp_setup_memfuncTGRSIFunctionsDict();
extern void G__cpp_setup_funcTGRSIFunctionsDict();
extern void G__set_cpp_environmentTGRSIFunctionsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/GRSISort/include/TGRSIFunctions.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIFunctionsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIFunctionsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFunctionsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIFunctionsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFunctionsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIFunctionsDictLN_TGRSIFunctions;

/* STUB derived class for protected member access */
