/********************************************************************
* TGRSIFitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIFitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIFitDict();
extern void G__cpp_setup_inheritanceTGRSIFitDict();
extern void G__cpp_setup_typetableTGRSIFitDict();
extern void G__cpp_setup_memvarTGRSIFitDict();
extern void G__cpp_setup_globalTGRSIFitDict();
extern void G__cpp_setup_memfuncTGRSIFitDict();
extern void G__cpp_setup_funcTGRSIFitDict();
extern void G__set_cpp_environmentTGRSIFitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/GRSISort/include/TGRSIFit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIFitDictLN_TClass;
extern G__linked_taginfo G__TGRSIFitDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIFitDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIFitDictLN_TObject;
extern G__linked_taginfo G__TGRSIFitDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIFitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGRSIFitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TH1;
extern G__linked_taginfo G__TGRSIFitDictLN_maplEunsignedsPintcOpairlEdoublecOdoublegRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOpairlEdoublecOdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TGRSIFitDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TGRSIFitDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TGRSIFitDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIFitDictLN_TGRSIFit;

/* STUB derived class for protected member access */
