
OBJECTS = TTigress.o TTigressData.o TTigressHit.o TBGOData.o TCrystalHit.o TTigressDict.o
DICTOBJ = $(INCDIR)/TCrystalHit.h $(INCDIR)/TTigressHit.h $(INCDIR)/TTigress.h 
DICTNAM = TTigress
NAME = Tigress

-include ../../../make.rules
