/********************************************************************
* TBGODataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TBGODataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTBGODataDict();
extern void G__cpp_setup_inheritanceTBGODataDict();
extern void G__cpp_setup_typetableTBGODataDict();
extern void G__cpp_setup_memvarTBGODataDict();
extern void G__cpp_setup_globalTBGODataDict();
extern void G__cpp_setup_memfuncTBGODataDict();
extern void G__cpp_setup_funcTBGODataDict();
extern void G__set_cpp_environmentTBGODataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TBGOData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TBGODataDictLN_TClass;
extern G__linked_taginfo G__TBGODataDictLN_TBuffer;
extern G__linked_taginfo G__TBGODataDictLN_TMemberInspector;
extern G__linked_taginfo G__TBGODataDictLN_TObject;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TBGODataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TBGODataDictLN_MNEMONIC;
extern G__linked_taginfo G__TBGODataDictLN_TFragment;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TBGODataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TBGODataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_TChannel;
extern G__linked_taginfo G__TBGODataDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TBGODataDictLN_TBGOData;
extern G__linked_taginfo G__TBGODataDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TBGODataDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
