/********************************************************************
* TCrystalHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCrystalHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCrystalHitDict();
extern void G__cpp_setup_inheritanceTCrystalHitDict();
extern void G__cpp_setup_typetableTCrystalHitDict();
extern void G__cpp_setup_memvarTCrystalHitDict();
extern void G__cpp_setup_globalTCrystalHitDict();
extern void G__cpp_setup_memfuncTCrystalHitDict();
extern void G__cpp_setup_funcTCrystalHitDict();
extern void G__set_cpp_environmentTCrystalHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TCrystalHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCrystalHitDictLN_TClass;
extern G__linked_taginfo G__TCrystalHitDictLN_TBuffer;
extern G__linked_taginfo G__TCrystalHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TCrystalHitDictLN_TObject;
extern G__linked_taginfo G__TCrystalHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCrystalHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCrystalHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCrystalHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TCrystalHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TCrystalHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TCrystalHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TCrystalHitDictLN_TCrystalHit;
extern G__linked_taginfo G__TCrystalHitDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TCrystalHitDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
