/********************************************************************
* TTigressHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTigressHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTigressHitDict();
extern void G__cpp_setup_inheritanceTTigressHitDict();
extern void G__cpp_setup_typetableTTigressHitDict();
extern void G__cpp_setup_memvarTTigressHitDict();
extern void G__cpp_setup_globalTTigressHitDict();
extern void G__cpp_setup_memfuncTTigressHitDict();
extern void G__cpp_setup_funcTTigressHitDict();
extern void G__set_cpp_environmentTTigressHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TTigressHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTigressHitDictLN_TClass;
extern G__linked_taginfo G__TTigressHitDictLN_TBuffer;
extern G__linked_taginfo G__TTigressHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TTigressHitDictLN_TObject;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressHitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TTigressHitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTigressHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTigressHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTigressHitDictLN_TVector3;
extern G__linked_taginfo G__TTigressHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TTigressHitDictLN_TCrystalHit;
extern G__linked_taginfo G__TTigressHitDictLN_TTigressHit;
extern G__linked_taginfo G__TTigressHitDictLN_vectorlETCrystalHitcOallocatorlETCrystalHitgRsPgR;
extern G__linked_taginfo G__TTigressHitDictLN_reverse_iteratorlEvectorlETCrystalHitcOallocatorlETCrystalHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
