/********************************************************************
* TTigressDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTigressDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTigressDict();
extern void G__cpp_setup_inheritanceTTigressDict();
extern void G__cpp_setup_typetableTTigressDict();
extern void G__cpp_setup_memvarTTigressDict();
extern void G__cpp_setup_globalTTigressDict();
extern void G__cpp_setup_memfuncTTigressDict();
extern void G__cpp_setup_funcTTigressDict();
extern void G__set_cpp_environmentTTigressDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TTigress.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTigressDictLN_TClass;
extern G__linked_taginfo G__TTigressDictLN_TBuffer;
extern G__linked_taginfo G__TTigressDictLN_TMemberInspector;
extern G__linked_taginfo G__TTigressDictLN_TObject;
extern G__linked_taginfo G__TTigressDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TTigressDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDictLN_MNEMONIC;
extern G__linked_taginfo G__TTigressDictLN_TFragment;
extern G__linked_taginfo G__TTigressDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TTigressDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_TChannel;
extern G__linked_taginfo G__TTigressDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTigressDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTigressDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTigressDictLN_TVector3;
extern G__linked_taginfo G__TTigressDictLN_TTigressHit;
extern G__linked_taginfo G__TTigressDictLN_vectorlETCrystalHitcOallocatorlETCrystalHitgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlETCrystalHitcOallocatorlETCrystalHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TTigressDictLN_TTigressData;
extern G__linked_taginfo G__TTigressDictLN_setlEunsignedsPshortcOlesslEunsignedsPshortgRcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTigressDictLN_TBGOData;
extern G__linked_taginfo G__TTigressDictLN_TGRSIDetector;
extern G__linked_taginfo G__TTigressDictLN_TTigress;
extern G__linked_taginfo G__TTigressDictLN_vectorlETTigressHitcOallocatorlETTigressHitgRsPgR;
extern G__linked_taginfo G__TTigressDictLN_reverse_iteratorlEvectorlETTigressHitcOallocatorlETTigressHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
