/********************************************************************
* TBetaDecayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TBetaDecayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTBetaDecayDict();
extern void G__cpp_setup_inheritanceTBetaDecayDict();
extern void G__cpp_setup_typetableTBetaDecayDict();
extern void G__cpp_setup_memvarTBetaDecayDict();
extern void G__cpp_setup_globalTBetaDecayDict();
extern void G__cpp_setup_memfuncTBetaDecayDict();
extern void G__cpp_setup_funcTBetaDecayDict();
extern void G__set_cpp_environmentTBetaDecayDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TBetaDecay.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TBetaDecayDictLN_TClass;
extern G__linked_taginfo G__TBetaDecayDictLN_TBuffer;
extern G__linked_taginfo G__TBetaDecayDictLN_TMemberInspector;
extern G__linked_taginfo G__TBetaDecayDictLN_TObject;
extern G__linked_taginfo G__TBetaDecayDictLN_TNamed;
extern G__linked_taginfo G__TBetaDecayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TBetaDecayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TBetaDecayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TBetaDecayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TBetaDecayDictLN_TNucleus;
extern G__linked_taginfo G__TBetaDecayDictLN_TBetaDecay;

/* STUB derived class for protected member access */
