/********************************************************************
* TEnergyLevelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TEnergyLevelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEnergyLevelDict();
extern void G__cpp_setup_inheritanceTEnergyLevelDict();
extern void G__cpp_setup_typetableTEnergyLevelDict();
extern void G__cpp_setup_memvarTEnergyLevelDict();
extern void G__cpp_setup_globalTEnergyLevelDict();
extern void G__cpp_setup_memfuncTEnergyLevelDict();
extern void G__cpp_setup_funcTEnergyLevelDict();
extern void G__set_cpp_environmentTEnergyLevelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TEnergyLevel.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEnergyLevelDictLN_TClass;
extern G__linked_taginfo G__TEnergyLevelDictLN_TBuffer;
extern G__linked_taginfo G__TEnergyLevelDictLN_TMemberInspector;
extern G__linked_taginfo G__TEnergyLevelDictLN_TObject;
extern G__linked_taginfo G__TEnergyLevelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEnergyLevelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEnergyLevelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEnergyLevelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEnergyLevelDictLN_TEnergyLevel;

/* STUB derived class for protected member access */
