/********************************************************************
* TTransitionDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTransitionDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTransitionDict();
extern void G__cpp_setup_inheritanceTTransitionDict();
extern void G__cpp_setup_typetableTTransitionDict();
extern void G__cpp_setup_memvarTTransitionDict();
extern void G__cpp_setup_globalTTransitionDict();
extern void G__cpp_setup_memfuncTTransitionDict();
extern void G__cpp_setup_funcTTransitionDict();
extern void G__set_cpp_environmentTTransitionDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TTransition.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTransitionDictLN_TClass;
extern G__linked_taginfo G__TTransitionDictLN_TBuffer;
extern G__linked_taginfo G__TTransitionDictLN_TMemberInspector;
extern G__linked_taginfo G__TTransitionDictLN_TObject;
extern G__linked_taginfo G__TTransitionDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTransitionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTransitionDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTransitionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTransitionDictLN_TTransition;

/* STUB derived class for protected member access */
