/********************************************************************
* TECalDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TECalDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTECalDict();
extern void G__cpp_setup_inheritanceTECalDict();
extern void G__cpp_setup_typetableTECalDict();
extern void G__cpp_setup_memvarTECalDict();
extern void G__cpp_setup_globalTECalDict();
extern void G__cpp_setup_memfuncTECalDict();
extern void G__cpp_setup_funcTECalDict();
extern void G__set_cpp_environmentTECalDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TECal.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TECalDictLN_TClass;
extern G__linked_taginfo G__TECalDictLN_TBuffer;
extern G__linked_taginfo G__TECalDictLN_TMemberInspector;
extern G__linked_taginfo G__TECalDictLN_TObject;
extern G__linked_taginfo G__TECalDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TECalDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TECalDictLN_maplEunsignedsPintcOboolcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOboolgRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_maplEunsignedsPintcOunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_maplEunsignedsPintcOpairlEdoublecOdoublegRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOpairlEdoublecOdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TECalDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TECalDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TECalDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TECalDictLN_TECal;

/* STUB derived class for protected member access */
