/********************************************************************
* TECalDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TECalDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTECalDict();
extern void G__cpp_setup_inheritanceTECalDict();
extern void G__cpp_setup_typetableTECalDict();
extern void G__cpp_setup_memvarTECalDict();
extern void G__cpp_setup_globalTECalDict();
extern void G__cpp_setup_memfuncTECalDict();
extern void G__cpp_setup_funcTECalDict();
extern void G__set_cpp_environmentTECalDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TECal.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TECalDictLN_TClass;
extern G__linked_taginfo G__TECalDictLN_TBuffer;
extern G__linked_taginfo G__TECalDictLN_TMemberInspector;
extern G__linked_taginfo G__TECalDictLN_TObject;
extern G__linked_taginfo G__TECalDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TECalDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TECalDictLN_TECal;

/* STUB derived class for protected member access */
