/********************************************************************
* TGRSIintDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIintDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIintDict();
extern void G__cpp_setup_inheritanceTGRSIintDict();
extern void G__cpp_setup_typetableTGRSIintDict();
extern void G__cpp_setup_memvarTGRSIintDict();
extern void G__cpp_setup_globalTGRSIintDict();
extern void G__cpp_setup_memfuncTGRSIintDict();
extern void G__cpp_setup_funcTGRSIintDict();
extern void G__set_cpp_environmentTGRSIintDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIint.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIintDictLN_TClass;
extern G__linked_taginfo G__TGRSIintDictLN_TBuffer;
extern G__linked_taginfo G__TGRSIintDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSIintDictLN_TObject;
extern G__linked_taginfo G__TGRSIintDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGRSIintDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TGRSIintDictLN_string;
extern G__linked_taginfo G__TGRSIintDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIintDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIintDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIintDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIintDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGRSIintDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIintDictLN_TQObject;
extern G__linked_taginfo G__TGRSIintDictLN_TApplication;
extern G__linked_taginfo G__TGRSIintDictLN_TRint;
extern G__linked_taginfo G__TGRSIintDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSIintDictLN_TEnv;
extern G__linked_taginfo G__TGRSIintDictLN_TGRSIint;

/* STUB derived class for protected member access */
