/********************************************************************
* TGRSIOptionsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSIOptionsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSIOptionsDict();
extern void G__cpp_setup_inheritanceTGRSIOptionsDict();
extern void G__cpp_setup_typetableTGRSIOptionsDict();
extern void G__cpp_setup_memvarTGRSIOptionsDict();
extern void G__cpp_setup_globalTGRSIOptionsDict();
extern void G__cpp_setup_memfuncTGRSIOptionsDict();
extern void G__cpp_setup_funcTGRSIOptionsDict();
extern void G__set_cpp_environmentTGRSIOptionsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TGRSIOptions.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSIOptionsDictLN_string;
extern G__linked_taginfo G__TGRSIOptionsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSIOptionsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIOptionsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSIOptionsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSIOptionsDictLN_TGRSIOptions;
extern G__linked_taginfo G__TGRSIOptionsDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TGRSIOptionsDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
