/********************************************************************
* TKinematicsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TKinematicsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTKinematicsDict();
extern void G__cpp_setup_inheritanceTKinematicsDict();
extern void G__cpp_setup_typetableTKinematicsDict();
extern void G__cpp_setup_memvarTKinematicsDict();
extern void G__cpp_setup_globalTKinematicsDict();
extern void G__cpp_setup_memfuncTKinematicsDict();
extern void G__cpp_setup_funcTKinematicsDict();
extern void G__set_cpp_environmentTKinematicsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/GRSISort/include/TKinematics.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TKinematicsDictLN_TClass;
extern G__linked_taginfo G__TKinematicsDictLN_TBuffer;
extern G__linked_taginfo G__TKinematicsDictLN_TMemberInspector;
extern G__linked_taginfo G__TKinematicsDictLN_TObject;
extern G__linked_taginfo G__TKinematicsDictLN_TNamed;
extern G__linked_taginfo G__TKinematicsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TKinematicsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TKinematicsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TKinematicsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TKinematicsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TKinematicsDictLN_TSpline3;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TKinematicsDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TKinematicsDictLN_TVector3;
extern G__linked_taginfo G__TKinematicsDictLN_TLorentzVector;
extern G__linked_taginfo G__TKinematicsDictLN_TNucleus;
extern G__linked_taginfo G__TKinematicsDictLN_TKinematics;

/* STUB derived class for protected member access */
