/********************************************************************
* TGriffinHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGriffinHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGriffinHitDict();
extern void G__cpp_setup_inheritanceTGriffinHitDict();
extern void G__cpp_setup_typetableTGriffinHitDict();
extern void G__cpp_setup_memvarTGriffinHitDict();
extern void G__cpp_setup_globalTGriffinHitDict();
extern void G__cpp_setup_memfuncTGriffinHitDict();
extern void G__cpp_setup_funcTGriffinHitDict();
extern void G__set_cpp_environmentTGriffinHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TGriffinHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGriffinHitDictLN_TClass;
extern G__linked_taginfo G__TGriffinHitDictLN_TBuffer;
extern G__linked_taginfo G__TGriffinHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TGriffinHitDictLN_TObject;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinHitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGriffinHitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGriffinHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGriffinHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGriffinHitDictLN_TVector3;
extern G__linked_taginfo G__TGriffinHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TGriffinHitDictLN_TCrystalHit;
extern G__linked_taginfo G__TGriffinHitDictLN_TGriffinHit;
extern G__linked_taginfo G__TGriffinHitDictLN_vectorlETCrystalHitcOallocatorlETCrystalHitgRsPgR;
extern G__linked_taginfo G__TGriffinHitDictLN_reverse_iteratorlEvectorlETCrystalHitcOallocatorlETCrystalHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
