/********************************************************************
* TGriffinDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGriffinDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGriffinDataDict();
extern void G__cpp_setup_inheritanceTGriffinDataDict();
extern void G__cpp_setup_typetableTGriffinDataDict();
extern void G__cpp_setup_memvarTGriffinDataDict();
extern void G__cpp_setup_globalTGriffinDataDict();
extern void G__cpp_setup_memfuncTGriffinDataDict();
extern void G__cpp_setup_funcTGriffinDataDict();
extern void G__set_cpp_environmentTGriffinDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/rdunlop/Programs/GRSISort/include/TGriffinData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGriffinDataDictLN_TClass;
extern G__linked_taginfo G__TGriffinDataDictLN_TBuffer;
extern G__linked_taginfo G__TGriffinDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TGriffinDataDictLN_TObject;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_MNEMONIC;
extern G__linked_taginfo G__TGriffinDataDictLN_TFragment;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGriffinDataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TChannel;
extern G__linked_taginfo G__TGriffinDataDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TGriffinDataDictLN_TGriffinData;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
