/********************************************************************
* TSceptarDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSceptarDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSceptarDict();
extern void G__cpp_setup_inheritanceTSceptarDict();
extern void G__cpp_setup_typetableTSceptarDict();
extern void G__cpp_setup_memvarTSceptarDict();
extern void G__cpp_setup_globalTSceptarDict();
extern void G__cpp_setup_memfuncTSceptarDict();
extern void G__cpp_setup_funcTSceptarDict();
extern void G__set_cpp_environmentTSceptarDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TSceptar.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSceptarDictLN_TClass;
extern G__linked_taginfo G__TSceptarDictLN_TBuffer;
extern G__linked_taginfo G__TSceptarDictLN_TMemberInspector;
extern G__linked_taginfo G__TSceptarDictLN_TObject;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDictLN_MNEMONIC;
extern G__linked_taginfo G__TSceptarDictLN_TFragment;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TSceptarDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_TChannel;
extern G__linked_taginfo G__TSceptarDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSceptarDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSceptarDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSceptarDictLN_TVector3;
extern G__linked_taginfo G__TSceptarDictLN_TSceptarHit;
extern G__linked_taginfo G__TSceptarDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TSceptarDictLN_TSceptarData;
extern G__linked_taginfo G__TSceptarDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDictLN_TGRSIDetector;
extern G__linked_taginfo G__TSceptarDictLN_TSceptar;
extern G__linked_taginfo G__TSceptarDictLN_vectorlETSceptarHitcOallocatorlETSceptarHitgRsPgR;
extern G__linked_taginfo G__TSceptarDictLN_reverse_iteratorlEvectorlETSceptarHitcOallocatorlETSceptarHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
