/********************************************************************
* TSceptarDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSceptarDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSceptarDataDict();
extern void G__cpp_setup_inheritanceTSceptarDataDict();
extern void G__cpp_setup_typetableTSceptarDataDict();
extern void G__cpp_setup_memvarTSceptarDataDict();
extern void G__cpp_setup_globalTSceptarDataDict();
extern void G__cpp_setup_memfuncTSceptarDataDict();
extern void G__cpp_setup_funcTSceptarDataDict();
extern void G__set_cpp_environmentTSceptarDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TSceptarData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSceptarDataDictLN_TClass;
extern G__linked_taginfo G__TSceptarDataDictLN_TBuffer;
extern G__linked_taginfo G__TSceptarDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TSceptarDataDictLN_TObject;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDataDictLN_MNEMONIC;
extern G__linked_taginfo G__TSceptarDataDictLN_TFragment;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TSceptarDataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_TChannel;
extern G__linked_taginfo G__TSceptarDataDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TSceptarDataDictLN_TSceptarData;
extern G__linked_taginfo G__TSceptarDataDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarDataDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
