/********************************************************************
* TSceptarHitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSceptarHitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSceptarHitDict();
extern void G__cpp_setup_inheritanceTSceptarHitDict();
extern void G__cpp_setup_typetableTSceptarHitDict();
extern void G__cpp_setup_memvarTSceptarHitDict();
extern void G__cpp_setup_globalTSceptarHitDict();
extern void G__cpp_setup_memfuncTSceptarHitDict();
extern void G__cpp_setup_funcTSceptarHitDict();
extern void G__set_cpp_environmentTSceptarHitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TSceptarHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSceptarHitDictLN_TClass;
extern G__linked_taginfo G__TSceptarHitDictLN_TBuffer;
extern G__linked_taginfo G__TSceptarHitDictLN_TMemberInspector;
extern G__linked_taginfo G__TSceptarHitDictLN_TObject;
extern G__linked_taginfo G__TSceptarHitDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarHitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarHitDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSceptarHitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TSceptarHitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSceptarHitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSceptarHitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSceptarHitDictLN_TVector3;
extern G__linked_taginfo G__TSceptarHitDictLN_TGRSIDetectorHit;
extern G__linked_taginfo G__TSceptarHitDictLN_TSceptarHit;

/* STUB derived class for protected member access */
