.TH GADD 1
.SH NAME
gadd \- Merge ROOT files into one file, with support for GRSISort classes
.SH SYNOPSIS
.B gadd 
[\fB\-kTO\fR]
[\fB\-f\fR [\fI0-9\fR]]
[\fB\-v\fR [\fIverbosity\fR]]
[\fB\-n\fR \fImaxopenedfiles\fR]
.I "targetfile sourcefiles ..."
.PP
Options can be grouped behind a single - (minus character).
.SH DESCRIPTION
This program will add histograms from a list of 
.B ROOT 
files and write them to a target 
.B ROOT 
file. The target file is newly created and must not be identical to
one of the source files. 
This program was copied from \fBhadd\fR and adapted to handle GRSISort
classes.
.SH OPTIONS
.TP
.B \-k
Don't exit on corrupt or non-existant input files, but skip the offending files
instead.
.TP
.B \-T
Don't merge trees.
.TP
.B \-O
When merging TTrees, re-optimize the basket size.
.TP
\fB\-v\fR [\fIverbosity\fR]
Explicitly set the verbosity level; 0 requests no output, 99 is the default.
.TP
\fB\-n\fR \fImaxopenedfiles\fR
Open at most 'maxopenedfiles' at once, use 0 to request the system maximum.
.TP
\fB\-f\fR [\fI0-9\fR]
Force the creation of the target file, i.e. overwrite an existing file if it 
exists.
One can also specify the compression level of the target file.
By default the compression level is 1, but if "-f0" is specified, the target 
file will not be compressed.
.SH SEE ALSO
.SB
\fIhadd\fR(1), \fIgrsisort\fR(1), \fIroot\fR(1)
.PP
.\" .SE
For documentation on GRSISort, see
.UR https://github.com/GRIFFINCollaboration/GRSISort/wiki
\fIhttps://github.com/GRIFFINCollaboration/GRSISort/wiki\fR
.UE
.PP
The GRSISort classes are all documented by the automatical documentation system
.UR
\fIhttps://rawgit.com/wiki/GriffinCollaboration/GRSISort/technical-docs/ROOT-Gen-Html/htmldoc/GRSISORT_Index.html\fR
here.
.UE
.SH AUTHORS
P.C. Bender, R. Dunlop, V. Bildstein, D. Miller
