.\" Process this file with
.\" groff -man -Tascii grsisort.1
.\"
.TH grsisort 1
.SH NAME
grsisort \- sort data from GRIFFIN or TIGRESS experiments
.SH SYNOPSIS
.B grsisort 
[\fB\-alqs\fR]
[\fB\-\-no_waveforms\fR]
[\fB\-\-record_stats\fR]
[\fB\-\-suppress_error(s)\fR]
[\fB\-\-log_errors\fR]
[\fB\-\-work_harder\fR]
[\fB\-\-reading_material\fR]
[\fB\-\-bad_frags\fR | \fB\-\-bad_fragments\fR | \fB\-\-write_bad_frags\fR |
\fB\-\-write_bad_fragments\fR]
[\fB\-\-no_speed\fR]
[\fB\-\-ignore_odb\fR]
[\fB\-h\fR \fIhost\fR]
[\fB\-e\fR \fIexpt. name\fR]
[\fIfile\fR ...]
.PP
.B grsisort 
[\fB\-?\fR] |
[\fB\-\-help\fR]
.PP
Options can be grouped behind a single - (minus character).
File names with extensions .mid or .bz2 are treated as midas input files.
File names with extension .root are treated as root input files.
File names with extension .cal are treated as calibraton files.
File names with extension .info are treated as run-info files.
File names with extension .xml are treated as ODB input in xml format.
File names with extension .odb are treated as c-like ODB input (not implemented
yet).
File names with extension .C, .c, .C+, or .c+ are treated as root macro files.
.SH DESCRIPTION
.B grsisort
sorts data from GRIFFIN or TIGRESS experiments.
.SH OPTIONS
.TP
.BR \-? ", " \-\-help
Display README.html in a ROOT browser.
.TP
.B \-a
Sort into analysis tree.
.TP
.B \-l
Don't display splash screen at start.
.TP
.B \-q
Quit after sorting, don't drop into interactive shell.
.TP
.B \-s
Sort(?).
.TP
.B \-\-no_waveforms
Don't include waveforms in the output tree.
.TP
.B \-\-record_stats
Record run statistics to log-file.
.TP
.B \-\-suppress_error(s)
Suppress output for corrupt events.
.TP
.B \-\-log_errors
Write parsing errors to log-file.
.TP
.B \-\-work_harder
Executes a macro with .x after the sorting is done. The macro has to be provided
as one of the files.
.TP
.B \-\-reading_material
Provides reading material while waiting.
.TP
.BR \-\-bad_frags | \-\-bad_fragments | \-\-write_bad_frags | \-\-write_bad_fragments
Writes fragments with parsing errors to BadFragmentTree.
.TP
.B \-\-no_speed
Doesn't open the PROOF speedometer.
.TP
.B \-\-ignore_odb
Ignores the ODB stored in the midas file, useful if dealing with a corrupt ODB.
.TP
\fB\-h\fR \fIhost\fR
Get data from \fIhost\fR instead of file.
.TP
\fB\-e\fR \fIexpt. name\fR
Use \fIexpt. name\fR as experiment name to connect to.
.SH EXAMPLES
To sort a midas file into a fragment-tree, running a script called "Script.C" 
afterwards before dropping into the interactive shell:
.PP
.nf
.RS
grsisort <midas file> --work_harder Script.C
.RE
.fi
.PP
To sort a midas file into an analysis-tree using a custom calibraton and 
run-info file, without showing the splash screen and without the interactive
shell:
.PP
.nf
.RS
grsisort -alq <midas file> <.cal file> <.info file>
.RE
.fi
.PP
.SH AUTHORS
P.C. Bender, R. Dunlop, V. Bildstein, D. Miller
