/********************************************************************
* TGRSITransitionDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGRSITransitionDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGRSITransitionDict();
extern void G__cpp_setup_inheritanceTGRSITransitionDict();
extern void G__cpp_setup_typetableTGRSITransitionDict();
extern void G__cpp_setup_memvarTGRSITransitionDict();
extern void G__cpp_setup_globalTGRSITransitionDict();
extern void G__cpp_setup_memfuncTGRSITransitionDict();
extern void G__cpp_setup_funcTGRSITransitionDict();
extern void G__set_cpp_environmentTGRSITransitionDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/grifuser/packages/GRSISort/include/TGRSITransition.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGRSITransitionDictLN_TClass;
extern G__linked_taginfo G__TGRSITransitionDictLN_TBuffer;
extern G__linked_taginfo G__TGRSITransitionDictLN_TMemberInspector;
extern G__linked_taginfo G__TGRSITransitionDictLN_TObject;
extern G__linked_taginfo G__TGRSITransitionDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGRSITransitionDictLN_TGRSITransition;

/* STUB derived class for protected member access */
