/********************************************************************
* TNucleusDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TNucleusDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTNucleusDict();
extern void G__cpp_setup_inheritanceTNucleusDict();
extern void G__cpp_setup_typetableTNucleusDict();
extern void G__cpp_setup_memvarTNucleusDict();
extern void G__cpp_setup_globalTNucleusDict();
extern void G__cpp_setup_memfuncTNucleusDict();
extern void G__cpp_setup_funcTNucleusDict();
extern void G__set_cpp_environmentTNucleusDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
<<<<<<< HEAD
#include "/home/grifuser/packages/GRSISort/include/TNucleus.h"
=======
#include "/home/tiguser/packages/GRSISort/include/TNucleus.h"
>>>>>>> 4a316a9dd7ac23b728aa0d427aecf68b93bd0085
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TNucleusDictLN_TClass;
extern G__linked_taginfo G__TNucleusDictLN_TBuffer;
extern G__linked_taginfo G__TNucleusDictLN_TMemberInspector;
extern G__linked_taginfo G__TNucleusDictLN_TObject;
extern G__linked_taginfo G__TNucleusDictLN_TNamed;
extern G__linked_taginfo G__TNucleusDictLN_string;
extern G__linked_taginfo G__TNucleusDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TNucleusDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TNucleusDictLN_TList;
extern G__linked_taginfo G__TNucleusDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TNucleusDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TNucleusDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TNucleusDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TNucleusDictLN_TNucleus;

/* STUB derived class for protected member access */
