/********************************************************************
* TTriFoilDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TTriFoilDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTriFoilDict();
extern void G__cpp_setup_inheritanceTTriFoilDict();
extern void G__cpp_setup_typetableTTriFoilDict();
extern void G__cpp_setup_memvarTTriFoilDict();
extern void G__cpp_setup_globalTTriFoilDict();
extern void G__cpp_setup_memfuncTTriFoilDict();
extern void G__cpp_setup_funcTTriFoilDict();
extern void G__set_cpp_environmentTTriFoilDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/ryan/installdir/GRSISpoon/grsiGIT/GRSISort/include/TTriFoil.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTriFoilDictLN_TClass;
extern G__linked_taginfo G__TTriFoilDictLN_TBuffer;
extern G__linked_taginfo G__TTriFoilDictLN_TMemberInspector;
extern G__linked_taginfo G__TTriFoilDictLN_TObject;
extern G__linked_taginfo G__TTriFoilDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTriFoilDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTriFoilDictLN_MNEMONIC;
extern G__linked_taginfo G__TTriFoilDictLN_TGRSIDetectorData;
extern G__linked_taginfo G__TTriFoilDictLN_TFragment;
extern G__linked_taginfo G__TTriFoilDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTriFoilDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TTriFoilDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_TChannel;
extern G__linked_taginfo G__TTriFoilDictLN_maplEunsignedsPintcOTChannelmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__TTriFoilDictLN_TGRSIDetector;
extern G__linked_taginfo G__TTriFoilDictLN_TTriFoilData;
extern G__linked_taginfo G__TTriFoilDictLN_TTriFoil;

/* STUB derived class for protected member access */
