
OBJECTS = GROOTGuiFactory.o GRootCanvas.o GRootBrowser.o GCanvas.o GDirectory.o \
          GRootGlobals.o GRootObjectManager.o GH1D.o GROOTDict.o GTree.o GChain.o GFile.o
DICTOBJ =  $(INCDIR)/GROOTGuiFactory.h 
DICTOBJ += $(INCDIR)/GRootCanvas.h 
DICTOBJ += $(INCDIR)/GRootObjectManager.h 
DICTOBJ += $(INCDIR)/GRootGlobals.h 
DICTOBJ += $(INCDIR)/GRootBrowser.h 
DICTOBJ += $(INCDIR)/GCanvas.h 
DICTOBJ += $(INCDIR)/GDirectory.h 
DICTOBJ += $(INCDIR)/GH1D.h 
DICTOBJ += $(INCDIR)/GFile.h 
DICTOBJ += $(INCDIR)/GTree.h 
DICTOBJ += $(INCDIR)/GChain.h
DICTNAM = GROOT
NAME = GROOT

-include ../../make.rules

LFLAGS = `root-config --glibs`
